### ISSUE TITLE
tablet focus/visibility bug

### ISSUE THREAD

**Issue by tastydev** [mexyn/statev_v2_issues#10]
**Zeitpunkt**
19.08.2020 - Beta Phase1

**Beobachtetes Verhalten**
Wenn man im Tablet zuvor auf dem browser tab war und in diesem Zustand das Tablet ausblendet, bugt es mit einem betätigen der Tabulatortaste halb durchsichtig ins Bild.

**Erwartetes Verhalten**
Kein unerwartetes erscheinen des Tablets

**Schritte um den Fehler nachvollziehen zu können**
Siehe oben.

Bild: 
![image](https://user-images.githubusercontent.com/10810443/91063160-e6e67080-e62d-11ea-9c30-d5c727564193.png)

**Comment by r3sist3nt** [comment]
Fixed. Ich schließe das hier.
