### ISSUE TITLE
MRPD; Tür; Umkleide

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1009]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
oft, letzmalig 10.01 

**Beobachtetes Verhalten**
Die Tür zur MRPD Umkleide ist sehr oft offen, obwohl sie eigentlich geschlossen sein müsste.

**Erwartetes Verhalten**
Die Tür sollte nicht offen sein, obwohl sie eigentlich abgesperrt sein müsste. Das tritt bei der Tür häufig auf.

(Man könnte aber theoretisch vlt. auch die Absperrbarkeit der Umkleide Tür  komplett rausnehmen, da dahinter erstens eh direkt die andere Tür zur Lobby ist, und zum Treppenhaus eig auch eine absperrbare ist (glaub ich), und zweitens man auch öfter Probleme mit dem auf und absperren der Richtigen Tür hat, da dahinter ja eben direkt eine andere absperrbare Tür ist.) 

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/bTZRbGVsZIE

**Comment by DrGrizzlY17** [comment]
Das mit den Türen ist gefühlt nur im MRPD so. Meist behebt sich das mit einmaligen auf und abschließen. Ich denke mal darüber mach das wirklich dort rauszunehmen. Sobald mein PC wieder heile

**Comment by DonVitoDiangelo** [comment]
Aktuell keine Relevanz. Schaue ich mir später aber mal an.
