### ISSUE TITLE
Orangener Bauarbeiterhelm funktioniert nicht in den Minen

### ISSUE THREAD

**Issue by DerHessenTyp** [mexyn/statev_v2_issues#101]
Andreas Jung

**Zeitpunkt 27.08.2020 / 01:30 Uhr)**

**Beobachtetes Verhalten**
Bauarbeiterhelm orange (Einer der neuen Items) im 24/7 gekauft angezogen und versucht in der Schwefelmine aber auch in den normalen Mine zu arbeiten. Dort tritt dann der Fehler ,,Dir fehlen die benötigten Kleidungsstücke, um die Aktion auszuführen: [M] Schutzhelm, gelb" auf. Mit dem normalen Arbeiterhelm funktioniert es dann wieder.

**Erwartetes Verhalten**
Man sollte mit dem passenden Schutzhelm und der Spitzhacke ganz normal arbeiten können.

**Schritte um den Fehler nachvollziehen zu können**
Bauarbeiter helm angezogen, Spitzhacke im Inventar zum Abbaupunkt gegangen und die Fehlermeldung ist angezeigt worden

**Optional: Video / Bilder des Fehlers**
![orangener Bauhelm nicht möglich](https://user-images.githubusercontent.com/70151958/91367043-b822f280-e805-11ea-81d2-ddcf3d018dc0.jpg)

**Comment by DrGrizzlY17** [comment]
fixed next update
