### ISSUE TITLE
Doppelte Bezeichnung für 2 verschiedene Kleidungsstücke

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#1010]
**R&M Valdes**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

1 Bild erste Hellgraue Multifunktionsweste
2. Bild zweite Hellgraue Multifunktionsweste
**Erwartetes Verhalten**

Zusätzlich wäre es eine Idee die Multifuntionswesten umzubenennen damit die Leute wissen zu welcher Helixhose die Weste gehört zb: Pastellblaue Multifunktionsweste zu Hellblaue Helix Workweste

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![bug1](https://user-images.githubusercontent.com/70231715/104213234-5bcc1280-5436-11eb-8130-174e67691d76.png)
![bug2](https://user-images.githubusercontent.com/70231715/104213243-5d95d600-5436-11eb-9a3e-a8ac74aae23a.png)
![vorschlag](https://user-images.githubusercontent.com/70231715/104213261-5ff83000-5436-11eb-9ace-6086903fd96f.png)

**Comment by Enemyaa** [comment]
Hi @PlayInc89 

Könnte man mal machen ja, wobei die auch nicht alle 1zu1 zusammenpassen, aber ich habs mir mal notiert. Da gibts ja auch noch normale Jacken von. Vielleicht werd ich die in dem Zuge mit umbenennen. Mal schauen!

**Comment by PlayInc89** [comment]
Alles klar danke. Und der fehler mit der Doppelten Bezeichnung wird denke mal beim nächsten update behoben ?

**Comment by Enemyaa** [comment]
Ja, die unterste heißt jetzt vorläufig erstmal [F] Hellgraue Multifunktionsweste V2
