### ISSUE TITLE
Anzeigefehler bei den neuen Undershirts

### ISSUE THREAD

**Issue by Clawdie** [mexyn/statev_v2_issues#1011]
**Character Name**
Glinda Ehrmantraut

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11.01.2020

**Beobachtetes Verhalten**
In der Schneiderei bereits Anzeigefehler bei den neuen Undershirts.
Dennoch Genähtes ist teils korrekt im Verkauf, teils werden Artikel nicht gefunden, da sie falsch angezeigt werden (teils in der Übersicht, teils in der Theke).

Beispiele: Freedom-Undershirts Damen, Schwarze Space Ranger Logo-Undershirts Herren
Gesamtumfang Anzeigefehler unbekannt

**Erwartetes Verhalten**
Korrekte Darstellung überall da, wo die Kleidungsstück angezeigt werden sollen

**Schritte um den Fehler nachvollziehen zu können**
Durchsicht

**Comment by Enemyaa** [comment]
Hi @Clawdie 

ich weiß was du meinst. Die Id's dahinter sind um 2 versetzt. Danke für den Hinweis!
