### ISSUE TITLE
Fieldmaster Motorleistung

### ISSUE THREAD

**Issue by RomusLapisimus** [mexyn/statev_v2_issues#1012]
Character Name
Romus Lapisimus

Auftrittszeitpunkt (Datum / Uhrzeit)
12.01.2021 12:30 Uhr

Beobachtetes Verhalten:
Auf dem Baytree Canyon R. stadtauswärts Richtung Zentralmiene. 
Bergauf mit Fieldmaster und Graintrailer.
Leistung bricht ein! Fieldmaster kommt fast zum Stehen. Unter 10 KMH.
Die Automatik schaltet zu früh.

Erwartetes Verhalten:
Endgeschwindigkeit ist opitmal. 

Mehr Leistung beim Bergauffahren. 
Sollte nicht unter 30 KMH fallen.
Es ist ein Traktor. Richtig. 
Jedoch große Traktoren wie der Fieldmaster sollten mehr Leistung haben.

Monitorauflösung (nur wenn Falsche Darstellung in der UI)

Optional: Video / Bilder des Fehlers

**Comment by DonVitoDiangelo** [comment]
Wird so bleiben, sry.
