### ISSUE TITLE
Hotel Wohnungsübersicht "Letzte Miete" Fehlerhaft

### ISSUE THREAD

**Issue by Koree7** [mexyn/statev_v2_issues#1013]
**Charakter Name**
Brooks Miller

**Auftrittszeitpunkt (Datum / Uhrzeit)**
täglich

**Beobachtetes Verhalten**
Unter Immobilien > Hotel > Wohnungen; Dort wird die letzte Miete falsch angezeigt. Datum und Uhrzeit werden nicht aktualisiert.

**Erwartetes Verhalten**
Datum und Uhrzeit sollten mit Kontenabbuchung vom Mieter aktualisiert werden

**Schritte um den Fehler nachvollziehen zu können**
Immobilien > Hotel > Wohnungen > Letzte Miete anschauen

**Comment by DrGrizzlY17** [comment]
#942
