### ISSUE TITLE
Weiterhin Problem mit neuen Undershirts

### ISSUE THREAD

**Issue by Clawdie** [mexyn/statev_v2_issues#1014]
**Character Name**
Glinda Ehrmantraut, Kunden

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11.01.21 + aktuell

**Beobachtetes Verhalten**
Hatte bereits eine Bugmeldung verfasst: https://github.com/mexyn/statev_v2_issues/issues/1011

Da scheint es immer noch ein Problem zu geben. Kunden finden zumindest das schwarze Space Ranger Logo Shirt für drunter nicht in der Theke, bekommen es aber bei den Vorschauen im Laden korrekt angezeigt.
Probetragen nach persönlicher Übergabe des Shirts zeigt das gelbe Space Ranger (nicht Logo!)-Shirt.
Ein Kunde hat ein weißes Two Moon-Shirt für Drunter erworben, das wiederum aussieht wie das schwarze Space Ranger Logo-Shirt.
usw.

**Erwartetes Verhalten**
Shirts für Drunter zeigen, was sie zeigen sollten. ;-)

**Schritte um den Fehler nachvollziehen zu können**
Obige (oder auch andere?) Shirts für Drunter in einem Bekleidungsgeschäft auswählen und anprobieren.

**Comment by Enemyaa** [comment]
Nach dem nächsten Update sollte alles wieder passen!
