### ISSUE TITLE
Motorleistung TowTruck 

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1015]
Laut Changelog wurde das Drehmoment ja angepasst, ABER deutlich zu wenig...

![oil](https://user-images.githubusercontent.com/70241137/104333362-6eefe880-54f1-11eb-85ec-86bf6f1cd1ad.jpg)

Diese Steigung reicht schon aus um das gesamte Gespann lahmzulegen, nix geht mehr..
Man sieht ja am Drehzahlmesser das ich voll das Gas Durchdrücke...

**Comment by DonVitoDiangelo** [comment]
Verstehe ich, aber wir können dem TowTruck nicht 1000 PS geben, dann fährt der noch 250 am Ende, dass wollen wir auch nicht.
Da muss man dann Wege nehmen, die "gerade" sind und nicht diese steilen Pisten fahren. :)
