### ISSUE TITLE
Schaden bei Motorräder noch zu hoch 

### ISSUE THREAD

**Issue by masterppc** [mexyn/statev_v2_issues#1016]
**Character Name**
Hans Hentschel

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.01.2021 21:00 Uhr

**Beobachtetes Verhalten**
geparktes Motorrad kippt um nachdem einer vorbei läuft und der Motor geht sofort kaputt. 

**Erwartetes Verhalten**
Wenn das Motorrad aus dem Stand umkippt kein Total schaden.

**Schritte um den Fehler nachvollziehen zu können**
Motorrad abstellen leicht gegenlaufen > kippt um > fängt an zu qualmen Motorleuchte Gelb bis Rot

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
welches Motorrad genau?

**Comment by masterppc** [comment]
Sry total vergessen, es geht um die Carbon RS. Ich bin gerade sogar nur vorbei gelaufen und hab es leicht gestriffen und sie fing an zu dampfen

**Comment by DonVitoDiangelo** [comment]
fixed nextupdate
