### ISSUE TITLE
Probleme beim Hauskauf

### ISSUE THREAD

**Issue by ArnoZuDemB** [mexyn/statev_v2_issues#1017]
**Character Name**
Arno Bjerg

**Auftrittszeitpunkt (Datum / Uhrzeit)**
13.01.2020 00:10

**Beobachtetes Verhalten**
Das Haus mit dem Kürzel "SandyShores25" ist nicht erwerbbar, obwohl es zum Verkauf steht.
Die Fehlermeldung "Das Objekt kann nicht verkauft werden, wenn es bereits vermietet ist." erscheint, wenn man die herrenlose Wohnung kaufen möchte. 
Vermutung: möglicherweise Probleme durch Überschneidung vom Grundstück mit der Nachbarwohnung "SandyShores24" (bewohnt und NICHT zum Verkauf stehend)

**Erwartetes Verhalten**
Erfolgreicher Hauskauf

**Bilder:**
![Haus](https://user-images.githubusercontent.com/77365416/104388879-6ff93800-553a-11eb-9e8e-06464aa972c1.PNG)

![Haus2](https://user-images.githubusercontent.com/77365416/104388873-6a9bed80-553a-11eb-828a-04e69c5cd5f7.PNG)

**Comment by tastydev** [comment]
Sollte beim nächsten Update fixed sein
