### ISSUE TITLE
Paragon R Leistungsverlust?

### ISSUE THREAD

**Issue by Koree7** [mexyn/statev_v2_issues#1018]
**Character Name**
Brooks_Miller

**Beobachtetes Verhalten**
Der Paragon R hat mMn an Leistung verloren in V2. Bei 222KM/H schaltet er in den letzten Gang und fährt danach "nur" noch 215 KM/H. Für ein Sportwagen mit Allrad etwas mager bei einem Preis 200k+ im Vergleich zu einem Schafter V12 welcher 50k-60k kostet und 260 fährt. Der Preis richtet sich natürlich nicht nach der Geschwindigkeit, aber wohl ein großer Faktor auf dem Server.

**Erwartetes Verhalten**
Angepasste Leistung.

**Comment by DonVitoDiangelo** [comment]
Der gesamte Fahrzeugpool wurde zu v2 überarbeitet. Hierbei haben Fahrzeuge was gewonnen aber natürlich auch das ein oder andere etwas verloren.
