### ISSUE TITLE
Titanbarren

### ISSUE THREAD

**Issue by StateMellow** [mexyn/statev_v2_issues#1019]
Mellow_Esposito

Seit Start V2 keine Titanbarren mehr im Export und es gibt keinerlei andere Verwendung dafür momentan,
daher wäre es Sinnvoll die dort wieder einzufügen damit sie einen Nutzen haben

**Comment by DonVitoDiangelo** [comment]
werden bald anderweitigen Einsatz finden. Export only nach Möglichkeit nicht gewollt.
