### ISSUE TITLE
Munitions-Anzeige Bug

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#102]
**Character Name**

Jannik Datsch

**Zeitpunkt (Datum / Uhrzeit)**

27.08 06:10

**Beobachtetes Verhalten**

Falsche Anzeige der Munition. (zu viel)

**Erwartetes Verhalten**

korrekte Anzeige der Munition

**Schritte um den Fehler nachvollziehen zu können**

bisher einmaliger Bug

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=R2wSznwp6OQ&feature=youtu.be

**Comment by DrGrizzlY17** [comment]
konnte es bis jetzt nicht replizieren. maybe nen altV oder GTA Bug
