### ISSUE TITLE
Bug auf dem Ockerfeld

### ISSUE THREAD

**Issue by Stoffel123** [mexyn/statev_v2_issues#1020]
**Character Name**
Dean Foster

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Der Bug ist permanent

**Beobachtetes Verhalten**
Man kann auf dem Ockerfeld einfach kurz Funken oder über dsa X  Menü die Animation abbrechen, dadurch steht der Char vorher auf und kann dann sofort losrennen. Man verkürzt damit die Zeit einfach und ist schneller als jemand der ausgelernt ist. 

**Erwartetes Verhalten**
Warten bis der Balken bei 100% angekommen ist, der Chat aufsteht und dann nach kurzer Zeit weiter läuft

**Schritte um den Fehler nachvollziehen zu können**
Aufs Ockerfeld gehen, E drücken und dann entweder Funken oder mit dem X Menü Animation abbrechen.

**Comment by its4l3x** [comment]
Hi,

habe es gerade eben nochmal gegengetestet in deinen oben genannten Szenarien und konnte nicht feststellen, dass man früher losrennen kann als der andere.

Man kann aber wie du schon festgestellt hattest, über X Menu Abbrechen oder sonstiges. Trotzdem ist der Spieler weiterhin gefreezed und kann sich dadurch nur auf dem eigenen Fleck bewegen.

Wenn du dies aber feststellst das die abused wird, dann melde dich ggf. im Support dies bzgl.

**Comment by tastydev** [comment]
Reopened wird gefixt, wenn mehr zeit da ist. Jetzt gilt erstmal Meldung an den Support.

**Comment by its4l3x** [comment]
fixed next update
