### ISSUE TITLE
Kaputte Flaschengussform

### ISSUE THREAD

**Issue by Annabelle-Smith** [mexyn/statev_v2_issues#1021]
**Character Name**

Annabelle Smith

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Seit V2

**Beobachtetes Verhalten**

Die gekauften Flaschengussformen noch vor v2 sind defekt, ohne etwas gemacht zu haben.

**Erwartetes Verhalten**

das diese nutzbar sind

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Flaschengussform](https://user-images.githubusercontent.com/74880091/104557831-2d228780-5642-11eb-8048-efc6323667ef.png)

**Comment by DonVitoDiangelo** [comment]
Diese sind, wie der Name schon sagt defekt. Also ab in den Müll damit. :)
