### ISSUE TITLE
Animation Sitzen (Alkohol trinken)

### ISSUE THREAD

**Issue by Annabelle-Smith** [mexyn/statev_v2_issues#1022]
**Character Name**

Annabelle Smith

**Auftrittszeitpunkt (Datum / Uhrzeit)**

V2 weil (neu)

**Beobachtetes Verhalten**

ich wollte interagieren mit Y
Sitzen (Alkohol trinken)
kommt der Fehler:  dir fehlt z.B das Item Tasse Glühwein etc 
Obwohl ein glas Rotwein vorhanden ist im Inventar, habe es getestet ist egal was es geht nicht.
erst als ich den wein getrunken hatte konnte mein char sich mit dieser Animation hinsetzen hatte aber 
eine Flasche Bier in der Hand. Obwohl ein anderes alkoholisches Getränk vorgesehen war. 

**Erwartetes Verhalten**

Schön wäre es wen es bei der Animation der richtige Alkohol ist, also wen ne falsche Bier, dann diese aber wen ein glas wein im Inventar dann wäre ein glas wein in der Hand schöner. Aber maßstäblich wäre es wichtig das wen man den Alkohol im Inventar hat man sich auch hinsetzen kann mit dieser Animation und nicht zuerst trinken muss und 5 x testen 

**Schritte um den Fehler nachvollziehen zu können**

an einen stuhl gehen oder eine sitzgelegenheit
Y betätigen
Sitzen (Alkohol trinken)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

Animation auswählen

![animationen Stizen alkohol trinken](https://user-images.githubusercontent.com/74880091/104559261-6e1b9b80-5644-11eb-8a4e-2606c22a792a.png)

Fehlermeldung: 
![fehler hinsetzen](https://user-images.githubusercontent.com/74880091/104559625-f00bc480-5644-11eb-8a3b-1da8e8bc57c0.png)

Inventar: 
![getränk](https://user-images.githubusercontent.com/74880091/104559331-855a8900-5644-11eb-9080-2ac2f18b906a.png)

nach alkohol trinken und 5 mal versuch:
![feierabend](https://user-images.githubusercontent.com/74880091/104559399-a15e2a80-5644-11eb-8025-8b4ddb7344cc.png)

**Comment by DonVitoDiangelo** [comment]
Das item in der Hand (Flasche) ist in diesem Fall am Scenario gebunden. 

Mit dem hinsetzen, da hattest du das Glas Rotwein, in deinem Inventar und nicht  im Rucksack?
Ist das immer so oder war es jetzt nur ein mal so?

**Comment by Annabelle-Smith** [comment]
genau nicht im Rucksack sondern im Inventar.  Zeigte immer wieder was anderes was man z.b haben kann erst wen man den Alkohol getrunken hat hat man sich dann so hingesetzt.

**Comment by ShauniKT** [comment]
Der Fehler ist nicht nur beim Szenario Alkohol trinken, sondern des Öfteren bei allen Sitzszenarios, wo man Essen oder trinken benötigt, obwohl man das Inventar voller Essen/Trinken/Alkohol hat.

**Comment by its4l3x** [comment]
Hi,

leider hat Rockstar Games keine genauen Szenarien für bestimmte Items eingebaut (z.B. Weinfalschen Szenario, etc pp...)

Daher haben wir uns auf so eine Lösung geeinigt.

Die Sache bzgl. das der trotzdem noch einen Fehler wirft, schaue ich mir die Tage mal genauer an.

**Comment by DonVitoDiangelo** [comment]
@its4l3x  "Die Tage" sind vorbei :D   Closed?
