### ISSUE TITLE
Autohaus Autos

### ISSUE THREAD

**Issue by Annabelle-Smith** [mexyn/statev_v2_issues#1023]
**Character Name**

Annabelle Smith

**Auftrittszeitpunkt (Datum / Uhrzeit)**

V2

**Beobachtetes Verhalten**

Ihr lieben, wen ich ein frisch gebautes Auto ins Autohaus bringe dies entpacke und ins Autohaus stelle ob in den Raum oder in die Autohaus Garage ist nach dem nächsten Server neustart das auto in einer anderen Dimension und ich muss in den Support das Auto wieder in die richtige zeit zu holen. 
habe aber ausgetestet wen ich das auto auspacke und auf mich schreibe dann wieder aufs Autohaus und stehen lasse wie oben geschrieben im Autohaus oder in der Garage passiert dies nicht. 

**Erwartetes Verhalten**

wen ich das auto entpacke wäre es schön das nach dem neustart dies dann nicht in einer anderen Dimension ist sonder in der Autohausgarage. 

**Schritte um den Fehler nachvollziehen zu können**

Fehler: 
Auto bauen 
ins Autohaus bringen und entpacken
im autohaus stehen lasen 
auf den neustart warten
nach neustart in die autohaus garage schauen oder tablet
auto nicht da im tablet irgendwo am Flughafen unterirdisch

So könnte man es umgehen aber ist für meine ansicht so nicht gewollt: 
sonst auto entpacken 
einmal kaufen und dan wieder auf das Autohaus zurück
und das Problem ist nicht da. aber wird auf kurz oder lang ein Problem mit der hk geben.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Hi, 

Danke fürs Reporten. 

Habs gefixed und ist mit dem nächsten Update wieder dabei.
