### ISSUE TITLE
Spritverbrauch zu gering bei div. Fahrzeugen

### ISSUE THREAD

**Issue by Annabelle-Smith** [mexyn/statev_v2_issues#1024]
**Character Name**

Annabelle Smith

**Auftrittszeitpunkt (Datum / Uhrzeit)**

V2

**Beobachtetes Verhalten**

Ist das von euch so gewollt? 
Das div. Fahrzeuge nur noch obwohl man sie gleich nutzt wie früher nur noch jeden 2ten tag tanken muss? obwohl man die früher 2 mal tanken musste am tag, betroffen sind da Burrito, Hauler, Phantom noch weniger als vorher, Mixer, etc teils eher bei Arbeitsfahrzeugen beobachtet auch Pounder, bei supersportlern bin ich weniger informiert weil ich diese nicht unbedingt großartig fahre. 
gestern auch ein schönes Gespräch gehabt wie viele runden ein Müllwagen um die Insel fahren kann ohne zu tanken.
für mich ist es so, durch die Lehrgänge bekommt man supper öl , aber es wird kaum gebraucht weil die Autos viel viel weniger benötigen an Sprit, das heißt der Beruf ölfahrer werden fast ausgelöscht, und die Tankstellenbesitzer haben es noch schwieriger als früher , hat nichts mit den preisen zu tun. in der Stadt sind wir alle fast gleich + /-  0,5ct
z.b unsere Tanken müssen höchstens nur noch 2 mal in der Woche nachgefüllt werden und da sind sie nicht annähernd leer im Gegensatz zu vor v2 und neuem Spritverbrauch war es täglich oder ab und an auch zu schwierigen Zeiten alle 2 tage.

**Erwartetes Verhalten**

das der verbrauch von Fahrzeugen nochmals überprüft werden würde , wäre sehr schön. um die Arbeitsplätze für ölfahrer auch zu sichern. nicht das ein ganzer Berufszweig weggällt. Hier geht es mir erstens um den Arbeiter nicht um Besitzer von Tankstellen, aber klar hängt dies zusammen.

**Schritte um den Fehler nachvollziehen zu können**

nehmt euch Arbeitsautos ihr werdet schnell merken was ich meine. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Nein, hier gab es keine nennenswerte Änderung. Früher war es nur so, dass es schlagartig zu einem Spritverbrauch kam, der gar nicht hätte sein dürfen. Das war ein Bug, der natürlich nicht mehr existiert und daraus resultiert jetzt ein vermeintlich geringerer Verbrauch. Teils wurde der reguläre Verbrauch sogar erhöht.

**Comment by Annabelle-Smith** [comment]
okey, kann man da intern vielleicht nochmals darüber reden den hochzumachen den verbrauch? wie oben schon geschrieben mir geht es nicht um den besitzer sondern um den Berufszweig, damit wieder normal öl gefahren werden kann und man nicht den arbeitern sagen muss es gibt keine arbeit.  weil jetzt einfach schon viele Arbeiter den Job so verlieren und das ölfeld halt schon leer ist.  Ist für mich einfach nur ne frage und es wäre schön wen da was möglich wäre um den beruf zu schützen.

**Comment by DonVitoDiangelo** [comment]
Wir werden den Verbrauch nicht weiter erhöhen und der Markt reguliert sich hier von allein. Entweder über den Preis oder aber der ein oder andere Job fällt vllt. weg. Das ein Zweig bedroht sein, ist schlicht übertrieben.
