### ISSUE TITLE
Kamacho Schaden viel zu hoch

### ISSUE THREAD

**Issue by Chexxter** [mexyn/statev_v2_issues#1025]
**Character Name**
Herbert Pfefferkorn

**Auftrittszeitpunkt (Datum / Uhrzeit)**
öfters, zuletzt am 14.1.21 um ca. 12:00 Uhr

**Beobachtetes Verhalten**
Sobald man mit dem Kamacho gegen etwas fährt, wird die Kontrollleuchte gelb. Man sieht nicht mal einen Schaden am Fahrzeug.

**Erwartetes Verhalten**
Bei solch einem Fahrzeug sollte normalerweise nichts so schnell kaputt gehen. Vor einigen Wochen noch, konnte man mit dem Kamacho so ziemlich alles machen, ohne dass er Schaden genommen hat, was meiner Meinung nach auch realistisch ist. Es ist immerhin kein Supersportler.

**Schritte um den Fehler nachvollziehen zu können**
Eins zwei mal irgendwo hängenbleiben. Muss nicht unbedingt stark sein.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Das Damage System ist korrekt so wie es ist. Nur weil Sie gelb wird, heißt es ja nicht das der Wagen gleich stehen bleibt. Wenn du natürlich mehrere Objekte mitnimmst, bleibt er halt irgendwann stehen.
