### ISSUE TITLE
"[Bag] Graue Sand Castle Duffle Bag" hat kein Icon

### ISSUE THREAD

**Issue by h3adbang3r** [mexyn/statev_v2_issues#1026]
**Schritte um den Fehler nachvollziehen zu können**
"[Bag] Graue Sand Castle Duffle Bag" kaufen xD

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
![2021_0114-125550](https://user-images.githubusercontent.com/15799077/104588077-2c9ce780-5668-11eb-90a3-087e7fa75216.png)
![2021_0114-125612](https://user-images.githubusercontent.com/15799077/104588081-2e66ab00-5668-11eb-9c1d-8c42d56087f7.png)

**Comment by Statev-Bonsai** [comment]
Anmerkung: es haben viele der neuen Taschen kein Icon, wenn nicht sogar alle ;)
