### ISSUE TITLE
Dienstnummer LSPD Ausweis

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1027]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14.01.2021 14:05

**Beobachtetes Verhalten**
Die Nummer auf dem LSPD Dienstausweis hat keinen wirklichen Nutzen. Sie ändert sich bei jedem vorzeigen, und ist auch ansonsten nicht brauchbar und sorgt höchstens zu Verwirrung beim Vorzeigen des Ausweises.

**Erwartetes Verhalten**
Man könnte sie entweder ganz rausnehmen, oder aber durch die tatsächliche, individuelle Dienstnummer des entsprechenden Officers (bsp. bei mir 219) ersetzen.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/Mh3RTzVg3H4

**Comment by Chrinis007** [comment]
Das selbe beim LSMD

**Comment by CaleighRhodes** [comment]
Schön wäre ja auch, wenn auf meinem Ausweis nicht LSPD stehen würde, sondern tatsächlich BCSO... oder wenn man mit übergeordneter Behörde argumentiert, dann wenigstens SAPD :P Aber das ist wirklich nichts weltbewegend Wichtiges :)

**Comment by its4l3x** [comment]
Hi ihr beiden,

Tatsache ist das Random generiert. Du hast mich aber auf eine Idee gebracht, welche ich direkt umgesetzt habe. Deshalb:

Mit dem nächsten Update gibts dann eine Custom vergebbare DutyNumber (Dienstnummer) im STATENTE zu vergeben, welche auch auf dem Ausweis dann zu sehen ist. Standartmäßig haben alle 0

**Comment by Chrinis007** [comment]
Danke ❤️
