### ISSUE TITLE
T-Shirts buggen nach Produktion weg, im Kleiderladen sind die Items unsichtbar

### ISSUE THREAD

**Issue by tibbersyo** [mexyn/statev_v2_issues#1028]
**Character Name** Amy

**Auftrittszeitpunkt (Datum / Uhrzeit)** 14.01.2021 - 16:59 Uhr

**Beobachtetes Verhalten** Bubblegum T-Shirt Verpackt (für Frauen und Männer) nach Produktion nicht in der Maschine vorhanden obwohl Produktion erfolgreich. https://gyazo.com/04f9871b09730b88759abe3dea163c72 Scheint aber schonmal funktioniert zu haben. Außerdem werden diese Shirts und das Azurblaue T-Shirt beim Anprobieren im Kleiderladen nicht angezeigt, Kleidungsstück ist durchsichtig.

**Erwartetes Verhalten** Nach Produktion im Maschineninventar vorhanden

**Schritte um den Fehler nachvollziehen zu können** Produktion von Bubblegum T-Shirt Verpackt M/F

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Enemyaa** [comment]
[1014](https://github.com/mexyn/statev_v2_issues/issues/1014)
