### ISSUE TITLE
Telefon Bug bei bestimmter SIM Karte

### ISSUE THREAD

**Issue by DylanDuncan** [mexyn/statev_v2_issues#1029]
**Character Name**
Dylan Duncan und jeder andere der die SIM Karte benutzt hat

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Nach einem Anruf um ca. 23 Uhr

**Beobachtetes Verhalten**
Wenn wir auf der Firmen Nummer angerufen wurden, konnten wir den Anruf weder annehmen noch wegdrücken. Sobald das Telefon geklingelt hat, weil man diese SIM aktiv hatte musste man entweder jemand anderen anrufen oder das Spiel neustarten um das Telefon wieder funktionsfähig zu machen. (Siehe Video)
Auf allen anderen SIM Karten hat alles ohne Probleme funktioniert.

**Erwartetes Verhalten**
Den Anruf normal annehmen oder wegdrücken können.

**Schritte um den Fehler nachvollziehen zu können**
Mit dieser SIM Karte versuchen Anrufe entgegen zu nehmen, sollte der Fehler morgen früh nach dem Restart weiterhin auftreten.

**Optional: Video / Bilder des Fehlers**
https://streamable.com/mjc266

**Comment by its4l3x** [comment]
Hi,

ich habe eine Vermutung an was das liegen kann. Kannst du dich am Sonntag im laufe des Tages bei mir melden? Discord (Alex) oder im Termin Channel im TS. Wäre super!

Danke :D

**Comment by DylanDuncan** [comment]
alles klar, ich meld mich bei dir :)

**Comment by Dean-Gallagher** [comment]
Wir haben aktuell das gleiche Problem gehabt, haben wir regelmäßig mit der Werkstattsim.

**Comment by its4l3x** [comment]
Ich glaube du hast es wieder vergessen :P @DylanDuncan

**Comment by its4l3x** [comment]
fixed next update
