### ISSUE TITLE
X-Taste Interaktion Auto Bug

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#103]
**Character Name**

Jannik Datsch

**Zeitpunkt (Datum / Uhrzeit)**

27.08. 06:45

**Beobachtetes Verhalten**

Beim drücken der X-Taste im Fahrzeug, duckt sich der Char gleichzeitig

**Erwartetes Verhalten**

Das drücken der X Taste hat kein Ducken zur Folge

**Schritte um den Fehler nachvollziehen zu können**

Ins Auto steigen -> X drücken 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=mTlHOcqEBZI&feature=youtu.be

**Comment by tastydev** [comment]
Normales GTA-Verhalten, ist halt so.

**Comment by DonVitoDiangelo** [comment]
Tipp: Tastenbelegung ändern
