### ISSUE TITLE
Anzeigefehler Skill Wissenschaftler

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1030]
Normalerweise müsste da nun stehen: Produktionsbonus 5% und Reduzierung der Produktionsdauer um 70%...

Der Skill scheint nun ausgelernt zu sein, dann wäre es aber Klasse wenn dann trotzdem irgendwas angezeigt werden würde ;D

![Screenshot_9](https://user-images.githubusercontent.com/70241137/104686509-a59a4e80-56fd-11eb-99dc-7e33c3a928d6.jpg)

**Comment by Dean-Gallagher** [comment]
https://github.com/mexyn/statev_v2_issues/issues/987

**Comment by Statev-Bonsai** [comment]
Das ist ähnlich aber das hier ist im Produktions Bereich und das andere im Farming Bereich...

**Comment by KingMarcel** [comment]
Hey, ist das gleiche Problem und wird mit dem nächsten Update behoben sein
