### ISSUE TITLE
Löschen meiner aufgestellten Objekte

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1031]
**Character Name**
Max Broady

**Anliegen**
Ich finde leider mein 10. Objekt nicht mehr weswegen ich im aktuellen Zeitpunkt nur 9 Gegenstände aufstellen kann.
Ich habe nun alle Gegenstände abgebaut und dadruch festgestellt, dass ich irgendwo auf der Insel scheinbar noch was stehen habe. Ist es möglich, dass ein Dev meine aufgestellten Gegenstände löscht?
Sollte nun nur noch das verschollene Objekte sein sofern das Objektlimit bei 10 liegt.

Vielen Dank!

**Comment by DonVitoDiangelo** [comment]
Bitte über den Support klären
