### ISSUE TITLE
Schlüssel weg nach Tot

### ISSUE THREAD

**Issue by DrColgate** [mexyn/statev_v2_issues#1032]
**Character Name**
Anton Mueller

**Auftrittszeitpunkt (Datum / Uhrzeit)**

15.01.2021 gegen 11 Uhr morgens
**Beobachtetes Verhalten**

Bin heute morgen gestorben. Nachdem ich im Krankenhaus gespawnt bin war ein Schlüssel weg.
Der Schlüssel befand sich im normalen Inventar. Schlüssel war von einer Enduro.
Wollte das Fahrzeug nur kurz leihen, daher nicht am Schlüsselbund.
**Erwartetes Verhalten**

Schlüssel bleiben auch im normalen Inventar erhalten wenn man stirbt.
**Schritte um den Fehler nachvollziehen zu können**

Ein Schlüssel ins Inventar legen, sich das Leben nehmen und im MD spawnen.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Hi,

ist seit V2 so gewollt. Immer den Schlüssel sicherheitshalber ins Schlüsselinv. legen-

Daher invalid
