### ISSUE TITLE
Wasserfelder viel schneller Erschöpft [Team sagte macht Bugtracker]

### ISSUE THREAD

**Issue by LukiiTime** [mexyn/statev_v2_issues#1033]
Lukii Time

13.01.2020 zwischen 02:00 Uhr- 03:00 Uhr

**Beobachtetes Verhalten**
Wasserfeld ist nach 1 1/2 Tanker zu zweit Fahren (alleine auf dem Feld) erschöpft

Ich habe über das Forum einen Konversation gestartet und angefragt, worauf man mir sagte, dass ich eine Bugtracker schreiben solle das ihr da mal drüber schauen könnt.

**Comment by DonVitoDiangelo** [comment]
Nein, hier gab es keine Änderung. Generell gilt aber, auch wenn die Verfügbarkeit geringer wird, spielt das IC einfach aus.
Nichts ist unendlich verfügbar. Und wenn der Pool die Stunden oder Tage zuvor sehr belastet wurde, ist schlicht weniger verfügbar und die Ressource muss sich langsam generieren.

**Comment by LukiiTime** [comment]
Perfekt, danke für dein Feeback. mir wurde nur gesagt ich solle es melden. 
Aber dann weiß man ja nun bescheid.
