### ISSUE TITLE
Der Herr zum Ausparken ist manchmal unsichtbar

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1035]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
immer wieder, zuletzt 16.01 13:00

**Beobachtetes Verhalten**
Der Herr fürs Ausparken ist manchmal nicht sichtbar. Man kann dann zwar dort, wo er normal steht über "e" weiterhin ausparken, aber dazu muss man natürlich wissen, wo er normal steht an der entsprechenden Garage. 

Ich hatte das Gefühl, dass das vor allem dann Auftritt, wenn man im Spawnradius dieses Herren selbst spawnt, aber gerade bsp. sind wir von weit weg gekommen, sodass das diesmal sicher nicht das Problem war.

**Erwartetes Verhalten**
Der Herr sollte immer sichtbar sein

**Schritte um den Fehler nachvollziehen zu können**
siehe oben 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Stiefel911** [comment]
Selbige hatte ich gestern auch an öffentliche Garage Paleto Bay... Mein Char war nicht in Reichweite und ist von weitem gekommen!
Wenn ich es nicht gewußt hätte.... für mich dann ausparken unmöglich ;)

**Comment by DonVitoDiangelo** [comment]
Das Problem wurde im letzten Changelog näher beschrieben.
