### ISSUE TITLE
Werbetafel und Objektlimit

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#1036]
**Character Name**
Dean Gallagher

Heyo, ich will nicht um den Brei reden. 
Stellt man eine Werbetafel auf, so benötigt man einen Objektlimit Slot. Wäre es möglich dass man die Werbetafeln da raus nimmt? Sprich jeder hat 10 und zusätzlich die Werbetafel/n ? 

Wäre super. Danke

**Comment by DonVitoDiangelo** [comment]
Nein.
