### ISSUE TITLE
Überweisungsgebühren: eigenes Hotel auf Privatkonto 

### ISSUE THREAD

**Issue by SEUKings** [mexyn/statev_v2_issues#1038]
**Character Name**
Calvin Kings

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer bei Überweisungen wie unten beschrieben

**Beobachtetes Verhalten**
Bei einem Update wurden die Szenarien angepasst bei denen Gebühren wegfallen bei einer Überweisung, unter anderem, dass
"Zwischen Firmeninhaber und Privatkonto". 

![image](https://user-images.githubusercontent.com/74829891/104821365-86094000-583b-11eb-83be-dfe3bfa1aff8.png)

Jedoch musste ich leider feststellen, dass wenn ich von meinem EIGENEN Hotel eine Überweisung auf mein eigenes Privatkonto tätige, hier immer noch Gebühren anfallen....

![image](https://user-images.githubusercontent.com/74829891/104821375-a33e0e80-583b-11eb-90c5-7a7eb418b816.png)

**Erwartetes Verhalten**
Auch bei Überweisungen zwischen dem eigenen Hotel und dem Privatkonto, sollten keine Gebühren anfallen.

**Schritte um den Fehler nachvollziehen zu können**
Überweisungen tätigen vom Hotel auf das Privatkonto

**Comment by its4l3x** [comment]
Korrekt, derzeit zahlst du bei Überweisungen vom Gebäude steuern. Auf Wunsch haben wir dies bereits vor paar Tagen abgeändert und mit dem nächsten Update gibt es dann noch Szenarien wo die Überweisungssteuer auch bei Hotels/Building nicht mehr anfällt.

Daher einfach auf das Update warten.

**Comment by SEUKings** [comment]
Super danke für die schnelle Antwort!

**Comment by its4l3x** [comment]
Kein Problem
