### ISSUE TITLE
Aufnahme von Objekten während man im Auto sitzt.

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#104]
**Character Name**

Jannik Datsch

**Zeitpunkt (Datum / Uhrzeit)**

27.08 9:00

**Beobachtetes Verhalten**

Man kann während man im Auto sitzt, bzw. auch während der Fahrt, Objekte mit "." einsammeln.

**Erwartetes Verhalten**

Man sollte keine Objekte aufsammeln können, während man sich im Auto befindet / während man fährt.

**Schritte um den Fehler nachvollziehen zu können**

oben beschrieben.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by eiksch** [comment]
fixed im nächsten Update
