### ISSUE TITLE
Timed out

### ISSUE THREAD

**Issue by Stiefel911** [mexyn/statev_v2_issues#1040]
Yanalar Vemo

**Wann**
16.01.21 / 22:30

**passiert**
Timed out bekommen wärend man in einem Gespräch ist seid etwa 5-10 min. Mein Char hat sich selbst nicht bewegt und nur zwischen drin eine Mahlzeit zu sich genommen..

**Erwartet**
Man bleib connected

**Comment by DonVitoDiangelo** [comment]
Leider nichtssagend. Daher closed. Wenn so etwas passiert, einfach mal TS und GTA neu starten.
