### ISSUE TITLE
Antrag auf öffentliche Garagen

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#1041]
**Character Name**
Dean Gallagher

Huhu, ich mal wieder. 
Unzwar geht es diesmal um Öffentliche Garagen. In den Bildern 1 und 2 sieht man die Wohnkreisel im Country und die Fehlenden öffentlichen Garagen dort. In Bild 1 war früher ja das Festgelände bzw die Garage am Kraftwerk in der nähe. Diese ist ja weg gekommen nun fehlt dort eine. Im Bild 2 würden die Officer die dort wohnen es bestimmt sehr begrüßen. 

Dies würde auch vll etwas mehr fördern das die Betroffenen mehr nach hause fahren und nicht Random irgendwo ausloggen. 

Bild 1
https://pic.statev.de/i/pxNeS.jpg

Bild 2
https://pic.statev.de/i/px21g.jpg

lg

**Comment by DonVitoDiangelo** [comment]
@DrGrizzlY17  Kannst ja eine so dazwischen packen, wenn es sich ergibt

**Comment by DrGrizzlY17** [comment]
Für den Cop Kreisel in SS ist eine Garage in der nähe. Für den anderen Park kommt etwas altbewehrtes zurück
