### ISSUE TITLE
Hotring (Racing) 10 Diamanten

### ISSUE THREAD

**Issue by Michi993** [mexyn/statev_v2_issues#1042]
**Luke_Hammer**

**immer**

**Ist es richtig, dass der Hotring (Racing) inzwischen 10 Diamanten braucht, da es im Handbuch nicht eingetragen ist**

**Fahrzeug enthält keine Diamanten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Jap, 10 Dias sind korrekt
