### ISSUE TITLE
Ratbike schieben bricht ab

### ISSUE THREAD

**Issue by MrMutantus** [mexyn/statev_v2_issues#1043]
**Character Name**
Felix Sommer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.01.21 ca 16:35

**Beobachtetes Verhalten**
Es wurde versucht ein Ratbike von der Straße zu schieben, wo die animation gestartet hat und das Ratbike auch ein kleines stück geschoben wurde aber dann direkt wieder abgerbrochen wurde.
Am Ende hat es noch geklappt bei Freya Michaels, nachdem sie direkt nach auswählen mit a/d gelenkt hat.

**Erwartetes Verhalten**
Normales schieben möglich

**Schritte um den Fehler nachvollziehen zu können**
offenes Ratbike, xmenü schieben auswählen, schieben startet.

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=kZxL-MRmk4I

**Comment by its4l3x** [comment]
Hallo Felix,

Dadurch das dein Spieler die ganze Zeit mit dem Ratbike kollidiert, bricht es ab.

Dafür müsste die Position vom Ratbike nach hinten verlegt werden, daher ist das ein GD Issue.

Alex

**Comment by DrGrizzlY17** [comment]
Das Ratbike hat wohl ein Problem. Mit dem nächsten Update ist es nicht mehr schiebbar
