### ISSUE TITLE
Man kann nicht mit Messern, die schon benutzt sind, Fesseln durchschneiden

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#1044]
**Character Name**
Paul Humpert

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.01.2021 / 19:00 Uhr

**Beobachtetes Verhalten**
Man kann mit einem Messer, bei welchem bereits der "Benutztbalken" hat, keine Fesseln bei Spielern durchschneiden

**Erwartetes Verhalten**
Mit allen Messern sollte man fesseln durchschneiden können

**Schritte um den Fehler nachvollziehen zu können**
- Mit einem Messer, das mal benutzt wurde, einen gefesselten Spieler versuchen zu entfesseln.

**Comment by its4l3x** [comment]
Fixed, next update
