### ISSUE TITLE
Aufenthalt im oberen Bereich des Gerichtsgebäudes (Büro)

### ISSUE THREAD

**Issue by motioncsgo** [mexyn/statev_v2_issues#1045]
**Name**
Marc Randall

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Ca. 06.01.21 - heute

**Beobachtetes Verhalten**
Wenn ein Spieler (Spieler A) oben im Gerichtsgebäude steht und ein weiterer Spieler (Spieler B) unten das Gericht betritt, steht für diesen das Playermodel mitsamt der F10-Nummer über dem Kopf bei ihm sichtbar unten in der Lobby, obwohl dieser sich real oben im Gebäude aufhält. Dies führt dazu, dass Personen die Anliegen oftmals denken, die Justiz wäre ignorant, außerdem könnte dies bei potentiellen versuchten Geiselnahmen ein großer Problem darstellen.

Wenn man auf Stühlen sitzt, tritt das Problem nicht auf, am meisten tritt das Problem auf, wenn man bestimmte Animationen (z.b. Arme verschränken (Boss) ) macht. 

**Erwartetes Verhalten**
Die Person sollte unten nicht sichtbar sein, wenn sie in Wirklichkeit oben steht. 

**Schritte um den Fehler nachvollziehen zu können**
Person A) stellt sich oben ins Gericht und macht eine Animation
Person B) fährt von weit außerhalb das Gericht an und schaut ob die Person unten im Gericht steht

Nicht jedes mal reproduzierbar - bisher auch kein Video dazu vorhanden - 

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/970
