### ISSUE TITLE
Trinken bei übervollen Taschen nicht möglich

### ISSUE THREAD

**Issue by CaleighRhodes** [mexyn/statev_v2_issues#1046]
**Character Name**
Caleigh_Rhodes

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.01.2021, ca. 20:30 Uhr

**Beobachtetes Verhalten**
Nach einem Abbauauftrag und einer Überladung der Hosentaschen ist es nicht möglich, etwas zu trinken -> Das Trinken (Flasche Wasser) wurde verbraucht, aber am Durst-Zustand hat sich nichts geändert. Vermutlich deshalb nicht, weil kein Platz für eine weitere leere Plastikflasche war, es wurde jedoch weder eine weitere Plastikflasche generiert, noch wurde der Durst gestillt, jedoch verringerte sich die Zahl der Flaschen Wasser in meinem Inventar

**Erwartetes Verhalten**
Verbrauchtes Getränk verändert den Durstzustand oder Info, dass Tasche zu voll und daher kein Trinken möglich

**Schritte um den Fehler nachvollziehen zu können**
Hosentasche überladen (kam dadurch, dass ich als Cop etwas abgebaut habe, das meine Tasche zu voll gemacht hat), Flasche Wasser oder anderes Getränk trinken

**Comment by JannikDatsch** [comment]
#736

**Comment by JannikDatsch** [comment]
#736

**Comment by CaleighRhodes** [comment]
@JannikDatsch

Essen konnte ich und der Effekt war da, bei mir bezog sich das nur aufs Trinken.

**Comment by its4l3x** [comment]
Hi,

Abgeändert, dass bei einem Rückgabe Item (Leere Wasserflasche etc...) nun nicht mehr auf das Gewicht im jeweiligen Inventar geschaut wird.

Somit wie immer: Fixed, next Update :P

Alex
