### ISSUE TITLE
Sandking (5 Türer) seit V2 Benziner kein Diesel mehr

### ISSUE THREAD

**Issue by Maximilian63** [mexyn/statev_v2_issues#1047]
**Character Name**
Max Clinton

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.11.2020/19:00 Uhr

**Beobachtetes Verhalten**
Sandkin 5 Türer mit größten Motor (mein eigenens Fahrzeug) tankt Benzin statt Diesel. Auf der Tür steht Turbo Diesel u. der Sandkin SWB mit dem 2 größten Motor ist nach wie vor ein Diesel (wurde mir gesagt IC). Ob die anderen Motoron auch betroffen sind konnte ich leider nicht raus finden.
Denke nicht, dass das beabsichtigt ist.

**Erwartetes Verhalten**
Das der Sandking wieder ein Diesel wird

**Schritte um den Fehler nachvollziehen zu können**
Sandking an die Tanke fahren

**Comment by DonVitoDiangelo** [comment]
Das wurde bereits vor einem Monat gefixt. Bitte prüfe das noch einmal genau. Der 2 und 4 Motor, waren Benziner, sind aber wieder Diesel.
