### ISSUE TITLE
Magazine sind verbuggt nach vollständiger Leerschießung

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#1048]
**Character Name**
Paul Humpert

**Auftrittszeitpunkt (Datum / Uhrzeit)**
18.01.2021 / 7:50

**Beobachtetes Verhalten**
Wenn man ein angebrochenes Magazin der MPX leerschießt und dann die Waffe entrüstet, hat man immer wieder ein Magazin mit 1/2 Kugeln, obwohl das Magazin leer sein müsste. Ob das mit anderen Waffen auch so ist ist noch nicht geprüft.

**Erwartetes Verhalten**
Man sollte kein Magazin mehr rausbekommen.

**Schritte um den Fehler nachvollziehen zu können**
Ein angebrochenes Magazin der SIG MPX verschießen und danach die Waffe entrüsten.

Video: https://youtu.be/Ak5QDlO-KwM

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/715
