### ISSUE TITLE
Skilltree falsche lvl Anzeige?

### ISSUE THREAD

**Issue by DrColgate** [mexyn/statev_v2_issues#1049]
**Character Name**

Anton Mueller
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Seit dem Update heute nacht.
**Beobachtetes Verhalten**

Naturausbeuter ist das maximun 63% und 8%
**Erwartetes Verhalten**

Müsste es nicht 60% und 10% sein? So wie beim Minenarbeiter? Denn die 63%/8% Stufe habe ich ja geskillt.
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Unbenannt](https://user-images.githubusercontent.com/74769835/104888938-bd780980-596d-11eb-9a2e-0e471c01061e.PNG)

**Comment by tastydev** [comment]
fixed next update
