### ISSUE TITLE
WUNSCH: Sortierfunktion Hauslager / Kleidung und speichern von Outfits

### ISSUE THREAD

**Issue by zarazandra** [mexyn/statev_v2_issues#105]
**Character Name**
Jeder

**Zeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Beim Suchen im Schrank muss immer die Suchleiste genutzt werden, was voraussetzt, dass man genau weiß, was man sucht oder man scrollt sich zu Tode, wenn man entsprechend viel Zeug besitzt.

**Erwartetes Verhalten**
Kategorien z.B. als Reiter für Kleidung, Schuhe, Nahrungsmittel, Waffen [...], um gesuchte Gegenstände übersichtlich und schnell finden zu können und eventuell auch beim Aussuchen des Outfits einfacher und schneller fündig zu werden. 
Eventuell auch speichern von zusammengestellten Outfits möglich? 

**Schritte um den Fehler nachvollziehen zu können**
(Kein Fehler, nur unübersichtlich)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by r3sist3nt** [comment]
Ich bin mit der aktuellen Umsetzung auch nicht zufrieden. Da gibt es noch einiges an Verbesserungspotential. 
Wenn ich Zeit dazu habe, wollte ich am Inventar sowieso noch quality of Life machen

**Comment by its4l3x** [comment]
In Punkto Hauslager Kleidung, wird es nach V2 so oder so ein paar Änderungen geben.

Werde daher das Ticket closen, da das schon auf der Liste "Nach V2" draufsteht.
