### ISSUE TITLE
Durch die Wand im neuen PD

### ISSUE THREAD

**Issue by Afrostatev** [mexyn/statev_v2_issues#1050]
**Character Name**
 Felix_Bang

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 18.01.2021 10:30 

**Beobachtetes Verhalten**
 Mit y auf einen Stuhl durch die Wand

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**
 Vor die Wand stellen y drücken und auf sitzen klicken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
 https://www.youtube.com/watch?v=NM-cOzOhLuo&feature=youtu.be

**Comment by DrGrizzlY17** [comment]
Lässt sich nicht beheben. Wer das halt nutzt, ist halt Bugusing
