### ISSUE TITLE
Hotel mit Tür in den freien Fall

### ISSUE THREAD

**Issue by Afrostatev** [mexyn/statev_v2_issues#1052]
**Character Name**
Felix_Bang

**Auftrittszeitpunkt (Datum / Uhrzeit)**
18.01.2021 10:55Uhr

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=F7G_69_tRjo&feature=youtu.be

**Comment by DonVitoDiangelo** [comment]
gta related, werden wir nicht fixen
