### ISSUE TITLE
Funk wird durch "#" deaktiviert und muss danach neu aktiviert werden

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1053]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
18.01 14:00

**Beobachtetes Verhalten**
siehe Video

**Erwartetes Verhalten**
Funk bleibt drin

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/nHX3tzBIw2c

**Comment by TheOutburst** [comment]
#1054

**Comment by its4l3x** [comment]
Hi, korrekt, das ist derzeit mit Absicht, ist aber auch Intern schon bei uns diskutiert worden.

Ich setze mich mal an eine Lösung gebe feedback

**Comment by JannikDatsch** [comment]
@its4l3x Also dass das mit Absicht ist, wundert mich doch sehr.  Ich, aber auch andere schalten bes. abends an frequentierten das HUD über "#" aus, weil es beim Fahren einiges an FPS zieht, wenn man das jetzt nicht mehr kann wäre sehr schlecht.

**Comment by its4l3x** [comment]
Liegt an einem Technischen Problem, weshalb das mit Absicht war. Habe das jetzt aber grundauf nochmal abgeändert und die funk freq. bleiben nun bestehen.

**Comment by JannikDatsch** [comment]
Aso, ich dachte das wäre aus iwelchen anderen Gründen tatsächlich gewollt, hab ich zumindest so verstanden

Thx für den schnellen fix.
