### ISSUE TITLE
Schmuck

### ISSUE THREAD

**Issue by Sirena88** [mexyn/statev_v2_issues#1055]
Peggy Black

18.01.2021 ca 9uhr

Beim anlegen von [F][Ears] Silber Creolen und [F][Neck] Silberne Herz-Layering Halsketten zusammen wird das zuerst angelegte (Reihenfolge egal) Schmuckstück nicht am Charakter angezeit aber unter ',' ist alles angezogen.

Beide Schmuckstücke sollten zeitgleich am Charakter zu sehen sein.

**Comment by CaleighRhodes** [comment]
Geht nicht anders, hab ich auch schon gemeldet -> #687

**Comment by DrGrizzlY17** [comment]
Jap wie Caleigh schon schrieb. Leider nicht anderst möglich

**Comment by CaleighRhodes** [comment]
Geht aber bspw. mit Diamantsteckern oder so. Was nicht geht sind die Creolen und die Muschelohrringe :)
