### ISSUE TITLE
#LSMD Problem beim Einladen der Trage

### ISSUE THREAD

**Issue by Walker-Mo** [mexyn/statev_v2_issues#1057]
Beim Einladen der Trage (mit Patient) wird der eigene Char in den RTW geladen, jedoch nicht der Patient auf der Trage (drop am Heck des RTW auf den Boden).

**Comment by Chrinis007** [comment]
Seit dem gestrigen Bzw heute Nacht diesem Update

**Comment by its4l3x** [comment]
fixed next update
