### ISSUE TITLE
Mehrere Gamecrashes + starke FPS drops am/um den Würfelpark

### ISSUE THREAD

**Issue by Jaz1441** [mexyn/statev_v2_issues#1058]
**Jazlyn Brooks**

Jazlyn Brooks
**Auftrittszeitpunkt (Datum / Uhrzeit)**

18. Januar, gegen 20:45 Uhr
**Beobachtetes Verhalten**

Mehrere Gamecrashes + massive FPS drops (Von 110 auf 20-30) am und um den Würfelpark herum. Würde sagen im Bereich der Streaming Range vom neuen PD MLO. 
Glaube der Server kommt mit dem Laden von den Objekten nicht schnell genug hinterher, ich kenn das PD MLO. Hat viele kleine Objekte und Details welche die Performance extrem fressen. Und ich würde behaupten das ich mit meiner RTX 2060 und meinem Ryzen 5 ne ziemlich gute Hardware hab weshalb es nicht an meinem PC liegen kann haha :D 
Dazu kommen noch alle kleinen Objekte die jeder Spieler platzieren kann. Die fressen auch ordentlich Perfomance. 
Wo alle Spieler gestern ihre Objekte entfernt hatten aufgrund des Updates, lief es um tausendmal besser. Wenige bis gar keine FPS drops oder Gamecrashes. Sind einfach zu viele Objekte in den Streaming Ranges die geladen werden müssen.

**Comment by DonVitoDiangelo** [comment]
Bitte deine Einstellungen prüfen und ggf. einmal Treiber neu installieren.
Kann nicht bestätigt werden, dass das neue PD negativen Einfluss hat. Meist sind es schlicht die Settings der Spieler oder die Belastung des Rechners im gesamten.

Und technisch ist es auch nicht so relevant, da die meisten Objekte unloaded sind, wenn du nicht im PD bist.
Da kannst du dich dann mit der MLO und LOD Mechanik mal im Detail auseinander setzen, wenn dich das Thema interessiert. ;)

**Comment by Dean-Gallagher** [comment]
Die Objekte die Spieler hinstellen können haben viel weniger einfluss auf die Leistung als du denkst. Fahrzeuge sind das Problem. Im Vergleich zu Rage haben sie nun einen 3-5x so großen Einfluss. Darum haben wir auch die harten Regelungen bezüglich Fahrzeuge. Objekte wurden Limitiert damit nicht alles so überfüllt wird und damit die Last vom Server genommen wird, denn das ist der einzige einfluss wo Objekte hinfallen. Bezüglich all der Details ect und spieler Objekte, spiel mal GTA Online, da hast du 1000x mehr objekte als wir auf den Server haben aber viel weniger Fahrzeuge/Spieler. 

Ich gebe dir aber einen Settingstipp mit, die "Erweiterte Darstellungsdistanz" ist etwas bugged unter Alt. Stell sie komplett aus und es kann dir unter umständen 20-30 FPS mehr bringen.

**Comment by JannikDatsch** [comment]
Dazu kommt auch, dass das Tacho HUD einiges an FPS zieht.
