### ISSUE TITLE
Drückt man # beim fahren um das Interface auszublenden, verlässt man alle funkkanäle, statt nur das Funkgerät auszublenden

### ISSUE THREAD

**Issue by 3xcu** [mexyn/statev_v2_issues#1059]
Müsste einmal bitte gefixt werden dass man nur das Gerät ausblendet und nicht alle Kanäle verlässt, sodass man auch beim fahren noch # drücken kann um das Interface auszublenden und nicht das Funkgerät nicht mehr nutzen kann.

**Comment by DonVitoDiangelo** [comment]
Paar Einträge unter deinem. Bitte nächste mal checken: https://github.com/mexyn/statev_v2_issues/issues/1053
