### ISSUE TITLE
Fahrzeuge nicht voll betankbar

### ISSUE THREAD

**Issue by EaselWeasel** [mexyn/statev_v2_issues#106]
Name:
William Easel

Datum/Uhrzeit:
15:25 27.08

Problem:
Wenn man ein Fahrzeug tankt kann man nur ganze Liter tanken wodurch man häufig nicht ganz voll tanken kann.

Erwartetes Verhalten:
Liter auch Anteilig tankbar.  68,5 -> 70/70

Erzeugung:
Fahrzeug fahren bis es einen Tankstand hat welcher nicht ganzzahlig ist und dann tanken.

**Comment by DrGrizzlY17** [comment]
Die Tank UI zeigt an das man z.B 8.82L getankt hat, die ThefeedPost Message sagt wiederum 8L was auch der tatsächlichen Menge entspricht

**Comment by r3sist3nt** [comment]
Das wird so bleiben.
Man wird nur ganze Liter tanken können. Alles andere hätte zur Folge, das wir die Anzahl an Items mit Dezimalstellen definieren müssen. Die UI wird hierfür noch angepasst werden, sodass nur bei geraden Litern gestoppt werden kann.

**Comment by r3sist3nt** [comment]
UI Fehler wurde behoben. Anteiliges Tanken wird nicht umgesetzt.
