### ISSUE TITLE
SIM Karte Bug von 911

### ISSUE THREAD

**Issue by SamortonstateV** [mexyn/statev_v2_issues#1060]
Sam Orton

**Auftrittszeitpunkt (Datum / Uhrzeit)**
18.01.2020 22:10 Uhr

**Beobachtetes Verhalten**

Fraktionsim buggt sobald jemand anruft, ist für andere belegt, sobald man SIM wechselt ist aber diese Leitung für die Normale Nummer frei, aber 911 ist noch belegt
**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**
Simkarte eingelegt, 1. Anruf kam rein, SIM verbuggt, 

**Optional: Video / Bilder des Fehlers**
https://youtu.be/PHSngcZGRXQ

**Comment by its4l3x** [comment]
Sitze bereits dran. Dauert noch

**Comment by its4l3x** [comment]
Problem dieser seits sollte mit dem nächsten Update gefixed sein!
