### ISSUE TITLE
Bootsanker wird nicht gespeichert - Boot treibt weg

### ISSUE THREAD

**Issue by TemaropManato** [mexyn/statev_v2_issues#1062]
**Character Name**
Temarop_Manato

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Die Anker eines Bootes lösen sich von alleine

**Erwartetes Verhalten**
Das Boot bleibt an Ort und Stelle, auch wenn man sich aus Sichtweite des Bootes entfernt

**Schritte um den Fehler nachvollziehen zu können**
1 Boot ankern und sich dann aus Sichtweite begeben und wieder zurückkehren. Das Boot treibt weg und man muss es "einfangen" und wieder den Anker setzen

**Comment by its4l3x** [comment]
Leider nicht realisierbar, wenn du alleine bist, da wir das nur über den Client syncen lassen und sobald du weg bist und kein andere Owner das Fahrzeug weitersyncen kann, derzeit unmöglich.
