### ISSUE TITLE
Schwebende Parkplatz Markierung

### ISSUE THREAD

**Issue by Kaycee91** [mexyn/statev_v2_issues#1064]
**Nick Adam**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

18.01.21 gegen 20 Uhr
**Beobachtetes Verhalten**

Auf dem Parkplatz nähe dem Redwood 24/7 schwebt eine Markierung ca 30 cm über dem Boden
**Erwartetes Verhalten**

Markierung sollte auf dem Boden sein und nicht schweben 

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Grand Theft Auto V Screenshot 2021 01 18 - 21 18 17 47](https://user-images.githubusercontent.com/38119374/105033451-7286f080-5a58-11eb-9963-04e6f1850eb9.png)
![Grand Theft Auto V Screenshot 2021 01 18 - 21 18 30 41](https://user-images.githubusercontent.com/38119374/105033462-77e43b00-5a58-11eb-93d3-b4ab82164630.png)

**Comment by DonVitoDiangelo** [comment]
gta related, werden wir nicht fixen
