### ISSUE TITLE
Unter der Map nach Login wen Spielabbruch ist beim Verlassen des Autohauses

### ISSUE THREAD

**Issue by Annabelle-Smith** [mexyn/statev_v2_issues#1065]
**Character Name**

Annabelle Smith

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Heut sowie gestern mehrmals seit dem fix für autohaus Autos

**Beobachtetes Verhalten**

wen mein spiel crasht wen ich aus der Tür des Autohauses gehe lande ich laut aussage der gm´s unter der Karte. 
das verlassen des Autohauses bringt viele spiele Abbrüche für mich. 
natürlich etwas doof weil das mein Beruf ist und ich da rein und raus muss 

**Erwartetes Verhalten**

wen ich einen Spielabbruch habe mich neu einlogge nicht unter der Map lande sondern im Autohaus oder draußen vor der Türe

**Schritte um den Fehler nachvollziehen zu können**

hoffen das beim verlassen vom Autohaus ein crash passiert beim spiel und man sich dan nach dem einlogen unter der map findet.. weiss nicht wie man das nachstellen kann. sorry 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Hi,

welches Autohaus besitzt du? Kannst du mir mal ein Bild von der Karte schicken, wo dein Autohaus zu sehen ist?

Alex

**Comment by Annabelle-Smith** [comment]
![Autohaus Karte](https://user-images.githubusercontent.com/74880091/105089760-d41d7e00-5a9d-11eb-8f47-7cf8c275600e.png)

Ist Luxury Cars zwischen liveinvader und dem Gericht unterhalb des Friseurs. 
dan sorry es sollte doch gefixt geworden sein das frisch ausgepackte autos die hergestellt wurden nicht nach server neustart unterirdisch geparkt werden. war heut aber wieder so. rs7 neu ausgepackt um ca 15,45 uhr und nach neustart war er wieder am flughafen und nicht in der autohaus garage. :-) nur infohalber

**Comment by its4l3x** [comment]
Korrekto, bitte noch weiterhin beobachten. Habe mit dem heutigen Update dort nochmal Änderungen aufgespielt.

**Comment by Annabelle-Smith** [comment]
So heut Abend hat es mich jetzt schon das 2te mal unter die Karte gehauen. Aktuell Sitz ich jetzt da noch. Asmir hat mich das erste mal befreit.  Beobachte ich gerne weiter. Seit heut passiert es wieder öfters die letzten Tage ging es etwas besser und musste kaum deshalb in den Support. Danke für eure mühe ich hoffe wir finden bald eine Lösung, für mich einfacher und für euch auch. Ihr macht gute arbeit das wollt ich einfach auch mal gesagt haben.

**Comment by its4l3x** [comment]
Sollte jetzt nicht mehr auftreten. ^^
