### ISSUE TITLE
Abschlepper spielen Sirenen-Sound ab auf Distanz

### ISSUE THREAD

**Issue by AngelMaravilla** [mexyn/statev_v2_issues#1066]
Angel Maravilla

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.01.2021 14:00 Uhr, ist mir vor ein paar Tagen schon mal aufgefallen

**Beobachtetes Verhalten**
Abschlepper mit eingeschalteten Rundumleuchten spielen auf Distanz den Sirenen-Sound ab. Sobald man sich ihnen nähert, verschwindet der Sound, bis man wieder genügend Abstand zum Fahrzeug hat.

**Erwartetes Verhalten**
Ein Abschlepper spielt zu keinem Zeitpunkt einen Sirenen-Sounds ab.

**Schritte um den Fehler nachvollziehen zu können**
Bei einem Abschleppfahrzeug die Rundumleuchte einschalten und dann Abstand von dem Fahrzeug nehmen. Ab einer bestimmten Distanz startet der "Weiter entfernte Sirene"-Sound. (Siehe Video)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/HwW6Soa2D_Y

**Comment by its4l3x** [comment]
Meine Vermutung: Ambient Sounds auf Entfernung. Würde der Abschlepper Tatsache Sirenen haben, würdet ihr die auch von der nähe hören.

**Comment by TheBroady** [comment]
Kann ich auch so bestätigen. Auf entfernung höre ich immer ein Einsatzfahrzeug. War die letzte Zeit deutlich verwirrt 😆

**Comment by DrGrizzlY17** [comment]
> Meine Vermutung: Ambient Sounds auf Entfernung. Würde der Abschlepper Tatsache Sirenen haben, würdet ihr die auch von der nähe hören.

Ja sind Ambient Sounds, war bei v1 auch schon so

**Comment by AngelMaravilla** [comment]
> Ja sind Ambient Sounds, war bei v1 auch schon so

Das kann ich nicht bestätigen. Mir ist das auf v1 nie aufgefallen.

**Comment by TheBroady** [comment]
> 
> 
> > Meine Vermutung: Ambient Sounds auf Entfernung. Würde der Abschlepper Tatsache Sirenen haben, würdet ihr die auch von der nähe hören.
> 
> Ja sind Ambient Sounds, war bei v1 auch schon so

Bei Abschleppern war bei v1 das einzige was man gehört hat der Haken. Dadurch hat sich ein Schlepper immer verraten wennn er in die nähe gekommen ist. Aber Polizei Sirenen sind neu

**Comment by Statev-Bonsai** [comment]
Doch gabs ne Zeitlang bei V1, das kann ich bestätigen ;p

**Comment by AngelMaravilla** [comment]
Wie dem auch sei, die Frage ist und bleibt: Kann man die Sirenen-Ambient-Sounds beim Abschlepper deaktivieren?

**Comment by its4l3x** [comment]
Kann ich nicht beantworten - @DonVitoDiangelo @DrGrizzlY17 Können das aber 👍

**Comment by DonVitoDiangelo** [comment]
gta related, werden wir nicht fixen sry.

**Comment by JannikDatsch** [comment]
@DonVitoDiangelo @its4l3x Könnte man dann nicht die Rundum Leuchten deaktivieren, bzw das so kommunizieren, dass man die nicht einschaltet?
