### ISSUE TITLE
MRPD Garage aus dem EG interagierbar

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1067]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.01 23:05

**Beobachtetes Verhalten**
Das Garagen Tor ist aus dem EG interagierbar. 

**Erwartetes Verhalten**
Sollte nicht so sein.

**Schritte um den Fehler nachvollziehen zu können**
siehe Video

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/kROPOmfDsGk

**Comment by DrGrizzlY17** [comment]
Radius war fürs interagieren war hoch, damit ihr auch mit großen Fahrzeugen raus kommt. Hab es mal etwas runter gesetzt
