### ISSUE TITLE
Rucksack wird nicht angezeigt

### ISSUE THREAD

**Issue by Stoffel123** [mexyn/statev_v2_issues#1068]
**Character Name**
Dean_Foster

**Auftrittszeitpunkt (Datum / Uhrzeit)**
20.01.2020 00:35 

**Beobachtetes Verhalten**
Ich habe eine Duffle Bag auf dem Rücken, ziehe ich aber den schwarzen V2 Pulli an, sieht man die DUffle Bag nicht mehr. Zieht man dann den Pulli wieder aus, erscheint sie instant.

**Erwartetes Verhalten**
Man sollte die Duffle Bag sehen

**Schritte um den Fehler nachvollziehen zu können**
Duffle Bag anlegen, dann schwarzen V2 Pulli anziehen und wieder ausziehen

**Comment by Statev-Bonsai** [comment]
https://github.com/mexyn/statev_v2_issues/issues/903
