### ISSUE TITLE
Türen MRPD nach Restart offen

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1069]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
20.01 09:30

**Beobachtetes Verhalten**
Am Morgen um 09:30 standen (wohl nach dem Restart um 8:00) alle Türen des MRPD offen

**Erwartetes Verhalten**
Die Türen sollten, wie bei allen anderen Gebäuden (Gericht, LSMD, andere PDs) geschlossen sein.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Es gibt leider ein Problem mit den Türen, deswegen ist das so gewollt

**Comment by JannikDatsch** [comment]
@DrGrizzlY17 Wäre es möglich, zumindest die Außentüren zu schließen?

Bei den Zellen ist das ja, wenn ich mich nicht irre, zur Zeit auch so.
