### ISSUE TITLE
Vunk kein Komma setzbar

### ISSUE THREAD

**Issue by MarkHarland** [mexyn/statev_v2_issues#107]
**Mark_Harland**

**27.08.2020  15:30**

**Vunk keine Kommasetzung möglich**
<!Es lässt sich beim Vunkgerät kein Komma/Punkt setzen sowie die erste Zahl lässt sich nachdem setzen nicht mehr löschen

**Erwartetes Verhalten**
Das man den Punkt/Komma setzen kann und die erste Zahl löschen kann

**Schritte um den Fehler nachvollziehen zu können**
VunkGerät öffnen>Plus drücken für neue Frequenz>Gewünschte Frequenz mit Punkt eingeben was nicht funktioniert>Versuchen die Komplette Nummer zu löschen was auch nicht geht

>**Optional: Video / Bilder des Fehlers**
https://youtu.be/Uz6L3wl6pVk

**Comment by tastydev** [comment]
Gewollt wir akzeptieren keien Gleitkommazahlen mehr.

**Comment by MarkHarland** [comment]
Auch das sich die erste Zahl sich nicht mehr löschen lässt?

**Comment by Kalumel** [comment]
Kannst STRG + A machen dann einfach was neues eingeben und damit ist auch die erste Zahl weg aber ja, wenn man mit backspace versucht alle zu löschen geht das nicht.
