### ISSUE TITLE
Ein bisschen Liebe für die Hauler

### ISSUE THREAD

**Issue by powerswissi** [mexyn/statev_v2_issues#1070]
**Character Name**

Roger Thickle 

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Seit V2 .. mal mehr mal weniger gut

**Beobachtetes Verhalten**

Dem Hauler wurde die Kraft genommen. Ca im 3 Gang hat der Hauler keine Kraft mehr und man muss manuell runterschalten. Fühlt sich so an als wäre beim Öl Auflieger die Bremsen angezogen. Das kleine Öl Feld kann man mit dem Hauler nicht befahren.
Ob Grösster Motor oder kleinster Motor ist egal.
Phantoms haben hingegen keine Probleme.

Mit den normalen Auflieger sowie Tieflader bestehen keine Probleme.
Hingegen mit dem Öl Auflieger, sowie Holzauflieger sind die Probleme vorhanden 

**Erwartetes Verhalten**

Mehr Power für den Hauler.
Oder einen Zwischengang einbauen
oder den Öl auflieger leichter machen..
Oder den Hauler höher machen 
oder die Physik vom normalen Auflieger auf den Öl auflieger übertragen

**Schritte um den Fehler nachvollziehen zu können**

Hauler reinsetzen. Aufs kleine Ölfeld fahren.. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by SwissJokerTV** [comment]
Ich kann das Problem mit dem Hauler & Öl-Achse bestätigen, wäre mir auch ein anliegen, wenn das Problem angeschaut und korrigiert wird. Die Phantom und Phantom Custom fahren uns richtig um die Ohren. Vergleich wie du mit einem Fahrrad unterwegs bisst und die Phantom Fahrer mit einem Supersportler.

**Comment by DonVitoDiangelo** [comment]
next update changed
