### ISSUE TITLE
vermehrte Spielabbrüche im Bereich / z.B. Pier 

### ISSUE THREAD

**Issue by LelaBelar** [mexyn/statev_v2_issues#1071]
**Character Name**

Lela Belar

**Auftrittszeitpunkt (Datum / Uhrzeit)**

seit wenigen Tagen, vorrangig abends/nachts, vereinzelt auch tagsüber

**Beobachtetes Verhalten**

Sobald der Bereich des Piers betreten wird (schon auf der Zufahrtsstraße) oder direkt auf dem Pier kommt es zu 
Spielabbrüchen. Der Client schließt sich dann ohne Fehlermeldung einfach komplett. 

**Schritte um den Fehler nachvollziehen zu können**

Es ist schwer nachzuvollziehen oder nachzustellen,wann diese Abbrüche erfolgen, da sie teilweise direkt am Pier, aber auch auf dem Pier passieren. Ebenso ist es bei Gruppen möglich, dass nur eine Person und das immer wieder betroffen ist. Auffällig hierbei ist es, dass die anderen scheinbar die Problematiken dann nicht haben.

**Comment by JannikDatsch** [comment]
Joa, die Ecke auch grad bei GioV ist schwierig was Game Crashes angeht.

**Comment by DonVitoDiangelo** [comment]
Danke, das ist uns bekannt.
Wir versuchen das Problem mit einigen Änderungen und Tests mit dem nächsten Update zu beheben.

**Comment by JannikDatsch** [comment]
bei North Werkstatt in der Ecke ist auch ganz schlimm

**Comment by DonVitoDiangelo** [comment]
bitte gebt uns mal direkte Koordinaten oder eine Karte, wenn es sehr oft spezifisch Orte betrifft.

**Comment by Chrinis007** [comment]
Wie kommt man an die Koordinaten ran?

**Comment by dastiii** [comment]
Ohne Koordinaten zu haben, aber aus GioV-Sicht sind die roten Punkte echte Hotspots, jedenfalls nach eigener Erfahrung und 
der Anzahl der Fahrzeuge, die dort ständig auf der Straße stehen. Orange sehe ich eher seltener, auch auch regelmäßig. Gerade die Position der roten Marker ist fast zu 99% immer identisch.

![Screenshot 2021-01-22 at 22 46 14](https://user-images.githubusercontent.com/1284232/105552334-0defbe00-5d04-11eb-9fff-d4dc8971cbfe.png)

**Comment by DonVitoDiangelo** [comment]
Danke, bitte mal ab sofort beobachten ob sich eine Besserung einstellt und hier auch mitteilen, dass wir mal ein Feedback haben nach den letzten Änderungen.

**Comment by MisterCopeland** [comment]
Howdy, habe die letzten Stunden an den roten Spots selbst keine Probleme gehabt, aber andere Personen bei denen ich im Fahrzeug saß.
Ich habe festgestellt, wenn man "langsam" also nicht schneller als 120 km/h an die Spots fährt, nichts passiert.

**Comment by JannikDatsch** [comment]
Grade bei Gio einige Disconnects, ich war bsp. nicht schnell unterwegs und hab auch gehabt, aber grad ist eh viel mit Gamecrashes

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1100

**Comment by dastiii** [comment]
![Screenshot 2021-01-30 at 18 05 30](https://user-images.githubusercontent.com/1284232/106362959-f6c55780-6325-11eb-928d-ce006f0749cb.png)


[client.log](https://github.com/mexyn/statev_v2_issues/files/5898344/client.log)

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1116

**Comment by DonVitoDiangelo** [comment]
Wie im obigen Post zu sehen https://github.com/mexyn/statev_v2_issues/issues/1116 , prüft bitte auch eure Settings und das diese zu eurem System passen. Wer dazu fragen hat, kann dies gerne fragen. (Specs + Settings)

**Comment by powerswissi** [comment]
![Screenshot_815](https://user-images.githubusercontent.com/70152806/106938092-d3801b00-671e-11eb-8a5d-026aa348c58f.png)

tritt immer am abends auf.. zwischen 18 und 20 Uhr...

**Comment by Hutstaender** [comment]
@powerswissi bitte fahr bei dem nächsten crash dort mal den Parkplatz vom Hotel 3217 ab und schau ob da bestimmte modded Fahrzeuge z.B. Öltanker stehen.

**Comment by powerswissi** [comment]
@Hutstaender ja es standen Ölauflieger rum. Aber nicht nur am Parkplatz sondern auch an diversen Gebäuden in der Umgebung. Bei 2 Ölaufliegern stand jeweils ein Phantom davor..

**Comment by Ladyblanche85** [comment]
Hi.
Die letzte Zeit war es relativ ruhig, aber gestern Abend hatte ich gleich drei Crashes hinter GioV um die Ecke in der San Andreas Avenue.
Der erste (siehe Bild) war um 22:22 Uhr. Da kam ich aus Richtung GioV, hatte ich auf dem Bordstein beim 24/7 dort geparkt, war im 24/7, und als ich wieder einsteigen wollte, schloss sich das Spiel.
Der zweite passierte um kurz nach Mitternacht, als ich mit einem Beifahrer im Wagen dort um die Ecke fuhr, um Richtung Innenstadt weiterzufahren. Mein Beifahrer hatte keinen Crash und fuhr den Wagen an den Straßenrand. Als ich dann wieder einloggte, zum Auto ging und gerade den Motor eingeschaltet hatte, flog ich erneut raus. Mein Beifahrer hat den Wagen dann über die nächste Kreuzung gefahren. Nachdem ich dort dann hingelaufen war, konnte ich die Fahrt ganz normal fortsetzen.
Alle drei Crashes waren etwa auf Höhe des 24/7, vielleicht ganz wenige Meter dahinter.
![Crash GioV 2021_02_04](https://user-images.githubusercontent.com/78599177/107034184-a7b07400-67b6-11eb-9d31-04d1fdc5327e.jpg)

**Comment by Hutstaender** [comment]
> @Hutstaender ja es standen Ölauflieger rum. Aber nicht nur am Parkplatz sondern auch an diversen Gebäuden in der Umgebung. Bei 2 Ölaufliegern stand jeweils ein Phantom davor..

Ok, auch Modded Fahrzeuge in der nähe?

**Comment by powerswissi** [comment]
@Hutstaender ja es standen 2-3 Modded Fahrzeuge rum.. Welche genau kann ich dir nicht sagen.. sahen wie die mercedes AMG aus..

**Comment by Auralein** [comment]
![grafik](https://user-images.githubusercontent.com/76708950/107847415-9fc28680-6deb-11eb-8b6e-ab6177dc0c14.png)

2 Disconnects in 10 min. Fahrzeuge: Phantom + Trailer von mir. Bei GioV übliche Fahrzeuge wie Burrito und Youga.
Zeitpunkt ca. 11 Uhr
