### ISSUE TITLE
Duping - Inventar war voll

### ISSUE THREAD

**Issue by RomusLapisimus** [mexyn/statev_v2_issues#1073]
Romus Lapisimus

Auftrittszeitpunkt (Datum / Uhrzeit)

21.01.2021 15:00 Uhr

Beobachtetes Verhalten:

Duping

Erwartetes Verhalten:

Kein Duping. Objekte verdoppeln sich nicht.

Schritte um den Fehler nachvollziehen zu können:

Ich habe Objekte plaziert. 
Auf einen Tisch habe ich einen Laptop gestellt.
Beim Einsammeln der Ojekte hatte ich keinen Platz mehr im Inventar.
Der Laptop blieb auf dem Tisch stehen, aber im Inventar erschien ein neuer Laptop.
Nachdem ich mein Inventar wieder frei hatte, konnte ich das Laptop auf dem Tisch aufnehmen.
Nun habe ich 2 Laptops.

(Siehe oben) - Nicht nachstellbar
Optional: Video / Bilder des Fehlers

**Comment by TheBroady** [comment]
Soweit mir bekannt, kann man sich beim einsammeln von Gegenständen überladen.
Dort ist es egal ob du "voll" bist oder nicht.
Korrigiert mich wenn ich falsch liege.

**Comment by Hutstaender** [comment]
ist so korrekt.
