### ISSUE TITLE
Fahrzeuge nehmen beim spawnen schaden

### ISSUE THREAD

**Issue by MisterCopeland** [mexyn/statev_v2_issues#1074]
Seit einiger Zeit nehmen die Fraktionsfahrzeuge schaden, wenn die aus Garagen gespawned werden. Liegt wohl daran das die Spawnpoints in der "Luft" hängen und das Fahrzeug dadurch "fällt". 

Erwartetes Verhalten: Fahrzeuge spawnen richtig und nehmen durch den spawn keinen schaden.

**Comment by DonVitoDiangelo** [comment]
Welche Fraktion? Welcher Ort? Was bedeutet seit einiger Zeit? Gibt es hier nähere Angaben (Tage/Wochen/Update X)?

**Comment by MisterCopeland** [comment]
Fraktion SAPD
Alle PD Garagen
Seit ca 2-3 Wochen (Seitdem fällt es auf)

Vielleicht einfach mal den Prozentualen Schaden an Fahrzeugen beobachten und das Auto immer wieder ein und ausparken.

**Comment by DonVitoDiangelo** [comment]
Werden zum nächsten Update teils etwas nach unten versetzt

**Comment by MisterCopeland** [comment]
@DonVitoDiangelo Problem besteht immer noch, ist immer noch zu Hoch.
