### ISSUE TITLE
Waffenkaufregistrierungen im StateCom

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1075]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit V2

**Beobachtetes Verhalten**
Es werden seit V2 die gekauften Waffen nicht mehr dem entsprechenden Käufer, sondern dem Verkäufer als Waffe in die Akte geschreiben. So kommt es, dass bsp. auf Bonsai als Besitzer eines Waffenladens mehrere Waffen am Tag gelistet werden, die eigentlich beim entsprechenden Käufer gelistet werden sollten. Somit lassen sich auch im Prinzip keine Waffen mehr als gestohlen melden, außer man hat zufälligerweise die Reg.Nummer usw. 

**Erwartetes Verhalten**
Sollte wieder so sein wie zu V1, dass dem Käufer auch die Waffe in seine StateCom Akte eingetragen wird.

**Schritte um den Fehler nachvollziehen zu können**
X kauft beim Waffenladen von Y eine Waffe. Dann erscheint die Waffe in der Akte von Y und nicht in der von X.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Statev-Bonsai** [comment]
o.0 ernsthaft? Und Bonsai wird dann des Waffenhandels etc. angeklagt, weil die Waffen der Käufer ALLE auf ihn laufen.lol

**Comment by DonVitoDiangelo** [comment]
Bonsai ist halt nen Verbrecher! RP-Opener :D    Wird geprüft...

**Comment by masterppc** [comment]
Ich hatte das beim Start von V2 auch schon mal gemeldet da hieß es das ist so gewollt. (An sich ja nicht schlimm das man in der Akte ALLES sieht aber das gestohlen melden ist halt leider so gut wie unmöglich weil keiner schreibt sich die nummern auf)

https://www.youtube.com/watch?v=z7VE8zw9Kd0

**Comment by TheBroady** [comment]
Gibt's hier einen neuen Stand?

**Comment by eiksch** [comment]
@TheBroady @masterppc @JannikDatsch 

Hallo,
wir haben bei v2 einige Korrekturen in den Waffenlogiken vorgenommen. Es sollten bisher immer der Käufer, der Besitzer des Ladens und der Laden selber gespeichert werden. Damals wurden diese Werte leider falsch (oder falsch herum) gespeichert, weshalb das StateCOM dann noch auf den falschen Wert zugegriffen hat. Wir ändern es, sodass ihr wieder die richtigen Käufer der Waffen abfragen könnt, aber das führt (glaube ich) dazu, dass ihr alle alten Waffen dann für einen Spieler nicht mehr sehen könnt. Wir überlegen uns noch was dazu und sprechen dann noch mit ein paar Leitungspersonen im TS darüber.

Gruß,
Tito

**Comment by JannikDatsch** [comment]
@eiksch Müsste soweit schon seit längerem wieder behoben sein, oder?

**Comment by DonVitoDiangelo** [comment]
Jupp, sollte definitiv behoben sein. Fall was in der Richtung wiederkommt, reopen
