### ISSUE TITLE
Import: Fahrzeug wird abgeschlossen

### ISSUE THREAD

**Issue by ProgrammingFox** [mexyn/statev_v2_issues#1076]
**Character Name**
Daniel Fox

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.01.2021 - ~12:35 Uhr

**Beobachtetes Verhalten**
Der Import schließt automatisch das Fahrzeug ab, nachdem ein Gegenstand beladen wurde.

**Erwartetes Verhalten**
Der Import schließt nicht das Auto ab, sondern lässt es weiterhin offen bzw. in dem Zustand wie es vor dem Beladen war.

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug aufschließen, Kofferraum öffnen, Gegenstand vom Import beladen lassen, ans Auto gehen und versuchen Kofferraum zu schließen. "Fahrzeug abgeschlossen"

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/AK0JhAd4uGQ

**Comment by DonVitoDiangelo** [comment]
Ein Stück weit protection, wird daher nicht geändert.

**Comment by ProgrammingFox** [comment]
@DonVitoDiangelo Und was genau wird da geschützt? Der Kofferraum steht immer noch offen. Ergo kann man einfach leichte Importgüter klauen oder einfach den ganzen Wagen mit nem Abschlepper klauen und entladen.
