### ISSUE TITLE
Doppelter Eintrag Konto beim Kauf von Uhr

### ISSUE THREAD

**Issue by miischaa** [mexyn/statev_v2_issues#1077]
**Character Name**
 Heinrich Iwanow, Simon Pfeiffer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 23.01.2021 15:37Uhr

**Beobachtetes Verhalten**
 Bei ihm, als auch auf dem Konto vom Juwelier wurde die Buchung beim Kauf einer Silbernen Timeline Business Uhr doppelt angezeigt aber nur ein Mal abgebucht und nur ein Mal auf dem Juwelier Konto eingegangen.

**Erwartetes Verhalten**
 Nur ein Mal die Buchung auf den Konten anzeigen, da es zur Verwirrung für.

**Schritte um den Fehler nachvollziehen zu können**
 Silberne Timeline Business Uhr im Juwelier kaufen und per Karte zahlen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

![](https://i.gyazo.com/e6a73f650df587b1760a34ee13a3d801.png)
![Bild_2021-01-23_170444](https://user-images.githubusercontent.com/76888365/105607071-17793480-5d9d-11eb-80de-bec29f39bd80.png)

**Optional: Video / Bilder des Fehlers**

![Bild_2021-01-23_170524](https://user-images.githubusercontent.com/76888365/105607092-2f50b880-5d9d-11eb-949a-876271145e10.png)

**Comment by MarcelMuerto** [comment]
@miischaa 
Ist dieses Verhalten aktuell immer noch vorhanden?

**Comment by miischaa** [comment]
Bisher nicht wieder vorgekommen
