### ISSUE TITLE
Fest stecken in Cafeanhänger

### ISSUE THREAD

**Issue by wichtTSV** [mexyn/statev_v2_issues#1078]
Bei Imperial Cars gibt es im Gebäude drinne einen kleinen Kaffee verkauf anhänger wo man rein gehen kann, man kommt allerdings nicht mehr ohne Hilfe, von nem Stuhl oder ähnlichem raus. Anscheind sind dort schon einige stecken geblieben und mussten deswegen in den Support.

![Screenshot_32](https://user-images.githubusercontent.com/74994115/105611419-882c4b00-5db5-11eb-8540-1507576826ff.png)

**Comment by Statev-Bonsai** [comment]
Die Spielfigur ist ja auch größer als der Eingang ;) 
Einfach mit Ö zusammenfallen lassen dann kommst du meistens nach dem ersten Versuch wieder raus...

**Comment by DonVitoDiangelo** [comment]
Das was Bonsai sagt. Da werden wir nichts machen können.

**Comment by wichtTSV** [comment]
Aber wieso kommt man dann da rein? :D
