### ISSUE TITLE
Funk bleibt nicht gespeichert.

### ISSUE THREAD

**Issue by OloFFink** [mexyn/statev_v2_issues#108]
Olof_Fink

**Beobachtetes Verhalten**
Wenn man einen Funk einspeichert und reloggt ist der Funk nicht mehr eingespeichert.

**Erwartetes Verhalten**
Das der Funk immer gespeichert bleibt.

**Schritte um den Fehler nachvollziehen zu können**
Funk einspeicher und GTAV Neustarten.

**Comment by tastydev** [comment]
Bei mir geht alles. Hast du spezifisch etwas gemacht?

**Comment by OloFFink** [comment]
Hab gestern mit einem Kollegen den Funk getestet und war dann ne Stunde off glaube auch da war ein Server Restart dazwischen und als ich mich wieder eingeloggt habe war mein Funk nicht mehr eingespeichert.

**Comment by r3sist3nt** [comment]
@OloFFink Bitte Fülle die Vorlage komplett aus. Das Datum hätte hier schon gezeigt, dass der Fehler bereits gestern Abend aufgetreten ist, aber inzwischen behoben worden ist:
![image](https://user-images.githubusercontent.com/10810443/91452816-52734c80-e87f-11ea-9048-b4a08a3b5eca.png)

**Comment by Kalumel** [comment]
Man kann aber keinen Punkt mehr machen.

**Comment by tastydev** [comment]
Das Feature gab es gestern noch nicht und wurde erst in der Nacht hunzugefügt bitte schaut auch mal in die geschlossenen issues um Duplikate zu vermeiden. daher mahc ich heir zu.
