### ISSUE TITLE
Lohnklassen im Team sehen

### ISSUE THREAD

**Issue by PrimroseBloom** [mexyn/statev_v2_issues#1081]
**Character Name**
Primrose Bloom

**Auftrittszeitpunkt (Datum / Uhrzeit)**
November

**Beobachtetes Verhalten**
Angestellte Ohne "Edit Teammanagement" können ihre und die Lohnklasse von den anderen Mitarbeitern nicht sehen.

**Erwartetes Verhalten**
Lohnklassen sind von allen zusehen oder es gibt Häkchen wo man die Lohnklassen sehen kann aber nicht bearbeiten

**Schritte um den Fehler nachvollziehen zu können**
Ohne Rechte in einer Staatsfraktion angestellt sein

**Comment by DonVitoDiangelo** [comment]
Lohnklassen können nur von entsprechenden Leuten mit entsprechenden Rechten eingesehen werden, nicht von allen. Das ist so korrekt.
