### ISSUE TITLE
[SAPD Waffenlager Maschinenproblem] Waffen vermehren sich

### ISSUE THREAD

**Issue by DerHessenTyp** [mexyn/statev_v2_issues#1082]
**Andreas Jung**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
Die Maschine war am Anfang leer, da wir dort nur immer die Waffenkisten Oder Verpackten Magazine reinlegen wenn wir Sie entpacken. 
- 10x Colt M1991A1 Waffenkisten reingelegt 
- An die Maschine gegangen dort wurden mir dann schon 10 entpackte Colt angezeigt + 10 Waffenkisten (Nachgefragt im PD es hat niemand die Maschine dort betätigt bzw. entpacke nur Ich als Person die Waffen)
- Als ich an die Maschine rangetreten bin waren dort auch dann 10 entpackte Colt Waffen + die 10 Waffenkisten
- Zurück an die Maschine gegangen waren dann 20x Colt entpackt + 10 Waffenkisten.
- Habe dann die Maschine mit den 10x Colt angeschmissen und heute Mittag am 24.01.2021 habe ich dann wieder erst die Maschine ausgestellt an die Maschine rangetreten und dort waren dann 30 entpackte Colt. (Eindeutig 20x zuviele Colt)

**Erwartetes Verhalten**
Beim Gang an die Maschine sollten nur die 10 Waffenkisten angezeigt werden und dass man Sie entpacken kann.
Nach Ende des Entpackungsvorganges sollten dann 10 Colt entpackt sein

**Schritte um den Fehler nachvollziehen zu können**
- 10x Colt M1991A1 Waffenkisten reingelegt 
- An die Maschine gegangen dort wurden mir dann schon 10 entpackte Colt angezeigt + 10 Waffenkisten (Nachgefragt im PD es hat niemand die Maschine dort betätigt bzw. entpacke nur Ich als Person die Waffen)
- Als ich an die Maschine rangetreten bin waren dort auch dann 10 entpackte Colt Waffen + die 10 Waffenkisten
- Zurück an die Maschine gegangen waren dann 20x Colt entpackt + 10 Waffenkisten.
- Habe dann die Maschine mit den 10x Colt angeschmissen und heute Mittag am 24.01.2021 habe ich dann wieder erst die Maschine ausgestellt an die Maschine rangetreten und dort waren dann 30 entpackte Colt. (Eindeutig 20x zuviele Colt)

------------------------------------------------------------------------------------------------------------------------------

Ich war im Support dort wurde mir von Louie Lagarde gesagt ich solle die 20 Colt Waffen die entpackt sind erstmal zur Seite legen, da Sie wahrscheinlich dann gelöscht werden, und einen Bug Report schreiben. Sie liegen jetzt bei uns im SAPD - Equipmentlager.

**Comment by DerHessenTyp** [comment]
Wollte das gleiche jetzt nochmal mit einem Taser versuchen.
- Waffenkiste ins Maschinenlager gelegt.
- An die Maschine rangetreten und jetzt haben wir 10x weitere Colt Waffen in der Maschine liegen

Danach habe ich versucht den Taser im Equipmentlager zu entpacken da funktioniert alles einwandfrei. Wir werden somit erstmal das Auspacken im Waffenlager unterlassen bis das geklärt ist.


Ein Bild zu der Situation mit dem Waffenlager und dem Taser und der 10 Colt Waffen seht ihr hier

![1x Taser entpacken und 10 neue Colt](https://user-images.githubusercontent.com/70151958/105631778-764bb600-5e50-11eb-926d-2bc999a9c8c5.jpg)

**Comment by DerHessenTyp** [comment]
Mittlerweile haben wir den Fehler auch im Equipmentlager. Jedes Mal wenn ich an die Maschine gehe, entpackt er genau das letzte ausgepackte nochmal. (Hab euch mal hier einen Screenshot vom ,,Produktionen" gemacht.
Entpackt wurden am 27.01.2021 aber nur 11x Taser rausgekommen sind am Ende 24x Taser


![Equipmentlager Waffen auspacken Fehler](https://user-images.githubusercontent.com/70151958/106043059-297d0f00-60de-11eb-92d5-891139547a47.jpg)

**Comment by TheOutburst** [comment]
Video dazu: https://www.youtube.com/watch?v=RGAGWEWH3YQ
