### ISSUE TITLE
Unsichtbarer Boden in einem Store

### ISSUE THREAD

**Issue by TheMoonicorn** [mexyn/statev_v2_issues#1083]
**Charakter Name**

Freya Michaels

**Auftrittszeitpunkt (Datum / Uhrzeit)24.01.21**

24.01.21 13:27 Uhr

**Beobachtetes Verhalten**

Man geht zum Store und blickt auf die Straße hinunter, die sich dahinter befindet.

**Erwartetes Verhalten**

Nicht durch den Boden durch gucken zu können

**Schritte um den Fehler nachvollziehen zu können**

Zum Postal 7069 fahren, zum "Nelsons General Store" gehen und zum Laden gehen und auf den nicht vorhandenen Boden achten.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/oZLIaiehFto

**Comment by DonVitoDiangelo** [comment]
Wird nicht gefixt werden. Hängt mit dem Interior PD zusammen, welches wir aber nicht editieren werden.
