### ISSUE TITLE
Creolen und Ketten zusammen tragen macht die Kette unsichtbar

### ISSUE THREAD

**Issue by TheMoonicorn** [mexyn/statev_v2_issues#1085]
**Character Name**

Freya Michaels

**Auftrittszeitpunkt (Datum / Uhrzeit)**

24.01.21 13:28 Uhr

**Beobachtetes Verhalten**

Man zieht eine Kette und Creolen an und die getragene Kette wird unsichtbar

**Erwartetes Verhalten**

Man kann eine Kette und auch Creolen gleichzeitig tragen und es ist beides sichtbar.

**Schritte um den Fehler nachvollziehen zu können**

einen weiblichen Character erstellen, eine beliebige Kette anziehen und danach beliebige Creolen (Bei anderen Modellen der Ohrringe funktioniert es)

**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=9uXWDbSL2OU

**Comment by DrGrizzlY17** [comment]
#687
