### ISSUE TITLE
Be/Entladen Lifeinvader Lager muss ebenfalls ausgenommen werden

### ISSUE THREAD

**Issue by RealSocius** [mexyn/statev_v2_issues#1086]
[Changed] Folgende Aktionen können Staatsbedienstete onDuty nicht mehr tun:
-Ankauf/Verkauf (+Preisänderung) (Ausgenommen: Apotheke, Asservatenkammer)
-Beladen/Entladen vom Marker (Über Türmenü, Lager) (Ausgenommen: Apotheke, Asservatenkammer)

Lifeinvader Lager muss ebenfalls ausgenommen werden

**Comment by its4l3x** [comment]
Bitte erst absprechen mit Spoon/Shanel

Danke
