### ISSUE TITLE
Partybus nicht in der Garage

### ISSUE THREAD

**Issue by PrimroseBloom** [mexyn/statev_v2_issues#1087]
**Character Name**
Primrose Bloom

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.01. und 24.01.

**Beobachtetes Verhalten**
Lifeinvader Partybus wird nach dem Restart in der NSA Garage eingeparkt und kann nicht von Mitarbeitern ausgeparkt werden.

**Erwartetes Verhalten**
Der Partybus wird in der Lifeinvader Garage eingeparkt

**Comment by DonVitoDiangelo** [comment]
Wenn das Fahrzeug keinem Team angehört, kommt es in die normale Garage. Im Support checken lassen und ob das gewollt ist.

**Comment by PrimroseBloom** [comment]
Das Fahrzeug ist dem Team angehörig. Der Support hat gesagt, ich soll es hier rein schreiben. Die wissen auch nicht warum er da oben eingeparkt wird. Er stand beim ersten mal beim Restart am Zort Zancudo und gestern stand er an der Lost Bar. Und beide male ist er in der NSA Garage eingeparkt wurden und wie gesagt kein Mitarbeiter kann ihn ausparken sondern nur der Support.

**Comment by its4l3x** [comment]
Kennzeichen vom Bus bitte

**Comment by PrimroseBloom** [comment]
Kennzeichen: Lifegig

**Comment by its4l3x** [comment]
Passt schaue später mal

**Comment by its4l3x** [comment]
Fahrzeug-Config vom pbus2 fehlt. Bitte nachtragen. @DonVitoDiangelo @DrGrizzlY17

**Comment by DonVitoDiangelo** [comment]
fixed next update
