### ISSUE TITLE
Beim bearbeiten eines Teammitglieds im Teammanagement muss die Dienstnummer immer erneut eingeben werden

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#1089]
**Character Name** Erwin Dulach

**Auftrittszeitpunkt (Datum / Uhrzeit)** 19:30

**Beobachtetes Verhalten** Beim bearbeiten eines Teammitglieds im Teammanagement muss man die Dienstnummer immer erneut eingeben, wenn man das nicht tut kann die Änderung nicht gespeichert werden.

**Erwartetes Verhalten** Die bereits eingetragene Dienstnummer wird beim bearbeiten genauso wie alle anderen Angaben angezeigt

**Schritte um den Fehler nachvollziehen zu können** Auf das Stiftsymbol im Teammanagement klicken -> Änderungsbild prüfen

**Optional: Video / Bilder des Fehlers** https://prnt.sc/xk6l51 (Man beobachte wie im Änderungsscreen die DNR fehlt, in der Übersicht unten aber bereits exisitiert.

**Comment by its4l3x** [comment]
fixed next update
