### ISSUE TITLE
Handy & Tablet schließen

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#109]
**Character Name**

Erwin_Dulach aber auch allen anderen

**Zeitpunkt (Datum / Uhrzeit)**

Immer, zuletzt 25.08 gegen 22:00

**Beobachtetes Verhalten**

Handy sowie Tablet schließen sich erst mit Hotkey, nachdem man auf den Homebutton (bzw ich glaube irgendwo auf das Model) geklickt hat. Vorher passiert beim F2/F3 klicken nichts.

**Erwartetes Verhalten**

Handy & Tablet zu jeder Zeit mit F2 / F3 wegklicken können.

**Schritte um den Fehler nachvollziehen zu können**

F2 drücken -> warten bis Handy ganz eingeblendet ist -> F2 drücken und sehen wie nix passiert -> Mit Maus auf Homebutton klicken -> F2 drücken und damit erst Handy wegklappen.
Gleiches Vorgehen fürs Tablet.

**Comment by its4l3x** [comment]
Kein Bug, ist ein cooldown
