### ISSUE TITLE
Duffle Bag Unsichtbar

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#1090]
**Character Name**

Sven Rosenbach
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer
**Beobachtetes Verhalten**

Wenn man den V2 Hoodie anzieht sieht man den Duffle Bag nicht
**Erwartetes Verhalten**

Man sieht den Duffle Bag
**Schritte um den Fehler nachvollziehen zu können**

Duffle Bag ausrüsten und gleichzeitig den Pullover
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://user-images.githubusercontent.com/58612983/105642456-1d990f00-5e8a-11eb-820c-8f6f075ee00e.mp4

**Comment by DrGrizzlY17** [comment]
![image](https://user-images.githubusercontent.com/70150988/105643727-dadb3500-5e91-11eb-9faa-0cf2807336c5.png)
