### ISSUE TITLE
Keine Aktionen im Auto mehr möglich

### ISSUE THREAD

**Issue by CaleighRhodes** [mexyn/statev_v2_issues#1091]
**Character Name**
Caleigh_Rhodes

**Auftrittszeitpunkt (Datum / Uhrzeit)**
immer, seit ca. 2 Wochen

**Beobachtetes Verhalten**
Ich kann im Fahrzeug weder den Mittelfinger rausstrecken, noch das Waffenrad bedienen. Ich muss für letzteres aussteigen. 

**Erwartetes Verhalten**
Mit Rechtsklick Arm heben, mit TAB Waffenrad bedienen können

**Schritte um den Fehler nachvollziehen zu können**
keine Ahnung - bei anderen scheint es zu funktionieren :(

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920 * 1080

**Comment by DonVitoDiangelo** [comment]
Bitte über Forum oder Support Hilfe suchen. Hier werden wir dir nicht helfen können. Sry
