### ISSUE TITLE
Garage für Haus Nicola Place 22

### ISSUE THREAD

**Issue by ManuelLadner** [mexyn/statev_v2_issues#1092]
**Manuel_Ladner**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 Für Immer!

**Beobachtetes Verhalten**
Garagentor/Innenhofeinfahrt optisch vorhanden!

**Erwartetes Verhalten**
Privatgarage für 6 Fahrzeuge oder maximal wenn möglich 

**Optional: Video / Bilder des Fehlers**
Bilder anbei! Besitzer ist Thomas Schnarch ich bin der Käufer der das Haus gerade in Raten kauft! Ich habe das OK von Thomas das mit der Garagenbeantragung zu machen! 

![20210125123644_1](https://user-images.githubusercontent.com/77968842/105702066-7fe62400-5f0b-11eb-83aa-38dc023f2d8e.jpg)

![20210125123654_1](https://user-images.githubusercontent.com/77968842/105702078-84124180-5f0b-11eb-89a1-2b0dd19c306d.jpg)

![20210125123710_1](https://user-images.githubusercontent.com/77968842/105702091-883e5f00-5f0b-11eb-9765-4fd84a84b825.jpg)

In dieser Straße ("Copkreisel") hat fast jedes Haus eine Garage ich würd mich freuen das unser Haus auch eine bekommen kann!

**Comment by Statev-Bonsai** [comment]
Offtopic: Was ist denn das da oben links am Bildschirm? o.0

**Comment by ManuelLadner** [comment]
hy ja ich war 5 min ic um diese bilder zu screenshoten und gleichzeitig auf discord! wenn du das anspielen willst!?

**Comment by Statev-Bonsai** [comment]
;)

**Comment by ManuelLadner** [comment]
ja discord! aber ich weiß nicht warum es mir das anzeigt!

**Comment by Statev-Bonsai** [comment]
ist halt kritisch wenn ihr beide auf state spielt und nebenbei noch im discord am quatschen seid....

**Comment by ManuelLadner** [comment]
das ist mir klar aber sie ist nicht ic!!

**Comment by Statev-Bonsai** [comment]
das ist egal!

**Comment by ManuelLadner** [comment]
was woll ich jetzt deiner meinung nach machen? mir ist klar das das ein fehler ist! ich bin aber jetzt schnell ic gegangen um 3 screenshots zu machen und ja ich bin in discord gewesen! ich kann es jetzt nicht ändern!

**Comment by DrGrizzlY17** [comment]
Da ist zwar ne Hofeinfahrt, aber keine Garage. Deshalb abgelehnt
