### ISSUE TITLE
Objekt entfernen an privatem Haus

### ISSUE THREAD

**Issue by AngelMaravilla** [mexyn/statev_v2_issues#1094]
**Character Name**
Angel Maravilla

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Ich würde mich freuen, wenn man das Verkaufsschild vor dem Wohngebäude im West Mirror Drive 0 (Ja, wirklich null) entfernen könnte.
Haushash: house_Vinewood_0

**Erwartetes Verhalten**
Das auf den Screenshots dargestellte Schild wird entfernt.
![Screenshot_1](https://user-images.githubusercontent.com/74780492/105719619-c8f5a280-5f22-11eb-97f3-99ea2a8ccd54.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/74780492/105719622-ca26cf80-5f22-11eb-9e85-dfbf0e18d343.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/74780492/105719628-cb57fc80-5f22-11eb-8ec0-5f95bbdca3ac.jpg)

**Comment by DonVitoDiangelo** [comment]
Optisch zwar entfernbar, aber die Kollision würde bleiben. Von daher abgelehnt, sry.
