### ISSUE TITLE
Kleidung, Rucksäcke und Tattoos werden falsch angezeigt

### ISSUE THREAD

**Issue by BeastclawTV** [mexyn/statev_v2_issues#1095]
**Pascal_Martinez**

**Immer**

**Kleidung wird falsch angezeigt, genau wie Rucksäcke und Tattoos**

****

****

**https://www.youtube.com/watch?v=jMabRgr5MYI&feature=youtu.be**

**https://www.youtube.com/watch?v=UCsNPArflw8**

**Comment by DonVitoDiangelo** [comment]
Was genau wird wie falsch angezeigt?

**Comment by DonVitoDiangelo** [comment]
Vllt. kann unsere Modedesignerin hier weiterhelfen @Enemyaa  :)

**Comment by Enemyaa** [comment]
@DonVitoDiangelo @BeastclawTV Dein Player hat scheinbar Anzeigefehler, bei absolut jedem mod. Item. Ich kann den Fehler nicht nachstellen, da ich solche Probleme nicht habe!

**Comment by BeastclawTV** [comment]
Sind ja nicht nur die Markensachen sondern auch die Diamandhoodies, meine Tattoos und die Rucksäcke
