### ISSUE TITLE
Animation länger als Prozess

### ISSUE THREAD

**Issue by Knippsa** [mexyn/statev_v2_issues#1096]
**Kalle Knutsen**

**Egal**

**Die Arbeitsanimation beim Salat, Gurken & Kartoffelfeld ist länger als der Prozess. Selbst auf Skill-Stufe 1. Die Animation kann nicht durch bewegen unterbrochen werden. Dementsprechend wird die Arbeit immer gleichlang dauern, egal wie gut man geskillt ist. **

**Animation sollte nach Prozessabschluss automatisch unterbrochen werden.**

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/768
