### ISSUE TITLE
Teleporter für Durchgang zum Garten

### ISSUE THREAD

**Issue by Nightdelta77** [mexyn/statev_v2_issues#1097]
Ethan Willis

Haus: North Conker Ave. 4 // Haushash: house_VinewoodHills_3

Kann bitte an beiden gezeigten Türen ein Teleporter eingefügt werden,
damit man einen Zugang zum Garten bekommt?
Einen normalen/natürlichen Eingang zum Garten gibt es nicht.

Bilder: https://ibb.co/sbpWV0F  und  https://ibb.co/JvnWTGf
Video: https://youtu.be/cAK3875uRdY

**Comment by DonVitoDiangelo** [comment]
Abgelehnt, da wir keine privaten Teleporter einführen werden.

**Comment by Nightdelta77** [comment]
Aber es gibt doch an sehr vielen Häusern Teleporter um auf den Balkon oder in den Garten zu kommen?
