### ISSUE TITLE
Indianisches Kriegsbeil & Alter Koffer nicht mehr in Wohnung

### ISSUE THREAD

**Issue by miischaa** [mexyn/statev_v2_issues#1098]
**Character Name**
Heinrich Iwanow

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 24.01.2020 Uhrzeit ungenau

**Beobachtetes Verhalten**
Uns ist mit mehreren Leuten aufgefallen, dass unsere Indianischen Kriegsbeile UND unser Koffer die man damals die ersten beiden Tage herstellen konnte (welche durch den Aktenkoffer ersetzt wurden) nicht mehr in unseren Wohnungen sind. 

**Erwartetes Verhalten**
Naja sollte eigentlich da sein oder etwa nicht?

**Schritte um den Fehler nachvollziehen zu können**
Habe in meine Wohnung geschaut und es festgestellt, danach haben die anderen 3 Leute das auch gemacht und es ebenfalls festgestellt

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Wie lange bzw. seit wann waren die dort drin? Vllt. wurdet ihr gekündigt und der Mieter hat Sie entfernt.

**Comment by Statev-Bonsai** [comment]
Die Kriegsbeile die man bei V1 gefunden hat sind seid V2 nicht mehr vorhanden, das kann ich so bestätigen.
Ich hatte auch 2 in meinem Haus und die sind seit V2 Release nimmer auffindbar.

**Comment by DonVitoDiangelo** [comment]
Stimmt, mir fällt gerade ein, dass wir da etwas ändern mussten, daher wurden diese entfernt.
Danke für den Reminder

Also nein, diese sind dann verloren, sry.
