### ISSUE TITLE
Ausparken öffentliche Garage Paleto Bay

### ISSUE THREAD

**Issue by Stiefel911** [mexyn/statev_v2_issues#1099]
**Character Name**
Yanalar Vemo

**Beobachtetes Verhalten**
Fahrzeug spawned zu hoch.
z .b.: 
- Burrito nach ausparken, Scheiben platzen ;
- Bike spawned gefühlt ein Meter über dem Platz

**Erwartetes Verhalten**
Ausparken wie in Grapeseed / Sandy Shoers
 
**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug ausparken

**Comment by DrGrizzlY17** [comment]
Konnte es nicht reproduzieren. Kannst du mal nen Video davon aufnehmen z.B vom Burrito? Am besten mit einparken und ausparken.

**Comment by DonVitoDiangelo** [comment]
Das mit dem Scheiben platzen ist ein alt:V issue. Sollte aber nach nem Restart bzw. einer Reparatur beim Mechaniker wieder fixed sein.

**Comment by Stiefel911** [comment]
Neuigkeiten. 
kam bis jetzt leider nur nicht zum Antworten.
Gestern Abend wollte ich es aufnehmen. Nur was passierte? Nichts passiert.
Entweder hat es sich selber gefixt oder es war Clientseitig... Ich parkte mehrmals ein und aus, und passiert ist nichts, ganz normal gespawned.
**Was es auch war, es ist weg**.  

vielen Dank für Eure Mühe und sry zwecks Umstände
