### ISSUE TITLE
Skillsystem / skill-description zu klein

### ISSUE THREAD

**Issue by DonVitoDiangelo** [mexyn/statev_v2_issues#11]
**Zeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
zu kleine Description   (Auflösung 2k/WQHD/ 2560x1440)

**Erwartetes Verhalten**
Größere Decription

**Schritte um den Fehler nachvollziehen zu können**
Skillsystem UI öffnen (K) und gelernten Skill auswählen

**Optional: Video / Bilder des Fehlers**
![1](https://user-images.githubusercontent.com/70151087/91192361-2082ae80-e6f6-11ea-8662-6873a9b02753.jpg)

**Comment by r3sist3nt** [comment]
@DonVitoDiangelo kannst du das bitte nochmal testen, ich hab das angepasst.
