### ISSUE TITLE
Loginscreen - Passwortfeld nicht anklick bar.

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#110]
**Zeitpunkt (Datum / Uhrzeit)**
27.08.2020 / 16:36

**Beobachtetes Verhalten**
Wenn man aus dem Eingabefeld rausklickt kann man nicht mehr reinklicken außer mit der TAB Taste. 

**Erwartetes Verhalten**
Man sollte rein klicken können.

**Schritte um den Fehler nachvollziehen zu können**
1. Mit der Maus aus dem Eingabefeld rausklicken
2. Versuchen mit der Maus reinzuklicken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920*1080 @ 144Hz

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/130efd6bc0d75fd0d6a2280c447d6160

**Comment by r3sist3nt** [comment]
Anmerkung: Das ganze ist erst reproduzierbar, wenn man das passwort einmal falsch eingegeben hat.

**Comment by r3sist3nt** [comment]
fixed nach restart
