### ISSUE TITLE
Bauantrag Werkstatt ReactionCorp - Little Bighorn Avenue

### ISSUE THREAD

**Issue by LautaroTesto** [mexyn/statev_v2_issues#1101]
**Character Name**
Lautaro_Testo in Vertretung von Simon_Maddicks
IC ausgeführt von Lautaro_Testo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.01.2021 13:00-14:00Uhr

**Beobachtetes Verhalten**
Wie im Video zu sehen, ist leider die Lackierkabine in der Werkstatt zu klein. Dadurch müssen Ingame immer wieder Kunden weggeschickt werden = Minus Geschäft

**Erhofftes Verhalten**
Ich hoffe ich konnte in dem Video genug Argumente aufzeigen das die Lackierkabine leider zu klein ist. 
Lösungsansätze: Vielleicht die Türen in der Lackierkabine ausbauen, was mehr Platz bringt um diese Autos rein zu fahren, aber es weiterhin schwierige "Arbeitsumstände" mit sich bringt. Lackierpunkt vielleicht umsetzen, dass hätte nochmehr Platz und man könnte sich auch um das Auto stellen um die neue Lackierung zu begutachten. 
Sollte vielleicht noch was unklar sein, kann man dies ja gegebenfalls im Teamspeak besprechen.

Vielen Dank im Voraus!

**Optional: Video / Bilder des Fehlers**
Youtube Video: https://youtu.be/PWwC4CvQ6zQ

**Comment by DonVitoDiangelo** [comment]
Ja, für manches zu klein, deshalb gibt es ja auch größere. Daher Abgelehnt.
