### ISSUE TITLE
Kleidung - Notfall MD

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1103]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
ca 11:00

**Beobachtetes Verhalten**
Ausgeteilte Kleidung am Notfall MD passt nicht.
Es wurde nur ein unterteil ausgeteilt, aber kein oberteil

**Erwartetes Verhalten**
Das die Kleidung die man bekommt, optisch auch vollständig ist.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Das wurde ausgeteilt:
![Screenshot_3](https://user-images.githubusercontent.com/70150887/105985908-74763280-609c-11eb-8914-25cb8986d4f6.jpg)

So sah es aus:
![Screenshot_2](https://user-images.githubusercontent.com/70150887/105985916-763ff600-609c-11eb-854e-461896c9814c.jpg)

**Comment by TheBroady** [comment]
Zusatz: Das Tshirt scheint ein Oberteil gewesen zu sein, allerdings wurde es am Char, als Unterteil angezeigt. Ganz weird

**Comment by Enemyaa** [comment]
Hi @TheBroady Kann ich leider nicht nachstellen. Bei mir ist alles ok, deswegen denk ich mal, dass war nur ein seltsamer Zufall.

**Comment by TheBroady** [comment]
Bringt es dir was, besagtes T-shirt zu bekommen?
Es ist eins für oben drüber aber wird drunter angezeigt
