### ISSUE TITLE
Konto kann nicht gelöscht werden

### ISSUE THREAD

**Issue by MaxiKowa** [mexyn/statev_v2_issues#1104]
**Maxi Kowa**

**Beobachtetes Verhalten**
Konten lassen sich nict löschen über das statenet funktion fehlt 

**Erwartetes Verhalten**
Das ich das konto löschen kann 

**Schritte um den Fehler nachvollziehen zu können**
neues konto erstellen und versuchen zu löschen 

https://pic.statev.de/image/pOmOg

**Comment by DonVitoDiangelo** [comment]
Korrekt, das ist so gewollt.

**Comment by MaxiKowa** [comment]
und wie soll ich dann ein konto löschen ???
