### ISSUE TITLE
Doppelter Perso im X-Menü

### ISSUE THREAD

**Issue by Kaycee91** [mexyn/statev_v2_issues#1106]
**Nick Adam**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

dauerhaft
**Beobachtetes Verhalten**

Habe in meinem X Menü zwei mal die Auswahlmöglichkeit Personalausweis zeigen beide Funktionieren
**Erwartetes Verhalten**

Nur einmal diese Option zu haben 
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Grand Theft Auto V Screenshot 2021 01 22 - 00 22 00 72](https://user-images.githubusercontent.com/38119374/106158088-aadaad00-6183-11eb-9bc5-5d68ae4f9d9d.png)
![Grand Theft Auto V Screenshot 2021 01 22 - 00 21 56 45](https://user-images.githubusercontent.com/38119374/106158102-af06ca80-6183-11eb-9fae-259310746c77.png)
![Grand Theft Auto V Screenshot 2021 01 22 - 00 22 15 63](https://user-images.githubusercontent.com/38119374/106158112-b29a5180-6183-11eb-9b1e-e98511422dce.png)
![Grand Theft Auto V Screenshot 2021 01 22 - 00 22 10 45](https://user-images.githubusercontent.com/38119374/106158128-b62dd880-6183-11eb-8f07-3d06b5a8cd94.png)

**Comment by its4l3x** [comment]
Bist du in einer Fraktion? (HK, Lifeinvader, etc..)

**Comment by Kaycee91** [comment]
Ja bin bei Lifeinvader

**Comment by its4l3x** [comment]
Top. Habe es gefixed. Ist im nächsten Update dabei

**Comment by Kaycee91** [comment]
vielen dank

**Comment by its4l3x** [comment]
no problemo
