### ISSUE TITLE
Einbinden eines Objekts

### ISSUE THREAD

**Issue by DanielKules** [mexyn/statev_v2_issues#1107]
Guten Abend in die Runde,

Ich hoffe der Thread ist hier korrekt eingeordnet, ansonsten lyncht mich dafür.

Ich bin oft oben im Norden unterwegs da fiel mir letztens auf, dass dort dieser Verpflegungsstand leer steht und ich mich an dieses Forum wenden solle.

Wenn ich es richtig verstanden habe finde ich hier jemanden, der dieses Objekt einbinden könne?

Hier einmal die Ansicht der Karte sowie eins des Objekts um das es sich handelt:
https://pic.statev.de/image/nordkuste-san-andreas.pfIVJ
https://pic.statev.de/image/verpflegungsstand-mit-blick-zur-tankstelle.pfvjI

Würde mich sehr freuen von Ihnen zu hören

Und falls sich jemand die Arbeit macht schon einmal Vielen Dank im Voraus

Mit freundlichen Grüßen

**Comment by DonVitoDiangelo** [comment]
Hi, danke für die Anfrage, allerdings werden wir keine weiteren Imbisse einbinden.
