### ISSUE TITLE
"Wanted" Bug nach dem ich aus "Autoshop" raus gegangen bin.

### ISSUE THREAD

**Issue by Lysiahx3** [mexyn/statev_v2_issues#1111]
**Character Name**
 Lyss Parker

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 21:00 Uhr ca. am 30.01.21

**Beobachtetes Verhalten**
 Ich bin in die Werkstatt "Autoshop" eingetreten, als ich wieder raus kam hatte ich einen Stern wie im Online Modus, wenn man von Cops verfolgt wird. (Map hat ebenso geblinkt)
Ps. Falls nötige information, ich war eingestempelt unterwegs im SAPD.
**Erwartetes Verhalten**
 Einfach nicht passieren? Hatte das Problem bisher nie.

**Schritte um den Fehler nachvollziehen zu können**
 Reproduzierbarkeit nicht nachweisbar.

**Optional: Video / Bilder des Fehlers**
 
![GTA5 2021-01-30 21-28-36](https://user-images.githubusercontent.com/78279170/106368068-305a8a80-6347-11eb-8924-62aa36e0df37.png)

**Comment by Bene-RonnyMoritz** [comment]
Hatte das gestern auch zum 1. Mal, nachdem wir zu 4. (onduty) im Auto saßen und versehentlich die Alarmanlage beim Auto neben uns ausgelöst haben. Der Fahndungsstatus blieb auch bis zum ausloggen (4h später) bestehen 

![53fcd8ef5557987eb50b9cc05699f7c3-jpg](https://user-images.githubusercontent.com/78343649/106428784-cd154900-6469-11eb-9091-9f422aea89b7.jpg)
