### ISSUE TITLE
Tar-21 Waffengurt zu lang 

### ISSUE THREAD

**Issue by masterppc** [mexyn/statev_v2_issues#1113]
**Character Name**
Hans Hentschel

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Waffe hängt fast unterm Po

**Erwartetes Verhalten**
Wie bei den anderen Waffen richtig am Rücken

**Schritte um den Fehler nachvollziehen zu können**
Tar 21 ausrüsten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
---
**Optional: Video / Bilder des Fehlers**
https://i.imgur.com/vpkD22Z.jpg

**Comment by DonVitoDiangelo** [comment]
Leider haben wir das System hier nicht pro Waffe, sondern pro Slot.  Würden wir dies jetzt hoch setzen, wäre diese eine Waffe korrekt aber alle anderen and diesem Slot wieder zu hoch. Daher belassen wir das hier so.
