### ISSUE TITLE
Miete wird nicht vom Konto abgezogen

### ISSUE THREAD

**Issue by zarazandra** [mexyn/statev_v2_issues#1114]
**Character Name**
Venus Moreau

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit gestern Abend, ca. 19/20 Uhr

**Beobachtetes Verhalten**
Bin innerhalb des gleichen Hotels umgezogen, seitdem wird dem Charakter die Miete nicht mehr abgezogen

**Erwartetes Verhalten**
Miete wird stündlich abgezogen 

**Schritte um den Fehler nachvollziehen zu können**
unbekannt, da erstmals aufgetreten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![wisdahl](https://user-images.githubusercontent.com/70195103/106392833-feebc880-63f3-11eb-8821-5827471f2037.png)
![konto](https://user-images.githubusercontent.com/70195103/106392834-001cf580-63f4-11eb-9c10-c411017f9181.png)

**Comment by zarazandra** [comment]
Hinweis: Keine Ahnung, ob schon was gemacht wurde, nach neuem Einloggen wird Miete abgezogen!

**Comment by its4l3x** [comment]
So oder so werden wir uns dem Haussystem demnächst widmen, da dies einen Dringend Rework benötigt.

**Comment by JulianMa** [comment]
Mit #1534 behoben.
