### ISSUE TITLE
Itemslots bei Durchsuchung

### ISSUE THREAD

**Issue by DrColgate** [mexyn/statev_v2_issues#1115]
**Character Name**

Anton Mueller
**Auftrittszeitpunkt (Datum / Uhrzeit)**

27.01.2021 19:19
**Beobachtetes Verhalten**

Ich wurde von Raymond_Brooks - Dienst-Nr.: 242 gefessellt und durchsucht.
Er wollte mir Handy, Tablet und Vunk abnehmen. Erst hatte ich die Items noch in den Slots. Durch das RP habe ich germerk das er mir die so nicht abnehmen kann. Deshalb habe ich die Items ins Inventar gezogen. Auch dadurch konnte er die wohl nicht sehen oder mir abnehmen.
Habe die Items dann über das Handelsmenü übergeben.

Angeblich wurde in seinem Stream gesagt das ich das ausgenutzt hätte, und die Items in den Slots gelassen habe damit er sie mir nicht abnehmen kann. Ob das wirklich so gesagt wurde weiß ich nicht und ist mir auch egal.
Aus irgendeinem Grund konnte er mir die Items nicht abnehmen. Warum weiß ich nicht, ich kenne nur meine Perspektive, die eines Cops nicht. Auch den Stream habe ich nicht gesehen, kann also nichts zu seiner Sicht sagen.

**Erwartetes Verhalten**

Das ein Cop auch Dinge aus den Itemslots nehmen kann
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TaylorTheguy** [comment]
Man muss als Cop einfach ein zweites mal "durchsuchen" klicken damit sich das Inventar aktualisiert vom zu Durchsuchenden.

**Comment by DonVitoDiangelo** [comment]
So ist es. :)
