### ISSUE TITLE
Gamecrash rund um den Würfelpark

### ISSUE THREAD

**Issue by HarzadousElexir** [mexyn/statev_v2_issues#1116]
Luca Disanta

Luca Disanta
**Auftrittszeitpunkt (Datum / Uhrzeit)**
immer 

**Beobachtetes Verhalten**

Gamecrash rund um den Würfelpark. Ca 1km radius
**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

Gamecrash beim vorbeifahren in der Nähe
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

3440*1440
**Optional: Video / Bilder des Fehlers**

**Comment by Gruntelicious** [comment]
Absolut unspielbar der Bereich, bei 90% aller Durchfahrten Abstürze + mehrere Crashs (Gerade min. 5 mal hintereinander) beim Einloggen.

Besonders auffällig bei mir an der Südseite des Würfelparks von Ost nach West und West nach Ost, ganz speziell die Kreuzung Vespucci Blvd Ecke Elgin Ave. Jede Einsatz/PD An- und Abfahrt endet im Crash.

**P.S.: Habe mit dem Originalposter hier nix zu tun, ich nutze das Thema nur gleich mal.**

[client_01-02-2021_13-36-08.log](https://github.com/mexyn/statev_v2_issues/files/5904181/client_01-02-2021_13-36-08.log)
[client_01-02-2021_13-52-30.log](https://github.com/mexyn/statev_v2_issues/files/5904182/client_01-02-2021_13-52-30.log)
[client_01-02-2021_13-56-00.log](https://github.com/mexyn/statev_v2_issues/files/5904183/client_01-02-2021_13-56-00.log)
[client_01-02-2021_14-01-32.log](https://github.com/mexyn/statev_v2_issues/files/5904184/client_01-02-2021_14-01-32.log)
[client_01-02-2021_14-09-07.log](https://github.com/mexyn/statev_v2_issues/files/5904185/client_01-02-2021_14-09-07.log)
[client_01-02-2021_14-11-10.log](https://github.com/mexyn/statev_v2_issues/files/5904186/client_01-02-2021_14-11-10.log)
[client_01-02-2021_14-13-28.log](https://github.com/mexyn/statev_v2_issues/files/5904187/client_01-02-2021_14-13-28.log)
[client_01-02-2021_14-15-34.log](https://github.com/mexyn/statev_v2_issues/files/5904188/client_01-02-2021_14-15-34.log)
[client_01-02-2021_14-20-17.log](https://github.com/mexyn/statev_v2_issues/files/5904189/client_01-02-2021_14-20-17.log)

**Comment by Gruntelicious** [comment]
Wieder unzählige Crashes. MR Garage Richtung WP und von da aus Richtung Süden.
Der Zustand ist vergleichbar mit Mitte 2019.

**Comment by DonVitoDiangelo** [comment]
Bitte schreibt mal eure PC Specs und Graphic Settings mit dazu. (Bild reicht -Normale und Erweiterte)

**Comment by HarzadousElexir** [comment]
![Grafik 1](https://user-images.githubusercontent.com/78348210/106488474-0bcff100-64b4-11eb-818f-5a528ff3a950.png)
![Grafik 2](https://user-images.githubusercontent.com/78348210/106488503-1094a500-64b4-11eb-9fa0-09c70fca28b3.png)


PC Specs: 
Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz   2.70 GHz
Nvidia Geforce GTX 1060
16 GB RAM

**Comment by Dean-Gallagher** [comment]
@HarzadousElexir bei einer 1060 solltest nicht auf 1440 Spielen, da ist die Graka überlastet.

**Comment by DonVitoDiangelo** [comment]
P.S. Dein System ist für die Darstellung mit diesen Settings nicht ausgelegt. Da brauchst du dich dann nicht wundern, das es auch oft crasht. 

Bitte zukünftig hier posten:
https://github.com/mexyn/statev_v2_issues/issues/1071
https://github.com/mexyn/statev_v2_issues/issues/1071
https://github.com/mexyn/statev_v2_issues/issues/1071

**Comment by DonVitoDiangelo** [comment]
-----------------------------CLOSED-----------------------------
