### ISSUE TITLE
Error beim Produzieren in der Schneiderei

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#1118]
**Ryan & Mila Valdes**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**

[M] Schwarzes Elected Homme Blouson löst einen Error beim produzieren aus

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![érror](https://user-images.githubusercontent.com/70231715/106555171-50dc3d80-651d-11eb-995a-5e09230e7cdf.png)

**Comment by Enemyaa** [comment]
fixed!
