### ISSUE TITLE
Tow Truck Leuchten deaktivieren?

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1119]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Seit V2

**Beobachtetes Verhalten**

Wie bekannt ist, fahren die Tow Trucks seit V2, wenn die Leuchten an sind, mit Sirene durch die Gegend. #1066 

**Erwartetes Verhalten**

Keine Sirenen, deshalb: Wäre es nicht mgl. die Leuchten für den Tow Truck, solange dieses Problem besteht komplett zu deaktivieren?

**Comment by DonVitoDiangelo** [comment]
In der Theorie bestimmt. Wir werden hier allerdings keine Ressourcen für aufwenden, sry.

**Comment by JannikDatsch** [comment]
@DonVitoDiangelo  Ok, könnte man dann vlt. stattdessen kommunizieren, dass diese Leuchten aufgrund dieses Problems ausbleiben sollen?

**Comment by DrGrizzlY17** [comment]
> **Character Name**
> Jannik_Datsch
> 
> **Auftrittszeitpunkt (Datum / Uhrzeit)**
> 
> Seit V2
> 
> **Beobachtetes Verhalten**
> 
> Wie bekannt ist, fahren die Tow Trucks seit V2, wenn die Leuchten an sind, mit Sirene durch die Gegend. #1066
> 
> **Erwartetes Verhalten**
> 
> Keine Sirenen, deshalb: Wäre es nicht mgl. die Leuchten für den Tow Truck, solange dieses Problem besteht komplett zu deaktivieren?

Die sind auch schon zu v1 mit Sirene auf Distanz gefahren

**Comment by JannikDatsch** [comment]
@DrGrizzlY17  Die Meinungsverschiedenheit dazu gab es auch schon im anderen Bugtraker Eintrag dazu. Vlt war das früher mal, oder nur bei manchen Spielern, ich bin jetzt seit März letzten Jahres auf dem Server, und da ist es mir zu V1 Zeiten nie aufgefallen, anderen auch nicht. Aber keine Ahnung vlt. wars auch so und es ist vielen nicht aufgefallen, würde mich aber sehr wundern.
