### ISSUE TITLE
Platzieren von Gegenständen während dem Schieben von Fahrzeugen

### ISSUE THREAD

**Issue by Downgradeeu** [mexyn/statev_v2_issues#112]
**Name**
Chris Samonds

**Zeitpunkt (Datum / Uhrzeit)**
27.08.2020 / 16:30

**Beobachtetes Verhalten**
Während ich mein Fahrzeug (Surfer) geschoben habe konnte ich aus dem Inventar einen Gegenstand zum Platzieren auswählen und diesen setzen. Daraufhin bin ich durch die Map gefallen aber nach einigen Sekunden wenige Meter nebenan wieder gelandet.

**Erwartetes Verhalten**
Kein Platzieren von Gegenständen während dem Schieben von Fahrzeugen möglich.

**Schritte um den Fehler nachvollziehen zu können**
X-Menü am Fahrzeug öffnen > Fahrzeug schieben > Inventar öffnen > platzierbaren Gegenstand wählen und diesen platzieren.

**Comment by DrGrizzlY17** [comment]
bin zwar nicht durch den boden gefallen, das platzieren war aber möglich

**Comment by its4l3x** [comment]
Fixed, next update
