### ISSUE TITLE
Kleidung wird geklont

### ISSUE THREAD

**Issue by HarzadousElexir** [mexyn/statev_v2_issues#1120]
Luca Disanta
**Auftrittszeitpunkt (Datum / Uhrzeit)**

02.02.2021 15:11
**Beobachtetes Verhalten**

WEnn man seine Kleidung wehselt, wird die neu angezogene Kleidung trotzdem Im Inventar angezeigt. Wenn man die Kleidung dann in einen Kofferraum legt, dann klont man das Kleidungsstück und hat auf einmal 2 davon.
**Erwartetes Verhalten**

Kleidung sollte verschwinden, wenn sie angezogen ist
**Schritte um den Fehler nachvollziehen zu können**

1. Kleidungstück anziehen
2.Kleidungsstück von Inventar in Kofferraum ziehen
3. kleidungsstück ausziehen
4. Kleidung doppelt im Inventar
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Da hattest du vermutlich 2x das gleiche Kleidungsstück. Kann ich nicht reproduzieren. Wenn das Kleidungsstück angezogen wird, ist es nicht mehr im normalen Inventar, so wie es auch sein soll.

**Comment by HarzadousElexir** [comment]
Ja richtig jetzt wieder schon deswegen Honig ich davon aus, dass es behoben
wurde. Aber ein paar Tage lang ging es die Kleidung zu klonen. Wenn du in
meinen Schrank im Hotel Zimmer reinsiehst sind da 2 Bauarbeiter Helme.
Einer davon wurde geklont


DonVitoDiangelo <notifications@github.com> schrieb am Di. 2. März 2021 um
10:05:

**Comment by DonVitoDiangelo** [comment]
ok, danke für die Rückmeldung.
