### ISSUE TITLE
Keine Waren mehr im Bekleidungsgeschäft!

### ISSUE THREAD

**Issue by Clawdie** [mexyn/statev_v2_issues#1121]
Glinda Ehrmantraut
Lasse Leverstone
**Auftrittszeitpunkt (Datum / Uhrzeit)**
heute nach 12 Uhr irgendwann; aktuell bestehend!

**Beobachtetes Verhalten**
Lager gefüllt, Ware bepreist, letzter Verkauf mittags, aber egal wo (Oberteile, Hosen etc.): KEINE Ware zu kaufen, nur angezeigtes X

**Erwartetes Verhalten**
Übliche Menüs

**Schritte um den Fehler nachvollziehen zu können**
Versuchen, bei Chiliad Fashion etwas zu kaufen (bislang durch 3 Personen reproduziert; in getesteten anderen Läden nicht gegeben)

**Comment by its4l3x** [comment]
ist fixed. war ein zufälliger fehler. wird mit dem nächsten update nicht mehr auftreten
