### ISSUE TITLE
Hotel zuwenig Zimmer für die Größe

### ISSUE THREAD

**Issue by Schnarch** [mexyn/statev_v2_issues#1123]
Ich habe mir vor kurzem ein Hotel gekauft (ca. 550.000$), es hat 31 Zimmer
Nun habe ich es mal mit anderen deutlich kleineren Hotels verglichen und die haben größtenteils mehr Zimmer als mein Castle.
Daher bitte ich darum die Anzahl der Zimmer zu erhöhen.
Grüße Schnarch
https://pic.statev.de/image/p95v2
https://pic.statev.de/i/p9DBP.png

Vielen Dank für die Bearbeitung

**Comment by DrGrizzlY17** [comment]
Auf 45 Zimmer erhöht

**Comment by Schnarch** [comment]
Vielen dank, habe ich die Möglichkeit auf 65  Zimmer aufgrund der Größe? 
Hotels in meiner größe haben sonst ca. 120 Zimmer.
Wäre super. vielen Dank
