### ISSUE TITLE
Fahrzeug Teleportiert sich nach ausloggen weg

### ISSUE THREAD

**Issue by Michi993** [mexyn/statev_v2_issues#1124]
**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Bitte neuen Eintrag eröffnen mit mehr Infos.
