### ISSUE TITLE
Fahrzeug Teleportiert sich nach ausloggen weg

### ISSUE THREAD

**Issue by Michi993** [mexyn/statev_v2_issues#1126]
**Character Name**
 Luke_Hammer 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Fast jeden abend nach ausloggen aus dem game im Hotelzimmer 
**Beobachtetes Verhalten**
Das davor benutzte fahrzeug teleportiert sich random an einen punkt, der in den vorherigen 30 min mal angefahren wurde mit angeschaltetem Motor. 
**Erwartetes Verhalten**
Fahrzeug bleibt da stehen, wo es sein soll 

**Schritte um den Fehler nachvollziehen zu können**
Einfach mal das Fahrzeug abstellen und ausoggen 
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
X

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Ist das immer noch so? Habe mich mal eben umgehört, alle meinten das dies lange nicht mehr so ist.

Wir hatten diese Fehler bereits Anfangs zu Release von V2 gefixed...

Vllt. fährt jemand mit deinem Auto?

Markiere es als Invalid, aber kannst trotzdem noch Antworten

**Comment by M4rvinLP** [comment]
Hatte das Problem am Anfang von V2, dann ewigkeiten nicht mehr. Gestern ist es mir aber auch wieder passiert.

**Comment by Michi993** [comment]
niemand hat schlüssel außer ich, und das fahrzeug steht angeschalten irgendwo rum, aktuell parke ich es immer ein, aber versuche es nochmal

**Comment by its4l3x** [comment]
@M4rvinLP Wann genau gestern (Uhrzeit bitte)

@Michi993 Alles klar, wäre super. Danke

**Comment by M4rvinLP** [comment]
War zwischen 19 und 20:30 Uhr.

**Comment by M4rvinLP** [comment]
Am Mittwoch auch wieder: Fahrzeug stand an meiner Tanke, sollte beim automatischen einparken in die Bootsgarage eingeparkt werden --> Fahrzeug stand zuvor etwas länger beim PD und wurde beim Würfelpark eingeparkt.

Gerade eben: Fahrzeug stand am PD --> nach Server Restart wurde es zurück zur Bootsgarage eingeparkt.

**Comment by M4rvinLP** [comment]
Gestern Nacht gegen 1 Uhr das Fahrzeug in Little Seoul abgestellt, zuvor war es länger beim Casino. --> Auto wurde in die Casino Garage eingeparkt.

**Comment by DonVitoDiangelo** [comment]
Gibt es hier noch Probleme? @M4rvinLP

**Comment by M4rvinLP** [comment]
Nicht wieder passiert.

**Comment by its4l3x** [comment]
okay, closed
