### ISSUE TITLE
Wohnung an der Mayellane AVE. 53 nicht zum Ausziehen

### ISSUE THREAD

**Issue by BenjaminKendrick** [mexyn/statev_v2_issues#1127]
**Hilma_Kaiser**

**Auftrittszeitpunkt (03.02.2021/23:00)**

**Beobachtetes Verhalten**
<wollte aus der Wohnung ausziehen, kann ich aber nicht da zwei Wohnungspunkte (Grün) übereinander liegen und das ausziehen somit nicht möglich ist.

**Erwartetes Verhalten**
<den einen Grünen Einzugspunkt verlegen und mich aus der Wohnung schmeißen

**Schritte um den Fehler nachvollziehen zu können**
<zwei einzelne Grüne Wohnungen liegen übereinander

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
  
![bug1](https://user-images.githubusercontent.com/78513508/106825050-60c26180-6684-11eb-8c1d-57b1e43cc1f3.png)
->

**Comment by BenjaminKendrick** [comment]
Update in der Wohnung Rechts daneben ist es noch schlimmer, 6 Wohnparteien aber nur ein Grüner Ring

**Comment by BenjaminKendrick** [comment]
Wenn man ca. 50 Meter weg ist wird aus dem grünen Punkt ein blauer

**Comment by DrGrizzlY17** [comment]
Ich brauch bitte mal nen konkreten Hinweis wo das ist. Foto von der Map, Hash oder ne Adresse

**Comment by BenjaminKendrick** [comment]
![Uploading bug 2.png…]()

**Comment by BenjaminKendrick** [comment]
![Uploading bug 2.png…]()

**Comment by BenjaminKendrick** [comment]
Da wo das Haus ist 
![Uploading bug 2.png…]()
