### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by scortie1337** [mexyn/statev_v2_issues#1128]
**Andrew_Pearson**
 Andrew Pearson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 04.02.2021 23:55Uhr

**Beobachtetes Verhalten**
Gamecrash beim Autofahren

**Erwartetes Verhalten**
Kein Game Crash :D

**Schritte um den Fehler nachvollziehen zu können**
 
Das Bild zeigt die genaue Stelle inc. Fahrtrichtung.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://i.gyazo.com/cae8634b8679066334d33024645efeff.png

**Comment by its4l3x** [comment]
Besteht die Möglichkeit auch ein größeres Bild zu machen von der Karte? :D

**Comment by scortie1337** [comment]
Aber natürlich
https://gyazo.com/2743258b73b76fa0cb9391edfd3a142b

**Comment by DrGrizzlY17** [comment]
In #1143 verschoben
