### ISSUE TITLE
Game Crash am Highway LSMD

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#1129]
**Character Name**
Paul Humpert

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.02.2021 / 15:01 

**Beobachtetes Verhalten**
Game ist abgestürzt, beim Fahren in Richtung Stadt sowie beim Fahren aus der Stadt

**Erwartetes Verhalten**
Game sollte nicht crashen
![Crash MD](https://user-images.githubusercontent.com/74912696/107044637-e0574a00-67c4-11eb-9597-498cd61b0da1.PNG)

**Comment by DrGrizzlY17** [comment]
In #1143 verschoben
