### ISSUE TITLE
Game Crash 5150

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1130]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.02.2021 17:55

**Beobachtetes Verhalten**
Fahrtrichtung westen bei Posten 5150.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
![Screenshot_1](https://user-images.githubusercontent.com/70150887/107065502-24564900-67dd-11eb-9dc2-42d280f03ef7.jpg)

**Comment by TheBroady** [comment]
Gerade erneut an dieser Stelle Gamecrash gehabt.

**Comment by DrGrizzlY17** [comment]
In #1143 verschoben
