### ISSUE TITLE
Crash GioV und "Dimensionsfehler"

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1131]
**Character Name**
Max Broady & Lyss Parker

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.02.2021 - 19:52

**Beobachtetes Verhalten**
Gamecrash nähe GioV in richtung Süden.
Nach Login waren Fahrzeuge unsichtbar und nur die Schatten sichtbar.
Beim Einsteigen ist man "weg geportet" worden und anschließend erneut gecrashed.

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=SeJV3alIl-Y

**Comment by its4l3x** [comment]
Ist bereits bekannt. Wir analysieren das Problem seit Tagen bereits. Geben bescheid, wenn Änderungen kommen

**Comment by DrGrizzlY17** [comment]
In #1143 verschoben
