### ISSUE TITLE
Telefon - Anruf bleibt bestehen

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#1132]
**Character Name**
Marvin_Elpe

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.02.2021 - 22:30
05.02.2021 - 23:07

**Beobachtetes Verhalten**
Habe die Nummer der MuR Group angerufen, es ging dort keiner dran weshalb ich auf auflegen geklickt habe. Klingelsound ging weg, telefonat bleibt weiterhin als "aktiv".

**Erwartetes Verhalten**
Telefonat wird beendet

**Comment by its4l3x** [comment]
Möglicher Fix deines Problems wurde gepublished und ist mit dem nächsten Update auf dem Server verfügbar.
