### ISSUE TITLE
Game Crash 3x hintereinander

### ISSUE THREAD

**Issue by masterppc** [mexyn/statev_v2_issues#1133]
![Crash 1](https://user-images.githubusercontent.com/17258618/107105200-5d1a1080-6825-11eb-9528-5e7d90e011fd.jpg)
![Crash 2](https://user-images.githubusercontent.com/17258618/107105202-5e4b3d80-6825-11eb-9afb-38b6527cdf54.jpg)
![Crash 3](https://user-images.githubusercontent.com/17258618/107105203-5e4b3d80-6825-11eb-8702-7bb61652140a.jpg)

01:02 Uhr 01:05 Uhr 01:12 Uhr

Fahrtrichtung aus der Stadt Richtung Westhighway

Crashdumps:
https://drive.google.com/file/d/1HQd6KelYyl4QGe1j5sG8Xn-okn6YkaH4/view?usp=sharing
https://drive.google.com/file/d/16Fj7QsYMBTAstY_F-WBbdKVmU156_ZSX/view?usp=sharing
https://drive.google.com/file/d/1jyn7AQvm_9w70Srv0oOPBBjPWGrPTcDu/view?usp=sharing

**Comment by DrGrizzlY17** [comment]
In #1143 verschoben
