### ISSUE TITLE
Sortierung Outfit-System Fraktionen

### ISSUE THREAD

**Issue by GonzoMenendez** [mexyn/statev_v2_issues#1135]
Gonzo Menendez

Gonzo Menendez (und alle anderen Fraktionsmitglieder)

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit dem letzten Patch Inhalt - 2.0.35 vom 01.02.2021

**Beobachtetes Verhalten**
Seit dem Patch ist das ohnehin falsch Sortierte Kleidungs-system nun komplett durcheinander.
Die Einzige Sortierung welche noch stimmt ist der Rang. Alle anderen Outfits welche erstellt wurden
sind Wirr durcheinander. 
Eine Anordnung nach Rang  -> Name absolut Dienlich um eine Ordentliche Sortierung in Verbindung von z.b. Nummern wie im PD zu ermöglichen

**Erwartetes Verhalten**
Eine Anordnung nach Rang  -> Name absolut Dienlich um eine Ordentliche Sortierung in Verbindung von z.b. Nummern wie im PD zu ermöglichen

**Schritte um den Fehler nachvollziehen zu können**
Hohen PD Rang geben und durch die Kleidung schalten. Normal fängt es mit PBO an und endet mit Chief

**Comment by its4l3x** [comment]
An der Sortierung wurde seit Anfang an nichts mehr gemacht. Ich kann deinen Unmut verstehen.

Ich werde mir das mal anschauen.

Meinst du am Auswähl Punkt und/oder am Erstell-Punkt?

**Comment by CaleighRhodes** [comment]
Im Auswahlmenü beim Umziehen ist es extrem durcheinander. Manche der BCSO-Uniformen sind mitten zwischen den LSPD-Uniformen. Und umgekehrt. Denke, das ist gemeint.

**Comment by its4l3x** [comment]
Alles klar. Habe dies dann nun bearbeitet - Gleiche auch bei der Skin-Erstellung. Ist mit dem nächsten Update drauf

**Comment by GonzoMenendez** [comment]
Awesome, danke! durch Alphabetsoertierung da zählen auch Sonderzeichen und Ziffern?

Unsere Sortierung ist ja zb

[M][600] <NAme>
