### ISSUE TITLE
Gamecrash am Pier beim einsteigen vom Phantom

### ISSUE THREAD

**Issue by PrimroseBloom** [mexyn/statev_v2_issues#1136]
**Character Name**
Primrose Bloom

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.02.21 7:11 

**Beobachtetes Verhalten**
Gamecrash beim einsteigen in einem Phantom

**Erwartetes Verhalten**
Kein Gamescrash dabei

[altv_2.10_Social Club_0x5e98e8_06-02-2021_07-11-52.zip](https://github.com/mexyn/statev_v2_issues/files/5936403/altv_2.10_Social.Club_0x5e98e8_06-02-2021_07-11-52.zip)
[altv_2.10_Social Club_0x5e98e8_06-02-2021_07-14-27.zip](https://github.com/mexyn/statev_v2_issues/files/5936404/altv_2.10_Social.Club_0x5e98e8_06-02-2021_07-14-27.zip)
[altv_2.10_Social Club_0x15cde9a_06-02-2021_07-18-57.zip](https://github.com/mexyn/statev_v2_issues/files/5936405/altv_2.10_Social.Club_0x15cde9a_06-02-2021_07-18-57.zip)
[altv_2.10_Social Club_0x15cde9a_06-02-2021_07-24-56.zip](https://github.com/mexyn/statev_v2_issues/files/5936406/altv_2.10_Social.Club_0x15cde9a_06-02-2021_07-24-56.zip)
[altv_2.10_Social Club_0x62510d_06-02-2021_07-21-34.zip](https://github.com/mexyn/statev_v2_issues/files/5936407/altv_2.10_Social.Club_0x62510d_06-02-2021_07-21-34.zip)

**Comment by DonVitoDiangelo** [comment]
Hast du den immer beim einsteigen in einen Phantom gehabt oder nur 1 mal?

**Comment by DrGrizzlY17** [comment]
In #1143 verschoben
