### ISSUE TITLE
Game Crash zu Fuß

### ISSUE THREAD

**Issue by scortie1337** [mexyn/statev_v2_issues#1137]
**Character Name**
Andrew Pearson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.02.2021 13:38Uhr

**Beobachtetes Verhalten**
Beim telefonieren und hin und herlaufen um mein Auto ist das Game gecrasht.

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/bbd885eeba4c327e8ef3a77929066138

**Comment by DrGrizzlY17** [comment]
In #1143 verschoben
