### ISSUE TITLE
GameCrash Gericht

### ISSUE THREAD

**Issue by No1likeyou** [mexyn/statev_v2_issues#1138]
Ben Stark

Ben Stark
**Auftrittszeitpunkt (Datum / Uhrzeit)**

05.02.2021 in der Zeit von  18.50 bis 19.15 Uhr
**Beobachtetes Verhalten**

Mehrere Spieler hatten starke Voice-Probleme (Marc Randall, Gonzo Menendez, Ben Stark) sowie Game Crashes (Ben Stark)
**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
In #1143 verschoben
