### ISSUE TITLE
Game Crash PLZ 5022

### ISSUE THREAD

**Issue by powerswissi** [mexyn/statev_v2_issues#1139]
**Character Name**

Roger Thickle

**Auftrittszeitpunkt (Datum / Uhrzeit)**

6.2.2021 20Uhr

**Beobachtetes Verhalten**

Game Crash ohne Ankündigung

Ein AMG, Porsche und ein Buritto standen am Parkplatz beim Restaurant. Sonst nichts weiteres in der Umgebung 

**Erwartetes Verhalten**

Kein Crash

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot_817](https://user-images.githubusercontent.com/70152806/107127444-6901e300-68b6-11eb-866a-cd74f680ade1.png)

**Comment by DrGrizzlY17** [comment]
In #1143 verschoben
