### ISSUE TITLE
Rucksack/Tasche - Fehlermeldungen werden falsch angezeigt

### ISSUE THREAD

**Issue by Downgradeeu** [mexyn/statev_v2_issues#114]
**Character Name**
Chris Samonds

**Zeitpunkt (Datum / Uhrzeit)**
27.08.2020

**Beobachtetes Verhalten**
Errors werden  in folgenden Szenarien falsch angezeigt:
1. Rucksack/Tasche anlegen bei bereits angelegtem Rucksack/Tasche.
2. Rucksack/Tasche in Rucksack/Tasche ziehen.

**Erwartetes Verhalten**
Korrektes Anzeigen der Fehlermeldungen

**Schritte um den Fehler nachvollziehen zu können**
1. Bei angelegtem Rucksack versuchen einen anderen Rucksack anzulegen > error.item.slot.full
2. Angelegten Rucksack versuchen in den Rucksack zu ziehen > error.item.move.itself

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
2560x1440

**Optional: Video / Bilder des Fehlers**
![GTA5 2020-08-27 17-13-16](https://user-images.githubusercontent.com/70332260/91461003-c8c87c80-e888-11ea-8d3a-183b365eb6b0.png)
![GTA5 2020-08-27 17-14-01](https://user-images.githubusercontent.com/70332260/91461008-ca924000-e888-11ea-8bff-e83025e064ef.png)

**Comment by tastydev** [comment]
Die Meldungen sind richtig nur noch nicht für Spieler übersetzt.

**Comment by DrGrizzlY17** [comment]
fixed next update
