### ISSUE TITLE
Gamecrash Paleto Bay Sheriff Office/Stoppschild

### ISSUE THREAD

**Issue by CaleighRhodes** [mexyn/statev_v2_issues#1140]
**Character Name**
Caleigh_Rhodes

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.02.2020 / 20:21

**Beobachtetes Verhalten**
Gamecrash bei Fahrt aus dem Nichts heraus ohne vorherige Ruckler, Spiel geht einfach aus.

Fahrt von Procopio Drive 17 Richtung LS über Westhighway. Bei Ausfahrt aus Paleto direkt auf der Stopp-Markierung Höhe Paleto Bay Sheriff Office Gamecrash. Fahrzeug nach Einloggen an der selben Stelle, ich selber spawne (stehend) auf dem Fahrersitz,

**Erwartetes Verhalten**
kein Crash

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug aus Garage (in meinem Fall Hausgarage) ausparken, losfahren.

**Comment by DrGrizzlY17** [comment]
In #1143 verschoben
