### ISSUE TITLE
Ausbau des Hotels - Wohneinheiten

### ISSUE THREAD

**Issue by AdnanT57** [mexyn/statev_v2_issues#1141]
Ich bin der Meinung, dass mein Hotel von der Optik her mehr Zimmer hat, als vorhanden sind.
In einem Hotelzimmer ist 1 Fenster zum rausschauen und nicht gerade viel Platz im Raum.
Ich habe im Anhang Fotos beigefügt bei denen man erkennt, dass das Hotel deutlich mehr als 150 Fenster hat. (Bedeutet nicht das ich so viele Wohneinheiten möchte, die Entscheidung trifft das Team, darüber bin ich mir bewusst.)
Von der Fläche und Höhe her sollten mehr Einheiten als nur 30 Verfügbar sein. 
Ich würde mich freuen, wenn ein Blick drauf geworfen wird und eventuell eine Erweiterung der Einheiten gemacht wird.

Hotel Hash: AkiPillboxHillRew_Flat_4
Adresse: OLS - Resort - San Andreas Ave. 50
Inhaber: Adnan Turkoglu
Antragsteller (Charaktername): Adnan Turkoglu
aktuell verfügbare Einheiten im Hotel: 30

Foto Vorderseite: https://pic.statev.de/image/0lWgY

Foto Seite: https://pic.statev.de/image/0lgrz

Foto Standort: https://pic.statev.de/image/0lK5w

Mit freundlichen Grüßen
Adnan Turkoglu

**Comment by DrGrizzlY17** [comment]
Zimmer auf 45 erhöht
