### ISSUE TITLE
Gamecrash bei GioV

### ISSUE THREAD

**Issue by sGtDeath** [mexyn/statev_v2_issues#1142]
**Character Name**
Frank_Gruber

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.02.2021 23 Uhr

**Beobachtetes Verhalten**
Gamecrash an der Kreuzung 5019 Ecke Sandcastle Way/ Magellan Ave.
In einem Neon unterwegs, Es standen Lowrider in der Hood und einige andere Fahrzeuge auf dem großen Parkplatz bei 5043. Dazu noch ein Schafter und Youga Classic bei GioV

**Erwartetes Verhalten**
Kein Crash

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Comment by DrGrizzlY17** [comment]
In #1143 verschoben
