### ISSUE TITLE
Map Änderung Hotel Vespucci_Flat_16

### ISSUE THREAD

**Issue by JosefRitter** [mexyn/statev_v2_issues#1144]
**Character Name**
Josef_Ritter
**Änderungswünsche**
Ich würde gerne auf der Dachterasse die 3 vorderen Schirme weg haben wenn das möglich ist (Bild: https://pic.statev.de/image/20210207235922-1.0XoGt) und wäre es möglich bei der Wand das letzte Element wegzunehmen das man da ein Eingang zur Dachterasse machen kann (Bild: https://pic.statev.de/image/20210208000054-1.0XRDn) das die Gäaste für die Partys nicht durch die Hood müssen.

Vielen Dank im Voraus .

**Comment by DrGrizzlY17** [comment]
Abgelehnt.

Zu den Schirmen. Sie stören nicht im RP und sehe keinen Grund diese zu entfernen.
Zu der Mauer. Leider ist es nicht Möglich das einzelne Stück zu entfernen. 

Was ich anbieten kann, ist den Teleportpunkt aufs Dach auf die andere Seite des Gebäudes zu setzen.

**Comment by JosefRitter** [comment]
Das Problem bei den Schirmen ist das man schnell war auf den Schirm hochklettert und da sie sehr nah am Geländer stehen man schnell runterfällt. Und sie stören schon im RP da sie die Sicht behindern. 

Das Angebot zum verlegen des Teleports nehme ich gerne an. Wäre super wenn er zum Haupteingang gelegt werden könnte.

**Comment by DrGrizzlY17** [comment]
Habe den Teleporter auf die andere Seite versetzt. Am Haupteingang war dafür kein Platz.

Das Entfernen der Schirme wird weiterhin abgelehnt.
