### ISSUE TITLE
Progressbalken weg

### ISSUE THREAD

**Issue by infinityrueffel** [mexyn/statev_v2_issues#1145]
**Max_Sternberg**

**08.02.2021 10:30**

**Wenn man eine Produktion in der Gießerei startet hat man wenn man wieder an einem Abaupunkt arbeitet keinen Progressbalken**

**Funktionierender Progressbalken**

**Produktion Starten - Zum Feld fahren und arbeiten**

**4k**

**Comment by Statev-Bonsai** [comment]
Das betrifft alle Produktionsfirmen, sobald man einmal an die Maschinensteuerung geht ist der Progressbalken verbugt, man kann nur wieder den Normalzustand herstellen wenn man reloggt..

**Comment by Stiefel911** [comment]
> Das betrifft alle Produktionsfirmen, sobald man einmal an die Maschinensteuerung geht ist der Progressbalken verbugt, man kann nur wieder den Normalzustand herstellen wenn man reloggt..

sehe das Problem ist schon länger, mir ist es erst seid ca 7 Tage aufgefallen, wenn Produktion aber fertig und man geht an die Maschine, kommt aus dem nichts der Balken und bleibt fest bei 100 dann stehen.

**Comment by JulianMa** [comment]
Dublicate von #1404
