### ISSUE TITLE
LSMJ StateCOM Aktenzugriff

### ISSUE THREAD

**Issue by milkdrops** [mexyn/statev_v2_issues#1146]
Bradley_Yu

Seit Dez. 2018

Das LSMJ hat keinen Aktenzugriff im StateCOM

Justizbeamte sollten Aktenzugriff erhalten, damit Akten nicht mehrmals geschrieben und weitergeschickt werden müssen per Googledocs.
Dies würde den Spielern dazu verhelfen, den Großteil der Googledocs der Detectives ( und evtl. des LSMJ) zu entfernen und mehr Zeit im RP zu verbringen.

1. Eingestellt sein im LSMJ
2. Einloggen im LSMJ StateCOM
3. Nur eine sehr abgespeckte Form des StateCOMs ist verfügbar, darunter keine Akten.

**Comment by its4l3x** [comment]
Hi,

wenn das noch nicht mit Shanel und/oder Spoon abgeklärt ist, klär das bitte ab und schreib mir ggf. auf Discord. 🗡️ 

Alex
