### ISSUE TITLE
Gamecrash beim Fahren. 

### ISSUE THREAD

**Issue by rubbaduck-twitch** [mexyn/statev_v2_issues#1147]
**Character Name**
Raymond_Brooks

**Auftrittszeitpunkt**
08.02.2021 / 17:20

**Beobachtetes Verhalten**
Gamecrash ohne Fehlermeldung beim Fahren

**Erwartetes Verhalten**
Nicht Crashen

**Schritte um den Fehler nachvollziehen zu können**
Bin gefahren. War schnell. Instant Crash
Fahrtrichtung Westen
ca. 235kmh
Motorrad: Hakuchou

**Optional: Video / Bilder des Fehlers**
![Grand Theft Auto V - Spielaufzeichnung_2021-02-08_17-21-41](https://user-images.githubusercontent.com/75338532/107248815-fc602300-6a32-11eb-91ca-ee201b4c6faf.jpg)
![Grand Theft Auto V - Spielaufzeichnung_2021-02-08_17-21-46](https://user-images.githubusercontent.com/75338532/107248819-fcf8b980-6a32-11eb-8e75-6f86845a2f77.jpg)

**Comment by DrGrizzlY17** [comment]
In #1143 verschoben
