### ISSUE TITLE
Platz in Tasche

### ISSUE THREAD

**Issue by VictorCorticera** [mexyn/statev_v2_issues#1148]
Gustavo Luciano

08.02.2021 19:30

Die graue Dufflebag kann beispielsweise bis zu einem Gewicht von 29,50 kg oder 29,90 kg gefüllt werden, aber nicht die vollen 30 kg. Nur mit dieser Tasche getestet.

Die graue Dufflebag sollte logischerweise Materialen bis zu 30 kg aufnehmen können.

Graue Dufflebag mit Materialien füllen. Beispielsweise 59 Kautschuk. Dann befinden sich in der Tasche 29,50 kg und es kann kein weiteres Kautschuk hinzugefügt werden.

**Comment by DonVitoDiangelo** [comment]
Das kommt durch eine Berechnung zustande, welche nach Addition der Gewichte z.B. die Nachkommastelle 30.0065494 hat und damit über dem Limit der 30 liegt. Da nimmst du dann eines weniger mit. Wir wollen ja nicht, dass die Tasche platzt. ;)
keine Prio.
