### ISSUE TITLE
Telefon Bug bzw fehlendes Icon

### ISSUE THREAD

**Issue by lpmitalex** [mexyn/statev_v2_issues#115]
**Character Name**
Manfred Vogel

**Zeitpunkt (Datum / Uhrzeit)**
17.08.2020 17:45 Uhr

**Beobachtetes Verhalten**
Wenn man auf den Kontakten schaut ( also da wo man auch die nummern bearbeiten kann) sieht man kein Nachrichten Icon mehr

**Erwartetes Verhalten**
Icon für Sms neben dem Anruf Icon

**Schritte um den Fehler nachvollziehen zu können**
Telefon öffnen
auf ein kontakt gehen
Icons anschauen

![alt_V Multiplayer 27 08 2020 17_47_49](https://user-images.githubusercontent.com/70335662/91464949-72aa0800-e88d-11ea-965f-b89069a7d8ed.png)

**Comment by DrGrizzlY17** [comment]
Wie man vielleicht bereits bemerkt hat, existiert vorerst kein Messenger mehr im Handy.
Somit kein SMS Button notwendig.
