### ISSUE TITLE
Kann mein Hotel eine Hotelgarage bekommen? 

### ISSUE THREAD

**Issue by Schnarch** [mexyn/statev_v2_issues#1150]
Thomas Schnarch

Schönen Guten Tag,
mein Hotel hat 45 Zimmer.
Ich habe 2 Garagen am Hotel, kann ich dazu eine Hauseigene Garage bekommen? 

Anbei ein paar Bilder, wo man es möglich machen könnte, wie bei einem Haus. 
Entweder Bild 1 oder am besten Bild 2 
Eingang https://pic.statev.de/image/adresse.p95v2
Bild 1 https://pic.statev.de/i/0kFnV.th.jpg
Bild 2 https://pic.statev.de/i/0kiQg.jpg

Vielen Dank und beste Grüße

**Comment by TheBroady** [comment]
Wurde bereits abgelehnt: https://github.com/mexyn/statev_v2_issues/issues/767

**Comment by CaleighRhodes** [comment]
Gekauft wie gesehen....?! ;)

**Comment by Schnarch** [comment]
Naja geht ja nur darum, dass es entspannter für alle wird. Bzgl. der Fahrzeug geschichten. Von mir aus, können auch alle draußen stehen. Ist ja theoretisch kenie großer aufwand. Große villen haben ja auch 6 Plätze. :) 
Habe es nur gut gemeint. :)

**Comment by DrGrizzlY17** [comment]
Ist leider nicht möglich
