### ISSUE TITLE
Dispatch System LSPD, kein Ton

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1152]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
09.02 10:35

**Beobachtetes Verhalten**
Ich stand direkt neben dem LST Punkt im Ditspatch Raum, es war jedoch trotz eines eingegangenen Notrufs rein Ton zu hören, der dies signalisiert

**Erwartetes Verhalten**

Es sollte, ein im Umkreis des Punktes vernehmbarer Ton zu hören sein.

**Schritte um den Fehler nachvollziehen zu können**
Neben Dispatch Punkt stehen --> Notruf wird angerufen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
alrdy fixed. :D Wollte das euch noch in die fraktions channel schreiben.
