### ISSUE TITLE
LSPD, Bank interagierbar machen, 

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1153]
**Character Name**
Jannik_Datsh

**Auftrittszeitpunkt (Datum / Uhrzeit)**
09.02 11:00

**Beobachtetes Verhalten**
Bank nicht mit "Y" interagierbar 

**Erwartetes Verhalten**
Über Y interagierbar

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://pic.statev.de/image/0oVYJ

**Comment by DrGrizzlY17** [comment]
Leider technisch nicht umsetzbar
