### ISSUE TITLE
Xenon Lichter verschwinden aus Lager

### ISSUE THREAD

**Issue by VictorCorticera** [mexyn/statev_v2_issues#1154]
Lautaro Testo, Dean Flunscher

09.02.2021 - 22-23 Uhr

Tuning Xenon Lichter wird angeschaut, dann aber nicht bezahlt sondern wieder abgebrochen. Xenon Lichter bleiben auf Fahrzeug temporär bis Serverneustart oder das Fahrzeug eingeparkt wird. 2x Xenon Lichter verschwinden dann aus dem Lager.
Problem ist am genannten Datum 2x aufgetreten. Dementsprechend fehlen 4 Xenon Lichter. 
Es wurde bereits ein ähnlicher Bug Tracker dazu erstellt, dachte auch, dieses Problem wird da mit reingeschrieben. Insgesamt sind nun schon mindestens 10 Xenon Lichter verschwunden.

Sollten logischerweise im Lager bleiben, wenn diese nicht berechnet oder verbaut wurden.

Tuning starten (mit anderer Person), Xenon Lichter ansehen, Vorgang abbrechen (Menü schließen), Xenon Lichter bleiben an Fahrzeug dran, Xenon Lichter fehlen im Lager

**Comment by VictorCorticera** [comment]
https://github.com/mexyn/statev_v2_issues/issues/986

Wurde hier übrigens auch bereits gemeldet.

**Comment by its4l3x** [comment]
Topi, dann schließe ich das weil duplicate
