### ISSUE TITLE
Strafzahlung Export fehlerhaft

### ISSUE THREAD

**Issue by VerenaBelters** [mexyn/statev_v2_issues#1155]
**Verena Belters**
Verena Belters

**Auftrittszeitpunkt (Datum / Uhrzeit)**

09.02.2021 13:00 Uhr

**Beobachtetes Verhalten**

Export Auftrag wurde nicht abgegeben ( Wert 300 Dollar) -> Strafzahlung beträgt aber 395.20 Dollar

**Erwartetes Verhalten**
 80% vom Wert

**Optional: Video / Bilder des Fehlers**

![Export](https://user-images.githubusercontent.com/75080037/107365171-b8c1f380-6adc-11eb-8489-3b84ad57e7d1.JPG)
![Konto Nano Labs II](https://user-images.githubusercontent.com/75080037/107365173-b95a8a00-6adc-11eb-972d-98c4f804135f.JPG)

**Comment by sempre88** [comment]
80% vom Starpreis des Auftrags, sonst könnte man ja alles auf 0 bieten und würde keine Strafe bezahlen. Da Schwefel ca. 5$/stk bringt bist bei 100 Sack bei ca 400$ Strafzahlung.

**Comment by Statev-Bonsai** [comment]
Richtig, das passt so...

**Comment by VerenaBelters** [comment]
Okay.. Ist mir nie aufgefallen und wusste ic auch keiner :D
