### ISSUE TITLE
Menüs bei 2k Auflösung verschwommen

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#1156]
**Character Name**
Marvin_Elpe

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit 08.02.2021

**Beobachtetes Verhalten**
Einige Menüs sind in 2k seit gestern etwas verpixelt/verschwommen. Habe auch die Monitore mal gewechselt, Problem bleibt weiterhin.

**Erwartetes Verhalten**
Menüs sind scharf.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
2k Auflösung

**Optional: Video / Bilder des Fehlers**
https://i.imgur.com/AMOuBJW.jpg

**Comment by M4rvinLP** [comment]
Das ging fix xD

**Comment by KingMarcel** [comment]
Wir haben das Problem bereits gestern entdeckt und auch direkt behoben ;) Danke trotzdem für die Meldung.
