### ISSUE TITLE
"Yelp" Signal, bei Motor / Auf- Absperren 

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1157]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
07.02 16:30

**Beobachtetes Verhalten**
siehe Video, das war dann nach gewisser Zeit wieder weg, ist mir nicht das erste mal aufgefallen, scheint ab und zu mal kurzzeitig vorzukommen

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/kkbxZLRmFmw

**Comment by its4l3x** [comment]
ehm. wtf?

Das ist ja mal super strange. Drückst du noch irgend eine Taste außer X?

**Comment by JannikDatsch** [comment]
ne, hab ich nicht xD, das ist mir, wie gesagt, abundzu auch mal aufgefallen, wo ich mich gewundert habe, warum jetzt der Yelp kam, beim Motor anschalten. Außerdem hätte es dann bei den anderen Fkt. wie Kofferraum usw. auch kommen müssen.

**Comment by its4l3x** [comment]
Okay sehr sehr strange. Kann das noch jemand bestätigen? Habe das vorhin auf unserem DEV Server gestet - Konnte das nicht reproduzieren

**Comment by JannikDatsch** [comment]
Wie beschrieben tritt das, zumindest bei mir, nur äußerst selten auf, und fällt kaum auf (bsp. beim Motor anschalten, weil es nach kurzer Zeit wieder weg ist.)  und ist daher nicht wirklich relevant. Aber ich habs halt trotzdem mal gemeldet, weils ja trotzdem ein Bug ist. Ich schau auch mal, ob ich bei Wiederauftreten an irgendwas vorangegangenen festmachen kann, woran es liegt.

**Comment by DonVitoDiangelo** [comment]
Keine Relevanz und wird nicht weiter geprüft. Gibt wichtigeres. :)
