### ISSUE TITLE
Kopfschmerzen im Gericht

### ISSUE THREAD

**Issue by No1likeyou** [mexyn/statev_v2_issues#1158]
**Character Name**
Ben Stark

**Auftrittszeitpunkt (Datum / Uhrzeit)**
09.02.2021 um 19:02 Uhr

**Beobachtetes Verhalten**
Gamecrash

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Chrinis007** [comment]
#1143

**Comment by DrGrizzlY17** [comment]
Übertragen
