### ISSUE TITLE
Massive Kopfschmerzen & Verladepunkt

### ISSUE THREAD

**Issue by Knippsa** [mexyn/statev_v2_issues#1159]
**Kalle Knutsen**

**Rund um die Uhr**

**2 Themen: Beim Firmenhash pfWestVine21 wurde der Verladepunkt auf den Parkplatz gesetzt allerdings eigentlich etwas zu weit weg vom Terminal. Wäre super den noch weiter an den Lagereingang zu setzen. Außerdem ist der irgendwie ziemlich hoch. k.A. ob der sich immer auf Ebene des Terminalpunktes setzt aber ggf. kann man den ja runtersetzen. Foto: https://pic.statev.de/image/0RBPy    ///////////  Als 2. Muss ich melden, dass rund um die Firma extreme Probleme auftreten. Fast jeder der bisher da war kriegt sofort einen Crash und kommt dann teilweise erst beim x-ten Mal wieder ohne Probleme rauf. Auch beim eintreten in das Lager hat man alle paar Male einen Crash. Beide Probleme wurden nun schon von sehr vielen Spielern beobachtet.**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Chrinis007** [comment]
#1143

Da rein

**Comment by DrGrizzlY17** [comment]
Whupsala. Da hab ich die Höhe nicht angepasst

**Comment by Knippsa** [comment]
Kein Problem @DrGrizzlY17 
Wie gesagt, es wäre auch schön, wenn der n guten Meter weiter Richtung Terminal kommt. FOlgend ein Foto. Auf dem Boden ist auch so eine dunkle Stelle. Da wäre das perfekt: https://pic.statev.de/image/0sxCn

**Comment by DrGrizzlY17** [comment]
Alles klar
