### ISSUE TITLE
In Revivepunkt gezogen danach konnte ich mich nicht mehr bewegen

### ISSUE THREAD

**Issue by MarkHarland** [mexyn/statev_v2_issues#116]
Bitte die Vorlage unten vollständig ausfüllen

Mit welchem Character wurde das Verhalten in-game ausgelöst/beobachtet
**Mark_Harland**

**Zeitpunkt (Datum / Uhrzeit)**
27.08.2020  17:40

**Beobachtetes Verhalten**
Wir wollten am WP den Sync beim schlagen testen danach hat Stormy_Valley mit in den Revivepunkt gezogen als ich meine Brille wieder aufsetzen wollte konnte ich mich nicht mehr bewegen (versucht um mich wieder bewegen zu können: Handy,Inventar,Handel,Animation,Waffen)

**Erwartetes Verhalten**
Das ich die Brille wieder auf hab und mich bewegen kann

**Schritte um den Fehler nachvollziehen zu können**
 In Revive gezogen>danach Kleidermenü geöffnet und keine bewegung mehr gehabt 

**Optional: Video / Bilder des Fehlers**
https://youtu.be/SZfMLVo25mA

 -->

**Comment by tastydev** [comment]
Revivepunkt ist nur für die Beta um nicht verdursten zu müssen etc.
