### ISSUE TITLE
Bootswerkstatt Nordosten - Anpassungswünsche

### ISSUE THREAD

**Issue by Montifero** [mexyn/statev_v2_issues#1160]
**Character Name**
Rene_Ballista

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Permanent

**Beobachtetes Verhalten**

1. Arbeitsboje ist RP-technisch eher suboptimal positioniert
2. Werkstattbeleuchtung nicht vorhanden
3. Holzboot in Werkstatt schränkt den Durchgang/Zugang zur Slipstelle ein

**Erwartetes Verhalten**

1. Versetzen der Arbeitsboje an den kleinen, nach unten versetzten Steg
2. Anbringung von Leuchtmitteln in der Werkstatt
3. Holzboot entfernen, versetzen oder durch kleineres ersetzen

**Schritte um den Fehler nachvollziehen zu können**
Siehe Fotos 

**Optional: Video / Bilder des Fehlers**

1. Arbeitsboje - aktuelle & gewünschte Position -> https://photos.app.goo.gl/pQDBBPZTAf2XDMZT6
2. Werkstattbeleuchtung aktuell -> https://photos.app.goo.gl/adu4fTwMmaGLpwxaA
3. Holzboot in Werkstatt ->https://photos.app.goo.gl/adu4fTwMmaGLpwxaA

**Comment by Montifero** [comment]
Hallo, ich weiß ihr habt sehr viel um die Ohren, aber wollte nur kurz nachfragen ob die Änderungenwünsche möglich sind bzw. gewährt werden, da für Samstag die Eröffnung geplant ist.

Danke, schöne Grüße

**Comment by DonVitoDiangelo** [comment]
Ja, werden wir was machen:
1.  wird versetzt
2.  müsst Ihr selbst setzen
3.  wird entfernt

**Comment by Montifero** [comment]
Alles klar, danke.

Nur kurz fürs Verständnis, ist Punkt 2 technisch nicht realisierbar?

Geht mir nur darum daß ich meinen Kunden auch Sitzgelegenheiten, Schattenspender ect. bieten möchte, da dies für mich zu gutem Kundenservice zählt und wenn ich die Werkstattbeleuchtung selbst setzen muss, sind meine Möglichkeiten zur Schaffung eines entspannten maritimen Ambiente halt leider begrenzt.

Vielleicht wird ja eurer Seitens nochmal darüber beraten.

Danke, schöne Grüße

**Comment by DonVitoDiangelo** [comment]
Realisierbar schon, werden wir aber nicht extra dafür machen. Dafür habt Ihr das System zum setzen von Gegenständen und 1 oder 2 Slots für ein Licht, sind absolut vertretbar.
