### ISSUE TITLE
Mehrere Bandagen(/Medkits?) einsetzbar

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1162]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit V2 / 10.02 16:15

**Beobachtetes Verhalten**

Seit V2 gibt es den (sinnvollen) Cooldown fürs Einsetzen von Healing (Bandagen u. Medkits)
Normalerweise kann man immer nur eins einsetzen und muss dann eine gewisse Zeit warten.

Das Einsetzen zumindest lässt sich umgehen, wenn man mehrere "spammt" während der Healing Animation. 
( Bandage mehrmals probiert, fraglich ob das auch bei Medkits zutrifft, lässt sich auf dem Live-Server schwer ausprobieren)

Fraglich ist insbesondere, ob diese, während der Animation eingesetzten Bandagen (Medkits?) eine Wirkung haben. Ich glaube ich hatte das mal probiert bei Bandagen, und sie hatten eine, aber das dürfte sich ja auf dem Dev-Server schnell und einfacher rausfinden lassen.

**Erwartetes Verhalten**

Man sollte nach dem Einsetzen eines Healings keine anderen mehr einsetzen können, auch nicht während der Animation.

**Schritte um den Fehler nachvollziehen zu können**
siehe Video

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/j1LKwb_Fxq4

**Comment by its4l3x** [comment]
Danke fürs Reporten. Zählt 100% zur Kategorie Bugabuse. Wenn du User hast, wo du weißt, dass sie das absichtlich nutzen bitte melde dies unverzüglich im Support.

**Comment by JannikDatsch** [comment]
Hat es was gebracht danach noch andere einzusetzen? Oder waren die dann nur sinnlos verbraucht?

**Comment by its4l3x** [comment]
Siehe edited nachricht oben.
