### ISSUE TITLE
Pounder wird auf Seite ausgeparkt

### ISSUE THREAD

**Issue by JonnyHart** [mexyn/statev_v2_issues#1163]
**Character Name**
Jonny Hart

**Auftrittszeitpunkt (Datum / Uhrzeit)**
09.02.2021 ca. 23:00 Uhr

**Beobachtetes Verhalten**
Nach ausparken eines Pounders aus dem Autohaus in Vinewood liegt dieser auf der Seite und ist kaputt (rote Motorkontrolleuchte). Das passiert nur ab und zu, aber nicht immer.

**Schritte um den Fehler nachvollziehen zu können**
Pounder aus Autohaus ausparken
![GTA5 2021-02-09 23-05-04](https://user-images.githubusercontent.com/78865364/107531662-5c82d080-6bbd-11eb-88f9-2c6570c0b2a0.png)

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Ich hab den Punkt etwas näher zu Straße geparkt. Nur ist es jetzt so das man mit den meisten Fahrzeugen direkt mit der Motorhaube auf der Straße steht. Sollte es deswegen zu Unfällen kommen, eröffnet dann am besten einen neuen Beitrag und wir suchen nach anderen Optionen

**Comment by JonnyHart** [comment]
Top. Danke für die schnelle Hilfe. <3
