### ISSUE TITLE
Bündel Zuckerrohr im Verkaufsterminal nicht sichtbar

### ISSUE THREAD

**Issue by Knippsa** [mexyn/statev_v2_issues#1164]
**Kalle Knutsen**

**Generell**

**Wenn man Bündel Zuckerrohr in den Verkauf einpflegt sieht man es anschliessend nicht. Sowohl am Computer im Innenraum, als auch draussen am Terminal. Ein Verkauf ist daher nicht möglich. Wenn man versucht den Artikel noch einmal einzutragen kriegt man natürlich die Nachricht, dass das Produkte bereits existiert. Löschen allerdings nicht möglich, da eben nicht sichtbar.**

**Erwartetes Verhalten**

**Artikel einpflegen. Am besten einmal raus/rein und Kassensystem erneut öffnen**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Knippsa** [comment]
> 
> 
> Von welchem Verkaufsterminal ist die Rede?


Firmenhash: pfWestVine21
Verkaufstermina = Eingangssymbol wo man auch ankauft/verkauft/lagert

**Comment by Knippsa** [comment]
Irgendwelche Updates? 
Die Leute fragen schon alle, warum der Artikel nicht in der Verkaufsliste ist.

**Comment by DonVitoDiangelo** [comment]
![1](https://user-images.githubusercontent.com/70151087/109623187-293cbd00-7b3d-11eb-8338-489bee12caab.jpg)
Also konnte problemlos hinzugefügt werden.

Es wird im UI schlicht gar nicht angezeigt oder fehlen nur die Informationen? Also ob sozusagen nur ein Platzhalter zu sehen wäre.

**Comment by DonVitoDiangelo** [comment]
@Knippsa

**Comment by Knippsa** [comment]
@DonVitoDiangelo Seit dem letzten großen Update (Insel) ist es nun in der Preisliste richtig aufgetaucht. Danke :)
