### ISSUE TITLE
Sturz beim Sparnen auf dem Carsino Dach

### ISSUE THREAD

**Issue by glb11** [mexyn/statev_v2_issues#1165]
Jens_Summer

10.02.2021 ca 23 Uhr

**Beobachtetes Verhalten**

Fehlerhaftes Sparnen auf dem Carsino Dach nach den Update mann stürtzt ab und wird dann bei laden der Position bewusstlos 
1x neben Garage Grabseed hinter der Halle
2x an der NSA Base passiert 
jeweils im Support gemeldet und abgeklärt

War Heute das Erstmal zeit dem GTA Update online (Lade mit dem Altv-Launcher) 

**Erwartetes Verhalten**

Korrektes Laden des Charakters ohne Bewusstlosigkeit

**Schritte um den Fehler nachvollziehen zu können**

War nach den Update so ohne das ich sonst was verändert habe.

**Optional: Video / Bilder des Fehlers**
Grabseed: https://youtu.be/Vvo1QMlH6o4 (mann sieht es bei ca 0:02)
2x NSA (nur ein Video (2. Verfügbar)):  https://youtu.be/84EOJgNDky4 (mann sieht es bei ca 0:08)

**Comment by DonVitoDiangelo** [comment]
System Issue: Bitte teile uns mal deine PC Specs mit, mit welcher Auflösung du spielst und welche Einstellungen du bei GTA aktiv hast. Ich nehme hier stark an, das eine HDD vorliegt bzw. die Festplatte eine Macke hat. Hier können wir wohl nichts weiter machen außer, dass du deine Einstellungen runter drehst.

**Comment by glb11** [comment]
Update:

Wahrscheinlich hat Steam beim Update die Dateien zerstört, musste nach dem Fehlerüberprüfen ca 38 GB neu Laden.

- Kleidung hat nicht ganz funktioniert (hatte aber gedacht das kommt vom deaktivieren der moodded Sachen)

---> nach dem Reparieren  der Datei ist wieder alles ok und Login funktioniert wieder top
