### ISSUE TITLE
Chrash 

### ISSUE THREAD

**Issue by Tobias1496** [mexyn/statev_v2_issues#1166]
[
**Tobias Meier**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Tobias1496** [comment]
https://pic.statev.de/image/0vCOB

**Comment by Tobias1496** [comment]
irgendwas hat da anscheinden nicht funktionier aber 11.2.21/10:30 Kein Modded Fahrzeug gesehen

**Comment by its4l3x** [comment]
Hi Tobi,

Modded Fahrzeuge sind seit gestern Abend komplett ausgeschalten. Hast du noch irgendwas anders gesehen?

Bitte Dokumentiere aber trotzaller dessen das Ticket hier runter nochmal:

#1143 


A

**Comment by DrGrizzlY17** [comment]
In #1143 übertragen
