### ISSUE TITLE
Gamecrash

### ISSUE THREAD

**Issue by EmmaSvensson** [mexyn/statev_v2_issues#1167]
Auf dem Weg zur Ostmine, alleine und ohne irgendein Auto in sichtbarer nähe, bekam ich ein Timeout und flog aus dem Spiel.
Zum Nachteil meines Kamachos der dann beschloss in einen Strommast zu fahren ;)

**Comment by its4l3x** [comment]
Bitte wichtig unterscheiden:

Timeout oder Crash? 

Timeout ist meistens wenn du aus dem Spiel rausfliegst und bei altV im Menü die Meldung Timeout bekommst.

Gamecrash ist wenn sich dein Game aufhängt und sich auf einmal schließt.


Bitte genau mitteilen was genau.

**Comment by EmmaSvensson** [comment]
Es war ein Timeout, aber jetzt grade auch noch ein Gamecrash an der Kreuzung vom Casino

**Comment by its4l3x** [comment]
Okay,

ein Timeout passiert meistens durch eure Seite, z.B. Hoher Paketlos (Durch Download, kurz Verbindunge weg, etc..) liegt sehr sehr selten an uns..

Bitte unter den folgenden Thread den Gamecrash genau Dokumentieren:

#1143
