### ISSUE TITLE
Kein Export mit Auflieger möglich

### ISSUE THREAD

**Issue by SternChef** [mexyn/statev_v2_issues#1168]
**Character Name**
Stella_Sanchez

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11.02.2021 Um 12:20 Uhr

**Beobachtetes Verhalten**
Abgabe eines Export-Auftrages an beiden Export-Punkten mit Auflieger nicht möglich.
Fehlermeldung siehe Bild unten.
Wiederholtes hin und her fahren ohne Erfolg.

**Erwartetes Verhalten**
Anfahrt des Export-Punktes mit dem Auflieger und erfolgreiche Abgabe des Auftrages

**Schritte um den Fehler nachvollziehen zu können**
Erneutes anfahren der Export-Punkte mit Auflieger.

**Optional: Video / Bilder des Fehlers**
![Screenshot_285](https://user-images.githubusercontent.com/74982338/107632136-6280bc00-6c66-11eb-9547-c20426472830.png)

**Comment by DrGrizzlY17** [comment]
War der Auflieger aufgeschlossen und nicht die Zugmaschine?
Stand der Auflieger auf dem Abgabepunkt und nicht die Zugmaschine?
Könntest du bitte mal ein Bild dazu posten wie du auf dem Marker geparkt hast?

**Comment by glb11** [comment]
Top einmal die Achse komplett schließen (Kofferraum + Kupplung) zum Typen hin gehen einmal die Meldungen abholen und dann alles wieder aufschließen und dann wieder hin gehen und den Export abgeben können. (habe auch schon paar min daran gesessen bis ich es diesen workarrount gefunden habe)

**Comment by SternChef** [comment]
@DrGrizzlY17  Der Auflieger-Kupplung war geöffnet. Kofferraum war auch offen. Siehe Bild 1-4. Dann habe ich das so probiert wie gbl11 das geschgrieben hatte und musste bis zur letzten Achse auf den Ladepunkte damit der Auftrag abgegeben wurde (Siehe Bild 5)
Bild 1-4
![Screenshot_286](https://user-images.githubusercontent.com/74982338/107636184-9068ff00-6c6c-11eb-900e-3e6ce976d991.png)
![Screenshot_287](https://user-images.githubusercontent.com/74982338/107636208-9828a380-6c6c-11eb-8420-9e9ccac8b39c.png)
![Screenshot_288](https://user-images.githubusercontent.com/74982338/107636255-a7a7ec80-6c6c-11eb-9633-17d3bd1e3559.png)
![Screenshot_290](https://user-images.githubusercontent.com/74982338/107636285-b4c4db80-6c6c-11eb-9124-cca7ea06e3b2.png)

Bild 5
![Screenshot_291](https://user-images.githubusercontent.com/74982338/107636328-c1e1ca80-6c6c-11eb-9a25-4532a6e1eba5.png)

**Comment by Statev-Bonsai** [comment]
Das Problem ist nicht die Achse, der Punkt erkennt auch die Zugmaschine vorne dran... Achse abkuppeln und Zugmaschine etwas wegfahren sollte das Problem beheben, dafür spricht auch das du ziemlich weit mit der Zugmaschine vor gefahren bist und dann erst abgeben konntest!
Denn so wurden nicht 2 Fahrzeuge erkannt..

**Comment by SternChef** [comment]
@Statev-Bonsai  Sorry, aber das Problem bestand auch bei abgekoppelter Zugmaschine an beiden Export-Punkten.

**Comment by glb11** [comment]
Ich habe mein Tipp auch auf die abgekoppelte Achse gemeint (weil das ist für mich schon Standart ist)

**Comment by DylanDuncan** [comment]
#996 

war mir auch ziemlich sicher, dass ich alles richtig gemacht habe aber hat irgendwie nicht funktioniert.
hatte dann mit tasty geschrieben, er hats getestet und meinte alles würde funktionieren und mir den screen mitgeschickt:
https://gyazo.com/952cf1b3fab2495c46415d042a17e43b
seitdem stelle ich die Achse etwas anders hin und habe keine probleme mehr
