### ISSUE TITLE
Messer nutzt sich nicht ab

### ISSUE THREAD

**Issue by JonnyHart** [mexyn/statev_v2_issues#1169]
**Character Name**
Jonny Hart

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11.02.21 12:00

**Beobachtetes Verhalten**
Messer nutzt sich nciht ab

**Erwartetes Verhalten**
Messer sollte sich abnutzen

**Schritte um den Fehler nachvollziehen zu können**
Weintrauben farmen xD

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Michi993** [comment]
beim weintrauben sammeln braucht man kein messer, hat man noch nie, die werden gepflückt, so wie bei orangen

**Comment by JonnyHart** [comment]
ok, wusste ich nicht. Hab noch keine Orangen gemacht. Danke
