### ISSUE TITLE
Kleidungsmenü beim Leute ziehen

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#117]
**Character Name**

Erwin_Dulach

**Zeitpunkt (Datum / Uhrzeit)**

27.08 18:00
**Beobachtetes Verhalten**

Wenn man Bewusstlose Zieht und ins Kleidunsmenü gehen möchte, kommt die Meldung "Du kannst nicht ins Kleidungsmenü gehen wenn du gezogen wirst" - trotzdem kommt der Mauszeiger, welchen man durch nochmal "," drücken weg machen kann, nicht durch "n" drücken.
**Erwartetes Verhalten**

Entweder öffnet sich das Kleidungsmenü + Mauszeiger oder es passiert gar nix. Außerdem müsste die Fehlermeldung "Du kannst nicht ins Kleidungsmenü gehen wärend du jemanden ziehst" heißen.

**Schritte um den Fehler nachvollziehen zu können**

Jemanden umhauen -> per X Menü ziehen -> "," drücken

**Comment by r3sist3nt** [comment]
nach restart fixed.
