### ISSUE TITLE
Gamecrash 

### ISSUE THREAD

**Issue by EmmaSvensson** [mexyn/statev_v2_issues#1170]
Character Name
Emma_Svensson

Auftrittszeitpunkt (Datum / Uhrzeit)
11.2.21. gegen 11:15

In welcher Region ist der GameCrash aufgetreten? (Screenshot oder PLZ von der Map)
An der Kreuzung direkt neben dem Casino, ich habe grade dort an der ampel gehalten

Welche Fahrtrichtung wurde gefahren?
Süden

Fahrzeuge in der Nähe gesehen? Wenn ja, welche?
Es waren keine Fahrzeuge in Sichtbarer nähe

Optional: Crashdump (im altV Ordner hinterlegt)
Bin unterwegs, daher nein

**Comment by DrGrizzlY17** [comment]
In #1143 übertragen
