### ISSUE TITLE
Unsichtbarer Gegenstand - ZIP 7028 Nord

### ISSUE THREAD

**Issue by Knippsa** [mexyn/statev_v2_issues#1172]
**Kalle Knutsen**

**Permanent**

**Wer bremst verliert - Zumindest wenn man auf dem Eclipse Blvd. Richtung Osten bei ZIP 7028 rechts ran fährt. Dort steht irgendwas unsichtbares auf dem grauen Fundament. Position: https://pic.statev.de/image/0iweI  /// Video: https://www.youtube.com/watch?v=3NSI0vqLDrs**

**Kein Bumm**

**Um weitere Schäden zu vermeiden, empfehle ich es nicht auszuprobieren und nur das Video zu sehen ;)**

**Optional: Position: https://pic.statev.de/image/0iweI  /// Video: https://www.youtube.com/watch?v=3NSI0vqLDrs**

**Comment by Statev-Bonsai** [comment]
Da vor der Firma wurde vom Gamedesign Team damals ein Baum entfernt, das ist die Hitbox vom Baum die über geblieben ist :D

**Comment by DrGrizzlY17** [comment]
Ich werde den Baum mal wieder hinzufügen :D
