### ISSUE TITLE
Antrag:Anpassungswünsche - Beim  Unternehmen Hashen: petrolstation11

### ISSUE THREAD

**Issue by Xymena** [mexyn/statev_v2_issues#1173]
**Character Name**
Anna_Luna

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Permanent

**Beobachtetes Verhalten**

Tankstelle an Innocence Blvd./Alta Street 841 (4003) ist schwer zu betreiben wegen mangelnden Geldautomaten und andere RP Objekte. 
Erwartetes Verhalten, Aufstellen eines Geldautomaten und optional eines Müllcontainer.

**Gründe:**
Die Tankstelle, so wie sie jetzt ist sehr schwer zum Betreiben und müsste in der jetzigen Form Wirtschaft und RP unverträglich betrieben werden.
In etwa ein Fahrtradius von 400 Meter befinden sich mehre weitere Tankstellen, die in unmittelbarer Nähe oder direkt auf dem Gelände ein Geld Automaten haben. 
So befindet der nächste Geldautomat bei 40118 und 401,2, wobei der 4012 schwer zu erkennen ist ohne ausreichende Ortskenntnisse. Der andere Geldautomat befindet sich bei 40118 und es handelt sich hierbei um eine Tankstelle.

Beide Geldautomaten befinden sich aber, sodass sie sich aus Fahrtrichtung Tankstelle nicht ohne Weiteres anfahren lassen.
Drüber hinaus befindet sich die Tankstelle in der Nähe, wodurch aus regelmäßig Gang-RP stattfindet daher ist die Gefahr groß, dass jemand überfallen wird nach dem Geld holen. Was ebenfalls mit einem Automaten gemindert werden kann. 
Aus wirtschaftlicher Sicht ist es für jedes Bankinstitut ein lohnenswertes Ziel, da es ein Markt Bereich ist, der erschlossen werden kann.

**Siehe Fotos**
![tankstellen](https://user-images.githubusercontent.com/76626768/107762140-da191e80-6d2c-11eb-8c8b-54fbf888f6db.JPG)
![automat](https://user-images.githubusercontent.com/76626768/107762518-6d525400-6d2d-11eb-85cf-2c685be06dd9.JPG)
![automat2](https://user-images.githubusercontent.com/76626768/107762537-7511f880-6d2d-11eb-88eb-ff266975bb8b.JPG)

**Comment by DonVitoDiangelo** [comment]
Wir werden hier keine weiteren "personalisierten" Props aufstellen. Bei weiteren Fragen kannst du mich gern im TS kontaktieren
