### ISSUE TITLE
Crashes 11.02-12.02

### ISSUE THREAD

**Issue by LautaroTesto** [mexyn/statev_v2_issues#1174]
**Character Name**
Lautaro Testo

1x Crash Ostmine am 11.02.2021 um 14:00Uhr
1x Crash zwischen Ostmine und Tattooshop 12.02.2021 um 12:30Uhr
1x Crash als ich in eine Firma reingehen wollte PLZ: 4040 11.02.2021 um 01:20Uhr
1x Crash Westseite Würfelpark bei Vankov 11.02.2021 um 22:20Uhr
1x Crash Ostmine am 12.02.2021 um 13:00Uhr

**Comment by DrGrizzlY17** [comment]
In #1143 übertragen
