### ISSUE TITLE
Einausparkpunkt bei carWorkshop12 verbuggt

### ISSUE THREAD

**Issue by Husky2002** [mexyn/statev_v2_issues#1176]
**Character Name**
Eddy Husky

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.02.2021 um 04:22

**Beobachtetes Verhalten**
Wenn man einen Pounder bei der Werkstatt(ADAC) carWorkshop12  ausparkt, buggt dieser zum teil in der Wand so, dass der Pounder ab und zu beschädigt (Gelbe/Rote Motorleuchte) oder gar auf der Seite ausgeparkt wird.

**Erwartetes Verhalten**
Man sollte den Pounder ganz normal ausparken können, dass er nirgendwo buggt und immer auf der Reifen spawnt

**Schritte um den Fehler nachvollziehen zu können**
Der Pounder wurde ganz normal ausgeparkt, da der Pounder ein kleines bischen in der Wand buggt fahre ich immer ein kleines stück nach vorne und dann lag der Pounder schon auf der Seite

**Optional: Video / Bilder des Fehlers**
![20210212042254_1](https://user-images.githubusercontent.com/61657852/107775414-89abbc00-6d40-11eb-9d45-38fa9984f702.jpg)

**Comment by DrGrizzlY17** [comment]
Der Punkt ist jetzt etwas weiter unten für ein- und ausparken
