### ISSUE TITLE
Vorschlag: Weiterer Dispatchpunkt am LSPD Tresen

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1177]
Vorschlag: Weiterer Dispatchpunkt am LSPD Tresen,

dieser wäre am besten hinten an der Wand vom Tresen zu platzieren, sodass die Kunden am Tresen nicht hören, was im Notruf reinkommt, den Radius des Piepens könnte man dementsprechend auch verringern, da der Tresenraum ja sehr klein ist, sodass man das ständige Piepen im Großraumbüro nicht hört.

Vorteil daran wäre, dass man gerade wenn nicht so viel los ist, man am Tresen dann auch die Leitstelle belegen könnte, und so beides zusammen gemacht werden könnte.

**Comment by DrGrizzlY17** [comment]
Bitte an eure Fraktionsleitung abgeben und mit Spoon klären
