### ISSUE TITLE
2 Poeler

### ISSUE THREAD

**Issue by StateV2Marie** [mexyn/statev_v2_issues#1178]
Ich hätte eine bitte wärt ihr bitte so lieb die 2 Pöller die ich makiert habe zu entfernen da fährt man sich ständig das auto kaputt zudem sie mega weit drinnen stehen es geht auch nur um die 2 die wo makiert sind wäre echt lieb danke bild schick ich mit 

[https://pic.statev.de/image/poellermuessenweg.0jqr0](url)

**Comment by DrGrizzlY17** [comment]
Abgelehnt
