### ISSUE TITLE
Gamecrash beim Fahren 

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#1179]
**Character Name**

Ryan_Valdes
**Auftrittszeitpunkt (Datum / Uhrzeit)**

19:55Uhr & 19:58Uhr
**Beobachtetes Verhalten**

Gamecrash beim Fahren in Richtung norden & Beim Reloggen Standort Im Screenshot

**Erwartetes Verhalten**

Kein Gamecrash

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://user-images.githubusercontent.com/70231715/107810530-1d937d00-6d6d-11eb-8781-52e6de9eb150.png)

![image](https://user-images.githubusercontent.com/70231715/107810560-2be19900-6d6d-11eb-8da9-9eb84444d5ce.png)

**Comment by DrGrizzlY17** [comment]
Biite in #1143 eintragen mit der Vorlage
