### ISSUE TITLE
Hitbox Bahamas Mamas

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#118]
**Character Name**

Erwin_Dulach
**Zeitpunkt (Datum / Uhrzeit)**

27.08
**Beobachtetes Verhalten**

Hitbox der Säule links nicht existent.
**Erwartetes Verhalten**

Wand sollte solide sein.
**Schritte um den Fehler nachvollziehen zu können**

In die pinke Säule links neben dem Baum rennen.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://x-up.ws/i/7eac56fd349f.png
https://x-up.ws/i/51737476864b.png

**Comment by DonVitoDiangelo** [comment]
zu vernachlässigen
