### ISSUE TITLE
Gamecrash Ostmine

### ISSUE THREAD

**Issue by JonnyHart** [mexyn/statev_v2_issues#1180]
**Character Name**
Jonny Hart

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.02.2021

**Beobachtetes Verhalten**
Gamecrash
**Erwartetes Verhalten**
...

**Schritte um den Fehler nachvollziehen zu können**
Schliessen Kofferraum Pounder an der Ostmine. Ca 15 Fahrzeuge und 7 Leute in der nähe

**Comment by JonnyHart** [comment]
3 Leute an der gleichen STelle Gamecrash gehabt

**Comment by JonnyHart** [comment]
und wieder Game Crash Ostmine fast gleiche Position

**Comment by DrGrizzlY17** [comment]
Bitte mit Vorlage in #1141 eintragen
