### ISSUE TITLE
Crashes 13.02.2021

### ISSUE THREAD

**Issue by miischaa** [mexyn/statev_v2_issues#1184]
Character Name
Heinrich Iwanow

1x Crash beim Fahren der Straße Richtung Westen gegen 18:45 Uhr am 13.02.2021
1x Crash beim einloggen direkt danach, noch bevor mein Char auf der Straße zu sehen war 
1x Crash beim einloggen danach, nachdem ich 2 Meter gelaufen bin

Nach dem dritten Crash hab ich mich eingeloggt und einer hatte mit seinem Phantom + Ölachse direkt neben mir einen Crash

**Comment by CatherineGallagher** [comment]
Ich schließ mich mal hier an
1x: Einloggen > ausm Haus raus in Davis neben Ballas Hood, wollte gerade losfahren > Crash
1x nach dem Einloggen losgefahren richtung Davis Tankstelle, fast höhe Tankstelle wieder Crash

**Comment by miischaa** [comment]
Habe ganz vergessen den Screenshot mit bei zu packen.
https://i.gyazo.com/9fae858195f975fcbc5304ce4a1cca1f.png
