### ISSUE TITLE
Visualbug öffnen von Handy/Tablet

### ISSUE THREAD

**Issue by ArnoZuDemB** [mexyn/statev_v2_issues#1189]
**Character Name**
Arno Bjerg

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14.02.2021 13:30

**Beobachtetes Verhalten**
Grafikbug bei Versuch Handy/Tablet zu öffnen

**Erwartetes Verhalten**
reguläre Einloggen in die Geräte 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080p

**Optional: Video / Bilder des Fehlers**
https://user-images.githubusercontent.com/77365416/107877703-58f98d00-6ece-11eb-9750-a31796364b4f.mp4

**Comment by ArnoZuDemB** [comment]
Tritt häufig direkt nach dem Login ein. verstärkt bei schlechter Internetverbindung und/oder starker CPU Auslastung.

Kurios daran: die schwarzen balken verschwinden kurz, sollte man über ESC in die Einstellungen gehen und tauchen wieder auf, wenn man das ESC Menu schließt.

**Comment by its4l3x** [comment]
Ist in der Hinsicht bei uns kein Bug, sondern ein User bezogenes Problem.

Schließe das Ticket erstmal wieder.
