### ISSUE TITLE
Produktion. Indikator grün obwohl zu wenig Materialien im Maschinenlager

### ISSUE THREAD

**Issue by Gee1337** [mexyn/statev_v2_issues#119]
**Character Name**
Duke_Rain
**Zeitpunkt (Datum / Uhrzeit)**
19:20

**Beobachtetes Verhalten**
Benötigte Materialien stehen auf grün, Produktion kann aber nicht gestartet werden, da im Maschinenlager zu wenig Materialien vorhanden sind. 

**Erwartetes Verhalten**
Sollte != grün sein, da benötige Summe an Materialien nicht im Maschinenlager vorhanden sind.

**Schritte um den Fehler nachvollziehen zu können**
Bis auf einen Gegenstandstypen waren alle vollständig.
Dann musste der fehlende Gegenstandstyp (Spezialfederung) nachproduziert werden.
Daher hat sich die Anzahl der Materialien im Maschinenlager geändert. Dennoch blieben benötigten Materialien für die Produktion true, aber die mögliche Produktionsanzahl auf 0.

![360a66e81daeea88c73a42cb80256ab1](https://user-images.githubusercontent.com/70242468/91476859-d9cfb880-e89d-11ea-9194-08aae1584fcf.gif)

**Comment by KingMarcel** [comment]
Konnte ich weder auf dem Server noch im UI reproduzieren. Bitte nochmal testen.

**Comment by DrGrizzlY17** [comment]
War schon bei V1 das Problem. Der UI des Produktionscomputers macht wohl nur eine Abfrage ob das Item im machineInvetory ist, aber nicht ob die Anzahl auch der benötigten Summe entspricht

![7701640bddf1f6640d2a67e9d40fe41b](https://user-images.githubusercontent.com/70150988/91542514-47232e00-e91e-11ea-8925-a0897619b324.png)

**Comment by tastydev** [comment]
fixed im nächsten update. Das item wird nun nur grün hinterlegt, wenn die Anzahl für die Produktion mit der des Inventar übereinstimmt oder mehr im Inventar liegt.
