### ISSUE TITLE
Schieben und einparken

### ISSUE THREAD

**Issue by RealSocius** [mexyn/statev_v2_issues#1190]
**Character Name**
Sebastian Schindler

**Auftrittszeitpunkt (Datum / Uhrzeit)**
15:28 Uhr

**Beobachtetes Verhalten**
Schiebeanimation kann nachdem das Auto vom Mitarbeiter in die Horizon Werkstatt eingeparkt wurde nicht abgebrochen werden.

**Erwartetes Verhalten**
Schiebeanimation nach einparken abbrechen

**Schritte um den Fehler nachvollziehen zu können**
Auto in Einparkpunkt Schieben, zweite Person parkt währenddessen Auto in die Werkstatt

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Sorry, aber das ist kein richtiger Bug :D 

Ihr müsst da selber aufpassen. Vor allem parkt ein Fahrzeug nicht ein, während es geschoben wird. Einfach abwarten bis zu Ende geschoben. Macht ja auch wenig Sinn im RP während ich am schieben bin, Fahrzeug dann weg. => ;)
