### ISSUE TITLE
Achse verschwindet kurzzeitig während Fahrt und taucht wieder auf

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#1194]
**Character Name**
Paul Humpert

**Auftrittszeitpunkt (Datum / Uhrzeit)**
15.02.2021 / 10:30

**Beobachtetes Verhalten**
Achse teleportierte sich weg und tauchte kurz danach wieder auf und fiel dann um

**Erwartetes Verhalten**
Achse sollte sich nicht wegteleportieren und nicht umfallen

**Schritte um den Fehler nachvollziehen zu können**
Mit einem LKW + Trailer Large Achse fahren

Video:
https://www.youtube.com/watch?v=-0F_lN9X5aE&feature=youtu.be

**Comment by its4l3x** [comment]
ehm. wtf

**Comment by DonVitoDiangelo** [comment]
Sieht stark nach einem alt:V sync Fehler aus - Einfach weiter beobachten und ggf. erneut melden.

**Comment by DonVitoDiangelo** [comment]
Hat sich das Problem mit dem letzten alt:V Update behoben?

**Comment by Humperrrt** [comment]
Kann ich keine Angabe zu machen, hatte den Fehler seit der Meldung nicht mehr. Insgesamt ist mir das sowieso nur 2x passiert.
