### ISSUE TITLE
Versetzung des Garagen Ein/Ausparkpunktes...

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1195]
Siehe Video... ^^
https://youtu.be/5Ertak_dzSY

Den neuen Punkt bitte dahin setzen wo Bonsai steht...

![garage2](https://user-images.githubusercontent.com/70241137/107939676-5c048400-6f87-11eb-9956-8db4a27646f0.jpg)

![garage3](https://user-images.githubusercontent.com/70241137/107939683-5e66de00-6f87-11eb-901c-8c2dd1ebaed7.jpg)

**Comment by DrGrizzlY17** [comment]
So oft wie ich jetzt schon irgendwelche Punkte von dir verschoben hab, sollte IC dein Hausmeister oder so werden

**Comment by Statev-Bonsai** [comment]
Hahahahaha, aber diesmal geht es ja nun wirklich net anders :)
Dankeeeeeeeeeeeeeeeeeeeeeeeee..
