### ISSUE TITLE
Geldautomat verschwunden

### ISSUE THREAD

**Issue by BerozSV** [mexyn/statev_v2_issues#1196]
**Ante_Cilic**
 Ante_Cilic

**Auftrittszeitpunkt (Datum / Uhrzeit)** 15.02.2021
 06.12.20

**Beobachtetes Verhalten**
 Habe gesehen, das der Geldautomat, der am Pacific Bluffs (Großes Hotelgebäude mit Partylocation am Westhighway nach dem Übertritt nach State V2, aufeinmal weg war.

**Erwartetes Verhalten**
 Ich war bereits im Support und Harry Spotter meinte zu mir, das ich das im Bug-Report wieder beantragen könnte. Mein Charakter hat das Hotel erworben, deshalb wäre es mir lieb, wenn es möglich wäre, den Geldautomaten wieder aufzustellen, da dort auch eine Bar ist und verschiedene Events geplant sind. Wenn es möglich ist, wäre auch eine Garage gewünscht, da es direkt ein Stückchen weiter oben direkt 3 Stück nebeneinander gibt, aber oben kaum Häuser/Hotels sind.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Ja, das ist so gewollt. Hier soll auch klar der Transfer nicht vereinfacht werden, sodass einfach auch Potenzial für einen theoretischen Überfall gegeben sein kann. Wenn jeder immer nur 50 Meter zu einem Automaten laufen muss ist das halt nicht gegeben. Nur an div. vereinzelten Spots ist dieser verblieben.
