### ISSUE TITLE
Brouge Ave 4 grüner Ring fehlt

### ISSUE THREAD

**Issue by BenjaminKendrick** [mexyn/statev_v2_issues#1197]
**Hilma Kaiser**

**Auftrittszeitpunkt 16.02.2021 04.50)**

**Es fehlt eine grüner Ring zum ausziehen bei einer Wohnung**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

<img width="960" alt="bug 11" src="https://user-images.githubusercontent.com/78513508/108017353-f4951580-7014-11eb-8c90-52f6c10ca5b7.png">
<img width="960" alt="bug 23" src="https://user-images.githubusercontent.com/78513508/108017356-f65ed900-7014-11eb-8db6-f1d3486a4721.png">

**Comment by Enemyaa** [comment]
Hi, sollte mit dem nächsten Update gefixt sein.

**Comment by BenjaminKendrick** [comment]
Problem ist immernoch vorhanden, wenn ich die Wohnung verlasse werde ich 5 Meter über der Hauptstraße gespawnt.
