### ISSUE TITLE
UI Bug beim drücken der Tabulator Taste (z.B. beim ziehen der Waffe Ingame)

### ISSUE THREAD

**Issue by FoxXxyLive** [mexyn/statev_v2_issues#1198]
**Samy_Nustrajev**

**immer wenn man die Tabulator Taste betätigt. Das Problem trat seitdem Zeitpunkt auf als die Waffenattechments deaktiviert wurden**

**Verzerrung des UI´s also Tacho, Funkgerät; Map, Leben und Nahrungsanzeige etc**

**Statisches UI wie sonst auch immer**

**bei mir taucht es immer auf, wenn ich meine Waffe mit der Tabulator Taste, Ingame heraus holen möchte. Um den normalen Zustand des UI´s wieder zubekommen, blende ich es kurz mit # aus und wieder ein, jedoch ist das für mich keine Lösung und bitte daher um einen fix bzw Lösungsvorschlag, Danke :) **

**Fenstermodus ohne Rahmen und wahlweise getestet bei der Full HD Auflösung sowie auch bei der WQHD Auflösung mit 240Hz

Normalzustand des UI´s: https://prnt.sc/zr6rsi
Zustand nach Drücken der Tabulatortaste, im freien: https://prnt.sc/zr6u5g
Zustand nach drücken der Tabulatortaste im Fahrzeug: https://prnt.sc/zr6y01

**Comment by FoxXxyLive** [comment]
und nochmal ein Bild mit Interactionwheel: https://prnt.sc/zr708a

**Comment by DrGrizzlY17** [comment]
Funk ausm Slot ziehen und wieder reinziehen fixed es erstmal.

Zudem Duplikat und schon bekannt
#253

**Comment by FoxXxyLive** [comment]
Das mit dem Funkgerät fixt es leider nicht. 

Okay, das wusste ich nicht Rusty meinte ich solle einen neuen Eintrag schreiben.

**Comment by FoxXxyLive** [comment]
https://prnt.sc/zr7k41 es verschiebt sich dennoch weiterhin, oder muss man dafür reconnecten?

**Comment by CaleighRhodes** [comment]
du kannst auch das Vunkgerät aufmachen, paar mal hoch und runter scrollen und dann wieder einklappen. Dann ist deine UI auch wieder normal. Problematisch wird es, wenn du mehr als 3 Funkfrequenzen hast.

**Comment by FoxXxyLive** [comment]
ja habe 4 Stück :D derzeit blende ich das UI mit # aus und wieder ein das behebt es natürlich auch, jedoch ist das keine Dauerhafte Lösung :D
