### ISSUE TITLE
GameCrash: SandyShores- Garage

### ISSUE THREAD

**Issue by theJanosch** [mexyn/statev_v2_issues#1199]
**Character Name:**
Heinz_Heineken

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.02.2021 - 20:14Uhr

In welcher Region ist der GameCrash aufgetreten? (Screenshot oder PLZ von der Map)
SandyShores Höhe Garageneinfahrt/Ausfahrt
 
**Welche Fahrtrichtung wurde gefahren?**
west-wärts
(von der SandyShores Tankstelle, an dem Sandy-PD vorbei zur Garage)
https://prnt.sc/zrh7ud
https://prnt.sc/zrhfb0
PLZ: 818

**Fahrzeuge in der Nähe gesehen? Wenn ja, welche?**
Fahrzeuge des County-PDs

**Optional: Crashdump (im altV Ordner hinterlegt)**
Ja, siehe Anhang. [client[1].log](https://github.com/mexyn/statev_v2_issues/files/5991160/client.1.log)

**Comment by DrGrizzlY17** [comment]
#1143
