### ISSUE TITLE
Tuning / Fahrzeug unterwegs tunen

### ISSUE THREAD

**Issue by DonVitoDiangelo** [mexyn/statev_v2_issues#12]
**Zeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Fahrzeug unterwegs tunen

**Erwartetes Verhalten**
Fahrzeug muss verschlossen sein und bleiben. Kein öffnen möglich.

**Schritte um den Fehler nachvollziehen zu können**
Tuning starten -> N Coursor deaktivieren -> zum Fahrzeug laufen und einsteigen -> wegfahren und tunen wann man will

**Optional: Video / Bilder des Fehlers**
![1](https://user-images.githubusercontent.com/70151087/91196145-0d71dd80-e6fa-11ea-97de-37f5a05be653.jpg)

**Comment by mexyn** [comment]
mit dem nächsten update gefixt. Fahrzeuge werden jetzt beim Öffnen des Menüs verschlossen und geblockt
