### ISSUE TITLE
Animation von Objektinteraktion geht weiter, auch wenn Objekt abgebaut ist.

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#120]
**Character Name**

Erwin_Dulach

**Zeitpunkt (Datum / Uhrzeit)**

27.08 20:00

**Beobachtetes Verhalten**

Animation läuft auch nach abbauen des Objektes weiter. Beliebig Reproduzierbar. Auf Laufmühlen rennt der Char dann sogar weg und buggt immer wieder zurück.

**Erwartetes Verhalten**

Animation bricht ab oder Objekt nicht abbaubar

**Schritte um den Fehler nachvollziehen zu können**

Objekt platzieren -> "y" -> Animation nach belieben auswählen -> "."

**Optional: Video / Bilder des Fehlers**

https://x-up.ws/i/b5a17c521e21.png

**Comment by its4l3x** [comment]
Korrekt, können wir nicht so easy abfangen. Ich bitte da einfach auf Rücksicht. Schlussendlich mache ich das im RP ja auch nicht und wenn doch, dann easy neustarten löst das Problem.
