### ISSUE TITLE
Crash beim verlassen des Autohauses

### ISSUE THREAD

**Issue by Beartox** [mexyn/statev_v2_issues#1200]
Tobias_Schlueter

Auftrittszeitpunkt:
16.02.2021 / 20:43

In welcher Region ist der GameCrash aufgetreten?
7044 Autohaus Luxury Cars

Optional: Crashdump (im altV Ordner hinterlegt)
[client.log](https://github.com/mexyn/statev_v2_issues/files/5991511/client.log)

**Comment by DrGrizzlY17** [comment]
#1143
