### ISSUE TITLE
Game Crash Emilio

### ISSUE THREAD

**Issue by EmilioLucianoV** [mexyn/statev_v2_issues#1201]
**Emilio Luciano**

**16.02.2021 / 21:30**

**Game Crash auf dem Highway mit ca 200 km/h**

**kein crash**

**Mit einem Vanilla fahrzeug an der Paleto Werksatt vorbei fahren**

[client.log](https://github.com/mexyn/statev_v2_issues/files/5991533/client.log)
![9f0cf4d196249d1fbcf67d15a2e97130](https://user-images.githubusercontent.com/79170188/108118949-58fcb700-709f-11eb-8b48-99b225296889.jpg)

**Comment by DrGrizzlY17** [comment]
#1143
