### ISSUE TITLE
Kriegsbeil entfernt - oder doch nicht?

### ISSUE THREAD

**Issue by miischaa** [mexyn/statev_v2_issues#1204]
**Character Name**
Heinrich Iwanow

**Auftrittszeitpunkt (Datum / Uhrzeit)**
24.01.2021

**Beobachtetes Verhalten**
Wir haben festgestellt, dass bei allen von uns die ein Indianisches Kriegsbeil in der Wohnung hatten, keins mehr vorhanden ist. Daraufhin habe ich ein Bug Report geschrieben, wo mir erklärt wurde, dass diese entfernt wurden, weil ein weil "etwas geändert werden musste". Am selben Tag hab ich schon eine Werbung gesehen, dass Jemand seins verkauft und vor einigen Tagen wieder. Also sind wir hingefahren und haben uns vergewissert, dass es genau das gleiche Kriegsbeil ist wie es bei uns war und tatsächlich war es das.

Wie kann es also entfernt worden sein, aber andere haben das noch? Oder ist es doch nur ein Bug und es soll uns nicht erstattet werden? Da gehen schon wieder Sachen flöten, die man sammelt und ewig lange aufbewahrt und dann einfach so weg sind.

**Erwartetes Verhalten**
Das wir unsere wieder bekommen, wenn es garnicht entfernt wurde

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://github.com/mexyn/statev_v2_issues/issues/1098
https://i.gyazo.com/e767fdfcd2c6f1ca8481a17eb341b09d.png
https://youtu.be/CHUzshGx6e8

**Comment by DonVitoDiangelo** [comment]
^Ja, hier gab es "alte" die nicht mehr genutzt werden konnte. Diese wurden entfernt. Aber es gibt nach wie vor welche. Diese sind dann neu gefunden worden.

**Comment by miischaa** [comment]
Und die kann man nicht ersetzen?

**Comment by DonVitoDiangelo** [comment]
Nein diese wurden und werden nicht ersetzt, da diese broked waren.
