### ISSUE TITLE
Mehr Möglichkeiten der Kleidungsanpassung

### ISSUE THREAD

**Issue by Michi993** [mexyn/statev_v2_issues#1205]
**Character Name**
Luke Hammer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Kurze Shirts, die vorne offen sind kann man nur mit Unterteil tragen, da man sonst einen durchsichtigen Körper hat.

**Erwartetes Verhalten**
Möglichkeit, dass man Kurzarm 4 Erschafft, bzw noch mehr möglichkeiten, um ausschnitte von T-Shirts mit V-ausschnitt möglich zu machen und eben auch Oberkörperfrei darunter zu sein.

**Schritte um den Fehler nachvollziehen zu können**
Mehrere Möglichkeiten  der Oberteilanpassung einfügen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/gta5-2021-02-17-19-35-27.0JOAT
https://pic.statev.de/image/gta5-2021-02-17-19-35-42-1.0Jn50

**Comment by DrGrizzlY17** [comment]
https://wiki.rage.mp/index.php?title=Male_Torsos

Wie du siehst, gibt uns GTA nicht mehr Möglichkeiten. Deswegen ist dein Wunsch nicht Möglich

**Comment by Michi993** [comment]
ist es jedoch möglich, "Drawable 184 - 194" hinzuzufügen?
