### ISSUE TITLE
Veränderungen Hotel - 5038

### ISSUE THREAD

**Issue by ADACRaf** [mexyn/statev_v2_issues#1206]
****Character Name****
 Raphael Blanc 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Vor 3 Tagen ist uns das Dach besonders ins Auge gestochen. 

**Beobachtetes Verhalten**
 Das Dach bietet zum jetzigen Zeitpunkt kaum fläche und ist sehr unsicher, da jederzeit die Gefahr besteht, dass jemand runterfällt. 

**Erwartetes Verhalten**
 Wir würden Sie erbitten, dass das Dach eine komplett flache Fläche bekommt und mit zwei Swimming-Pool´s ausgestattet wird, damit wir mehr Fläche und Spielraum bekommen und den ganzen Aufenthalt auf den Dach sorgfältiger, spannender und sicherer gestalten zu können, da wie gesagt jederzeit die Chance besteht runterzufallen. 

**Schritte um den Fehler nachvollziehen zu können**
 1. Die Dachfläche flach zu gestalten.
2. Evtl die Dachränder höher anlegen.
3. Auf den Flächen auf den Dach, einen Pool anlegen für die Besucher des Hotels.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Welches Hotel?

**Comment by ADACRaf** [comment]
Das Hotel befindet sich bei der Postleitzahl 5038, direkt neben dem Resteraunt. Der Hotelbesitzer ist Chiko Garcia. Da wir das Hotel erst neu bekommen haben, haben wir uns noch nicht entschieden für einen Namen.

**Comment by DrGrizzlY17** [comment]
Für das nächste mal einfach in der UI gucken und die Infos weiter geben vom Gebäude
![image](https://user-images.githubusercontent.com/70150988/108477412-77c39f00-7293-11eb-9a14-6a1db4506195.png)

Anfrage muss ich dennoch ablehnen
