### ISSUE TITLE
GameCrash

### ISSUE THREAD

**Issue by conny97** [mexyn/statev_v2_issues#1207]
Character Name
Mandy Ritter 

Auftrittszeitpunkt (Datum / Uhrzeit)
17.02.21/21:50Uhr

In welcher Region ist der GameCrash aufgetreten? (Screenshot oder PLZ von der Map)
Region, PLZ (evtl. Screenshot)
PLZ 5039 das Hotel Laufrichtung Tricksters Hood

Welche Fahrtrichtung wurde gefahren?
Gelaufen Richtung Norden

Fahrzeuge in der Nähe gesehen? Wenn ja, welche?
Bodhi und Kuruma

Crashdumps:
[altv_2.11_Steam_0x5eaca0_17-02-2021_21-44-31.zip](https://github.com/mexyn/statev_v2_issues/files/5998582/altv_2.11_Steam_0x5eaca0_17-02-2021_21-44-31.zip)
[altv_2.11_Steam_0x5eaccf_17-02-2021_21-42-18.zip](https://github.com/mexyn/statev_v2_issues/files/5998584/altv_2.11_Steam_0x5eaccf_17-02-2021_21-42-18.zip)

**Comment by DrGrizzlY17** [comment]
#1143
