### ISSUE TITLE
Gamecrash PLZ 7000

### ISSUE THREAD

**Issue by ArnoZuDemB** [mexyn/statev_v2_issues#1208]
Arno Bjerg

Gamecrash direkt oberhalb Postal 7000 östliche Fahrtrichtung (südl. Toiletten LS) mit ca. 100 km/h gesehen 1 Hauler und 1 Phantom je mit Ölachse

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.02.2021 22:13 Uhr

**Comment by DrGrizzlY17** [comment]
#1143
