### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by julieed** [mexyn/statev_v2_issues#1209]
**Character Name**

Julieta Garcia

**Auftrittszeitpunkt (Datum / Uhrzeit)**

17.02.2021 ( 22:15 / ca. 23:30)

**Beobachtetes Verhalten**

Game crash

**Schritte um den Fehler nachvollziehen zu können**

Einmal beim Pier und einmal in Paleto nähe Werkstatt

**Comment by DrGrizzlY17** [comment]
#1143
