### ISSUE TITLE
Beim einladen ins MD manchmal synced unter dem bett liegend

### ISSUE THREAD

**Issue by Chrinis007** [mexyn/statev_v2_issues#121]
**Character Name**
Christian_Maier

**Zeitpunkt (Datum / Uhrzeit)**
Heute

**Beobachtetes Verhalten**
Beim entladen vom stabilsierten Patienten im RTW liegt der Patient laut meinem sync manchmal unter dem bett obwohl er synced drauf liegt

**Erwartetes Verhalten**
Auf dem Bett liegend

**Schritte um den Fehler nachvollziehen zu können**
Person bewusstlos schlagen
Stabilisieren
In rtw einladen mit der Trage
Am Md ausladen über den Marker
Zum Bett gehen

**Optional: Video / Bilder des Fehlers**

**Comment by r3sist3nt** [comment]
@its4l3x war das nicht solved?

**Comment by Chrinis007** [comment]
Ist immer noch so
