### ISSUE TITLE
Oberkörper "abgeschnitten" bei offenen Kurzarmhemden

### ISSUE THREAD

**Issue by CalitoRamirez** [mexyn/statev_v2_issues#1210]
**Character Name**
Calito Ramirez

**Auftrittszeitpunkt (Datum / Uhrzeit)**
18.02.2021

**Beobachtetes Verhalten**
Mir ist aufgefallen, dass man bei einem offenem Kurzarmhemd gezwungen ist etwas darunter zu tragen, da ansonsten der Rest des Torsos fehlt.

**Erwartetes Verhalten**
Ich würde mir wünschen, dass man bei den offenen Kurzarmhemden, so wie bei den offenen Langarmhemden nicht zwingend etwas darunter tragen muss, sodass man den restlichen Oberkörper problemlos sieht.

**Schritte um den Fehler nachvollziehen zu können**
"Weißes Slim Shirt, offen" anziehen und alle "Reiter" an Kleidungstypen ausprobieren
![Grand Theft Auto V Screenshot 2021 02 18 - 18 14 40 35](https://user-images.githubusercontent.com/79257207/108394793-650a8500-7215-11eb-863b-a5399bb9fe29.png)
![Grand Theft Auto V Screenshot 2021 02 18 - 18 14 51 21](https://user-images.githubusercontent.com/79257207/108394888-83708080-7215-11eb-82eb-68bc7c0ca132.png)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**

**Comment by h3adbang3r** [comment]
Aussehen auf "Oberkörperfrei" stellen dürfte Dein "Problem" beheben.

**Comment by CalitoRamirez** [comment]
Negativ, also jain. Da sieht man dann zwar den gesamten Oberkörper, aber da sitzt das Oberteil nicht richtig (Risse/offene Stellen bei Bewegung und Animationen).

**Comment by DrGrizzlY17** [comment]
Es gibt von GTA keine Möglichkeit Kurzarm & offenes Hemd zu tragen.

Siehe #1205
