### ISSUE TITLE
Lackierungen Werkstatt bug oder nicht?

### ISSUE THREAD

**Issue by ShauniKT** [mexyn/statev_v2_issues#1212]
**Character Name**

Shauni Teller (Bennys)

**Auftrittszeitpunkt (Datum / Uhrzeit)**

laut Aussage ca. seit 2 Wochen

**Beobachtetes Verhalten**

Uns ist aufgefallen, dass man das Auto außerhalb der Werkstatt lackieren kann, indem vorher jmd. im Auto sitzt mit angeschaltetem Motor, dann der Mechaniker die UI öffnet und der Fahrer einfach aus der Werkstatt fahren kann. Vorher gab es eine Fehlermeldung beim Lackieren, dass alle aussteigen müssen, um Blödsinn zu vermeiden (jmd. fährt mit dem Auto rum, obwohl nur die Lack Vorschau zu sehen ist), da ich dies zu Anfang von V1 schon gemeldet hatte und es daher dann gefixet wurde, damit man dies eben nicht kann (Vorbeugung Fail RP, etc., allerdings nun auch über 2 Jahre her)

Daher die Frage:
Soll das so sein? Oder ist das ein Fehler?
einerseits gut, da man Lackierungen im normalen Tageslicht und nicht verfälscht (Bennys zu hell, andere zu dunkel) sehen kann, andererseits ist da dann die Frage, wie weit das genutzt werden darf. Zum angucken der Farbe okay aber lackieren trotzdem drinnen? bitte um Rückmeldung. Dazu gäbe es dann nämlich auch den Punkt, dass sich LKW Werkstätten benachteiligt fühlen könnten, da sie das ja nicht können (Interior).

**Erwartetes Verhalten**

Wenn jemand im Auto sitzt während der Lackierung, hat das System gemeckert, dass alle aussteigen sollen, da man sonst das Lackierinterface nicht öffnen konnte.

**Schritte um den Fehler nachvollziehen zu können**

2 Personen, 1 Auto
- Person 1 stellt sich mit dem Auto auf den Lackierpoint und bleibt sitzen
- Person 2 öffnet Lackierinterface
- Person 1 kann mit Auto wegfahren, während interface offen ist
- Person 2 kann derweil die Farbe ändern

**Comment by DonVitoDiangelo** [comment]
Sollte so nicht sein, muss dann nochmal geschaut werden aber ist auch klar Bugabuse. Also falls sowas mal jemand mitbekommt einfach melden.

**Comment by DonVitoDiangelo** [comment]
https://statev.de/forum/thread/13602-beim-lack-anschauen-mit-dem-kunden-vor-die-werkstatt-gehen-erlaubt/?postID=124824&highlight=lackierung#post124824
