### ISSUE TITLE
Account/Charakter Bug ?

### ISSUE THREAD

**Issue by Dxxe** [mexyn/statev_v2_issues#1213]
**Character Name**
Sergio Martin

 Eigenen und allen anderen Charaktern

**Auftrittszeitpunkt (Datum / Uhrzeit)**
  21.12.2020

**Beobachtetes Verhalten**
 bestimmte Kleidungstücke werden nicht angezeigt/ falsch angezeigt z.b. : Bauerbeiterhelm wird als Cap angezeigt , Vanda Jacke wird garnicht angezeigt , bestimmte Tattoos/Armbänder usw  werden ingame nicht angezeigt falsch angezeigt

**Erwartetes Verhalten**
 

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=DOdxgmDm46I&feature=youtu.be&ab_channel=SergioMartin

**Comment by DonVitoDiangelo** [comment]
Bitte leere mal deinen Cache Ordner und lade alles neu herunter. Welchen Client nutz du? alt:V Standard oder den StateV Client?

**Comment by Dxxe** [comment]
Morgen :)
hab jetzt über Nacht Gta neu installiert , und den alt v launcher auch schaue jetzt ob sich was verändert hat.

**Comment by Dxxe** [comment]
benutze den State V client.

**Comment by Dxxe** [comment]
UPDATE: nach der Neuinstallation sehe ich endlich meinen Rucksack und den Gelben Helm.
