### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by julieed** [mexyn/statev_v2_issues#1214]
**Character Name**

Julieta Garcia
**Auftrittszeitpunkt (Datum / Uhrzeit)**

18.2.2021 (zwischen 22Uhr und 1Uhr) // auf der Straße bei Club 7 3x Crash
ca. 21:15 Paleto näche Werstatt einmal crash

**Comment by MisterCopeland** [comment]
Hej, in deinem Alt V Ordner ( Pfad-> F:\AltV\crashdumps) sind ZIP Ordner. Die Zip Ordner von deinen Crashes sind für hier sehr Interessant. Vielleicht kannst du die ja hier mal Uploaden. 
Deren Name sehen ungefähr so aus -> altv_2.11_Steam_0x5eaccf_18-02-2021_21-05-43
