### ISSUE TITLE
Antrag auf Versetzung des Garagen Ein/Ausparkpunktes

### ISSUE THREAD

**Issue by Micha190** [mexyn/statev_v2_issues#1216]
**Michy_Sauerland**

**Immer**

**Antrag auf Versetzung des Garagen Ein/Ausparkpunktes des Hauses 
Grapeseed Maid Street 3
(Haushash SandyShores3)
Durch die bauliche Strucktur des Carports ist es leider nicht Möglich ein größeres Fahrzeug einzuparken.**

**Garagen Ein/Ausparkpunktes nach vorn Verlegen
Von Rot nach Grün**

**Optional: Video / Bilder des Fehlers**

![Haus Garage](https://user-images.githubusercontent.com/75121724/108593174-8339c780-7372-11eb-86a8-d2887438f097.jpg)

**Comment by Statev-Bonsai** [comment]
https://github.com/mexyn/statev_v2_issues/issues/691

**Comment by DrGrizzlY17** [comment]
Größere Fahrzeuge bitte 2m weiter in der öffentlichen Garage parken
