### ISSUE TITLE
Entferung eines Zauns 

### ISSUE THREAD

**Issue by CatherineGallagher** [mexyn/statev_v2_issues#1218]
**Character Name**
Catherine Gallagher

**Beobachtetes Verhalten**
Der Zaun stört extrem, da man so entweder um das Gebäude komplett herum laufen muss, oder über Containern zum Eingang kletter muss um das Gebäude betreten zu können, In V1 war der Zaun nicht vorhanden. Der Abladepunkt befindet sich nämlich auf dem Parklatz rechts vom Zaun.

Ort: 🎀Horizons🎀Schneiderei - Orchardvile Ave. 55 
       #Cypressflats17

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/20210211165257-1.0D77T
https://pic.statev.de/image/20210211165319-1.0DFE0

**Comment by DrGrizzlY17** [comment]
Habe den Entladepunkt auf eure Seite versetzt. Ist deutlich Ressourcenfreundlicher als den Zaun zu entfernen.

PS: Wie seit ihr die ganze Zeit auf das Gelände vom Entladepunkt gefahren? :D

**Comment by Dean-Gallagher** [comment]
@DrGrizzlY17 Etwas ältere Bilder aber genau so. 

https://pic.statev.de/i/0wWzm.jpg
https://pic.statev.de/i/0wKdS.jpg

**Comment by DrGrizzlY17** [comment]
@Dean-Gallagher Ah ok, ja da wo der pinke Burrito ist die höhe kommt jetzt der Marker hin in die Mitte^^

**Comment by Dean-Gallagher** [comment]
@DrGrizzlY17 Danke dir Ehre
