### ISSUE TITLE
Ui ausblenden über # erweitern

### ISSUE THREAD

**Issue by Mr-Chris-VRTY** [mexyn/statev_v2_issues#1219]
Heyho zusammen
Es wäre schön, wenn das Ausblenden der UIs mit # noch erweitert werden könnte, indem es auch Werbeanzeigen von Firmen/Banken usw. ausblendet, damit diese beim Fahren mit dem Auto oder Laufen nicht einblenden.
Danke im Vorraus :)

**Comment by AlexSchneiders** [comment]
Würde es mal mit F7 probieren.

**Comment by DrGrizzlY17** [comment]
Möglichkeit besteht über F7, wie bereits erwähnt
