### ISSUE TITLE
Keine 2 Simkarten gleichzeitig zum Telefonieren nutzbar

### ISSUE THREAD

**Issue by Headmonsta** [mexyn/statev_v2_issues#122]
**Character Name**
Uri_Holiday hat beobachtet, mit Jonny_Parkinson, John_Vernon, Willy_Wollbaer getestet

**Zeitpunkt (Datum / Uhrzeit)**
27.08.2020 19:30

**Beobachtetes Verhalten**
Wenn man eine Simkarte eingelegt hat (beispielsweise die 1822-912) und diese nicht als Hauptsim markiert hat. Bekommt man keine Notfall anrufe. Dies gilt für alle anderen Anrufe auf den Sims genauso. Heißt im Umkehrschluss, es können keine 2 Simkarten benutzt werden bzw man kann keine weiteren Anrufe über weitere Nummern bekommen.

**Erwartetes Verhalten**
Unserer Meinung sollte man wenigstens 3 Simkarten markieren können wo man anrufe bekommt um z.b. Firmennummern oder Private Nummern trotzdem zu haben.

**Schritte um den Fehler nachvollziehen zu können**
2  Simkarten im Telefon, eine Markiert im Einstellungsmenu, auf der anderen kann kein Anruf kommen

**Comment by tastydev** [comment]
Dies ist kein Bug sondern eine Designänderung mit der ihr euch in Zukunft arrangieren müsst. Es gab technische, sowie rp-technische Hintergründe für diese Entscheidung.
