### ISSUE TITLE
Konversation einer Simkarte nicht vom Besitzer löschbar

### ISSUE THREAD

**Issue by RubyWer** [mexyn/statev_v2_issues#1221]
**Character Name**
 Zed Wert

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.02.2021, 19Uhr

**Beobachtetes Verhalten**
 Hab eine Simkarte mit Nummer von einem Freund bekommen, mit der ich eine Konversation erstellt habe. Diese Konversation lässt sich bezüglich Beschreibung, Name, Admin und Teilnehmer entfernen, nicht ändern. Selbst der ursprüngliche Besitzer der Simkarte kann die Konversation nicht bearbeiten etc. obwohl diese Simkarte Admin der Konversation ist. Es taucht die Fehlermeldung "Ein Fehler ist aufgetreten:" in Orange auf. Auch nicht im StateNet, im Internet veränderbar. Support meinte, dass weil der nicht-Besitzer die Konversation erstellt hat, ist sämtliches Bearbeiten scheinbar blockiert, auch für den Besitzer.

**Erwartetes Verhalten**
Konversation sollte vom Besitzer der Simkarte bearbeitet werden können, unabhängig davon, wer diese erstellt hat.

**Schritte um den Fehler nachvollziehen zu können**
Simkarte von einem Freund nehmen, Konversation erstellen, Konversation ist unveränderlich.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Verbesserungsvorschlag**
Simkarte kann, wie mit Autos auch, den Besitzer wechseln, wenn der Besitzer es veranlasst.

**Comment by its4l3x** [comment]
Wird erstmal leider nicht kommen. Nur der Besitzer kann die Konversation löschen.

Wenn es da irgendwelche Probleme o.ä. gibt, dahingegen im Support melden, dann wird das nochmal besonders geprüft.
