### ISSUE TITLE
Einige Interaktionen nicht mehr ausführbar

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1222]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.01.2021  gg. 16:00 und 17:20

**Beobachtetes Verhalten**

Es war nicht mehr möglich einige Interaktionen auszuführen(es passierte nichts), wie: Funk über U Inventar über I, oder über X-Menü Person durchsuchen, Ticket ausstellen und viele andere Funktionen über X-Menü (bsp. am Auto) gingen aber noch.

War heute zum ersten Mal, und dann gleich zweimal innerhalb einer Stunde. Konnte nur durch Neustart von Alt-V behoben werden.

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

?

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Hast du irgendwas gemacht, was das ausgelöst hat?
Hast du es reproduzieren können?

**Comment by JannikDatsch** [comment]
Habs probiert das irgendwie zu reproduzieren, bisher nicht gelungen. Sollte ich da iwas zu finden, schreib ich es rein

Habs auch reingestellt, dass vlt. wer anders da auch noch was zu sagen kann, der das vlt. hatte, weil wie beschrieben ist das noch nie aufgetreten, und dann plötzlich zweimal in ner Stunde.

**Comment by DonVitoDiangelo** [comment]
ggf. erneut öffnen

**Comment by JannikDatsch** [comment]
https://statev.de/forum/list/index.php?thread/12189-x-menü-inventar-tel-tablet-öffnet-sich-nicht-mehr/

**Comment by JannikDatsch** [comment]
https://statev.de/forum/thread/12848-statev-ui-buggt-gta-funktioniert-normal/?postID=114357#post114357

Ein Lösungsvorschlag hier: 
"Hab mal rumprobiert und glaube als adminstrator ausführen ODER echtzeitschutz beim windows defender scheint das Problem relativ konsistent zu fixen, zumindest für mich."
