### ISSUE TITLE
Crash am Flugfeld in Sandy Shores

### ISSUE THREAD

**Issue by SpeedRaiseR1337** [mexyn/statev_v2_issues#1223]
Volkan Jaman

Auftrittszeitpunkt (Datum / Uhrzeit)
23.02.2021 18:27

In welcher Region ist der GameCrash aufgetreten? (Screenshot oder PLZ von der Map)
Sandy Shores Flugfeld Tankstelle richtung Sandy Shores

Fahrzeuge in der Nähe gesehen? Wenn ja, welche?
Kann ich jetzt so nicht sagen könnte man im VOD gucken ( twitch.tv/speedraiser )

Optional: Crashdump (im altV Ordner hinterlegt)
Falls du ein Crashdump besitzt
[altv_2.12_Social Club_0x5ea3f0_23-02-2021_18-27-16.zip](https://github.com/mexyn/statev_v2_issues/files/6031476/altv_2.12_Social.Club_0x5ea3f0_23-02-2021_18-27-16.zip)

**Comment by SpeedRaiseR1337** [comment]
![GTA5 2021-02-23 20-37-08](https://user-images.githubusercontent.com/76440262/108899340-98d01b00-7618-11eb-8c48-2986ebb09369.png)

**Comment by DrGrizzlY17** [comment]
#1141

**Comment by MisterCopeland** [comment]
#1143
