### ISSUE TITLE
Anpassung der Gesetze im StateCom

### ISSUE THREAD

**Issue by lavouuzu** [mexyn/statev_v2_issues#1224]
**Character Name** Valentin Dubois

**Auftrittszeitpunkt (Datum / Uhrzeit)** 23.02.

**Beobachtetes Verhalten** Gesetzte im StateCom sind nicht mehr aktuell. Sprich man kann einige der Straftatbestände in der Aktenvorlage nicht mehr auswählen. Wäre cool wenn das an das aktuelle Strafgesetzt angepasst werden würde.

**Comment by its4l3x** [comment]
Habe ein kleines System dazu gebaut. + noch eine kleine Überraschung. ;)
