### ISSUE TITLE
Erste Hilfe Kästen werden verbraucht obwohl es nicht nötig ist

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#1225]
**Character Name**

Sven Rosenbach
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Jeder Zeit
**Beobachtetes Verhalten**

Wenn man als MDler im Dienst versucht Leute zu heilen, die keine Behandlung brauchen verbraucht es einen Erste-Hilfe Kasten.
**Erwartetes Verhalten**

Das keiner verbraucht wird, da keine Behandlung stattfindet 
**Schritte um den Fehler nachvollziehen zu können**

1. Man suche sich eine Person mit vollem Leben
2. Man versucht sie zu heilen und bekommt die Nachricht, dass die Person keine Behandlung benötigt
3. Erste-Hilfe Kasten ist weg
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://user-images.githubusercontent.com/58612983/108993949-7df2ba80-769b-11eb-827d-2c348bfb155b.mp4

**Comment by its4l3x** [comment]
Fixed next update
