### ISSUE TITLE
Frisuren buggen durch Sheriff Hut

### ISSUE THREAD

**Issue by AngelMaravilla** [mexyn/statev_v2_issues#1228]
**Character Name**
Angel Maravilla

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.02.2021

**Beobachtetes Verhalten**
Frisuren buggen/glitchen durch den Sheriff Campaign Hat hindurch (auch non-mod Haare)

**Erwartetes Verhalten**
Wie auf v1 ohne Durchbuggen

**Schritte um den Fehler nachvollziehen zu können**
Mit einem Char die entsprechende Uniform mit Hut anziehen

![image](https://user-images.githubusercontent.com/74780492/109193706-f2f7ea00-7798-11eb-9c4d-1caa6fc95442.png)
![image](https://user-images.githubusercontent.com/74780492/109193720-f5f2da80-7798-11eb-8646-25350c2a3bed.png)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by milkdrops** [comment]
Bei einigen Frisuren umgehbar durch Hüte, die man im ','-Menü anzieht.

**Comment by TheOutburst** [comment]
Gleiches Verhalten bei einer LSPD Cap
https://cdn.discordapp.com/attachments/721764106394140684/817086022546358333/unknown.png
