### ISSUE TITLE
Paleto Bay Medical Center

### ISSUE THREAD

**Issue by MisterCopeland** [mexyn/statev_v2_issues#1229]
Character Name
Paddy Copeland

**Auftrittszeitpunkt (Datum / Uhrzeit)**
24.02.2021 // Abends

**Beobachtetes Verhalten**
Das Paleto Bay Medical Center MLO ist ein wenig buggy. Siehe Bilder. 

**Erwartetes Verhalten**
Änderung des MLO, weil dies ja durch das MLO kommt und nicht durch die Entwicklung. Das vorgeschlagene MLO ist offener und freundlicher gestaltet. Für das MD dadurch auch reizvoller zu bespielen. 

Aktuelles MLO -> https://de.gta5-mods.com/maps/mlo-paleto-bay-medical-center
Vorgeschlagenes MLO ->https://de.gta5-mods.com/maps/mlo-paleto-bay-hospital-add-on-sp-fivem-ragemp

Bilder des Problems
So steht man: https://ibb.co/cw2T424 , 
So sieht es aus in der 3th Person View: https://ibb.co/z4MJyqN 
und so in der POV: https://ibb.co/sVw8Zcw

**Comment by DonVitoDiangelo** [comment]
Abgelehnt. Da ist auch nichts buggy, das sind Vorhänge.

**Comment by MisterCopeland** [comment]
Ich verstehe mal wieder nicht das Problem. Nachdem man sich mit einigen Spielern die aktiv im MD spielen unterhält sind unter anderem diese Vorhänge ein Grund warum das MLO nicht wirklich bespielt wird.
Verstehe also nicht warum für die aktiven Spieler dieses Servers nicht etwas geändert wird. 

_"....Mit V2 und auch in Zukunft wollen wir uns, dort wo es möglich ist, von Teleport-Markern distanzieren und lieber begehbare Häuser schaffen, wo man rein/rausschauen kann und nicht die Gefahr hat wegen komischen Texturproblemen unter den Boden zu fallen. Im Zuge dieses Updates haben wir etliche neue Interiors geschaffen und fast alle selbst erstellten Interiors mit “Runterfallgefahr” entfernt. Außerdem gehört Regen und Schnee innerhalb der neuen Interiors nun der Vergangenheit an.

Viele Interiors kommen nicht aus unser eigenen Hand. Manche haben wir erworben, andere stehen der Community kostenlos zur Verfügung. Deshalb hier nochmals ein Dank an die Creator...."_

Von dem Text merkt man in den letzten Monaten garnichts.
