### ISSUE TITLE
Rucksack buggt bei rtw durch

### ISSUE THREAD

**Issue by Chrinis007** [mexyn/statev_v2_issues#123]
**Character Name**
Christian_Maier

**Zeitpunkt (Datum / Uhrzeit)**
Vor 1 Minute

**Beobachtetes Verhalten**
Tasche bugged durch

**Erwartetes Verhalten**
unisichtbar von außen

**Schritte um den Fehler nachvollziehen zu können**
rucksack anziehen
in den rtw hinten setzen

**Optional: Video / Bilder des Fehlers**
![grafik](https://user-images.githubusercontent.com/70342279/91480755-b576da80-e8a3-11ea-97d8-573781bc38a3.png)

**Comment by eiksch** [comment]
Wir werden mal besprechen müssen, ob wir daran überhaupt etwas ändern.

**Comment by Chrinis007** [comment]
Wurde daran was geändert?
