### ISSUE TITLE
Automatisches Wegparken von Fahrzeugen

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1230]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer zum Restart

**Beobachtetes Verhalten**
Keine Ahnung ob Bug, oder gewollt:
Wenn eine Hausgarage voll ist, können bei einem Restart trotzdem naheliegende Fahrzeuge automatisch in diese Garage geparkt werden.
Meine Hausgarage fasst 6 Fahrzeuge hatte aber vorhin 8 Fahrzeuge drinnen stehen.

**Erwartetes Verhalten**
Das wenn die Garage voll ist, die Fahrzeuge in die nächstgelegene Öffentliche Garage geparkt werden.
( Habe allerdings auch kein Problem damit, wenns so bleibt ;) )

**Schritte um den Fehler nachvollziehen zu können**
Garage Voll machen, fahrzeuge am Haus stehen lassen und warten bis es automatisch eingeparkt wird.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
ist so gewollt. :)
