### ISSUE TITLE
Animationen weg

### ISSUE THREAD

**Issue by AniballCosta** [mexyn/statev_v2_issues#1231]
**Aniball Costa**

**26.02.2021 - 12 Uhr (Datum / Uhrzeit)**

**die unter Favoriten gespeicherten Animationen sind plötzlich weg und nicht wieder aufgetaucht nach einem Neustart**

**Animationen sollten vorhanden sein**

**Animationen waren auf 0 zurückgesetzt**

**4K(nur wenn Falsche Darstellung in der UI)**

**Comment by its4l3x** [comment]
Ist kein Bug, sondern ein Lokales Problem. Eure Animationen speichert ihr selber in eurem resourcen Ordner im alt:V Ordner. Wenn dieser gelöscht wird oder du auf einmal über eine andere Methode connectest (wie z.B. Direct Connect, dann auf einmal über Master List dich verbindest) entsteht diese Situation.


Daher closed
