### ISSUE TITLE
Karton-Animation läuft weiter, obwohl dieser nicht mehr Inventar ist

### ISSUE THREAD

**Issue by No1likeyou** [mexyn/statev_v2_issues#1232]
**Character Name**
Ben_Stark

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.02.2021 um 9.25 Uhr

**Beobachtetes Verhalten**
Ich hielt das Item "Pappkarton" in der Hand und legte den in meinen Spind. Die Animation (Karton wird getragen) wurde weiterhin ausgeführt.

**Erwartetes Verhalten**
Nachdem der Karton im Spind liegt, wird die Animation beendet.

**Schritte um den Fehler nachvollziehen zu können**
1. Pappkarton aus dem Inventar mit Rechtsklick ausrüsten.
2. Pappkarton in Spind legen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://drive.google.com/file/d/138WFd6HGnr1pL34wtvPpqTQ11NC_crAW/view?usp=sharing

**Comment by DonVitoDiangelo** [comment]
ja, das ist "normal". Die item Bound Animations beendest du normal wie alles andere auch.
