### ISSUE TITLE
Handy - Anrufliste

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#1236]
**Character Name**
Marvin_Elpe

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit heute

**Beobachtetes Verhalten**
Anrufliste ist bei 2k ziemlich groß geraten.
Zusätzlich werden Anrufe nicht mehr in der Liste angezeigt, wenn die Person nicht erreichbar ist.

**Erwartetes Verhalten**
Anrufliste wird angepasst und ausgehende Anrufe werden korrekt angezeigt.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
2k

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/33394632/109541647-539e6400-7ac4-11eb-8e21-721a77115e4f.png)

**Comment by Hutstaender** [comment]
Sieht vllt. am Anfang etwas befremdlich aus. Vor allem bei Auflösungen größer FullHD, weil die Texte dort die ganze Zeit nicht mit hochskaliert wurden. Verglichen mit anderen Apps sind die Schriftgrößen jetzt allerdings endlich mal einheitlich. Nehm dir beispielsweise mal die Kontaktliste als Pic daneben, die Schrift dort ist nur unwesentlich größer, da Überschriften.
Unsere Phones sehen mit einer Ausnahme nun endlich auf jeder Auflösung gleich aus. Die Ausnahme sind die Ecken, je höher die Auflösung desto eckiger das Phone 🍡
