### ISSUE TITLE
Handy buggt am Ohr

### ISSUE THREAD

**Issue by OfcStern** [mexyn/statev_v2_issues#1237]
**Character Name**
 
Marcel_Stern

**Auftrittszeitpunkt (Datum / Uhrzeit)**

01.03.2021 19:20 +-

**Beobachtetes Verhalten**

Nach Absetzen eines Notrufes blieb die Hand am Ohr und ließ sich auch nicht "wegnehmen".
Edit: Obwohl der Dispach geschlossen und gelöscht wurde. (Und somit nicht mehr vorhanden war)
Andere Animationen unterbrechen die "Hand am Ohr" Animation nur, beenden sie aber nicht.
Relogg hat das Problem gelöst.

**Erwartetes Verhalten**

Nach Auflegen durch den Operator sollte die Animation (Handy am Ohr) beendet werden.

**Schritte um den Fehler nachvollziehen zu können**

F2 -> Notruf -> LSPD Notruf absetzen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Handy](https://user-images.githubusercontent.com/79868317/109542132-f5be4c00-7ac4-11eb-89b4-71e7ccf715a5.png)

**Comment by OfcStern** [comment]
Nach Relogg ist das Problem nicht mehr aufgetreten.

**Comment by its4l3x** [comment]
Sorry - falsch gelesen. Ist kein Bug. Es war von Anfang an geplant, Animationen damit zu versehen, dies ist nun mit einem Phone Rework passiert, es ist normal das du den Hörer am Ohr hast, denn du wartest ja bis sich jemand mit dir verbindet ;)

Daher kein Bug, closed

**Comment by OfcStern** [comment]
"denn du wartest ja bis sich jemand mit dir verbindet ;)"  

Richtig lesen. Der Operator hat den Dispach angenommenen, aufgelegt und der Dispach wurde geschlossen und gelöscht und war somit nicht mehr aktiv. Die Animation war jedoch weiterhin aktiv und ließ sich nicht beenden.

**Comment by its4l3x** [comment]
Alles klar. Danke für die Korrektur. Schauen das uns nochmal an.

**Comment by its4l3x** [comment]
Kannst du mir genau sagen, was passiert ist, wie z.B. Hast du abgebrochen? Hast du das Bild mit Streife auf Anfahrt gesehen? Etc... Am besten den kompletten Ablauf. Würde mir persönlich sehr helfen.

**Comment by OfcStern** [comment]
Wir wollten testen, wo und wie die Meldung bei einem eingehendem Dispatch kommt.
Ich hab also einen Notruf abgesetzt und der wurde dann angenommen, geschlossen und gelöscht. Die Hand blieb am Ohr und konnte nicht mehr "entfernt" werden.

**Comment by its4l3x** [comment]
Ok - schaue ich mir die Tage an. Momentan etwas alles ein bisschen stressig :D

**Comment by its4l3x** [comment]
Sorry für die etwas spätere Antwort. Gehe erst jetzt wieder die Issues durch. Durch das drücken auf Ok, beendet sich die Animation erst final. Daher immer auf Ok am Ende auf dem Handy drücken, dann wird auch das Handy wegbewegt.
