### ISSUE TITLE
Telefonat auf Simkarte kann nur noch von einer Person angenommen werden

### ISSUE THREAD

**Issue by masterppc** [mexyn/statev_v2_issues#1239]
**Character Name**
Hans Hentschel
**Auftrittszeitpunkt (Datum / Uhrzeit)**
immer
**Beobachtetes Verhalten**
Wenn jemand die Gang Unit Nummer anruft kann nur noch einer dran gehen bei den anderen verschwindet dann sofort das Telefonat.
**Erwartetes Verhalten**
Es können mehr Teilnehmer teil nehmen

**Schritte um den Fehler nachvollziehen zu können**
Nummer anrufen die mehrere Personen aktiv haben
 Drag & Drop -->

**Comment by its4l3x** [comment]
Das ist Teil des neuen Handy Systems, daher gewollt und kein bug.

closed
