### ISSUE TITLE
Browser Favoriten-Label anpassen

### ISSUE THREAD

**Issue by saltym** [mexyn/statev_v2_issues#1240]
Eliot_Moore

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Favoriten-Label hat doppelten Background

**Erwartetes Verhalten**
Zweiten Background entfernen und evtl. die Border vom Label entfernen

**Schritte um den Fehler nachvollziehen zu können**
Tablet öffnen, auf Browser gehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
https://prnt.sc/10ar46w

**Comment by KingMarcel** [comment]
Hey, inwiefern doppelten Background?

**Comment by saltym** [comment]
Musst die Bildschirmhelligkeit mal hochschrauben. 
https://pic.statev.de/i/OXFfB.png
