### ISSUE TITLE
Anruf nach Fehlgeschlagenem Versuch nicht in der Anrufliste

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1241]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.03.21 - 23:50

**Beobachtetes Verhalten**
Wenn ich versuche eine Person zu erreichen, welche gerade nicht erreichbar ist. Ist der Anrufversuch anschließend nicht in meiner Anrufliste drin.

**Erwartetes Verhalten**
 Das der Anruf in meiner Liste angezeigt wird, auch wenn ich die Person nicht erreiche.

**Schritte um den Fehler nachvollziehen zu können**
Person anrufen die nicht da ist, und anschließend die Anrufliste checken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=7cCxTqeEt0M

**Comment by TheBroady** [comment]
nvm Dublicate
https://github.com/mexyn/statev_v2_issues/issues/1236

**Comment by its4l3x** [comment]
Nene, kannste schon offen lassen. Das hier ist was anderes. Schaue mir das mal an.

**Comment by its4l3x** [comment]
changed, next update
