### ISSUE TITLE
Bootswerkstatt nicht mehr nutzbar

### ISSUE THREAD

**Issue by Montifero** [mexyn/statev_v2_issues#1242]
**Character Name**
Rene_Ballista

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.03.2021 / 22:00 Uhr

**Beobachtetes Verhalten**
Kein Reparieren und Lackieren mehr möglich / Keine Marker mehr vorhanden

**Schritte um den Fehler nachvollziehen zu können**
Besuch der Bootswerkstatt im Nordosten.

**Bilder des Fehlers**
- Marker Reparaturtisch fehlt -> https://photos.app.goo.gl/WhDsmuiArAwwn2pH9
- Marker Lackiermaschine fehlt -> https://photos.app.goo.gl/1dHnCoC4gZtuDh6B8

**Comment by DonVitoDiangelo** [comment]
my bad, punkte sind nach unten verschoben worden, sry.  Nächstes update fixed.

**Comment by Montifero** [comment]
Alles gut, kann passieren ;-)
Danke fürs rasche erledigen!
