### ISSUE TITLE
Sprachanzeige/Mikrofonanzeige

### ISSUE THREAD

**Issue by Gee1337** [mexyn/statev_v2_issues#1243]
**Gee_Rodriguez**

**Beobachtetes Verhalten**

Benutzt man push to talk, ist die Mikrofonanzeige kontinuierlich gemuted (Bild 1). Unabhängig davon, ob man nun tatsächlich sein Mikrofon gemutet hat oder nicht. Die schwarz unterlegte Anzeige für die Sprachreichweite ist komplett weg. Redet man im Spiel, ist wie erwartet die grün unterlegte Anzeige aktiv (Bild 3). 
Daraus entstehen zwei Probleme. Man sieht gar nicht mehr, ob man nun wirklich mutet ist im Teamspeak/IC und man kann die aktuelle Sprachreichweite nicht sehen. Man muss also entweder sprechen, um zu sehen wie weit diese eingestellt ist oder ständig Z drücken um sicherzugehen, dass man nicht rumschreit.

**Erwartetes Verhalten**
Bild 1 nur, wenn man wirklich gemutet ist.
Bild 2, wenn man nicht gemutet ist und nicht spricht.
Bild 3, wenn man aktuell spricht.

**Schritte um den Fehler nachvollziehen zu können**

Push to talk aktivieren

**Optional: Video / Bilder des Fehlers**

![mic1](https://user-images.githubusercontent.com/70242468/109630887-b5eb7900-7b45-11eb-9848-99201fc134b7.PNG)
![mic2](https://user-images.githubusercontent.com/70242468/109631760-91dc6780-7b46-11eb-8c67-3be5e8e57940.PNG)
![mic3](https://user-images.githubusercontent.com/70242468/109631774-956fee80-7b46-11eb-87ad-80fe0cb9b538.PNG)

**Comment by masterppc** [comment]
Habt ein Herz für p2t User :D bin jedes mal nur am z drücken um zu gucken wie weit ich gerade rede
