### ISSUE TITLE
MD StateCOM Überlappung von Icons

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#1244]
**Character Name**

Sven Rosenbach
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer
**Beobachtetes Verhalten**

Icons im neuen MD StateCOM überschneiden sich 
**Erwartetes Verhalten**

sollten sie halt nicht
**Schritte um den Fehler nachvollziehen zu können**

MD StateCOM öffnen, Anmelden und obere rechte Seite anschauen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

Sowohl IC bei 2560x1440p als auch in Chrome bei 1920x1080
**Optional: Video / Bilder des Fehlers**

![image](https://user-images.githubusercontent.com/58612983/109650625-c3146200-7b5d-11eb-97ef-e4781c6b3ea6.png)

**Comment by its4l3x** [comment]
alrdy solved und prod. geschaltet
