### ISSUE TITLE
Dispatch System Meldung

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1245]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit 01.03 später Abend  / 02.03 14:08

**Beobachtetes Verhalten**
Man erhält aktuell wieder KEINE Meldung über einen neuen Dispatch, wenn man als LST eingestempelt ist. Das sollte wohl durch eine Feature mit dem gestrigen Abend anders sein, und hat auch gestern Abend kurzzeitig geklappt.

**Erwartetes Verhalten**
Man sollte jetzt auch wenn man das LST System nicht offen hat, als LST über eingegange Dispatches per Nachricht informiert werden

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Auch solved.

Ich muss euch aus dem Speicher werfen, wenn einer Disconnected, weshalb ihr nun euch immer neu einstempeln müsst bei einem Disconnect o.ä.
