### ISSUE TITLE
 Ressourcenexport nicht möglich

### ISSUE THREAD

**Issue by BenniButlack** [mexyn/statev_v2_issues#1248]
**Character Name**
Benni Butlack

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.03.2021 - 17:50 Uhr

**Beobachtetes Verhalten**
Trotz aufgeschlossenem Burrito und offenem Kofferraum war es nicht möglich, etwas zu exportieren. Fehlermeldung: "Der Verkauf kann nicht durchgeführt werden." (siehe Screenshots)
![Desktop Screenshot 2021 03 02 - 17 54 07 43](https://user-images.githubusercontent.com/79930909/109685683-c883a380-7b81-11eb-9808-91c124d50257.png)
![Desktop Screenshot 2021 03 02 - 17 54 23 96](https://user-images.githubusercontent.com/79930909/109685692-ca4d6700-7b81-11eb-8a4b-dc766a82cbdc.png)

**Erwartetes Verhalten**
Ware hätte aus dem Burrito verkauft werden müssen.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Prüfe bitte dein Bankkonto. Diese Meldung kommt, wenn du zu wenig Geld hast, oder du keine Anzahl eingeben hast, wie viel du exportieren willst.

**Comment by BenniButlack** [comment]
Bedienungsfehler meinerseits!
