### ISSUE TITLE
Uboot - kein Kofferraum Zugriff mehr möglich

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1249]
Früher konnte man auf den Kofferraum zugreifen wenn man hinten auf dem Uboot stand, nun kommt man weder von oben noch von innen an den Kofferraum her ran...
Daher ist ein Be und Entladen des Kofferraums nicht möglich...

**Comment by its4l3x** [comment]
Wir haben nichts am Handling verändert im letzten Update... Bist du dir da ganz Sicher?

**Comment by Statev-Bonsai** [comment]
ja, habs eben versucht weil ich den kofferraum beladen wollte...
ich werde es nachher nochmal versuchen :)

**Comment by Statev-Bonsai** [comment]
vorhin hat es dann wieder geklappt.. komisch
