### ISSUE TITLE
Schwarze Umhängetasche im MD Dienst nicht sichtbar

### ISSUE THREAD

**Issue by 48619** [mexyn/statev_v2_issues#125]
**Character Name**
Magdalena Kurowska

**Zeitpunkt (Datum / Uhrzeit)**
26.08 - 27.08

**Beobachtetes Verhalten**
Eingestempelt im MD Dienst, wird die schwarze Umhängetasche nicht angezeigt.
Bei erstellung der Dienstkleidung wurde keine Tasche gewählt, das Feld wurde bei erstellung der Kleidung nicht benutzt.

Bisher nur mit der Schwarzen Umhängetasche beobachtet.
Andere Taschen am selben Char wurden angezeigt.

**Erwartetes Verhalten**
Schwarze Umhängetasche sollte im Dienst auch sichtbar sein.

**Schritte um den Fehler nachvollziehen zu können**
MD Dienst einstempeln und ein Outfit ohne Tasche wählen.
Dabei spielt es keine Rolle ob Tasche vorher schon angelegt war oder nicht.

**Comment by r3sist3nt** [comment]
Welches Outfit hattest du an? Das ist wichtig.

**Comment by 48619** [comment]
Outfit ist ein Supreme Schneecamo Hoodie als Dienstkleidung des LSMD

**Comment by its4l3x** [comment]
Hast du auch schon mal versucht die Tasche erst nachdem in den Dienst gehen wieder anzusetzen?

**Comment by 48619** [comment]
Alles versucht, diese Tasche wird nicht angezeigt.
Andere Taschen werden ganz normal angezeigt.

**Comment by its4l3x** [comment]
Sollte mit dem neuen Team-Skin Menü bereits gefixed sein - Daher Closed
