### ISSUE TITLE
Zigarette verschwindet beim Funken

### ISSUE THREAD

**Issue by JimmyHernandez2** [mexyn/statev_v2_issues#1250]
Jimmy_Hernandez

Ständiges auftreten
Hat man sich eine Zigarette angezündet, raucht und funkt dann, verschwindet die Zigarette und selbige wird nicht mehr geraucht. Dies passiert jedoch nicht bei Nutzung von Handy oder Tablet oder Essen

**Erwartetes Verhalten**
Möglichkeit des weiter rauchens während des Funkens

**Comment by its4l3x** [comment]
Wird erstmal so bleiben und nicht weiter beobachtet bzw. in naher Zukunft gefixed.
