### ISSUE TITLE
Lagerfeuer zündet bei Platzierung an

### ISSUE THREAD

**Issue by LukaEnis** [mexyn/statev_v2_issues#1251]
Charakter Name: Luka_Enis

Auftrittszeitpunkt (02.03.2021; ~22:00 Uhr)

Hervorgerufenes Verhalten
Beim Vorgang des platzieren (in Hock Animation) eines Lagerfeuers werden Mitspieler und der Charakter selbst teils angezündet.

Erwartetes Verhalten
Lagerfeuer entzündet erst nach der finalen Platzieren und nicht in der Animation

**Schritte um den Fehler nachvollziehen zu können**
1. Animation für Hocken ausführen
2. Lagerfeuer im Inventar rechtsklicken
3. Position suchen (dabei entzündet man sich meist selbst)

Keine Bilder/Videos vorhanden.

**Comment by DonVitoDiangelo** [comment]
Könne wir nicht ändern. Bitte normal im stehen aufstellen
