### ISSUE TITLE
Fahrzeugproduktion: BF Club 43PS fehlerhaft

### ISSUE THREAD

**Issue by ZacCooperr** [mexyn/statev_v2_issues#1252]
**Zac Cooper**

**02.03.2021 / 22:55**

**Das Material und der Motor liegen in der Maschine und augenscheinlich ist auch die Produktion vom BF Club 43/PS möglich.
Sobald man auf "Produktion starten" am Terminal klickt, erhält man unten links ein rotes Fenster mit dem Hinweis: Fehler in der Konfiguration der Produktion!**

**Die Produktion sollte stattdessen startet.**

1.) Motor in die Maschine
2.) Angezeigtes Material in die Maschine
3.) Ans Terminal gehen und Produktion starten klicken

**Optional: Video / Bilder des Fehlers**
![BFClub](https://user-images.githubusercontent.com/74767269/109720764-ca159180-7baa-11eb-9340-197dc03d7f66.JPG)

**Comment by DonVitoDiangelo** [comment]
Scroll innerhalb des Clubs einmal herunter um alle benötigten Ressourcen zu sehen. ;)

**Comment by ZacCooperr** [comment]
Alle Ressourcen wurden zwei mal geprüft und sind vorhanden(grün). Erkennen ist dies an "**Nur herstellbare Gegenstände anzeigen**" sowie seitlich an der **Menge 1**. Ich habe testweise noch 4x Dose schwarzer Lack hinzugefügt, da es bei diesem Wagen fehlt. Leider ohne erfolg.

Weiterhin die Meldung: Fehler in der Konfiguration der Produktion! 
Kann gerne heute Abend alle Ressourcen auflisten, falls benötigt.

**Comment by DonVitoDiangelo** [comment]
Ja, bitte mla alles konkret auflisten und bebildern. Gibt es vllt irgendwo ein Übersetzungsfehler? Sollte eigentlich funktionieren

**Comment by DonVitoDiangelo** [comment]
nvm. Fehler gefunden, my bad. fixed next update :)

**Comment by ZacCooperr** [comment]
Super danke :)
