### ISSUE TITLE
Waffen Zubehörteile im Ammunation

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1253]
Soll man die auch dort anbieten können?
Im Moment kommt der Fehler Falsche Transportgruppe wenn man sie in die Theke legen möchte.

ABER man weiß ja net ob es so gewollt ist (dann ist es kein bug) oder aber andersherum ;D

**Comment by DonVitoDiangelo** [comment]
nein, nicht gewollt. :) Straßenhandel
