### ISSUE TITLE
Auftragsexport schlecht verteilt

### ISSUE THREAD

**Issue by Eisdealer** [mexyn/statev_v2_issues#1254]
Jack_Grafenhorst

Seit Update am 01.03.2021

im Auftragsexport kommen so gut wie keine Produkte mehr für die Verpackung. Das einzige Produkt das ich seit Montag gesehen habe waren Zigarettenboxen. Ich bin mir auch nicht sicher ob man dies als Bug bezeichnet, aber ich hoffe mal es ist nicht gewünscht

Mehr verschiedene Aufträge damit jede Firmenart eine Chance bekommt etwas abzusetzen.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Ja, sind aktuell ein paar weniger und auch andere. Aber da wird es mit der Zeit Abwechslung geben.

**Comment by Eisdealer** [comment]
Ein paar weniger wäre ja durchaus OK. Aber gar keine ist halt echt bescheiden. Hätte ja sein können das ihr in der Verteilung einen Fehler habt. --Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 03.03.21, 15:30 schrieb DonVitoDiangelo <notifications@github.com>:

   
  Ja, sind aktuell ein paar weniger und auch andere. Aber da wird es mit der Zeit Abwechslung geben.
