### ISSUE TITLE
Bobcat kann nicht zurück gegeben werden

### ISSUE THREAD

**Issue by masterppc** [mexyn/statev_v2_issues#1256]
**Character Name**
Hans Hentschel
**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.03.21 21.00 Uhr
**Beobachtetes Verhalten**
Bobcat kann nicht zurück gegeben werden. Fahrzeug ist repariert vollgetankt und Kofferraum ist leer.

**Erwartetes Verhalten**
Zum Verleih fahren hupen und Auto abgeben

**Schritte um den Fehler nachvollziehen zu können**
Mit einem Bobcat zum Fahrzeugverleih? Der Bobcat ist aber auch alt keine Ahnung ob es da Änderungen gab. Der Roller musste damals auch administrativ gelöscht werden weil es ihn nicht mehr im Verleih gibt.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
2k

**Optional: Video / Bilder des Fehlers**
https://i.imgur.com/r1qHy2Z.jpg

**Comment by its4l3x** [comment]
Da fehlt die return Config (Zurückgabe der Fahrzeug für diesen Autoverleih). Ein GD Problem.

**Comment by masterppc** [comment]
Ahhh also bei nem anderen Verleih geht es dann?

**Comment by its4l3x** [comment]
jo probier mal sandy oder so da geht das ^^

**Comment by masterppc** [comment]
jo hab nen anderen genommen hat geklappt hätte ich ma eher drauf kommen können xd dann is das nur der unten am flughafen

**Comment by DrGrizzlY17** [comment]
Mit dem nächsten Update kannste dir neu mieten und da abgeben :D
