### ISSUE TITLE
Versetzen des Auspark /-Lagerpunkt der Werkstatt

### ISSUE THREAD

**Issue by Husky2002** [mexyn/statev_v2_issues#1257]
**Character Name**
Eddy Husky

Wir würden uns Wünschen, dass die Punkte nochmals überarbeiten werden.

**Optional: Video / Bilder des Fehlers**
![Ausparkpunk](https://user-images.githubusercontent.com/61657852/109842860-c9343c80-7c4a-11eb-9a2e-2a17b2791a98.jpg)
![Lagerpunkt](https://user-images.githubusercontent.com/61657852/109842862-c9ccd300-7c4a-11eb-8251-7cabfd497116.jpg)

Rot = Alte Position Grün = Neue Position

**Comment by DrGrizzlY17** [comment]
Also wenn ich euch den Fahrzeugpunkt fürs Ein-/ Ausparken flippen eure LKWs dann wieder. Wenn das für euch ok ist, dann gerne.

Den Entladepunkt versetze ich gern

**Comment by Husky2002** [comment]
Also lag das Flippen garnicht an der wand?

StateV_Dan <notifications@github.com> schrieb am Do. 4. März 2021 um 16:14:

**Comment by DrGrizzlY17** [comment]
Nein das Flippen lag daran dass das Fahrzeug komplett grade spawnen und somit in der rampe hinten stuckt

**Comment by Husky2002** [comment]
Wäre es dann Theoretisch möglich, dass alle fahrzeuge dort ein-/ausgeparkt werden wie in Bild 1 und nur der Pounder dort ausgeparkt wird wo der Punkt aktuell ist?

**Comment by DrGrizzlY17** [comment]
Nein das ist nicht möglich

**Comment by Husky2002** [comment]
Okey magst du beide Punkte wie gewünscht verschieben?

**Comment by DrGrizzlY17** [comment]
Dann flippt doch der LKW... ich bin verwirrt

**Comment by Chiko-Garcia** [comment]
hi ich hatte denn punkt immer dort bis dieser carton dazu kam seit dem kiptes um deswegen nur etmwas weiter runter packen da wo ich stehe

**Comment by Husky2002** [comment]
![20210305035402_1](https://user-images.githubusercontent.com/61657852/110061316-b3686980-7d67-11eb-83ec-b7549fd12d7a.jpg)

(Wo Chiko steht) Alte Position vom Marker

![20210305035411_1](https://user-images.githubusercontent.com/61657852/110061322-b5322d00-7d67-11eb-838a-0692b7ed8ae5.jpg)

(Wo Chiko steht) neue Position vom Marker

![20210305035515_1](https://user-images.githubusercontent.com/61657852/110061365-c67b3980-7d67-11eb-9b58-8c40b687d04a.jpg)



Wir gehen immernoch davon aus das der Carton (Bild 1) der Grund ist warum der Pounder flippt, da in den letzten 3 Jahren wo der Carton noch nicht da war es keine probleme gab. Jetzt seit dem der Carton da ist haben wir das Problem und nur mit dem Pounder, dass dieser, wenn der Carton da ist Flippt und wenn er vorm ausparken weg ist Parkt er ganz normal aus

**Comment by DonVitoDiangelo** [comment]
@DrGrizzlY17  Dann remove einfach den Karton und das Thema ist erledigt :)

**Comment by Chiko-Garcia** [comment]
ok danke und denn punkt wieder zuruck setzten dann bitte noch danke
