### ISSUE TITLE
Nach Spielende kein Zugriff auf externes Tablett möglich

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1259]
Habe mich auf der neuen Insel ausgeloggt, jetzt ca. 5 Minuten später zeigt das Tablet über den Browser immer noch an das kein Signal vorhanden ist.

Feature oder Bug?

**Comment by Dean-Gallagher** [comment]
kein Bug

**Comment by DonVitoDiangelo** [comment]
:)
