### ISSUE TITLE
Werkstatt - Rechnungsfenster schließen

### ISSUE THREAD

**Issue by 48619** [mexyn/statev_v2_issues#126]
John Vernon

**Zeitpunkt (Datum / Uhrzeit)**
27.08.2020 23:00

**Beobachtetes Verhalten**
Wenn beim Tuning/Reperatur oder Lackierung das Rechnungsfenster durch den Kunden geschlossen wird, kann der Mechaniker kein zweites Tuning oder Lackierung beginnen. Dieser bekommt die Meldung: "mechanic.alreadyTuning"
Erst nach einem Relog des Mechaniker Chars kann dieser wieder die Werkbank und Lackierkabiene nutzen.

Das Fahrzeug ist für den Kunden normal nutzbar, aufschließen und bewegen des Fahrzeugs ohne Einschränkungen möglich.

Dieses tritt nicht auf wenn der Mechaniker die Rechnungs selbst schließt, nur bei Kunden.

**Erwartetes Verhalten**
Mechaniker kann nach schließen des Rechnungsfensters weiterhin die Werkbank oder Lackierkabine nutzen.

**Schritte um den Fehler nachvollziehen zu können**
1. Tuning/Reparatur oder Lackierung wählen
2. Kunde schließt das Rechnungsfenster
3. Bug tritt auf

**Comment by mexyn** [comment]
Fixed
