### ISSUE TITLE
#MakeMuscleCarsGreatAgain

### ISSUE THREAD

**Issue by EvviiL1050** [mexyn/statev_v2_issues#1260]
**Drasko Kostic / Kenny Blake**

Beide
**Auftrittszeitpunkt (Datum / Uhrzeit)**

V1 & V2
**Beobachtetes Verhalten**

Bis auf den Hellfire, Dominator GTX und vereinzelte Muscle Cars, schaffen die meisten kaum 200 km/h. Die meisten machen auch keinen Wheelie und wenn sie einen Wheelie schaffen, dann gibt es auch keinen sonderlichen Beschleunigungsboost, ganz im Gegenteil man hat eher das Gefühl das die dadurch langsamer am Start sind. Ich möchte hier keine andere Projekte im Mund nehmen, aber wenn es um die Muscle Car Kategorie ging, haben dort alle einen Wheelie geschafft.

Sabre GT Turbo Custom 180 km/h kein Wheelie
Tulip 140-150 km/h Wheelie=nein 201 ps
Vamos 190 km/h Wheelie=nein 253 ps
Phoenix 180 km/h (glaube der macht nen Wheelie) 149 ps
Ganuntlet Classic 170 km/h Wheelie=nein 233 ps
Hellfire 230-240 km/h Wheelie=ja 349 ps
Ellie 180 km/h Wheelie=ja 162 ps
Dominator GTX 225 kmh Wheelie=ja 174 ps
Buccaneer 170 km/h meines wissens nacht --- Wheelie=nein 150 ps

Das ist eine Liste mit meinen Persönlichen Erfahrungen auf V2, ich habe oben V1 erwähnt, weil das zu V1 auch nicht ging, da aber schon lange V2 angekündigt worden ist hatte ich die Hoffnung, dass sich das Problem mit Altv automatisch löst. Weiters waren das ja nicht mal alle Muscle Cars.

Habe dazu auch ein Thread im Forum gemacht:
https://statev.de/forum/list/index.php?thread/12078-make-muscle-cars-great-again/

**Erwartetes Verhalten**

Alle Muscle Cars sollten ein Wheelie mit Beschleunigungsboost können, mir sind die Einstellungsmöglichkeiten bekannt soweit. Auch wenn man nicht allen Fahrzeugen einen Wheelie "schenken" kann, dann zumindest diese von der Endgeschwindigkeit hochschrauben. Ich bitte euch, ich schaffe nicht mal die zugelassen Höchstgeschwindigkeit auf dem Highway mit dem Tulip. Ich verlang hier nicht bei Gott, das jede karre 240+ km/h fährt, aber um ein bisschen auf der Straße mithalten zu können aus X Gründen, wäre es echt gut.

Hier einen kleinen Vergleich was ich genau meine:
https://www.youtube.com/watch?v=zPjsQHvQQRQ&feature=youtu.be&ab_channel=EvviiL1050
zu StateV
https://www.youtube.com/watch?v=SqPfYyG7skA&feature=youtu.be&ab_channel=EvviiL1050

**Comment by EvviiL1050** [comment]
Hier einen kleinen Vergleich was ich genau meine:
https://www.youtube.com/watch?v=zPjsQHvQQRQ&feature=youtu.be&ab_channel=EvviiL1050
zu StateV
https://www.youtube.com/watch?v=SqPfYyG7skA&feature=youtu.be&ab_channel=EvviiL1050

**Comment by DonVitoDiangelo** [comment]
Primär geht es hier um Geschwindigkeitsstufen und nicht um den Wheelie. Das hatte aber bereist ein Teammitglied im Forum aufgeschlüsselt. Weiterhin ist v1 nicht relevant, da zu v2 das System neu aufgebaut wurde und hier andere Maßstäbe gelten. Andere Server sind hier auch nicht relevant, da Wir eben Wir sind und nicht andere. Wir haben unsere eigenen Maßstäbe gesetzt. Oft genug gibt es auch mehrere Motoren etc.. Dadurch sind kleinere Motoren schlussfolgernd auch langsamer. haben dann nicht genug power und es gibt keinen Wheelie. Je nach Konfiguration ist das aber auch beim größten Motor der Fall, da er gegenüber anderen Fahrzeugen sonst zu viel Kraft hätte.  Aber wir können das ein oder andere Car gern anschauen, das ist kein Problem, Allerdings möchte ich auch gleich betonen das die Chancen auf eine Korrektur eher gering sind, da das System so wie es ist, unser Konzept erfüllt.

**Comment by EvviiL1050** [comment]
Scheint ein komisches Konzept zu sein, wenn Autos mit weniger PS einen Wheelie am Tag hinlegen und schneller sind als die mit mehr PS, aber gut. Es gibt ja nicht mal einen Anhaltspunkt. 

Es geht doch genauso darum, das man keine Lust hat, für einen Wagen Geld auszugeben, wo man nicht weiß wie der ist.. Klar fördert das RP, weil man den suchen muss, aber man findet die eine Karre nicht immer, um dann meine lang ersparte 40-80k auszugeben, um dann enttäuscht zu werden, muss ich denk ich mal nicht erklären und los wirst du die sowieso nicht.
