### ISSUE TITLE
Benachrichtigung Handy Anruf

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#1262]
**Character Name**
Marvin_Elpe

**Auftrittszeitpunkt (Datum / Uhrzeit)**
04.03.2021

**Beobachtetes Verhalten**
Früher stand bei der angerufenen Nummer immer der Name, welchen man der Nummer gegeben hat. Aktuell steht nur die Telefon Nummer da.

**Erwartetes Verhalten**
Name der SIM Karte steht dort.

**Optional: Video / Bilder des Fehlers**
![](https://pic.statev.de/i/ORKQD.png)

**Comment by its4l3x** [comment]
Fixed, next Update.
