### ISSUE TITLE
Bootsgarage Cayo Perico

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1264]
Es wäre klasse wenn man den Einparkpunkt näher an die Wasseroberfläche setzen könnte, wenn man normal ran fährt und es einparken möchte ist es nicht möglich.
Entweder man wartet auf hohe Wellen oder versucht das Boot durch einen Kickstart höher zu bekommen, beides funktioniert auch nur bedingt!

![Screenshot_37](https://user-images.githubusercontent.com/70241137/110040417-109df400-7d43-11eb-9db0-918847f504ce.jpg)

**Comment by DonVitoDiangelo** [comment]
mal etwas nach unten gesetzt, bitte mal für den tug dann aber weiter beobachten
