### ISSUE TITLE
SAPD Police Predator

### ISSUE THREAD

**Issue by MisterCopeland** [mexyn/statev_v2_issues#1265]
**Character Name**
Paddy Copeland

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.03.2021

**Beobachtetes Verhalten**
SAPD Police Predator Boot ist sehr langsam und es fehlt ein StateCom Zugriff. 

**Erwartetes Verhalten**
Das Boot sollte nicht mit 90km/h langsamer sein als jedes andere Boot. Auch der Zugriff auf das StateCom sollte machbar sein. Das Boot verfügt über mehr Antennen und Radarsysteme als der Staat Los Santos selbst. 

Weiterer Vorschlag. Das PD Boot ist nur durch die Folierung erkennbar. Das Licht am Abend ist sehr dunkel. Das Außenlicht von Speeder oder Toro sind 5x heller, mein Vorschlag wäre es, Sirenen an das Boot zu adden. Das man akustisch auf sich aufmerksam machen kann.

**Comment by DonVitoDiangelo** [comment]
Das Boot wird nicht gemodded werden und auch StateCom wird es da nicht geben. Dafür habt Ihr dann den Funk für eine entsprechende Kommunikation. Die Geschwindigkeit liegt im Standard und wird auch so bleiben. Das Boot könnt ihr "weiß" lackieren lassen, dann ist das Problem da auch gelöst, was die Liverie angeht.
