### ISSUE TITLE
Leute ziehen fehlerhaft

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#1266]
**Character Name**

Sven Rosenbach
**Auftrittszeitpunkt (Datum / Uhrzeit)**

04.03.2021 22:35
**Beobachtetes Verhalten**

Konnte normal Laufen beim ziehen einer Person
**Erwartetes Verhalten**

Richtige Animation und nicht normal Laufen
**Schritte um den Fehler nachvollziehen zu können**

1. Bewusstlose Person finden
2. Über App einen Notruf absetzten
3. beim Warten die Person ziehen
4. sich wundern warum das so ist
**Optional: Video / Bilder des Fehlers**

https://streamable.com/h5wdhv

**Comment by DonVitoDiangelo** [comment]
Telefonieren oder zeihen, beides geht nicht ;)

**Comment by its4l3x** [comment]
Ok - Also es ist sehr fragwürdig, wie du das im RP Argumentieren willst, wenn du eine Person schiebst und nebenbei noch Telefonierst? 

Trotz aller dessen, ist es kein Bug in der Hinsicht, habe aber trotzdem das noch mit abgefangen....

**Comment by SHaagmann** [comment]
> Ok - Also es ist sehr fragwürdig, wie du das im RP Argumentieren willst, wenn du eine Person schiebst und nebenbei noch Telefonierst?
Naja man kann ja theoretisch auf Lautsprecher stellen, wie soll man sonst auch Erste-Hilfe leisten können ^^

**Comment by its4l3x** [comment]
Man kann auch kurz andere Fragen oder auflegen und sagen man ruft gleich wieder an ^^.Naja egal. Wie oben erwähnt - wird jetzt dann mit abgefangen.
