### ISSUE TITLE
MD Lexus Licht

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#127]
**Character Name**

Jannik Datsch

**Zeitpunkt (Datum / Uhrzeit)**

27.08 23:15

**Beobachtetes Verhalten**

Das Licht des Lexus wird fehlerhaft dargestellt

**Erwartetes Verhalten**

normaler Lichtkegel

**Schritte um den Fehler nachvollziehen zu können**

siehe oben

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

1920-1080

**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=WI3QWc0ajeY&feature=youtu.be

**Comment by DonVitoDiangelo** [comment]
fixed next update
