### ISSUE TITLE
Haussystem "Edel Villa Rustikal" fehlerhaft. 

### ISSUE THREAD

**Issue by Romeny1** [mexyn/statev_v2_issues#1271]
__**Character Name**__

Mitt_Romney
Haushash: house_RockfordHills_9

_**_Beobachtetes Verhalten_**_

Die meisten Möbel/ Einrichtungsgegenstände im Haussystem 3 "Edel Villa Rustikal" sind "begehbar", sprich ich kann durch Tische, Schränke, Stühle etc. mich frei bewegen.
Auch ist nur eine, von den 28 Sitzmöglichkeiten (Sessel/Stühle/Sofas) benutzbar. 

**Erwartetes Verhalten**

Möbel sollten, wie auch in den anderen Häusern nicht mehr durchschreitbar sein, auch wäre es super wenn man mehr als nur eine Möglichkeit hat, sich setzen zu können (gerade wenn Gäsete da sind). 

**Schritte um den Fehler nachvollziehen zu können**

Haus betreten; in bzw. durch Möbel laufen. 

**Optional: Video / Bilder des Fehlers**

Einige Beispiele: 

![bug6](https://user-images.githubusercontent.com/78976896/110147004-7ccc3680-7ddb-11eb-8bc4-5cb38b0d44b8.jpg)
![bug4](https://user-images.githubusercontent.com/78976896/110147064-89e92580-7ddb-11eb-891f-4ede477d7603.jpg)
![bug3](https://user-images.githubusercontent.com/78976896/110147070-8b1a5280-7ddb-11eb-9496-fc8d5a32c5c1.jpg)
![bug2](https://user-images.githubusercontent.com/78976896/110147092-8f467000-7ddb-11eb-9294-7c91244c4faa.jpg)
![bug1](https://user-images.githubusercontent.com/78976896/110147097-90779d00-7ddb-11eb-9bc1-2c390b2435d7.jpg)

**Comment by DonVitoDiangelo** [comment]
Das ist ein Standard GTA MLO, welches wir auch nicht bearbeiten werden, daher closed, sry.
