### ISSUE TITLE
Rumpo Motor Import

### ISSUE THREAD

**Issue by ProgrammingFox** [mexyn/statev_v2_issues#1272]
**Beobachtetes Verhalten**
In der Fahrzeugfertigung kann man ein Rumpo bauen. Jedoch gibt es diesen Motor wohl nicht im Import. Oder ist das so ein Spezialfahrzeug?

**Erwartetes Verhalten**
Dass der Motor auch Importierbar ist.

**Comment by DonVitoDiangelo** [comment]
Ja, der Rumpo Custom(rumpo3) ist vorhanden. Der andere wurde glaube mal wegen den Folien oder sowas entfernt. Das weiß ich nicht mehr genau.
