### ISSUE TITLE
Collisionbug Central Highway Checkpoint 

### ISSUE THREAD

**Issue by MisterCopeland** [mexyn/statev_v2_issues#1273]
**Character Name**
Paddy Copeland

**Beobachtetes Verhalten**
Collisionbug am Checkpoint Central Highway (Betrifft alle Leitern)

**Erwartetes Verhalten**
Treppe kann man drauf um auf besserer Höhe mit LKW Fahrern zu sein und davor kann man durchlaufen.

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=nJYFWs1sh38

**Comment by DonVitoDiangelo** [comment]
Kann grad nicht genau sagen von was das kommt (vermutlich die Leitplanke, Standard GTA Objekt), aber werden wir nicht weiter bearbeiten. Vllt. gibt es mal neue Mautstellen, aber bis dahin, bleibt das so, sry.
