### ISSUE TITLE
Frisur/ auto

### ISSUE THREAD

**Issue by Annabelle-Smith** [mexyn/statev_v2_issues#1275]
**Character Name**

Annabelle Smith

**Auftrittszeitpunkt (Datum / Uhrzeit)**

nicht zeitlich relevant

**Beobachtetes Verhalten**

bei gewissen Fahrzeugen kommt die Frisur durch das Autodach , z.b osiris, Itali RSX, xa-21 ist aber glaub bei jedem fahrzeug das so niedrig ist. :-)

**Erwartetes Verhalten**

das die Frisur nicht durchs Dach bugt

**Schritte um den Fehler nachvollziehen zu können**

als frau ne hoch gebundene haare. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![frisur](https://user-images.githubusercontent.com/74880091/110210162-b743db00-7e90-11eb-980c-1954dd266eba.png)
![frisur1](https://user-images.githubusercontent.com/74880091/110210170-bca12580-7e90-11eb-8776-850633fdd0b6.png)

**Comment by DonVitoDiangelo** [comment]
Wird so bleiben müssen. Wir werden keine anderen Frisuren setzen wenn sich jemand in Fahrzeug setzt.
