### ISSUE TITLE
Komische Handy Fehlermeldung

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#1276]
**Character Name**
Marvin_Elpe

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.03.2021 17:23

**Beobachtetes Verhalten**
Komische Fehlermeldung beim auflegen.

**Erwartetes Verhalten**
Keine Fehlermeldung

**Schritte um den Fehler nachvollziehen zu können**
bisher einmalig aufgetreten

**Optional: Video / Bilder des Fehlers**
![20210306172434_1](https://user-images.githubusercontent.com/33394632/110213594-fbd77280-7ea0-11eb-8e13-beb29559fde8.jpg)

**Comment by its4l3x** [comment]
Abgeändert - Kommt eig. sehr sehr selten vor. Meistens wenn du schneller bist, als jemand anderes. Fange ich jetzt mit ab. Daher wie immer, changed next update :P

**Comment by M4rvinLP** [comment]
Bin immer schneller als andere :o Danke

**Comment by M4rvinLP** [comment]
Immer noch zu schnell :P
![](https://pic.statev.de/i/OE1DT.jpg)
