### ISSUE TITLE
Zimt Stange dauert sehr lang und in keiner Produktion eingeplant

### ISSUE THREAD

**Issue by xtorox** [mexyn/statev_v2_issues#1277]
**Character Name**

 Robin_Toro
**Auftrittszeitpunkt (Datum / Uhrzeit)**

06.03.2021 18:15
**Beobachtetes Verhalten**

 Es wurden 30 Zimt Stangen in der Lager Produktion angeworfen, dies dauert 10 Stunden und bei den Skills hat sich sowohl bei Ernährer als auch Handwerker nichts getan. Hatten dies auch schon mit Wissenschaftler probiert und da auch kein Fortschritt. 
**Erwartetes Verhalten**

Ein Fortschritt bei den Skills und nicht so lange. 
**Schritte um den Fehler nachvollziehen zu können**

Produktion anwerfen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

Beschreibe Schritt für Schritt wie man den Fehler nachstellen kann 
**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Prod fixed next update und das Lager wird im SS nicht berücksichtigt.
