### ISSUE TITLE
Weißer Schatten bei Objekten/Chars bei Kamerabewegung

### ISSUE THREAD

**Issue by PeterGlore** [mexyn/statev_v2_issues#1278]
**Peter Glore**

Mit meinem Charakter

**Auftrittszeitpunkt (Täglich/ egal welche Uhrzeit)**

**Beobachtetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by PeterGlore** [comment]
https://clips.twitch.tv/DeterminedKawaiiPancakePicoMause-Uzn97tdX8tepj1T7

**Comment by DonVitoDiangelo** [comment]
mh, noch nie gesehen. Siehst du das nur bei so? Nutzt du Mods? Sehen andere das an dir auch?

**Comment by Stiefel911** [comment]
das ist eine Einstellungssache der Grafikkarte, vllt mal nach updates schauen oder eben schauen ob die Einstellungen noch stimmen.
Diese "Umrandung" hatte auch mal vor einem Jahr... da aber komplett... nach einem Graka update war es weg ;)

**Comment by DrGrizzlY17** [comment]
Was isn das für ne Hose die du da trägst?

**Comment by PeterGlore** [comment]
Ich hab nur das Problem. Die anderen nicht. Nach Graka updates hab ich
schon geschaut, ist aktuell. Und die hose is außem klamottenladen so ne
besche kurze hose

StateV_Dan <notifications@github.com> schrieb am So., 7. März 2021, 15:44:

**Comment by PeterGlore** [comment]
Ah und an den grakaeinstellungen ahb och auch schon rungetüfftelt. Aber
bringt irgendwie nichts

Kevin Gunkel <kevin.gunkel90@gmail.com> schrieb am So., 7. März 2021, 18:09:

**Comment by DonVitoDiangelo** [comment]
Am besten mal im Support Forum um Hilfe Fragen oder im Discord. Das werden wir hier nun schließen.

**Comment by PeterGlore** [comment]
Ich habe das Problem entdeckt. Es lag an der DirektX Version. Sie war auf 10.1 oder so eingestellt. Fehler ist weg
