### ISSUE TITLE
Umsetzen: Ausparkpunkt Haus Garage (house_DavisMidLS_0)

### ISSUE THREAD

**Issue by statevmj** [mexyn/statev_v2_issues#1279]
**Character Name**

Mathew_Jones

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Seit dem die "neue" Map wieder auf dem Server ist.

**Beobachtetes Verhalten**

Fahrzeuge können nicht bewegt werden, weil sie teilweise auf der Mülltonne ausgeparkt werden. Fahrzeuge müssen öfter ein- und ausgeparkt werden, damit man sie bewegen kann.

**Erwartetes Verhalten**

Fahrzeuge werden vernünftig ausgeparkt. Gerne die Objekte vor der Garage entfernen oder den Ausparkpunkt weiter auf die Straße verlegen (nicht den Marker und den Einparkpunkt, wenn möglich)

**Schritte um den Fehler nachvollziehen zu können**

Fahrzeug in die Haus Garage einparken und wieder ausparken. Hash: house_DavisMidLS_0 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

irrelevant

**Optional: Video / Bilder des Fehlers**

https://pic.statev.de/i/OmpmV.jpg

**Comment by statevmj** [comment]
Nein, das war nicht nur jetzt so, das war auch vorher schon so, als diese Map auf dem Server war. Reena weiß darüber auch Bescheid, war bisher aber nicht mehr von Bedeutung, da ja die ganze Zeit eine andere Map auf dem Server war. Das ist zwar korrekt, dass die Fahrzeuge so ausgeparkt werden, wie sie eingeparkt werden, allerdings werden Fahrzeuge ja auch manchmal automatisch nach Server-Restart eingeparkt. Und wenn das passiert, dann tritt dieses Problem auf.

**Comment by DonVitoDiangelo** [comment]
Ah ok, verstehe, ja werden wir dann prüfen.
