### ISSUE TITLE
StateNet Preise nach reload der Seite im Lager

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1280]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit längerem - 09.03.21 - 9:00

**Beobachtetes Verhalten**
Wenn man sein Lager öffnet kann es sein das die Preise auf 0 Sind und erst nach mehrfachem Reload angezeigt werden.
Der Fehler tritt sowohl am Handy als auch am PC auf. Das Video ist allerdings am Handy

**Erwartetes Verhalten**
Preise direkt korrekt angezeigt werden.

**Schritte um den Fehler nachvollziehen zu können**
Mehrfach das Lager einer Firma reloaden

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=vc3wIh18lYU

Der Fehler sollte eigentlich behoben sein, scheint aber immer noch aufzutreten:
https://github.com/mexyn/statev_v2_issues/issues/673

**Comment by TheBroady** [comment]
Video vom StateNet extern:
https://www.youtube.com/watch?v=ofUyujgp9vQ

**Comment by TheBroady** [comment]
Problem besteht weiterhin

**Comment by TheBroady** [comment]
Wieso werden die Dinge eigentlich nicht in der "Ladentheke" angezeigt sondern direkt im Lager ? (Mit Preisangabe)

**Comment by MarcelMuerto** [comment]
@TheBroady 
Das Fehlverhalten konnte reproduziert und behoben werden.
Die Änderung kommt mit dem nächsten StateNet Update.

Zu deiner Frage:
Bei Tankstellen wird die Preisliste im Lager angezeigt und dort verwaltet. 
Man kann halt keine Flüssigkeiten in die Ladentheke packen :P
