### ISSUE TITLE
SAPD Bug Sehen was unter einem ist

### ISSUE THREAD

**Issue by RappelZappel80** [mexyn/statev_v2_issues#1283]
**Character Name** Olivier_Massieu

Oliver_Massieu
**Auftrittszeitpunkt (Datum / Uhrzeit)**

09.03.2021 / 22:08 Uhr
**Beobachtetes Verhalten**

In der LAPD Lobby die Taste "Ö" gedrückt und mit dem Fall zu Boden sah ich die Dinge die unter mir waren. 
**Erwartetes Verhalten**

Mit drücken der Taste "Ö" sollte ich mit dem Character einfach zu Boden sacken. Dort kurz verbleiben und dann wieder normal aufstehen. 
**Schritte um den Fehler nachvollziehen zu können**

In der LAPD Lobby die Taste "Ö" gedrückt und mit dem Fall zu Boden sah ich die Dinge die unter mir waren. 

![Bug_1](https://user-images.githubusercontent.com/80391742/110614549-be216500-8192-11eb-9939-1bcf39fd8dcb.png)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Werden wir nicht wirklich fixen können. Ist auch ein externes MLO.  Hier dann den Fehler mit dem ö drücken am besten nicht machen.
