### ISSUE TITLE
Entfernen von Terassen Inventar

### ISSUE THREAD

**Issue by Ekaz58** [mexyn/statev_v2_issues#1284]
**Character Name**
Rainer Kornn

**Ort/Lage**
Hillcrest Ave. 101
Haushash : house_VinewoodHills_94

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Unabhängig

**Beobachtetes Verhalten**
Bei meinem Haus befindet sich jede Menge "Müll" auf der Terasse den ich gerne entfernt hätte. Interaktionen und Bewegung sind auf der Terasse so gut wie unmöglich ohne einen Glastisch zu zertreten oder sämtliches Inventar vor sich her zuschieben, ich hoffe dies bereitet euch nicht allzu viel Arbeit.

**Erwartetes Verhalten**
Sofern möglich eine "saubere" Terasse ohne Zeitschriften, umgefallene Stehtische und Musikboxen. Die ansteuerbaren Elemente wie die Großen Weissen Sofas sind vollkommen okay, nur das drum herum stört.

MFG der Rainer

**Optional: Video / Bilder des Fehlers**
![hausd](https://user-images.githubusercontent.com/21086097/110702040-497e1300-81f2-11eb-8419-0be3f93d1dc4.png)
![haus 2f](https://user-images.githubusercontent.com/21086097/110702056-4e42c700-81f2-11eb-8e65-2d179ab2abdc.png)

**Comment by DrGrizzlY17** [comment]
Abgelehnt.

Man kann sich frei bewegen und man hat genug Optionen Sachen auszuweichen

**Comment by Ekaz58** [comment]
Ja natürlich kann man sich frei bewegen, der Tisch wird des öfteren verrückt aber mir geht es auch um die generelle Unordnung. Ist da garnichts dran zu machen?

**Comment by Ekaz58** [comment]
Ich mein das Haus kostet knapp 600k und ich will nicht jedes mal auf ne durchgemachte Partynacht angesprochen werden. Es sieht schlichtweg einfach nicht gut aus.  Ich fände es echt schön wenn ihr euch das nochmal überlegen könntet.
