### ISSUE TITLE
Kilometeranzeige bei Fahrzeugüberschreibung

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1285]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11.03.2021 - 17:30 ca

**Beobachtetes Verhalten**
Die Kilometeranzeige im Fahrzeugüberschreibungsmenu ist völlig falsch.
Da scheinen die Kommas weit verfehlt zu sein

**Erwartetes Verhalten**
Die korrekte Laufleistung als Anzeige

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug überschreiben und die Kilometer im Menu betrachtnen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/i/OY2bI.jpg

**Comment by ProgrammingFox** [comment]
Den Fehler gabs auch schon in V1. Von meinen Beobachtungen her kann ich sagen, dass die KM Anzahl in Wirklichkeit die Meteranzahl des Fahrzeugs ist. Muss nur durch 1000 geteilt werden dann passt es.

**Comment by its4l3x** [comment]
Wie @ProgrammingFox schon sagte, was angezeigt wurde war die Meterzahl. Habe es abgeändert, wird nun die korrekte km Anzahl angezeigt mit dem Update um 18 Uhr :)
