### ISSUE TITLE
Charakter steht auf, wenn Handy weggesteckt wird.

### ISSUE THREAD

**Issue by BenniButlack** [mexyn/statev_v2_issues#1286]
Benni Butlack
**Mit welchem Character wurde das Verhalten in-game ausgelöst/beobachtet**

12.03.2021 / 05:00 Uhr
**Wann exakt (Datum / Uhrzeit) ist der Fehler beobachtet worden**

Charakter steht von einer Liege auf, nachdem das Handy weggesteckt wurde. Bei der Benutzung des Tablets ist dies nicht der Fall.
**Beschreibe den Fehler**

Charakter bleibt nach Wegstecken des Handys liegen/sitzen.
**Beschreibe wie es richtigerweise sein sollte**

Auf platzierte Liege legen, Handy rausholen und wieder wegstecken.
**Beschreibe Schritt für Schritt wie man den Fehler nachstellen kann**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by JannikDatsch** [comment]
#983
