### ISSUE TITLE
Grafikbug beim Öffnen von Handy/ Tablet

### ISSUE THREAD

**Issue by Herrmannn** [mexyn/statev_v2_issues#1288]
Herrmann_Fuchs

13.03.2021 15: 30

Wie in diesem Beitrag ( https://github.com/mexyn/statev_v2_issues/issues/1189 ) schon geschrieben, offnet sich, wenn ich das Handy/ Tablet in die Hand nehme nichts, ich bekomme den Mauszeiger auf dem Bildschirm, der Char hat das Handy in der Hand, aber ich kann es nicht benutzen. Das gleiche beim Tablet. Und das gleiche auch mit dem X Menü, ich kann es benützen, indem ich die Maus in die Richtige Richtung mache, aber es wird mir nichts angezeigt. 
Und Irgendwann bekomme ich eine halben Blackscreen. 

´Weiß ich natürlich nicht, aber ich habe es bei jedem Start

2560 x 1440

**Optional: Video / Bilder des Fehlers**
https://user-images.githubusercontent.com/77365416/107877703-58f98d00-6ece-11eb-9750-a31796364b4f.mp4

**Comment by its4l3x** [comment]
Auslastung, CPU & GPU? Wie siehts da aus? Laptop?

Fehlende Treiber?

Kann viele Aspekte haben, sieht aber nach einem User-Spezifischen Problem deinerseits aus.

**Comment by Herrmannn** [comment]
CPU und GPU normale Auslastung. Spiele nicht auf dem Laptop, Treiber auch der aktuellste.

Ich habe schon alles neu installiert, den Ressourcen ordner gelöscht, gta neu installiert, ich weiss keine Lösung mehr...

**Comment by DonVitoDiangelo** [comment]
Ja, eher ein Supportfall. Vllt. fragst du dich mal durchs Forum oder direkt im Discord Support Bereich und jemand kennt das Problem. Auch mal directx software und die net framework Sachen neu installieren.  https://wiki.altv.mp/wiki/Tutorial:Troubleshoot_Client/de
