### ISSUE TITLE
Zu langer Name fürs UI (Farmfeld)

### ISSUE THREAD

**Issue by glb11** [mexyn/statev_v2_issues#129]
**Character Name**
Jens_Summer, Andreas_Jung

**Zeitpunkt (Datum / Uhrzeit)**
28,08,2020 0;00

**Beobachtetes Verhalten**
Bei Farmfelder (Tasche)(1)/ Maschineninventaren(3) werden bei langen Namen die Stückzahlen (Vom 2. Item) nicht mehr korrekt angezeigt (Vollständig)
(2) Sobald ein Item mit kurzen Namen mit in der Zeile ist ist es kein Problem mehr

**Erwartetes Verhalten**
mann sollte beide zahlen lesen Können

**Schritte um den Fehler nachvollziehen zu können**
Cochennilleschildlaus, Blattwespenlarve auf dem z.B. Gurkenfeld (Grapseed) sammeln und die Beiden Items in eine Zeile Legen  

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
(1)
![20200828000256_1](https://user-images.githubusercontent.com/70204338/91500857-9d638300-e8c4-11ea-94ef-25dface070ef.jpg) (2) 
![20200828000304_1](https://user-images.githubusercontent.com/70204338/91500872-a48a9100-e8c4-11ea-8983-2027b38185f8.jpg) (3) 
![20200828000815_1](https://user-images.githubusercontent.com/70204338/91500881-ab190880-e8c4-11ea-9162-4df4244ea2eb.jpg)

**Comment by r3sist3nt** [comment]
note: ```word-break: break-all;```

**Comment by r3sist3nt** [comment]
Fixed.
