### ISSUE TITLE
Nicht Endende Farmanimation

### ISSUE THREAD

**Issue by glb11** [mexyn/statev_v2_issues#1290]
**Character Name**
Jens_Summer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
zeit 13.03.2021  18:00

**Beobachtetes Verhalten**
Farm Animation endet nicht wenn Abbauzeit rum ist  (muss jedes Mal per Hand abgebrochen werden über ,  oder über das X-Menü)

**Erwartetes Verhalten**
Endet Automatisch wenn fertig

**Schritte um den Fehler nachvollziehen zu können**
Aufs Feld gehen und Arbeiten

**Optional: Video / Bilder des Fehlers**
https://youtu.be/eQQbzVEXmGk

**Comment by glb11** [comment]
Ergänzung:   Wahrscheinlich bei allen Feldern so    (laut Rückmeldungen im Discord)

**Comment by its4l3x** [comment]
fixed seit dem 2 uhr restart
