### ISSUE TITLE
Farmbug

### ISSUE THREAD

**Issue by franzjosef27** [mexyn/statev_v2_issues#1291]
**Franz Josef**

Franz Josef
**Auftrittszeitpunkt (Datum / Uhrzeit)**

13.02.2021, 19.00
**Beobachtetes Verhalten**

Bei der Hühnerfarm steht man nach dem Einsammeln nicht mehr auf. Man muss die Animation selber beenden.
**Erwartetes Verhalten**

Der character sollte von Alleine aufstehen nach dem Einsammeln und schließen des inventars.
**Schritte um den Fehler nachvollziehen zu können**

Gehe zum Huhn, drücke E um den Sammelprozess zu starten, warte bis dieser abgeschlossen ist und sammle die Rohstoffe ein. Dannn versuch zum nächsten Huhn zu laufen.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=wSd5Mwn-oIc

**Comment by its4l3x** [comment]
fixed seit dem 2 uhr restart
