### ISSUE TITLE
Begrenzer Fehler als Beifahrer

### ISSUE THREAD

**Issue by Luca5k** [mexyn/statev_v2_issues#1292]
**Character Name**
Luke Chase

**Auftrittszeitpunkt (Datum / Uhrzeit)**
13.03 - 20 Uhr

**Beobachtetes Verhalten**
Man kann bei niedriger Geschwindigkeit als Beifahrer den Begrenzer vom Fahrzeug auslösen. Sobald die Geschwindigkeit überschritten wird, buggt das Auto rum.

**Erwartetes Verhalten**
Fahrzeug nicht am rumbuggen, (Begrenzer nicht auslösbar als Beifahrer?) 

**Schritte um den Fehler nachvollziehen zu können**
Als Beifahrer den Begrenzer bei niedriger Geschwindigkeit aktivieren

**Optional: Video / Bilder des Fehlers**

https://user-images.githubusercontent.com/75338130/111041198-7cfdaf00-8437-11eb-870f-eefbc5423757.mp4

**Comment by its4l3x** [comment]
fixed heute 18 uhr
