### ISSUE TITLE
Farm Animation Fehler

### ISSUE THREAD

**Issue by Daniel160982** [mexyn/statev_v2_issues#1293]
**Character Name**

Daniel Rossi
**Auftrittszeitpunkt (Datum / Uhrzeit)**

13.03.2021 um 20:35 Uhr 
**Beobachtetes Verhalten**

Farming Animation wird nicht von selbst beendet, man muss sie selbst beenden.
**Erwartetes Verhalten**

Wenn der Farmig Vorgang abgeschlossen ist soll sich die Animation selbst beenden
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
fixed seit 2 uhr nachts
