### ISSUE TITLE
Anschnall Anzeigefehler bei Motorrad

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#1294]
**Character Name**

Sven Rosenbach
**Auftrittszeitpunkt (Datum / Uhrzeit)**

13.03 Nach Update
**Beobachtetes Verhalten**

Beim Anschnallen auf dem Motorrad wird grün angezeigt im UI obwohl kein Gurt verfügbar ist
**Erwartetes Verhalten**

Wird ignoriert/immer als nicht angeschnallt angezeigt
**Schritte um den Fehler nachvollziehen zu können**

Auf Motorrad anschnallen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://streamable.com/jzgut5

**Comment by its4l3x** [comment]
fixed heute 18 uhr
