### ISSUE TITLE
Kofferraum platz noch frei, aber kann nix rein tun

### ISSUE THREAD

**Issue by wichtTSV** [mexyn/statev_v2_issues#1295]
Tom Spider
 
Tom Spider und wahrscheinlich vielen anderen

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Täglich

**Beobachtetes Verhalten**

Man hat im Kofferraum (gerade z.b Kamacho) 200kg ladevolumen. Ich kann allerdings nur 199kg nutzen. Obwohl 1kg noch frei ist, kann ich nichts weiter rein tun an Erzen, Kohle etc (die ja 1kg oder weniger wiegen)

**Erwartetes Verhalten**

Das die 200kg voll genutzt werden können

**Schritte um den Fehler nachvollziehen zu können**

Selber die Autos mit Rohstoffen füllen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Hier liegst du warsch. bei einem sehr ekligen Kommawert, vllt. 199,97kg. 

Lass mich mal das abquatschen und vllt lassen wir das in Zukunft auch mit der Kommazahl anzeigen.
