### ISSUE TITLE
Vorschlag: Abladen / Aufladen sollte eine gewisse Zeit dauern 

### ISSUE THREAD

**Issue by powerswissi** [mexyn/statev_v2_issues#1297]
Moinsen Liebes Team

Ich bedanke mich mal in alle Form für eure Super geile Arbeit! Nicht jeder schafft das was ihr da geschafft habt. DANKE 

Violet und mir ist gerade eine Blitzidee gekommen und da nehme ich auch gerne meine Erfahrungen als LKW Fahrer mit rein. 

Wäre es möglich das man z.b beim Öl abladen (in der Firma ) einen Countdown bekommt wie lange das geht bis der Tanker leer ist?

Oder wie lange das abladen vom Eisenerz geht usw. usw. usw.

Das vorgehen wäre ungefähr gleich wie beim Tanken.. Ausser das man rumlaufen kann. Damit man auch ausserhalb des Gefahrenbereichs rumgehen kann, wenn der LKW z.b. auf ne Strasse steht.
Zudem ist das nicht einfach ranfahren, abladen und wieder los fahren, sondern wenn man NICHT angestellt ist kann man noch RP machen mit dem Bediener vom Computer.

Das Geld wird erst nach dem Abladevorgang überwiesen.

Wenn jemand angestellt ist muss er halt 10min warten bis der LKW leer ist. 
Alles nur rein theoretisch  

Man könnte dies auch mit dem Skill koppeln. Wenn  man gelernt ist in dem Skill z.b. Minenarbeiter kann man auch schneller abladen.

Wie gesagt das ist einfach gerade eine Blitzidee und muss sicher noch daran gefeilt werden.

Da gehört das Aufladen auch mit rein ;-)

Grüsse

Euer Swissi

**Comment by DonVitoDiangelo** [comment]
Hi, ja so etwas hatten wir damals in den öffentlichen mit drin. Müssen wir mal gucken ob wir sowas wieder implementieren wollen. Aber wahrscheinlich eher nicht. Mal schauen.

**Comment by eiksch** [comment]
Werden wir leider vorerst nicht mehr implementieren, da diesem System auch ein paar gravierende Änderungen bevorstehen.

Abseits davon sind aber zeitbasierte Prozesse immer sehr anfällig ausgenutzt zu werden, ein weiterer Grund weshalb wir das auch leider nicht eingebaut hätten :(
