### ISSUE TITLE
Court Building in Davis ohne Kollision

### ISSUE THREAD

**Issue by ArnoZuDemB** [mexyn/statev_v2_issues#1298]
**Character Name**
Arno Bjerg

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14.03.2021 13:45 Uhr (vermutlich permanent)

**Beobachtetes Verhalten**
Court Building in Davis hat keine Kollision, man kann sich von allen Seiten ins Gebäude buggen 
Gebäude zwischen Davis PD und Davis Garage
Das Gebäude kann man durchgehen, die außenstehenden Säulen nicht.

**Erwartetes Verhalten**
Wände sind betoniert und nicht zugänglich.

**Schritte um den Fehler nachvollziehen zu können**
Zum Gebäude gehen und dagegen gehen/laufen

**Optional: Video / Bilder des Fehlers**
https://youtu.be/2DsY85iU0qU

**Comment by DonVitoDiangelo** [comment]
Bekannt und wird auch vorerst so bleiben, sry.
