### ISSUE TITLE
Blutabnahme auch ausserhalb nutzbar machen

### ISSUE THREAD

**Issue by ChrisY2k** [mexyn/statev_v2_issues#1299]
Man kann zur Zeit nur als Medic eine Blutabnahme in den Behandlungsräumen machen. Wäre schön wenn man das auch ausserhalb nutzen könnte sobald man im Dienst ist. Es wäre auch für das RP schön das man zum Bsp. vor Ort eine Blutprobe entnehmen könnte und dies dann im Labor auswertet.

Gruss

**Comment by DonVitoDiangelo** [comment]
Das RP spielst du, indem du den Patienten mitnimmst ins MD. So hat auch dein gegenüber mehr davon. Sonst wird das nur wieder so ein wir machen noch schnell ne Blutabnahme und Sie sind entlassen. Hat dann im Zweifel negative Folgen für den Patienten der 2 Min. Blutabnahme RP hatte.
