### ISSUE TITLE
Bewusstlose Personen Ziehen - Animation Canceling 

### ISSUE THREAD

**Issue by AideenCarter** [mexyn/statev_v2_issues#13]
**Zeitpunkt (Datum / Uhrzeit)**
18:34 Beta Test Tag 1
**Beobachtetes Verhalten**
Wenn man Bewusstlose Personen Zieht und das Handy raus holt kann man rennen und somit die Animationen canceln

**Erwartetes Verhalten**
Handy sollte die Animation des ziehenes beenden.

**Schritte um den Fehler nachvollziehen zu können**
Tito erschießen und ziehen

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Fixed.

**Comment by Kalumel** [comment]
@its4l3x wenn man "B" drückt besteht der Fehler weiterhin.
