### ISSUE TITLE
entfernen nerviger und störender Schaufensterpuppen

### ISSUE THREAD

**Issue by FoxXxyLive** [mexyn/statev_v2_issues#1300]
**Samy_Nustrajev**

**Immer**

**nervige und störende Schaufensterpuppen, sodass man beim hinaus gehen der Firma (TP use) manchmal bugt, oder umfällt, hängen bleibt etc**

**Bitte die Schaufenster Puppen entfernen**

**Bei der Firma FoxXxy´s Smelting mit dem Firmenhash pfGroupAllRew_13
--

**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**https://prnt.sc/10ktda6**

**Comment by DrGrizzlY17** [comment]
Hi, beim rausgehen werdet ihr weit genug auf den Bordstein teleportiert. Ich hab das jetzt ausgehend getestet. Sollte das weiterhin auftreten bitte mit Video erneut einreichen.
