### ISSUE TITLE
Mieter rauswerfen klappt nicht

### ISSUE THREAD

**Issue by Patrick-Snooze** [mexyn/statev_v2_issues#1301]
Patrick Snooze

14.03.2021 / 21:30

Ein Aktueller Mieter hat das letzte mal am 13.02.21 Miete bezahlt und kann diesen nicht aus der Wohnung werfen. 

Fehler beheben / Mieter aus der Wohnung entfernen.

Beim Besitzt eines Hotels einfach selber mal Testen.

![mieter](https://user-images.githubusercontent.com/74994851/111083571-8443bc00-850e-11eb-9356-7ad194797d18.PNG)
**Optional: Video / Bilder des Fehlers**

gr33tz
Snooze

**Comment by Statev-Bonsai** [comment]
Tja, wären schon 30 Tage rum dann hättest du ihn auch rauswerfen können.
Der letzte Monat hatte nur 28 Tage..
Mathe mangelhaft, er war stets bemüht ;p

**Comment by its4l3x** [comment]
Wie Bonsai sagte.

**Comment by Patrick-Snooze** [comment]
Jop zu spät bemerkt, hatte aber kb den Artikel zu bearbeiten^^
