### ISSUE TITLE
Fundquote Roh + geschliffene Diamanten und deren Verwendung

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1305]
Die Fundquote von Rohdiamanten und geschliffenen ist m.e. im Gegensatz zum Verbrauch von Diamanten deutlich zu hoch.
Es gibt keinen Durchsatz weil zur Zeit nicht wirklich (auch durch die Tauschaktion) keiner der Autofertigungen Bestellungen für Supersportwagen bekommt, sie nehmen quasi nichts mehr ab im Gegensatz zu früher.

Nun wurden auch noch Diamanten aus dem Export entfernt, verdient hat man durch den extremen Niedrigpreis im Export pro Dia nur ca 400$ und wenn man schlechte schlechte Schleifergebnisse hatte dann hat man auch mal Miese gemacht, egal aber man hatte einen Durchsatz und konnte den Ankauf von Dias weiter gewährleisten.
Ich habe teilweise die Dias für 11k angekauft und für 10,7k in den Export gebracht, nur um den Leuten die Edelsteine abzunehmen.

Mittlerweile ist es so das sich die Diamanten stapeln und weit und breit keine Abnehmer in Sicht sind, auch die Perllackierungen reißen es nicht raus!
Konsequenz wird sein das die Händler keine Dias mehr ankaufen werden und so die Bürger sie nicht mehr loswerden.
Um das zu verhindern öffne ich diesen Beitrag, vielleicht kann ja Zeitnah mehr Durchsatz geschaffen werden!

Ich verlange keinen Export, aber irgendwas das wieder ein Durchsatz herrscht denn sonst gibt es viele enttäuschte Minenarbeiter die ihre Steine nicht mehr loswerden.
Die beiden extrem teuren Supersportwagen (Panamera Ersatz) reißen es auch nicht wirklich raus, klar brauchen die Edelsteine aber wie viele bauen sich schon ein Auto für ca 1,4 Millionen Dollar..

Diese Problematik trifft nur bei Diamanten zu!

**Comment by Statev-Bonsai** [comment]
Tja, ich kann deine Aussage komplett widerlegen.
Ich betreibe den größten Edelsteinankauf der Insel, und ich sehe was rein und raus geht!

Zudem ist es fakt das kaum bis gar keine Supersportwagen mehr importiert werden, das kann jeder im Import beobachten..
Und die Autobauer waren die Hauptabnehmer, die sind komplett weggefallen!
Nicht umsonst habe ich sie Bündelweise in den Export geschafft...

**Comment by DonVitoDiangelo** [comment]
Was die Fundquote betrifft, sehen wir auf den Stein genau, was da abgebaut wird. Wir werden das Thema und den Verbrauch begutachten und auch im High Meeting besprechen. Alles weitere folgt dann. :)

**Comment by Statev-Bonsai** [comment]
Und? :)
