### ISSUE TITLE
Gehen in Luft wenn man gegen Gebüsch läuft

### ISSUE THREAD

**Issue by FynnScherer** [mexyn/statev_v2_issues#1307]
**Character Name**
Fynn_Scherer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
15.03.2021 20:00

**Beobachtetes Verhalten**
Hinterm PD kann man wenn man auf das Beet geht irgendwie in der Luft gehen.

**Erwartetes Verhalten**
Naja... man sollte nicht in der Luft gehen können

**Schritte um den Fehler nachvollziehen zu können**
Einfach gegen das Beet laufen, ob Egoperspektive oder Third Person is egal

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
-

**Optional: Video / Bilder des Fehlers**
https://youtu.be/oKjNLj7ZDGQ

**Comment by DonVitoDiangelo** [comment]
gabz mlo issue, wird nicht weiter von uns behandelt.
