### ISSUE TITLE
[Friseur] Materialanzeige beim Makeup fehlerhaft

### ISSUE THREAD

**Issue by DerHessenTyp** [mexyn/statev_v2_issues#131]
Andreas Jung

**Zeitpunkt (28.08.2020 / 01:52 Uhr)**

**Beobachtetes Verhalten**
Wir haben alles ausser 2 Sachen die für den Friseur gebraucht werden im Friseur auf Lager und wollten verschiedenes austesten unter anderem auch das Makeup. Wir haben das Make Up ,,Nude Look" aber auch andere Make Ups ausprobiert, und uns wird angezeigt als Material braucht man 1x Bonita Basis Creme. Nach Einstellung vom Preis und dem Button ,,Schminken" gedrückt kommt dann folgende Fehlermeldung: Es fehlen folgende Gegenstände: Make Up Entferner Pads, LadyQ Foundation, Shanel Mascara, Shanel E" Das sollte meiner Meinung nach wenn wie bei allen anderen Anwendungen dort auch stehen.

**Erwartetes Verhalten**
Das richtige Material dabei stehen neben der 1x Bonita Basis Creme.

**Schritte um den Fehler nachvollziehen zu können**
. 1. Make Up auswählen
2. Material was man braucht angezeigt bekommen
3. Preis einstellen
4. Schminken
5. Der Schminkvorgang beginnt.

**Optional: Video / Bilder des Fehlers**
![Makeup 01](https://user-images.githubusercontent.com/70151958/91506843-7e202200-e8d3-11ea-96eb-b1f369be9927.jpg)

![Makeup 02](https://user-images.githubusercontent.com/70151958/91506848-81b3a900-e8d3-11ea-8ed2-48fd3d72af3f.jpg)

**Comment by its4l3x** [comment]
Fixed, next update
