### ISSUE TITLE
Notizen verschwinden im  Handy

### ISSUE THREAD

**Issue by MarkusSilber** [mexyn/statev_v2_issues#1311]
Ich habe öfter schon eine Notiz geschrieben im Handy und wenn ich dann irgendwann wieder die " Notizenapp " geöffnet habe, ist die letzte Notiz verschwunden. 

Dies ist leider schon öfter passiert und ist nervig, wenn dauernd die Notiz weg ist einfach....

**Comment by DonVitoDiangelo** [comment]
Direkt nach dem schreiben oder erst später? Also die Notizen werden lokal bei dir gespeichert. Wenn du dann öfter im alt/cache Ordner gewisse Dateien/Ordner löschst, kann es passieren, das du diese dann mit löschst. Auch daran zu merken, wenn du z.B: Animationen neu abspeichern musst.

**Comment by MarkusSilber** [comment]
Nene also wenn ich eine Notiz schreibe und dann auf " zurück " klicke, dann sehe ich das die Notiz gespeichert ist. Wenn ich das Handy dann weg lege und wieder raus hole nach paar Minuten und wieder in die Notizen App gehe, ist die Notiz verschwunden. Passiert ziemlich oft bei mir, das die Notiz dann weg ist einfach.

Ich habe noch nie irgendwas im alt / cache Ordner gelöscht

**Comment by Hutstaender** [comment]
Antivierensysteme oder fehlende Adminrechte vllt, die das Schreiben von Dateien im AltV Ordner verhindern?
