### ISSUE TITLE
Överflöd Imogon Bild fehlt im StateNET & StateCOM

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#1312]
**Character Name** Erwin Dulach

**Auftrittszeitpunkt (Datum / Uhrzeit)** Immer

**Beobachtetes Verhalten** Överflöd Imogon Bild fehlt im StateNET & StateCOM

**Erwartetes Verhalten** Eingebautes Bild

**Schritte um den Fehler nachvollziehen zu können** 
NET: Schlüssel von Överflöd haben, im StateNET in Fahrzeugliste schauen
COM: Kennzeichen von Överflöd suchen & anklicken

**Optional: Video / Bilder des Fehlers**

NET:
![grafik](https://user-images.githubusercontent.com/70150675/111512249-d6bfeb00-874f-11eb-86a1-554bfea2f327.png)
COM:
![grafik](https://user-images.githubusercontent.com/70150675/111512288-dfb0bc80-874f-11eb-90b9-7843893f661e.png)

**Comment by Micha190** [comment]
Das Bild vom BF Club ist auch nicht vorhanden.

**Comment by DrGrizzlY17** [comment]
hash: imorgon

![image](https://user-images.githubusercontent.com/70150988/111627771-b6e00400-87ef-11eb-87b1-6f7cdf1c444c.png)

hash: club

![image](https://user-images.githubusercontent.com/70150988/111627905-e42cb200-87ef-11eb-8592-6756e4c38717.png)
