### ISSUE TITLE
Doppelte Postel auf der Karte

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1313]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
immer

**Beobachtetes Verhalten**
Doppelte Postel

**Erwartetes Verhalten**
Das Postel einzigartig bleiben

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://prnt.sc/10ogy6g

**Comment by DonVitoDiangelo** [comment]
Wird auch so bleiben da wir dies nicht editieren, sry.
