### ISSUE TITLE
Tempomat wird falsch angezeigt.

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1314]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit Einführung des Tempomaten

**Beobachtetes Verhalten**
Parkt man ein Fahrzeug mit aktiven Tempomaten ein und parkt ein neues aus, wird einem der Tempomat weiterhin als aktiv (grün) angezeigt, obwohl er abgeschaltet ist, und nicht begrenzt.

**Erwartetes Verhalten**
Der Tempomat sollte als inaktiv (weiß) angezeigt werden.

**Schritte um den Fehler nachvollziehen zu können**
siehe Video

**Optional: Video / Bilder des Fehlers**

https://youtu.be/xKp63AxwBN4

**Comment by its4l3x** [comment]
fixed next update
