### ISSUE TITLE
Produzierte schwarze Lackdosen weg

### ISSUE THREAD

**Issue by meckitv** [mexyn/statev_v2_issues#1315]
**Mecki_Messer**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

18.03.21 18:08Uhr
**Beobachtetes Verhalten**
Vorm Serverrestart 13 schwarze Lackdosen angeworfen und nachm Restart erst ins Tablet und dann in die Maschine geguckt aber von den 12/13 waren keine da. Habe noch mal das Spiel neu gestartet aber trotzdem weg.

**Erwartetes Verhalten**

Die schwarzen Lackdosen sollten wie produziert auch in der Maschine liegen.
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

Ich hab kein Bild gemacht

**Comment by DonVitoDiangelo** [comment]
Bitte suche für dein Anliegen den Support auf, vielen Dank.
