### ISSUE TITLE
Kein Boden hinter der Tür [Hotel in Paleto Bay 925]

### ISSUE THREAD

**Issue by ReikaNight** [mexyn/statev_v2_issues#1316]
**Character Name**
Lucia Ashton

**Auftrittszeitpunkt (Datum / Uhrzeit)**
18.03.2021 ca 21:00 Uhr

**Beobachtetes Verhalten**
Bein Näher kommen der Hotel Tür durch den Boden gefallen und 1 Straße weiter im Wald ausgetaucht

**Erwartetes Verhalten**
keine durch lauf bare Tür oder festen Boden 

**Schritte um den Fehler nachvollziehen zu können**
Mit W nach vorne gelaufen und durch die Tür gegangen -> Fallen durch den Boden 

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=FB6YFXOUGVI&ab_channel=JuliaNight

**Comment by DonVitoDiangelo** [comment]
bekannt, gta related, werden wir vermutlich nicht fixen.
