### ISSUE TITLE
Reproduzierung #1157

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1317]
@its4l3x 

Ich konnte jetzt #1157 reproduzieren.

Und zwar muss zur Entstehung das Blaulicht bereits an sein.

Man schaltet dann entweder Motor an/aus, oder schließt den Wagen auf/ab. Direkt danach schaltet man das Blaulicht (E) aus. 

So bekommt man diesen Bug. Der bleibt auch wenn man den Wagen verlässt und wieder einsteigt, und geht erst weg, wenn man die Leuchte (E) wieder betätigt.

Das Yelp ist aber wohl nur für einen selbst hörbar, nicht für andere.

Sollte es zu irrelevant sein, um das zu fixen, könnt ihr es ja wieder schließen, aber zumindest ist mal herausgefunden, wie der Bug zustande kommt.

**Optional: Video / Bilder des Fehlers**

https://youtu.be/oglRskUKzqE
https://youtu.be/OTM0ziWqMac

**Comment by DonVitoDiangelo** [comment]
Danke, aber wie ich schon vorher geschrieben hatte, werden wir hier keine Ressourcen zum fixen einsetzen. :)

**Comment by its4l3x** [comment]
@JannikDatsch 
Ok danke fürs Reproduzieren, sehr interessant zu sehen, dass das das caused. Aber ja, dass ist sowas, was eig. nicht gefixed wird, da das halt so uninteressant ist.
