### ISSUE TITLE
Gamecrash bei Beendigung von Dispatch

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1318]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.03.2021 11:30

**Beobachtetes Verhalten**
Direkt bei Beendigung eines Dispatch Anrufes ist das Game so halb gecrasht.

Ich flog in diesem Moment, wo ich den Anruf im Menü beendete aus dem TS Live Voice und das Dispatch Menü (M) ließ sich nicht mehr schließen. Das Game crashte jedoch nicht komplett, so dass ich noch mit dem Wagen fahren konnte, jedoch halt keine Möglichkeit hatte das Menü zu schließen und so das Game neu starten musste.

Dies ist auch, wenn ich mich richtig erinnere, bereits schon mal vor ein paar Wochen so gewesen

**Comment by its4l3x** [comment]
Haste n Vid?

**Comment by JannikDatsch** [comment]
Ne, leider nicht
