### ISSUE TITLE
Fehler: Hausgarage

### ISSUE THREAD

**Issue by Gartenzaun1** [mexyn/statev_v2_issues#1319]
Hallo zusammen,

ich habe bereits vor zwei Wochen einen Post erstellt, in dem ich um einen Garagenstell in meinem Haus gebeten habe.
(https://github.com/mexyn/statev_v2_issues/issues/1255)
Dieser wurde auch anscheinend hinzugefügt.... oder auch nicht.
Sofern man ein Auto dort einparken möchte taucht unten links über der Minimap folgendes auf:
"Die Garage ist voll" 

Außerdem habe ich mein Fahrzeug vor dem Haus gegen 15:00 Uhr vor dem Haus abgestellt und nach dem Restart war es in zwar in der Hausgarage, allerdings konnte ich es nicht dort ausparken und musste, um es zu "zu befreien", in den Support.

Daher bitte um Überprüfung.

Bei dem Haus handelt es sich um folgendes

Hash:
house_EastLS_25
Roy Lowenstein Blvd. 9

**Comment by DonVitoDiangelo** [comment]
fixed next update. Hat sich leider ein kleiner Fehler eingeschlichen, sry. :)
