### ISSUE TITLE
Fortschritt bei Erz Abbau nicht mehr Sichtbar nach anschmeißen einer Produktion

### ISSUE THREAD

**Issue by Daniel-Meister-508** [mexyn/statev_v2_issues#1320]
**Daniel Meister**

**Auftrittszeitpunkt (19.03.2021 / ca. 16:30 )**

**Beobachtetes Verhalten**
Nach Anschmeißen einer Produktion ist der Fortschritt Balken bei z.B Erzabbau nicht mehr Sichtbar

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

Eine Produktion Anschmeißen und in die Mine Gehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Was genau meinst du mit nicht sichtbar? Bitte mach uns mal ein Bild oder Video davon.

**Comment by TheBroady** [comment]
Er meinte das wenn man auf dem Feld steht ja oben am Bildschirmrand eine Progressbar angezeigt wird. Allerdings gab es einen Bug, dass wenn man eine Produktion in einer Firma angeworfen hat, wurde beim anschließenden Abbau auf einem Feld, keine Prograssbar mehr angezeigt. (Abbau klappt wie gewohnt, nur hat man keine Info mehr, wann man mit dem Abbauen fertig ist.)

Dazu gab es auch schon ein Issue, kann es aber gerade nicht finden.

**Comment by TheBroady** [comment]
Gerade ein zweites issue dazu gefunden. Also duplicate

https://github.com/mexyn/statev_v2_issues/issues/1145

**Comment by JulianMa** [comment]
mit nächstem Update behoben
