### ISSUE TITLE
Tablet Animation wird nicht abgebrochen

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1321]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.03.2021 - 19.27

**Beobachtetes Verhalten**
Holt mein sein Tablet raus, und steckt es wieder weg. Wird die Animation nicht abgebrochen

**Erwartetes Verhalten**
Animation endet wie erwartet

**Schritte um den Fehler nachvollziehen zu können**
Tablet Raus und wegstecken :D

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=RUrPA6Z2D3M

**Comment by its4l3x** [comment]
fixed 12/1 uhr heute nacht
