### ISSUE TITLE
StateNET Teammanagement Einladung Dienstnummer wird nicht direkt übernommen

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#1322]
**Character Name** Erwin Dulach

**Auftrittszeitpunkt (Datum / Uhrzeit)** immer

**Beobachtetes Verhalten** Wenn man jemanden ins Team einläd muss ja Name, Titel, Dienstnummer und Lohnklasse angeben. Nur wird die Dienstnummer nach akzeptieren des Invites nicht übernommen und muss erneut eingestellt werden (man kommt mit DNr 0 rein)

**Erwartetes Verhalten**

Dienstnummer muss nur einmal eingestellt werden.

**Schritte um den Fehler nachvollziehen zu können**

Person ins Team einladen

**Comment by its4l3x** [comment]
fixed
