### ISSUE TITLE
Geblitzt mit angeblich 160 aber nur 10-20 gefahren.

### ISSUE THREAD

**Issue by RoLaBeKa** [mexyn/statev_v2_issues#1325]
**Character Name**
Roland Becker

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.03.2021 21:13

**Beobachtetes Verhalten**
Aktenzeichen: SC307783
Höhe des Bußgeldes: 75$
Fahrzeug: Declasse Burrito
Kennzeichen : KOSHKA
Geschwindigkeit bei Messung: 160.0km/h
Tatzeit: 2021-3-19
Ort: Strawberry Ave - Los Santos Freeway, Innenstadt
Grund: Geschwindigkeit überschritten §3.2 StVo
Ich hatte den Tempobegrenzer AKTIV auf 160 eingestellt bin aber mit NUR 10 - 20 an dem Blitzer vorbeigefahren und dann hat es geblitzt und ich habe mich erschrocken weil ich echt sehr langsam war.

**Erwartetes Verhalten**
Blitzer sollte nicht auslösen.

**Schritte um den Fehler nachvollziehen zu können**
Mit Burrito und aktivem Tempobegenzer auf 160 eingestellt Stadteinwärz fahren rechtzeitig bremsen und abwarten.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by xtorox** [comment]
Ja habe das selbe Problem am PD, siehe Video.

https://www.youtube.com/watch?v=wqHqHPSrXsQ

Begrenzer war auf 200 eingestellt und bin deutlich drunter gefahren
