### ISSUE TITLE
Idee Verkehrssünder Statistik im StateCom

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1326]
**Character Name**
Max Broady

**Idee**
Dort ähnlich wie "Fallakten insgesamt" eine Übersicht wie viele Verkehrssünder pro Tag ein Ticket erhalten haben etc

**Optional: Video / Bilder des Fehlers**
![Screenshot_3](https://user-images.githubusercontent.com/70150887/111840682-1aa42300-88fd-11eb-903d-de960f8eb2e3.jpg)

**Comment by its4l3x** [comment]
Dadurch das die Blitzer mit den Cops nichts zu tun haben, wird das nicht kommen.
