### ISSUE TITLE
Fenster sind schwarz im Haus 

### ISSUE THREAD

**Issue by Schnarch** [mexyn/statev_v2_issues#1327]
Guten Tag,

ich habe eine Schönes Haus am Westhighway mit wunderbaren Blick auf das Meer.
Nur leider ist innerhalb des Hauses alles dunkel.
Könnte man das bitte anpassen? 

[https://pic.statev.de/image/OQChz](url)
[https://pic.statev.de/image/OQMOD](url)
[https://pic.statev.de/image/OQSwV](url)
und weitere Räume. 

Vielen Dank
Thomas Schnarch

**Comment by DonVitoDiangelo** [comment]
Das ist so gewollt, damit man nicht nach draußen schauen kann.

**Comment by Schnarch** [comment]
Wie? ALso bleibt es dunkel? ... Ja danke für die Hilfe :D
