### ISSUE TITLE
#MakeStateComGreatAgain Forum Beitrag

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1328]
**Anliegen**
Es wurde vor geraumer Zeit im Forum ein Aufruf gestartet indem wir um unsere Ideen und Wünsche zum StateCom gefragt wurden.
Da wir nun diese wunderbare Plattform haben um Idee und Wünsche zu Sammeln würde ich gerne den ganzen Bums nochmal auf den Tisch werfen für zukünftige mögliche Anpassungen, sofern die Zeit dazu besteht :)

Forum Beitrag: https://statev.de/forum/list/index.php?thread/10357-sapd-makestatecomgreatagain/
(Wenn gewünscht, schreibe ich alles aus dem Forum raus und erstelle diese hier einzeln als Kommentar)

**Comment by DonVitoDiangelo** [comment]
Sry, aber dies hier ist ein Bugtracker, kein Ideen und Wünsche thread, dafür ist das Forum da mit entsprechendem Bereich.
https://statev.de/forum/list/index.php?board/17-feedback/
