### ISSUE TITLE
Turismo Classic Kofferraum hinten

### ISSUE THREAD

**Issue by Amoxicilllin** [mexyn/statev_v2_issues#1329]
Wenn man beim Turismo Classic den Kofferraum öffnet, dann öffnet sich, so wie auch realistisch vorne die Haube. Um aber nun an das Kofferrauminventar zu kommen muss man nach hinten gehen. Sieht etwas doof aus. Wäre cool wenn man das anpassen könnte wenn es nicht viel Arbeit ist. Bei Bedarf kann ich auch ein Video dafür machen

**Comment by its4l3x** [comment]
Hi,

Kann dich verstehen, ist leider bisschen mehr Aufwand das wieder umzubauen. Kann dich da voll und ganz Verstehen, werden wir aber weiterhin erstmal nicht ändern.

**Comment by Amoxicilllin** [comment]
Alles klar dann weiß ich bescheid. Wenn das viel Aufwand ist dann lohnt es sich auch einfach nicht. 
Vielen Dank fürs prüfen
