### ISSUE TITLE
Hantelstangen bleiben nach Abbau liegen

### ISSUE THREAD

**Issue by badshah23** [mexyn/statev_v2_issues#133]
Yuri_Greene

**Zeitpunkt (Datum / Uhrzeit)**
27.08.2020 16:34

**Beobachtetes Verhalten**
Wenn man die Hantelbank nutzt und dann wieder abbaut, bleiben die Hantelstangen liegen.

**Erwartetes Verhalten**
Sollten nach dem Benutzen und Abbau auch verschwinden.

**Schritte um den Fehler nachvollziehen zu können**
Hantelbank aufgebaut, mit Y Animation gestartet zur Benutzung (hier haben 2 Personen die Bank genutzt) und nach der Nutzung wurde das Item wieder abgebaut aber die beiden Hantelstangen bleiben dann liegen und rollen um her :)

**Optional: Video / Bilder des Fehlers**
![GTA5 2020-08-27 16-34-42](https://user-images.githubusercontent.com/5107384/91537167-2525ad80-e916-11ea-9345-4f6bcc888da1.png)

**Comment by tastydev** [comment]
Sind Objekte die durch GTA-Szenarien entstehen, die räumen sich selber nach ner Zeit auf. Können wir nicht beeifnlussen.
