### ISSUE TITLE
Fahrzeug wird geportet

### ISSUE THREAD

**Issue by JonnyHart** [mexyn/statev_v2_issues#1330]
**Character Name**
Jonny Hart

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.03.2021 gegen 23:30 Uhr

**Beobachtetes Verhalten**
Fahrzeug wird auf die Position von vor 2 Stunden geportet.

**Erwartetes Verhalten**
nicht porten?!

**Schritte um den Fehler nachvollziehen zu können**
Bin am Autohaus zum Salz gestartet, hab dann 1 Stunde Salz gemacht und wollte es in die Mühle bringen. Nach betreten des Gebäudes, wurde das Fahrzeug wieder zum Autohaus geportet.

https://www.twitch.tv/videos/956307493

**Comment by M4rvinLP** [comment]
Hatte das Problem letzte Woche auch gehabt.

**Comment by Hawtin1** [comment]
Ich heute ebenfalls.

**Comment by CaleighRhodes** [comment]
Uns ist es tatsächlich passiert, dass wir auf dem Parkplatz standen und den Port Live mitbekommen haben... das Auto eines Geschäftspartners krachte unvermittelt aus dem Himmel mitten auf die anderen Fahrzeuge... leider hats keiner aufgenommen... war aber schon... STRANGE.

**Comment by TheBroady** [comment]
Tritt vereinzelt immer mal wieder auf

**Comment by JulianMa** [comment]
Siehe #400
