### ISSUE TITLE
Verbesserungsvorschlag: Verpasste Anrufe

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1331]
Es wäre Klasse wenn es einen Button geben würde der ALLE verpassten anrufe auf einmal löscht.
Zur Zeit muss man um **einen** Anruf zu löschen immer auf den Anruf gehen und danach das Handy weg stecken und dann den nächsten löschen.

Das ist bei vielen Anrufen sehr nervig...

**Comment by JannikDatsch** [comment]
Rechtsklick auf die Meldung.

**Comment by Statev-Bonsai** [comment]
das ist doch logisch.. es geht um alle Anrufe mit einmal löschen zu können..
