### ISSUE TITLE
Telefon Auflegen nicht möglich

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1332]
**Character Name**
Max Broady & Reggi Stone

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.03.2021 - 01:27 Uhr

**Beobachtetes Verhalten**
Nach einem Telefonat war dieses nicht mehr auflegbar.
Der Anruf wurde lediglich minimiert und man wurde auf den Hauptscreen geworfen.

**Erwartetes Verhalten**
Anrufe wie gewollt beendet.

**Schritte um den Fehler nachvollziehen zu können**
Noch nicht bekannt..

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=hpmYowSvFZU

**Comment by its4l3x** [comment]
Ok, das ist ja mal super selten sowas. Ich kann bei dem Fehler echt nur Schätzen, kann den Fehler weder Reproduzieren oder finden.

Fehler kommt wenn der Anruf keinem Gegenspieler zuzuordnen ist. Vllt habts ihr beide in der gleichen Sekunde gedrückt.

Auf jeden Fall mal beobachten, würde mich sehr interessieren, wie das zur Stande kommt.

**Comment by TheBroady** [comment]
> Ok, das ist ja mal super selten sowas. Ich kann bei dem Fehler echt nur Schätzen, kann den Fehler weder Reproduzieren oder finden.
> 
> 
> 
> Fehler kommt wenn der Anruf keinem Gegenspieler zuzuordnen ist. Vllt habts ihr beide in der gleichen Sekunde gedrückt.
> 
> 
> 
> Auf jeden Fall mal beobachten, würde mich sehr interessieren, wie das zur Stande kommt. 

Gleichzeitig aufgelegt wars nicht, aber ich behalte das mal im Auge. 🙋🏻‍♂️

**Comment by its4l3x** [comment]
Wäre nice.

**Comment by its4l3x** [comment]
Ist das nochmal aufgetreten?

**Comment by TheBroady** [comment]
So in der art nicht.
Allerdings hatte ich einen anderen Bug mit dem Handy.
Leider jedesmal noch kein Video davon.
Ich eröffne ein Issue sobald ich den mal auf Video bekomme.
