### ISSUE TITLE
Hängendes UI im Hauler nach Begrenzer Betätigung

### ISSUE THREAD

**Issue by powerswissi** [mexyn/statev_v2_issues#1333]
**Character Name**

Roger Thickle

**Auftrittszeitpunkt (Datum / Uhrzeit)**

21. März 2021 12.30

**Beobachtetes Verhalten**

Nach dem ich den begrenzer angemacht habe steckt das UI bei 82kmh fest 

**Erwartetes Verhalten**

er sollte nicht hängen.. also das UI ;-)

**Schritte um den Fehler nachvollziehen zu können**

normal fahren.. dann den begrenzer rein 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

1920x1080

**Optional: Video / Bilder des Fehlers**

![Screenshot_854](https://user-images.githubusercontent.com/70152806/111903226-75469780-8a41-11eb-8fee-503504fc8555.png)

**Comment by powerswissi** [comment]
Es ist auch kein x menü verfügbar

**Comment by its4l3x** [comment]
client log? fehler? etc...

**Comment by powerswissi** [comment]
Neagtiv .. gab keine client log. der letzte crash war am 19.3.2021 bei mir 

war ja auch ekin crash .. ich hab das spiel selber beendet da ich nix mehr machen konnte mit X,E,I

**Comment by its4l3x** [comment]
Einen Client log gibt es immer, zu jeder Spielsession.. den bräuchte ich bitte.

**Comment by powerswissi** [comment]
[client_21-03-2021_10-36-45.log](https://github.com/mexyn/statev_v2_issues/files/6183195/client_21-03-2021_10-36-45.log)
[client_21-03-2021_12-36-42.log](https://github.com/mexyn/statev_v2_issues/files/6183196/client_21-03-2021_12-36-42.log)


sry habs mit der crash log verwechselt

**Comment by Hutstaender** [comment]
Immer noch? Konnte nicht nachgestellt werden.

**Comment by powerswissi** [comment]
negativ kann geschossen werden
