### ISSUE TITLE
Rückgabe Bodhi in Grapeseed hat 2x nicht funktioniert - je 500$ sind weg

### ISSUE THREAD

**Issue by Benjik87** [mexyn/statev_v2_issues#1334]
**Character Name**
Fritz_Kolbe

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.8.2021 gegen 17 Uhr

**Beobachtetes Verhalten**
Ich wollte meinen Leihwagen (Bodhi) in Grapeseed abgeben. Ich es 2x versucht und musste je 500$ zahlen. Beim ersten gescheiterten Versuch dachte ich, dass es nicht funktioniert hat, weil das Fahrzeug noch leicht fuhr. Ich bin dann nochmals zur Bank um nochmals 500$ abzuheben. Aber beim 2ten Versuch hat es wieder nicht funktioniert. Trotzdem wurde das Geld aus dem Inventar genommen.

**Erwartetes Verhalten**
Normalerweise hätte das Fahrzeug schon beim ersten Versuch verschwinden müssen.

**Schritte um den Fehler nachvollziehen zu können**
Mit dem Fahrzeug (einem Bodhi) nach Grapseed zum Fahrzeugverleiher fahren. Dort mit "e" das Fahrzeug zurückgeben. Das Fahrzeug kommt Ursprünglich nicht von diesem Verleiher. Ggf. kommt noch die Aussage, dass das Fahrzeug beschädigt sei obwohl die Motorleuchte aus ist. Fahrzeugverleiher will auf jeden Fall 500$ für die Rückgabe.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
-

**Optional: Video / Bilder des Fehlers**
Leider nein. Das ist das erste Mal, dass ich mich an den Support wenden muss. Ich muss wohl in Zukunft einen Screenshoot machen.

**Comment by DonVitoDiangelo** [comment]
Gab es denn unten links eine Meldung, als du versucht hast das Fahrzeug zurück zu geben.

**Comment by Benjik87** [comment]
Ja, dass das Geld abgebucht wurde in rot und ich glaube in Grün, dass das was zurückgebucht wurden. Wurde aber nicht. Ich kann es aber nicht mehr genau sagen. Wusste leider zu dem Zeitpunkt nicht, was passiert. --Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 21.03.21, 18:55 schrieb DonVitoDiangelo ***@***.***>:

   
  Gab es denn unten links eine Meldung, als du versucht hast das Fahrzeug zurück zu geben?
