### ISSUE TITLE
Fahrzeug spawned während Serverrestart auf dem Ausparksmann

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#1335]
**Character Name**
Paul Humpert

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.03.2021 / 17:57-18:06

**Beobachtetes Verhalten**
Hab kurz vor Serverrestart mein Auto ausgeparkt bin ein paar Meter gefahren. Dann startete der Server neu und als ich wieder ins Game kam, lag das Auto auf dem Parkwächter.

**Erwartetes Verhalten**
Das sollte nicht passieren, Auto sollte normal eingeparkt werden.

**Schritte um den Fehler nachvollziehen zu können**
- Fahrzeug kurz vor Serverrestart ausparken
- wenige meter von Garage entfernen und dann durch Serverneustart gekickt werden
- Garage in der Nähe prüfen

Video vom Fehler:
https://www.youtube.com/watch?v=UO4B2BBV6No

**Comment by DonVitoDiangelo** [comment]
Schlechtes Timing, letzte Safe war dann halt genau da. Wird nicht oft vorkommen und ist in dem Sinne auch kein Bug.
