### ISSUE TITLE
Auftragsauktion: Holzbretter entfernt?

### ISSUE THREAD

**Issue by ZacCooperr** [mexyn/statev_v2_issues#1337]
**Zac Cooper**

**19.03. bis 22.03.**

**Wir konnten seit dem letzten Update v2.0.42 feststellen, dass bis dato keine Holzaufträge(Bretter) in den Auftragsauktionen aufgetaucht sind. Wir haben drei Tage gewartet um uns relativ sicher zu sein, dass keine Aufträge mehr eingehen.**

**Da im Ressourcenexport schon seit längerer Zeit die Holzbretter herausgenommen worden sind und jetzt seit paar Tagen auch keine Holzaufträge mehr in der Auftragsauktionen eingehen, wurde dem Sägewerk jegliche Art genommen. Wir bitten darum, dass wenigstens wie auch in den anderen Branchen eine Ressource für die Abgabe zurückkommt. Eine Goldschmiede hat z.B. 5.Möglichkeiten, eine Raff 3.Möglichkeiten, etc.. Es wäre schön, wenn neben Holzbretter auch eventuell Pappe mit aufgenommen wird in einer der beiden "Exporten"**

**Bitte einmal die Auftragsauktionen überprüfen für Sägewerke**
Vielen Dank!

**Comment by DonVitoDiangelo** [comment]
Der Export wird in der Zukunft rotieren. Wenn etwas jetzt aktuell nicht da ist, heißt das nicht, das es immer so bleiben wird.
