### ISSUE TITLE
Bootsgarage Bananeninsel die Zweite

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1338]
Ich hatte es ja damals schon gemeldet..
https://github.com/mexyn/statev_v2_issues/issues/1264

Der Punkt ist immer noch deutlich zu hoch über dem Wasser...

![Screenshot_8](https://user-images.githubusercontent.com/70241137/111978987-d4211500-8b04-11eb-8e9e-4e88bcad2e5e.jpg)

**Comment by DonVitoDiangelo** [comment]
Da müssen wir dann wohl die Range erhöhen.

**Comment by Statev-Bonsai** [comment]
Mit normalen Booten gibts auch diese Probleme...
Und das Uboot einparken ist halt unmöglich ;D

**Comment by DonVitoDiangelo** [comment]
Ja, die Range ist halt zu klein, da soll nen Tug einparken können aber auch dein halb unter der Wasserlinie liegendes Uboot.
