### ISSUE TITLE
Keine Dispatchmeldung in Firmen möglich

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1339]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.03.2021

**Beobachtetes Verhalten**
Es ist  nicht mehr möglich, Dispatches in Firmengebäuden abzuschicken. 

Hängt wahrscheinlich mit dem letzten Update zusammen, ab dem man auf der Insel keine Dispatches mehr abschicken konnte.

**Erwartetes Verhalten**
Es ist möglich.

**Schritte um den Fehler nachvollziehen zu können**

![Grand Theft Auto V Screenshot 2021 03 22 - 13 25 34 96](https://user-images.githubusercontent.com/70178420/111989592-43e9cc80-8b12-11eb-888c-5c1572036206.png)

**Comment by Statev-Bonsai** [comment]
Das war m.e. noch nie in Firmen möglich da das Interior irgendwo auf der Insel gemappt ist und es zu einem falschen ergebnis führen würde..

**Comment by Bene-RonnyMoritz** [comment]
Ist gewollt das dies nicht geht. 
Wie Bonsai schon schreibt: Das Interior liegt in einer anderen Dimension. 

Es gibt einfach keinen Empfang in den Gebäuden. Dann muss man einfach vor die Tür um den Notruf abzusetzen

**Comment by DrGrizzlY17** [comment]
Jap, as already mentioned. Ist so nicht gewollt
