### ISSUE TITLE
Fahrzeuginventar über Firma erreichbar trotz Kofferraum abgeschlossen

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#134]
Dan_Lee

**Zeitpunkt (Datum / Uhrzeit)**
28.08.2020

**Beobachtetes Verhalten**
Ich erreiche das Fahrzeuginventar über das Firmenmenü -> Lager trotz das der Kofferraum abgeschlossen ist. Kann aber keine Transaktion von Items vornehmen solange es abgeschlossen ist.

**Erwartetes Verhalten**
Kein Zugriff, wenn der Kofferraum abgeschlossen ist

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug auf Entladepunkt
Kofferraum zulassen
An Firmenpunkt laufen
E drücken und Lager drücken

**Optional: Video / Bilder des Fehlers**
https://youtu.be/2kHUmmeTc-M

**Comment by DrGrizzlY17** [comment]
Nachtrag:
Das gleiche gilt beim Farming. Wenn ich z.B Quarzsand abbaue und der Kofferraum des Fahrzeuges ist zu, kann ich den Ertrag nicht einladen. Schließe ich das Inventar um den Kofferraum zu öffnen, verliere ich den Farmingertrag

**Comment by its4l3x** [comment]
fixed, next update gibts ne Meldung davor.
