### ISSUE TITLE
Gurkenfeld (und vermutlich ähnliche Felder) mit zu langer Aufstehanimation

### ISSUE THREAD

**Issue by RomanSpielberg** [mexyn/statev_v2_issues#1340]
Roman_Spielberg

Immer 

Man erntet mit der Schaufel die Gurken, das Auswahlfenster kommt hoch, man zieht sich seine Sachen rüber und schließt den Dialog .... nun heißt es warten, da die Aufstehanimation noch läuft. Das nervt wirklich unheimlich und tritt so sonst nirgends auf, nimmt jeden Spaß, leider meine Meinung.

Kürzere Aufstehanimation

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/768
