### ISSUE TITLE
Waffenfertigungen und Ammunation die Zweite...

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1341]
Vor drei Monaten hatte ich dieses Thema eröffnet--> https://github.com/mexyn/statev_v2_issues/issues/891
Leider gab es keinerlei Reaktionen, daher hole ich das Thema nochmal hoch...

Die hergestellten Langwaffen auf der Bananeninsel können ja nun auch nicht  im Ammunation verkauft werden, genauso wie die Zubehörteile.

Langsam aber sicher geht der Ammunation wirtschaftlich den Bach runter weil da so gut wie kein Durchlauf mehr herrscht, da muss was passieren!

Daher wäre es klasse wenn sich da was ändert, z.b. das man wenigstens die Waffenanbauteile dort verkaufen kann..

Und für die Waffenfertigung wäre es Klasse wenn man Schwarzpulver exportieren könnte!

**Comment by DonVitoDiangelo** [comment]
Keine duplicates bitte. Das Ticket wird zu gegebener zeit seine Beachtung finden. Daher auch  "enhancement".
