### ISSUE TITLE
Animation Salat, Gurken und Kartoffeln | Vorschlag zur Güte ...

### ISSUE THREAD

**Issue by JonnyHart** [mexyn/statev_v2_issues#1342]
**Character Name**
Jonny Hart

**Auftrittszeitpunkt (Datum / Uhrzeit)**
ständig, zu jeder Tages- und Nachtzeit

**Beobachtetes Verhalten**
Animation länger als Abbauprozeß

**Schritte um den Fehler nachvollziehen zu können**
Abbau des jeweiligen Rohstoffes

Ich hätte ein Vorschlag zur Güte:

Anhebung der Dauer des Abbauprozeß, dann kommt die Animation nicht her solange vor und ....
Animation Dauer = Abbauprozeßdauer

**Comment by DonVitoDiangelo** [comment]
Zu dem Thema ist nun bereist mehrfach und auch alles gesagt. Hier wird es keine Änderung geben, schon gar nicht zulasten der Farmzeit.
