### ISSUE TITLE
Teleporter zum Dach des Hochhauses

### ISSUE THREAD

**Issue by DettmarDettmers** [mexyn/statev_v2_issues#1344]
Name: Dettmar_Dettmers

Anfrage: Zugang per Teleporter zum Dach des Hochhauses. Wurde damals schon angefragt, als StateV noch auf RageMP war. Da wurde gesagt, dass ein paar Teleporter nur Testweise eingeführt worden sind und man nochmal fragen soll, wenn der Server auf AltV gewechselt ist. Nun sind ein paar Monate vergangen und der Wunsch, dass man das Dach des Bürogebäudes betreten kann, ist immer noch vorhanden, da sonst nur per Fallschirm erreichbar leider. 

Gebäude: https://pic.statev.de/image/toooower.nPQOI
Eingänge unten: https://pic.statev.de/image/eingagn1.nPTdq
                           https://pic.statev.de/image/eingang2.nPtz7
Tür Dach: https://pic.statev.de/image/dach-eingang1.nP9Vc

**Comment by DonVitoDiangelo** [comment]
@DrGrizzlY17  Aber nur 1 Eingang

**Comment by DettmarDettmers** [comment]
Na klar, ging nur um die beiden Möglichkeiten ❤
