### ISSUE TITLE
Big T4sty Burger und V Burger 

### ISSUE THREAD

**Issue by RomanSpielberg** [mexyn/statev_v2_issues#1345]
Roman_Spielberg

Bitte mal die beiden Items vom Gamedesign überprüfen, das Rezept ist für beide Burger gleich und auch wieviele bei einer Produktion rauskommen ist gleich. 
Am Anfang war mal zumindest der Unterschied, das der V-Burger keinen Käse benötigte. 
Der einzige Unterschied ist aktuell noch das Gewicht, der vermeintlich Große "Big T4sty Burger" wiegt 0.25 und der V-Burger 0.40 .... :-/
Mein Vorschlag wäre beim T4Sty Burger noch Speck (Schweinespeck roh verpackt) zuzufügen (alternative zu Bacon) und ggf. das Gewicht anpassen.

**Comment by DonVitoDiangelo** [comment]
Das wurde damals schon Aufgrund von Feedback geändert. Es gab da mal einen Unterschied, aber der eine war demnach dann schlicht billiger als der andere und wurde demnach auch mehr gegessen. Damit diese dann auf gleicher Höhe waren, wurden die Rezepte in den Fällen angeglichen.
