### ISSUE TITLE
Anfrage Garage

### ISSUE THREAD

**Issue by Skipp4r** [mexyn/statev_v2_issues#1347]
**Character Name: Frank Schmied**
**Haus ID: SandyShores57**

Hallo liebes Support Team,
Ich möchte gerne eine Garage in Sandy Shores anmelden.
Meine Hausnr ist SandyShores57, da sich unmittelbar dahinter eine Garage befindet und nicht zugeordnet ist, möchte ich diese gerne für mich beanspruchen.
Ich hoffe das Sie mir bei meinem Anliegen weiterhelfen können.
MFG Skipp4r

![20210325181404_1](https://user-images.githubusercontent.com/81380594/112515139-4cead000-8d96-11eb-986d-ee508a5a8735.jpg)
![20210325181412_1](https://user-images.githubusercontent.com/81380594/112515071-3cd2f080-8d96-11eb-87f6-3db36fbf203b.jpg)
![20210325181425_1](https://user-images.githubusercontent.com/81380594/112515108-452b2b80-8d96-11eb-8395-36816cb02082.jpg)
![20210325181450_1](https://user-images.githubusercontent.com/81380594/112517384-8b818a00-8d98-11eb-9bc3-922d8424b19d.jpg)

**Comment by DrGrizzlY17** [comment]
Das isn Schuppen und keine Garage. Daher abgelehnt
