### ISSUE TITLE
GitHub webhook im discord ist kaputt 

### ISSUE THREAD

**Issue by Chrinis007** [mexyn/statev_v2_issues#1349]
**Character Name**
Discord

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Siehe Zeitpunkt letzter Nachricht 

**Beobachtetes Verhalten**
Webhook postet keine neuen Bugtracker Einträge mehr 

**Erwartetes Verhalten**
Webhook postet neue Bugtracker Einträge

**Schritte um den Fehler nachvollziehen zu können**
Im Discord issues-log öffnen 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
wieder am laufen ;)
