### ISSUE TITLE
offenen Kofferaum kann mann ohne schlüssel nicht mehr schließen

### ISSUE THREAD

**Issue by glb11** [mexyn/statev_v2_issues#135]
**Character Name**
Jens_Summer

**Zeitpunkt (Datum / Uhrzeit)**
28.08.2020 10:50

**Beobachtetes Verhalten**
Wenn mann von einen Auto keinen Schlüssel dabei hat/bzw an einem Fremden Auto ist wo der Kofferraum geöffnet ist kann mann diesen nicht mehr schließen sondern es kommt die Fehlermeldung: Sie besitzen keinen Schlüssel für dieses Fahrzeug  

**Erwartetes Verhalten**
Schließen sollte immer möglich sein egal ob mann nen Schlüssel hat oder nicht. Wie aktuell auf dem Liveserver auch

**Schritte um den Fehler nachvollziehen zu können**
Bei eigen Auto schlüssel vom Schlüsselbund nehmen und in ein Anderes Fahrzeuginventar (Rucksack? (auf Beta nicht getestet ob das reicht) legen und davor aber den Kofferraum öffnen und ihn dann versuchen zu schließen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920*1080

**Optional: Video / Bilder des Fehlers**
https://youtu.be/WM1_KUsvlDc

**Comment by eiksch** [comment]
fixed next update
