### ISSUE TITLE
Geblitzt im U-Bahn Tunnel

### ISSUE THREAD

**Issue by KruemelGames** [mexyn/statev_v2_issues#1350]
Dave Weinstein

25.3. 20.57Uhr

Wurde geblitzt im U-Bahn Tunnel

Man wird dort nicht geblitzt weil der Blitzer oberirdisch ist

Zu schnell im U-Bahn Tunnel fahren (unterm MD Highway)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

https://pic.statev.de/image/20210325205728-1.nXSI7

**Comment by its4l3x** [comment]
Nach dem Update?

**Comment by KruemelGames** [comment]
vor dem Update

**Comment by its4l3x** [comment]
Passt, ist mit dem Update um 18 Uhr gefixed worden
