### ISSUE TITLE
vOS - Designfehler

### ISSUE THREAD

**Issue by saltym** [mexyn/statev_v2_issues#1353]
**Character Name**
Eliot_Moore

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.03.2021 19:30

**Beobachtetes Verhalten**
Fehler im Padding:
Ticket-App "Keine Tickets vorhanden" - Padding links fehlt
Tastenfeld Input - Padding rechts fehlt, Buchstaben können eingegeben werden
Notruf-App - Container von aufgeklapptem Button breiter als Container des jeweiligen Services (somit nicht bündig)

**Erwartetes Verhalten**
Ticket-App "Keine Tickets vorhanden" - Padding gleichmäßig
Tastenfeld Input - Padding gleichmäßig & Restriction auf Nummern, Buchstaben somit verbieten
Notruf-App - Container von aufgeklapptem Button bündig mit Container des jeweiligen Services

**Schritte um den Fehler nachvollziehen zu können**
Jeweilige Apps öffnen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
![texteingabe in nr](https://user-images.githubusercontent.com/55654646/112730918-940ec780-8f34-11eb-8bfd-28cc427dbbb7.png)
![padding2](https://user-images.githubusercontent.com/55654646/112730923-95d88b00-8f34-11eb-93f3-63b8b77091f9.png)
![padding1](https://user-images.githubusercontent.com/55654646/112730926-98d37b80-8f34-11eb-8d13-74fec9663325.png)

**Comment by Hutstaender** [comment]
Tastenfeld Input: fixed, das padding war's nich aber ich weiß was du meinst
Ticket App: fixed
Notruf-App: ist gewollt, soll nen ripcage Effekt erzeugen
