### ISSUE TITLE
Ammunation - Falsche Transportgruppe

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1354]
Tritt bei Verpackten Taschenlampen, Verpackten HK416 + Verpackten M40A1 Magazinen auf...

![Screenshot_2](https://user-images.githubusercontent.com/70241137/112735519-e2c85b80-8f4c-11eb-868f-1562700f77fb.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/70241137/112735520-e6f47900-8f4c-11eb-902f-39e7222550cd.jpg)

**Comment by DonVitoDiangelo** [comment]
Verpackten Taschenlampen -> Cop
Verpackten HK416 -> Cop
Verpackten M40A1 Magazinen -> Gibt es nicht mehr (Sniper Stuff)
