### ISSUE TITLE
Coca/Opium Tisch Error

### ISSUE THREAD

**Issue by ManuelLadner** [mexyn/statev_v2_issues#1355]
**Manuel_Ladner**

**27.-28.3.2021 / Ganztägig (Datum / Uhrzeit)**

**error.drugprod.start.hasnotools**

**Produktion sollte starten**

**anzug an, tisch hinstellen, werkzeug rechts rein und produkt links rein (wie am bild ersichtlich), produktion starten**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by ManuelLadner** [comment]
Wurde auch an anderen Standorten getestet nicht am selben! Sogar mit unterschiedlichen Tischen!

**Comment by Statev-Bonsai** [comment]
Nimm mal nen neues Messer!

**Comment by Statev-Bonsai** [comment]
Und nächstes mal NICHT irgendwelche Bilder mit den Rezepturen veröffentlichen, schwärze entsprechende Stellen...
Man weiß wie die Leute sind!

**Comment by DonVitoDiangelo** [comment]
Japp, liegt am benutzten Messer :) Einfach mal nen neues nehmen
