### ISSUE TITLE
Massives Syncproblem

### ISSUE THREAD

**Issue by FarkasCian** [mexyn/statev_v2_issues#1356]
**Farkas_Cian**

**Sonntag 28.03.2021, 10:30 Uhr**

**Personen werden nicht gesehen oder laufen ca. 3-4m abseits ihrer eigentlichen Position (also zwischen Position in der sich der Spieler sieht und Position in der die anderen Spieler ihn sehen**

**Position Spieler = Position in der er gesehen wird**

**Größere Gruppe (Lifeinvader Frühsport) mit Gehstil: Joggen durch die Stadt unterwegs**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Kann durch sehr viele Faktoren zusammen hängen. Kann am Server sein, welcher kurz ein Delay hatte
Kann auch sein, dass du gerade einfach die Pakete vom Server nicht entgegennehmen kannst, weshalb sich das für dich alles verzögert.

Leider in dem Falle nicht reproduzierbar. Daher Close
