### ISSUE TITLE
Preisverfall Diamanten...

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1358]
Ich hatte euch damals ja schon das leid mit den Diamanten geklagt...

https://github.com/mexyn/statev_v2_issues/issues/1305

Mittlerweile kauft Bonsai sie schon ca zwei Wochen nicht mehr an, der Preisverfall ist seitdem extrem geworden.
Das einzige Preisstabilisierungselement, der Export wurde entfernt und somit ist der Preis mittlerweile unter dem von Bergkristallen!

Bitte fügt die Diamanten wieder in den Export ein, wie früher bis 11.200$ damit der Preis stabilisiert wird!

Das Problem ist Hausgemacht, da hätte man bevor man sie aus dem Export nimmt über eine bessere Verwendung nachdenken müssen!

Anbei noch 2 Dashbord Werbungen von heute...
![Screenshot_6](https://user-images.githubusercontent.com/70241137/112762560-8292f180-9000-11eb-8ca7-135285230941.jpg)
![Screenshot_7](https://user-images.githubusercontent.com/70241137/112762561-84f54b80-9000-11eb-8762-cd2e1bb53b3d.jpg)

**Comment by DonVitoDiangelo** [comment]
Marktlage schwankt
