### ISSUE TITLE
Afterhour Tisch verschwindet spurlos noch vor dem Platzieren

### ISSUE THREAD

**Issue by Clawdie** [mexyn/statev_v2_issues#1359]
Glinda Ehrmantraut
Lasse Leverstone

**Auftrittszeitpunkt (Datum / Uhrzeit)**
vor ca. 8-10 Tagen
am 28.3.21 gegen 20 Uhr

**Beobachtetes Verhalten**
Tisch im Inventar, Rechtsklick zum Platzieren --> Tisch weg
Nicht woanders, noch nicht gesetzt, einfach weg.

Nach 1. Vorkommen bereits Support aufgesucht, es hieß: Tisch existiere nicht (?)

**Erwartetes Verhalten**
Platzieren von Objekten wie üblich

**Schritte um den Fehler nachvollziehen zu können**
Afterhour Tisch im Inventar, Platzieren, hier beide Male am Hotel (Helldogs Place) in Paleto Bay gegenüber Garage

**Comment by Enemyaa** [comment]
Hi @Clawdie 
Ich kann das Problem leider nicht nachstellen, da es bei mir einwandfrei funktioniert.
Es gibt auch mittlerweile einige Spieler die diesen Tisch nutzen und auch keine Probleme haben.

**Comment by Clawdie** [comment]
@Enemyaa An anderen Orten haben wir den auch schon problemlos aufgestellt.
Ist beide Male nur am genannten Ort aufgetreten (zwischen den Pollern und den Sofas/dem Sessel).
