### ISSUE TITLE
Sack auf dem Kopf nach Notfall MD

### ISSUE THREAD

**Issue by RuedigerRommel** [mexyn/statev_v2_issues#136]
**Ruediger_Rommel**
Tyrone Jones

**Zeitpunkt (Datum / Uhrzeit)**
 26.08.2020    22:00

Sack ist nach Notfall MD immer noch auf dem Kopf

**Erwartetes Verhalten**
Sack ist genauso wie die Handfesseln verschwunden

**Schritte um den Fehler nachvollziehen zu können**
Jemand wurde mit sack auf dem Kopf gefesselt und ist Gestorben. Nach aufwachen im Notfall MD sind die Fesseln verschwunden der Sack ist aber immer noch auf dem Kopf.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by eiksch** [comment]
fixed next update
