### ISSUE TITLE
StateNET komisches aussehen

### ISSUE THREAD

**Issue by Chrinis007** [mexyn/statev_v2_issues#1360]
**Character Name**
Christian_Maier

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit ein paar Tagen

**Beobachtetes Verhalten**
Komische schwarze Felder

**Erwartetes Verhalten**
So wie früher ohne schwarze Felder

**Schritte um den Fehler nachvollziehen zu können**
StateNET öffnen
Benutze Browser
Chrome (IOS)
Safari (IOS)
Firefox (Windoof) 

**Optional: Video / Bilder des Fehlers**
![grafik](https://user-images.githubusercontent.com/70342279/112766775-9dbb2c80-9013-11eb-941a-24acf269509e.png)

**Comment by TheBroady** [comment]
Kann ich nicht bestätigen,
Firefox, Chrome und Opera getestet, dort ist alles normal.

**Comment by CaleighRhodes** [comment]
Nutze ebenfalls Chrome, auch bei mir alles normal.

**Comment by Dean-Gallagher** [comment]
Ich sowie einige andere auch haben das Problem mit Firefox auf der aktuellsten version.
