### ISSUE TITLE
Bodenproben beschriften

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1361]
**Wunsch**
Das man es möglich macht wie bei Schlüsseln, Bodenproben zu beschriften.
Derzeit sind Bodenproben immer gleich benannt und so kann man wenn man mehrere nimmt keinen Überblick behalten sofern die Bodenproben an verschiedenen Orten entnommen wurden.

**Optional: Video / Bilder des Fehlers**
![Screenshot_5](https://user-images.githubusercontent.com/70150887/112848695-a4e04a00-90a8-11eb-8f37-e14ac6dc7171.jpg)

**Comment by its4l3x** [comment]
done next update
