### ISSUE TITLE
Fahrzeug auf-/zusperren; Ton

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1362]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit V2 ?

**Beobachtetes Verhalten**
In V1 hörte man noch, wenn jmd. das Auto auf/zu schließt. Seit V2(?) hört man es nur noch, wenn man es selber macht, nicht jedoch, wenn andere auf und zu sperren.

**Erwartetes Verhalten**
Sollte eig. wieder so sein wie zu V1

**Comment by its4l3x** [comment]
Future is Calling.
