### ISSUE TITLE
Enus Windsor Design-/Beschriftungswechsel

### ISSUE THREAD

**Issue by Uleasht** [mexyn/statev_v2_issues#1363]
**Legan_Cole**

**30.03.21 14:00Uhr (Tritt aber permanent auf)**

**Enus Windsor wechselt immer wieder die Beschriftung/Design**

**Die normale schwarze Farbe beibehalten oder ein selbst ausgesuchtes Design beibehalten**

**Enus Windsor kaufen/bauen -> aus einem Gebäude gehen -> ausloggen/einloggen -> aus Garage ausparken -> sich dem Fahrzeug zu weit entfernen so dass es sich neu lädt**

**Video: (https://youtu.be/_lnFtrNvRHg)**

**Comment by TheBroady** [comment]
Gleiche Problem wie bei einem der Speed Mustangs des SAPD.
Kennzeichen: SEU 9O5

**Comment by Chrinis007** [comment]
Duplikat von #337
