### ISSUE TITLE
UI nach TAB drücken verschoben

### ISSUE THREAD

**Issue by annalurch** [mexyn/statev_v2_issues#1364]
**Character Name**

Skyler_Grey

**Auftrittszeitpunkt (Datum / Uhrzeit)**

30.03.2021 18:50Uhr

**Beobachtetes Verhalten**

Nach dem drücken von der TAB Taste ist das ganze UI verschoben

**Erwartetes Verhalten**

Es sollte nur das Messer gezogen werden

**Schritte um den Fehler nachvollziehen zu können**

Stand bei ein paar leuten, wolltte das messer ziehen, UI komplett verrutscht.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

1920x1080

**Optional: Video / Bilder des Fehlers**

Video war zu groß deswegen hier der Youtbe link.
https://youtu.be/kiMYMDwxY2w

**Comment by MisterCopeland** [comment]
Vielleicht gut zu wissen: Das passiert nur wenn man mehr als 3 Funkfrequenzen eingespeichert hat. Weil das Mausrad das UI vom Funkgerät anspricht statt nur das Waffenrad...

**Comment by Chrinis007** [comment]
Duplikat von #253
