### ISSUE TITLE
Ausparken und Entrümpeln

### ISSUE THREAD

**Issue by RoyMckellar** [mexyn/statev_v2_issues#1365]
**Roy Mckellar**

Seit der V.2 mit regelmäßigen Abständen habe ich dieses Problem.

Beim Ausparken im "**Joshua Road Circle 2432** / **JunSandyShoresRew_House_14**" steht mein Pounder ab und zu quer, liegt auf der Seite oder auf dem Rücken. Die Ursache dafür könnte das von meinem Vormieter zurück gelassene Fahrgestell, was ich natürlich zur Beweissicherung **[Fotografiert](https://roymckellar.de/bug/)** und mit einer [1](https://roymckellar.de/bug/) gekennzeichnet habe sein.

Weiter sind auch viele Gegenstände wie ein alter Autosessel [(2)](https://roymckellar.de/bug/), eine Eisenbahnachse [(3)](https://roymckellar.de/bug/), ein verfranztes Sofa [(4)](https://roymckellar.de/bug/), Stühle, Tisch und Grill [(5,6)](https://roymckellar.de/bug/) sowie zwei defekte BMX-Räder [(7)](https://roymckellar.de/bug/) zurück gelassen worden. Auch die Bäume[ (9)](https://roymckellar.de/bug/) hatten anscheinend zu viel Strahlung von der daneben stehenden Microwelle[ (9) ](https://roymckellar.de/bug/)abbekommen.

**Es ist mir ein Anliegen eine Entrümpelung bei der Stadt zu beantragen, dieses aber IC noch nicht möglich ist um oben erwähnte Dinge[ (1-9) ](https://roymckellar.de/bug/)aus meinem Garten zu entfernen.**

**Besucht mich zuhause im "**Joshua Road Circle 2432** / **JunSandyShoresRew_House_14**"**

**https://roymckellar.de/bug/**

Mit freundlichen Grüßen
und Dankbarkeit für dieses Projekt
**Roy Mckellar**

**Comment by CaleighRhodes** [comment]
Wieso parkt man einen Pounder in eine Hausgarage, deren Eingang und komplette Größe kleiner ist, als das Fahrzeug selbst?

**Comment by zarazandra** [comment]
> Wieso parkt man einen Pounder in eine Hausgarage, deren Eingang und komplette Größe kleiner ist, als das Fahrzeug selbst?

Wo steht denn da was von Hausgarage?
Die Fahrzeuge verschieben sich auch, wenn die Map neu geladen wird, z. B. Wenn man rein und wieder raus geht.

**Comment by CaleighRhodes** [comment]
Hier: Beim Ausparken im "Joshua Road Circle 2432 / JunSandyShoresRew_House_14" steht mein Pounder ab und zu quer

**Comment by RoyMckellar** [comment]
Wieso einparken? **Ausparken** ist das Problem.

**Comment by CaleighRhodes** [comment]
Das ist schon klar, Roy. Mir stellt sich nur die Frage, warum du kritisierst, dass dein Fahrzeug blöd ausgeparkt wird, wenn du es in einer Garage einparkst, die faktisch nicht dafür geeignet ist. Hätte ich von dir halt nicht gedacht, da du immerhin einer der Spieler bist, die extrem auf schlüssiges RP achten (ich sage nur vor V2 am Ockerfeld extra Animation ausgeführt, damit du nicht, wie andere, nach dem ersten Schippen wieder aufstehst und dann dumm rum stehst oder erschöpfst übers Feld rennen statt wie andere mit Full Speed).

Bin halt der Meinung, ein Pounder/Benson/PhantomPackerHauler/Mixer/Rubbel and so on gehören nicht in ne Hausgarage. Ich selber parke die Arbeitsfahrzeuge in der nächsten öffentlichen, auch wenn das ein Stück weg ist. Darauf bezog sich mein Satz.

**Comment by DrGrizzlY17** [comment]
Hi zusammen,

ich gucke mir das mit der Garage die Tage an.

@CaleighRhodes ich bitte dich sowas vielleicht mit Roy persönlich zu klären und nicht im BugTracker. Vielleicht erfährst du auch die Umstände für das geparkte Nutzfahrzeug. (Bedenke unser System zum automatischen einparken, da kann Roy z.B dann nichts für wenn es in der HG landet)

Kuss und Gruß geht raus

**Comment by DrGrizzlY17** [comment]
@RoyMckellar Hi Roy,

das Chasis ist entfernt mit dem nächsten Update. Der Rest bleibt bestehen, da es in die Location passt und nicht im RP stört

**Comment by RoyMckellar** [comment]
Ich bedanke mich recht herzlichst.

Am Di., 6. Apr. 2021 um 08:57 Uhr schrieb StateV_Dan <
***@***.***>:
