### ISSUE TITLE
"Kaugummi unterm Schuh" ~Teleportieren von Punkt zu Punkt in Animation

### ISSUE THREAD

**Issue by StateV-Larry** [mexyn/statev_v2_issues#1367]
**Charakter Name**
Larry_Klein

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit ca. Februar 2021

**Beobachtetes Verhalten**
Nach einer getätigten Animation, wird diese von mir beendet und ich gehe mit meinem Charakter normal weiter. Bei anderen mache ich diese Animation aber noch: Entweder in einer Dauerschleife vor ihnen oder ich teleportiere mich bei ihnen durch die Gegend. Mir wird dann gesagt, dass ich "Kaugummi unterm Schuh" habe. Mein Charakter muss sich dann auf einen Stuhl setzen oder auf den Boden schmeißen damit ich bei anderen wieder normal laufe. 
Ich habe auch schon bei anderen mitbekommen, dass sie so ein Problem haben.

Gibt es irgend eine Einstellung oder vllt ein HotFix damit sowas reduziert oder gar komplett verschwindet?

**Comment by StateV-Larry** [comment]
https://www.youtube.com/watch?v=oMVnldzVHus
Ich glaube da sieht man das etwas deutlich (Bin die Person welche sich hin und her teleportiert)

**Comment by its4l3x** [comment]
Merci

**Comment by DonVitoDiangelo** [comment]
Hat sich das Problem mit dem letzten alt:V Update behoben?

**Comment by JannikDatsch** [comment]
@DonVitoDiangelo Nein, kommt weiterhin vor

**Comment by TheOutburst** [comment]
#2116
