### ISSUE TITLE
Kofferräume nach Nutzung des Brecheisen schließbar machen

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1368]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.04.2021

**Beobachtetes Verhalten**
Wenn man ein Fahrzeug aufbricht welches abgeschlossen ist, ist anschließend der Kofferraum nicht schließbar
Damit Diebstahl vermieden wird, nehmen wir anschließend immer alles raus um es der Person direkt zu geben. Was bei gewissen Mengen aber zu Problemen führt.

**Erwartetes Verhalten**
Kofferräume immer zumachen können, oder nach dem aufbrechen ein Fahrzeug "aufschließen" damit der Kofferraum geschlossen werden kann

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug zuschließen
Aufbrechen
Kofferraum nicht ohne Schlüssel schließbar 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TheBroady** [comment]
https://www.twitch.tv/thebroady/clip/ExcitedDiligentDolphinRalpherZ-9iBHADXZvqGzdtUs?filter=clips&range=7d&sort=time :P

**Comment by DonVitoDiangelo** [comment]
Wenn du das im RP aufbrichst, dann sorge anschließend für eine Reparatur, fertig.

**Comment by TheBroady** [comment]
> Wenn du das im RP aufbrichst, dann sorge anschließend für eine Reparatur, fertig.

Gehe ich also richtig in der Annahme das der Kofferraum auch schließbar ist, wenn das Fahrzeug zugeschlossen ist.
Das es hierbei nur an der Beschädigung des Fahrzeug lag?

Mein Standpunkt ist, das Kofferräume nicht schließbar sind wenn das Fahrzeug zugeschlossen ist und es zu sehr beschädigt wurde.
