### ISSUE TITLE
Anzeige Fehler Verletzungen

### ISSUE THREAD

**Issue by RuedigerRommel** [mexyn/statev_v2_issues#137]
Ruediger_Rommel
Arnaldo Bloom

26.08.2020    23:02 

**Beobachtetes Verhalten**
Nach aufwachen im Notfall MD ist man selber ohne Verletzungen der andere hat aber welche

**Erwartetes Verhalten**
Bei beiden Personen sind die Verletzungen sichtbar

**Schritte um den Fehler nachvollziehen zu können**
Sind beide gestorben im Notfall MD aufgewacht der Eigene Char war ohne Verletzungen die Person gegenüber waren Verletzungen sichtbar

**Monitorauflösung 1920x1080**

![Ansicht Ruediger Rommel](https://user-images.githubusercontent.com/70349694/91554716-f5839f00-e92f-11ea-9925-7b15b3aed330.jpg)
Ansicht von Ruediger Rommel

![Arnaldo Bloom  jpg](https://user-images.githubusercontent.com/70349694/91555177-cf123380-e930-11ea-9ab3-5f517cacf4f8.png)
Ansicht von Arnaldo Bloom

**Comment by JulianMa** [comment]
durch alt:V fixed
