### ISSUE TITLE
Titanbarren gehen immer noch kaputt...

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1372]
Changelog: [Fix] Titanbarren Produktion trotz ausgelerntem Skill manchmal fehlerhaft
https://github.com/mexyn/statev_v2_issues/issues/1352

![Screenshot_22](https://user-images.githubusercontent.com/70241137/113614327-a4205880-9652-11eb-9d20-6f4697efb996.jpg)

**Comment by DonVitoDiangelo** [comment]
ai ai, next update nun aber wirklich. Kleiner Zahlendreher
