### ISSUE TITLE
Handbremse + Fahrrad = keine Fahranimation

### ISSUE THREAD

**Issue by Koree7** [mexyn/statev_v2_issues#1373]
**Character Name**
Brooks_Miller

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.04.2021 / 20:00

**Beobachtetes Verhalten**
Keine Animation beim Fahrrad fahren wenn man die Handbremse bei einem Fahrrad zieht und fährt.

**Erwartetes Verhalten**
Keine Handbremse ODER Animation haben beim Fahren

**Schritte um den Fehler nachvollziehen zu können**
Aufs Fahrrad steigen, Handbremse ziehen, absteigen, aufsteigen, fahren

**Optional: Video / Bilder des Fehlers**

[](https://imgur.com/a/p6O13M3)

**Comment by Koree7** [comment]
Verlinkung hatte keine Lust, hier ein GIF: https://imgur.com/a/p6O13M3

**Comment by its4l3x** [comment]
fixed next update
