### ISSUE TITLE
Drogen + Waffentisch

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1375]
Wenn man gerade an den Tischen was produziert z.b eine. AK-47, und ein Serverrestart angekündigt wird dann hat man den Waffentisch ca 12k + die Bauteile ca. 12k bei Serverrestart verloren!
Manche Produktionen dauern länger als die Ankündigung erscheint, z.b. eine Ak dauert 10 Minuten zusammenzusetzen!

Daher wäre es Sinnvoll wenn man eine Produktion komplett abbrechen könnte und dann die Bauteile (bei den Drogentischen die Zutaten) + Tisch wieder ins Inventar bekommt, zur Zeit kann man die Produktionen nur unterbrechen und den Tisch nicht abbauen wenn etwas Produziert wird!

Das betrifft alle Arten von Waffen und Drogentischen...

**Comment by DonVitoDiangelo** [comment]
Müssen wir mal schauen ob und wenn ja, wie wir das umsetzen. Die Sachen werden im Grunde bei Start schon verbraucht und schon zur Sicherheit wird es da auch kein "abbrechen und wiederbekommen" geben. Den Restart plant man da natürlich im besten Fall aktuell mit ein wie bei vielen anderen Dingen auch. Eine schnelle Lösung ist hier also nicht zu erwarten.

**Comment by Statev-Bonsai** [comment]
Na klar plant man das mit ein, aber die Restarts zwischendurch wie vorhin sind das Problem...

**Comment by DonVitoDiangelo** [comment]
Wird es voraussichtlich erstmal keine Änderung geben. Wenn so etwas eintritt, erstmal den Weg in den Support suchen.
