### ISSUE TITLE
Textfeld für SMS im StateNet vergrößern

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1377]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Schon immer

**Beobachtetes Verhalten**
Das Textfeld beim Schreiben einer SMS ist sehr schmal. So kann man den Text den man schreibt sobald dieser mehr als eine Zeile ist nicht mehr richtig lesen.

**Erwartetes Verhalten**
Das der Bereich vlt ein bisschen höher wird, um mehr als nur eine Zeile einsehen zu können.

**Optional: Video / Bilder des Fehlers**
![Screenshot_5](https://user-images.githubusercontent.com/70150887/113705978-6701a800-96de-11eb-907d-0ee5b2032918.jpg)

**Comment by Bene-RonnyMoritz** [comment]
Das kann man so beheben:
https://user-images.githubusercontent.com/78343649/113738287-10589600-96ff-11eb-9750-7cc1a6988ff7.mp4

**Comment by its4l3x** [comment]
Erstmal closed. Stay Tuned! ;)
