### ISSUE TITLE
Dispatch

### ISSUE THREAD

**Issue by KorbysWorld** [mexyn/statev_v2_issues#1378]
Josh_Korby

Josh_Korby
**Auftrittszeitpunkt (Datum / Uhrzeit)**

06.04.21 / 17:30
**Beobachtetes Verhalten**

PD übergibt ein Dispatch an das MD , Das MD kann den Dispatch nicht an die Einheit übergeben. 
**Erwartetes Verhalten**

Den übergebenden Dispatch an die Einheit übergeben zu können.
**Schritte um den Fehler nachvollziehen zu können**

PD übergibt das MD ein Dispatch , MD versucht den Dispatch an die Einheit zu übergeben.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by JannikDatsch** [comment]
Man muss, so ist das zumindest bei der umgekehrten Dispatch Weiterleitung (MD->PD) zuerst auf, das Grüne Telefon klicken, bevor man den übergeben kann.  Dann kommt eine Meldung links unten, dass kein Telefonat mgl. ist oder so. Dies müsste gefixt werden.
