### ISSUE TITLE
Signalfackeln können endlos genutzt werden

### ISSUE THREAD

**Issue by GonzoMenendez** [mexyn/statev_v2_issues#1379]
Gonzo Menendez

**Auftrittszeitpunkt (Datum / Uhrzeit)**
<07.04.21 ~ 1.30 Uhr

**Beobachtetes Verhalten**
Fackeln werden beim Werfen im Waffenrad "verbraucht" das item bleibt aber im Inventar-Utensiel-slot-
Kann also abgerüstet und neu ausgerüstet werden wodurch neue Aufladung entsteht im Waffenrad.

https://www.twitch.tv/gonzo_menendez/clip/AgitatedMuddyDillMikeHogu-1DyAm_xKsu-GrOfW?filter=clips&range=24hr&sort=time

Ab 10 Sekunden beginnt der Test

**Erwartetes Verhalten**
Nach Wurf sollte die Fackel auch im Utensiel-slot verbraucht werden da sonst endlose Aufladung möglich ist.

**Schritte um den Fehler nachvollziehen zu können**
Siehe Video-Clip

**Comment by MarcelMuerto** [comment]
@GonzoMenendez 
Vielen Dank für den Report, dieses Verhalten ist im nächsten Update korrigiert ✅
