### ISSUE TITLE
Reifen in der Straße

### ISSUE THREAD

**Issue by Chrinis007** [mexyn/statev_v2_issues#138]
**Character Name**
Christian_Maier

**Zeitpunkt (Datum / Uhrzeit)**
Gestern und jetzt

**Beobachtetes Verhalten**
NEF Mustang ausgeparkt beim MD; Reifen in der Straße drin so dass sie platzen

**Erwartetes Verhalten**
Auf der Straße liegende reifen wie bei anderen Autos

**Schritte um den Fehler nachvollziehen zu können**
NEF mustang beim MD ausparken

**Optional: Video / Bilder des Fehlers**

![grafik](https://user-images.githubusercontent.com/70342279/91561008-1b627100-e93b-11ea-8927-251c01e2645d.png)

**Comment by Chrinis007** [comment]
Nachtrag:
Nach dem reparieren direkt wieder platt
![grafik](https://user-images.githubusercontent.com/70342279/91561260-93c93200-e93b-11ea-8a2e-d11555691a03.png)

**Comment by tastydev** [comment]
Siehe #60 . Allerdings ist das ausparken mit platten Reifen gewollt insofern sie vorher kaputt waren :)

**Comment by Chrinis007** [comment]
Die Reifen sind auch direkt nach der Reparatur wieder geplatzt
