### ISSUE TITLE
Nach dem klicken auf  [url=] [/url] tags kommt man nicht mehr zurück zur normalen Ansicht.

### ISSUE THREAD

**Issue by mashen456** [mexyn/statev_v2_issues#1381]
**Character Name**
~

**Auftrittszeitpunkt (Datum / Uhrzeit)**
~

**Beobachtetes Verhalten**
Wenn man jemanden einen Link viva url tag ( [url=] [/url]) verschickt und dieser dann auf diesen Link klickt kann dieser sein Tablet quasi bis zum Neustart des Spieles nicht mehr benutzen.  Er ist dann quasi auf er Seite gefangen

**Schritte um den Fehler nachvollziehen zu können**
[url=https://i.ebayimg.com/images/g/tZkAAOSw8lBToq0C/s-l300.jpg] Wichtiger Link [/url]

**Comment by MarcelMuerto** [comment]
@mashen456 
Vielen Dank für dein Report des fehlerhaften Verhaltens, dies sollte bei dem nächsten Update behoben sein. ✅
