### ISSUE TITLE
Waffenscheinausgabe im PD nicht möglich

### ISSUE THREAD

**Issue by Diak27** [mexyn/statev_v2_issues#1383]
**_Jacob Mason_**

_**Gestern den ganzen Abend über**_

**Beobachtetes Verhalten**
Wir hatten gestern den ganzen Abend über das Problem, wenn wir im PD Waffenscheine ausstellen wollten, dies nicht möglich ist, die Person, welche den Waffenschein bekommen sollte, erhielt eine Fehlermeldung mit irgendwas "Konto nicht gedeckt" oder "Ausstellung nicht möglich, keine Finanzmittel" oder so (kenne da nicht den genauen Wortlaut, als PD Mitarbeiter bekommen wir ja die Fehlermeldung nicht, sondern nur die Person welche einen Waffenschein haben möchte, und im RP ist es wohl schwierig den genauen Wortlaut wiederzugeben).
Personen hatten genug Bargeld dabei und auch ein gültiges Gutachten im Portmonee. Wir sind alle möglichen uns bekannten Probleme bei der Ausgabe durchgegangen (anderer Officer, Gutachten hin und her getradet, mehr Geld abgeholt, Geld getradet usw.) aber es war nicht möglich, Dokumente auszustellen.
Anzumerken hier ist auch, das es nicht nur bei einer Person so gewesen ist, sondern bei mehreren Chars, die einen Waffenschein haben wollten.

**Comment by its4l3x** [comment]
Wie die Fehlermeldung schon sagt, hatte dein Gegenüber einfach keine Geld dabei.

=> "Konto nicht gedeckt"

Waffenscheine sind nur Möglich, mit gedecktem Konto.

Daher kein Fehler und Close
