### ISSUE TITLE
Sprachreichweite ändern während Stabilisierung nicht möglich

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1384]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
08.04.2021

**Beobachtetes Verhalten**
Wärhend man bewusstlos ist und auch nach der Stabilisierung am Boden sowie im LSMD ist  es einem nicht möglich via Z die Sprachreichweite anzupassen. Man ist stuck auf der Reichweite die man hatte als man down ging. Kann beim "Schreien" im LSMD gut nervig werden :D

**Erwartetes Verhalten**
Z Sollte immer funktionieren.

**Schritte um den Fehler nachvollziehen zu können**
Umschießen lassen und Z drücken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TheBroady** [comment]
Edit: Man hat auch keine Visuelle Info mehr ob man gerade Redet und entmuted/Muted ist.

**Comment by its4l3x** [comment]
fixed next update

**Comment by Hutstaender** [comment]
#1423

**Comment by its4l3x** [comment]
fixed next update
