### ISSUE TITLE
X menü Verschwindet

### ISSUE THREAD

**Issue by powerswissi** [mexyn/statev_v2_issues#1385]
**Character Name**

Roger_Thickle

**Auftrittszeitpunkt (Datum / Uhrzeit)**

9.4.2021 18.30 Uhr
**Beobachtetes Verhalten**

X Menü verschwindet. Auch keine Interaktion mit abbaupunkt vorhanden

**Erwartetes Verhalten**

X menü sollte da sein 

**Schritte um den Fehler nachvollziehen zu können**

nicht nachvollziehbar

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/iWkhaJQ6DMM
[altv_2.23_Steam_0xffff800a32726ca4_09-04-2021_18-01-09.zip](https://github.com/mexyn/statev_v2_issues/files/6287292/altv_2.23_Steam_0xffff800a32726ca4_09-04-2021_18-01-09.zip)

[client_09-04-2021_18-38-42.log](https://github.com/mexyn/statev_v2_issues/files/6287295/client_09-04-2021_18-38-42.log)

**Comment by its4l3x** [comment]
ja wie wo was? brauche mindestens bei so einem undetailierten Beitrag ein Video, wenn du keins mitliefern kannst, schließe ich das  ticket wieder.

**Comment by powerswissi** [comment]
is doch verlinkt unten 

https://youtu.be/iWkhaJQ6DMM

kann da auch nix genau dazu sagen .. da das x menü einfach verschwunden ist

**Comment by its4l3x** [comment]
Habs erst jetzt gesehen - sorry.

Nach Absprache: Ein Problem welches nicht von uns oder von alt:V kommt, daher wieder closed.
