### ISSUE TITLE
Fliege unter die Map

### ISSUE THREAD

**Issue by J0Sii** [mexyn/statev_v2_issues#1386]
**Jimmy_Lopez**

Jimmy Lopez
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Jeden Tag wenn ich aus dem Hotelzimmer gehe
**Beobachtetes Verhalten**
Fliege unter die Map und lande hinterm Haus 

**Erwartetes Verhalten**
 Das ich ganz normal vor der Wohnung stehe

**Schritte um den Fehler nachvollziehen zu können**
Wenn man aus der Wohnung geht
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
Beschreibe Schritt für Schritt wie man den Fehler nachstellen kann 
**Optional: Video / Bilder des Fehlers**
 https://www.youtube.com/watch?v=9L-gqx1ETUo

**Comment by its4l3x** [comment]
Z Pos vllt hochsetzen @DrGrizzlY17 


@J0Sii Bitte noch den Hash deiner Wohnung uns geben.

**Comment by J0Sii** [comment]
Häuserhash ChamberlainHills_Flat_6
ChamberlainHills_Flat_6_9
