### ISSUE TITLE
Ammunation - Falsche Transportgruppe die Zweite....

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1387]
HK416 Munition kann man immer noch nicht in die Theke legen!
Changelog: [Fix] Transportgruppe für HK416 (Ammunation)

Zudem kann man sie auch nicht kaufen im Ammunation!

 Ammunation - Falsche Transportgruppe #1354

**Comment by callmerusty** [comment]
**Waffenkiste M249** selbes Problem

**Comment by DonVitoDiangelo** [comment]
- hk fix
- m249 wird nicht mehr unterstützt, ebenso sniper

**Comment by Diak27** [comment]
HK416 Transportgruppe funktioniert immer noch nicht, kann nicht in die Theke gepackt werden. Hier bei "Ammunation Black Eagle"

**Comment by Diak27** [comment]
> * hk fix
> * m249 wird nicht mehr unterstützt, ebenso sniper

HK416 Transportgruppe funktioniert immer noch nicht, kann nicht in die Theke gepackt werden. Hier bei "Ammunation Black Eagle"
