### ISSUE TITLE
Zwei Häuser oder Hotel punkte auf einer Position

### ISSUE THREAD

**Issue by M4cm4ni4c** [mexyn/statev_v2_issues#1388]
Zwei Haus/hotel interaktions punkt auf einer Position:
![image](https://user-images.githubusercontent.com/79061254/114268039-667b5100-99ff-11eb-9c37-842452ebcae1.png)
oder
![image](https://user-images.githubusercontent.com/79061254/114268063-785cf400-99ff-11eb-84c5-493fda7f930b.png)
oder
![image](https://user-images.githubusercontent.com/79061254/114268075-8448b600-99ff-11eb-9bf4-492fa2395d7d.png)

Ist mir nur aufgefallen beim rumlaufen das dort die Positionen auf einem Fleck sind weis nicht ob das mit absicht so ist.

Karten Positionen:
![image](https://user-images.githubusercontent.com/79061254/114268459-801d9800-9a01-11eb-8a39-1bd56f2e4654.png)

**Comment by TheBroady** [comment]
Haushash sichtbar?
