### ISSUE TITLE
Garage fürs Haus?

### ISSUE THREAD

**Issue by DerLeroy** [mexyn/statev_v2_issues#1389]
Würden diese beiden Häuser eine Garage bekommen? 

Danke schon mal für die Antwort

![Grand Theft Auto V Screenshot 2021 04 10 - 21 52 51 87](https://user-images.githubusercontent.com/82288439/114283164-a4e92e00-9a48-11eb-9d8e-563ba97bf267.png)
![Grand Theft Auto V Screenshot 2021 04 10 - 21 54 19 48](https://user-images.githubusercontent.com/82288439/114283166-a87cb500-9a48-11eb-8941-ab4e008d904e.png)

**Comment by DrGrizzlY17** [comment]
Bitte Haushash beifügen

**Comment by DerLeroy** [comment]
was ist denn der Haushash? Ist das der Straßenname? Wennn ja ist es einmal West mirror Drive 19 und East mirror Drive 13

**Comment by DerLeroy** [comment]
![Grand Theft Auto V Screenshot 2021 04 11 - 10 27 07 48](https://user-images.githubusercontent.com/82288439/114297388-a5b5aa80-9ab0-11eb-82b1-7559a0bedff0.png)
![Grand Theft Auto V Screenshot 2021 04 11 - 10 27 57 40](https://user-images.githubusercontent.com/82288439/114297394-a9493180-9ab0-11eb-9269-8e647e038921.png)

**Comment by its4l3x** [comment]
Das Reicht schon. Danke. :)

**Comment by DerLeroy** [comment]
und gibt es schon eine Info?

**Comment by its4l3x** [comment]
Wie der Tag solved sagt, wurde dir eine Garage hinzugefügt.
