### ISSUE TITLE
Makeup machen blockiert durch Friseur

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#139]
Dan_Lee

**Zeitpunkt (Datum / Uhrzeit)**
28.08.2020

**Beobachtetes Verhalten**
Der Spielerin wurden nur die Haare geschnitten, danach wollte sie Makeup machen. Dies ging nicht, weil sie kurz vorher beim Barbier war

**Erwartetes Verhalten**
Der Friseur sollte nicht das Makeup blockieren

**Schritte um den Fehler nachvollziehen zu können**
1. Haare schneiden lassen
2. Makeup machen lassen

**Optional: Video / Bilder des Fehlers**
![20200828143008_1](https://user-images.githubusercontent.com/70150988/91561174-6f6d5580-e93b-11ea-9e2f-4cf1f431f2ff.jpg)

**Comment by its4l3x** [comment]
Brauche bitte den Namen der Person mit der das getestet wurde... @DrGrizzlY17

**Comment by DrGrizzlY17** [comment]
Emily_Grant

**Comment by its4l3x** [comment]
Alles klar, ich gucke mal.

**Comment by Chrinis007** [comment]
Bug trat heute morgen auch an 4 Personen beim selben Friseur auf

**Comment by its4l3x** [comment]
Fixed
