### ISSUE TITLE
Zwei Fahrer gleichzeitig

### ISSUE THREAD

**Issue by FunnyBuddys** [mexyn/statev_v2_issues#1391]
**Character Name**

Ranjid_Boniakale

**Auftrittszeitpunkt (Datum / Uhrzeit)**

11.04.2021, 03:00 Uhr

**Beobachtetes Verhalten**

Ich steige über Beifahrerseite auf Fahrersitz während eine andere Person gleichzeitig über Fahrerseite auf Fahrersitz setzt. Beide Personen auf Fahrersitz.

**Erwartetes Verhalten**

Ich bleibe auf Beifahrersitz, andere Person setzt sich auf Fahrersitz.

**Schritte um den Fehler nachvollziehen zu können**

Auf Beifahrersitz gleichzeitig auf den Fahrersitz rutschen während Fahrer sich hineinsetzt.

**Optional: Video / Bilder des Fehlers**

![Screenshot_36-min](https://user-images.githubusercontent.com/16995710/114288879-5e5cf900-9a73-11eb-8b82-5994b6ed923b.png)

**Comment by its4l3x** [comment]
Passiert in ganz wenigen Situationen mal (F+G Handle). Ist ein bekannter alt:V Bug, welchen die bereits wissen, daher closed und als alt:V Bug mentioned
