### ISSUE TITLE
Vergessene Relikte aus vergangener Zeit...

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1393]
Man findet noch Karotten die man nur für Schneemänner nutzen konnte im Jahre 2019, alte Pfeifen genauso...

Weihnachtskleidung findet man auch noch an der Klettermine, wurde letztes Jahr zu Weihnachten reingepatcht.

Containerkarten sind auch noch verfügbar, die sind ja als Aprilscherz hinzugekommen...

**Comment by PlayInc89** [comment]
Naja wenn es danach geht hat man vergessen die Bewohner aus dem Alturistenlager wieder Einzusiedeln

**Comment by CaleighRhodes** [comment]
Ich dachte die Feilen braucht man für die Insel? Hab IC irgendwas undefinierbares gehört. Oder weshalb wurden die gekauft wie bekloppt?

**Comment by DonVitoDiangelo** [comment]
Das sollte mittlerweile schon alles raus sein.
