### ISSUE TITLE
[Antrag] Entladepunkt versetzen

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#1396]
**Character Name**
Marvin_Elpe

**Unternehmen**
🍃Green Oil🛢️ - littleSeoulWest127
und
🍃Green Logistics2📦 - littleSeoulWest126

Bitte die beiden Entladepunkte neben die Firmen setzen (siehe Bild: beide auf den linken Entladepunkt, welcher bereits von einer anderen Firma genutzt wird. Vielen Dank

**Optional: Video / Bilder des Fehlers**
![](https://pic.statev.de/i/4yREi.jpg)

**Comment by DrGrizzlY17** [comment]
Abgelehnt

**Comment by M4rvinLP** [comment]
Dürfte man erfahren wieso es abgelehnt wurde?
