### ISSUE TITLE
Apartment nicht kündbar

### ISSUE THREAD

**Issue by nirualis** [mexyn/statev_v2_issues#1398]
**Character Name** 
Jonny Stoned

**Auftrittszeitpunkt (Datum / Uhrzeit)** 
12.04.2021 ca. 04:50 Uhr

**Beobachtetes Verhalten** 
Wohnung lässt sich nicht kündigen

**Erwartetes Verhalten** 
Wohnung sollte kündbar sein

**Schritte um den Fehler nachvollziehen zu können** 
In die Wohnung "JunSandyShoresRew_Flat_15_8" einmieten (Adresse: PANORAMA DRIVE 4015)

**Comment by its4l3x** [comment]
Bitte ein paar mehr Details... 
Bekommst du eine Fehlermeldung?
Um welchen Mieter handelt es sich?

**Comment by nirualis** [comment]
Nein, ich bekomme keine Fehlermeldung da der Button zur Kündigung komplett fehlt.
Werde ein Bild in den Anhang hängen.
Der Mieter bin ich 


![button fehlt](https://user-images.githubusercontent.com/82384404/114398896-9f9ef700-9ba0-11eb-8d82-192cf1371f35.png)

**Comment by DrGrizzlY17** [comment]
@nirualis versuch einmal die Wohnung direkt am Wohnungspoint zu kündigung und nicht am blauen Marker. Also such deine Wohnung mit dem grünen Marker und gib dann mal Feedback

**Comment by nirualis** [comment]
Wusste nicht dass die grünen Marker dazu gehören, hat geklappt, danke.
