### ISSUE TITLE
Firma gekauft und nur Zweitzugang zum Nachbargebäude (eigene Metzgerei) erhalten

### ISSUE THREAD

**Issue by AmschelGoldblum** [mexyn/statev_v2_issues#1399]
Amschel_Goldblum

Amschel_Goldblum
**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.04.2021 19:19 (Ich hatte Euch hierzu auch schon eine Bug Report Mail geschickt, bislang aber nichts von Euch gehört.)

**Beobachtetes Verhalten**
Ich habe das noch freie Firmengebäude (Bay City Ave. 2348 gekauft, jedoch lediglich einen zweiten Zugang zu meiner Metzgerei (Jun_VespucciRew_2348
![FehlerFirmenkauf](https://user-images.githubusercontent.com/74988511/114407719-fe686e80-9ba8-11eb-9c5c-4b0638bb15f9.jpg)
) im Nebengebäude bekommen.

**Erwartetes Verhalten**
Ich hätte ein Firmengebäude erhalten müssen, welches ich dann als Mühle hätte verwenden können.

**Schritte um den Fehler nachvollziehen zu können**
Keine Ahnung, hatte diesen Fehler noch nicht. Ich habe das Gebäude gekauft und wie oben beschrieben nur einen zusätzlichen Eingang zu meiner Metzgerei bekommen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by KingMarcel** [comment]
mit dem nächsten Update behoben
