### ISSUE TITLE
Klimmzüge ungenaues Positionsoffset

### ISSUE THREAD

**Issue by Frommser9** [mexyn/statev_v2_issues#140]
**Norman_Frommser**

Norman_Frommser
**Zeitpunkt (Datum / Uhrzeit)**

28.08.2020 14:30
**Beobachtetes Verhalten**

Charakter hängt zu weit oben an den Ketten
**Erwartetes Verhalten**

an den Ringen festhalten
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://i.gyazo.com/f0142a69e1d63076c07e1b85f07f4b11.jpg

**Comment by DonVitoDiangelo** [comment]
etwas verbessert, allerdings bekommt man das nicht sooo Perfekt hin :)
