### ISSUE TITLE
Ammunation - falsche Transportgruppe Taschenlampen

### ISSUE THREAD

**Issue by VictorCorticera** [mexyn/statev_v2_issues#1400]
Gustavo Luciano

12.04.2021 22:00

Verpackte Taschenlampen werden im StateNet im Ladeninventar angezeigt, allerdings in der Ammunation werden sie nicht angezeigt. Als ich sie einmal aus dem Ladeninventar rausgenommen habe, konnten die Taschenlampen nicht zurückgelegt werden: Fehlermeldung: falsche Transportgruppe.

Verpackte Taschenlampen können in der Ammunation verkauft werden.

Verpackte Taschenlampen können in das Ladeninventar gelegt werden und werden den Kunden auch angezeigt.

**Comment by Statev-Bonsai** [comment]
Das ist richtig so, Taschenlampen sind nur noch für die Staatlichen Behörden entpackbar...

**Comment by VictorCorticera** [comment]
Ok, wann wurde denn diese Änderung plötzlich aktiv und vor allem, wieso???
Die meisten Leute kaufen diese ja nicht primär als Waffe, sondern weil eine Taschenlampe überraschenderweise auch noch eine andere Funktion hat :D 
@devs kann man da vllt nochmal eine Änderung beantragen oder zumindest, dass das nochmal überdacht wird?

**Comment by Statev-Bonsai** [comment]
Gustavo, ich bemängle es auch...
Die Änderung wurde einfach vorgenommen ohne es irgendwo zu vermerken.
Zudem wird es immer und immer weniger was im Ammunation angeboten werden kann, keine Langwaffen mehr, keine Taschenlampen etc. etc.
24/7 Shops bekommen neue Artikel quasi dauerhaft, und aus dem Ammunation werden nur Waren entfernt...

**Comment by Diak27** [comment]
Dem kann ich mich nur anschließen, ohne Ankündigung die Taschenlampen einfach zu entfernen ist S****. Auch ohne einen Sinn dahinter. Desweiteren sind Taschenlampen im Wiki auch nicht als "Cop" Equip getagged. 
[OffTopic] Also sollen die Cops jetzt Minenarbeiter die mit ner Lampe in der Mine sind, wegen Besitz staatliches Eigentum rankriegen? :D [OffTopic Ende]

**Comment by DonVitoDiangelo** [comment]
First Step, cool bleiben :)

Wir werden uns das Thema noch einmal mit allen Waffen soweit anschauen.
Das mit den Taschenlampen war bei mir noch nen altes Ding im Hinterkopf.  Hier gab es auch zu v2 Umstellungen die etwas, sagen wir durcheinander gebracht haben.  Aber wir gucken uns das wie gesagt nochmal an und die Lampen werden definitiv zurück kommen.
