### ISSUE TITLE
Riesige Pfütze in überdachter Hotellobby

### ISSUE THREAD

**Issue by KruemelGames** [mexyn/statev_v2_issues#1402]
Dave_Weinstein

Immer bei Regen und Gewitter

Jedes mal wenn es regnet, wird die Hotel Lobby des Cooper Tower Inc. (Alta Street 2) (PillboxHill_Flat_1) in der Mitte zum halben Planschbecken. Eine Riesige Pfütze ist dann dort zu sehen. Auch ohne NVE und Reshade. Außerdem sind keine offensichtlichen Öffnungen in der Decke die ein eindringen des Regens erklären würden. Edit: Vermutlich würde auch im Winter bei Schnee ebenfalls Schnee in der Lobby liegen. 

Es bildet sich bei Regen keine Pfütze in einem Überdachten Raum

Zum Hotel gehen und es regnen lassen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

https://pic.statev.de/image/20210414194330-1.45FVn

**Comment by DonVitoDiangelo** [comment]
gta related, wird nicht gefixt
