### ISSUE TITLE
Zahlungsaufforderung Blitzertickets

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1403]
**Character Name**
Max Broady

**Beobachtetes Verhalten**
Wenn man eine Zahlungsaufforderung von einem Blitzerticket erhält, wird dort das SAPD als Aussteller genannt.

**Erwartetes Verhalten**
Die Regierung dort angesprochen wird.

**Comment by its4l3x** [comment]
Habe im gleichem Atemzug das LSPD auch zu SAPD umbenannt.


https://i.imgur.com/EPVxhb5.png
