### ISSUE TITLE
Bitte Stühle und Tische vor dem Café Redemption befestigen

### ISSUE THREAD

**Issue by MelinaHolzman** [mexyn/statev_v2_issues#1406]
**Melina_Holzman**

**Auftrittszeitpunkt (17.4.21/ Uhrzeit)**

**Tische und Stühle vor dem Café Redemption lassen sich bewegen**

**Objekte werden wie im Inneren befestigt und laden zum Sitzen ein**

**Die Tische und Stühle fliegen durch die Gegend und behindern das RP**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![stühle1](https://user-images.githubusercontent.com/82753167/115139699-9ea01680-a033-11eb-91fd-8ffa5868b689.png)

**Comment by DonVitoDiangelo** [comment]
Wird leider so bleiben.
