### ISSUE TITLE
Gewerbeschein interaktion

### ISSUE THREAD

**Issue by sGtDeath** [mexyn/statev_v2_issues#1407]
**Character Name**
Frank_Gruber

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit V2

**Beobachtetes Verhalten**
Beim Rechtsklicken eines Gewerbescheins im Inventar wird dieser nicht angezeigt

**Erwartetes Verhalten**
Beim Rechtsklicken eines Gewerbescheins im Inventar wird dieser angezeigt
**Schritte um den Fehler nachvollziehen zu können**
1. Gewerbeschein im Inventar
2. Rechtsklick drauf
3. Es kommt nix

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Öhm. Gabs den Gewerbeschein schon vor V2?
