### ISSUE TITLE
Abschleppvorgang nicht möglich

### ISSUE THREAD

**Issue by FunnyBuddys** [mexyn/statev_v2_issues#1408]
**Character Name**

Ranjid_Boniakale

**Auftrittszeitpunkt (Datum / Uhrzeit)**

19.04.2021 - 03:32

**Beobachtetes Verhalten**

Ich habe versucht, einen Burrito mittels eines Flatbets abzuschleppen, während oben der Ladebalken lädt ist mein Spiel gecrasht. Ab da konnte man den Abschleppvorgang nicht mehr beenden oder neustarten. Den Flatbed konnte man auch nicht mehr aufschließen. Das Spiel ging davon aus, dass der Abschleppvorgang anhält.

**Erwartetes Verhalten**

Abschleppvorgang wird trotzdem zu Ende geführt oder wenigstens abgebrochen.

**Schritte um den Fehler nachvollziehen zu können**

Mit einem Flatbed einen Wagen abschleppen und während der Ladebalken läd, das Spiel verlassen.

**Comment by JulianMa** [comment]
Technisch kann der Abschleppvorgang nicht zu ende geführt werden.
Das der Flatbed gesperrt bleibt, ist allerdings ein Fehler.

**Comment by JulianMa** [comment]
Mit kommendem Update behoben.
