### ISSUE TITLE
Zugang zum Garten durch Objekte versperrt / Objekt entfernen. 

### ISSUE THREAD

**Issue by Valaray** [mexyn/statev_v2_issues#1409]
**Character Name**
Valaray_Youth

**Auftrittszeitpunkt (Datum / Uhrzeit)**
jederzeit

**Beobachtetes Verhalten**
der Zugang zum Garten meines Wohnhauses in Rancho ist, mit Blick aufs Haus, auf der rechten Seite durch ein unter Plane stehendes Auto versperrt. Auf der linken Seite stehen die Gebäude so eng beieinander, dass ein Durchkommen nicht möglich ist. 

Zugang zum hinteren Bereich des Grundstücks nur durch Klettern über das Carport, Zäune oder andere Gebäude möglich. 

**Erwartetes Verhalten**
freier Durchgang zum hinteren Bereich des Grundstücks.

**Schritte um den Fehler nachvollziehen zu können**
Grundstück besuchen und gucken. ^^

**Optional: Video / Bilder des Fehlers**

![GTA5_pKDj3jTQcN](https://user-images.githubusercontent.com/70233639/115182970-34db4780-a0db-11eb-904e-1d09942fe1dd.png)

![GTA5_diqmzDmiEI](https://user-images.githubusercontent.com/70233639/115183005-43296380-a0db-11eb-853b-6e217d0de016.png)

![GTA5_AJwM4yz5CS](https://user-images.githubusercontent.com/70233639/115183015-491f4480-a0db-11eb-828b-2aebc53b9248.jpg)

![GTA5_bPDfzH9K2W](https://user-images.githubusercontent.com/70233639/115183030-4f152580-a0db-11eb-81dd-25afe6c5f2a3.png)

**Comment by DrGrizzlY17** [comment]
Da es kein RP störendes Problem oder das Objekt selber blockiert, Abgelehnt

**Comment by Valaray** [comment]
Ich fuhle mich in meinem rp tatsächlich sehr wohl gestört denn wer lässt bei einer Gartenparty alle Gäste im Normalfall über Häuser klettern um daran teilnehmen zu können?
