### ISSUE TITLE
kein Interior Umbau möglich

### ISSUE THREAD

**Issue by nirualis** [mexyn/statev_v2_issues#1410]
**Character Name** 
Jonny_Stoned

**Auftrittszeitpunkt (Datum / Uhrzeit)** 
19.04.2021 / 22:50 Uhr

**Beobachtetes Verhalten** 
Ich habe mir gerade das Haus am Mariana Drive 14 gekauft (Haushash: SandyShores48).

Das Haus ist Größe 2, Klasse 1 und ohne Garage.

Ich wollte direkt schauen welches Interior eingebaut ist und welche Möglichkeiten bestehen es umzubauen aber leider habe ich gesehen dass ich kein Interior einbauen kann. 

Ich habe versucht alles anzuklicken, inklusive "KAUFEN" jedoch kommt da überall keine Reaktion, kein Auswahlmenü, keine Fehlermeldung und das Menü schließt sich nicht - außer bei dem Button schließen. 

Ich werde unten ein Bild einfügen vom Menü am Haus. 

**Erwartetes Verhalten**
Klicken sollte ein Dropdownmenü mit der Auswahl zeigen.

**Schritte um den Fehler nachvollziehen zu können**
An der Tür das Menü "Interior" aufrufen.

**Optional: Video / Bilder des Fehlers**
![Interior](https://user-images.githubusercontent.com/82384404/115304284-10c44880-a165-11eb-927a-8498d54fb0e7.png)

**Comment by its4l3x** [comment]
Fehlt da vllt. eine Interior Config o.ä?

**Comment by nirualis** [comment]
Scheint so, ja. Das derzeitige Interior heißt ja auch "NO INTERIOR"

**Comment by DrGrizzlY17** [comment]
Hi Jonny,

das [NO INTERIOR] ist nicht das jetzige Interior sondern, deine anderen Optionen.
Jedes Haus hat gewisse Spezifikationen wie z.B. Klasse, Größe und noch ein paar Interne.

Für dein Haus stehen einfach keine weiteren Interior zur Verfügung.

Die Anzeige wird angepasst, ansonsten kein Fehler vorliegend
