### ISSUE TITLE
Waffenhändler sagt nein zu Klappmesser

### ISSUE THREAD

**Issue by SunnyPlays** [mexyn/statev_v2_issues#1412]
**Character Name**
Jonas_Luca

**Auftrittszeitpunkt (Datum / Uhrzeit)**
20.4.2021 ca 18:30

**Beobachtetes Verhalten**
Waffenhändler händigt keine Klappmesser aus, obwohl vom LSPD mir bestätigt wurde, das für Klappmesser kein kleiner Waffenschein benötigt wird.

**Erwartetes Verhalten**
Kauf eines Klappmessers

**Schritte um den Fehler nachvollziehen zu können**
In ein Waffengeschäft fahren und ohne Waffenschein versuchen ein Klappmesser zu kaufen

**Comment by Chrinis007** [comment]
Klappmesser war zu v1 auch nur mit Waffenschein

**Comment by DonVitoDiangelo** [comment]
korrekt, wird auch weiterhin so bleiben. Waffenschein wird benötigt.
