### ISSUE TITLE
Dienstausweis LSMD

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1414]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Falsche Anordnung der Infos auf dem Dienstausweis des LSMD's

**Erwartetes Verhalten**
Das die Infos richtig angeordnet sind. Zusätzlich das Datum der Einstellung statt das heutige Datum angezeigt wird.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/70150887/115541453-6d2b8300-a29f-11eb-9e77-424d6cf322dd.png)

**Comment by Hutstaender** [comment]
Der is schon längst geändert, die medics haben nen neues design gemacht
