### ISSUE TITLE
Issi sport

### ISSUE THREAD

**Issue by minu666** [mexyn/statev_v2_issues#1415]
**Character Name** 

Minu Maslov

 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 21.04.2021 12:50

**Beobachtetes Verhalten**
 Weeny Issi Sport repariert/zerstört sich automatisch beim an und ausschalten der unterbodenbelichtung

**Erwartetes Verhalten**
 Auto sollte sich nicht reparieren

**Schritte um den Fehler nachvollziehen zu können**
 Unterboden an und ausschalten !

**Comment by Hutstaender** [comment]
Immernoch der Fall? Konnte bisher nicht nachgestellt werden.

**Comment by minu666** [comment]
Ja ich denke das es immernoch so ist !

**Comment by minu666** [comment]
Nimm man en Issi Sport fahr ihn gegen die wand und wenn die Motor leuchte rot ist mach die Unterboden an oder aus

**Comment by Hutstaender** [comment]
Konnte immer noch nicht bestätigt werden. Wenn das Fahrzeug kaputt ist, kann das Unterbodenlicht nicht mehr verändert werden.

**Comment by Hutstaender** [comment]
Ich mach den Beitrag mal zu, wenn du nähere Infos hast, wie sich der Fehler reproduzieren lässt, eröffne bitte ein neues Ticket.

**Comment by minu666** [comment]
also ich würde es ja ic testen aber zählt das nicht als bug using?
