### ISSUE TITLE
Nach "Maske abziehen", diese nicht auffindbar

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1417]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.04

**Beobachtetes Verhalten**
Nachdem dem Spieler über "Maske abziehen" die Maske abgezogen wurde, war diese bei der "Durchsuchung" in keinem Inventar mehr auffindbar, weder im eigenen noch in dem des Spieler, oder in dessen Tasche.

**Erwartetes Verhalten**
Die Maske sollte irgendwo auftauchen.

**Schritte um den Fehler nachvollziehen zu können**
siehe Video

**Optional: Video / Bilder des Fehlers**
https://youtu.be/-OGaCHjDokU

**Comment by its4l3x** [comment]
fixed next update
