### ISSUE TITLE
Sanchez wird nicht geblitzt

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1418]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Auch wenn mich jetzt einige schlagen werden, die Sanchez wird aktuell nicht geblitzt.

**Erwartetes Verhalten**
Das alle Fahrzeuge geblitzt werden

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by VictorCorticera** [comment]
Vielleicht ist das ja gewollt, die Sanchez hat ja schließlich auch kein Kennzeichen ;)

**Comment by TheBroady** [comment]
> Vielleicht ist das ja gewollt, die Sanchez hat ja schließlich auch kein Kennzeichen ;)

Deswegen Report. Da kann es ja dann geschaut werden. Glaube ich aber nicht.

**Comment by Statev-Bonsai** [comment]
Alle Fahrzeuge die Serienmäßig ohne Kennzeichen ausgeliefert werden bekommen keine Tickets!
Endlich haben diese Fahrzeuge auch mal einen Sinn :)

**Comment by DonVitoDiangelo** [comment]
Fahrzeuge  ohne Kennzeichen werden und sollen nicht geblitzt werden.
