### ISSUE TITLE
Metalldetektor fürs Gericht

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1419]
**Wunsch**

Wäre es möglich, Metalldetektoren wie diese in der Handelskammer auch im Gericht einzuführen. Denke die machen da fast mehr Sinn als in der Handelskammer.

**Comment by DonVitoDiangelo** [comment]
Abgelehnt. Wir sind der Meinung hier gibt es schon genug Kontrolle vor jeder Verhandlung, daher brauchen wir hier kein extra Detektor.
