### ISSUE TITLE
Respawn Point nach einloggen inkorrekt.

### ISSUE THREAD

**Issue by mxRde** [mexyn/statev_v2_issues#142]
**Character Name**

Maximilian Jones

**Zeitpunkt (Datum / Uhrzeit)**

28.08.2020 - 17.40

**Beobachtetes Verhalten**

Habe mich auf dem Dach ausgeloggt, nach erneutem einloggen unter dem Helipad.

**Erwartetes Verhalten**

Respawn auf dem Helipad.

**Schritte um den Fehler nachvollziehen zu können**

Wie oben beschrieben.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://puu.sh/GmHGE/2647007cfe.png

**Comment by DonVitoDiangelo** [comment]
Bitte alle generell darauf achten, ob sich das Verhalten bessert.
