### ISSUE TITLE
StateNET Dashboard Firefox: Aktive Zeiten vertikal gestreckt

### ISSUE THREAD

**Issue by ProgrammingFox** [mexyn/statev_v2_issues#1420]
**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit einigen Wochen/Monaten

**Beobachtetes Verhalten**
StateNET in Firefox hat eine Fehlerhafte Darstellung im Dashboard für die aktive Zeit der Werbung
![image](https://user-images.githubusercontent.com/48456305/115668680-b33c2180-a347-11eb-9b2f-bab43fa7ae7f.png)

**Erwartetes Verhalten**
Das die aktive Zeit sich nicht mehr über das ganze Kartenelement streckt:
![image](https://user-images.githubusercontent.com/48456305/115668735-c3ec9780-a347-11eb-8f47-f6f158d2ac84.png)

**Lösungsvorschlag**
Wenn der Klasse "timeValue" im CSS die Eigenschaft "height: max-content;" hinzugefügt wird löst sich das Problem (zumindest für Firefox). Ob das wo anders Fehler verursacht kann ich leider nicht sagen.

**Schritte um den Fehler nachvollziehen zu können**
Firefox -> net.statev.de -> anmelden -> Dashboard

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Comment by Chrinis007** [comment]
Selbes Problem..

**Comment by MarcelMuerto** [comment]
@ProgrammingFox @Chrinis007 
Besteht dieses Verhalten weiterhin?

Ich konnte es bei mir bisher nicht reproduzieren, selbst mit aktueller Version von Firefox.

**Comment by ProgrammingFox** [comment]
@MarcelMuerto 
Besteht weiterhin:
![grafik](https://user-images.githubusercontent.com/48456305/118334100-3139b580-b50d-11eb-8d50-311bdd0cef24.png)

**Comment by MarcelMuerto** [comment]
@ProgrammingFox 
Okay nvm, hab es jetzt grade geschafft zu reproduzieren. 
Werde mir das später mal anschauen.

**Comment by MarcelMuerto** [comment]
@ProgrammingFox
Fehler der Darstellung ist bei dem nächsten Update behoben. ✅
