### ISSUE TITLE
Auto biegt plötzlich ab.

### ISSUE THREAD

**Issue by edel91** [mexyn/statev_v2_issues#1421]
**Auftrittszeitpunkt (Datum / Uhrzeit)**
passiert immer mal wieder. Immer sporadisch. 

**Beobachtetes Verhalten**
Ich fahre mit dem Pounder oder einem Burrito und dieser zieht plötzlich nach rechts oder links. Dadurch fahre ich dann irgendwo gegen, oder ich kann es noch abfangen. Die reifen stehen dann auch fest in die jeweilige Richtung. Erst erneutes lenken in die Richtung in die die Reifen fest stehen behebt das ganze. An meiner Tastatur kann es nicht liegen, alles schon probiert.

**Erwartetes Verhalten**
Normal geradeausfahren.

**Comment by JannikDatsch** [comment]
Kann es sein, dass du auf die linke Maustaste kommst in dieser Situation? Mit der kann man nämlich auch das Auto entsprechend steuern.

**Comment by edel91** [comment]
Huhu. Nein ausgeschlossen. Passiert einfach plötzlich. Und das an allen möglichen Orten. Kann es mir selber nicht erklären. Wenn es wieder passiert kann ich es gerne mal aufnehmen.

**Comment by its4l3x** [comment]
Ist kein Bug unsererseits - sondern einer bei dir.
