### ISSUE TITLE
Dauerfunken nach Stabilisierung

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1423]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
immer wieder seit V2

**Beobachtetes Verhalten**
In Ergänzung zu #1384, da es ein ähnlicher Fehler ist, kommt es manchmal vor, dass Personen nachdem sie bewusstlos waren, nach der Stabilisierung Dauerfunken. (Vlt. weil sie während dem bewusstlos werden gefunkt haben). 

Auf jeden Fall ist das dann auch in Stabilisierten Zustand nicht mgl., zu unterbinden, dass man nicht mehr Dauerfunkt, da man noch keinen Zugriff auf Handy Tablet Funk usw. hat.

**Erwartetes Verhalten**

Man sollte nicht Dauerfunken

**Comment by Hutstaender** [comment]
angehängt an andere Bugmeldung
