### ISSUE TITLE
Blitzerticket Mahnungen

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1424]
Die Blitzerticket Mahnungen/ (letzte) Zahlungsaufforderung kommen von einer LSPD E-Mail mit LSPD auch im Text, sie sollten aber von der Regierung kommen, da das LSPD nichts damit zu tun hat.

**Comment by MisterCopeland** [comment]
#1403

**Comment by its4l3x** [comment]
Duplicate siehe #1403
