### ISSUE TITLE
Tankstellenpreise beliebig einstellbar

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1425]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.04.2021

**Beobachtetes Verhalten**
Es ist möglich den Literpreis auf 0,0000001 zu stellen wodurch kein Geld abgezogen wird beim Tanken.

**Erwartetes Verhalten**
0,01 das kleinste ist.

**Schritte um den Fehler nachvollziehen zu können**
Tankstelle runterstellen, tanken.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
So siehts während des Tankens aus wenn der preis auf 0,0000001 steht.
![image](https://user-images.githubusercontent.com/70150887/116267868-1204ff00-a77d-11eb-9b9d-aa42af57fb8f.png)

**Comment by M4rvinLP** [comment]
Das könnte das Facepalm Label bekommen xD

**Comment by TheBroady** [comment]
> Das könnte das Facepalm Label bekommen xD

https://pic.statev.de/i/Bmg7T.png

**Comment by its4l3x** [comment]
Ok.

**Comment by DonVitoDiangelo** [comment]
abgelehnt

**Comment by JulianMa** [comment]
Die kleinste Geldeinheit auf StateV ist 0.01$.
Wer Mathe in der Grundschule hatte, der wird auch wissen das 000000001 auf 2 stellen gerundet nicht 0.01, sondern 0.00 ergibt.
Das System ist explizit so designed, da bei einem Betrag von 0.00$ nicht getankt werden kann, damit man nicht aus versehen sein ganzen Benzin verschenkt. Ich schließe das dann mal.

**Comment by TheBroady** [comment]
Wenn man seinen Preis auf 0,0000001 stellt ist das tanken möglich (kostenfrei)

Wenn man seinen Preis allerdings auf 0 setzt, ist das Tanzen dieses Treibstoffes dann nicht möglich.

Dieser Report dient nur als Abfrage ob es so gewollt ist.
Wenn ja, ignoriert den Beitrag und schließt ihn.
