### ISSUE TITLE
eine Garage fürs Haus?

### ISSUE THREAD

**Issue by MisterGarry** [mexyn/statev_v2_issues#1426]
**Brain Garry**

**Wunsch**
Beantragung einer Garage für Haus

**Erwartetes Verhalten**
Haus besitzt ein Carport, wäre es möglich das eine Garage hinzugefügt werden kann.

**Optional: Video / Bilder des Fehlers**
Haushash: SandyShores1 

![20201107134520_1](https://user-images.githubusercontent.com/76521332/116451849-4fd95480-a85d-11eb-9dfa-fd57ae04fdf6.jpg)
Ist ein älteres Bild, Lostflagge ist nicht mehr vorhanden. Danke in vorraus.

**Comment by DrGrizzlY17** [comment]
Abgelehnt. Unter dem Pavillon ist zu viel müll als das dort Fahrzeuge einbahnfrei ausgeparkt werden. In unmittelbarer Nähe ist zudem eine Garage
