### ISSUE TITLE
Garage Einparkpunkt versetzen

### ISSUE THREAD

**Issue by CaptainGhostLive** [mexyn/statev_v2_issues#1427]
**Emilio_Luciano**

**Da der Punkt zu nah an der Garage ist können keine Autos außen geparkt werden weil dauerhaft die Position blockiert ist.**

**Etwas mehr von dem Garagentor weg Richtung Einfahrt**

![b15bb59b251b32b102937a694eead077](https://user-images.githubusercontent.com/28830199/116483854-3568a080-a888-11eb-84ac-62f7fcc9234e.png)
![GTA5 2021-04-25 15-38-45](https://user-images.githubusercontent.com/28830199/116483856-36013700-a888-11eb-9aeb-4481814f6adb.png)

**Comment by DrGrizzlY17** [comment]
Nächste mal haus hash pls dazu
