### ISSUE TITLE
Zurücksetzen von Fahrzeug bei Alt+F4/Crash

### ISSUE THREAD

**Issue by KruemelGames** [mexyn/statev_v2_issues#1428]
Dave_Weinstein

~23.30 29.04.

Freeze+Alt+F4, Fahrzeug an anderer Stelle aufgetaucht.  Konnte nicht gestohlen werden.
Enduro war zum Zeitpunkt an der Zentral-Mine Nord Straße im Bach (konnte man drinne fahren) (Offroad). Freeze + Alt+F4 danach war die Enduro unter 3217 (Adams Apple Bvld) unter dem Highway.
Edit: Sachen sind nicht verschwunden: Fehler meinerseits.

Kommt auch vor bei "Kopfschmerzen", dass das Fahrzeug woanders steht.

Fahrzeug portet sich nicht weg

Versuchen mit Crash oder Alt+F4 hervorzurufen 🤷

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Ist auf ein alt:V System zurückzuführen. Wenn ein anderer Spieler den Sync deines Fahrzeuges übernimmt, dann rollt das Fahrzeug dementsprechend aus. Wird kein User gefunden, welcher den Sync des Fahrzeuges übernehmen könnte, bleibt das Fahrzeug auf der Position freezed, bis ein Spieler wieder da ist, welcher weiter Syncen kann. Diese Sync-Reichweite kann bis zu 500 yards betragen. 

Daher closed
