### ISSUE TITLE
Skill Drogenverarbeitung Fehlerhaft/Wirkungslos

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1429]
Der Skill Drogenverarbeitung funktioniert nicht wie er soll, man kann Level aufsteigen aber bekommt keine Reduzierung der Produktionsdauer sowie den Produktionsbonus gutgeschrieben.

Beispiel Kokainxxx (zweite Stufe bei der Produktion von Kokain) :
Ungelernt dauert eine Produktion 15minuten (900 Sekunden) .
Gelernt in Level 2 ( 2x Levelup) dauert sie immer noch 15 Minuten , ich habe aber 5% Zeitbonus erreicht also dürfte die Produktion nur noch 14,25 Minuten (855 Sekunden) dauern.
Tut sie aber nicht, daher müsste der Skill überarbeitet werden.

![bugtracker](https://user-images.githubusercontent.com/70241137/116541988-65e22600-a8ec-11eb-9f91-b374953ecbd4.jpg)

![Screenshot_43](https://user-images.githubusercontent.com/70241137/116539259-e0a94200-a8e8-11eb-9cea-8d6cef9d28a4.jpg)

Zudem finde ich man müsste man die Fortschrittsberechnung neu anpassen, so wie ich das mitbekommen habe wird der Fortschritt wie bei jedem anderem Produktionsskill wie z.b. im Labor etc. bemessen.
Das ist meines Erachtens falsch berechnet, denn im Labor mache ich eine Ladung an und die Maschine rödelt mehrere Stunden ohne irgend ein zu tun vom Spieler.
Am Tisch hingegen muss man Aktiv arbeiten und kann nicht weg man steht mitunter mehrere Stunden dort, zudem hat man das Risiko vom PD oder von anderen Gruppierungen erwischt zu werden und die Produktion zu verlieren.

Auf Anfrage kann ich euch die Zeit nennen die ich am Tisch verbracht habe und wie viele Packungen ich produziert habe, dann werden ihr merken was ich meine.

Es wäre Klasse wenn sich der Skillfortschritt wie im Farmingbereich bewegen würde...

**Comment by Statev-Bonsai** [comment]
Und, wurde schonmal geschaut?

**Comment by DonVitoDiangelo** [comment]
Wird die nächsten Wochen (Juni/July) genauer geprüft. Müsst leider noch etwas Geduld haben.
