### ISSUE TITLE
Staatskonto geplündert

### ISSUE THREAD

**Issue by Arnaldo-Milano** [mexyn/statev_v2_issues#143]
**Arnaldo Bloom**

**28.08.2020 17:30**

**Staatskonto geleert**

**Nichts**

**Gehaltskonto im Lifeinvader Negativ eingestellt
![gehalt1](https://user-images.githubusercontent.com/70387900/91587872-a6516480-e957-11ea-9151-6a9f6feca490.png)
![gehalt2](https://user-images.githubusercontent.com/70387900/91587877-a8b3be80-e957-11ea-9572-41667ebb2a8c.png)

**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![gehalt3](https://user-images.githubusercontent.com/70387900/91587895-ad787280-e957-11ea-84f3-9c1b1b89e90b.png)
![gehalt4](https://user-images.githubusercontent.com/70387900/91587909-b2d5bd00-e957-11ea-89de-48c9f80a57e7.png)
![gehalt1](https://user-images.githubusercontent.com/70387900/91587910-b36e5380-e957-11ea-9178-1ffa5adc1483.png)
![gehalt2](https://user-images.githubusercontent.com/70387900/91587943-bc5f2500-e957-11ea-8630-f26c98022161.png)

**Comment by MarcelMuerto** [comment]
@Arnaldo-Milano Ist behoben 👍
