### ISSUE TITLE
Bug beim Schwarzmarkthändler

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1430]
Wenn 2 Artikel gleicher Bauart in der Auslage liegen und man den letzten der hinzukommen ist kaufen möchte kauft man den der schon länger im Sortiment vorhanden ist.
Ist schwer zu erklären, daher gibts nun Bilder... ;D

Wir wollten den Griff für 1070$ kaufen, man sieht auch die eingebende Kaufmenge von uns.
https://prnt.sc/125anpt

Bekommen haben wir aber den teuren Griff für 1624$ und der günstigere war noch im Sortiment.
https://prnt.sc/125aoek

Der Bug ist nun schon 3x vorgekommen...

**Comment by its4l3x** [comment]
fixed next update
