### ISSUE TITLE
Bug mit Adidas Hoodie und Turntasche

### ISSUE THREAD

**Issue by MaximillianMeyer** [mexyn/statev_v2_issues#1431]
**Maximillian_Meyer**

      Männlicher Character Langarm /Langarm 3
**Auftrittszeitpunkt (Datum / Uhrzeit)**

 29.04.2021 15:10
**Beobachtetes Verhalten**

Wenn man ein dunkelroten Adidas Pullover anzieht und man anschließend ein Duffelback anzieht, sieht man den Duffleback nicht. Das Laufgeräusch und den zusätzlichen Platz hat man aber es hängt keine Tasche um den Character
**Erwartetes Verhalten**

Normalerweise sollte die Tasche erscheinen 
**Schritte um den Fehler nachvollziehen zu können**

Roten Adidas Hoodie anzieh
 dann den grauen Duffleback Rucksack anziehen 
Duffleback wird nicht um den Character angezeigt
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

Link zu dem Bug Video: https://www.youtube.com/watch?v=oZyKpG7QAB4

**Comment by Statev-Bonsai** [comment]
https://github.com/mexyn/statev_v2_issues/issues/903
