### ISSUE TITLE
Entfernung von Tötlichen Papkisten

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#1432]
**Character Name**
Dean Gallagher

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Random

**Beobachtetes Verhalten**
Man berührt die Pappkisten und die töten einen

**Erwartetes Verhalten**
Papkisten sind weg also bitte einmal entfernen wenne s geht. 

**Schritte um den Fehler nachvollziehen zu können**
extrem seltener bug 

**Optional: Video / Bilder des Fehlers**
kleiner kicker 
https://youtu.be/fK_RCQvShSE

**Comment by JulianMa** [comment]
Wenn das öfter passiert, dann kann man darüber reden. Wenn das ein einmaliger Physiks-Bug ist, dann sehe ich keinen Grund warum der entfernt werden sollte.

**Comment by Dean-Gallagher** [comment]
war schon 3. oder 4. mal
