### ISSUE TITLE
Container Bug SAC

### ISSUE THREAD

**Issue by SevenJordan** [mexyn/statev_v2_issues#1433]
Seven_Jordan

21 Uhr

Nachdem man auf dem Container geraucht hat und die Animation abgebrochen hat, fällt man durch den Container in den Innenraum, man kommt aber wieder raus

Man sollte nicht durchglitchen können

https://cdn.discordapp.com/attachments/835899749059526706/838127264250986516/unknown.png
https://cdn.discordapp.com/attachments/835899749059526706/838127326801428550/unknown.png

**Comment by DrGrizzlY17** [comment]
Is etwas das mit GTA und Szenarien zu tun hat. Also einfach nicht mehr drauf rauchen.
