### ISSUE TITLE
Haus kauf nicht möglich

### ISSUE THREAD

**Issue by Stiefel911** [mexyn/statev_v2_issues#1435]
**Character Name**
Yanalar Vemo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.05.21 ; 01.36

**Beobachtetes Verhalten**
kauf nicht möglich da vermietet

**Erwartetes Verhalten**
kauf erfolgreich

**Schritte um den Fehler nachvollziehen zu können**
hin gehen und versuchen zu kaufen, es ist ein Haus mit zwei Zugängen, andere ist verkauft. evtl deswegen eine Vermischung!
![Grand Theft Auto V Screenshot 2021 05 02 - 01 36 16 69](https://user-images.githubusercontent.com/74860269/116798155-161e7d00-aaed-11eb-8c6c-7636d856d223.png)

**Optional: Video / Bilder des Fehlers**

![Grand Theft Auto V Screenshot 2021 05 02 - 01 36 34 75](https://user-images.githubusercontent.com/74860269/116798160-1c145e00-aaed-11eb-80e5-5570cbdf1821.png)

**Comment by its4l3x** [comment]
Ist soweit fixed. Ein Temporäres Problem, welches gerne mal auftritt. Das Haus ist nun kaufbar.
