### ISSUE TITLE
Ausweis verschieben (bsp. Beim Zielen)

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1436]
**Character Name**
Jannik Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.05.21

**Beobachtetes Verhalten**
Wenn man einen Dienst-/Personalausweis noch oben links geöffnet hat, kann man diesen verschieben, auch wenn man den Cursor (N) nicht aktiv hat, und zufällig grad drauf ist. Dies ist besonders dann schlecht, wenn man gerade ggf. in einer Schießerei o.ä. ist.

**Erwartetes Verhalten**
Ausweise sollten bsp. nur verschiebbar sein, wenn man aktiven Cursor (N) hat, sodass man diese nicht einfach so ungewollt übern Screen schiebt.

**Schritte um den Fehler nachvollziehen zu können**
siehe Video

Ausweis aktiv haben, mit dem Cursor auf den Ausweis kommen, und schieben (Bsp. beim gedrückhalten R. Maustaste beim Zielen)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/mJCBt3t4SRU
https://www.youtube.com/watch?v=hA_q5yPzJHc

**Comment by Hutstaender** [comment]
Welche Mauseingabeeinstellunge hast du denn ausgewählt?

**Comment by JannikDatsch** [comment]
Raw Input

**Comment by Hutstaender** [comment]
Konnte ich leider nicht nachstellen, bei mir geht soweit alles. Wenn du weist durch was es hervorgerufen wird, meld dich bitte nochmal.

**Comment by JannikDatsch** [comment]
Das wird dadurch hervorgerufen, wenn man mit dem nicht angezeigtem, aber dennoch ja vorhandenem Cursor, zufällig beim Zielen auf dem Ausweis ist.

Bsp. schieb den Ausweis oben links in die Ecke. Schalte dann den Cursor über N aus, aber bewege dann deine Maus nach links oben, sodass der in dem Moment versteckte Cursor oben links ist.

(Der Cursor existiert ja trotzdem, wird aber halt in der Regel in GTA, außer über N nicht angezeigt)

Dann ziele --> Der Ausweis wird sich bewegen, da zu vor der nicht angezeigte Cursor auf den Ausweis lag.

**Comment by Hutstaender** [comment]
Die Mauseinstellung Raw Input blockiert meine Mausklicks, wenn diese nicht aktiv (über N deaktiviert) ist. Damit sollte sowas nicht passieren. Ich hab jetzt auch alles Durchgetestet, Fenstermodus, Vollbild, verschiedene Mauseinstellungen, rein raus tabben. Das einzige was ab und zu passiert ist, dass bei Direct Input der Maus Zielen und verschieben des Ausweises bei eingeblenteter Maus (N) erlaubt. Aber sobald ich sie ausblende steht der Ausweis fest wie ne Eins.

Für mich hört es sich eher so an als hättest du Direct Input oder Windows Maus aktiv, bzw. deine ausgewählte Einstellung Raw Input ist wohl nicht aktiv. Evtl auch mal deine Windowseinstellungen zu den Mausoptionen testen.
hier gerne auch nochmal der test: https://youtu.be/0dcQ5KOL9S4

**Comment by JannikDatsch** [comment]
Ich kann nur mit einem weiteren Video antworten xD

Es ist auch sonst natürlich nicht absolut relevant, aber es hat mich im ersten Video irritiert, in der Sitaution, deswegen hab ich geschaut, woran es liegt.

Sonst kann ja vlt. ein anderes Teammitglied das auch mal ausprobieren, wie es bei dem dann ist.

https://youtu.be/Z-rsMszcu84

**Comment by Hutstaender** [comment]
Also wie gesagt irgendwas funkt dir da dazwischen, entweder falsche Einstellungen in der Windows Maus oder suspekte Treiber für deine Maus. Vllt sogar ein Antivierensystem, die sind teilweise für die komischsten Bugs verantwortlich.

Hab jetzt mit mehreren Leuten gesprochen, keiner von denen konnte dein Problem nachstellen. Du bist damit dann wohl auf dich gestellt. =(
