### ISSUE TITLE
Musiküberlagerung im Anmeldebildschirm

### ISSUE THREAD

**Issue by Luetti666** [mexyn/statev_v2_issues#1438]
Moin, was mich ein wenig stört ist das ich im Anmeldebildschirm ( wo der Char die Tafel hält ) immer 2 überlagernde Musikstücke höre. Das ist nur eine Kleinigkeit aber vielleicht bekommt man ja irgendwie das Ingameradio, auf dem Dach, weg. ( ja ich könnte es ausstellen aber dann ist es überall aus und nimmt viel Atmosphäre weg )

**Comment by DonVitoDiangelo** [comment]
Bleibt leider so.
