### ISSUE TITLE
Teleport an Playboyvilla

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1439]
Pacho hatte das wohl schon mit den Gamedesigner Team besprochen, anbei noch die Bilder von den dazugehörigen Türen und die Adresse..

![tür3](https://user-images.githubusercontent.com/70241137/116909483-8ee41d00-ac44-11eb-83f1-25173a7d76c7.jpg)

Eingang zur Dachterasse (rechte Tür)
![tür1](https://user-images.githubusercontent.com/70241137/116909518-9a374880-ac44-11eb-8012-717a3b71d4b3.jpg)

Ausgang auf der Dachterasse
![tür2](https://user-images.githubusercontent.com/70241137/116909548-a6230a80-ac44-11eb-90ed-ed6b40deda00.jpg)

**Comment by DrGrizzlY17** [comment]
Eingang zur Teressa ist wo anders, aber done
