### ISSUE TITLE
Cop sachen kaufen in Amo

### ISSUE THREAD

**Issue by RudiAlme** [mexyn/statev_v2_issues#144]
**Rudi_Alme**

**Zeitpunkt (28.08.20 / 18:26)**

**Beobachtetes Verhalten**
wenn ichsachen in die amo packe die denn cops gehören kann ich sie dort kaufen 

**Erwartetes Verhalten**
ich denke das sollte so nicht sein da ich kein kampfmesser so erwerben kann 

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://www.bilder-upload.eu/bild-88cd86-1598632196.png.html
https://www.bilder-upload.eu/bild-73ab44-1598632221.png.html

**Comment by its4l3x** [comment]
Bei den Cop Waffen die jeweilige Transportgroup "ammunation" entfernen.
