### ISSUE TITLE
Falsch gesetztes Hotel

### ISSUE THREAD

**Issue by Alexbold1** [mexyn/statev_v2_issues#1440]
**Alex_Bold**

Jedem
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer
**Beobachtetes Verhalten**

Das Hotel wurde falsch gestellt und überschneidet sich mit dem Nachbargrundstück
**Erwartetes Verhalten**

Zaun sollte nicht quer über treppe verlaufen, Hotel sollte außerhalb des Grundstücks enden
**Schritte um den Fehler nachvollziehen zu können**

Einfach besichtigen

192/ Paleto Pause - Procopio Drive 20 
Haushash | paletobay32

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

Einfach besichtigen

**Optional: Video / Bilder des Fehlers**

![Haus Paleto 1](https://user-images.githubusercontent.com/83372955/116992672-b2f03e80-acd6-11eb-8a5e-873f9ab33104.png)

![Haus Paleto 2](https://user-images.githubusercontent.com/83372955/116992727-c56a7800-acd6-11eb-904e-a68743ab9de1.png)

![Haus Paleto 3](https://user-images.githubusercontent.com/83372955/116992740-cbf8ef80-acd6-11eb-930e-30ac8c43f965.png)

![Haus Paleto](https://user-images.githubusercontent.com/83372955/116992755-d1563a00-acd6-11eb-99ef-d05214c5f087.png)

**Comment by DonVitoDiangelo** [comment]
Wurde einst etwas falsch gesetzt, wird aber auch nicht geändert.
