### ISSUE TITLE
Ausbau des Hotels 

### ISSUE THREAD

**Issue by FrankGrado** [mexyn/statev_v2_issues#1441]
Frank_Grado
Hotel : Hookah Palace - Vespucci Blvd. 36
Firmenhash:  AkiPillboxHillRew_Flat_2

Ich würde mich freuen, wenn ihr mal ein Blick über mein Hotel werfen könntet. Eventuell seid ihr ja der gleichen Meinung.
Dort sind leider etwas wenig Zimmer vorhanden im Vergleich zu anderen Hotels, welche sogar teilweise kleiner sind. Anhand der Größe des Gebäudes (Höhe ,Fläche) wäre es schön wenn ihr die Anzahl der Zimmer anpassen könntet. 

Aktuelle Wohneinheiten : 15

![Hotel1](https://user-images.githubusercontent.com/83590340/117023198-2d31ba80-acf9-11eb-9712-83ab83ba24ce.png)

![Hotel2](https://user-images.githubusercontent.com/83590340/117023217-2f941480-acf9-11eb-99e4-3c7a4e7b55b3.png)

**Comment by DrGrizzlY17** [comment]
Um 10 erhöht
