### ISSUE TITLE
StateNET Bugs

### ISSUE THREAD

**Issue by RealSocius** [mexyn/statev_v2_issues#1443]
1. StateV Net Frontend Code einsichtbar
 Step 1: Firefox öffnen
 Step 2: Dev-Tools öffnen
 Step 3: Debugger Tab öffnen
 
 https://prnt.sc/12htwul

 Nun seht ihr c:// in dem die Typescript dateien sind und unter Angular die Html Templates

2. StateV unendlich lange Werbung für 200$
 Step 1: StateNet Werbungstab öffnen
 Step 2: Billigste Tarife wählen
 Step 3: Über das DevTool das maxlength Attribut im Input entfernen
 Step 4: (ACHTUNG BUGABUSE, deshalb) Werbung (nicht) posten

**Comment by JulianMa** [comment]
..oder das ganze einfach an json api posten. Das macht keinen unterschied.
Es gibt gründe warum das statenet aktuell nicht obfuscated und im prod mode läuft.
Deshalb kein fix hier.

**Comment by MarcelMuerto** [comment]
@RealSocius Danke für den Report des Verhaltens, wir werden uns diesen Anschauen und beim nächsten Update beheben. :)

**Comment by RealSocius** [comment]
Kein Thema, ich helfe gerne.
