### ISSUE TITLE
Tank des 6x6

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#1444]
**Character Name**

Sven Rosenbach
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer
**Beobachtetes Verhalten**

Tank fasst seit V2 nur noch 65 Liter
**Erwartetes Verhalten**

Ein größerer Tank wäre ganz geil, da das Auto recht groß ist und andere um einiges kleiner Fahrzeuge einen viel Größeren Tank haben (Baller Sport 85L, Schafter V12 70L)

**Comment by Statev-Bonsai** [comment]
Dafür verbraucht er weniger...
Der wurde damals bei V1 schon von 50 auf 65l erhöht...

**Comment by SHaagmann** [comment]
in V1 hatte er nen Größeren Tank da bin ich mir ziemlich sicher

**Comment by DonVitoDiangelo** [comment]
wie erwähnt, wurde das Volumen bereits erhöht. Hier wird es keine weitere Änderung geben.
