### ISSUE TITLE
Fehler beim Tanken eines Firmenfahrzeugs

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#1445]
**Character Name**
Paul Humpert

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.05.2021 / 12:14

**Beobachtetes Verhalten**
Wenn man ein Firmenfahrzeug (z.B. einen Abschlepper von der Werkstatt) mit dem Geld von der Werkstatt auftankt, kann man nur so viele Liter tanken, wie man Bar dabei hat (bei mir waren das 3 Liter, da ich nur $4 dabei hatte. Da das Geld jedoch sowieso vom Werkstattkonto abgebucht wird, macht das ja eigentlich keinen Sinn.

**Erwartetes Verhalten**
Das Tanken von Firmenfahrzeugen sollte unabhängig vom Bargeld sein, dass man dabei hat.

**Schritte um den Fehler nachvollziehen zu können**
- Wenig Bargeld dabei haben
- Mit einem Firmenfahrzeug tanken fahren

**Comment by ArnoZuDemB** [comment]
Kann ich bestätigen, ist mir auch schon mehrfach passiert und es ist extrem nervig den Tank mit 20$ in der Tasche vollhauen zu müssen

**Comment by JulianMa** [comment]
Mit nächstem Update behoben.
