### ISSUE TITLE
Wände von Gebäude haben keine Collision

### ISSUE THREAD

**Issue by M4cm4ni4c** [mexyn/statev_v2_issues#1451]
**Beobachtetes Verhalten**
Wände im Gebäude haben keine Collision und man kann durchgehen anscheinend(wollte ich nicht testen falls man da durch die map fliegt)

**Erwartetes Verhalten**
Das die Wände auch Collision haben und man nicht durchclipped wie im bild zu sehen ist

**Schritte um den Fehler nachvollziehen zu können**
Zum Gebäude gehen bei der Verwahrstelle und durch die Wand laufen (siehe minimap im Bild)
![image](https://user-images.githubusercontent.com/79061254/117891532-57661800-b2b7-11eb-8638-48a98afc309d.png)

**Comment by JannikDatsch** [comment]
#1298
