### ISSUE TITLE
Anfrage über Ausgleich der Hotelwohneinheiten

### ISSUE THREAD

**Issue by Grizzlymuerto** [mexyn/statev_v2_issues#1452]
Name: Grizzly_Muerto

Auf dem folgendem Bild sieht man zwei exakt selbe Hotels in Del Perro, welche nebeneinander stehen und die gleiche Größe haben, jedoch unterschiedliche Wohneinheiten!

Hier mein Hotel mit nur 6 Wohneinheiten:

![BayCity Ave29 Hotel Del Perro Nr 2](https://user-images.githubusercontent.com/77779959/118036230-9dc97e80-b36c-11eb-9cb5-51d096a82798.png)

Hier sehen wir den Blick auf beide Hotels. Links das Hotel mit 16 Wohneinheiten und Rechts daneben das gleiche Gebäude mit 6 Wohneinheiten.
![Blick auf beide Hotels](https://user-images.githubusercontent.com/77779959/118036235-a02bd880-b36c-11eb-9481-d8c2cabcc952.png)

Hier ist das Hotel direkt daneben mit mit 16 Wohneinheiten:
![BayCity Ave25 Hotel Del Perro Nr 1](https://user-images.githubusercontent.com/77779959/118036254-a5892300-b36c-11eb-9647-7f7e78cdacf9.png)

Bitte um Anpassung von dem rechten Hotel auf ebenfalls 16 Wohneinheiten, da es sonst in meinen Augen einfach ungerecht ist, wenn exakt dieselben Gebäude unterschiedliche Wohneinheiten haben.

Hash vom Hotel: DelPerro_Flat_25

Vielen Dank!

Viele Grüße
Grizzly Muerto

**Comment by DrGrizzlY17** [comment]
Abgelehnt

Dein Hotel kostet 80.000$, das andere Hotel mehr als das 4fache
