### ISSUE TITLE
Fahrzeug zurückversetzt

### ISSUE THREAD

**Issue by ajrafi** [mexyn/statev_v2_issues#1454]
**Character Name**
Andi Jonson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.05.21  22:52

**Beobachtetes Verhalten**
Heute gegen 18:15 bis ca. 21:00 in der Ostmine mit dem Pounder gewesen. Danach an die Gießerei gefahren wo das Fahrzeug die ganze Zeit geparkt war. Um c.a. 22:49 die Gießerei betreten und als ich paar Minuten später wieder rauskam war der Pounder weg. GPS-Check ergab das er an der Ostmine stand. Hingefahren und da stand er genauso wie ich ihn geparkt habe beim Arbeiten.

**Erwartetes Verhalten**
Pounder steht vor Gießerei

**Schritte um den Fehler nachvollziehen zu können**
??? Keine Ahnung ???

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
---

**Optional: Video / Bilder des Fehlers**
Leider keine

**Comment by JulianMa** [comment]
siehe #400
