### ISSUE TITLE
Haus besitzt keinen Eingang und kann somit nicht gekauft werden

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#1455]
**Character Name**
Paul Humpert

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.05.2021 / 22:30

**Beobachtetes Verhalten**
Ein Haus hat zwar eine Garage, jedoch keinen Eingang. Es wurde auch weit und breit kein Eingang für dieses Haus gefunden.

**Erwartetes Verhalten**
Der Eingang des Hauses sollte neben der Garage sein, wo dieser auch am Haus angebracht ist.

**Schritte um den Fehler nachvollziehen zu können**
Das Haus betrachten und den Eingang richtig setzen

**Optional: Video / Bilder des Fehlers**
![Haus kein Eingang](https://user-images.githubusercontent.com/74912696/118044512-087fb780-b377-11eb-9a6c-1f933a9f6398.PNG)

**Comment by Humperrrt** [comment]
Postal ist 642, habs davor vergessen mit hinzuzufügen ^^

**Comment by DrGrizzlY17** [comment]
Eingangspunkt war schüchtern. Ist mit dem nächsten Update verfügbar
