### ISSUE TITLE
Darstellung von Funk und Kauffenstern zu groß auf 2k Auflösung

### ISSUE THREAD

**Issue by masterppc** [mexyn/statev_v2_issues#1456]
**Character Name**

Hans Hentschel

**Auftrittszeitpunkt (Datum / Uhrzeit)**

2.1 Release

**Beobachtetes Verhalten**

Auf einer 2k Auflösung sieht der Funk aus wie ein Rentner Handy und auch das Kaufinventar ist total groß nun

**Erwartetes Verhalten**

Größe der Fenster skaliert mit Auflösung

**Schritte um den Fehler nachvollziehen zu können**

Auflösung auf 2k stellen und shoppen gehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

2k

**Optional: Video / Bilder des Fehlers**

https://i.imgur.com/8wRkkYo.jpg https://i.imgur.com/WC9cCyD.jpg

**Comment by Hutstaender** [comment]
Ist kein Fehler, das Scaling hat die Texte vorher mit viel zu kleiner Schriftgröße dargestellt. Deine Gewohnheit spielt dir da leider einen Streich. Nun passt alles, egal auf welcher Auflösung die UIs sehen exakt gleich aus und sind angenehm zu lesen.
