### ISSUE TITLE
Hydraulik auf "alle" Autos

### ISSUE THREAD

**Issue by byPandi** [mexyn/statev_v2_issues#1458]
Erfan Asalan

**(13.06.2021/20 Uhr)**

T20 hat aufeinmal Hydraulik

keine Hydralik

Ausprobieren

?

?

**Comment by powerswissi** [comment]
**Character Name**

Josephina_Nardozzi

**Auftrittszeitpunkt (Datum / Uhrzeit)**


ca 20 minuten nach server start nach dem update

**Beobachtetes Verhalten**

bucaneer und virgo, aus der garage geholt. bucaneer am haus mirrow park, virgo an garage mirrow park

Siehe Video


**Erwartetes Verhalten**

hydraulik fahrzeug hüpfen

**Schritte um den Fehler nachvollziehen zu können**

siehe video. wie gesagt, es war bei dem virgo genau das selbe. einsteigen, hydraulik versuch….also, das fahrzeug zum springen bekommen. dachte erst, das es zu eng gewesen wäre am haus. aber virgo hatte ja genug platz.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**


**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=Q8imTf581A8

**Comment by its4l3x** [comment]
Sitzen bereits dran und versuchen nach zustellen an was das liegen könnte.

**Comment by its4l3x** [comment]
Fixed, siehe Hotifx
