### ISSUE TITLE
Antrag - Fahrstuhl für unser Hotel

### ISSUE THREAD

**Issue by masterppc** [mexyn/statev_v2_issues#1459]
**Character Name**

Hans Hentschel

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Es wäre super wenn wir einen Teleporter für unseren Balkon bekommen könnten. Damit sparen wir uns 2 Leiterwagen.

Eingang: https://i.imgur.com/PgMpRc9.jpg
Ausgang: https://i.imgur.com/kreAJo9.jpg
Ort: https://i.imgur.com/18KfWhs.png

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Abgelehnt
