### ISSUE TITLE
Wetter unterschiedlich

### ISSUE THREAD

**Issue by RuedigerRommel** [mexyn/statev_v2_issues#146]
Ruediger Rommel
Arnaldo Bloom

29.08.2020   00:30

**Beobachtetes Verhalten**
Bei einem Regnets beim anderen nicht 
Wetter nicht richtig Gesynct

**Erwartetes Verhalten**
Gleiches Wetter bei beiden 

>

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080
1920x1080
![Ohne Regen](https://user-images.githubusercontent.com/70349694/91620337-f3512d00-e98f-11ea-9847-59124832988d.jpg)
Ohne Regen bei Ruediger
![Mit Regen](https://user-images.githubusercontent.com/70349694/91620389-1d0a5400-e990-11ea-9578-7829c8e1c8f1.png)

Mit Regen bei Analdo gleiche zeit gleiches Auto 

**Optional: Video / Bilder des Fehlers**

**Comment by eiksch** [comment]
Mal ein paar Funktionen ausgetauscht - muss mal getestet werden.
