### ISSUE TITLE
Tankanzeige zufahrt SAC

### ISSUE THREAD

**Issue by dschereau** [mexyn/statev_v2_issues#1460]
**Character Name**
Desmond Schereau

**Auftrittszeitpunkt (Datum / Uhrzeit)**
13.05.2021 / 22:09

**Beobachtetes Verhalten**
Die Anzeige der Tankstelle an der Bootsanlegestelle richtung SAC wird bereits oben auf der Straße angezeigt

**Erwartetes Verhalten**
Anzeige sollte nicht Erscheinen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
2560x1080

**Optional: Video / Bilder des Fehlers**
https://ibb.co/tY5RykJ

**Comment by its4l3x** [comment]
Radius wird anhand des Tank-Punkts und der Tank-Säule berechnet.

Vllt einfach die Punkte verschieben bzw. generell alles verschieben?

@Hutstaender 
@DrGrizzlY17
