### ISSUE TITLE
Scout Livery wechselt

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1461]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
13.05 22:00

**Beobachtetes Verhalten**
Scout (LSPD 601) wechselt beim Ausparken zwischen LSPD und Sheriff Skin.

**Comment by TheOutburst** [comment]
Das ist glaube ich immernoch der AltV bug, beim Mustang wechselt die Livery auch zwischen Police und Sheriff

**Comment by JannikDatsch** [comment]
Bei welchem? Sicher nicht bei allen.

**Comment by its4l3x** [comment]
Das Livery Problem sollte behoben sein. Bitte nochmal mit dem 601 gegentesten

**Comment by JannikDatsch** [comment]
Ist das nur bisher beim 601 gefixt? Weil seitdem 601 nur noch in LSPD gesehen, LSPD 602 und CRU wechseln aber auf jeden Fall noch.

**Comment by its4l3x** [comment]
Jo bei dem 601 bis jetzt nur.

Die Personen welche das nervt, sollen mir im TS privat schreiben, mit den Kennzeichen dann ändere ich das ab. Anforderung: Fahrzeuge müssen in der Garage stehen.
