### ISSUE TITLE
Skills verlernt nach Game Crash

### ISSUE THREAD

**Issue by RickoSanchez** [mexyn/statev_v2_issues#1462]
Character Name
Ricko_Sanchez

Auftrittszeitpunkt (Datum / Uhrzeit)
13.05.2021 ca 23.40 Uhr nach dem Game Crash.
3. Pumpe Großes Ölfeld

Beobachtetes Verhalten
Mein Char war voll ausgelernt in Naturausbeuter : Zeitersparniss 60% Doppelte Chance10%
Minenarbeiter : Zeitersparniss 69% Doppelte Chance 4 %
Raffienerie :  Zeitersparniss 95% , 1,5 % Erfolg Chance .

Jetzt ist mein Char komplett ungelernt  (siehe Bild  https://ibb.co/308fbXq ).

Erwartetes Verhalten
Das es beim Öl pumpen schneller geht .

Schritte um den Fehler nachvollziehen zu können
Ich war auf dem großen Ölfeld an der 3. Pumpe und wollte pumpen da ist mir aufgefallen das es extrem lange dauert und hab dann nachgeschaut und alles gelernte war weg .

Optional: Video / Bilder des Fehlers
https://ibb.co/308fbXq

**Comment by JulianMa** [comment]
Kannst du mir sagen, was genau du im Moment des Crashes gemacht hast?

**Comment by RickoSanchez** [comment]
Ich war am Öl pumpen

**Comment by RickoSanchez** [comment]
Heute Morgen bis zum Server Restart war der alte Lernstand wieder da und aber dem Server Restart war wieder alles weg . Hilft dir das?

**Comment by RickoSanchez** [comment]
Jetzt ist wieder alles Okay.

**Comment by JulianMa** [comment]
Da ist was bei dir in der Datenbank kaputt.
Ich hab den Fehler behoben, der das auslösen konnte und habe deine Daten mal korrigiert.

**Comment by JulianMa** [comment]
Falls der Fehler nochmal bei dir auftreten sollte, dann schreib mich ruhig direkt im Discord an: r3sist3nt#3119

**Comment by RickoSanchez** [comment]
Vielen Dank. Fals was ist melde ich mich .
