### ISSUE TITLE
Falscher Motorenname im Import

### ISSUE THREAD

**Issue by Koree7** [mexyn/statev_v2_issues#1463]
Wann?
14.05.2021 01:04

Was ist falsch?
Falscher Motorenname im Import

Wie sollte es sein?
Richtiger Name

Bild:
![image](https://user-images.githubusercontent.com/51489673/118198026-67fdc600-b450-11eb-8a2a-4cf774f3f228.png)

**Comment by DrGrizzlY17** [comment]
Bitte im Auge behalten ob dieser nochmal aufgetaucht. Sollte eigentlich nicht passieren
