### ISSUE TITLE
Waren Kaufen (öl)

### ISSUE THREAD

**Issue by Falk-Alers** [mexyn/statev_v2_issues#1464]
Character Name
Falk_Alers

Auftrittszeitpunkt (Datum / Uhrzeit)
14.05.2021 ca 00:50 Uhr 

Beobachtetes Verhalten
ich wollte eine leere öl-achse mit 1200l öl an der firma über den marktkauf füllen
wenn ich 1200l also maximal menge wähle erhalte ich einen error, siehe bild unten
wenn ich 1199l kaufe dann funktioniert es

Erwartetes Verhalten
volles befüllen der achse 1200l

Schritte um den Fehler nachvollziehen zu können
öl-achse mit 1200l kaufen befüllen

Optional: Video / Bilder des Fehlers
http://prntscr.com/12w9txa

**Comment by JulianMa** [comment]
Bitte mal nach dem kommendem Update schauen, ob der Fehler auch weiterhin auftritt.
Die Fehlermeldung ist jetzt allerdings anders: 
```
Die Aktion konnte nicht durchgeführt werden. Bitte versuche es erneut.
```
