### ISSUE TITLE
[Markt] Ware Verkaufen

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#1465]
**Character Name**
Marvin_Elpe

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14.05.2021 0:49

**Beobachtetes Verhalten**
Wenn man Waren verkaufen will, allerdings weniger Geld auf den Konto hat als man bekommen würde, kommt eine Fehlermeldung + das man die Waren erfolgreich verkauft hat (was auch klappt).
Zusätzlich steht im Verwendungszweck bei der Überweisung der Marktkauf:[Ware]. Dort sollte Marktverkauf stehen.

**Erwartetes Verhalten**
Verkauf funktioniert ohne Fehlermeldung. Verwendungszweck ist korrekt.

**Optional: Video / Bilder des Fehlers**

![image](https://user-images.githubusercontent.com/33394632/118200883-7a7afe00-b456-11eb-8738-d5766a8e98bf.png)

**Comment by JulianMa** [comment]
Mit kommendem Update behoben
