### ISSUE TITLE
Friseurmenü wird nur zur Hälfte angezeigt

### ISSUE THREAD

**Issue by HarleyHand** [mexyn/statev_v2_issues#1466]
Harley_Hand

Harley_Hand
-ab Hotfix des Servers nach großem Update

**Beobachtetes Verhalten**
Wenn ich das Friseurmenü öffne ist nur noch die Hälfte der Anzeige gefüllt, kann dadurch nicht mehr alle Farben und Frisuren anklicken.

**Erwartetes Verhalten**
Für Normal ist das Kästchen komplett ausgefüllt uns es kann normal durch das Frisuren und Farbenmenü geklickt werden

Bild zum Problem:

https://cdn.discordapp.com/attachments/842399737667911702/842538025883009105/IMG-20210514-WA0002.jpeg

**Comment by Dean-Gallagher** [comment]
Das hab ich auch ebend im Autohaus beim Autoverkauf festgestellt, sieht genauso zusammengedrückt aus wo die fahrzeugdaten stehen.
