### ISSUE TITLE
Kleiner Schönheitsfehler: Telefon App

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#147]
**Character Name**

Jannik_Datsch

**Zeitpunkt (Datum / Uhrzeit)**

29.08 01:15

**Beobachtetes Verhalten**

Bei der Telefonfunktion ist unten eine Leiste zum nach links und rechts verschieben, die eigentlich nicht gebraucht wird

**Erwartetes Verhalten**

Keine Leiste zum verschieben da.

**Schritte um den Fehler nachvollziehen zu können**

Telefon öffnen. und dann die App "Telefon" öffnen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

1920x1080

**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=DjJ9qH_fy5w&feature=youtu.be

**Comment by mxRde** [comment]
bug ist bereits bekannt & gemeldet. duplicate entry
