### ISSUE TITLE
[Piercing] Tattooladen 

### ISSUE THREAD

**Issue by KingBuki** [mexyn/statev_v2_issues#1471]
Guten Tag zusammen,

das Piercing Problem besteht immer noch.
Wenn ein Kunde vor Ort ist, kann man zwar die Tattoos den Kunden anlegen.
Aber nicht die Piercings > Piercings werden immer noch den Tätowierer selbst angelegt.

mfg KingBuki

**Comment by its4l3x** [comment]
fixed seit gestern 18 uhr
