### ISSUE TITLE
Einstellung "Vunkgerät verstecken" wird nach neujoinen oder Serverrestart nicht gespeichert

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#1472]
**Character Name** Erwin Dulach

**Auftrittszeitpunkt (Datum / Uhrzeit)** gestern Abend und heute, 14.05.2021

**Beobachtetes Verhalten** Das Funkgerät ist trotz Einstellung sichtbar

**Erwartetes Verhalten** Die Einstellung wird auch nach Serverrestart / Rejoin gespeichert

**Schritte um den Fehler nachvollziehen zu können** Einstellung machen -> Rejoin nach Restart (ob Rejoin in der selben Periode ausreicht habe ich nicht getestet) -> Funk wieder sichtbar

**Optional: Video / Bilder des Fehlers**

![grafik](https://user-images.githubusercontent.com/70150675/118273411-2d357580-b4c4-11eb-882f-7dad3bea5dbc.png)

**Comment by TheOutburst** [comment]
Aus- und einschalten der Einstellung versteckt das Overlay dann ordnungsgemäß

**Comment by its4l3x** [comment]
fixed next update
