### ISSUE TITLE
Marktplatz - Ei unauffindbar

### ISSUE THREAD

**Issue by VitoCastellano** [mexyn/statev_v2_issues#1473]
Vito_Castellano

13.05.2021/14.05.2021 - Uhrzeit irrelevant, da bisher nicht behoben

Sobald man den Filter des Marktplatzwächters benutzen möchte, ist es unmöglich "Ei" zu finden, da man nicht die Möglichkeit hat im Filter zu scrollen. Es gibt einfach zu viele Gegenstände die mit "Ei" anfangen, dass einem das "Ei" nicht ganz oben gelistet wird. Zudem hat man keine Möglichkeit seine Filter genauer zu verändern. 
**So besteht derzeit keine Möglichkeit das Item "Ei" zu finden.**

Sobald man "Ei" bei Suche eingibt, soll dies auch an erster Stelle erscheinen, damit man "Ei" verkaufen/kaufen kann.

- Marktplatz öffnen
- Gegenstand verkaufen/kaufen auswählen (ist egal)
- bei "Filter" "Ei" eingeben
- leider kein Treffer, da es zu viele Gegenstände mit dem Anfang "Ei" gibt

https://drive.google.com/file/d/1R6c05GRnRnEZnEhGNFptjaSSkOKKk4_3/view?usp=sharing

**Comment by VitoCastellano** [comment]
P.S.: Das Gleiche gilt auch für die Marktplatzeinstellungen in den Firmen.

**Comment by Statev-Bonsai** [comment]
Ich will ja nun nichts sagen, ABER der selbe Fehler wurde 5 Threads unter deinem schon mal protokolliert!
