### ISSUE TITLE
Diamantringe (Frauen) auf dem falschen Slot

### ISSUE THREAD

**Issue by motioncsgo** [mexyn/statev_v2_issues#1474]
**Name**
Mia Randall

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14.05.2021 um 15:20 Uhr

**Beobachtetes Verhalten**
Die Diamantringe für Frauen werden auf dem Kettenslot getragen, daher ist kein gleichzeitiges Tragen einer Kette und des Rings möglich. Sinnvoller wäre es, wenn der Diamantring auf dem linken Armbandslot getragen wird, wie die vielen Ringe. Dies würde aus meiner Sicht mehr Sinn machen, vorallem da mehr Armbänder als Ketten getragen werden.  

**Erwartetes Verhalten**
Der Diamantring sollte auf dem Slot für das linke Armband getragen werden. 

**Schritte um den Fehler nachvollziehen zu können**
Diamantring anziehen (Frauen)

**Optional: Video / Bilder des Fehlers**
![unknown](https://user-images.githubusercontent.com/74965816/118278444-4ccf9c80-b4ca-11eb-9145-3688b9a5a7c2.png)

**Comment by Enemyaa** [comment]
Der Kettenslot dient für sämtliche "Accessoires". Selbst bei GTA selbst ist diese Komponente gemischt mit anderen Sachen - nicht nur Ketten.
Das kann ich nicht eben mal ändern, das kann ich mir aber mal im Hinterkopf behalten.

**Comment by Enemyaa** [comment]
Wobei das eh nicht so easy going ist. Da die Accessoires Clothes sind und die Bracelets - Props!

**Comment by TheMoonicorn** [comment]
Vielleicht wär ja auch eine Option, dass man einen Extra Slot für Ringe machen könnte?

Je nachdem, wie viel Arbeit das ist O.o
