### ISSUE TITLE
Badge wird an den neuen PD Uniformen nicht angezeigt.

### ISSUE THREAD

**Issue by 77maarc** [mexyn/statev_v2_issues#1475]
Aaron Santiago

13.05.2021 / 19:30

**Beobachtetes Verhalten**
Wenn man im PD im Umkleideraum durch die Uniformen schaut (ohne zu Bestätigen), ist alles gut. Wenn man jedoch eine Uniform auswählt, dann wird der  Goldene Badge, das kleine "Police" Schild, und andere Kleine Sachen nicht angezeigt. Dies tritt nur bei den Uniformen ohne Schutzweste auf. Also Bei Allen bei denen es den Goldenen Police Officer Badge hat.

**Erwartetes Verhalten**
Wenn man Uniformen auswählt, sollten die Goldenen Badges, sowie die anderen Sachen, wie das "Police" Schild, Angezeigt werden.

**Schritte um den Fehler nachvollziehen zu können**
Im PD im Kleiderschrank die Uniformen durchschauen (ohne zu Bestätigen), Eine Uniform ohne Weste auswählen, und Bestätigen. Es werden nun keine Badges oder andere kleine Schilder an der Uniform mehr Angezeigt.

**Optional: Video / Bilder des Fehlers**
![Im Auswahl Menu (vor dem Bestätigen)](https://user-images.githubusercontent.com/84183071/118299446-0b96b700-b4e1-11eb-9111-b0786da61f1d.png)

![Nach dem Bestätigen](https://user-images.githubusercontent.com/84183071/118299484-18b3a600-b4e1-11eb-8d7f-e1a3436c43b4.png)

**Comment by Enemyaa** [comment]
Trägst du da möglicherweise gerade eine Tasche?

**Comment by 77maarc** [comment]
Ja...

**Comment by Enemyaa** [comment]
Die Brustbadges liegen auf dem Taschenslot, deswegen solltest du die vorher ausziehen.
