### ISSUE TITLE
Kann nicht mehr durch die Menüs scrollen

### ISSUE THREAD

**Issue by HarleyHand** [mexyn/statev_v2_issues#1476]
**Character Name**
Harley Hand

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19Uhr , 14.05.2021
**Beobachtetes Verhalten**
wenn ich das Handy/Tablet/ Animationsmenü öffne kann ich nicht mehr durch die Menüs scrollen. 
Jedoch beim Öffnen des Optionsmenüs ist die Scroll Funktion aktiv.
**Erwartetes Verhalten**
Für Normal sollte man zwischen den  Animationsmenüs/ durchs Handy/ Tablet scrollen können

**Comment by Hutstaender** [comment]
Warum sollte man gleichzeitig tablet, handy und andere Menüs nutzen?

**Comment by HarleyHand** [comment]
Es war nie die Rede von gleichzeitiger Benutzung.

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Hutstaender** [comment]
Ich würde sagen das liegt nicht an uns? Wenn nur du nicht scrollen kannst, aber jeder andere schon. Überprüfe mal deine Mauseinstellungen in GTA und teste mal verschiedene Input möglichkeiten durch.

**Comment by HarleyHand** [comment]
Leider habe ich da schon alles durchprobiert...hatte auch an sich nichts verändert an den Einstellungen..  das Problem ist erst nach dem Hotfix gestern plötzlich aufgetreten, vorher war alles normal ..Bin langsam ratlos:/ Wenn ich ins normale Einstellungsmenü von GTA gehe dann funktioniert die scroll Funktion. Nur leider nicht wenn ich dann wieder rausgehe

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Hutstaender** [comment]
Also am UI liegt's definitiv nicht, hab mal rumgehört bei allen die ich gefragt hab geht's. Wenn du selbst schon einiges Probiert hast würde ich auf die Üblichen verdächtigen tippen: GTA Installation, oder Alt Cache rigged. Oder ein Antivierenprogramm pfuscht dazwischen.
Sonst können wir dir leider auch nicht weiter helfen, sorry.

**Comment by HarleyHand** [comment]
Alles klar, vielen Dank. Dann werde ich das alles mal rumprobieren

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by HarleyHand** [comment]
Habe Nun komplett GTA, altv..sämtliche caches, virenprogramme etc, die darauf Einfluss nehmen könnten Platt gemacht und neu aufgesetzt...leider besteht das Problem immernoch.
So langsam  weiß ich mir nicht mehr zu helfen:/

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>

________________________________
