### ISSUE TITLE
Rauchen während man eine Animation am laufen hat beendet die Animation nicht

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#1477]
**Character Name**
Paul Humpert

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14.05.2021 / 20:08

**Beobachtetes Verhalten**
Wenn man eine Animation am Laufen hat (z.B. "Arme verschränken (Boss)")

**Erwartetes Verhalten**
Die vorherige Animation sollte automatisch beendet werden, wenn man sich eine Zigarette anzündet.

**Schritte um den Fehler nachvollziehen zu können**
- Eine beliebige Animation auswählen
- eine Zigarette anzünden

**Comment by its4l3x** [comment]
Werden wir nicht abändern, einfach die Animation beenden und Problem gelöst :D
