### ISSUE TITLE
Position der Nasenpiercings

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1478]
Wenn man einen mittelmäßigen Kolben hat dann passt es vorne und hinten net ;D

Stecker:
https://prnt.sc/12xmjvu
Nasenring:
https://prnt.sc/12xmj7c

Und so sollte es eigentlich aussehen...
https://prnt.sc/12xmx4z

**Comment by Enemyaa** [comment]
Ja, es gibt aber im Moment nur die, die zur Auswahl stehen.
