### ISSUE TITLE
Beim Benutzen der Speedgun crasht das game

### ISSUE THREAD

**Issue by MarkHarland** [mexyn/statev_v2_issues#1479]
**Mark_Harland**

**14.05.2021-21:45Uhr**

**Beim benutzen Crasht das Game**

**Das es nicht Crasht**

**Inventar öffnen>Speedgun mit rechtsklick auswählen>Spiel Crasht**

**nur Crashdumps**
[altv_2.23_Steam_0x135e393_14-05-2021_21-40-29.zip](https://github.com/mexyn/statev_v2_issues/files/6480953/altv_2.23_Steam_0x135e393_14-05-2021_21-40-29.zip)
[altv_2.23_Steam_0x135e393_14-05-2021_21-36-54.zip](https://github.com/mexyn/statev_v2_issues/files/6480955/altv_2.23_Steam_0x135e393_14-05-2021_21-36-54.zip)
[altv_2.23_Steam_0x1357ba9_14-05-2021_21-32-16.zip](https://github.com/mexyn/statev_v2_issues/files/6480958/altv_2.23_Steam_0x1357ba9_14-05-2021_21-32-16.zip)
[altv_2.23_Steam_0x135e393_14-05-2021_22-03-42.zip](https://github.com/mexyn/statev_v2_issues/files/6480960/altv_2.23_Steam_0x135e393_14-05-2021_22-03-42.zip)
[altv_2.23_Steam_0x135e393_14-05-2021_21-47-17.zip](https://github.com/mexyn/statev_v2_issues/files/6480962/altv_2.23_Steam_0x135e393_14-05-2021_21-47-17.zip)

**Comment by TheOutburst** [comment]
Dazu sei gesagt: Bei 2 von ~8 Leuten crasht es, beim Rest gehts

**Comment by its4l3x** [comment]
NVE?

**Comment by MarkHarland** [comment]
Ja ich habe NVE es hat aber auch bei welchen mit NVE funktioniert. Ich versuche es aber mal ohne

**Comment by MisterCopeland** [comment]
Bei mir keine Probleme trotz NVE.
Auflösung: 1920x1080 // Rahmenloser Fenstermodus auf 144hz Monitor.

**Comment by its4l3x** [comment]
Jo, dürfte an ENB liegen, einfach ENB rausnehmen. NVE klappt ohne Probs. Daher closed

**Comment by JulianMa** [comment]
@MarkHarland hast du es mal ohne NVE / ENB probiert? Klappt es dann?

**Comment by JulianMa** [comment]
Es kann sein, dass der crash auch von einer bestimmten Einstellung in NVE / ENB kommt, da wir auf der Speedgun texturen ersetzten, und einige Teile der Grafikmods wohlmöglich nicht mit diesem alt:V Feature klar kommen. Dazu muss aber gesagt werden, dass die nicht an uns liegt, sondern an dem grafikmod. Da sollte beim Entwickler dieser mods dann ein issue eröffnet werden.

**Comment by MisterCopeland** [comment]
@JulianMa Wir haben das gestern gemeinsam Reproduziert.

Cleanes GTA -> Kein Crash
GTA + NVE -> Kein Crash
GTA + NVE + ENB -> Crash
GTA + ENB ->  Nicht getestet.
Alles wurde mit und ohne ReSahde getestet. Das macht nichts aus.
