### ISSUE TITLE
Ablieferung MD mit Helikopter

### ISSUE THREAD

**Issue by RuedigerRommel** [mexyn/statev_v2_issues#148]
Ruediger Rommel

29.08.2020   01:28

Nach Ablieferung mit dem Heli im MD Landet man als 1. Neben dem Bett und man hat wenn man X drückt noch die Helikopter Animation mit Abseilen Türen öffnen usw

**Erwartetes Verhalten**
Kein X menü vorhanden

**Schritte um den Fehler nachvollziehen zu können**
Lässt sich mit Heli abliefern im MD nach bewusstlosigkeit wenn man im Bett aufswitcht kann man über X menü noch den Heli Steuern. Nach behandlung ist es weg.

![Bug Heli](https://user-images.githubusercontent.com/70349694/91622852-614e2200-e999-11ea-9ccf-6b0942530c01.jpg)

![Nach Behandlung](https://user-images.githubusercontent.com/70349694/91622868-6d39e400-e999-11ea-8880-0f08b29f5d32.jpg)
Nach Behandlung

**Comment by its4l3x** [comment]
Du kannst das X-Menu weiterhin haben, aber es passiert nichts am Heli ^^ Daher kein Bug
