### ISSUE TITLE
HUD von StateV (Mit "#" aktivierbar) laggt und löst FPS Einbrüche aus

### ISSUE THREAD

**Issue by MystikMaster** [mexyn/statev_v2_issues#1480]
**Character Name**
Miguel_Bartholomae

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Tritt random auf. Hauptsächlich nach dem Verlassen von Gebäuden.

**Beobachtetes Verhalten**
Seit längerem habe ich das Problem, dass meine FPS manchmal von 60 auf 30 runter droppen.
Wenn ich das HUD von StateV deaktiviere sind die Drops verschwunden.
Während dieser Fehler auftritt ist das HUD verzögert und lädt langsam.
Des Weiteren ist die Schrift von manchen Menüs (zB. Werkstatt Computer) sehr klein als wäre die Skalierung
oder der Bildschirmzoom verstellt. Dies ist aber nicht der Fall.

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
3840x2160 4K

**Optional: Video / Bilder des Fehlers**

**Comment by JannikDatsch** [comment]
"Seit längerem habe ich das Problem, dass meine FPS manchmal von 60 auf 30 runter droppen.
Wenn ich das HUD von StateV deaktiviere sind der Drops verschwunden."

Kann ich bestätigen, das ganze vor allem, wenn man am Steuer vom Fahrzeug sitzt (Tachoanzeige) und in eine belebte Zone fährt (WP,LSMD,MRPD)
Das ganze hat sich auch seit Neugestaltung des HUDs des Tachos (Einführung des Tempomats usw.) nm. deutlich verschlechtert:
Kam es zu vor nur zu gleichmäßigem FPS Verlust, so kommt es seitdem zum Teil zu Hängern die z.T. auch länger dauern.

Insgesamt ist dieses HUD sehr FPS lastig, wobei in einem StateV Stream zu V2 (Sommer 2020)  das Thema im Chat aufkam, und bis dahin anscheinend gar nicht bekannte war. Es wurde da gesagt, dass mit V2 durch die Neu-Codierung? dieses Problem entfalle, was nicht geschehen ist, sondern sich eben seit dem Update zum HUD nm. verschlechtert hat.

**Comment by JulianMa** [comment]
Ich wollte da sowieso nochmal drüber schauen. Ich nehme mir das mal.

**Comment by powerswissi** [comment]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```


**Character Name**

Roger Thickle

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Seit dem Altv Update

**Beobachtetes Verhalten**

Wenn das Overlay an ist gehen die FPS in den Keller
Von 100 FPS auf 40 Fps 
Getestet wurde es mit frischen GTA Installation Ohne Mods
Wurde auch mit niedrig , hoch und sehr hohen einstellungen getestet

**Erwartetes Verhalten**

Stabile FPS beim fahren 

**Schritte um den Fehler nachvollziehen zu können**

Einsteigen und fahren ... 
einmal mit overlay an und aus 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**


**Optional: Video / Bilder des Fehlers**

**Comment by JannikDatsch** [comment]
@powerswissi Wie sieht das aus? Das hängt doch vermutlich pirmär mit dem Tacho UI zusammen oder?

Weil dann wäre es doch cool, wenn man einfach erstmal eine 3te "#" Stufe einführen würde, dass:

1. UI komplett da
2. UI da, bis auf das Tacho UI
3. UI weg.

Gerade weil man ja auch Autofahren usw. Navi und auch Essen/Trinken gern sehen würde, und man so nur den teils FPS lastigen Tacho seperat abschalten könnte, nur so als Idee @its4l3x @DonVitoDiangelo 

Das dürfte ja relativ schnell und gut umsetzbar sein

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2424
