### ISSUE TITLE
Manche Fahrzeuge ab und zu unsichtbar seit dem 2.1.0 Update

### ISSUE THREAD

**Issue by MystikMaster** [mexyn/statev_v2_issues#1481]
**Character Name**
Miguel_Bartholomae

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit dem letzten Update (Am 14.05. 3 mal aufgetreten)

**Beobachtetes Verhalten**
Manche Fahrzeuge sind für mich seit dem letzten Update unsichtbar.
Ich sehe nur eine Person, welche im Boden buggt aber kein Fahrzeug.
Nach dem reloggen sehe ich das Fahrzeug wieder.
Bei folgenden Fahrzeugen ist es bislang aufgetreten:
Phantom + Öl Achse
Seventy Seven
Schafter

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
3840x2160 4K
![Screenshot_23](https://user-images.githubusercontent.com/84205671/118328420-40693500-b506-11eb-8e05-01d6bfd03095.png)

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Kann durch ein alt:V Problem auftreten, können dagegen nichts machen, altV weiß bescheid.
