### ISSUE TITLE
Funk geht nicht (Reproduzierbar)

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1482]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14.05.21 00:20

**Beobachtetes Verhalten**
Hat man mehrere Funks aktiv, und schaltet dann einen (Hören) ab, und geht auf sprechen im anderen aktiven Funk, ist es nicht mehr mgl. zu funken, und man muss nm Sprechen aus und wieder an schalten.

**Optional: Video / Bilder des Fehlers**

https://youtu.be/UwfZ_XaBkMs

**Comment by TheOutburst** [comment]
#726

**Comment by JannikDatsch** [comment]
Hier ist aber zumindest eine, der bisher anscheinend unbekannten Ursachen

**Comment by JannikDatsch** [comment]
Gleiches gilt wohl, wenn man auf einem neuen Funkkanal zusätzlich zuhören will, aber noch im alten sprechen will.
