### ISSUE TITLE
Gegenstände nicht aufhebbar. (LSPD)

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1483]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
mehrmals, letztmalig 14.05 

**Beobachtetes Verhalten**
Gegenstände die (von Kollegen) platziert wurden, waren für mich nicht aufhebbar (über .) , für andere Ofc. auch nicht. Ein Lt. konnte dann jedoch über das jedoch. (Weiß nicht ob das generell so ist, aber in der Situation war es so) Ist das so gewollt?

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**
Kollege platziert was -> kann ich und andere Ofc. nicht entfernen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TheOutburst** [comment]
Um Objekte aufzusammeln braucht es seit V2 ein eigenes Recht was durch die Fraktionsleitung vergeben werden kann. Vermutlich hast du (warum auch immer) das Recht nichtmehr.

**Comment by JannikDatsch** [comment]
Ok, na gut, vlt wurde das Intern neuerdings auf ein best. Rang angehoben, denn das ist sehr neu, dass das nicht mehr geht

**Comment by its4l3x** [comment]
Nein, ein Rang hat damit nichts mehr zu tun Wie @TheOutburst schon meinte. Der Leader deiner Fraktion gibt dir Individuell Rechte dafür.

Daher kein Bug und closed
