### ISSUE TITLE
Ui Bug im "Elfenburg"

### ISSUE THREAD

**Issue by SirFeuerstein** [mexyn/statev_v2_issues#1484]
**Character Name**
Mike Feuerstein

**Auftrittszeitpunkt (Datum / Uhrzeit)**
15.05.2021 um ca. 0:02 Uhr 

**Beobachtetes Verhalten**
Das UI "blinkte" extrem

**Erwartetes Verhalten**
Das UI bleibt normal

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
4k Auflösung

**Optional: Video / Bilder des Fehlers**
https://youtu.be/E4Tp1sVAiug

**Comment by its4l3x** [comment]
Könnte ein Problem bei dir sein. Hast du schon mal Versucht zu Reconnecten?

**Comment by its4l3x** [comment]
Gut heute nochmal Fehlersuche betrieben, fehler ist gefunden und wir morgen 18 Uhr deployed. :)
