### ISSUE TITLE
Rolle Stoff bei Werkzeugen?

### ISSUE THREAD

**Issue by nox142** [mexyn/statev_v2_issues#1486]
Jona Lindner

**Auftrittszeitpunkt (Datum / Uhrzeit)**
15.05.31 06:00 Uhr

**Beobachtetes Verhalten**
Haben Veränderung der Produktion stattgefunden?
Für Werkzeuge (Diamanten Spitzhacke, Spitzhacke, Messer, Schaufel, werden plötzlich auch Rolle Stoff in der Fertigung benötigt.
So gewollt oder ein Fehler?

**Comment by DrGrizzlY17** [comment]
Die Änderungen sind so gewollt
