### ISSUE TITLE
StateNet Css Bug Firefox

### ISSUE THREAD

**Issue by RealSocius** [mexyn/statev_v2_issues#1487]
Fehler im StateNet im Firefox Browser:
https://prnt.sc/12ydpbs

Lösung:
Span element der Zeitangabe mit der Property "height: min-height" zu versehen
Im Inspector getestet: https://prnt.sc/12ydrkl

**Comment by MarcelMuerto** [comment]
@RealSocius 
Hatte diesen Bug nicht gestern schon behoben? (#1420)

**Comment by RealSocius** [comment]
Hatte die andere Frage nicht gesehen ... dann ist wohl das duplicate Label angemessen ¯\_(ツ)_/¯

**Comment by MarcelMuerto** [comment]
@RealSocius 
Okay, ja die Änderung kommt auf jeden Fall bei dem nächsten Update mit rein :)
