### ISSUE TITLE
Teleportbug nach Not MD

### ISSUE THREAD

**Issue by RealSocius** [mexyn/statev_v2_issues#1488]
**Character Name**
Sebastian Schindler

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14.05.2021 21:00

**Beobachtetes Verhalten**
Nach Verhungern im Not MD gelandet, dann ist das Spiel abgestürzt. Als ich das Game wieder gestartet habe war ich erneut im Lifeinvader Büro (Firma / Facility (nicht das Lifeinvader Gebäude auf der Map))

**Erwartetes Verhalten**
Am letzten Punkt im Not MD sein

**Schritte um den Fehler nachvollziehen zu können**
1. In ein Bürogebäude gehen
2. Sterben
3. Not MD
4. Game close
5. Im Bürogebäude sein

**Comment by its4l3x** [comment]
Leider bist du zu dem angegeben Zeitpunkt nicht gestorben. Dein letzter Tod war am 15.5 um 0:14.

**Comment by RealSocius** [comment]
Dann habe ich mich wohl in der Uhrzeit vertan. Es ist bisher schon zweimal bei mir passiert einmal davon war gestern. War aber zu müde um das direkt zu melden. Beim ersten Mal hätte es ja Zufall sein können, deshalb habe ich mir dabei nix gedacht.

**Comment by its4l3x** [comment]
Okay, ja leider ist das so gut wie nicht zu reproduzieren. Es kann sein, dass du gestern wirklich am Notfall-MD um die Uhrzeit warst, wir aber nichts mitbekommen haben, da wir zu dem Zeitpunkt Performanceoptimierungen gemacht hatten und dadurch kurzzeitige 10-20 Sekündige Laggs entstanden sind. Daher gehe ich davon aus, dass du auch in der angegeben Zeit dort auch warst, wir kein Log haben, wegen Gründen oben. Schließe das erstmal wieder.
