### ISSUE TITLE
Fahrzeug-Schiebemodell Marked Granger verschoben

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#149]
**Character Name**

Jannik Datsch

**Zeitpunkt (Datum / Uhrzeit)**

29.08  01:50

**Beobachtetes Verhalten**

Das Schiebemodell des Marked Police Granger ist verschoben. Dadurch schiebt man den Granger von hinten im Kofferraum stehend, und von vorne so, dass man zu weit vom Fahrzeug dann weg ist, um den Schiebe-Vorgang abzubrechen.

(Betrifft nur den Marked Granger, nicht den Unmarked Granger.)

**Erwartetes Verhalten**

Korrektes Fahrzeugmodell beim Schieben

**Schritte um den Fehler nachvollziehen zu können**

Granger im X-Menü Schieben

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=2r9_8sdOmLI

**Comment by JannikDatsch** [comment]
Gleiches gilt für den LSMD Dodge Charger KZ: "ERT 3"

**Comment by its4l3x** [comment]
Kein Bug, wurde mit Absicht rausgenommen. Cop Fahrzeuge Ihre Bones bewegen sich leider, dass ist iwie mega strange
