### ISSUE TITLE
Antrag auf Entfernung von unbenutzbaren Gegenständen

### ISSUE THREAD

**Issue by Alexbold1** [mexyn/statev_v2_issues#1490]
**Character Name**
Alex Bold

**Auftrittszeitpunkt (Datum / Uhrzeit)**

immer
**Beobachtetes Verhalten**

Seit dem V2.0 Update stehen 2 Sofas und 1 Kugelgrill im Gerten welches beides nicht benutzt werden kann. Bitte um entfernung der Gegenstände.

Haushash | paletobay32 |  
Hausname | 192/ Paleto Pause

**Optional: Video / Bilder des Fehlers**

![Unbenannt](https://user-images.githubusercontent.com/83372955/118366719-b9b56600-b5a0-11eb-8f75-2475cb481909.png)

**Comment by DrGrizzlY17** [comment]
Abgelehnt
