### ISSUE TITLE
Fehlerhafter Eintrag im Marktplatz ( Tattoofarbe)

### ISSUE THREAD

**Issue by SternChef** [mexyn/statev_v2_issues#1491]
**Character Name** 
Stella Sanchez

**Auftrittszeitpunkt (Datum / Uhrzeit)** 
15.05.21 um 21:20 Uhr

**Beobachtetes Verhalten**

Beim Einstellen von "Tattoofarbe" in den Marktplatz über ein Labor wurde diese nicht im Lager angezeigt.
Im Marktplatz selber kann man nur "Verpackte Tattoofarbe" einstellen.
Diese wird aber nicht im Labor hergestellt.

**Erwartetes Verhalten**

Korrektur der Anzeige im Marktplatz

**Schritte um den Fehler nachvollziehen zu können**

Öffnen der Produktionsverwaltung in einem Labor sowie Öffnung des Markplatzes zum Abgleich des Eintrages
![Screenshot_295](https://user-images.githubusercontent.com/74982338/118375855-b8963000-b5c4-11eb-8314-32880c9fcb5c.png)
![Screenshot_296](https://user-images.githubusercontent.com/74982338/118375858-bd5ae400-b5c4-11eb-86f6-70bf521a6865.png)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Jolu2831** [comment]
Danke, so einen Eintrag wollte ich auch gerade machen. Habe mich IC durch 3 Tattoostudios telefoniert aber die kaufen immer nur unverpackte Tattoofarbe. Sieht  man eigentlich ja auch am Export, dort ist die Tattoofarbe ja auch unverpackt.
