### ISSUE TITLE
Produktionskosten und Boni Schneiderei

### ISSUE THREAD

**Issue by Clawdie** [mexyn/statev_v2_issues#1493]
**Character Name**
Glinda Ehrmantraut

**Auftrittszeitpunkt (Datum / Uhrzeit)**
fortlaufend

**Beobachtetes Verhalten**
Die Produktionskosten für Kleidung steigen mit jedem Update weiter an. Teilweise liegen die Herstellungskosten mittlerweile beim 10-20fachen der Kosten für "alte" Kleidungsstücke.
Ich gehe mal davon aus, dass das so gewollt ist?

Sämtliche mit dem letzten Update zugefügten Kleidungsstücke werden allerdings immer 1:1 hergestellt, ohne dass ein geskillter Bonus abseits der Herstellungszeit berücksichtigt wird.

**Erwartetes Verhalten**
Stoffbaron-Skill (Produktionsbonus) findet auch Anwendung bei neuen und zukünftigen Kleidungsstücken.

**Schritte um den Fehler nachvollziehen zu können**
Produktion Schneiderei, vergleichen

**Comment by Clawdie** [comment]
Nachtrag: Betrifft ja durchaus auch "ältere" Sachen wie Helme, Taschen/Rucksäcke, Outfits, allerdings sollte sowas doch eher die Ausnahme und nicht die Regel sein?

**Comment by Enemyaa** [comment]
Es ist die Ausnahme und betrifft nur wenige GTA Sachen und alle modded Sachen.
