### ISSUE TITLE
Produktion Rechner [Autofertigung]

### ISSUE THREAD

**Issue by byPandi** [mexyn/statev_v2_issues#1495]
Bei der Autofertigung muss man jeden einzelnen Motor mit Preis hinzufügen, damit er das rechnet. Und das macht bei der Autofertigung nicht viel Sinn aber es wäre Cool wenn er es auch einfach ohne Motor Preis rechnet, das wäre auch viel praktischer, weil IC die Marge auch nicht auf den Motor kommt sondern auf die Produktion kosten.

**Comment by Hutstaender** [comment]
Um eine Aussage über den Preis eines Fahrzeugs treffen zu können, muss man sowieso vor Ort sein. Ich denke kurz den entsprechenden Motor zu bepreisen ist dabei kein großes Problem.

Zitat: "... weil IC die Marge auch nicht auf den Motor kommt sondern auf die Produktion kosten."

Hinter der Ersteigerung und dem Abholen eines Motors steckt dennoch ein gewisser Service, den man sich vergüten lassen kann. Wenn du das nicht möchtest liegt es bei dir.

**Comment by byPandi** [comment]
ja aber dann, dass man den Preis auf 0 Einstellen kann

damit der den einfach nicht berechnet

**Comment by Hutstaender** [comment]
Nehm doch einfach 10 Cent oder 1 Dollar? Ich glaub dafür reißt dir niemand den Kopf ab.

Aufwand zu Nutzen liegt da leider bei 0 Dollar lieber nicht einbauen.
