### ISSUE TITLE
Seit Update fehlende Leistung bei Gunlet Hellfire 349PS (GrM)

### ISSUE THREAD

**Issue by MisterGarry** [mexyn/statev_v2_issues#1496]
**Character Name**
Brain Garry / Ogi Black

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit letzten Update

**Beobachtetes Verhalten**
Wheely seit Update nur noch geringfügig (Vorher wurde die Heckstoßstange zerkratzt und war eine weile)
Jetzt geht er kaum noch hoch.
Höhstgeschwindigkeit weniger? vorher 230 jetzt 220
**Erwartetes Verhalten**
Wheely wie vor dem Update

**Schritte um den Fehler nachvollziehen zu können**
Handbremse halten und volle drehzahl erreichen danach, Handbremse lösen

**Comment by Hutstaender** [comment]
Der Hellfire war mit einer Fehlerhaften Konfiguration versehen. Der Fehler wurde mit dem Letzten Update korrigiert.

**Comment by l4m4rr224** [comment]
wieso wird so ein Fahrzeug, was eigentlich als " König " der Muscle Cars bezeichnet wird so beschnitten, ich verstehe den sinn dahinter nicht, die relation zum Verbrauch / Kraft der Hellfire ist einfach much seit dem update

**Comment by Hutstaender** [comment]
Dann hast du unser Balancing System falsch verstanden. Es geht im Grunde darum Fahrzeuge einer Klasse auf ein ungefähr gleiches Level zu setzen. Dabei werden schnelle Fahrzeuge langsamer und langsame Fahrzeuge schneller gemacht, um jedem eine Daseinsberechtigung zu geben. Es gibt nicht das eine Auto, dass in seiner Klasse alles andere Zerstört.
Mal abgesehen davon, dass der Hellfire immer noch einer der schnellsten ist.
