### ISSUE TITLE
Rucksack nicht seh bar bei neuem TankTop

### ISSUE THREAD

**Issue by byPandi** [mexyn/statev_v2_issues#1497]
Erfan Asalan

16.05.2021 Aber auch schon seit dem Update

Sobald ich mir wenn ich dieses neue Schwarze TankTop trage und mein rucksak anziehe den "Schwarze Duffle bag" sieht man den nicht !

Man sollte ihn schon sehen

-

-

https://pic.statev.de/i/EhvUc.jpg

**Comment by ChrisY2k** [comment]
Ist bereits bekannt und soweit ich weis ein Alt:V Problem. Das tritt bei Modded Kleidungsstücken auf.
