### ISSUE TITLE
Werkstatt Rep/Tuning

### ISSUE THREAD

**Issue by CaptainGhostLive** [mexyn/statev_v2_issues#15]
**Zeitpunkt (Datum / Uhrzeit)**

Nach dem man in Tuning HUD nicht Tunend sonder es verlässt kann es nicht mehr verwendet werden.
"mechanic.alreadyTuning"

**Erwartetes Verhalten**

Nach dem Schließen sollte das menu normal abrufbar sein

**Schritte um den Fehler nachvollziehen zu können**

1. Fahrzueg auf Punkt fahren
2. An den Tuning/Rep punkt gehen
3. E Drücken und Menü Öffnen
4. Verlassen Ohne zu Tunen
5. Versuchen das Menü wieder zu öffnen

**Optional: Video / Bilder des Fehlers**

**Comment by mexyn** [comment]
sollte mit dem nächsten update gefixt sein
