### ISSUE TITLE
Fahrzeug schieben, Handbremse Bug

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#150]
**Character Name**

Jannik Datsch

**Zeitpunkt (Datum / Uhrzeit)**

29.08 02:46

**Beobachtetes Verhalten**

Versucht man ein Fahrzeug zu schieben, wo die Handbremse gezogen ist, muss man danach das Spiel neustarten um generell Fahrzeuge schieben zu können, auch wenn diese gar keine Handbremse gezogen haben.

**Erwartetes Verhalten**

Man sollte auch, nachdem man versucht hat ein Fahrzeug mit Handbremse zu schieben, weiterhin problemlos Fahrzeuge schieben können, die keine Handbremse drinnen haben, ohne das Spiel neustarten zu müssen.

**Schritte um den Fehler nachvollziehen zu können**

Vesuch Fahrzeug zu schieben, was aktivierte Handbremse hat -> misslingt -> versucht danach Fahrzeug ohne Handbremse zu schieben -> nicht mehr möglich

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
 https://www.youtube.com/watch?v=wX3D5MMUVok

**Comment by its4l3x** [comment]
Fixed, next update
