### ISSUE TITLE
HK Dienstausweis für Frauen n.v.

### ISSUE THREAD

**Issue by KingMarcel** [mexyn/statev_v2_issues#1502]
**Beobachtetes Verhalten**
im Outfit Erstell-UI ist für Frauen kein Dienstausweis vorhanden. Für Herren gibt es 2 Variationen.
Statt einem Dienstausweis ist nur eine Body Cam vorhanden.

**Erwartetes Verhalten**
Dienstausweis für Frauen sollte in 1-2 Variationen vorhanden sein

**Optional: Video / Bilder des Fehlers**
https://prnt.sc/1305paj

**Comment by Enemyaa** [comment]
Hast du selber Zugriff zur Outfit Erstellung? Weil es gibt einen Dienstausweis für Frauen und da liegt auch keine Body Cam darauf, sondern der richtige Ausweis.

**Comment by KingMarcel** [comment]
Die aktuelle Auswahl
https://prnt.sc/13318j8
https://prnt.sc/13317zh
@Enemyaa

**Comment by Enemyaa** [comment]
Tatsächlich ist der verschwunden. Das wird aber auch leider ne Weile dauern bis er wieder nutzbar ist, da wir nicht so oft DLC's updaten.

**Comment by Enemyaa** [comment]
Sollten wieder gehen!
