### ISSUE TITLE
Antrag auf Teleportpunkt, um in Garten von Haus zu kommen

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#1503]
**Character Name**
Paul Humpert

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.05.2021 / 18:30

**Beobachtetes Verhalten**
Man kann nicht in den Garten des Hauses kommen.

**Erwartetes Verhalten**
Man sollte über Teleportpunkte in den Garten kommen können.
Standort ist zwischen den Postals 644 und 646.

An folgenden Punkten könnten Teleportpunkte hinzugefügt werden:
![Teleport 1](https://user-images.githubusercontent.com/74912696/118405572-e8067480-b678-11eb-9e39-06af2dce9dea.PNG)
![Teleport 2](https://user-images.githubusercontent.com/74912696/118405600-17b57c80-b679-11eb-9a0d-fbf23356ed6f.PNG)

Damit man in den Garten des Hauses kommen kann, wären solche Punkte notwendig, um nicht irgendwo über Mauern zu klettern. Dadurch würde dieses Haus auch attraktiver werden und bald gekauft werden ;)

LG

**Comment by Humperrrt** [comment]
![Klingelschild](https://user-images.githubusercontent.com/74912696/118700327-d5c03e00-b812-11eb-9f7a-55dffe6f9a26.PNG)
Hier nochmal ein Bild von dem Hauseingang :)

**Comment by DrGrizzlY17** [comment]
Abgelehnt
