### ISSUE TITLE
Mitarbeitervertrag

### ISSUE THREAD

**Issue by Auralein** [mexyn/statev_v2_issues#1504]
**Character Name**
Clara Young

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.05.2021 19:20

**Beobachtetes Verhalten**
Link zur Mitarbeitereinstellung nicht richtig gelinkt

**Erwartetes Verhalten**
Link kann angeklickt werden

**Schritte um den Fehler nachvollziehen zu können**
Mitarbeitervertrag verschicken -> Person kann annehmen

**Optional: Video / Bilder des Fehlers**
![grafik](https://user-images.githubusercontent.com/76708950/118406332-eab69900-b67b-11eb-9241-74f3e694b5d0.png)

**Comment by MarcelMuerto** [comment]
@Auralein 
Danke für dein Report, das fehlerhafte Verhalten wird im nächsten Update behoben sein. (Nächster Restart des StateNets)
