### ISSUE TITLE
Oberkörper passt nicht 

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#1506]
**Character Name**

Mila Valdes

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer

**Beobachtetes Verhalten**

Oberkörper passt nicht (keine der 3 Optionen) bei Crop Tops und Neue Adidas Oberteile (Bauchfrei)

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![unknown](https://user-images.githubusercontent.com/70231715/118407457-1425f380-b681-11eb-8b77-ee047154cbbb.png)
![Inkedunknown2_LI](https://user-images.githubusercontent.com/70231715/118407549-81398900-b681-11eb-803f-646f6dc92ba0.jpg)

**Comment by Enemyaa** [comment]
Kurzarm 2 ist der einzige der funktioniert. 

Die Sweater haben dann zwar n minimal kleines Loch am Arm, aber das liegt am Mod und wird hoffentlich mal ausgebessert vom Creator.
