### ISSUE TITLE
Maske abziehen, Person behält Maske optisch auf

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1507]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.05 23:30

**Beobachtetes Verhalten**
Person behält optisch die Maske auf, nachdem sie abgezogen wurde.
Maske landete zwar in meinem Inventar, aber optisch behielt er sie an. Auch seiner Reaktion entnehmend, sah das in seinen Augen genauso aus.

**Erwartetes Verhalten**
Maske verschwindet nicht nur techn., sondern auch optisch

**Schritte um den Fehler nachvollziehen zu können**
siehe Vid

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/cxb_ffjkm0c

**Comment by its4l3x** [comment]
fixed next update
