### ISSUE TITLE
Antrag: 2.Schweinefarm

### ISSUE THREAD

**Issue by xExplicitx** [mexyn/statev_v2_issues#1509]
Charaktername: Jay Parker

Es gibt von jeder Ressource mindestens 2 Felder, nur von den Schweinen nicht. Wäre eine 2.Schweinefarm knapp oberhalb von Los Santos bei den Rindern/Hühnern möglich? 

Hier wäre es doch perfekt oder?

![Schweinefarm](https://user-images.githubusercontent.com/74860489/118442937-8df2c700-b6eb-11eb-9c26-fa84c0d605c2.PNG)

**Comment by DonVitoDiangelo** [comment]
Abgelehnt, es wird keine weitere Schweinefarm geben, da genug im Umlauf ist.
