### ISSUE TITLE
Objekte zu nah am Abladepunkt

### ISSUE THREAD

**Issue by unlocked1337** [mexyn/statev_v2_issues#151]
**John Rizzo**

**Zeitpunkt (29.08. / 03:00)**

**Objekte zu nah am Abladepunkt**

**Mehr Platz für z.B. Phatom mit Achse**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**https://ibb.co/WkpM9RS
https://ibb.co/xYWKWjw
https://ibb.co/dtGZcxk**

**Comment by DonVitoDiangelo** [comment]
Immer den hash der Firma bei solchen Meldungen dazu schreiben @unlocked1337
