### ISSUE TITLE
Pachtfirmen Handelskammer - Doppelte Besteuerung bei Überweisung

### ISSUE THREAD

**Issue by RomanSpielberg** [mexyn/statev_v2_issues#1510]
Roman_Spielberg

Wenn ich bei meiner von der Handelskammer gepachteten Firma, Geld auf mein Privatkonto überweise, erfolgt eine Besteuerung.

Eine von der Handelskammer gepachtete Firma, sollte nicht doppelt besteuert werden, da die 5% ja bereits beim Zahlungseingang auf dem Firmenkonto abgezogen wurden. 

Vielleicht kann ja geprüft werden, ob es eine Firma der HK ist und der offizielle Pächter Geld auf sein Privatkonto überweist, und dann keine weitere Gebührt anfällt, so wie es bei der eignen Firma ist.

**Comment by xExplicitx** [comment]
Ist bei jeder gepachteten Firma so, da du ja nicht der Inhaber bist.

**Comment by RomanSpielberg** [comment]
Aber wenn der Inhaber die HK ist, gibt es überhaupt keine Möglichkeit, der Doppelbesteuerung zu entgehen. Bei allen anderen verpachteten Firmen, kann zumindest der Inhaber ohne Zusatzsteuer das Geld entnehmen.

**Comment by xExplicitx** [comment]
In meinem Fall zahle ich ein Gebäude ab und bin solange als Pächter angegeben, ich zahle also für jede wöchentliche Rate 5% Überweisungsgebühr, wenn ich Produkte über die Firma verkaufe 5% und wenn ich mir vom Firmenkonto etwas auf mein Privatkonto als Privatentnahme überweise nochmal 5% Überweisungsgebühr. 3-fach Besteuerung wenn du es so willst.

**Comment by RomanSpielberg** [comment]
Das hat doch mit meinem Thema an sich nichts zu tun, deine Firma gehört nicht der HK. Das deine Pacht, Zinsen und Rate besteuert werden, ist meiner Meinung nach korrekt, da hier der Einheitssteuersatz trifft. Die kostenfreie Privatentnahme wäre aber weiterhin möglich, für den Inhaber.

**Comment by DrGrizzlY17** [comment]
In Absprache mit Pacho:

Das ganze ist kein Bug, sondern aktuell so gewollt von der HK.
Jeder pachtet hat eine Doppelbesteuerung, da er nicht Inhaber der Firma ist und somit ebenfalls 5% Steuern zahlt bei Auszahlung und Pachtrate.

Bei Rückfragen gerne ans Forum wenden
