### ISSUE TITLE
Bei Telefoneingabe, Interaktion mit Gegenständen

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1512]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11.05 23:30

**Beobachtetes Verhalten**
Bei Schreiben im Telefon wird u. a. Objekt Interaktion getriggert, was seit kurzem bei Tablet, StateCom ja gefixt wurde. 

**Erwartetes Verhalten**
Auch bei Eingabe in Handy, sollten Objekt Interaktion o. ä. nicht ausgeführt werden

**Schritte um den Fehler nachvollziehen zu können**
siehe Video

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/CWdMvyYlJBA

**Comment by its4l3x** [comment]
fixed next update
