### ISSUE TITLE
Item Erdbeerkuchen - Schiefstand

### ISSUE THREAD

**Issue by RomanSpielberg** [mexyn/statev_v2_issues#1513]
Roman_Spielberg

Abgesehen vom allgemeinen Schiefstand im Bereich Lebensmittel, haben wir hier einen extremen Schiefstand, der es unmöglich macht, mittlere Bestellungen in einer angemessenen Zeit zu realisieren. 

Für die Herstellung des Item Erdbeerkuchen werden je Produktion 10 Erdbeeren benötigt. Der "Beifund" für Früchte wurde aber vor einiger Zeit massiv runter gesetzt, da es einfach zu viel war und die Leute auf den Feldern sich komplett davon ernähren konnten (daher wurde die Droprate massiv gesenkt und der Nährwert auch, was wohl auch richtig ist).

Aktuell findet man bei ca. 100 Tomaten etwa EINE Erdbeere, was untern Strich nun bedeutet, man muss unfassbare 50.000 Tomaten ernten, um dann ca. 500 Erdbeeren zu haben, um damit dann  ca. 100 Kuchen produzieren zu können.
 

Eine einfache Lösung wäre, die Anzahl der benötigten Erdbeeren für eine Produktion von 10 auf 1-2 zu senken.

**Comment by its4l3x** [comment]
Siehe Forum Post.

Closed
