### ISSUE TITLE
Verschwinden von Duffle-Bag bei neuen Merch-Shirts

### ISSUE THREAD

**Issue by KruemelGames** [mexyn/statev_v2_issues#1514]
Dave_Weinstein

Immer

Beim Anziehen von Merch-Shirts verschwindet optisch die Duffle-Bag (evtl auch andere Rucksäcke)

Kein optisches Verschwinden der Duffle-Bag 

neues Merch-Shirt anziehen und Dufflebag umhängen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/E7kJJ
https://pic.statev.de/image/E7XKi
https://pic.statev.de/image/E78i6

**Comment by Statev-Bonsai** [comment]
Einfach mal die Suche bemühen...

**Comment by KruemelGames** [comment]
Hatte schon durchgeschaut, habs aber anscheinend überlesen

**Comment by DrGrizzlY17** [comment]
Bei modded Klamotten verschwinden die Rucksäcke in der Regel
