### ISSUE TITLE
Schreibfehler bei Ticketautomat

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1516]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.05.2021 - 22:00

**Beobachtetes Verhalten**
Schreibfehler im Errortext (das V am Ende)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/70150887/118549412-b3b7b480-b75b-11eb-88d9-cd63ea449ab2.png)

**Comment by DrGrizzlY17** [comment]
Sieht nach Zeichenlimit aus

**Comment by its4l3x** [comment]
Der Fehler ist doch schon seit 100 Jahren bekannt :D :D

**Comment by its4l3x** [comment]
habs geändert.
