### ISSUE TITLE
Garage vom Haus SandyShores27 voll

### ISSUE THREAD

**Issue by Stiefel911** [mexyn/statev_v2_issues#1517]
**vielen Dank für die eure Arbeit**,
nur leider scheint sich ein Fehler eingeschlichen zu haben, denn beim Versuch ein Fahrzeug einzuparken kommt die

Fehlermeldung : Die Garage ist voll

wobei sich noch kein einziges Fahrzeug drinnen befindet.
[#1442 ](https://github.com/mexyn/statev_v2_issues/issues/1442)

War mir jetzt nicht sicher ob es nicht evtl auch über dem TS Support geklärt werden kann.?

**Comment by DrGrizzlY17** [comment]
Hey Sorry, mein Fehler. Fixed next update
