### ISSUE TITLE
Tankbug

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1518]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.05.2021 - ca. 23:00

**Beobachtetes Verhalten**
Ich bin zur Tanksäule gefahren und hatte kein Tank UI. 
Der Vorgang ließ sich trotzdem starten allerdings alles ohne UI.
Allerdings konnte dieser Vorgang nicht mehr abgebrochen werden und nur ein Relog half das man wieder laufen konnte.
Anschließend war das Fahrzeug blockiert. (Auf/Zuschließen, sowie tanken nicht möglich)

Ich hatte 160$ Bar dabei.

**Erwartetes Verhalten**
Das Tanken wie gewohnt funktioniert.

**Schritte um den Fehler nachvollziehen zu können**
Unbekannt

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=2uBvWhobQWU

![image](https://user-images.githubusercontent.com/70150887/118557958-42313380-b766-11eb-930e-8f176091f53b.png)

**Comment by Dean-Gallagher** [comment]
Workaround -> nicht direkt E spammen und warten bis Tank UI geladen hat dann E drücken 
für den fall des Fails -> Werkstatt anrufen und abschleppen lassen

**Comment by TheBroady** [comment]
> Workaround -> nicht direkt E spammen und warten bis Tank UI geladen hat dann E drücken
> für den fall des Fails -> Werkstatt anrufen und abschleppen lassen in eine LKW Werkstatt, Ein Ausparken dann ist fixed

Okay, ich war müde und dachte ich hätte Overlays ausgeblendet (Ja auch wenn man sie sieht) War kurz vor dem pennen gehen.
Hab das jetzt so ausgespielt das ich Diesel getankt hätte und den Wagen von einer Werkstatt mitnehmen lassen :D

**Comment by its4l3x** [comment]
@Dean-Gallagher 's Workaround ist eig. kein Workaround, sondern der korrekte Weg. :D 

Closed
