### ISSUE TITLE
Motor Icon im Lager

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1519]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
18.05.2021

**Beobachtetes Verhalten**
Fahrzeugmotoren haben im Lager kein Bild.

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**
Ins Lager schauen wo der Motor liegt und die Entwicklerconsole nutzen

**Optional: Video / Bilder des Fehlers**
Geladen wird folgendes Icon im Lager:
![image](https://user-images.githubusercontent.com/70150887/118606923-471ed300-b7b8-11eb-8b5a-c53c572ab35f.png)

Im Import wird dieses Icon angezeigt: 
https://net.statev.de/assets/images/icons/items/vehicleEngine.png

So siehts im Lager aus
![image](https://user-images.githubusercontent.com/70150887/118607087-79c8cb80-b7b8-11eb-9cfe-b0a1a8c3a364.png)

**Comment by MarcelMuerto** [comment]
@TheBroady 
Danke für dein Report, dieser Fehler ist im nächsten Update des StateNet's behoben ✔
