### ISSUE TITLE
Viele PD Fahrzeuge nicht schiebbar

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#152]
**Character Name**

Jannik Datsch
**Zeitpunkt (Datum / Uhrzeit)**

29.08 03:12
**Beobachtetes Verhalten**

Es sind viele PD Fahrzeuge nicht schiebbar 

nicht schiebbar: CVPI unmarked/LSPD, Interceptor, Buffalo marked, Mustang, Motorrad

schiebbar: CVPI Sheriff, Granger unmarked/marked, Buffalo unmarked, McLaren, Fahrrad

**Erwartetes Verhalten**

Es sollten entsprechend gebaute PD Fahrzeuge schiebbar sein, bzw. wenn das nicht gewollt ist, dann alle nicht schiebbar sein.

**Schritte um den Fehler nachvollziehen zu können**

siehe oben

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Hier gab es bei div. Emergency Fahrzeugen Probleme mit den Bones, daher haben diese keine Schiebe Animation.
Da wo es ging, gibt es die Animation aber und wird es weiterhin geben.
