### ISSUE TITLE
Fahrzeug wird teleportiert

### ISSUE THREAD

**Issue by Donplaya85** [mexyn/statev_v2_issues#1520]
Schönen guten Tag zusammen,

es ist nun mehr wiederholt vorgekommen, dass mein Fahrzeug "Revolter" wegteleportiert wurde nachdem ich eine Firma bzw. ein Geschäft verlassen habe. In der Regel wird es an einen Ort teleportiert an dem ich an diesem Tag bereits einmal mein Fahrzeug abgestellt habe. ( Nicht eingeparkt, nur abgestellt). Es wirkt fast so als ob manchmal wenn ich eine Firma bzw. ein Geschäft betrete (Juwelier) das ein alter Speicherort für das Fahrzeug gebraucht wird.

Hoffe es kann da Abhilfe geschaffen werden denn ein ständiges Taxi fahren und besuchen einer Werkstatt ist zwar ab und an mal unterhaltsam und lustig aber da das Fahrzeug in der Regel dann auch öfters beschädigt ist schwer auszuspielen.

Mit freundlichem Gruß

Tom Barnaby

**Comment by JulianMa** [comment]
Siehe #400
