### ISSUE TITLE
Haus ist nicht registriert (besitzt keinen Eingang/Garage)

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#1525]
**Character Name**
Paul Humpert

**Auftrittszeitpunkt (Datum / Uhrzeit)**
18.05.2021 / 20:00

**Beobachtetes Verhalten**
Das Haus besitzt weder einen Eingang, noch eine Garage.

**Erwartetes Verhalten**
Das Haus sollte eine Garage und einen Eingang haben

**Schritte um den Fehler nachvollziehen zu können**
- Hauseingang hinzufügen
- Garage hinzufügen
- Teleportpunkt um in den Garten zu kommen

Bild vom Haus:
![Haus ohne alles](https://user-images.githubusercontent.com/74912696/118704057-04d8ae80-b817-11eb-81bc-d43876764b1a.PNG)

Standort vom Haus:
![Haus ohne alles Standort](https://user-images.githubusercontent.com/74912696/118704429-66991880-b817-11eb-8210-4241751e1c96.PNG)

Teleportpunkt für Garten am Vordereingang:
![Teleport Haus ohne alles vorne](https://user-images.githubusercontent.com/74912696/118704501-7c0e4280-b817-11eb-8419-c17ee469156c.PNG)

Teleportpunkt für Garten im Garten:
![Teleport Haus ohne alles 1](https://user-images.githubusercontent.com/74912696/118704573-8fb9a900-b817-11eb-8328-95788d488157.PNG)

**Comment by Enemyaa** [comment]
Danke für die Info! Wird dann bald verfügbar sein!
