### ISSUE TITLE
Haus besitzt keinen Eingang

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#1526]
**Character Name**
Paul Humpert

**Auftrittszeitpunkt (Datum / Uhrzeit)**
18.05.2021 / 21:00 Uhr

**Beobachtetes Verhalten**
Haus besitzt keinen Eingang und kann somit nicht gekauft werden.

**Erwartetes Verhalten**
Haus sollte einen Eingang besitzen sowie möglicherweise eine Garage

**Schritte um den Fehler nachvollziehen zu können**
- Haus Eingang sowie Garage hinzufügen

Standort vom Haus:
![Standort](https://user-images.githubusercontent.com/74912696/118712440-132bc800-b821-11eb-90b1-ac0d5d82d476.PNG)

Eingangstür:
![Eingang](https://user-images.githubusercontent.com/74912696/118713061-d01e2480-b821-11eb-9cbe-654cb420fd50.PNG)

Garage:
![Garage](https://user-images.githubusercontent.com/74912696/118713128-e0360400-b821-11eb-9d35-51e63d6787f1.PNG)

**Comment by Enemyaa** [comment]
Danke für die Info!
