### ISSUE TITLE
Doppelter Name

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#1528]
**Character Name**

Ryan_Valdes
**Auftrittszeitpunkt (Datum / Uhrzeit)**

19.05.2021
**Beobachtetes Verhalten**

Doppelter Name im Produktionscomputer

Das erste ist blank ohne Schirft das zweite mit dem rosa Adidas-Schriftzug

Siehe Bild 
**Erwartetes Verhalten**

Kein Doppelter Name
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![adidas bug](https://user-images.githubusercontent.com/70231715/118829977-e3330200-b8be-11eb-9579-021bba81ab21.png)

**Comment by Enemyaa** [comment]
Next Update
