### ISSUE TITLE
Fahrzeuge Schieben, Abbruch

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#153]
**Character Name**

Jannik Datsch

**Zeitpunkt (Datum / Uhrzeit)**

29.08 03:30

**Beobachtetes Verhalten**

Versucht man ein Fahrzeug zu schieben, so passiert es immer wieder, dass der Vorgang nach dem Spawn zum Fahrzeuganfang/-ende abbricht. 

Dies passiert besonders häufig dann, wenn das Fahrzeug zum Ende hin nicht kontrolliert auf 0 gebremst wurde, sodern bsp. der Motor davor abgeschaltet wurde. Aber auch bei Unfällen, wenn das Fahrzeug aus der Garage kommt, oder wenn es davor schon geschoben wurde. 

**Erwartetes Verhalten**

Der Schiebevorgang wird nicht abgebrochen.

**Schritte um den Fehler nachvollziehen zu können**

oben beschrieben

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/X-DrZR1whag

Auch hier am Anfang: https://www.youtube.com/watch?v=2r9_8sdOmLI

**Comment by its4l3x** [comment]
Hi, die Police Fahrzeuge wurden wegen den Bones generell schon rausgenommen. Da waren noch 3 Fahrzeuge drinnen, welche eig. raus sollten, darunter auch der Granger, welcher nun auch draußen ist. Das Abbrechen hat mehrere Gründe. z.B. wenn,
- Das Fahrzeug mit etwas collided.
- Der Fahrzeugsitz vom Fahrer nicht mehr frei ist.
- Aufeinmal jemand wieder im Fahrzeug hockt.
- Du auf einmal stirbst.
- Sich das Fahrzeug dreht (rotiert)

Daher ist das auf deinem Kurzen Video zu sehen invalide, weil das alles passiert sein kann, du kannst ja schließlich auch mit dem Fahrzeug als Spieler collided sein ;)
