### ISSUE TITLE
Böse Tore entfernen (Kartoffel-Feld Paleto)

### ISSUE THREAD

**Issue by Knippsa** [mexyn/statev_v2_issues#1530]
**Character Name**
Kalle Knutsen

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Würde mich freuen, wenn das Tor beim Kartoffel-Feld in Paleto, entfernt wird. Es führt halt immer dazu, dass die Fahrzeuge angekratzt werden. Leichte Beulen gehen nach Dimensionswechsel zwar wieder weg aber wenn das Licht beschädigt wird, bleibt das. Dabei ist es auch egal mit welcher Geschwindigkeit gegenfährt. Selbst beim "anstupsen" kann es dir die Front zerhauen.

**Erwartetes Verhalten**
Tor weg; KFZ heil

**Schritte um den Fehler nachvollziehen zu können**
Immer feste druff ;)

**Comment by Stiefel911** [comment]
Wo fährst du da bitte durch ein Tor? Hab da noch nie eins gesehen.

**Comment by Knippsa** [comment]
Da? https://pic.statev.de/image/EVXZD

**Comment by Stiefel911** [comment]
Wenn du eins vorher rein fährst hast du offen, fast als wenn du zu den Wasserpumpen möchtest 😉. 
Denn da fährt mein Charakter immer rein.... Deswegen wusste ich nicht mal das dort überhaupt ein Tor existiert 🙃🤭

**Comment by Knippsa** [comment]
Das stimmt sogar xD Ist mir nie aufgefallen.

**Comment by DrGrizzlY17** [comment]
Habs trotzdem entfernt
