### ISSUE TITLE
Unbrauchbare Punkte nach Gamechrash in den Werkstätte/Tattoo/Friseur

### ISSUE THREAD

**Issue by KorbysWorld** [mexyn/statev_v2_issues#1531]
Josh Korby

Josh Korby
**Auftrittszeitpunkt (Datum / Uhrzeit)**
Unregelmäßig

**Beobachtetes Verhalten**
Mechaniker/Friseur/Tättowierer fliegt aus dem Game. 
Der bespielte punkt zeigt dann Fehler auf das man derzeit in einem Arbeitsschritt ist ... 
Andere können den Punkt nicht weiter nutzen. 
Beide spieler müssen sich dann relogen um bsp das auto von der Hebebühne zu bekommen.

Änderungsverhalten nach einem Server restart.

**Erwartetes Verhalten**
Das trz. Gamechrash der Arbeitsschritt weiter ausgeführt wird um ein Missstand der Arbeitspunkte der Spezialobjekte zu verhindern.

**Schritte um den Fehler nachvollziehen zu können**
Autoreparieren - während des vorgangs Spielbeenden - anderer User versucht auf den Punkt neu zugreifen. 

Gruß Korby

**Comment by its4l3x** [comment]
fixed next update
