### ISSUE TITLE
Chucks Bug

### ISSUE THREAD

**Issue by Domeex3** [mexyn/statev_v2_issues#1532]
Domenik_Sommer

Permanent

**Beobachtetes Verhalten**
Leichtes Buggen der Socken durch die Hose, Aufgetreten bei Skinny Jeans (Nicht bei Levis Skinny auch wenn die fast 1:1 so geschnitten sind), Jogger, Baggy Sagged Jeans, Urban Cargo Pants, Adidas Joggern, Drop Crotch Jeans und sicher ein paar andere

**Erwartetes Verhalten**
Hose liegt über Socken, Problem liegt zu 99% an den Socken.

![Chucks Bug](https://user-images.githubusercontent.com/70150715/118846905-7b37e800-b8cd-11eb-864f-a5fa5d417b56.png)

**Comment by Domeex3** [comment]
![ChucksLevis](https://user-images.githubusercontent.com/70150715/118848507-19787d80-b8cf-11eb-8d50-dc1e4aa6079a.png)

Hier mit Levis Skinny als Verlgleich

**Comment by Hutstaender** [comment]
Dagegen können wir leider nichts machen, bestimmte Kleidungsstücke können einfach nicht miteinander getragen werden. Rockstar hat da teilweise Restriktionen eingebaut, wodurch du nur passende Klamotten zusammen anziehen kannst. Bei uns gibt es solche einschränkungen nicht, dafür musst du dir leider die passende Hose suchen.
