### ISSUE TITLE
Boot: Tug betanken nicht möglich

### ISSUE THREAD

**Issue by ZacCooperr** [mexyn/statev_v2_issues#1533]
**Character Name**
Zac Cooper

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.05.2021 von 18:30 - 21:30 Uhr 

**Beobachtetes Verhalten**
Wir wollten unser Tug an der Bootstankstelle in LS betanken, jedoch egal in welcher Position (Schiffsspitze, Schiffshintern, Seitlich) das Tug auch steht, die Tankstelle erkennt das Boot nicht (Marker). Meldung: Kein Fahrzeug zum Betanken gefunden. 
Alternative dazu war angedacht den Tankkanister zu benutzen. Das komplette Schiff wurde abgelaufen als auch unterwasser, leider erfolglos und die gleiche Meldung.
Als dritte Möglichkeit wurde die  Bootstankstelle San-Chianski-Bergkette mit 2 Zapfsäulen) angesteuert, erfolglos und zu guter letzt auch noch die Bootstankstelle in Paleto Cove, erfolglos.
Auch andere Personen haben es versucht.

Vorab wurde durch das einparken der ungefähre Punkt ausgemacht. 

Nach erfolglosen 2 1/2 Stunden haben wir kurz im Support nachgefragt, jedoch ist nichts bekannt und somit dieser Eintrag.

**Erwartetes Verhalten**
Tug auf den Marker fahren und danach an die Zapfsäule tanken.

**Schritte um den Fehler nachvollziehen zu können**
-In jeglicher Position den Marker angefahren. (Egal zur welcher genannten Bootstankstelle). Testweise auch mit und ohne Anker.
-Im Anschluss zur Zapfsäule gelaufen und versucht mit den Tankvorgang zu beginnen. Alternative auch vom Schiff versucht.

**Optional: Video / Bilder des Fehlers**
![Tug- Kein Fahrzeug zum Betanken gefunden](https://user-images.githubusercontent.com/74767269/118878181-93b8fa00-b8ef-11eb-8946-56e62126605e.png)
![Marker](https://user-images.githubusercontent.com/74767269/118878222-9c113500-b8ef-11eb-9587-67b788af6eea.JPG)

**Comment by glb11** [comment]
Das kann ich bestätigen das es nicht geht (bis jetzt nur Grapseed und die beim Kaffee getestet gehabt.         Meine Vermutung zur Ursache:. Das der Radius der Tanke zu Tief im Wasser liegt. Dieser wurde zum Start der V2 wegen dem U-Boot nach unten verlegt weil diese Sonst nicht nutzbar waren für das Boot.  (Also den Radius etwas vergrößern so das Boot wieder erkannt wird (Wenn es an den Tanken selber liegt))

**Comment by DrGrizzlY17** [comment]
@its4l3x Maybe nen neuen cb mit höherem Radius für Bootstanken?

**Comment by glb11** [comment]
#1183 war ein ähnliches Problem.  Da ging es durch versetzten des Punkten in tieferes Wasser

**Comment by JulianMa** [comment]
> @its4l3x Maybe nen neuen cb mit höherem Radius für Bootstanken?

Der cb type regelt nur den Radius für den Interaction Marker.
Ich kann aber der Radius für die Fahrzeugsuche für Boote erhöhen.

**Comment by JulianMa** [comment]
Mit nächstem Update behoben.
