### ISSUE TITLE
Hotel Abrechnung der Miete fehlerhaft

### ISSUE THREAD

**Issue by SEUKings** [mexyn/statev_v2_issues#1534]
**Character Name**
Calvin Kings

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer wenn jemand in ein Hotelzimmer einzieht

**Beobachtetes Verhalten**
**_Einige Hotels haben das Problem mit der Abrechnung._**

**Beispiel :**

Max Mustermann zieht um 14:00 Uhr ins Hotelzimmer ein.

Beim Einzug wird ihm direkt einmal die Miete abgezogen.

Danach bekommt er, trotz gedeckten Konto, stündlich eine Meldung, dass sein Konto nicht gedeckt sei.

Das ganze geht dann bis 18 Uhr so, bis dann der Server Neustart kommt und erst dann werden ihm stündlich die Miete abgezogen.

Das gleich gilt natürlich auch wenn jemand nach 18 Uhr einzieht. Dann wird im erst die Miete ab 8 Uhr (Server Neustart) abgezogen.

**Erwartetes Verhalten**
Erwartet wird, dass direkt nach dem Einzug eines Mieters, die Miete stündlich abgezogen wird und nicht erst nach Server Neustart

**Schritte um den Fehler nachvollziehen zu können**
Ins Hotel einziehen und feststellen, dass nach einer Stunde eine Fehlermeldung kommt

**Comment by JulianMa** [comment]
Vermutlich selber Fehler wie hier: #1114

**Comment by JulianMa** [comment]
Ist bekannt und mit dem nächstem Update behoben.
