### ISSUE TITLE
StateNet Fahrzeugbilder

### ISSUE THREAD

**Issue by FynnScherer** [mexyn/statev_v2_issues#1535]
**Character Name**
Fynn Scherer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
20.05.2021 00:11

**Beobachtetes Verhalten**
Kein Anzeigebild beim Declasse Stallion im StateNet

**Erwartetes Verhalten**
Nen Anzeigebild

**Schritte um den Fehler nachvollziehen zu können**
Nen Declasse Stallion-Schlüssel haben und unter Fahrzeuge im StateNet schauen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
3840x2160 (ka ob das relevant is)

**Optional: Video / Bilder des Fehlers**
<img width="251" alt="Screenshot_4" src="https://user-images.githubusercontent.com/80713933/118891853-4729ea80-b900-11eb-94d5-85e5b231f508.png">

**Comment by Patrick-Snooze** [comment]
Da könnte man eigentlich ein Sammelbeitrag draus machen :D

- Shitzu Jetmax
- Zombie Bobber / Chopper
- Krieger
Da gibt es sicher noch ein paar andere...

**Comment by Statev-Bonsai** [comment]
+
Pounder Custom
Bati Custom (Race)

**Comment by MystikMaster** [comment]
- Albany VSTR
- Bravado Gauntlet Hellfire (hat bild von dem normalen Gauntlet drin)
- Dundreary Landstalker XL

**Comment by TheMoonicorn** [comment]
- Brioso 300

**Comment by JonnyHart** [comment]
Bale Trailer

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1640

**Comment by epichalt** [comment]
Dubsta Sport
Gauntlet Classic Custom
Trailer BG

**Comment by DonVitoDiangelo** [comment]
Next update alle Fahrzeugbilder nachgereicht
--------------------------------------------------------------------------------------------------------
