### ISSUE TITLE
Locs Brillen & Frisuren

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1537]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
20.05.2021

**Beobachtetes Verhalten**
Wenn man die Brille aufsetzt clipped die Frisur weg.
Das ist nur behebbar in dem man eine andere Bille anzieht oder bsp. diese Hörschläuche.

**Erwartetes Verhalten**
Das diese auch mit Mod Frisuren nutzbar

**Schritte um den Fehler nachvollziehen zu können**
Locs kaufen, Mod Frisur haben und locs aufsetzen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=CpqurLCbbt4

**Comment by Enemyaa** [comment]
Next Update!
