### ISSUE TITLE
Double-T Tuning und Blitzer

### ISSUE THREAD

**Issue by Koree7** [mexyn/statev_v2_issues#1539]
**Character Name**
Brooks Miller

**Beobachtetes Verhalten**
- Double-T nicht tunebar wie in GTA-Online (Carbon-Verkleidung und Auspuff)
- Trotz (Race) im Namen und ohne Kennzeichen wird man geblitzt

**Erwartetes Verhalten**
- Verkleidung und Auspuff tunebar
- Nicht geblitzt werden

**Schritte um den Fehler nachvollziehen zu können**
- Tuning anschauen in der Werkstatt
- Blitzen lassen

**Comment by DrGrizzlY17** [comment]
Von welchem Fahrzeug ist hier die Rede? Wir haben kein Fahrzeug namens Double-T

**Comment by DrGrizzlY17** [comment]
Die von dir angesprochenen Tuningmöglichkeiten scheinen bei unseren freigegebenen Tuningmöglichkeiten nicht verfügbar zu sein.

Wegen dem Blitzen, muss @its4l3x mal nachschauen, Fahrzeughash "double"

**Comment by Koree7** [comment]
Ist es möglich diese Tuningmöglichkeiten (evtl. falls vorhanden auch von anderen Fahrzeugen) in Zukunft irgendwann hinzuzufügen?

**Comment by DrGrizzlY17** [comment]
Aktuell nicht geplant, nein

**Comment by its4l3x** [comment]
ist abgeändert, kommt im nächsten update

**Comment by Koree7** [comment]
Akuma (Race) und Double-T (Race) werden immer noch geblitzt.

**Comment by Koree7** [comment]
![image](https://user-images.githubusercontent.com/51489673/121779303-400e9900-cb9b-11eb-9259-3d8551a457fa.png)

**Comment by Koree7** [comment]
![image](https://user-images.githubusercontent.com/51489673/124304099-8b491580-db63-11eb-94f9-e475f2e6c514.png)

@its4l3x  :-(
