### ISSUE TITLE
Keine Motoren am Import abholbar

### ISSUE THREAD

**Issue by RuedigerRommel** [mexyn/statev_v2_issues#154]
Ruediger Rommel
Arnaldo Bloom

29.08.2020 13:00

**Beobachtetes Verhalten**
Motor ersteigert über Fahrzeugfertigung wenn man sie abholen will kommt keine Berechtigung dafür obwohl alle Rechte erteilt.

Man kann die Motoren verladen

**Schritte um den Fehler nachvollziehen zu können**
Motor Kaufen und abholen am Import punkt Flughafen
![Bug Motor](https://user-images.githubusercontent.com/70349694/91638287-9d6f9a00-ea0e-11ea-921e-3af4d9eda1d7.jpg)
Ersteigerte Motoren 

![REchte Firma](https://user-images.githubusercontent.com/70349694/91638293-ab251f80-ea0e-11ea-9481-e7a8ee59987f.jpg)
Meine Rechte der Firma

**Comment by tastydev** [comment]
wie lautet de firmenname/hash? @RuedigerRommel

**Comment by RuedigerRommel** [comment]
Grand Bank cars

tastydev <notifications@github.com> schrieb am Sa., 29. Aug. 2020, 17:39:

**Comment by tastydev** [comment]
fixed
