### ISSUE TITLE
Vapid Utiliti (Contender)

### ISSUE THREAD

**Issue by wanderwolf4** [mexyn/statev_v2_issues#1540]
Hallo,
Nick_Johnson der Name folgendes Pobleme habe ich mit diesem Fahrzeug--->
1. Kofferaumklappe öffnet nach innen und glitcht durch den hinten auf der Ladefläche liegenden Plastikeimer.
2.  Der Wagen hat keinerlei Tuning möglichkeiten...Ist es geplant wenigstens Reifen +FelgenTuning auf den Server zu spielen?
3. 180kg Kofferaumvolumen---> rein Optisch müsste der Wagen mehr haben als z.b. ein Bison (hat 220) und der (Bison Standart 250) dies passt in meinen Augen nicht ganz da der Vapid Utiliti (Contender)  eine erheblich größere Ladefläche +ganze Schränke als Seiten Backen hat...Ist es geplant dies zu ändern?
4 Vielen dank fürs lesen :) und danke schonmal im vorraus

**Comment by wanderwolf4** [comment]
1 Punkt vergessen das Fahrzeug Bild fehlt unter den aufgelisteten Fahrzeugen.

**Comment by Dean-Gallagher** [comment]
Wo Fehlt das Bild?

**Comment by DrGrizzlY17** [comment]
Grüße,
1. Wenn mich nicht alles täuscht, ist das mit der Kofferraumklappe von GTA aus, maybe @its4l3x kann mehr dazu sagen.
2. Wir haben das Tuning nicht geblockt für dieses Fahrzeug, dann hat es von GTA aus keine Tuningmöglichkeiten
3. Kofferraumgröße kann dir @Hutstaender mehr sagen
4. Was meinst du, wo fehlt ein Bild?

**Comment by Hutstaender** [comment]
Ja du hast recht, die Ladeflächen von Bison und Utillitytruck sind ungefähr gleich groß, aber durch den ganzen Kram auf der Ladefläche ist leider nicht mehr so viel über. Deswegen die niedrigere Kapazität. Das Fahrzeug verfolgt einen RP gedanken für beispielsweise Hausmeister oder Gärnereispieler.

**Comment by its4l3x** [comment]
Zum 1. Thema, leider liegen die Objekte hinten am Fahrzeug am Fahrzeug Modell selbst, welche nur durch manuelle Bearbeitung entfernbar sind. Sich dafür den Aufwand zu machen, macht keinen Sinn. Zum Thema Ladeklappe öffnet nach innen: Jo kommt von GTA aus.

**Comment by wanderwolf4** [comment]
Hallo
Das Bild fehlt im State Net unter dem reiter Fahrzeuge.

Zu den anderen Antworten vielen dank---> Und die Ladefläche mag voll sein aber der Wagen hat diverse Schließfächer Artige Verstaumöglichkeiten.
