### ISSUE TITLE
Unmarked Mustang Livery

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1544]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.05.2021

**Beobachtetes Verhalten**
Die beiden Unmarked Mustangs  der OCD haben eine SAPD Livery drauf

**Erwartetes Verhalten**
Das diese wieder Schwarz bzw, dunkel Blau sind.
Wie Früher
LSO - Schwarz
LSX - Dunkel Blau

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeuge Ausparken und schauen was für eine Livery drauf is

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![20210522112458_1](https://user-images.githubusercontent.com/70150887/119221593-5c656b80-baf0-11eb-9e38-d1bb73480bb4.jpg)

**Comment by DonVitoDiangelo** [comment]
Bei diesem Fall bitte die Fahrzeuge eingeparkt und mit Kennzeichen bei Alex melden. Dort wird euch dann geholfen.
