### ISSUE TITLE
Im Dienst Personalausweise Zeigen

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1545]
**Character Name**
Max Broady

**Beobachtetes Verhalten**
Es ist nicht möglich im Dienst seinen Personalausweis vorzuzeigen.
Man kann nur den Dienstausweis vorzeigen

**Erwartetes Verhalten**
Das man beide Vorzeigen kann, gerade bei Undercover Einsätzen ist es von Vorteil nicht den Dienstausweis zu zeigen.
Schließlich kann man den Dienstausweis auch außer Dienst zeigen.

**Comment by Hutstaender** [comment]
Welchen Grund gibt es denn, unbedingt den Personalausweis im Dienst zeigen zu müssen?

**Comment by MisterCopeland** [comment]
"Gerade bei Undercover Einsätzen ist es von Vorteil nicht den Dienstausweis zu zeigen."
Klingt plausibel und ist verständlich.

**Comment by TheBroady** [comment]
Egal ob Undercover in einer Firma oder Ähnlichem ist es manchmal notwendig den Ausweis zu zeigen.
Dies dann zu verweigern ist meist heikel und trägt nicht zum erfolgreichen Abschluss der Ermittlungen bei.

**Comment by masterppc** [comment]
Wir hatten es erst letzte Woche, Undercover ins Unicorn und die Secruity verlangt nen Ausweis und dann wurde halt 3x der Dienstausweis gezeigt (Pole hat es aber gecheckt und es net weiter angespielt) weil man leider nicht den normalen Perso zeigen kann.

**Comment by TheBroady** [comment]
> Wir hatten es erst letzte Woche, Undercover ins Unicorn und die Secruity verlangt nen Ausweis und dann wurde halt 3x der Dienstausweis gezeigt (Pole hat es aber gecheckt und es net weiter angespielt) weil man leider nicht den normalen Perso zeigen kann.

Klar, nen Not Workaround gibts immer. "Oh da hab ich mich wohl vergriffen, aber der sollte ja auch reichen". Aber es gibts Situationen wo der gegenüber garnicht wissen sollte das man Cop ist. Ist einfach angenehmer den normalen Perso vorzeigen zu können.

**Comment by KingMarcel** [comment]
Mit dem nächsten Update hinzugefügt.
