### ISSUE TITLE
Zuschauertribünen verkehrt orientiert

### ISSUE THREAD

**Issue by Shksbr** [mexyn/statev_v2_issues#1546]
**Donovan Carter**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

Zuschauertribünen liegen auf der falschen Seite.

**Erwartetes Verhalten**

Zuschauertribünen als platzierbares Item müssten um 90° gekippt werden.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
 https://imgur.com/a/QjO2Lrg

**Comment by DrGrizzlY17** [comment]
Das ist keine Tribüne, das ist eine Markierung für Flugzeuge auf einem Flughafen

**Comment by Shksbr** [comment]
Danke fürs Label. Ich dachte das wären Tribünen. LUL
