### ISSUE TITLE
Visitenkarten werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#1547]
**Character Name**
Marvin_Elpe

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.05.2021 22 Uhr

**Beobachtetes Verhalten**
Wenn man im Inventar eine Visitenkarte hat, kann man diese zwar anklicken und der Mauszeiger wird angezeigt, man sieht die Visitenkarte allerdings nicht. Wenn man dann einmal linksklick macht, geht der Mauszeiger wieder weg (was normal immer zum Visitenkarte weg stecken war, was auch klappt). 

**Erwartetes Verhalten**
Visitenkarten werden angezeigt

**Schritte um den Fehler nachvollziehen zu können**
Visitenkarte anzeigen lassen

**Comment by TheBroady** [comment]
Hängt wahrscheinlich mit den Wartungsarbeiten zusammen.

**Comment by M4rvinLP** [comment]
Ah stimmt, könnte sein.

**Comment by DrGrizzlY17** [comment]
Moin Elpe, die Visitenkarten funktionieren aktuell nicht, da die Dateien auf dem aktuellem Server liegen, der Down ist

**Comment by M4rvinLP** [comment]
Ok. Danke dir
