### ISSUE TITLE
Wohntrailer Lagerplatz

### ISSUE THREAD

**Issue by loelchn** [mexyn/statev_v2_issues#1550]
James_Ackles

James_Ackles
**Auftrittszeitpunkt (Datum / Uhrzeit)**

jederzeit
**Beobachtetes Verhalten**

Mir wurde bestätigt, das Wohntrailer die 2 Tonnen Lagerplatz besitzen, nach Antragstellung eine
Erweiterung bekommen auf 5 Tonnen. Dies wurde bereits schon durchgeführt bei div. Wohntrailer.
Das möchte ich natürlich auch erhalten, da es mir genauso zusteht. 

Ich besitze zwei Wohntrailer mit dem Hash:
1. EveZone3Rew_House_20
2. EveZone3Rew_House_25

**Erwartetes Verhalten**

5 Tonnen, so wie es andere haben.
**Schritte um den Fehler nachvollziehen zu können**

In die Lagerkapazität schauen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

In die Lagerkapazität schauen
**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Würde mich mal interessieren ob du andere Wohntrailer kennst die das haben und von wem dir das versichert wurde

**Comment by loelchn** [comment]
Einem den ich mein Trailer verkauft hat, der hat sich mehrere angeschaut und meinte u.a. werden ihm viele angeboten mit 5T, Name ist gefallen Heinz Heiniken. Ich denke nicht das er mich belogen hat.. deshalb frage ich mich wieso gewisse Leute das hoch gestuft bekommen haben.

**Comment by DrGrizzlY17** [comment]
Die anderen Wohntrailer haben dann andere Wohngröße/Wohnklasse, dementsprechend schließe ich das hier.
