### ISSUE TITLE
Verladepunkte

### ISSUE THREAD

**Issue by scortie1337** [mexyn/statev_v2_issues#1551]
Andrew Pearson
**Character Name**
 Andrew Pearson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit immer

**Beobachtetes Verhalten**
 Die Verladepunkte unserer Firmen befinden sich unter einem Dach. Wenn man nicht ganz genau aufpasst, wie man an das Dach heran fährt, Ist Die Motorkontrolllampe direkt Rot/ Achsen explodieren.

**Erwartetes Verhalten**
 Wenn man die Verladepunkte zusammen tun würde, und ein wenig weiter auf die Straße versetzt, würde das viele unnötige Unfälle/Explosionen verhindern.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![99b4b8348bde1aea9235db4c7e99d0f8](https://user-images.githubusercontent.com/78598179/119259231-8e98cb00-bbcd-11eb-8a8a-1e54f06dbeb5.jpg)
![c2dcc2ee314c6adc599e90452469e7b4](https://user-images.githubusercontent.com/78598179/119259233-935d7f00-bbcd-11eb-8e5f-8338423c1a8e.jpg)
![d39d256e04e4d242d252c706ca6c7111](https://user-images.githubusercontent.com/78598179/119259235-95bfd900-bbcd-11eb-927a-47f52b7263b2.jpg)

**Comment by scortie1337** [comment]
![Uploading 99b4b8348bde1aea9235db4c7e99d0f8.jpg…]()

**Comment by DonVitoDiangelo** [comment]
Bitte die Hashes aller Firmen nachtragen.

**Comment by Enemyaa** [comment]
👍 Next Update!
