### ISSUE TITLE
Torso buggt durch Kleidung

### ISSUE THREAD

**Issue by statevmj** [mexyn/statev_v2_issues#1552]
**Character Name**
Mathew_Jones

**Beobachtetes Verhalten**
Torso buggt durch die Kleidung bzw. Torso ist durchsichtig bei bestimmter Kombination an Kleidung (siehe Screenshots)

**Erwartetes Verhalten**
-  Langarm 4 erweitern, dass der Torso noch etwas tiefer geht
-  Langarm 5 anpassen, damit der Torso nicht durch die Kleidung buggt 
-  Weitere Option einführen, damit die Kleidung getragen werden kann

**Schritte um den Fehler nachvollziehen zu können**
Folgende Kleidungsstücke anziehen und die Langarm Optionen durchtesten:
[M][U] Weißes Hemd, deep v 
[M] Schwarzes Il Fascino Sakko, offen

**Optional: Video / Bilder des Fehlers**
https://i.ibb.co/WKGkV7g/Kombination.png
https://i.ibb.co/Y3bL4WY/Langarm-4.png
https://i.ibb.co/n78fQn6/Langarm-5.png

**Comment by Enemyaa** [comment]
Ich mal rumgeguckt und man kann nicht alle Sakkos dazu tragen. Langarm 5 ist der einzig passende Torso und das Halsproblem liegt am Model selbst und sieht auch weiterhin seltsam aus. 

Ich finde keine weiteren Torsos und ich hab mal in das Update von damals selbst reingeguckt und auch da waren keine extra Torsos mit dabei.

Langarm 5 
Mögliche Sakkos:
[M] Hellbeiges Sakko offen
[M] Dunkelgraues Sakko offen
[M] Blau-Graues Sakko offen
[M] Helllila Sakko offen
[M] Hellgelbes Sakko offen

https://prnt.sc/13bsa6n
