### ISSUE TITLE
Keine nummer

### ISSUE THREAD

**Issue by halloheyleon** [mexyn/statev_v2_issues#1553]
seit neusten kriege ich immer ein anruf von einer nummer die nicht angezeigt wird man kann sie nicht sehen nicht annehmen nicht ablehnen und auch nicht zurückrufen genauso ist sie nicht einzuspeichern 
![Screenshot (21)](https://user-images.githubusercontent.com/76777215/119268148-eea16880-bbf1-11eb-8795-1b3df8e1366e.png)

**Comment by its4l3x** [comment]
Bitte paar Details... Dein IG Namen z.B. ;)

**Comment by KingMarcel** [comment]
Da hier nichts weiter kam, machen wir mal zu.
Gerne ein neuen Bugtracker mit mehr Infos erstellen.

**Comment by JannikDatsch** [comment]
https://discord.com/channels/365251792679862292/411925103048392724/855824179722452992
