### ISSUE TITLE
Dinka Akuma (Race) Blitzer und Tank 

### ISSUE THREAD

**Issue by masmanK** [mexyn/statev_v2_issues#1556]
**Character Name**
Van Blake

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.05.2021 20:05

**Beobachtetes Verhalten**
Obwohl "Race flag" und kein Kennzeichen, wird trotzdem Geblitzt
Tankvolumen beträgt 20L  andere Bikes z.b. Double T haben ein Tankvolumen von 25L 
**Erwartetes Verhalten**
nicht von BLitzer erfasst werden
Tankvolumen anpassen

**Comment by Hutstaender** [comment]
Ja, der Tank ist 20% kleiner, als der von der Double T, allerdings verbraucht sie auch 14% weniger Sprit. Hält sich also die Wage.

An den Kennzeichen können wir leider nichts ändern. Einige Fahrzeuge liefern bei einer Native die wir zur Kennzeichenermittlung nutzen ein TRUE, obwohl das Fahrzeug keines besitzt. Sorry.

**Comment by Hutstaender** [comment]
Ok, vllt kann wegen dem Blitzerthema @its4l3x was machen.

**Comment by masmanK** [comment]
alles klar, wäre mega .
