### ISSUE TITLE
Frisur hat sich einfach verändert. 

### ISSUE THREAD

**Issue by Yuna-Roads** [mexyn/statev_v2_issues#1557]
Yuna Roads

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.05.21/20 Uhr 

**Beobachtetes Verhalten**
Frisur hat sich Random verändert. Hatte vorher die neue Frisur mit dem Ombre verlauf. Wollte dann zum Friseur & das ändern, naja geht nicht, war ja mit meinem Char erst vor kurzem beim Friseur, cool..^^ & mit einer Mütze verstecken geht auch nicht, die Haare buggen aus der Mütze raus. Die Frisur ist so ein unordentlicher Dutt mit 2 langen Strähnchen vorne. 

**Erwartetes Verhalten**
Naja, das die Frisur sich nicht plötzlich ändert ^^ .. & wenn so ein Fehler passiert, wäre es echt nett wenn es mal möglich wäre das zu beheben ohne das man ne Woche damit rumrennen muss :( .. Gibt anscheinend mehrere Fälle davon, hab ich mitbekommen. 

**Schritte um den Fehler nachvollziehen zu können**
Keine Ahnung. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Enemyaa** [comment]
Du kannst im Support anfragen ob dein CD zurückgesetzt werden kann.

**Comment by Yuna-Roads** [comment]
Da habe ich vorhin nachgefragt, sei angeblich nicht möglich & wäre ein Haufen Aufwand ..

**Comment by Enemyaa** [comment]
OK. Vielleicht sind die noch nicht informiert darüber. Gordon hat ihn dir zurückgesetzt!

**Comment by Yuna-Roads** [comment]
Danke für die schnelle Hilfe! :)
