### ISSUE TITLE
Kleidung "sitzt" bei Bewegungen nicht richtig

### ISSUE THREAD

**Issue by Madelaine90** [mexyn/statev_v2_issues#1558]
**Character Name**
Leonie_Honig

**Auftrittszeitpunkt (Datum / Uhrzeit)**
bei Bewegungen, wenn diese Kleiderkombination getragen wird

**Beobachtetes Verhalten**
Für die Kombination "Blaues Slim Shirt, offen" und "Schwarzes Trägertop" gibt es keine passende Kurzarm-Auswahlmöglichkeit. Ärmellos 4 passt zwar auf den ersten Blick, allerdings blitzt da bei bestimmten Bewegungen der Oberkörper durch das Hemd

**Schritte um den Fehler nachvollziehen zu können**
Kleidung anziehen und Bewegungen ausführen

**Optional: Video / Bilder des Fehlers**
![bug2](https://user-images.githubusercontent.com/84710496/119329876-f01c7080-bc85-11eb-98c2-baed00fa0ddf.png)
![bug1](https://user-images.githubusercontent.com/84710496/119329898-f4488e00-bc85-11eb-8630-10d3aebac5f7.png)
![bug](https://user-images.githubusercontent.com/84710496/119330003-0fb39900-bc86-11eb-93b7-06609cd0a658.png)

**Comment by Stiefel911** [comment]
falsche Einstellung, schau mal im Bekleidungmenü, dort ist es einstellbar

**Comment by Madelaine90** [comment]
ich hab alles durchprobiert und nichts gefunden. Entweder der Bauch ist unsichtbar, das Dekolleté, oder die Arme. das einzige das passt ist ärmellos 4, da buggt aber der Oberkörper teilweise durch

**Comment by Stiefel911** [comment]
> ich hab alles durchprobiert und nichts gefunden. Entweder der Bauch ist unsichtbar, das Dekolleté, oder die Arme. das einzige das passt ist ärmellos 4, da buggt aber der Oberkörper teilweise durch

ah okay , hab nichts geschrieben ;)

**Comment by TheMoonicorn** [comment]
Das ist mir auch schon bei anderen Kleidungsstücken aufgelassen, alles was nicht ein normales Shirt ist, hat seine Probleme :(

**Comment by Enemyaa** [comment]
Kann ich nicht so bestätigen @TheMoonicorn Man kann jedes GTA Top mit den Torsos die zur Verfügung stehen fixen.

Das Slim Shirt hat ein neuen Torso. Die hab ich eigentlich für male/female reingestellt. Ich guck nochmal nach, wenn sie bei female noch fehlt, dann kommt sie mit dem nächsten Update!
