### ISSUE TITLE
Unsichtbarer Gegenstand

### ISSUE THREAD

**Issue by xtorox** [mexyn/statev_v2_issues#1559]
**Character Name**

Robin Toro
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer
**Beobachtetes Verhalten**

Bleibt immer hängen an unsichtbaren Gegenstand
Baytree Canyon Road 10b
**Erwartetes Verhalten**

Normalerweise sollte man dort einfach durchlaufen können
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=Ke321__E0IM

**Comment by ArnoZuDemB** [comment]
Da wollte ich Mal mitm Bike durch und es ist komplett kaputt gegangen. Dieses durchsichtige Objekt existiert dort auf jeden Fall seit November letzten Jahres.

**Comment by MisterGarry** [comment]
Da war ich auch schon öfters gewesen klingt nach einen Busch.

**Comment by Enemyaa** [comment]
Da steht halt normalerweise ein riesen Busch https://prnt.sc/13gl711 und den wollte jemand entfernen lassen. Nun ist der Busch zwar optisch weg, aber die Kollision ist zurückgeblieben. Ist halt Geschmackssache was am Ende besser ist.

**Comment by xtorox** [comment]
Am besten wäre es natürlich, wenn die Kollision weg wäre. Sollte das nicht gehen, würde ich den Busch sogar dort mal schöner finden. Ständig dort hängen zu bleiben ohne den Grund zu kennen ist schon etwas komisch.

**Comment by Enemyaa** [comment]
Ok, der Busch wird dann wieder bis zum nächsten Update eingepflanzt sein!
