### ISSUE TITLE
4k Auflösung Problem

### ISSUE THREAD

**Issue by 48619** [mexyn/statev_v2_issues#156]
**Character Name**
John Vernon

**Zeitpunkt (Datum / Uhrzeit)**
Dauerhaft

**Beobachtetes Verhalten**
Wenn man 4k spielt sind die UI´s teils so kleine das man ne Lupe braucht. Inventare, Lagerräume etc kann man so gut wie nicht lesen. Siehe Screenshots unten.

**Erwartetes Verhalten**
Das man es normal lesen kann und man nicht gezwungen ist die Auflösung runter zu drehen.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
3840 x 2160

**Optional: Video / Bilder des Fehlers**
![20200827232627_1](https://user-images.githubusercontent.com/47455680/91639907-335cf200-ea1a-11ea-9b10-2e62a24d74e7.jpg)
![20200827232538_1](https://user-images.githubusercontent.com/47455680/91639908-348e1f00-ea1a-11ea-99c7-d69afeb46d53.jpg)
![20200827232528_1](https://user-images.githubusercontent.com/47455680/91639909-3526b580-ea1a-11ea-91f3-c05d898c459b.jpg)
![20200827232458_1](https://user-images.githubusercontent.com/47455680/91639911-3657e280-ea1a-11ea-9db3-a49fa11c74ed.jpg)
![20200827232425_1](https://user-images.githubusercontent.com/47455680/91639912-36f07900-ea1a-11ea-8c4b-03fea30dc883.jpg)

**Comment by zarazandra** [comment]
Spiele auch auf 4k. Empfand es eigentlich als ok. 🤔

**Comment by r3sist3nt** [comment]
Die meisten Entwickler von uns haben keinen 4k Monitor, deshalb sieht das vermutlich so aus.
Danke für die Screenshots! Das hilft mir sehr weiter.

**Comment by r3sist3nt** [comment]
* Inventar Fixed
* Settingsmenü fixed
