### ISSUE TITLE
Character Beine Bug bei Sagged Bape shorts

### ISSUE THREAD

**Issue by Afrostatev** [mexyn/statev_v2_issues#1560]
**Felix_Bang**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 Seitdem es die Kleidung gibt

**Beobachtetes Verhalten**
 Haut Bug 

**Erwartetes Verhalten**
 Haut Bugt nicht?

**Schritte um den Fehler nachvollziehen zu können**
 Man sieht sich die Hose an und die Haut bugt 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://imgur.com/a/Yh7vZai

**Comment by Enemyaa** [comment]
Ja, ist bekannt. Ist halt nicht so super nice gemodded.
