### ISSUE TITLE
Gamecrash beim rausgehen vom Autohaus...danach keinen Boden sichtbar im Autohaus.

### ISSUE THREAD

**Issue by M4cm4ni4c** [mexyn/statev_v2_issues#1561]
**Character Name**
Ronny_Mcleod

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.05.2021 ca. 19Uhr

**Beobachtetes Verhalten**
Zum gleichen Zeitpunkt wo ich aus dem Autohaus "Luxury Cars" rausging hatte ich einen Gamecrash. Nachdem ich mich wieder eingeloggt habe war ich wieder im autohaus, nur konnte ich keinen Boden sehen

**Erwartetes Verhalten**
Kein Gamecrash oder nachdem man wieder aufwacht nachm gamecrash alles normal sieht.

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/79061254/119540836-2e04bc00-bd8e-11eb-9bf2-0f85a945a7b8.png)
[altv_2.24_EGS_0x62fa2b_25-05-2021_19-00-32.zip](https://github.com/mexyn/statev_v2_issues/files/6541195/altv_2.24_EGS_0x62fa2b_25-05-2021_19-00-32.zip)

**Comment by Enemyaa** [comment]
Das ist aber leider immer so bei einem Gamecrash in einer anderen Dimension. Entweder den Weg nach draußen finden oder kurz in den Support kommen.
