### ISSUE TITLE
Frage: Umbau eines Objekts/Gebäude

### ISSUE THREAD

**Issue by Maddy267** [mexyn/statev_v2_issues#1563]
Ist es möglich bei dem dargestellten Objekt das große Einfahrtstor zu entfernen damit man nicht immer über die Mauer springen muß um was aus dem Auto zu laden. Dies ist erstmal nur eine Frage weil wir dieses Objekt eigentlich Kaufen wollen, es aber mit verschlossenem Tor uninteressant wäre.
https://ibb.co/4VXPK1W
https://ibb.co/khdgKRY

**Comment by Enemyaa** [comment]
Notiz: Man kann das Tor nur optisch entfernen, aber bleiben tut es trotzdem. Deswegen wenn dann ymap!

**Comment by DonVitoDiangelo** [comment]
Eine Bearbeitung wird hier leider nicht erfolgen. (Collision)
