### ISSUE TITLE
Afterhour Tisch weg !!!

### ISSUE THREAD

**Issue by HansKelly** [mexyn/statev_v2_issues#1564]
Hans Kelly

Auftrittszeitpunkt (Datum / Uhrzeit)
26.05.2021 um ca. 13:45

Beobachtetes Verhalten

Ich wollte ein Tisch aufstellen und zwar den Tisch Afterhour Tisch hatte ihm im Rucksack und wo ich ihn aufgestellt hatte war er mit einmal weg komplett ich habe alle sachen nochmals aufgehoben aber der Tisch ist nicht mehr in meiner Tasche zu finden !!!
Erwartetes Verhalten
Naja den Tisch aufstellen und stehe lassen

Schritte um den Fehler nachvollziehen zu können
Afterhour Tisch hatte ihm im Rucksack und wo ich ihn aufgestellt hatte war er mit einmal weg komplett ich habe alle sachen nochmals aufgehoben aber der Tisch ist nicht mehr in meiner Tasche zu finden !!!

**Comment by Enemyaa** [comment]
Hast du den Tisch oberhalb der NSA Base aufgebaut? Sandy Shores oder Richtung Paleto?

**Comment by Enemyaa** [comment]
Dann geh ich mal davon aus, dass es so war. Man kann diesen Tisch jedenfalls nur in LS Ciry und naher Umgebung aufstellen - warum auch immer!
