### ISSUE TITLE
Antrag zur Entfernung eines Objektes

### ISSUE THREAD

**Issue by Chiko-Garcia** [mexyn/statev_v2_issues#1566]
https://pic.statev.de/i/EfhhS.png (Kamera) löschen oder verschieben

#1 Bei mir an der Werkstatt ist seit v2 eine Kamera, die jedes mal dazu führt, dass ein Pounder, sobald ich ihn ausparke, umkippt, da er mit dem Objekt kollidiert. Wenn ich den Pounder wieder einparke, und danach wieder ausparke, funktioniert es, da die Kamera kaputt ist, sieht aber im RP vor Kunden einfach nicht schön aus, wenn jedes mal der Pounder umkippt und auf der Seite liegt.

https://pic.statev.de/i/Efsnm.png (Mülleimer) löschen oder verschieben

#2 Wenn mehrere Spieler gleichzeitig die Werkstatt verlassen, passiert es, dass die Leute am Mülleimer buggen, weil der Gang zu schmal ist. Problem kann nur gelöst werden, indem 1-2 Spieler wieder die Werkstatt betreten.

**Comment by Enemyaa** [comment]
Die kleine Kamera lässt also den Pounder umfallen? Ich denke eher, dass du nicht durch Fremdschaltung beobachtet werden willst. :)

**Comment by Chiko-Garcia** [comment]
häää du kannst es gerne testen und die kamera fält dann ab

**Comment by Chiko-Garcia** [comment]
hier die beweisse als op ich es nötig häte zu lügen

https://gyazo.com/c641a5af162ff9070c0cc1730ef6f6d7
https://gyazo.com/0bc23ada51434635d5e5c07f80593e35
https://gyazo.com/06ca6a6a326b8d451114864dbdf5327e
https://gyazo.com/1d25d40a91fe23f9edd781fca3111490
https://gyazo.com/fdb6f6b4560b59fa049f4c21f4a0b444

**Comment by Chiko-Garcia** [comment]
:)

**Comment by Enemyaa** [comment]
War nur Spaß Chiko alles gut. Bisschen ooc RP. Wir gucken mal...

**Comment by Chiko-Garcia** [comment]
ich weiss aber wollte trotzdem mal die bilder zeigen ^^ wie es dann aus sieht
