### ISSUE TITLE
StateCOM MRPD, LSMJ-Member

### ISSUE THREAD

**Issue by MrGotAB** [mexyn/statev_v2_issues#1567]
**Character Name**

Jason Forelli

**Auftrittszeitpunkt (Datum / Uhrzeit)**

27.05.2021

**Beobachtetes Verhalten**

LSMJ-Mitglieder haben keinen Zugriff auf das StateCOM im MRPD, man kann dieses öffnen und sich einloggen, jedoch keine Akten öffnen oder Personen suchen etc.

**Erwartetes Verhalten**

StateCom sollte auch im MRPD nutzbar sein.

**Schritte um den Fehler nachvollziehen zu können**

Als LSMJ-Mitlglied StateCOM im MRPD öffnen und Person suchen, Akte öffnen etc.

**Comment by DrGrizzlY17** [comment]
Hi, mach mal bitte ein Screenshot wo du versuchst darauf zuzugreifen

**Comment by its4l3x** [comment]
Ist Administrativ nicht gewollt, dass an jedem PC der Zugriff möglich ist. Änderungen stehen derzeit nicht an.
