### ISSUE TITLE
Fehlerhafte Tattoo Anzeige

### ISSUE THREAD

**Issue by Stoffel123** [mexyn/statev_v2_issues#1568]
**Character Name**
Dean_Foster

**Auftrittszeitpunkt (Datum / Uhrzeit)**
aufgefallen am 7.05.2021, aber scheinbar schon länger vorhanden

**Beobachtetes Verhalten**
Mein Char hat auf dem rechten Unterarm ein Dollarzeichen als Tattoo.  Scheinbar bin ich aber die einzige Person die dieses Tattoo sieht.

**Erwartetes Verhalten**
Auch gegenüber sollte es sehen können

**Schritte um den Fehler nachvollziehen zu können**
Dollarzeichen auf den rechten Unterarm stechen lassen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![Tattoo Eigenansicht](https://user-images.githubusercontent.com/77417691/119916083-2139c100-bf64-11eb-86bc-52a0e74748c1.JPG)
![Tattoo Fremdansicht](https://user-images.githubusercontent.com/77417691/119916088-2434b180-bf64-11eb-95a9-806ef06a4aed.png)

**Comment by Enemyaa** [comment]
Ist das noch aktuell und bei jedem Gegenüber oder nur bei einer Person?

**Comment by Stoffel123** [comment]
Ist noch aktuell und bisher bei jedem gegenüber so gewesen den ich gefragt habe ob dort eine gute Tattoostelle ist
