### ISSUE TITLE
Benefactor Krieger lässt sich nicht abschleppen

### ISSUE THREAD

**Issue by Patrick-Snooze** [mexyn/statev_v2_issues#1571]
**Character Name**
Patrick Snooze

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Wenn der Motor rot ist, der Mechaniker war am verzweifeln warum er das Fahrzeug nicht aufladen konnte.

**Beobachtetes Verhalten**
Mit dem Flatbed unmöglich mit dem normalen Abschlepper kein Problem

**Erwartetes Verhalten**
Das man den auf dem Fltbed laden kann.

**Optional: Video / Bilder des Fehlers**
![20210529132028_1](https://user-images.githubusercontent.com/74994851/120068725-74099a80-c082-11eb-8388-31e7bfd0a53c.jpg)

gr33tz

**Comment by TheMoonicorn** [comment]
Brioso 300 kann auch nicht mit dem Flatbed abgeschleppt werden

**Comment by DrGrizzlY17** [comment]
Soweit korrekt und so gewollt. Gibt Probleme mit den Fahrzeugen beim Abschlepper. Kann nur mit nem TowTruck abgeschleppt werden.
