### ISSUE TITLE
Verladepunkt versetzen

### ISSUE THREAD

**Issue by ChrisY2k** [mexyn/statev_v2_issues#1572]
Char Name: John_Vernon

Firmen:

pfJunRockfordHillsRew_86 - Dorset Drive 243

Warum versetzen?

Beim Bild ist der Verladepunkt zu weit im Innenhof so das man mit dem Pounder meist sämtliche Objekte streift und umfährt. Mit nem Phantom + Achse ist es fast unmöglich dort Ladetätigkeiten durch zu führen.

Antrag:

Würde gerne den Ladepunkte zu dem vorhandenen Ladepunkt zusammenführen. Wie auf dem Bild ersichtlich zum rechten Verladepunkt zusammenführen.
![Grand Theft Auto V Screenshot 2021 05 30 - 18 50 18 94](https://user-images.githubusercontent.com/74937202/120113095-36d40400-c179-11eb-98ac-9c9645a111fd.png)

Danke im voraus.

**Comment by Enemyaa** [comment]
👍 Next Update!
