### ISSUE TITLE
Boot Tug - Radius anpassen für Reparaturkasten/Tankkanister

### ISSUE THREAD

**Issue by ZacCooperr** [mexyn/statev_v2_issues#1573]
**Character Name**
Zac_Cooper

**Auftrittszeitpunkt (Datum / Uhrzeit)**
30.05.2021 / 20:40

**Beobachtetes Verhalten**
Das Boot Tug wurde so stark beschädigt, dass es nicht mehr Fahrtüchtig ist. Wie aus dem [https://github.com/mexyn/statev_v2_issues/issues/1533](url) zu entnommen ist, war damals schon die Problematik, dass man keine Tankkanister für das Tug benutzen kann. Ein weiteres Problem besteht nun auch mit dem Reparaturkasten. Meldung: Kein Fahrzeug in der nähe gefunden.

**Erwartetes Verhalten**
Das Boot mit einem Reparaturkasten wieder soweit Fahrtüchtig machen, damit man im Anschluss die Boots Werkstatt anfahren kann.

**Schritte um den Fehler nachvollziehen zu können**
Tug so stark beschädigen( Motorleuchte rot).
Versuchen mit einem Reparaturkasten das Boot zu reparieren(das gleiche gilt auch für einen Tankkanister).
Meldung ercheint: Kein Fahrzeug in der nähe gefunden.

**Optional: Video / Bilder des Fehlers**
![Boot_Kaputt](https://user-images.githubusercontent.com/74767269/120116517-d3ea6900-c188-11eb-8f60-68ec551b317d.JPG)
![Boot_Kaputt1](https://user-images.githubusercontent.com/74767269/120116522-d77df000-c188-11eb-9d1d-78c2bc6b2d93.JPG)

**Comment by Dean-Gallagher** [comment]
Hast du es mal oben in der Fahrerkabine versucht? ich weis noch von früher aus rage Zeiten das man dort sowas machen mußte

**Comment by DonVitoDiangelo** [comment]
Japp, bitte in der Fahrerkabine ausführen.
