### ISSUE TITLE
Ausparkposition Pounder/Fallhöhe andere Fahrzeuge Garage Vinewood West

### ISSUE THREAD

**Issue by CaleighRhodes** [mexyn/statev_v2_issues#1574]
**Character Name**
Caleigh_Rhodes

**Auftrittszeitpunkt (Datum / Uhrzeit)**
immer

**Beobachtetes Verhalten**
Beim Ausparken eines normalen Pounders verkantet sich das Heck an der oberen Mauerkante der Einfahrt ins Parkhaus. Dabei wird das Fahrzeug beschädigt und klappert umgehend.

Beim Ausparken anderer Fahrzeuge fallen diese aus einer bestimmten Höhe, die gefühlt noch zu hoch ist, weil auch andere Fahrzeuge mitunter klappernd ausgeparkt werden (Buffalo jeglichen Typs, Hellion, teilweise auch Brawler).

**Erwartetes Verhalten**
Pounder wird ein kleines Stück weiter vorn ausgeparkt (Achse verklemmt sich bspw. auch nicht), Fahrzeugspawnhöhe - wenn möglich - wird verringert.

**Schritte um den Fehler nachvollziehen zu können**
Entsprechende Fahrzeuge in der Garage ein- und dann wieder ausparken.

**Comment by its4l3x** [comment]
HI, brauche den Garagen-Namen :D

**Comment by CaleighRhodes** [comment]
Steht doch da, Alex. Garage Vinewood West ;)

**Comment by its4l3x** [comment]
Oh Gott. Sorry, habs nicht gesehen 👀

**Comment by Enemyaa** [comment]
👍 Next Update!

**Comment by CaleighRhodes** [comment]
Danke 🙏
