### ISSUE TITLE
Alte Schlüssel funktionieren noch nach Schlosswechsel

### ISSUE THREAD

**Issue by MaximilianKellermann** [mexyn/statev_v2_issues#1575]
**Character Name**
Maximilian Kellermann

**Auftrittszeitpunkt (Datum / Uhrzeit)**
31.05.2021 14:22 war der Schlosswechsel / gegen 14:30 wurde der Fehler festgestellt.

**Beobachtetes Verhalten**
Leider funktionieren die alten Schlüssel noch

**Erwartetes Verhalten**
Die alten Schlüssel sollten nicht mehr funktionieren. Ist bei einer Autovermietung sonst doof.

**Schritte um den Fehler nachvollziehen zu können**
Gute Frage, ich weis nicht in wie weit der Fehler reproduzierbar ist.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
n.a.

**Optional: Video / Bilder des Fehlers**
n.a.

Vielen Dank für eure Zeit. Laut Auskunft der Werkstatt soll ein erneuter Schlosswechsel kein Erfolg bringen. Zitat:"Dann hast du noch mehr Schlüssel die funktionieren" Fzg. wurde natürlich auch mal eingeparkt, damit man das ausschließen kann als Lösung.

**Comment by KingMarcel** [comment]
Hast du die neuen und alten Schlüssel im Inventar gehabt?
Wenn ja nimm die neuen mal raus, dann müssten die alten auch nicht mehr gehen.

**Comment by MaximilianKellermann** [comment]
Danke für den Tipp, das Versuche ich mal später

**Comment by Enemyaa** [comment]
Und hat es geklappt?

**Comment by DonVitoDiangelo** [comment]
Schlüssel wegwerfen. Sind diese zusammen mit den neuen im Inventar, funktionieren Sie noch.
