### ISSUE TITLE
Garagenantrag für mein Haus

### ISSUE THREAD

**Issue by Jake-Fox7** [mexyn/statev_v2_issues#1576]
Ich beantrage einen Stellplatz/ Garagenplatz zu meinem Haus.
Eine Art Carport ist vorhanden (siehe Bild)
Das Haus befindet sich im Mirrorpark
Hausbesitzer: Jake Fox 
Adresse: Westmirror Drive 8 
Haushash: house_Vinewood_8
UND: Ich würde mich sehr freuen, wenn dieses hässliche Sale Schild entfernt wird. 

![Haus 1](https://user-images.githubusercontent.com/85178909/120342692-5180b700-c2f8-11eb-9215-9f2aa3219fa9.png)

**Comment by Enemyaa** [comment]
Das Haus hat leider keine Garage, sondern nur ein Carport, wie du selbst geschrieben hast. 

Das Schild haben seit dem Wechsel zu AltV sehr sehr viele Häuser und die alle einzelnd zu entfernen, führt zu neuen Komplikationen.
