### ISSUE TITLE
Teleporter zum Dach

### ISSUE THREAD

**Issue by DettmarDettmers** [mexyn/statev_v2_issues#1577]
Name: 
Dettmar_Dettmers

Anfrage: 
Zugang zum Dach des Hochhauses. Gab damals schon die "Ansage", dass das auf RageMP nicht mehr gemacht wird und nur eine "Testphase" vom Server für ein paar Objekte war. Jetzt auf AltV gibts aber immer mehr und diese erweitern die Möglichkeiten um so ein Gebäude natürlich immens. 

Das Objekt ist ein Hotel mit mäßig vielen Einheiten, wo es eine schöne Erweiterung wäre, wenn man zusätzlich das Dach betreten könnte. Das ganze Gelände samt Gebäude wird sowieso regelmäßig bespielt. 
Hinten am Hotel gibt es zwei Doppeltüren, wo man eine von sehr gut als Eingang für einen Fahrstuhl nehmen könnte (Bild 2).
Auf dem Dach selber gibt es leider KEINE richtige Tür. Da hier in der Regel aber ja von Fahrstühlen gesprochen wird und es oben mehrere Tür hohe Fenster gibt, wovon eins auch wie eine Art Doppeltür aussieht, nur eben ohne Henkel, würd das doch schon konform aussehen. (Bild 4)

Bilder: 
Gebäude ganz: 
https://pic.statev.de/image/ganzes-haus.Jr15A

Eingang unten: 
https://pic.statev.de/image/eingang.JrqAU

Dachbereich (ein mal komplett um den Turm rum mit großem Platz in den Ecken: 
https://pic.statev.de/image/dachhhh.JrMgy

Ausgang Dach: 
https://pic.statev.de/image/6666666666.Jra12

**Comment by Enemyaa** [comment]
👍 Next Update!
