### ISSUE TITLE
🔥Mein Roller fängt ständig an zu brennen!🔥

### ISSUE THREAD

**Issue by ScooterTina** [mexyn/statev_v2_issues#1580]
Guten Tag, mein Name ist Tina Taube und ich möchte gerne folgende Nachricht an den Hersteller meines **Pegassi Faggio Modern/ 21PS** hinterlassen:

Als ich am 31.05.2021 nach 3 Jahren Urlaub zurück auf die Insel gekommen bin, musste ich mit großem **ENTSETZEN** feststellen, dass mein Roller nun noch sensibler als ich geworden ist. 
Wenn man ihn _versehentlich_ streift, fällt er um und fängt an zu brennen! 🔥🔥🔥🔥🔥🔥 (siehe Anhang)
Die ständig anfallenden Reperaturkosten sind völlig unverhältnismäßig und er ist schon drei Mal plötzlich **explodiert**(!) und musste jedes Mal für 500$ freigekauft werden.

Obwohl er von mir ausgesprochen sorgfältig gepflegt wird, entstehen fortlaufend Schäden. Ich bin quasi Stammgast in allen Werkstätten und mir konnte bisher jeder Mechaniker bestätigen, dass dies nicht mein Verschulden ist. Mir wurde mehrfach geraten (aufgrund der **überzogenen** Sensibilität des Rollers), mein Fahrzeug zu verkaufen. 💔

Ich würde mich riesig über eine Rückmeldung freuen. 
Mit dolle freundlichen Grüßen,

Tina Taube
♥

![fire](https://user-images.githubusercontent.com/85257182/120549331-bf5dd900-c3f3-11eb-8839-23479ccb36cd.jpg)

**Comment by its4l3x** [comment]
Also ich muss mal eine Auszeichnung verleihen:

Das ist der bis jetzt beste Report den wir je hatten XD

**Comment by DonVitoDiangelo** [comment]
Im nächsten Update gefixed
