### ISSUE TITLE
[Bag] Schwarzer Rucksack problem beim Öl fahren

### ISSUE THREAD

**Issue by cadpri** [mexyn/statev_v2_issues#1582]
**Character Name**
Fabian Picard

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Aufgefallen ist es mir am 2.6.2021. Uhrzeit kann ich nicht genau sagen

**Beobachtetes Verhalten**
wenn ich den [Bag] Schwarzer Rucksack aktiv habe und mit dem bearbeiten einer Ölpumpe fertig bin verschwindet der Rucksackinhalt als Inventar.

**Erwartetes Verhalten**
Rucksack bleibt als Inventarfenster immer aktiv

**Schritte um den Fehler nachvollziehen zu können**
[Bag] Schwarzer Rucksack als aktiven Rucksack nehmen und entweder Öl pumpen oder Quarzsand machen.
Fehler ist reproduzierbar. Tritt jedes mal auf.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by cadpri** [comment]
Ich habe das grad mal beim Quarzsand probiert. Dort tritt der Fehler auch auf. Scheint also am Rucksack zu liegen.
Andere Rucksäcke habe ich nicht getestet

**Comment by Humperrrt** [comment]
Kann ich auch von mehreren anderen Rucksäcken bestätigen z.B. die Stylische Umhängetasche

**Comment by DonVitoDiangelo** [comment]
Tritt dieser Fehler bei div. Rucksäcken immer auf oder eher sporadisch?

**Comment by cadpri** [comment]
Der Fehler tritt immer auf

**Comment by Dean-Gallagher** [comment]
Wenn nur das overlay verschwindet, sprich das man was reinschieben kann, links hast du die auswahlmöglichkeit den rucksack wieder einzublenden inform von einer aktentasche :)

**Comment by DonVitoDiangelo** [comment]
Ok, jetzt verstehe ich. Das ist kein Fehler. ÖL und z.B. auch Sand spezielle item Gruppen, die so oder so, nicht im Rucksack gelagert werden können. Am Farmende wird dann immer entsprechend das Fahrzeuginventar angezeigt.
