### ISSUE TITLE
Verladepunkt ändern cypressflats58

### ISSUE THREAD

**Issue by Xaviju89** [mexyn/statev_v2_issues#1583]
**Character Name**

Xavier Martinez

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
schon länger

**Erwartetes Verhalten**

Der Verladepunkt an meiner Firma (cypressflats58) befindet sich an einem Absatz/Schräge wo man sich öfter mit der Hinteren Stoßstange aufhängt. Das sorgt dafür das man öfters einen Abschlepper benötigt der einen von dort runter zeiht. 
**Schritte um den Fehler nachvollziehen zu können**

Wenn man den Verladepunkt auf der großen Fläche vor dem Eingang setzen könnte würde es einfach sein mit dem Pounder oder Phantom dort abzuladen. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

Auf dem Bild sieht man die schräge wo man sich aufhängt. 

https://pic.statev.de/image/20210603194045-1.JAFRP

Hier wo der Sugoi steht würde ich gerne den Verladepunkt haben
 
https://pic.statev.de/image/20210603194033-1.JAjdi

Hier kann man nochmal alter Verladepunkt, neuer Verladepunt und Firmeneingang sehen

https://pic.statev.de/image/20210603194054-1.JAbKt

**Comment by Enemyaa** [comment]
👍 Next Update!
