### ISSUE TITLE
Verbesserungsvorschlag: Geld als Objekt im Inventar

### ISSUE THREAD

**Issue by croveans** [mexyn/statev_v2_issues#1584]
**Character Name**
Marty Taylor

**Auftrittszeitpunkt (Datum / Uhrzeit)**
04.06.2021 / 10:24

**Beobachtetes Verhalten**
Zum heutigen Zeitpunkt ist Geld nur als Eintrag oberhalb des Inventars sichtbar. Geld kann nur verwendet werden, um entweder Bezahlungen durchzuführen (Tankstelle, Werkstatt, 24/7, Tickets etc.) oder um es direkt mit einem Spieler zu handeln.

**Erwartetes Verhalten**
Geld sollte als Objekt im Inventar sein oder es sollte eine Möglichkeit geben, dass man das Geld irgendwo in einem anderen Objekt platzieren kann. Es geht hierbei nicht darum, dass das Geld irgendwie vor dem Notfall MD geschützt wird. Es wäre nur eine tolle RP-Bereichung, wenn man Geld z.B. ohne Anwesenheit eines anderen Spielers übergeben kann (z.B. Mülltonnen, Kofferraum, evtl. sogar Lagerfläche in Wohnungen). So kann man z.B. anonyme Geldübergaben durchführen.

**Schritte um den Fehler nachvollziehen zu können**
-- Kein Bug --

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Wird es nicht geben, sry.

**Comment by croveans** [comment]
@DonVitoDiangelo Glaube mir ist der technische Hintergrund dafür klar, warum ihr dagegen seid.

Kann ich alternativ einen Vorschlag einreichen bzgl. eines Schecksystems, was auf das bestehende Finanzsystem zurückgreift und z.B. gedeckte (Transaktions)konten voraussetzt? Dann wäre der Scheck zum Auszahlen nur eine erweiterte Funktion des bestehenden ATM-Systems, aber dafür kann er auch nur bei gedeckten Konten dafür verwendet werden. Bei dem Vorschlag würde das Bargeldsytem nicht angerührt werden.

**Comment by DonVitoDiangelo** [comment]
Dir steht es frei im Forum gern deine Vorschläge zu posten. Das ist hier auch ein Bugtracker und zum diskutieren von Themen nicht so gut geeignet. Ich persönlich sehe da keinen Vorteil drin zum aktuellen Zeitpunkt, aber wie gesagt, einfach mal im Forum vorschlagen.
