### ISSUE TITLE
Dieselverbrauch Caracara

### ISSUE THREAD

**Issue by SatyriaDine** [mexyn/statev_v2_issues#1586]
**Character Name**

Sofia Black / Ogi Black

**Auftrittszeitpunkt (Datum / Uhrzeit)**

etwa seit dem letzten Update

**Beobachtetes Verhalten**

Der Caracara mit 139PS hat ca seit dem letzten Update einen auffällig höheren Dieselverbrauch als vorher, bei gleicher Kilometerleistung.

**Erwartetes Verhalten**

Geringerer Verbrauch

**Schritte um den Fehler nachvollziehen zu können**

Caracara auftanken und herumfahren

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Hier gab es  keine Änderung.
