### ISSUE TITLE
Nasen Piercing 

### ISSUE THREAD

**Issue by maddin404** [mexyn/statev_v2_issues#1587]
**Character Name**
Eddy Schmitz 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.06.2021 17:49

**Beobachtetes Verhalten**
Die Kundin "Marlise Lovanzic"  hatte bereits ein Nasen Piercing ( Septum) und wollte jetzt noch einen Stecker an der Nase haben. 
Nachdem piercen war dann aber Ihr Septum weg. 

**Erwartetes Verhalten**
Septum und Nostril Stecker sollten an der Nase zu sehen sein. 

**Schritte um den Fehler nachvollziehen zu können**
- Septum piercen  
- verheilen lassen 
- Nostril Stecker piercen

**Comment by Enemyaa** [comment]
Nasenpiercings teilen sich einen gemeinsamen Slot und 2 sind daher leider nicht möglich.

**Comment by maddin404** [comment]
Okay alles klar, wird sich das nochmal ändern oder bleibt es so das nur 1 Nasenpiercing möglich ist?

**Comment by Enemyaa** [comment]
Das wird wohl so bleiben. Es gibt halt nur begrenzt viel Slots und jedem da individuell gerecht werden ist wohl so gut wie unmöglich.

**Comment by maddin404** [comment]
okay danke dann weiß ich da bescheid.
