### ISSUE TITLE
beim tanken der Sanchez kann man nicht mehr aufhören zu tanken

### ISSUE THREAD

**Issue by VereeKaktus** [mexyn/statev_v2_issues#1588]
**Veree_Kaktus**

**Auftrittszeitpunkt 05.06.2021 - 22.45 **

**Beobachtetes Verhalten**

beim betanken der Sanchez kann der Charakter nicht mehr aufhören zu tanken und sollange man den Schlauch in der Hand hat kann man sich natürlich auch nicht bewegen, nach einem Game Neustart kann man die Sanchez nicht mehr wegfahren oder betanken denn "das fahrzeug wird bereits betankt",  hab das Problem jedesmal wen ich versuche die Sanchez zu tanken, ca die letzten 5 mal, an verschiendenen Tankstellen, andere Spieler können meine Sanchez aber problemlos tanken. 

https://user-images.githubusercontent.com/72275879/120905984-1fec5080-c656-11eb-8d65-0b8dc28fe255.mp4

**Erwartetes Verhalten**

Charakter hört auf zu tanken wen der Tank voll ist und kann sich wieder bewegen

**Schritte um den Fehler nachvollziehen zu können**

Sanchez zur Tankstelle fahren und tanken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by ChrisY2k** [comment]
Das ist kein Bug. Du musst darauf achten das die Tankanzeige angezeigt wird ansonsten führt es dazu das du ewig tankst und wenn du reloggst das Fahrzeug nicht bewegen kannst weil es stucked.
