### ISSUE TITLE
Unmöglich zu öffnendes Tor

### ISSUE THREAD

**Issue by Tobistar** [mexyn/statev_v2_issues#1589]
**Character Name**
Tobias_Star

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.06.21 18:34

**Beobachtetes Verhalten**
Das Tor bei der 🔥 SOUTHSIDE FOUNDRY 🔥 - Roy Lowenstein Blvd. 17 in 4017-B geht nicht auf. Es ist ein metallisches Schwingtor, welches sich nicht bewegt. Der Eingang der dahinter befindlichen Firma ist nur über eine Mauer zu erreichen, welche zu erklimmen ist.

**Erwartetes Verhalten**
Das Tor sollte sich öffnen, bei Krafteinwirkung von einer Seite. Oder es sollte einfach nicht mehr da sein, denn ein verschlossenes Tor ist für den Besitzer unnötig, wenn man es nicht öffnen kann.

**Schritte um den Fehler nachvollziehen zu können**
Berühre das Tor und sehe wie nichts passiert.

**Optional: Video / Bilder des Fehlers**
![grafik](https://user-images.githubusercontent.com/85433586/120918494-fd3d5480-c6b4-11eb-9f65-0da9c07f4120.png)
![grafik](https://user-images.githubusercontent.com/85433586/120918519-1fcf6d80-c6b5-11eb-9daa-4aad0ec05e18.png)

**Comment by Statev-Bonsai** [comment]
Genau zu diesem Gebäude gab es erst kürzlich einen Beitrag.. https://github.com/mexyn/statev_v2_issues/issues/1563

**Comment by Enemyaa** [comment]
Das Tor lässt sich weder bewegen, noch kann man es spurlos entfernen - nur optisch. 
In Anbetracht dessen, dass der Marketplace dazu kam und dieser Irrweg auch sinnlos ist, hab ich den Marker nun an das Tor vorne gesetzt. Kommt dann mit dem nächsten Update!
