### ISSUE TITLE
Anhang #13 Bewusstlose Personen ziehen.

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#159]
**Zeitpunkt (Datum / Uhrzeit)**
29.08.2020 / 11:00

Als Nachtrag zu: #13 

Denke das klappt dann auch wie bei #73 

**Beobachtetes Verhalten**
Wenn man eine Person zieht und dann "ö" für Ragdoll drückt und wieder aufsteht, kann man wieder wie vorher mit der Person wild umher rennen.

**Erwartetes Verhalten**
Taste "ö" sollte deaktiviert o.ä sein.

**Schritte um den Fehler nachvollziehen zu können**
1. bewusstlose Person ziehen
2. 2x "ö" drücken zum hinfallen und wieder aufstehen
3. Man kann rennen

**Comment by its4l3x** [comment]
Fixed, next update
