### ISSUE TITLE
Verladepunkt versetzen oder zusammenführen

### ISSUE THREAD

**Issue by M4cm4ni4c** [mexyn/statev_v2_issues#1590]
Firma:
pfGroupAllRew_90 - Ginger St 81

Warum versetzen?
Wie im Bild zu sehen ist, ist es schwer mit dem Pounder auf dem Verladepunkt zu kommen den der Verladepunkt ist zu nahe an den Pollern. Mit achse ist es genauso blöd zum entladen, da man zwischen den pollern aufm Bürgersteig fahren muss.
![image](https://user-images.githubusercontent.com/79061254/121028037-c09e5580-c7a7-11eb-863d-7ac2cd07106b.png)

Ist es möglich diesen Punkt weiterweg von den Pollern zu setzen. Ich hab auch schon gesehen das bei manchen Orten viele Firmen auf einem Punkt be- und ent-laden können vlt ist das auch hier irgendwie als möglichkeit zu sehen.
Möglichkeit 1(Zusammenführung):
![image](https://user-images.githubusercontent.com/79061254/121028685-4de1aa00-c7a8-11eb-99c9-875f3a562c47.png)
Möglichkeit 2(Versetzen):
![image](https://user-images.githubusercontent.com/79061254/121029121-9ef19e00-c7a8-11eb-9e93-7578c28bb48c.png)

**Comment by Enemyaa** [comment]
👍 Variante 1 - Next Update!
