### ISSUE TITLE
Antrag für eine öffentliche Mülltonne

### ISSUE THREAD

**Issue by Chiko-Garcia** [mexyn/statev_v2_issues#1591]
Sehr geehrte Damen und Herren, ich möchte Sie um die Genehmigung einer öffentlichen Mülltonne an unserer Gießerei (PLZ 7006) bitten. Da wir in der Werkstatt nebenan sehr viele Schlosswechsel von sämtlichen Fahrzeugen durchführen, bietet sich eine öffentliche Mülltonne zwischen Gießerei und Werkstatt an. Mülltonnen sind vorhanden, sie sind bloß nicht "öffentlich." Desweiteren hinterlassen die Kunden der Werkstatt außerdem viel Müll. Über eine zeitnahe Rückmeldung würde ich mich sehr freuen.

https://gyazo.com/976dbca8d4e4faa87cd3d47d07d7985e

Chiko Garcia

**Comment by Enemyaa** [comment]
Sehr geehrter Herr Chiko,

mit großer Freude möchte ich sie über den Versand einer Superdeluxe Mülltonne direkt vor ihren Werkstatt Eingang informieren.

**Comment by Chiko-Garcia** [comment]
:) danke schön freu mich schon auf das Superdeluxe Mülltonne
