### ISSUE TITLE
Dinka Marquise Kofferaum 

### ISSUE THREAD

**Issue by Irishman1991** [mexyn/statev_v2_issues#1592]
**Patrick_Okeen**

**07.06.2021 21:58**

**Das Boot Dinka Marquise hat keinen Kofferaum**

**Hinzufügen eines angemessenen Stauraums mit zugang wenn Möglich an der Kajütentür **

**Aufschließen und Kofferaum Suchen**

****

****

**Comment by DonVitoDiangelo** [comment]
next update range erhöht
