### ISSUE TITLE
Unangemeldete Fahrzeuge im StateCom

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1593]
**Erwartetes Verhalten**
Das im StateCom nur Fahrzeuge angezeigt werden welche auch durch die Kennzeichen Zulassungsstelle eingetragen/Zugelassen wurden.

Derzeit werden alle Fahrzeuge, sobald diese auf eine Person geschrieben wurden im StateCom angezeigt.

**Comment by SgtSkipper** [comment]
Soweit ich mich erobern kann ist meine unangemeldet Carbon RS auch nicht im statecom hinterlegt weil sie ein Statev Kennzeichen hat. 

LG Edwards

**Comment by TheBroady** [comment]
nvm ich sehe Fahrzeuge die Kennzeichen haben (aber nicht angemeldet sind) Sind nicht im StateCom sichtbar.
Hingegen Fahrzeuge ohne Kennzeichenhalterrung schon.
Closed
