### ISSUE TITLE
State Forum Anmelde Problem

### ISSUE THREAD

**Issue by ManuelLadner** [mexyn/statev_v2_issues#1594]
**Manuel_Ladner**

**Seit ein paar tagen / Täglich!**

**Captcha lässt sich nicht anklicken! egal ob Handy/Tablet oder PC**

**kein LogIn im Forum möglich!**

**einfaches Anmelden im Forum**

![](https://cdn.discordapp.com/attachments/774951831415685142/852480727328227339/image0.png)

**Comment by Chrinis007** [comment]
Bitte im extra eingerichteten Discord Bereich dafür melden
