### ISSUE TITLE
Haare buggen durch [F] New Era NFL Raiders Snapback

### ISSUE THREAD

**Issue by TamiGaming** [mexyn/statev_v2_issues#1597]
**Character Name**
Carlie Tacus

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11.06.2021 13:36 Uhr

**Beobachtetes Verhalten**
Haare bei weiblicher NFL Raiders Cap buggen durch ([F] New Era NFL Raiders Snapback)

**Erwartetes Verhalten**
Kein buggen der Haare

**Schritte um den Fehler nachvollziehen zu können**
Weibliche NFL Raiders Cap anziehen ([F] New Era NFL Raiders Snapback)

**Optional: Video / Bilder des Fehlers**
![GTA5 2021-06-11 13-36-31](https://user-images.githubusercontent.com/40512639/121699877-a0380900-cacf-11eb-9e01-0f2c364fd39e.png)
![GTA5 2021-06-11 15-17-34](https://user-images.githubusercontent.com/40512639/121699894-a4642680-cacf-11eb-98f9-dba3283ab35d.png)

**Comment by TamiGaming** [comment]
Gleiches gilt für die Fisherman Beanies.
![GTA5 2021-06-11 17-18-08](https://user-images.githubusercontent.com/40512639/121710619-13df1380-cada-11eb-8c63-c984ef72b983.png)

und bei den normalen Flexfit Caps Bw (Schirm nach hinten) schauen an der Seite auch die Haare durch.
Und generell sitzen die Flexfit Caps für Frauen sehr weit von der Stirn weg. Eventuell kann da ja noch ein wenig was angepasst werden.
![GTA5 2021-06-11 17-28-19](https://user-images.githubusercontent.com/40512639/121711048-789a6e00-cada-11eb-83a0-2fec155c8761.png)

**Comment by Enemyaa** [comment]
1. ist gefixt
2. ist nach dem Update nicht mehr verfügbar für Frauen
3. bleibt erstmal so
