### ISSUE TITLE
Double-T wird immer noch geblitzt.

### ISSUE THREAD

**Issue by Koree7** [mexyn/statev_v2_issues#1598]
**Character Name**
Brooks Miller

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16:49 12.06.2021

**Beobachtetes Verhalten**
Double-T wird immer noch geblitzt.

**Erwartetes Verhalten**
Double-T wird nicht mehr geblitzt.

![image](https://user-images.githubusercontent.com/51489673/121779916-405c6380-cb9e-11eb-9339-bf625f0221ff.png)

Siehe Ticket #1539  , eigentlich sollte es behoben sein.

**Comment by its4l3x** [comment]
Einmal reconnecten. Gab ein Fehler mit dem Download

**Comment by Koree7** [comment]
@its4l3x Update geladen, Double T ein- & ausgeparkt und werde immer noch geblitzt

**Comment by its4l3x** [comment]
Ok, dass ist strange. Ich schaue nochmal nach.

**Comment by DrGrizzlY17** [comment]
My bad, ist mit dem nächsten Update dann fixed
