### ISSUE TITLE
Herstellbare Waffenaufsätze

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1599]
Kann es sein das die benötigte Lampenfassung in keiner Firma herstellbar ist?
Wurde es vergessen oder soll es so sein, weiß net ob es ein Bug ist...

**Comment by DonVitoDiangelo** [comment]
find ic raus :)

**Comment by Statev-Bonsai** [comment]
Also kein Bug, das wollte ich nur wissen.. dankeeeeeeeeeeeee :)
