### ISSUE TITLE
[Schneiderei/Kleidungsladen] Produktion stuckt nach Fertigstellung

### ISSUE THREAD

**Issue by statevmj** [mexyn/statev_v2_issues#16]
**Zeitpunkt (Datum / Uhrzeit)**
25.08.2020 / 18:45 Uhr

**Beobachtetes Verhalten**
Nach erfolgreich durchgelaufener Produktion stuckt der PC in dem Produktions UI, man hat keine Möglichkeit ohne den PC zu schließen und neu aufzurufen weiter zu produzieren.

**Erwartetes Verhalten**
Nach Fertigstellung der Produktion weiter produzieren.

**Schritte um den Fehler nachvollziehen zu können**
In einer Schneiderei/in einem Kleidungsladen eine Produktion starten.

**Optional: Video / Bilder des Fehlers**
http://prntscr.com/u5p9u3

**Comment by eiksch** [comment]
Das Verhalten ist so gewollt. Um eine neue Produktion zu starten muss man den Produktionscomputer neu aufmachen.
