### ISSUE TITLE
Goldbarren wiegen 1KG davor 100 Gramm

### ISSUE THREAD

**Issue by Bully90** [mexyn/statev_v2_issues#160]
**Character Name**

Jason Bulls
**Zeitpunkt (Datum / Uhrzeit)**

29.08.2020 / 18.15
**Beobachtetes Verhalten**

Goldbarren wiegen 1KG 
**Erwartetes Verhalten**

Goldbarren wiegt wie auf dem Liveserver 100 Gramm
**Schritte um den Fehler nachvollziehen zu können**

Goldbarren in der Gießerei produzieren
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
so gewollt
