### ISSUE TITLE
Akuma wird noch geblitzt

### ISSUE THREAD

**Issue by masmanK** [mexyn/statev_v2_issues#1600]
**Character Name**
Van Blake
**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.06.2021 17:20
**Beobachtetes Verhalten**
Akuma Race wird trotzdem geblitzt

**Erwartetes Verhalten**
wird nicht mehr geblitzt

**Optional: Video / Bilder des Fehlers**
https://ibb.co/8m9DwXP

**Comment by DonVitoDiangelo** [comment]
next update fixed
