### ISSUE TITLE
Waffe nicht mehr am Holster

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1604]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.06.21

**Beobachtetes Verhalten**
Waffen werden nicht mehr am Holster angezeigt. (Speziell die Taurus hier im Video)

**Erwartetes Verhalten**
Das waffen sichtbar sind

**Schritte um den Fehler nachvollziehen zu können**
Ausrüsten, faust als aktive "waffe" nutzen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/CTsZVTgUyBs

**Comment by DrGrizzlY17** [comment]
It's not a bug, it's a feature

**Comment by DrGrizzlY17** [comment]
Nvm wohl doch nen Bug, aber schon gefixt

**Comment by its4l3x** [comment]
Kein Bug, so gewollt.
