### ISSUE TITLE
Verladepunkt verletzen bei Atlee Street 21 & Atlee Street 115

### ISSUE THREAD

**Issue by AllRounderTim** [mexyn/statev_v2_issues#1605]
**Character Name**
Gert_Ekla

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Bei jedem ab- beladen

**Beobachtetes Verhalten**
Ablade Punkt zu über Bordstein bei Atlee Street 21 & Atlee Street 115

**Erwartetes Verhalten**
Abladepunkt auf Straße versetzen oder beide zusammenführen 

**Schritte um den Fehler nachvollziehen zu können**
Beim ab- beladen, vor allem mit größeren Fahrzeugen, muss man Mülleimer etc umfahren. Abladepunkt ist nur erschwert zu erreichen - bei Atlee Street 21 & Atlee Street 115
Sehr oft wird der Abladepunkt zugeparkt, da dieser direkt hinter einem öffentlich markierten Parkplatz ist - bei Atlee Street 115

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![Atlee Street 21 Ladepunkt umsetzen](https://user-images.githubusercontent.com/85811131/121791462-32343480-cbea-11eb-9464-03828a7cb6ba.PNG)
![Atlee Street 115 Lagerpunkt umsetzen](https://user-images.githubusercontent.com/85811131/121791466-3bbd9c80-cbea-11eb-9cea-72999de7ace6.PNG)

**Comment by DonVitoDiangelo** [comment]
next update changed
