### ISSUE TITLE
Namen der neuen Trailer Komponenten

### ISSUE THREAD

**Issue by Knippsa** [mexyn/statev_v2_issues#1606]
Nur ist aufgefallen dass beim Import für den Trailer Black ein Motor mit 0PS importiert wird. Ggf. nochmal die neuen Trailer-Importe betrachten und schauen, dass Achsen und keine Motoren importiert werden und dementsprechend auch so im Bau-Rezept angegeben sind :)

**Comment by DonVitoDiangelo** [comment]
next update renaming
