### ISSUE TITLE
HVY Mixer (Biff variant) kann nichts beladen werden

### ISSUE THREAD

**Issue by PrimroseBloom** [mexyn/statev_v2_issues#1608]
Primrose Bloom

13.06.2021

Im HVY Mixer (Biff variant) kann nichts verladen werden.
Man bekommt beim Quarzsand angezeigt, dass das nicht das richtige Fahrzeug ist.

Es wäre gut wenn man zumindest Sand verladen kann

![Screenshot (403)](https://user-images.githubusercontent.com/70226823/121817800-cdc5b380-cc83-11eb-9636-abb2e9fa8e2c.png)

**Comment by DonVitoDiangelo** [comment]
next update fixed
