### ISSUE TITLE
[F] New Era NFL Raiders Snapback

### ISSUE THREAD

**Issue by ZirbelR** [mexyn/statev_v2_issues#1609]
**Character Name**
Richie Zirbel

**Auftrittszeitpunkt (Datum / Uhrzeit)**
13.06.2021

**Beobachtetes Verhalten**
Raiders Cap für Frauen ist nicht mehr produzierbar

**Erwartetes Verhalten**
kann produziert werden

**Schritte um den Fehler nachvollziehen zu können**
In der Schneiderei nach [F] New Era NFL Raiders Snapback suchen

**Comment by Enemyaa** [comment]
Next Update!
