### ISSUE TITLE
Sirene und Blaulicht beim Tippen ins Tablet/StateCom (PD Fahrzeuge)

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#161]
**Character Name**

Jannik Datsch

**Zeitpunkt (Datum / Uhrzeit)**

30.08 07:20

**Beobachtetes Verhalten**

Wenn man, während man im Streifenwagen sitzt, im Tablet/StateCom schreibt, schaltet man Sirene und Blaulicht an und aus. 

**Erwartetes Verhalten**

Blaulicht/Sirene sollten unverändert bleiben.

**Schritte um den Fehler nachvollziehen zu können**

Ins Auto setzen -> Im Tablet/StateCom schreiben

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by eiksch** [comment]
fixed

**Comment by JannikDatsch** [comment]
Ist aktuell wieder so wie oben beschrieben, Tippen aktiviert wieder Sirene usw.
