### ISSUE TITLE
Produktion Bug & Skill Zurücksetzung

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#1610]
**Character Name**

Ryan_Valdes

**Auftrittszeitpunkt (Datum / Uhrzeit)**

14.06.2021   13:20Uhr

**Beobachtetes Verhalten**

Produktion Endet nicht zeit läuft weiter obwohl 100% 

**Erwartetes Verhalten**

100% Produktionsende

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://user-images.githubusercontent.com/70231715/121886174-65271700-cd15-11eb-988f-3e5deb76f754.mp4

Nach dem Server Restart geht es zwar wieder aber mein Skill wurde zurückgesetzt 

![image](https://user-images.githubusercontent.com/70231715/121908567-6c5a1f00-cd2d-11eb-8013-a499ff0ffc9f.png)

Skill war bei Bonus 2.50% & Reduzierung auf 90 % Danke an Alex für die Hilfe

**Comment by PlayInc89** [comment]
Nach Server Restart geht dann der Produktionscomputer wieder !

**Comment by PlayInc89** [comment]
Ich hoffe man kann mich wieder auf den alten Stand setzten.

**Comment by DonVitoDiangelo** [comment]
Das Problem hatte sich durch Restart behoben?

**Comment by PlayInc89** [comment]
Nach dem Restart konnte ich zumindest wieder Klamotten Produzieren.
