### ISSUE TITLE
Kleidungsmenü verwendbar während Behandlung durch LSMD

### ISSUE THREAD

**Issue by AngelMaravilla** [mexyn/statev_v2_issues#1611]
**Character Name**
Angel Maravilla

**Auftrittszeitpunkt (Datum / Uhrzeit)**
13.06.2021

**Beobachtetes Verhalten**
Nicht 100% sicher ob gewollt/nicht gewollt. Falls es ein Bug bei mir war, alles cool. Wenn nicht, dann siehe hier:

Solange man sich nach Bewusstlosigkeit in Behandlung durch Medics befindet (auf der Trage, im Krankenbett) und noch nicht "entlassen" wurde, kann man das Kleidungsmenü (Komma) nicht öffnen. Dies verhindert technisch, dass man den Anweisungen der Medics nicht wirklich nachkommen kann, wenn man sich freimachen soll oder die Kopfbedeckung/Brille zur Behandlung abnehmen soll.

**Erwartetes Verhalten**
Das Kleidungsmenü (Komma) ist uneingeschränkt verwendbar während man durch das LSMD behandelt wird.
(Ggf. auch das normale Inventar, hatte aber da noch keine Situationen, wo ich das direkt gebraucht hätte. Dieses kann man zwar öffnen aber nichts per Rechtsklick aktivieren oder auswählen)

**Schritte um den Fehler nachvollziehen zu können**
Von Medics aus der Bewusstlosigkeit geholt werden und dann auf der Trage oder im Krankenbett liegen bevor man entlassen wird.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Bekommen wir sicherlich eingerichtet :)

**Comment by its4l3x** [comment]
fixed next update
