### ISSUE TITLE
Feuerwerksbatterie nicht auf Dach platzierbar

### ISSUE THREAD

**Issue by Playfor25** [mexyn/statev_v2_issues#1612]
**Max_Rosen*

**13.06.2021 gegen 22 Uhr**

**Beobachtetes Verhalten**
Feuerwerksbatterie nicht auf Dach platzierbar

**Optional: Video / Bilder des Fehlers**
https://youtu.be/ZVU00d2EeHI

**Comment by DonVitoDiangelo** [comment]
Auf den Boden stellen :)
