### ISSUE TITLE
Cliffhanger nimmt bei der kleinsten Berührung Schaden

### ISSUE THREAD

**Issue by thumbsucker** [mexyn/statev_v2_issues#1613]
**Character Name**
Riley Everett

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14.06.2021 23:30 Uhr

**Beobachtetes Verhalten**
Ähnlich wie die Faggio zuvor geht die neu hinzugefügte Cliffhanger bei der kleinsten Berührung kaputt und fängt an zu qualmen bzw. brennen. Man läuft dagegen, sie fällt um und ist kaputt... Man läuft dran vorbei, es platzen Lichter und sie ist kaputt etc. 

**Erwartetes Verhalten**
Das Motorrad sollte genau wie andere nicht bei jeder kleinen Berührung eine gelbe oder sogar rote Kontrollleuchte bekommen.

**Schritte um den Fehler nachvollziehen zu können**
Is denke ich schon beschrieben aber ja, mal näher am Motorrad entlang gehen und es sollte zur folge haben, dass es umkippt und recht ein gelbe Kontrollleuchte bekommt.

**Comment by DonVitoDiangelo** [comment]
Sollte dann ab nächsten Update besser werden.

**Comment by thumbsucker** [comment]
Das Motorrad ist leider nach wie vor sehr empfindlich
