### ISSUE TITLE
Brioso 300 kann nicht auf Flatbed verladen werden / Neue Fahrzeuge brauchen keine Dosen Schwarzer Lack

### ISSUE THREAD

**Issue by ChrisY2k** [mexyn/statev_v2_issues#1614]
Wollten einen Brioso 300 überführen mit einem Flatbed aber leider gibt es dafür keine Abschleppfunktion.

Ich weis nicht wie es bei den anderen neuen Fahrzeugen ist da müsste vielleicht auch geprüft werden ob es da eine Abschleppfunktion für den Flatbed gibt.

Desweiteren brauchen alle neuen Fahrzeuge die in den Import gekommen sind keine Dosen Schwarzer Lack mehr. 
Vielleicht da auch nochmal drüber schauen und ggf. nachjustieren.

![Grand Theft Auto V Screenshot 2021 06 14 - 01 10 46 26](https://user-images.githubusercontent.com/74937202/122086203-c62d1880-ce03-11eb-82f4-aeb881a879ae.png)
![Grand Theft Auto V Screenshot 2021 06 14 - 01 10 54 55](https://user-images.githubusercontent.com/74937202/122086219-ca593600-ce03-11eb-9362-88a844e01c08.png)

**Comment by Patrick-Snooze** [comment]
Das mit dem abschleppen ist bekannt, gibt wohl aktuell mit den neuen Fahrzeugen Probleme...

https://github.com/mexyn/statev_v2_issues/issues/1571#issuecomment-854217773

**Comment by DonVitoDiangelo** [comment]
Korrekt, bitte mit einem Abschlepper abschleppen.
