### ISSUE TITLE
Ammunation - Waffenkisten Falsche Transportgruppe!

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1615]
Man kann keine Waffenkisten für AK-47, Mini Uzi, MP5 usw mehr in die Theke legen.
Fehlermeldung: Falsche Transportgruppe

Das betrifft auch die HK416 Munition, bei anderen Munitionsarten gibt es keine Probleme.

![Screenshot_36](https://user-images.githubusercontent.com/70241137/122131126-fe028300-ce38-11eb-842b-ce9f610221ed.jpg)

**Comment by callmerusty** [comment]
Generell kann man keine Langwaffen mehr in die Theke legen:

Mossberg 590A1 AOW
--
Mini Uzi
HK MP5
--
AK-47
AKMSU
HK416
QBZ-95B

**Comment by Statev-Bonsai** [comment]
mit dem nächsten update @DonVitoDiangelo ? :)

**Comment by DonVitoDiangelo** [comment]
jupp
