### ISSUE TITLE
Western Deathbike geht kaputt wenn man gegen läuft

### ISSUE THREAD

**Issue by LautaroTesto** [mexyn/statev_v2_issues#1616]
Lautaro Testo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.06.2021 12:40Uhr

**Beobachtetes Verhalten**
Wenn man gegen Western Deathbike gegenläuft wird der Motor Gelb oder sogar Rot

**Erwartetes Verhalten**
Es nicht kaputt geht, wenn man gegen läuft

**Schritte um den Fehler nachvollziehen zu können**
 Char rennt > läuft gegen Western Deathbike > Deathbike kaputt

**Comment by DonVitoDiangelo** [comment]
Das Bike ist schon in einer entsprechenden Config eingetragen. Mehr können wir da nicht machen.
