### ISSUE TITLE
[F] Mit Nike Schuhe größer

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1617]
**Character Name**
Max Broady / Emilia Porter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.06.2021

**Beobachtetes Verhalten**
Emilia Porter ist mit Nike Schuhen immer ein stück größer, da sie in der Luft schwebt.
Sobald sie diese neu anzieht, ist der Bug behoben aber tritt kurz darauf wieder auf.
Ist nur für andere Sichtbar, sie selbst sieht es nicht so
Getragen werden hier die [F] Weiße Nike Air Max Thea 

**Erwartetes Verhalten**
Man ist normal Groß

**Schritte um den Fehler nachvollziehen zu können**
Nicht bekannt

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Größen Unterschied:
![image](https://user-images.githubusercontent.com/70150887/122262222-7ae33a80-ced5-11eb-9a86-c50e024867c0.png)

hier fliegt sie
![image](https://user-images.githubusercontent.com/70150887/122262229-7d459480-ced5-11eb-926b-ab5145d322f7.png)

**Comment by TheBroady** [comment]
Information:
Scheint bisher nur bei Emilia Porter aufzutreten.

**Comment by Enemyaa** [comment]
Ich trag die Sneaker auch ic und viele Leute um mich herum. Ich hab das weder ic bis jetzt gesehen, noch kann ich es nachstellen auf dem Dev. Deswegen können wir da auch leider nichts groß ändern.

**Comment by TheBroady** [comment]
Bislang ist der Fehler auch nur bei ihr aufgetreten.
Allerdings immer nur dann wenn sie die Nike Schuhe trägt und sie bsp vor dem Hotel steht, und man selbst dann aus dem Hotel kommt und ihr Charakter geladen wird.
