### ISSUE TITLE
Inventarfensters des Rucksacks verschwindet aus Item-Menü

### ISSUE THREAD

**Issue by ThomFly** [mexyn/statev_v2_issues#1619]
Tom_Knight

Tom_Knight

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.06.2021 
Uhrzeit kann ich leider nicht mehr genau sagen, wusste bis grade nicht, dass man eine genaue Uhrzeit angeben muss.
Würde aber irgendwann zwischen 18-20 Uhr schätzen

**Beobachtetes Verhalten**
Habe aktuell das Problem, dass das Inventarfenster meines Rucksacks (40kg) verschwindet, hauptsächlich dann, wenn ich vom Auto etwas ins Lager der Gießerei einlager oder eben von der Produktion dieser ins Lager.
Der Rucksack ist weiterhin optisch und auch im Inventar (im Slot unten links) am Charakter.
Um das Problem zu beheben muss ich den Rucksack kurz ins Auto oder in ein Lager/Schrank packen und wieder anziehen, dann erscheint das Inventarfenster auch wieder im Menü.
Das Spiel selber denkt ebenfalls, dass ich den Rucksack nicht an habe, da es Gegenstände (bei Shift+Linksklick) in die Hosentasche stecken will.

Vergisst man, dass der Rucksack "weg" ist (und die eigenen Hosentasche zu voll ist) und man hat grade weder Lager/Schrank noch Auto in der Nähe, muss man eben erst zu einem gehen.

**Erwartetes Verhalten**
Inventarfenster des Rucksacks bleibt im Menü sichtbar

**Schritte um den Fehler nachvollziehen zu können**
oben beschrieben

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**

**Comment by CaleighRhodes** [comment]
Mal das Rucksacksymbol hier angeklickt, wenn du vor der Firma stehst? Es wird nämlich immer erstmal nur dein Hosentascheninventar, daneben das Autoinventar und daneben das Lagerinventar gezeigt. Du musst den Rucksack erst per Klick "aktivieren". Gleiches gilt bei Maschinen.

![Inkedorangen_LI](https://user-images.githubusercontent.com/74977218/122384938-7e75d080-cf6c-11eb-9ef6-dc0bb83dc959.jpg)
