### ISSUE TITLE
Anfrage - Verbrauch bzw. Spritart - Bison / Kamacho

### ISSUE THREAD

**Issue by Knippsa** [mexyn/statev_v2_issues#1620]
**Character Name**
Kalle Knutsen

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Kamacho und Bison sind im Gegensatz zu allen anderen bekannten PickUps Benziner. Das macht Sie natürlich unattraktiver und deutlich teurer. Dass Pickups Benziner sind finde ich gar nicht so vekrehrt. Der Bison aber z.B. verbraucht dazu unglaubliche 1,4l/km. Ein Pounder zum Vergleich 1,7l/km ist aber auch Diesel und hat 3x mehr Platz. (Beide Werte gemessen auf dem Central Highway mit Navi auf 5km)

**Erwartetes Verhalten**
Anpassung vom Verbrauch und/oder Spritart der beiden Pickups um auch die Unterhaltskosten auf ein gleichwertiges Level zu Anderen ähnlichen KFZs zu setzen.

**Comment by DonVitoDiangelo** [comment]
Ist gut so wie es ist, da werden wir nichts ändern. Die Configs wurden alle zu v2 überarbeitet. Ich habe auch gerade noch einmal geprüft und kann dort keine Unregelmäßigkeit feststellen.  Und das z.B. ein Kamacho unattraktiv sei, bei dieser Meinung scheiden sich dann wohl die Geister. Aber wie gesagt, soweit alles i.O. und es wird dort keine Änderung geben.
