### ISSUE TITLE
2 Rusty Rebel Produzierbar

### ISSUE THREAD

**Issue by ProgrammingFox** [mexyn/statev_v2_issues#1621]
**Beobachtetes Verhalten**
Es können aktuell 2 Rusty Rebels gefertigt werden. Ein "Karin Rusty Rebel" und ein "Karin Rusty Rebel & Rebel".

**Erwartetes Verhalten**
Da ich den "Karin Rusty Rebel" besitze, würde ich vermuten, dass der "Karin Rusty Rebel & Rebel" der neue "Karin Rebel" aus dem Changelog ist. Der Motor müsste dazu auch noch umbeannt werden.

**Optional: Video / Bilder des Fehlers**

![grafik](https://user-images.githubusercontent.com/48456305/122454274-7ee18c00-cfab-11eb-9583-4715faab2b73.png)

**Comment by DonVitoDiangelo** [comment]
next update fixed
