### ISSUE TITLE
Boot einparken schwierig

### ISSUE THREAD

**Issue by Stiefel911** [mexyn/statev_v2_issues#1622]
Hi,

jedesmal ist es leider sehr schwierig das Boot bei der Bootswerkstatt nähe Kaffeeinsel einzuparken.
Sobald der Punkt unter Wasser ist, verschwindet er und es muß gewartet werden bis er sich wieder zeigt!
Selbst wenn man trotzdem richtig steht.

https://youtu.be/t0ZAvi-G9Co

genau in der letzten sec. kam dann auch das Symbol wieder ;)

So long

**Comment by DonVitoDiangelo** [comment]
next update fixed
