### ISSUE TITLE
Garagenpunkt / Müll in der Einfahrt 

### ISSUE THREAD

**Issue by CaleighRhodes** [mexyn/statev_v2_issues#1623]
**Character Name**
Caleigh_Rhodes

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Betrifft mein Grundstück Procopio Drive 17, Postal 936, Paleto Bay. Wenn Fahrzeuge serverseitig eingeparkt werden, spawnen sie nach dem Ausparken zu Teilen im Garagentor. Das verursacht auch Schaden (beim Burrito war bspw. das Hecklicht kaputt).

![20210618162448_1](https://user-images.githubusercontent.com/74977218/122578704-71341100-d054-11eb-8965-3b92c728833f.jpg)

Vor der Einfahrt stehen zwei Mülltonnen und drei Pappkartons. Die Pappkartons touchiert man meist, wenn man auf das Gelände fährt. Offenbar verursachen auch diese Schaden, da mir beim nächsten Ausparken des besagten Fahrzeuges auch Lichter geplatzt sind (ohne vorherigen Unfall). Deshalb wäre es schön, wenn diese entfernt werden könnten. Die Mülltonnen können gerne stehen bleiben.

![20210618163329_1](https://user-images.githubusercontent.com/74977218/122578728-76915b80-d054-11eb-8d8d-310246297167.jpg)

**Erwartetes Verhalten**
Bitte den Einparkpunkt bzw. den Punkt, auf den die Fahrzeuge ausgeparkt werden, etwas weiter vor verlegen. Entweder zur Steinkante oder da hin, wo ich gerade stehe:

![20210618163317_1](https://user-images.githubusercontent.com/74977218/122578052-c9b6de80-d053-11eb-9110-4a2b46ebbf23.jpg)

Bitte, wenn möglich, die Pappkartons entfernen.

Danke!

**Comment by DonVitoDiangelo** [comment]
next update changed

**Comment by CaleighRhodes** [comment]
Danke für die Erfüllung meiner Wünsche! <3
