### ISSUE TITLE
Stuhl vor dem Haus fällt immer um

### ISSUE THREAD

**Issue by cadpri** [mexyn/statev_v2_issues#1624]
Fabian Picard
Haus Route 68 / SandyShores40

Vor meinem Haus befinden sich von GTA selbst 2 Stühle und ein Tisch. Mit beiden Stühlen kann ich interagieren.
Einer der beiden Stühle ist aber umgefallen. 
Wäre es vielleicht machbar diesen zu entfernen und durch einen anderen zu ersetzen der nicht umgefallen ist ?

https://pic.statev.de/i/f69Qs.jpg

**Comment by DonVitoDiangelo** [comment]
Wir werden diese Props nicht befestigen. Wenn überhaupt, kann dir angeboten werden, diese zu entfernen, wenn möglich.
Dann musst du deine eigenen hinstellen.

**Comment by cadpri** [comment]
Ich meine nicht befestigen.
Ich meine den umgefallenen entfernen und durch einen ersetzen der nicht umgefallen ist sondern normal steht

**Comment by DonVitoDiangelo** [comment]
stuhl wird entfernt mit dem nächsten update
