### ISSUE TITLE
MTL Packer fährt sich fest am nördlichen Wasserfeld in Paleto Bay

### ISSUE THREAD

**Issue by cadpri** [mexyn/statev_v2_issues#1625]
**Character Name**
Fabian Picard

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.06.2021 17 Uhr circa

**Beobachtetes Verhalten**
Ich habe oben in Paleto Bay dreckiges Wasser gepumpt. Auf dem Stück zum Strand runter wurde ja vom Team die Rampe gebaut um an den Strand runter zu fahren. Diese ist aber so spitz, dass der MTL Packer dort aufsetzt und feststeckt, wenn man mit der nötigen Vorsicht über diese Brücke fährt.

**Erwartetes Verhalten**
Wäre es vielleicht machbar diese Brücke etwas umzugestalten, dass ein festfahren nicht mehr so einfach möglich ist ?

**Schritte um den Fehler nachvollziehen zu können**
Langsam mit dem MTL Packer über diese selbstgebaute Brücke fahren

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/i/f6e3t.jpg

**Comment by CaleighRhodes** [comment]
Ist mir mit dem Phantom auch schon passiert, da musste mit Geschwindigkeit rüber :/

**Comment by cadpri** [comment]
über diese klapprige Brücke mit Speed drüber ist meiner Meinung nach nicht so ne gute Idee ;)

**Comment by CaleighRhodes** [comment]
Ist aber die einzige Möglichkeit, nicht hängen zu bleiben. Ungünstig gemacht, aber wenn man so argumentiert, müsstest du die Punkte am Strand eh auslassen, weil welcher LKW mit Flüssigkeitsachse würde nicht auf dem Sand stecken bleiben?

ich umgehe das Problem ganz anders: ich fahre Wasser nur am Staudamm

**Comment by cadpri** [comment]
Der Staudamm geht leider mit dem Packer nicht

**Comment by DonVitoDiangelo** [comment]
Es ist, wie es ist. :)
