### ISSUE TITLE
Canis Mesa (offroad) nur Felgen und Scheiben "tunebar"? 

### ISSUE THREAD

**Issue by kaeiveh** [mexyn/statev_v2_issues#1626]
**Character Name**
Caleb Bradley

**Auftrittszeitpunkt (Datum / Uhrzeit)**

20.06.2021
**Beobachtetes Verhalten**

Beim Canis Mesa (Offroad) kann man nur Scheibentönung und Felgen ändern
**Erwartetes Verhalten**

Mehrere dinge tunebar? Stoßstange, Überrollkäfig uvm.?

**Schritte um den Fehler nachvollziehen zu können**

Canis Mesa Offroad in die Werkstatt fahren und versuchen zu tunen (?)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
jap, leider nicht mehr möglich
