### ISSUE TITLE
Bitte um Verschiebung des Abladepunkts für #pfJunAltaRew_10

### ISSUE THREAD

**Issue by Guoliver405** [mexyn/statev_v2_issues#1627]
**Character Name: Kalle_Grabowski**

**Auftrittszeitpunkt (Datum / Uhrzeit):permanent**

**Beobachtetes Verhalten: Es handelt sich (wie bereits im Titel vorweggenommen) nicht um einen Fehler, sondern betrifft ausschließlich die Bitte, den Abladepunkt für meine Firma #pfJunAltaRew_10 geringfügig zu verlegen. Derzeit liegt der Abladepunkt auf einem ausgewiesenen Parkplatz an der anliegenden Straße (siehe beigefügtes Bild). Da direkt neben der Firma ein Friseurgeschäft ist, welches von einem größerem Team betrieben wird, sind die Parkplätze leider oft belegt. Zwar handelt es sich bei den Betreibern des Friseurgeschäfts um nette Leute, die auch sehr hilfsbereit die Fahrzeuge beiseite fahren, die derzeitige Positionierung des Abladepunkts macht es jedoch bei Anlieferung mit einem LKW erforderlich, immer gleich die ganze Parkreihe (4-5 Fahrzeuge) zu verlegen (vgl. Abbildung). Das ist auf Dauer für mich sowie die netten Nachbarn des Friseursalons und deren Kunden recht nervig und stört darüberhinaus auch regelmäßig das RP beim Friseur. Meine Bitte wäre dementsprechend, den Abladepunkt knapp hinter die Parkreihe (vgl. grüne Markierung in der Abbildung) zu verschieben. So könnte dann das Be- und Entladen in wenigen Sekunden aus zweiter Reihe erfolgen. Die Breite der anliegenden Hawick Avenue gibt das aus meiner Sicht problemlos her. Ich würde mich freuen. Vielen Dank im Voraus - euer Kalle.**

**Erwartetes Verhalten: entfällt - kein Fehler**

**Schritte um den Fehler nachvollziehen zu können: entfällt - kein Fehler**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI): entfällt - kein UI-Problem**

**Optional: Video / Bilder des Fehlers: 
![Abladepunkt_pfJunAltaRew_10](https://user-images.githubusercontent.com/86207996/122689621-6203bd80-d224-11eb-8297-94edd47b9908.jpg)
**

**Comment by DonVitoDiangelo** [comment]
changed next update
