### ISSUE TITLE
nicht definierte Sitzbänke im Tequi-La-La 

### ISSUE THREAD

**Issue by Valaray** [mexyn/statev_v2_issues#163]
**Character Name**
Valaray_Youth

**Zeitpunkt (Datum / Uhrzeit)**
jederzeit

**Beobachtetes Verhalten**
das betätigen der Y-Taste ruft keine Sitzfunktion an den Bänken links UND rechts von der Bühne auf.

**Erwartetes Verhalten**
es öffnet sich das Sitzmenü

**Schritte um den Fehler nachvollziehen zu können**
vor die Sitzbank treten, Y drücken 

[https://drive.google.com/file/d/1bVXxuZZt7QBbuRpqzdPhm2MfH1fNJnpI/view?usp=sharing](url)

**Comment by DrGrizzlY17** [comment]
done
