### ISSUE TITLE
Rechtschreibfehler rund um Lifeinvader

### ISSUE THREAD

**Issue by ZeSchleicher** [mexyn/statev_v2_issues#1630]
**Character Name**
Wilhelm Schleicher

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Dauerhaft

**Beobachtetes Verhalten**
Lifeinvader wird auf der Startseite des Tablets falsch geschrieben. Nervt mich als Lektor IC ungemein. :D
Falsche Schreibweise: LifeInvader

Der Spind bei Lifeinvader ist ebenfalls falsch geschrieben.
Falsche Schreibweise: Spint

**Erwartetes Verhalten**
Richtige Schreibweise: Lifeinvader
Richtige Schreibweise: Spind

**Optional: Video / Bilder des Fehlers**
![Fehler](https://user-images.githubusercontent.com/86252255/122798283-b0ff3080-d2c0-11eb-9c91-912998811874.PNG)
![Fehler2](https://user-images.githubusercontent.com/86252255/122798507-f7548f80-d2c0-11eb-9caa-2aa28486369d.PNG)

**Comment by its4l3x** [comment]
Am 2.7 fixed.

**Comment by ZeSchleicher** [comment]
Sorry, dass ich die Person sein muss, aber der Spind ist immer noch falsch geschrieben.

Falsch: Spint
Richtig: Spind

**Comment by its4l3x** [comment]
Jo das ist korrekt, die Änderung kommt erst später Online, gegen 16.7/17.7.

Die Änderung liegt zusammen mit den Änderungen für das kommende alt:V am 16.7/17.7.
