### ISSUE TITLE
Schalldämpfer verschwindet wenn das Inventar voll ist

### ISSUE THREAD

**Issue by masterppc** [mexyn/statev_v2_issues#1631]
**Character Name**

Hans Hentschel
**Auftrittszeitpunkt (Datum / Uhrzeit)**

21.06.21 18:05
**Beobachtetes Verhalten**

Ich wollte den Schalldämpfer von meiner Waffe machen und meine Taschen waren voll. Es wurde mir angezeigt das die Taschen voll sind aber der Schalldämpfer ist trotzdem weg
**Erwartetes Verhalten**

Fehlermeldung das Taschen voll sind und man kann den dann nicht abmachen
**Schritte um den Fehler nachvollziehen zu können**

Volles Inventar und versuchen das Item in die Tasche zu ziehen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

-
**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=qpKQYTjdrRs

€: Außerdem konnte ich nach diesen Bug die Waffe nicht mehr ausrüsten. Erst ein Relog behob das Problem.

**Comment by its4l3x** [comment]
fixed next update
