### ISSUE TITLE
Vinewood West Garage bugged

### ISSUE THREAD

**Issue by Knippsa** [mexyn/statev_v2_issues#1632]
**Character Name**
Kalle Knutsen

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Beim Ausparken

**Beobachtetes Verhalten**
Seit dem letzten Update spawnen die Fahrzeuge irgendwie "härter". Das bestätigt auch, dass de Fahrzeuge seitdem immer wieder Schaden nehmen und eine gelbe Kontrollleuchte haben. Das geht allmählich ins Geld :P

**Erwartetes Verhalten**
Sanftes Ausparken ohne Schaden

**Comment by Enemyaa** [comment]
Also ich hab mit dem letzten Update genau das geändert, weil genau das immer zum Problem stand, dass die Autos 1. fallen und 2. dadurch manchmal Schaden nehmen. 
Nun fallen sie gar nicht mehr und werden sanft ausgeparkt. Das irrritiert mich halt total, denn ich hab die Garagenpunkte selbst getestet. 
Wo genau hast du denn das Problem und mit welchem Fahrzeug?

**Comment by Knippsa** [comment]
Roosevelt Valor (immer)
Bravado Bison (alle paar Male)

Denke es ist einfach ein Tick zu niedrig.

**Comment by DonVitoDiangelo** [comment]
Was heißt härter @Knippsa ? Hast du mal ein kleines Video?

**Comment by Knippsa** [comment]
Here we go: https://youtu.be/6ub8PtU257c

**Comment by CaleighRhodes** [comment]
Hm, Ich hatte ja vor einer Weile darum gebeten, dass sie niedriger spawnen, weil sonst immer alle Buffalo-Typen und mein Carbonizarre und der Drafter kaputt gegangen sind.

**Comment by Enemyaa** [comment]
Ich teste das nochmal mit deinem Auto Knippsa, aber eigentlich sollten die jetzt gar nicht mehr aufschlagen und sanft ausparken, so war auch mein Test gerade an dieser Garage.

**Comment by DonVitoDiangelo** [comment]
nochmal minimal höher gesetzt den spawn, sollte dann next update ok sein.
