### ISSUE TITLE
Fehlende Blockade

### ISSUE THREAD

**Issue by Weddn** [mexyn/statev_v2_issues#1633]
**Character Name**
Laveda_Clark

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.06.2021 / 17:50 Uhr

**Beobachtetes Verhalten**
Keine Blockade hinter der Tür, man kann einfach durch die Welt fallen.

**Erwartetes Verhalten**
Nicht durchfallen können/Tür verschlossen

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=Qe_tChEKqiM

**Comment by DonVitoDiangelo** [comment]
gta related, werden wir nicht fixen
