### ISSUE TITLE
BF400 geht weit zu schnell kaputt

### ISSUE THREAD

**Issue by CCastles22** [mexyn/statev_v2_issues#1634]
**Charaktername**
Hons Klescheneder

**Beobachtetes Verhalten**
Hab mit dem Bike leicht ne Mauer gestreift , bei vorher weisser Motorleuchte , danach instant rot
Kam mir schon komisch vor....
Danach in Werkstatt wieder repariert der Mechaniker hat das Bike wieder ausgeparkt ich wollt aufsteigen dann ist das gerade reparierte Bike im Stand umgefallen und wieder Motorlampe instant auf rot!

**Erwartetes Verhalten**
Naja sollte schon deutlich mehr aushalten das Teil

VG

**Comment by DonVitoDiangelo** [comment]
next updat efixed
