### ISSUE TITLE
Garage hinzufügen

### ISSUE THREAD

**Issue by WalDragoner3425** [mexyn/statev_v2_issues#1636]
**Auftrittszeitpunkt**
Immer

**Anliegen**
Schönen guten Tag, ich wollte mal nachfragen, ob es eventuell möglich wäre, bei dem Haus (Haushash: house_EastLS_15) eine Garage hinzuzufügen?

Und zwar befindet sich ja zur Zeit in dieser Straße das Zuhause der Vagos, welche ebenfalls das beschriebene Haus besitzen. Das Problem ist, dass es zu Stoßzeiten dann halt oft dazu kommt, dass dort massenhaft Autos rumstehen, da die öffentliche Garage ein gutes Stück entfernt ist und wir oft schnell unsere Fahrzeuge brauchen. Durch die ganzen Fahrzeuge kommt es jedoch regelmäßig zu Problemen mit Kopfschmerzen und es zerstört auch ein wenig die Optik, wenn dort alles zugestellt ist. Aus diesem Grund wollte ich mal fragen, ob wir eine Garage für das beschriebene Haus bekommen könnten, damit wir ein paar Fahrzeuge dort einparken können. Das würde uns wirklich sehr helfen. Das Haus besitzt sogar einen kleinen Anbau auf der rechten Seite (siehe Bild_1), welchen man als Garage nutzen könnte oder man nutzt eine der vielen freistehenden Garagen rechts neben dem Haus (siehe Bild_2) als Garage für das Haus.

MfG William

Bild 1: https://ibb.co/NFPrk34
Bild 2: https://ibb.co/zrcGFB2

**Comment by Stiefel911** [comment]
Du wirst es nicht glauben, aber auf dem ersten Bild dieses ist die Garage vom Haus. :-D ;)

**Comment by WalDragoner3425** [comment]
Ja ich weiß, aber nicht nutzbar ¯\_(ツ)_/¯

**Comment by DonVitoDiangelo** [comment]
next update neue öffentliche garage  murrieta
