### ISSUE TITLE
Antrag auf öffentliche Garage

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#1637]
Character Name:
Santito Quintero

Da im Mirror Park mittlerweile wieder mehr los ist und teilweise sehr viele Autos geparkt sind kommt es hier und da immer mal wieder zu Disconnects. Und da es im Mirror Park selbst keine öffentliche Garage gibt würde ich gerne eine beantragen. 

Das wäre so die beste Stelle von der Parkfläche her. Da hätten auch Zugmaschinen Platz ausgeparkt zu werden. 
![20210624214739_1](https://user-images.githubusercontent.com/16436981/123327183-6e488d00-d53a-11eb-840d-124de52aa209.jpg)

**Comment by DonVitoDiangelo** [comment]
direkt unten bei der Brücke wurde vor nicht zu langer Zeit, eine Garage eingeführt. Oben am Casino steht auch eine.

**Comment by epichalt** [comment]
@DonVitoDiangelo 
Ich habe es abgemessen, es sind genau 566m zwischen der Casino Garage und dem Punkt den ich ausgesucht hatte. 

https://github.com/mexyn/statev_v2_issues/issues/1565

Hier wurde auch eine Garage beantragt und es sind witzigerweise ebenfalls genau 566M zwischen der Garage und der Casino Garage. 
Zudem hat/hätte die Werkstatt die Möglichkeit die Fahrzeuge im Fahrstuhl zu "parken". 

Daher meine Frage wieso diese Garage abgelehnt wird und andere anstandslos genehmigt werden unter den eigentlich gleichen Voraussetzungen?

**Comment by epichalt** [comment]
Dass da am Casino eine Garage ist, ist mir bewusst. Schließlich muss da jeden tag 5x hin rennen und fahre zusätzlich 10-12x am Tag noch dort hin nur um Autos zu wechseln weil ich darauf bedacht bin, dass zusätzlich zu den Fahrzeugen im Mirror Park nicht noch mehr Autos dort rumstehen. 
Gestern haben beim Friseur gegenüber 25 Autos geparkt und die Person mit der ich unterwegs war ist direkt 2x aus dem Game geflogen. 

Daher bitte ich nochmal die Entscheidung zu überdenken. Dieser Garagenpunkt befindet sich ziemlich mittig von den zwei anderen Garagen und wäre eine deutliche Erleichterung im Bezug auf das tägliche hin und her rennen und auch für die Fahrzeugproblematik im Mirror Park.

**Comment by kingrobttv** [comment]
Eine Garage in dem Bereich wäre für viele von Vorteil. Besucher vom Friseur und Firmenbesitzer könnten ihre Fahrzeuge dort parken, sodass der Spielfluss nicht durch Game Crashs beeinflusst wird.

**Comment by LanabobanaTTV** [comment]
Das kann ich auch nur unterschreiben. Bin teilweise am Tag sehr lang damit beschäftigt, zwischen Casino und Firma hin und her zu switchen, nur um Fahrzeuge zu holen/wechseln. Wurde im Stream auch schon mal darauf angesprochen, warum ich denn die ganze Zeit hin und her laufen muss. 
Zudem sind die disconnects durch das Leben im Mirror Park halt leider wirklich aufgefallen in letzter Zeit. Viele würden von so einer Garage profitieren.  
Wäre schön, wenn es dazu nochmal eine Rückmeldung gäbe. Liebe Grüße

**Comment by Koray5858** [comment]
@epichalt dann sollte man aber nicht seinen eigenen Firmen Hinterhof dafür vorschlagen(der meistens mit Fahrzeugen von Vortec voll steht), sondern den am Mirror Park bereits vorhandenen Parkplatz in der nähe der Werkstatt den man Perfekt dafür nutzen könnte

**Comment by epichalt** [comment]
@Koray5858 Firmen Hinterhof? Ich weiß nicht was du versuchst hier gerade zu sagen, aber das ist ein öffentlicher Parkplatz, welcher viel von den umliegenden Gebäuden und Häusern genutzt wird weil der Parkplatz gegenüber hier und da für gelbe Motoren sorgt durch den Zaun bzw. das Tor. 
Neben der Werkstatt würde eine Garage ebenfalls passen und wäre ich auch dafür. Aber dafür könntest du auch deinen eigenen Eintrag eröffnen, wenn du dort eine haben möchtest. :)
