### ISSUE TITLE
Anzeigefehler Mieten-Hotel

### ISSUE THREAD

**Issue by Auralein** [mexyn/statev_v2_issues#1638]
Clara Young

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.06.2021 um 10:22

**Beobachtetes Verhalten**
Wenn ich von einem Hotel auf Wohnungen schaue und dann direkt auf die Wohnungen eines anderen Hotels wechsel übernimmt er im Tablet die Mieten der vorherigen Wohnungen.

**Erwartetes Verhalten**
Das er die tatsächlichen Mieten des aktuellen Hotels anzeigt

**Schritte um den Fehler nachvollziehen zu können**
Im tablet beide Hotels aufgeklappt haben und dann von Tab Wohnungen auf das Tab Wohnungen des anderen Hotels wechseln

**Optional: Video / Bilder des Fehlers**

https://gyazo.com/f91bdd8c5903585e3a407b452c03de96

https://gyazo.com/942e8ed9c49f580896ee9e223b2290bf

**Comment by epichalt** [comment]
Denke das ist die selbe Problematik wie wenn man von den Finanzkonten bei Firmen hin und her wechselt. Da werden dann ebenfalls die Konten der vorherigen Firma angezeigt. Man darf dann nicht von Finanzen auf Finanzen klicken, sondern muss einen Zwischenstopp und einen anderen Reiter anklicken

**Comment by TheOutburst** [comment]
Wir werden uns sämtliche Hotelbugs mit StateNET 2.0 annehmen #942
