### ISSUE TITLE
Visierhalterung hat kein Icon

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1639]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.06.21

**Beobachtetes Verhalten**
Visierhalterung hat im Inventar kein Icon

**Erwartetes Verhalten**
Das es wie andere Items ein Icon hat

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/70150887/123394831-d8dfe400-d59f-11eb-9c91-39eb7dbe9c95.png)

**Comment by DonVitoDiangelo** [comment]
next update fixed
