### ISSUE TITLE
Tequi-La-La unschön platziertes Anlehnen außerhalb des Clubs

### ISSUE THREAD

**Issue by Valaray** [mexyn/statev_v2_issues#164]
**Character Name**
Valaray_Youth

**Zeitpunkt (Datum / Uhrzeit)**
jederzeit

**Beobachtetes Verhalten**
das Y-Menü ruft "anlehnen" auf. Beim drücken dieser Funktion teleportiert sich der Charakter nach draußen an die Außenwand vom Tequi-La-La und lehnt sich an den dort stehenden Mülleimer an.

**Erwartetes Verhalten**
Sitzmenü öffnet sich

**Schritte um den Fehler nachvollziehen zu können**
an die Sitzbank (wenn man zur Bühne schaut LINKS) herantreten, Y drücken und "anlehnen" klicken

**Comment by its4l3x** [comment]
Nicht so schnell immer, langsam, ruhig. Erst wenn dein Char mit den Augen in diese Richtung schaut, dann wird auch das richtige Menu aufgerufen. Daher invalid
