### ISSUE TITLE
Abgeschleppte Fahrzeuge setzen sich zurück

### ISSUE THREAD

**Issue by AngelMaravilla** [mexyn/statev_v2_issues#1641]
**Character Name**
Angel Maravilla

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.06.2021, 17:05 Uhr

**Beobachtetes Verhalten**
An der Kreuzung direkt am Ammunation beim Würfelpark ist dieser Fall bereits zum zweiten Mal aufgetreten: Ein leeres Fahrzeug, welches (vermutlich durch einen game crash) die Kreuzung blockiert, wurde von einem Abschlepper mit Haken von der Kreuzung entfernt. Nach einiger Zeit, wenn man aus der render distance raus war, steht das Fahrzeug dann wie von Zauberhand aber wieder dort wo es vorher war. Wie viel Zeit genau dazwischen vergeht ist nicht klar. Es _kann_ sein, dass es vielleicht mit dem 16:00 Uhr Restart zusammenhängt und das Fahrzeug wieder an der Position ist, wo es zuletzt gesynced wurde und nicht dort, wo der Abschlepper es hingezogen hat. Kurioserweise passierte dies zwei Mal an der selben Stelle mit ein paar Tagen Abstand.

**Erwartetes Verhalten**
Fahrzeuge bleiben an der Stelle, wo sie abgeschleppt wurden.

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug von der Kreuzung am Ammunation WP abschleppen und dann etwas Zeit verstreichen lassen. Wie lang genau ist nicht bekannt. Dann landet das Fahrzeug wieder dort. Wir haben es nicht gezielt getestet aber es ist zwei Mal aufgetreten.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by statevmj** [comment]
Ich beobachte seit einigen Tagen ein alten Bug, der zum Start von V2 bereits da war. Fahrzeuge teleportieren sich an eine Stelle zurück, wo sie zuvor mal standen. Mir ist das persönlich jetzt schon 3x in den letzten 3 Tagen passiert und 1x hat ein Pounder ein Abladepunkt blockiert, der zuvor etwas bei mir verkauft hatte - ca. 2 Std. vorher. Dieser Bug war zwischenzeitlich mal behoben bzw. kam nur noch äußerst selten vor. Seit dem vorletzten bzw. letzten Patch tritt dieses Problem wieder deutlich häufiger auf, was man auch am Stadtbild an sich erkennt, da viel mehr Autos an Stellen rumstehen, wo man sie nicht vermuten wurde - bspw. mitten auf der Straße.

**Comment by JulianMa** [comment]
Siehe #400
