### ISSUE TITLE
Magazin Bug 

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#1642]
**Character Name**

Sven Rosenbach
**Auftrittszeitpunkt (Datum / Uhrzeit)**

27.06.21 11:25
**Beobachtetes Verhalten**

Nachdem man eine Taurus/AK47 leer geschossen hat und man sie ins Inventar packt hat man wieder ein Magazin mit einer Kugel.
**Erwartetes Verhalten**

Kein Magazin bekommen beim wegstecken
**Schritte um den Fehler nachvollziehen zu können**

Waffe leer schießen und dann ins Inventar packen.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

2560x1440
**Optional: Video / Bilder des Fehlers**

AK: https://streamable.com/6b70qx
Taurus: https://streamable.com/mlojcx

**Comment by Chrinis007** [comment]
Duplikat von #715
Sollte bereits Gefixed sein
