### ISSUE TITLE
Rumpo Custom Kofferraum kleiner geworden

### ISSUE THREAD

**Issue by cadpri** [mexyn/statev_v2_issues#1643]
**Character Name**
Fabian Picard

**Auftrittszeitpunkt (Datum / Uhrzeit)**
immer

**Beobachtetes Verhalten**
Mein Rumpo Custom hat nur noch ein Kofferraumvolumen von 250kg. Früher waren es 300kg und im Wiki steht auch, dass er 300kg hat.

**Erwartetes Verhalten**
Ändern des Kofferraum auf die ursprüngliche Größe von 300kg

**Schritte um den Fehler nachvollziehen zu können**
Kofferraum aufmachen und i drücken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
Egal bei welcher auflösung

**Comment by DonVitoDiangelo** [comment]
Die Kofferraumgrößen, wurden bei einer Anpassung vor über einem Jahr geändert.. Diese bleiben auch so bestehen
