### ISSUE TITLE
Trailer BG sackt vorne ab und macht ein erneutes anhängen an eine Zugmaschine fast unmöglich

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#1644]
**Character Name**
Santito Quintero

**Auftrittszeitpunkt (Datum / Uhrzeit)**
dauerhaft

**Beobachtetes Verhalten**
Neuer Achse "Trailer BG" sackt vorne ab, falls man den "Kofferraum" öffnet und wieder schließt. Daraus ergibt sich keine Möglichkeit mehr den Trailer aufzusatteln an die Zugmaschine. Erst durch Ein und Ausparken lässt sich das wieder beheben. 
Hier ein Clip der es zeigt was ich in etwa meine. 
https://clips.twitch.tv/SuspiciousCharmingPieFloof-rocmxb0g_DvoNd85

Hier noch ein Bild der Problematik 
![20210627190206_1](https://user-images.githubusercontent.com/16436981/123553672-eef6cb80-d77c-11eb-8264-e7e5f288bc18.jpg)

**Comment by Hutstaender** [comment]
Jo, war ne Fehlkommunikation. Sorry. Der Trailer sollte eigentlich nie rein kommen. Der wird mit dem nächsten Update durch den richtigen ausgetauscht.
