### ISSUE TITLE
"For sale" Schild entfernen und Mülltonne versetzen bei house_EastLS_31

### ISSUE THREAD

**Issue by PlayerJosephine** [mexyn/statev_v2_issues#1645]
**Charaktername**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Bene-RonnyMoritz** [comment]
Beispielbilder wären nicht verkehrt denke ich^^

**Comment by DonVitoDiangelo** [comment]
also bei dem Schild kann ich schonmal sagen, das da die Kollision vorhanden bleiben würde

**Comment by DonVitoDiangelo** [comment]
Wird keine Änderung vorgenommen
