### ISSUE TITLE
Hauler kippt beim Ausparken

### ISSUE THREAD

**Issue by DasMang** [mexyn/statev_v2_issues#1646]
**Earl_Sinclair**

**Beim Ausparken**

**Der Hauler spawnt beim Ausparken nicht gerade und kippt um. Es ist bisher 2 mal nicht auf die Räder sondern komplett auf die linke Seite gekippt.**

**Schulung des Parkwächters**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**https://youtu.be/tPfMUtODQy0
   https://youtu.be/-mGkRVxgREY**

**Comment by PlayInc89** [comment]
Jop kann ich so bestätigen
