### ISSUE TITLE
Fehlende Kollisionsbox Palomino AVE. 84

### ISSUE THREAD

**Issue by Xymena** [mexyn/statev_v2_issues#1649]
**Character Name**
Anna_Luna

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.07.2021  17:00

**Beobachtetes Verhalten**
Beim Laufen gegen einer Tür / Wand ist diese nicht vorhanden und du betrittst das das Gebäude in der  keine Textur vorhanden ist. Du stürzt anschließend durch die welt 

**Erwartetes Verhalten**
Beim laufen gegen die Wand kommt eine Kollision und es ist nicht möglich das Gebäude zu "betreten"

**Schritte um den Fehler nachvollziehen zu können**
Du läufst die treppe runter, und kannst die tür des unteren Apartment durch die Wand betreten. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
Nutze NVE.

**Optional: Video / Bilder des Fehlers**
![20210701170833_1](https://user-images.githubusercontent.com/76626768/124148361-de519880-da8f-11eb-8332-7a4bf03fab7d.jpg)
![20210701170906_1](https://user-images.githubusercontent.com/76626768/124148376-e0b3f280-da8f-11eb-93c6-75ee94aa1a53.jpg)

**Comment by DonVitoDiangelo** [comment]
gta related, werden wir nicht fixen
