### ISSUE TITLE
Handwerker Lehrgang levelt nicht obwohl in der Fertigung produziert wird

### ISSUE THREAD

**Issue by Bully90** [mexyn/statev_v2_issues#165]
**Character Name**

Jason Bulls
**Zeitpunkt (Datum / Uhrzeit)**

30.08.20/10.30
**Beobachtetes Verhalten**

Handwerker Lehrgang bekommt keinen fortschritt beim produzieren in der Fertigung
**Erwartetes Verhalten**

Der Lehrgang sollte beim produzieren in der Fertigung fortschritt bekommen
**Schritte um den Fehler nachvollziehen zu können**

Produzieren in der Fertigung mit erlernten Skill Handwerker
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

Lehrgang erlernen und Produktion in der Fertigung anstellen
**Optional: Video / Bilder des Fehlers**

**Comment by eiksch** [comment]
fixed
