### ISSUE TITLE
Verlegung Be-Entladepunkt

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#1650]
**Character Name**
Dean Gallagher

**Firmenhash**
 lamessa40

**Erwartetes Verhalten**
Be-Entladepunkt weiter nach vorne verlegen damit der Laufweg nicht so lang ist. 
Im gelben Kreis ist der Türmarker und im roten der Be-Entladepunkt dazu. Der Phantom dient zur Darstellung wie weit der Punkt entfernt ist am besten wäre der Punkt auf höhe der Tür.  

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/i/fibyn.jpg

Danke euch :)

**Comment by DonVitoDiangelo** [comment]
changed next update
