### ISSUE TITLE
Verlegen von Be-/Entladepunkt, Türmarker

### ISSUE THREAD

**Issue by WoahJeesus** [mexyn/statev_v2_issues#1651]
**Character Name**
Jonny Parkinson

**Firmenhash**
pfSamsonLSRew_2

**Erwartetes Verhalten**

Der Be-/Entladepunkt befindet sich zu nah am Objekt, sodass bei größeren Fahrzeugen Ladetätigkeiten unmöglich sind.
Es würde schon reichen, wenn der Verladepunkt auf die Position des Türmarkers verlegt wird.
Außerdem befindet sich der Türmarker frei in der Einfahrt und nicht an der vorgesehenen Tür.

**Optional: Video / Bilder des Fehlers**

![alt_V Multiplayer 15 06 2021 18_33_16](https://user-images.githubusercontent.com/70155401/124170320-92125280-daa7-11eb-9282-418c280645d5.png)

Danke im Voraus! ^^

**Comment by DonVitoDiangelo** [comment]
changed next update
