### ISSUE TITLE
Fehlender Sound beim Aufbrechen einer Tür?

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1652]
Warum gibts da keinen Sound ähnlich wie beim Klopfen an der Mine o. ä.? Ergibt irgendwie keinen Sinn.  Wenn es schon die Mgl. gibt mittlerweile jede Tür aufzubrechen (was auch daran liegt, dass in LS halt nicht 4000000 sondern 400 Leute leben) dann sollte es zumindest einen Sound geben, dass man das noch irgendwie mitkriegen kann.

**Comment by DonVitoDiangelo** [comment]
Wird es vorerst nicht geben, vllt. später.
