### ISSUE TITLE
Fehler Tablet

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1653]
Wenn man IC das Tablett bedient und gleichzeitig die STRG Taste drückt dann schließt sich das Spiel und das Tablett wechselt in den Fullsreen...
Edit: aber anscheinend ist das nicht immer so....

![Screenshot_2](https://user-images.githubusercontent.com/70241137/124274514-a60a9280-db41-11eb-94be-466ae082ee1a.jpg)

**Comment by Chrinis007** [comment]
Duplikat von #68
