### ISSUE TITLE
Double-T wird immer noch geblitzt Teil 3

### ISSUE THREAD

**Issue by Koree7** [mexyn/statev_v2_issues#1654]
**Character Name**
Brooks_Miller

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.07.2021 18:30

**Beobachtetes Verhalten**
Double-T wird immer noch geblitzt.

**Erwartetes Verhalten**
Double-T wird nicht mehr geblitzt.

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/51489673/124304588-335ede80-db64-11eb-8457-5f09bb6ee8a5.png)

Siehe #1598

**Comment by its4l3x** [comment]
So hab das System nochmal umgebaut. Sollte jetzt dann mit dem nächsten Update fixed sein. :)
