### ISSUE TITLE
Neue Handbewegungen im Animationsmenü falsch

### ISSUE THREAD

**Issue by SgtSkipper** [mexyn/statev_v2_issues#1655]
**James Edwards**

James Edwards
**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://prnt.sc/1827fx9

**Comment by Chrinis007** [comment]
Bereits im Discord kommuniziert worden. Lt. Hutstaender fixed next update :D
