### ISSUE TITLE
Karin Rusty Rebel Bezeichnung

### ISSUE THREAD

**Issue by ProgrammingFox** [mexyn/statev_v2_issues#1656]
Referenz zum Orginal: #1621 

Anscheinend wurde der "Karin Rusty Rebel" jetzt in "Karin Rebel" umbenannt (siehe Bild), was aber nicht nötig war. Es sollte eigentlich, zumindest in der Produktion als auch der Motor, der "Karin Rusty Rebel & Rebel" in "Karin Rebel" abgeändert werden, da dort der Name falsch war und es sich nur um den "Karin Rebel", der mit dem großen Fahrzeugupdate neulich eingeführt wurde, handelte.
![grafik](https://user-images.githubusercontent.com/48456305/124305798-d95f1880-db65-11eb-9f67-bad4e3798b47.png)

**Comment by DonVitoDiangelo** [comment]
Hat sich nen Fehler eingeschlichen, Rebel (Rusty Rebel) - rebel2 (Rebel). next update fixed
