### ISSUE TITLE
Neue Animationen nicht korrekt benannt und fehlerhaft

### ISSUE THREAD

**Issue by Mr-Chris-VRTY** [mexyn/statev_v2_issues#1657]
**Character Name**
Chris Schubert

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.07.2021 19:10 Uhr

**Beobachtetes Verhalten**
Beide Animationen sind unbenannt und die zweite funktioniert gar nicht (zumindest macht der Char nichts)

**Erwartetes Verhalten**
korrekt Bennenung + beide Animationen funktionieren

**Schritte um den Fehler nachvollziehen zu können**
Animationsmenü öffnen -> Handbewegungen

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/70213538/124309340-dc103c80-db6a-11eb-96c2-880324ced61b.png)

**Comment by Chrinis007** [comment]
Duplikat von #1655
