### ISSUE TITLE
Lebensanzeige beim Boxen

### ISSUE THREAD

**Issue by NeedManu** [mexyn/statev_v2_issues#1658]
Martin_Henks

02.07.2021 19:45 Uhr

Man verliert DEUTLICH weniger Leben durch einen Schlag

Normaler Schaden wie gewohnt

Jemand anderes schlagen / geschlagen werden

![Lebensanzeige](https://user-images.githubusercontent.com/81923141/124311894-bc7b1300-db6e-11eb-8dd9-e9eb046edb07.png)

Das ist die Lebensanzeige nach 2 Schlägen

**Comment by DonVitoDiangelo** [comment]
Japp, so gewollt, da hier div. Schaden angepasst wurde. :)
