### ISSUE TITLE
ungültiges Ziel Inventar Tranfer am Haus 

### ISSUE THREAD

**Issue by Valaray** [mexyn/statev_v2_issues#166]
**Character Name**
Valaray_Youth

**Zeitpunkt (Datum / Uhrzeit)**
jederzeit

**Beobachtetes Verhalten**
Inventar-transfer ausschließlich vom eigenen Tascheninventar in das Haus (und andersrum) transferierbar jedoch nicht vom Inventar in Fahrzeug oder Haus ins Fahrzeug oder Fahrzeug ins Haus oder Haus ins Inventar. 
Fehlermeldung oberhalb der Mini-Map "Ungültiges Ziel" 

**Erwartetes Verhalten**
Transfer von Fahrzeug ins Haus, 
Transfer von Haus ins Fahrzeug

**Schritte um den Fehler nachvollziehen zu können**
Parke das Auto auf dem Garagenpunkt am Haus. 
Gehe an die Haustür und drücke E
Drücke auf "Inventar Transfer" 
Verschiebe die Gegenstände von Fahrzeug ins Haus 
Verschiebe die Gegenstände von Haus ins Fahrzeug

**Comment by its4l3x** [comment]
Fixed, next Update. In Zukunft muss btw. der Kofferraum nun immer Offen sein, bekommst nun auch eine Meldung wenn dies nicht der Fall ist.
