### ISSUE TITLE
Ammunation...

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1660]
Ist es richtig das die normale Colt + Muni auch nicht mehr im Ammunation verkauft werden kann?
Genauso sieht es mit den Schrotflinten aus, diese sind auch importierbar...
Ist etwas sinnfrei da man diese auch importieren kann...

![Screenshot_8](https://user-images.githubusercontent.com/70241137/124349717-f7be2600-dbf0-11eb-9961-8fd1d5fa9c00.jpg)

**Comment by Statev-Bonsai** [comment]
![Screenshot_12](https://user-images.githubusercontent.com/70241137/124367297-42be5480-dc56-11eb-9e32-eb998974d695.jpg)

Importierbar aber nicht im Ammonation verkaufbar...

**Comment by DonVitoDiangelo** [comment]
Jap, so gewollt. Wir dann zum nächsten Update aus dem Import entfernt und anderweitig zur Verfügung stehen.
