### ISSUE TITLE
Änderung Abladepunkt

### ISSUE THREAD

**Issue by JonnyHart** [mexyn/statev_v2_issues#1661]
**Character Name**
Jonny Hart

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Rund um die Uhr

Bitte den Abladepunkt anhand der Skizze versetzen. Wir möchten die Parkplätze als Mitarbeiter Parkplätze nutzen.

Danke und weiter so ....
![asdsadsd](https://user-images.githubusercontent.com/78865364/124351542-4a9cdb00-dbfb-11eb-810c-03ff6375abca.png)

**Comment by JonnyHart** [comment]
Firmenhash: **davis26**

**Comment by DonVitoDiangelo** [comment]
next update changed
