### ISSUE TITLE
Graues Paisley Bandana (Maske)

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1662]
**Character Name**
Max Broady

**Erwartetes Verhalten**
Wäre es möglich das Graue Paisley Bandana hinzuzufügen?
Das Graue fehlt leider noch. Blau, Rot & Lila wurden bereits hinzugefügt.

**Comment by Enemyaa** [comment]
Ist bereits auf dem Server verfügbar!

**Comment by TheBroady** [comment]
> Ist bereits auf dem Server verfügbar!

Ich danke dir! :)
