### ISSUE TITLE
Habe mein Sofa gegessen :/

### ISSUE THREAD

**Issue by JosefStark** [mexyn/statev_v2_issues#1663]
**Character Name**
Josef_Stark
**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.07.2021 ca.12:45 - 13:00 Uhr
**Beobachtetes Verhalten**
Habe ein Bundy Sofa im 24/7 gekauft und wollte es vor dem Shop aufstellen, rechte Maus angeklickt dann war es weg und ich meinte Essensgeräusche zu vernehmen(könnten aber auch von einem der zwei Gamer neben mir gekommen sein), jedoch ohne Animation, die Sättigung meines Charakters und das Leben wurde auch nicht verändert.

**Erwartetes Verhalten**
Sofa sollte nach Rechtsklick vor meinem Auge erscheinen um es mit Punkt aufzustellen.
Ich bitte auch um eine Rückerstattung meines Sofas oder der 99$.

**Schritte um den Fehler nachvollziehen zu können**
Sofa Bundy rechte Maus anklicken und dann ist es weg + deutlich hörbares Schmatzen...

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Enemyaa** [comment]
Ich weiß nicht was du für ein RP mit dem Sofa hattest, aber systemtechnisch kann man dieses Sofa nicht essen. Du kannst aber gerne noch hinzufügen, wo genau du das Sofa aufstellen wolltest.

**Comment by JosefStark** [comment]
Vor dem 24/7 auf dem Highway an der Ostseite, wo auch die Tanke ist. In dem Laden wo gestern der 50% Sale angekündigt war, direkt zwischen Shop und Tanke
Es wurde mir aber gar nie vor meinem Auge angezeigt nach der rechten Maustaste sondern ist einfach instant verschwunden aus dem Inventar.
Die Schmatzgeräusche könnten von einem der anderen Spieler neben mir gekommen sein, zumal ich so ein Geräusch auch noch nie ingame gehört habe.

**Comment by DonVitoDiangelo** [comment]
Manchmal gibt es Regionen in denen bestimmte Objekte nicht geladen werden können, bevor Sie nicht schon vorher iwo. zu sehen waren bzw. ein Interior zu dem dieses Objekt explizit gehört geladen wurde . Ist son technisches Ding was bei div. Props auftritt. Können wir leider nicht so einfach fixen. Daher wird die bei der Couch dort unten so bleiben
