### ISSUE TITLE
Preis von Haus hat sich von null auf 513 000 gestellt, von allein

### ISSUE THREAD

**Issue by lillyking** [mexyn/statev_v2_issues#1665]
Lilly_King

Lilly_King
**Auftrittszeitpunkt (Datum / Uhrzeit)**

04.07.2021 gegen 10.00

**Beobachtetes Verhalten**

Das Haus sollte nicht zum Verkauf stehen, es war daher 0 als Preis eingestellt seit je her. Habe heute plötzlich entdeckt das 513 000 eingestellt war. Ich habe es selbst nicht umgestellt, es kam von alleine.
**Erwartetes Verhalten**

Es sollte auf 0 stehen, damit es nicht zum Verkauf steht. Habe es selbstständig wieder auf null gestellt und jetzt passt es wieder.

**Schritte um den Fehler nachvollziehen zu können**

Ich wüsste nicht wie.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

Ich wüsste nicht wie.

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Wir hatten kleine Überarbeitungen am Haussystem gemacht, weshalb der Preis jetzt so ausgeschrieben worden ist.

Daher gewollt und closed
