### ISSUE TITLE
Navy Seal mit Kriechen durch Wasser

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1666]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.07.2012

**Beobachtetes Verhalten**
Das Es Fail ist, keine Frage.
Nur vlt ist es ja fixbar.
Mit Kriechen kann man durchs Wasser ohne "Luft" zu verbrauchen. 
Geht auch im Meer

**Erwartetes Verhalten**
Luft wird trotzdem Verbraucht

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=0wtGJ0qbNJ4

**Comment by DonVitoDiangelo** [comment]
fail rp und melden. fixbar, bestimmt iwie., aber zu viel Aufwand.
