### ISSUE TITLE
Big T4sty Burger ermöglicht Szenario "Sitzen (Donut)" nicht

### ISSUE THREAD

**Issue by AngelMaravilla** [mexyn/statev_v2_issues#1667]
**Character Name**
Angel Maravilla

**Auftrittszeitpunkt (Datum / Uhrzeit)**
04.07.2021, 16:50 Uhr

**Beobachtetes Verhalten**
Mit dem "Big T4sty Burger" im Inventar kann man das Szenario (Y-Menü) "Sitzen (Donut)" nicht starten. Das Item scheint nicht als Essen-Item registriert zu werden. Habe es an einer Werkbank und dem großen beigen Sofa getestet.
![Screenshot_1](https://user-images.githubusercontent.com/74780492/124389584-22d77100-dce8-11eb-9203-caca115c2b6d.jpg)

**Erwartetes Verhalten**
Ein "Big T4sty Burger" sollte das Szenario (Y-Menü) "Sitzen (Donut)" ermöglichen.

**Schritte um den Fehler nachvollziehen zu können**
Als einziges Essen-Item den "Big T4sty Burger" im Inventar haben und dann versuchen das Szenario "Sitzen (Donut)" zu starten.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by CaleighRhodes** [comment]
Funktioniert auch mit Flasche Bier nicht bei "Sitzen (Alkohol trinken)" obwohl darauf hingewiesen wird, dass man 1 Flasche Bier o.ä. im Inventar haben sollte. Funktioniert nur mit Wein oder ähnlichem, oder wenn man lange genug klickt ;)

**Comment by DonVitoDiangelo** [comment]
1. @AngelMaravilla  fixed next update
2. @CaleighRhodes das liegt an einem anderen Fehler, den wir so nicht einfach beheben können.
