### ISSUE TITLE
[Maske] Weißes Paisley Bandana 

### ISSUE THREAD

**Issue by TamiGaming** [mexyn/statev_v2_issues#1668]
**Character Name**
Carlie Tacus

**Erwartetes Verhalten**
Gibt es die Möglichkeit ein weißes Paisley Bandana als Maske hinzuzufügen, da die Nachfrage ziemlich groß ist und es fürs Gesicht alternativ nur ein weißes Bandana gibt. (Weißes Broker Bandana)
Als Wrist, Neck, Sagged, Sandana etc. ist das weiße Paisley bereits vorhanden, nur nicht als Maske, also für das Gesicht.

**Comment by Enemyaa** [comment]
Ja, kann ich hinzufügen, wird dann mit einem der nächsten Updates hinzukommen - je nachdem, wann wir dlc's updaten.
