### ISSUE TITLE
Kofferraumvergrößerung bei Offroad Mesa möglich?

### ISSUE THREAD

**Issue by Koree7** [mexyn/statev_v2_issues#1669]
Ein zu kleiner Kofferraum bei Offroad Mesa?
Andere ähnliche Fahrzeuge wie Dubsta, Dubsta Sport (beides auch Geländewagen) oder auch die Baller-Reihe (SUVs) haben einen ähnlichen optischen Kofferraum aber etwas mehr Lagerplatz.
Ist eine Kofferraumanpassung möglich?

**Comment by DonVitoDiangelo** [comment]
Leider abgelehnt. Selbst die aufgezählten Fahrzeuge haben optisch schon "beachtlich" mehr Kofferraumvolumen. Hier sehe ich keine Punkte für eine Vergrößerung.
