### ISSUE TITLE
Rappelkiste (Trade für Spongebob)

### ISSUE THREAD

**Issue by RomanSpielberg** [mexyn/statev_v2_issues#1670]
Roman_Spielberg

05.07.2021 14:55Uhr und 15:11Uhr

Die Spongebob Figur V10 wird nicht mehr benötigt und damit auch nicht mehr "verbraucht". Bitte mal prüfen, ob die so gewollt ist.

Erwarten würde man, da es 10 Varianten gibt, das auch alle 10 Figuren benötigt werden.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
ja, da es leider nur 9 Slots gibt, wird diese 10te nicht mehr gebraucht, sad :/
