### ISSUE TITLE
Schlamm Falsche Transportgruppe

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1671]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.07.2021

**Beobachtetes Verhalten**
Schlamm kann nicht in eine Öl Achse geladen werden.
Keine Ahnung wofür man das braucht, aber es ist nicht einlagerbar.

Wenn kein Bug, einfach schließen.

**Erwartetes Verhalten**
Das man es verladen kann. Wenn man es möchte

**Schritte um den Fehler nachvollziehen zu können**
Öltanker an eine Pumpe Fahren und Schlamm verladen wollen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Chrinis007** [comment]
Schlamm hat auch zu v1 schon nicht in den Tanker gepasst :D

**Comment by DonVitoDiangelo** [comment]
so ist es
