### ISSUE TITLE
Anfrage: Terrassen-Mobiliar entfernen

### ISSUE THREAD

**Issue by Knippsa** [mexyn/statev_v2_issues#1672]
**Character Name**
Kalle Knutsen

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Für Haushash: SamsonCountryRew_House_8
Wenn möglich bitte die gesamte Terasse von dem Mobiliar befreien. Stuhlgarnitur fällt direkt um. Heizpilz und Schlauchtrommel sind unpassend und der Grill ist nicht verwendbar. Möchte da gerne richtiges Mobiliar aufbauen. Foto: https://pic.statev.de/image/fYc5D

**Erwartetes Verhalten**
Leere Terrasse

**Comment by DrGrizzlY17** [comment]
Tische & Stühle entfern, Rest bleibt

**Comment by Knippsa** [comment]
> Tische & Stühle entfern, Rest bleibt

Danke aber wieso nicht zumindest auch der Grill, der eben nicht verwendbar ist. Wäre der Pfannenwender dort nutzbar hätte ich auch gar nicht erst gefragt aber in der Form werden die RPs dort nicht gut. Zum Verständnis: Ich möchte dort echt oft RP machen und das nicht nur der optik halber aufräumen. Mit der losen Schlauchtrommel und Heizpilz kann ich mich gerne arrangieren.

**Comment by Knippsa** [comment]
> Tische & Stühle entfern, Rest bleibt

Könnt ihr bitte nochmal drüber nachdenken den "defekten" Grill auch wegzunehmen? Das würde das RP deutlich angenehmer machen.
