### ISSUE TITLE
Skill Drogenverarbeitung immer noch wirkungslos...

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1673]
Bin mittlerweile in der fünften Stufe mit 10% Zeitersparnis, aber die Produktion dauert wie es auch ungelernt ist 15 Minuten.
Also passt da immer was noch nicht...

Hier der alte Thread...
https://github.com/mexyn/statev_v2_issues/issues/1429

**Comment by Statev-Bonsai** [comment]
@JulianMa gibts hierzu schon was neues?

**Comment by its4l3x** [comment]
fixed, next update
