### ISSUE TITLE
Garage Ausparkrichtung ändern

### ISSUE THREAD

**Issue by Knippsa** [mexyn/statev_v2_issues#1674]
**Character Name**
Kalle Knutsen

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Haushash: SamsonCountryRew_House_8
Fahrzeuge werden beim ausparken sehr schräg ausgeparkt.  Diese können dadurch, dass direkt daneben die Mauer ist zum Schaden führen. Foto siehe unten

**Erwartetes Verhalten**
Wäre gut wenn die Ausparkrichtung zur Straße begradigt und auch ein Stück weiter zur Straße hin gesetzt wird. 

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/fY5g6

**Comment by DrGrizzlY17** [comment]
Grüße,

kurze Rückfrage. Wurde das Auto von dir eingeparkt oder automatisch durch das System?
Mit v2 gab es nämlich eine Änderung, das Fahrzeug so ausparken wie sie eingeparkt wurden.
Im Code ist die Fahrzeugrichtung soweit ok, also vermute ich liegt es am automatischen einparken.

**Comment by Knippsa** [comment]
Okay dann ergibt das sinn. Werde ich nochmal ausprobieren. Wenn ihr nichts mehr hört passt es auch :)
