### ISSUE TITLE
Umhängetasche ummodden? / Aktenkoffer als Tasche?

### ISSUE THREAD

**Issue by Knippsa** [mexyn/statev_v2_issues#1676]
**Character Name**
Kalle Knutsen

**Beobachtetes Verhalten**
Wollte mal fragen, ob man diese Leder-Umhängetasche mit 15kg Volumen im Umhängeband ummodden kann. Grundsätzlich passt dieser Bügel eher wenn man Pullis oder dicke Jacken anhat. Optisch ist es ja aber eher eine "Business-Tasche" wo man Hemden, Sakkos, Mäntel trägt aber der Bügel passt dafür überhaupt nicht.

Außerdem fände ich es cool, wenn die 2 Aktenkoffer (Braun aus Leder und Schwarz als Hartkoffer) nicht nur optisch sondern auch als Tasche zu gebrauchen wären. Dann würden noch weniger Leute in der Stadt mit einer Umhängetasche etc. rumlaufen. Da reichen ja schon 10-15kg.

**Erwartetes Verhalten**
Passform des umhängebügels halbwegs am Körper.

**Comment by Stiefel911** [comment]
> **Character Name**
> Kalle Knutsen
> 
> **Beobachtetes Verhalten**
.......
> Außerdem fände ich es cool, wenn die 2 Aktenkoffer (Braun aus Leder und Schwarz als Hartkoffer) nicht nur optisch sondern auch als Tasche zu gebrauchen wären. Dann würden noch weniger Leute in der Stadt mit einer Umhängetasche etc. rumlaufen. Da reichen ja schon 10-15kg.
> 
.......
fände ich richtig nice ;)

**Comment by Enemyaa** [comment]
Das mit dem Gurt wird wohl eher nichts. Das sind alles modded Sachen und die meisten Sachen sind locked, somit kann man sie nicht bearbeiten. 

Ich hab die Aktenkoffer jetzt mal so gebaut, dass man die auch als Tasche tragen kann, um sie optisch zu sehen, muss man sie aber wie vorher auch anklicken, damit die Animation startet.

Im Moment leider der einzige Weg!
