### ISSUE TITLE
Karin Rusty Rebel wird nicht geblitzt

### ISSUE THREAD

**Issue by CoreForcee** [mexyn/statev_v2_issues#1680]
**Beobachtetes Verhalten**
Wenn man mit dem Karin Rusty Rebel beim blitzer vorbeifährt egal mit welcher geschwindigkeit löst der Blitzer nicht aus

**Erwartetes Verhalten**
Blitzer sollte richtig auslösen

**Comment by its4l3x** [comment]
exceptionVehicles.json @DrGrizzlY17
