### ISSUE TITLE
Falsche Zimmer im Hotel Vespucci_Flat_16

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1681]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
09.07.2021

**Beobachtetes Verhalten**
im Tablet des Hotel Vespucci_Flat_16 sind Zimmer mit Hash Magellan Ave. 55_** & Magellan Avenue 55_** hinterlegt.
An der Tür allerdings nicht. Es ist möglich die Preise der Zimmer zu ändern, allerdings sind diese nicht in unserem Hotel mietbar, da sie zu einem anderen Hotel gehören.

**Erwartetes Verhalten**
Nur Zimmer mit dem Hash Vespucci_Flat_16_** werden angezeigt.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
DB einmal die Magellan Zimmer entfernen

**Comment by its4l3x** [comment]
Bitte mir eine Liste geben @DrGrizzlY17 mit den ganzen Hashes.

**Comment by TheBroady** [comment]
string(18) "Magellan Ave. 55_1"
string(19) "Magellan Ave. 55_10"
string(18) "Magellan Ave. 55_2"
string(18) "Magellan Ave. 55_3"
string(18) "Magellan Ave. 55_4"
string(18) "Magellan Ave. 55_5"
string(18) "Magellan Ave. 55_6"
string(18) "Magellan Ave. 55_7"
string(18) "Magellan Ave. 55_8"
string(18) "Magellan Ave. 55_9"
string(20) "Magellan Avenue 55_1"
string(21) "Magellan Avenue 55_10"
string(20) "Magellan Avenue 55_2"
string(20) "Magellan Avenue 55_3"
string(20) "Magellan Avenue 55_4"
string(20) "Magellan Avenue 55_5"
string(20) "Magellan Avenue 55_6"
string(20) "Magellan Avenue 55_7"
string(20) "Magellan Avenue 55_8"
string(20) "Magellan Avenue 55_9"

**Comment by TheBroady** [comment]
@its4l3x die Zimmer sind noch im Tablet zu sehen, falls du was gemacht hattest.
