### ISSUE TITLE
Häuser Preise 

### ISSUE THREAD

**Issue by simonrolex** [mexyn/statev_v2_issues#1682]
**Character Name**
Simon Dallas

**Auftrittszeitpunkt (Datum / Uhrzeit)**
08.07.2021

**Beobachtetes Verhalten**
Die Häuser Sustancia Road 22 & Sustancia Road 31 kosten zum Kauf 245k & 404k. Zum Vergleich kostet ein Haus in der Fudge Lane( gegenüberliegende Straße)145k.

**Erwartetes Verhalten**
Durch vielleicht steigende Immobilienpreise könnte ich einen Anstieg von 145k auf 180k verstehen, da die anliegenden Häuser sich auch nicht vom Aussehen oder der Lage unterscheiden.

**Schritte um den Fehler nachvollziehen zu können**
/

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
/

**Optional: Video / Bilder des Fehlers**
/

**Comment by DrGrizzlY17** [comment]
Hat seine Gründe, das es so ist
