### ISSUE TITLE
[M] Schwarze Turnschuhe - Passen nicht am Fuß

### ISSUE THREAD

**Issue by SirAres** [mexyn/statev_v2_issues#1684]
**Character Name**

Ares_Hohengarten

**Auftrittszeitpunkt (Datum / Uhrzeit)**

09.07.2021  - 20:19

**Beobachtetes Verhalten**

Die [M] Schwarze Turnschuhe haben an den Versen hinten jeweils auf beiden Seiten ein Loch

**Erwartetes Verhalten**

Turnschuhe sollten passend sein 

**Schritte um den Fehler nachvollziehen zu können**

[M] Schwarze Turnschuhe anziehen und von hinten auf die Versen schauen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot_3](https://user-images.githubusercontent.com/87204556/125120910-71737980-e0f3-11eb-8434-d89eae094224.png)

**Comment by Enemyaa** [comment]
Das sind GTA eigene Sneaker. Da können wir leider nichts machen, aber ich hab sie mal komplett aus dem Spiel entfernt.
