### ISSUE TITLE
Fehler Interieur Ace Jones Drive 174

### ISSUE THREAD

**Issue by SimonPfeifferStateV** [mexyn/statev_v2_issues#1685]
Character Name: Simon_Pfeiffer

Auftrittszeitpunkt (Datum / Uhrzeit): 10.07.2021, 12:56 Uhr

Beobachtetes Verhalten: Wenn man das Gebäude Ace Jones Drive 174 betritt, kann man in der Inneneinrichtung (Story Mode: Michaels Haus) das Haus verlassen und im Garten rauslaufen.

Erwartetes Verhalten: Man kann nicht durch die Gartentür laufen.

Schritte um den Fehler nachvollziehen zu können: In das Haus Ace Jones Drive 174 gehen und in den Garten laufen.

Monitorauflösung (nur wenn Falsche Darstellung in der UI)

Optional: Video / Bilder des Fehlers: https://youtu.be/znh0aPg8sVs

**Comment by DonVitoDiangelo** [comment]
so gewollt
