### ISSUE TITLE
Coil Cyclone wird beim Ausparken beschädigt

### ISSUE THREAD

**Issue by sGtDeath** [mexyn/statev_v2_issues#1686]
**Character Name**
Frank Gruber

**Auftrittszeitpunkt (Datum / Uhrzeit)**
10.07.2021 15:45

**Beobachtetes Verhalten**
Bei dem Ausparken eines Coil Cyclone (tiefer gelegt) aus der Bootsanleger Garage (5008) clippen die Vorderreifen in den Boden und beschädigen das Fahrzeug jedesmal bis zur Roten Kontrollleuchte. Bis jetzt tatsächlich nur bei der Garage beobachtet.

**Erwartetes Verhalten**
Das Fahrzeug wird einfach ausgeparkt und wird dabei nicht beschädigt.

**Schritte um den Fehler nachvollziehen zu können**
Coil Cyclone (tiefer gelegt) bei dem Garagen NPC einparken und wieder ausparken.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
-

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
@DrGrizzlY17  den spawn etwas höher setzen

**Comment by Tony-Mofa** [comment]
Character Name
Tony Mofa

Auftrittszeitpunkt (Datum / Uhrzeit)
16.07.2021 schon seit letztem Freitag 09.07.2021

Beobachtetes Verhalten
Habe ebenfalls das Problem mit dem Cyclone (tiefer gelegt) hängt im Boden feste bis Totalschaden, betrifft aber nicht nur die Garage am Bootsanleger. Die an der Pillbox Garage und die LosSantos Garage auch. Habe noch nicht alle durchgetestet. Das Problem wird bestimmt noch die ein oder andere Garage haben.

Idee
Wie oben beschrieben, den Spawn minimal höher setzen 

Grüße
