### ISSUE TITLE
Antrag - Teleport auf Dachterrasse 

### ISSUE THREAD

**Issue by Gartenzaun1** [mexyn/statev_v2_issues#1688]
### Character Name

Chaze Alvarez

### Anfrage
Grüße,

ich würde mich sehr freuen, wenn ich für mein Haus ein Teleportpunkt auf die Dachterrasse bekommen könnte.
Aktuell verwende ich dafür einen Leiterwagen. Sieht ned so dufte aus.

Ich danke schonmal im Voraus.

Gruß
Gartenzaun

**Optional: Video / Bilder des Fehlers**

https://imgur.com/a/n5ZQ6LJ

**Comment by DrGrizzlY17** [comment]
Bräuchte nen Hash oder Adresse

**Comment by Gartenzaun1** [comment]
house_VinewoodHills_138
South Mo Milton Drive 146

Sry hatte ich vergessen anzugeben
