### ISSUE TITLE
Kein Voice mehr nach Handel mit anderen Spieler

### ISSUE THREAD

**Issue by Arnaldo-Milano** [mexyn/statev_v2_issues#169]
**Arnaldo Bloom**

**30.08.2020 14:30**

**Beobachtetes Verhalten**
Nach dem Handel mit einem anderen Spielen ist keine Ingame Voice mehr möglich....
Ein Plugin Neustart hat nichts gebracht. Teamspeak Neustart auch nichts

**Erwartetes Verhalten**

Voice funktioniert weiterhin

**Comment by its4l3x** [comment]
Dupicate, dein UI crashed. #83
