### ISSUE TITLE
Hotel 2 Zimmer Preis nicht änderbar

### ISSUE THREAD

**Issue by loelchn** [mexyn/statev_v2_issues#1690]
James_Ackles

James_Ackles
**Auftrittszeitpunkt (Datum / Uhrzeit)**

dauerhaft
**Beobachtetes Verhalten**

trotz Preisänderung hüpft der Preis immer auf 100$ zurück
**Erwartetes Verhalten**
nach einen bestimmten Stundenpreis von z. B. 10$ sollte der Preis nach Aktualisierung nicht wieder auf 100$ sein

**Schritte um den Fehler nachvollziehen zu können**
Hotel: Firmenhash	JunSandyShoresRew_Flat_21

Zimmer 1: JunSandyShoresRew_Flat_22_28
Zimmer 2: JunSandyShoresRew_Flat_22_23

Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
jederzeit im satev.de

**Optional: Video / Bilder des Fehlers**
<!--- Falls du ein Video oder Bild vom Fehler gemacht hast, dann kannst du diesen hier einfügen. Dies geht ganz einfach per 

https://prnt.sc/1alm25v

**Comment by DrGrizzlY17** [comment]
DB Einträge löschen

**Comment by loelchn** [comment]
Wenn ich meine löschen sollte. nein, kein Erfolg damit.

**Comment by DrGrizzlY17** [comment]
Nein nicht du, Alex muss das machen

**Comment by its4l3x** [comment]
fixed after restart

**Comment by loelchn** [comment]
Moin. Was ist daran gefixt, wenn ich ein Hotel mit 32 Einheiten gekauft habe, und jetzt nur noch 30 Zimmer habe? o_0

**Comment by loelchn** [comment]
Macht Sinn, wenn ich einen Antrag auf Aufstockung der Hotelzimmer hier mache?

**Comment by DrGrizzlY17** [comment]
Nein, würde abgelehnt werden. 30 Zimmer ist ok für das Gebäude.

Was daran fixed ist? Das dir zwei Zimmer entfernt wurden, die zu deinem Gebäude gar nicht gehört haben und ein Bug war.
Erkennst du daran das dein Gebäude den hash: JunSandyShoresRew_Flat_21 hatte und alle 30 Wohnungen auch diesen hash haben JunSandyShoresRew_Flat_21_1 bis JunSandyShoresRew_Flat_21_30. Die buggy Zimmer hatten JunSandyShoresRew_Flat_22_X

**Comment by loelchn** [comment]
Ok  close  danke fürs nachschauen.

*Diese Mail wurde vom Smartphone verschickt!

StateV_Dan ***@***.***> schrieb am Mi., 21. Juli 2021, 17:53:
