### ISSUE TITLE
Neue Öffentliche Garage 

### ISSUE THREAD

**Issue by MarkHarland** [mexyn/statev_v2_issues#1691]
Ich wollte einmal anfragen ob es möglich wäre das es in Stab City eine Öffentliche Garage gibt.
Leider sind die Trailer dort kaum benutzbar da die Autos meist am nächsten Tag weg sind und man keine Möglichkeit hat dort 
einzuparken.
Leider landen die Autos auch ab und zu in anderen Garagen den (Sandy Shores oder Harmonie)

![Screenshot_26](https://user-images.githubusercontent.com/70329528/125353321-b18c6380-e362-11eb-86f1-2eecedff08ca.png)

**Comment by DonVitoDiangelo** [comment]
Abgelehnt, unten habt Ihr eine Garage
