### ISSUE TITLE
Police Bike hat Gurte

### ISSUE THREAD

**Issue by AngelMaravilla** [mexyn/statev_v2_issues#1692]
**Character Name**
Angel Maravilla

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.07.2021, 18:00 Uhr

**Beobachtetes Verhalten**
Das Polizei Motorrad hat im Gegensatz zu allen anderen Motorrädern Gurte
(Screenshot ist leider etwas abgeschnitten aber man erkennt's)

**Erwartetes Verhalten**
Es sollte keine Gurte haben

**Schritte um den Fehler nachvollziehen zu können**
Auf dem Polizei Motorrad anschnallen
![Screenshot_1](https://user-images.githubusercontent.com/74780492/125409128-e37de400-e3bb-11eb-9223-c1ebb614ae4b.jpg)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Da wird nichts dran geändert, cloes
