### ISSUE TITLE
Anfrage Bad & Lagerpunkt Luxury House Modern Design Art

### ISSUE THREAD

**Issue by Knippsa** [mexyn/statev_v2_issues#1693]
**Character Name**
Kalle Knutsen

**Beobachtetes Verhalten**
1. Im Wiki steht für o.g. Haus-Einrichtung dass dort ein Badezimmer drin ist. Zu finden ist dies jedoch nicht. Allerdings sind dort 4 Türen im unteren Bereich die man nicht begehen kann. ggf. seit AltV so? Vielleicht könnt ihr ja prüfen, ob es dort doch ein Badezimmer gibt nur geöffnet werden muss. 
2. Aus reiner RP-Sicht würde ich es cool finden, wenn der Lagerpunkt nicht unten bei der Treppe wäre sondern in der Küche z.B. vor dem Kühlschrank. Nur eine Idee um RP in der Einrichtung ggf. etwas authentischer zu gestalten weil man bei Besuch ja meist nur daran geht um Essen/Trinken zu holen.

**Comment by DonVitoDiangelo** [comment]
Punkt wird nach oben verschoben und ein direktes Bad, hat dieses Interior nicht. Nur ne Wanne die im Schlafzimmer steht.
