### ISSUE TITLE
Türkises Paisley Bandana (Maske, Wrist, Sagged, Neck, Sandana)

### ISSUE THREAD

**Issue by xkanni** [mexyn/statev_v2_issues#1695]
Character Name
Kristian Saiz

Erwartetes Verhalten
Wäre es möglich ein Türkises Paisley Bandana als Maske, für die Hose, den Arm, Kopf und Hals hinzuzufügen?
Da unsere Gang die Aztecas am Arm, Hose, Kopf und Hals mit den weißen rum laufen und tragen das Gold Leaves Bandana als Maske. Dadurch ist halt unsere Farbe die wir tragen eingeschränkt an den besagten stellen und es herrscht immer ein bisschen verwirrung bei anderen Gangs/Familien.

**Comment by TamiGaming** [comment]
Eventuell wäre dies generell für alle farbigen Bandanas möglich, die es für Neck, Wrist, Sagged gibt.
Da es dort einige nicht als [Maske] gibt.

**Comment by Enemyaa** [comment]
@xkanni Ich schau mal. Habt ihr denn n passendes türkis? In nem Hemd oder Sweater, damit ich ne Vorlage habe?

**Comment by Enemyaa** [comment]
Next Update!
