### ISSUE TITLE
Harre Clippen durch Cap durch

### ISSUE THREAD

**Issue by SgtSkipper** [mexyn/statev_v2_issues#1697]
Character Name
James Edwards

Auftrittszeitpunkt (Datum / Uhrzeit)
15.07.2011 19:00

Beobachtetes Verhalten
Wenn man die Schwarze Snapback Cap anzieht Clippen die harre durch die Cap

Erwartetes Verhalten
das die Haare nicht durch die Cap Buggen

Schritte um den Fehler nachvollziehen zu können
Schwarze Snapback kaufen für männer und anziehen.

Monitorauflösung (nur wenn Falsche Darstellung in der UI)

Optional: Video / Bilder des Fehlers
https://prnt.sc/1bgvlfs

**Comment by epichalt** [comment]
Du musst die Cap als letztes aufsetzen, dann gehts  (zumindest mit den ganzen neueren Caps)

**Comment by SgtSkipper** [comment]
hat leider nicht funktioniert

**Comment by its4l3x** [comment]
Korrekt, kommt bald ein neues System. Be prepared.
