### ISSUE TITLE
Anfrage Gartentor entfernen/öffnen

### ISSUE THREAD

**Issue by LanabobanaTTV** [mexyn/statev_v2_issues#1698]
Charakter: Lana_Winters

Hallo,

wollte fragen ob man bei unserer Villa:  house_RockfordHills_2   die weißen Holzgartentore öffnen oder entfernen kann (hecke kann bleiben), damit man in den Garten kann. Können momentan nur in den Garten, indem wir über die Hecke klettern. Ein Teleport wäre auch okay.

Liebe Grüße 

Lana

![lanavilla3](https://user-images.githubusercontent.com/86558691/125830733-051a52d9-486f-436b-99bb-3a8096ddf429.jpg)
![lanavilla2](https://user-images.githubusercontent.com/86558691/125830769-74c1d219-84fb-4b7a-a397-a9dc264e9093.jpg)

**Comment by DonVitoDiangelo** [comment]
Nicht möglich, bzw. es würde eine Kollision übrig bleiben, von daher leider abgelehnt.
