### ISSUE TITLE
Preise nicht in Ladetheke (Restaurant) beim Laden im StateNet vorhanden.

### ISSUE THREAD

**Issue by Asmier** [mexyn/statev_v2_issues#1699]
Asmier Umid / Sarah_Lee

**Zeitpunkt (Datum / Uhrzeit)**
Ab 15.07.2020 / 22:53 

**Beobachtetes Verhalten**
Restaurant: snrKebab alias 🦴 Bone Eater 🍽️
Preise verschwinden aus dem Tablet

**Erwartetes Verhalten**

   1. Tablet aktualisieren
   2. Preise bleiben

**Schritte um den Fehler nachvollziehen zu können**

   1. Tablet aktualisiert
   2. Preise auf 0

Selbe Fehler wie damals nur das man nun gar keine eingestellten Preise mehr hat.
Bedeutet für mich bei einer Preisänderung, alle Preise wieder neu einzutragen da sonst das System die 0 Dollar übernimmt.
Browser ist FireFox, mit Microsoft Edge tritt der Fehler ebenso aus.

Ebenso laden bei mir die Preise im Kleiderladen so wie sie es sollen.
Nur beim Restaurant nicht.

https://github.com/mexyn/statev_v2_issues/issues/415#issue-748359861

**Comment by TheBroady** [comment]
Meint ihr sowas?
https://www.youtube.com/watch?v=ofUyujgp9vQ

**Comment by Asmier** [comment]
Richtig, nur das bei uns gar keine Preise mehr kommen. Selbst wenn ich 5 Minuten lang versuche da zu switchen

**Comment by MarcelMuerto** [comment]
@TheBroady @Asmier 
Das Fehlverhalten konnte reproduziert und behoben werden.

Die Änderung kommt mit dem nächsten StateNet Update.
