### ISSUE TITLE
Tablet animation verschwindet nicht auf Friseurstuhl

### ISSUE THREAD

**Issue by Otacon225** [mexyn/statev_v2_issues#17]
**25.08.2020 18:56Uhr**

**Nach wegstecken von Tablet auf dem Friseurstuhl verschwindet zwar das Tablet aber die Animation nicht**

**Verschwinden der Animation**

![Unbenannt](https://user-images.githubusercontent.com/70226950/91204891-fb496c80-e704-11ea-97f7-cfbb3d1ce692.jpg)

**Comment by its4l3x** [comment]
Fixed. 👍
