### ISSUE TITLE
Diamanten gehen beim schleifen kaputt trotz max. Bonus

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#1700]
**Character Name**
Dean Gallagher

**Beobachtetes Verhalten**
Wissenschaftler hat den maximalen Produktionsbonus von 5% aber Edelsteine gehen beim schleifen im Labor noch kaputt. 

**Erwartetes Verhalten**
Das Edelsteine beim schleifen im Labor nicht mehr kaputt gehen da man den maximalen Produktionsbonus hat.

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/i/f5Z5g.jpg
https://pic.statev.de/i/f59WS.jpg

**Comment by DonVitoDiangelo** [comment]
das ist so korrekt , es gibt hier keine 100% Chance.

**Comment by Statev-Bonsai** [comment]
hahahaah.... sie gingen früher kaputt und sie gehen heute kaputt ;)
