### ISSUE TITLE
Haus verkauft sich immer wieder selbst

### ISSUE THREAD

**Issue by cadpri** [mexyn/statev_v2_issues#1701]
**Character Name**
Fabian Picard

**Auftrittszeitpunkt (Datum / Uhrzeit)**
immer wieder mal

**Beobachtetes Verhalten**
Ich möchte mein Haus SandyShores40 nicht verkaufen. Deswegen habe ich den Verkaufspreis auf 0 gestellt.
Immer wieder mal stellt sich der Verkaufspreis dann aber auf 90.000. Dies habe ich nicht gemacht.

**Erwartetes Verhalten**
Haus soll nicht verkauft werden

**Schritte um den Fehler nachvollziehen zu können**
Haus auf 0$ Verkaufspreis stellen und hin und wieder mal reinschauen

**Comment by CaleighRhodes** [comment]
Das ist kein Bug.
Kann aber keiner dein Haus kaufen, solange du nicht aktiv auf "Verkaufen drückst" - der Preis wird sich immer wieder zurück stellen.
Also einfach so lassen und keine Panik schieben :)

**Comment by its4l3x** [comment]
Wie @CaleighRhodes schon sagt, ist kein Bug.
