### ISSUE TITLE
Sortierung Kleidungsmenü

### ISSUE THREAD

**Issue by NeedManu** [mexyn/statev_v2_issues#1702]
**Character Name**
Martin Henks

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.07.2021 23:30

**Beobachtetes Verhalten**
Sortierung im Kleidungsmenü durcheinander

**Erwartetes Verhalten**
Sortiert

**Schritte um den Fehler nachvollziehen zu können**
Kleidungsmenü mit "Komma" öffnen

**Optional: Video / Bilder des Fehlers**
![Kleidungsmenü](https://user-images.githubusercontent.com/81923141/126010817-eef07855-4d67-45bb-a150-7ec175d81a29.png)

**Comment by SHaagmann** [comment]
Nicht nur dort, sondern auch wenn man sich handschuhe etc anziehen will 
![image](https://user-images.githubusercontent.com/58612983/126013972-7a2bb4b3-457a-40f5-89eb-84b91509eaa6.png)

**Comment by Hutstaender** [comment]
Das rührt wohl nicht vom UI her, intern sind scheinbar Array Sortierungen verändert worden. Das Problem tritt bei allen Listen auf, auch in Produktionsmenüs etc.

**Comment by its4l3x** [comment]
fixed next update
