### ISSUE TITLE
Handel-Bug

### ISSUE THREAD

**Issue by KruemelGames** [mexyn/statev_v2_issues#1703]
Dave Weinstein

23.09Uhr

Handels-UI schließt nicht nach dem Bestätigen der Interaktion. Man kann nicht mehr reden. Relogg hilft nur, 3mal aufgetreten bei 2 Personen innerhalb 30 MInuten.
Edit: Man fliegt direkt aus dem Voice/TS wenn der Bug auftritt

UI Schließt sich, man kann weiter reden

Mehrmals handeln. Evtl kommt der Fehler. Keine Ahnung ob es dafür bestimmte Faktoren braucht. 

1920x1080

https://www.youtube.com/watch?v=u1toDYoWL2I

**Comment by Hutstaender** [comment]
Sind bei einem der beiden handelnden Grafikmods installiert?

**Comment by KruemelGames** [comment]
Hatte kein NVE drauf wegen Update aber dafür enb und reshade
