### ISSUE TITLE
[Error] Marker render error at [object Object] (cb: => () undefined) NO TYPE NO COL RED NO COL BLUE NO COL GREEN 255, 0

### ISSUE THREAD

**Issue by tristan1297** [mexyn/statev_v2_issues#1704]
**Character Name**
Peter Rumpe

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit dem AltV Update

**Beobachtetes Verhalten**
Man betritt eine Wohnung und der Marker fehlt. In der Console wird o.g. Fehler dauerhaft gespammt

**Erwartetes Verhalten**
Marker vorhanden, kein Error in der Console

**Schritte um den Fehler nachvollziehen zu können**
In eine Wohnung gehen und Console öffnen. Entfernt man die Marker mit F7 so sind auch die Console-Logs weg

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
"Man betritt eine Wohnung und der Marker fehlt. In der Console wird o.g. Fehler dauerhaft gespammt"

Welcher Marker?

Tür? Lager?

**Comment by tristan1297** [comment]
Der von der Tür. Sorry :D

**Comment by its4l3x** [comment]
Alles gut, fixe ich eben

**Comment by its4l3x** [comment]
fixed, next update.
