### ISSUE TITLE
Lackieren nicht möglich 

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#1705]
**Character Name**
carWorkshop8 - 🎀Horizons🎀Hottest Engines

**Beobachtetes Verhalten**
Lackieren nicht möglich da Fehler, siehe screen für die Meldung

**Erwartetes Verhalten**
Das ich lackieren kann

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug nehmen, in Werkstatt auf Lackierpunkt stellen und versuchen

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/i/fLYJy.jpg

**Comment by DerRazer** [comment]
Яeaction 👁‍🗨 Corp - Repair das gleiche Problem

**Comment by SHaagmann** [comment]
Helmuts auch das gleiche

**Comment by KruemelGames** [comment]
MagicX Repairs ebenfalls

**Comment by its4l3x** [comment]
fixed seit heute
