### ISSUE TITLE
Gonzo Sammelfiguren

### ISSUE THREAD

**Issue by CCastles22** [mexyn/statev_v2_issues#1706]
**Hons_Klescheneder**

**Gonzo Sammelfiguren**
Hab mehrere Kombinationen ausprobiert , auch mit andere Gegenstände die 4 leeren Felder auffüllen
Kann es sein das man diese Serie noch nicht umtauschen kann?

**Erwartetes Verhalten**
Umtauschen möglich

btw: IC hatte noch einer gesagt das die Rappelkiste gleich aussieht wie der Drogentisch (also von den Feldern) wenn das wirklich so ist und einfach 1:1 übernommen worden ist könnte man dann die 3 Felder Rechts einfach wegmachen weil die ansonsten viele Leute mehr verwirren als helfen!?

VG

**Comment by DonVitoDiangelo** [comment]
Gab es nicht und wird auch nicht kommen.

**Comment by CCastles22** [comment]
hm schade damit ist Hochseeangeln nochmal uninterressanter weil man die Gonzo am meisten da findet!
