### ISSUE TITLE
Fashion Killa

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#1707]
**Character Name**
Ryan_Valdes

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Seit Update

**Beobachtetes Verhalten**

Es ist einfach alles Durcheinander im Fashion Killa und sachen werden teils falsch dargestellt.

**Erwartetes Verhalten**

Wie vor dem Update

**Schritte um den Fehler nachvollziehen zu können**

Einfach mal den Fashion Killa nutzen.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Enemyaa** [comment]
Next Update
