### ISSUE TITLE
Produkt "Flasche Eistee" wurde nicht durch "Flasche Eistee Pfirsich" ersetzt

### ISSUE THREAD

**Issue by DylanDuncan** [mexyn/statev_v2_issues#1708]
**Character Name**

Dylan Duncan

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Seit dem Update gestern

**Beobachtetes Verhalten**

Das Produkt "Flasche Eistee" wurde überall entfernt. Aus Lager, Ladentheke, Inventar etc.

**Erwartetes Verhalten**

Das neue Produkt "Flasche Eistee Pfirsich" hat exakt die selbe Produktion, bisher wurden die Produkte bei so einem Fall immer ersetzt.
Also 100x Flasche Eistee im Lager vor Update --> 100x Flasche Eistee Pfirsich nach Update

**Comment by Dean-Gallagher** [comment]
kann ich so bestätigen, etwa 1100 flaschen eistee sind weg

**Comment by DrGrizzlY17** [comment]
Items wurden separiert und somit sind vorhandene Items nicht mehr vorhanden. So gewollt

**Comment by dastiii** [comment]
nett :)

**Comment by DrGrizzlY17** [comment]
Wir haben uns wegen dem Thema nochmal besprochen. Kommt in den Support für Erstattung

**Comment by dastiii** [comment]
Freut mich, dass ihr euch das nochmal überlegt habt. :)

Mir hätte auch einfach eine ehrliche Entschuldigung o.ä. gereicht, statt einer Erstattung. Scheiß aufs Geld, aber wenigstens ein kleines "Sorry" und nicht ein gefühltes "Jo, wurden entfernt, fuck off". So kommt es jedenfalls irgendwie rüber.

Manche Dinge müssen halt gemacht werden, gar kein Problem. Aber ordentlich und respektvoll kommuniziert, wäre es auch einfach weniger schlimm. Davon ab, dass der Changelog darauf schließen lässt, dass das Item 1:1 ersetzt wurde.

Aber entsprechend noch einmal danke, dass das nicht das letzte Wort war und ein dickes DANKE für eure Arbeit. :)

**Comment by DonVitoDiangelo** [comment]
> Wir haben uns wegen dem Thema nochmal besprochen. Kommt in den Support für Erstattung

Leider gab es hier wohl eine Miss-Kommunikation, was uns leid tut. Es wird keine Erstattungen geben, sorry.
