### ISSUE TITLE
Einloggen mit Fehlermeldung

### ISSUE THREAD

**Issue by Tony-Mofa** [mexyn/statev_v2_issues#1709]
![error](https://user-images.githubusercontent.com/87539207/126035859-90d8cadf-8cfb-4b58-8429-85965dfe689c.JPG)

**Comment by Tony-Mofa** [comment]
**Character Name**

Tony_Mofa

**Auftrittszeitpunkt (Datum / Uhrzeit)**

17.07.2021 13:07Uhr

**Beobachtetes Verhalten**

Beim Einloggen auf dem Server, erscheint nach ich verbinde "Der CDN stimmt nicht..." (siehe Screenshot)
Wenn ich über die Serverliste verbinde, klappt es sofort. Doch habe ich komplette FPS einbußen, das Spiel läuft nicht sauber.

**Erwartetes Verhalten**

Wie gewohnt, das Einloggen über Connect am StartUp das Launchers

Was hab ich vorgenommen:
- Rechner neustart
- GPU Treiber aktuellisiert.

**Optional: Video / Bilder des Fehlers**

**Comment by epichalt** [comment]
v2.statev.de:80 in direct connect als ip eingeben, dann sollte es gehen

**Comment by Tony-Mofa** [comment]
Top! Danke für die schnelle Antwort. weiter machen ;)
