### ISSUE TITLE
Tore in der Tricksters Hood entfernen

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1710]
**Character Name**
Max Broady

**Beobachtetes Verhalten**
Wäre es möglich die beiden Tore in der Tricksters Hood zu entfernen?
Diese machen ständig Schrammen in die Fahrzeuge und es ist fast unmöglich da ohne Visible Schäden durch zu kommen.

**Erwartetes Verhalten**
Tore weg alle Happy :)

**Optional: Video / Bilder des Fehlers**
![GTA5 2021-07-17 14-20-13](https://user-images.githubusercontent.com/70150887/126036692-fbac63f8-c683-468f-b5fb-95dd06cc0e02.png)

**Comment by DonVitoDiangelo** [comment]
Wie nicht möglich? Einfach jemanden hinstellen, der das Tor aufhält. ;)
