### ISSUE TITLE
Knotbandana Ändert Frisur

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1712]
**Character Name**
Ben Reaper

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.07.21

**Beobachtetes Verhalten**
Das Knot Bandana ändert die Frisur den Chars

**Erwartetes Verhalten**
Die Frisur bleibt wie gewohnt bestehen.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Vorher
![image](https://user-images.githubusercontent.com/70150887/126041854-c99ca834-7268-4cfb-a7a8-17a1e75adb10.png)

Nachher:
![image](https://user-images.githubusercontent.com/70150887/126041858-8d5e10ab-0dc2-455a-99d0-cddc91f4ae59.png)

**Comment by its4l3x** [comment]
Vllt. die Reset Config?

**Comment by Enemyaa** [comment]
Next Update!
