### ISSUE TITLE
Autohaus -> [13:33:15][Error] Marker render error at Vector3{ x: -1245.6200, y: -3035.4399, z: -48.4800 } (cb: => () spawnVehPosition) NO TYPE NO COL RED NO COL BLUE NO COL GREEN 255, 29.1

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#1713]
**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
im Autohaus dauerhaft

**Beobachtetes Verhalten**
Im Autoshaus sein, und in der Konsole dauerthaft 
[13:33:15][Error] Marker render error at Vector3{ x: -1245.6200, y: -3035.4399, z: -48.4800 } (cb: => () spawnVehPosition) NO TYPE NO COL RED NO COL BLUE NO COL GREEN 255, 29.1
bekommen

**Erwartetes Verhalten**
kein dauerspam des error bzw fixen :D

**Comment by its4l3x** [comment]
fixed next update
