### ISSUE TITLE
Motorleistung Dinka Verus

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1714]
Wäre klasse wenn ihr das Ding überarbeiten könntet, es ist ja das ultimative Gelände Quad, aber es kommt Steigungen nicht wirklich hoch....
So ist es nicht nutzbar, die Steigung auf dem Bild kommt es schon nicht mehr hoch und rollt rückwärts...
Es ist in der Endgeschwindigkeit auch sehr Lahm, jeder Roller überholt den Verus...

![Screenshot_38](https://user-images.githubusercontent.com/70241137/126043368-82cb3093-3e47-4633-828e-182efb884ea3.jpg)

EDIT: ein Teil der Tuningoptionen fehlt leider auch (alles Waffenfrei bei dem Fahrzeug). normalerweise kann man vorne und hinten Munikisten etc drauf schnallen...

**Comment by Statev-Bonsai** [comment]
https://www.youtube.com/watch?v=VHWn0vHmGr;D
Hier sieht man es ganz gut, für ein Fahrzeug das dazu gemacht ist Steigungen zu erklimmen ist es sehr Mau :D

**Comment by DonVitoDiangelo** [comment]
changed next update
