### ISSUE TITLE
Perücken Frisurenbug

### ISSUE THREAD

**Issue by Saaria83** [mexyn/statev_v2_issues#1715]
**Character Name**

 Hanna Jung
 
**Auftrittszeitpunkt (Datum / Uhrzeit)**

17.07.2021 ggn 16:00 Uhr

**Beobachtetes Verhalten**

Man sieht die verschiedenen Frisuren als Friseur nicht, der Kunde allerdings schon

**Erwartetes Verhalten**

Das man als Friseur die verschiedenen Perücken beim Kunden auch sieht

**Schritte um den Fehler nachvollziehen zu können**

Man setzt sich beim Friseur auf den Stuhl, benutzt das Friseuroverlay und kann durch die verschiedenen Frisuren swappen

**Comment by Bully90** [comment]
Ich ergänze......  die Frisuren die der Kunde sieht Stimmen nicht überein mit der Liste die der Friseur vor sich hat. Als Beispiel: Undercut mit Waves ist bei dem Kunden ein Afro.....

**Comment by Saaria83** [comment]
Kann ich, durch einen Kunden von gestern, auch so bestätigen. Um das noch mal genau zu sagen. Die Frisuren stimmen nicht mit den Namen überein und als Friseur kann man die wechselnden Frisuren nicht sehen. Farbe, Bärte und Schminke allerdings schon

**Comment by its4l3x** [comment]
fixed, next update.
