### ISSUE TITLE
Fps einbrüche und starke lags auf dem ganzen Server seit dem neuen Update

### ISSUE THREAD

**Issue by schlado** [mexyn/statev_v2_issues#1717]
**Character Name**
Jack_Camora

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.07.2021/ 20 Uhr

**Beobachtetes Verhalten**
Egal wo ich bin und was ich mache ich bekomme immer wieder Fps drops die mich von 70-90 Fps normalerweise auf 11-20 Fps fallen lassen.

**Erwartetes Verhalten**
Es sollte wie vor dem Update sein als man noch ganz gemütlich in die Stadt fahren konnte ohne das mein Spiel sich fast andauernd aufhängt.

**Schritte um den Fehler nachvollziehen zu können**
Einfach im Abend wenn ca. 200 Spieler darauf sind auf dem Server gehen und durch die Städte fahren.

**Optional: Video / Bilder des Fehlers**

**Comment by Dean-Gallagher** [comment]
bekannt, siehe Discord und Tito seine Nachrichten

**Comment by its4l3x** [comment]
Bereits bekannt, schließe weil wir davon alle gerade mitbekommen
