### ISSUE TITLE
Cop Attachments bei Frauen

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1718]
**Character Name**
Amber Reaper & diverse andere

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.07.2021

**Beobachtetes Verhalten**
Amber Reaper hat Cop Kleidung an  (Handschellen & Marke)
Sie selbe kann diese Gegenstände an sich nicht sehen, allerdings alle anderen.
Dies tritt bei diversen Frauen auf, allerdings nicht bei allen.

**Erwartetes Verhalten**
Marke und Handschellen nur im Dienst bei Cops.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://user-images.githubusercontent.com/70150887/126065029-be8752c2-263b-45e1-8f91-cef87886d9b2.png)

![image](https://user-images.githubusercontent.com/70150887/126065031-f92dc801-e438-404e-965d-aaff0febcf16.png)

![image](https://user-images.githubusercontent.com/70150887/126065038-473a8aa9-5026-46e2-bfc0-9e3da73e9c39.png)

**Comment by its4l3x** [comment]
Brauchen bitte den Item-Namen. Dann können wir das fixen.

**Comment by TheBroady** [comment]
> Brauchen bitte den Item-Namen. Dann können wir das fixen.

Der ist nicht bekannt. Die Damen selber können die Attachments auch nicht sehen. Geschweige denn haben sie etwas dergleichen an.
