### ISSUE TITLE
Kleidung verschwinden im "Fashion Killa"

### ISSUE THREAD

**Issue by Afrostatev** [mexyn/statev_v2_issues#1719]
**Felix_Bang**
 Felix_Bang

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 Alt:v 4.0

**Beobachtetes Verhalten**
 Hut,Brille und Uhr verschwinden wenn man in den "Fashion Killa" geht

**Erwartetes Verhalten**
 Alles bleibt wie es ist 

**Schritte um den Fehler nachvollziehen zu können**
 E auf den Marker am Boden :)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
 https://www.youtube.com/watch?v=z1ifpCJPp4o

**Comment by TheBroady** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1711

**Comment by Enemyaa** [comment]
Next Update!
