### ISSUE TITLE
Durch Möbel laufen

### ISSUE THREAD

**Issue by TheMoonicorn** [mexyn/statev_v2_issues#172]
**Character Name**

Maxi Kowa, Freya Michaels 

**Zeitpunkt (Datum / Uhrzeit)**

30.08.20 17:50 Uhr

**Beobachtetes Verhalten**

In der Edel Villa Rustikal kann man durch fast alle Möbel hindurch gehen. Wenn man sich dann in einem Schrank befindet und eine andere Person auf einen schießt, blocken die Möbel das ab. Also zusammengefasst, die Möbel sind so, dass sie Kugeln etc abwehren, aber keine Personen.

**Erwartetes Verhalten**

Normalerweise sollte man nicht durch die Möbel hindurchgehen können.

**Schritte um den Fehler nachvollziehen zu können**

Man kauft ein Haus mit der Größe 3 und baut danach die Edel Villa Rustikal ein. Dann geht man ins Haus und befindet sich im Interior des Hauses. Dort läuft man dann im Haus rum und geht gezielt auf verschiedene Möbel zu, wo man dann durch diese Möbel hindurch gehen kann.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=8fLNwU5n4CA

**Comment by DrGrizzlY17** [comment]
Möbel haben von GTA5 aus keine Kollision
