### ISSUE TITLE
Anschnallen beim Street Blazer

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#1721]
**Character Name**

Sven Rosenbach
**Auftrittszeitpunkt (Datum / Uhrzeit)**

18.07.21 11:00:00
**Beobachtetes Verhalten**

Man hat die Möglichkeit sich beim Street Blazer anzuschnallen
**Erwartetes Verhalten**

Da so weit ich weiß Quads keine Gurte haben sollte man sich nicht anschnallen können
**Schritte um den Fehler nachvollziehen zu können**

Man setzte sich auf ein quad und schnallt sich an

**Optional: Video / Bilder des Fehlers**

https://user-images.githubusercontent.com/58612983/126066026-d7c8582c-4021-4578-8fef-39743b2c9980.mp4

**Comment by DonVitoDiangelo** [comment]
Keine Relevanz, hier wird es keine Änderung geben. Und das hat dann eben einen. :)
