### ISSUE TITLE
Kofferaumgröße Canis Mesa Offroad

### ISSUE THREAD

**Issue by NussEcke1** [mexyn/statev_v2_issues#1722]
Character Name: Rainer Ecke

Anfrage zur Anpassung des Kofferaum's beim Canis Mesa Offroad
Die Kofferaumgröße beträgt 80kg, bei einem preislich vergleichbarem Fahrzeug wie dem Annis Hellion beträgt diese 210kg

![20210718235314_1](https://user-images.githubusercontent.com/81488412/126083399-9e0fab0f-be1b-4623-bf59-a8a42a7532b1.jpg)
![20210718235628_1](https://user-images.githubusercontent.com/81488412/126083401-82afc13f-1cd6-46a3-9c53-9572bd64ded5.jpg)

**Comment by Statev-Bonsai** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1669

**Comment by its4l3x** [comment]
duplicate und siehe #1669
