### ISSUE TITLE
Gamecrash beim Tanken --> Fahrzeug stuck

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1723]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.07.2021 04:30

**Beobachtetes Verhalten**

Tankvorgang --> Während Tankvorgang Gamecrash --> Fahrzeug, wie nach Totalschaden nicht mehr bedienbar

Ähnlich dem : #1518

**Comment by its4l3x** [comment]
fixed next update
