### ISSUE TITLE
Bauchnabelpiercing nicht mehr sichtbar seit Update

### ISSUE THREAD

**Issue by TheMoonicorn** [mexyn/statev_v2_issues#1724]
**Character Name**

Freya Michaels

**Auftrittszeitpunkt (Datum / Uhrzeit)**

19.07. 16:40

**Beobachtetes Verhalten**

Bauchnabelpiercing ist nicht mehr sichtbar

**Erwartetes Verhalten**

Bauchnabelpiercing sollte sichtbar sein

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

früher: https://pic.statev.de/image/20210705170334-1.fQGuC
jetzt: https://pic.statev.de/image/20210719164057-1.fQAAP

**Comment by Enemyaa** [comment]
Next Update!
