### ISSUE TITLE
Handel UI-Bug

### ISSUE THREAD

**Issue by Kennymode** [mexyn/statev_v2_issues#1725]
**Charakter Name**
Domo_East

**Beobachtetes Verhalten**
Das Handel-UI beim Annehmen von Gegenständen lässt sich nicht schließen. Ein Game-Restart ist notwendig.

**Comment by Chrinis007** [comment]
Duplikat von #1703

**Comment by Hutstaender** [comment]
Sind bei einem der beiden handelnden Grafikmods installiert?

**Comment by its4l3x** [comment]
#1727 

duplicate
