### ISSUE TITLE
Fahrzeug aufschließen zum Einsteigen braucht mehrere Versuche

### ISSUE THREAD

**Issue by beugr** [mexyn/statev_v2_issues#1726]
**Character Name**
Rene Beuger

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit dem alt:V Update eigentlich immer.

**Beobachtetes Verhalten**
Wenn man versucht, sein Motorrad oder manchmal sogar andere Fahrzeuge aufzusperren, braucht es mehrere Versuche, einsteigen zu können, weil das Fahrzeug trotz Öffnung immer noch als geschlossen erkannt wird.

Wichtig: Der Fehler tritt nicht immer auf. Manchmal klappts beim ersten Mal, manchmal spinnt es wieder rum. War vor dem Update nie so.

**Erwartetes Verhalten**
Das man das Fahrzeug/Motorrad nur einmal aufschließen muss um einzusteigen, nicht mehrfach.

**Schritte um den Fehler nachvollziehen zu können**
Man nehme sich ein Motorrad oder Auto und versucht dies abzuschließen und dann zu öffnen, um dann irgendwann Einsteigen zu können.

**Optional: Video / Bilder des Fehlers**
https://streamable.com/x13psf

**Comment by AngelMaravilla** [comment]
Kann dasselbe Problem bestätigen. Passiert mir vor allem wenn ich in der Laufbewegung schon das X-Menü öffne – vielleicht hängt es damit zusammen.

**Comment by JannikDatsch** [comment]
Hatte das gestern auch, dass obwohl Fahrzeug offen wahr, ich nicht auf den Fahrersitz einsteigen konnte, Kollege konnte jedoch fahren. Nach einer Zeit war das dann wieder normal.

**Comment by JannikDatsch** [comment]
@AngelMaravilla Das ist tatsächlich wieder anderes, kommt bsp. auch vor, wenn man während einsteigen funkt, und dann aufhört. Aber dass man wie hier gar nicht aufsteigen kann, bzw. gestern nicht einsteigen kann, ist neu.

**Comment by CannaDE** [comment]
Ist mir gestern im Stream auch passiert. Hab maln Clip erstellt. Ich war vorher nicht am funken oder sonstiges. Bin ausgestiegen, hab die Motorhaube auf gemacht und bin zum Mechaniker(in).
https://clips.twitch.tv/BashfulStrangeDillDBstyle-yU4yPmX4Q3MGE274

**Comment by its4l3x** [comment]
Scheint auf zu treten, nachdem alt:V das Update gebracht hatte. Kann jetzt R* liegen oder an alt:V. Wenn ihr einfach kurz 1-2 Sekunden länger wartet, passiert sowas nicht.
