### ISSUE TITLE
Handeln im Sitzen freezed UI und crasht Voice Plugin

### ISSUE THREAD

**Issue by AngelMaravilla** [mexyn/statev_v2_issues#1727]
**Character Name**
Angel Maravilla
Mia Randall

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.07.2021, 21:00 Uhr

**Beobachtetes Verhalten**
Wir saßen beide per Szenario (Y-Menü) nebeneinander auf Stühlen und ich wollte dem anderen Spieler ein Item per Handelsmenü übergeben; in diesem Fall einen Donut. Gut zu erkennen auf der detaillierten Darstellung unten. Sobald wir beiden den Handel akzeptiert hatten, kickt mich das TS-Plugin aus dem Voice Channel zurück in die Eingangshalle und das Handelsmenü-UI fror ein und konnte nicht geschlossen werden. Ich hatte keinen Cursor mehr, konnte die Kamera aber noch drehen und sehen was ingame geschieht. Ich musste das Spiel per Alt-F4 beenden.

Um sicherzustellen, dass es kein einmaliger Zufall war, haben wir den oben beschriebenen Prozess (natürlich RP-gerecht) wiederholt. Diesmal ist jedoch der freeze und Plugin crash nicht bei mir selbst sondern beim anderen Spieler aufgetreten. Auch hier musste per Alt-F4 beendet werden.

Ich bin mir nicht sicher, ob dieser Fehler auch bei anderen Szenarien auftritt.

**Erwartetes Verhalten**
Solange zwei Spieler sitzen in einem Szenario (Y-Menü) sollte Handeln problemlos möglich sein.

**Schritte um den Fehler nachvollziehen zu können**
Zwei Spieler müssen sich in einem Szenario befinden und so nah beieinander sein, dass sie per X-Menü das Handelsfenster aufrufen können. Dann traded man ein beliebiges Item und das UI müsste freezen und man wird aus dem Voice gekickt.
![Screenshot_1](https://user-images.githubusercontent.com/74780492/126213796-41a551c1-c6bc-4a9e-ade0-90872597bd21.jpg)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Chrinis007** [comment]
Duplikat von #1703

**Comment by Hutstaender** [comment]
Sind bei einem der beiden handelnden Grafikmods installiert?

**Comment by its4l3x** [comment]
Problem ist tiefgehender, liegt warsch. im UI, ein riesen Aufwand dort den Fehler zu finden. Fällt erst seit dem alt:V Update auf, davor nie gehabt. Wir versuchen trotzdem alles mögliche. Dauert aber leider.
