### ISSUE TITLE
Parkkralle bei zu vollem Inventar nicht aufnehmbar

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1728]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
20.07 04:00

**Beobachtetes Verhalten**

Ähnlich wie bei #1631:
Parkkralle wiegt 7 kg --> hatte nur 6 kg Inventar frei --> Parkkralle entfernt, ging aber nicht ins Inventar und war verschwunden.

**Comment by its4l3x** [comment]
Du hast laut Code generell nie ein Item zurückgekriegt, nachdem du die Parkkralle entfernt hattest. ^^

**Comment by JannikDatsch** [comment]
Ja, aber normal bekommt man doch die Parkkralle zurück, oder? Die wird ja nicht verbraucht, hab sonst auch ein Video zu.

**Comment by its4l3x** [comment]
Nene, das ist ja das Ding.. Du bekommst nämlich gar keine zurück

**Comment by JannikDatsch** [comment]
Ok, wusst ich gar nicht, dann closed
