### ISSUE TITLE
Vorschlag: Animationen innerhalb der Ordner sortierbar machen

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1729]
**Beobachtetes Verhalten**

Aktuell ist es zwar mgl., die Reihenfolge der verschiedenen Animationsordner im X-Menü zu bestimmen, nicht aber, innerhalb dieser Ordner die Animationen neu anzuordnen

Vorschlag:
Auch innerhalb dieser Ordner , die Animationen sortierbar machen, da da immer neue dazukommen, und man die, wenn man die in eine gewisse Reihenfolge bringen will, den gesamten Ordner neu machen müsste. 

Video:
https://youtu.be/_8i-RPC1phM

--> Hier also nicht nur ersteres, sondern auch letzteres sortierbar machen

**Comment by Hutstaender** [comment]
#684
