### ISSUE TITLE
Firmen Rechte gehen nicht

### ISSUE THREAD

**Issue by RuedigerRommel** [mexyn/statev_v2_issues#173]
Ruediger Rommel

**Zeitpunkt (Datum / Uhrzeit)**
30.08.2020   13:47

**Beobachtetes Verhalten**
Wurde in eine Firma eingeladen volle REchte bekommen konnte aber nichts machen da der Fahler kam keine Berechtigung 

**Erwartetes Verhalten**
Man kann alles in der Firma benutzen. Firmennamen Tyrone ist Coooool

Einladung in eine Firma schicken, Volle rechte vergeben dannoch geht nichts,

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

![Bug Sägewerk](https://user-images.githubusercontent.com/70349694/91667805-78128700-eb07-11ea-9385-e05dcc6d711e.jpg)

https://cdn.discordapp.com/attachments/708425373196615724/749709401710919680/Screenshot_24.png

**Comment by its4l3x** [comment]
Was genau ist das für ein Marker, bzw. was macht man an dem?

**Comment by RuedigerRommel** [comment]
Egal ob der Marker zum einlagern oder in die Maschinen Lagern oder zum Einschalten der Maschine bzw der Produkte

**Comment by its4l3x** [comment]
Ok

**Comment by eiksch** [comment]
Wird getestet - könnte nur temporär fehlerhaft gewesen sein, da das StateNET vielleicht ausgelastet war und die Rechte verschluckt hat o.ä

**Comment by Chrinis007** [comment]
War wahrscheinlich weil die Firma gekauft wurde und ja ein restart benötigt wird um das Interieur nutzbar zu machen

**Comment by RuedigerRommel** [comment]
Alles klar ich teste mbeim nächsten mal nochmal deswegen

Chrinis007 <notifications@github.com> schrieb am Mo., 7. Sept. 2020, 17:05:

**Comment by its4l3x** [comment]
@Chrinis007 neenenene, das ist egal. Wir ändern das mitlerweile in Runtime

**Comment by its4l3x** [comment]
Erneut getestet gehabt - Nicht aufgetreten.
