### ISSUE TITLE
Cliffhanger immernoch sehr anfällig für gegenläufer

### ISSUE THREAD

**Issue by RemboW911** [mexyn/statev_v2_issues#1730]
**Remo_Greifenfels**

**Auftrittszeitpunkt (Datum / Uhrzeit)** 
21.07.2021 03:50 uhr

**Beobachtetes Verhalten** 
Cliffhanger beim gegenlaufen (nicht mal umgekippt) von gerade repariertem zustand zum rauchend und gelbe leuchte

**Erwartetes Verhalten** 
gegenlaufen entweder sie fällt um und es passt alles soweit oder sie sollte von meiner auch stehenbleiden aber sie sollte halt keinen schaden nehmen

**Schritte um den Fehler nachvollziehen zu können** 
Motorad neben sich abstellen und gegenlaufen notfalls auch mehrmahls

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
da das aufnahme programm (Nvidia expirience irgendwie nichts aufnehmen will ka)

**Comment by DonVitoDiangelo** [comment]
nach nächstem update bitte nochmal prüfen

**Comment by RemboW911** [comment]
wer soll das nur alles bezahlen ;(
