### ISSUE TITLE
Tornado Rust Import Name

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#1731]
der neue Tornado Rusty ist nur als Hash im Import 

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/148d878888d11f8145c09e0394c670c0

**Comment by TheBroady** [comment]
![image](https://user-images.githubusercontent.com/70150887/141952548-27cde1e2-cd6c-423d-85ed-571c8cbdd088.png)
Ist immernoch @DonVitoDiangelo 
- 16.11.2021
