### ISSUE TITLE
Pulloveraufdruck auf der Haut

### ISSUE THREAD

**Issue by Minakiu** [mexyn/statev_v2_issues#1732]
**Character Name** Mina Harris

Mina Harris

**Auftrittszeitpunkt (Datum / Uhrzeit)**

22.07.2021 / 23:45 Uhr

**Beobachtetes Verhalten**

komische schriftzüge durch klamotten zu sehen und auf der Haut.

**Erwartetes Verhalten**

das man die schriftzüge nicht sieht

**Schritte um den Fehler nachvollziehen zu können**

.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

.

**Optional: Video / Bilder des Fehlers**

![image](https://user-images.githubusercontent.com/87786538/126570587-5e50ec89-1f5a-46f9-9706-3feb67cc7702.png)

**Comment by Enemyaa** [comment]
Habt ihr einen Nasen oder Bauchnabelpiercing (normalerweise)?e
