### ISSUE TITLE
Man kann nicht mehr als Beifahrer einsteigen

### ISSUE THREAD

**Issue by la0660** [mexyn/statev_v2_issues#1733]
**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TheBroady** [comment]
Mit dem Drücken von "G" geht das schon.
Allerdings gibt es manche Fahrzeuge wo es nicht geht. (Double T)

**Comment by JulianMa** [comment]
Duplicate von #1735
