### ISSUE TITLE
Leute sehen bei mir Schriftzüge die nicht da sind!

### ISSUE THREAD

**Issue by SgtTukiTuki** [mexyn/statev_v2_issues#1734]
![Desktop_Screenshot_2021 07 22_-_00 46 11 51](https://user-images.githubusercontent.com/87803938/126610774-51c42ce4-090f-45ce-80ff-d4d5f8ab480f.png)
![Desktop_Screenshot_2021 07 22_-_00 46 18 08](https://user-images.githubusercontent.com/87803938/126610778-393f8459-efdd-46ef-a65a-042d1f5897ea.png)

**Sandy_Folk**

Steve_Walker hat dieses beobachtet,ich selbst sehe das nicht so!
**22.07.21 1.00Uhr und zwischen 9.30 und 10.30Uhr**

**Comment by CaleighRhodes** [comment]
Sind keine Tattoos, gibt dazu auch schon ein Issue -> #1732

**Comment by Enemyaa** [comment]
Habt ihr einen Nasen oder Bauchnabelpiercing (normalerweise)?

**Comment by CaleighRhodes** [comment]
Ich hab weder das eine noch das andere und habe keine Schriftzüge auf dem Körper. Auch mit modded Klamotten (Grly Jeans und Crop Top neu) keine. Also hast du wohl schon den richtigen Einfall gehabt…
