### ISSUE TITLE
Einsteigen als Beifahrer mit der Taste F erzeugt sofortigen Rauswurf des Fahrers

### ISSUE THREAD

**Issue by SgtTukiTuki** [mexyn/statev_v2_issues#1735]
Festgestellt am 22.07.21 mit Sandy_Folk und Hanna_Jung

Einsteigen mit Taste-F als Beifahrer kickt den Fahrer nun sofort aus dem Auto. 
War vorher nur mit langem drücken der Taste-F möglich!
Mit Taste-G geht aber alles wie gewohnt!

Wie wir aber wissen ist es mit Taste-G nicht immer möglich als Beifahrer vorne einzusteigen und man nutzt die Taste-F dazu!

**Comment by Dean-Gallagher** [comment]
Kann ich mich anschließen, kurz F drücken boxt direkt raus.

**Comment by Saaria83** [comment]
Kann mich da auch anschließen. Entschuldige Sandy :c

**Comment by JulianMa** [comment]
Der Fehler ist bei alt:V bekannt:
https://github.com/altmp/altv-issues/issues/1023

**Comment by JulianMa** [comment]
Laut alt:V behoben
