### ISSUE TITLE
Holster der Waffe wechselt, wenn Waffe in der Hand

### ISSUE THREAD

**Issue by OfcStern** [mexyn/statev_v2_issues#1736]
**Marcel_Stern**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 22.07.2021 / 15:50 

**Beobachtetes Verhalten**
Die Uniform ([130] OFC bis CPL - Klasse C) hat ein Gürtelholster, bei dem die Waffe nicht sichtbar ist.
Nimmt man die Waffe in die Hand, hat die Uniform einen Oberschenkelholster mit "sichtbarer" Waffe.
Steckt man die Waffe wieder ein, hat die Uniform wieder den Gürtelholster ohne sichtbarer Waffe.

**Erwartetes Verhalten**
Sichtbare Waffe beim Gürtelholster, die beim Auswählen der Waffe nicht zum Oberschenkelholster wechselt.

**Schritte um den Fehler nachvollziehen zu können**
Skin auswählen und Waffe herausnehmen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
--

**Optional: Video / Bilder des Fehlers**
![GTA5 Waffe](https://user-images.githubusercontent.com/79868317/126650606-f73f9a60-4ed1-44fd-b11d-b14d4e55069c.png)

**Comment by its4l3x** [comment]
bereits gefixed, mit dem nächsten update.
