### ISSUE TITLE
Dinka Double T kein 2 Sitzer mehr!

### ISSUE THREAD

**Issue by masterppc** [mexyn/statev_v2_issues#1737]
**Character Name**

Hans_Hentschel
**Auftrittszeitpunkt (Datum / Uhrzeit)**

22.07.21 18:30
**Beobachtetes Verhalten**

Beim versuch als 2. Person auf das Bike zu steigen schmeißt man immer den Fahrer runter. Die G Taste reagiert gar nicht und wenn man F nur kurz antippt schmeißt er die Person vom Bike.
**Erwartetes Verhalten**

Mit G oder auch F hinten aufsteigen
**Schritte um den Fehler nachvollziehen zu können**

Das Bike ausparken und versuchen zu 2. drauf zu sitzen.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/lBfMgW2hOJ0

**Comment by masterppc** [comment]
Außerdem kann man anscheinend bei jeden Fahrzeug nu die Leute aus dem Wagen ziehen. Nicht mehr wie damals das man von der Beifahrerseite bei gedrückter F Taste den Fahrer raushaut sondern ihn direkt wie im SP rauszieht.

**Comment by DrGrizzlY17** [comment]
#1733 bereits bekannt mit dem Beifahrer. Sehr wahrscheinlich fixed wenn die Beifahrer sache fixed ist

**Comment by JulianMa** [comment]
Erstmal Closed, Verweis auf #1735
