### ISSUE TITLE
Kariun Kuruma tuning Bremse / Folie

### ISSUE THREAD

**Issue by masmanK** [mexyn/statev_v2_issues#1738]
**Character Name**
Van Blake

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.07.2021 19;25

**Beobachtetes Verhalten**
Beim Kuruma Bremsen tuning kommt Folie aufs auto und beim Folie passiert ganr nichts
Ausserdem ist die hupe sehr Weihnachtlich 

**Erwartetes Verhalten**
Fixen des Probelms

**Schritte um den Fehler nachvollziehen zu können**
Bin in deine Werrkstatt gefahrne und wollte mein auto tunen da ist es mir aufgefallen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by MrMutantus** [comment]
Ich hätte noch hinzuzufügen, dass ein getunter Kuruma auch verändert wurde.
Hatte vorher keine Folie und eine andere Hupe.
Hier noch ein Video dazu:
[Kuruma undercover](https://youtu.be/THFV2AAh6lM)

**Comment by its4l3x** [comment]
Bekannt - ist ein alt:V Bug, wir warten auf den Fix.
