### ISSUE TITLE
Einsteigen auf den Fahrersitz mit "F" nicht möglich, ohne Fahrer herauszuschlagen

### ISSUE THREAD

**Issue by ArnoZuDemB** [mexyn/statev_v2_issues#1739]
**Character Name**
Arno Bjerg

**Auftrittszeitpunkt (Datum / Uhrzeit)**
immer

**Beobachtetes Verhalten**
Beim Einsteigen mit "F" wird der Fahrer immer aus dem Fahrzeug gestoßen. Dies passiert unabhängig bei Antippen sowie gedrückthalten der Taste

**Erwartetes Verhalten**
Herkömmliches Einsteigen auf dem Beifahrersitz, ohne den Fahrer aus dem Fahrzeug zu werfen.

**Schritte um den Fehler nachvollziehen zu können**
In eine Fahrzeug mit Fahrer Einsteigen (mit "F")

**Comment by CaleighRhodes** [comment]
Doppelt, Siehe #1733
