### ISSUE TITLE
Verwendung mehrer Gegenstände

### ISSUE THREAD

**Issue by RuedigerRommel** [mexyn/statev_v2_issues#174]
Ruediger Rommel

29.08.2020  15:45
**Beobachtetes Verhalten**
WEnn man z.b. eine Fackel in der Hand hat und nimmt was anderes in die hand schwebt die fackel frei in der Luft.

**Schritte um den Fehler nachvollziehen zu können**
Haben eine Fackel in der Hand und nehmen eine Bohrmaschine dazu dann schwebt die Fackel geht auch mit verschiedenen Animationen.
![Bug 2](https://user-images.githubusercontent.com/70349694/91668067-b90b9b00-eb09-11ea-94f1-3470715a9914.jpg)

**Comment by tastydev** [comment]
GTA standard Verhalten bei Waffen und Animationen. Nichts von uns daher close.
