### ISSUE TITLE
Getätigter Notruf kann nicht beendet werden

### ISSUE THREAD

**Issue by beugr** [mexyn/statev_v2_issues#1740]
**Character Name**
Rene Beuger

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.07.2021, 23:00 Uhr

**Beobachtetes Verhalten**
Wenn ich einen Notruf absetze, ändert sich das Interface nicht. Es bleibt bei "Notruf Absetzen" und man kann diesen auch nicht mehr abbrechen. Das Handy weglegen, ausschalten etc. bringt nichts.

**Erwartetes Verhalten**
Es sollte wie sonst auch die Möglichkeit zum auflegen geben.

**Schritte um den Fehler nachvollziehen zu können**
1. Handy raus
2. Notruf -> Polizei
3. Freuen das es nicht geht

**Optional: Video / Bilder des Fehlers**
https://i.imgur.com/F8L7WUG.jpeg

**Comment by its4l3x** [comment]
Ist ein temporäres Problem gewesen, ist auf Zukunft behoben, kann aber auch während der Runtime gelöst werden.
