### ISSUE TITLE
Schlagen mit waffe in hand wieder möglich

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#1742]
**Character Name**
Dean

**Beobachtetes Verhalten**
mit taser, 1 Person stand direkt vor mir, habe mit Taser zugeschlagen auf die Person was laut changelog vom 13.05 nicht mehr gehen sollte

**Comment by Hutstaender** [comment]
Man kann nur Schlagen, wenn der Charakter sich im Kontermodus befindet, also wenn dich z.B. jemand zuerst schlägt. Sonst konnten wir das nicht nachstellen. Falls du nen Tipp hast wie man es Auslösen kann, meld dich gerne nochmal. Sonst mach ich den Eintrag demnächst zu.
