### ISSUE TITLE
Charakter stehen still wenn geschlagen

### ISSUE THREAD

**Issue by beugr** [mexyn/statev_v2_issues#1743]
**Character Name**
n.V.

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Seit dem alt:V Update.

**Beobachtetes Verhalten**

Personen, welche geschlagen werden, haben keine anständige Animation mehr. Schlagen macht daher natürlich weniger Spaß, weil man einfach still steht.

**Erwartetes Verhalten**

Das Charaktere sich bewegen wie sonst auch wenn diese geschlagen werden.

**Schritte um den Fehler nachvollziehen zu können**

Prügelt euch mit jemanden.

**Optional: Video / Bilder des Fehlers**

Der Fehler ist in diesem VOD ab Stunde 3:55:30 gut zu sehen https://www.twitch.tv/videos/1095662451

**Comment by Dean-Gallagher** [comment]
bekannt, alt V problem müssen auf deren fix warten
zumal bitte keine VODs nehmen für sowas welche man den streamer abonieren muss ^^

**Comment by beugr** [comment]
> bekannt, alt V problem müssen auf deren fix warten
> zumal bitte keine VODs nehmen für sowas welche man den streamer abonieren muss ^^

Achso, ja gut, wusste nicht das seine VODs Sub-only sind.

**Comment by its4l3x** [comment]
Fixed seit dem alt:V Update von vor 2 Tagen
