### ISSUE TITLE
Pullover Aufdruck bleibt am Körper

### ISSUE THREAD

**Issue by NeedManu** [mexyn/statev_v2_issues#1744]
**Character Name**
Amber Reaper

**Auftrittszeitpunkt (Datum / Uhrzeit)**
24.07.2021 20:30 Uhr

**Beobachtetes Verhalten**
Aufdruck von einem Pullover bleibt auf dem Körper
Etwas ausziehen/anziehen bringt nichts.
Reloggen funktioniert auch nicht.

**Erwartetes Verhalten**
Keine Aufschrift

**Schritte um den Fehler nachvollziehen zu können**

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/81923141/126878141-e4f0fa93-3a55-4d79-a4ef-75b2b2002a04.png)

**Comment by CaleighRhodes** [comment]
Bereits gemeldet, #1734
