### ISSUE TITLE
Werkzeuggürtel verwandelt sich in Holster / Magazine (optisch)

### ISSUE THREAD

**Issue by ShauniKT** [mexyn/statev_v2_issues#1746]
Shauni Teller

**Auftrittszeitpunkt (Datum / Uhrzeit)**

24.07.2021

**Beobachtetes Verhalten**

Nach einer Weile verwandelt sich der Werkzeuggürtel für frauen in ein Holster. Genaue Gründe oder evtl triggernde ereignise werden noch erforscht und nachtraglich angebracht. Dies sehe ich selbst, allerdings andere nicht.
(die sehen bei mir nur den bereits bekannten Aufkleber/Tattoobug oder die Polizeimarke. Ka ob es da einen zusammenhang gibt)

**Erwartetes Verhalten**

Das ich für mich und andere normal aussehe

**Schritte um den Fehler nachvollziehen zu können**

Als Frau Werkstattgürtel anziehen und warten

**Optional: Video / Bilder des Fehlers**

[https://puu.sh/HYQ31/7a5dbf8342.jpg](url)

Item: [F][O] Mechaniker Gürtel, braun

**Comment by Enemyaa** [comment]
Ich geh mal davon aus, dass du den Wink mit dem Zaunpfahl nicht verstanden hast liebe Shauni und der heilige Johannes dir erneut etwas zusandte, damit du dein Schicksal "Cop zu werden" endlich in die Hand nimmst, nach dem die Dienstmarke schon nichts brachte.

**Comment by ShauniKT** [comment]
Der heilige Johannes kennt mich wohl nicht gut genug um zu wissen, daß dies in diesem Leben nie eine Option fur shauni sein wird.

**Comment by Enemyaa** [comment]
@ShauniKT Achte mal drauf, ob es jetzt noch passiert. Die Holster wurden gestern gefixt!
