### ISSUE TITLE
Nummernschild Fehler

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1747]
Unangemeldete Fahrzeuge die STATEV als Nummernschild hatten haben auf einmal irgendwelche Nummernschilder...

![Screenshot_13](https://user-images.githubusercontent.com/70241137/126900937-ae646a64-c521-4be2-b73e-d280e05b6a0d.jpg)

Das betrifft alle STATEV Nummernschilder,,,

**Comment by its4l3x** [comment]
bereits gesolved, brauchst kein ticket dazu aufmachen...
