### ISSUE TITLE
Klo Benutzung im Haus

### ISSUE THREAD

**Issue by RuedigerRommel** [mexyn/statev_v2_issues#175]
Ruediger Rommel

30.08.2020  13:51
WEnn ich in meinem Haus die Toilette benutzen will sitz ich neben dran

**Erwartetes Verhalten**
ich setze mich auf die Toilette

**Schritte um den Fehler nachvollziehen zu können**
Haus Kaufen beste Einrichtung gekauft dann in die Toilette und Mit y sitzen benutzen

![Bug Haus](https://user-images.githubusercontent.com/70349694/91668227-7054e180-eb0b-11ea-9a92-424980c4653c.jpg)

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
@RuedigerRommel wie heißt das Interior?

**Comment by DrGrizzlY17** [comment]
![20200830233501_1](https://user-images.githubusercontent.com/70150988/91669972-7c47a000-eb19-11ea-9373-4d1836c26552.jpg)

Problem konnte nicht nachgestellt werden

**Comment by RuedigerRommel** [comment]
Bin mir nicht sicher müsste aber das letzte gewesen sein mit dem ausblick

DrGrizzlY17 <notifications@github.com> schrieb am So., 30. Aug. 2020, 23:29:
