### ISSUE TITLE
Voice Funktioniert nicht 

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#1750]
**Character Name**

Sven Rosenbach
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Nach 15 Uhr Restart 25.07.21
**Beobachtetes Verhalten**

Kann nicht mehr dem LiveVoice beitreten. PlugIn schon neu Installiert, AltV komplett neu Installiert, PC mehrfach neugestartet, mit komplett neuer TS Identität probiert nichts hat geholfen. Mit F5 kommt auch keine Meldung, dass es einen Fehler gibt o.ä.
**Erwartetes Verhalten**

Kann dem Voice Joinen
**Schritte um den Fehler nachvollziehen zu können**

Update runterladen und pech haben. 

**Optional: Video / Bilder des Fehlers**

https://streamable.com/da11zs

**Comment by AxelAichinger** [comment]
Ich habe ganau das selbe Problem bei mir

**Comment by theSiixx** [comment]
+1

**Comment by SHaagmann** [comment]
Konnte es bei mir Fixen, in dem ich meine Waffen/Fallschirm entrüstet habe und anschließend das Spiel neugestartet habe.

**Comment by its4l3x** [comment]
Ist bereits seit 2 Tagen gefixed.
