### ISSUE TITLE
Reaction Corp Autohaus Marker nicht vorhanden

### ISSUE THREAD

**Issue by cadpri** [mexyn/statev_v2_issues#1751]
**Character Name**
Fabian Picard

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.07.2021 circa 17:15

**Beobachtetes Verhalten**
Ich wollte im Autohaus ein Auto kaufen. Die einzigen Marker die vorhanden waren war der Ausgang Marker und der Stempeluhr Marker. Alle anderen waren nicht vorhanden und auch nicht unsichtbar, wir haben versucht sie zu benutzen aber nichts ging

**Erwartetes Verhalten**
Marker sollten vorhanden sein und funktionieren

**Schritte um den Fehler nachvollziehen zu können**
Ins Autohaus von Reaction Corp gehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
Da es beim Käufer als auch beim Verkäufer auftrat glaube ich nicht, dass es an der Monitorauflösung liegt

**Optional: Video / Bilder des Fehlers**
Bilder reiche ich morgen nach, da ich aktuell nicht mehr einloggen kann

**Comment by its4l3x** [comment]
Fixed.
