### ISSUE TITLE
Haare clippen durch Cap

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1752]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.07.21 18:14

**Beobachtetes Verhalten**
Haare klippen durch die Cap

**Erwartetes Verhalten**
Haare clippen nicht durch

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/70150887/126905946-455ca5ce-58a0-45f1-93e3-58b4ae74f975.png)

**Comment by its4l3x** [comment]
Ist bereits bekannt und da wird auch an einer neuen und geileren Lösung gearbeit.

**Comment by Koree7** [comment]
Cap aus- und wieder anziehen klappt nicht mehr? Sonst wars immer so, dass die Cap das letzte Kleidungsstück ist, welches angezogen werden muss, damit die Haare nicht clippen

**Comment by TheBroady** [comment]
> Cap aus- und wieder anziehen klappt nicht mehr? Sonst wars immer so, dass die Cap das letzte Kleidungsstück ist, welches angezogen werden muss, damit die Haare nicht clippen

nope geht beides nich

**Comment by TamiGaming** [comment]
Gleiches gilt auch für Frauen bei der Raiders Cap und Strapback Caps.
![image](https://user-images.githubusercontent.com/40512639/127109642-8d529869-f883-43db-9379-c2d203105a85.png)
