### ISSUE TITLE
Nach abhostern der Waffe, aus Voice gekickt und Interaktionen mit Fahrzeug nicht mehr möglich

### ISSUE THREAD

**Issue by NeedManu** [mexyn/statev_v2_issues#1753]
**Character Name**
Martin Henks

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.07.2021 18:40

**Beobachtetes Verhalten**
Ich stieg von meiner Sanchez ab, will die Waffe entholstern, währenddessen ist das Bewegen des Charakters nicht möglich.
Nach dem Entholstern, als der Ladebalken bei 100% steht, bleibt dieser auch sichtbar, ich werde aus dem Voice gekickt und muss mein Game neustarten.

**Erwartetes Verhalten**
Abholstern, währenddessen Charakter bewegen, nicht aus dem Voice gekickt werden

**Schritte um den Fehler nachvollziehen zu können**
Waffe entholstern

**Optional: Video / Bilder des Fehlers**
https://youtu.be/gm_U4KtxTS8

**Comment by its4l3x** [comment]
Ist mitlerweile gefixed - Trotzdem ist hier der gleiche Bug, wie beim Trading. Scheint ein alt:V Issue mit zu sein. Prüfen das bereits.
