### ISSUE TITLE
Waffe ohne Seriennummer

### ISSUE THREAD

**Issue by DerFlo123** [mexyn/statev_v2_issues#1754]
Florian_Schroeder

**Auftrittszeitpunkt (Datum / Uhrzeit)**

24.07.2021
**Beobachtetes Verhalten**
Ich hatte eine Waffe die ganze zeit ausgerüstet als ich sie gestern vom Holster nahm hatte sie keine Serienummer mehr
diese wurde nicht von einen NPC entfernt sondern ist einfach weg.

**Erwartetes Verhalten**

Waffe wird vom Holster genommen und es wird Name, Gewicht, und Serienummer angezeigt. Waffe ist am 18.07.2021 mit Serienummer Gekauft worden.
**Schritte um den Fehler nachvollziehen zu können**

ich weis nicht wie man den Fehler nachstellen könnte denn ich vermute er ist durch ein Patch aufgetreten.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

!920x1080

**Optional: Video / Bilder des Fehlers**

![Waffe ohne sehriennummer](https://user-images.githubusercontent.com/87943849/126907253-a5b3274c-5ef0-4e49-952e-f21af02c46d9.PNG)

Serienummer: 4382979878795572.

Mir ist das selber mit einer 2. Waffe passiert. Hier ist ein Clip. Ich weis nicht wieso das passiert. Waffe wurde auch am 18.07.2021 Gekauft
Serienummer: 3699381956193676.

https://user-images.githubusercontent.com/87943849/127047460-9d11cb9b-064a-47c7-9882-e87f1a93470f.mp4

**Comment by MarcelMuerto** [comment]
Ist mittlerweile bei mehreren Person aufgetreten. @its4l3x

**Comment by its4l3x** [comment]
Jo und auch fixed

**Comment by DrUnbelievable** [comment]
Ist mir gerade wieder passiert, also noch nicht fixed
