### ISSUE TITLE
Rappelkisten Fehler

### ISSUE THREAD

**Issue by Cashiflux** [mexyn/statev_v2_issues#1755]
**Character Name**
Frank_Kruger

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.07.2021 / 1845

**Beobachtetes Verhalten**
Nach dem Einlegen der Sammelfiguren und eintauschen dieser, war es nicht möglich die Rubine aufzunehmen. Da gesagt wird das der Prozess noch im gang ist. Genau so war es nicht möglich die Rappelkiste wieder aufzunhemen. 

**Erwartetes Verhalten**
Nach Abschluss des Umtauschens, sollte man einfach die Rubine in sein Inventar bekommen, sowie die Kiste wieder ohne Probleme aufnehmen können.

**Schritte um den Fehler nachvollziehen zu können**
-

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
-

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=fs2cGsB0eZ0

**Comment by its4l3x** [comment]
fixed next update

**Comment by RomanSpielberg** [comment]
Oh nein, habe gerade das gleiche Problem ... gibt es eine Chance auf Erstattung? Video und Screenshot liegen vor ...

**Comment by Cashiflux** [comment]
probiere es im support.

**Comment by PhantomSeventyEight** [comment]
Wenn man mehr als 9 dosen im inventar hat sind alle weg nicht nur 9 als info
