### ISSUE TITLE
Villa eingang+Terasse 

### ISSUE THREAD

**Issue by MrsPxtn** [mexyn/statev_v2_issues#1756]
♡ Paxton Family. ♡ - South Mo Milton Drive 165
Haushash | house_VinewoodHills_157

Der "Garten" ist von beiden Türen nicht begehbar, man muss klettern.. Wäre es möglich diese zugänglich zu machen ? 
Außerdem kann man 2 Terassen nicht betreten, nur durch klettern & objekte möglich.
Vielen Dank für die Aufmerksamkeit und vorträglich für die Hilfe. <3

Mila Paxton

**Comment by DonVitoDiangelo** [comment]
Nein, leider nicht möglich, da die Collisions noch vorhanden wären. Wird daher so bleiben müssen.

**Comment by Enemyaa** [comment]
Next Update!
