### ISSUE TITLE
Vapid Slamtruck - Flatbed Funktionalität fehlt

### ISSUE THREAD

**Issue by 48619** [mexyn/statev_v2_issues#1757]
**Beobachtetes Verhalten**
Beim Vapid Slamtruck fehlt trotz Seilwinde und Rampe die "Flatbed" Funktionalität.
Fahrzeuge können nicht auf den Truck geladen werden.
Genauso ist der Kofferraum zu klein für die Auslieferung von Neufahrzeugen zum Autohaus.

**Erwartetes Verhalten**
Fahrzeug hinter dem Slamtruck parken und aufladen.
Kofferraum lässt sich mit Neufahrzeugen beladen.
Gleches Verhalten/Funktionalität wie beim original Flatbed.

**Comment by DonVitoDiangelo** [comment]
Wird es für dieses Fahrzeug auch nicht geben.

**Comment by 48619** [comment]
StateV hat sich aktiv dazu entschieden dieses Fahrzeug auf den Server zu bringen, Funktionalitäten die offensichtlich zu diesem Fahrzeug gehören werden allerdings verwehrt.
Dieses wurde, soweit mir bekannt, nirgendwo dokumentiert.

**Comment by Chrinis007** [comment]
Die Funktion wird es wohl auch bis auf weiteres nicht geben.
Ist ja ne Entscheidung vom Team :)

**Comment by WaDuTv** [comment]
Möchte mich bei dem Thema auch noch mal reinhängen. 

Der Slamtruck IST ein Abschlepper. Wenn das nicht vorhanden sein der EINZIGEN Funktion, die dieses Fahrzeug irgendwie interessant bzw. sinnvoll macht, bewusst erfolgt ist, muss ich leider sagen: Fail. Der Slamtruck hat 180Kg Ladefläche, laut Wiki. WO soll denn auf einer abgeschrägten "Ladefläche", die zudem eine abgeschrägte, klar als Fahrzeugrampe zu erkennende Fläche ist, bitte Sachen verstaut werden, ohne Kannte am Ende, die die Ladung vorm herunterfallen bewahren würde?

Beim Utility Truck wurde die geringe Ladungskapazität damit gerechtfertigt, dass die Ladefläche verkleinert ist, weil dort Fächer etc. verbaut sind. Und hier? Hier gibt es nicht mal eine Ladefläche, AUSSER für Fahrzeuge.

Ich bitte deshalb auch nochmal darum, diese Entscheidung zu überdenken und dem Slamtruck seine (einzig passende) Funktion zu geben, nämlich die, ihn als Abschleppfahrzeug, ähnlich wie den Flatbed nutzen zu können. Verpackte Autos damit zu transportieren zu können ist unnötig, dafür reicht ein Flatbed. Wir reden immer von RP und dass alles möglichst realitätsnah sein soll und angemessen etv. Werkstätten, wie San Andreas Customs, MagicX und natürlich auch Bennys würden sich über ein Abschleppfahrzeug freuen, dass auch zu einer solchen Tuningwerkstatt passt. Zumal der Slamtruck auch noch die passenden Folierungen für die genannten Werkstätten hat und somit auch noch RP-technisch mega Sinn machen würde, wenn diese Werkstätten sich eben auch "representen" könnten.

Liebe Grüße und inständiges Bitten 

Doc Kev ;)

**Comment by Schnarch** [comment]
Moin, wollte auch gerade ein Ticket eröffnen. Haben einen Slamtruck gebaut aufgrund der Abschlepp funktion. 
Jetzt hat der offensichtliche Truck gar keine Möglichkeit Fahrzeuge abzuschleppen. 
Bitte die Funktion aktivieren, ist ja schließlich offensichtlich ein Abschlepp Fahrzeug.
Grüße

**Comment by JulianMa** [comment]
Wir haben das Abschleppsystem auf das neue Attachment System von alt:V umgebaut und dabei entschieden, den Slamtruck auch direkt mit einzubauen. Mit dem nächsten größeren Update wird es den also nun doch geben.

**Comment by JulianMa** [comment]
Bitte bedenkt aber, das der Slamtruck eine wesentlich kleinere Ladefläche als der flatbed hat und dementsprechend auch nur etwas kleinere Fahrzeuge abschleppen kann.
