### ISSUE TITLE
Friseurbug besteht weiterhin.

### ISSUE THREAD

**Issue by Saaria83** [mexyn/statev_v2_issues#1758]
Hanna Jung, Emilia Rose

**Auftrittszeitpunkt (Datum / Uhrzeit)**

25.07.2021 ggn. 20:00 Uhr

**Beobachtetes Verhalten**

Emilia Rose wollte einem Kunden den "gelockten Bob" frisieren aber die Frisur "Loc Bob" kam dabei raus.

**Erwartetes Verhalten**

Das die Frisur entsteht, die man sich ausgesucht hat

**Schritte um den Fehler nachvollziehen zu können**

Man setzt sich auf den Friseurstuhl, sucht sich im Katalog eine Frisur aus und bekommt diese auch vom Friseur gemacht

**Optional: Video / Bilder des Fehlers**

![Gelockter Bob](https://user-images.githubusercontent.com/70151476/126910426-e09e4e0c-88fb-4343-9684-92a705766c4e.png)
 Das ist die Frisur gewesen die man wollte
![Loc Bob](https://user-images.githubusercontent.com/70151476/126910436-76612133-4977-44f9-a8f9-23694d45e781.png)
Das ist die Frisur die dabei raus kam

**Comment by M4rvinLP** [comment]
Kann ich so bei einer anderen Frisur auch bestätigen. Ist allerdings tatsächlich nicht bei jeder Frisur so.

**Comment by LeonieLL** [comment]
Kann von Anna Black bestätigt werden. Zusätzlich hat man keine Option, Augenbrauen bearbeiten zu können.

**Comment by Saaria83** [comment]
> Kann ich so bei einer anderen Frisur auch bestätigen. Ist allerdings tatsächlich nicht bei jeder Frisur so.

War grade auch bei Fawkes und die haben das auch. Einer wollte den Pomp Undercut und bekam die zusammengebundenen Dreads

**Comment by Enemyaa** [comment]
Das Problem is n bissi tricky. Auf dem Dev funktioniert nämlich alles einwandfrei!

**Comment by EmmaSvensson** [comment]
Hatte selbst als Eigentümerin das Problem und uns ist dabei aufgefallen das jede 2. Frisur die in unserem Friseur gemacht wurde dieses Fehler aufweist.

**Comment by its4l3x** [comment]
Besteht das Problem immer noch?

**Comment by Saaria83** [comment]
Ich habe gestern bei UniCut eine Frauenfrisur gemacht und die ging problemlos. Es handelte sich um "Mittellang mit Bangs"

**Comment by Enemyaa** [comment]
Next Update!
