### ISSUE TITLE
Pfister Comet extrem langsam (im verhältnis zum Preis und wie es davor war.)

### ISSUE THREAD

**Issue by Michi993** [mexyn/statev_v2_issues#1759]
**Character Name**
Luke Hammer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.07.2021 21 Uhr
**Beobachtetes Verhalten**
Pfister Comet fährt extrem langsam (unverhältnismäsig, da er für den preis eine deutlich höhere leistung verdient hätte (wie davor) hat jedoch kein gutes handling, was die leistung kompensieren würde).

**Erwartetes Verhalten**
Comet fährt so schnell wie sonst auch.

**Schritte um den Fehler nachvollziehen zu können**
Ins auto setzen und Fahren.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Was für ein Comet genau ist das?

**Comment by DonVitoDiangelo** [comment]
Aktuell gehen wir davon aus, das es eventuell durch das Tuning Update mehr Einflüsse auf Handling und Speed gibt.
Oder eben das Handling generell überarbeitet wurde, von GTA aus, da wir nichts angepasst haben.
Nach einem Check der Daten kann ich allerdings keine Änderungen feststellen und auch auch dem Dev Server fährt der comet2 seine 250-206 km/h max.

Versucht es einfach mal noch einmal und gebt erneut Rückmeldung. Scheint auch bis dato, nur bei diesem Fahrzeug aufzutreten.
Bitte geht auch sicher, das euer Fahrzeug ganz ist.

**Comment by Michi993** [comment]
Habe es heute erneut getestet. Fahrzeug vom Handling etc. noch gleich, allerdings von der Geschwindigkeit viel langsamer.

**Comment by DonVitoDiangelo** [comment]
was heißt denn viel langsamer? habt Ihr vllt. Video Vergleiche, bzw. ein Video, welches das Problem aufzeigt?

**Comment by Michi993** [comment]
Ist vorhanden (mit vorher/nacher vergleich) werde ich so gegen 16/17 uhr adden

**Comment by Michi993** [comment]
Vorher: https://clips.twitch.tv/AgileResilientTruffleRaccAttack-QY2_ElYEgdc7e4c0
Nacher: https://youtu.be/6Q8AloieyRg

**Comment by epichalt** [comment]
Also ich weiß, dass der Comet vorher OHNE Bodenwellen 250kmh gefahren ist. Was mMn etwas unbalanced war, da er schneller war als viele Supersportler. 
Aber im zweiten Video erkennt man ganz gut, dass er langsamer geworden ist, wobei er jetzt ähnlich schnell ist wie der Comet SR. 
Dementsprechend finde ichs eigl nur komisch, dass die Geschwindigkeit sich geändert hat obwohl eigl nichts geändert wurde. Aber ich habe noch von keinem anderen Fahrzeug gehört, dass es sich so stark geändert hat im Vergleich zu vor dem Update.

**Comment by DerVerruecke** [comment]
Gibt es was neues zu dem Comet oder noch nicht ??

**Comment by DonVitoDiangelo** [comment]
next update , angepasst
