### ISSUE TITLE
Lackiermenu mit Farbcode + Name

### ISSUE THREAD

**Issue by 48619** [mexyn/statev_v2_issues#176]
**Beobachtetes Verhalten**
Im Lackiermenu werden nur Farbcodes angezeigt, es ist schwer zu wissen welche Farbe welche ist.

**Erwartetes Verhalten**
Zumindest den Farbcode + Namen im Menu anzeigen lassen damit man nicht raten muss wie die Farbe heißt.
Eine Liste der Farbcodes + Namen gibt es bei altV direkt https://wiki.altv.mp/Colors_(Vehicle)

**Comment by r3sist3nt** [comment]
Da ich da sowieso gerade dran war, hab ich das eingebaut
