### ISSUE TITLE
Fahrzeug fährt nicht mehr so wie vorher.

### ISSUE THREAD

**Issue by DerVerruecke** [mexyn/statev_v2_issues#1760]
**Mason Street**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.07.2021  21:00 Uhr

**Beobachtetes Verhalten**
Der Pfister Comet fährt seit denn letzten Kleinen Updates langsamer und fährt sich generall anders.
Vor denn Updates fuhr der 250 Km/h und jetzt nur noch fast 220 Km/h.

**Schritte um den Fehler nachvollziehen zu können**
Das war erst gewesen nach denn kleinen Updates. Vielleicht ist ja da ein Fehler drine seit dem Update.

**Comment by Chrinis007** [comment]
#1759 duplikat

**Comment by DerVerruecke** [comment]
> #1759 duplikat

??

**Comment by its4l3x** [comment]
duplikat von #1759

**Comment by DonVitoDiangelo** [comment]
Aktuell gehen wir davon aus, das es durch das Tuning Update mehr Einflüsse auf Handling und Speed gibt.
Oder eben das Handling generell überarbeitet wurde, von GTA aus, da wir nichts angepasst haben.
Nach einem Check der Daten kann ich allerdings keine Änderungen feststellen und auch auch dem Dev Server fährt der comet2 seine 250-206 km/h max.

**Comment by Michi993** [comment]
ist vorhanden (mit vorher nacher vergleich) werde ich so gegen 16/17 uhr hinzufügen
