### ISSUE TITLE
Comet fährt deutlich langsamer

### ISSUE THREAD

**Issue by GymKong** [mexyn/statev_v2_issues#1761]
**Jim Koenig**

Jim Koenig
**Auftrittszeitpunkt (Datum / Uhrzeit)**

25.07.2021 119Uhr
**Beobachtetes Verhalten**

Der Comet fährt nach den kleinen Updates unverhältnismäßig langsamer im Gegensatz zu vorher.
**Erwartetes Verhalten**

Normalerweise fährt der Comet aus eigener Kraft 250-260kmh und hat auch eine deutlich bessere Beschleunigung.
**Schritte um den Fehler nachvollziehen zu können**

Selbst fahren

**Comment by Chrinis007** [comment]
Duplikat von #1759 und #1760

**Comment by its4l3x** [comment]
duplicate siehe @Chrinis007
