### ISSUE TITLE
Dinka Verus Reparatur

### ISSUE THREAD

**Issue by DrColgate** [mexyn/statev_v2_issues#1762]
**Character Name**
Anton Mueller

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.07.21

**Beobachtetes Verhalten**
Ich benötige 2 reparaturkästen zum reparieren

**Erwartetes Verhalten**
nur einen benötigen

**Schritte um den Fehler nachvollziehen zu können**
dinka verus kaputt machen und mit einem reparaturkasten reparieren

für meinen geschmack, geht dieses fahrzeug viel zu schnell kaputt. wenn man damit durchs gelände fährt, reicht schon ein stein aus und es qualmt(gelbe kontrolllampe). wäre super wenn ihr euch das nochmal anschauen würdet. danke!

**Comment by DrColgate** [comment]
gerade nur 1 benötigt

**Comment by DonVitoDiangelo** [comment]
Ja, zum reparieren benötigt man einen Kasten.  Wird nach dem nächsten udpate nicht ehr so schnell kaputt gehen.
