### ISSUE TITLE
Durchsuchung verbuggt

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1763]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.07 00:00

**Beobachtetes Verhalten**
Beim Durchsuchen wird zwar das "gegnerische" Inventar angezeigt, aber die eigenen Waffenslots, zudem fehlt auch der Rucksack des Gegenüber

**Erwartetes Verhalten**
Gegnerische Waffenslots und auch Rucksack sichtbar

**Schritte um den Fehler nachvollziehen zu können**
Siehe Vid 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/X2aQyaitA5Y

**Comment by its4l3x** [comment]
fixed next update
