### ISSUE TITLE
Parkkralle konnte nicht gelöst werden

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1766]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.07 17:30

**Beobachtetes Verhalten**
Parkkralle konnte trotz vorhandener Brechstange nicht vom Fahrzeug gelöst werden. Kollege hat es davor auch schon probiert.

**Erwartetes Verhalten**
Parkkralle wird gelöst

**Schritte um den Fehler nachvollziehen zu können**
Siehe Vid

https://youtu.be/pPPKdPN-pXE

**Comment by its4l3x** [comment]
Bitte lege das Item nochmal in den Inventar und schreib mir dann sobald du das gemacht hast auf Discord bitte. 

Muss was gegenchecken, damit ich das fixen kann...

**Comment by its4l3x** [comment]
sollte fixed sein nächstes update
