### ISSUE TITLE
Keine Extras bei Grove St. Flanellhemd

### ISSUE THREAD

**Issue by Afrostatev** [mexyn/statev_v2_issues#1768]
**Character Name**
 Felix_Bang

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 Seit immer?

**Beobachtetes Verhalten**
 Grove St./Ballas Flanellhemd hat nicht die Extras Funktion im Kleidungsmenü (Anhang Broady: Schwarze Trickster Collagejacke hat auch keine Extras)

**Erwartetes Verhalten**
Extras verfügbar

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=5iX_QDqXiDM

**Comment by Enemyaa** [comment]
Next Update!
