### ISSUE TITLE
Tattoovorlage wurde anders Angezeigt

### ISSUE THREAD

**Issue by SgtTukiTuki** [mexyn/statev_v2_issues#1769]
Gesehen mit Sandy_Folk am 27.07.2021 um ca 21.30 Uhr

Kunde im Tattooladen wollte sich Tattoos anschauen, dabei ist mir aufgefallen das bei einigen Vorlagen der Name nicht mit dem Tattoo übereinstimmt... Kann es sein das dort ein Bug besteht? Hab den Kunden erstmal auf morgen vertröstet, weil ich das Risiko nicht eingehen wollte das dort ein falsches Tattoo bei rauskommt. Da ich auch im Friseurladen arbeite und dort ja auch Probleme bestehen möchte ich mich absichern!

Bilder sind leider nicht vorhanden aber ich denke es ist verständlich was ich damit sagen möchte!

**Comment by Enemyaa** [comment]
@SgtTukiTuki Können wir so nicht nachstellen. Weöche Tattoos sollen denn ein falschen Namen haben? Bitte mal notieren oder aufnehmen.

**Comment by SgtTukiTuki** [comment]
war wohl kurzfristiger anzeigefehler! Funktioniert alles wieder!
