### ISSUE TITLE
Idee Suchfunktion im Gehstilmenü

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#177]
**Character Name**
Dan_Lee

**Erwartetes Verhalten**
Suchfunktion im Gehstilmenü implementieren, erleichtert die Auswahl.
War eine Idee die sich aus einer Diskussion im Support-Discord herauskristallisierte.

**Comment by its4l3x** [comment]
Habe ich umgesetzt. Ist beim nächsten Update dabei.
