### ISSUE TITLE
Fehler Fahrzeugüberschreibung am Autohaus nähe 2015

### ISSUE THREAD

**Issue by SirFeuerstein** [mexyn/statev_v2_issues#1770]
**Character Name**
Mike Feuerstein

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12:31 Uhr

**Beobachtetes Verhalten**
Fahrzeug konnte nicht überschrieben werden / Beim Autohausbesitzer kam keine Meldung, es erschien einfach nicht das erwartete UI.

**Erwartetes Verhalten**
Fahrzeug hätte auch mich überschrieben werden sollen 

**Schritte um den Fehler nachvollziehen zu können**
Normales vorgehen beim entpacken & überschreiben eines neues Fahrzeuges ****

**Optional: Video / Bilder des Fehlers**

Problem liegt am Fahrzeug Enus Stafford, alle anderen Fahrzeuge lassen sich ohne Probleme überschreiben

**Comment by epichalt** [comment]
Das üben wir glaub ich nochmal :D

**Comment by its4l3x** [comment]
?

**Comment by Bene-RonnyMoritz** [comment]
Fahrzeug Enus Stafford konnte im Autohaus entpackt werden. Fahrzeug Enus Stafford konnte im Autohaus NICHT überschrieben werden. Mit anderen Autos klappt das schon. 

Siehe letzte Zeile im Eintrag
> Problem liegt am Fahrzeug Enus Stafford, alle anderen Fahrzeuge lassen sich ohne Probleme überschreiben

**Comment by KingMarcel** [comment]
Confirmed. Es öffnet sich kein UI wenn man den Stafford verkaufen möchten. 
![08dTQ50](https://user-images.githubusercontent.com/44339872/127772803-3837f89c-6e07-4b6a-bc96-76a96795858a.png)

**Comment by its4l3x** [comment]
Merci für das Bild @KingMarcel

Ist fixed im nächsten Update...

**Comment by SirFeuerstein** [comment]
Update: Es geht leider immer noch nicht.
