### ISSUE TITLE
Tuningmenu (Werkstatt) Bugged Banshee & Kuruma

### ISSUE THREAD

**Issue by Domeex3** [mexyn/statev_v2_issues#1772]
Domenik_Sommer // Sludgie Customs

Tritt Permanent auf

Man nimmt das Tuningtablet, ändert z.b. die Folierung -> Nichts Passiert, ändert man jedoch die Bremsanlage ändert sich die Folie

Folie = Folie, Bremsen = Bremsen

Tablet in die Hand nehmen

https://streamable.com/1sb9q3

**Comment by Hutstaender** [comment]
War ein AltV Bug, dieser wurde mit ihrem letzten Update behoben.
