### ISSUE TITLE
Waffenrad beim Inventar öffnen + automatischen gehen

### ISSUE THREAD

**Issue by EmmaSvensson** [mexyn/statev_v2_issues#1774]
**Character Name**

Emma_Svensson
**Auftrittszeitpunkt (Datum / Uhrzeit)**

29.7.21 ca 12:15 anhaltend
**Beobachtetes Verhalten**

Beim Einloggen bereits hatte ich das Waffenrad im Vordergrund, dachte mir aber noch nichts dabei. Als ich dann im Haus mein Handy rausholte kam das Waffenrad wieder und ich lief automatisch los. Auch beim Inventar öffnen und anderen Overlays passiert dieser Fehler.
**Erwartetes Verhalten**

Nur das Handy oder Inventar wird geöffnet, man rennt nicht automatisch los und das Waffenrad öffnet sich nicht mir F2 und co.
**Schritte um den Fehler nachvollziehen zu können**

F2 drücken, Handy overlay öffnet sich
Waffenrad öffnet sich ebenfalls , gleichzeitig läuft man los
Beendigung nur durch schließen des Menüs
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Waffenrad](https://user-images.githubusercontent.com/74768516/127477529-ac5f9b47-0895-4402-a190-6c62e96f12f9.png)

**Comment by DonVitoDiangelo** [comment]
Controller angeschlossen?

**Comment by Statev-Bonsai** [comment]
Ja, das liegt am Controller...
Musste ich auch schon feststellen ;D

**Comment by EmmaSvensson** [comment]
habe aber derzeit keinen angeschlossen ^^
