### ISSUE TITLE
Interface bugt nach Browserbesuch LSMJ

### ISSUE THREAD

**Issue by Hochfels** [mexyn/statev_v2_issues#1776]
**Character Name**
 Marcel Hochfels

**Auftrittszeitpunkt (Datum / Uhrzeit)**
29.07.2021 17:40

**Beobachtetes Verhalten**
 nachdem ich auf dem Tablet im Browser die neue LSMJ Webseite geöfnet habe, hat sich alle nach oben verschoben.
Dieser Fehler ist reproduzierbar und lies sich bis jetzt nur mit einem Restart lösen.
Wenn ich z.B. das Funkgerät öffne, geht es wieder runter auf Normalposition und wenn ich es wieder wegpacke, springt es wieder ein paar cm nach oben.
Sobald man aber in das Funkgerät klickt, und dann wieder wegpackt, springt es wieder auf NormalPsotition zurück.
Gleiches gilt auch für die Marker für Gebäude verlassen etc.

**Erwartetes Verhalten**
 es sollte sich nicht verschieben, nachdem man eine Webseite geöffnet hat :)

**Schritte um den Fehler nachvollziehen zu können**

F3 für Tablett öffnen,
auf Seite 2 gehen
das letzte Symbol anklicken (LSMJ Webseite)
Das Interface (UI) verschiebt sich automatisch nach oben

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
2560*1440 144 HZ

**Optional: Video / Bilder des Fehlers**

![Fehler GTA StateV Interface](https://user-images.githubusercontent.com/88154450/127524415-a0c73fa3-c56a-471f-91bb-be375987b4f7.JPG)

Hoffe, ich konnte es gut beschreiben.

**Comment by KingMarcel** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1773
Website erstmal aus dem Browser entfernt bis der Fehler gefunden ist
