### ISSUE TITLE
Haare gucken immer noch durchs Cap

### ISSUE THREAD

**Issue by Rehki** [mexyn/statev_v2_issues#1777]
**Character Name**
Rayana_Vemo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
29.07.21   19:40 Uhr
**Beobachtetes Verhalten**
Haare schauen bei fast jeder Frisur die man auswählt weiterhin durchs Cap

**Erwartetes Verhalten**
Haare sind darunter versteckt

![Grand Theft Auto V Screenshot 2021 07 29 - 19 43 07 85 (2)](https://user-images.githubusercontent.com/87999101/127541438-03679bd4-aa00-40bc-8d65-f6d2508ca9c2.png)

**Comment by Enemyaa** [comment]
Das ist eine modded Cap. Das steht in den Changelogs unter Informationen!

**Comment by Rehki** [comment]
Ah ok, überlesen, danke dir
