### ISSUE TITLE
Trailer Pisswasser Importpreis #2

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#1778]
Wie bereits hier erwähnt hat die Trailer Pisswasser Achse starke Unterschiede bei den Importpreisen.
https://github.com/mexyn/statev_v2_issues/issues/1741#event-5075625763

Gestern war eine für 24k Startpreis im Import, heute sind wir wieder bei knapp 10k
https://gyazo.com/76da98e137e3aa741a81d4c5c6b8645a

**Comment by DonVitoDiangelo** [comment]
next update
