### ISSUE TITLE
Bug? - Einkäufe landen im Rucksackinventar - auch wenn Rucksack nicht ausgerüstet

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#178]
**Character Name**

Erwin_Dulach
**Zeitpunkt (Datum / Uhrzeit)**

28.08 ~20:00
**Beobachtetes Verhalten**

Wenn man zwar einen Rucksack im Inventar, diesen aber nicht im Rucksackslot hat, landen Käufe (24/7, Restaurant, Essensladen) trotzdem in diesem und man muss diesen ausrüsten und das Zeug aus diesem raus nehmen.
**Erwartetes Verhalten**

Den Bug gibt es auch sein ein paar Updates auf Rage, früher war es so, dass Sachen im Hauptinv landen und erst im Rucksack, wenn man diesen auch wirklich ausgerüstet hat.
**Schritte um den Fehler nachvollziehen zu können**

Rucksack von Slot ins Hauptinv ziehen -> Sachen kaufen -> ins Inv schauen und nix finden -> Rucksack in Slot ziehen -> Dinge Finden

**Comment by eiksch** [comment]
Kriege den Bug nicht reproduziert. @TheOutburst 

Wenn ich nach deiner Beschreibung gehe, werden die Items ins Hauptinventar gezogen.

**Comment by zarazandra** [comment]
Also empfinde ich jetzt nicht zwangsläufig als bug - ich fand das immer sehr gut, dass Einkäufe direkt in den Rucksack gewandert sind, wenn im normalen Inventar nicht genug Platz war - so musste man vorher erst immer gucken was man wohin schiebt und hat mehr Tetris gespielt als sonst was. Es wäre im "echten Leben" ja auch logisch, die Sachen in ne Tasche zu packen, wenn die Hosentaschen voll sind. ;) Man könnte es ja vielleicht eher so regeln, dass man den Rucksack dann automatisch anlegt? Wäre das eine Option?

**Comment by DrGrizzlY17** [comment]
@eiksch das ganze ist ein v1 Bug und ist in v2 anscheinend durch den neuen Code behoben
