### ISSUE TITLE
Haus am Mirrorpark / Garten Objekte

### ISSUE THREAD

**Issue by ChapWinchester** [mexyn/statev_v2_issues#1780]
**Character Name**
Chap_Winchester

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Im Garten Baustelle

**Erwartetes Verhalten**
Baustellen Objekte Entfernen gegeben falls die Fläche ändern.

**Schritte um den Fehler nachvollziehen zu können**
Da ich immer im RP gefragt werde wann der Garten fertig ist dachte ich mir es wäre vielleicht was feines wenn es da frei von den Objekten wäre um bisschen abends dort Chillen zu können mit freunden. Würde mich bei einer Änderung freuen, wenn nicht war es ein versuch wert :)

**Optional: Video / Bilder des Fehlers**
![vorne](https://user-images.githubusercontent.com/78925037/127689818-aded7796-2b00-4ca4-8b42-487bc4943a30.jpg)
![Garten](https://user-images.githubusercontent.com/78925037/127689826-0efcfbc1-883c-4125-86e6-608380a2251c.jpg)
![map](https://user-images.githubusercontent.com/78925037/127689829-02d34c8a-6419-4cb1-9d99-247845679394.jpg)

**Comment by DrGrizzlY17** [comment]
Ging nicht alles zu entfernen, aber das was ging ist weg

**Comment by ChapWinchester** [comment]
Vielen dank, sowas ist natürlich nicht selbstverständlich. Danke für die Hilfe und Unterstützung
