### ISSUE TITLE
 Fäuste, Hieb und Stichwaffen wieder etwas mehr Schaden

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1783]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Gewünschtes Verhalten**
Hieb und Stichwaffen sollen wieder etwas mehr Schaden machen.
Derzeit brauchen Nahkämpfe (sofern das RP Verständnis zum Drücken von Ö nicht vorhanden ist) Jahre.
Hinzu kommt, das es einen Fehler gibt, weswegen Ö nicht jederzeit drückbar ist. (umgehbar indem man vorher das Tablet raus holt und nach dem weg stecken ca 3 Sekunden wartet.
Es wäre Schön wenn Fäuste, Hieb und Stichwaffen wieder etwas mehr Schaden machen würden.
Nicht so viel wie früher, aber auch nicht so wenig wie jetzt.
So das Kämpfe nicht Jahre dauern.

**Comment by TheBroady** [comment]
> **Character Name**
> Max Broady
> 
> **Auftrittszeitpunkt (Datum / Uhrzeit)**
> 
> **Gewünschtes Verhalten**
> Hieb und Stichwaffen sollen wieder etwas mehr Schaden machen.
> Derzeit brauchen Nahkämpfe (sofern das RP Verständnis zum Drücken von Ö nicht vorhanden ist) Jahre.
> Hinzu kommt, das es einen Fehler gibt, weswegen Ö nicht jederzeit drückbar ist. (umgehbar indem man vorher das Tablet raus holt und nach dem weg stecken ca 3 Sekunden wartet.
> Es wäre Schön wenn Fäuste, Hieb und Stichwaffen wieder etwas mehr Schaden machen würden.
> Nicht so viel wie früher, aber auch nicht so wenig wie jetzt.
> So das Kämpfe nicht Jahre dauern.

Vielleicht auch mehr Variationen zwischen Faust vs Schlagring. Oder Baseballschläger vs Faust.
Derzeit fühlt sich alles recht gleich an was den Schaden betrifft.

**Comment by DonVitoDiangelo** [comment]
Next Update change.
