### ISSUE TITLE
Alle Items aus Kofferraum verschwunden

### ISSUE THREAD

**Issue by zarazandra** [mexyn/statev_v2_issues#1784]
**Character Name**
Shiva Connelly

**Auftrittszeitpunkt (Datum / Uhrzeit)**
31.07.21, Uhrzeit zwischen 1630 und 19 Uhr 

**Beobachtetes Verhalten**
Tasche mit Kleidung ins Auto (Jugular, ICEDA117) gelegt, noch eine leere Tasche dazu. 
Es waren 2, 3 Reparaturkästen und nochwas im Auto (weiß nicht mehr genau, welches Item das war).
Kofferraum zu und Auto wurde, nach Fahrt dorthin, in die Mission Row-Garage eingeparkt. (das war gegen 1630 oder so - kann es nicht genau sagen).
Später, gegen 1830 wurde das Fahrzeug ausgeparkt und eine Viertelstunde später war der Kofferraum beim Reinschauen komplett leer - beide Taschen sowie die Items, die vorher schon drin waren, sind alle weg gewesen. 

**Erwartetes Verhalten**
Sachen bleiben wo sie sind

**Schritte um den Fehler nachvollziehen zu können**
siehe oben

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
nicht vorhanden

**Comment by Hutstaender** [comment]
Das war kein Bug, es war zwischenzeitlich nochmal mehrfach jemand an deinem Kofferraum. Hast wohl vergessen abzuschließen.

**Comment by zarazandra** [comment]
> Das war kein Bug, es war zwischenzeitlich nochmal mehrfach jemand an deinem Kofferraum. Hast wohl vergessen abzuschließen.

Das Fahrzeug war in der Garage EINGEPARKT und es gibt nur eine weitere Person, die einen Schlüssel dazu hat (und demnach ausparken kann) und die war es definitiv nicht. 

Zu jedem Zeitpunkt, an dem das Auto ausgeparkt war, stand ich nebendran. 
Es kann also keiner an meinem Kofferraum gewesen sein.
