### ISSUE TITLE
Schneiden von Conrows bei bestimmten char nicht möglich

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1786]
**Character Name**
Amber Reaper und Ben Reaper

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.08.21 - 20:10

**Beobachtetes Verhalten**
Beim abschicken der Rechnung für die conrows kommt folgende Fehlermeldung:
Es wurde keine Änderung beim schneiden vorgenommen.

**Erwartetes Verhalten**
Schneiden möglich und Kunde bekommt wie gewohnt die Frisur

**Schritte um den Fehler nachvollziehen zu können**
Conrows versuchen zu schneiden 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/70150887/127781290-792e093d-87bd-4079-a002-c92e6e8d899c.png)

**Comment by TheBroady** [comment]
Nachtrag:
Bei einer anderen Person ging es.
Ben reaper bei dem es nicht geht hatte eine Woche zuvor versucht die conrows geschnitten zu bekommen, allerdings durch den Bug eine andere Frisur bekommen. Kann es daran liegen, das das System nun denkt er hätte bereits welche?

**Comment by Enemyaa** [comment]
Mit dem nächsten Update wird sich das problem beheben.
