### ISSUE TITLE
Zäune & Objekte vor Werkstatt seit V2

### ISSUE THREAD

**Issue by callmerusty** [mexyn/statev_v2_issues#1787]
Hallo,

gäbe es vielleicht die Möglichkeit, die Zäune und Objekte, die dort seit V2 sind, vor der Werkstatt zu entfernen?

Im RP bespielen wir die Werkstatt als Fraktion mit einem Tuning Club, ein Ort, wo viele Spieler vorbei kommen, um den Abend zu verbringen neue Spieler kennenzulernen und sich über Fahrzeuge ect. auszutauschen und es ist einfach keine aklimatische Umgebung; Sitzmöglichkeiten ect. einen Meter neben Mülltonnen aufzustellen.

Durch die Entfernung der Zäune hätte man zusätzlich mehr Parkmöglichkeiten.

https://i.imgur.com/A9oO9ye.png
https://i.imgur.com/kDpFXhM.jpg
https://i.imgur.com/ZaAvW4P.jpg

So sah es in V1 aus:
https://i.imgur.com/wQl4ySa.png

Mit freundlichen Grüßen,
Rusty

**Comment by Chrinis007** [comment]
Duplikat von #211
