### ISSUE TITLE
Fahrzeuge ohne Kennzeichen

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1788]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit letztem Update

**Beobachtetes Verhalten**
Fahrzeuge ohne Kennzeichen werden Kennzeichen aus der Umgebung "zugeteilt", diese wechseln auch von Person zu Person die draufschaut

**Erwartetes Verhalten**
Fahrzeug hat kein Kennzeichen

**Schritte um den Fehler nachvollziehen zu können**
Video folgt bei Bedarf

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Bitte mir das Fahrzeug beschreiben, was das für eins ist,  auf wenn das geschrieben ist, etc...

**Comment by Statev-Bonsai** [comment]
Penumbra FF, einen Tag in einen Stream gesehen..

**Comment by JannikDatsch** [comment]
Da war jetzt schon mehrmals so. Grade eben ein Mesa von einem Gordon Freeman. Ich schicke da nachher mehrere Videos zu.

**Comment by JannikDatsch** [comment]
> Penumbra FF, einen Tag in einen Stream gesehen..

Stream von Shane? Da war ich auch dabei, ja

**Comment by Statev-Bonsai** [comment]
Ja genau, am Würfelpark...

**Comment by TheBroady** [comment]
Alex ich schick dir heute Nachmittag ein paar Beispiele. Ist bei uns auch vermehrt aufgetreten. Habe screens und Fahrzeughalter.

**Comment by JannikDatsch** [comment]
Halter: (Wohl) Gordon_Freeman   Datum: 02.08  18:40 
https://youtu.be/si8M4tS-7cA

**Comment by its4l3x** [comment]
Bitte nochmal gegenchecken.

**Comment by JannikDatsch** [comment]
@its4l3x Grade zumindest einen Streiter ohne Kennzeichen gesehen. Werde schreiben, wenn nm. Probleme auftauchen.
