### ISSUE TITLE
Drift Yosemite Unterbodenbeleuchtung

### ISSUE THREAD

**Issue by dschereau** [mexyn/statev_v2_issues#1789]
**Character Name**
Desmond_Schereau

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.08.2021 21:30

**Beobachtetes Verhalten**
Während der Fahrt geht das Unterbodenlicht das seitlich angebracht ist aus.
Eventuell Liegt es an der Tieferlegung aber das wäre schon sehr komisch.

**Erwartetes Verhalten**
Das Licht sollte durchgehend an sein

**Schritte um den Fehler nachvollziehen zu können**
Unterbodenbeleuchtung an Fahrzeug während der Fahrt aktivieren

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
https://user-images.githubusercontent.com/68921120/127924917-68e484f5-05c5-4856-bba5-32fc908ec5e7.mp4

**Comment by DonVitoDiangelo** [comment]
Ich denke eher das durch die Speed ein Anpressdruck generiert wird, der Wagen fast aufliegt und das Licht einfach nicht durchscheint. Aber wie auch immer, daran können wir eh nichts ändern. Wieder ne Stufe nach oben schrauben und das beste draus machen.
