### ISSUE TITLE
Idee: Geld Item

### ISSUE THREAD

**Issue by CaptainGhostLive** [mexyn/statev_v2_issues#179]
**Character Name**
Emilio Luciano

**Grund**
Aufgrund von diversen RP Strängen hat mir bis dato die Funktion gefehlt Geld in Fahrzeugen zu lagern um ein Deal sauber ablaufen zulassen, aufgrund dessen habe ich mir Gedanken dazu gemacht.
Und Zwei Möglichkeiten gefunden die Zweite jedoch ist Komplexer und nicht notwendig. 

**Beschreibung**

1)Die Geld anzeigen oben rechts im Inventar so Kopieren das man theoretisch auch die selbe Anzeigen Oben Links am Fahrzeug hat, und somit die Möglichkeit vom Inventar Geld ins Auto zu Übertragen.

2)Ein Koffer im Inventar den man mit Rechtsklick und Benutzen "Bearbeiten" kann und und eine gewisse Summe reinlegen kann (max. 5000$) dieser sollte ggf. seinen Namen im Inventar ändern (Koffer (2500$)). Diesen kann man in Fahrzeugen oder im Inventar Lagern. Genauso an andere Spieler Übergeben.

**Comment by tastydev** [comment]
Auf diesem Projekt wird es Geld als Item niemals geben. Abusegefahr zu riesig (z.B durch einen Bug), welche die Serverwirtschaft kippen könnte.
