### ISSUE TITLE
Kleidung implementieren

### ISSUE THREAD

**Issue by statevmj** [mexyn/statev_v2_issues#1790]
Wenn's möglich ist, wäre es cool, wenn man vielleicht die grüne und die lilane Shorts aus untem stehenden Link auf den Server bringen könnte. Ich weiß nicht, ob man das von der roten und blauen seperarieren kann, aber auf denen steht leider nicht "Los Santos". Vielleicht kann man die grüne/lilane ja auch als Basis nehmen um sie einzufärben für mehrere Möglichkeiten.

Link: https://de.gta5-mods.com/player/mp-male-gang-shorts

**Comment by Enemyaa** [comment]
Next Update!
