### ISSUE TITLE
Wand / Tür Textur nicht massiv. Man fällt durch die Welt Mariana Drive 29 / sandyshores25

### ISSUE THREAD

**Issue by cadpri** [mexyn/statev_v2_issues#1791]
**Character Name**
Fabian Picard

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.08.2021 20:00

**Beobachtetes Verhalten**
An der Raffinerie     Mariana Drive 29 / sandyshores25 kann man durch die Tür Textur laufen und durch die Welt fallen.

**Erwartetes Verhalten**
Die Tür sollte massiv sein.

**Schritte um den Fehler nachvollziehen zu können**
Zu besagtem Ort gehen und gegen die Wand/Tür laufen. Vorsicht !

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
Hat nichts mit der Auflösung zu tun. Da fallen alle durch.

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/i/qXyLB.jpg
https://pic.statev.de/i/qXzyR.jpg

**Comment by DrGrizzlY17** [comment]
GTA related
