### ISSUE TITLE
LCC Innovation sehr, sehr zerbrechlich !!!

### ISSUE THREAD

**Issue by ButzzDiggah** [mexyn/statev_v2_issues#1793]
Robin_Benardo

Robin_Benardo

mehrere Tage jetzt schon beobachtet

Der Fehler tritt bei der LCC Innovation auf. Wenn man gegen das Mottorad läuft dann zerbricht das Frontlicht und Hecklicht, sowie die Motoranzeige wird gelb und ab und zu geht der Motor auch ganz kaputt (anzeige rot). Selbes Problem also wie es bei dem Western LOST Bike war/ist

Naja, es sollte nicht anfangen zu qualmen und alles kaputt gehen, wenn man etwas gegen läuft

Einfach das ding mal ausparken und etwas gegen laufen, vielleicht mal hinrennen und etwas zu spät abbremsen, dann werdet ihr es schon sehen 

Habe jetzt noch kein Video von gemacht, aber wenn es erwünscht ist oder so dann kann ich noch eins machen.

**Comment by DonVitoDiangelo** [comment]
next update
