### ISSUE TITLE
Fehler im Frisurladen viele Frisuren Passen nicht mehr über ein

### ISSUE THREAD

**Issue by HansKelly** [mexyn/statev_v2_issues#1795]
**Hans Kelly**

Hans Kelly

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Datum:  04.08.2021
Uhrzeit: 23:00

**Beobachtetes Verhalten**
Kunde seine Frisur sollte geändert werde auf Glatrasiert und am ende kam eine andere Frisur raus dies ist aber nicht der erst Fall sonder die fälle passieren bei verschieden Kunden im Laden 

**Erwartetes Verhalten**
Das die Frisuren wieder richtig über ein stimmen denn wenn man Glatrasiert macht kommen siehe foto im Anhang 
andere Frisuren raus

**Schritte um den Fehler nachvollziehen zu können**
kunde Frisur angepasst
und geschnitten und kam anderen Frisuren raus
![fehler Friseur fehler](https://user-images.githubusercontent.com/74863998/128259031-e3730f01-bab5-4bdf-8f98-5fc3b8ed77ee.png)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![fehler Friseur fehler](https://user-images.githubusercontent.com/74863998/128259091-dd342932-55f4-491b-bbc8-905251280ebc.png)

**Comment by Enemyaa** [comment]
@HansKelly Deinen Eintrag hast du während dem Update geschrieben, ist das jetzt noch aktuell oder war das davor?

**Comment by HansKelly** [comment]
ist noch schlimmer gewurden jetzt nun bem schmicken der Kunden ändert sich jett auch die haare

**Comment by HansKelly** [comment]
Ich habe einer kundin auf dem Frisurstuhl die haare geschnitten dann wollte sie schmicke haben da wir ihren Lippenstift geändert haben wurde auch ihre frisuer nun wieder geändert es sind aktuell sehr große Fehler im Bereich Frisuer vorhanden bei jeden kunden ändert sich irgendwas anderes nur nicht das was sie haben wollen seid dem update gerade ist nun auch wieder ein fehler das mit dem Schminken vorhanden

**Comment by Enemyaa** [comment]
Autsch! OK...

 Danke für die Info.

**Comment by HansKelly** [comment]
gerne doch hoffe ihr bekommt das wieder hin weil langsam werden auch die Kunde ungemüdlich ich musste schon gutscheie ausschreiben als wieder gut machung

**Comment by Saaria83** [comment]
Und wurde von Tito gesagt, dass wir die Kunden in den Support schicken sollen. Die bekommen dann die Möglichkeit Ihre Haare erneut machen zu lassen

**Comment by eiksch** [comment]
Beim nächsten Update ist es behoben. Wenn ihr nur schminkt/färbt, ohne die Haare zu machen, kann es aktuell passieren, dass die Haare anders werden.

**Comment by HansKelly** [comment]
eiksch kann man das nicht ändern weil sonst können wir bei den kunden kein Lippenstift oder schminke machen ? weil sonst sich ja die haare wieder ändern kann das nicht behoben werden ????

**Comment by M4rvinLP** [comment]
Es kommt leider immer noch eine falsche Frisur raus (beim normalen schneiden und färben).

**Comment by eiksch** [comment]
Immer? Es kann sein, dass manche Charaktere durch das vorherige falsche Verhalten "verbuggt" sind und somit etwas in der Datenbank stehen haben, was da nicht hingehört. Hast du mal einen Namen für mich ?

**Comment by M4rvinLP** [comment]
> Immer? Es kann sein, dass manche Charaktere durch das vorherige falsche Verhalten "verbuggt" sind und somit etwas in der Datenbank stehen haben, was da nicht hingehört. Hast du mal einen Namen für mich ?

Marvin_Elpe

**Comment by Saaria83** [comment]
Wir haben heute einige Frisuren und auch Schminke gemacht und alles lief problemlos

**Comment by eiksch** [comment]
Marvin welche Frisur solltest du haben? ich überprüfe das mal dann und korrigier wenn du offline bist.

**Comment by M4rvinLP** [comment]
Die Messy Crew Cut, die farben müssten schon so passen. Bin jetzt auch off. Danke dir
![](https://cdn.discordapp.com/attachments/721812055509958657/872209168826789919/Marvin_Wunsch.png)

**Comment by TomStark93** [comment]
Ich war heute im Support, der cooldown wurde zurückgesetzt um die Haare zu schneiden, aber IC habe ich eine andere Frisur als glattrasiert siehe Bild vom ersten Beitrag. Mein Charakter heißt Tom Stark. Ich habe jetzt gerade auch nochmal eine Fehlermeldung geöffnet, da ich noch nicht wusste, dass ein Beitrag existiert und der Fehler nicht behoben wurde.

**Comment by Saaria83** [comment]
Es gibt 2 Frisuren mit dem Namen gelockter Bob. Man bekommt, aber nicht die "Locken" die man eig. möchte sondern die Dreads 

Gewollte
![Gelockter Bob](https://user-images.githubusercontent.com/70151476/128524073-4e968d11-e7e8-42be-b401-333e020ef51c.png)

Die er bekommen hat
![Loc Bob](https://user-images.githubusercontent.com/70151476/128524103-e050ff8b-d2c9-47c5-9974-793ccc53d93a.png)


Zusätzlich stehen bei dem Kunden, der die Frisur bekommen hat, bei beiden Frisuren der gleiche Name "Gelockter Bob".
Bei einem anderen, 2 unterschiedliche "Gelockter Bob" und "Loc Bob"


Pls fix it nooow :D

**Comment by HansKelly** [comment]
Leider trifft es noch immer sehr viele die falsche Frisuren bekommen gesternw aren wieder 2 kunden bei mir die wieder falsche Frisuren bekommen haben wenn das soweiter geht verlieren wir unsere Kunden und dann gibt es keine Frisuren odersonst was mehr 
nune hatte esdie Freundin Mlla Hohnstein getroffen BITTE bekommt das langsam wieder hin sonst verliere ich meine Kunden immer mehr und kann den ladens chon schliessen .

**Comment by M4rvinLP** [comment]
@eiksch hattest du es bei mir probiert zu fixen?

**Comment by eiksch** [comment]
@M4rvinLP nein, du müsstest dir ab heute einfach direkt eine neue Frisur holen.

@HansKelly es gingen alle Friseure nicht... du tust so als wärst du alleine betroffen.

**Comment by M4rvinLP** [comment]
> @M4rvinLP nein, du müsstest dir ab heute einfach direkt eine neue Frisur holen.
> 
> @HansKelly es gingen alle Friseure nicht... du tust so als wärst du alleine betroffen.

Alles klar, ich danke dir vielmals!
