### ISSUE TITLE
Xenons werden auf Serie zurück gesetzt nach Reperatur + Tuning

### ISSUE THREAD

**Issue by Fabsee** [mexyn/statev_v2_issues#1797]
Fabio_Gonzales

Fabio_Gonzales

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.08.2021 11:40

**Beobachtetes Verhalten**

Nach einer Reperatur wurden an einem Penumbra ff Bodykit Front, Auspuffanlage Sport und Kotflügel getuned. Durch die vorherige Reperatur werden anscheinend die Xenon Farben zurück gesetzt. Durch das anschließende tuning werden aber die Xenons überschrieben und neu abgespeichert obwohl dort die gemachten Xenons mit Farbe im Tuning pc angezeigt werden die vorher drinnen waren. Das Xenons beim tunen gebraucht werden wird auch im tuning pc nicht angezeigt. Wenn also bei einem Fahrzeug der Motor nicht läuft und die Scheinwerfer nicht an sind fällt dies nicht auf.

**Erwartetes Verhalten**

Nach einer Reperatur sollten die Xenons sich nicht auf Serie zurücksetzen und durch ein anschließendes Tuning nicht überschreiben und gespeichert werden.

**Schritte um den Fehler nachvollziehen zu können**

Beliebiges Fahrzeug mit verbauten Xenons Reparieren und direkt tunen. Somit werden die Xenons überschrieben und auf Serie gesetzt.

**Comment by CatherineGallagher** [comment]
https://github.com/mexyn/statev_v2_issues/issues/986

ist bereits seit längerem bekannt, das einzige was hilft ist das Fahrzeug einzuparken und danach ein Tuning vorzunehmen.
