### ISSUE TITLE
Verpacktes Klemmbrett kann nicht produziert werden

### ISSUE THREAD

**Issue by LouieLagarde** [mexyn/statev_v2_issues#1798]
Louie Lagarde

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.08.2021 00:05

**Beobachtetes Verhalten**
Fehlermeldung beim Starten der Produktion:
"Fehler in der Konfiguration der Produktion!"

**Erwartetes Verhalten**
Produktionsvorgang startet

**Schritte um den Fehler nachvollziehen zu können**
-> Fertigungsfabrik -> Verpacktes Klemmbrett -> Produktion starten

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/47a257289b53f857f43380d1f09e6328

**Comment by DerHessenTyp** [comment]
Stand 05.08.2021 um 15:25 Uhr

Fehler besteht weiterhin mit Fehler in der Konfiguration der Produktion


![Klemmbrett](https://user-images.githubusercontent.com/70151958/128357603-9f6c2cb1-a0f4-49d7-8866-1f623fbb2666.jpg)
