### ISSUE TITLE
Hoodies werden nicht richtig angezeigt 

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#1799]
**Character Name**

Ryan_Valdes
**Auftrittszeitpunkt (Datum / Uhrzeit)**

01:00 Uhr 05.08.2021
**Beobachtetes Verhalten**

Den Hoodie den man trägt wird bei den anderen Falsch angezeigt.
siehe Bilder
**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

Wie ich es Sehe
![Screenshot_7](https://user-images.githubusercontent.com/70231715/128267257-e9ac70f6-f7dd-482f-a838-0ead4fca0272.png)

Wie andere mich sehen 
![unknown](https://user-images.githubusercontent.com/70231715/128267288-41c4a603-fcdb-43d4-acd0-0a936edbdaf0.png)

**Comment by DrGrizzlY17** [comment]
Was fürn Hoodie ist das?

**Comment by PlayInc89** [comment]
Die Neuen Collegejacken sind auch von mit betroffen

**Comment by PlayInc89** [comment]
Die Neuen allgemein

**Comment by DrGrizzlY17** [comment]
Was genau ist mit den Collegejacken? Auch unsichtbar?

**Comment by PlayInc89** [comment]
![lsc](https://user-images.githubusercontent.com/70231715/128268058-277d506c-1ec2-4c35-9916-823f9757d327.png)
Das ist zB die Los Santos Cutom Collegejacke

**Comment by PlayInc89** [comment]
Wenn wir grad dabei sind die FlipFlops bei Frauen sind auch Fehlerhaft

**Comment by DrGrizzlY17** [comment]
FlipFlops sind fixbar. Bei den anderen sieht es nach nem altV Ding aus. Müssen wir morgen auf die Entwickler warten

**Comment by PlayInc89** [comment]
Alles klar

**Comment by Enemyaa** [comment]
Die Flip Flops sind schon mal gefixt. Die Items gehen euch auch nicht verloren dadurch, falls ihr schon welche hergestellt habt.

**Comment by Hutstaender** [comment]
Die Hoodies habe ich bei AltV bereits gemeldet, mal schaun was passiert.
