### ISSUE TITLE
Essen/Trinken/Voice Anzeige im Bewusstlosen Zustand

### ISSUE THREAD

**Issue by AideenCarter** [mexyn/statev_v2_issues#18]
**Zeitpunkt (Datum / Uhrzeit)**
19:01 Day 1 Beta Phase 2

**Beobachtetes Verhalten**
Die Essen/Trinken/Voice anzeige bleibt erhalten wenn man Bewusstlos ist und triggert auch wenn man etwas sagt + man hört den Funk etc.
**Erwartetes Verhalten**
Die Anzeige sollte verschwinden und Funk sollte nicht hörbar sein

Im Bewusstlosen zustand einfach testen. 
**Optional: Video / Bilder des Fehlers**

**Comment by tastydev** [comment]
Ist so gewollt.
