### ISSUE TITLE
Falsche Darstellung der neuen Flip Flops

### ISSUE THREAD

**Issue by CatherineGallagher** [mexyn/statev_v2_issues#1800]
**Character Name**
Catherine Gallagher

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit dem letzten Patch am 5.8

**Beobachtetes Verhalten**
Die neuen Flip Flops werden entweder gar nicht angezeigt (der Character hat keine Füße mehr)
oder werden als Pumps mit Nylons gezeigt

**Erwartetes Verhalten**
Die richtigen Artikel zum Namen natürlich 

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/i/qk64I.jpg

**Comment by PlayInc89** [comment]
Nach dem Fix immernoch der Selbe Fehler
