### ISSUE TITLE
Kopfbedeckung verschwindet im Fahrzeug

### ISSUE THREAD

**Issue by LivePlayerHD** [mexyn/statev_v2_issues#1801]
**Character Name**
Kira Noka

**Auftrittszeitpunkt (Datum / Uhrzeit)**
NAch den Letzten Update am 05.08.2021 (V2.1.7)

**Beobachtetes Verhalten**
bei einigen Kopfbedekungen wird diese nicht mehr im auto angezeit wenn man in eins sitzt. Bis jetzt aufgefallen nur bei Caps

**Erwartetes Verhalten**
Das die Kopfbedeckung angezeigt wird.

**Schritte um den Fehler nachvollziehen zu können**
Kopfbedeckung aufsetzen und in ein fahrzeug setzten.

**Optional: Video / Bilder des Fehlers**
![20210805101815_1](https://user-images.githubusercontent.com/74984092/128319332-bb0ebf3c-30bd-49db-86cd-dfcaecde7631.jpg)

**Comment by Stiefel911** [comment]
Das passiert grundsätzlich, gerade bei Bedeckungen die etwas grösser sind. Du kannst sie im Fahrzeug entweder erneut aufsetzen oder kurz Bandana um und wieder ab, funktioniert auch mit Brille etc... 😉

**Comment by LivePlayerHD** [comment]
jJa ich weiß aber vor den letzten Update war das nicht so und man konnte soweit ich weiß alle Kopfbedekungen in ein Fahrzeug tragen ohne das die verschwindet.

**Comment by Stiefel911** [comment]
bei meinem Char verschwindet die Kopfbedeckung schon immer, früher nutzte ich kurz das Bandana damit es wieder zu sehen ist. ;)
liegt vllt bei meinem auch daran das es ein Hut ist :D
