### ISSUE TITLE
Rumpo nicht Lackierbar

### ISSUE THREAD

**Issue by AdnanT57** [mexyn/statev_v2_issues#1802]
**Character Name**
Adnan Turkoglu

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.08 - 13:40 ca.

**Beobachtetes Verhalten**
Ein Rumpo sollte lackiert werden, jedoch öffnete sich der Computer nicht. Erst dachte ich es wäre ein allgemeiner Bug wegen dem Update, was über Nacht kam. Daraufhin fuhr ich meinen Reaper in die Kabine und das Lackierfenster öffnete sich.

**Erwartetes Verhalten**
Man sollte den Rumpo logischerweise auch lackieren können :D

**Schritte um den Fehler nachvollziehen zu können**
Rumpo in die Lackierkabine fahren und E am Marker drücken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/8xA1rqxrPB8

**Comment by epichalt** [comment]
Das ist doch kein Rumpo oder?^^

**Comment by cadpri** [comment]
Doch das ist der Liveinvader Rumpo. Nicht zu verwechseln mit dem Rumpo Custom

**Comment by Hutstaender** [comment]
Der Weazel News Rumpo hat keine Farboption von GTA aus. Wenn der Lifeinvader ne andere Farbe braucht müssen die sich bei einem unserer Devs melden, damit das über DB gesetzt wird.
