### ISSUE TITLE
Western Cycle Company Deamon (Lost)

### ISSUE THREAD

**Issue by ButzzDiggah** [mexyn/statev_v2_issues#1805]
Robin_Benardo

Robin_Benardo
**Auftrittszeitpunkt (Datum / Uhrzeit)**

seitdem das Motorrad im Import ist (ca. seit 2 Monaten)
**Beobachtetes Verhalten**

wenn man gegen das Motorrad rennt dran rumläuft, fängt es an zu brennen (Motorlampe rot). Das ist bei der Western Cycle Company Deamon (Lost) genauso wie bei der LCC Innovation 
**Erwartetes Verhalten**

Es sollte halt einfach nicht anfangen zu brennen, wenn man gegen läuft
**Schritte um den Fehler nachvollziehen zu können**

Einfach gegen rennen !
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
next update fixed
