### ISSUE TITLE
Laut Friseur die Frisur Glatze, tatsächlich andere Frisur 

### ISSUE THREAD

**Issue by TomStark93** [mexyn/statev_v2_issues#1806]
Statt eine Glatze hat mein Charakter folgende Frisur:

https://pic.statev.de/i/qoI7J.png

**Comment by TomStark93** [comment]
Nach Cool down reset, beim Friseur gewesen und konnte mir die Frisur glattrasiert nicht schneiden, da mein Charakter es laut System hat. Also gut, dann haben wir die Haare umgefärbt in der Hoffnung, dass mein Charakter dann die Frisur glattrasiert hat, aber die Frisur blieb gleich bis auf die Haarfarbe.

**Comment by Hutstaender** [comment]
Sollte jetzt gelöst sein seit dem letzten Update. Einfach kurz im Support den Cooldown resetten lassen falls vorhanden.
