### ISSUE TITLE
Beim Essen in Restaurant Schaden bekommen

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1808]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.08.2021

**Beobachtetes Verhalten**
wenn man bereits nichts zu Essen und Trinken mehr hat und dieses auch schon Schaden verursacht. Bekommt man weiter schaden während man im Restaurant am essen ist.

**Erwartetes Verhalten**
Während des Essens-Prozess wäre es cool keinen Schaden mehr zu bekomme, da man ja bereits Isst aber die Hud's erst nach den erreichen der 100% Fortschrittsanzeige gefüllt werden.
(vlt wie bei den Medics auf dem Krankenbett regeln, solange man Isst bekommt man keinen Hunger/Durst Schaden. 

**Schritte um den Fehler nachvollziehen zu können**
Hungern bis es weh tut und dann was futtern gehen. ;)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
fixed next update
