### ISSUE TITLE
Vorschlag: Erweiterung der Settings unter F7 (Frisur Extras bei Caps)

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1809]
**Gewünschtes Verhalten**
Es wäre Cool wenn man die Einstellung welche man für die Frisur in den F7 Settings festlegen kann und diese dort gespeichert wird.
Sprich ich lege für meine Caps die Frisur 2 fest und diese Frisur wird immer gesetzt sobald ich eine Cap aufziehe.
Aktuell muss die Einstellung der Haare bsp. jedes mal neu ausgewählt werden, wenn die Cap kurzzeitig ausgezogen wurde.
Je nach Einstellung muss man dann erstmal wieder mühselig durch alle Frisuren klicken, bis man bei seiner angekommen ist.

Möglicherweise ist dies auch für andere Extras möglich, allerdings bei Hoodies (Kaputze auf/ab, Hemd auf/zu) nicht ganz so nevig. Für die Frisuren wäre es allerdings eine schöne Anpassung.

**Comment by DonVitoDiangelo** [comment]
Vorschläge ab sofort bitte ins Forum, danke.
