### ISSUE TITLE
Vorschlag: Schlüssel für Fahrzeuge nachmachen lassen (Limit von max 3 erhöhen)

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1810]
**Gewünschtes Feature**
Ich wünsche mir das man für ein Fahrzeug auch mehr als 3 Schlüssel haben kann. (nicht Unendlich, aber das Limit erhöhen)
Cool wäre es wenn man bsp bei der Auslieferung weiterhin 3 oder auch gerne nur einen Schlüssel bekommt und anschließend bei der Werkstatt neue Schlüssel durch den Halter (max Limit kann durch euch ja bestimmt werden) herstellen lassen kann.
Firmen müssten nicht immer die Firmenwagen-Schlüssel ins Lager legen damit andere Zugriff auf die Karre haben (Fahrzeuganmeldung auf Firma würde dadurch ggf auch Komplett vom Tisch fallen)

**Comment by DonVitoDiangelo** [comment]
Wird so nicht kommen. Weiterhin Vorschläge ab sofort nur noch ins Forum.
