### ISSUE TITLE
Bein Tattoo mit neuer Hose verwischt

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1811]
**Character Name**
Amber Reaper

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.08.2021

**Beobachtetes Verhalten**
Wenn ich die neue Hose an habe ([F] Schwarze Los Santos Shorts) wird mein Bein Tattoo verwischt und ist nicht mehr zu sehen

**Erwartetes Verhalten**
Bein Tattoo bleibt sichtbar

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Ohne Hose
![image](https://user-images.githubusercontent.com/70150887/128539216-3de7254b-849e-4805-911c-554184dac053.png)

Mit Hose
![image](https://user-images.githubusercontent.com/70150887/128539228-ded84220-0319-4c1a-9134-ef0d8e39bc6d.png)

**Comment by TamiGaming** [comment]
![image](https://user-images.githubusercontent.com/40512639/128632191-aa676307-62d8-40f6-991b-bb292bdbc9dd.png)
Gleiches Problem auch, wenn man keine Tattoos am Bein hat.

**Comment by Enemyaa** [comment]
Ich guck mal ob ich da was machen kann. Danke für die Info!
