### ISSUE TITLE
Diamond Hoodie wechselt sich bei Kaputze nutzen

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1812]
**Character Name**
Emilia Porter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.08.2021

**Beobachtetes Verhalten**
Sie hat den Hoodie ([F] Grauer Diamond Hoodie) angezogen und die Kapuze genutzt, nachdem ich die Kapuze wieder abgenommen habe. ist der Hoodie plötzlich durch "[F] Weißer Los Santos Hoodie" ersetzt worden.
Der Ursprünglich Hoodie ist dann weg.

**Erwartetes Verhalten**
Das Die Hoodies nicht das Modell wechseln beim Kapuze nutzen

**Schritte um den Fehler nachvollziehen zu können**
Grauer Diamond Hoodie anziehen und Kapuze nutzen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Hutstaender** [comment]
fixed next update
