### ISSUE TITLE
Verbesserungsvorschlag  Serviertabletts

### ISSUE THREAD

**Issue by glb11** [mexyn/statev_v2_issues#1813]
**Character Name**
Jens_Summer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Zeit dem Update mit dem Restáurant Essen

**Beobachtetes Verhalten**

Aktuell sind die Serviertabletts komplett Kosten los und Wertlos (Verhinder Reclingmüll (Wo von aus wieder Leute leben)
Weil mit Jeden Tablett wird Müll verhindert (z.B. 5x Waser, Eistee, Spezi = 5 leere Plastikflaschen ; 5 Dosen Red BuV, Spunk  = 5 leere Dosen; 5 V-Burger =  5 schmutzige Essenschachtel;  5 Döner = 5 schmutziges Papier)

**Erwartetes Verhalten**

Die Serviertabletts müssen in der Fertigung (z.B. Für 5 Tablets --> 15 Sack Kunstoffgranulart + 2 Rolle Pappe (Einlege Böden auf dem Serviertabletts)) her gestellt werden und es wird im Resaturant ein Servieraufschlag verlangt. (Vorteil: wäre es muss sich auch im Restaurant drum gekümmert werden --> es wird auch einige Restaurants geben die Sowas nicht anbieten, weil sie sich nicht darum kümmern wollen --> Wieder etwas mehr Wetbewerb unter den Restaurants)  

Die Benutzen Serviertabletts sollte mann im Reclinghof wieder recycln/aufbereiten können:

_Variante 1_  
Mann Zerlegt die Serviertabeletts wieder in seine Einzelteile  --> z.B. Sack Kunstoffgranulart (natürlich mit weniger wie mann zur Herstellung braucht) (z.B: für 5 Serviertabletts bekommt mann dann 12 Sack Kunstoffgranulart und etwas Schmutzige Essenschachtel /Papier) 

_Variante 2_
Man Reinigt die Serviertabletts im Reclinghof z.B. Man braucht für 10 schmutzige Serviertablettes 2 Liter Wasser (vieleicht auch einen Schwann oder Lappen noch dazu (dann vieleicht ehr 30/40 Serviertabletts mit einmal)) zum reinigen 
-->  raus kommt 1 Liter Dreckiges Wasser , 10 sauber Serviertabletts, + Random: 30-50 Recyclingrohstoffe der Getränke (leere Plastikflasche, Leere Glasflasche, leere Dose) und noch 0-30 Recyclingrohstoffe von den Essensgerichte (Schmutzige Essenschachtel, Schmutziges Papier).  Diese werden dan dem regulären Recyling Prozess wieder zugefürt 
(Bei dem Random Sachen auch immer eine Mischung aus den jeweiligen Rohstoffen zu bevorzugen)

_Variante 3_
Eine Kombination aus Variante 1+2 das mann das Serviertablett Zerstört und in Sack Kunstoffgranulart und Schmutige Esenschachtel/Papier umwandelt + den Random Faktor mit den Recyclingrohstoffen (Von Variante 2) noch hinzu bekommt, diese müssen dann in einem seperaten Prozessen weiter recyelt werden.

**_Achtung:
Alle genanten Zahlen sind Vorschläge und stehen halbwegs im Verhältnis zueinander_**

Mich wüde eine Rückmeldung sehr Freuen  
Bei anden Vorschlägen auch gerne in die Komentare hier drunter

Vielen Dank im Vorraus für die Bemühungen

**Comment by its4l3x** [comment]
Bitte in Forum-Bereich "Vorschläge".

Somit erstmal closed. In Zukunft auch keine Enhancement Sachen mehr im Bugtracker.
