### ISSUE TITLE
Ein Schwung neuer Masken?

### ISSUE THREAD

**Issue by Koree7** [mexyn/statev_v2_issues#1814]
Hey,

damit mal ein wenig Abwechslung in das Schnuffeltuch-Game kommt, wäre es möglich Gesichtsschals, Kopftücher, Schlauchschals, etc. hinzuzufügen? Sind ja so schon in GTA:O vorhanden. 
Siehe Bilder: 

Schlauchschal vom Diamond-Casino-Heist:
![image](https://user-images.githubusercontent.com/51489673/128596955-ace1b8ab-c9ab-4d3e-b235-030853905b6d.png)

Gesichtsschal:
![image](https://user-images.githubusercontent.com/51489673/128596971-f973f1fb-4be2-4120-8b69-05c22a884529.png)

Kopftuch:
![image](https://user-images.githubusercontent.com/51489673/128596978-5a324d02-8ffc-4eac-87d9-85004e8b5b9f.png)

loses Kopftuch:
![image](https://user-images.githubusercontent.com/51489673/128596990-b9e9c1f0-9fb1-4cef-ae37-dce87acb9822.png)

**Comment by DonVitoDiangelo** [comment]
Vorschläge ab sofort bitte nur noch im Forum. Div. Masken und Kleidung generell werden nach und nach implementiert.
