### ISSUE TITLE
Vapid Taxi Scheibentönung

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#1815]
Auf V1 war es noch möglich, seitdem V2 am Start ist bleiben die Scheiben trotz Folie einfach durchsichtig.

Ist da eventuell was machbar?

Zudem kann man am Taxi keine Unterbodenbeleuchtung anbringen, jemand anderes hat bei der Justiz durchsetzen können das die UB als frei/besetzt Licht leuchten darf.

Könnt ihr hier auch bitte schauen?

**Comment by Hutstaender** [comment]
Unterbodenlicht hat das Taxi noch nie gehabt, da es kein Fahrzeug ist, was von Spielern erworben werden kann. Ähnlich wie andere Öffentliche Fahrzeuge.

Zum Window Tint habe ich mal einiges durchprobiert und scheinbar lassen die sich beim Taxi gar nicht setzen. Jetzt ist nur die Frage ob es ein AltV issue ist, oder ob hier das gleiche Problem wie beim Kuruma etc. besteht und Rockstar das mit einem der Patches kaputt gemacht hat.

Ich schließe den Beitrag vorerst, da wir selbst daran leider nichts ändern können.
