### ISSUE TITLE
Antrag auf Hausgrößen Änderung

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#1817]
Guten Tag, ich wollte nachfragen, ob es möglich wäre die Größe des Hauses paletobay8 von 1 auf 2 zu erhöhen, da das Haus äußerlich recht Groß ist und auch mehrere Etagen besitzt und es kleinere Häuser mit Größe 2 gibt. 

Größe Grundriss: 
![20210808112155_1](https://user-images.githubusercontent.com/58612983/128629762-a66f9ba0-052a-47f7-92a4-b9099e4dd05c.jpg)

Mehrere Etagen: 
![20210808112036_1](https://user-images.githubusercontent.com/58612983/128629770-f7682ad3-75ac-47cf-be28-8f3b46e84610.jpg)

**Comment by DonVitoDiangelo** [comment]
abgelehn t
