### ISSUE TITLE
Verbesserungsvorschlag: Random-Inhalte von Mülltonnen

### ISSUE THREAD

**Issue by zarazandra** [mexyn/statev_v2_issues#182]
**Character Name**
Shiva_Connelly; gilt für alle

**Zeitpunkt (Datum / Uhrzeit)**
immer

**Beobachtetes Verhalten**
Die Idee mit den Mülleimern ist FANTASTISCH! Ich liebe sie und habe mir sowas schon lange gewünscht. Leider fehlt aktuell die Attraktivität, auch aktiv in die Dinger hinein zu schauen. Tendenziell wird man leere Flaschen zum Beispiel eher sammeln und dann irgendwo an Punkten, wo eh viel los ist, loswerden wie am Würfelpark. Dem könnte man mit ein paar random Gegenständen entgegenwirken. 

**Erwartetes Verhalten**
Wenn man in eine Mülltonne reinschaut, kann man hin- und wieder ein paar random Gegenstände finden, zum Beispiel einen Akku oder ein Bündel Tomaten. Zwischendrin vielleicht auch mal einen Glücksgriff und man findet einen Baseballschläger oder so. Das würde viel frischen Wind reinbringen und die Leute ermutigen, vielleicht einfach mal in eine Tonne reinzuschauen, wenn man eine sieht. 
Den Inhalt könnte man mit jedem Serverneustart spawnen - wenn weg, dann weg. Oder alle X Stunden. Es muss auch nicht in jeder Tonne was drin sein, aber eben in manchen. 

**Schritte um den Fehler nachvollziehen zu können**
In die Mülltonnen schauen :) 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by zarazandra** [comment]
Hinweis: Alle meine Verbesserungsvorschläge gelten natürlich nicht für Day 1 von V2, sondern eher allgemein. No pressure. :)

**Comment by DonVitoDiangelo** [comment]
aktuell nein, es werden "Abfälle" von Mitbürgern in den Mülltonnen liegen. Dies soll auch erst einmal so bleiben.
