### ISSUE TITLE
Frisurenwechsel unter Helm/Cap

### ISSUE THREAD

**Issue by RudiRanger** [mexyn/statev_v2_issues#1820]
**Rudi_Ranger**
**Samstag 07.08.21 / ca. 21 UHR - andauernd**
als ich vom Friseur zurück gekommen bin und meinen Bauarbeiterhelm erst aufgesetzt und dann abgesetzt habe, hatte ich wieder einer Glatze. Ich hab bemerkt das ich immer wenn ich den Bauarbeiterhelm aufsetzte, eine der 24 Frisuren die man unter dem Helm wählen kann behalte, wenn ich diesen wieder absetze. Sollte denk ich mal nicht so sein. 
Etwas später ist mir aufgefallen dass das gleiche auch mit eine Cap funktioniert. Ich habe jetzt mal den Server Neustart um 15 Uhr abgewartet aber das Problem ist weiterhin vorhanden. 
Was kann man tun?

PS. das ist mein erste Beitrag Überhaupt, falls ich was falsch gemacht habe, Sorry
[Frisur.odt](https://github.com/mexyn/statev_v2_issues/files/6950967/Frisur.odt)

**Comment by DonVitoDiangelo** [comment]
Bitte lade Bilder in den Anhang mit hoch und nicht in einem Word Dokument danke.

**Comment by RudiRanger** [comment]
Hallo, das Problem besteht weiterhin. Ich trage nun einfach immer Glatze, etwas ärgerlich aber hab mich schon dran gewöhnt.
