### ISSUE TITLE
Barracks hat kein Nummernschild

### ISSUE THREAD

**Issue by cadpri** [mexyn/statev_v2_issues#1821]
Fabian Picard

**Auftrittszeitpunkt (Datum / Uhrzeit)**
08.08.2021 20:46

**Beobachtetes Verhalten**
Der HVY Barracks hat nur eine Chrome Blende dort wo das Nummerschild sein sollte.
Sowohl bei der Übergabe im Autohaus als auch beim Kennzeichenwechsel.
Fahrzeug ist angemeldet und hat ein Gültiges Kennzeichen.

**Erwartetes Verhalten**
Kennzeichen sollte sichtbar sein

**Schritte um den Fehler nachvollziehen zu können**
Barracks anschauen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
Niemand sieht es. Liegt also nicht an der Monitorauflösung

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/i/qvvqR.jpg

**Comment by Statev-Bonsai** [comment]
Der Barracks hat von Haus (GTA) aus kein Nummernschild, ist ja auch ein Staatsfahrzeug (US Army)...

**Comment by cadpri** [comment]
Ah okay. Gut zu wissen :)
Dann kann das hier ja geschlossen werden :D
