### ISSUE TITLE
Entladepunkt versetzen

### ISSUE THREAD

**Issue by JimBaker5387** [mexyn/statev_v2_issues#1822]
Jim Baker

Bitte für die Firma "HK-K510 | GHC Melting Pot" den Entladepunkt versetzen. Durch die Laterne und den Baum ist es umständlich mit einer Achse zu rangieren. In der Seitenstraße wäre genug Platz. 
Ausserdem wollte ich mal nachfragen ob es möglich wäre links neben der bestehenden Firma eine neue Firma zu eröffnen, die Räumlichkeiten wären vorhanden. Vielen Dank im Vorraus.
Firmen-Hash: pfAkiPillboxRew_6
![Ladepunkt](https://user-images.githubusercontent.com/88632735/128645241-41718113-8c16-4c7f-a7e0-83a795bd3f22.jpg)

**Comment by AdnanT57** [comment]
Heyho allerseits.. Ich würde mal einen kleinen Einwand zugeben. Das Gebäude nebenan ist mein Hotel und das ist die direkte Zufahrt zum Parkplatz, weshalb dieser Abladepunkt sehr ungelegen wäre. Besser würde ich es finden, wenn der Abladepunkt weiter auf der Straße, also quasi vor der Firma wäre.

Grüße
Adnan

**Comment by JimBaker5387** [comment]
Falls ich nochmal was dazu sagen darf, wenn man auf dem Verladepunkt steht ist links daneben noch genug Platz für (grosse) Fahrzeuge zum durchfahren. Man steht da ja auch nicht den ganzen Tag. Auf der Strasse bereitet es mir doch etwas sorgen weil hier sehr oft sehr schnell vorbeigefahren wird. Hinterm Gebäude wäre theoretisch auch genug Platz aber da hat man dann die rennerei zur Firmentüre und das Fahrzeug mit dem offenen Kofferraum steht unbewacht Rum.

**Comment by DonVitoDiangelo** [comment]
Verladepunkt wird auf die Straße  bzw. den Straßenrand verlegt. Du musst ja nicht auf der Straße stehen, von daher ist das ja kein Problem.

**Comment by JimBaker5387** [comment]
OK, vielen Dank für die Bearbeitung.
LG
