### ISSUE TITLE
[Marktplatz] Bitte " Trinkglas" hinzufügen.

### ISSUE THREAD

**Issue by SternChef** [mexyn/statev_v2_issues#1823]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Stella Sanchez

**Auftrittszeitpunkt (Datum / Uhrzeit)**
09.08.2021 / 08:43 Uhr

**Beobachtetes Verhalten**
Die Ware "Trinkglas " lässt sich nicht im Marktplatz verkaufen.

**Erwartetes Verhalten**
Die Korrektur im Markplatz; so das auch " Trinkglas " verkauft werden kann.

Danke!

**Comment by Hutstaender** [comment]
fixed next update
