### ISSUE TITLE
Bauchnabelpiercing durch kleidung sichtbar

### ISSUE THREAD

**Issue by Minakiu** [mexyn/statev_v2_issues#1824]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Mina Harris

Mina Harris

**Auftrittszeitpunkt (Datum / Uhrzeit)**
08.08.2021 / 22 Uhr

**Beobachtetes Verhalten**
Nachdem das Piercing gestochen wurde und ich einige Kleidungsstücke angezogen habe, konnte man das Piercing durch die Kleidung sehen.

**Erwartetes Verhalten**
Richtigerweise, müsste das Piercing nicht sichtbar sein.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/87786538/128724452-8da141e9-275e-4d72-8f31-5a28e49c339d.png)
![image](https://user-images.githubusercontent.com/87786538/128724590-8bdaa8b3-7ce6-4bee-8d67-c42ea84e786f.png)
![image](https://user-images.githubusercontent.com/87786538/128724682-7c71425c-568a-4d0d-9953-82b68d12a7cb.png)
![image](https://user-images.githubusercontent.com/87786538/128724855-0b4b1398-33f0-4e13-b6fd-997aba76e369.png)

**Comment by DonVitoDiangelo** [comment]
Dann das Piercing vllt. einfach  "ausziehen"?

**Comment by Enemyaa** [comment]
Piercings sind permanent.

**Comment by its4l3x** [comment]
Werden hier erstmal keine Änderungen vornehmen, daher closed.
