### ISSUE TITLE
Mülleimer in Restaurants sind gesynct

### ISSUE THREAD

**Issue by NeedManu** [mexyn/statev_v2_issues#1825]
**Character Name**
Martin_Henks

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.08.2021

**Beobachtetes Verhalten**
Alle Mülleimer in Restaurants haben immer den Selben Inhalt

**Erwartetes Verhalten**
Jeder Mülleimer sollte sein eigenes "Inventar" haben

**Schritte um den Fehler nachvollziehen zu können**
Ins Restaurant gehen und Müll in den Mülleimer legen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/IBNyBEgxVro

**Comment by glb11** [comment]
Ich (Als "Müllmann") finde es nur "eine" Mülltonne gibt.
Wenn mann  als "Müllmann" die einzelnen Mülltonnen + Restaurant abklappert ist mann über 1,5h unterwegs und wenn dann noch in jedem Restaurant 4 Mülltonnen hat, verlängert sich die Zeit nochmal ummindestens nee Halbe Stunde.  Vobei es kaum Menge bringt weil ja jeder nur 2 kilo groß ist.  (Den Müll den mann Sammelt Deckt gerade mal sie Spritkosten)

Jetzt mein Vorschlag:

1 Ich würde es besser finden wenn es bei einer Mülltonne bleibt und dafür das Verfassungsmenü größer sind.  (4*2=8  Also mindestens 8KG beser 10-15KG (mit dem jetzigen Tablet Gewicht)

2 Wenn mann es auf 4 Mülltonnen aufteilt wäre es schöne wenn es eine möglichkeit gebe als Müllmann wo man es von einer Tonne alles abhollen kann.
