### ISSUE TITLE
Peyote Custom fehlende Tuningoption "Dach"

### ISSUE THREAD

**Issue by iDropBombs** [mexyn/statev_v2_issues#1826]
**Character Name**
Declan Montague

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.08.2021 / 17:30 Uhr

**Beobachtetes Verhalten**
Peyote Custom verfügt nicht über die Tuningkategorie "Dach" bzw. ist auch in keiner anderen Kategorie der Dachumbau möglich. Laut GTA V Wiki ist es allerdings möglich das Dach bei diesem Fahrzeug abzuändern bzw. sogar zu demontieren.

**Erwartetes Verhalten**
Vielleicht mal nachsehen, ob da nicht vergessen wurde die Tuningoption des Daches mit einzubinden, das Fahrzeug kam ja recht neu dazu.

**Schritte um den Fehler nachvollziehen zu können**
Peyote Custom Tuningmenü kontrollieren oder eben in der Config schauen.

**Optional: Video / Bilder des Fehlers**
Ich denke zum nachvollziehen sind hier keine Bilder nötig. Falls doch reiche ich gern nach was gewünscht wird.

**Comment by Hutstaender** [comment]
Das Fahrzeug hat unter AltV leider keine Dach Tuning option. Hab alles durchrpbiert, das Dach bleibt immer auf Option 2.
