### ISSUE TITLE
Stay Tuned Hoodies nicht für andere sichtbar

### ISSUE THREAD

**Issue by Michi993** [mexyn/statev_v2_issues#1827]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Luke Hammer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Stay Tuned Hoodies werden nicht richtig angezeigt (bei anderen als Lederjacke oder unsichtbar)

**Erwartetes Verhalten**
sollten richtig angezeigt werden

**Schritte um den Fehler nachvollziehen zu können**
Kein plan

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
#1799
