### ISSUE TITLE
Essenanimation canceln durch Handy

### ISSUE THREAD

**Issue by TamiGaming** [mexyn/statev_v2_issues#1828]
**Character Name**
Carlie Tacus

**Auftrittszeitpunkt (Datum / Uhrzeit)**
13.08.2021

**Beobachtetes Verhalten**
Wenn man in einem Restaurant sitzt und isst kann durch das ziehen und wieder wegstecken des Telefons die Animation gecancelt werden und einfach weggegangen werden.

**Erwartetes Verhalten**
Charakter sollte sitzen bleiben.

**Schritte um den Fehler nachvollziehen zu können**
An einen Tisch setzen, Essen und dann das Telefon öffnen.

**Comment by Hutstaender** [comment]
Das kommt nicht durch das Handy, sondern durch nochmaliges E drücken beim essen und schließen.

**Comment by Bene-RonnyMoritz** [comment]
Passiert auch beim Y drücken, dass man vom Tisch aufsteht und sich frei bewegen kann

**Comment by ShauniKT** [comment]
Ist mir jetzt gerade auch passiert.Nachdem ich mein telefonat aufgelegt habe, ist mein Char aufgestanden und Stuckte dann stehend auf dem Tisch
