### ISSUE TITLE
Bandana Visual Bug

### ISSUE THREAD

**Issue by Samadez** [mexyn/statev_v2_issues#1829]
![sfwefgw](https://user-images.githubusercontent.com/88893018/129368369-b30c35b8-a476-4bcd-ad36-9c8255491e4f.png)

Beim Bandana glitcht ein Teil der Nase durch (an der Nase selbst wurde nichts verändert, ist ein normales Gesicht)

**Comment by Chrinis007** [comment]
Duplikat von #564
