### ISSUE TITLE
Verbesserungsvorschlag: Favoritenordner v. Animationen und Gehstilen auf Numblock speichern?

### ISSUE THREAD

**Issue by zarazandra** [mexyn/statev_v2_issues#183]
**Character Name**
Shiva_Connelly; gilt für alle

**Zeitpunkt (Datum / Uhrzeit)**
immer

**Beobachtetes Verhalten**
Der Numblock ist nun nicht mehr belegt, abgesehen von der Helisteuerung, die man, nun, nur im Heli braucht. Wenn man im Heli sitzt, wird man eher selten Animationen und Gehstile benutzen wollen. ;) 

**Erwartetes Verhalten**
Wäre es möglich, die verschiedenen Favoritenordner auf die Zahlen zu packen, also wenn ich z.B. die 1 gedrückt halte, das Radialmenü der gespeicherte Animationsordner "Tanzen", den ich angelegt und auf die 1 gebunden habe, zu öffnen und auswählen zu können?
Man könnte zum Beispiel auf die Null entsprechend die Gehstile als Radialmenü packen. Das wäre mega geil. 
Der Übersicht halber könnte man vielleicht die Möglichkeit bieten, custom Buttonicons einzufügen? Wenn ich z.B. zehn Animationen im Radialmenü habe, sehe ich die Namen ja auch nur, wenn ich mit der Maus drüber fahre, wenn ich das richtig in Erinnerung habe. Eventuell könnte man, wenn man die Dinger speichert, kleine Icons selbst hochladen ODER man definiert für jede Aktion etwas? Vielleicht ein Kürzel? A28 für die 28. Animation in Allgemein, von der man dann, wenn man's benutzt, irgendwann weiß, dass das, keine Ahnung, Brogreet ist? Man sieht dann halt auf jeden Fall schonmal, wohin man mit der Maus muss, ohne erst auswendig zu lernen, wo was liegen könnte. 

Ich weiß, wäre ne scheiss Menge an Arbeit, da wir auch wirklich viele Animationen haben (DANKE dafür!! Liebe geht raus!), würde bei solchen "Strafarbeiten" auch unterstützen sofern möglich. 

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by zarazandra** [comment]
Hinweis: Alle meine Verbesserungsvorschläge gelten natürlich nicht für Day 1 von V2, sondern eher allgemein. No pressure. :)

**Comment by DonVitoDiangelo** [comment]
Ist derzeit nicht geplant.
