### ISSUE TITLE
Idee woran das liegt? 

### ISSUE THREAD

**Issue by LukiSchnuki** [mexyn/statev_v2_issues#1830]
![image](https://user-images.githubusercontent.com/88906088/129408971-f633f6f4-098d-4200-9843-f2d6ecbab9e3.png)

**Comment by CatherineGallagher** [comment]
Das hättest du auch leicht im Discord oder im Forum suchen können :) , da wäre dir schneller geholfen worden. Du musst einfach auf den Server über die Serverliste connecten.

**Comment by DrGrizzlY17** [comment]
Bitte über Direct Connect oder Serverliste
