### ISSUE TITLE
Hotelgäste fliegen aus Zimmer

### ISSUE THREAD

**Issue by DrColgate** [mexyn/statev_v2_issues#1832]
**Character Name**
Anton Mueller

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Kann ich nicht genau sagen, mindestens seit mehreren Tagen

**Beobachtetes Verhalten**
Scheinbar werden Spieler aus ihren Hotelzimmern gekickt.
Ich dachte erst die Spieler würden das Zimmer selber verlassen, um die Fahrzeugmiete zu umgehen.
Das sind die beiden Hotels der Fahrzeugvermietung:
JunSandyShoresRew_Flat_22
JunSandyShoresRew_Flat_21

Bis uns jemand aus unserem Hotel in Paleto anrief, weshalb wir ihm das Hotelzimmer gekündigt hatten. Er war aus 2 von 3 Zimmern geflogen.
Wir haben ihn jedoch nicht rausgeworfen.
Das Hotel aus Paleto:
JunPaletoRew_Flat_6

Mir selber ist es noch nicht passiert. Ich habe 2 Zimmer in dem Hotel aus Paleto und noch ein weiteres in einem Hotel in Sandy.

4x habe ich das nur beobachten. Im Verhältnis zu der Gesamzmieterzahlt ist das wirklich nur ein bruchteil.

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrColgate** [comment]
bei dem herren aus paleto ist es ausgeschlossen das sein konto nicht gedeckt war

**Comment by CCastles22** [comment]
Hatte auch schon 2-3 Fälle wo die Mieter hoch und heilig versprochen hatten das ihr Konto gedeckt war und sie nicht selbständig raus sind !

**Comment by TheOutburst** [comment]
Wir werden uns sämtliche Hotelbugs mit StateNET 2.0 annehmen #942
