### ISSUE TITLE
T20 nur als "Sportwagen" geflagged?

### ISSUE THREAD

**Issue by Koree7** [mexyn/statev_v2_issues#1833]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Brooks Miller

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14.08.2021 14:16

**Beobachtetes Verhalten**
T20 hat nur ein Sportwagen Flag obwohl er ein Supersportler ist.
Als Vergleich:

- Turismo R (Supersportwagen) - 295 PS - 270+ Km/h
- T20 (Sportwagen) - 305 PS -  ca 240 Km/h

Ist es gewollt, dass der T20 "nur" als Sportwagen geflagged wurde?

**Comment by sYnaTiion** [comment]
Was soll man sagen... 

Thrax - 419PS - 245 Km/h 
XXR - 242PS  - 270 Km/h

**Comment by Koree7** [comment]
> T20 ist als Super Sportler geflaggt...
> 
> Aber dennoch könnte man sich über die Geschwindigkeiten unterhalten.
> Finde den Unterschied zwischen XXR und Thrax / XXR und T20 schon heftig.
> 
> Thrax - 419PS - 245 Km/h
> XXR - 242PS - 270 Km/h

Ah du hast recht, hatte nur bei einer Firefox App gesehen, dass er dort als Sportwagen gelistet ist.
Aber im Allgemeinen sind die Unterschiede mancher Höchstgeschwindigkeiten etwas "komisch".

**Comment by sYnaTiion** [comment]
vielleicht kann man ja nochmal darüber nachdenken.

**Comment by DrGrizzlY17** [comment]
Zum Thema der Flag... Closed
