### ISSUE TITLE
Rumpo Custom hat nur 250kg anstatt 300kg 

### ISSUE THREAD

**Issue by tristan1297** [mexyn/statev_v2_issues#1834]
**Character Name**
Peter_Rumpe

**Auftrittszeitpunkt (Datum / Uhrzeit)**
15.08.2021 20:00

**Beobachtetes Verhalten**
Der Rumpo Custom hat laut Wiki 300kg Kofferraum. Ingame sind es jedoch nur 250kg

**Erwartetes Verhalten**
Er sollte wie im Wiki beschrieben 300kg haben. Allerdings haben Burrito, Speedo und Speedo Custom, man könnte es alles eventuell auch auf 350kg anheben

**Schritte um den Fehler nachvollziehen zu können**
Rumpo Custom kaufen und den Kofferraum mit der Angabe im Wiki vergleichen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Chrinis007** [comment]
Duplikat von #1643 
Kann somit closed werden da es so bleiben wird.

Aber im Forum kann’s umgeändert werden auf 250kg damit das überein stimmt
