### ISSUE TITLE
Stafford lässt sich nicht im Autohaus überschreiben

### ISSUE THREAD

**Issue by RuedigerRommel** [mexyn/statev_v2_issues#1835]
## WICHTIGE INFORMATION!!:

#1770 Fehler besteht immer noch 
Wurde am 15.08.2021 getestet

**Comment by Romeny1** [comment]
Der Wagen wurde zwar auf mich überschrieben, aktuell steht das Fahrzeug aber noch in der Liste vom Autohaus bzw. die Tankrechnungen gehen nicht an mich sondern ans Autohaus.

**Comment by DrGrizzlY17** [comment]
Wir haben wohl irgendwie was ähnliches. Sie kennt die Autos gar nicht, ist aber als Besitzerin aufgeführt und gleichzeit das Autohaus

![image](https://user-images.githubusercontent.com/70150988/130092902-c14b9d04-f09a-4be4-9ab3-d6a30bb2380d.png)

**Comment by VictorCorticera** [comment]
Dass sie als Besitzerin aufgeführt ist, deutet darauf hin, dass sie die Inhaberin ist. Zumindest war das früher so. Diese Fahrzeuge sollten also immer noch auf das Autohaus geschrieben sein.

**Comment by Hutstaender** [comment]
Stafford Ist mit dem nächsten Update fixed. Der Motor war falsch defniert, stand mit 180ps statt mit 48ps in den jsons
