### ISSUE TITLE
Sachen sind verschwunden

### ISSUE THREAD

**Issue by HansKelly** [mexyn/statev_v2_issues#1836]
**Hans Kelly**

Hans Kelly
**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.08.2021 um 13:30Uhr

**Beobachtetes Verhalten**
Ich bin zwar gestern gestorben in der Klettermine und haben nadem ich aus dem Notfall MD wieder kam alles neu gekauft alle sachen fürs Klettern habe diese in meine Rucksack gelegt und habeden Rucksack in der Gießerrei gelgt ich bin dann in die nurmale mine eisen sammel gegangen bis etwa Heute früh um 03:30Uhr bin dan in die Gießerrei gefahren und habe alles entleert selbst da habe ich ein 2 Rucksack mit meine Mine  arbeit sachen wie Spitzhacke und Helm reingelgt, Heute wollte ich wieder los um zu arbeiten da ist mir aufgefallen das meine kleetermine sachen sowie meine Mine sachen weg sind zwar sind die rucksäcke noch da aber Leer es ist nix mehr drin.

**Erwartetes Verhalten**
Das meine sachen nicht verschwinden 

Ich bitte doch sehr drum das nachgeschaut wird wo die sachen hin sind und das ich sie wenigstens wieder ersetze bekomme 
Danke um vorfehlt schon mal

**Comment by Chrinis007** [comment]
Volle Rucksäcke nicht in Lager reinlegen, wurde aber oft genug vom Team kommuniziert

**Comment by HansKelly** [comment]
komisch das wenn ich sie in mein haus lege nix passiert und friuersladen auch nicht nur in der gießerei

**Comment by Koree7** [comment]
Ausnahmen bestätigen die Regel. Habe auch vor nem Jahr ein Rucksack voller Weihnachtsmasken verloren. Aus Fehlern lernt man.

**Comment by DrGrizzlY17** [comment]
> Volle Rucksäcke nicht in Lager reinlegen, wurde aber oft genug vom Team kommuniziert

Sollte seit v2 eigentlich kein Problem mehr sein. Wurde so aber auch von uns so kommuniziert ;)

Muss geguckt werden ob es reproduziert werden kann. Sollte eigentlich nicht vorkommen, seit v2 wird der inhalt auch gesaved
