### ISSUE TITLE
Einige Supersportler langsamer als andere

### ISSUE THREAD

**Issue by Koree7** [mexyn/statev_v2_issues#1837]
Hallo, wie bei #1833 angesprochen fahren einige Supersportler deutlich langsamer als andere.
Zum Beispiel:

- Turismo R - 295 PS - 270+ Km/h
- T20  - 305 PS - ca 240 Km/h
- Thrax - 419PS - 245 Km/h
-  XXR - 242PS - 270 Km/h
- Cyclone - 246 PS - 270 Km/h
- Cop Mustang - 260 Km/h  :-P
- Pfister Comet ("nur" ein Sportwagen) - 256 PS - 270 Km/h

Leider hab ich keine Erfahrung wie es mit anderen Supersportlern aussieht.
Jedoch finde ich, dass, bei den oben genannten Beispielen, T20 und Thrax schneller bzw. den anderen angepasst werden sollte.

Grüße

**Comment by sYnaTiion** [comment]
Stehe zu 100% hinter deiner Aussage.

**Comment by epichalt** [comment]
Zunächst stimmen die Geschwindigkeitswerte nicht. Bei manchen habt ihr Topspeed mit Bodenwellen aufgeschrieben und bei anderen eben nicht. Daher kommen schon einige wirre Zahlen zustande. 

Und endgeschwindigkeit ist nicht alles. 
Mein Taipan ist bisher das schnellste (von mir gemessene) Fahrzeug was die Endgeschwindigkeit angeht(abgesehen von Hypercars) dafür ist das Ding in der Stadt oder in Kurven ein Krampf. Bodenwellen mach das Auto auch langsamer statt schneller. 

Der T20 dagegen hat eine sehr gute Beschleunigung und frisst die Bodenwellen auf. Dafür ist er ohne Bodenwellen eben in der Spitze langsamer. 

Der Thrax dafür hat ein sehr gutes Handling. 

Ich bin froh, dass nicht jeder Supersportler sich 1:1 identisch fährt und natürlich ist es vlt nicht 100% perfekt gebalanced, aber das wird auch nie klappen weil jeder andere Vorlieben hat. Während der eine eher auf Beschleunigung steht, möchte der andere eben topspeed. Wenn du alles haben willst, muss nen hypercar her. 

Bevor der T20 zum Volkswagen wurde, war er echt beliebt weil er für die Stadt optimal ist mit der Beschleunigung.

**Comment by sYnaTiion** [comment]
T20 hat die bessere Beschleunigung und das besseres Handling als ein Thrax..
ist zudem genauso schnell mit und ohne Bodenwelle..
Es sagt hier keiner das plötzlich alle 270+ fahren sollen es wird nur gesagt das ein T20 und ein Thrax zumindest die 250 ez aufm Highway packen sollten... selbst ein Seven 70 schaffte letztens noch 240 - 245 auf der geraden, wie es jz ist keine ahnung.

**Comment by Koree7** [comment]
Das Thema um die Bodenwellen spreche ich erst gar nicht an, weil das für mich kein Indiz dafür ist, wie schnell ein Auto sein soll.
Bei den genannten Fahrzeugen bin ich jedes selbst gefahren außer den Trax und natürlich den Mustang.
Und ich denke nicht, dass das Handling usw. mit dem Ganzen was zutun hat, da die Neupreise der Fahrzeuge die selben sind wie in V1. Zu V2 wurde das Handling ja eher GTA:O angepasst.
Und zum Vergleich, warum der T20 vermutlich eine bessere Beschleunigung hat als dein Taipan, das könnte daran liegen, dass der T20 AWD hat und der Taipan RWD.

**Comment by epichalt** [comment]
Wenn die Bodenwellen kein Indiz für dich sind, wieso zählst du dann die Topspeeds mit Bodenwellen auf? 
Die Taipan Höchstgeschwindigkeit ohne Bodenwellen ist bei 265kmh. Natürlich muss man es wo anders testen und nicht auf dem Highway da es dort trotzdem Bodenwellen gibt. 
Der Comet fährt ohne Bodenwellen etwa 253kmh. Das ist eher das Problem für mich. Wieso fährt ein Comet schneller als viele Supersportler? Wieso schafft ein Comet SR es dann nicht, welcher im Prinzip ein Nachfolger des Comets ist? 

Durch die ganzen Bodenwellen ist ein perfektes Balancing unmöglich. Mit dem 811er bin ich letztens 330 auf dem Highway gefahren mit 2-3 guten Bodenwellen. Ohne Bodenwellen knackt er nicht mal die 235. 

Ich stimme zu, dass ein Thrax, aber auch der 811er ein paar kmh zusätzlich vertragen könnten. Aber der t20 auf Grund der guten Beschleunigung usw. nicht.

**Comment by Koree7** [comment]
Die Info über den Comet hab ich über Promo. Aber der Comet wurde ja auch vor kurzem erst angepasst. Mit Bodenwellen erreicht er ca. die 300. Aber trotzdem ist es für den Comet, der um die 100k kostet, einfach zu schnell wenn er ohne Bodenwellen 250 Km/h fährt.

**Comment by epichalt** [comment]
Naja angepasst nicht, durch das altv Update wurde er langsamer. Er hatte dann eigl Normalgeschwindigkeit für die Autos in seiner Klasse, aber er war wohl nur ein „bug“. Nach dem Update wollte jeder seinen Comet verkaufen, jetzt nimmer ^.^

**Comment by Koree7** [comment]
Aber lustigerweise, der der das Ticket erstellt hatte für den Comet, möchte sein Comet nun verkaufen 😄 
Trotzdem ist momentan der Comet der schnellste seiner Klasse und einiger Supersportler.

**Comment by DrGrizzlY17** [comment]
Ist es so tragisch das ein Fahrzeug mal langsamer fährt als das andere? Wenn ja, wie wirkt sich das auf euer RP aus. Weitere Frage, ist denn ein Auto das 270 fährt so RP fördernd, das es unbedingt angepasst werden muss?

Der T20 ist für mich persönlich nicht mehr in dieser gruppe der supersportler drinne, da er hinterher geschmissen wurde bei den replacements für AMG, Audi und BMW. Welche übrigens keine Supersportler waren.

**Comment by Koree7** [comment]
Fürs RP an sich ist mir das total Schnuppe. Es geht mir eher um das Balancing der Fahrzeuge.

Warum sollte ein Auto welches einen Herstellungspreis von 280k+ hat ungefähr die gleiche Höchstgeschwindigkeit haben wie Fahrzeuge, die 130k-150k oder sogar weniger haben.
Wie bei #1759 fuhr der Comet vorher am Vinewood Blvd max. 310 Km/h. Nach dem Tuners-Update 264 Km/h.
Das wurde anschließend gefixt (wie der Comet nun fährt, keine Ahnung).
An selber Stelle mit dem T20 (https://streamable.com/yev7vz) "nur" 285 Km/h.
Der T20 schaltet sogar bei 235 Km/h in den letzten Gang für die letzten 5-10 Km/h 🤣 

Bei dem Punkt, dass der T20 hinterher geschmissen wurde stimme ich dir zu, da zu sehr auf den preislichen Unterschied zwischen Austausch- und Importfahrzeugen geschaut wurde von den jeweiligen Spielern, was natürlich nun den Wiederverkaufspreis rechtfertigt.

**Comment by DrGrizzlY17** [comment]
Ja das Balancing vom Comet kann man nicht vergleichen wenn der von GTA generfed wurde.

Du wirst immer haben das ein Fahrzeug für 130k genauso schnell sein wird wie eins für 240k. Alleine weil die Fahrphysik von GTA so ist zwecks Unebenheiten etc. das so hergibt. Da nen akkurates Balancing wäre so eine enorme Arbeit. 

Mich würde aber eher interessieren, welches Auto für 130k so schnell ist wie ein Supersportler. Da kann man eher dran arbeiten. Und wir reden nicht von den Geschwindigkeiten in der Stadt. Da kannste einfach nichts gegen machen.

**Comment by epichalt** [comment]
Der Comet, ein etwa 100k Fahrzeug ist  auf dem Flugfeld 253kmh schnell. Damit schneller in der Endgeschwidigkeit als ein Thrax, t20, Nero custom, Visione, 811, xa21, und vermutlich noch einige Supersportler mehr, die ich noch nicht gefahren bin seit dem Umstieg auf v2. 
schneller in der Endgeschwindigkeit ist meiner Info nach aktuell der XXR und der Taipan. Vermutlich noch ein paar andere, aber die bin ich nicht gefahren

**Comment by DrGrizzlY17** [comment]
Ich teste mal

**Comment by DonVitoDiangelo** [comment]
Es wird nicht alles gleich schnell fahren, gleich teuer sein und gleich schnell beschleunigen.
Die Fahrzeuge wurden damals zu V2 alle überarbeitet, an diesem Stand wird in dem Sinne nichts geändert.
Wir werden div. Fahrzeuge prüfen, aber ich möchte da jetzt auch keine Versprechungen machen. Wir schauen uns das ganze mal an. Falls es Anpassungen geben wird, werdet Ihr es im Changelog erfahren.
