### ISSUE TITLE
Deep V Unterhemd hat keine richtige Langarm-Einstellung

### ISSUE THREAD

**Issue by Koree7** [mexyn/statev_v2_issues#1838]
**Character Name**
Brooks Miller

**Beobachtetes Verhalten**
Beim Deep V Unterhemd hat man keine richtige Langarm-Einstellung.
Bei Langarm 4 ist ein Teil der Brust abgeschnitten, bei Langarm 5 clippt die Brust durch das Sakko.

**Erwartetes Verhalten**
Richtige Einstellung für das Hemd.

**Optional: Video / Bilder des Fehlers**
![GTA5_zgyp5S9GCJ](https://user-images.githubusercontent.com/51489673/130082467-942bccda-b983-40ca-9cd2-118000c57577.png)
![GTA5_9T6PVI4kES](https://user-images.githubusercontent.com/51489673/130082477-b1341017-a245-4c62-9b26-379d792f8c5a.png)

**Comment by Enemyaa** [comment]
Es gibt nur die erste Einstellung und dass die Brust dabei rausblitzt, liegt daran, dass man das Unterhemd nur unter wenigen Sakko's tragen kann, die einen bestimmten Schnitt haben.

**Comment by CaleighRhodes** [comment]
Deep V ganz gefährlich. Bei den Frauen kannst es nur mit dem sackigen Sakko tragen, weil sonst haste Armreifen :D
