### ISSUE TITLE
Kofferraum öffnet sich nach Unfall, jedoch kann ich nichts entnehmen

### ISSUE THREAD

**Issue by Ekaz58** [mexyn/statev_v2_issues#1839]
**Rainer Kornn**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Beobachtetes Verhalten**
Bei einem Totalschaden, egal in welcher form lässt sich bei meinem Sultan Classic sowie bei dem Vapid Bullet der Kofferraum zwar öffnen, jedoch sehe ich das Inventar nicht und dies macht es unmöglich das Auto zu reparieren bzw. den Reparaturkasten oder sonstiges aus dem Kofferraum zu nehmen. Ob es auch bei anderen Autos ist weiß ich nicht. Andere Spieler haben das Problem nicht bzw. kennen es auch nicht. 

**Erwartetes Verhalten**
Beim öffnen des Kofferraums lässt sich das Kofferraum Inventar öffnen und mit diesem interagieren.

Mfg der Rainer

**Comment by MarcelMuerto** [comment]
Konnte es bisher nicht reproduzieren.

**Comment by Ekaz58** [comment]
Okay ich teste es Sonntag nochmal und erstelle ein Video dazu. Gruß!

**Comment by TheBroady** [comment]
Mein Wissensstand war das es gewollt ist. Fahrzeuge die derart beschädigt wurden haben keinen Kofferraum Zugriff und eine Reparatur über den Abschleppdienst ist zwingend erforderlich. 
So mein letzter Stand.

Zumal bei gewissen Unfallstärken ein Repkit einfach fail wäre.

**Comment by Statev-Bonsai** [comment]
So soll es ja auch sein, bzw war schon immer so!..
Rainer, du schreibst oben von Totalschaden, aber im gleichen Atemzug von Reparaturkasten..Merkst du selber oder? ;)

**Comment by Ekaz58** [comment]
Okay :D ja der Rainer ist ja mit jahrelanger erfahrung als mechaniker eigentlich geschult dafür 😋 #mechanikersagtsorry
