### ISSUE TITLE
Patientenhemd Schwarze Fingernägel 

### ISSUE THREAD

**Issue by KorbysWorld** [mexyn/statev_v2_issues#1841]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Josh Korby

Josh Korby
**Auftrittszeitpunkt (Datum / Uhrzeit)**

21.08.21 / 22:16
**Beobachtetes Verhalten**

Beim Anziehen vom Patientenhemd bekommt man schwarze Fingernägel
**Erwartetes Verhalten**

Fingernägel die bleiben normal und verändern sich nicht.
**Schritte um den Fehler nachvollziehen zu können**

Komplett nackt machen ... auf die hand achten ... Patientenhemd anziehen und wieder auf die hand achten. 

Fingernägel syncro isz da. 

**Optional: Video / Bilder des Fehlers**

https://pic.statev.de/image/ohne-nagellack.qJ3TX  - ohne Nagellack

https://pic.statev.de/image/mit-nagellack.qJ8XU  - mit nagellack

**Comment by Enemyaa** [comment]
Muss ich gucken, ob ich daran überhaupt was ändern kann. Danke für die Info!
