### ISSUE TITLE
Firmenkomplex zu Teuer? Soll das so sein?

### ISSUE THREAD

**Issue by falco7712** [mexyn/statev_v2_issues#1844]
**Character Name**
Louis Gambino

**Beobachtetes Verhalten**
Für mich nicht verständlich wie dieser Firmenkomplex der Deutlich runtergekommen ist **463500$** Kostet. Die umlegende Gebäude aber zwischen 350 ~ 385k kosten obwohl dies viel Luxuriöser ist.  

**Erwartetes Verhalten**
Der Preis von dem Firmenkomplex sollte meiner Meinung nach den umlegenden Objekten angepasst werden. 

**Optional: Video / Bilder des Fehlers**
Firmenkomplex für 463500$ pro Firmen **(Runtergekomme)**
[https://pic.statev.de/image/20210823050044-1.qqdgy](url)
[https://pic.statev.de/image/20210823045142-1.qqDAU](url)
Firmenkomplex eine Straße weiter für 386250$ deutlich **Luxuriöser** ist. 
[https://pic.statev.de/content/images/system/logo_1527643124282_1c67ed.png](url)

**Comment by DonVitoDiangelo** [comment]
Der Preis wird bleiben. Die Preise wurden damals der Lage und Größe angepasst. Es kann natürlich sein, dass die Läden mal etwas teurer und mal etwas billiger ausfallen. Aber wenn dir dieser Komplex je nach Lage zu teuer ist, dann kaufst du Ihn halt nicht und schaust dich wo anders um.
