### ISSUE TITLE
Autos Respawnen bei LS Customs/MagicX

### ISSUE THREAD

**Issue by KruemelGames** [mexyn/statev_v2_issues#1848]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Dave Weinstein

25.08.2021 02:07 Uhr

Wichtig! Nicht nur ich habe das Problem! Es ist kein Client-Seitiges Sync Problem. Andere sehen das gleiche und können das Auto nutzen.
Autos Respawnen an der Werkstatt (MagicX). Passiert immer wenn Leute in Interiours gehen, sei es Hotel oder Restaurant. Passiert gefühlt in 2km Umgebung. Alleine heute/gestern (20Uhr-3.00) 4 mal passiert. Egal ob Reparatur oder Tuning. Noch nie bei Lackierung passiert. Fahrzeuge respawnen im Reperatur Bereich sowie auf den Parkplätzen zu 100% derzeit. Nirgends dazwischen beim fahren etc. 

Fahrzeuge Respawnen nicht und bleiben an Ort und Stelle wo sie abgestellt wurdne bevor man ein Interiour betritt. 

Einen Abend bei MagicX verbringen, Leute in Interiours gehen lassen nachdem sie bei uns repariert haben.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

https://www.youtube.com/watch?v=61nkSXH8cSk
https://www.youtube.com/watch?v=-9bZKWraJjg
2tes Video paar Minuten nach dem ersten erstellt. Gleiches Problem.

Zusatz:
Sollte das Problem schon bekannt sein, sollte dies dringend behoben werden. Denn das Problem tritt in den letzten Tagen öffters auf. 1mal in der Woche okay... aber 4mal am Tag? Erklär das man den Kunden im RP?!?! Langsam wird es einfach nervig weil es auch die Werkstatt versperrt und ich nen kleinen Abschlepper rufen darf. An sich kein Ding aber sowas darf einfach nicht sein oder weiterhin vorkommen. Wenn das Problem bereits bekannt ist bzw nicht von StateV gelöst werden kann, bitte ich darum dies dem AltV Team mitzuteilen so dass es im nächsten Update gefixt wird.

**Comment by Statev-Bonsai** [comment]
Dieses Problem besteht schon seid Monaten, bislang weiß wohl niemand wie man es reproduziert und behebt.
Mich nervt es auch ungemein..

**Comment by JulianMa** [comment]
Siehe #400 
Der Fehler ist bekannt, kann aber durch alt:V nicht behoben werden, da er nicht verlässig reproduzierbar ist.
Ich schließe den Issue deshalb erstmal mit Verweis auf das Sammelticket.
