### ISSUE TITLE
Trailer 200

### ISSUE THREAD

**Issue by AxelAichinger** [mexyn/statev_v2_issues#1852]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Axel_Aichinger*

**Auftrittszeitpunkt (25,08,2021 / 22:30)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (1920 x 1080  16:9)**
Hänger Auf reparatur punkt gefahren und die reparatur gestartet nach fertigstellung ist das stutzrad in den boden gebugt und der hänger kann nicht mehr angekuppelt werden

**Comment by TheOutburst** [comment]
@AxelAichinger 
ich kriege den Bug nur zum Teil reproduziert. Der Anhänger buggt zwar leicht in den Boden rein, aber ich kann ihn ohne weitere Probleme anhängen. Ich habe ein paar Fragen zum setup:

Was für ein Fahrzeug war dein Zugfahrzeug?
Ist mit dem Anhänger irgendwas vorher passiert? (bzw warum repariert man überhaupt nen Anhänger?)
War der Anhänger zum Zeitpunkt angekoppelt oder abgekoppelt?
