### ISSUE TITLE
Nach Vor-Ort Behandung durch MD, Bugs

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1853]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.08.2021 / gg. 23:00

**Beobachtetes Verhalten**
Nach Bewusstlosigkeit u. Vor-Ort Behandlung durch LSMD wurde die Sprachreichweite nicht mehr in den entsprechenden Kreisen (grün / blau / orange) dargestellt. Zudem wurde beim nächsten Tanken das Tank UI nicht geladen und ich war darin stuck. Während Restart konnte aber Kollege problemlos tanken und den Wagen dann auch wegfahren. Nach diesem Restart wurde auch die Sprachreichweite wieder dargestellt. 

**Schritte um den Fehler nachvollziehen zu können**

Bewusstlos --> Vor Ort Behandlung --> Sprachreichweite verändern / tanken

https://youtu.be/8Hx2z73NL8o

**Comment by JannikDatsch** [comment]
Auch das Dispatch System (M)

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2046

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2438
