### ISSUE TITLE
Rucksack im Auto verschwunden

### ISSUE THREAD

**Issue by Erumeldor** [mexyn/statev_v2_issues#1855]
**Character Name**
Jon_Lewis

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Irgendwann zwischen 28.08 01:00Uhr und 28.08 12:00Uhr

**Beobachtetes Verhalten**
Ein Rucksack gefüllt mit Klamotten nachts in den Kofferraum eines Autos gelegt. Das Auto wurde kurz davor ausgeparkt und direkt danach wieder eingeparkt. (Garage am ADAC)
Mittags das Auto ausgeparkt, Rucksack war verschwunden.
Vermutlich sehr schwer zu reproduzieren. Mir wurde anschließend IC gesagt das man vorsichtig sein soll gefüllte Rucksäcke ins Auto zu legen. Wohnung Lager etc. sei kein Problem, Autos wohl schon.

**Comment by Erumeldor** [comment]
Achja, könnte vielleicht auch etwas mit #1863 zu tun haben(?)

**Comment by Chrinis007** [comment]
Duplikat von #1836

**Comment by JulianMa** [comment]
Kein Duplikat, da hier andere Mechanismen greifen als in der Fabrik.

**Comment by JulianMa** [comment]
Kannst du mir bitte einmal das Kennzeichen das Fahrzeuges geben?

**Comment by Hutstaender** [comment]
In der Zeit waren mehrere Personen am Kofferraum des Fahrzeugs, es ist nicht auszuschließen dass ihn jemand herausgenommen hat. Bisher sind keine weiteren Meldungen von verschwundenen Taschen in Fahrzeugen aufgetaucht, die sich nicht auf herausnehmen zurückführen ließen. Daher vorerst closed. Sollte noch was auftreten bitte erneut öffnen.
