### ISSUE TITLE
Abladepunkt umsetzen

### ISSUE THREAD

**Issue by Saaria83** [mexyn/statev_v2_issues#1857]
Huhu Ihrse

Wäre es möglich meine Abladepunkte von 3 leicht versetzten, auf einen gemeinsamen zu versetzen?
Das würde das umlagern deutlich angenehmer machen, ohne immer wieder das Fahrzeug um zu parken. 

Hanna Jung

Die Firmenabladepunkte die zusammengeführt werden sollen sind

Pure Storage
Pure Foundry
Pure Labs

![GTA5_udfxcHhSi2](https://user-images.githubusercontent.com/70151476/131380549-67bce1cc-2dc4-4f94-8c22-455ba9234b06.jpg)

Dort die ersten 3 Punkte zusammen auf einen :)

**Comment by DrGrizzlY17** [comment]
Bitte hashes oder Adresse hinzufügen.

**Comment by Saaria83** [comment]
Hups, vergessen^^

Pure Foundry - Carson Ave. 27 
Pure Storage - Carson Ave. 29
Pure Labs - Carson Ave. 30

**Comment by DrGrizzlY17** [comment]
Dankö
