### ISSUE TITLE
Hotel - Kann Mieter nicht entfernen keine letzte miete 

### ISSUE THREAD

**Issue by falco7712** [mexyn/statev_v2_issues#1858]
**Louis_Gambino**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
30.08.2021 | 21:01

**Beobachtetes Verhalten**
Kann Mieter nicht aus dem Hotel schmeißen da keine Letzte Miete vorhanden ist. 
![chrome_StbvcM9QVh](https://user-images.githubusercontent.com/79071390/131393056-97667dbb-9793-4573-a78f-d86cf300fb9e.png)
**Erwartetes Verhalten**
Das ich die Mieter entfernen kann // oder sie entfernt werden. 

**Wichtige Informationen über das Hotel**
Firmenhash:	RockfordHills_Flat_5
Firmenname:	Global - Home

Mieter nicht entfernbar:
Tomi_Gan 
James_Green 
Syko_Muerte
Dennis_Darf 
Agnieszka_Domanski 
Till_Lindemann 
Mario_Santoro
Berry_Allen 
Doc_Baker 
Fiona_Clarke 
Iron_Sheldor 
Jin_Toujo

**Comment by Chrinis007** [comment]
Wahrscheinlich eingemietet und nie wieder online gekommen

**Comment by JulianMa** [comment]
Hier wurde offensichtlich nicht das Datum beim Einzug gesetzt. Ich würde das zum nächsten Server Restart auf das aktuelle Datum setzten. 
Ihr müsst dann aber leider noch die 30 Tage Frist für die Betroffenen Mieter abwarten..
Der Fehler selbst wird in einem zukünftigen Update behoben.

**Comment by TheOutburst** [comment]
Wir werden uns sämtliche Hotelbugs mit StateNET 2.0 annehmen #942
