### ISSUE TITLE
[M] Mexican Sagged Bandana Verpackt mit doppeltem Leerzeichen

### ISSUE THREAD

**Issue by TamiGaming** [mexyn/statev_v2_issues#1859]
**Character Name**
Carlie Tacus

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.09.2021

**Beobachtetes Verhalten**
Im Produktionscomputer der Schneiderei findet man das [M] Mexican Sagged Bandana nur mit Eingabe von einem doppelten Leerzeichen zwischen Mexican und Sagged. 
Bei den entpackten [M] Mexican Sagged Bandana ist es nur ein Leerzeichen und somit richtig.

**Erwartetes Verhalten**
Nur ein Leerzeichen zwischen Mexican und Sagged.

**Schritte um den Fehler nachvollziehen zu können**
In Schneiderei nach Mexican Sagged Bandana suchen.

**Comment by Enemyaa** [comment]
Danke dir für die Info!

Next Update dann!
