### ISSUE TITLE
Alkoholtester messen 1,0 bei nicht-alkoholisierten Personen

### ISSUE THREAD

**Issue by FunnyBuddys** [mexyn/statev_v2_issues#1860]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Ranjid_Boniakale

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.09.2021; 16:50

**Beobachtetes Verhalten**
Beim Messen des Atemalkoholwertes mittels eines Alkoholtesters werden bei nicht-alkoholisierten Personen ein Atemalkoholwert i.H. von exakt 1,0 gemessen.

**Erwartetes Verhalten**
nicht-alkoholisierte Personen sollen lediglich einen Atemalkoholwert von 0,0 aufweisen.

**Schritte um den Fehler nachvollziehen zu können**
Einen Alkoholtest an einer nüchternen Person durchführen.

**Optional: Video / Bilder des Fehlers**

Hier ein Bild von einem Alkoholtest, der an mir ausgeführt worden ist, obwohl kein Konsum von Alkohol stattgefunden hat.
![Screenshot_41](https://user-images.githubusercontent.com/16995710/132025968-5e394d82-0852-4da1-a512-d827b51a79fc.png)

**Comment by Chrinis007** [comment]
Nytech Technologie halt :P

**Comment by FunnyBuddys** [comment]
Edit: Scheinbar zeigt es bei allen Personen unabhängig vom Alkoholkonsum, einen Atemalkoholwert von 1,0

**Comment by JannikDatsch** [comment]
So, isses, ist aber erst seit kurzem so.

**Comment by its4l3x** [comment]
fixed
