### ISSUE TITLE
Paisley Sandanas nicht in allen Farben verfügbar

### ISSUE THREAD

**Issue by TamiGaming** [mexyn/statev_v2_issues#1862]
**Character Name**
Carlie Tacus

**Beobachtetes Verhalten**
Paisley Sandanas sind in allen Farben herstellbar bis auf Braun, Grau, Orange und Rosa. 
Wäre es möglich diese mit einzufügen, da es alle anderen Arten von Bandanas auch in diesen Farben gibt?

**Erwartetes Verhalten**
Sandanas sind in allen Farben herstellbar.

![image](https://user-images.githubusercontent.com/40512639/132039575-057d61dd-16de-4bfb-b527-1b47def2c3b0.png)

**Comment by Enemyaa** [comment]
Coole Übersichert :) Kommt dann beim nächsten größeren Update!
