### ISSUE TITLE
Taucherausrüstung funktioniert nicht / ertrunken

### ISSUE THREAD

**Issue by Gallidubma** [mexyn/statev_v2_issues#1864]
Hallo, ich bin gerade in StateV durch einen Bug gestorben und versuche den mal zu erläutern: 
Wenn man tauchen will, braucht man eine Tauchausrüstung und diese funktioniert bekannterweise nur, wenn man bereits im Wasser ist und schwimmt, während man sie anzieht. Das habe ich mit einem Kumpel zusammen gemacht (wir haben die ganze Zeit vom ins Wasser gehen bis zum Tod telefoniert). Dann sind wir runtergetaucht, nach ca. 5 Sekunden bin ich nochmal kurz an die Oberfläche, weil ich anscheinend zu weit oben war und deshalb ist der Charakter "automatisch aufgetaucht". Aber das Wasser sollte tief genug sein, sodass ich durchgängig geschwommen bin und nie gestanden habe. Ich bin wieder runter und nach wenigen Sekunden (vielleicht 10-15) ertrunken. Ich bin nicht verhungert/verdurstet und war auch sonst bei nahezu voller Gesundheit bevor ich ertrunken bin.
Ich weiß nicht ob das normal ist, aber nach meinem vermeintlichen Tod war mein Lebensbalken ein zweites mal voll  und ging nochmal langsam zurück bis ich schließlich nochmal tot war. Ich konnte mich dabei aber nicht bewegen und hatte schon die typische "Ertrunkenen-Animation", also Rücken nach oben und Beine + Arme nach unten.
Die Sanitäter kamen zu spät und ich starb letztendlich.
Hoffe der Bug kann irgendwie behoben werden.

Leider hab ich keine Bilder oder Videos gemacht.

Mit freundlichen Grüßen,
Hannes Hawkins :)

**Comment by Bene-RonnyMoritz** [comment]
Mal ne Nebenfrage. Wie kann man unter Wasser telefonieren? 🤨

**Comment by Chrinis007** [comment]
Naja wenn dein Charakter jetzt tot ist Würde ich mich evtl an deiner Stelle drum kümmern dass du n neuen bekommst

**Comment by SvenPhoenix** [comment]
Naja die Taucherausrüstung ist ein GTA Feature und StateV hat nur die Funktion des anlegens verändert. Die Taucherflasche ist für den ,,unendlichen" Sauerstoff unterwasser verantwortlich. 
Ich gehe selber relativ viel Tauchen und hatte diesen Bug noch nie.
In GTA dauert es standartmäßig 40 Sekunden bis man keinen Sauerstoff unterwasser mehr zum Atmen hat.
Außerdem stirbt man dann nicht sofort sondern man bekommt erstmal Schaden.
Es kann sein das irgendwelche Rucksäcke den Taucherflaschen-Effekt verhindern aber dazu kann ich leider nichts sagen (Habe es mal gehört aber weiß nicht ob es stimmt).
Die Medics machen übrigens nur sehr selten Wasserrettung weil es keine Wasserrettungseinheit bzw. Ausrüstung gibt.
Ich gehe mal grob davon aus das dein Char nicht Tot ist sondern nur Bewusstlos und irgendwo gerespawnt ist.
LG
Sven

**Comment by its4l3x** [comment]
So wie Sven es sagte.

Closed
