### ISSUE TITLE
Nichts bleibt auf dem Tisch

### ISSUE THREAD

**Issue by RoyMckellar** [mexyn/statev_v2_issues#1866]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Nichts bleibt auf dem Tisch

**Erwartetes Verhalten**
Alles was ich dort abstelle sollte dort auch bleiben.

**Schritte um den Fehler nachvollziehen zu können**
Tisch und was drauf stellen. Nach dem man im Gebäude war oder weiter weg und zurück kommt, ist das nicht Lustig. Auch andere Leute sehen das dann unter dem Tisch liegen und du nicht.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/zgI7zdjeiFo

**Comment by CatherineGallagher** [comment]
dupilicat was du selbst damals erstellt hast ^^ ,denke mal zu heute hat sich da nicht viel geändert

https://github.com/mexyn/statev_v2_issues/issues/487

**Comment by its4l3x** [comment]
Ist schon bereits seit mehreren Wochen bekannt, werden wir aber auch erstmal nicht fixen, da wir dazu eine Queue brauchen, welche wir aber gerade nicht haben und das ein größerer Aufwand wäre.

Sorry für eben, falscher Post :)
