### ISSUE TITLE
Tisch und Stühle sind nicht fürs PR zu gebrauchen.

### ISSUE THREAD

**Issue by RoyMckellar** [mexyn/statev_v2_issues#1867]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Roy Mckellar

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit V.2 immer

**Beobachtetes Verhalten**
Die Stühle, Tisch und Grill werden nur von einem Spieler gesehen. Wenn ich mich hinsetze sehe ich, dass ich auf dem Stuhl sitze, mein Besuch sieht den Stuhl am Boden liegen.

**Erwartetes Verhalten**
Ich würde mich tierisch freuen, wenn das entsorgt wird. 

**Schritte um den Fehler nachvollziehen zu können**
Dazu kannst du den Tisch mal verschieben und lässt dich dann von einem Freund Besuchen und fragst ihn, auf welchem Tisch ich stehe oder wo der Tisch steht.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/T79L2YJapSA

**Comment by its4l3x** [comment]
Ist schon bereits seit mehreren Wochen bekannt, werden wir aber auch erstmal nicht fixen, da wir dazu eine Queue brauchen, welche wir aber gerade nicht haben und das ein größerer Aufwand wäre.

**Comment by DrGrizzlY17** [comment]
Ich versteh nicht so ganz das Problem. Du hast da nen riesen Grundstück wo du selber noch was aufstellen könntest.
Und das vorhandene einfach für die Optik da lassen. Da ich hier einfach kein Störfaktor sehe und du das potential hast mit dem verfügbaren Platz selber Objekte zu platzieren wo man Sitzgelegenheiten schaffen kann, lehne ich das ab.
