### ISSUE TITLE
Teleport nach Ragdoll im Hotel

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1868]
**Character Name**
Jason Brook (für ihn eingereicht)

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.09.21 - 20:50 

**Beobachtetes Verhalten**
Ich bin mit meinem Char im Hotelzimmer in die gezeigte Ecke gesprungen und wurde anschließend zum WP oder in eine Tiefgarage geportet.
Ich habe dort niemand anderen gesehen denke also ich bin dort in einer anderen Dimension.
Ein Reconnect behebt das dann wieder.

Ka ob das fixbar ist. Da es sich hier ja um die "Ragdoll" Funktionalität von Rockstar handelt. (Anti Stuck System)

**Erwartetes Verhalten**
Es passiert nichts und ich bleibe in meinem Zimmer

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://streamable.com/s91hpi

**Comment by Hutstaender** [comment]
Is bekannt, musst du an Rockstar weiterleiten. Das geht in GTA Online genauso.
