### ISSUE TITLE
Konto fehlerhaft

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#1869]
**Character Name**
Marvin_Elpe

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit gestern

**Beobachtetes Verhalten**
Konto mit der VBAN 168816 kann keinen runden Betrag mehr haben. Beispiel: Aktuell sind $11.000 drauf, ich überweise $1000. Es werden anschließend aber nur $11.999,99 angezeigt. Überweise ich anschließend z.B $1000,01, sind dann $13.000,01 drauf.

**Erwartetes Verhalten**
Kontostand wird richtig angezeigt

**Comment by Chrinis007** [comment]
Wahrscheinlich hast einmal mit der Karte bezahlt und da wurde irgend n Betrag wie 100,000052 abgebucht

**Comment by M4rvinLP** [comment]
Ist tatsächlich ein Sparkonto

**Comment by TheBroady** [comment]
![image](https://user-images.githubusercontent.com/70150887/132545594-2016acf5-3b31-4971-ac48-856af416a88e.png)
Hier ein Auszug von meinem Hauptkonto. So dinge wie %-Steuern sind denke ich der Grund

Dadurch hat das Konto weit mehr als 2 nachkommastellen.
Und dann eine Kombination aus Rundung wodurch das Problem dann auftritt.

**Comment by M4rvinLP** [comment]
@TheBroady konnte es fixen für mich.

**Comment by TheBroady** [comment]
Ideal wäre das man es unterbindet das es mehr als 2 nachkommastellen für ein Konto geben kann.
