### ISSUE TITLE
Wohnung nicht bezahlt dennoch weiterhin drin

### ISSUE THREAD

**Issue by Slayraw** [mexyn/statev_v2_issues#1870]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Simon_Riley

Simon_Riley
**Auftrittszeitpunkt (Datum / Uhrzeit)**

08.09.2021 16:21
**Beobachtetes Verhalten**

Nachdem die miete Abgezogen wurde (hatte 20$ auf dem konto) Bekam ich die nachricht das meine Wohnung gekündigt wurde durch nicht bezahlen der miete. Ich bin hin gefahren und wohnte immer noch dort. Miete wurde aber nicht vom konto abgezogen! Somit habe sozusagen eine stunde gratis gewohnt
**Erwartetes Verhalten**

Das meine Wohnung gekündigt wird oder die miete nach dem hartzV abgezogen wird
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Chrinis007** [comment]
Vielleicht behältst die noch ne Stunde Schonfrist?

**Comment by Slayraw** [comment]
Laut kollegen wurde ihre wohnung direkt gekündigt als sie das Problem hatten. desweiteren ändert es ja nicht das man dennoch die Meldung bekommt das wohnung gekündigt worden ist und man ne stunde gratis wohnt

**Comment by Slayraw** [comment]
Update: Nach einer Stunde wurde miete wieder nicht abgezogen dennoch weiterhin bin ich wohnhaft im Hotel. Laut tablet (habe zugriff aufs Hotel) bin ich aber bereits ausgezogen bzw gekündigt.

**Comment by KruemelGames** [comment]
@Slayraw am besten mal die Hotel Adresse mit angeben damit die Dev's das direkt überprüfen können. Sowas wie "Alta Street 2", zu finden am blauen Punkt.

**Comment by Slayraw** [comment]
ChamberlainHills_Flat_6_2 ist die adresse
