### ISSUE TITLE
Cargohose X, Knöchel fehlt

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1871]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
09.09 01:00

**Beobachtetes Verhalten**
siehe Vid

**Optional: Video / Bilder des Fehlers**

https://youtu.be/TwF7gLaMbcc

**Comment by Chrinis007** [comment]
Du brauchst Schuhe mit Socken, war zu v1 schon genau so :)

**Comment by Stiefel911** [comment]
Stiefel mein Bester, Stiefel ;)

**Comment by TheOutburst** [comment]
Diese Hose gibt es nicht in "langer" Version, wie geschrieben brauchst du da bestimmte Schuhe als Kombination für.
