### ISSUE TITLE
Garage am Haus möglich?

### ISSUE THREAD

**Issue by SgtTukiTuki** [mexyn/statev_v2_issues#1872]
Ich habe ein Haus erworben was keine eigene Garage hat, aber diese im Tablet Angezeigt wird. Nun frage ich mich, ob es möglich wäre diese Garage nutzbar zu machen. 

![InkedScreenshot_48_LI](https://user-images.githubusercontent.com/87803938/132698823-7e7d63d4-b73b-48c7-bf2c-49ac76802025.jpg)

![Screenshot_49](https://user-images.githubusercontent.com/87803938/132697913-7e179163-4927-4df3-904b-f21b00256c2c.png)
![Screenshot_50](https://user-images.githubusercontent.com/87803938/132697916-ad1059e7-c0b8-4c61-bff6-2cbcf00e0b9e.png)
![Screenshot_52](https://user-images.githubusercontent.com/87803938/132697918-da66b9a3-a3d5-4509-9cbb-f1d972cacc1c.png)

Weiss ja nicht ob dieser "hasenstall" hinten genutzt werden kann um die Garage dort zu setzen und den Ein und Aus und Ladepunkt davor in der Einfahrt setzen könnte.

Mfg 
Sandy Folk

**Comment by VictorCorticera** [comment]
Jedes Haus auch ohne Garage zeigt im Tablet trotzdem die Garage an. Das Menü ist halt bei jedem Haus das gleiche ;)

**Comment by TheOutburst** [comment]
Das Haus hat leider keine Garage, wie du schon selbst geschrieben hast, da ist keine Hausgarage möglich.
