### ISSUE TITLE
Kofferraum-Platzierung GB200 falsch

### ISSUE THREAD

**Issue by KruemelGames** [mexyn/statev_v2_issues#1873]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Dave_Weinstein

Immer

Kofferraum ist nur hinten erreichbar, trotz dass der Kofferraum vorne ist.

Ich kann den Kofferraum vorne nutzen ohne nach hinten laufen zu müssen.

GB200 (197PS) Kofferaum aufmachen und merken dass er vorne nicht erreichbar ist. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

https://www.youtube.com/watch?v=jMm-3AicZ8g

**Comment by Dean-Gallagher** [comment]
Das haben tatsächlich einige fahrzeuge dies problem.

**Comment by DonVitoDiangelo** [comment]
Jap, das ist leider so und wird sich vermutlich auch nicht ändern.
