### ISSUE TITLE
Damaliges Auto verschwunden

### ISSUE THREAD

**Issue by Entenbrust** [mexyn/statev_v2_issues#1874]
**Rudi Entenbrust**

Nach Rücksprache mit einem GM erläutere ich mein Problem hier: 
Damals (2019) hatte ich zu meiner Assistenzarztzeit im alten MD einen Audi A4 gekauft. Ende ´19 musste ich aufgrund meinen Studiums erst einmal ausreisen. Nun bin ich seit 3 Tagen wieder da, jedoch ist der Audi nirgends auffindbar. Weder im Tablet, noch wo anders. 
Einen Schlüssel habe ich noch im Portemonnaie. Die anderen hatte ich in meinem Haus. Das dortige Inventar ist ebenfalls verschwunden. Dies ist mir aber soweit egal. 
Ich finde den Audi weder im Tablet, noch sonst wo. Ich habe ihn sicher nicht verkauft! 
Meine Kontoauszüge kann ich leider nicht mehr bis 2019 zurück scrollen. Vielleicht könnt ihr dies? 

Ich hoffe es wird eine Lösung für das Problem gefunden, da ich mich nach meiner Wiedereinreise auf das Auto gefreut habe (Nun weiß ich das es diese nicht mehr gibt. Aber es kann ja nicht weg sein) 

Beste Grüße, Rudi Entenbrust

**Comment by Stiefel911** [comment]
alle gemoddeten Autos wurden mal entfern ( zuviele Poly) und man konnte sich einen Ersatz im TS Support geben lassen.
Hätte dir gerne die Liste gegeben aber ich kann es einfach nicht mehr finden. ;) Weiß auch nicht mehr ob es im Forum stand, was ich ehr glaube, oder hier im Bugtracker.

**Comment by Entenbrust** [comment]
genau. aber um es zu ersetzen, muss es ja iwo sein. Da es nicht in meinem tablet oder sonst wo zu finden ist, wird das wohl schwer. wobei das teil auch geld gekostet hat

**Comment by Stiefel911** [comment]
> genau. aber um es zu ersetzen, muss es ja iwo sein. Da es nicht in meinem >Tablet oder sonst wo zu finden ist, wird das wohl schwer. wobei das teil auch geld gekostet hat

diese sind quasie rausgelöscht worden und man bekam Ersatz über dem Support, da gab/gibt es irgendwo eine List wo man zwischen 2 Autos als Ersatz sich aussuchen durfte. Da du ja noch einen Schlüssel für ein Fahrzeug hast was nicht mehr Existent ist, Denke ich sollte es als evtl Beweis reichen. Ich weiß aber leider auch nicht mehr ob es da eine 2 Wöchige Zeitspanne bestand wo man dies erstattet bekommen hat. Was ja nicht mehr da ist, kann auch nicht mehr irgendwo angezeigt werden ;)

**Comment by Entenbrust** [comment]
Ich hoffe ein GM nimmt sich dem ganzen nochmal an. Wäre schade ums Geld

**Comment by CaleighRhodes** [comment]
> > genau. aber um es zu ersetzen, muss es ja iwo sein. Da es nicht in meinem >Tablet oder sonst wo zu finden ist, wird das wohl schwer. wobei das teil auch geld gekostet hat
> 
> diese sind quasie rausgelöscht worden und man bekam Ersatz über dem Support, da gab/gibt es irgendwo eine List wo man zwischen 2 Autos als Ersatz sich aussuchen durfte. 

Was du meinst war der RS7. Der A4 wurde schon im November 2020 rausgenommen. da gab es 3 Ersatzautos, aus denen man auswählen konnte. ABER: Wenn Entenbrust das Fahrzeug nicht findet, ist das schlecht, weil selbst wenn du noch ein so altes Auto faktisch besitzt, wird es dir im Tablet noch angezeigt.

**Comment by Entenbrust** [comment]
Genau das ist das Problem. Es wird nicht mehr angezeigt :/

**Comment by CaleighRhodes** [comment]
Ich drücke dir sehr die Daumen, dass es zu deinen Gunsten aufgeklärt werden kann.

Übrigens kann ich bis zur ersten Buchung auf meinem Konto im Februar 2020 zurück gehen, macht sich aber besser im OOC Browser. Einfach eeeeeeeeewig runter scrollen und immer kurz warten, dann werden ältere Buchungen ausgewiesen.

**Comment by Entenbrust** [comment]
ich kann komischerweise nur bis vor 3 tagen zurück scrollen, als ich wieder einreiste. Obwohl es das alte Konto ist. Iwas ist da ganz komisch

**Comment by TheOutburst** [comment]
@Entenbrust Das ganze ist ein wenig kniffeliger, lass dich bitte im Ts Support ans Development weiterleiten, gerne mit Verweis auf den Bugtracker hier.

**Comment by Entenbrust** [comment]
Kann man im TS einen festen Termin bekommen? Nicht so schön nach Feierabend über ne Stunde dort zu warten :D

**Comment by eiksch** [comment]
Komm einfach heute nochmal, dann wird sich darum gekümmert.
