### ISSUE TITLE
Hotelzimmer grundlos verloren..

### ISSUE THREAD

**Issue by ZacCooperr** [mexyn/statev_v2_issues#1876]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Zac Cooper

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Geschätzter Zeitraum zwischen den (12.09 und dem 14.09.) Genau können wir das aber nicht sagen und kann durchaus schon paar Tage länger der Fall sein.

**Beobachtetes Verhalten**
Ohne Vorwarnung verlieren Personen aus unserem Hotel ( The PinkCage Motel - Hawick Ave. 69 ) Zimmer, die Sie mieten und bezahlen. Das erste mal ist es uns Mitte Juli aufgefallen,(hier waren es direkt 4 Zimmer) jedoch konnten wir die betreffenen Personen nicht ausfindig machen.
Seitdem führen wir eine Liste, da wir bei diesem Objekt genau darauf achten, wer ein Zimmer bekommt.

Heute haben wir per Mail erhalten, dass wir einen neuen Mieter haben.
Die betroffene Person war aber das letzte mal am 12.09. Anwesend, dass ein 30Tage rauswurf ausgeschlossen ist. Ein nachfragen der Person hat ergeben, dass das Konto zur jederzeit ausreichend gedeckt war.
Er besitzt auch weiterer Zimmer in diesem Hotel, welche noch auf Ihn laufen.

**Erwartetes Verhalten**
Das Zimmer wird so lange behalten, bis der Kunde entweder die Miete nicht zahlen kann, selbstständig kündigt oder nach 30 Tagen gekündigt wird. Welch ein schaden dadurch entstehen kann, wenn Personen grundlos das Zimmer verlieren ist..

**Schritte um den Fehler nachvollziehen zu können**
S. Beschreibung sowie:

Es handelt sich hierbei um Hotel/Zimmer:
The PinkCage Motel - Hawick Ave. 69
Vinewood_Flat_1_18 - Mieter: Vince_Creed
Vinewood_Flat_1_18 - Ehemals Mieter: Carlos_Capone

**Optional: Video / Bilder des Fehlers**

Vielen Dank vorab.
Anbei Bilder von unserer Liste mitte Juli sowie nun der aktuelle Mieter und E-Mail vom Einzug:
![E-Mail](https://user-images.githubusercontent.com/74767269/133274296-57a2bd52-6a56-4edc-b628-b46fa1280d2e.JPG)
![Aktuell](https://user-images.githubusercontent.com/74767269/133274316-ab52106e-647a-4333-9d27-19cb497dd5fa.JPG)
![vorheriger_Mieter](https://user-images.githubusercontent.com/74767269/133274327-7a986647-415a-4e42-b703-04dfa13564d5.JPG)

**Comment by TheOutburst** [comment]
Wir werden uns sämtliche Hotelbugs mit StateNET 2.0 annehmen #942
