### ISSUE TITLE
Gartentor entfernbar oder das es aufgeht? 

### ISSUE THREAD

**Issue by Annabelle-Smith** [mexyn/statev_v2_issues#1881]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Annabelle Smith

**Beobachtetes Verhalten**

Objekt Haus : West Mirror Drive 15 - Westmirror Drive 15

Das Gartentor geht nicht auf. Ist es möglich zu machen das es auf geht und zu ?
Oder könnte man das Tor selber entfernen beim Mapping? 
damit man da nicht über den Zaun klettern muss. 

**Erwartetes Verhalten**

Wäre schön wen das Tor auf und zu geht 
oder weggenommen wird beim Eingang um ohne zu klettern in den Garten zu gelangen. 

da Up Loud nicht geht auch hier das Bild so
https://prnt.sc/1skpd5u

**Comment by Dean-Gallagher** [comment]
Huhus, wie bei jedem objekt würde es nur optisch weg sein. Das Hinderniss würde also nur unsichtbar werden und man könne dennoch nicht durch gehen.

**Comment by powerswissi** [comment]
Dann könnte man nen Port vorne an der Türe oder dort machen wenn möglich.. Danke

**Comment by DrGrizzlY17** [comment]
Entfernen bringt leider nichts.
Teleport abgelehnt. Einfach simpel drüber klettern.
