### ISSUE TITLE
Goldschmiede - diverse Ketten fehlen

### ISSUE THREAD

**Issue by VictorCorticera** [mexyn/statev_v2_issues#1883]
Gustavo Luciano

20.09.2021 / 14 Uhr

Mehrere Ketten können in der Goldschmiede nicht hergestellt werden. 
Folgende wurden geprüft:
[M][Neck] Goldene Panzerkette 15mm
[M][Neck] Silberne Panzerkette 15mm
[M][Neck] Silberne Figarokette 10mm
[M][Neck] Goldene Kordelkette 10mm

Vermutung, die umbenannten Ketten.

In einer Goldschmiede in der Produktionssuche den Namen der Ketten eingeben.

<img width="817" alt="goldschmiede" src="https://user-images.githubusercontent.com/28830176/133997140-e2b82a19-0721-4219-8c97-d9bb0879a456.PNG">

**Comment by VictorCorticera** [comment]
Gibt es hierzu was neues?

**Comment by Enemyaa** [comment]
Sorry, für die späte Antwort. Die Produktion wird wieder mit dem nächsten Update möglich sein. Das letzte Update umfasste nur Änderungen durch das AltV Update, deswegen sind einige Sachen noch nicht live, die aber schon fixed sind.
