### ISSUE TITLE
Garage am Trailer oder generell in Stab  City (Lost Kreisel) & Abladepunkt für den Trailer erstellen bitte!

### ISSUE THREAD

**Issue by ManuelLadner** [mexyn/statev_v2_issues#1885]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Manuel Ladner**

**Täglich)**

**Kilometerweites laufen für eine Garage**

**Garage hinterm, neben dem Trailer oder in Stab City (siehe Bilder)**

**kein Parken möglich oder Kilometerlanges laufen um ein Fahrzeug auszuparken!**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehler
![20210921161603_1](https://user-images.githubusercontent.com/77968842/134189532-c329b424-b5d6-48db-9cd7-dab96a7333c4.jpg)
![20210921161614_1](https://user-images.githubusercontent.com/77968842/134189540-a1583992-2af3-4211-9eca-1ec7555a3dc8.jpg)
![20210921161628_1](https://user-images.githubusercontent.com/77968842/134189545-1429138b-78ba-4a26-a407-5de5ee6ad449.jpg)
![20210921161843_1](https://user-images.githubusercontent.com/77968842/134189548-a171b86b-ae51-4427-b0a0-4480cd2844bd.jpg)
![20210921162029_1](https://user-images.githubusercontent.com/77968842/134189552-65511d49-24a6-461c-82d8-6a627148dfc9.jpg)
s**

**Comment by CatherineGallagher** [comment]
wurde schon abgelehnt, da weiter unten eine Garage ist. 
https://github.com/mexyn/statev_v2_issues/issues/1691

**Comment by epichalt** [comment]
> Wurde schon abgelehnt, da weiter unten eine Garage ist.
> Die Anfrage ist auch erst 2 Monate alt.
> #1691

Schön 2km durch die Wüste rennen

**Comment by TheOutburst** [comment]
Wie oben geschrieben, diese Anfrage gab es bereits.

On a personal note: ich hab da auch nen Trailer, die Minute rüber Joggen kann man gut machen.
