### ISSUE TITLE
Frontlicht beim Motorad Vortex funktioniert nicht

### ISSUE THREAD

**Issue by Hochfels** [mexyn/statev_v2_issues#1886]
**Character Name**
Marcel Hochfels

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit dem Tuning

**Beobachtetes Verhalten**
Nachdem ich die Frontscheinwerfer ausgewechselt habe (NICHT das Licht selber), funktionieren die Frontscheinwerfer nicht mehr.

**Erwartetes Verhalten**
Das Licht sollte leuchten, damit ich Nachts etwas sehe und gesehen werde :)

**Schritte um den Fehler nachvollziehen zu können**
Bei der Vortex die Frontlichter auf das letzte Tuningteil stellen und schon leuchtet dieses nicht mehr.

Es sieht so aus, als wäre die Verkleidung ein Stück zu hoch und dahinter die Lichter, dass die da nicht korrekt durchscheinen können.

**Comment by Stiefel911** [comment]
Das letzte Tuning Teil (Front Maske) benutzt das Licht der Sekundär Farbe.... Dies ist Original von GTA... 😉

**Comment by TheOutburst** [comment]
Wie Stiefel schon schrieb, dieses Auto hat mit diesem Tuningteil kein leuchtendes Licht mehr.

![grafik](https://user-images.githubusercontent.com/70150675/134403541-2bd47e47-2b16-4684-b0b1-ce0dd0770cf7.png)
