### ISSUE TITLE
Verbesserungsvorschlag: Auto schieben automatisch beenden; geradeaus schieben verbessern; Bordsteine "absenken"

### ISSUE THREAD

**Issue by zarazandra** [mexyn/statev_v2_issues#189]
**Character Name**
Shiva_Connelly; betrifft alle

**Zeitpunkt (Datum / Uhrzeit)**
immer

**Beobachtetes Verhalten**
Autos zu schieben ist fantastisch, krankt aber im Moment an zwei Dingen: 
- um das Schieben zu beenden, muss man erst wieder über das X-Radialmenü gehen und es aktiv beenden. 
- geradeausschieben ist quasi nicht möglich. Sobald man einmal eingelenkt hat, kann man nicht mehr richtig geradeaus schieben und bewegt sich im Zickzack. 
- Man kann Autos nicht über einen Bordstein schieben.

**Erwartetes Verhalten**
- Einfacher wäre es mMn, das Schieben zu beenden, indem man einfach vom Fahrzeug wegtritt, also mit S. Ist vielleicht nur eine Gewohnheitssache, aber ich hab das immer vercheckt und viel zu weit geschoben, weil ich dann erst über das Radialmenü gehen musste. Fühlt sich ein wenig sperrig an.
- Wenn man mit W aktiv geradeaus schieben möchte, sollte das Fahrzeug auch entsprechend geradeaus geschoben werden. :) No hate. 
- Versucht man ein Fahrzeug in einer engeren Straße aus der Fahrbahn zu rollen, scheitert man an jedem Bordstein, selbst wenn man mit beiden Front- oder Hinterreifen parallel auf den Bordstein schieben möchte. Ist bisschen doof, denn mit genug Schub kann man ein Auto auch auf einen Bordstein schieben. Das Aus-dem-Weg-räumen hat somit sein Ziel verfehlt oder muss komplett aus der gesamten Gasse geschoben werden. 

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by zarazandra** [comment]
Hinweis: Alle meine Verbesserungsvorschläge gelten natürlich nicht für Day 1 von V2, sondern eher allgemein. No pressure. :)

**Comment by DonVitoDiangelo** [comment]
Bordsteine sind eben Bordsteine. viel Spaß beim hochschieben. :D vllt. frontal, wenn überhaupt. Aber das ist dann halt so.   Das mit der Lenkung ist aktuell nicht anders machbar.

**Comment by zarazandra** [comment]
Ja, frontal war bei mir mit "beiden Front- oder Hinterreifen parallel" gemeint. :D 
Habe das halt auch bei abgesehnkten Bordsteinen erlebt, was bisschen schade war (die kleine Einbahnstraße in Richtung Mission Row-PD, da gibts ne kleine Abzweigung mit abgesenktem Bordstein, da wollte ich das Auto reinschieben - ging nicht) 

Danke für die Antwort!
