### ISSUE TITLE
Schminkstuhl im Friseur Fawkes (Mirrorpark) defekt

### ISSUE THREAD

**Issue by EmmaSvensson** [mexyn/statev_v2_issues#1891]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Emma Svensson und Cleo Swan
**Auftrittszeitpunkt (Datum / Uhrzeit)**

25.9.21 gegen 22:00 Uhr und zuvor schon einmal mit Olivia Hammer
**Beobachtetes Verhalten**

In unserem Friseur (Mirrorpark) funktioniert der Schminkstuhl nicht; Cleo setzte sich, ich machte ihr das gewünschte Make-Up drauf und wollte ihr die Rechnung reichen, jedoch kam eine Fehlermeldung (siehe Anhang). Bei einem weitern versuch genau das selbe. Ein paar Tage zuvor war sie wohl schon bei Olivia Hammer, wo der selbe Fehler aufgetreten ist.
**Erwartetes Verhalten**

Alle Personen können sich ein neues Make-Up machen lassen
**Schritte um den Fehler nachvollziehen zu können**

1. hinsetzen und make_up aussuchen
2. Rechnung erstellen und zum Kunden geben
3. In unserem Fall kam die Fehlermeldung
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot_5](https://user-images.githubusercontent.com/74768516/134819383-a15d9c09-7161-4194-acee-650d79f92c15.png)
![Screenshot_6](https://user-images.githubusercontent.com/74768516/134819387-97159511-8022-4f8c-87c3-6c070745abce.png)

**Comment by DrGrizzlY17** [comment]
Tritt das nur bei Cleo_Swan auf oder sind andere Kunden davon ebenso betroffen?

**Comment by EmmaSvensson** [comment]
Haben es eben bei mir getestet und da kam die gleiche Fehlermeldung

**Comment by EmmaSvensson** [comment]
Es war alles vorhanden, die Fehlermeldung kam dennoch. Haben sogar extra noch aus der Fertigung Sachen nachgelegt
Mittlerweile ist der Fehler jedoch weg.
