### ISSUE TITLE
Lifeinvader: Bilder nach Löschung immernoch in der Timeline

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1894]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.09.21

**Beobachtetes Verhalten**
Bilder die man auf Social Postet und löscht, sind immernoch in der Timeline des Profil's zu sehen.

**Erwartetes Verhalten**
Timeline wird korrekt gecleared.

**Schritte um den Fehler nachvollziehen zu können**
1. Bild Posten
2. Löschen
3. is noch in der Timeline

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by JulianMa** [comment]
ist schon länger bekannt

**Comment by KingMarcel** [comment]
fixed für künftige und vergangene posts
