### ISSUE TITLE
Umgehen des Freezes beim Restaurant

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#1897]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Dan Lee

**Beobachtetes Verhalten**

Im Restaurant anfangen was zu essen. Während des Ladebalkens eine Waffe equippen und unequippen.
Frei sein.

**Erwartetes Verhalten**

Weiter gefreezed sein.

**Optional: Video / Bilder des Fehlers**

![image](https://user-images.githubusercontent.com/70150988/135717171-72877c87-67fe-46a8-8d04-aa3256180aa8.png)

**Comment by Hutstaender** [comment]
fixed
