### ISSUE TITLE
Lifeinvader Social Anmeldung klappt nicht

### ISSUE THREAD

**Issue by PrimroseBloom** [mexyn/statev_v2_issues#1898]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Primrose Bloom

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Nach dem Update am 1.10.2021

**Beobachtetes Verhalten**
Die Anmeldung auf Lifeinvader Social über das Tablet funktioniert nicht. Man kann nicht auf die Felder Klicken um seinen Namen und Passwort einzugeben.

**Erwartetes Verhalten**
Man kann auf die Felder gehen und seinen Benutzernamen und Passwort eingeben.

**Schritte um den Fehler nachvollziehen zu können**
Tablet öffen und auf Lifeinvader klicken.

**Comment by PrimroseBloom** [comment]
Zusatz: Man kann eine Anmeldedaten eingeben ABER! man kann sich nicht Einloggen!

**Comment by DrGrizzlY17** [comment]
Das gleiche gilt fürs StateCom

**Comment by DrGrizzlY17** [comment]
Und im Messenger im StateNet kann man nicht mehr in das Feld klicken um eine Nachricht einzugeben

**Comment by PrimroseBloom** [comment]
Man kann manche Mitarbeiter im Team nicht in eine andere Lohnklasse setzen. Sie werden immer wieder zurück gesetzt. Und man sieht im Team nicht mehr wer im Dienst ist.

**Comment by JulianMa** [comment]
alt:V CEF issue, in zusammenhang mit IFrames
