### ISSUE TITLE
Rucksack hat negative Kilogrammanzahl

### ISSUE THREAD

**Issue by ProgrammingFox** [mexyn/statev_v2_issues#19]
**Zeitpunkt (Datum / Uhrzeit)**

Wenn mehrere Items in den Rucksack gezogen werden und anschließend wieder aus dem Rucksack rausgezogen werden, steht oben als Belegung "-0.00kg" und der Balken, der die Belegung anzeigt, ist nicht vollständig verschwunden.

**Erwartetes Verhalten**

Es sollte "0.00kg" dastehen und der Balken sollte verschwunden sein.

**Schritte um den Fehler nachvollziehen zu können**

Einige Items in einen angelegten Rucksack ziehen und anschließend wieder komplett rausnehmen.

**Optional: Video / Bilder des Fehlers**

![grafik](https://user-images.githubusercontent.com/48456305/91206904-35683d80-e708-11ea-913f-0937f567c78f.png)

**Comment by DrGrizzlY17** [comment]
Sobald man das Inventar schließt und wieder öffnet, ist das -0 weg und wieder korrekt auf 0

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/975

**Comment by DonVitoDiangelo** [comment]
keine Relevanz
