### ISSUE TITLE
IC Tablet Scrollen nicht möglich

### ISSUE THREAD

**Issue by Asmier** [mexyn/statev_v2_issues#1900]
Asmier Umid

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Seid AltV Update

**Beobachtetes Verhalten**

Keine Möglichkeit mehr im Tablet IC zu scrollen.  Muss man per Balken gemacht werden.
Extern gibt es da keine Probleme.

**Erwartetes Verhalten**

Im Tablet scollen können.

**Comment by cadpri** [comment]
Kleines workaround:
Page up und page down funktioniert zum scrollen

**Comment by JasminHarper** [comment]
Hab davon mal nen Video gemacht

https://youtu.be/43zqnvfuRSE

**Comment by timderspieler** [comment]
Eine Beschreibung für meine Werbun kann ich ebenfalls nicht mehr hinzufügen :(

**Comment by EvilGateway** [comment]
Allgemein SChreiben geht halt zeitweilig nicht und dann doch wieder.

**Comment by TheOutburst** [comment]
#2116
