### ISSUE TITLE
house_MirrorPark_31 - Gartentor entfernen

### ISSUE THREAD

**Issue by theJanosch** [mexyn/statev_v2_issues#1902]
**Character Name**

Heinz_Heineken
**Auftrittszeitpunkt (Datum / Uhrzeit)**

immer
**Beobachtetes Verhalten**

Garten kann nur betreten werden, indem man über das weiße Gartentor rechts von der Garage springt
**Erwartetes Verhalten**

Wenn möglich, Entfernung des weißen Gartentors oder beweglich machen oder austauschen durch bewegliches
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![mirrorpark-31heinzheineken](https://user-images.githubusercontent.com/70151661/135756510-7ab43eb4-fe1a-48b1-8b2f-451eee70499c.png)
![mirrorpark-31heinzheineken2](https://user-images.githubusercontent.com/70151661/135756768-610d1be0-bdb6-4772-8fe7-9c21e0dddbd6.png)

**Comment by Dean-Gallagher** [comment]
Entfernen würde man nur Optisch das Tor entfernen. Die Hitboxbox würde bleiben sprich es wäre ein unsichtbares objekt.

**Comment by DrGrizzlY17** [comment]
Die Kollision würde bestehen bleiben und würde den Durchgang nicht ermöglichen. Daher abgelehnt
