### ISSUE TITLE
Objekt Entfernung

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#1906]
Santito Quintero 

Villa Rockford - Steele Way 5
Haushash	house_RockfordHills_2

**Auftrittszeitpunkt (Datum / Uhrzeit)**
dauerhaft

**Beobachtetes Verhalten**
Diese Sitzecke aus Stühlen ist leider nur bedingt nutzbar. Falls man dort Platz nimmt, kann man nicht wieder aufstehen. Man buggt dann etwas in der Luft und kann sich nicht von der Stelle bewegen. Nur ein Restart des Games behebt den Fehler. 
Ich bitte darum die Stühle, Tische und die Schirme zu entfernen, da wir dann dort selbst eine Sitzecke platzieren möchten. 
Der Grill könnte in diesem Zuge auch entfernt werden falls es geht, da er nicht nutzbar ist. 
defacto eine ähnliche Problematik wie beim Opa Knutsen in diesem Report 
https://github.com/mexyn/statev_v2_issues/issues/1716

**Optional: Video / Bilder des Fehlers**
<!--- Falls du ein Video oder Bild vom Fehler gemacht hast, dann kannst du diesen hier einfügen. Dies geht ganz einfach per Drag & Drop --
![9b7c54cef91d978f4dcc1791b976a81f](https://user-images.githubusercontent.com/16436981/136302586-1c6c1dc9-ec52-43fc-b60b-8d309d0be5df.jpg)
>

**Comment by epichalt** [comment]
![9b7c54cef91d978f4dcc1791b976a81f](https://user-images.githubusercontent.com/16436981/136302746-669a4a2d-6e54-4ecc-87dc-3b891740bc78.jpg)

**Comment by CaleighRhodes** [comment]
Der Grill IST nutzbar, aber nur mit dem Hydrodynamischen Pfannenwender... ;) Und nur für Männer. :(

**Comment by CaleighRhodes** [comment]
Wir konnten den spielseitig gesetzten Grill im Interior Luxury House Modern Design Art mit einem besagten Pfannenwender nutzen.
