### ISSUE TITLE
Anker bei Booten bleibt nicht dauerhaft

### ISSUE THREAD

**Issue by VictorCorticera** [mexyn/statev_v2_issues#1911]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Gustavo Luciano

Man aktiviert die Ankerfunktion bei einem Boot, bewegt sich dann etwas weiter vom Boot weg und kommt zu einem späteren Zeitpunkt wieder zurück, ist der Anker nicht mehr aktiv und man kann einfach losfahren.

Anker sollte wie die Handbremse dauerhaft bleiben.

**Comment by VictorCorticera** [comment]
@JulianMa weiß wohl schon woran das liegt

**Comment by Hutstaender** [comment]
dublicate von #1151
