### ISSUE TITLE
Stempeluhrproblem nach Firmenüberschreibung

### ISSUE THREAD

**Issue by LeonBam** [mexyn/statev_v2_issues#1917]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Leon_Bam

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit der Firmenüberschreibung

**Beobachtetes Verhalten**
Ich war in zwei Firmen an der Stempeluhr eingestempelt. Jetzt wurden die Firmen auf mich überschrieben und ich kann mich nicht mehr ausstempeln. Bekomme trotz eingestelten gehalt von $0 eine stündliche SMS der Gehaltsabrechnung.

**Erwartetes Verhalten**
Sich auch als Firmen-Besitzer ausstempeln zu könne.n 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by KingMarcel** [comment]
Problem für den Spieler gelöst. (Überschrieben und Rücküberschrieben)
