### ISSUE TITLE
Funkprobleme

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1920]
**Auftrittszeitpunkt (Datum / Uhrzeit)**
Schon länger 

**Beobachtetes Verhalten**
Es kommt manchmal vor, dass man in einem Funkkreis eine Person, die alle anderen hören, nicht hört.  Dies kann der, den man nicht hört, wenn es auffällt, oft /(vlt. auch immer) durch Deaktivieren und Aktivieren der Sprechfunktion beheben 

(siehe bsp.  https://youtu.be/_TJE1r3L0E4?t=202 ) hier hat dann Shelby seine Sprechfunktion nm. deaktiviert u. aktiviert, sodass ich ihn dann auch hören konnte.) 

Aber auch gestern war so ein Fall bei wem anders, den ich über Stream gesehen habe.

Zudem besteht auch weiterhin #726 /#1482 
 

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Stiefel911** [comment]
kann ich so bestätigen, deaktivieren aktivieren hilft nur...denke liegt am wechseln  der Frequenzen
