### ISSUE TITLE
Roadhouse Diner PB Offenes Interior

### ISSUE THREAD

**Issue by Eskadiel** [mexyn/statev_v2_issues#1921]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Eskadiel Nightmare**

**Seit StateV V2 Release**

** Schlecht platzierte Bestuhlung im offenen Interior, Schwebende Charaktere nach dem Hinsetzen, Akustikprobleme durch Stuhl Abstände (Flüstern oft zu leise-normal oft zu laut), Nicht benutzbare Stühle, da Abstände zu gering (feststecken der Charaktere und verursachen von Klitsches mit dem Interior), Charaktere verschwinden im Sofas, Sessel nicht mit Y nutzbar. Nicht Abschließbare Türen der offenen Räumlichkeiten.**

**Stühle näher an den Tischen, Charakter schweben nicht wenn mit Ihnen interagiert wird, Abstände der Tische mit Bestuhlung besser Aufteilen. Sessel benutzbar per Y, Sofas als 3 Sitzplatz ohne versinken von Charakteren"austausch zu herkömmlichen schwarzen Sofa gern gesehen". Nicht genutzter Raum mit Tisch und Stühlen ausstatten. Abschließbare Türen "3 stk" wie bei Fraktionen um den Zugang Beschränkbar zu machen **

** Roadhouse Diner PB besuchen und das offene Interior nutzen als wenn man im richtigen RL Restaurant bedient wird. "MI und SA 19-22Uhr" IC Möglichkeit. Direktes setzen an die Fenster und mit Personen,Tablett oder ähnlichem interagieren **

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**![Ungenutzt](https://user-images.githubusercontent.com/92888219/138166838-21066eae-6aec-4807-9187-522a6deddd81.jpg)
![Abstand](https://user-images.githubusercontent.com/92888219/138166939-65b22550-7894-46ee-ae0b-a67384f2501b.jpg)
![Besetzbarkeit](https://user-images.githubusercontent.com/92888219/138166951-c0ca154b-ce5d-4c0d-9669-806ad5cb60fc.jpg)
![Sprachreichweite](https://user-images.githubusercontent.com/92888219/138166974-38159e1d-32ed-47a9-aad9-765b6f10ad1f.jpg) 
![stühle 2](https://user-images.githubusercontent.com/92888219/138466551-ec35dbe4-83b4-4952-8f59-e274ccdd5128.jpg)
![Sofa 1](https://user-images.githubusercontent.com/92888219/138466655-bc658e22-2d23-47fb-aa84-23728b7cfc99.jpg)**

**Comment by Eskadiel** [comment]
![flying](https://user-images.githubusercontent.com/92888219/140183543-8e523617-f170-4d92-ac17-29228c4289f7.jpg)

**Comment by Eskadiel** [comment]
![bug](https://user-images.githubusercontent.com/92888219/140183879-22498bb0-5d02-424f-9ab6-59c839821f78.jpg)

**Comment by DrGrizzlY17** [comment]
Das mit dem schweben tritt irgendwie mal immer random auf. Wenn wir die Stühle näher an die Tische schieben provozieren wir das schweben stärker. Ich gucke mal was so geht

**Comment by Eskadiel** [comment]
Gibt es schon ein Feedback, Ob und wann es veränderungen am Interior des Aussen Diners geben wird.
Seit der letzten Rückmeldung ist ein wenig zeit vergangen weswegen ich jetzt mal nachfrage ob es dazu schon was neues gibt. MFG Eska
Nachtrag, das schweben ist das kleinzte Problem, das schwere bis überhaupt nicht mögliche besetzen der stühle schon eher, weswegen ich ja um die verschiebung, NICHT Löschen, der Tischgruppen gebeten hatte.

**Comment by DrGrizzlY17** [comment]
Wir sind noch dran. In der Größe ist der Raum halt beschränkt. Am Ende soll es halt noch gut aussehen. Deswegen dauert das alles ein wenig. Hat halt tatsächlich eher ne low prio. Aber ist nicht vergessen :)

**Comment by Eskadiel** [comment]
Stand der Dinge ? Würden uns über Rückmeldung freuen ob und wann es in Betracht kommen kann ?

**Comment by TheOutburst** [comment]
das fliegen ist leider ein anderes Thema, alles weitere ist zum nächsten Update verändert
