### ISSUE TITLE
Kommastelle beim Fahrzeugzurückgeben

### ISSUE THREAD

**Issue by Krapfal** [mexyn/statev_v2_issues#193]
**Lagu**

**2.9.2020)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Kommastelle](https://user-images.githubusercontent.com/70897064/92386804-cd0c5980-f114-11ea-8d16-639fd2b31f07.png)

**Comment by tastydev** [comment]
Kein V2 Screenshot :D
