### ISSUE TITLE
Kleidung ausziehbar bei vollem Inventar / Kleidung nicht tauschbar bei vollem Inventar

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#195]
Dan Lee

**Zeitpunkt (Datum / Uhrzeit)**
11.09.2020 12.55

**Beobachtetes Verhalten**
Wenn ich ein Kleidungsstück ausziehen will, nicht tauschen, kann ich das tun auch wenn mein Inventar schon voll ist.
Anders wenn ich es tauschen will. Brille gegen Brille tauschen, sagt er mir das für meine alte Kleidung kein Platz ist. (als Vergleich)

**Erwartetes Verhalten**
Ich sollte kein Kleidungsstück ins Inventar zurück legen können, wenn es voll ist.
Bzw. ich sollte Kleidungsstücke tauschen können wenn es voll wäre

**Schritte um den Fehler nachvollziehen zu können**
1. Brille anlegen
2. Inventar füllen
3. Brille ausziehen

für Fall 2
1. Brille anlegen und zweite im Inventar haben
2. Inventar füllen
3. Auf zweite Brille rechtsklicken um auszutauschen

**Comment by r3sist3nt** [comment]
solved nach restart
