### ISSUE TITLE
Nos verschwindet nach Ein-/ ausparken von Fahrzeugen

### ISSUE THREAD

**Issue by Michi993** [mexyn/statev_v2_issues#1951]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Luke Hammer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.10.2021 - ca. 22.30 uhr

**Beobachtetes Verhalten**
Nach ein und ausparken eknes Fahrzeuges, welches mit Nos ausgestattet war, ist dieses (Nos) nicht mehr vorhanden.

**Erwartetes Verhalten**
Nos bleibt eingebaut/ verschwindet nicht nach ein- und ausparken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Zum aktuellen Zeitpunkt werden wir das nicht angehen, da wir das System mit Absicht so generfed lassen wollen.
