### ISSUE TITLE
Antrag auf Garage

### ISSUE THREAD

**Issue by Esry84** [mexyn/statev_v2_issues#1955]
Hallo,
ich habe kürzlich ein Haus gekauft bei PLZ 810. (Hinter der Tankstelle.)
Die Lage und das ambiente des Hauses ist super, allerdings hat es keine Garage.
Aber neben dem Haus ist eine große Fläche als "Stellfläche" vorhanden.
Lässt sich darauf vielleicht sowas wie eine kleine Garage ´/Abstellplatz basteln?
Wäre echt schade wenn es nicht geht, muss auch nur 1-2 Autos "reinpassen", würde halt gern dort wohnen nur die nächste Garage ist echt wahnsinnig weit weg.

Haushash: 
SandyShores59

Viele Grüße

Esry Grafenhorst

**Comment by DonVitoDiangelo** [comment]
der Antrag ist hiermit abgelehnt.
