### ISSUE TITLE
Einparkthematik

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#1959]
Siehe https://github.com/mexyn/statev_v2_issues/issues/1935#issuecomment-951811093

Also es ist absolut verständlich, dass man keine großen Fahrzeuge in einer Hausgarage einparken soll. 

Allerdings gibt es hier trotzdem 2 Probleme. Die Autos werden quer ausgeparkt und buggen dann zwischen den Mauern links und rechts. Eben bin ich dann mit einem CaraCara unter die Map gefallen. Nach einigen Sekunden Absturz bin ich mit kaputtem Fahrzeug auf der Straße gelandet. 

Der Pounder und auch andere großen Fahrzeuge werden automatisch eingeparkt. (Betrifft auch vermietete und finanzierte Fahrzeuge - auf die man keinen Einfluss hat, wo diese abgestellt werden.)
Ich kann nicht mal einen Abschlepper holen, da das Ding kopfüber im Garten ausgeparkt wird.
Es bleibt nur der Gang über den Support. Dort konnte mir eben zügig geholfen werden und die Fahrzeuge wurden umgeparkt.
Dort wurde mir gesagt ich soll nochmal einen Bugtracker aufmachen damit der Auspark Punkt geändert wird. Der Einparkpunkt kann ja unter dem Dach bleiben. 

![de84ac12b3749dc165a4f18af8883107](https://user-images.githubusercontent.com/16436981/139084559-e35fc4fd-bbfd-444f-bda3-f72b46cd680c.jpg)

**Comment by DonVitoDiangelo** [comment]
LKW, Anhänger usw. werden zukünftig nicht mehr in Hausgaragen eingeparkt.
