### ISSUE TITLE
Auto nicht in der angezeigten Garage zu finden

### ISSUE THREAD

**Issue by Heavenflower** [mexyn/statev_v2_issues#1960]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Zula Summers

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.10 23:15

**Beobachtetes Verhalten**
Ich hatte meinen Jugular am ADAC stehen lassen, nach dem Serverrestart um 22:45 wurde er laut Tablet in der Vinewood Garage eingeparkt. Dort ist laut Garagenwärter aber kein Auto zum ausparken vorhanden. Genau das selbe Problem hatte ich vor ein paar Tagen schon einmal. Beide male musste es dann in eine andere Garage geportet werden.

**Erwartetes Verhalten**
Auto sollte an der nächstmöglichen Garage eingeparkt werden. Oder zumindest an der angezeigten Garage zu finden sein.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Ist dir das Problem erneut aufgefallen?

**Comment by Heavenflower** [comment]
Nein. War zu dem Zeitpunkt etwa nur wo auch die Garage vom ADAC ständig als blockiert gemeldet wurde.

**Comment by TeubyDE** [comment]
Ich mach das hier mal zu, sollte es noch einmal vorkommen gerne bescheid geben.
