### ISSUE TITLE
Schlüsselbund Fahrzeuge im Tablet

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#1967]
Hallo, 

ist es gewollt oder ein Bug, dass Fahrzeuge - welche einem nicht gehören, man aber einen Schlüssel bekommen hat, nicht mehr im Tablet zu sehen sind? 

Man sieht nur noch seine eigenen Fahrzeuge

**Comment by DonVitoDiangelo** [comment]
Derzeit sehen wir hier keinen Handlungsbedarf. Ihr könnt die Fahrzeuge wie gewohnt orten.
Daher werden wir die Übersicht im Tablet nicht erweitern.
