### ISSUE TITLE
Terry redet nicht mehr 

### ISSUE THREAD

**Issue by simonrolex** [mexyn/statev_v2_issues#1968]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Simon Dallas **

**28.10.21**

**Der Crime npc Terry lässt sich nicht mehr mit e anhandeln**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by JohnRappStateV** [comment]
Ist immer noch aktuell

**Comment by Koree7** [comment]
Ich glaube das Problem tritt auf nachdem man einen ATM ausgeraubt hat. Konnte nach dem Serverrestart um 15 Uhr mit Terry reden und nach einem Raub nicht mehr.
