### ISSUE TITLE
Roter Kreis beim X drücken geht nicht weg

### ISSUE THREAD

**Issue by CubeXLIVE** [mexyn/statev_v2_issues#1969]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Patrick_Nowak

**Auftrittszeitpunkt (Datum / Uhrzeit)**
28.10 - 20:30

**Beobachtetes Verhalten**
Beim hinsetzen zum Beispiel (X-Menü öffnen für Animationen) geht der Kreis unter Leuten nicht weg

**Erwartetes Verhalten**
Kreis sollte verschwinden

**Schritte um den Fehler nachvollziehen zu können**
X drücken, wenn man neben jemandem steht, Animation benutzen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/3b320a7068eccfe90635e7dfabfc193f

**Comment by JulianMa** [comment]
Sollte seit heute morgen fixed sein

**Comment by CubeXLIVE** [comment]
Scheint gefixt zu sein
