### ISSUE TITLE
Gebäude Türen auf-/abschließen ist Fraktionsunabhängig

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#197]
**Character Name**
Dan_Lee

**Zeitpunkt (Datum / Uhrzeit)**
02.10.2020

**Beobachtetes Verhalten**
Wenn ich im Team "lspd" bin kann ich Türen des LSMD, HK, Justiz etc. aufschließen.

**Erwartetes Verhalten**
Die Definition in den JSON welches Team, welche Türen auf-/abschließen kann wird nicht beachtet.
Mitglieder der Fraktion "lspd", sollte nur Türen bearbeiten können, in denen sie definiert sind.

**Schritte um den Fehler nachvollziehen zu können**
1. Sich in das Team lsmc setzen
2. Zum Justizgebäude gehen
3. Alle Türen aufschließen
(Für das Justizgebäude sind die Medics nicht definiert)

**Optional: Video / Bilder des Fehlers**
https://i.gyazo.com/a53d9a3a8e71bffa28e194b8acabf63c.jpg

**Comment by tastydev** [comment]
Feature funktioniert wie gewollt. Wer bestimmte Adminrechte hat kann alle Türen öffnen.
