### ISSUE TITLE
Erfahrungsfortschritt (Roter Balken unter Talente, wenn man K drückt)

### ISSUE THREAD

**Issue by TomStark93** [mexyn/statev_v2_issues#1970]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
 Tom Stark

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 seit Umstellung der Bücher

**Beobachtetes Verhalten**
 Erfahrung wird nicht mehr.

**Erwartetes Verhalten**
 Erfahrung wird mit der Zeit mehr.

**Schritte um den Fehler nachvollziehen zu können**
 garnicht möglich

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by tastydev** [comment]
Der unterste Balken (Der große lange) hat nichts mit dem farmen zu tun. Dieser ist für die Major-Points zuständig und ist nur durch Spielzeit beeinflussbar. Die kleinen Balken innerhalb der gelernten Talente sind durch Farming beeinflussbar.

**Comment by JulianMa** [comment]
wie @tastydev schon sagte, der große Balken unten ist der Spielzeit-Abhängige Erfahrungspunkte Balken. Die benötigte Spielzeit steigt hier stark pro Level an. 
Es ist also kein Fehler.
