### ISSUE TITLE
ATM Raub Dispatches Bug

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#1971]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
29.10 17:00

**Beobachtetes Verhalten**
Man kann eingehende ATM Raub weder annehmen / an die die Einheiten weiterleiten, noch löschen. Diese werden als Dispatch in der Warteschlange behandelt, sodass man wenn man anruft 2 aktive Anrufe hat. 

--

Zusatz: Mir ist aufgefallen, dass im Leistellensystem in der Notrufliste zudem immernoch "An Gegenfraktion übergeben" steht. Da man den Begriff raus haben wollte könnte man dafür entweder einen anderen Begriff nutzen, oder einfach beim LSPD "An LSMD übergeben" und umgekehrt schreiben

**Erwartetes Verhalten**
Man sollte den Dispatch annehmen und weiterleiten können. Zudem sollte auch das löschen möglich sein.

**Optional: Video / Bilder des Fehlers**

Falls benötigt könnte ich nachreichen.

**Comment by its4l3x** [comment]
@TeubyDE @TheOutburst 

Bitte nochmal testen

**Comment by JannikDatsch** [comment]
Weiterleiten ist mittlerweile möglich löschen aber immer noch nicht, zudem wird das auch weiterhin als aktiver Anruf in der Warteschleife angezeigt
