### ISSUE TITLE
Log Achse lässt sich nicht ankuppeln

### ISSUE THREAD

**Issue by PrimroseBloom** [mexyn/statev_v2_issues#1973]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Primrose_Bloom

**Auftrittszeitpunkt (Datum / Uhrzeit)**
29.10.21 19:50

**Beobachtetes Verhalten**
Log Achse lässt sich nicht vom Phantom ankuppeln. Die Achse liegt zu tief, da die Beine vorne in den Boden verschwinden. Man kann auch nicht schauen ob was in der Achse liegt.

**Erwartetes Verhalten**
Log Achse steht höher und lässt sich ankuppeln

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![grafik](https://user-images.githubusercontent.com/70226823/139480842-abdd5a71-ed05-4f8e-8f36-4f87824b8ed7.png)

**Comment by CaleighRhodes** [comment]
Ehm... das war schon immer so?! Die Log-Achse kann man eigentlich NUR problemlos mit dem Hauler ankuppeln. Beim Phantom braucht es Gewalt.

**Comment by PrimroseBloom** [comment]
> 
> 
> Ehm... das war schon immer so?! Die Log-Achse kann man eigentlich NUR problemlos mit dem Hauler ankuppeln. Beim Phantom braucht es Gewalt.

Selbst mit Gewalt geht es nicht. Sonst ging es immer. Man kann auch nicht mehr in den " Kofferraum" schauen.

**Comment by CaleighRhodes** [comment]
Das ist natürlich blöd. Mal sehen, ob da was dran zu machen ist.

**Comment by DonVitoDiangelo** [comment]
Nein leider können wir das nichts machen. Da heißt es, es ist wie es ist.
