### ISSUE TITLE
keine Be-/Entladepunkt

### ISSUE THREAD

**Issue by Stiefel911** [mexyn/statev_v2_issues#1974]
Es gibt keine Be-/Entladepunkt
dieser ist einfach nicht da, nicht nur nicht sichtbar

[#1845](https://github.com/mexyn/statev_v2_issues/issues/1845)

bitte um Behebung

Danke

**Comment by DrGrizzlY17** [comment]
Hö. Ich schaus mir an

**Comment by DonVitoDiangelo** [comment]
next update fixed
