### ISSUE TITLE
ADAC Garage defekt

### ISSUE THREAD

**Issue by patrickschfr** [mexyn/statev_v2_issues#1975]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Patrick Shepard**

**Auftrittszeitpunkt (29.10.2021/23:00)**

**Die Fahrzeuge lassen sich aus der Garage nicht mehr ausparken. Bei dem Versuch Fahrzeuge auszuparken steht, dass die Ausfahrt blockiert sei. Jedoch ist die Ausfahrt frei.**

**Fahrzeuge sollten im Normalfall einfach ausgeparkt werden können, wenn die Ausfahrt frei ist.**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Dean-Gallagher** [comment]
Stehen da placebalbes oder Spieler? Weil diese zählen auch als Objekte die Blockieren.

**Comment by SatyriaDine** [comment]
So wie ich das sehe steht da gar nichts. Einzige was mir an der Garage schon immer aufgefallen ist, dass gerade größere Fahrzeuge wie Pounder ect beim ausparken jedes Mal fast umkippen. Weiß nicht ob das irgendwie weiterhilft

**Comment by Dean-Gallagher** [comment]
Es muss ein Physisches Objekt in der nähe sein, Spieler oder ein Placeable. Der Radius für den Einparker ist recht groß. Etwa pounder länge vom park punkt im kreis um ihn herrum. Sprich es können auch Objekte oder Spieler sein welche an der Eingangstür stehen und sogar etwas weiter darum.

**Comment by l4m4rr224** [comment]
Nein da steht absolut gar nichts im Weg aber die ausfahrt ist Blockiert.
https://pic.statev.de/image/CLlAY
https://pic.statev.de/image/CLy3w

**Comment by SatyriaDine** [comment]
Bin das ganze Ding grade mal abgegangen. Da ist wirklich nix. :/

![20211030204800_1](https://user-images.githubusercontent.com/84275938/139555161-180c2c5b-a363-417e-b631-f9e573744fea.jpg)
![20211030204837_1](https://user-images.githubusercontent.com/84275938/139555163-74ba96bc-abc3-4e2f-b838-6a27ccc4a682.jpg)

**Comment by hexlpd** [comment]
der nutzbare Mülleimer Links neber dem Häuschen wo der auspark Herr steht könnte es nicht zufällig sein, was das Problem verursacht?

**Comment by hexlpd** [comment]
Falls das Problem noch nicht gelöst wurde, ich habe grade mmal den von mir erwähnten mülleimer leer gemacht. Ausparken hat geklappt!

**Comment by hexlpd** [comment]
am Mülleimer liegt es leider doch nicht, dies habe ich grade ausgetestet

**Comment by Hutstaender** [comment]
Ist die Garage immer noch blockiert? Eben getestet ging wunderbar

**Comment by hexlpd** [comment]
Ja hab ja vor gute halbe Std erwähnt das das Ausparken grade klappt, daher war auch die vermutung bei mir, das es an der Mülltonne lag, weil die diese vorm ausparken geleert hatte

**Comment by Hutstaender** [comment]
ich mach ihn erst mal zu, wenn noch was ist neu aufmachen bitte.
