### ISSUE TITLE
Anfrage auf Garage und Erhöhung der Klasse

### ISSUE THREAD

**Issue by CapTaaiinZ** [mexyn/statev_v2_issues#1976]
**Character Name**
Hasan Bang

**Auftrittszeitpunkt (Datum / Uhrzeit)**
31.10.2021

Grüsse,

ich habe Gestern ein Haus in Davis gekauft und wollte wegen Garagenpunkt anfragen. Es hat einen Carport und genügend Platz für eine Garage. 

Haushash: house_DavisMidLS_10
Bild: https://pic.statev.de/image/haus.CLeY7

Ausserdem wollte ich mal nachfragen ob eine Erhöhung auf Klasse 2 möglich wäre.

MfG.
Hasan

**Comment by DrGrizzlY17** [comment]
Garage kein Problem,
Klasse bleibt die gleiche

**Comment by DonVitoDiangelo** [comment]
added next update

**Comment by CapTaaiinZ** [comment]
Grüsse, kommt die Garage mit dem nächsten Upate ? 15 Uhr war ein Update und es ist kein Garagenpunkt da. 
LG
