### ISSUE TITLE
Telefonat wird beendet bei Nutzung der Suche

### ISSUE THREAD

**Issue by flogut4e** [mexyn/statev_v2_issues#1977]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Lars_Stromberg**

**31.10.2021 ca 11:00**

**Wenn man während eines Telefonats die Suchfunktion im Lager benutzt wird das Gespräch beendet (sofern ein N im Wort ist)**

**Telefonat sollte nicht beendet werden**

**Telefonieren, in der Lager Suche ein Wort mit N eintippen**

**Comment by CaleighRhodes** [comment]
Gilt auch für B.

**Comment by its4l3x** [comment]
fixed next update
