### ISSUE TITLE
Telefonsound Bug

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#1978]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
30.10.

**Beobachtetes Verhalten**
Es tutet nur 1x dann ist stille

**Erwartetes Verhalten**
Das, das Tuten solange kommt, bis die Person dran geht.

**Schritte um den Fehler nachvollziehen zu können**
Telefonieren

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=YEcXVk9h53M

**Comment by DrGrizzlY17** [comment]
Das sollte eigentlich gefixt sein. Bei mir hat es heute normal funktioniert

**Comment by DrGrizzlY17** [comment]
Einfach nochmal heute probieren
