### ISSUE TITLE
Mietfahrzeug kann nicht zurückgegeben werden

### ISSUE THREAD

**Issue by UNST4BL3** [mexyn/statev_v2_issues#1979]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Atze_Barth

31.10.2021 zwischen 11:00 Uhr und 12:00 Uhr

MTL Öltanker wird trotz Vollem Tank, 70 km gefahren und Frischer Reparatur nicht zurückgenommen mit dem Fehler
"Dieses Fahrzeug kann nicht zurückgegeben werden." Ein Kollege hat es mit einem gemieteten Surfer Probiert, hier besteht das gleiche Problem.

Fahrzeug wird zurückgenommen

Wie beschrieben bei der Rückgabe des MTL Öl Mietfahrzeugs

**Comment by DrGrizzlY17** [comment]
An welchem Fahrzeugverleih wurde das probiert?

**Comment by UNST4BL3** [comment]
Fahrzeugverleih am LS Airport

**Comment by DonVitoDiangelo** [comment]
Kofferraum leer, aufgetankt und ganz muss er sein.

**Comment by UNST4BL3** [comment]
Alle drei Sachen treffen zu und es geht trotzdem nicht 

> Kofferraum leer, aufgetankt und ganz muss er sein.
