### ISSUE TITLE
Tankstelle - Fahrzeug bereits voll

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#198]
**Character Name**
Marvin_Elpe

**Zeitpunkt (Datum / Uhrzeit)**
02.10.2020 18:15

**Beobachtetes Verhalten**
Habe mein Auto mit 5L betankt, alles super gewesen. Danach wollte ich weiter volltanken, seitdem kommt eine Meldung das ich kein Geld habe oder das Fahrzeug bereits voll ist, was beides nicht der Fall ist

**Erwartetes Verhalten**
Tanken funktioniert

**Schritte um den Fehler nachvollziehen zu können**
Auto Tanken, Tanken beenden. Erneut Tanken versuchen

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/i/bos0n.jpg

**Comment by M4rvinLP** [comment]
Auch nachdem ich eingeparkt habe besteht das Problem.

**Comment by r3sist3nt** [comment]
Wie voll war dein Tank?
Es ist nur möglich ganze Liter zu tanken. Wenn dein Tank z.B. auf 54.5/55 steht, dann kannst du den liter nicht mehr tanken.

**Comment by M4rvinLP** [comment]
War der Geldtransporter. Passen 400L rein, 122 waren drin.

**Comment by r3sist3nt** [comment]
Gehörte der einer Fraktion/Firma an? Oder war das ein eigener?

**Comment by M4rvinLP** [comment]
War mein eigener

**Comment by r3sist3nt** [comment]
Konnte es nachstellen
