### ISSUE TITLE
Ausparkpunkt 

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#1980]
Santito Quintero
Haushash
house_MirrorPark_34 - West Mirror Drive 35

siehe https://github.com/mexyn/statev_v2_issues/issues/1959#event-5543496037 
und https://github.com/mexyn/statev_v2_issues/issues/1935#issuecomment-951811093
Der Ausparkpunkt müsste bitte trotzdem versetzt werden, da die Fahrzeuge oft auch mal so ausgeparkt werden und es schwierig ist aus zu parken :D 

![67ead362f067691964d7771ad5c01222](https://user-images.githubusercontent.com/16436981/139590681-6943816a-5dc8-4eba-8e11-b5d7c144ca0b.jpg)

**Comment by DonVitoDiangelo** [comment]
fixed enxt update
