### ISSUE TITLE
Normaler Whisky lässt sich im Bahama Mamas nicht mehr entpacken

### ISSUE THREAD

**Issue by CrimeMouse** [mexyn/statev_v2_issues#1981]
Pablo Dosmas

31.10.2021 | 17:50

Verpackter Whisky lässt sich nicht auspacken, Item ist nicht mehr im Produktions Compute
![20211031175305_1](https://user-images.githubusercontent.com/74876113/139594016-88b49338-6a09-433a-bf0c-9f06d3f1b4cd.jpg)
r

**Comment by DonVitoDiangelo** [comment]
fixed next update
