### ISSUE TITLE
Trailer BG

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#1983]
siehe: https://github.com/mexyn/statev_v2_issues/issues/1644

der Trailer BG ist wohl wieder in die Import Datenbank gerutscht :D 
Der war ja nicht wirklich nutzbar - oder wurde dieser gefixed?
![acc31dbd088f854499a022da6747c76a](https://user-images.githubusercontent.com/16436981/139601107-73908dd1-d1c4-40be-ba4e-a9a18004c00d.png)

**Comment by DonVitoDiangelo** [comment]
removed next update
