### ISSUE TITLE
Currypulver im Marktplatz nicht hinterlegt

### ISSUE THREAD

**Issue by RomanSpielberg** [mexyn/statev_v2_issues#1984]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Roman_Spielberg

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.11.2021

**Beobachtetes Verhalten**
Item Currypulver (nicht der Sack) kann im Marktplatz nicht gesucht und zugefügt werden

**Erwartetes Verhalten**
Neues Item ergänzen

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Das ist so korrekt. Hier kann es nur als Paket verarbeitet verkauft werden.
