### ISSUE TITLE
Fahrzeuge im Autohaus werden weiterhin eingeparkt

### ISSUE THREAD

**Issue by Stonny1** [mexyn/statev_v2_issues#1985]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Donny Stalves**

**Auftrittszeitpunkt ( 01.11.2021/ 15:15 Uhr)**

**Beobachtetes Verhalten**
Fahrzeuge werden teilweise nach Serverneustart eingeparkt.

**Erwartetes Verhalten**
Vermutlich muss hier eine Einstellung weiter nach oben geschraubt werden.

**Optional: Video / Bilder des Fehlers**
<!--- Falls du ein Video oder Bild vom Fehler gemacht hast, dann kannst du diesen hier einfügen. Dies geht ganz einfach per Drag & Drop --
![Autos weg](https://user-images.githubusercontent.com/89075729/139685950-37fea632-9a7c-4969-be95-943f4c0cf846.png)
>

**Comment by Stonny1** [comment]
![Autos weg](https://user-images.githubusercontent.com/89075729/139686416-62a7ebf0-bc7d-46f2-8300-8a133ce51fdf.png)

**Comment by epichalt** [comment]
Also mir ist die letzten Tage aufgefallen, dass zu jedem Neustart weiterhin so 25+ Fahrzeuge wieder automatisch eingeparkt werden. 

Heute Morgen zum Neustart waren es 31 Fahrzeuge.
Wir sind da allgemein die Regeln? Ist es eine bestimmte Anzahl? Spielt der Zeitfaktor eine Rolle, wann das Fahrzeug zuletzt bewegt wurde? 

![463b2dcd29679001e60da90409ecd20c](https://user-images.githubusercontent.com/16436981/139831433-f48a3af4-6083-48a3-b906-c6f233ae0b3f.png)

**Comment by Dean-Gallagher** [comment]
kann ich so bestätigen, ist in werkstätten auch noch der fall

**Comment by epichalt** [comment]
Um das mal zu updaten, 
zum Restart gestern Mittag und auch heute Morgen wurden keine Fahrzeuge eingeparkt.

**Comment by Hutstaender** [comment]
Ich mach das dann mal zu. Sollte noch was sein bitte nochmal melden.
