### ISSUE TITLE
Resturants verbugt

### ISSUE THREAD

**Issue by StateV2Marie** [mexyn/statev_v2_issues#1986]
Hallo haben das Problem aktuell wenn du ers nur getrunken oder beides hast durftes du nich mehr essen dir wird dan ne fehler meldung gezeigt das du bereits isst was aber nich der fall ist z.b hat ne Freundin Getrunken durfte aber danach nich essen mehr ers als se ein relog gemacht hat durfte sie wieder essen was doch nich richtig ist oder? bild is da>>  https://pic.statev.de/image/isstbereits.CwPsX

mfg Marie Pech

**Comment by tristan1297** [comment]
Hey, du hast oben eine Leiste mit einer Prozent anzeige die beim Essen/Trinken durchläuft. Wenn du Essen und trinken willst musst du beides auswählen und dies dann kaufen, Wenn du nur eins von beiden kaufst musst du warten bis der Balken durchgelaufen ist. LG

**Comment by DerHessenTyp** [comment]
Ist bei mir genauso gestern Abend gewesen. Man hat was gegessen und getrunken und wollte die Karte nochmal öffnen NACHDEM ich fertig war mit Essen und Trinken und auch die Prozentanzeige durch war. Habs dann 5 Minuten später nochmal probiert und es wurde mir angezeigt: ,,Du isst bereits" Ein Relogg hab ich jetzt nicht probiert gehabt.
