### ISSUE TITLE
Utensilien anlegen geht nicht "Meldung Ess erst auf erscheint"

### ISSUE THREAD

**Issue by wichtTSV** [mexyn/statev_v2_issues#1988]
Tom Spider
**Auftrittszeitpunkt (Datum / Uhrzeit)**
1.11.2021, 23:20
**Beobachtetes Verhalten**
Ich habe probiert im Feld Utensilien anzulegen, sowie Fallschirm, Taschenlampe, Messer etc.. Geht anscheind alles nicht mehr.
**Erwartetes Verhalten**
Das ich den Fallschirm, Taschenlampe etc, anlegen kann wie gewohnt, den ich nicht essen kann.
**Schritte um den Fehler nachvollziehen zu können**
Fallschirm, Taschenlampe, Messer etc.

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/74994115/139750435-dbcba747-ff8e-4efa-90f6-f4c8a7514e65.png)

**Comment by CaleighRhodes** [comment]
Gleicher Fehler, wenn man nach dem Essen eine Taschenlampe ABrüsten will.

**Comment by CubeXLIVE** [comment]
Ähnliches Problem, manchmal wenn man dann ins Restaurant gehen will steht dann da auch sowas ähnliches. "Du isst bereits" oder so ähnlich.

**Comment by JulianMa** [comment]
Fixed mit #1986
