### ISSUE TITLE
Sultan RS Classic Produktion

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#1989]
Nichts super kritisches -  er braucht 4 Sitze + 2 Carbon Rennsitze

![6b0d89f9d9f6f373007602fde289fb09 (1)](https://user-images.githubusercontent.com/16436981/139873778-07b12559-a977-4b18-920e-f8f65dd3eacf.png)

**Comment by DonVitoDiangelo** [comment]
next update fixed

**Comment by Dean-Gallagher** [comment]
Dies ist bei allen neuen autos btw @DonVitoDiangelo

**Comment by epichalt** [comment]
bei fast allen anderen passt es. es sind zwar 2 Sitzer, aber hinten ist noch eine Sitzbank bei fast allen. Daher finde ich 4 Sitze (inkl. Carbon Sitze) schon in Ordnung. Aber die 6 Sitze beim Sultan sind halt zu viel :D
