### ISSUE TITLE
Kofferraum am Heck, auch bei Heckmotoren

### ISSUE THREAD

**Issue by Chunk3r** [mexyn/statev_v2_issues#1990]
Beispielsweise der Comet Safari hat den Kofferraum vorne, das sorgt seit dem Update für Verwirrung. 
Außerdem kommt man beim Granger nicht an den Kofferraum wenn man die Heckklappe nicht runter drückt, was nur möglich ist wenn kein Fahrer im Fahrzeug sitzt.

**Comment by CaleighRhodes** [comment]
#1958

**Comment by DonVitoDiangelo** [comment]
> #1958

This,. Was den Granger betrifft, nach dem nächsten Update nochmal prüfen. Sollte dann leichter sein an den Trunk zu kommen.
