### ISSUE TITLE
Hunger/Durst bleibt viel zu lange auf Max

### ISSUE THREAD

**Issue by CaleighRhodes** [mexyn/statev_v2_issues#1992]
**Character Name**
Caleigh_Rhodes, Hanna_Fields, John_Rapp

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.11., ca. 9 Uhr

**Beobachtetes Verhalten**
Sind alle unabhängig voneinander im Restaurant gewesen gegen ca. 9 Uhr. Haben dort gegessen. Sind alle seit mehreren Stunden mit nur kurzen Pausen IC und die Durst/Hunger-Anzeige ist gleichbleibend.

**Erwartetes Verhalten**
Hunger und Durst bekommen.

**Schritte um den Fehler nachvollziehen zu können**
Essen gehen, mehrere Stunden IC sein.

**Comment by JohnRappStateV** [comment]
Ich habe gerade Hunger bekommen (17:08 Uhr) - Durst ist noch ok. 

Bin aber auch so um ~11:00 Uhr (weiß nicht mehr ganz genau) essen gegangen. Meiner Meinung nach immer noch zu lange für einen Restaurantbesuch.

**Comment by Saaria83** [comment]
Ca 10h war man satt. Denke da lief was  nicht richtig :D

**Comment by CaleighRhodes** [comment]
Kommt hin, ich bekomme jetzt gerade Durst, war aber zwischendurch knapp 2 Stunden offline.

**Comment by Hutstaender** [comment]
Ist das noch aktuell?

**Comment by CaleighRhodes** [comment]
Kann ich dir erst morgen sagen, war gestern & heute nicht IC. 
Melde mich morgen im Laufe des Tages hier nochmal.

**Comment by JohnRappStateV** [comment]
War glaub ich nur der eine Tag, bei mir hat es sich heute wieder "normal" angefühlt
