### ISSUE TITLE
keine Be-/Entladepunkt #1974

### ISSUE THREAD

**Issue by Stiefel911** [mexyn/statev_v2_issues#1994]
Irgendwie scheint der Wurm drin zu sein...

leider fehlt dieser immer noch

man kann ja vieles mit Hand transportieren, aber mit Flüssigkeiten sieht es nun mal schlecht aus...
![Grand Theft Auto V Screenshot 2021 11 03 - 01 56 01 92](https://user-images.githubusercontent.com/74860269/139978445-e9fc64cc-b0d0-4f69-8d32-c042dbc032b6.png)
hab vorgesetzt damit man es vlt besser sieht, was man eben nicht sieht und leider auch nicht da ist...
die Meldung Kein Fahrzeug gefunden kommt immer noch, egal wie ich es positioniere... :~

So long

[#1974](https://github.com/mexyn/statev_v2_issues/issues/1974)

**Comment by DonVitoDiangelo** [comment]
![1](https://user-images.githubusercontent.com/70151087/140017527-3d0e906b-d6df-49b9-ae18-d1ec95f0f43b.jpg)
Bitte nächste Update abwarten

**Comment by Stiefel911** [comment]
Langsam wird es kritisch, auch wenn es bereits 10 Tage erst her ist...die Flüssigkeiten im Lager bekomme ich einfach nicht da raus, obwohl diese benötigt werden. Und was ich nicht verstehen kann ist, 14:13 heißt es erledigt, 15:00 Update mit diversen BE/Endlade Punkte gefixt..und hier, ach das ist noch gar nicht eingespielt...
so verstehe ich jedenfalls die Antwort...
Ganz davon abgesehen das der punkt eigentlich so gedacht war das man mit einer Achse zwischen den Gebäuden fahren kann, aber da bin ich vllt auch selbst schuld anhand des Bildes etwas schlecht zu erkennen... Ist jetzt aber auch nicht der Wichtigkeitsfaktor..

Sorry bin da etwas nun ungeduldig...hängt ja noch etwas mehr hinten drann als nur lagern

trotz Frust super Arbeit .....
