### ISSUE TITLE
Bug beim Annehmen von Racing Events

### ISSUE THREAD

**Issue by ShauniKT** [mexyn/statev_v2_issues#1999]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name** Shauni Teller

**Auftrittszeitpunkt (Datum / Uhrzeit)** s
 seit es das Rennfahrupdate gibt

**Beobachtetes Verhalten**
 Wenn ich ein renne auswähle, bleibt das fenster trotzdem aktiv. dadurch kann ich kein anderes Menü nutzen (x-menü, telefon, tablet, inventar, etc.)

**Erwartetes Verhalten**
 dass sich das fenster nach der fahrstreckenauswahl schließt (tut es auch nach 1-3 mal relogg und neu annehmen)

**Schritte um den Fehler nachvollziehen zu können**
 Zum Renndude gehen und ein rennen auswählen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Fabse96** [comment]
![Grand Theft Auto V_2021 11 05-13 33](https://user-images.githubusercontent.com/74773267/140510889-5675f049-9b8c-4d62-9e0d-92e498fc36ea.png)

hatte den selben fehler, villeicht hilft dies hier etwas weiter

**Comment by JulianMa** [comment]
Kein Frontend-Bug, hier crashed das CEF

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2049

**Comment by TheOutburst** [comment]
#2116
