### ISSUE TITLE
Kaufmenge durch Pfeiltasten einstellen

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#200]
Ben Blumenberg

Jederzeit

Man kann die Kaufmenge in jeglichen Shops nur noch durch eine Zahleneingabe einstellen, früher war es auch möglich dieses einfach mit den Pfeiltasten zu tätigen

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by r3sist3nt** [comment]
mache ich sobald ich zeit habe

**Comment by r3sist3nt** [comment]
Done
