### ISSUE TITLE
Waffen zieh Animations Bug

### ISSUE THREAD

**Issue by ShauniKT** [mexyn/statev_v2_issues#2000]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Shauni Teller (bei Klaus Kevin beobachtet)

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit Update

**Beobachtetes Verhalten**
Wenn man eine Waffe angelegt hat, triggert die Animation des Waffe Ausrüstens beim einsteigen in ein Fahrzeug. Wenn man Aussteigt, triggert die "Wegsteck" Animation. An sich nicht sehr schlimm, allerdings wird sie im RP ausgespielt, was nun mehrmals dazu geführt hat, das PD Beamte einen Taser auf uns richteten mit der Aufforderung, die Waffe wegzustecken, obwohl man sie ja nicht in der Hand hatte. Es wurde nur die Animation wahrgenommen und darauf reagiert.

**Erwartetes Verhalten**

Das die Animation nicht triggert (oder falls es nicht möglich ist, darauf nicht wirklich reagiert wird?)

**Schritte um den Fehler nachvollziehen zu können**

mit im Inventar angelegter Waffe beim frei wählbaren Fahrzeug ein- und aussteigen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by epichalt** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1966

**Comment by Hutstaender** [comment]
Also ich weiß nicht, du müsstest vllt noch nen video nachreichen. Wir bekommen beim Aussteigen keine Weapon Pull Animation

**Comment by ShauniKT** [comment]
Okay ich mach die tage ein video von und reiche das nach
