### ISSUE TITLE
Fagaloa wird immer wieder versetzt

### ISSUE THREAD

**Issue by Stonny1** [mexyn/statev_v2_issues#2001]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Donny Stalves**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22:40 03.11.2021

**Beobachtetes Verhalten**
Fahrzeug wird geparkt und verschwindet dann. Taucht dann irgendwo anders wieder auf. (wird nicht in der Garage einparkt)

**Erwartetes Verhalten**
Bitte prüfen

**Schritte um den Fehler nachvollziehen zu können**
Passiert total willkürlich. Gibt kein Muster.

**Comment by DonVitoDiangelo** [comment]
Passiert dir das ständig? Hat noch wer anders einen Schlüssel? Seit wann hast du das Problem?
