### ISSUE TITLE
Prodoverluste trotz ausgelernt

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#2003]
**Character Name**
Dean Gallagher

**Beobachtetes Verhalten**
Sack Kohlefasern haben verluste trotz das man ausgelernt ist.

**Erwartetes Verhalten**
keine Verluste mehr als bei Sack Kohlefasern wie bei allen anderen Labor sachen

**Optional: Video / Bilder des Fehlers**
https://prnt.sc/1yc3t1v
https://prnt.sc/1yc3zwk

**Comment by DonVitoDiangelo** [comment]
next update fixed
