### ISSUE TITLE
Senftütchen und Ketchup Tütchen

### ISSUE THREAD

**Issue by LiljaMorningstar** [mexyn/statev_v2_issues#2005]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Lilja_Teller
**Auftrittszeitpunkt (Datum / Uhrzeit)**

30.10.2021
**Beobachtetes Verhalten**

Wenn man Rinderrouladen sowie Currywurst herstellt benötigt man ketchup tütchen. Diese werden aber dann beim Kochvorgang nicht verbraucht sondern bleiben erhalten. Kochvorgang wurde im HooVers gestartet mit den Rouladen.
**Erwartetes Verhalten**

Sollte wie immer verbraucht werden
**Schritte um den Fehler nachvollziehen zu können**

Kochvorgang für Rinderrouladen gestartet und nach der fertig stellung gesehen dass benötigte senf tütchen in der Maschine verblieben sind
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Wie kommst du da drauf? Hast du mal ein Bild von deinem Rezept? Es gibt keine Tütchen mehr, nur Tuben und Ketchup wird z.B. in der Rouladen Produktion nicht benötigt.

**Comment by LiljaMorningstar** [comment]
Das ist Richtig für die Currywurst gibts ja auch kein Rezept zum Beispiel.  Bei der Brauchst du im Inventar 1xCurry 1xBratwurst im Brötchen und 1x Tube Ketchup. Hast du eines der 3 Dinge nicht bekommt man ja die Fehlermeldung was fehlt. Hab ich aber alles im Inventar und stelle die Currywurst her, hab ich alle Dinge verbraucht ausser der Tube Ketchup. Die verbleibt im Inventar. Und ich kann wenn Ich will mit der einen Tube Ketchup 1000 weitere Currywürste herstellen. Weil sie einfach nicht verbraucht wird. 

Das Gleiche bei den Rouladen. Brauche bei einem Kochvorgang Rouladen 8 Senf Tuben. Die Rouladen werden Produziert, aber in der Maschine verbleiben die Senftuben. Werden auch nicht verbraucht obwohl sie ja Teil des Rezeptes sind. 

P.S.: Mit Tütchen meinte ich auch Tuben :)
