### ISSUE TITLE
Gamecrash beim Fahren > Auto dreht ohne Fahrer weiter durch

### ISSUE THREAD

**Issue by masterppc** [mexyn/statev_v2_issues#201]
**Character Name**
Hans Hentschel
**Zeitpunkt (Datum / Uhrzeit)**
02.10.2020 18:40
**Beobachtetes Verhalten**
Nach einem Game Crash wieder ins Game gegangen. Mein Fahrzeug in dem ich den Crash hatte fuhr ohne Fahrer weiter
**Erwartetes Verhalten**
Auto steht?
**Schritte um den Fehler nachvollziehen zu können**
Gamecrash beim Fahren (hatte gefunkt)
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/5xl4e_XtflU

**Comment by Chrinis007** [comment]
Crashdump bitte hinzufügen

**Comment by masterppc** [comment]
https://discordapp.com/channels/365251792679862292/695674055155777617/761638177261748330

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1112

**Comment by its4l3x** [comment]
Kein alt:V Issue. Ist normal, wenn in deiner Umgebung ein Spieler ist, der das "Fahrzeug Syncen" übernehem kann. 
Wenn keiner da ist für das Syncen, steht dein Fahrzeug auf dem Punkt, wo du disconnected bist.
