### ISSUE TITLE
ADAC Werkstatt raus fahrt ist blockiert

### ISSUE THREAD

**Issue by Chiko-Garcia** [mexyn/statev_v2_issues#2011]
ADAC Werkstatt

Chiko Garcia 

von der garage raus fahrt geht nicht rein fahren kann jeder ein und aus parken geht auch nur raus fahren geht nicht.
drausen vor der garage ist auch nix
und das ist jetzt schon seit 04.11.21

https://gyazo.com/4b2b95a72521d1aa907ddabe8d7911a6

**Comment by Chrinis007** [comment]
@Hutstaender schon wieder ;(

**Comment by Chiko-Garcia** [comment]
dieses mal nicht die offentliche garage sonder die werkstatt

**Comment by Dean-Gallagher** [comment]
Steht da ein Strahler oder desgleichen? Zählt alles als Objekt

**Comment by Chiko-Garcia** [comment]
müss ich mal schaun aber es hatte davor auch funktioniert

**Comment by Hutstaender** [comment]
Also aktuell geht es bin grad ic an der Werkstatt. Wenn sowas mal wieder ist bitte schreib mir direkt im Discord bezüglich der Blockade.
Blockiert ist der Ausgang wenn am jeweils anderen Marker ein Fahrzeug oder ein Spieler im Umkreis von 5 Metern steht. Also haltet die Ausfahrt immer frei.
