### ISSUE TITLE
Krawatte verschwindet bei Dienstantritt [EUP]

### ISSUE THREAD

**Issue by PresLincoln** [mexyn/statev_v2_issues#2012]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**David_Lincoln*

**06.11.2021**

**Beobachtetes Verhalten**
Wenn ich außer Dienst eine Krawatte tragen, mich dann in den Dienst melde - verschwindet die Krawatta bzw. wird unsichtbar. Im Kleidungsmenü (,) wird sie noch angezeigt.

**Erwartetes Verhalten**
Dass die Krawatte trotz Dienstantritt im EUP Menü noch nutzbar ist.

**Comment by DrGrizzlY17** [comment]
Es kann sein das bei der Skinerstellung dieser Slot überschrieben wird. Klär das am besten erstmal mit dem ab, der den Skin erstellt hat

**Comment by milkdrops** [comment]
Genau, der Slot ist immer durch Holster belegt.

Kleidungs-Slots in GTA sind limitiert, EUP benutzt eben diese Slot, wie es deren Devs vorgesehen haben.
Funktioniert also ordnungsgemäß.

Es gibt Skins, die keine Holster haben, bei denen dann privat angezogene Krawatten angezeigt werden können.
Generell halten wir die Slots der PD-Skins so minimal belegt, wie es nur möglich ist.
Gerne bei sonstigen Fragen zu unseren PD-Skins per Discord an mich / Gonzo wenden.
