### ISSUE TITLE
Ausparkpunkt Garage Tequi-La-La

### ISSUE THREAD

**Issue by CaleighRhodes** [mexyn/statev_v2_issues#2014]
**Character Name**
Caleigh Rhodes

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.11.2021 / 19 Uhr

**Beobachtetes Verhalten**
Beim Ausparken an der Garage Tequi-La-La schlägt das Fahrzeug möglicherweise in Fahrzeuge ein, die wie der graue Issi Classic in den Parkbuchten stehen oder kann deshalb gar nicht erst ausgeparkt werden (Ausfahrt blockiert). Vielleicht wäre es daher besser, den Ausparkpunkt entweder in den hinteren Bereich des Parkplatzes zu verlegen oder dort hin, wie auf dem Bild markiert.

**Optional: Video / Bilder des Fehlers**
![Inked20211106190408_1_LI](https://user-images.githubusercontent.com/74977218/140625185-7bc7db4a-12cc-4a28-b441-144c71627a0b.jpg)

**Comment by CaleighRhodes** [comment]
Achso, der aktuelle Ausparkpunkt liegt direkt hinter dem Heck vom grauen Issi.

**Comment by TamiGaming** [comment]
Pounder hängen aktuell auch beim Ausparken hinten an der Kante fest und gehen dadurch kaputt. 
Wäre also nicht nur wegen den parkenden Fahrzeugen :)

**Comment by DrGrizzlY17** [comment]
Hab sie auf den hinteren Parkplatz verschoben. Sollte die beste Problemlösung sein
