### ISSUE TITLE
Krawatten im EUP-Menü deaktiviert

### ISSUE THREAD

**Issue by PresLincoln** [mexyn/statev_v2_issues#2016]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**David_Lincoln**

**06.11.2021**

**Wenn man als Cop z.B. ein Detective Outfit im Kleiderschranks auswählt, kann man in der Regel seine eigenen Klamotten selber bestimmen, jedoch ist es nicht möglich eine Krawatte anzuziehen, da diese nicht angezeigt wird, während man im Cop-Dienst eingestempelt ist. Wenn man sich wieder ausstempelt, erscheint die Krawatte jedoch wieder - im Dienst kann man also keine Krawatten tragen. Krawatte wird trotzdem im Kleidungsmenü UI (,) angezeigt.**

**Erwartetes Verhalten**
Dass man die Krawatte auch im Cop-Dienst tragen kann bzw. am Char angezeigt wird.

**Schritte um den Fehler nachvollziehen zu können**
1. Im Cop-Dienst einstempeln
2. Ein Detective Outfit auswählen (Nr.553 im Kleiderschrank)
3. Krawatte probieren anzuziehen = Krawatte wird am Char nicht geladen. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Chrinis007** [comment]
Duplikat von #2012

**Comment by Chrinis007** [comment]
`Genau, der Slot ist immer durch Holster belegt.

Kleidungs-Slots in GTA sind limitiert, EUP benutzt eben diese Slots, wie es deren Devs vorgesehen haben.
Funktioniert also ordnungsgemäß.

Es gibt Skins, die keine Holster haben, bei denen dann privat angezogene Krawatten angezeigt werden können.
Generell halten wir die Slots der PD-Skins so minimal belegt, wie es nur möglich ist.
Gerne bei sonstigen Fragen zu unseren PD-Skins per Discord an mich und Gonzo wenden. `

**Comment by Chrinis007** [comment]
> Genau, der Slot ist immer durch Holster belegt.
> 
> Kleidungs-Slots in GTA sind limitiert, EUP benutzt eben diese Slots, wie es deren Devs vorgesehen haben. Funktioniert also ordnungsgemäß.
> 
> Es gibt Skins, die keine Holster haben, bei denen dann privat angezogene Krawatten angezeigt werden können. Generell halten wir die Slots der PD-Skins so minimal belegt, wie es nur möglich ist. Gerne bei sonstigen Fragen zu unseren PD-Skins per Discord an mich und Gonzo wenden.
