### ISSUE TITLE
Nase bugt durch das Bandana

### ISSUE THREAD

**Issue by Binkiii** [mexyn/statev_v2_issues#2017]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Jaden_Curtis

**Auftrittszeitpunkt (Datum / Uhrzeit)**
07.11.2021 / 18:40
**Beobachtetes Verhalten**
Beim aufsetzen eines Bandanas schaut bei mir ein kleiner Teil der Nase durch.

**Erwartetes Verhalten**
Das der Bug mit der Nase und den Bandanas behoben wird.

**Schritte um den Fehler nachvollziehen zu können**
Mit meinem Character ein Bandana aufziehen und das Verhalten beobachten.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TheOutburst** [comment]
#1924
