### ISSUE TITLE
Mixer Bug Spritverbrauch

### ISSUE THREAD

**Issue by JonnyHart** [mexyn/statev_v2_issues#2019]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Jonny Hart

09.11.2021 - 05:00 Uhr

Spritverbrauch Mixer sehr hoch

Spritverbrauch sollte nicht so hoch sein, damit man wenigstens von Tanke zu Tanke kommt

Mixer tanken und los fahren (War nur heute morgen bei mir)

https://youtu.be/d_jTXyROfao

**Comment by epichalt** [comment]
Das letzte Update ging wohl an dir vorbei^^

**Comment by JonnyHart** [comment]
Das hab ich im Hinterkopf, kann mir aber schwer vorstellen das jemand ein Loch in mein Tank gebohrt hat und der Spritverbrauch so hoch ist, dass ich nicht mal mehr in die Stadt zurück komme. Zumal es gestern Abend nicht so war und ich keine Probleme hatte. Nun nachdem einloggen heute morgen, war es so.

**Comment by DrGrizzlY17** [comment]
Also hier liegt schonmal kein Bug vor. Und da es von gestern auf heute kein Update gab, haben wir auch nichts dran verändert.

Wie bereits erwähnt wurde, könnte hier vielleicht das neue Verschleiß eingetreten sein. Wenn du damit nicht in die Stadt kommst, rate ich dir ne alternative Lösung für das Problem an deinem Mixer zu finden.

**Comment by JonnyHart** [comment]
Das ich mir eine Alternative überlegen muss, ist mir bewusst. Ich hab es nicht böse gemeint, wollte nur einen eventuellen Bug melden. Gut das es sich dann doch um den Verschleiß handelt überrascht mich ein bißchen, dass es so krass ist. Naja SoWhat werde ich mich das nächste mal zurückhalten mit Meldungen, nicht das wieder der Fehler auf meiner Seite liegt.

**Comment by DrGrizzlY17** [comment]
> Das ich mir eine Alternative überlegen muss, ist mir bewusst. Ich hab es nicht böse gemeint, wollte nur einen eventuellen Bug melden. Gut das es sich dann doch um den Verschleiß handelt überrascht mich ein bißchen, dass es so krass ist. Naja SoWhat werde ich mich das nächste mal zurückhalten mit Meldungen, nicht das wieder der Fehler auf meiner Seite liegt.

Ne du verstehst mich glaube falsch. Du kannst sowas natürlich melden, wenn du denkst das ein Fehler vorliegt. Das entsprechende Feedback ob es sich um ein Fehler hält oder es vielleicht wie hier ein Feature ist, kriegst du dann halt mitgeteilt :D Ist nicht böse gemeint

**Comment by JonnyHart** [comment]
Alles klar ...
