### ISSUE TITLE
Bluse Aufgeknüpft & Geschlossen nicht Produzierbar 

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#2020]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Ryan & Mila Valdes

**Auftrittszeitpunkt (Datum / Uhrzeit)**

09.11.2021 22:25Uhr

**Beobachtetes Verhalten**

Die Blusen sind zwar im Fashion Killa enthalten aber nicht im Produktionscomputer.
Es handelt sich hierbei um [F][U] Blusen 1-20

https://media.discordapp.net/attachments/734511525691129976/907741800662433852/unknown.png?width=779&height=416

**Erwartetes Verhalten**

 Blusen Produzierbar machen

**Comment by Enemyaa** [comment]
Das sind Fraktionshemden, die du als Zivi eigentlich gar nicht sehen solltest. Die werden nicht herstellbar gemacht.
