### ISSUE TITLE
Kiste Whisky kann nicht ausgepackt werden 

### ISSUE THREAD

**Issue by Smaty86** [mexyn/statev_v2_issues#2021]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Hi, in der Bar Vanilla Unicorn können keine Kisten Whisky ausgepackt werden. Normalerweise kann man die Kisten in jeder Bar oder Restaurant auspacken. 

**Tim_Rock**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

1. mal Beobachtet, heute: 10.11.2021

**Beobachtetes Verhalten**

Der Punkt Kiste Whisky auspacken ist nicht vorhanden. 

**Erwartetes Verhalten**

Der Punkt Kiste Whisky auspacken sollte vorhanden sein, wie aucfh bei den anderen Snaps Sorten

**Schritte um den Fehler nachvollziehen zu können**

Kiste Whisky in die Maschiene von der Bar legen. Es erscheint keine Möglichkeit die Kiste auszupacken. Im Restaurant ist dies weiterhin möglich. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Chrinis007** [comment]
#1981

**Comment by DonVitoDiangelo** [comment]
Bitte prüfen, sollte bereits gefixt sein. Kann aktuell auch keinen Fehler erkennen.

**Comment by Enemyaa** [comment]
Geht einwandfrei! Sollte das aktuell nicht auf dem Live Server funktionieren, wird es das mit dem nächsten Update.

**Comment by Smaty86** [comment]
Hi,

im Vanilla Unicorn kann die normale Flasche Whisky weiterhin nicht ausgepackt werden. Wann kommt das nächste Update? 

![grafik](https://user-images.githubusercontent.com/76659094/142088253-97b4bde7-78ab-481f-b60b-de4e83946a68.png)
