### ISSUE TITLE
Sync Bug Zentralmine auto

### ISSUE THREAD

**Issue by MarkHarland** [mexyn/statev_v2_issues#2024]
**Mark Harland**

**10.11.2021 / 21:10**

**Polizeifahrzeug wurde nicht angezeigt ist den aufeinmal aus den nix aufgedacht und wild durch die gegend geflogen der SUV der Gerammt wurde hatte danach eine Gelbe leuchte**

**Fahrzeug normal angezeigt wird**

**Schwer zu beschreiben am besten einfach das Video angucken*

**https://medal.tv/games/gta-v/clips/71087432/d1337Km388ne?invite=cr-MSx5a2MsMjk3MTY5NDgs**

**Comment by DonVitoDiangelo** [comment]
Denke da können wir nicht viel machen, kann passieren.
