### ISSUE TITLE
Tankstelle Sandy Shores

### ISSUE THREAD

**Issue by Lucky2406** [mexyn/statev_v2_issues#2025]
**Character Name**
Miguel Ashton

**Auftrittszeitpunkt (Datum / Uhrzeit)**
10.11.2021 21:39

**Beobachtetes Verhalten**
Tankstelle explodiert trotz Abstand von mindestens 1-2 Metern

**Erwartetes Verhalten**
Tankstelle explodiert nicht, da Hitbox kleiner und somit nicht so schnell getroffen

**Schritte um den Fehler nachvollziehen zu können**
Zwischen Tank und Tankstelle mit einem Phantom Custom und einer  Achse fahren und zu beiden Seiten gleich viel Abstand halten.

**Verdacht auf zu große Hitbox für zu kleine Tanke**

**Comment by M4rvinLP** [comment]
Es explodieren in letzter Zeite generell die Tankstellen extrem häufig wie ich mitbekommen habe.

**Comment by Dean-Gallagher** [comment]
> 
> 
> Es explodieren in letzter Zeite generell die Tankstellen extrem häufig wie ich mitbekommen habe.

liegt daran weil leute immer reinfahren :D

**Comment by M4rvinLP** [comment]
Ja, möglich. Kommt mir bloß aktuell etwas komisch vor. Nicht das es doch aktuell Syncprobleme gibt.

**Comment by Hutstaender** [comment]
Also an explodierenden Fahrzeugen können wir nicht viel ändern, wenn ihr da rein fahrt ^^ ich mach den mal zu
