### ISSUE TITLE
Respawn immer in PaletoBar nach GameCrash

### ISSUE THREAD

**Issue by JohnRappStateV** [mexyn/statev_v2_issues#2026]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

John Rapp

John Rapp, div. andere Member der Hell Dogs

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Bei jedem Gamecrash

**Beobachtetes Verhalten**
Nach einem Gamecrash spawne ich in der Bar in Paleto, wenn ich das Gebäude kurz vorher betreten habe. Egal ob ich gerade in Vespucci, Paleto, oder sonst wo bin. Dieses Verhalten tritt auch bei anderen Spielern der Hell Dogs auf, hierzu kann ich aber leider keine weiteren Angaben machen.

**Erwartetes Verhalten**

Am Ort des Crashes respawnen.

**Schritte um den Fehler nachvollziehen zu können**
Gamecrashes sind für mich nicht "einfach so" reproduzierbar.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Hutstaender** [comment]
Bist du zuvor aus der Bar über den Fahrzeug-Marker raus?

**Comment by JohnRappStateV** [comment]
Das kann ich dir leider nicht mehr mit 100% Gewissheit beantworten.. werde beim nächsten Mal drauf achten.

**Comment by its4l3x** [comment]
Denke mal das du das darüber bist - Ist Fixed im nächsten Update
