### ISSUE TITLE
Werkstatt Keller nach Relog begehbar

### ISSUE THREAD

**Issue by ElfengamesTV** [mexyn/statev_v2_issues#2027]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Charles Baker**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Nach jedem Relog in der Werkstatt (09.11.2021 15:40)

**Beobachtetes Verhalten**
Boden nicht mehr Sichtbar und die Tür zum Keller der Werkstatt ist begehbar

**Erwartetes Verhalten**
Boden sichtbar und Keller verschlossen

**Schritte um den Fehler nachvollziehen zu können**
In der Werkstatt (NORTH CUSTOM) Ausloggen und dort auch wieder Einloggen 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/gOEZ1UmFp60

**Comment by Chrinis007** [comment]
Glaube das is n Problem vom Zusammenspiel zwischen Alt:V und den Interieur

**Comment by its4l3x** [comment]
Bekannter Fehler - Ist mit dem nächsten Update gefixed
