### ISSUE TITLE
Windsor Drop portet weg.

### ISSUE THREAD

**Issue by miischaa** [mexyn/statev_v2_issues#2028]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Heinrich Iwanow

10.11.2021 gegen etwa 21:00 Uhr und 11.11.2021 gegen etwa 18:20 Uhr

Mein Windsor Drop wurde beide Male beim verlassen einer Goldschmiede woanders hingeportet (maybe auch während ich drinne war). Beim ersten Mal zur Mission Row Garage auf den Parkplatz (wo er vorher etwas länger stand) und beim zweiten Mal auf die südliche Straße von der Bank am Würfelpark (da bin ich vorher nur einmal durchgefahren). 
Die Goldschmiede befindet sich am Playermarker auf dem Screenshot. Der Screenshot selbst zeigt nur die Location wo der Windsor Drop beim zweiten Port gelandet ist (vom ersten Mal hab ich keinen Screenshot).
Von dem Auto hat nur eine Person einen Schlüssel und die war an beiden Tagen bisher garnicht eingeloggt.

Dass, das Auto am abgestellten Punkt vor der Goldschmiede ist.

Wie oben beschrieben.
Steige ins Auto > Fahre zur Goldschmiede > Mache etwas in der Goldschmiede > Komme raus, Auto weg

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

https://i.gyazo.com/270681cea253c698cffd21493145efec.png

**Comment by miischaa** [comment]
Kleiner Edit, habe ihn wie folgt an der Position vorgefunden, falls das hilft.
https://i.gyazo.com/62637f623d2a963032755646781be590.jpg

**Comment by Hutstaender** [comment]
hängt im Sammelticket.
