### ISSUE TITLE
Ketten X

### ISSUE THREAD

**Issue by miischaa** [mexyn/statev_v2_issues#2029]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Heinrich Iwanow

**Auftrittszeitpunkt (Datum / Uhrzeit)**
---

**Beobachtetes Verhalten**
Ich weiß das kommt ziemlich spät, bin aber sonst bisher noch nicht dazu gekommen... Wollte mal nachfragen was mit den ganzen alten Ketten ist, gab ja A & B Ketten beim Juwelier. Eine Sorte ist ja jetzt tragbar und die andere ist mit einem X im Namen gekennzeichnet. Was macht man nun mit denen die useless sind? Kann man die eintauschen o.ä.?

**Erwartetes Verhalten**
---

**Schritte um den Fehler nachvollziehen zu können**
---

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
---

**Optional: Video / Bilder des Fehlers**
---

**Comment by Enemyaa** [comment]
Keine Kette ist useless. Es ist aber nur noch eine Version herstellbar, da man die unter den Extras entweder enganliegend tragen kann oder ober der Klamotte und wenn du nur die normale Version im Verkauf haben willst, kannst du die ganzen X Versionen 1x anziehen und in den Extras auf enganliegend gehen, dann wird das Modell automatisch getauscht.

**Comment by miischaa** [comment]
Ach okay, vielen Dank dir. 
Dann habe ich das etwas falsch verstanden.
