### ISSUE TITLE
Tunings nicht übernommen

### ISSUE THREAD

**Issue by RealSocius** [mexyn/statev_v2_issues#203]
**Character Name**
Sebastian Schindler

**Zeitpunkt (Datum / Uhrzeit)**
19:31 02.10.2020

**Beobachtetes Verhalten**
Fahrzeug ausgeparkt und komplett anders getunt (Farbe, Scheiben, Motorhaube, ect.)

**Erwartetes Verhalten**
Tuning von v1 auf dem Fahrzeug

**Schritte um den Fehler nachvollziehen zu können**
Annis Hellion ausgeparkt und statt schwarz war er blau und komplett anders getunt

**Comment by Chrinis007** [comment]
Das savegame ist das vom letzten Test, da hast du den wahrscheinlich anders getuntes ;)

**Comment by r3sist3nt** [comment]
Ist mir die Tage auch schon aufgefallen. Ich schau mir das an.

**Comment by r3sist3nt** [comment]
@RealSocius Ach, ich dachte es geht hier um Fehler beim Tuning in der Werkstatt.
Wie Chrinis schon sagte, der Datenbankstand ist vom vorherigen Lasttest. Das Tuning deshalb auch das sein, was zum zeitpunkt dieses letzten Lasttests am Fahrzeug aktiv war.
