### ISSUE TITLE
Falsches Icon für Bracelets

### ISSUE THREAD

**Issue by miischaa** [mexyn/statev_v2_issues#2031]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Heinrich_Iwanow

**Auftrittszeitpunkt (Datum / Uhrzeit)**
13.11.2021 10Uhr

**Beobachtetes Verhalten**
Die Bracelets haben das Icon von den Watches, aber nur nachdem sie entpackt sind.

**Erwartetes Verhalten**
Richtiges Icon haben

**Schritte um den Fehler nachvollziehen zu können**
Bracelet entpacken im Juwelier.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://i.gyazo.com/da5197c9dcb4ea728d5755115903e283.png

**Comment by Enemyaa** [comment]
Die Icon's im Userinterface stehen für ein Sammelbegriff der nicht immer 1zu1 stimmen muss. GTA selbst hat alle Armbänder die links getragen werden, zu den Uhren (watches) sortiert,
