### ISSUE TITLE
Puffer Jacket Herstellung

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#2034]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Ryan_Valdes
**Auftrittszeitpunkt (Datum / Uhrzeit)**

15.11.2021
**Beobachtetes Verhalten**

Ich weiß nicht ob es so gewollt ist oder nicht bei manchen Frauen Puffer Jackets brauch man zusätzlich Daunenfüllung, und bei anderen wiederum nicht. Bei Männer Puffer Jackets allerdings brauch man bei keiner Jacke die Daunenfüllung.
**Erwartetes Verhalten**

Endweder überall Daunenfüllung oder die Daunenfüllung entfernen.
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![unknown](https://user-images.githubusercontent.com/70231715/141808831-32b74cd0-2ded-4667-8402-f79e8c0c3fa9.png)
![unknown (1)](https://user-images.githubusercontent.com/70231715/141808845-c49e4474-d4b9-49d2-bd1a-3c1fd5faace1.png)
![unknown (2)](https://user-images.githubusercontent.com/70231715/141808855-ee9cc2a5-33cc-4ea2-8a52-52d01af50793.png)
![unknown (3)](https://user-images.githubusercontent.com/70231715/141808866-174a8bb9-04d5-4c33-a339-99a4f5bcabe4.png)
![unknown (4)](https://user-images.githubusercontent.com/70231715/141808890-e2134b2d-47b5-4038-b801-e94552d59606.png)

**Comment by Enemyaa** [comment]
Das ist richtig. Da wurden einige mal zum Test bearbeitet. Schau ich mir nochmal an.
