### ISSUE TITLE
Automatischen einparken von Fahrzeugen

### ISSUE THREAD

**Issue by JohnMckansy** [mexyn/statev_v2_issues#2035]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

John_Mckansy

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Kurz nach server-restart 15:00 14.11.21

**Beobachtetes Verhalten**

Nach dem Serverneustart war meine vorher noch benutze Zugmaschine in der Garage, der Auflieger stand derweil immernoch neben mir. Der Phantom wurde demnach ohne lange STandzeit einfach eingeparkt vom System.

**Erwartetes Verhalten**

Der Phantom hätte vor dem Auflieger stehen sollen.

**Schritte um den Fehler nachvollziehen zu können**

Ich habe schmutziges Wasser geholt. Kurz vor dem Serverrestart Phantom und Auflieger geparkt. (am Staudamm um nach dem Restart weiterzuarbeiten) Nach dem Restart eingeloggt. Auflieger steht da wie er sein sollte. Zugmaschine weg / in der Garage neben dem Ölfeld eingeparkt.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

Nope

**Optional: Video / Bilder des Fehlers**

Leider nicht vorhanden.

**Comment by DonVitoDiangelo** [comment]
Fahrzeuge müssen mehr benutzt werden. im Zweifel an eine Garage fahren vor Restart.
