### ISSUE TITLE
Animationen von verschiedenen Ordnern Sync

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#2037]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.11.2021 00:00  zuvor auch schon aufgefallen

**Beobachtetes Verhalten**
Zwei verschiedene Animationsordner haben sich gesynct. (siehe Vid)

**Schritte um den Fehler nachvollziehen zu können**
Ist mir irgendwann mal aufgefallen, dass Animationen, die ich in einen Ordner speicher, auch im anderen landen. Seitdem auch mehrere Neustarts, der Fehler ist geblieben.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/sI2iBaR5Vk8
https://youtu.be/WBEVTBvyHu0

**Comment by JannikDatsch** [comment]
Jetzt, wo ich Tage später alle Animationen aus dem einen Ordner gelöscht habe, waren auch die beim anderen leer.

**Comment by Hutstaender** [comment]
lösch mal beide favoriten, die haben scheinbar die gleiche id.
