### ISSUE TITLE
Haare glitschen durch EUP Kopfbedeckungen 

### ISSUE THREAD

**Issue by PresLincoln** [mexyn/statev_v2_issues#2038]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

David_Lincoln

**Schon etwas länger, kp wie lange*

**Beobachtetes Verhalten**
Haare glitschen durch EUP Kopfbedeckungen 

**Erwartetes Verhalten**
Haare bleiben unter dem Hut

**Optional: Video / Bilder des Fehlers**
![ad](https://user-images.githubusercontent.com/75540676/142461095-129a5b2b-24df-43d2-afe1-a6f223e3454d.PNG)

**Comment by SgtSkipper** [comment]
Das Problem existiert tatsächlich schon seit längerem. Ich kann mir nur noch dran erinnern das die meisten sich ne beanie Mütze angezogen haben außerhalb des Dienstes und dann in den Dienst gegangen sind um das Problem mit den Hüten zu umgehen da dann die Menü Auswahl zur Verfügung stand zwecks dem ändern der Haare.

aber ich denke nicht das es im Sinne des Erfinders ist das System mit diesem Trick zu umgehen.

**Comment by Enemyaa** [comment]
Also, wenn du mit Uniform keine Extras hast um die Haare zu ändern, dann gehts auch nicht im Moment. Denn das ist ja ein mod. Hut, der kein hairclippig nutzt. 
@its4l3x Kann man die Extras auch für Dienstagkleidung einbauen?

**Comment by Enemyaa** [comment]
Also man kann die Extras nur triggern, wenn man zusätzlich über die Uniform (mit Hut), noch ein Hut/Cap anzieht. Das Outfit selber macht das nicht.
