### ISSUE TITLE
NFL Hosen erzeugen Linie am Bein

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#2039]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Noah Reese

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.11.21

**Beobachtetes Verhalten**
Hose erzeugt Linie am Bein, Siehe Bild

**Erwartetes Verhalten**
Keine Linie am Bein

**Schritte um den Fehler nachvollziehen zu können**
NFL Hose anziehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/70150887/142663355-6fb9b125-7824-4107-94f4-ddc860b9897a.png)

**Comment by Enemyaa** [comment]
Ist halt ne locked Mod. Entweder man kommt damit klar, oder man kauft sie einfach nicht, :)
