### ISSUE TITLE
Preise der Häuser fehlberechnet

### ISSUE THREAD

**Issue by SirAres** [mexyn/statev_v2_issues#2040]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
 
Ares_Hohengarten

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 
19.11.21

**Beobachtetes Verhalten**
 
Häuser sind Kaufbar für 2125000$

**Erwartetes Verhalten**

Den Häusern einen entsprechende Preis zuweisen der ihrer würdig ist

**Schritte um den Fehler nachvollziehen zu können**

Zum Haus gehen und selbst nachschauen

**Optional: Video / Bilder des Fehlers**

![Hausbug](https://user-images.githubusercontent.com/87204556/142671345-8a8e63ee-40b9-4cec-b921-129d11844d00.png)
![Hausbug 2](https://user-images.githubusercontent.com/87204556/142671355-658dbdc9-6db1-48b0-bf22-ee84c4df472b.png)

Hier noch eine Haus welches "richtig" ist. ( Ist zwar trotzdem teuer aber egal )
![Haus Richtig](https://user-images.githubusercontent.com/87204556/142671461-fa180ddd-92bb-402c-b2d0-7407b0fe2fb5.png)

**Comment by Chrinis007** [comment]
Gab schonmal n Eintrag dazu und dort wurde gesagt es bleibt so

**Comment by Chrinis007** [comment]
Hier zb #1682

**Comment by epichalt** [comment]
> Hier zb #1682

Sind doch komplett andere Häuser, am anderen Ende der Stadt
