### ISSUE TITLE
Fenster Hochfahren über X Menü fehlerhaft

### ISSUE THREAD

**Issue by SgtSkipper** [mexyn/statev_v2_issues#2041]
Character Name
James Edwards

Auftrittszeitpunkt (Datum / Uhrzeit)
20.11.2021

Beobachtetes Verhalten
Fenster Hochmachen Funktioniert nicht

Erwartetes Verhalten
Das Fenster Normal wieder hochfahren

Schritte um den Fehler nachvollziehen zu können
Fenster Runtermachen über X und dann wieder hochfahren lassen.
(Offenbar nicht syncht)

Monitorauflösung (nur wenn Falsche Darstellung in der UI)

Optional: Video / Bilder des Fehlers

https://prnt.sc/208pfth

**Comment by DrGrizzlY17** [comment]
Hat der Fahrer das gleiche Problem?

**Comment by SgtSkipper** [comment]
Laut aussage des fahrers fahren die Fenster bei ihm hoch und runter ganz normal

**Comment by DrGrizzlY17** [comment]
Hängt wahrscheinlich damit zusammen wenn man per Rechtsklick das Beifahrerseite Fenster runter fährt.

Müsste mal von der QA komplett getestet werden

**Comment by Hutstaender** [comment]
ist ein bereits bestätigter altv fehler

**Comment by TheOutburst** [comment]
#2116
