### ISSUE TITLE
Nos Flasche in Taxi

### ISSUE THREAD

**Issue by Michi993** [mexyn/statev_v2_issues#2042]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Luke Hammer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
20.11.2021

**Beobachtetes Verhalten**
Nos Flasche in Taxi einbauen -> Nos zünden

**Erwartetes Verhalten**
Nos flasche sollte nicht in taxi eingebaut werden

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
ist so gewollt
