### ISSUE TITLE
Person war unsichtbar für mich bis sie sich bewegt hatte

### ISSUE THREAD

**Issue by M4cm4ni4c** [mexyn/statev_v2_issues#2043]
**Character Name**
Ronny_Mcleod

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.11 ca. 3 uhr

**Beobachtetes Verhalten**
Person war für mich komplett nicht sichtbar bis sie sich bewegt hatte

**Erwartetes Verhalten**
Person sichtbar nicht nur für kollegen sondern auch für mich sichtbar

**Optional: Video / Bilder des Fehlers**

https://user-images.githubusercontent.com/79061254/142749973-fdabc2a7-eb1f-4976-8901-efd71510be73.mp4

**Comment by DonVitoDiangelo** [comment]
Wird sich vermutlich unter das Dach/Gebäude geglitcht haben für dich. Kommt vor, aber da können wir jetzt auch nichts dran ändern.
