### ISSUE TITLE
Waffenanimation beim ausstempeln obwohl keine Waffe dabei

### ISSUE THREAD

**Issue by M4cm4ni4c** [mexyn/statev_v2_issues#2044]
**Character Name**
Ronny_Mcleod

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.11 ca 4 uhr

**Beobachtetes Verhalten**
Char macht Waffenanimation obwohl keine waffe oder andere sachen ausgerüstet sind. beim ausstempeln

**Erwartetes Verhalten**
Char macht keine animation wenn er keine waffe oder ähnliches dabei hat.

**Schritte um den Fehler nachvollziehen zu können**
Kein plan. Einzige was mir einfallen würde wäre der Fallschirm den ich kurz vorher aufm dach ausgezogen hatte der das triggern könnte. Besitze nämlich keine waffe oder co.

**Optional: Video / Bilder des Fehlers**
Hab leider selbst kein clip aber hier von einer anderen Perspektive gesehen wie das aussah.
https://clips.twitch.tv/EmpathicStrangeVanillaYouWHY-DtdB7SsN5V0OjxE1

**Comment by Hutstaender** [comment]
integriert in #2018
