### ISSUE TITLE
Notrufsystem Funktioniert nach Bewusstlosigkeit nicht

### ISSUE THREAD

**Issue by SvenPhoenix** [mexyn/statev_v2_issues#2046]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Sven Phoenix**

**21.11.21 / 0-1 Uhr**

**Nachdem ich am Berg Bewusstlos wurde und von meinen Kollegen gerettet wurde funktionierte das Notrufsystem in den Fahrzeugen nicht mehr. Ich habe mehrmals die Taste ,,M´´ gedrückt aber es passierte nichts. Das Dispatch-System funktioniert anscheinend nicht wenn man vorher einmal Bewusstlos war. Info: Ich bin Medic und war zu dem Zeitpunkt im Dienst.**

**Das Dispatch-System in den Fahrzeugen sollte auch nach Bewusstlosigkeit funktionieren.**

**1. Mein sei Medic und im Dienst.**
**2. Man prüfe ob Dispatch-System funktioniert.**
**3. Wenn Dispatch-System funktioniert muss man irgendwie bewusstlos werden.**
**4. Wiederbeleben lassen und in einem Medic-Fahrzug ,,M´´ drücken um zu schauen ob die Notrufe funktionieren.**

**Comment by JannikDatsch** [comment]
#1853
