### ISSUE TITLE
Racer Untergrund Sprachreichweitenvisualisierung fehlerhaft

### ISSUE THREAD

**Issue by cadpri** [mexyn/statev_v2_issues#2047]
**Character Name**
Fabian Picard

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.11.2021

**Beobachtetes Verhalten**
Im Racer Untergrund wird die Sprachreichweitenvisualisierung nicht visualisiert

**Erwartetes Verhalten**
Die Sprachreichweitenvisualisierung wird visualisiert

**Schritte um den Fehler nachvollziehen zu können**
Untergrundrennen auswählen, reinfahren und die Sprachreichweite ändern

**Comment by SHaagmann** [comment]
Liegt nicht am reinfahren sondern am annehmen eines Rennes beim NPC wollte dazu noch nen bugtracker schreiben bin aber noch nicht dazu gekommen

**Comment by cadpri** [comment]
Danke für den Zusatz 🙂

**Comment by Hutstaender** [comment]
Tritt das noch auf?

**Comment by SHaagmann** [comment]
> Tritt das noch auf?

Bin in den letzten Tagen n paar Rennen gefahren, da hatte alles so weit ich mich errinern kann funktioniert. Teste das sobald ich zuhause bin nochmal um sicher zu gehen.

**Comment by SHaagmann** [comment]
@Hutstaender ist gefixed. Wird alles wie gewohnt angezeigt
