### ISSUE TITLE
Verschwinden von NOS-Flasche nach Ausparken

### ISSUE THREAD

**Issue by ArnoZuDemB** [mexyn/statev_v2_issues#2048]
**Mit welchem Character wurde das Verhalten in-game ausgelöst/beobachtet**
Robert Bates

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.11.2021 gegen 21:30 Uhr

**Beobachtetes Verhalten**
Einparken des Sultan Classics "TO MIAMI" mit verbautem NOS. Nach Einparken NOS nicht mehr verfügbar. (Ist mir mittlerweile mehrfach passiert). Mir ist unbekannt, ob auch andere Fahrzeuge dieses "Problem" haben.

**Erwartetes Verhalten**
Fahrzeug steht wie eingeparkt zur Verfügung (mit NOS)

**Schritte um den Fehler nachvollziehen zu können**
1. Sultan Classic spawnen
2. NOS-Flasche setzen
3. ins Fahrzeug setzen (Motor aus und stehend)
4. Rechtsklick auf NOS-Flasche (zum Einbau)
5. Fahrzeug in öffentlicher Garage einparken
6. Fahrzeug ausparken
(7. sich wundern)  

**Optional: Video / Bilder des Fehlers**
https://medal.tv/games/gta-v/clips/72479841/d1337oK9FnhV?invite=cr-MSxBbHQsMTg3NzgyNTks

**Comment by DonVitoDiangelo** [comment]
Wir gucken uns das an. :)

**Comment by its4l3x** [comment]
Gleiches Thema wie bei #1951 

Daher close

**Comment by Hutstaender** [comment]
in #2018 integriert
