### ISSUE TITLE
4K-Auflösung: Anzeigen zu groß/funktionieren nicht richtig

### ISSUE THREAD

**Issue by zarazandra** [mexyn/statev_v2_issues#205]
**Character Name**
Shiva Connelly

**Zeitpunkt (Datum / Uhrzeit)**
02.10. 20:15

**Beobachtetes Verhalten**
Animationsmenü | Auflösung nicht passend, man muss mehrmals auf die Ordner klicken, damit man das + zum Hinzufügen zu Ordnern sehen kann -> Siehe Bilder; 
Animationsmenü auf X |  Bilder zu groß -> Siehe Bilder;
Inventarmenü | Das Menü ist viel zu riesig (Schrift, Icons für Tab, Vunk und Telefon). 

**Erwartetes Verhalten**
Angenehme Größe von Elementen

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
4K | 3840x2160

**Optional: Video / Bilder des Fehlers**
![anim2](https://user-images.githubusercontent.com/70195103/94957341-e1fac380-04ed-11eb-9186-74d061a85402.png)
![anim1](https://user-images.githubusercontent.com/70195103/94957347-e32bf080-04ed-11eb-9874-8c9e032e9509.png)
![anim3](https://user-images.githubusercontent.com/70195103/94957349-e32bf080-04ed-11eb-8d0d-dc2cfd6cb3ee.png)
![animx](https://user-images.githubusercontent.com/70195103/94957461-13738f00-04ee-11eb-9429-0180b42822f0.png)
![inv](https://user-images.githubusercontent.com/70195103/94957667-6c432780-04ee-11eb-843c-c2815c1d9cf1.png)

**Comment by r3sist3nt** [comment]
* Animations: Fixed
* XMenu: Wird nicht behoben, aber die maximale Anzahl an Items wird reduziert
* Inventory: in Progress

**Comment by r3sist3nt** [comment]
Solved
