### ISSUE TITLE
Currypulver ---->> Kein Ankauf/Verkauf möglich

### ISSUE THREAD

**Issue by RomanSpielberg** [mexyn/statev_v2_issues#2050]
"Sack Currypulver" kommt aus dem Import und muss entpackt werden, dann kommt "Currypulver" raus. Das Currypulver kann man dann für Gerichte verwenden.

Im Marktplatz und Ankauf/Verkauf kann man aber das Item "Currypulver" nicht auswählen, da es fehlt. Bitte ändern.

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Das ist so korrekt. Die Grundressource kann nicht verkauft werden am Marktplatz, aber der Sack.
