### ISSUE TITLE
Service Reperaturen bei Fahrzeugen mit wenig KM und sorgsamen umgang

### ISSUE THREAD

**Issue by Reggi257** [mexyn/statev_v2_issues#2052]
Hallo ich habe das gefühl das bei manchen fahrzeugen sehr früh service reperaturen auftreten obwohl sie nicht viel gelaufen sind und auch ehr sorgsam mit gefahren wurde. ist das so gewollte das auch fehler auftretten bei fahrzeugen die gerade mal um die 4000KM gefahren sind oder ist das ehr noch zur zeit verbuggt?

**Comment by TheOutburst** [comment]
Ja, das ist so gewollt
