### ISSUE TITLE
Abladen von Flatbed Glücksspiel

### ISSUE THREAD

**Issue by Reggi257** [mexyn/statev_v2_issues#2053]
Wenn man mit Flatbed so wie SLamtruck abschleppt ist es beim Abladen immer Glücksspiel oder der wagen normal abgeladen wird oder ob er durch die gegend gefeuert wird. wir hatten auch schon denn fall das der wagen durch das abladen anfing zu brennen

**Comment by DrGrizzlY17** [comment]
Irgendwie Fahrzeuge wo das öfters vorkommt?

**Comment by Reggi257** [comment]
Nein es ist egal was für ein drauf ist kommt bei allen vor

**Comment by Dean-Gallagher** [comment]
kann ich bestätigen ist bei allem ultimativ random, dachte liegt nur an unserer werkstatt aber gut haben scheibar alle :D

**Comment by Dean-Gallagher** [comment]
https://youtu.be/WWJpumYJPHE sowas ist gemeint UA, 
das Diagnose geräte ist purer zufall das ichs in der hand hab und damit nix zutun

**Comment by Hutstaender** [comment]
Hab mal was versucht.

Bitte mal in nächster Zeit beobachten, sollte euch das nach dem nächsten Update nochmal auffallen direkt hier melden.

**Comment by Dean-Gallagher** [comment]
ist noch nicht gefixt
