### ISSUE TITLE
Bug beim Alkoholtest

### ISSUE THREAD

**Issue by CubeXLIVE** [mexyn/statev_v2_issues#2054]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Patrick_Nowak

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.11.21 - 22:01 Uhr

**Beobachtetes Verhalten**
Fehlermeldung nach Pusten beim Test

**Erwartetes Verhalten**
Kein aufploppen der Fehlermeldung

**Schritte um den Fehler nachvollziehen zu können**
-Alkoholtest durchführen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/e8833c8779a55b7b1a5ed6d9beaf542e

**Comment by its4l3x** [comment]
fixed next update
