### ISSUE TITLE
Bravado Paradise wechselt Folierung

### ISSUE THREAD

**Issue by croveans** [mexyn/statev_v2_issues#2055]
**Character Name**
Marty_Taylor

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.11.2021 / 23:50

**Beobachtetes Verhalten**
Bravado Paradise wandelt random seine Folierung & sieht bei jedem Spieler unterschiedlich aus. Zusätzlich kann man die Folierung nicht beim Tuning wechselt. Wenn das Fahrzeug eingeparkt wird, wechselt es im Anschluss weiterhin die Folierung.

**Erwartetes Verhalten**
Die Folierung wechselt sich nicht und kann in einer Werkstatt exakt ausgewählt werden (und ist also als Tuning verfügbar).

**Schritte um den Fehler nachvollziehen zu können**
Bravado Pardise ein- und ausparken.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://streamable.com/kgo1kp

**Comment by DrGrizzlY17** [comment]
Warum das Tuning nicht funktioniert, kann ich nicht sagen. Auf jedenfall sollte er demnächst nicht mehr die Folierung wechseln
