### ISSUE TITLE
Antrag für den bau einer Garage

### ISSUE THREAD

**Issue by SgtTukiTuki** [mexyn/statev_v2_issues#2056]
Sandy Folk
23.11.2021 um 9.09 Uhr

Es geht um das Gebäude:
Haushash: SandyShores17

Ich würde gerne eine Garage in diesem kaputten Wohnwagen einbauen lassen

![InkedSandyShores Garage_LI](https://user-images.githubusercontent.com/87803938/142989631-216f1105-aab6-487d-833a-aadfd72892bc.jpg)

und dann den Ausgang von der Seite bitte nach vorne Verlegen wenn möglich

![Ausgang](https://user-images.githubusercontent.com/87803938/142990167-a811b30f-ce85-4dbc-abcf-e6750caeda4d.png)

**Comment by DrGrizzlY17** [comment]
Grüße,
wir machen prinzipiell keine Umbauten von irgendwelchen Gebäuden. Daher ist der Garagenumbau abgelehnt. Außer ich hab das irgendwie falsch verstanden.

Wegen dem Eingang schaue ich mal

**Comment by SgtTukiTuki** [comment]
Das Gebäude hat keine Garage! Wäre es machbar dort eine hinzuzufügen? zwischen dem haus ansich und diesem wohnwagen ist quasi sowas wie nen Carport. Ich weiss nicht genau was ihr dafür braucht um Garagen zu setzen

**Comment by DrGrizzlY17** [comment]
Achso, ich gucke mal. Kann sein das es aber ohne Garage bleibt. Kriegst von mir dann nochmal Rückmeldung

**Comment by DrGrizzlY17** [comment]
Kannst du mir nochmal sagen wo der Ausgang hin soll?

Wegen der Garage, also das ist kein richtiges Carport.
Aber, am Trailer selber hinten sind Tore dran das auf eine Garage vermuten lässt. 
Können wir also umsetzen :)

**Comment by SgtTukiTuki** [comment]
Also Eingang siehst du ja auf dem Bild auf dem 2. und raus kommt man rechts daneben wo eine nebentür angedeutet ist und man steht ausserhalb des Grundstückes und muss immer wieder über den Zaun oder aussen rumlaufen
