### ISSUE TITLE
Gegenstände entfernen

### ISSUE THREAD

**Issue by WalDragoner3425** [mexyn/statev_v2_issues#2057]
Hallo,

wäre es möglich, die weißen Stühle, den weißen Tisch sowie die bleue Mülltonne im Zaun (siehe Bild) bei meinem Haus (Haushash "house_EastLS_15") zu entfernen? Die Gegenstände stehen nur im Weg, sind nicht nutzbar und fliegen bei der kleinsten Bewegung wild durch den Garten und stören nur. 

LG
William_Void

https://pic.statev.de/image/Mn3Cc

**Comment by DrGrizzlY17** [comment]
Lehne den Antrag ab.
Das Gelände bietet genug Platz um einen Ausweichplatz für platzierbare Objekte zu nutzen.

**Comment by WalDragoner3425** [comment]
Wäre es möglich, sich den Antrag nochmal anzusehen? Es geht mir nicht darum Platz für plazierbare Gegenstände zu schaffen, da gibt es wirklich mehr als genug Möglichkeiten, da stimme ich zu. Vielmehr geht es mir darum, dass wenn man sich hinten im Garten mit mehreren Leuten aufhält, dass die Stühle bei der kleinsten Berührung dann im Garten rumfliegen und einfach nur von den Leuten hin und her geschoben werden und bei jedem dann wo anders liegen. Das stört einfach nur und ist lästig.

**Comment by DrGrizzlY17** [comment]
Klar kann ich mir das nochmal anschauen, das Ergebnis bleibt aber das gleiche.
Wie gesagt, das Grundstück ist nicht gerade klein, also hat man für alles weitere ebenfalls Ausweichmöglichkeiten.

Das entfernen von Objekten kostet auch irgendwo ressourcen. Also geht meine Bitte einfach dahin, einfach vorsichtig zu sein wenn es dich stört, dann stößt man auch nichts um.
