### ISSUE TITLE
Paisley V2 in Fashion Killa nicht sichtbar.

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#2060]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Noah Reese

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.11.21

**Beobachtetes Verhalten**
[Maske] Gelbes Paisley Bandana V2
[Maske] Weißes Paisley Bandana V2
[Maske] Schwarzes Paisley Bandana V2
Werden im Fashion Killa nicht angezeigt.

**Erwartetes Verhalten**
Das man diese sieht

**Schritte um den Fehler nachvollziehen zu können**
Fashion Killa öffnen und schauen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by tastydev** [comment]
ganzen items sind auch deleted... hash gechanged/gelöscht worden?
