### ISSUE TITLE
Modded Frisur verbuggt

### ISSUE THREAD

**Issue by tristan1297** [mexyn/statev_v2_issues#2062]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Peter_Rumpe

**Auftrittszeitpunkt (Datum / Uhrzeit)**
direkt nach dem Update vom 26.11.2021

**Beobachtetes Verhalten**
die Modded Frisur vom Foto ist nicht mehr wie vorher

**Erwartetes Verhalten**
Frisur sollte wie vorher sein

**Optional: Video / Bilder des Fehlers**
![Screenshot_25](https://user-images.githubusercontent.com/87550844/143619579-293c6776-74f7-496e-8775-7b5fdde582ab.png)

**Comment by TheOutburst** [comment]
Das sieht bei dir sehr nach einem lokalen Ladeproblem aus, wir konnten das mit der Frisur (würde sagen das ist "Hipster) nicht reproduzieren.

**Comment by tristan1297** [comment]
die Frisur ist auch bei anderen verbuggt. Siehe hier https://clips.twitch.tv/SmoothFrigidRaisinKreygasm-VfJV_Anaau8--03J 

vielleicht hilft das ja :)

**Comment by tristan1297** [comment]
nun Abschließend Fixed! Wer ein ähnliches Problem hat, bitte in den Grafiksettings MSAA auf mindestens X2 stellen, das fixed den Fehler.
