### ISSUE TITLE
Abgabepunkt Kokain verbuggt

### ISSUE THREAD

**Issue by miischaa** [mexyn/statev_v2_issues#2066]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Heinrich_Iwanow

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.11.2021 ca. 20:30Uhr

**Beobachtetes Verhalten**
Der Marker ist in der Luft, man kann jedoch trotzdem ganz normal am Stromkasten abgeben.

**Erwartetes Verhalten**
 ...

**Schritte um den Fehler nachvollziehen zu können**
 Koksauftrag annehmen > Punkte abfahren

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
 

**Optional: Video / Bilder des Fehlers**
https://i.gyazo.com/34d1050c4d9f1ef23fe7e5675197eb00.jpg

**Comment by miischaa** [comment]
![image](https://user-images.githubusercontent.com/76888365/143626822-18697df7-0636-4da5-8e62-c04c74e9ab29.png)

Hier ist noch einer, den man garnicht abgeben kann, hab es aus sämtlichen Winkeln probiert. Auch wenn man E durchspammt oder ganz schnell E drückt und das Dialogfeld direkt schließt..

**Comment by BradleyDerKrasse** [comment]
Fixed next Update.
Weiteres bitte hier melden, falls vorhanden
