### ISSUE TITLE
Lederblouson

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#2067]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Ryan & Mila Valdes
**Auftrittszeitpunkt (Datum / Uhrzeit)**

20:30Uhr
**Beobachtetes Verhalten**

Alle Lederblouson werden nicht angeziegt weder im Fashionkilla noch nach dem Produzieren
**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by PlayInc89** [comment]
Die neuen Henry Bags sind auch noch nicht im FashionKilla verfügbar

**Comment by Enemyaa** [comment]
Next Update
