### ISSUE TITLE
Defibrillator und Teleport aus Ambulance fehlerhaft

### ISSUE THREAD

**Issue by Julian25081** [mexyn/statev_v2_issues#2068]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Julian Soerensen**

**26.11.2021 21:20 Uhr**

**Defibrillator und Trage bzw. Abladen des Patienten ins MD fehlerhaft**

**Der Defibrillator hätte die Person zum stehen bringen sollen; Am Abladepunkt hätte der Patient ins MD teleportiert wer**

**Perosn war bewusstlos. Wurde danach technisch Stabilisiert. Daraufhin wurde versucht zu defibrillieren (hochzuhelfen). Nach einem Versuch kam die Fehlermeldung "Die Person ist nicht bewusstlos". Trotz dessen lag sie noch am Boden. Interaktionen wie Geld geben haben nicht geholfen. PErson wurde auf die Trage gelegt und ins MD gebracht. Dort wurde am Abladepunkt in der Garage versucht, den Patienten oben ins MD bringen zu lassen. Dann kam allerdings die fehlermeldung "Im Rettungwasgen befindet sich kein Patient".  Nach game restart konnte er dann wieder herumlaufen.**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by milkdrops** [comment]
Konnte bisher nicht reproduziert werden, gibt es evtl. mehr Infos wie Todesursache, ob andere X-Menü Optionen probiert wurden etc.?

**Comment by n0rstar** [comment]
Patient wurde aus dem Wasser gezogen und im Feld abgelegt. Kollegin sah Ihn an einer anderen Stelle als ich. Patient konnte ebenfalls stabilisiert werden aber Defi ( Aufhelfen ) und Epinephrin Spritze ließen sich nicht anwenden. 
Problem mit der Trage gelöst. Der Patient lag bis zum Einladen verkrümmt auf der Trage und konnte danach aussteigen und sich normal bewegen

**Comment by Julian25081** [comment]
@BradleyDerKrasse , laut den Aussagen der Passanten war er wohl im Wasser bewusstlos geworden. (Bestätigen kann ich das nicht). Auch die Diagnose Funktion hat nichts ergeben. 
 Was ich vor Ort probiert habe:
          1. Defibrillieren
          2. Epinephrin verabreichen + Defibrillieren (Defi hat nicht funktioniert wegen Fehlermeldung s.o.)
          3. Den Passanten gefragt ob er alleine hochkommt (er war also in keiner Animation o.ä.)
          4. Geld zugesteckt um eine Animation zu forcen
     Weitere X-Menü Aktionen habe ich nicht ausprobiert
Danach auf die Trage.
Ich denke dass der Teleport nicht funktioniert hat weil er technisch nicht mehr Bewusstlos war (siehe thread https://github.com/mexyn/statev_v2_issues/issues/2074 )

**Comment by TamiGaming** [comment]
Hatte das gleiche Phänomen an Halloween mit Armstrong. 
Er ist glaube damals durch n Molotow Cocktail gestorben.
Er wurde jedoch relativ schnell durch nen Team Revive hoch geholt, weshalb sich das dann erledigt hatte.

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2438
