### ISSUE TITLE
Marktplatz Bug

### ISSUE THREAD

**Issue by ChapWinchester** [mexyn/statev_v2_issues#2069]
Habe am Marktplatz nähe Casino dieses Bug bekommen mit Meldung.

**BUG:**

> A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://reactjs.org/link/crossorigin-error for more information.
Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://reactjs.org/link/crossorigin-error for more information.
    at Object.invokeGuardedCallbackDev (http://resource/client/ui/index.js:5373:30)
    at invokeGuardedCallback (http://resource/client/ui/index.js:5399:41)
    at flushPassiveEffectsImpl (http://resource/client/ui/index.js:18488:19)
    at unstable_runWithPriority (http://resource/client/ui/index.js:2015:22)
    at runWithPriority$1 (http://resource/client/ui/index.js:10137:20)
    at flushPassiveEffects (http://resource/client/ui/index.js:18392:24)
    at http://resource/client/ui/index.js:18311:21
    at workLoop (http://resource/client/ui/index.js:1976:44)
    at flushWork (http://resource/client/ui/index.js:1955:24)
    at MessagePort.performWorkUntilDeadline (http://resource/client/ui/index.js:1781:37)

> 
![sfdffsd](https://user-images.githubusercontent.com/78925037/143655561-0ab1fef4-bcf7-4572-ac37-24ff63d3ce10.jpg)

**Comment by its4l3x** [comment]
alrdy fixed im nächsten update

**Comment by ChapWinchester** [comment]
Vielen dank für die schnelle Info

**Comment by Beartox** [comment]
Davis Markt genauso auch die gleiche Fehlermeldung habe es jedes Mal mehrfach getestet aber jedes Mal die gleiche Fehlermeldung

A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://reactjs.org/link/crossorigin-error for more information. Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://reactjs.org/link/crossorigin-error for more information. at Object.invokeGuardedCallbackDev (http://resource/client/ui/index.js:5373:30) at invokeGuardedCallback (http://resource/client/ui/index.js:5399:41) at flushPassiveEffectsImpl (http://resource/client/ui/index.js:18488:19) at unstable_runWithPriority (http://resource/client/ui/index.js:2015:22) at runWithPriority$1 (http://resource/client/ui/index.js:10137:20) at flushPassiveEffects (http://resource/client/ui/index.js:18392:24) at http://resource/client/ui/index.js:18311:21 at workLoop (http://resource/client/ui/index.js:1976:44) at flushWork (http://resource/client/ui/index.js:1955:24) at MessagePort.performWorkUntilDeadline (http://resource/client/ui/index.js:1781:37)

**Comment by Beartox** [comment]
**Richman Markt** 

![511245cc3fc8a91f525af6c3c9951baf](https://user-images.githubusercontent.com/79170045/143661830-9427be24-e940-496a-bbe2-6546ef5c4c4e.jpg)
