### ISSUE TITLE
StateV Farmingsimulator ? Weizen Menge !

### ISSUE THREAD

**Issue by Eskadiel** [mexyn/statev_v2_issues#2070]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Eskadiel Nightmare**

**27.11.21 13:41Uhr**

**Fund menge von Weizen beträgt trotz erhöhtem Aufwand/Zeit und Kosten"Diesel"/Fahrzeugpreis nur 1-6 Weizen,1 Pfirsich**

**Durch das Upgrade von Handarbeit auf Maschinelle Bearbeitung sollte die Menge der Farm punkte auf 10-15 Weizen mindestens gesteigert werden um das Gleichgewicht zu den anderen Feldern wie Tomate ,Gurke,Etc wieder herzustellen. Nicht nur Die Geschwindigkeit des abbauen "Anfahrtszeit an den Punkt,Aus/einsteigen", sondern auch die simple Hin und Rückfahrt zu den Feldern ist nun massiv im Nachteil gegenüber anderer Materialien. Desweiteren ist der Dieselverbrauch des Traktors deutlich zu Hoch was sich bei Dauerbenutzer auf den Preis vom Weizen zusätzlich auswirken würde, was dazu führt, das sämtlichen Lebensmittel die in irgendeiner Komponente Weizen enthalten im Preis unerschwinglich würden und nicht mehr gekauft würden.**

**Anfahrt von Paleto Bay mit Traktor und Achse auf das Weizenfeld in Grapesseed, Anfahren eines Punktes und Sammeln von Weizen. Stoppen der Benötigten Fahrzeit/Verbrauch und der Zeit vom Anfahren des Punktes bis wieder losfahren zum nächsten Punkt, Vergleich der Zeiten wie beim Sammeln von Salat,was manuell erfolgt und mit einem Burrito Angefahren werden kann**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**![rly](https://user-images.githubusercontent.com/92888219/143682562-34668780-566f-42c8-a8f3-b92666a3e8fe.jpg)**

**Comment by Eskadiel** [comment]
Ich stehe auch gerne für ein genaueres Gespräch für ein TS3-Termin zur Verfügung. MFG Eska

**Comment by glb11** [comment]
Das ist mir auch aufgefallen das da extrem wenig rauskommt.     Was mann vieleicht im gleichem Atemzug mit machen könnte  wäre das mann die einzelen Farmpunkte etwas weiter aus einander ziehen und üner das gesamte feld verteilen weil es sonst eng werden könnte wenn mal mehere Auf dem Feld sind

So ist es aktuell:  
![20211127210445_1 - Kopie_LI](https://user-images.githubusercontent.com/70204338/143721245-e321b2f7-f227-48c7-b611-0b948b98bc43.jpg)

So wäre ein vorschlag  was auch vom Rangieraufwand mit dem Tracktor pasen würde und auch sinn ergeben würde weil alle Punkte wenn an den Ballen oder im dichten BEstand angesiedelt sind
![20211127210445_1_LI](https://user-images.githubusercontent.com/70204338/143721282-bfbfb5ff-040c-40c4-a42f-67bdf3def96a.jpg)

Sind jeweils die aktuell auch anliegenden neu Punkte.

**Comment by Eskadiel** [comment]
Freu mich auf meine erste Tour mit den Traktor auf einem größeren Feld und die ersten 20 Weizen, die ich in den Hänger schmeißen kann. Bis dahin heißt es Traktor in die Garage und hoffen das der Weizenpreis und damit die Lebensmittel Kosten nicht in die unendliche geht. Manuelle Farm dauer für 350Kg "Burrito"= 1,2Std -1,5Std.  "Traktor"= 350Kg ca 3,5Std. Somit müsste für ein ausgleich des Weizenpreis von 0,8$-1,0$ auf ca 3$-3,5$ steigen um einen gleichwertigen Lohn wie beim restlichen Gemüse zu schaffen. Was allerdings Lebensmittel Absolut zu teuer machen würde. Desweiteren sollte über den Gebrauch vom Messer nochmal überdacht werden, da zu den Kosten für Messer wie bei allen anderen Feldern, nun auch noch die Treibstoffkosten dazukommen, wo weder bei Wasser/Öl/Sand ein Werkzeug notwendig ist. An der Stelle möchte ich nochmals erwähnen das mir die Traktor Idee wie vielen anderen auch sehr gut gefällt, sie aber so leider weder Spaß noch finanziellen Gleichwert zum restlichen Gemüse bringt. Wie bereits erwähnt steh ich auch gerne für ein Gesprächstermin zur Verfügung

**Comment by DonVitoDiangelo** [comment]
Wir haben das im Auge und werden nach internen Auswertungen auch ggf. Anpassungen vornehmen. Dazu gucken wir uns das aber noch etwas an, um auch ein statistisch aussagekräftiges Ergebnis zu erzielen. Es sind ja auch nicht immer nur 2 oder 3 Mann, sondern wir betrachten das ganze ja "global". Aber danke schon einmal für euer Feedback.

**Comment by Eskadiel** [comment]
Moin moin,

Es ist nun schon eine Weile her seit der Traktor notwendig ist und leider ist nach wie vor die Ausbeute 1-5 Weizen.
Ich war wieder mal zur Probe auf dem Weizenfeld unterwegs um zu schauen ob es einfach nur Pech ist oder die Ausbeute grundsätzlich nach wie vor ein Witz ist. Ich habe mich auch IC mit anderen Bauern unterhalten und auch dort leider vernichtende Aussagen erhalten, das die Ernte sehr Mager bis nicht vorhanden ausfällt. Ich war 30 minuten auf dem Feld,und habe folgende Ausbeute erhalten:
![30minuten farmen](https://user-images.githubusercontent.com/92888219/145451700-7e9bfd12-8ccf-49dd-9d83-8c885a2e9e92.jpg)

Hier nochmals die dringende Bitte um baldige Anpassung der Ausbeute auf min 10 -15 und max 25-30 Stk pro Punkt,
so das man wie zuvor in etwa 1,5 Std / 350KG erreicht.
MFG Eska

**Comment by glb11** [comment]
Moin    ich hatte es heute auch nochmal in Ruhe ausprobiert, mann bekommt ich ca 1h gerade einmal ca 150 Weizenballen vom Feld (Ausgelernt Farmer).[war auf dem oberen Feld (mit der Langen gerade, + zügiges Laufen zwischen den Punkten zum Tracktor]    Was in der Produktion gerade einmal 50 Packungen Mehl sind  und das ist fast gar nichts!!   

Ich hoffe auch auf eine Baldige Anpassung der Erträge Vorschläge wurden ja schon einige genannt (hier + im Forum)

**Comment by DonVitoDiangelo** [comment]
Wird sich sicher etwas erholen mit immer wärmer werdendem Wetter. :)
