### ISSUE TITLE
Rote Nase

### ISSUE THREAD

**Issue by Michi993** [mexyn/statev_v2_issues#2071]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Luke Hammer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.11.2021 - 14.50 Uhr

**Beobachtetes Verhalten**
Rätsel mit roter Nase kann nicht fortgeführt werden, Rote Nase ist vorhanden aber nicht möglich abzugeben.

**Erwartetes Verhalten**
rote Nase sollte eingetauscht werden können 

**Schritte um den Fehler nachvollziehen zu können**
k.p.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://ibb.co/RzQJMyH
https://ibb.co/K0wqSv5
https://ibb.co/xf73C0x

**Comment by DonVitoDiangelo** [comment]
Das Rätsel funktioniert auf jeden Fall, wenn dann fehlt dir noch irgendwas. :)

**Comment by Michi993** [comment]
okeee^^
