### ISSUE TITLE
Diagnosegerät Funktion defekt

### ISSUE THREAD

**Issue by Fabse96** [mexyn/statev_v2_issues#2072]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Fabio_Gonzales
**Auftrittszeitpunkt (Datum / Uhrzeit)**

27.11.2021 18:25 und 18:30
**Beobachtetes Verhalten**
-Vor Neustart ging das auslesen noch
-Beim auslesen mit dem Diagnose gerät freezt der char, man kann sich nicht mehr bewegen. Diagnosegerät Anzeige öffnet sich 
 auch nicht

**Erwartetes Verhalten**
-Fehler werden angezeigt und alle wie sonst

**Schritte um den Fehler nachvollziehen zu können**
-Diagnosegerät an einem Fahrzeug nutzen

**Comment by TheOutburst** [comment]
#2065
