### ISSUE TITLE
Diagnosegerät defekt

### ISSUE THREAD

**Issue by ShauniKT** [mexyn/statev_v2_issues#2073]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
 Alle Bennys Mitarbeiter (u.A. Tima Bunde, Klaus Kevin, Shauni Teller, Kev Floid, Liam Jamar)

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 Seit dem Winter Update (26.11.2021)

**Beobachtetes Verhalten**
 Das UI des Diagnosegerätes erscheint nicht bei Benutzung. Man hat zwar das Gerät in der Hand und der Akku wird verbraucht, aber man kann nichts machen. Auch Reloggen hat nichts geholfen.
Fall Shauni Teller: 1 mal hat es nach dem Update funktioniert, danach erschien zwar das Bild vom Gerät, allerdings stand nur Scanning (?) ohne diese wartepunkte und weiter nichts. Oder das Gerät erscheint einfach nicht als UI oben links.

Das Problem ähnelt dem Werkstatt Bug bei einigem, wo die Rechnung der Reparatur nach Erstellung nicht erscheint. Allerdings hilft wie gesagt ein Relogg hier nicht weiter. Denke der Prozess läuft irgendwo im Hintergrund weiter und sitzt dauerhaft fest.

**Erwartetes Verhalten**
 Dass das Gerät wie gestern funktioniert und die Fehler ausspuckt.

**Schritte um den Fehler nachvollziehen zu können**
 1x Diagnosegerät bei defektem Auto verwenden-> funktioniert.
ab dem 2. mal funktioniert es nicht mehr.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TheOutburst** [comment]
#2065
