### ISSUE TITLE
MD Teleporter (Patienten wird ins Bett teleportiert) fehlerhaft

### ISSUE THREAD

**Issue by WoahJeesus** [mexyn/statev_v2_issues#2074]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Jonny Parkinson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.11.2021 / 22:50 Uhr

**Beobachtetes Verhalten**
Wir können jetzt Personen die technisch nicht bewusstlos sind auf die Trage Packen. Laut Teleporter, befindet sich aber kein Patient im Fahrzeug.

**Erwartetes Verhalten**
Ab jetzt sollten auch Personen, die technisch NICHT bewusstlos sind, unseren Teleport nutzen können.

**Schritte um den Fehler nachvollziehen zu können**
1. 2 Spieler stellen sich in die MD Garage  
2. Eine Person lässt sich auf die Trage legen 
3. Person in den Krankenwagen einladen
4. Zum Teleporter fahren und als Fahrer E drücken 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2438
