### ISSUE TITLE
Über 300l Spritverbrauch in 1ner Sekunde

### ISSUE THREAD

**Issue by Reggi257** [mexyn/statev_v2_issues#2075]
## WICHTIGE INFORMATION!!:
```
Ist es gewollt das ein fahrzeug einfach so über 300 liter verliert wir reden hier nicht von wie es bei einen fehler ist das er ein enormen verbraucht hat und schnell leer wird sondern das von jetzt auf gleich der ganze tank leer war 
```

**Character Name Reggi Stone

**Auftrittszeitpunkt (Datum / Uhrzeit)**
eta 2 uhr auf dem weg nach paletto über Great Ocean Highway

**Beobachtetes Verhalten**
Es wurden von einer sekunde auf die andere über 300 liter aus dem tang gezogen und er war komplet leer 

**Erwartetes Verhalten**
Es hätte selbst bei einen fehler am auto der tank langsam leer gehen sollen klar schneller als gewöhnlich aber nicht von 1ner sekunde auf die andere über 300liter

**Schritte um den Fehler nachvollziehen zu können**
Ich bin einfach nur gefahren

**Comment by DrGrizzlY17** [comment]
Gabs über das Diagnosegerät ne Fehlermeldung am Fahrzeug?
Welches Fahrzeug war es?

**Comment by Reggi257** [comment]
mit dem diagnosegerät muss ich noch schauen und fahrzeug ist es ein pfahntom

**Comment by Reggi257** [comment]
Die fehler habe ich auch auslesen können es ist einmal xxxx, P0550,P00f,U029D,P115a das der wagen durch die fehler mehr sprit verbraucht stelle ich auch garnicht in frage aber was halt kommisch ist und nicht so ganz sinn ergibt das er von 1ner sekunde wo über 300 liter im tank sind auf die andere sekunde einfach 0 drin hat

**Comment by Hutstaender** [comment]
Ne, dass ist soweit alles korrekt.
