### ISSUE TITLE
Henny Bagback

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#2076]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Ryan_Valdes
**Auftrittszeitpunkt (Datum / Uhrzeit)**

28.11.2021 05:00Uhr
**Beobachtetes Verhalten**

Die Rucksäcke sind nicht im Fashion Killa vorhanden. Genau so können sie nicht aus dem Laden gekauft werden da sie auch da nicht angezeigt werden.
**Erwartetes Verhalten**

Sollte im Fashion Killa angezeigt werden. Sowie im Laden zur kaufauswahl stehen !

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TheBroady** [comment]
Zusatz:
![image](https://user-images.githubusercontent.com/70150887/143781884-bb6b589e-9611-41db-b0eb-c885881ff8f3.png)
Icon im Inventar ist auch bruch

**Comment by CubeXLIVE** [comment]
Rucksäcke können im Laden ver-/gekauft werden, allerdings ist das Icon immer noch verbuggt
