### ISSUE TITLE
Hotelzahlungen fehlen

### ISSUE THREAD

**Issue by VerenaBelters** [mexyn/statev_v2_issues#2077]
Character Name Verena Belters

Auftrittszeitpunkt (Datum / Uhrzeit) 27.11.2021 14:00 - 01:00 Uhr ca

Beobachtetes Verhalten: Anzeige beim Hotel stimmt nicht, wann die letzte Zahlung war. Die Zahlungen sind jedoch wie gewohnt von meinem Konto angegangen.

Erwartetes Verhalten: Die letzte Zahlung wird angezeigt

Leider kann ich nicht nachvollziehen, ob es bei anderen Bewohnern auch passiert ist.

Optional: Video / Bilder des Fehlers
![Unbenannts](https://user-images.githubusercontent.com/75080037/143767671-261f5eed-565e-4598-8ad8-7f145fd7f039.JPG)
![Unbenanntss](https://user-images.githubusercontent.com/75080037/143767672-5eeab4d5-f3f5-41c4-8ec9-d5f8dcd048fd.JPG)

**Comment by JohnRappStateV** [comment]
Das gleiche ist beim Dream View Hotel in Paleto. 

![image](https://user-images.githubusercontent.com/93606498/143767852-3c727e6b-0947-4b21-a308-3b5fa8ebee06.png)

**Comment by TheOutburst** [comment]
Wir werden uns sämtliche Hotelbugs mit StateNET 2.0 annehmen #942
