### ISSUE TITLE
Lagerbestand StateNet/Inventar ungleich

### ISSUE THREAD

**Issue by VictorCorticera** [mexyn/statev_v2_issues#2079]
Gustavo Luciano

28.11.2021 - ca. 18 Uhr

Wenn man in die Werkstatt geht und dort das Lager öffnet wird eine maximale Kapazität von **20.000** angezeigt und in unserem Fall ca. **4.800** belegt. Im StateNet jedoch wird dann ca. **6.500** von **15.000** angezeigt
Also nochmal der Vergleich:
Inventar: 4800/20000
StateNet: 6500/15000

--> Es wurde bisher noch nicht in anderen Firmen geprüft

Gleiche Anzeige der maximalen und der belegten Lagerkapazität im StateNet und im Inventar

Werkstatt mit dem Hash carWorkshop3 --> Lageranzeige im StateNet --> Lageranzeige im Inventar

https://pic.statev.de/image/M5yhI
https://pic.statev.de/image/M5gcm

**Comment by Hutstaender** [comment]
Da fehlte nur ein State-Net Update. Die Reifengewichte wurden angepasst und waren im State-Net nicht aktuell
