### ISSUE TITLE
Postleitzahlen Duplikat

### ISSUE THREAD

**Issue by RIT-FR** [mexyn/statev_v2_issues#2080]
Unter anderem existiert die Postleitzahl "5151" doppelt. Andere sind mir soweit noch nicht aufgefallen.

![Screenshot_8](https://user-images.githubusercontent.com/77400784/143840578-376094ea-681d-4a71-87c1-12a06a9805f7.png)

**Comment by Chrinis007** [comment]
Wird so bleiben ist eine externe source. 
kann dementsprechend closed werden
#867

**Comment by DonVitoDiangelo** [comment]
So ist es :)
