### ISSUE TITLE
Wechseln zwischen Animationsfavoriten nicht möglich mit Mausrad

### ISSUE THREAD

**Issue by HarzadousElexir** [mexyn/statev_v2_issues#2081]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Luca Disanta

Luca Disanta
**Auftrittszeitpunkt (Datum / Uhrzeit)**

29.11.2021 12:48
**Beobachtetes Verhalten**

Ich kann nicht zwischen den Animationsmenüs mit dem Mausrad hin und her wechseln. z.b: ich stehe vor einer Peron und möchte anstatt ihr etwas zu geben etc. die Arme verschränken. Ebenso ist es nicht möglich im tablet mit dem Mausrad zu scrollen. (Waffen wechseln / Radiosender umschalten IC Funktioniert aber mit dem Maurad. Das bedeutet meine Maus hat keinen Fehler. Dieser Fehler mit dem wechseln der Animationen besteht schon seit dem ich eingereist bin. ( Habe es bisher immer mit der Taste < gemacht) Der Fehler mit scrollen Im Tablet ging einige zeit danach nicht mehr.
**Erwartetes Verhalten**

Scrollen zwischen Animationen und im tablet mittles Maurad und nicht mit der Taste <
**Schritte um den Fehler nachvollziehen zu können**

"X" drücken und scrollen mit dem Mausrad. 
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Auf was steht dein Mausinput in den GTA Settings? Also mal in GTA die Optionen öffnen und in der Steuerung mal nach dem Mouse Input schauen

**Comment by HarzadousElexir** [comment]
Da steht Raw Input :)

**Comment by Hutstaender** [comment]
Das Tablet Scroll Problem liegt an altv. Hier macht das CEF Probleme, da können wir nur abwarten. 

Und was dein Animations-Scroll-Problem betrifft, vermute ich den Fehler eher auf deinem Rechner. Da gibt es verschiedene Möglichkeiten. Z.B. geänderte GTA Steuerung, wierdes Treiber-Verhalten oder Antivierenprogramme die mal wieder übermotiviert sind.
