### ISSUE TITLE
Heroinablage fehlerhaft

### ISSUE THREAD

**Issue by fossi13779** [mexyn/statev_v2_issues#2082]
in sandy shores geht der Punkt zur Heroinablage am Werbe Schild nicht
![Unbenannt1](https://user-images.githubusercontent.com/90260064/144055730-ac807803-0024-4ce5-8ecc-e9d8b441edb3.jpg)

**Comment by Chrinis007** [comment]
Danke für den Spoiler

**Comment by TheOutburst** [comment]
@fossi13779 was genau geht bei dem Marker nicht? Gab es eine Fehlermeldung oä? (genau dafür haben wir btw die Vorlage)

**Comment by fossi13779** [comment]
Es gibt keine Fehlermeldung der Maker funktioniert einfach nicht ich kann dort nicht mit dem Punkt interagieren ( drücken von der Taste E. Ich tippe mal das die höhen Koordinaten nicht stimmen oder zu klein sind. bei 859 im Trailer park Stab City gibt es auch einen ablagepunkt am Briefkasten hier kann man mit dem Punkt auch nicht interagieren. Auch hier kommt keine Fehlermeldung
