### ISSUE TITLE
Kofferraum öffnen Kamacho

### ISSUE THREAD

**Issue by Cro20** [mexyn/statev_v2_issues#2090]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

01.12.2021/ 22:00

**Beobachtetes Verhalten**

Nach öffnen des Kofferraum über Inventar EGAL von welcher Seite, KEIN ZUGRIFF auf den Kofferraum

**Erwartetes Verhalten**

Kofferraum Öffnen I Inventar öffnen und sachen ins Auto packen

**Schritte um den Fehler nachvollziehen zu können**

Kofferraum öffnen und I Inventar drücken und sachen rein packen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Dean-Gallagher** [comment]
einmal einparken und wieder ausparken sollte es fixen

**Comment by Hutstaender** [comment]
Kann sein, dass sich da der Defect-Status überschlagen hat. Wie Dean bereits sagte, einfach ein und ausparken und alles is tutti
