### ISSUE TITLE
Trailer bugt wieder zurück an den Ausgangspunkt

### ISSUE THREAD

**Issue by powerswissi** [mexyn/statev_v2_issues#2093]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Roger Thickle

**Auftrittszeitpunkt (Datum / Uhrzeit)**

2.12.2021 ca 8 Uhr 15

**Beobachtetes Verhalten**

Den ÖLAUFLIEGER ausgeparkt an der Casino Garage und angehängt. Danach ca 300m gefahren und der Auflieger hat sich zurück an den Ausgangspunkt gestellt. 
Erneut zurück gefahren und angehängt. Bis zum jetzigen Zeitpunkt bleibt dieser am Fahrzeug!
**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

LKW ausparken -> Auflieger anhängen -> Los fahren 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by SHaagmann** [comment]
Duplikat #2086

**Comment by Cashiflux** [comment]
Hoffe das ist hier richtig, kann ich so bestätigen, Passiert mir auch dauernd mit dem Dock Trailer (1350kg). Genau wie Swissi es beschrieben hat. 

Immer nach dem Ausparken setzt er sich einmal zurück, danach bleibt er problemlos am Fahrzeug. Parkt man ihn wieder ein, das selbe spiel von vorne. Anzumerken ist, einige sagen ich haben den Trailer noch am Fahrzeug andere wiederum sehen gar keinen mehr. Für mich steht er immer an der Garage dann. 

kann so auch immer und immer wieder reproduziert werden.

**Comment by Xymena** [comment]
Character Name

Anna_Luna

Auftrittszeitpunkt (Datum / Uhrzeit)

02.12.2021  zwischen 14 und 15 uhr 

Beobachtetes Verhalten

Beim Ausparken der Large Trailerachse wird sie immer wieder zum Ausladepunkt zurück geportet, nachdem man sich von ihr entfernt hat oder das Spiel neugestartet hat.

Schritte um den Fehler nachvollziehen zu können

LKW ausgeparkt -> Achse dran -> etwas gefahren 
Zugriff auf den hänger nicht mehr möglich
Einparken nicht möglich 

Monitorauflösung (nur wenn Falsche Darstellung in der UI)

Optional: Video / Bilder des Fehlers

https://youtu.be/xZ9lWIKjpGA

**Comment by RobMccoy** [comment]
Charaktername
Rob Mccoy

Auftrittsdatum:
02.12.2021  14.35Uhr und 15.15Uhr

Beobachtetes Verhalten:
Nach dem Ausparken von phantom und large-achse zur firma gefahren zum beladen,dort wird Achse aber nicht gefunden obwohl sie auf dem beladepunkt steht,gps-ortung zeigt noch den standpunkt vor der garage an. Nach einem relogg wird die Achse wieder korrekt am garageausparkpunkt angezeigt,beim ankoppeln und wegziehen aber das gleiche Problem wie vorher.

Edit:die achse erstmal vom support einparken lassen weil selbst das ging nicht ingame und die achse blockierte die garage für andere spieler

**Comment by SatyriaDine** [comment]
Charaktername: 
Sofia_Black / Ogi_Black

Auftrittsdatum:
02.12.2021 ca 17Uhr

Beobachtetes Verhalten:
Packer samt Ölauflieger stand ausgeparkt am Straßenrand. Wollten beides zusammen umparken und in eine Gasse stellen. Plötzlich kamen unstimmigkeiten auf wo der Auflieger nun steht. Ogi_Black konnte den Auflieger nicht sehen. Sofia_Black konnte ihn sehen aber nicht interagieren.  Das Problem löste sich durch kurzes "ins haus gehen". Einparken des Packer-Auflieger Gespanns funktioniert auch nicht. Der Auflieger bleibt draußen stehen.
Daraufhin Auflieger mit zum Glück vorher ausgeparkten Phantom weggezogen, daraufhin wieder Sync probleme. Auflieger stand bei Ogi_Black plötzlich in besagter Gasse, bei Sofia_Black hing er am Phantom.
Auflieger vom Phantom abgekoppelt. Auflieger in Gasse an Packer gekoppelt. Auflieger für beide am Packer sichtbar und nutzbar.

Kurze Zeit später: Ausparken eines Trailer Logs Aufliegers. Auflieger an Packer dran. Ausparken weiterer Fahrzeuge in Grapeseed nicht möglich da Ausfahrt blockiert. Kurz ins Haus rein und wieder raus, Auflieger steht wieder am Ausparkpunkt. Wieder angekoppelt, Garage nicht mehr blockiert.

**Comment by TheOutburst** [comment]
#2116
