### ISSUE TITLE
Piercing buggt durch Kleidung

### ISSUE THREAD

**Issue by nox142** [mexyn/statev_v2_issues#2094]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Beobachtetes Verhalten**
Bei den neuen Kleidern (XOXO) von den Frauen buggt das Bauchnabelpiercing durch die Kleidung

**Erwartetes Verhalten**
Kein Durchbuggen

Lösungsvorschlag:
Einen Button zum Ein- und Ausschalten des Piercings, so wie man bei Mützen die Haare ändern kann oder halt Jacken auf und zu machen kann

**Comment by TheMoonicorn** [comment]
Das Piercing buggt bei jedem eng anliegendem Oberteil rum, leider nur umgehbar bisher mit der High Waist Jeans

**Comment by CatherineGallagher** [comment]
Wurde damals schon erwähnt

https://github.com/mexyn/statev_v2_issues/issues/1824

**Comment by Hutstaender** [comment]
Leider zu viel Aufwand für ein so winziges Detail
