### ISSUE TITLE
Haarfarbenwechsel beim Frisör für Beistehende nicht sichtbar

### ISSUE THREAD

**Issue by EinzJackiez** [mexyn/statev_v2_issues#2095]
**Charaktername:**

Ava White

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17:36 am 02.12.2021

**Beobachtetes Verhalten**
Wenn man bei einem Frisör die Farben durchgeht sieht nur die Person, dessen Frisur gerade gemacht wird, die wechselnden Farben aber sonst niemand.

**Erwartetes Verhalten**
Jede Person sollte die wechselnden Farben sehen.

**Schritte um den Fehler nachvollziehen zu können**
 Beim Frisör eingestellt sein > bei einer Person die Haarefarben durchgehen

 **Video / Bilder des Fehlers**
 
 https://www.youtube.com/watch?v=4XFEryI1TJU

**Comment by Saaria83** [comment]
Bei UniCut das gleiche grade. Der Kunde selbst sieht die Farbveränderung, wir als Friseur aber nicht. Zugleich sieht man auch nicht die verschiedenen Bärte. Der Kunde wiederum schon.

**Comment by Saaria83** [comment]
Grade auch bei der Schererei getestet und da ist es das gleiche

**Comment by StateV2Marie** [comment]
Bei O Sheas Barber Shop is ebenfals das gleiche problem leider.

**Comment by CubeXLIVE** [comment]
Geht im allgemeinen nicht. Selbst der Friseur sieht es nicht. Frisur ja, Farbe oder Makeup oder sonst was, das geändert wird, sieht man nicht

**Comment by CubeXLIVE** [comment]
Nach einmal Haare schneiden bei einer Person, hab ich danach bei der nächsten allerdings die Frisurenvorlage wieder gesehen. Ganz kurios

**Comment by Enemyaa** [comment]
Duplikat #2110
