### ISSUE TITLE
Trailer bugt  zurück an den Ausgangspunkt

### ISSUE THREAD

**Issue by Dieselfloh** [mexyn/statev_v2_issues#2096]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Flo Strauss

Flo Strauss
**Auftrittszeitpunkt (Datum / Uhrzeit)**
2.12.21 ca. 17Uhr 19uhr

**Beobachtetes Verhalten**
Den ÖLAUFLIEGER ausgeparkt an dem Elektrizitätswerk und angehängt. Nach ca. 500m ist der Auflieger zurück an den Ausparkpunkt gestellt worden.

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**
LKW ausparken -> Auflieger anhängen -> Los fahren

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

https://user-images.githubusercontent.com/95440240/144485012-7c922bb3-8287-4350-8459-cf02f38d99ba.mp4

**Optional: Video / Bilder des Fehlers**

**Comment by Dieselfloh** [comment]
Auch zusehen im meinem Stream vom 02.12.21 bei 2:39:30-2.45:00

**Comment by TheOutburst** [comment]
Danke für das Video, aber den Bug haben wir schon
#2093
