### ISSUE TITLE
Werkstatt -> Fahrzeuge posi bei selbstparken wieder rip

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#2097]
**Character Name**
Horizon Hottest Cars

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Fahrzeuge mit E selbst ein/aus parken und Fahrzeuge landen auf seite/dach kreuz und quer

**Erwartetes Verhalten**
kein veh spinning mehr 

wenn vid gebraucht wird bescheid sagen

**Comment by TeubyDE** [comment]
Sollte sich mit dem letzten Update verbessert haben.
