### ISSUE TITLE
Handelskammerausweis - Textfelder nicht groß genug

### ISSUE THREAD

**Issue by ProgrammingFox** [mexyn/statev_v2_issues#21]
**Zeitpunkt (Datum / Uhrzeit)**

25.08.2020 um 19:30 Uhr
**Beobachtetes Verhalten**

Das Textfeld für den Rang ist zu klein, außerdem steht das aktuelle Datum auf dem Ausweis.
**Erwartetes Verhalten**

Der Rang sollte in eine Zeile passen und es sollte kein Datum vorhanden sein.
**Schritte um den Fehler nachvollziehen zu können**

Handelskammermitarbeiter sein und den Ausweis rausholen.
**Optional: Video / Bilder des Fehlers**

![grafik](https://user-images.githubusercontent.com/48456305/91207853-b411aa80-e709-11ea-9f43-7d6f674e242e.png)

**Comment by r3sist3nt** [comment]
nach restart fixed.
