### ISSUE TITLE
Charaktererstellung

### ISSUE THREAD

**Issue by Enemyaa** [mexyn/statev_v2_issues#210]
**In der Charaktererstellung kann man sich keine Hosen aussuchen, da die Health Bar (rechts) genau auf dem Pfeil nach rechts liegt und eine Auswahl mit dem linken Pfeil gar nicht möglich ist.**

**Erwartetes Verhalten:**
Keine Health Bar in der Charaktererstellung oder die Möglichkeit auch mit dem linken Pfeil die Auswahl zu durchsuchen.

https://prnt.sc/vbcrs9

**Comment by r3sist3nt** [comment]
Fixed
