### ISSUE TITLE
Bandana Bug wie früher

### ISSUE THREAD

**Issue by CubeXLIVE** [mexyn/statev_v2_issues#2101]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Patrick_Nowak

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.12.2021

**Beobachtetes Verhalten**
Gesicht buggt durch Bandana

**Erwartetes Verhalten**
Gesicht passt sich dem Bandana an

**Schritte um den Fehler nachvollziehen zu können**
Gewisse Charaktermodels + Bandana

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/d3df0c0ecf6bca8ec16986a307ee0701

**Comment by SHaagmann** [comment]
Der Bug war bei mir nie weg (Sven Rosenbach)

**Comment by Hutstaender** [comment]
#1924 duplicate
