### ISSUE TITLE
Winterunterbekleidung Damen

### ISSUE THREAD

**Issue by JaquelineBouvier** [mexyn/statev_v2_issues#2102]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Jaqueline_Bouvier

03.12.2021

**Beobachtetes Verhalten**
Die Winterunterbekleidung lässt keine Langen Arme zu bezogen auf den Schwarzen Hoodie [F][U]

**Erwartetes Verhalten**
Lange arme sollten einstellbar sein in den dafür Charakterbekleidungsoptionen

**Schritte um den Fehler nachvollziehen zu können**
Schwarze Kutte kaufen und für Darunter den Schwarzen Hoodie für Weibliche Charaktäre. Lange Arme lassen sich nicht anpassen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Enemyaa** [comment]
Es gibt keine langarm Hoodie Version für Frauen unter den Westen.
