### ISSUE TITLE
Flatbed - geladenes Fahrzeug verschwindet bei Abladen in Werkstatt

### ISSUE THREAD

**Issue by GusTaylor** [mexyn/statev_v2_issues#2104]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Gus Taylor

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.12.21 - 10:48 Uhr

**Beobachtetes Verhalten**
Fahrzeug verschwindet beim Abladen (lt. Info Support y-Koordinate >2000)

**Erwartetes Verhalten**
Fahrzeug wird normal Abgeladen

**Optional: Video / Bilder des Fehlers**
https://streamable.com/3i60lf

**Comment by Hutstaender** [comment]
tritt das noch auf?
