### ISSUE TITLE
Nutzung vom Tisch im Haus Haussystem Grösse 2  High Class Apartment Brown

### ISSUE THREAD

**Issue by Annabelle-Smith** [mexyn/statev_v2_issues#2105]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Annabelle Smith**

Annabelle Smith

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer zuhause

**Beobachtetes Verhalten**

Mann kann den Tisch im Haus nicht nutzen mit Y 
kann sich da nicht hinsetzen

**Erwartetes Verhalten**

das ich mich zu hause auch an den tisch setzen kann mit meinem besuch wie bei der Einrichtung High Class Apartment (Bordaux)

**Schritte um den Fehler nachvollziehen zu können**

Ein Haus umbauen lassen bei haussystem grösse 2 
hight class apartment (brown)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
<!--- Falls du ein Video oder Bild vom Fehler gemacht hast, dann kannst du diesen hier einfügen. Dies geht ganz einfach per Drag & Drop --

![Tisch stühle Tressen stühle](https://user-images.githubusercontent.com/74880091/144750355-52e43480-d512-4a22-8c6e-c233ac46e361.png)

https://prnt.sc/21uvjv6

**Comment by TheOutburst** [comment]
mit dem neuen aufstehsystem konnten wir es endlich realisieren, frohe Dinnerpartys!
