### ISSUE TITLE
Fahrstuhl am Hotel

### ISSUE THREAD

**Issue by ChapWinchester** [mexyn/statev_v2_issues#2106]
Han_Namikaze

**Auftrittszeitpunkt (Datum / Uhrzeit)**
-

**Beobachtetes Verhalten**
Bitte um ein Fahrstuhl am Hotel an der [ Dorset Drive 23 - Firmenhash | RockfordHills_Flat_6 ]

**Erwartetes Verhalten**
An der Eingangsseite ist ein Balkon wo man drauf kann und direkt links auch.
An der eingangs Seite wäre ein Balkon recht schön zu nutzen
(Vielleicht kann man ja beide begehen da am Hinterseite des Hotels auch ein Tür ist den man dafür nutzen könnte. )
[https://ibb.co/yQqMsdJ](url)

**Schritte um den Fehler nachvollziehen zu können**
Hier ein Foto von der Map.
Ort: Dorset Drive 23
Hash | RockfordHills_Flat_6 
[https://ibb.co/LhfDWfZ](url)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
-

**Optional: Video / Bilder des Fehlers**
![ic balkone](https://user-images.githubusercontent.com/78925037/144759841-f8b28fb9-3a95-4566-a30d-69150177df18.jpg)
![eingang](https://user-images.githubusercontent.com/78925037/144758747-e62d430d-7dfc-462d-a8b4-efc17c983a6a.jpg)
![map](https://user-images.githubusercontent.com/78925037/144758748-125f470d-38c6-455b-8c05-0bbb953fad62.jpg)

**Comment by DrGrizzlY17** [comment]
Einen hab ich dir hinzugefügt :)

**Comment by ChapWinchester** [comment]
Vielen dank @DrGrizzlY17 freut mich :)

**Comment by ChapWinchester** [comment]
> Einen hab ich dir hinzugefügt :)

Hey Dan, will nicht aufdringlich sein aber wann darf man das Balkon begehen? :) *HYPED*

**Comment by DrGrizzlY17** [comment]
Sollte mittlerweile live sein :)

**Comment by ChapWinchester** [comment]
Hallo nochmal, wollte mal ein Info abholen wie das mit dem Fahrstuhl im Moment ist. Gruß Chap
