### ISSUE TITLE
Unterbodenbeleuchtug nicht sichtbar

### ISSUE THREAD

**Issue by Pitsch83** [mexyn/statev_v2_issues#2108]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Peder Lundberg

**Auftrittszeitpunkt (Datum / Uhrzeit)**
04.12.2021 - ca. 23 Uhr

**Beobachtetes Verhalten**
Ich habe mir gestern eine Unterbodenbeleuchtung einbauen lassen. Wenn ich diese nach erfolgreichem Einbau nun einschlaten möchte ist kein licht zu sehen. Es wird aber Angezeigt "Unterbodenbeleuchtung Eingeschlatet"

**Erwartetes Verhalten**
Das Licht sollte zu sehen sein

**Schritte um den Fehler nachvollziehen zu können**
In dsa Fahrzeug setzen und die Unterbodenbeleuchtung Einschalten

**Comment by TeubyDE** [comment]
Ist das nur bei diesem einen Fahrzeug der Fall?
Oder betrifft es ggf. mehrere Fahrzeuge?

**Comment by Pitsch83** [comment]
Also bei mir tritt ist das nur an diesem Fahrzeug ist auch das einzige wo ich Unterbodenbeleuchtung drann habe!

**Comment by SHaagmann** [comment]
Um welches Fahrzeug handelt es sich denn nicht alle unterstützen Unterboden

**Comment by Pitsch83** [comment]
Ein Vapid Taxi wie gesagt eingebeut ist sie und angezeigt das sie an ist wird es auch nur leider ist nichts zu sehen!

**Comment by SHaagmann** [comment]
Das Vapid Taxi unterstützt keine Unterbodenbeleutung von GTA aus kann also geclosed werden
