### ISSUE TITLE
Nike Schuhe lassen schweben

### ISSUE THREAD

**Issue by SheoBam** [mexyn/statev_v2_issues#2109]
**Character Name**
Sarah Sommerfeldt

**Auftrittszeitpunkt (Datum / Uhrzeit)**
24/7

**Beobachtetes Verhalten**
Mit den F Weiße Nike Air Jordan bin ich für andere immer höher und schwebe in der Luft. Es ist so, als hätte mein Charakter Heels an. Jedoch ist der Bug nur für andere zu sehen. Ich hingegen stehe ganz normal auf dem Boden. 

Der Gleiche Bug trat hier schon einmal auf: https://github.com/mexyn/statev_v2_issues/issues/1617

**Erwartetes Verhalten**
man ist normal groß

**Schritte um den Fehler nachvollziehen zu können**
nicht bekannt

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![IMG-20211123-WA0000](https://user-images.githubusercontent.com/95241865/144762486-10a9b6a4-9d18-433b-9487-5c37d7bceb62.jpg)
![IMG-20211123-WA0002](https://user-images.githubusercontent.com/95241865/144762489-3bede2de-67be-476f-9f4e-0520d0abafbd.jpg)

**Comment by Enemyaa** [comment]
Das ist bei 1-2 weiteren weiblichen Charakteren auch und bei allen anderen aber gar nicht, deswegen können wir da gar nichts groß machen, denn eigentlich funktioniert es so wie es soll. 

Vielleicht löst eine bestimmte Animation das aus?!
