### ISSUE TITLE
Neue Objekte auf altV blockieren alle Parkmöglichkeiten vor Werkstatt

### ISSUE THREAD

**Issue by callmerusty** [mexyn/statev_v2_issues#211]
RageMP: https://i.imgur.com/9s1NEqp.png
altV: https://i.imgur.com/PxUUhmH.jpg

GTA online: https://i.imgur.com/22OQQws.png

Werkstatt: carWorkshop9

**Comment by DrGrizzlY17** [comment]
Durch alt:V sind nur viel mehr Objekte Teil der Map... In diesem Fall stören sie nicht. In der Gegend gibt es genug Parkmöglichkeiten. Bitte beachte zudem, das nicht unnötig Fahrzeuge rum stehen, die gar nicht gebraucht werden.
