### ISSUE TITLE
Frisuren und Bärte auf State

### ISSUE THREAD

**Issue by StateV2Marie** [mexyn/statev_v2_issues#2110]
Hallo wie ihr vll schon nen post bekommen habt wisst ihr das aktuell die Frisur Maschinen nich gehen weder kann man Haare Färben noch kann man Bärte zurecht schneiden ohne den kunden zu bitten zu helfen...
Traurig is wie willst das erklären dann kommen so sprüche wie ihr seid nich kompitent genug ihr taugt nix geh wo anders hin das is kunden verlust den man nich brauchen kann... ich weiß ihr seid vll schon dran den fehler zu beheben aber so nen kleines feedback wie es läuft ob mans beheben kann oder worans liegt wäre schön. zu hören. ihr habt immer viel arbeit und das wissen wir aber mehr wie sagen durch den winter sind die spiegel zu doll beschlagen und sie müssen uns bei der Frisur helfen können wir nich und das geht nun schon mehrere wochen leider. Gibt es vll ne möglichkeit den fehler zu beheben wenn ja wäre es lieb wenn ihr uns nen kleines feedback geben könntet das wir Frisure bald wieder hoffen können das die Maschinen wieder richtig laufen. Danke.
mfg: Marie P.

**Comment by StateV2Marie** [comment]
PS. im übrigen die 2 letzten neuen frisuren kann man nich färben was die kunden leider traurig macht.

**Comment by Enemyaa** [comment]
@StateV2Marie es ist halt auch RP und selbst wenn die sich einen besseren Friseur suchen wollen und dich dumm anmachen, dann werden sie ja auch bei den anderen Friseursalons keinen Erfolg haben.  ;-)

**Comment by StateV2Marie** [comment]
ja da geb ich dir recht das sehe ich auch so aber gleich dann mit dem tot drohen geht meiner meinung nach bissel zu weit sorry
