### ISSUE TITLE
"glitch through floors" kommt weiterhin vor

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#2112]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
09.12.2021 20:40

**Beobachtetes Verhalten**
Es kommt weiterhin, ( wenn auch seltener? ) vor , dass Personen durch Ebenen durchglitchen. (#970 wurde mit dem letzten AltV update geclosed)

**Optional: Video / Bilder des Fehlers**

https://youtu.be/1RRNO75MVWU

**Comment by TheOutburst** [comment]
#2116
