### ISSUE TITLE
Fehlerhafte Preisberechnung an Tankstelle

### ISSUE THREAD

**Issue by JonnyHart** [mexyn/statev_v2_issues#2114]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Jonny_Hart

**Auftrittszeitpunkt (Datum / Uhrzeit)**
10.12.2021 ca 22:30 Uhr

**Beobachtetes Verhalten**
Diesel Preis 0,99$ und trotzdem Preis höher als Literzahl siehe Screen. 

**Erwartetes Verhalten**
Richtige Preisberechnung

**Schritte um den Fehler nachvollziehen zu können**
Auto tanken

**Optional: Video / Bilder des Fehlers**
![Uploading ABAB3118-ACB1-41D5-83D7-8A919F0E599F.jpeg…]()

**Comment by DrGrizzlY17** [comment]
Bitte den Screenshot erneut hochladen. Ist Fehlerhaft. Danke

**Comment by JonnyHart** [comment]
![image](https://user-images.githubusercontent.com/78865364/145723887-79cd0a6c-90d3-4658-95b5-d5608ac7c240.jpeg)

**Comment by Hutstaender** [comment]
Die Berechnung ist korrekt, das ist nur ein Anzeigefehler.
Du hast 128 Liter zu 126.72$ getankt

**Comment by MrHaix** [comment]
Hey, ich konnte den Fehler leider nicht reproduzieren. Ist noch bekannt mit welchem Fahrzeug und an welcher Tankstelle getankt wurde?

**Comment by JonnyHart** [comment]
Pounder an der Tanke bei U-Group 24/7

**Comment by MrHaix** [comment]
Auch in dem Zusammenhang bekomme ich den Fehler nicht reproduziert. Bitte erneut versuchen. Sollte der Fehler wieder auftauchen im besten Fall mit Video oder weiteren Infos nochmal hier melden.
