### ISSUE TITLE
Fahrzeuge verändern trotz schieben die Position nicht

### ISSUE THREAD

**Issue by Mondmadchen** [mexyn/statev_v2_issues#2115]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Jenny_Hohengarten

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11.12.2021, 14:25 Uhr

**Beobachtetes Verhalten**
Bei dem Versuch ein Fahrzeug zu schieben bewegte es sich bei mir nicht, bei dem Kollegen allem Anschein nach schon. Das Fahrzeug veränderte nach Beendigung des Schiebevorgangs nicht die Position und blieb unverändert auf der Straße stehen.

**Erwartetes Verhalten**
Das Fahrzeug bewegt sich bei allen anwesenden Personen und ist auf der neuen Position zu sehen.

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug schieben lassen

**Optional: Video / Bilder des Fehlers**
https://youtu.be/RiD1IBJrlQQ

**Comment by TheOutburst** [comment]
#2116
