### ISSUE TITLE
MD kann einen nicht durch "Olga" hochbringen wenn man nicht bewusstlos war

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#2117]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Sven Rosenbach
**Auftrittszeitpunkt (Datum / Uhrzeit)**

10.12 gegen 23 Uhr
**Beobachtetes Verhalten**

Nachdem man von den Medics ohne bewusstlos gewesen zu sein in ein Fahrzeug gebracht wurde kann man nicht hochgeportet werden
Außerdem kann man als Person Selber aussteigen und sich auch anschnallen, was normalerweise nicht möglich ist
**Erwartetes Verhalten**

Man wird hochgeportet
**Schritte um den Fehler nachvollziehen zu können**

1. Auf eine Liege gebracht werden ohne bewusstlos zu sein
2. In ein Fahrzeug gebracht werden
3. Zum Porter in der MD garage fahren
4. "E" drücken und merken, dass nichts passiert
5. 
**Optional: Video / Bilder des Fehlers**

https://streamable.com/38qs7i

**Comment by TeubyDE** [comment]
Selber Fehler wie in https://github.com/mexyn/statev_v2_issues/issues/2074 beschrieben.
