### ISSUE TITLE
unsichtbares Hindernis - links neben Eingang 24/7 Ortseinfahrt Paleto Bay

### ISSUE THREAD

**Issue by h3adbang3r** [mexyn/statev_v2_issues#2119]
**Character Name**
Throlic Redoran

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.12.2021 21:15

**Beobachtetes Verhalten**
schwebender "Gegenstand

**Erwartetes Verhalten**
keine unsichtbaren Hindernisse

**Optional: Video / Bilder des Fehlers**
https://youtu.be/KScHm4kxlSs

**Comment by milkdrops** [comment]
Auf dem Dev-Server nicht vorhanden

**Comment by WoahJeesus** [comment]
Liegt an der Lichterkette, ist ein unsichtbarer "Block" der sich sonst auf dem Boden befindet. Ist hier nicht der Fall, da die Kette zu hoch hängt. Kann also closed werden ^^
