### ISSUE TITLE
E Ladestelle 

### ISSUE THREAD

**Issue by PhilMorrison93** [mexyn/statev_v2_issues#2120]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Philipp_Morrison**

Philipp Morrison

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

Keine E Ladestelle an Tankstelle La Puerta/Shank St. 386 petrolstation16 PLZ: 5010
Um Marktfähig/Wertbewerbsfähig zu sein wäre eine E-Ladestelle vom Vorteil
**Erwartetes Verhalten**

E Ladestelle an Tankstelle

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by milkdrops** [comment]
Abgelehnt, bereits 1/2 Helikopter Tankstellen in der Stadt.
