### ISSUE TITLE
Mehrere Scout Liverys wechseln

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#2121]
**Beobachtetes Verhalten**
Wechselt zwischen den Liverys, sollte LSPD haben.  Fahrzeug LSPD 6O3  (O statt 0)

(vgl. #1461)

**Comment by milkdrops** [comment]
Benötigt vrmtl. einen festen Wert in der Database

**Comment by DrGrizzlY17** [comment]
@milkdrops wir gucken uns das mal zusammen an :)

**Comment by JannikDatsch** [comment]
Auch OCD 6O1 und NT 6O5 müssten gefixt werden. Hier würde die LSPD Livery auf jeden Fall mehr Sinn machen als die Sheriff Livery. Aber aktuell fehlt auch hier ein fester Wert.

**Comment by JannikDatsch** [comment]
Selbiges gilt für LSPD 6O4

**Comment by DrGrizzlY17** [comment]
Das wechseln der Liverys sollte für die nächsten Neugebauten nicht mehr sein. Das setzen über DB für Sheriff Livery muss in der Zukunft trotzdem noch gemacht werden. @milkdrops weiß bescheid
