### ISSUE TITLE
Teleport "hinter" Garagentor beim schieben eines Fahrzeugs

### ISSUE THREAD

**Issue by Erumeldor** [mexyn/statev_v2_issues#2123]
**Character Name**
Jon_Lewis

**Auftrittszeitpunkt (Datum / Uhrzeit)**
15.12 - ~12:00Uhr

**Beobachtetes Verhalten**
Ich bin beim schieben eines durchs Ausparken beschädigtes Fahrzeugs, welches sehr nah vor dem Haus (house_DelPerro_1) stand, in dessen Garage gebuggt. Siehe Bild unten.
Da ging es dann nicht mehr raus. Musste mich rausteleportieren lassen.

**Erwartetes Verhalten**
Fahrzeug lässt sich einfach nicht schieben weil es zu nah am Haus stand.

**Schritte um den Fehler nachvollziehen zu können**
Auto direkt an die Garage parken. An die Seite vorne hinstellen. Schieben.

**Optional: Video / Bilder des Fehlers**
Hier ist ein Bild von innen:
https://ibb.co/nLntb9L

**Comment by DrGrizzlY17** [comment]
Ja gut, das passiert halt wenn das Fahrzeug zu nah an ner Wand steht. Ist kein Bug.
