### ISSUE TITLE
Autohaus Problem Werkstatt-Flatbed lässt sich nicht ausparken

### ISSUE THREAD

**Issue by StgParker** [mexyn/statev_v2_issues#2125]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Greg Parker / Rainer Kornn

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Beobachtetes Verhalten**
Werkstatt Flatbed lässt sich nicht im Autohaus einer anderen Firma ausparken.
Fehlermeldung: "Das fahrzeug darf nicht ausgeparkt werden"

**Erwartetes Verhalten**
Flatbed lässt sich ganz normal ausparken

**Schritte um den Fehler nachvollziehen zu können**
Mit einem Flatbed einer beliebigen Werkstatt in ein fremdes Autohaus fahren und es dort wieder ausparken wollen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
Egal

**Optional: Video / Bilder des Fehlers**
-

**Comment by StgParker** [comment]
d

**Comment by CatherineGallagher** [comment]
Das liegt an Fahrzeugen generell, die auf Firmen geschrieben sind, diese kann man aber immernoch über den Garagen NPC ein und ausparken, muss man es halt manuell machen.

**Comment by Ekaz58** [comment]
das mit dem npc haben wir versucht, der hat uns aber keinen flatbed angezeigt.

**Comment by DrGrizzlY17** [comment]
Der Flatbed ist auf die Werkstatt geschrieben, korrekt?

**Comment by Ekaz58** [comment]
Genau, Flatbed läuft auf die Firma Gordon Customs, und das Problem bestand im Autohaus von Reaction Corp.

**Comment by Dean-Gallagher** [comment]
sollte eig. fixed sein 
https://github.com/mexyn/statev_v2_issues/issues/2091

**Comment by GusTaylor** [comment]
Wurde scheinbar mit Serverrestart zurück ins Autohaus teleportiert. Dort kann er wieder nicht ausgeparkt werden. Fehlermeldung: "Das Fahrzeug darf nicht ausgeparkt werden"
