### ISSUE TITLE
Lampen deaktivieren/entfernen

### ISSUE THREAD

**Issue by JosefRitter** [mexyn/statev_v2_issues#2126]
**Josef_Ritter**

**Ich wollte Fragen ob die Lampen die in der Hood an den Wänden sind siehe Bilder ( https://pic.statev.de/image/inked20211214224854-1-li.SYuJT und https://pic.statev.de/image/inked20211214224903-1-li.SY590 ) abgeschalten oder entfernt werden könne. **

**Comment by DrGrizzlY17** [comment]
Also zu den Lampen am Boden die scheinen nicht von GTA oder von unserer Map Erweiterung aus zu sein. Könnten von nem User sein.

Die an den Wänden teste ich mal, wenn altV geupdatet ist

**Comment by DrGrizzlY17** [comment]
![image](https://user-images.githubusercontent.com/70150988/146795683-0562321a-87ff-423f-9174-d0c64b02bf1a.png)

lampen entfernen bringt leider nichts, das light object bleibt
