### ISSUE TITLE
Greifautomat blockiert, wenn Spieler Timeout erhält

### ISSUE THREAD

**Issue by CaleighRhodes** [mexyn/statev_v2_issues#2129]
**Character Name**
Caleigh_Rhodes

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.12. / 22:16 Uhr

**Beobachtetes Verhalten**
Hatte einen Timeout am Automaten (weiß allerdings nicht, ob während dem Zieh-Vorgang oder danach/dazwischen). Logge mich wieder ein, Automat zeigt an, er wäre blockiert - auch für andere Spieler.

**Erwartetes Verhalten**
Automat ist nicht für andere Spieler blockiert.

**Schritte um den Fehler nachvollziehen zu können**
Eventuell einfach mal während dem Greifvorgang ausloggen.

Einen Crashdump gibt es leider nicht.

**Comment by DonVitoDiangelo** [comment]
Ja, der Automat ist dann bis zum nächsten Restart "Defekt".

**Comment by CaleighRhodes** [comment]
Ja, ich weiß, wusste nur nicht, ob der Grund des Problems bekannt war und wollt Bescheid sagen. (:
