### ISSUE TITLE
Defekter Ablage Punkt für 40er Heroin Mission

### ISSUE THREAD

**Issue by Wheazle** [mexyn/statev_v2_issues#2130]
**Character Name**
Aaron Reed

**Auftrittszeitpunkt (Datum / Uhrzeit)**
18.12.2021 - 09:03 Uhr

**Beobachtetes Verhalten**
Defekter Ablage Punkt für 40er Heroin Mission.

**Erwartetes Verhalten**
Ablage Punkt sollte funktionieren um die Mission abschließen zu können.

**Schritte um den Fehler nachvollziehen zu können**
Interaktion mit "E" nicht möglich. Auch nicht im Knien oder in sonstigen Postionen

**Optional: Video / Bilder des Fehlers**

![unknown1](https://user-images.githubusercontent.com/95701378/146634346-c9b7cc13-228e-4516-a671-3fc7fb0e64ec.png)
![unknown](https://user-images.githubusercontent.com/95701378/146634348-ba9a5722-0147-4d73-a69e-ee55eeb9646e.png)
![unknown3](https://user-images.githubusercontent.com/95701378/146634350-beaea6be-b5a0-4167-8c6f-3f577b1c216b.png)
![unknown2](https://user-images.githubusercontent.com/95701378/146634353-b9d60c79-a40d-4a51-9183-5dd70127d19e.png)

**Comment by TheOutburst** [comment]
Fixed next Update
