### ISSUE TITLE
Drift Mode nach Alt:V Update langsamer als vorher?

### ISSUE THREAD

**Issue by Koree7** [mexyn/statev_v2_issues#2134]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Brooks_Miller

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit altv Update?

**Beobachtetes Verhalten**
Fahrzeug(Cypher) mit Drift Modus ist langsamer als vorher. (alt: 270+ neu: capped auf 245)

**Erwartetes Verhalten**
Sollte wieder wie vor dem Update fahren, außer es war nicht gewollt.

**Schritte um den Fehler nachvollziehen zu können**
Drift Mode an, fahren

**Comment by CubeXLIVE** [comment]
Kann ich so bestätigen. War vorher uncapped sogar bis 300+ möglich aufm Highway mit Bodenwellen aber jetzt bleibt der strikt auf 245 hängen

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2136
