### ISSUE TITLE
Anschalten des Begrenzers bei durchdrehenden Reifen teilweise nicht möglich

### ISSUE THREAD

**Issue by Pregon** [mexyn/statev_v2_issues#2135]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Ronny_Roberts

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Ziemlich lang

**Beobachtetes Verhalten**
Bei durchdrehenden Reifen kann der Begrenzer nicht auf 80km/h oder niedriger (je nach Fahrzeug unterschiedlich) eingeschalten werden, da man angeblich zu schnell ist, obwohl die aktuelle Geschwindigkeit niedriger als der Begrenzer ist.

**Erwartetes Verhalten**
Solang die Geschwindigkeit unter der Begrenzer Einstellung ist sollte dieser auch an gehen

**Schritte um den Fehler nachvollziehen zu können**
In beispielsweise einen Seven-70 setzen und anfahren, beim durchdrehen der Reifen versuchen den Begrenzer einzuschalten

**Optional: Video / Bilder des Fehlers**
https://user-images.githubusercontent.com/75855042/146774035-7086ea5d-681b-40e5-9ee7-51971a2435c3.mp4

**Comment by DonVitoDiangelo** [comment]
Reifendrehzahl ist halt zu hoch beim durchdrehen der Reifen.
