### ISSUE TITLE
Werkstatt: Reifenwechsel & Service "Die Zahlung kann nicht durchgeführt werden" 

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#2138]
**Character Name**
Horizon Hottest Engines

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Will man Service oder Reifenwechsel bezahlen so kommt die Meldung "Die Zahlung kann nicht durchgeführt werden"

**Erwartetes Verhalten**
Das es wieder geht -> vll gleich noch in den Finanzen die Trennung der neuen Kategorien einbinden aus dem https://github.com/mexyn/statev_v2_issues/issues/1963

**Comment by DrGrizzlY17** [comment]
ressources mergen pls :D

**Comment by GusTaylor** [comment]
Fehler besteht weiterhin für Reifenwechsel und Serviceleistungen.

**Comment by DrGrizzlY17** [comment]
Ja gab auch noch kein Update :P
