### ISSUE TITLE
Reifenwechsel nicht möglich

### ISSUE THREAD

**Issue by nox142** [mexyn/statev_v2_issues#2139]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Jona Lindner

**Auftrittszeitpunkt (Datum / Uhrzeit)**
20.12.2021 16 Uhr 

**Beobachtetes Verhalten**
Reifenwechsel nicht möglich. Weder mit Bargeld noch per Karte. Anscheinend betrifft das auch den Service. 
Reparatur und Tuning funktionieren anscheinend.
Getestet bei Gordons und Horizon

**Erwartetes Verhalten**
Reifenwechsel bezahlen und der Wechsel beginnt

**Schritte um den Fehler nachvollziehen zu können**
Zu einer Werkstatt gehen und versuchen Reifen wechseln zu lassen

**Optional: Video / Bilder des Fehlers**
https://prnt.sc/23q1ckh

**Comment by DrGrizzlY17** [comment]
#2138
