### ISSUE TITLE
Trailer nicht abhängbar

### ISSUE THREAD

**Issue by nox142** [mexyn/statev_v2_issues#2140]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Jona Lindner

**Auftrittszeitpunkt (Datum / Uhrzeit)**
~15:30

**Beobachtetes Verhalten**
Nach dem betreten und verlassen des Sägewerks, konnte ich den Semi nicht mehr wirklich fahren. Bei dem versuch, die Tieflader Achse abzuhängen, ging das auch nicht mehr. Siehe Video unten.

**Erwartetes Verhalten**
Achse abhängbar nach betreten einen Gebäudes. Sync?

**Schritte um den Fehler nachvollziehen zu können**
Zugmaschine und Auflieger (aneinander gekoppelt) vor dem Gebäude abstellen, Gebäude betreten, Gebäude verlassen und dann versuchen los zu fahren

**Optional: Video / Bilder des Fehlers**
https://medal.tv/games/gta-v/clips/5yol9eeTjXKux/d1337h2SHy54?invite=cr-MSxLeEosMTc4MTA3ODMs

**Comment by cadpri** [comment]
Exakt das gleiche Problem habe ich mit dem Barracks und meinem Ölauflieger auch.
Alles gut bis da sman in ein Gebäude geht und wieder raus geht

**Comment by TeubyDE** [comment]
Ich gehe davon aus das dieses Verhalten mit dem aktuell altv Bug zu tun hat.
Am besten mit den Trailern aktuell vorsichtig sein.

Siehe Server Status im Discord

**Comment by cadpri** [comment]
Ja das ist schon richtig.
Interessant ist halt, dass es nur Barracks betrifft.

Naja vorsichtig sein ist gut. Sie sind einfach garnicht mehr benutzbar 😄
