### ISSUE TITLE
Nagasaki Blazer / Hot Rod Blazer

### ISSUE THREAD

**Issue by Koray5858** [mexyn/statev_v2_issues#2141]
Charakter : Jason Rains

Datum 20.12.2021 Uhrzeit zwischen 16:10-16:15Uhr 

Fehler bei der Produktion von Nagasaki Blazer / Hot Rod Blazer 

Statt dem Hot Rod Blazer 2x den Blazer erhalten

Ich habe zweimal den Motor für den Hot Rod Blazer gekauft jedoch sind die Motoren als "Import engine_blazer_35ps" gelistet statt  als "Import engine_blazer3_35ps", somit habe ich beim entpacken im Autohaus 2x den Nagasaki Blazer erhalten anstatt 2x den Hot Rod Blazer zu erhalten.
Habe bereits mit Acc3zZ im TS über das Thema gesprochen.
Bitte um Überprüfung bzgl. eines Austausches zum Hot Rod Blazer bzw. wenn ein Fehler meinerseits vorliegt um eine Namensanpassung der Motoren und der Produktion da beides mit Nagasaki Blazer / Hot Rod Blazer betitelt ist.

**Comment by DrGrizzlY17** [comment]
Die Namensanpassung ist gemacht.
Vorher: Nagasaki Blazer / Hot Rod Blazer -> Nagasaki Blazer

Damit ist es jetzt eindeutiger.
