### ISSUE TITLE
Winterreifen Zahlung erfolgt nicht.

### ISSUE THREAD

**Issue by Romeny1** [mexyn/statev_v2_issues#2142]
Character Name
Mitt Romney

Auftrittszeitpunkt (Datum / Uhrzeit)
~18:05

Beobachtetes Verhalten
Kann keine Winterraifen aufziehen lassen; Bezahlvorgang kann nicht abgeschlossen werde. (Geld vorhanden).

Erwartetes Verhalten
Die Rechnung sollte begl. werden, bzw. der Vorgang abgeschlossen. 

Schritte um den Fehler nachvollziehen zu können
Winterreifen wechseln, haben es in LSC mehrfach probiert, auch der Mechaniker, hat nicht funktioniert.  

Optional: Video / Bilder des Fehlers
https://pic.statev.de/image/pic.SBn9B

**Comment by CaleighRhodes** [comment]
#2138 #2139
