### ISSUE TITLE
Scout Blaulicht broke

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#2143]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.12.2021 

**Beobachtetes Verhalten**
Die Blaulichter der Scouts sind bei den neuer produzierteren Scouts verbuggt, sodass sie komplett schwarz sind und auch die Rückseite gar nicht leuchtet. (bsp. LSPD 6O3 u. OCD 6O1)

*Edit LSPD 6O4 hingegen ist, obwohl neu, auch normal

**Erwartetes Verhalten**
Sollten normal leuchten und dargestellt werden wie bsp. LSPD 6O1

**Schritte um den Fehler nachvollziehen zu können**
siehe Vid

**Optional: Video / Bilder des Fehlers**

https://youtu.be/87N2MXAeHxc

**Comment by JojoGHB** [comment]
Meines Wissens nach kein Bug, sollte am Tuning (Scheibentönung) liegen

**Comment by DonVitoDiangelo** [comment]
Oder Montagsproduktion, such es dir aus.
