### ISSUE TITLE
Fehlerhafte Texturen

### ISSUE THREAD

**Issue by Erumeldor** [mexyn/statev_v2_issues#2145]
**Character Name**
Jon_Lewis

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.12.2021 16:10

**Beobachtetes Verhalten**
Texturen von den Palmen/Bäumen im Dorset Drive sind fehlerhaft.
Siehe Bilder :)

**Schritte um den Fehler nachvollziehen zu können**
Einfach mal da hin fahren. Nähe PLZ 5154.

**Optional: Video / Bilder des Fehlers**

![image](https://user-images.githubusercontent.com/21212905/146952992-4c6b7f7b-28f0-457c-9a5e-5afd42a6acbf.png)
![image](https://user-images.githubusercontent.com/21212905/146953042-18c361b3-54f8-4e82-985a-669aa4284065.png)

**Comment by Erumeldor** [comment]
Achja, man kann dagegen fahren. Sind also schon noch tatsächlich da.

**Comment by Erumeldor** [comment]
Und hier noch ein Baum, der sehr seltsam aussieht.
![image](https://user-images.githubusercontent.com/21212905/146953302-3c71fb40-6427-4f26-95cf-6e837b2e680b.png)

**Comment by DrGrizzlY17** [comment]
Liegt wohl an deinen Grafiksettings :) 
![image](https://user-images.githubusercontent.com/70150988/146957286-13fd77d7-f5cd-464f-8eca-44b33d59da63.png)

**Comment by Erumeldor** [comment]
Sad ^^
Okay, dann sorry für das unnötige Ticket :D
Ich schau mir das mal nochmal an.

**Comment by ChapWinchester** [comment]
Ist bei mir auch das selbe, nur an der selben straße, überall geht das. habe einstellung von low bis high umgestellt trotzdem transparent
