### ISSUE TITLE
Underground UI-Maske bugt , restart notwendig

### ISSUE THREAD

**Issue by Schmiddie01** [mexyn/statev_v2_issues#2147]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
John Smitty

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.12.2021 19:20

**Beobachtetes Verhalten**
Beim auswählen des Underground Races muss restartet werden , weil die User-Interface Maske sich nicht schließt und man nichts mehr auswählen kann und sonstige interaktions möglichkeiten wie Voice/Animation nicht mehr funktionieren , nach restart kann man auch nicht im Underground Fahren.

**Erwartetes Verhalten**
Rennen auswählen und den Underground betreten

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2424
