### ISSUE TITLE
Verbrauch vom Phantom mit dem größten Motor (456PS)

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#2148]
**Character Name**
Paul Humpert

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Dauerhaft

**Beobachtetes Verhalten**
Der normale Phantom mit dem größten Motor verbraucht deutlich mehr Sprit als die mit dem kleineren Motor bzw. andere Zugmaschinen, z.B. von Grapeseed in die Stadt und zurück 90L

**Erwartetes Verhalten**
Der Spritverbrauch sollte etwas gesenkt werden, sodass es sich auch noch lohnt, anstatt eine andere Zugmaschine zu holen, einen Phantom zu kaufen.

**Schritte um den Fehler nachvollziehen zu können**
Mit einem Phantom fahren

**Comment by DonVitoDiangelo** [comment]
Die Zugmaschinen verbrauchen je nach Motor annähernd identischen Sprit. Das ein kleinerer Motor weniger Sprit verbraucht , sollte klar sein.
