### ISSUE TITLE
Bandana immernoch verbuggt

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#2149]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Sven Rosenbach
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Release von V2, kein Fix, obwohl #1924 als Solved steht
**Beobachtetes Verhalten**

Nase buggt duch Bandana
**Erwartetes Verhalten**

Nase buggt nicht durch 
**Schritte um den Fehler nachvollziehen zu können**

Mit betroffenen Char ein Bandana aufsetzten
**Optional: Video / Bilder des Fehlers**

![image](https://user-images.githubusercontent.com/58612983/147235788-a87cb09d-da02-43a4-baaa-b816d3a572a0.png)

**Comment by Hutstaender** [comment]
Schau dir das nach dem nächsten Update nochmal an und geb hier rückmeldung pls.

**Comment by SHaagmann** [comment]
![image](https://user-images.githubusercontent.com/58612983/148231144-5f334fdb-ce78-4942-b42f-83ecf14fabbb.png)
klappt alles jetzt
