### ISSUE TITLE
Lackieren Anzeige für benötigte Rohstoffe fehlerhaft

### ISSUE THREAD

**Issue by BlackyGER** [mexyn/statev_v2_issues#215]
Wollte Mattschwarz lackieren
Weis was dafür benötigt wird. 
Bei Kohlestaub fehlt die Anzeige das es Kohlestaub, ist bei allen Stäuben. 
Lackieren ging auch nicht. 

https://i.imgur.com/hKTDzfJ.jpg
https://i.imgur.com/ARstnMa.jpg

**Comment by DonVitoDiangelo** [comment]
Berechnung fehlerhaft. Bei Fragen nochmal bei mir melden. neue Config liegt vor.

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/296

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/358

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/265
