### ISSUE TITLE
Mülleimer entfernen

### ISSUE THREAD

**Issue by AlbertPike1** [mexyn/statev_v2_issues#2150]
https://pic.statev.de/image/mulleimer-2.SCGa0

bitte die Eimer wegmachen

vielen dank Frohes Fest und Guten Rutsch

**Comment by DonVitoDiangelo** [comment]
Danke, das wünschen wir dir auch.
Bitte teile uns dort noch den Standort mit, wo genau das ist. Am besten einen Firmenhash, danke.
