### ISSUE TITLE
Gamecrash während Autofahrt.

### ISSUE THREAD

**Issue by Rheco** [mexyn/statev_v2_issues#2151]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by milkdrops** [comment]
Bitte Vorlage ausfüllen.
