### ISSUE TITLE
Fahrzeug wird beschädigt beim ausparken / Vinewood West Garage

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#2152]
Santito Quintero

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03:15

**Beobachtetes Verhalten**
Pounder Custom wird beim Ausparken beschädigt. Manchmal passiert nix, manchmal direkt ein Totalschaden. Vinewood West Garage

**Erwartetes Verhalten**
Fahrzeug soll nicht beschädigt werden

**Comment by DrGrizzlY17** [comment]
Garage Rockford same

**Comment by DrGrizzlY17** [comment]
* On Hold * Könnte aktuell mit dem Bug zusammen hängen, das man aktuell nicht im Fahrzeug spawnt. <- Fixed next update. Dann beobachten @epichalt

**Comment by Saaria83** [comment]
Garage Rancho auch. Aber so ist mir das nur beim Youga Classic 4x4 aufgefallen, der dann auch direkt kaputt geht. Alle anderen Stehen beim ausparken normal der. Dieser allerdings "fällt" ein bisschen

Damit Ihr sehr was ich meine:

https://www.youtube.com/watch?v=_vpkI2fopcI

**Comment by epichalt** [comment]
Vinewood West ist der Fehler auf jeden Fall behoben, denke bei den anderen Garagen auch. Bin mal so frei und close das einfach 😅
