### ISSUE TITLE
Gleiche Samen werden nach Handel getrennt im Inventar angezeigt

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#2154]
**Character Name**
Paul Humpert

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.12.2021 / 19 Uhr

**Beobachtetes Verhalten**
Wenn man mit einem anderen Spieler handelt, dieser einem zuerst einen Teil von Samen gibt (z.B. 4x Koka) und dann nochmal die selben Samen gibt (z.B. 2x Koka) dann werden diese nach Abschluss des Handels dauerhaft im Inventar getrennt angezeigt, obwohl es sich um die selbe Art von Samen handelt. Auch wenn man die Samen in ein Zimmer oder in ein Auto legt, bleiben diese weiterhin getrennt.

**Erwartetes Verhalten**
Die Samen sollten wieder zusammengefügt werden und nicht getrennt im Inventar angezeigt werden.

**Schritte um den Fehler nachvollziehen zu können**
- Die selbe Art von Samen nehmen (z.B. Koka)
- Mit einem anderen Spieler handeln
- die Samen aufteilen (z.B. zu erst 3 Samen und dann 4 Samen)
- Handel abschließen

**Comment by Statev-Bonsai** [comment]
es gab schon immer 2 arten von koka samen!

**Comment by Humperrrt** [comment]
ah top okay dann kann geschlossen werden wusste ich nicht dachte das wäre durch das traden entstanden :)

**Comment by its4l3x** [comment]
Perfekt.
