### ISSUE TITLE
Userinterface absturz beim ATM Ausrauben

### ISSUE THREAD

**Issue by Husky2002** [mexyn/statev_v2_issues#2155]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Eddy Husky

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.12.21 14:11Uhr

**Beobachtetes Verhalten**
Als ich den ATM gegenüber dem Frisur "Die Schererei" knacken wollte und ich oben rechts auf das rote symbol gedrückt habe kam folgende Nachricht *siehe Bild*

**Erwartetes Verhalten**
Fehler beheben

**Schritte um den Fehler nachvollziehen zu können**
/

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
/

**Optional: Video / Bilder des Fehlers**

![20211226141052_1](https://user-images.githubusercontent.com/61657852/147409841-8d40e8dd-bbf8-46d9-ac76-e5d9680c0b32.jpg)

**Comment by Hutstaender** [comment]
selber fehler wie #2144
