### ISSUE TITLE
Ölachse Bug

### ISSUE THREAD

**Issue by Cro20** [mexyn/statev_v2_issues#2157]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name** Dominik_Sova

**Auftrittszeitpunkt (Datum / Uhrzeit)**

26.12.2021/20:30
**Beobachtetes Verhalten**

Beim Fahren mit dem Kamacho, ist mir ein Phantom mit Ölachse entgegen gekommen, mit dem Bug der eig. gelöst sein sollte
**Erwartetes Verhalten**

Ölachse wird ganz Normal gezogen ohne zu Buggen
**Schritte um den Fehler nachvollziehen zu können**

Kamacho Fahren und beobachten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=XK2uFw7wim0

**Comment by TheOutburst** [comment]
#2116
