### ISSUE TITLE
erneutes Annehmen eines Dispatches

### ISSUE THREAD

**Issue by DrJaneX** [mexyn/statev_v2_issues#2158]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Jane Winter
**Auftrittszeitpunkt (Datum / Uhrzeit)**

26.12.2021 / 23:15 Uhr
**Beobachtetes Verhalten**

man geht an den Dispatch, nimmt einen Anruf an, schließt während dem Dispatch das Overlay - Anruf bricht ab, bei erneutem Aufrufen des Dispatchsystems kann der Anruf entgegen genommen werden
**Erwartetes Verhalten**

bei Schließen des Overlays sollte man den Anruf nicht mehr annehmen können
**Schritte um den Fehler nachvollziehen zu können**

als Leitstelle einstempeln - Notruf absetzen - Overlay öffnen - Anruf entgegen nehmen - System schließen - System erneut Aufrufen - Anruf erneut annehmbar
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by milkdrops** [comment]
Soweit geklärt:
Für Rückfragen ist das Feature in Ordnung, bleibt in Beobachtung
