### ISSUE TITLE
Geschwindigkeitsbug

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#2161]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.12.2021 03:54

**Beobachtetes Verhalten**
Der Interceptor 207 war direkt nach ausparken in Geschwindigkeit und Beschleunigung stark verbessert.

Auch durch ein und wieder ausparken blieb der Fehler bestehen.

Nachdem ich dann 24h später den Wagen nm. gefahren bin, war alles wieder normal.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/bb3fJ4Mdi4M
https://youtu.be/6-jZtDzLE58

**Comment by Hutstaender** [comment]
das war kein Bug, alles cool
