### ISSUE TITLE
Fehler Meldung beim betreten der Gießerei

### ISSUE THREAD

**Issue by StateV2Marie** [mexyn/statev_v2_issues#2163]
Wolte in Gießerei Summer gehen an der tür angekommen sie is Pyrite Ave/Paleto Blvd. 21 kam als fehler meldung  ein komisches bild wo ihr wohl mehr mit anfangen könnt link geb ich euch hier gern dazu 

[https://cdn.discordapp.com/attachments/411925103048392724/924975114779492372/IMG_20211227_113905.jpg](url)

hoffe ihr könnt was mit anfangen ich nich.

mfg : Marie Pech

**Comment by Hutstaender** [comment]
selber fehler wie #2144
