### ISSUE TITLE
Weizen Farmen

### ISSUE THREAD

**Issue by StateV2Marie** [mexyn/statev_v2_issues#2164]
Hallo ich wolt mich mal erkundigen obs möglich is das man entweder den ertrag oder die felder bearbeiten kann es is verdammt schwer Weizen zu machen a is die fläche nich fürn traktor ausgeleht fahrzeug geht bei an dippen von strohballen kaputt. wendekreis is mega klein und nich leicht von ort zu ort zu fahren das schlimme is du fährt hälst an sammels packst ins auto steigst ein fährst weiter wenn wir das benzin und die arbeit rechnen wird es bald kein mehl mehr geben das wäre verlust für die lebens mittel branche leider den ohne mehl keine nudeln oder bröchen oder sonst was zudem kein weizen kein bier mehr was nich so toll kommen würde. es wäre also lieb wenn ihr da euch noch ne kleine verbesserung einfallen lassen würdet. danke

mfg; Marie Pech

**Comment by CaleighRhodes** [comment]
https://statev.de/forum/thread/13163-fieldmaster-f%C3%BCr-die-feldarbeit-einsetzen/?postID=119778&highlight=Weizen#post119778

Siehe Beitrag von Vito.
