### ISSUE TITLE
Hose buggt durch Bandana

### ISSUE THREAD

**Issue by lxrxnzlm** [mexyn/statev_v2_issues#2165]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Lukas_Madrig

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Wenn man ein Bandana mit der Helix Worker X Hose trägt dann buggt ein kleiner Teil der Tasche durch das Bandana

**Erwartetes Verhalten**
1. Dass die Hose nicht mehr durch das Bandana buggt
2. Außerdem wäre es ganz cool wenn man ein Unterhemd gleichzeitig mit nem Bandana anziehen könnte, indem man zb einen zweiten Unterhemd Slot einfügt oder so

**Schritte um den Fehler nachvollziehen zu können**
Helix Worker X anziehen mit einem Bandana

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/SucDc

**Comment by Hutstaender** [comment]
Da können wir leider nichts gegen machen. Diese Modded Bandanas passen leider bei einigen Hosen nicht richtig. Einzige Option wäre ne andere Hose anziehen.
