### ISSUE TITLE
Kennzeichen mit Umlaut wird abgebucht, aber nicht angezeigt

### ISSUE THREAD

**Issue by SirSvenselot** [mexyn/statev_v2_issues#2166]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Sven_Stern

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.12. ca. 22:15 Uhr

**Beobachtetes Verhalten**
Wollte das Kennzeichen Hütchen haben. Das Geld wurde abgebucht und auch das Nummernschild (zumindest der ausgewählte Stil) angebracht. Nummernschild war jedoch weder am Fahrzeug sichtbar, noch im Handy im Schlüsselbund. Huetchen hat wiederrum funktioniert, da kein Umlaut.

**Erwartetes Verhalten**
Fehlermeldung/Hinweis, dass keine Umlaute genutzt werden können und Abbruch des Kaufvorgangs oder korrekte Anzeige des Kennzeichens.

**Schritte um den Fehler nachvollziehen zu können**
Kennzeichen kaufen mit einem Umlaut

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://user-images.githubusercontent.com/96785542/147582547-38815925-d53e-425c-83dd-d06a2346ec6b.png)
![image](https://user-images.githubusercontent.com/96785542/147582606-dd6e1a50-36be-4fd1-92d7-d8257ba0ed5f.png)
![image](https://user-images.githubusercontent.com/96785542/147582653-d0892ede-e91c-419b-8df5-d56f890a359e.png)
 
![image](https://user-images.githubusercontent.com/96785542/147582699-496e1db7-2f40-4191-968f-c89e87e57d00.png)

**Comment by epichalt** [comment]
Du hast einfach nur den Stil gekauft. Hättest du das Kennzeichen gekauft, hättest du es 7 Tage nicht ändern können. Aber Umlaute gehen sowieso nicht. Daher ist das mMn. kein Bug weil der Kauf nie stattgefunden hat. Bin auch der Meinung du bekommst einfach eine Fehlermeldung falls du Umlaute auswählst.

**Comment by SirSvenselot** [comment]
Okay, könnte natürlich auch sein. Ist dann dann aber etwas irreführend, dass man lediglich den Stil kauft, wenn man ein Kennzeichen eingibt aber halt im Fenster Stil auf kaufen drückt. Hab gedacht, dass ich das Kennzeichen auswähle und dann noch ein Stil gleich mit dazu kaufen kann anstatt beides separat. 

Aber wenn's kein Bug is, kann's gerne zu xD

**Comment by CaleighRhodes** [comment]
Eigentlich kann man beides zusammen kaufen, war jedenfalls früher so o.o

**Comment by SirSvenselot** [comment]
> Eigentlich kann man beides zusammen kaufen, war jedenfalls früher so o.o

Gut, dann warten wir mal ab, ob's doch noch so ist, oder geändert wurde

**Comment by DrGrizzlY17** [comment]
Wie viel Geld wurde dir denn berechnet? Also wie viel hast du bezahlt?

**Comment by SirSvenselot** [comment]
> Wie viel Geld wurde dir denn berechnet? Also wie viel hast du bezahlt?

Konnte ich leider nicht nachvollziehen, hab ich auch nachgeschaut. Wird bar abgebucht und nicht übers Konto

**Comment by TeubyDE** [comment]
Habe es soeben versucht nachzustellen. 
Stieländerungen sind unabhängig von der Beschriftungsänderungen vorzunehmen.
```
• Stiel -> auswählen -> Kaufen -> Geldabgezogen bekommen
• Beschriftung -> Text eingeben ("Hütchen") -> Eintragen -> Fehlermeldung das nur Alphanumerische Zeichen erlaubt sind.
```
Beschriftungsänderungen mit Umlaufen können nicht durchgeführt werden.
