### ISSUE TITLE
Hauler crasht Werkstatt Terminal

### ISSUE THREAD

**Issue by BlackyGER** [mexyn/statev_v2_issues#217]
Hauler auf Repairpunkt gestellt
Terminal benutzt mit E 
ehlend langer ladeprozess bzw es baut sich nichts auf. 
Man sieht im Video die Maus als ich 1. E drückte
beim Zweiten mal E drücken kam die Meldung.
Restart brachte nix selbe Meldung
Nur /dv half. Danach ging das Terminal aber wie gewohnt

https://youtu.be/2KfAfY-z0Dw

**Comment by DonVitoDiangelo** [comment]
bekannt, modkit error

**Comment by BlackyGER** [comment]
Flatbads das gleiche problem!
