### ISSUE TITLE
Spritverbrauch Albany Alpha

### ISSUE THREAD

**Issue by StateV-Jan** [mexyn/statev_v2_issues#2172]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by StateV-Jan** [comment]
Grüße,
ich habe mir heute ein Albany Alpha gekauft und musste dann feststllen das man ca 1-1,5l auf ein km verbraucht. Bin hoch nach Paleto gefahrn und durfte danach erstmal 40l tanken als ich wieder unten war... Nun die Frage ob es so gewollt ist oder ein Bug ist. MFG Jan Bach

**Comment by cadpri** [comment]
Das klingt so auf Anhieb nach etwas das man zuerst mal ic prüfen sollte

**Comment by StateV-Jan** [comment]
Habe ich schon, der Fehlerspeicher ist leer und das Auto besitzt Winterreifen.

**Comment by cadpri** [comment]
Ah okay dann hab ich nichts gesagt 😄

**Comment by DrGrizzlY17** [comment]
Welchen Motor hat der Alpha drin?

**Comment by StateV-Jan** [comment]
Er hat denn 150ps Motor drin MFG

**Comment by DonVitoDiangelo** [comment]
Alles i.O. hier

**Comment by StateV-Jan** [comment]
Okay, also könnte man denn nicht irgendwie anpassen das er bisschen weniger verbrauchen würde? Trotzdem Danke
