### ISSUE TITLE
Ölausbeute seit AltV Update "komisch"

### ISSUE THREAD

**Issue by powerswissi** [mexyn/statev_v2_issues#2173]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Juna Matador, Ina Burnett, Roger Thickle

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Seit dem ALTV Update in Zusammenhang mit em GTA Update
  

**Beobachtetes Verhalten**

seid AltV Update ist die Ölausbeute um einiges gesunken obwohl ausgelernt bzw kurz davor. 
Es gibt Tage!! da kommen max 35 raus.. Ab und zu 40.. Ab und zu kommt an der letzten pumpe (wenn man noch 10 Liter braucht ) auch mal 79 raus.

Ansonsten ist es sehr mau mit doppelter Ausbeute. Von den 10% merkt man leider so gut wie gar nichts mehr. 

Für einen Tanker zu füllen benötigt man teilweise 4 Runden aber auch schon 4 1/2 Runden! auf dem grossen Ölfeld.
Gegenüber vor dem Update konnte man dort bereits nach 3 Runden nach Hause fahren.
  
**Erwartetes Verhalten**

Es darf ruhig ein wenig mehr sein. 

**Schritte um den Fehler nachvollziehen zu können**

Wir wissen nicht ob das ein Spieler bezogenes problem ist oder ein allgemeiner Fehler. Deswegen ist es schwer zu sagen wie man diesen reproduzieren soll

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by cadpri** [comment]
Kann ich so auch bestätigen.
Ich hatte vor dem Update nach 3 Runden circa 1000 Liter im Auflieger.
Aktuell ist der Auflieger nach 4 Runden knapp voll.

Ausgelernt und 10% kommt wirklich deutlich seltener als sonst.

**Comment by DonVitoDiangelo** [comment]
So ist das halt mit der Zufälligkeit. :)

**Comment by powerswissi** [comment]
Das hat nichts mehr mit Zufälligkeit zu tun wenn das immer ist, vorallem bei mehreren Personen. 
Wenn dies eine zufälligkeit ist braucht man meiner Meinungnach auch keinen Skill dafür denn ungelernt kommt genau so viel raus :)

**Comment by JohnMckansy** [comment]
Das selbe habe ich auch beobachtet. Ich bin zwar bislang nie über die 4 Runden hinausgegangen aber es war manchmal schon etwas seltsam im vergleich zu vor dem Update.
