### ISSUE TITLE
Textur vom Large Trailer buggt

### ISSUE THREAD

**Issue by SatyriaDine** [mexyn/statev_v2_issues#2174]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Sofia_Black // Ogi_Black

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.01.2022 ca 16:30

**Beobachtetes Verhalten**
Textur des large Trailers verändert sich

**Erwartetes Verhalten**
Textur bleibt gleich

**Schritte um den Fehler nachvollziehen zu können**
Zugmaschine ausparken (in unserem Fall war es ein Packer) Large Trailer ankoppeln. Herumfahren. Textur scheint sich je nach dem wo man herumfährt zu verändern

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=gtbBT45Ol2Q

**Comment by DrGrizzlY17** [comment]
Also prinzipiell ist das kein Fehler der von uns produziert oder gefixt werden kann.

Entweder ist es GTA related oder hast du eventuell Grafik Mods installiert wie QuantV, LA Roads etc.?

**Comment by SatyriaDine** [comment]
LA Roads hab ich drin. Könnte dann wohl daran liegen. :D

**Comment by l4m4rr224** [comment]
Also ich habe kein LA Roads o.ä nur Reshade und habe den Texturen Bug auch gehabt

**Comment by DrGrizzlY17** [comment]
> Also ich habe kein LA Roads o.ä nur Reshade und habe den Texturen Bug auch gehabt

Ah ok, meine Vermutung lag auf ner veralteten Mod Version.
