### ISSUE TITLE
Garage LSMJ - Fallhöhe beim Ausparken

### ISSUE THREAD

**Issue by CaleighRhodes** [mexyn/statev_v2_issues#2178]
**Character Name**
Caleigh Rhodes

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit ein paar Tagen, genaues Datum kann ich nicht nennen, zuerst gestern bemerkt. Heute wieder.

**Beobachtetes Verhalten**
Parkwächter der LSMJ-Garage schmeißt das Auto aus zu hoher Höhe -> Fahrzeug klappert danach und muss ggf. öfter repariert werden. Anbei zwei Beispiele mit meinem Oracle und Andy Christs Kommoda.

**Erwartetes Verhalten**
Geringere Fallhöhe, damit es nicht mehr klappert

**Schritte um den Fehler nachvollziehen zu können**
Ein Fahrzeug aus der LSMJ-Garage ausparken

**Optional: Video / Bilder des Fehlers**

https://user-images.githubusercontent.com/74977218/148106960-ebcd2f81-1e89-4c94-9424-4c7536f723ab.mp4

https://user-images.githubusercontent.com/74977218/148107045-6bd9b172-a8bd-460a-bec5-8cc64d3ad2d3.mp4

**Comment by DrGrizzlY17** [comment]
#2152 sollte nach dem nächsten update so nicht mehr sein. wenn doch bitte im verlinkten beitrag melden
