### ISSUE TITLE
GTA Karte überlagert die Karte mit Zip Codes

### ISSUE THREAD

**Issue by SirWussa** [mexyn/statev_v2_issues#218]
**Character Name**
Jeff Hicks

**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020 09:00

**Beobachtetes Verhalten**
Im ESC Menü wird die Karte mit den Zip Codes nur angezeigt wenn man komplett raus zoomt. Beim rein zoomen überlagert die default Karte die mit den Zip Codes.

**Erwartetes Verhalten**
Zip Code Karte sollte immer angezeigt werden. 

**Schritte um den Fehler nachvollziehen zu können**
ESC drücken und in der Karte hin und her zoomen.

**Optional: Video / Bilder des Fehlers**
![mapFEhler](https://user-images.githubusercontent.com/37578644/99777275-5a572b80-2b12-11eb-9abe-2071c5088469.png)

**Comment by SirWussa** [comment]
nun funzt die korrekt. Man kann rein und raus zoomen und die zip codes bleiben

**Comment by DrGrizzlY17** [comment]
Fixed
