### ISSUE TITLE
HATers Spam in der AltV Konsole

### ISSUE THREAD

**Issue by cadpri** [mexyn/statev_v2_issues#2180]
**Character Name**
Fabian_Picard

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.01.2022 17:20

**Beobachtetes Verhalten**
Fehlermeldungsspam in der Altv Konsole

baseobject is invalid at client/index.js:3:1176263
[V8] Exception at statev-rp:client/index.js:3
Ihre Hausverwaltung',k4u="Viel Spa\xDF mit deinem Caps Laden HATers!,b4u="wenn e...
Resource-Error Uncought Error: baseobjekt is invalid in Line 3

**Erwartetes Verhalten**
Kein Fehlermdlungspam in der Altv Konsole

**Schritte um den Fehler nachvollziehen zu können**
In den Log Files nachschauen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
https://www.twitch.tv/videos/1253817570

**Comment by Hutstaender** [comment]
Ohne zu wissen was du davor gemacht hast wird das schwierig. Beobachte das mal wann der Fehler auftritt.

**Comment by cadpri** [comment]
Also ich hatte nichts gemacht was irgendwas mit HATers zu tun hatte. Ich hatte mich noch nichtmal in der Stadt oder in der Nähe vom HATers aufgehalten. Nur Sandy Shores und Paleto Bay.
2 mal kurz im Mirror Park.

**Comment by Hutstaender** [comment]
Der Fehler hat auch nichts mit dem Haters shop zu tun, das kommt wo anders her

**Comment by cadpri** [comment]
Achso okay. Dann halte ich das mal im Auge und melde mich nochmal.
