### ISSUE TITLE
MD Heli verbraucht viel innerhalb Minuten

### ISSUE THREAD

**Issue by TheMoonicorn** [mexyn/statev_v2_issues#2182]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

05.01.2022

**Beobachtetes Verhalten**

Heli verbraucht  Kerosin schnell wie sonst was

**Erwartetes Verhalten**

Heli sollte weniger verbrauchen

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/FNogir755Uk

**Comment by DrGrizzlY17** [comment]
Tank lag IC bereits confirmed xD
