### ISSUE TITLE
Driftreifen

### ISSUE THREAD

**Issue by Michi993** [mexyn/statev_v2_issues#2183]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Luke Hammer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.01.2022

**Beobachtetes Verhalten**
Driftreifen lassen sich nicht produzieren (nicht vorhanden)

**Erwartetes Verhalten**
sollten produzierbar sein

**Schritte um den Fehler nachvollziehen zu können**
X

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Comment by milkdrops** [comment]
Next update

**Comment by Hutstaender** [comment]
Nein, ich mach das wieder Rückgängig. Das ist kein Bug sondern gewollt, weil die Driftreifen "anders" funktionieren als alle anderen und bisher bei uns noch nicht gehen.
