### ISSUE TITLE
Seit dem letzten Update, verändertes Charaussehen

### ISSUE THREAD

**Issue by WasabiMizz** [mexyn/statev_v2_issues#2184]
**Nini Berger*

**permanent**

**es ist wie zuviel Makeup im Gesicht, um die Augen und im Stirnbereich, siehe Bild vor dem Update und Bild nach dem Update.
wie eine permanenter Glanz um die Augen und auf der Stirn. Kleisung wurde schon merhfach gewechselt auf anraten des Supports, leider keine Veränderung**

<img width="341" alt="mmmm" src="https://user-images.githubusercontent.com/97202920/148357874-9223fb78-ce90-4867-a6b9-84319c1d8a83.png">
<img width="614" alt="Screenshot 2022-01-06 095650" src="https://user-images.githubusercontent.com/97202920/148357889-da69dc91-659b-4cab-97c4-a6e03f8ffab3.png">

**Comment by Hutstaender** [comment]
Es gibt leider keine charakter aussehenseinstellung für "glanz" was auch immer das ist daran können wir leider nix machen. Hast du Mods oder ähnliches? vllt je nach Wetter lage, Ich wette wenn du das Bild oben unter gleichen Bedingungen machst siehst du aus wie vorher.

**Comment by WasabiMizz** [comment]
Nein leider nicht. Benutze keinerlei Mods. Es ist auch egal in welche Position ich die Bilder mache zum Vergleich. Die Augen sehen immer komplett anders aus sowie der Glanz auf der Strin und auf der Nase. Die Augen sind wie nicht richtig ausgeprägt nach innen, wie wenn etwas fehlt. Ich weiß nicht wie ich es sonst beschreiben soll, sorry. Aber andere haben das auch schon so bestätigt bei meinem Char gestern nach dem Update.

**Comment by CaleighRhodes** [comment]
Gibt mehrere Spielerinnen mit dem selben Problem

**Comment by CaleighRhodes** [comment]
Mal kurz als Info: Das Make-Up "Fast and Chic" verändert komplett das Gesicht, und daher kommt offenbar auch der Glanz:

![20220106125253_1](https://user-images.githubusercontent.com/74977218/148379130-34f482de-b36e-4c75-b785-585d8819228c.jpg)

![20220106125255_1](https://user-images.githubusercontent.com/74977218/148379151-d0c610e1-c44a-47ca-99d4-af862368378d.jpg)

**Comment by WasabiMizz** [comment]
Ja nice. Danke für die Info. Also sollte bei einem anderen Makeup dann alles wieder bei alten sein?

**Comment by CaleighRhodes** [comment]
Wir sind grad zufällig beim Friseur und haben Make-Ups durchprobiert und der Effekt kommt nur bei diesem.
