### ISSUE TITLE
Spritverbrauch Calico GTF (/neue Tunerkarren)

### ISSUE THREAD

**Issue by Erumeldor** [mexyn/statev_v2_issues#2186]
Der Spritverbrauch des Calico GTF ist etwas sehr krass.
Egal ob im Winter mit Winterreifen, oder jetzt aktuell ohne Schnee und mit diesen High-Performance-Reifen.

Aktueller Spritverbrauch ca 1l/km. Fahrzeug ist getunt, hat wie gesagt High-Performance-Reifen drauf und sonst keinerlei Fehler.

Habe mir sagen lassen das ist "normal" für die Fahrzeuge, und betrifft wohl auch andere Fahrzeuge die neu hinzugekommen sind (Jester RR), aber da wohl nicht soo extrem.

Dafür das die Kiste aktuell nicht mal ansatzweise konkurrenzfähig ist (bezogen auf Geschwindigkeit etc., dazu kommt bei Gelegenheit ein anderes Ticket), passt der Spritverbrauch da eigentlich nicht dazu. :)

**Comment by DonVitoDiangelo** [comment]
Alles i.O. hier
