### ISSUE TITLE
LSPD 404 Livery wechselt

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#2187]
**Beobachtetes Verhalten**

Dasselbe wie #2121 , aber LSPD 404

**Comment by milkdrops** [comment]
Also der neue Mustang, bereits bekannt

**Comment by v3rpl4nt** [comment]
Kurze Zwischenfrage, ist bei den Mustangs per Default eine feste Livery gesetzt? Also ähnlich wie bei den Scouts?
