### ISSUE TITLE
Phantom Custom kaputt ? (obwohl repariert + ausgelesen)

### ISSUE THREAD

**Issue by StateVSergio** [mexyn/statev_v2_issues#2188]
Sergio_Marquina

**Auftrittszeitpunkt (Datum / Uhrzeit)**

05.01-06.01 ca 23-1 eingetreten und nicht wieder behoben

**Beobachtetes Verhalten**

Phantom wurde repariert und ausgelesen , danach kaputte teile ausgetauscht sowie eco reifen drauf gezogen. Danach ca 10 km gefahren und aus dem nichts Probleme beim beschleunigen und allgemeinen fahren. Mit Ölachse sind leichte steigungen nicht möglich und Vmax sind 60 kmh

Phantom danach nochmal ausgelesen - kein Fehler und normale sommerreifen draufgezogen. --> Problem besteht immernoch

**Optional: Video / Bilder des Fehlers**
(https://www.youtube.com/watch?v=ar68REb6Kto)

komplett vollgas ....

Fährt sich wie mein verschrotteter LKW mit 56k km ... unbrauchbar totalschaden
(hat mittlerweile das selbe kennzeichen aber sollte nicht im zusammenhang stehen)

**Comment by epichalt** [comment]
Mittlerweile mehren sich die Beschwerden über den Phantom custom. Manche fahren normal, andere kommen kaum den ölberg hoch. Obwohl keine Fehler vorhanden sind und die teilweise auch weit unter 10tkm haben

**Comment by l4m4rr224** [comment]
Kann ich so bestätigen... Unsere Phantoms einmal mit 1500 km und einmal mit nichtmal 700 km kommen auf dem Ölfeld nicht über 50 km/h

**Comment by SatyriaDine** [comment]
Same Here. Phantom Custom gerade 700km runter von jetzt auf gleich kaum mehr Leistung

**Comment by SatyriaDine** [comment]
Ich hab von meinem Phantom dann auch mal noch ein Video gemacht. Hoffe das hilft weiter und das Problem kann gefixed werden. 

https://www.youtube.com/watch?v=7UhFvQEuhLA

**Comment by Dean-Gallagher** [comment]
Phantoms die mit ÖL Achse um die 90 fahren sind IO da die anderen auch nicht schneller sind.

**Comment by epichalt** [comment]
> Phantoms die mit ÖL Achse um die 90 fahren sind IO da die anderen auch nicht schneller sind.

Die fahren aber 90 ohne Achse und mit Achse kommt man nicht mal mehr den Berg hoch.

**Comment by StateVSergio** [comment]
Wenn man vom Export mit Achse nicht mehr wegkommt weil der Berg zu steil ist hat das nix mehr mit io zu tuhen. Der Phantom ist ein Wrack du bist ihn ja selber gefahren. 

Irgendwie hab ich das Gefühl das die Ölachse etwas damit zutuhen hat ...
Ich hoffe das Problem kann bald behoben werden da ich auf den lkw angewiesen bin.

**Comment by SatyriaDine** [comment]
@Dean-Gallagher dass die Phantoms mit Öl Achse ausgebremst sind ist klar. Mein Phantom ist aber bis gestern Vormittag mit Öl Achse noch knappe 120 gefahren. Und war allgemein nicht so schwerfällig wie jetzt. 
Ich hab den direkten Vergleich, da ich bis vor kurzem noch nen Phantom mit 24.000km gefahren bin und der weißt genau das Fahrverhalten auf, welches mein neuer mit gerade einmal 700km aufweist. Auch ohne Öl Achse hinten dran ist der schwerfällig und in der Endgeschwindigkeit komplett ausgebremst.

**Comment by l4m4rr224** [comment]
Ja ein NORMALER Phantom fährt mit Öl-Auflieger 90 auf dem Highway...wir reden aber vom Phantom Custom...ein NEUER Phantom Custom...Es kann nicht sein das ein neuer Phantom Custom wie aus dem nichts aufeinmal nur noch 40km/h auf dem kleinen Ölfeld macht obwohl er vorher normal gefahren ist...
Wenn ich z.b einen Packer denn sehe der mit guten 80 auf dem Ölfeld langfährt kann da was nicht stimmen...
Zumal wir auch alles Ohne Auflieger getestet haben.
Phantom Custom (700 km)mit auflieger  90-100   / ohne  130 km/h    (Normal ohne auflieger ca 160-180)
Phantom Custom ( 1500 km ) mit auflieger 90-100  / ohne 130 km/h  (Normal ohne auflieger ca 160-180)
Phantom Custom ( 24.000 km) mit auflieger 90-100  / ohne 130 km/h 
Phantom normal (1300 km) mit auflieger  80 - 100  / ohne ~ 130 km/h
Packer ( 19.000 km ) mit auflieger kommt auf die doppelte Geschwindigkeit 
Und das sind nur die Highway werte...
Aber wenn ich sehe das unser Phantom bis gestern Nachmittag eigentlich auf dem kleinen Ölfeld mit 80 zur ersten Pumpe hochgefahren ist und aufeinmal nicht mal mehr wirklich die 80 auf normaler straße bringt..kann da etwas nicht stimmen

**Comment by SatyriaDine** [comment]
Hier noch ein Video vom Phantom Custom den @l4m4rr224 angesprochen hat mit mittlerweile 1500km. Zum damaligen Zeitpunkt noch 140km. Hier merkt man keinerlei Schwerfälligkeit. 

https://www.youtube.com/watch?v=cpoQ2b1YeSw

**Comment by cadpri** [comment]
Welche Reifen habt ihr drauf?
Mein Barracks fährt nämlich, seitdem er EcoFuel Reifen drauf hat, mit Öl Auflieger ein kleines bisschen langsamer und kommt manchen Berg schwerfälliger hoch.
Der Berg an der 6ten Pumpe am kleinen Ölfeld zb jetzt nur noch mit 20 kmh.
Vorher mit 30kmh

**Comment by SatyriaDine** [comment]
Auf dem mit 700km haben wir aktuell EcoFuel drauf. Habe da auch gemerkt dass da Einbußen sind. Aber das war nicht so heftig wie es jetzt ist. Der Custom fährt halt wirklich so als wäre er altersschwach.

**Comment by l4m4rr224** [comment]
Gestern Vormittag mit den Eco knapp 120 statt den 125/130 mit ECO. Nach dem Restart kam der verlust  auf satte 80-100 km/h

**Comment by Dean-Gallagher** [comment]
https://pic.statev.de/i/aLRoS.jpg
https://pic.statev.de/i/aLk9g.jpg
https://pic.statev.de/i/aLsdI.jpg
https://pic.statev.de/i/aLh0m.jpg
https://pic.statev.de/i/aL8JV.jpg

achtet genau auf den Kilometerstand .. hab extra mal unsere alte Mumu ausgegraben. 
wurde auf dem LiveServer gemacht, mit LA Roads da so ein direkter vergleich möglich ist
liegt also entweder am Zustand, Reifen oder Tuning.

Der Themenersteller hat ein ganz anderes problem wie ihr hier beschreibt.

**Comment by epichalt** [comment]
@Dean-Gallagher 
Du verstehst nicht so ganz um was es geht, aber ich erkläre es dir gerne nochmal. 

Es herrscht ein Problem mit dem Phantom Custom in Kombination mit der Tanker Achse. Kein generelles Problem, da nicht alle betroffen sind. 

Es ist kein Tuning, Zustand oder Reifen Problem. Der Fehler kam auch nicht mit dem letzten Update sondern besteht seit dem vorletzten Update bereits. 
Wir hatten auch den Fall, dass plötzlich der Phantom Custom wieder normal gefahren ist nach einigen Hundert Kilometern. Hier wurden Videos geschickt von einem fast neuen Phantom Custom, der kaum die 90 packt und dein „Gegenargument“ ist, dass dein LkW mit 22tkm völlig normal fährt?!

Gefühlt besteht der Fehler seit dem Altv Update. Iwas beißt sich da mit Verschleißsystem und triggert da neue Phantoms so zu fahren als ob sie recycled werden müssten. 

Es wurden Winterreifen bei Schnee, sowie Winter-, Sommer-, und Ecoreifen bei wieder freien Straßen getestet. Keine Fehler beim Auslesen und wenig Kilometer <1tkm -

**Comment by FriedrichArnold** [comment]
@epichalt dieses Problem ist aktuell mit vielen Phantoms, bei mir ist auch das Problem allerdings auch Solo oder mit einem Trailer Large über die Tankachse braucht man nicht Reden ;D aber leider ist das auch bei meinem normalen Phantom so beide habe sie um die 10k km und der Fehlerspeicher ist leer und bauen keine Leistung mehr auf. Wir haben aus Verdacht alles, was mit Leistung zu tun hat getauscht und es hat leider keine Wirkung gebracht... aktuell sieht man aufm Ölfeld immer mehr läute die das Gleiche Problem haben ich hoffe, dass es auf jeden Fall mal angeschaut wird.

Mit freundlichen Grüßen
:D

**Comment by xceliiex** [comment]
Bei mir ab heute gegen halb 11 ebenfalls von 7 bis 8 Acht eine Tour Öl gefahren alles fein. Ich logge mich aus logge mich wieder ein 2 Stunden später bekommt der Custom nicht mal saft um anzurfahren gesschweige kommt der Custom eine Steigung hoch und "stirbt" dabei. Bei 5.8k Km auf dem Custom

**Comment by l4m4rr224** [comment]
Phantom Custom / 278PS / ECO Reifen / Keine Schäden / 800KM / Kennzeichen: SUCCUBUS (gleiche Geschwindigkeit wie mit Winterreifen )
Phantom Custom / 278PS / Winterreifen / Keine Schäden / 1300KM / Kennzeichen: Wrack 39 ( gleiche Geschwindigkeit wie mit ECO )
Phantom / 456 PS / Sommerreifen / Keine Schäden / ~1500 KM / Kennezeichen Wrack 36

**Comment by Falk-Alers** [comment]
HVY Barracks Semi / 456PS / Sommerreifen / Keine Schäden / Keine Fehler / 66.6km / Kennzeichen: FROG I
Teststrecke Harmony Garage 31 Plz 716 nach Sandy Shores 852 
Max Geschwindigkeit 160~163 ohne Achse / Max Geschwindigkeit mit Achse "Trailer Large" 150~152

Phantom Custom / 278PS / Sommerreifen / Keine Schäden / Keine Fehler / 17020.1km / Kennzeichen: BULL
Teststrecke Harmony Garage 31 Plz 716 nach Sandy Shores 852
Max Geschwindigkeit 155~157 ohne Achse / Max Geschwindigkeit mit Achse "Trailer Large" 140~143

**Comment by SatyriaDine** [comment]
Phantom Custom / 278PS / Sommerreifen / keine Schäden / 900km gefahren Kennzeichen: SUCCUBUS

Extra gerade von ECO Fuel auf Sommerreifen gewechselt.

Verhalten bei ECO: 

Solo: Guter Anzug, Endgeschwindigkeit ca 120-130
mit Öl-Auflieger: sehr schwacher Anzug, Endgeschwindigkeit zwischen 90 und 100 (ähnelt sehr dem Fahrverhalten meines Customs mit 24k gefahrenen Kilometern

Verhalten bei Sommerreifen:

Solo: Guter Anzug, Endgeschwindigkeit ca 140-150
mit Öl-Auflieger: sehr schwacher Anzug, Endgeschwindigkeit zwischen 90 und 100 (im Prinzip hier auch gleiches Verhalten wie der altersschwache Custom)

Und ja, mir ist klar, dass der Öl-Auflieger Leistungseinbußen mit sich bringt. :D Weiß aber auch wie mein Custom gefahren ist bevor er nun vorzeitig gealtert ist. 

Verhalten bevor er vorzeitig gealtert ist: (mit Winterreifen und kurz nach dem Wechsel auf ECO auch noch)

Solo: guter Anzug, Endgeschwindigkeit ca 150-160
mit Öl-Auflieger: guter Anzug (kam am kleinen Ölfeld den Berg zur ersten Pumpe easy mit 70-80kmh hoch) Endgeschwindigkeit 110-120

**Comment by powerswissi** [comment]
bei 3300km und NACH regen und ECO Reifen bin ich jetzt auch bei der fehlenden Leistung angelangt

KEIN Fehler und KEIN Unfall

Sieht man bei mir übrigens im Stream.. hab noch gesagt oje da stimmt was nicht... Dann kam der regen .. hab ichs auf regen geschoben und jetzt bleibt dieses "verhalten" so nachdem der Regen weg war! .. Bin direkt auslesen gegangen aber kein fehler..

Auch getestet mit dem flatbet Trailer.

Alles in allem fehlt beim Packer Leistung.. Auch ohne Trailer

Fühlt sich an als würde jemand hinten die Handbremse ziehen.

**Comment by FriedrichArnold** [comment]
Sorry, dass ich hier mal so frage, aber gibt es vielleicht schon eine Lösung?
MfG

**Comment by StateVSergio** [comment]
Würde mich auch interrisieren hab seit 3 Wochen keine Zugmaschine :/

**Comment by powerswissi** [comment]
Kurze Info: 

Dieses Problem taucht abwechselnd auf.. 

Z.b auf dem Ölfeld.. manchmal komme ich den berg hoch, manchmal nicht.. 

Für mich hat er mal bisschen mehr Power, manhcmal bisschen weniger.. 

Der Packer fährt sich zur Zeit wie mein hauler mit dem 2.kleinsten motor!

**Comment by DonVitoDiangelo** [comment]
Also für uns innerhalb unserer Test Sessions, können wir kleine Auffälligkeiten feststellen.
Es gibt natürlich Einflüssen wie KM Stand, Reifen, Schaden, schlechtes Wetter, die einen Einfluss nehmen können. Daher achtet bitte darauf wann genau der Fehler auftritt. Wie gesagt, können wir derzeit nichts reproduzieren.

**Comment by powerswissi** [comment]
So siehts zur Zeit aus... 
3600km
KEINE Fehler
ECO Reifen
Kein Schaden
Schönes Wetter

Video ist angehängt.. 

https://www.twitch.tv/videos/1268652835?t=1h20m39s

**Comment by SatyriaDine** [comment]
Bei mir ist ebenfalls egal welches Wetter das gleiche Verhalten. 

mittlerweile 1000km
KEINE Fehler
Sommerreifen
Kein Schaden

Fahrverhalten wie in meinen oben bereits angehängten Videos.

**Comment by l4m4rr224** [comment]
Phantom Custom
1400KM
Winterreifen
Keine Schäden

verhält sich wie mit Sommerreifen und bringt keine Leistung

**Comment by FriedrichArnold** [comment]
Phantom Custom
11700 km
Sommerbereifung
keine Schäden
Fehlerspeicher Leer
es hat bei mir während es geregnet hat angefangen seit dem ist es dauerhaft da und wird immer Heftiger
keine Leistung mehr

https://www.youtube.com/watch?v=KeltztOeneU

https://www.youtube.com/watch?v=D5QNEFg-z1Q

**Comment by DonVitoDiangelo** [comment]
So meine Freunde der Sonne, gute Nachrichten. Das "Problem" wurde ausfindig gemacht bzw. rebalanced und wird mit dem nächsten Update aufgespielt. Bis dahin noch etwas gedulden. Damit sollten dann viele Fahrzeuge wieder "normaler" fahren.
