### ISSUE TITLE
Kein Wheely mehr mit Gauntlet Classic

### ISSUE THREAD

**Issue by Otacon225** [mexyn/statev_v2_issues#219]
**Artjom_Kaloshka**

**Beobachtetes Verhalten**
Bravado Gauntlet Classic macht keinen Wheely mehr.

**Erwartetes Verhalten**
Er zieht vorne Hoch.

**Comment by DonVitoDiangelo** [comment]
Mehr oder weniger so gewollt. Die Leistungen wurden angepasst.  Die entsprechende Leistung die hier notwendig wäre, würde das Gefüge wieder sprengen. Daher bleibt das so, sry.
