### ISSUE TITLE
Grafik Fehler im neuen kleid

### ISSUE THREAD

**Issue by StateV2Marie** [mexyn/statev_v2_issues#2192]
Danke der Dame auf dem bild kann ich nen Grafik fehler was reichweite des kleises angeben es handelt sich um die neuen kleider.

[https://pic.statev.de/image/kleidkaputt.aUr5k](url)

[https://pic.statev.de/image/kleidkaputt1.aUNWw](url)

weiß nich obs schon jemand gemeldet hat ich bin mal so frei

**Comment by Enemyaa** [comment]
@StateV2Marie Hm, also wir konnten das nachstellen. Ist zwar nicht bei jeder Person, aber ja.... Mal schauen, ob ich da was retten kann. Danke für die Info.

Tragt ihr das jetzt ic gar nicht mehr oder ist es halb so schlimm?

**Comment by ShauniKT** [comment]
Ich für meine  Teil finde es halb so schlimm. Mir ist das bisher noch gar nicht aufgefallen. Evtl. passiert das nur bei bestimmten Kombis?
Wäre für mich kein Grund es gar nicht zu tragen, da es ja ansonsten sehr gut "funktioniert".
