### ISSUE TITLE
Weed bei Jimmy nicht ablieferbar

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#2193]
**Character Name**
Paul Humpert / Patrick Nowak

**Auftrittszeitpunkt (Datum / Uhrzeit)**
09.01.2021 / 12:00

**Beobachtetes Verhalten**
Man konnte an bestimmten Punkten bei Weed-Abliefermissionen von Jimmy kein Weed ablegen. Es kam keine Fehlermeldung oder Nachricht. Vermutung: Wir haben davor einen Auftrag abgeschlossen und genau an den Punkten wo wir vorher abgeliefert haben konnten wir nicht nochmal was ablegen.

**Erwartetes Verhalten**
Man sollte das Weed an allen Stellen ohne Probleme ablegen können

**Schritte um den Fehler nachvollziehen zu können**
- Eine Mission bei Jimmy erledigt
- erneute Mission starten
- wenn die selben Punkte nochmal abgeliefert werden müssen, Versuch starten dort das Weed abzuliefern.

**Comment by CubeXLIVE** [comment]
Wie im Support besprochen hier die Videos zu den jeweiligen Spots. Wie Paul auch schon beschrieben hatte, haben wir diese Spots in einem Auftrag davor schon einmal angefahren.

https://streamable.com/28l0rd
https://streamable.com/dtsknh

**Comment by CubeXLIVE** [comment]
Noch ein Nachtrag. Grade bei Caleb im Stream passiert: https://www.twitch.tv/videos/1259310153?t=00h22m52s

Scheint wohl wirklich daran zu liegen, wenn man als Person einen zweiten Auftrag annimmt, und da nen Punkt bei ist, den man schon abgegeben hat, funktioniert der Punkt nicht mehr und somit kriegt man den Auftrag nicht fertig

**Comment by TheOutburst** [comment]
Wir konnten es soweit nachstellen, wenn man den selben Marker wie in einer Mission vorher bekommt geht dieser dann nicht.
(shitty) Workaround bis zum fix: game restart bevor man eine neue Mission annimmt.
