### ISSUE TITLE
Tuning vom Vapid Dominator GTT

### ISSUE THREAD

**Issue by Koray5858** [mexyn/statev_v2_issues#2194]
Jason_Rains

10.01.2022 10:00 Uhr

Das Tuning vom Dominator GTT ist komplett durcheinander, beim Spoiler verändert sich z.B. die Frontstoßstange oder die Motorhaube, beim Auspuff ändert sich die Karosserie aber am Auspuff selbst tut sich nichts und so zieht es sich durchs ganze Tuning.

**Comment by DrGrizzlY17** [comment]
Ist soweit kein Fehler von uns. Das geht leider auf die Kappe von GTA.
Um das kurz zu erklären.

Die Beschriftung in der Werkstatt der Tuningteile und den nötigen Items dafür sind entstanden
aufgrund der existierenden Tuning IDs die es in GTA gibt (https://wiki.altv.mp/wiki/GTA:Vehicle_Mods).
Daher kommt es immer mal wieder vor das es optisch nicht der Beschriftung entspricht, da geht
dem Fahrzeug einfach nen andere MOD ID gegeben hat, als z.B noch früher.

Im GTT scheinen die das mal ganz komplett weird gemacht zu haben.
Leider erstmal so zu ertragen, da wir sonst unser ganzes System umschreiben müssten
