### ISSUE TITLE
Gamecrash beim Weedausliefern

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#2197]
**Character Name**
Paul Humpert

**Auftrittszeitpunkt (Datum / Uhrzeit)**
10.01.2022 / 16:20

**Beobachtetes Verhalten**
Gamecrash während einer Weed Mission

**Erwartetes Verhalten**
Kein Gamecrash, möglicherweise das Weed zurückerstatten (40er Purple Auftrag, 12 bereits abgeliefert, 28 waren noch da siehe Video)

**Optional: Video / Bilder des Fehlers**
https://youtu.be/usg-nnUBYMg

**Comment by DonVitoDiangelo** [comment]
Wenn so etwas passiert, ist das ein Supportfall. Hier ist der Bugtracker. :)
