### ISSUE TITLE
Paisley Bandana V2 Gewicht

### ISSUE THREAD

**Issue by TamiGaming** [mexyn/statev_v2_issues#2198]
**Character Name**
Carlie Tacus

**Auftrittszeitpunkt (Datum / Uhrzeit)**
10.01.2022

**Beobachtetes Verhalten**
Paisley Bandanas V2 haben ein Gewicht von 0,80 kg anstelle von 0,08 kg wie alle anderen Bandanas.
![image](https://user-images.githubusercontent.com/40512639/148901850-eaec24a2-a580-4bec-82b8-ede2f86ca8de.png)

Betroffen sind folgende Bandanas [Maske]:
Gelbes Paisley Bandana V2, Weißes Paisley Bandana V2, Schwarzes Paisley Bandana V2, Lila Paisley Bandana V2

**Erwartetes Verhalten**
Bandanas sollten nur 0,08  kg wiegen

**Comment by Enemyaa** [comment]
Danke für die Info.

Next Update!

**Comment by TamiGaming** [comment]
Hab gestern gesehen, dass das gleiche auch für die neuen Sandanas gilt.
Wäre also cool, wenn du da auch nochmal rein schauen könntest. 
Dankeschön :)
