### ISSUE TITLE
Neue Paisley Sandanas mit [M] / [F] 

### ISSUE THREAD

**Issue by TamiGaming** [mexyn/statev_v2_issues#2199]
**Character Name**
Carlie Tacus

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit Ende November 

**Beobachtetes Verhalten**
Die neuen Paisley Sandanas sind nicht mehr "Unisex" sondern können nur von männlichen oder weiblichen Chars getragen werden. Ist das so gewollt? Da ja alle anderen Sandanas (auch Paisleys) Unisex sind. 
![image](https://user-images.githubusercontent.com/40512639/148902460-22b6f419-9864-4d68-ad20-3b5082a3020a.png)

**Erwartetes Verhalten**
Das die Paisleys auch ohne [M] / [F] bzw. geschlechtsunabhängig sind.

**Schritte um den Fehler nachvollziehen zu können**
Eines der neuen Sandanas herstellen. Siehe Bild oben.

**Comment by Enemyaa** [comment]
Die sind nicht unisex. Das stimmt schon so.
