### ISSUE TITLE
[Juwelier] Man kann nichts Kaufen

### ISSUE THREAD

**Issue by PrimroseBloom** [mexyn/statev_v2_issues#22]
**Zeitpunkt (Datum / Uhrzeit)**
25.08.2020 19:20

**Beobachtetes Verhalten**
Beim einkaufen im Juwelier stand man hätte nicht genug Geld dabei und Steuern konnte nicht berechnet werden.

**Optional: Video / Bilder des Fehlers**

![unknown (3)](https://user-images.githubusercontent.com/70226823/91208128-05ba3500-e70a-11ea-9609-e799db6e29fa.png)

**Comment by its4l3x** [comment]
Ist schon fixed, auf Update warten.
