### ISSUE TITLE
Funkgerät

### ISSUE THREAD

**Issue by EmilyGrant01** [mexyn/statev_v2_issues#220]
Es ist z.Z so das man nur ein Funkchannel nutzen kann, wenn man mehrere eingibt wird der erste nur "kopiert". Desweiteren wenn mann einen neuen Funk eingeben möchte, kann mann die letzte Zahl nicht löschen

**Comment by DonVitoDiangelo** [comment]
1. Bei mehreren Funk Channel, werden alle Zeilen über der aktiven mit geändert. (copy)

2. Letzte zahl löschen ist egal.

**Comment by its4l3x** [comment]
Kein Bug in dem Fall, sind sicherheitsabfrage, welche drinnen bleiben müssen.
