### ISSUE TITLE
Entferntes Helllila Paisley noch als Item "unisexmask1516" vorhanden

### ISSUE THREAD

**Issue by TamiGaming** [mexyn/statev_v2_issues#2200]
**Character Name**
Carlie Tacus

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit Ende November

**Beobachtetes Verhalten**
Die entfernten Helllila Paisley Bandanas sind noch als Item "unisexmask1516" vorhanden.
![image](https://user-images.githubusercontent.com/40512639/148903196-5880994c-b0d6-46d9-9bb8-51dff8c883e3.png)

**Erwartetes Verhalten**
Item sollte komplett entfernt sein.

**Comment by Enemyaa** [comment]
:thumbsup:
