### ISSUE TITLE
Phantoms Custom drastischen Leistungsverlust Fehlerspeicher leer

### ISSUE THREAD

**Issue by FriedrichArnold** [mexyn/statev_v2_issues#2201]
**Character Name**
Friedrich Arnold

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit dem 07.01.2022

**Beobachtetes Verhalten**
die Phantoms Custom Sowohl die Normalen haben Überhaupt keine Leistung mehr auch ohne Tank Achse Trotz Sommerbereifung ecos hatten wir nie darauf gehabt ist auch jetzt schon mehrfach im RP erwähnt worden, dass diese Fahrzeuge ein Softwareproblem haben. Ich habe unten für den Custom ein Video wie er sich mit Tank Achse fahren lässt, sowohl den Fehlerspeicher
**Erwartetes Verhalten**
mehr Grip und wider die ursprüngliche Fahrweise wie vorher, momentan sind sie fast nicht Nutzbar.

Video1: https://www.youtube.com/watch?v=KeltztOeneU
Video 2 Fehlerspeicher https://www.youtube.com/watch?v=D5QNEFg-z1Q

**Comment by Falk-Alers** [comment]
also mein phantom fährt ganz normal 
habe es aber OHNE achse/n getestet
fals das was hilft

**Comment by CaleighRhodes** [comment]
Mein Phantom Custom schafft mit voller Large-Achse nach wie vor knapp 160. Mit Winterreifen ohne Schnee war er etwas langsamer, aber dennoch annehmbar. Habe keine Leistungseinbußen, er hat aber auch noch keine 5.000 Kilometer runter.

**Comment by CatherineGallagher** [comment]
Uns ist das auch schon aufgefallen und wir gucken an was es liegen könnte, momentane vermutung unsererseits, das Gerät liest Fahrzeuge insbeosendere Phantoms nicht richtig aus. Heißt die Fahrzeuge haben Fehler, aber der Fehlerspeicher des Geräts bleibt leer. Es ist jetzt auch schon bei einem Toros aufgefallen.  Wir bekommen täglich die Klagelieder der Phantombesitzer zu hören ^^.
