### ISSUE TITLE
ADAC-Werkstatttor defekt

### ISSUE THREAD

**Issue by JohnMckansy** [mexyn/statev_v2_issues#2202]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

John_Mckansy

**Auftrittszeitpunkt (Datum / Uhrzeit)**

12.01.2021 20:30

**Beobachtetes Verhalten**

Durchfahrt in der Werkstatt ist von innnen nach aussen dauerhaft blockiert.
Meldung: "Etwas blockiert den Durchgang"

Werkstattfremde Spieler können die Werkstatt nicht alleine mit ihrem Fahzeug verlassen.
Die Fahrzeuge müssen vom Personal händisch ausgelagert werden.

Einfahrt funktioniert einwandfrei.

**Erwartetes Verhalten**

Spieler können von alleine mit "E" ausfahren /rausteleportiert werden.

**Schritte um den Fehler nachvollziehen zu können**

Reproduktion unbekannt

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TeubyDE** [comment]
Fehler bekannt. Sind dran.
