### ISSUE TITLE
Dominator GTT - Tuning vertauscht

### ISSUE THREAD

**Issue by thumbsucker** [mexyn/statev_v2_issues#2203]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Riley Everett

**Auftrittszeitpunkt (Datum / Uhrzeit)**
13.01.2022 ca. 0 Uhr

**Beobachtetes Verhalten**
Ich wollte bei meinem neuen Dominator GTT nach Folierungen gucken und musste dabei leider feststellen, dass das Tuning beim GTT noch vertauscht ist. Bei Folierungen wird der Spoiler geändert, bei Sitzen die Folie etc. 

**Erwartetes Verhalten**
Bei Fahrzeug Folierung sollte auch Folierung angezeigt werden etc. da dies sonst ausgenutzt werden kann um sich einen sehr billigen Spoiler auf Auto zu packen. 

**Schritte um den Fehler nachvollziehen zu können**
Siehe Videos

**Optional: Video / Bilder des Fehlers**
https://drive.google.com/file/d/1K5BDp1ey4v9B2bpfSdagamxtGub2tHHM/view?usp=sharing

https://drive.google.com/file/d/1gL42GqCItHCF4Uq7rNx8t6_VqQzZXH5t/view?usp=sharing

**Comment by CatherineGallagher** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2194

wurde erst vor kurzem beantwortet
