### ISSUE TITLE
Slucdie Customs Werkstatttor kaputt

### ISSUE THREAD

**Issue by Eve-Noxito** [mexyn/statev_v2_issues#2205]
## WICHTIGE INFORMATION!!:
```
Bei uns in der Werkstatt (Sludgie Customs im Mirror Park) funktioniert das eigenständige ausparken für Kunden nicht. Einparken klappt. 
```

**Eve_Noxito**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
<!Seit ca 11.01.2022 -->

**Beobachtetes Verhalten**
Beim Versuch von innen nach aussen durchs "Rolltor" zu fahren, kommt die Fehlermeldung: etwas blockiert den Durchgang

**Erwartetes Verhalten**
das man nach betätigung der Hupe ausgeparkt wird

**Schritte um den Fehler nachvollziehen zu können**
Haben das bereits mit verschiedenen Fahrzeugen und Charakteren geprüft, leider ohne Erfolg..und auch draussen in der ausparkzone geguckt ob eventuell Aufstellobjekte blockieren. dies ist nicht der Fall

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TeubyDE** [comment]
Bitte einmal im Support melden.

**Comment by TeubyDE** [comment]
Ist bekannt, Durchfahrt sollte wieder frei sein.
