### ISSUE TITLE
Beschleunigung vom Hellion

### ISSUE THREAD

**Issue by VitoCastellano** [mexyn/statev_v2_issues#2206]
**Vito_Castellano**

**Auftrittszeitpunkt:**
Seit dem 13.01.2022 ca. 18/19 Uhr

**Beobachtetes Verhalten:**
Seit 18/19 Uhr beschleunigt der Hellion kaum noch. 
Vor dem besagten Zeitpunkt bin ich ca. 3 Stunden lang in der Klettermine gewesen und ohne Probleme mit dem Hellion hochgekommen. Seit 18/19 Uhr beschleunigt der Hellion kaum noch, weshalb ein befahren der Klettermine nicht mehr möglich ist.
Ich war nach diesem "Vorfall" bei Sludgies und habe mein Auto auslesen lassen. Kein Fehler.
Im Anschluss war ich zur Kontrolle nochmal bei Hell Gates. Kein Fehler. Habe mein Auto extra nochmal reparieren lassen, das Auto wies dennoch keine Besserung auf. Das Ein- und Ausparken hat ebenfalls nicht geholfen.
Ich habe ebenfalls Mike Ehrmantraut, "Mücke", sowie Peggy Black den Hellion fahren lassen. Die 3 Personen bestätigten mir ebenfalls, dass das Auto ungewöhnlich langsam beschleunigt und sehr wenig Power aufweist.

**Erwartetes Verhalten:**
Kraftvolles Beschleunigen bei niedriger Geschwindigkeit bzw. aus dem Stand.

**Schritte um den Fehler nachvollziehen zu können:**
Ins Auto setzen und ab geht's! Leider nur etwas langsamer als gewöhnlich :(

**Comment by VitoCastellano** [comment]
Falls es irgendwie bei der Fehlersuche helfen sollte, der besagte Hellion läuft auf meinen Namen mit dem Kennzeichen "SIGSAUER"

**Comment by VitoCastellano** [comment]
Kleines Addon: Beim Toros scheint das Problem auch aufzutreten. Das Ding kommt einfach nicht mehr aus dem Arsch.

**Comment by DonVitoDiangelo** [comment]
Bleibt dieser jetzt immer in dem Leistungsbereich oder war das nur an dem Tag der Fall?

**Comment by VitoCastellano** [comment]
Also der Toros, sowie der Helion beschleunigt gefühlt wie ein Surfer, aber sobald er ein wenig fahrt aufgenommen hat, dann geht es einigermaßen. Habe aber das Gefühl, dass die Maximalgeschwindigkeit nicht erreicht wird. 
Mich verwundert das extrem, dass mein Helion gefühlt nicht aus dem Arsch kommt was die Beschleunigung angeht und einige scheinen da gar kein Problem mit zu haben. Scheint wohl wirklich an meinem Helion bzw. Toros zu liegen.

**Comment by VitoCastellano** [comment]
Habe den Helion zuletzt vor ca. 2 Tagen bewegt, da war das Problem immer noch aktuell.
