### ISSUE TITLE
Heroin Ablagepunkt nicht nutzbar

### ISSUE THREAD

**Issue by Ohio1337** [mexyn/statev_v2_issues#2207]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Mig_Jacoby

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14.01.21 ca. 13:45 Uhr

**Beobachtetes Verhalten**
Der Ablagepunkt für Heroin kann nicht benutzt werden

**Erwartetes Verhalten**
Ablagepunkt sollte benutzt werden können

**Schritte um den Fehler nachvollziehen zu können**
Heroin ausliefern und diesen Punkt beliefern

**Optional: Video / Bilder des Fehlers**

![Grand Theft Auto V Screenshot 2022 01 14 - 13 42 18 80](https://user-images.githubusercontent.com/29641551/149517867-6ae7746f-f184-4612-ab77-9e1c1bd0e3a1.png)
![Grand Theft Auto V Screenshot 2022 01 14 - 13 42 24 19](https://user-images.githubusercontent.com/29641551/149517875-9f50ae01-34ce-415c-b3bd-2ac65354bf9b.png)
![Grand Theft Auto V Screenshot 2022 01 14 - 13 42 35 51](https://user-images.githubusercontent.com/29641551/149517879-9255bc02-2577-45bd-972d-1e320b4f6bb2.png)

**Comment by TheOutburst** [comment]
#2193
