### ISSUE TITLE
Fehler mit Checkpoints auf Strecke bei Grapeseed

### ISSUE THREAD

**Issue by Pregon** [mexyn/statev_v2_issues#2208]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Ronny Roberts

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14.01.2022 11:44:18 Uhr

**Beobachtetes Verhalten**
Beim Zeitfahren reagiert Checkpoint 5 auf der Strecke um Grapeseed nicht, während man mit einer Carbon RS unterwegs ist

**Erwartetes Verhalten**
Checkpoint 5 reagiert wie alle anderen Checkpoints und ist einsammelbar

**Schritte um den Fehler nachvollziehen zu können**
Zeitfahrevent um Grapeseed annehmen und dieses mit der Carbon RS starten und durch Checkpoint 5 fahren

**Optional: Video / Bilder des Fehlers**

https://user-images.githubusercontent.com/75855042/149521221-e5543bb1-59e2-4a49-9eb6-3d55487f89c4.mp4

**Comment by Pregon** [comment]
Gerade erneut probiert, geht leider doch noch nicht.

**Comment by TeubyDE** [comment]
@Pregon Wir setzen den "solved" Status immer wenn es auf dem Dev Server behoben ist.
Somit kommt es beim nächsten Update auf den Live Server. 
Wenn das passiert ist, wird der Issue final geschlossen.
Somit vollkommen "normal" das es noch nicht fixed aufm Live ist ;)

**Comment by Pregon** [comment]
Achso ok gut, wusste ich noch nicht, danke für die Info
