### ISSUE TITLE
Gesichtsbemalungs Bug

### ISSUE THREAD

**Issue by StateV2Marie** [mexyn/statev_v2_issues#2209]
Hi hab nen Kunden gehabt sowas hab ich noch nich gesehen auf dem Schminkstuhl hieß es er sei Natürlich aber war es nich denn der gute hatte eine bemalung als wäre er von der bundeswehr war nich so weg ging wir haben ihn einfach auf den schminkstuhl gesetzt einmal nach links dann wieder zurrück und er war wieder sauber hab dadurch das es nen bug war aber nich berechnet was auch egal is haben es halt aus gespielt das er beim flug eingepennt is und er bemalt worden is hehe.. aber nur damit ihr bescheid wisst es gibt ein bug der leute die vor jahren weg sind nu wieder da sind aussehen können wie von der Arme ^^

[https://pic.statev.de/image/komischemaske.uH2ft](url)

**Comment by TeubyDE** [comment]
Danke für die Info.
