### ISSUE TITLE
Reden durch Wände nach wie vor möglich

### ISSUE THREAD

**Issue by 3xcu** [mexyn/statev_v2_issues#221]
Beobachtet durch: Nick Bishop
Jederzeit reproduzierbar

In den Betatests war es so dass die Stimmen anderer Spieler durch Wände/Türen nur sehr leise und abgedumpft waren. Dies ist es jetzt nicht so und man kann statt dessen durch das PD schreien bspw.

**Comment by tastydev** [comment]
War noch nie so mit dem leise sein etc.  Allerdings sollten nur Leute die schreien (größte reichweite) hörbar sein durch Wände. Das war auch schon auf RageMP so.
