### ISSUE TITLE
StateNet: Businessfinance Component reloaded nicht

### ISSUE THREAD

**Issue by RealSocius** [mexyn/statev_v2_issues#2211]
**Auftrittszeitpunkt (Datum / Uhrzeit)**
14:30 - 19.01.2022

**Beobachtetes Verhalten**
Wenn ich von z.B. Lager -> Finanzen auf Lager2 -> Finanzen wechsle, dann werden weiterhin noch die Finanzen von Lager1 angezeigt.

**Erwartetes Verhalten**
Finanzen von Lager 2 werden angezeigt.

**Lösungsansatz**
https://stackoverflow.com/questions/40983055/how-to-reload-the-current-route-with-the-angular-2-router

**Comment by epichalt** [comment]
ist bereits bekannt, lt. Forenaussage usw. wird es aber sowieso eine Statenet Überarbeitung geben. deswegen wird da wohl aktuell nix geändert

**Comment by RealSocius** [comment]
Passt, dann closed
