### ISSUE TITLE
Abschließen fehlerhaft

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#2213]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Sven_Rosenbach
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Seit einigen Wochen
**Beobachtetes Verhalten**

Wenn man ins Fahrzeug einsteigt und abschließt steigt der char wieder aus
**Erwartetes Verhalten**

Char bleibt wie früher im Fahrzeug Sitzten
**Schritte um den Fehler nachvollziehen zu können**

Auto nach dem einsteigen abschließen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://streamable.com/o5ayn8

**Comment by DonVitoDiangelo** [comment]
Erst reinsetzen, dann abschließen. Du machst es schlicht zu schnell.

**Comment by SHaagmann** [comment]
> Erst reinsetzen, dann abschließen. Du machst es schlicht zu schnell.

Gut weiß ich bescheid. War halt früher nicht der fall und bei Sekunde 12 Sitzt mein char z.B. auch komplett im Auto und hat schon die Tür zu gemacht und steigt trotzdem aus, deswegen war ich verwundert
