### ISSUE TITLE
Lippenstift auftragen Ungültiger Vorgang

### ISSUE THREAD

**Issue by Saaria83** [mexyn/statev_v2_issues#2215]
Hanna Fields, Marie Pech, Silia Gambino, Chayenne West

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.01.2022 ggn. 16 Uhr

**Beobachtetes Verhalten**
Lippenstift lässt sich nicht auftragen. 

**Erwartetes Verhalten**

Dass sich der Lippenstift auftragen lässt

**Schritte um den Fehler nachvollziehen zu können**
Kunde setzt sich auf den Schminkstuhl und lässt sich den Lippenstift auftragen

Diese Meldung kommt, wenn man den auftragen möchte.
Normale Schminke ausprobiert, dass geht ohne Probleme

![GTA5_EnJbAGeFAz](https://user-images.githubusercontent.com/70151476/150549814-78da3760-830a-4fb7-8b4e-e3ed68ecbd41.png)

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Alle Items vorhanden gewesen?

**Comment by Saaria83** [comment]
Ja war alles da. Aber uns ist aufgefallen, dass es welche gibt, die wohl funktionieren. Wir setzen und heute Abend dran und schauen durch

**Comment by Saaria83** [comment]
Gloss Rouge Amour
Gloss Punch 
Gloss Pink Exaltation
Gloss Pink Seduction
Gloss Lazy
Gloss Dangerous
Gloss Emotion
Gloss Honesty
Gloss I´m Nude
Gloss Nudest


Diese Lippenstifte mit Gloss funktionieren einwandfrei. Die anderen allerdings nur, wenn man die Intensität ändert .
Das ist nur bei den Frauen. Bei den Männern allerdings funktionieren sie.

Bei den anderen Effekten wie Matt, verschmiert etc funktionieren alles ganz normal.

Ja, wir haben darauf geachtet dass wie alle Materialien haben
Und ja, auch haben wir darauf geachtet dass der Kunde/Kundin nicht erst vor kurzem da war

Getestet (wie üblich) von UniCut und die Schererei

**Comment by DrGrizzlY17** [comment]
Wenn ihr nicht die Intensität ändert, kommt diese Fehlermeldung oder wie?
Die Fehlermeldung die ihr habt, kommt nämlich nur wenn Items fehlen, deswegen frag ich so

**Comment by Saaria83** [comment]
Wir haben das bei 3 Läden getestet, alle hatten alle Materialien da und nichts ging bei denen, die ich erwähnt habe. 
Die Fehlermeldung kommt, sobald man einer Kundin einen der Lippenstifte auftragen möchte. Ausgangsintenstität 0,5. Dann kommt die Fehlermeldung. Sobald man aber bei den Lippenstiften die Intensität erhöht oder niedriger macht, dann gehts. Es sollte aber immer funktionieren.

Zusätzlich ist uns heute aufgefallen, dass wir Friseure die Schminke bei Männern nicht mehr sieht. Bei Frauen ja aber nicht mehr bei Männern. Ob normale Schminke oder Gesichtsbemalungen.

**Comment by DrGrizzlY17** [comment]
Ich schaus mir an :)

**Comment by Saaria83** [comment]
Offensichtlich war der Fehler nur von kurzer Dauer. Auch hatte Fawkes das Problem, keine Frisuren zu machen, da etwas fehlte, was aber eigentlich da war. 
Aktuell scheint wohl alles zu gehen.
