### ISSUE TITLE
Fehlermeldung bei Automatbenutzung

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#2216]
**Character Name**
Paul Humpert

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.01.2022 / 16:48

**Beobachtetes Verhalten**
Bei öffnen von Automat kam der angefügte Fehler

**Erwartetes Verhalten**
Fehler sollte nicht auftreten

**Schritte um den Fehler nachvollziehen zu können**
- An den Automat gehen
- Automat mit e betätigen

**Optional: Video / Bilder des Fehlers**
![Automat bug](https://user-images.githubusercontent.com/74912696/150645820-8e43876d-19c5-4a5f-b00c-6ce6f9b49f24.PNG)

**Comment by TeubyDE** [comment]
Tritt das bei jedem Automaten auf oder nur bei einem bestimmten?
Hast du, wie im Text beschieden, den Box Inhalt kopiert ?

**Comment by Humperrrt** [comment]
Hallo,

den Inhalt von der Box konnte ich leider nicht kopieren, das hat nicht funktioniert. Um diese Zeit gestern kam das nur bei dem Automaten und jetzt gerade kann ich den automat auch wieder normal nutzen.

**Comment by TheOutburst** [comment]
Bei UI crashes wie diesem brauchen wir immer den gesamten Fehler in der weißen Textbox. Ohne den können wir da leider nicht viel machen. Ich mache hier grad mal zu, solltest du nochmal bei nem ATM nen UI crash hast pack den hier drunter oder in nen neuen tracker.
