### ISSUE TITLE
Patienten Teleport (Dach) fehlerhaft

### ISSUE THREAD

**Issue by WoahJeesus** [mexyn/statev_v2_issues#2217]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Jonny Parkinson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Fehlerhaft bei jeder Einlieferung über den Hubschrauber.

**Beobachtetes Verhalten**
Wenn wir stabilisierte Spieler über das Dach einliefern wollen, werden diese nicht in den Schockraum teleportiert.

**Erwartetes Verhalten**
Stabilisierte Spieler werden auch über das Dach in den Schockraum teleportiert.

**Schritte um den Fehler nachvollziehen zu können**
1. Spieler umhauen
2. Bewusstlosen Spieler stabilisieren
3. Auf die Trage legen
4. In den Helikopter einladen
5. Aufs MD Dach fliegen und auf der gelben flagge (Marker) landen
6. Spieler versuchen über "E" in den Schockraum zu teleportieren

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2438
