### ISSUE TITLE
Darstellungsfehler Dienstkleidung

### ISSUE THREAD

**Issue by h3adbang3r** [mexyn/statev_v2_issues#222]
**Thorlic_Redoran**

**Zeitpunkt (Datum / Uhrzeit)**
Serverstart und bisher unverändert

**Beobachtetes Verhalten**
Kleidung "[M][U]" bugt durch den Skin der Dienstkleidung

**Erwartetes Verhalten**
vorhandene Kleidung nicht sichtbar bzw.  unter der Dienstkleidung

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1280

**Optional: Video / Bilder des Fehlers**
![2020_1120-104718 (2)](https://user-images.githubusercontent.com/15799077/99791008-3fda7d80-2b25-11eb-8941-409a27534015.png)

**Comment by its4l3x** [comment]
Problem von den Leadern, welche die Skins erstellen. - Kein Fehler.
