### ISSUE TITLE
Import Anzeige Baller ST

### ISSUE THREAD

**Issue by PrimroseBloom** [mexyn/statev_v2_issues#2220]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Primrose Bloom

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.1.22.14:20

**Beobachtetes Verhalten**
Import Name vom Baller ST wird falsch angezeigt

![Unbenannt](https://user-images.githubusercontent.com/70226823/150680578-fa00f959-9e97-4d6e-93b1-ee5248906897.JPG)

**Comment by epichalt** [comment]
@DrGrizzlY17 Motor weiterhin nicht abholbar im Import
