### ISSUE TITLE
Schlüssel löschen

### ISSUE THREAD

**Issue by ShoxqZ1312** [mexyn/statev_v2_issues#2221]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**Ace Kings
 Ace Kings

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Allgemein

**Beobachtetes Verhalten**
 Wäre cool, wenn man diese Löschbestätigung hat bei den Schlüssel, wie bei dem Funk. In der Vermietung nicht so geil, wenn man ausversehen den Key löscht ^^.

**Erwartetes Verhalten**
 Mit Löschbestätigung 

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Hier bitte nur Bugs posten. Vorschläge bitte in das Forum, danke.
