### ISSUE TITLE
Änderung beim Haus

### ISSUE THREAD

**Issue by MisterGarry** [mexyn/statev_v2_issues#2222]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Brain Garry

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Seit V2

**Beobachtetes Verhalten**

Beim Umzug auf V2 ist unter dem Carport Sperrmüll entstanden (alte Möbel und gegenstände)
Fahrzeuge können nur noch bedingt drunter gestellt werden bis garnicht.
Beziehungsweise bedingt bei kleinern Autos.

Wenn möglich bitte einen Garagenplatz hinzufügen, da ein Carport vorhanden ist.
Haus Hash:  SandyShores1

**Erwartetes Verhalten**

Müll und alte Möbel entfernen 

**Optional: Video / Bilder des Fehlers**

**Comment by milkdrops** [comment]
Da dies eine Fabrik ist und kein Haus, wird kein Garagenpunkt hinzugefügt, um Autos einzuparken.

Es besteht die Möglichkeit, gewisse Objekte zu entfernen - aber persönlich finde ich, dass es einen guten Flair für das Gelände macht.
Im Schuppen neben der Fabrik gibt es ebenfalls genug Platz, Autos zu parken.

**Comment by milkdrops** [comment]
Upsi - derselbe Hash mit dem selben Besitzer war wohl auch ein Haus in Grapeseed.
Garage ist hinzugefügt im nächsten Update.

Falls Objekte entfernt werden müssen, bitte mit Bildern eine neue Issue öffnen.

**Comment by MisterGarry** [comment]
Ok hatte nur den Haushash hinzugefügt, dachte es würde reichen. Dachte die Hash's sind Einzigartig und würde reichen. 

Danke euch !

**Comment by MisterGarry** [comment]
> Upsi - derselbe Hash mit dem selben Besitzer war wohl auch ein Haus in Grapeseed. Garage ist hinzugefügt im nächsten Update.
> 
![20220204220401_1](https://user-images.githubusercontent.com/76521332/152602835-e73a1bbc-9332-4269-aee2-7df5091d49fd.jpg)

> Falls Objekte entfernt werden müssen, bitte mit Bildern eine neue Issue öffnen.

Bin gerade rein nach Update: keine Veränderung am Haus.

**Comment by milkdrops** [comment]
Verzeihung, erneute Hashverwechslung. Jetzt ist es aber drin, demnächst auch auf dem Live Server.
