### ISSUE TITLE
Bike Schlüssel

### ISSUE THREAD

**Issue by StateV2Marie** [mexyn/statev_v2_issues#2224]
Hallo hab jemand nen schlüssel von meiner Nightblade gegeben und wolte der Person den Schlüssel wieder entziehen was aber nich geht sobald ich auf den müll eimer zum löschen gehe steht da das is nich möglich? is das nen bug oder gehts allgemein nich was da los? oder liegts an mir?  [https://pic.statev.de/image/gehtnichweg1.usIUT](url)    << Bild is dabei

**Comment by epichalt** [comment]
Also lösche fast täglich Zugänge zu Fahrzeugen. Sollte also schon gehen. Mögliche Fehlerquellen wären:
1. Bike gehört evtl nicht dir und die andere Person hat auch Admin Zugang?
2. du stehst vlt zu weit weg vom Bike (vlt buggt das iwie und da hilft evtl ein-und ausparken)
3. evtl. doch ein Bug :D

**Comment by StateV2Marie** [comment]
ne es is mein bike und nein sie hat kein admin zugang siehe bild das is wie meldung die da kommt leider bekomme ich sie nich aus dem schlüssel raus

**Comment by StateV2Marie** [comment]
und ich habs mehr mals ein aus geparkt werd es gleich nach server neustart noch einmal versuchen.

**Comment by StateV2Marie** [comment]
geht nich gleiche meldung obwohls mein bike is und keiner admin recht hat nur ich selbs da es meins is

**Comment by DrGrizzlY17** [comment]
Hi, wenn welchen User hast du versucht aus der Liste zu entfernen?

**Comment by TheOutburst** [comment]
@StateV2Marie
