### ISSUE TITLE
Fehler nach dem Kiffen Effekt

### ISSUE THREAD

**Issue by MrsSykes** [mexyn/statev_v2_issues#2225]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Madison Cole

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.01.2022, ca 18:30

**Beobachtetes Verhalten**
Nachdem der Effekt vom kiffen weg geht, bekommt man ein ugly male face

**Erwartetes Verhalten**
Gesicht sollte bleiben wie es ist

**Schritte um den Fehler nachvollziehen zu können**
Joint rauchen, Effekt abwarten, nach Beendigung des Effekts ist das Gesicht da

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
https://youtu.be/UWEAo863Nt8

**Comment by its4l3x** [comment]
Duplicate #2171
