### ISSUE TITLE
Fehlende Darstellung von Maskierungen/Kopfbedeckungen/Frisuren in Fahrzeugen 

### ISSUE THREAD

**Issue by Wheazle** [mexyn/statev_v2_issues#2226]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Aaron Reed

**Auftrittszeitpunkt (Datum / Uhrzeit)**
permanent

**Beobachtetes Verhalten**
Maskierungen/Kopfbedeckungen/Frisuren sind für andere Spieler teilweise nicht mehr sichtbar wenn man in ein Fahrzeug steigt. Ebenfalls ist es für einen selbst nicht mehr sichtbar.

**Erwartetes Verhalten**
Maskierungen/Kopfbedeckungen/Frisuren sollten bei einsteigen in ein Fahrzeug nicht verschwinden.

**Schritte um den Fehler nachvollziehen zu können**
z.B. Fisherman Beanie aufziehen und in ein Fahrzeug steigen. Oder Helm aufziehen und in ein F1 Fahrzeug setzen.

**Comment by TeubyDE** [comment]
Kann mich auch täuschen, aber das ist meines Wissens nach ein "normales" GTA verhalten. 

Wenn man in eine Fahrzeug einsteigt wird die Kopfbedeckung entfernt. 
Wenn man aussteigt wird diese wieder hinzugefügt.

Das mit den Frisuren kann ich mir auch nur so erklären. Dadurch das du bei den Kopfbedeckungen die Möglichkeit hast im Kleidungsmenü die passenden Haare auszuwählen, sitzt man dann halt im Auto mit dieser gewählten Frisur.



@TheOutburst @DrGrizzlY17 wie steht ihr das?

**Comment by Hutstaender** [comment]
Ja das passiert automatisch, und wir haben aktuell keinen Workaround dafür.
