### ISSUE TITLE
Tannenholzbretter nicht in die trailer-achse verladebar

### ISSUE THREAD

**Issue by RobMccoy** [mexyn/statev_v2_issues#2227]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Rob Mccoy

Rob Mccoy
**Auftrittszeitpunkt (Datum / Uhrzeit)**

25.01.2022 13.10Uhr
**Beobachtetes Verhalten**

Tannenholzbretter lassen sich nicht wie normale Holzbretter in eine Trailer-Large-Achse verladen ( Fehlermeldung falsche Transportgruppe).
**Erwartetes Verhalten**

Die tannenholzbretter sollten sich wie normale Holzbretter in eine trailer-large-achse verladen lassen können, in einen Pounder oder Sandking lassen sie sich schließblich auch ohne Probleme ein- bzw ausladen.
**Schritte um den Fehler nachvollziehen zu können**

**Comment by KingMarcel** [comment]
mit dem nächsten Update behoben
