### ISSUE TITLE
Handbremse löst sich nach Serverneustart

### ISSUE THREAD

**Issue by PhilMorrison93** [mexyn/statev_v2_issues#2228]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name** Philipp Morrison

Philipp Morrison
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Schon länger, zuletzt heute 15:30 Uhr nach Serverneustart
**Beobachtetes Verhalten**

Fahrzeug/Fahrzeuge wurden mit angezogener Handbremse abgestellt. Nach erneutem Log In, nach Serverneustart, waren die Handbremsen an allen Fahrzeugen gelöst. (Streiter, Burrito, Hauler)
**Erwartetes Verhalten**

Handbremse sollte weiterhin angezogen bleiben
**Schritte um den Fehler nachvollziehen zu können**

Fahrzeug vor Restart mit angezogener Handbremse abstellen, auf Serverrestart warten und nach erneutem Log In, nach Restart prüfen. 
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TeubyDE** [comment]
Ist leider aufgrund von Sync Problemen nicht umsetzbar.
