### ISSUE TITLE
Objektplatzierung

### ISSUE THREAD

**Issue by MaxwellRicks** [mexyn/statev_v2_issues#2229]
Charaktername:
Maxwell_Ricks

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.01.2022, 16 Uhr

**Beobachtetes Verhalten**
ich kann nur 1 Objekt platzieren, danach sagt das Game mir, dass ich zu viele Objekte platziert habe, obwohl ich meines Wissens nach keine weiteren Objekte platziert habe

Bitte alle von mir platzierten Gegenstände entfernen.

**Comment by TeubyDE** [comment]
Bitte bist zum nächsten "Sturm" abwarten.
