### ISSUE TITLE
Abgabe von Exportaufträgen nicht möglich

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#223]
**Beobachtetes Verhalten**
Abgeben des Exportauftrages nicht möglich

**Erwartetes Verhalten**
Das man Aufträge erfüllen und abgeben kann

Original BT Eintrag:
https://statev.de/forum/StateBug/index.php?issue/3833-ressourcenexport-diesel/

**Comment by AtreuX** [comment]
Ja, bei uns das gleiche Problem!

![20201120144155_1](https://user-images.githubusercontent.com/74780325/99813844-7bd30a00-2b48-11eb-91f8-42e1f996a38a.jpg)

Keine Abgabe möglich, obwohl Auftrag definitiv vorhanden:

![Exportauftrag](https://user-images.githubusercontent.com/74780325/99813935-95745180-2b48-11eb-82dc-ebc5c9f45e3f.JPG)
