### ISSUE TITLE
Bei Waffe zielen, Animation abbrechen

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#2230]
**Beobachtetes Verhalten**
Ist man in einer aktiven Animation und zieht dann die Waffe und zielt, bleibt die Animation bestehen

(tritt vor allem bei Cops auf, da keine Waffenzieh Animation) .

**Erwartetes Verhalten**
Waffe ziehen bzw. zielen sollte Animation abbrechen

**Optional: Video / Bilder des Fehlers**

https://youtu.be/BXgIXAsJaZI

**Comment by TeubyDE** [comment]
Der Aufwand ist zu groß für den Benefit den wir dadurch bekommen.
