### ISSUE TITLE
Tannenholztransportgruppe fehlerhaft/ändern

### ISSUE THREAD

**Issue by MisterGarry** [mexyn/statev_v2_issues#2231]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Marco Mayer / Gordon Freeman

**Auftrittszeitpunkt (Datum / Uhrzeit)**

11:50 Uhr / heute
**Beobachtetes Verhalten**

Tannenholz kann nicht in Docktrailer verladen werden / Auftrag von Tannenholz Gewicht zu hoch (1350kg)
**Erwartetes Verhalten**

Tannenholzaufträge anpassen in Gewicht oder möglichkeit Tannenholz in Dock Trailer zu verladen.
**Schritte um den Fehler nachvollziehen zu können**

Auf Verladestation stellen und verladen möglich
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

Nicht nötig

**Comment by KingMarcel** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2227
mit dem nächsten Update behoben
