### ISSUE TITLE
StateCom Akte von altem Char in Akte von neuem Char

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#2232]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
28.01.2022

**Beobachtetes Verhalten**
Akte von altem Char (Nina Modl) in Akte von neuem Char (Laveda Clark)

**Erwartetes Verhalten**
sollte da nicht sein

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://user-images.githubusercontent.com/70178420/151612712-ca2904db-98a8-4ef0-b73f-dbc40d8bf489.png)

**Comment by DrGrizzlY17** [comment]
Da der Char anscheinend einfach renamed wurde ist das normal. Da kann man nichts dran ändern, da die Akte an der User ID gebunden ist und nicht am Namen. Soweit halt kein Bug. Einfach löschen
