### ISSUE TITLE
Änderung Abladepunkt

### ISSUE THREAD

**Issue by deOstfrees** [mexyn/statev_v2_issues#2233]
Charakter Name:
Karl Knall

Firmen Name: South LS Storage
Firmenhash davis28

Dieser Punkt soll versetzt werden, damit wir mit dem Verkehr auf der Hauptstrasse keine Probleme mehr haben, denn es ist oft so das man die Strasse komplett sperrt wenn man dort rangiert. 

Ladepunkt an der Alten Position:
https://pic.statev.de/i/ubZPP.png

Ladepunkt an der Neuen Position:
https://pic.statev.de/i/uA6RJ.png

**Comment by Enemyaa** [comment]
@deOstfrees Dein Ladepunkt ist doch perfekt da wo er ist? Mitten auf der Straße sollte nur die Notlösung sein, bei dir seh ich da gar kein Bedarf.

**Comment by Bobias92** [comment]
Problem ist bei dem Punkt noch das man jedesmal die schilder umfährt, damit man mir der Achse da rein kommt. Und beim rangieren habe ich schon öfter beinahe Unfälle. Sonst sollte er vielleicht in die strasse runter gelegt werden, dort ist nicht so viel Verkehr.

**Comment by Enemyaa** [comment]
OK

Next Update dann!
