### ISSUE TITLE
Antrag auf Hausgarage

### ISSUE THREAD

**Issue by cadpri** [mexyn/statev_v2_issues#2234]
Sehr geehrtes Bauunternehmen,
 
ich beantrage hiermit eine Hausgarage an meinem Haus:
Westmirror Drive 31 : house_Vinewood_31 ( Keine Ahnung warum der zweite Hash beim Mouseover von den Drei Punkten Vinewood sagt. Das Haus ist auf jedenfall im Mirror Park )
Die Einfahrt ist Großzügig gestaltet und hat einen Carport der Ausreichend groß ist. Die Gegebenheiten sind also erfüllt. (den Ausparkpunkt bitte dorthin wo das Auto steht um Kollisionen mit dem Carport beim ausparken zu vermeiden )
Über eine positive Antwort würde ich mich sehr freuen.
Viele Grüße,
Fabian_Picard

[Bildchen vom Haus, Carport und Ausparkpunkt](https://pic.statev.de/i/uAZGI.jpg)

P.S. Bei Rückfragen stehe ich gerne zur Verfügung.

**Comment by TheOutburst** [comment]
Sehr geehrter Herr Picard,

mit Freuden kann ich Sie über den erfolgreichen Empfang Ihres Antrages unterrichten.

Der Antrag befindet sich somit nun in Bearbeitung, wir werden unseren Kollegen Kalle in den nächsten 1 bis 100 Werktagen vorbeischicken. Dieser wird die beantragte Garage bei Ihnen errichten, er hat sowieso mehrere offene Aufträge und muss auch nochmal den Hochseefischtank in einem Ihrer Nachbarhäuser verglasen & verblomben, er ist also bald in der Nähe. Halten Sie bitte stets genug Kaffe, Schokoriegel und ein freies Scheisshaus bereit, ohne diese drei Kriterien wird er nicht tätig werden.

Hochachtungsvoll,
Herr Bauamt

**Comment by cadpri** [comment]
Hallo Herr Bauamt,

ich versuche noch schnellstmöglich ein Dixie Klo zu organisieren. Zur Not lasse ich aber auch einfach den Haustürschlüssel unter der Fußmatte liegen. Dann kann Kalle auch gerne drinnen aufs Klo gehen, falls ich zum Zeitpunkt der Bauarbeiten selber arbeiten bin. Ich lasse dort auch einen Zettel mit meiner Handynummer liegen, dann kann Kalle mich auch anrufen, falls er etwas braucht.

Viele Grüße und danke für die schnelle Antwort,
Fabian_Picard

**Comment by TheOutburst** [comment]
Sehr geehrter Herr Picard,

wir haben soweit alle Vorbereitungen getroffen, die Hoch und Tiefbau GmbH & Co Kg Ag ing sollte morgen die benötigen Materialen liefern, bitte halten sie eine Freifläche von 2 Hektar und 23 Zoll für die Lagerhaltung bereit. Wann Kalle mal seine Mittagspause beendet und die Aufträge abarbeitet können wir zum derzeitigen Zeitpunkt leider noch nicht nennen.

Ihr Auftrag wurde insofern umformuliert, dass das Fahrzeug nur unter ihrem Carport ausgeparkt werden kann, da wir den Fußgängern auf dem Fußweg vor dem Carport erschlagende Argumente inform ihres Autos ersparen möchten.

Mit freundlichen Grüßen,
Herr Kai Uwe Bauamt

**Comment by cadpri** [comment]
Hallo Herr Bauamt,

Oh das sind großartige Neuigkeiten.
Selbstverständlich werde ich den benötigten Platz frei halten. Ich werde auch nachher noch einen Sixpack kühl stellen, damit Kalle sich dann sein wohlverdientes Feierabend Bierchen gönnen kann.

OK das mit dem Fußgängerschutz ist ein gutes Argument das mir bei der Planung durchgegangen ist. Danke fürs mitdenken!

Viele Grüße,
Fabian_Picard
