### ISSUE TITLE
Antrag auf Hausgrage

### ISSUE THREAD

**Issue by HalvarCrayne** [mexyn/statev_v2_issues#2235]
Seehr geehrtes Bauunternehmen,

ich beantrage hiermit eine Hausgarage an meinem Haus:
Mirrowpark2 : house_Vinewood_28 ( Keine Ahnung warum bei Haushash Vinewood steht. Das Haus ist auf jedenfall im Mirror Park )
Die Einfahrt hat einen Carport der Ausreichend Platz bieten sollte. Die Gegebenheiten sind also erfüllt. (den Ausparkpunkt bitte dorthin wo das Auto steht um Kollisionen mit dem Carport beim ausparken zu vermeiden )
Über eine positive Antwort würde ich mich sehr freuen.
Viele Grüße,
Halvar_Crayne

https://pic.statev.de/i/uGq7R.jpg

**Comment by TheOutburst** [comment]
1. Texte von anderen Leuten kopieren (die zusätzlich nicht zutreffen) ist ein wenig unsportlich, fast schon peinlich
2. Das ist kein Carport sondern ne Markise, da passt keine Garage hin
