### ISSUE TITLE
AKMSU und HK416 Seriennummern nicht entfernbar...

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#2236]
Sind normale Zivi Langwaffen, daher müsste es ja möglich sein...
Es kommt die Meldung wenn man die Nummer entfernen lassen will das man sie nicht lackieren kann ^^

![Screenshot_41](https://user-images.githubusercontent.com/70241137/151771663-537a369a-6318-40c1-b8e1-f1e3b9cd7fe6.jpg)

![Screenshot_43](https://user-images.githubusercontent.com/70241137/151771702-56c71945-5c6e-494c-995f-0cfd7b29fd49.jpg)

**Comment by SHaagmann** [comment]
Mossberg AOW auch nicht möglich

**Comment by DrGrizzlY17** [comment]
So gewollt
