### ISSUE TITLE
Brute Dashound Kofferaum weg/wo anders?

### ISSUE THREAD

**Issue by MisterGarry** [mexyn/statev_v2_issues#2239]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Marc Mercer / Brain Garry

**Auftrittszeitpunkt (Datum / Uhrzeit)**

31.01.22 und frühere Updates

**Beobachtetes Verhalten**

Kofferaum ist bei einigen Updates von seite nach hinten wieder zur Seite und dann ganz verschwunden.
Mit Abstand probiert und ähnliches... sind noch Sachen drin. Sowie mit Abstand zum Fahrzeug falls zuweit weg gewandert.

Fahrzeug Brute Dashhound (Reisebus)

**Erwartetes Verhalten**

Kofferaum einsehen ob Seite/hinten egal Hauptsache da ?
Oder gewollt ob dies keinen mehr hat? 

**Schritte um den Fehler nachvollziehen zu können**

Über X Menu/App öffnen und Kofferaum öffnen. Bei Radkasten Mitte ursprünglich.

**Optional: Video / Bilder des Fehlers**

Falls Falsch beschrieben o.ä. ist mein erstes mal, dass ich ein Fahrzeugbug beschreibe ^^
MfG Garry

**Comment by TheOutburst** [comment]
was auch immer da passiert ist, next update ist der Kofferraum wieder seitlich zu finden.

**Comment by MisterGarry** [comment]
Spitze danke!
