### ISSUE TITLE
Schleichen nur über Gehstilauswahl möglich

### ISSUE THREAD

**Issue by 3xcu** [mexyn/statev_v2_issues#224]
Es wäre wesentlich praktikabler und sinnvoller wenn der Gehstil "schleichen" entweder über einen Hotkey wie STRG oder über das Animationsmenü einsetzbar ist. So wie es jetzt ist, ist es sehr unpraktisch das ins RP einzubauen und einfach zu umständlich wenn man dann bspw. wieder normal gehen will um schnell, weil man entdeckt wurde, die Flucht zu ergreifen.

**Comment by DonVitoDiangelo** [comment]
Schleichen liegt GTA Standard auf STRG.
Der Geh-Stil bliebt aber Geh-Stil.
