### ISSUE TITLE
Fehlerhafte Objekte in Villa Interrior

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#2240]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Ryan_Valdes

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Seit dem Alt:V Update

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

Habe mal bissl Rumgeschaut und einen Fix gefunden weiß nur nicht ob ihr den verwenden könnt.

https://de.gta5-mods.com/maps/fix-franklin-interior-after-mpsecurity-update
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TheOutburst** [comment]
fixed next update
