### ISSUE TITLE
Koks kann nicht abgegeben werden

### ISSUE THREAD

**Issue by Naui1** [mexyn/statev_v2_issues#2241]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Patric Strunk**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.02.22 5:55

**Beobachtetes Verhalten**
Punkt zum Koks abgeben vorhanden es kann jedoch nicht abgegeben werden obwohl man genau drin steht

**Erwartetes Verhalten**
Koks sollte abgegeben werden
**Schritte um den Fehler nachvollziehen zu können**
Jimmy Mission annehmen und bei 923 abliefern an einem blauen Briefkasten

**Optional: Video / Bilder des Fehlers**
![Bug1](https://user-images.githubusercontent.com/98866736/152096120-d9a2bae4-f49c-4c4c-86c4-b92730caf0c5.png)

**Comment by TheOutburst** [comment]
#2193
