### ISSUE TITLE
Kofferraum zugänglich mit Trailer 200

### ISSUE THREAD

**Issue by cadpri** [mexyn/statev_v2_issues#2242]
Fabian_Picard

**Beobachtetes Verhalten**
Wenn man den Trailer 200 an der Zugmaschine ( in diesem Fall Bobcat ) angekoppelt hat kann man nicht mehr an den Kofferraum der Zugmaschine gelangen. Man muss den Anhänger abkoppeln um dran zu kommen. 

**Erwartetes Verhalten**
Es wäre schön, wenn man die Erreichbarkeit vom Kofferraum auch von der Ecke aus machen könnte. Da die Zugmaschinen ja eh offene Ladeflächen haben verliert man auch nicht den Realitätsfaktor.

**Comment by Hutstaender** [comment]
Der Aufwand dafür ist leider nicht gerechtfertigt.
