### ISSUE TITLE
Antrag auf Hausgarage

### ISSUE THREAD

**Issue by Taxmax77** [mexyn/statev_v2_issues#2243]
Sehr geehrtes Bauamt,

ich beantrage hiermit eine Hausgarage an meinem Haus:
Westmirror Drive 8 : house_Vinewood_8 
Die Einfahrt ist Großzügig gestaltet und hat einen Carport der Ausreichend groß ist. Die Gegebenheiten sind also erfüllt. ( Den Ausparkpunkt vorzugsweise schon vor dem eigentlichen Carport , um Kollisionen mit dem Haus/ Carport zu vermeiden. )

Im Anhang finden Sie noch 2 Beispiele von Nachbarhäusern (Beispiel A und B), bei denen die Nutzung des Carports wohl gut funktioniert.
Und natürlich auch ein Bild von meinem Haus mit der Einfahrt.

Über eine positive Antwort würde ich mich sehr freuen.
Viele Grüße,
Jake Fox

![Beispiel A](https://user-images.githubusercontent.com/97894497/152219136-e21e33a8-558e-43f7-ab00-fd52cd7373a9.png)
![Beispiel B](https://user-images.githubusercontent.com/97894497/152219166-67e7722b-8b0c-4e0c-aed4-7136be544706.png)
![Mein Haus](https://user-images.githubusercontent.com/97894497/152219189-d02b86b7-e64c-46bf-8cd6-1c1fd03a5307.png)

**Comment by cadpri** [comment]
Sorry, dass ich hier jetzt so reinspame aber ich finds echt nicht schön, dass meinen Text jetzt schon der zweite relativ exakt kopiert.

Lasst euch mal eigene Sachen einfallen.

**Comment by TheOutburst** [comment]
Aaaaaaalso

1. das ist ist nen Bugtracker, kein IC Forenbereich. Und nen ic/ooc Text von wem anderen kopieren ist halt gar nicht mal so geil.
2. Referenzbilder braucht man nicht anhängen, wir entscheiden das pro Haus, nicht anhand anderer Häuser

Next update Garagenmarker unter dem Carport.
