### ISSUE TITLE
Antrag auf feste Blumenkübel

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#2244]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Ryan & Mila Valdes

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

Wäre es möglich vielleicht die Blumenkübel die wir am Laden stehen haben fest zu intrigieren. 
Wäre halt schön wenn das gehen würde. 
Vorallem hilft es gegen die Leute die gefühlt mit dem Auto in den Laden fahren.

Fragen kostet ja nix wenn es nicht klappt ist es auch ok.
**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![unknown](https://user-images.githubusercontent.com/70231715/152290735-8b265fdc-b4c3-4ec7-82d3-7cb9599103ce.png)
![2unknown](https://user-images.githubusercontent.com/70231715/152290748-024f2499-f597-4ec4-b6dc-e15a2d6fc5a6.png)

**Comment by DrGrizzlY17** [comment]
Ihr habt das doch schon schön gemacht, brauchen wir ja nicht machen :)
Nein wir machen keine user basierten Mappings, wenn sowas wie den Würfelpark, wo jeder was von hat.
Fängt man einmal an, wollen das alle. Das ist das Problem daran :)

**Comment by PlayInc89** [comment]
Ok trotzdem danke
