### ISSUE TITLE
Antrag auf Hausumbau

### ISSUE THREAD

**Issue by LeaBrandt** [mexyn/statev_v2_issues#2245]
**Hausbesitzer** 
Karl Bergmann

**Haushash**
house_MirrorPark_21 

Sehr geehrte Damen und Herren vom Bauamt, folgende Anliegen hätten wir an Sie:

**Schild entfernen**
Hiermit beantragen wir für unser Haus das Verkaufsschild im Vorgarten (siehe Foto) zu entfernen. Wir haben nicht vor das Haus wieder zu verkaufen und möchten mögliche Interessenten nicht verwirren. 

**Garagennutzung/ Parkerlaubnis**
Des Weiteren haben wir ein großes Tor, welches in einen Hinterhof führt. Sicherlich ist es nicht der größte Hinterhof, aber für ein Fahrzeug reicht er aus (Eine Garage mit einem oder zwei Fahrzeugslot würde uns schon vollends glücklich machen). Aufgrund des großen Tores (siehe Foto), welches zur Durchfahrt durchaus geeignet ist, sollte dies kein Problem darstellen. 
Eine weitere Option sehen wir, wenn Sie uns eine Genehmigung zum Bauen eines überdachten Carport im Garten hinter dem großen Tor erteilen würden, da wir mehr als ausreichend Platz im Hinterhof haben. 

Sollten Sie uns bezüglich der Parkerlaubnis bzw. des Carport keine Genehmigung erteilen können, dann bitten wir wenigstens um die Möglichkeit Einkäufe, die ja direkt ans Haus gefahren werden können, besser abladen zu können (wenigstens Abladepunkt, wenn Garage nicht möglich ist).

**Basketballkorb**
Diesen Aspekt würde ich gerne nur nebenbei erwähnen. Entsprechend unseres Hausnamens „Das Haus mit dem Basketballkorb“ und als Überraschung für meinen Mann wäre es wunderbar, wenn Sie bei sich noch rein zufällig einen Basketballkorb rumliegen haben. Nur wenn es nicht all zu aufwendig für Sie ist, würde ich Sie bitten uns an einer Stelle Ihrer Wahl einen anzubringen. Angelehnt an den Song von Emma6 hätte das für uns eine große Bedeutung. 

Mit freundlichen Grüßen,

Lea Brandt 
Karl Bergman
![Schild](https://user-images.githubusercontent.com/98689462/152441778-df03372c-7062-4633-801a-2b0c38ab73c2.png)
![Tor](https://user-images.githubusercontent.com/98689462/152441793-6e0eb814-bee0-4249-85d3-9de8f5d0b5e1.png)
![Hinterhof](https://user-images.githubusercontent.com/98689462/152441813-f3c6f958-49b1-45f9-8edc-039b3762fb73.png)

**Comment by LeaBrandt** [comment]
Referenz Haus mit Tor und Garage - Haushash: house_Vinewood_3

**Comment by its4l3x** [comment]
@TheOutburst 

User meldet immer noch bestehendes Problem, bitte nochmal schauen.

**Comment by KarlBergmann1** [comment]
Schild wurde entfernt, Garage fehlt

**Comment by TheOutburst** [comment]
Korregiere: Haushash ist house_MirrorPark_21
Next Update ist der Garagenmarker da
