### ISSUE TITLE
Hellblaues und Türkises Knot Bandana fehlen

### ISSUE THREAD

**Issue by TamiGaming** [mexyn/statev_v2_issues#2249]
**Character Name**
Carlie Tacus

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.02.2022  ca. 2:00 Uhr

**Beobachtetes Verhalten**
Knot Bandanas in den Farben Hellblau und Türkis gibt es nicht. 
Hab die Aufstellung vom letzten mal einmal überarbeitet, damit man es genau sehen kann.
Da die Helllila Paisleys alle entfernt wurden, müsste dementsprechend auch das Helllilane Knot Bandana raus genommen werden.

![image](https://user-images.githubusercontent.com/40512639/152623112-0880eb3e-c193-44d0-99bf-75bd28e9b6b7.png)

(x* bei den Sandanas gilt nur für mich als Übersicht)

**Erwartetes Verhalten**
Hinzufügen des Türkisen und Hellblauen Knot Bandanas, 
Entfernen des Helllila Knot Bandanas.

**Comment by Enemyaa** [comment]
OK! Kommt mit einen der nächsten Updates!
