### ISSUE TITLE
Fehlerhafte Beschreibung von neuen Sweats in der Ladentheke 

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#2251]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Ryan Valdes

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

Statt Schwarze Sweats steht in der Ladentheke malepants41381 was bei allen Hosen der Fall ist.
**Erwartetes Verhalten**

Statt malepants den richtigen namen 

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot_5](https://user-images.githubusercontent.com/70231715/152632552-acc036c1-7add-4185-b201-ad3dd076522d.png)
![Screenshot_4](https://user-images.githubusercontent.com/70231715/152632556-ad3399ff-2241-42b6-9660-c83abf03e2e9.png)
![Screenshot_3](https://user-images.githubusercontent.com/70231715/152632557-0ef413c2-c291-43d7-b6f7-05c751bc739e.png)

**Comment by its4l3x** [comment]
Ist gelöst. War aufgrund eines Fehlers unseres Updates. Sorry.
