### ISSUE TITLE
Zeitfahren kann nicht gestartet werden

### ISSUE THREAD

**Issue by Pregon** [mexyn/statev_v2_issues#2254]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Ronny Roberts

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.02.2022 13:20 Uhr

**Beobachtetes Verhalten**
Beim Zeitfahren wird das Rennen nicht ausgewählt und auch nicht auf der Karte markiert, wenn man auf "Rennen auswählen" klickt

**Erwartetes Verhalten**
Das Rennen wird ausgewählt und auf der Karte markiert

**Schritte um den Fehler nachvollziehen zu können**
Zum Racing NPC gehen und eine Strecke beim Zeitfahren starten

**Optional: Video / Bilder des Fehlers**

https://user-images.githubusercontent.com/75855042/152642161-3e5b4a66-db1c-4460-95a7-c8a736d0c2ff.mp4

**Comment by TeubyDE** [comment]
Hotfix is mit den 15 Uhr Restart heute drauf gekommen.
