### ISSUE TITLE
Orangenfeld in Paleto

### ISSUE THREAD

**Issue by Beartox** [mexyn/statev_v2_issues#2255]
Wie im Bild zu sehen, wirft das obere Orangenfeld in Paleto sehr viele Zitronen nur noch ab, also  was ich denke, dass es nicht richtig ist, das ist der Ertrag von zwei runden.

![unknown](https://user-images.githubusercontent.com/79170045/152644185-d15d7cb0-636e-422c-b31a-4d77bd11c6f3.png)

MFG

Tobias_Schlueter

**Comment by DonVitoDiangelo** [comment]
Kein Bug
