### ISSUE TITLE
Declesse Burrito nicht sichtbar. 

### ISSUE THREAD

**Issue by Donvito88** [mexyn/statev_v2_issues#2257]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Markus Haenk**

**06.02.2022 13:15**

**Fahrzeug nicht an dem Ort in Paleto, wo es abgestellt wurde. Per Handyortung aber an dem Punkt**

**Fahrzeug sollte noch aktiv am Punkt stehen **

**-**

**-**

**-**

**Comment by TheOutburst** [comment]
#2248
