### ISSUE TITLE
Coil Raiden umlänge schneller als der Pfister Neon

### ISSUE THREAD

**Issue by Sc8pex** [mexyn/statev_v2_issues#2258]
Guten Tag zusammen,
und zwar ist mir folgendes nach dem Update V2.2.6 - 04.02.2022 aufgefallen.
Der Coil Raiden ist um vieles schneller in der Beschleunigung und Endgeschwindigkeit als ein
Neon Pfister.
Auf dem Flugfeld kamen folgende Werte zustande: 
Coil Raiden 230 km/h ca. 2 Sekunden schneller als der Neon
Neon Pfister 225 km/h 

Nun meine Frage ist dies so gewollt? Oder wurde es getestet?

MfG
Wojtek

**Comment by epichalt** [comment]
siehe Changelog:

https://statev.de/forum/thread/13329-v2-2-6-04-02-2022/?postID=121757#post121757

**Comment by TheOutburst** [comment]
Das sind beides Autos mit starker Beschleunigung, die auf einer so kurzen Strecke wie dem nur auf dem Flugfeld zu testen machen wir nicht, und mit nur 5 km/h Differenz würde ich sagen das ist exakt so gewollt.
