### ISSUE TITLE
Auto nicht mehr sichtbar nach Gamecrash

### ISSUE THREAD

**Issue by Kaarster** [mexyn/statev_v2_issues#2259]
**Terry Rice**

**06.02.22 / 14:45**

**Ich war am 06.02.22 gegen 14:45 Uhr meinem Caracara auf der Harwick Avenue Richtung East Los Santos unterwegs als mein Game gecrashed ist. Ich habe mich umgehend neu eingeloggt, jedoch war das Fahrzeug nicht sichtbar. Nachdem ich über das Tablet den Wagen per GPS geortet habe, wurde mir auf der Karte an der Stelle wo er hätte stehen sollen ein Marker gesetzt. Optisch war er jedoch auch nach einem weiteren Restart weiterhin nicht sichtbar. Es blieb mir nichts anderes übrig als mich beim Support zu melden und mein Fahrzeug in eine Garage setzen zu lassen.**

**Comment by TheOutburst** [comment]
#2248
