### ISSUE TITLE
Fahrzeuge verhalten sich anderes. 

### ISSUE THREAD

**Issue by DerVerruecke** [mexyn/statev_v2_issues#2260]
Mason Street

06.02.2022 17:16 Uhr

Die Fahrzeuge fahren sich anderes ( langsamer und schlechtere Beschleunigung). Aktuell ist das mir am Pfister Comet, Elegy Retro Custom, MK 2 und Zion Classic aufgefallen.

Vor dem letzten Update und Fix war es noch alles gut aber heute ist der Fehler aufgetreten

Die Fahrzeuge mal testen und dann merkt man das eigentlich direkt

**Comment by Falk-Alers** [comment]
Also sowohl mein elegy, größter Motor 331ps 3123.2km, wie auch der Zion C, größter motor 110ps 506.5km, fahren sich mit den jeweiligen Modifikationen (UHP-Reifen, Spoiler ect) völlig normal

**Comment by TheOutburst** [comment]
Ja, im letzten GTA Update sind die Tuner Fahrzeuge von R* aus verändert worden, aber das ist ja schon ein wenig länger her. Wir haben in unserem letzten Update diese Autos nicht verlangsamt, im Gegenteil, wir haben einen Bug der Fahrzeuge zu sehr verlangsamt hat gefixt. Ich sehe beim groben durchtesten auch keine veränderte Fahreigenschaft, würde hier an der stelle Schließen
