### ISSUE TITLE
Personen werden in Kirchen unsichtbar je nach Kameraposition

### ISSUE THREAD

**Issue by onlyPASI** [mexyn/statev_v2_issues#2263]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Anthony_Chegwidden**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
in den Kirchen werden andere Spieler unsichtbar je nach Kameraposition. Passiert in allen 3 Kirchen. Und ist Spieler unabhängig.

**Erwartetes Verhalten**
Spieler sollen nicht verschwinden

**Schritte um den Fehler nachvollziehen zu können**
mit zwei Chars eine Kirche betreten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Kannst du hier mal ein Bild posten wo genau, aus welchen Winkel, der Fehler auftritt?

**Comment by TheOutburst** [comment]
das IPL ist leider nicht das beste, entweder wir fixen das oder machen direkt nen neues/suchen ein besseres
