### ISSUE TITLE
Nach Websitebesuch UI verschoben

### ISSUE THREAD

**Issue by PAEAEAEAEAET** [mexyn/statev_v2_issues#2265]
**Character Name**
Jochen_Gargitter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
08.02.2022, 14:45

**Beobachtetes Verhalten**
Nach dem Klicken der Schaltfläche "unsere DJs" (auf der Shining Crowns Webseite) verschob sich das State UI. Dies betraf das Inventar, die Essensleiste, das Tablett und den Gutachtendruck. Durch Reconnect hat sich das Problem lösen lassen.

**Erwartetes Verhalten**
UI verschiebt sich nicht.

**Schritte um den Fehler nachvollziehen zu können**
Siehe Video und beobachtetes Verhalten.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080, Vollbild Fenster

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=zLp6yGKDSq4

**Comment by milkdrops** [comment]
Warst du davor im Teamskins-Menü?

**Comment by PAEAEAEAEAET** [comment]
Hallo, 

diesen Fehler hatte ich 2x:
1: Ich war länger im Dienst, habe mir die Webseite angeschaut und og. Fehler trat auf.
2: Da ich ein Gutachten drucken musste, war ich zu einem Relog gezwungen, habe das Gutachten gedruckt und der Fehler trat danach (absichtlich für Aufnahme, da vor Restart) erneut auf. Im zweiten Fall habe ich die Skinauswahl definitiv nicht vorher geöffnet, war aber in beiden Szenarien im MD Dienst.

LG Jochen

**Comment by RealSocius** [comment]
Liegt an der Website selbst. Ich würde bald mal ein Websiten-Update hochladen.
