### ISSUE TITLE
Autos verschwinden in der Werkstatt u. Werkbank ist dann blockiert

### ISSUE THREAD

**Issue by Maximilian63** [mexyn/statev_v2_issues#2268]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Max Clinton

**Auftrittszeitpunkt (Datum / Uhrzeit)**
08.02.2022 / 20:43

**Beobachtetes Verhalten**
Nach game-crash, Fahrzeug in der Werkstatt verwunden und die Werkbank blockiert dadurch.

**Erwartetes Verhalten**
Fahrzeug steht da und Werkbank kann genutzt werden

**Schritte um den Fehler nachvollziehen zu können**
kann ich nicht sagen, passiert anscheinend zufällig

**Comment by TheOutburst** [comment]
Wir sammeln die tracker in #2273 auch wenn der hier theoretisch älter ist
