### ISSUE TITLE
Enus Jubilee Öl falle Tunebar

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#2269]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Sven Rosenbach
**Auftrittszeitpunkt (Datum / Uhrzeit)**

08.02 22:30
**Beobachtetes Verhalten**

Beim Enus Jubilee ist es Möglich beim Kotflügel/Extra Öl zu tunen, was wahrscheinlich die Ölminen aus GTA Online sind (nicht getestet, da kein bock Kotflügel wasten)
**Erwartetes Verhalten**

Sollte nicht auswählbar sein 
**Schritte um den Fehler nachvollziehen zu können**

Mit dem Jubilee in eine Werkstatt fahren und Tunen

**Optional: Video / Bilder des Fehlers**

https://streamable.com/6l3b58

**Comment by TheOutburst** [comment]
danke fürs melden, next update fixed
