### ISSUE TITLE
Smartphone -> Favoriten- sowie Namensänderung nicht gespeichert

### ISSUE THREAD

**Issue by TajuuLa** [mexyn/statev_v2_issues#227]
> **Character Name** Emilia Bradley
> 
> **Zeitpunkt (Datum / Uhrzeit)** 20.11.2020
> 
> **Beobachtetes Verhalten** Von 10 Favoriten, hat er leider nur 1 gespeichert gehabt. Zudem hat er auch Namensänderungen bei vorhandenen Kontakten im Smartphone nicht gespeichert.

**Comment by TajuuLa** [comment]
> **Character Name** Emilia Bradley
> 
> **Zeitpunkt (Datum / Uhrzeit)** 20.11.2020
> 
> **Beobachtetes Verhalten** Von 10 Favoriten, hat er leider nur 1 gespeichert gehabt. Zudem hat er auch Namensänderungen bei vorhandenen Kontakten im Smartphone nicht gespeichert.

**Comment by mexyn** [comment]
@TajuuLa Gerade bei mir lokal getestet und kann den Fehler nicht nachstellen. Bitte mal genaue Schritte beschreiben. Auch die Nummer um die es geht (notfalls per Discord oder TS wegen Meta). Ansonsten ist meine Vermutung, dass es mit der Ursache von #230 zu tun hat und evtl. schon mit dem nächsten Hotfix gelöst ist

**Comment by TajuuLa** [comment]
Das Problem ist tatsächlich schon gelöst. Lag lediglich in der ersten Nacht vor.

**Comment by TajuuLa** [comment]
Problem ist scheinbar schon gelöst. Das Problem lag lediglich in der ersten Nacht vor. 👍
