### ISSUE TITLE
Autos werden einfach unsichtbar

### ISSUE THREAD

**Issue by Chandena** [mexyn/statev_v2_issues#2273]
Chandena Mascarponi und Eddie Mallian

**Auftrittszeitpunkt (Datum / Uhrzeit)**
die letzten 3 Tage gegen Abend

**Beobachtetes Verhalten**
Autos sind einfach unsichtbar und werden auch nicht per GPS angezeigt.

**Erwartetes Verhalten**
Autos bleiben an Ort und Stelle sichtbar stehen!

**Schritte um den Fehler nachvollziehen zu können**
Ich stelle mein Auto ab und nach ein paar Minuten steht es nicht mehr da und per GPS wird kein Standort angegeben.

**Comment by Chandena** [comment]
Character Name:

 Chandena Mascarponi und Eddie Mallian
> 
> **Auftrittszeitpunkt (Datum / Uhrzeit)** die letzten 3 Tage gegen Abend
> 
> **Beobachtetes Verhalten** Autos sind einfach unsichtbar und werden auch nicht per GPS angezeigt.
> 
> **Erwartetes Verhalten** Autos bleiben an Ort und Stelle sichtbar stehen!
> 
> **Schritte um den Fehler nachvollziehen zu können** Ich stelle mein Auto ab und nach ein paar Minuten steht es nicht mehr da und per GPS wird kein Standort angegeben.

**Comment by epichalt** [comment]
duplikat 
https://github.com/mexyn/statev_v2_issues/issues/2248

**Comment by Hutstaender** [comment]
Könnt ihr dazu so viele details wie möglich liefern? Dabei meine ich am besten jeden einzelnen klick den ihr gemacht habt, jedes rein und raus porten, jeden gamecrash oder zumindest ne genaue uhrzeit. sonst hilft uns das leider nicht weiter und ich mach zu

**Comment by epichalt** [comment]
@Hutstaender 

ich werde morgen bei uns am Autohaus mal testen. Hatte das auch bereits 2-3x. 
Gefühlt war es als mehr als 5-6 Autos in der Streaming Range waren. Wenn dann alle ins Autohaus gehen und keine Person mehr draußen steht. Werden die Autos manchmal unsichtbar und tauchen bis zum nächsten Neustart auch nicht mehr auf. 
Die Fahrzeuge sind dann weder sichtbar noch kann man "dagegen laufen". Laut GPS befinden sie sich aber an der Stelle. 
Aber wie gesagt ich teste morgen mal, falls ich paar Autos finde, die verzichtbar sind für nen Tag :D

**Comment by Eskadiel** [comment]
Seit 22 Uhr am 12.2.22 sind teils Fahrzeuge an Ort und Stelle Unsichtbar. Sie sind zwar im GPS an der Stelle wo sie zu Letzt gestanden haben aber dort ist kein Fahrzeug vorhanden. 
Des weiteren kann es passieren das nach dem Porten aus einem Gebäude (Haus, Firma, Restaurant) Fahrzeuge nur noch 50 Kmh fahren oder nach einsteigen "Sie befinden sich nicht in einem Fahrzeug" gemeldet wird, obwohl man sich in einem befindet, sobald man den Motor starten will oder die Handbremse lösen möchte.

**Comment by Dean-Gallagher** [comment]
@Hutstaender bei uns hats vor der Werkstatt alles weggebugt. 

Ich geh rein, alles war noch da, bin keine 1 min drinne gewesen wollt nur hallo sagen, gehe raus, alles weg. Komplett alles weg bei jedem. Betroffen waren 4 Personen und 4 Fahrzeuge, je person 1 Fahrzeug.
