### ISSUE TITLE
Orangenplantage jetzt Zitronenplantage?

### ISSUE THREAD

**Issue by SgtTukiTuki** [mexyn/statev_v2_issues#2274]
Beobachtet mit Sandy_Folk
am 11.02.2022
um 9.15 Uhr bis 9.32 Uhr

Ich wollte Orangen sammeln und musste Feststellen, dass man jetzt mehr Zitronen statt Orangen findet... Das sollte in meinen Augen aber nicht Sinn der Sache sein... Nach ca 8 Runden habe ich 6 Orangen gefunden, dafür aber über 200 Zitronen?!?

Ist das so gewollt?

**Comment by CaleighRhodes** [comment]
Wurde schon mehrfach gemeldet und im Forum diskutiert, ist so gewollt.

**Comment by SgtTukiTuki** [comment]
Na super...
