### ISSUE TITLE
Health Anzeige nach Relog wieder aufgefüllt

### ISSUE THREAD

**Issue by v3rpl4nt** [mexyn/statev_v2_issues#2275]
**Character Name**
Tom_Reagan

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Über mehrere Tage beobachtet

**Beobachtetes Verhalten**
Wenn sich mit weniger als 100% Gesundheit ausgeloggt wird und anschließend wieder einloggt ist die 
Gesundheitsanzeige komplett wiederhergestellt. Dieses Verhalten tritt nicht bei direkten wieder einloggen auf.
Kürzester Zeitraum wo dies aufgetreten ist, war nach ca 45-60min relog. 

**Erwartetes Verhalten**
Gesundheitsanzeige gleichbleibend wie zum Zeitpunkt des ausloggens.

**Schritte um den Fehler nachvollziehen zu können**
Gesundheitsanzeige unter 100%, anschließend ausloggen und ca. 1Std später wieder einloggen (evtl. ist der Zeitraum auch kürzer)

**Comment by epichalt** [comment]
Ist mir auch schon aufgefallen. Habe allerdings noch kein Muster feststellen können. Teilweise logge ich mich am nächsten Tag ein und habe immer noch weniger Leben, teils auch über mehrere Tage am Stück.
