### ISSUE TITLE
Simkarte kann nicht kopiert werden

### ISSUE THREAD

**Issue by Bobias92** [mexyn/statev_v2_issues#2276]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Ernst Biller

11.02.2022  20:04

Man versucht eine Simkarte zu kopieren schlägt dies fehl, mit der begründung das keine Leere Sim vorhanden ist, obwohl dies so ist.

Simkarte sollte die im Handy ausgewählt ist, sollte kopiert werden.

1. Eine Simkarte im Handy, mit der Nummer, die kopiert werden soll
2. Eine nicht aktivierte Simkarte im Inventar ( Leer)
3. Im Handy in den Einstellungen die Simkarte auswählen und auf kopieren klicken
4. Es wird angezeigt das eine Leere Simkarte benötigt wird

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

https://pic.statev.de/image/bild-2022-02-11-214856.5HZpw

**Comment by SHaagmann** [comment]
Bist du der "ersteller" der Sim? Also hast du die Nummer selber gezogen?

**Comment by Bobias92** [comment]
Ja, habe sie auch mal getauscht. So das es ein Kollege hätte machen können. Konnte er aber nicht da er nicht der Besitzer bzw. Eigentümer der simkarte war.

**Comment by TheOutburst** [comment]
Wir hatten gestern kurz vor der Erstellung des Bugtrackers ein Datenbankproblem, was auch das Simkarte klonen beeinflussen würde.
Probiere es bitte heute nochmal, es sollte ohne Probleme funktionieren.

**Comment by Bobias92** [comment]
Geht wieder, danke
