### ISSUE TITLE
Antrag auf Busch-, Müll- und Stuhlentfernung

### ISSUE THREAD

**Issue by Pregon** [mexyn/statev_v2_issues#2277]
Sehr geehrte Stadtverwaltung,

gern würden wir sie um ein paar Dinge bitten, die unser Grundstück in Davis betrifft:
![Entfernung 3](https://user-images.githubusercontent.com/75855042/153669774-1c8e9d16-c503-4013-87f4-77e74aaca1dd.png)

Die erste Bitte richtet sich an die Gärtner ihrer Stadt Los Santos, damit die unschönen Büsche in unserem Vorgarten rausgezogen werden können, die unserem Vorgarten eindeutig den Platz und die Schönheit nehmen:
![Entfernen 1 1](https://user-images.githubusercontent.com/75855042/153670270-384bbcf5-bc9a-4360-bd4f-de04f076b1a8.png)

Unsere nächste Bitte richtet sich an die Städtische Müllabfuhr, die wir darum bitten würden, die Mülltonnen in unserem Vorgarten mitzunehmen, denn auch diese nehmen den Platz und die Schönheit des Gartens:
![Entfernen 1 2](https://user-images.githubusercontent.com/75855042/153670669-8f8560bd-bc7a-46a7-bf52-f98b25d8630d.png)

Und unsere letzte Bitte richtet sich an die Sperrmüllabteilung, die wir darum bitten möchte einen Stuhl vor unserer Tür mitzunehmen, über welchen wir Tag für Tag aufs neue drüber stolpern:
![Entfernen 2](https://user-images.githubusercontent.com/75855042/153670857-864a6e24-37b4-470a-a1b6-ff8d7dc44406.png)
https://user-images.githubusercontent.com/75855042/153670870-526f7d98-845b-44b5-8613-22f94522a669.mp4

Wir würde uns sehr freuen, falls sie unserer bitte nachkommen könnten.

Mit freundlichen Grüßen
Ronny Roberts (Verfasser)
Jim Hill & Luisa Heidemann (Mitbewohner)

**Comment by TheOutburst** [comment]
First of all: das hier ist nen Bugtracker, kein IC Medium.
(note to self: niemals aus Jux und Tollerei IC auf nen Bugtracker antworten)

Mülltonne & Stuhl:
Objekte die umhergeschoben werden können werden wieder sichtbar sobald man sie berührt.

Bleibt der Busch übrig:
Wenn ich dir den entferne, bleibt der "durch Gebüsch laufen" Sound bestehen.

Demnach kann ich euch leider nix davon entfernen.
