### ISSUE TITLE
Äste länger nicht im Ressourcenexport

### ISSUE THREAD

**Issue by HuiBuh32** [mexyn/statev_v2_issues#2278]
Inge_Knesebeck

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit einigen Wochen

**Beobachtetes Verhalten**
Seit einigen Wochen Äste nicht mehr im Ressourcenexport.

**Comment by KingMarcel** [comment]
Hallo Inge,

sowohl der Ressourcen Export, als auch der Auftragsexport werden regelmäßig durch rotiert, sodass Items kommen und gehen. 
Demnach handelt es sich hierbei um keinen Fehler.

Lg
