### ISSUE TITLE
Flug durch Windschutzscheibe trotz angeschnallt

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#2279]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Sven_ Rosenbach & Jenny Hohengarten
**Auftrittszeitpunkt (Datum / Uhrzeit)**

12.02 gegen 15 Uhr
**Beobachtetes Verhalten**

bin mit ner Geschwindigkeit von ca. 210 gegen nen schild gerutscht und danach bin ich als Fahrer und auch Jenny als beifahrer durch die Windschutzscheibe geflogen, obwohl wir angeschnallt waren. Da mir das jetzt schon ein paar mal passiert ist wollte ich nachfragen, ob das so gewollt ist? 
**Erwartetes Verhalten**

Man fliegt nicht raus
**Schritte um den Fehler nachvollziehen zu können**

Hoher Geschwindigkeit gegen Schild fahren
**Optional: Video / Bilder des Fehlers**

https://streamable.com/bfn0aw

**Comment by TheOutburst** [comment]
Ihr fahrt 200 km/h
Ja, da ist es gewollt, dass man trotz Anschnallgurt aus dem Fahrzeug geschleudert wird.

**Comment by SHaagmann** [comment]
> Ihr fahrt 200 km/h Ja, da ist es gewollt, dass man trotz Anschnallgurt aus dem Fahrzeug geschleudert wird.

danke für die Schnelle Antwort.
