### ISSUE TITLE
Abschleppen mit fremden Flatbed

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#228]
**Beobachtetes Verhalten**
Das Abschleppen mit einem Flatbed der nicht einem selber gehört ist nur dann möglich, wenn man den Fahrzeugschlüssel aus dem Schlüsselbund Inventar, ins das Hauptinventar zieht.

**Erwartetes Verhalten**
Es sollte irrelevant sein, in welchem der beiden Inventars sich der Schlüssel befindet

**Schritte um den Fehler nachvollziehen zu können**
1. Fremden Flatbed besorgen mit Schlüssel.
2. Auto abschleppen wollen

Original BT Eintrag:
https://statev.de/forum/StateBug/index.php?issue/3816-abschleppen-flatbed/

**Comment by its4l3x** [comment]
Richtig, du musst nur Schlüssel besitzen. Es ist egal in welchem Inventar. Konnte das nicht reproduzieren, daher invalid. Bitte dran denken - ein bisschen auch zu warten.
