### ISSUE TITLE
Das Problem mit dem Sultan Classic

### ISSUE THREAD

**Issue by ArnoZuDemB** [mexyn/statev_v2_issues#2280]
**Character Name**
Robert Bates

**Auftrittszeitpunkt (Datum / Uhrzeit)**
dauerhaft

**Beobachtetes Verhalten**
hoher Verbrauch / niedrige Reichweite des Sultan Classic im Vergleich zu anderen Tuningfahrzeugen

**Erwartetes Verhalten**
ähnliche Reichweite des Sultan Classic zu vergleichbaren Tuningfahrzeugen

**Schritte um den Fehler nachvollziehen zu können**
verschiedene Tuningfahrzeuge mit vollem Tank bei mittel- bis topspeed leer fahren (Sultan Classic, Elegy Retro Custom, Jester Classic, Flash GT, ...) und die geschafften Kilometer vergleichen

**IC-Begebenheiten**
Sultan Classic: Tankgröße: 60 Liter; Verbrauch pro Tick: 0,2 - 0,3 Liter bei normaler Fahrt, bei Topspeed 0,4 Liter pro Tick
Vergleichswerte: Tankgröße: 70 Liter (Elegy RC, Flash GT, Jester Classic, etc.); Verbrauch pro Tick 0,1-0,3 pro Tick

**Auswirkungen**
Aufgrund des erhöhten Verbrauchs und kleineren Tanks muss man sich deutlich früher als andere Fahrzeuge zum Tanken, dies stört häufig die Atmosphäre bei Ausfahrten, da andere bei Weitem noch nicht tanken müssen, die Ausfahrt aber aufgrund eines einzelnen Sultan Classics unterbrochen wird.
Auch bei Races schaffen oben genannte Fahrzeuge 2-3 Races (10-20 km) mehr als ein Classic, weshalb man sich aus diesen Situationen zum Tanken zurückziehen muss, was sind negativ auf die eigene Stimmung auswirken kann. 
Aufgrund der erhöhten Gefahr einer Verfolgungsjagd mit den Cops empfiehlt es sich bei 30 Litern tanken zu fahren, da man sonst wegen des hohen Verbrauchs kaum Spielraum hat, um eine ausgewogene, faire und interessante Verfolgungsjagd zu bieten.
Aufgrund seiner mittelmäßigen Overall Performance, was Leistung angeht, hat er Schwierigkeiten mit vielen neueren und älteren Tuningfahrzeugen mitzuhalten. Das und seine unterdurchschnittlichen Verbrauchsdaten machen ihn für die Szene unattraktiv und für den Fahrer teils zum Handicap. Er wird kaum als Option in Betracht gezogen.

**Lösungsvorschläge**
1. Erhöhung der Tankkapazität auf 70 Liter, um ebenbürtige Ausgangsbedingungen für die Tuningfahrzeuge zu schaffen (Wunsch)
2. Verringerung im Verbrauch, damit man länger mithalten kann, aber trotzdem die Downside des kleineren Tanks erhalten bleibt
3. Eine Mischung aus beidem bzw. beide Anpassungen (Ideal)

**Persönliche Meinung**
Der Sultan Classic ist ein älteres aber dennoch interessantes Fahrzeug, welches ein gutes Gegengewicht zu den neuen Tuningfahrzeugen darstellt. In der Tuningszene gehört der Sultan Classic, was die Gesamtleistung angeht, zum niedrigen Mittelfeld. Die geringe Kilometerlaufleistung pro Tankfüllung macht das Fahrzeug für viele unattraktiv, da er mit Elegy RC, Flash GT, Jester Classic etc. weder in der Leistung noch im Verbrauch mithalten kann.
Es ist deprimierend alle 20 Minuten tanken fahren zu müssen, für eine Unterbrechung bei Ausfahrten zu sorgen und Unmut Anderer zu ernten, da dieser Cut ihre Stimmung genauso mindert wie die eingenen.
Ich habe mich bereits mit mehreren Sultan Classic Fahrern OOC ausgetauscht, sie stimmen diesem Problem vom Classic zu. Wir sehen die beste Lösung für dieses Problem in der Erhöhung des Tanks auf die für Tuningfahrzeuge übliche Größe von 70 Litern.
Da das Fahrzeug es von Haus aus leistungstechnisch gegen viele andere Tuningfahrzeuge Probleme hat, ist es wünschenswert eine annähernd ähnliche Laufleistung zu gewährleisten.

**Abschluss**
Danke fürs Lesen und drüber nachdenken. Weiterer Input und Gedankengänge sind gewünscht.
Beste Grüße und einen erfolgreichen Tag.

-eure Sultan Classic Fahrer

**Comment by SatyriaDine** [comment]
Gleiches betrifft auch den Sultan RS Classic.

**Comment by Hutstaender** [comment]
Der Sultan ist dabei kein Einzelfall unsere Fahrzeuge sind grundsätzlich was Verbrauch und Tankvolumen angeht in einem fest gesteckten Rahmen, je nach Fahrzeugklasse. Dabei sind viele unterschiedlich, damit jedes Fahrzeug seinen eigenen Flair bekommt.

Wenn wir anfangen jedes Auto miteinander zu vergleichen landen wir am Ende dabei, dass alles exakt gleich wird und das wollen wir nicht. Es wird auch in Zukunft Fahrzeuge mit höherem und niedrigerem Verbrauch und Tankvolumen geben.
