### ISSUE TITLE
Objektentfernung Leiche Sandy Shores

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#2284]
**Auftrittszeitpunkt (Datum / Uhrzeit)**
Schon immer

**Beobachtetes Verhalten**
Es gibt durch GTA geplacet eine Leiche am Alamo See in Sandy Shores, welche regelmäßige Polizeieinsätze verursacht, da sie immer wieder durch Bürger gemeldet wird, woraufhin dann das PD / MD meist einfach eine "Puppe" feststellt und diese "mitnimmt". Vielleicht könnte man sie ja auch einfach entfernen. Um nicht alle paar Wochen dasselbe Spiel zu haben.

**Optional: Video / Bilder des Fehlers**

https://youtu.be/O_dcm3hxevM

**Comment by TheOutburst** [comment]
hab mal die Leiche aufn Friedhof gebracht, nach 3 Jahren wirds langsam mal Zeit
