### ISSUE TITLE
NSA Base entfernen/ändern

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#2285]
**Beobachtetes Verhalten**
Auf der Map existiert immer noch die "NSA - Base" was eig. ein Relikt aus vergangenen Zeiten ist und auch eher an FiveM Sprech erinnert. Ggf. entweder ändern in Observatorium oder ganz entfernen

**Optional: Video / Bilder des Fehlers**

![Grand Theft Auto V Screenshot 2021 10 21 - 18 01 33 50](https://user-images.githubusercontent.com/70178420/154098140-dbbf1df3-4eae-493d-9875-8a0460387b1e.png)

**Comment by milkdrops** [comment]
Genau wie @epichalt sagt
