### ISSUE TITLE
40x Heroin Aufgabe / Abgabepunkt 

### ISSUE THREAD

**Issue by KingBuki** [mexyn/statev_v2_issues#2286]
40er Hero Aufgabe kann man nicht abschließen da ein Abgabe Punkt s. Bild, nicht möglich ist.
![Bild1](https://user-images.githubusercontent.com/84183904/154259806-532cd1d3-33db-41ed-b998-ba91ae31c19d.PNG)
![Bild2](https://user-images.githubusercontent.com/84183904/154259816-2fde443c-11b0-474b-8015-b9742a40bb8d.PNG)

**Comment by TheOutburst** [comment]
next update fixed
