### ISSUE TITLE
Ablieferungspunkt Koks Fehlerhaft

### ISSUE THREAD

**Issue by StateV-Jan** [mexyn/statev_v2_issues#2288]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Jan Bach
**Auftrittszeitpunkt (Datum / Uhrzeit)**
17/02/2022 11:45

**Beobachtetes Verhalten**
Dadurch das der Ablieferungspunkt für Koks auf ein Wohnungsmarker ist öffnet sich der Wohnungspart zum betreten und man kann kein Koks abliefern. 

**Erwartetes Verhalten**
Ablieferung sollte möglich sein, ggf Koksabliefungspunkt verschieben oder höhere Priorität geben
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/komprimiert.53uQg

**Comment by TheOutburst** [comment]
next update fixed
