### ISSUE TITLE
Galivanter Baller ST falsch benannt

### ISSUE THREAD

**Issue by Koray5858** [mexyn/statev_v2_issues#2289]
Character Name
Jason_Rains

Auftrittszeitpunkt (Datum / Uhrzeit)
17.02.2022

Beobachtetes Verhalten
Import Name vom Baller ST wird falsch angezeigt und kann dadurch nicht aus dem Import abgeholt werden.

Im Folgenden Link wurde das Problem schon als Solved gelabelt, jedoch besteht der Fehler immer noch.

https://github.com/mexyn/statev_v2_issues/issues/2220

**Comment by Enemyaa** [comment]
Next Update!
