### ISSUE TITLE
Animationsordner multipliziert sich 

### ISSUE THREAD

**Issue by TajuuLa** [mexyn/statev_v2_issues#229]
**Character Name**
Emilia Bradley

**Zeitpunkt (Datum / Uhrzeit)** 
20.11.2020

**Beobachtetes Verhalten** 
Es wurden zwei Ordner für Animationen angelegt. Im ersten Ordner waren bereits 6 Animationen gespeichert. Daraufhin habe ich einen zweiten Ordner erstellt und in diesen knapp 4 Animationen hinzugefügt. Zwei von diesen, wurden jedoch dann auch im Ordner 1 angezeigt, obwohl diese dort NICHT gespeichert wurden. Als die Animation in Ordner 1 gelöscht worden ist, wurde sie auch aus Ordner 2 entfernt.

**Schritte um den Fehler nachvollziehen zu können**
Füge unter 8 Animationen in Ordner 1 hinzu und anschließend andere in Ordner 2. Wenn Animationen in Ordner 2 eingespeichert werden, müssten Animationen in Ordner 1 ebenso auftauchen.

**Comment by DonVitoDiangelo** [comment]
Kann nicht reproduziert werden. Falls wer noch den Fehler hat, bitte bestätigen.

**Comment by TajuuLa** [comment]
Habe beide Ordner gelöscht und neu angelegt. Problem nicht mehr bestehend.. 😃
