### ISSUE TITLE
Durch Bape Shorts GPU und CPU voll ausgelastet/ PC schmiert ab

### ISSUE THREAD

**Issue by AndoMalius** [mexyn/statev_v2_issues#2291]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

** Ando Malius**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
00:10 Uhr 18.Feb

**Beobachtetes Verhalten**
Nach dem Kauf einer Bape short zum Hotel gefahren, beim betreten und neu laden des Charakter knallt die auslastung auf 100% und der PC schmiert ab. Auch die anderen Versuche neu einzuloggen Funktionieren nicht da direkt beim neuladen sich GPU und CPU verabschieden.

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**
Bape Shorts Modelname unbekannt. Halb/Halb Grün Camo / Schwarz mit Trauer smiley, langes Model. Kaufen und Charakter nach dem anlegen neu laden lassen durch betreten vom Hotelzimmer.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by AndoMalius** [comment]
Während dem Charakter Laden kann das Hotelzimmer mit E spamen verlassen werden und das Game läuft. Nach dem wechseln auf eine Standard Hose, gibt es keine Probleme beim betreten des Hotels.
Ausser nochmals auf die Bape shorts gewechselt und direkt wieder Absturz beim betreten vom Hotel.
[M] 2-Tone Woodland Bape Sagged Shorts

**Comment by Enemyaa** [comment]
Hi, ich konnte dein Problem leider nicht nachstellen. Es macht bei mir absolut gar keinen Unterschied welche Hose ich trage, wenn ich ein Apartment joine. Ich weiß nicht was du alles nebenher laufen hast und wie lange dein PC schon läuft am Stück, aber ich hier noch nebenher Wow offen und absolut gar keine Probleme. 

Drum kann ich dir nur raten, wenn du das Problem in der Hose siehst, sie einfach nicht mehr zu tragen.
