### ISSUE TITLE
Hütchen beschädigen Fahrzeug / Abladepunkt versetzen

### ISSUE THREAD

**Issue by JonesMorgan2020** [mexyn/statev_v2_issues#2292]
**Character Name**
Jones Morgan

**Ort / Firma**
pfAkiTextileCityRew_22 / Sinner Street 59 neben Mission Row

**Auftrittszeitpunkt (Datum / Uhrzeit)**
immer

**Beobachtetes Verhalten**
Hütchen (https://pic.statev.de/image/58PkV) beschädigen das Fahrzeug.
Manchmal wenn man drüber fährt aber meistens wenn man aus der Firma kommt und das Fahrzeug darauf spawned.
3 x Gelbe Kontrolleuchte in 7-10 Tagen ohne vorangegangenen Crash

**Erwartetes Verhalten**
Bitte entfernen

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/58PkV

**Nachtrag:**
Bitte Abladepunkt um ein kleines Stück auf die Straße versetzen.
Man erreicht den fast nur wenn man die Laterne umfährt
![hinderniss](https://user-images.githubusercontent.com/76733801/154700379-50c2439b-a380-49bc-acd6-4af38ccffdb2.png)

**Comment by Enemyaa** [comment]
Hi,
ich hab die Hütchen mal weggemacht und den Marker nach vorne gezogen, da das hier wohl auch nicht viele lesen werden und es mit dem Marketplace vielleicht öfter zu solchen Problemen kommt. 

Next Update! 

Aber für dich als Tipp bis dahin. Der Marker hat ein sehr großen Radius. Schau mal auf meinem Bild https://i.imgur.com/knL2OQf.png. Es ist absolut unproblematisch von dort ein- und auszuladen.

**Comment by JonesMorgan2020** [comment]
Danke, bei mir hats nicht geklappt, der Marker hat das Fahrzeug knapp nicht berührt und schon gings nicht.
Aber vielen Dank schon mal für die Mühe!

**Comment by JonesMorgan2020** [comment]
Eine Frage, ab wann sollten die Änderungen erfolgen ?
