### ISSUE TITLE
Autos werden Unsichtbar

### ISSUE THREAD

**Issue by ShoxqZ1312** [mexyn/statev_v2_issues#2294]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**Ace Kings
Ace Kings

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 Jeden Nachmittag/Abend 19 Uhr ca

**Beobachtetes Verhalten**
 Die Autos die auf dem Darknet Parkplatz stehen, werden Unsichtbar. Wenn man sie ortet, stehen sie dort, sind aber nicht sichtbar für uns. 

**Erwartetes Verhalten**
Man sollte sie im besten Falle sehen können ^^

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TheOutburst** [comment]
#2248
