### ISSUE TITLE
Hausgarage Auto spawnt so, dass es oft Schaden bekommt

### ISSUE THREAD

**Issue by cadpri** [mexyn/statev_v2_issues#2295]
**Character Name**
Fabian_Picard

**Auftrittszeitpunkt (Datum / Uhrzeit)**
jedes Zweite mal, wenn ich das Auto aus der Hausgarage ausparke

**Beobachtetes Verhalten**
in 50% aller Fälle wird das Auto aus der Hausgarage Westmirror Drive 31 so schief raus gespawnt, dass es jedes mal Schaden an der Hauswand bzw Mauer nimmt.
Dabei ist es unrelevant, ob ich den Wagen vorher gerade oder schief in die Garage einparke oder ich ihn vor dem Haus gerade oder schief stehen lasse zum automatischen einparken.
Zudem fällt es im Verhältnis zu Öffentlichen Garagen relativ hoch wodurch auch Schaden entsteht.

**Erwartetes Verhalten**
Falls es machbar ist wäre es schön, wenn der Marker so weit nach vorne verlegt wird, dass das Auto keinen Schaden mehr nimmt, falls es schief aus der Garage spawnt. Es wäre auch schön, wenn es nicht mehr so hoch fallen würde.

**Schritte um den Fehler nachvollziehen zu können**
Auto einparken und wieder ausparken.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920 x 1080

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=LrHwDoMHoPQ

**Comment by Enemyaa** [comment]
@its4l3x Das Heading wird gar nicht ausgelesen. Man kann zwar selber bestimmen wie man das Auto einparkt und genau so wieder ausparken, aber wenn das Auto durch ein server restart eingeparkt wird, hat es immer die letzte Parkposition und wenn die waagerecht zum Haus, auf der Straße war, wird das Auto eben auch waagerecht ausgeparkt.

**Comment by cadpri** [comment]
Naja nicht so wirklich. Wenn ich das Auto schön gerade in der Einfahrt abstelle und es automatisch einparken lasse spawnt es in der Hälfte aller Versuche genau so schief wie in dem Video

**Comment by Enemyaa** [comment]
Also es sollte eigentlich so sein, dass das Auto immer so ausparkt, wie man selbst manuell einparkt. Bei mir ist das tatsächlich auch so. Problematisch wird es nur, wenn der restart es einparkt.

**Comment by cadpri** [comment]
Ja das sage ich ja. Und das ist der Grund warum ich bitte den Marker etwas nach vorne zu setzen, damit das Auto keinen Schaden mehr nimmt, wenn es automatisch eingeparkt wurde.

**Comment by Enemyaa** [comment]
@cadpri next update! Teste dann mal den neuen!

**Comment by cadpri** [comment]
Super Dankeschön! Ja ich teste dann mal nach dem Update
