### ISSUE TITLE
Ladepunkt versetzen

### ISSUE THREAD

**Issue by CosaTV** [mexyn/statev_v2_issues#2296]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Cosa Neubrandenburg**

**permanent**

**Be- und Entladepunkt versetzen**
Firmenhash: pfJunDelPerroBeach10

Verladepunkt gerne auf den Punkt der Firma: pfJunDelPerroBeach9 versetzen, sodass beide Firmen den gleichen Ladepunkt benutzen können.

Verladepunkt wurde auf RAGE schon mal versetzt. Durch das "Mapping" und Wechsel auf ALTV ist dieser versetzte Punkt allerdings mit LKWs nicht mehr so gut zu erreichen, da durch den Serverwechsel im unmittelbaren Umfeld neue Gegenstände entstanden sind - zBsp Poller, Parkplatzbegrenzungen.

Dankeschöön!
Grüße, Cosa

**Comment by Enemyaa** [comment]
Next Update!
