### ISSUE TITLE
Auslese Probleme 

### ISSUE THREAD

**Issue by Reggi257** [mexyn/statev_v2_issues#2298]
Festgestellt mit Reggi Stone

Folgendes problemm immer mehr und öfter kommen kunden an die werkstatt und haben problemme das die autos nicht mehr richtig beschlenigen oder auf endgeschwindigkeit kommen. doch leider werden beim auslesen nie fehler angezeigt. es kommt aber die letzte zeit so oft vor das man da nicht mehr von reden kann das die kunden das fehlverhalten nur einbilden

**Comment by Dean-Gallagher** [comment]
Kein auslesebug 

Glaube AltV Bug 

Workarround -> Motor ausschalten, aussteigen und wieder einsteigen .. Fixed

**Comment by Reggi257** [comment]
Also die sachen wie motor aus an und ein und aussteigen haben bei denn fahrzeugen nichts gebracht

**Comment by Dean-Gallagher** [comment]
wenn die reinfolge motor aus, aussteigen, wieder einsteigen und motor an nichts bringen hilft nur noch der klassische relog. 

wir haben keine probleme aktuell mit dem auslesen nur das problem wo die 2 wege wie von mir beschrieben helfen
