### ISSUE TITLE
Ladepunkt versetzen

### ISSUE THREAD

**Issue by Pommes11478** [mexyn/statev_v2_issues#2299]
Character Name
Kurt Weiland

Kurt_Weiland

Auftrittszeitpunkt (Datum / Uhrzeit)

Beobachtetes Verhalten

Be- und Entladen sehr mühselig, durch die parkenden Fahrzeuge.

Erwartetes Verhalten
![Ladepunkt_2](https://user-images.githubusercontent.com/71652319/155690047-5edf8173-3ce3-49b3-967b-7c934731bd93.jpg)

Be- und Entladepunkt auf die Straße versetzen
Der Be- und Entladepunkte der Firma bitte auf die Straße versetzen.
Firma:
Kuddels Mühle - Atlee Street 113 (Firmenhash: pfAkiyamaTextileCityRew_19)

Optional: Video / Bilder des Fehlers

Ladepunkt: https://pic.statev.de/image/ladepunkt-2.5VHJV

**Comment by Enemyaa** [comment]
Next Update!
