### ISSUE TITLE
Fehler in der Bugtrackervorlage

### ISSUE THREAD

**Issue by ProgrammingFox** [mexyn/statev_v2_issues#23]
**Zeitpunkt (Datum / Uhrzeit)**

25.08.2020 19:35 Uhr
**Beobachtetes Verhalten**

Der Zeitpunkt + die Überschrift für Beobachtetes Verhalten wird ausgeblendet.
**Erwartetes Verhalten**

Bei Zeitpunkt müsste am Ende "-->" stehen statt "->" da sonst der gesamte Zwischenraum bis Beobachtetes Verhalten auskommentiert wird.
**Schritte um den Fehler nachvollziehen zu können**

Neuen Bugtrackerentry erstellen
**Optional: Video / Bilder des Fehlers**

**Comment by tastydev** [comment]
fixed
