### ISSUE TITLE
RayBan Brille nicht sichtbar

### ISSUE THREAD

**Issue by VitoCastellano** [mexyn/statev_v2_issues#2300]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
 Vito_Castellano

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 25.02.2022 20:25

**Beobachtetes Verhalten**
 RayBan Brille [M] nicht mehr sichtbar - https://gyazo.com/c494dbd57a4d3f7e42318166f544115d

**Erwartetes Verhalten**
 Brille sollte sichtbar sein

**Schritte um den Fehler nachvollziehen zu können**
 Brille nach anziehen nicht sichtbar

**Optional: Video / Bilder des Fehlers**
 
![c494dbd57a4d3f7e42318166f544115d](https://user-images.githubusercontent.com/84188576/155776293-8379cbc5-9931-4ec2-8ae8-97e97dbbdb8b.jpg)

**Comment by SHaagmann** [comment]
Ist n bekanntes AltV Problem
![image](https://user-images.githubusercontent.com/58612983/155799445-0bf6abbd-d8c0-4f4f-b71b-9fa9eae16e69.png)

**Comment by Enemyaa** [comment]
Next Update!
