### ISSUE TITLE
Teleportpunk hinzufügen + Hotelpunkt verschieben

### ISSUE THREAD

**Issue by WalDragoner3425** [mexyn/statev_v2_issues#2301]
Hey, 

ich wollte Mal fragen, ob es möglich wäre bei dem Hotel mit dem Firmenhash "JunRockFordHillsRew_Flat_11", das blaue Hotelmenü in die Mitte der rechten Doppeltür zu setzen sowie in der Mitte der linken Doppeltür einen Teleportpunkt zum Dach hinzuzufügen (siehe Bild).

LG
William Void

![InkedScreenshot 2022-02-25 144922_LI](https://user-images.githubusercontent.com/56478386/155784638-1d1a66e2-977b-47e8-8cff-9568ebe70a55.jpg)

**Comment by Enemyaa** [comment]
Hi,
da ist halt absolut gar nichts. Nicht mal ne Tür. https://i.imgur.com/QkiCOdz.jpeg

**Comment by WalDragoner3425** [comment]
Hey, 
es wäre halt sehr cool, wenn man dort auf das Dach kommen würde, da dort echt viel Platz zum nutzen wäre. Vielleicht kann man ja die einzelne Textur einer Tür bzw. eine Tür dort oben in die Fassade modden oder sowas ähnliches, damit es optisch ebenfalls passt. 

Falls das nicht geht, wäre dass sehr schade aber eventuell kann man dann ja wenigstens den Hotelpunkt mittig setzen.

LG
