### ISSUE TITLE
Entfernung von Einkaufswagen

### ISSUE THREAD

**Issue by Hochfels** [mexyn/statev_v2_issues#2302]
Character Name
Marcel Hochfels

Firmenhash: lapuerta14
Firmenname: HK-P564 | Schall und Rauch - Alta Street 13 

Wunsch: Ich würde mich sehr freuen, wenn die Einkaufswagen entfernt werden könnten. Gerade wenn größere Fahrzeuge kommen, stören die ungemein. Es sind die Einkaufswagen direkt vor der Treppe. Alle.
Ich hoffe das geht bzw. ist ok, obwohl ich die Firma nur gepachtet habe. Ich kann mir aber vorstellen, dass es andere auch sören würde. Oder alternativ, wenn entfernen doof ist, dass man die versetzt, Würde mich wirklich freuen, da die Einkaufswagen stören :)

**Comment by Enemyaa** [comment]
Next Update!
