### ISSUE TITLE
Tragesystem des LSMDs hat neue Bugs

### ISSUE THREAD

**Issue by SvenPhoenix** [mexyn/statev_v2_issues#2304]
## WICHTIGE INFORMATION!!:
```

```

**Sven Phoenix**

**25.02.2022 (ca. 21 Uhr) und 26.02.2022 (ca. 01 Uhr)**

**Das Tragesystem lädt Spieler für den Medic zwar ins Fahrzeug ein (Und der Spieler/Patient sitzt auch drinne. Aber der Patient bleibt aus seiner Sicht am Einsatzort liegen und kann auch mit Umstehenden Kommunizieren. Der Spieler hat nun einen Klon von Sich im Rettungsfahrzeug sitzen (Der Medic kann alles hören was der Spieler sagt). Liegt dabei aber eigentlich noch unsichtbar am Einsatzort.**
**Im zweiten Fall wurder der Spieler zwar ins Rettungsfahrzeug reingesetzt aber wurde aus Sicht der Beteiligten hinter dem Fahrzeug hergeschliefen. An der Anzeige fürs Anschnallen kann man sehen das der Patient Offiziel nicht im Fahrzeug war (Es waren 3 Personen im Fahrzeug).** 

**Patienten sollten wieder richtig im Rettungsfahrzeug sitzen. (Ja ich weiß das Tragenfehler bekannt sind aber dieser beiden sind meiner Meinung nach neu und erst seit kurzem vorhanden.**

**Eine Bewusstlose (aber stabilisierte) Person auf die Trage packen und ins Fahrzeug einladen**

**Hier die Clips zu den Beiden Fällen**

https://www.youtube.com/watch?v=oDOfRdjmBLQ **Achtet auf die Anschnallanzeige!!**
https://www.youtube.com/watch?v=qtRItWYTJmA

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2438
