### ISSUE TITLE
Fahrzeug kann nicht zurückgegeben werden

### ISSUE THREAD

**Issue by Irishman1991** [mexyn/statev_v2_issues#2308]
Ich wollte nach über zwei Jahren meinen ersten gemieteten Budhi zurückgeben. Frisch repariert und getankt, wollte ich das Fahrzeug zurückgeben. Der Vermieter gibt mir aber die Fehlermeldung "Das Fahrzeug ist nicht gemietet". Daraufhin habe ich versucht, das Fahrzeug zu verschrotten. Beim verschrottet sagt das System aber "Das Fahrzeug ist gemietet.

Charakter Name: Patrick_Okeen

**Comment by Hutstaender** [comment]
Lass dir das Fahrzeug bitte über den Support entfernen. Da ist wohl damals was schief gegangen.

**Comment by Bene-RonnyMoritz** [comment]
Fahrzeug wurde gelöscht :)
