### ISSUE TITLE
Fahrzeuge werden beschädigt beim Ausparken aus der Hausgarage

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#2309]
Santito Quintero
house_MirrorPark_34
house_MirrorPark_34 - West Mirror Drive 35
**Auftrittszeitpunkt (Datum / Uhrzeit)**
Beim ausparken

**Beobachtetes Verhalten**
Ähnlich wie hier https://github.com/mexyn/statev_v2_issues/issues/2295 werden die Autos teils quer und schief ausgeparkt. Manchmal direkt in einem Schild oder auf der Mauer vor dem Haus. Dadurch liegen die Autos manchmal auf der Seite oder kommen direkt qualmend aus der Garage.  Passiert jetzt nicht jeden Tag, aber etwa 2x die Woche. 

**Erwartetes Verhalten**
Fahrzeuge sollten unbeschadet ausgeparkt werden

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Enemyaa** [comment]
Hi, schau mal beim nächsten Update, ob es besser ist. Vom Restart eingeparkte Autos werden so ausgeparkt, wie sie zuletzt geparkt wurden.
