### ISSUE TITLE
Abladepunkte zusammen legen 

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#2310]
Santito Quintero 
Vortec Ind. Depot - Mirror Park Blvd. 11  Hash: pfGroupAllRew_1
Vortec Ind. Cars - Mirror Park Blvd. 26 Hash :  pfGroupAllRew_16
Vortec Ind. Melting - Mirror Park Blvd. 29 Hash: pfGroupAllRew_18

Hallo, nach 2.5 Jahren mühevollem Umladen hätten wir gerne die Abladepunkt der 3 Firmen zusammen gesetzt. Optimal wäre relativ mittig bei dem X. Bin aber auch für Gegenvorschläge offen :D 

![7ec4196dc0c94cf03a4662180e69d295](https://user-images.githubusercontent.com/16436981/156396581-f885b73c-e457-4238-8fdd-d31bc858cb02.jpg)

**Comment by Enemyaa** [comment]
Next Update!
