### ISSUE TITLE
Spawne am nächsten Tag an der NSA Base

### ISSUE THREAD

**Issue by wichtTSV** [mexyn/statev_v2_issues#2311]
**Character Name**
Tom Spider

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.03.2022 9:47 und andere Tage

**Beobachtetes Verhalten**
Ich spawne immer wieder mal morgens an der  NSA Base, obwohl ich mich im Haus auslogge

**Erwartetes Verhalten**
Das ich auch wieder im Haus spawne und nicht an der NSA Base

**Schritte um den Fehler nachvollziehen zu können**
Gehts das? Ich logg mich im Haus aus und spawne am nächsten Tag wo anders

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
/

**Optional: Video / Bilder des Fehlers**
/

**Comment by DonVitoDiangelo** [comment]
Hast du das Problem noch immer? @wichtTSV
