### ISSUE TITLE
Fahrzeug nach GameChrash weg

### ISSUE THREAD

**Issue by JaxBorrow** [mexyn/statev_v2_issues#2312]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Jax Borrow

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.03.2022 um zirka 19:10Uhr

**Beobachtetes Verhalten**
Nach einem Gamecrash waren der von mir benutzte Barricks Semi sowie der daran angehängte Tanke 2 für mich nicht mehr sichtbar. Andere Spieler konnten beide Fahrzeuge sehen, aber nicht mit ihnen interargieren. Ein entfernen von dem Kartenbereich und anschließendes zurückkehren an den Ort hat auch keine Abhilfe schaffen können. Schlüssel konnte für einen weitern Lösungsansatz übergeben werden, hat aber leider auch nichts gebracht.

**Erwartetes Verhalten**
Das die Fahrzeuge nach Relog weiterhin sichtbar und nutzbar sind

**Schritte um den Fehler nachvollziehen zu können**
Es ist schwierig dies zu reproduzieren, da es nach einem Gamecrash war. Ist bei mir schon öfter aufgetreten in letzter Zeit.

**Optional: Video / Bilder des Fehlers**
1. Crash und Relog
https://drive.google.com/file/d/1bC84QOP_A9e_hFE_v0ccvkm2McxIGP_p/view?usp=sharing

2. Rückkehr zum Ort des Geschehens + Test mit Schlüsselübergabe
https://drive.google.com/file/d/1lkgv2-h3YxWZvcSw9Htik5rNtn7XUs1p/view?usp=sharing

**Comment by CaleighRhodes** [comment]
Ist ein bekannter Bug derzeit, falsche Dimension, dann in den Support und teleportieren lassen.

**Comment by JaxBorrow** [comment]
So auch gelöst. Mir war nur neu dass das Fahrzeug für andere Spieler sichtbar bleibt. Und Lela meinte, dass ich mal einen Bug-Tracker schreiben soll. Danke für die schnelle Reaktion

**Comment by CaleighRhodes** [comment]
Bin kein Teammitglied, dachte nur, dir ist das nicht bekannt. Wenn das ein GM gesagt hat, würd ich das Ticket offen lassen an deiner Stelle :)

**Comment by Enemyaa** [comment]
Hi,
es gibt einen Sammelthread dazu #2248
