### ISSUE TITLE
Fahrzeug posi in Autohaus/Werkstatt wird nicht richtig gespeichert

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#2313]
**Character Name**
Horizon Hottest Cars/Engines

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Alle Fahrzeuge in Werkstatt und Autohaus rücken nach jedem neustart immer eine kleine Ecke weiter in eine gewisse Richtung bis ein hinderniss kommt und sie dran festhängen oder sogar reinclippen. 

**Erwartetes Verhalten**
Fahrzeugposi wird korrekt gespeichert

**Comment by epichalt** [comment]
Ist nicht nur nach Neustarts so und auch außerhalb von Autohäusern. Die Fahrzeuge „wandern“ immer minimal. Glaube mit angezogener Handbremse funktioniert das. Im Autohaus fällt es nur stärker auf, da die Autos in der Regel länger stehen. 
meine mal gelesen zu haben es sei ein altv bug. Aber finde es grad nimmer

**Comment by Dean-Gallagher** [comment]
> Ist nicht nur nach Neustarts so und auch außerhalb von Autohäusern. Die Fahrzeuge „wandern“ immer minimal. Glaube mit angezogener Handbremse funktioniert das. Im Autohaus fällt es nur stärker auf, da die Autos in der Regel länger stehen. meine mal gelesen zu haben es sei ein altv bug. Aber finde es grad nimmer

nach neustart ist handbremse wieder raus :(

**Comment by PrimroseBloom** [comment]
> Ist nicht nur nach Neustarts so und auch außerhalb von Autohäusern. Die Fahrzeuge „wandern“ immer minimal. Glaube mit angezogener Handbremse funktioniert das. Im Autohaus fällt es nur stärker auf, da die Autos in der Regel länger stehen. meine mal gelesen zu haben es sei ein altv bug. Aber finde es grad nimmer

Mit angezogener Handbremse "wandern" die Autos auch. Auch ohne Neustart.

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2116
