### ISSUE TITLE
Sonnenbrille [F][Glasses] Black Windsor nicht Sichtbar

### ISSUE THREAD

**Issue by SgtTukiTuki** [mexyn/statev_v2_issues#2314]
**Character Name**
Sandy_Folk und Freya_Baranow

**Auftrittszeitpunkt (Datum / Uhrzeit)**
09.03.2022 gegen 13.00 Uhr 

**Beobachtetes Verhalten**
Wollte besagt Sonnenbrille aufsetzen! Im Kleidungsinventar ist sie zwar auch am Platz aber am Charakter selber ist sie nicht Sichtbar! Habe diese Brille dann Freya_Baranow gegeben und dort ist genau dasselbe Ergebnis gewesen!

**Erwartetes Verhalten**
Die Brille sollte Sichtbar sein

**Comment by Enemyaa** [comment]
Ist bekannt und gefixt. Die Brille wird mit dem nächsten Update wieder sichtbar sein.

**Comment by SgtTukiTuki** [comment]
Okay :D
