### ISSUE TITLE
Custom Pounder bleibt am Baum hängen

### ISSUE THREAD

**Issue by Digawen** [mexyn/statev_v2_issues#2317]
Character: - Ronnie Flex

Datum / Uhrzeit: 16.03.22 gegen 9.00 Uhr

Fehler: Zum wiederholten Male bin ich mit meinem Custom Pounder an einem Baum an der Senora Road hängen geblieben. Heute sogar mit einem Totalschaden als Folge. Ich bin nicht zu weit am Fahrbahnrand gewesen, sondern schon auf den zu erkennenden Fahrbahnrillen. (Bilder hänge ich an)

Evtl. Baumpflege als Lösung oder es liegt am Custom Pounder, dann ist es so.

Fahrt ging vom ADAC in Richtung Norden auf dem Weg zum Salzsee.

Mfg 
![pounder 1](https://user-images.githubusercontent.com/4532046/158546249-da157086-c2e1-4035-b4b6-8014bd5727b1.png)
![pounder 2](https://user-images.githubusercontent.com/4532046/158546264-0174420e-633d-460b-aec3-abfa2d9b525e.png)

**Comment by Enemyaa** [comment]
HI, in 2 von 10 Fällen stößt man da an eine Kollision, die bei mir gar kein Schaden hinterlassen hat, aber schon kräftig war. Auf dem Mittelstreifen hab ich gar keine Probleme. Die Kollision bleibt aber auch beim entfernen zurück und du solltest das halt so handhaben wie das RP es eben hergibt. Das heißt, WENN du dort öfter einen Unfall hast, dann fährst du entweder langsamer links dran vorbei oder nutzt einen anderen Weg.
