### ISSUE TITLE
Moosgrüne Bomberjacke => Einweg - "Wechsel"jacke

### ISSUE THREAD

**Issue by PlexerPG** [mexyn/statev_v2_issues#2318]
**Character Name**

Paul Graham

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer

**Beobachtetes Verhalten**

Wenn man eine "Moosgrüne Bomberjacke,offen" trägt und diese geschlossen tragen möchte, ändert sich die Jacke in eine "Rote ProLabs Bomberjacke". Diese bleibt auch im Inventar so, auch wenn man sie wieder öffnet.

**Erwartetes Verhalten**

Das es eine "Moosgrüne Bomerjacke,offen" in Inventar bleibt und nicht wechselt.

**Schritte um den Fehler nachvollziehen zu können**

Kleidungsinventar -> Extra --> Jacke ---> von <offen> auf <geschlossen> ändern.

**Comment by PlexerPG** [comment]
Kleidungsinventar -> Extra --> Jacke ---> von -offen- auf -geschlossen- ändern.

**Comment by Enemyaa** [comment]
Ist schon gefixt. Gab den Bugtracker bereits. Next Update
