### ISSUE TITLE
Struthioo Aftershave nicht herstellbar?

### ISSUE THREAD

**Issue by EmmaSvensson** [mexyn/statev_v2_issues#232]
**Character Name**
Emma Svensson und Xavier Martinez 

**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020 / 7:15 Uhr

**Beobachtetes Verhalten**
Beim Bartschneiden fiel uns auf das uns das Struthioo Aftershave fehlt, da mein Kumpel sowohl ein Labor als auch mehrere anderen Firmen hat wollten wir es herstellen, jedoch Tauchte das Aftershave nirgends zum Herstellen auf.

**Erwartetes Verhalten**
Struthioo Aftershave soll laut Wiki im Labor Herstellbar sein 

**Schritte um den Fehler nachvollziehen zu können**
Ins Labor gefahren
Itemliste durchgesehen
Aftershave stand nicht zur Verfügung

**Comment by BlackyGER** [comment]
Fixed
