### ISSUE TITLE
Hausgarage bei zwei Villen für insgesamt 3.000.000 $ fehlend

### ISSUE THREAD

**Issue by Chabo90** [mexyn/statev_v2_issues#2320]
**Character Name**
Chabo_Denison

**Auftrittszeitpunkt**
Immer

**Haushash**
GroupAllRew_House_7
GroupAllRew_House_8

**Beobachtetes Verhalten**
Keine Hausgarage bei zwei Villen für insgesamt 3.000.000 $

**Erwartetes Verhalten**
Frage ob eine bzw. zwei Garagen hinzugefügt werden kann. (max. Anzahl)

![Download_18](https://user-images.githubusercontent.com/102000968/159191913-92f08eeb-f794-4224-9bf8-c781879860db.png)
![Download](https://user-images.githubusercontent.com/102000968/159191916-fff208d5-0145-4e90-be7b-57d537807eb7.png)
![Download_1](https://user-images.githubusercontent.com/102000968/159191924-c2b11480-5806-4e88-be3d-44e2d4d4b678.png)
![Download_2](https://user-images.githubusercontent.com/102000968/159191931-76576f70-5ae8-454a-9b09-b7bc534123df.png)
![Download_3](https://user-images.githubusercontent.com/102000968/159191933-0477def5-149d-4544-b224-c1a1f0f2b0ed.png)
![Download_4](https://user-images.githubusercontent.com/102000968/159191941-40b2f44c-5162-450d-bbd4-ea63590b1c0f.png)
![Download_5](https://user-images.githubusercontent.com/102000968/159191947-d3702a96-4529-4b58-ac80-24649234d36a.png)

**Comment by Statev-Bonsai** [comment]
da gabs schonmal beitrage zu...

https://github.com/mexyn/statev_v2_issues/issues/835
https://github.com/mexyn/statev_v2_issues/issues/795

ps... die haben damals ca 200k  je villa gekostet :D

**Comment by ClexaDebnamcarey** [comment]
Ja, im normalen GTA ist es ein Rehabilitationszentrum, allerdings sind wir hier auf einem GTA RP Server, und die beiden Häuser wurden als normale Villen verkauft.
1. Wenn es ein Rehabilitationszentrum ist, warum gibt es dort dann Marker um die Häuser kaufen bzw. zu betreten?
2. Wenn es ein Rehabilitationszentrum ist, warum bespielt dann nicht das MD dieses Grundstück?
3. Das Interior der Häuser, spricht für sich als normales Wohnhaus.
4. Es ist doch egal, was draußen vor dem Haus steht, ob jetzt chinesische Zeichen vor der Türe sind oder ein Schild eines Rehazentrums.. im Endeffekt sind die Personen drinnen lebend, keine Chinesen oder Mitarbeiter des Zentrums.
5. Vindicta bespielt eine Mafia mit 18 Personen und hat sich im RP auf dieses Grundstück festgelegt, wobei dieses Grundstück nun auch täglich bespielt wird.
6. @Bonsai vielleicht haben die Villen damals 200k gekostet, nur mit der Zeit steigt der Wert jeder Immobilie, das ist im Real Life so, und ich denke mir, wir spielen hier auf einem RP Server, dann wird dies hier genauso sein..

Wo wäre das Problem dabei, einen einfachen Marker zu setzen, um 18 Personen das RP zu versüßen? Noch dazu haben verschiedene "Privatpersonen" der Mafia eigene Häuser in der Umgebung. Wir sind meistens schon alleine 20 Minuten (oder auch länger) damit beschäftigt, im RP jedes einzelne Auto zusammenzusuchen, anstatt unser RP genießen zu können.

**Comment by Enemyaa** [comment]
Danke für deine freundliche Aufklärung @ClexaDebnamcarey Das wusste ich natürlich gar nicht! :-)

Du scheinst den Punkt nicht zu verstehen. E geht nicht darum, dass es als Rehabilitationszentrum bespielt werden SOLL, deswegen werde ich jetzt auf die anderen Fragen gar nicht eingehen. Es geht darum, dass das ist, was man offensichtlich SIEHT, offensichtlich gibt es aber keine Garage und kein Carport dort. Es EXISTIERT NICHT und wurde wie Bonsai erwähnt hat, aus diesem Grund abgelehnt.

**Comment by Enemyaa** [comment]
@Chabo90 

Da wir unser System umgebaut haben und die Autos täglich eingeparkt werden, haben wir Verständnis für eure Situation.
Ihr seid da oben ziemlich weitab vom Schuss und das RP darum diese Autos meilenweit wieder auszuparken oder gar trotz Villa, an der Garage auszuloggen, ist nicht wirklich wertvoll.
Ihr werdet also mit dem nächsten Update eine Garage für das Vorderhaus kriegen. Das Hinterhaus ist zu weit weg vom Kreisel (die Marker haben ne max. range) und die Rasenfläche bietet sich nicht an.
