### ISSUE TITLE
Item nach Serverresart wieder da

### ISSUE THREAD

**Issue by DrCassado** [mexyn/statev_v2_issues#2323]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Ricardo_Cassado

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Am 17.03 wurden items verschenkt welche 2 tage später wieder im haus waren (haus lager)

**Beobachtetes Verhalten**
Am 17.03 wurden items verschenkt welche 2 tage später wieder im haus waren (haus lager). diese waren dan sowohl bei mir als auch bei der beschenkten person. (wurden inzwischen vom Support vernichtet)

**Erwartetes Verhalten**
Die item sollte nur die beschenkte person haben

**Schritte um den Fehler nachvollziehen zu können**
ich vermuute dies lag an einen auserplanmässigen serverneustart, da die item nach den auslogen weg waren und zum einloggen wieder da wahren.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/kbizumJbNdI (sorry für die ... quali nutze obs inzwisachen nur noch zum aufnehmen da der pc kaum leistung hatt

**Comment by DonVitoDiangelo** [comment]
Ja, dies KANN vorkommen. Dann am besten, um Missverständnisse zu vermeiden, in den Support kommen und melden/hinterlegen lassen.
