### ISSUE TITLE
Autos buggen unter die Map Vespucci

### ISSUE THREAD

**Issue by Relauty** [mexyn/statev_v2_issues#2324]
## WICHTIGE INFORMATION!!:
``` 
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Ralf Schulz**

Ralf_Schulz, Jordan_Wonabi, Carl_Reinsen, Enola_Berry, Anto_West, Micka_Sanders, Kevin_Schultz, Luke_Private, Domo_East
**Auftrittszeitpunkt (Datum / Uhrzeit)**

25.03.2022 / 20:00 Uhr
**Beobachtetes Verhalten**

Als Ich (Ralf_Schulz) aus dem Hotel erwacht bin, Habe ich nicht mehr die Fahrzeuge gesehen die ich ausgeparkt hatte. Die Autos werden mir auf dem Handy angezeigt wenn ich die Fahrzeuge Orte. Meine Mitspieler können die Fahrzeuge ebenfalls nicht sehen. 
**Erwartetes Verhalten**

Ich erwarte das die Fahrzeuge da stehen bleiben wo ich sie hin geparkt habe
**Schritte um den Fehler nachvollziehen zu können**

Ich denke das die Autos unter die Map gebuggt sind. Das passiert in Regelmäßigen abständen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

X
**Optional: Video / Bilder des Fehlers**

**Comment by TheOutburst** [comment]
#2248
