### ISSUE TITLE
Portpunkt in den Garten Picture Perfect Drive 119

### ISSUE THREAD

**Issue by CaleighRhodes** [mexyn/statev_v2_issues#2326]
**Character Name**
Caleigh Rhodes

**Antrag:**
obiges Haus (Haushash house_VinewoodHills_112, aktueller Besitzer Bobby_William) wird derzeit durch Max Clinton und mich abbezahlt (Kaufvertrag IC abgeschlossen und vorlegbar). Um das Haus im RP auch gut bespielen zu können, bitten wir um einen Portpunkt für den Garten. Diesen erreicht man derzeit leider nur, wenn man über die Mauer (Bild 1) klettert.

Der Portpunkt könnte hier eingerichtet werden, wo ich gerade auf dem Bild stehe:

![20220329233015_1](https://user-images.githubusercontent.com/74977218/160712868-e354bdcf-d60f-4300-8771-dbacc7d3dd4a.jpg)

Der Gegenpunkt im Garten könnte dann hier sein (am logischsten, da eine Fensterfront mit bodentiefen Fenstern):

![20220329233041_1](https://user-images.githubusercontent.com/74977218/160712922-0fe7ddef-2007-4c24-ac0e-a902e9b2b34f.jpg)

Mit dem aktuellen Hausbesitzer ist dieser Bugtracker abgesprochen, er bat uns, diesen selbst zu verfassen. Wir würden uns freuen, wenn wir einen Portpunkt bekommen könnten und bedanken uns im Voraus.

**Comment by DrGrizzlY17** [comment]
Abgelehnt:

1. Keine Tür für den Portpunkt
2. Da es durch einmaliges Klettern sehr leicht zu erreichen ist, wird hierfür keine Ressource aufgebraucht

**Comment by CaleighRhodes** [comment]
Hallo Dan,

Punkt 1 verstehe ich, dafür hätte ich ne Lösung, in der Garage gibt es eine Tür:

![20220329232957_1](https://user-images.githubusercontent.com/74977218/161153593-9db69fc7-12eb-4922-be61-700fa0946ee9.jpg)

Punkt 2 kann ich halt aus RP-Sicht nicht nachvollziehen. Wenn es einen anderen Weg in den Garten gäbe, hätte ich den Punkt nicht beantragt. Klettern finde ich nicht RP-konform, grade weil die Mauer so hoch ist, daher würde ich mich freuen, wenn du hinsichtlich der Tür in der Garage eventuell nochmal wohlwollend prüfst, ob es doch möglich wäre.

Danke!
