### ISSUE TITLE
Objekte entfernen, Garagenpunkt umsetzen, Frage zu altem Issue

### ISSUE THREAD

**Issue by WalDragoner3425** [mexyn/statev_v2_issues#2327]
Schönen guten Tag,

ich habe gleich mehrere Anliegen/Fragen, die sich hauptsächlich um die Straße "Armarilla Vista" drehen.
Bild Straße: https://pic.statev.de/image/grafik.DsAu6

Und zwar wollten wir fragen, ob die Reifen vor der Garage vom Haus mit dem Haushash "house_EastLS_13" entfernt werden können, da diese einen Meter vom Garagenpunkt entfernt sind und immer beim ein-/ ausparken sehr stören.
Bild Reifen: https://pic.statev.de/image/s-1.Dsicy

Als nächstes wollten wir fragen, ob die Kartons im abgezäunten Bereich gegenüber der Baustelle entfernt werden können, da wir dort des öfteren kleinere private Boxkämpfe veranstalten und diese uns stark dabei stören.
Bild Karton: https://pic.statev.de/image/s-2.DsFfA

Ebenfalls wollten wir noch fragen, ob die Pylonen, die Mülltonnen, das Baustellenschild sowie ein paar Stühle, welche über die ganze Straße verteilt sind, entfernt werden können, da diese immer wild durch die ganze Straße fliegen und die Autos daran hängenbleiben und manchmal rumbuggen, wenn man zum Beispiel weg war und wieder zurück kommt.
Bild 1: https://pic.statev.de/image/s-3.DsmRu
Bild 2: https://pic.statev.de/image/s-4.DsrO2
Bild 3 (Hinter dem Haus (Haushash "house_EastLS_15"): https://pic.statev.de/image/s-6.DsVzC
Bild 4: https://pic.statev.de/image/s-5.Ds2wP

Als vorletztes wollten wir noch fragen, ob der Garagenpunkt vom Haus mit dem Haushash "house_EastLS_14", ein kleines Stück nach hinten gesetzt oder eine feste Ausparkblickrichtung festgelegt werden kann, da beim Ausparken nach einem Serverneustart, die Autos sich manchmal zwischen den Pfeilern verkeilen und ständig kaputt gehen.
Bild 1: https://pic.statev.de/image/s-7.Dsbbi
Bild 2: https://pic.statev.de/image/screenshot-2022-02-07-152034.Dspjs

Zu guter letzt wollten wir uns Mal erkundigen, ob es so richtig ist, dass sich nach dem letzten kleinen Update, sich nichts bei dem Hotel mit dem Hotelhash "JunRockFordHillsRew_Flat_11" geändert hat, oder ob wir etwas im Issue falsch verstanden hatten, da bis jetzt noch alles wie vorher ist, obwohl es glaub ich schon ein kleines Update gab.
Altes Issue: https://github.com/mexyn/statev_v2_issues/issues/2301#issue-1150793978

War jetzt doch alles etwas mehr als gedacht, ich hoffe das geht so klar.

Gruß
William Void

**Comment by Enemyaa** [comment]
@WalDragoner3425 Hi, es gab noch gar kein Update. Bei dem Hotel wurde der Marker wie gewünscht mittig gelegt. Der Teleport ohne Tür wird nicht erfolgen.

**Comment by WalDragoner3425** [comment]
Ok alles klar

**Comment by WalDragoner3425** [comment]
Und wie siehts mit dem Rest aus?

**Comment by Enemyaa** [comment]
Manche Sachen habe ich entfernt, manche nicht, da sie zum Gesamtbild gehören.

Next Update!
