### ISSUE TITLE
Ragdoll durch Trinken + Bewusslosigkeit = keine Bewusslosigkeit

### ISSUE THREAD

**Issue by Headmonsta** [mexyn/statev_v2_issues#2329]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Uri Holiday

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.04.2022 23:30

**Beobachtetes Verhalten**
Wenn man in einem Fahrzeug sitzt und bis zum Ragdoll trinkt bleibt man sitzen und kann sich nicht mehr abschnallen (was ja auch verständlich ist), nach einem Gamecrash spawnt man auf dem Fahrzeug was auch normal ist wird jedoch in den Ragdoll geschmissen und stuckt im Fahrzeug. Bekommt da kontinuierlich Damage und wenn man dann Bewusstlos wird. ist noch alles normal. Jedoch wird man wenn man die Ragdollzeit vom Trinken vollendet hat man aus der Bewusstlosigkeit geschmissen. Heißt man könnte umher laufen. Ob man interaktionen machen kann weiß ich nicht jedoch kann man nicht reden.

**Erwartetes Verhalten**
Erwartet war natürlich das man durchgehend bewusstlos ist.

**Schritte um den Fehler nachvollziehen zu können**
In Fahrzeug einsteigen
Saufen
Saufen
Saufen
Ragdoll bekommen
Reloggen (Komplett Game neustarten)
Bewusstlos werden durch Damage im Fahrzeug
(jemand anderes Macht erste Hilfe um Zeit zu verlängern)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Video zum Switch von Drunkness Ragdoll zu keinem Ragdoll https://youtu.be/mqxd2b3oV_k
Außenansicht https://clips.twitch.tv/SpotlessGracefulMilkBibleThump-_H6mJ3bKMOpoD9gO

**Comment by DonVitoDiangelo** [comment]
Dont drink and Drive. Aber ja, das ist ein Case den werden wir nicht abdecken.
Seid kreativ, spielt das als z.B. Alkoholvergiftung aus, wenn Ihr euch in solch eine Situation bringt.  :)
