### ISSUE TITLE
Falsche Nummer in der Anrufhistory 

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#233]
**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020 / 02.00

**Beobachtetes Verhalten**
Nach einem Anruf wird die falsche Nummer in der Anrufhistory angezeigt. Es steht die eigene Nummer statt der vom angerufenen.
**Erwartetes Verhalten**
Die korrekt Nummer sollte angezeigt werden

**Schritte um den Fehler nachvollziehen zu können**
Telefonieren und danach in die Anrufhistory schauen. Es steht nur die eigene Nummer drinne.

**Comment by mexyn** [comment]
@Kalumel Sicher, dass es hier um **ausgehende** Anrufe geht, so wie oben beschrieben? Bei eingehenden Anrufen kann ich den Fehler nachstellen (bereits gefixt). Bei ausgehenden Anrufen steht aber korrekt die Nummer des Angerufenen in der Liste?!

**Comment by Kalumel** [comment]
Ehm, ja eingehende. Ausgehende sind nicht das Problem.
