### ISSUE TITLE
Falsche Animation beim Anlehnen

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#2330]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.04.2022  23:00

**Beobachtetes Verhalten**
Die anlehenen Animation wurde bei jemand anderes als Bier trinken Animation angezeigt

**Optional: Video / Bilder des Fehlers**

https://youtu.be/ShHTeb0zAI0

**Comment by DonVitoDiangelo** [comment]
Dann muss derjenige der es falsch sieht, sein NVE runter schmeißen. Hier wird vermutlich eine Mod genutzt, welche die Anims durcheinander bringt.
