### ISSUE TITLE
Platzierte Gegensätze löschen

### ISSUE THREAD

**Issue by OfcStern** [mexyn/statev_v2_issues#2332]
Nabend,

ich wollte Gegenstände platzieren, jedoch kam direkt die Nachricht, dass ich zu viele Gegenstände platziert habe.
Mir wäre neu, dass ich 10 Gegenstände voll habe. Ich habe lediglich gestern 3 Kerzen platziert. Absperrungen habe ich in letzter Zeit auch keine getätigt.

Es hieß im TS, dass ihr meine platzierten Gegenstände löschen könnt, um dies bitte ich hiermit.

Grüße
Marcel

**Comment by DonVitoDiangelo** [comment]
Bitte melde dich dafür im Support. Wenn, dann wird man dir dort weiterhelfen können.
