### ISSUE TITLE
Radius Blitzer Südseite

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#2334]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Sven Rosenbach 
**Auftrittszeitpunkt (Datum / Uhrzeit)**

03.04 23:00
**Beobachtetes Verhalten**

Blitzer löst auf der Nebenstraße aus
**Erwartetes Verhalten**

Er tut dies nicht. 
**Schritte um den Fehler nachvollziehen zu können**

Zu schnell auf der Straße fahren, die im Video zu sehen ist.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://streamable.com/rkivj8

**Comment by DonVitoDiangelo** [comment]
Es gibt eben auch Blitzer in den Ampeln.  :)

**Comment by SHaagmann** [comment]
Dachte rote Ampeln sind nur noch zu behandeln wie Stoppschilder 😜 
Aber kann verstehen, dass ihr höhere Prioritäten auf andere Dinge legt 👍
