### ISSUE TITLE
Interior Crash

### ISSUE THREAD

**Issue by Razor-ML** [mexyn/statev_v2_issues#2336]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Charakter Name**
Aiden_Wayne

**Auftrittszeitpunkt (Datum / Uhrzeit)**
ca 06.04.22  22:24

**Beobachtetes Verhalten**
Direkter Gamecrash im Black Screen nach erneutem einloggen interaktionspunkte sichtbar jedoch "E" nicht zu verwenden #keine Interaktion möglich

**Erwartetes Verhalten**
Spawn vor der Haustüre

**Schritte um den Fehler nachvollziehen zu können**
Oft aus dem haus und ins haus gehen tritt manchmal nicht immer auf beim Hineingehen und beim herausgehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1440p

**Optional: Video / Bilder des Fehlers**
Kein Fehler vorhanden direkter crash

**Comment by DonVitoDiangelo** [comment]
Was für ein Interior, bei welcher Firma? Am besten Firmenhash dazu schreiben, vielen Dank,

**Comment by Razor-ML** [comment]
Firmen kann ich nichts dazu sagen da ich einen Gangchar spiele aber das Iterior scheint hierbei egal zu sein. Bisher aufgetreten ist es beim Restaurant (bisher nur beim eintreten nicht rausgehen) und bei folgenden Häusern beim ein und herausgehen 

house_EastLS_3
house_EastLS_4

**Comment by TheOutburst** [comment]
ist das nach dem Update Heute das Problem nochmal aufgekommen?
@Razor-ML

**Comment by Razor-ML** [comment]
"Ja"

mittlerweile bekomme ich auch ohne interior, crashes heute 3 mal hintereinander beim autofahren

**Comment by DonVitoDiangelo** [comment]
Also das kann so nicht reproduziert werden.
Nutzt du Mods wie Quant oder NVE oder auch Reshade oder ENB? Bitte versuche es alternativ auch einmal mit der Reduzierung der Grafikeinstellungen. Das scheint mir derzeit eher ein Problem bei dir zu sein. Vllt. durch zu hohe Auslastung.
ich werde den Thread schließen. Bei Fragen kannst du dich gerne auch bei mir melden.
