### ISSUE TITLE
Fehler bei den Interieurs?

### ISSUE THREAD

**Issue by nox142** [mexyn/statev_v2_issues#2337]
**Character Name**
Jona Lindner

Haushash: SandyShores50

Ist das so korrekt, dass man wirklich nur das eine Interieur hat und es garnicht wechseln kann? Es steht anscheinend nur das Girlys Apartment zur Verfügung. Eigtl sollten doch noch weitere zur Verfügung stehen, es ist ein Größe 2, Klasse 1 Haus.

**Comment by Enemyaa** [comment]
Das ist ein Fehler. das ist ein 1 / 1 Haus

**Comment by Enemyaa** [comment]
Das wird mit dem nächsten Update korrigiert!

**Comment by nox142** [comment]
Ist es möglich, diese Innenausstattung zu behalten, nachdem es die ja anscheinend schon ein paar Jahre drinnen ist? Wollte mich ja eigtl nur erkundigen, ob das so korrekt ist.
