### ISSUE TITLE
Balkon Zugang

### ISSUE THREAD

**Issue by SatyriaDine** [mexyn/statev_v2_issues#2338]
**Character Name**
Sofia_Black

Ist es möglich einen Port von der linken, unbenutzten Tür (die Eingangstür zum Haus ist genau auf der anderen Seite) zum Balkon auf gleicher Höhe zu bekommen? 
Soweit ich es erkennen konnte ist auf dem Balkon eine Balkon Tür.

Haushash: JunWestCoastRew_House_8

Möglicher Portpunkt  zum Balkon
![20220408192217_1](https://user-images.githubusercontent.com/84275938/162515642-1989a5e0-df40-4a45-9ded-7852fde818a1.jpg)

Balkon, den ich meine. 
![Inked20220408192157_1_LI](https://user-images.githubusercontent.com/84275938/162515715-e7e12dbd-3ea9-492f-924a-b8cd4764b7d8.jpg)

**Comment by Enemyaa** [comment]
Next Update!
