### ISSUE TITLE
Fehler bei Garage + Entfernung von Trash im Garten

### ISSUE THREAD

**Issue by foggel8** [mexyn/statev_v2_issues#2339]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name:**
Eric_Mcallister

**Auftrittszeitpunkt (Datum / Uhrzeit):**
Seit dem 10.04.2022 (Kauf des Hauses in der SAHK Auktion)

**Anliegen:**
Hallöchen. Ich hätte mehrere kleine Anliegen. 

Vorab: Es handelt sich um das Haus in der "Brouge Ave. 13" mit dem Haushash: house_DavisMidLS_16

Als ich das Grundstück vor der Auktion begutachtet habe, ist mir die Garage auf meinem Grundstück (siehe hier Frontansicht: https://i.imgur.com/fuXANQm.png) aufgefallen. Ich dachte mir, dass das sehr praktisch ist und wollte deshalb auch unbedingt besagtes Haus. Doch leider habe ich scheinbar keinen Zugriff auf die Garage. 
Ich hatte bereits im RP via Handelskammer probiert, das ganze zu lösen, wurde jedoch hierher verwiesen. Die Handelskammer hat mir jedoch versichert, dass die Garage auf meinem Grundstück steht. Hier noch einmal die kleine Mauer als "Grundstücksbegrenzung": https://i.imgur.com/2FvlM41.png
Und hier eine Sicht aus dem Garten (Rückansicht der besagten Garage): https://i.imgur.com/bGHPtvp.png

Falls die o.g. Garage (aus welchem Grund auch immer) mit meinem Nachbarhaus gelinked ist, gibt es hinten im Garten noch eine weitere, kleinere Garage. Vielleicht wäre es möglich, diese benutzbar zu machen? Bild: https://i.imgur.com/tewx04c.png

Außerdem wollte ich fragen, ob ein paar "Trash-Gegenstände" entfernt werden könnten. Anbei die Fotos und dem eingekreisten Kram, den ich entfernt haben möchte: https://imgur.com/a/ZQZIaIA

Ich hoffe da lässt sich irgendetwas machen.

From Davis with Love
Big Mac

**Comment by Statev-Bonsai** [comment]
https://github.com/mexyn/statev_v2_issues/issues/839 gabs schonmal im bugtracker :)

**Comment by DonVitoDiangelo** [comment]
Siehe Verweis über mir, sry.

**Comment by foggel8** [comment]
@DonVitoDiangelo 
Das mit der Garage habe ich dann wohl übersehen, Schade dass das nicht klappt. 
Wie würde es theoretisch mit den kleinen Entfernungen (2ter Part meiner Issue hier) ausschauen?

**Comment by milkdrops** [comment]
@foggel8 Big Mac, alles weg 👍

**Comment by foggel8** [comment]
@milkdrops Hey, danke schonmal für die Entfernung der Plastikstühle und Tisch im Garten. Wären die anderen Sachen auch möglich? (das rostige Auto und die veranzte Matratze + weißer Plastikstuhl vorne)

**Comment by milkdrops** [comment]
Das ist verbunden mit der Kollision durch andere Objekte (wie die Couch) oder auch wenn Y-Animationen genutzt werden. Leider nicht änderbar aktuell.

Die anderen Objekte (Auto+Matratze) werden noch entfernt, allerdings mehr Objekte nicht, damit der Davis-Flair bleibt

**Comment by foggel8** [comment]
Ah perfekt, dann stelle ich die ein bisschen um, danke! Und mehr will ich da selbst auch nicht weg haben, eben wegen des Davis Flairs :)
