### ISSUE TITLE
Garage fürs Haus möglich?

### ISSUE THREAD

**Issue by glb11** [mexyn/statev_v2_issues#2340]
**Character Name**
Jens_Summer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.4.22

**Erwartetes Verhalten**
Ist es möglich für das Haus:

Adresse: Zancudo Ave. 31

Hash: SandyShores31

![20220410225556_1](https://user-images.githubusercontent.com/70204338/163027575-09eb9b2c-d35b-46f5-b5a8-feb3ffd232fe.jpg)

Dieses wäre im meinen Augen berechtigt weil leicht links hinter dem Haus sich 2 Garagen befinden. Und Mann es so top erklären kann 

**Schritte um den Fehler nachvollziehen zu können**

Hingehen und schauen

Vielen Dank im Vorraus

**Comment by TheOutburst** [comment]
next Update hast du an der rechteren Garage nen Marker (y)
