### ISSUE TITLE
Comet S2 Cabrio

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#2341]
Ich bin der Meinung das der Comet S2 Cabrio deutlich zu schnell (über 300km/h) für einen Sportwagen in der Preisklasse ist.
Er ist in der Endgeschwindigkeit schneller als ein Großteil der Supersportwagen und Hypercars, könnt ihr da mal drüber schauen?
Denn die Balance dieses Fahrzeuges passt absolut nicht..

**Comment by DonVitoDiangelo** [comment]
Wie bekommst du den wo auf über 300? Was für Tuning und Reifen hast du bzw. sind drauf?

**Comment by Statev-Bonsai** [comment]
Die Frage ist nicht wo, sondern wo nicht!
![111](https://user-images.githubusercontent.com/70241137/163336097-aa0f796e-dfea-4935-9406-6cefb545c5e2.jpg)

![222](https://user-images.githubusercontent.com/70241137/163336110-5e373cbf-f848-4dad-8cdf-6f1ba9c2cd99.jpg)

![333](https://user-images.githubusercontent.com/70241137/163336118-053c7ceb-222f-449d-a1f4-01f160aa66cb.jpg)

![444](https://user-images.githubusercontent.com/70241137/163336130-0f038d4e-f685-4076-99b2-ab9041918d3e.jpg)

![555](https://user-images.githubusercontent.com/70241137/163336145-1f5c4589-747e-4ab1-979a-1ff2d5c9fa5c.jpg)

Bin eben nur einmal Autobahn auf und ab gefahren, das Fahrzeug ist viel zu überpowered..
Der S2 Cabrio steckt selbst meine 3 Hypercars in die Hose..
Tuning nur UHP Reifen, aber auch mit Serienreifen ist der too much!

**Comment by epichalt** [comment]
Evtl. sollte man dazu sagen, dass es sich "nur" um den Driftmodus handelt. Gibt einige Fahrzeuge welche sich im Driftmodus aufschaukeln und dabei werden permanent Bodenwellen simuliert. Kann man meiner Meinung nach auch gut raushören beim Fahren.
Dementsprechend sind einige Fahrzeuge (auch 4 Sitzer) im Drift Modus deutlich schneller als fast alle Supersportler. 

Im normalen Racing Modus fahren allerdings alle Autos so wie sie sollten. Also sollte lediglich der Drift Modus gefixed werden, falls das überhaupt so möglich ist.

**Comment by DonVitoDiangelo** [comment]
Ah ok, ja der Drift Mode. Ja das ist sozusagen leider einfach so. Grade im High Speed, wenn du dann in dem Mode so schnell fährst ist das Handling so lala. Aber wir schauen, das wir da etwas ändern um z.B. auch einen Wechsel z.B. nur im stehen zu ermöglichen, damit man sich nicht immer instant der Situation anpassen kann.
