### ISSUE TITLE
Restaurantisch nur noch für 2 Personen

### ISSUE THREAD

**Issue by AdmiralState** [mexyn/statev_v2_issues#2343]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Nick Blinders

**Auftrittszeitpunkt (Datum / Uhrzeit)**
15.04.22 22:50 Uhr

**Beobachtetes Verhalten**
Tisch im Restaurant ist nur noch für 2 Personen obwohl 4 Marker. Bei der 3. Person wird immer gesagt das der Platz belegt ist

**Erwartetes Verhalten**
Zahl auf 4 erhöhen?

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
zusätzlich wird auch kein essens tablet mehr beim essen aufm tisch platziert.

**Comment by AdmiralState** [comment]
Genau, wollte dafür auch grade ein Issue aufmachen

**Comment by AdmiralState** [comment]
![271590_20220416020236_1](https://user-images.githubusercontent.com/103783836/163653765-470f0e45-7f8f-40ea-a1b4-ea991e1858f6.png)

**Comment by DrGrizzlY17** [comment]
Also wenn man etwas weiter weg ist von dem sitz, dann kann man auch zu viert an den tisch

**Comment by TheOutburst** [comment]
Wir haben mit dem letzten Hotfix ganz sneaky die Range der Marker verkleinert, in unseren Tests kann man wieder zu viert gleichzeitig essen. Sollte euch das noch irgendwo auffallen gerne nochmal hier rein, bitte mit Bild des Tisches
