### ISSUE TITLE
Fehler bei Klamotten 

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#2345]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**Ryan Valdes

**Auftrittszeitpunkt (Datum / Uhrzeit)**

14,04,2020 23:00
**Beobachtetes Verhalten**

Siehe Bilder // Weiß nicht ob das textile_Lether so gewollt ist vom namen her ?
**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![textile_leather](https://user-images.githubusercontent.com/70231715/163632062-f087793a-76b0-4316-b26d-10a58d35bcc9.png)
![unknown](https://user-images.githubusercontent.com/70231715/163632066-7a30a9a3-b275-4c15-ad6a-6788f8817e4a.png)

**Comment by Enemyaa** [comment]
Danke, das erste wurde gefixt. das 2. liegt daran, dass das Statenet noch nicht geupdated wurde.
