### ISSUE TITLE
Spieler zahlen keine Hotelmiete

### ISSUE THREAD

**Issue by WalDragoner3425** [mexyn/statev_v2_issues#2346]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name** 
William_Void

**Auftrittszeitpunkt (Datum / Uhrzeit)**
15.04.2022 ab 22:20 Uhr

**Beobachtetes Verhalten**
Spieler zahlen keine Hotelmiete (Hotel: "JunRockFordHillsRew_Flat_11"), obwohl sie im Hotel länger als eine Stunde eingemietet sind und andere Rechnungen wie Grundstütze oder Schlüssel Gebühr abgezogen werden.

**Erwartetes Verhalten**
Spieler zahlen Miete

**Optional: Video / Bilder des Fehlers**
![miete](https://user-images.githubusercontent.com/56478386/163636172-79d4c1ef-101e-4ebc-9fd1-d78aa8713882.png)

**Comment by foggel8** [comment]
Kann ich so bestätigen, oben stehender Auszug ist von meinem Konto. Auch nach 2-3 Stunden wurde mir nicht einmal die Miete abgezogen

**Comment by DrGrizzlY17** [comment]
![Uploading unknown.png…]()

**Comment by WalDragoner3425** [comment]
Gab jetzt nh neue Meldung:
![grafik](https://user-images.githubusercontent.com/56478386/163677919-78bc7ad9-64fd-4d28-a608-daf50bc58fe9.png)

**Comment by its4l3x** [comment]
Ist fixed und kommt zeitnah
