### ISSUE TITLE
Garagenpunkt unsichtbar

### ISSUE THREAD

**Issue by WalDragoner3425** [mexyn/statev_v2_issues#2347]
**Character Name**
William_Void

**Auftrittszeitpunkt (Datum / Uhrzeit)**
15.04.2022 ab 22:30 Uhr

**Beobachtetes Verhalten**
Der Garagenpunkt bei dem Haus mit dem Haushash "house_EastLS_13" ist nicht sichtbar, obwohl eine Garage vorhanden ist und auch funktioniert (andere Garagenpunkte sind sichtbar). Aufgrund des Issues https://github.com/mexyn/statev_v2_issues/issues/2327#issue-1189984243 wurden vor der Garage Reifen entfernt und dabei wohl auch der Garagenpunkt 

**Erwartetes Verhalten**
Vor der Garage sollte ein Garagenpunkt sichtbar sein

Bild Vorher (der rote Kreis ist vom alten Issue): https://pic.statev.de/image/s-1.Dsicy
Bild Nachher: https://pic.statev.de/image/grafik.L66AP

**Comment by Enemyaa** [comment]
Next Update
