### ISSUE TITLE
Vinewood Cars kaputt :D Game schließt sich beim Verlassen des Gebäudes

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#2348]
Santito Quintero

**Auftrittszeitpunkt (Datum / Uhrzeit)**
dauerhaft

**Beobachtetes Verhalten**

Falls man das Autohaus verlässt, egal ob über Tür oder "Garage" freezed das Spiel kurz und stürzt ab.
Gebäude: Vinewood Cars
>🚲🚗 Vinewood Cars 🚚🛵 - Spanish Ave. 45
Firmenhash | carShop11

Bei bereits 15+ Leuten getestet, keiner ist "normal" rausgekommen

**Erwartetes Verhalten**
Dass sich das Game nicht schließt

**Schritte um den Fehler nachvollziehen zu können**
Rein und wieder raus aus dem Autohaus

**Comment by epichalt** [comment]
![image](https://user-images.githubusercontent.com/16436981/163652593-dcab8525-d70c-4381-b775-e1b29c24b1ef.png)

eine der fehlermeldungen

**Comment by DonVitoDiangelo** [comment]
Bitte nach dem nächsten Restart im Auge behalten. 16.4.22 - 15:00 uhr :)

**Comment by epichalt** [comment]
läuft wieder :)
