### ISSUE TITLE
Baller ST weiterhin nicht abholbar

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#2349]
Santito Quintero

**Auftrittszeitpunkt (Datum / Uhrzeit)**
dauerhaft

**Beobachtetes Verhalten**
Baller ST Motor nicht abholbar

**Erwartetes Verhalten**
Motor soll abholbar sein

![image](https://user-images.githubusercontent.com/16436981/163650628-2a6ec934-a229-40b8-b131-094c992f410d.png)

rel.
https://github.com/mexyn/statev_v2_issues/issues/2289
https://github.com/mexyn/statev_v2_issues/issues/2220

3 Monate :(

**Comment by its4l3x** [comment]
Dir muss das Item aus dem Import manuell gelöscht werden. Meld dich morgen im Support
Weiterleitung an Development und markiere mich bzw. gebe an das ich dich in den Support gebeten habe.
Wir fixen das dann eben. Dauert nicht lange.

**Comment by its4l3x** [comment]
Morgen ab 13 Uhr bitte ^^

**Comment by its4l3x** [comment]
Jetzt schon erledigt, weil schnell.
