### ISSUE TITLE
Werkstatt/Xenon Lichter

### ISSUE THREAD

**Issue by Oger8602** [mexyn/statev_v2_issues#235]
**Zeitpunkt (Datum / Uhrzeit)**
19.11.2020 ca. 2:00 Uhr

**Beobachtetes Verhalten**
Geht man in der Werkstatt an den Computer --> Tuning --> Xenon Lichter und ändert diese bleiben diese nach dem schließen des Computers erhalten.

**Erwartetes Verhalten**
Sollte wie üblich dann auf das derzeit verbaute Licht zurückgesetzt werden nach dem schließen des Computers!

**Comment by Chrinis007** [comment]
An RTW vorhin auch festgestellt

**Comment by JulianMa** [comment]
behoben
