### ISSUE TITLE
Neue Tracks auch als Drift Event gelistet

### ISSUE THREAD

**Issue by Fabse96** [mexyn/statev_v2_issues#2351]
**Fabio_Gonzales**

**Samstag 16.04.2022  10:40**

**Beobachtetes Verhalten**
Neue Racestrecken werden im Race UI als Drift event gelistet und auch mit der Drift Mechanik gestartet.

**Erwartetes Verhalten**
Race strecken sollten als normales zeitfahren gewertet werden und nicht als drift event mit punkten

**Schritte um den Fehler nachvollziehen zu können**
Neue races ( Ohne Moos nix los, Vinewood BangerTrack und Musclecar Madness ) starten und siehe wird als drift event ausgeführt und nicht als Zeitfahren

![Bild_2022-04-16_104620650](https://user-images.githubusercontent.com/74773267/163668614-ee28fdda-d38a-49e7-95bd-6dc8315ccd7b.png)

**Comment by TheOutburst** [comment]
Die neuen Strecken haben wie man sieht ein anderes Icon als die bestehenden, weil es Driftstrecken sind. Hier ist also nix falsch

Das die Strecken als Rennen veranstaltbar sind und dann normale Rennen sind ist gewollt.

**Comment by Fabse96** [comment]
Naja aber das Sind Strecken die zum Racen angedacht sind und dies auch für Zeitfahrten. Da nur richtige Rennen starten zu können und kein Zeitfahren ist useless. Strecken kommen auch vom MNC und wir sind kein Drifting club. Und man muss dazu sagen das die Rennveranstalltungen nicht genutzt werden, da diese viel zu viel hin und her gefahre in anspruch nehmen. 

Die Leute sollen ja die Möglichkeit haben über das Zeitfahren die Strecken auch kennen zu lernen und sich zu verbessern und nicht mit einem copy paste system aus gta online was sich "Driften" nennen soll da unkontrolliert durch schleudern.

**Comment by Hutstaender** [comment]
"copy paste system aus gta online" WAS? Das tut weh, danke für dein Feedback

**Comment by eiksch** [comment]
Also Kurzform: Du wünscht dir gerne, dass diese Strecken auch im Zeitfahren zur Verfügung stehen? Wieso bistn du so eklig?

**Comment by TheOutburst** [comment]
Es wurd eine Lösung im Ts Gespräch mit ein paar Racern gefunden, ich denke das sollte alle zufriedenstellen
