### ISSUE TITLE
[F][Ears] Moon Cat nicht sichtbar

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#2352]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Hanna Fields & Sven Rosenbach
**Auftrittszeitpunkt (Datum / Uhrzeit)**

16.04 11:50
**Beobachtetes Verhalten**

Ohrringe werden nicht angezeigt, sowohl bei ihr als auch bei mir nicht
**Erwartetes Verhalten**

Ohrringe werden angezeigt
**Schritte um den Fehler nachvollziehen zu können**

Neue Ohrringe anprobieren
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://streamable.com/jyqtzj

**Comment by Enemyaa** [comment]
Next Update!

**Comment by SHaagmann** [comment]
Funktioniert nun alles 👍
Danke
