### ISSUE TITLE
Gamecrash nahe Rancho-Garage

### ISSUE THREAD

**Issue by McWulf1991** [mexyn/statev_v2_issues#2353]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Quentin_Mcallister

**Auftrittszeitpunkt (Datum / Uhrzeit)**

16.04.2022 - 12:26 Uhr & 12:43 Uhr

**Beobachtetes Verhalten**

Beim Anfahren oder Zulaufen der Rancho Garage in der Southside crashed das Spiel.

**Erwartetes Verhalten**

Kein Gamecrash

**Schritte um den Fehler nachvollziehen zu können**

Anfahren oder zulaufen der nächstgelegenen Kreuzung nahe der Rancho Garage.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

1920x1080

**Optional: Video / Bilder des Fehlers**

https://youtu.be/fGoTdoWft6c

**Comment by milkdrops** [comment]
Nicht reproduzierbar.

Aber ich habe die Vermutung, es könnte mit den neuen Objektentfernungen zu tun haben. Diese wurden jetzt angepasst, nach dem nächsten Update bitte nochmal testen und falls sich das wiederholt, wenn möglich genauere Schritte zum Reproduzieren angeben, damit das überprüft wird, worans liegt.
