### ISSUE TITLE
Autopilot nach Gamecrash auf Alta Street

### ISSUE THREAD

**Issue by McWulf1991** [mexyn/statev_v2_issues#2354]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Quentin_Mcallister

**Auftrittszeitpunkt (Datum / Uhrzeit)**

16.04.2022 - 13:06

**Beobachtetes Verhalten**

Nach Gamecrash in Alta Street und erneutem Login, fuhr mein Fahrzeug ohne mein zutun weiter, öffnen lies es sich auch nicht, ebenso buggte es auf der Strasse herum,  andere Spieler fuhren hinnein und es tauchte kurze Zeit später wieder woanders wieder auf.

**Erwartetes Verhalten**

Kein Gamecrash und kein Verlust der Fahrzeugkontrolle.

**Schritte um den Fehler nachvollziehen zu können**

Fahren auf Alta Street Richtung Vinewood.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

1920x1080

**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=bzzWnQPJ-80

**Comment by TeubyDE** [comment]
Ist ein altv Verhalten das bei einem Gamecrash "normal" ist.
