### ISSUE TITLE
Fahrzeug hat keinen Fehlercode aber dennoch keine Leistung mehr 

### ISSUE THREAD

**Issue by WanderHowden** [mexyn/statev_v2_issues#2355]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Lukas_Gassner**

 Lukas_Gassner
**Auftrittszeitpunkt (Datum / Uhrzeit)**

15.04.2022 ca 23:30 uhr
**Beobachtetes Verhalten**

Fahrzeug lief nach Update und der Anpassung völlig Normal. Während einer Verfolgung mit dem PD  (nach dem Update), plötzlich spürbar keine Leistung mehr , mehrfach Auslesen /Reparieren/ Einparken, kein Fehler zu finden.. Fahrzeug Sultan Rs kommt gerade noch so auf 180-190 kmh auf dem Highway.   

**Erwartetes Verhalten**

Fahrzeug auslesen - benötigten Service ausführen _ Leistung wieder da ... 
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Dean-Gallagher** [comment]
Mit dem gleichen Problem hatten wir in der Werkstatt auch schon den ein oder anderen

Fahrze waren

Mixer
Schafter v12
Burrito

**Comment by SHaagmann** [comment]
Gleiche Problem gerade auch gehabt:
Zorrusso (Kennzeichen: NORTH SR)

**Comment by SHaagmann** [comment]
K heute n paar mal beobachtet bei meinem Zorrusso:
Manchmal fuhr der wieder ganz normal aber n paar min wieder so langsam wie mit dem Fehler
Leider keine Ahnung, wie ich das gemacht habe würde aber die Tage da nen Auge drauf werfen, ob ich da irgendwas anders gemacht habe als vorher um es zu reproduzieren.
Wenn mir was auffällt schreibe ich es hier rein 👍

**Comment by cadpri** [comment]
gleiche Problem bei Phantom Custom, Größter Motor

**Comment by SHaagmann** [comment]
Nach n bisschen rumprobieren habe ich es noch nicht genau nachstellen können aber nen Video wie Random der Leistungsverlust kommt (19.04 ca 0 Uhr): https://streamable.com/j3b9eg
Vorher hatte ich den verlust auch bis ich im Juwelier war und mir schmuck angeschaut hatte, jedoch beim nachstell versuch anschließend nach dem erneuten verlust kein unterschied bemerkbar.

Stand im nachhinein von 0:19 - ca 0:40 am MD bin eingestiegen und wagen fuhr wieder normal. Nur Motor ausgemacht und abgeschlossen beim abstellen.

**Comment by adrosso** [comment]
Hallöchen ihr lieben, ich habe da mal eine Frage. Kann es sein das der Phantom Custom mit einem großen Motor und 7000 KM etwas an der geschwindigkeit gebastelt wurde? Ich war bei 4 unterschiedlichen Werkstätten und habe den immer auslesen lassen (kein befund), habe den dennoch reparieren lassen und es ist immer das selbe, die beschleunigung (anzug) ist echt mies geworden. Das "problem" habe ich jetzt seit 3 tage. Auf dem kleinen Öl feld (im steinbruch) fahre ich den berg (erste Pumpe) mit 5-10Km/h hoch. Wenn ich los fahre, braucht der po lange um mal aus dem Quark zu kommen. 

LG

**Comment by Atomic3** [comment]
Copy Problem mit Phantom Custom es fehlt an Leistung bin aber unter 7000KM denke das ist unabhängig von der Laufleistung.

**Comment by KurwaDerPole** [comment]
Mein Cyclone hatte ein ticken weniger Beschleunigung - hatte auch einen Fehler - Fehler behoben lief er wieder super. Jetzt ohne fehler, repariert vollgetankt ist er langsamer als ein t20...von heute auf morgen km 7648

**Comment by Eskadiel** [comment]
Ich denke mal das es aktuell einfach ein Bug ist.
Nach dem Einloggen und ausparken von Fahrzeugen, fährt das Auto wie gewohnt.
Allerdings wenn man nun eine Funktion wie Lagerpunkte, Teleports, Handeln oder Co. verwendet, werden die Fahrzeuge spürbar langsamer und beschleunigen sehr kraftlos.
Das fängt beim Burrito an und zieht sich über Sport und Geländewagen, bis zu den Hypercars.
Da es nach dem Einloggen noch nicht auftritt und meistens nach dem vollständigen Relogg "spiel schließen" wieder bis zu einer Aktion funktioniert, nahm ich an das dann irgendwas mit den Charakterdaten (evtl. Charakter Sync) passiert, da bei jemanden der bis dahin keine Aktion durchgeführt hat , das selbe Fahrzeuge wieder schneller fährt.

Wäre vielleicht Sinnvoll einen Sammelthread zu erstellen, um verschiedene Situationen, Beobachtungen zu Bündeln und damit das verursachende Problem zu finden.

**Comment by WanderHowden** [comment]
Dem kann ich leider so nicht Recht geben , trotz relog keine leistung :D

**Comment by sYnaTiion** [comment]
Revolter 170km/h ???

**Comment by StateV-Jan** [comment]
Reaper fährt nur noch 215-220 auf Highway

**Comment by Tyson0211** [comment]
habe genau die gleichen Probleme, dass die Fahrzeuge keine Leistung mehr besitzen. Weder in der Beschleunigung, noch in der Endgeschwindigkeit. Betroffene Fahrzeuge bei mir aktuel: X80 Proto; Sultan RS, T20, Barracks und Phantom Custom.

**Comment by sYnaTiion** [comment]
Bei mir sind Thrax & Revolter betroffen. Revolter sogar extrem von Beschleunigung und Endgeschwindigkeit.

**Comment by C0NN33R** [comment]
Bei mir ist der Pegassi Toros massiv betroffen. Extremer Leistungsverust.

**Comment by Stiefel911** [comment]
damit sich vielleicht ein besseres Bild gemacht werden kann.. Gang Burrito ist genauso betroffen von dieser Kuriosität

https://youtu.be/DHq-ZVWKjTo

**Comment by TeubyDE** [comment]
Hallo zusammen, Angabe wie "mein Fahrzeug XYZ is nun etwas langsamer" oder "bei meinem T20 auch" bringen uns hier wenig weiter. Mir ist bei dem Video von @Stiefel911  aufgefallen das du hier von der Beifahrer Seite aus eingestiegen bist.

Ist das etwas was alle andere hier im Thread auch regelmäßig machen? Gerade die Ölfahrer unter uns mit ihren LKW's?

**Comment by WanderHowden** [comment]
Ich für meinen Teil kann dir sagen , das bei meinem Sultan RS nichts bringt und es egal ist von welcher Seite ich Einsteige . Die Fahrzeuge verhalten sich als hätten sie einen Fehlercode der ihre Leistung drosselt . Wenn man sie Ausliest ist keiner Vorhanden, bei mir kam der Fehler z.b Plötzlich während einer Verfolgungjagd Plötzlicher Leistungsverlust. Mittlerweile habe ich alle Service Teile auf Verdacht tauschen lassen , was aber auch nichts gebracht hat . Habe bisher alles Getestete was hier aufgeführt wurde und nichts hat besserung gezeigt. Das einzige was ich noch nicht getestet habe wenn ich die Karre in die Luft jage und dann Repariere. Hoffe ich konnte es dir genauer Erklären, solltest du noch hilfe brauchen dann einfach Anschreiben

**Comment by SatyriaDine** [comment]
Lediglich bei meinem Phantom Custom steige ich ab und zu über die Beifahrer seite ein. Je nach dem auf welcher seite die Ölpumpe ist. Da merke ich regelmäßig aber auch nicht immer dass der mit Ölauflieger besser zieht und auf gerader strecke vermutlich knappe 200kmh fahren würde, was natürlich viel zu viel ist. 

Schlagen GT und Reaper steige ich nur über die Fahrerseite ein und bemerke da dass seit dem letzten größerem Update die Leistung stark eingeschränkt ist. Sowohl Beschleunigung als auch Endgeschwindigkeit. 

Alle Fahrzeuge werden regelmäßig ausgelesen und bei Bedarf auch repariert. 

Für mich fühlt sich das mit den fahrzeugen  aktuell genauso an wie die sache mit den Phantom Customs von anfang des Jahres.

**Comment by SHaagmann** [comment]
Meine Formel mit der mein Auto fast immer wie normal fährt:
Wenn es langsam ist:
1. Motor aus und aussteigen
2. Auto abschließen
3. Auto Aufschließen
4. Einsteigen über Beifahrerseite
5. Abschließen und Motor starten

**Comment by Stiefel911** [comment]
> Hallo zusammen, Angabe wie "mein Fahrzeug XYZ is nun etwas langsamer" oder "bei meinem T20 auch" bringen uns hier wenig weiter. Mir ist bei dem Video von @Stiefel911 aufgefallen das du hier von der Beifahrer Seite aus eingestiegen bist.
> 
> Ist das etwas was alle andere hier im Thread auch regelmäßig machen? Gerade die Ölfahrer unter uns mit ihren LKW's?

normalerweise wird nicht über die Beifahrerseite eingestiegen, dies war lediglich zum Vorführen getan worden.
Das ganze ist mir natürlich auch beim Phantom so passiert, per Zufall..da bin ich mit 130 aus Sandy in die Stadt, und auf dem Rückweg am Wasserwerk gehalten weil wegen Notdurft und aus Faulheit über die Beifahrerseite rein, und nähe Prison erschrocken... 200 .. upsala... 

Wie gesagt egtl steige ich nicht rechts ein.. aber es ist zu sehen wenn das geschieht, hat er das normale Fahrverhalten.

es ähnelt ja auch dem was @SHaagmann schreibt...

**Comment by DonVitoDiangelo** [comment]
Wir haben eine Fehler gefunden, der zum nächsten Update korrigiert wird. Bitte dann im Auge behalten und hier dazu Feedback geben.
