### ISSUE TITLE
keine Hotel miete

### ISSUE THREAD

**Issue by halloheyleon** [mexyn/statev_v2_issues#2356]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Grezzer Morgan**

**Auftrittszeitpunkt (16.04.2022 / 9:50 uhr)**

**Beobachtetes Verhalten**

Hotel miete wir nicht abgebucht
**Erwartetes Verhalten**

Hotel miete wird normal abgebucht
**Schritte um den Fehler nachvollziehen zu können**

online sein und eine stunde auf harz V warten
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![alt_V Multiplayer 16 04 2022 11_57_20 (1)](https://user-images.githubusercontent.com/76777215/163678009-abc6d863-e1b2-4004-8b2c-4bb8d4d6c3d1.png)

**Comment by TeubyDE** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2346
