### ISSUE TITLE
Wellchen Chumasch Highway

### ISSUE THREAD

**Issue by DrCassado** [mexyn/statev_v2_issues#2357]
Character Name
Ricardo_Cassado

Auftrittszeitpunkt (Datum / Uhrzeit)
16.04.2022 17:55

Beobachtetes Verhalten
Höhe chumasch sind extrem hohe wellen welche durch Häuser Glitchen

Optional: Video / Bilder des Fehlers
![Screenshot_6](https://user-images.githubusercontent.com/102039945/163682461-02390957-3553-4917-a6cd-6d7c41a4dae5.png)
![Screenshot_7](https://user-images.githubusercontent.com/102039945/163682466-a2e0285e-3511-4e7b-a8ca-e5ed10a42bf6.png)

**Comment by MrHaix** [comment]
Hast du Grafikmods installiert? Sieht nicht nach GTA stanart aus.

**Comment by DrCassado** [comment]
habe nur noch reshade drauf der rest ist runter reshade wurde auch einmal deaktiviert.

**Comment by DrGrizzlY17** [comment]
Also da das Wetter jetzt auch nicht auf Unwetter deutet, würde ich behaupten du hast korrupte Dateien. Also nen Clientseitiger Fehler

Bei Steam vielleicht mal auf Fehler überprüfen. Falls Social Club Version, da gibt es das auch. Musst nur bei google erfolgreich sein.

**Comment by DrCassado** [comment]
Dateien wurden überprüft nach einen neustart war das problem behoben, nach einen erneuten war wieder das problem da. werde im laufe der woche mal den kompletten pc erneut neu aufsetzten
