### ISSUE TITLE
Key gebühren trotz eingeparktem Fahrzeug

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#2359]
**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Stündliche Fahrzeuggebühr trotz eingeparkten Fahrzeug bezahlen

**Erwartetes Verhalten**
keine kosten sobald das Fahrzeug eingeparkt ist

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeugschlüssel jem. geben, darauf achten das der ein Dollar Symbol hinter dem namen hat. Fahrzeug dann einparken und warten bis gebühren abgezogen werden.

**Comment by epichalt** [comment]
ist so gewollt, wurde gestern korrigiert

**Comment by PrimroseBloom** [comment]
Ich bezahle stündlich $3 obwohl ich bei keinem Fahrzeug den 3. Schlüssel besitze.

**Comment by its4l3x** [comment]
@Dean-Gallagher 

Leider durch Misskommunikation gestern ein Fehler unserseits. Ist so gewollt. Du zahlst egal wann, sobald du Online bist, die Schlüssel.

Wir werden auch noch einen passenden Forumbeitrag erstellen, welcher das alles nochmal korrekt und deutlich zusammenfasst.

@PrimroseBloom 

Ich muss dich leider enttäuschen, aber du zahlst korrekt für diesen Schlüssel. Hier geht es um deinen Hellion für den du korrekt die 3$ stündlich zahlst.

**Comment by PrimroseBloom** [comment]
@its4l3x Ok! Danke für die Schnelle Antwort.
