### ISSUE TITLE
Bug Hotelzimmer miete

### ISSUE THREAD

**Issue by LukeRiley1507** [mexyn/statev_v2_issues#2360]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Luke Riley

**Auftrittszeitpunkt (Datum / Uhrzeit)**

16.04.22 21:15 

**Beobachtetes Verhalten**

Miete wurde nicht abgezogen fehlermeldung unten links wurde angezeigt.

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![20220416210839_1](https://user-images.githubusercontent.com/75139258/163688845-d1ef9298-43ce-4447-84e7-a20e0af4af84.jpg)

**Comment by LukeRiley1507** [comment]
![20220416210839_1](https://user-images.githubusercontent.com/75139258/163688986-6ff5f227-fd57-4dcc-ac24-4b4a2b022bcd.jpg)

**Comment by DrGrizzlY17** [comment]
#2346
