### ISSUE TITLE
Auffahrt vom Grundstück sowie Tür vom Schuppen. [Zaun entfernen] / [Tür freilegen]

### ISSUE THREAD

**Issue by Looper-L** [mexyn/statev_v2_issues#2361]
**Character Name**
- Gerold Langberg

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Date: 16.04.2022 / Uhrzeit: /

**Beobachtetes Verhalten**
Bild 1.: Der Zaun kann nicht selbstständig entfernt werden, blockiert somit die Einfahrt auf das Grundstück zum Carport mit einem Fahrzeug.
Bild 2.: Die Tür auf dem Bild kann man mit dem Charakter halb öffnen und nicht weiter, etwas blockiert den Durchgang und es kann so selbst nicht gelöst werden, leider.

**Erwartetes Verhalten**
Bild 1.: Ich weiß nicht genau wie die miteinander verbunden sind, aber soweit ich das weiß, kann man die markierte Stelle entfernen. Wenn die Stelle entfernt werden könnte, wäre das natürlich prima. Dann kann man die Auffahrt auch nutzen, sonst wäre das Carport echt zu schade. 
Bild 2.: Ob es möglich wäre den Durchgang komplett frei zumachen, sodass man durch die Tür kommt. Das kann ich selber nicht sagen, allerdings kann man ja mal Fragen. 
![StateV #1](https://user-images.githubusercontent.com/103857358/163692930-f7627c1c-79ab-4e6b-9f51-1703c611aecf.PNG)
![StateV #2](https://user-images.githubusercontent.com/103857358/163692931-7d07fc6c-b306-4ba5-8096-94b10677bd80.PNG)

**Schritte um den Fehler nachvollziehen zu können**
- Am besten selber mal ein Bild machen, bei Gelegenheit: PLZ 826, SandyShores32.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1440p

**Optional: Video / Bilder des Fehlers**
Bild-1: 
![StateV #1](https://user-images.githubusercontent.com/103857358/163692740-45b828d5-3931-44d9-966f-5599bf3344b5.PNG)
Bild-2: 
![StateV #2](https://user-images.githubusercontent.com/103857358/163692743-36e7d3f7-0a62-4846-bba3-e99ea0f437fe.PNG)

**Comment by DonVitoDiangelo** [comment]
1. Zaun entfernt
2. Tür wird so bleiben, dahinter ist im Grunde auch nichts

**Comment by Looper-L** [comment]
Hallo,
ich glaube beim Zaun wurde ein Teil Zuviel entfernt, oder funktionierte das nicht anders?

-> 
![#1](https://user-images.githubusercontent.com/103857358/166117738-e34e0aa3-2176-4d82-a6a9-36eef3d705ce.PNG)

Grüße.

**Comment by TheOutburst** [comment]
Metall ist teuer heutzutage, nen Abbau davon lässt man sich nicht zweimal sagen.
Spaß beiseite, da hats Vito wohl zu gut gemeint und wollte dir eine zweite Einfahrt schaffen, zum nächsten Update ist der zweite Zaun wieder da.

**Comment by Looper-L** [comment]
Rückt mein Zaun wieder raus, Ihr Bengel! 
Super, dann weiß ich bescheid. Vielen dank Euch.
