### ISSUE TITLE
Fehlende Magazine im 24/7 zum Entpacken

### ISSUE THREAD

**Issue by DerHessenTyp** [mexyn/statev_v2_issues#2362]
*Andreas Jung**

Das tritt seit Anfang des Updates auf, bis zum jetzigen Zeitpunkt 17.04. 09:15 Uhr

**Beobachtetes Verhalten**
Es ist kein Bug sondern eher eine Feststellung:
Man kann im 24/7 die Stadtkarte und das Finanzmagazin was man in der Fertigung herstellen kann entpacken.
Die Magazine:
Verpacktes Breasts OUT Spermen BURST (Heft)
Verpacktes Das NYchtliche TECHtelmechtel (Heft)
Verpacktes King Vock in der Vockahöhle (Magazin)
sind alle 3 nicht im 24/7 zu entpacken. 

**Erwartetes Verhalten**
Sollte hier also kein Fehler vorliegen, kann der Bug Report geschlossen werden, ansonsten bitte in der Maschine am 24/7 hinzufügen.

**Comment by TheOutburst** [comment]
hupsi.
ja, sollte man schon entpacken können, kann man dann ab 15:00 auch
