### ISSUE TITLE
ID's wegfeilen von bestimmten Waffen.

### ISSUE THREAD

**Issue by eldoodaks** [mexyn/statev_v2_issues#2366]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Darryl Bradley

**Auftrittszeitpunkt (17.04.22 / 12Uhr ca)**

**Beobachtetes Verhalten**
Als ich heute von meinen Langwaffen die ID's wegfeilen lassen sollte gehen folgende Waffentypen nicht: Hk416, Mossberg 590A1 AOW, Qbz, Akmsu

**Erwartetes Verhalten**
Normalerweise sollte es doch die Möglichkeit geben von allen Langwaffen die Id's wegfeilen zu können

**Schritte um den Fehler nachvollziehen zu können**
Man geht auf Cayo. Rüstet die Waffe aus wo die ID weggefeilt werden soll. Geht zu dem netten Herren und sagt er solle das bitte machen. Bei den oben genannten Waffen ist dies aber leider nicht möglich.

**Comment by Statev-Bonsai** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2236

**Comment by eldoodaks** [comment]
Oh sorry ich hatte das garnicht gesehen Bonsai :o

**Comment by eldoodaks** [comment]
Aber es macht halt kein sinn warum es bei den Waffen nicht gehen sollte. Warten wir einfach nochmal ab, hab schon viele gehört die es feiern würden.
