### ISSUE TITLE
Seitdem vorletzt Patch extreme FPS Einbrüche

### ISSUE THREAD

**Issue by darealpino** [mexyn/statev_v2_issues#2367]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```
**Character Name**
**Louis Gambino**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Vorletzten Patch am 16.04 [Gegen die Crashes/Casino]

**Beobachtetes Verhalten**
Seitdem Großen Patch von dem  Crashes/Casino habe ich sowie viele andere von meiner Fraktion Teilweise bei Bewegen des Chars / Autofahren extreme FPS Einbrüche, Durchschnittlich: 80 - 100 FPS Dropen auf 20 bis 7 FPS Hält circa 30 Sek bis 1 Minute an danach geht es wieder. 

**Foto / Videobeweis**
https://i.imgur.com/qdaYCCH.gif

**Erwartetes Verhalten**
Keine FPS Drops 

**Schritte um den Fehler nachvollziehen zu können**
Bewegung mit Char / Mausbewegung / Fahrzeuge

**Comment by JannikDatsch** [comment]
Am Freitag, also am Abend des Release war das noch ned so. Da gabs zwar auch einige Gamecrashes, aber FPS wie immer

**Comment by darealpino** [comment]
Gebe ich dir Recht - Es kam zwar immer wieder zu Gamecrashes allerdings waren meine FPS immer Stabil danach wurde meines wissen Nachts irgendwann ein Patch eingeführt, ein Fix gegen Crashes das hat auch geholfen aber dadurch ist das FPS Problem entstanden.

**Comment by TheOutburst** [comment]
Wir haben den akuten Fehler gefunden und mit dem letzten Update behoben, siehe Changelog
