### ISSUE TITLE
Neue Kleidung hat bei Frau und Mann unterschiedliche Materialien

### ISSUE THREAD

**Issue by CatherineGallagher** [mexyn/statev_v2_issues#2368]
**Character Name**
Catherine Gallagher

**Beobachtetes Verhalten**
Neuen Skinny Jeans der Männer benötigen SIlberbarren und Leder, gleichnamige Hose für Frauen aber nicht.
Beispiel:

[M] Schwarze Rebel Skinny Jeans
2x Schwarzer, 1x Leder , 1x Silberbarren, 2x Ballen Garn

[F] Schwarze Rebel Skinny Jeans
2x Schwarzer Stoff , 2x Ballen Garn

**Erwartetes Verhalten**

Sollten gleiche Produktionmaterialien benutzen

**Comment by Enemyaa** [comment]
Nee, da es sich bei der Männerhose um n ganz anderes Modell handelt mit Ledergürtel.
