### ISSUE TITLE
Inventar lässt sich nicht schließen

### ISSUE THREAD

**Issue by Fabse96** [mexyn/statev_v2_issues#237]
**Character Name**
Fabio_Gonzales

**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020/13:02

**Beobachtetes Verhalten**
Inventar lässt sich nicht mehr mit dem 2.ten anklickoption unter ausweis anzeigen im inventar schließen

**Erwartetes Verhalten**
Inventar schließt sich nach anklicken 

**Schritte um den Fehler nachvollziehen zu können**
Inventar öffnen und so versuchen zu schließen 

**Optional: Video / Bilder des Fehlers**
![Unbenannt](https://user-images.githubusercontent.com/74773267/99799242-a619cd00-2b32-11eb-83c3-f42af6863298.PNG)

**Comment by Chrinis007** [comment]
Das 2. Symbol war auch in V1 nur für den dienstausweis da damit du den selber siehst.
Schöne Grüße

**Comment by DonVitoDiangelo** [comment]
kein Bug
