### ISSUE TITLE
Einsteigen über "G" nicht mehr mgl.

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#2370]
**Character Name**
Jannik Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.04 20 Uhr

**Beobachtetes Verhalten**
Einsteigen über "G" nicht mehr mgl.,

Edit.: Bzw zumindest teilweise

**Comment by foggel8** [comment]
Habe das gleiche Problem, mehrere Kollegen ebenfalls

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2116
