### ISSUE TITLE
PD Sessel 

### ISSUE THREAD

**Issue by RylixYT** [mexyn/statev_v2_issues#2372]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Hamudi Dodl**

**00:20**

**Wenn man bei den Sesseln in Mission Row PD aufstehen will, buggt man sich durch die Wand dahinter**

**Das man ganz normal aufstehen kann**

**Hinsetzen, aufstehen**

**[Siehe Video](https://streamable.com/t3jvqq)**

**Comment by TheOutburst** [comment]
Aufstehanimation wurd von den braunen Stühlen im Flur entfernt
