### ISSUE TITLE
Anlehnen - Rauchen fehlerhaft?

### ISSUE THREAD

**Issue by AdmiralState** [mexyn/statev_v2_issues#2373]
**Character Name**
Nick Blinders

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.04.2022 00:45 Uhr

**Beobachtetes Verhalten**
Bei der Animation Anlehnen - Rauchen hält man die Kippe in der Hand und bewegt diese dann nicht obwohl man klar hört das der Char an der Kippe zieht und Rauch aus dem Mund kommt

**Erwartetes Verhalten**
Die Hand sollte sich beim Rauchen bewegen

**Schritte um den Fehler nachvollziehen zu können**
Kippe anzünden und Animation ausführen

**Optional: Video / Bilder des Fehlers**
https://streamable.com/y34g9g

**Comment by milkdrops** [comment]
Hier stimmt alles, ist so von GTA vorgegeben und anders nicht vorhanden.
