### ISSUE TITLE
Bei Gamestart StateV UI nicht geladen

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#2375]
**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.+18.+24.04

**Beobachtetes Verhalten**
Bei Gamestart lädt die StateV UI (Handy Tablet, Essensleiste) ned. Nach Restart gehts wieder. Hab das jetzt 2x in 2 Tagen gehabt, davor nie.

**Comment by DrGrizzlY17** [comment]
Huhu wenn du das nochmal hast bitte F8 und einen ausschnitt der Konsole posten oder aus dem altV den entsprechenden Log hochladen

**Comment by JannikDatsch** [comment]
Ach blöd, hatte das grad nm. aber hab das erst jetzt gelesen. Mir hat aber jmd. gesagt, dass er das auch vor dem Update schon kannte, bei mir zumindest ned.

**Comment by JannikDatsch** [comment]
Ich hab jetzt aber den AltV StateV Ordner gelöscht und neu runtergeladen. Vlt. löst das das Problem

**Comment by JannikDatsch** [comment]
Habs seitdem nicht mehr gehabt, kommts nm vor, schreib ich nm

**Comment by JannikDatsch** [comment]
Hatte es jetzt mal wieder
