### ISSUE TITLE
Casino - Lucky Wheel

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#2376]
**Character Name**
Marvin_Elpe

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.04.2022 - 00:40

**Beobachtetes Verhalten**
Tägliches drehen am Glücksrad klappt nicht immer. Habe gestern um kurz nach 0 gedreht, wodurch wieder nach 0 Uhr die Möglichkeit da wäre, was heute nicht der fall ist.

Zusätzlich wird der 2h Timer zum drehen, wenn ich es richtig mitbekommen habe, nach einen Restart resetet.

**Erwartetes Verhalten**
Glücksrad kann täglich gedreht werden.

2h Timer wird nach Restart nicht resetet.

**Schritte um den Fehler nachvollziehen zu können**
Nicht immer der Fall gewesen.

**Comment by M4rvinLP** [comment]
Drehen ging nach 1 Uhr dann, das Timer Problem ist trotzdem.

**Comment by epichalt** [comment]
timer "problem" ist einfach, dass du 2h ununterbrochen ic sein musst. was mMn so auch gut ist

**Comment by M4rvinLP** [comment]
Ah verstehe, dann passt es eig. ja schon. Danke

**Comment by TeubyDE** [comment]
System wurde optimiert und steht beim nächsten Update zur Verfügung.
