### ISSUE TITLE
Fahrzeuge im Wiki nicht aktuell

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#2377]
**Beobachtetes Verhalten**

Die Fahrzeuge der letzten Updates fehlen teilweise. 

https://wiki.statev.de/index.php?title=Übersicht_der_Fahrzeuge

Bsp.: Tailgater S, Granger 3600LX, I-Wagen
Manche wurden hingegen hinzugefügt: Astron, Buffalo STX, Cinquemila

**Comment by JannikDatsch** [comment]
Auch im StateNet/StateCom fehlen einige #1659

**Comment by Dean-Gallagher** [comment]
Hallo, wie du gesehen hast wird das Wiki überarbeitet wird. 
Neue Fahrzeuge werden so erst nach und nach eingetragen wenn sie Alphabetisch dran sind.
Außerdem ist diese Umstellung ein langdauernder Prozess welche durch extrem viele Faktoren abhängt und verlangsamt wird wie unter anderen Updates von GTA und ALT. 
Neue Fahrzeuge werden auserdem nicht direkt nach dem Release eingetragen damit man sich IC damit auseinander setzt. 

Grüße
Dean
