### ISSUE TITLE
Exakt gleiche Fahrzeug, verschiedene Leistung

### ISSUE THREAD

**Issue by Pregon** [mexyn/statev_v2_issues#2379]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Ronny Roberts

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.04.2022

**Beobachtetes Verhalten**
Fahrzeug hat unterschiedliche Leitung im Vergleich zu anderen Fahrten mit demselben Fahrzeug
--> 1. Fahrt zu kämpfen überhaupt auf 200 zu kommen --> https://cdn.discordapp.com/attachments/819295425403682846/965966475666030593/Schnelligkeitsunterschied_1.mp4
--> 2. Fahrt keine ohne Probleme auf 300 --> https://cdn.discordapp.com/attachments/819295425403682846/965966467168346152/Schnelligkeitsunterschied_2.mp4

**Erwartetes Verhalten**
Immer gleiche Leistung

**Schritte um den Fehler nachvollziehen zu können**
Auf gut Glück mit dem GTO testen

**Comment by Ekaz58** [comment]
Sind das nicht einfach nur die Bodenwellen die dein auto auf 300kmh bringen? ;) eigentlich sollte der GTO garnicht so schnell fahren können. ich denke Video 1 ist die richtige geschwindigkeit.

**Comment by Dean-Gallagher** [comment]
Bitte auf Youtube oder anderen Platformen hochladen wo man keinen Download macht. Danke

**Comment by Pregon** [comment]
Video 1: https://youtu.be/jlwg92Cn4d8
Video 2: https://youtu.be/Etcvk-JByd8

**Comment by epichalt** [comment]
Das sind nicht nur Bodenwellen. Aber gibt da allgemein aktuell einen Bug. Ein - und Aussteigen löst es normalerweise.

**Comment by l4m4rr224** [comment]
Zwei verschiedene Strecken bei Video 1 ist auch noch die Steigung die mit einspielt und bei Video 2 hast du unnormal viele Bodenwellen,da komm ich mit der Hellfire auf 270

Teste das mal auf der selben strecke und nicht zwei verschiedene

**Comment by Pregon** [comment]
Hier nochmal der direktvergleich auf selber Strecke: https://youtu.be/hYqbMCn3Cn8

**Comment by Dean-Gallagher** [comment]
in dem falle https://github.com/mexyn/statev_v2_issues/issues/2355
