### ISSUE TITLE
Phantom Custom mit Gr. Motor

### ISSUE THREAD

**Issue by adrosso** [mexyn/statev_v2_issues#2383]
**Kevin_Falck**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
(17.04.2022-20.04.2022/ Dauerhaft)

**Beobachtetes Verhalten**
Kann es sein das der Phantom Custom mit einem großen Motor und 7000 KM etwas an der geschwindigkeit gebastelt wurde? Ich war bei 4 unterschiedlichen Werkstätten und habe den immer auslesen lassen (kein befund), habe den dennoch reparieren lassen und es ist immer das selbe, die beschleunigung (anzug) ist echt mies geworden. Das "problem" habe ich jetzt seit 3 tage. Auf dem kleinen Öl feld (im steinbruch) fahre ich den berg (erste Pumpe) mit 5-10Km/h hoch. Wenn ich los fahre, braucht der po lange um mal aus dem Quark zu kommen. 

**Erwartetes Verhalten**
Geschwindigkeit anpassen sowohl in der End als auch im Anzug.

**Schritte um den Fehler nachvollziehen zu können**
Es gibt schon einige Reports zu dem Thema, ansonsten es vielleicht mal selber probieren und Fahren.

**Comment by milkdrops** [comment]
#2382
