### ISSUE TITLE
Fahrzeug Geschwindigkeiten verändert

### ISSUE THREAD

**Issue by sYnaTiion** [mexyn/statev_v2_issues#2384]
**Character Name**
Costa Cruze

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.04.22 Uhrzeit: 20:30

**Beobachtetes Verhalten**
Thrax ohne Bodenwelle 230 Km/h mit Bodenwelle 240 Km/h
Komoda ohne Bodenwelle 210 Km/h mit Bodenwelle 235 Km/h
Sultan RS ohne Bodenwelle 200 Km/h mit Bodenwelle 230 Km/h

alle Fahrzeuge waren ohne Fehlermeldung.

**Erwartetes Verhalten**
Thrax mit 419 PS sollte zumindest ein wenig schneller auf dem Highway fahren als Revolter oder Komoda.
Komoda fuhr vorher 230 Km/h ohne Bodenwellen.
Sultan RS fuhr vorher 250+ ist OP aber auf 200Km/h nicht passend.

**Schritte um den Fehler nachvollziehen zu können**
Auf dem Highway fahren

**Comment by Dean-Gallagher** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2355 würde ich mal vermuten

**Comment by eldoodaks** [comment]
Finde allgemein die Geschwindigkeiten von Supersportlern total unpassend. Wofür habe ich damals Mio von $ ausgegeben damit ich jetzt mit Supersportlern langsamer als normale fahre? Mh

**Comment by Statev-Bonsai** [comment]
Selbst die Hypercars im Wert von über einer Million werden teilweise von normalen Sportwagen Nass gemacht, das verhältnis der Geschwindigkeiten auf State passt nichtmal ansatzweise...

**Comment by h3adbang3r** [comment]
Evtl. sollte man erkennen das PS die Kraft und nicht die Höchstgeschwindigkeit ist. Sie sollten also schnell(er) beschleunigen, wenn aber die Drehzahl des Motors, im höchstem Gang, am Ende ist, war es das einfach mit dem beschleunigen.

**Comment by TamiGaming** [comment]
@h3adbang3r wenn aber ein Supersportler ala Thrax oder Furia die gleiche Geschwindigkeit wie ein Kuruma hat.. ist das ganze ein wenig fragwürdig. :D

**Comment by milkdrops** [comment]
#2355
