### ISSUE TITLE
Garage Freigabe

### ISSUE THREAD

**Issue by AnooMagic** [mexyn/statev_v2_issues#2386]
**Character Name**
- Kadir Padir

**Auftrittszeitpunkt (Datum / Uhrzeit)**
- Jeden Tag (Haushash: JunVespucciCanals_House_4)

**Beobachtetes Verhalten**
- Fahrzeuge werden in die Garage des Hauses eingeparkt

**Erwartetes Verhalten**
- Fahrzeuge sollten nicht eingeparkt werden
- Garage freigeben um die Autos ein- und ausparken zu können, da Garage vorhanden

**Schritte um den Fehler nachvollziehen zu können**
- Fahrzeuge die über uns laufen und in der Nähe geparkt sind werden in die Garage des Hauses eingeparkt und können nicht wieder ausgeparkt werden, da das Haus keine Garagenfreigabe hat

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/1e94dfad9ef4ae43f3a4991a052edba8

**Comment by TheOutburst** [comment]
Witzig, ihr habt nen Garagenpunkt aber dürft keine Autos einparken.
Das letztere habe ich euch mal zum nächsten Update gewährt, automatisch eingepart werden eure Autos vorerst weiter, solange da Slots frei sind.
