### ISSUE TITLE
Teleporter Anfrage

### ISSUE THREAD

**Issue by AnooMagic** [mexyn/statev_v2_issues#2387]
**Character Name**
- Kadir Padir, Lana Garcia

**Auftrittszeitpunkt (Datum / Uhrzeit)**
- Haushash: JunVespucciCanals_House_4

**Beobachtetes Verhalten**
- Terrasse vorhanden aber kein Zugang

**Erwartetes Verhalten**
- Zugang zur Dachterrasse 

**Schritte um den Fehler nachvollziehen zu können**
- Einrichtung High Class Apartment (Brown) -> Eingang an der obersten Etage, hinten eine Glastür zur Terrasse , hier würde der Teleporter nach draußen perfekt passen
- https://gyazo.com/a4354f2e9f56c3e257b85d528ad57844

**Optional: Video / Bilder des Fehlers**
- Teleporter für den Dachterrassenbereich 
- https://gyazo.com/dabd3e0004c74efe007b0abd7e3c3ae6

**Comment by TheOutburst** [comment]
Öffentliche Teleports aus privaten Interieurs heraus machen wir nicht, hab euch den Eingang an eure Garagentüre gepackt

**Comment by AnooMagic** [comment]
dann lieber an den Hintereingang vom Gebäude 
https://gyazo.com/f4eddb0cca0146da2712af0b25474914
