### ISSUE TITLE
SAPD Fahrzeuge, Dachnummern verbuggt

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#2389]
**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit neue Dachnummern eingeführt wurden

**Beobachtetes Verhalten**
Die Dachnummern wechseln teilweise, wobei das immer bei einzelnen Spielern unabhängig vorkommt und nicht immer für alle Spieler gleich dargestellt wird.

So ist bsp. hier ( https://www.twitch.tv/videos/1462729170?t=3h54m28s ) bei mir die richtige Dachnummer (302) angezeigt worden, die auch hier dann angezeigt wurde. ( https://www.twitch.tv/videos/1462729170?t=4h18m26s )

Ich hab außer LA Roads auch nix an Grafikmods drauf, sodass es an sowas ned liegen kann.

**Optional: Video / Bilder des Fehlers**

https://youtu.be/B6RRidXMmqs

**Comment by milkdrops** [comment]
Ist reproduzierbar mit dem "Kotflügel / Extras 1".
Ich gehe von dem aktuellen alt:V issue aus, dass extras durchgehend random sind.
Aber warum das während der Nutzung passiert, ist nicht bekannt

**Comment by DonVitoDiangelo** [comment]
Derzeit bleibt es so. Wenn wir die extras ins Tuning einbauen, kann es nochmal geprüft werden. Bis dahin closed.
