### ISSUE TITLE
Hotel Fehlerhaft - AkiPillboxHillRew_Flat_5

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#239]
**Character Name**
Max_Broady

**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020 - 13:26

**Beobachtetes Verhalten**
User Hotel ist AkiPillboxHillRew_Flat_5
allerdings im Reiter "Immobilien" unter Wohnungen werden Zimmer von AkiPillboxHillRew_Flat_6 & AkiPillboxHillRew_Flat_7 angezeigt.

**Erwartetes Verhalten**
Das wir nur Zimmer aus AkiPillboxHillRew_Flat_5 angezeigt bekommen
Diese sollten auch eigentlich behoben sein: https://statev.de/forum/StateBug/index.php?issue/3789-hotel-fehlerhaft/

**Schritte um den Fehler nachvollziehen zu können**
Im Hotel unter Übersicht den Hotelhash mit dem Zimmerhash vergleichen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
-

**Optional: Video / Bilder des Fehlers**
HotelHash
![Screenshot_3](https://user-images.githubusercontent.com/70150887/99800419-9ef3be80-2b34-11eb-870e-4b4a429858ec.png)
Zimmerhash
![Screenshot_1](https://user-images.githubusercontent.com/70150887/99800422-a0bd8200-2b34-11eb-9257-5a690c7ef027.png)
Zimmerhash
![Screenshot_2](https://user-images.githubusercontent.com/70150887/99800423-a0bd8200-2b34-11eb-9ea1-7d9b141abb10.png)

**Comment by DrGrizzlY17** [comment]
@TheBroady bitte mal Screenshots von allen Flats die dir im Hotel angezeigt werden

**Comment by DrGrizzlY17** [comment]
Sollte zum nächsten Update alles passen.

Euer Hotel hat zwar den _5 Hast, eure Wohnungen werden aber die Flat_7_* behalten. Ihr solltet nachm nächsten Restart
7_1 - 7_20 haben. Falls nicht, bescheid sagen.

**Comment by TheBroady** [comment]
Hallo @DrGrizzlY17 

rein logisch macht diese Lösung für mich keinen Sinn. Hoffe du kannst mir das nochmal erläutern.
Wir besitzen aktuell AkiPillboxHillRew_Flat_5, wieso bearbeiten wir dann im Tablet Flat_7. Wäre hier nicht 5_1 - 5_XX richtig?
Zudem hat sich die Zimmeranzahl seit dem Restart um 18 Uhr von 40 um die Hälfte (20) verringert.

Auf deine Frage hin kann ich so bestätigen.
Aktuell haben wir im Tablet die Auszahl: 7_1 - 7_20 kalkulieren allerdings seit Kauf am 23.09 mit 40 Zimmern.
