### ISSUE TITLE
Durch Wände Bugen anhand der neuen Aufstehanimationen 

### ISSUE THREAD

**Issue by Niinja231** [mexyn/statev_v2_issues#2391]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Angel_Jordan**

Angel_Jordan
**Auftrittszeitpunkt (Datum / Uhrzeit)**

22.04.2022 21:30
**Beobachtetes Verhalten**

Im PD in dem Eingangsbereich sind Sitzmöglichkeiten. Setzt man sich dort jedoch hin und steht wieder auf: so fällt man (anhand der neuen Aufstehanimation) durchs PD und steckt in einer falschen Dimension.
**Erwartetes Verhalten**

das man nicht durch die wand Bugt
**Schritte um den Fehler nachvollziehen zu können**

Man setzt sich hin und steht dann wieder auf 
![Screenshot_18](https://user-images.githubusercontent.com/79274300/164808535-85ff9608-2ee6-4708-b8c8-ed24a454c3c0.png)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by SHaagmann** [comment]
Duplikat: #2372

**Comment by TheOutburst** [comment]
Aufstehanimation wurd von den braunen Stühlen im Flur entfernt
