### ISSUE TITLE
Beschleunigung und Geschwindigkeit Pegassi Reaper

### ISSUE THREAD

**Issue by StateV-Jan** [mexyn/statev_v2_issues#2392]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Jan Bach

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Pegassi Reaper kommt nicht mehr auf seine 290, er ist jetzt bei 240-250 Ende auf grader Strecke. Dazu kommt noch das er für diese Geschwindigkeit sehr lange braucht zumindest länger als vor dem Update. Er fährt inmoment so wie ein 50k Auto verbraucht aber doppelt soviel Sprit wie ein Sportwagen der gleich schnell fährt (kein Fehler vorhanden)
**Erwartetes Verhalten**
Hat bessere Werte wieder und fährt seine 290 und kommt besser auf diese Geschwindigkeit

Reaper fährt seine 290 wieder und hat ne deutlich bessere Beschleunigung
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by milkdrops** [comment]
#2355
