### ISSUE TITLE
Ausladeproblem MD nach Laufanimationswechsel 

### ISSUE THREAD

**Issue by ArnoZuDemB** [mexyn/statev_v2_issues#2393]
**Character Name**
Robert_ Bates

**Auftrittszeitpunkt (Datum / Uhrzeit)**
20.04.2022 gegen 16:30 Uhr und am 23.04.2022 um 18:20 Uhr

**Beobachtetes Verhalten**
Man verbuggt im RTW nachdem man mit der Trage hineingepackt wurde. Man verbuggt im RTW in die Liegeanimation auf der Trage. Ausladen über "Olga" nicht möglich. Beim normalen Aussteigen wird man in die Liegeanimation auf der Trage geforced und kann sich nicht bewegen. Videomaterial bezieht sich auf den 23.04. Man wird während der Fahrt in die Liegeanimation gezwungen und das Playermodel buggt unter den RTW. Der MD Gegenpart in der Situation ist Aliyah King, sie hat in ihrem Stream bestätigt, dass sie ein Problem beim Ausladen hatte.

**Erwartetes Verhalten**
Ausladen und aussteigen sollte weiterhin normal möglich sein.

**Schritte um den Fehler nachvollziehen zu können**
1. sich über Trage in einen RTW laden lassen
2. Lauf-/Gehanimation wechseln
3. Ausstieg über Olga oder normal probieren

Meine Perspektive: https://medal.tv/games/gta-v/clips/iLQQN0iJasc-p/d1337quW7zbn?invite=cr-MSxZT3UsMTg3NzgyNTks
Bestätigung des Problems: https://www.twitch.tv/videos/1464590553?t=04h21m34s

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2438
