### ISSUE TITLE
Aufsteh-Bug von Stühlen im MD mit neuer Aufstehanimation

### ISSUE THREAD

**Issue by ArnoZuDemB** [mexyn/statev_v2_issues#2394]
**Character Name**
Robert Bates

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.04.2022 gegen 19 Uhr

**Beobachtetes Verhalten**
Aufstehanimation vom Restaurant greift auch im MD --> verbuggt man in Wänden und an Gegenständen
möglicher Lösungsvorschlag: aktuelle Restaurantaufstehanimation um IF-Zusatz ergänzen, sodass die neue Aufstehanimation nur in Restaurants auslöst

**Erwartetes Verhalten**
altes, herkömmliches Aufstehen ohne Probleme

**Schritte um den Fehler nachvollziehen zu können**
Auf Stühlen im MD Platz nehmen (mit Y) und aufstehen

https://medal.tv/games/gta-v/clips/iM36o3vQv0uxh/d1337KrBLJGa?invite=cr-MSxmT3IsMTg3NzgyNTks

**Comment by DrGrizzlY17** [comment]
fixed next update

**Comment by Hochfels** [comment]
Bei einem Stuhl ist der Bug noch im MD. Im Pausenraum gleich der erste Stuhl linksm landet man immer noch im nirgendwo
