### ISSUE TITLE
Einbruch Bug 

### ISSUE THREAD

**Issue by GoatJuan** [mexyn/statev_v2_issues#2396]
**Character Name: Juan_Solis*

**Auftrittszeitpunkt 24.04.2022/00:30**

**Wenn man den auftrag Grove Street 33 einbrechen kriegt von Toby kann man nicht einbrechen da steht nur wohnung mieten**

**Normalerweise steht da der name vom besitzer und ein feld wo dick ROT steht EINBRECHE**

**Bei Toby einen auftrag annehmen und in die Grove street 33 geschickt werden oder ein anderes haus im kreisel**

https://www.youtube.com/watch?v=xvfon43SdrY&ab_channel=GoatJuan

**Comment by GoatJuan** [comment]
jetzt hab ich das problem das mir angezeigt wird das ich noch eine aktive mission hab obwohl ich die nicht mehr habe bei Toby...

**Comment by TeubyDE** [comment]
Sollte sich mit dem Server restart von selbst lösen. @GoatJuan

**Comment by TeubyDE** [comment]
nächstes Update fix.
