### ISSUE TITLE
Verändern vom Kofferraum-Punkt bei Pfister Comet Retro Custom

### ISSUE THREAD

**Issue by Erumeldor** [mexyn/statev_v2_issues#2398]
**Beobachtetes Verhalten**
Beim Pfister Comet Retro Custom ist bauartbedingt der Motor hinten, und der Kofferraum vorne.
So reagieren natürlich auch die Klappen, beim aufmachen.
Leider ist der Zugriffspunkt für den Kofferraum trotzdem hinten. Ist etwas seltsam immer das so machen zu müssen ;)

**Erwartetes Verhalten**
Kofferraum-Zugriffspunkt nach vorne legen, vor das Fahrzeug.

Ich weiß nicht welche Autos das noch betrifft, aber den fahre ich aktuell eben viel ;)

**Comment by Statev-Bonsai** [comment]
Einfach mal die suche bemühen ;)

https://github.com/mexyn/statev_v2_issues/issues/1990

**Comment by epichalt** [comment]
Betrifft alle und wird auch nicht geändert. Mal die Suchfunktion nutzen 😅
