### ISSUE TITLE
HK-Portal: Website hochladen

### ISSUE THREAD

**Issue by Erumeldor** [mexyn/statev_v2_issues#2399]
**Character Name**
Satoru_Tsuyoshi (auch Name im HK Profil)

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.04, ~20:20Uhr

**Beobachtetes Verhalten**
Wenn man im Portal der Handelskammer eine Website für eine Firma hochladen will, gibt's dieses schöne Formular. Während des Formulars wird auch der Verwendungszweck und vban für die Überweisung mitgeteilt.
Auf der letzten Seite, bevor alles abgeschlossen wird, muss man noch bestätigen das man die Überweisung gemacht hat.
Wenn dieser Haken nicht gesetzt wird (hatte es erstmal vergessen) und trotzdem auf den abschließenden Button drückt, kommt zwar Meldung das die Dateien gesendet wurden, gleichzeitig auch gesagt das die Überweisung fehlt.
Nun ist das Problem, das die Dateien noch nicht hochgeladen wurden. 
Der Button zum Abschließen ist nun aber schon weg, egal ob man den Haken setzt das man die Überweisung getätigt hat oder nicht. Man muss daher alles neu machen. Dabei ändert sich dann aber auch der Verwendungszweck für die Überweisung.

**Erwartetes Verhalten**
Abschließend Button deaktivieren falls der Haken für die Überweisung noch nicht gesetzt ist.
Oder allgemein: Den letzten Button nicht verschwinden lassen. Vielleicht sogar wenn alles vollständig ist, das Fenster automatisch schließen. 

**Schritte um den Fehler nachvollziehen zu können**
Homepage hochladen.
Im letzten Schritt den Haken nicht senden, dann auf "Fertig". Dann Haken setzen und versuchen das die Dateien noch hochgeladen werden.

**Comment by KingMarcel** [comment]
Wird mit dem nächsten sahk.de Update behoben. Danke für die Meldung
