### ISSUE TITLE
Umherhüpfen bei Standortwahl für aufstellbaren Gegenstand

### ISSUE THREAD

**Issue by Nuuki900** [mexyn/statev_v2_issues#24]
**Zeitpunkt (Datum / Uhrzeit)**

25.08.2020 / ~19.15

**Beobachtetes Verhalten**

Wenn man einen Gegenstand aufstellen möchte, diesen auswählt, um den Standort zu wählen und dann mit Shift rennt, hüpft man durch die Gegend bzw portet sich von Standort zu Standort (siehe Video)

**Erwartetes Verhalten**

Shift = rennen

**Schritte um den Fehler nachvollziehen zu können**

1. aufstellbaren gegenstand aus Inventar mit rechtsklick ausgewählt
2. Standort gewählt
3. Shift dabei gedrückt

**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=xNFnVFtautw

**Comment by its4l3x** [comment]
Fixed. :)
