### ISSUE TITLE
Verladen ins Lager nicht möglich

### ISSUE THREAD

**Issue by statevmj** [mexyn/statev_v2_issues#240]
**Character Name**
Mathew_Jones

**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020 / 13:18 Uhr

**Beobachtetes Verhalten**
Es war nicht möglich Items aus dem Fahrzeug ins Lager zu verschieben und umgekehrt. Unten links stand nur die Fehlermeldung "ungültiges Ziel" - generell hat sich das UI nicht "gut angefühlt" und hat sich nach dem schließen durch "I" wieder geöffnet und ich hätte etwas vom Inventar ins Lager schieben können, obwohl ich außerhalb des Gebäudes stehe. Möglicherweise liegt es in diesem besonderen Fall aber daran, dass zuviele Objekte in dem Lager sind. Das Problem gab es schonmal zu v1 und wurde damals von Leroy gelöst. 

**Erwartetes Verhalten**
Das Verladen in und aus Fahrzeuge sollte reibungslos funktionieren, egal wie viele Objekte sich im Lager befinden. Das UI sollte nachdem schließen durch "I" nicht erneut aufgehen. 

**Schritte um den Fehler nachvollziehen zu können**
Auf dem DEV Server mit einem Fahrzeug an das Lager mit dem Firmenhash: pfWestVine20 fahren und aus testen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=KMUWVwQfr58

**Comment by DrColgate** [comment]
musst den kofferraum öffnen zum be und entladen

**Comment by statevmj** [comment]
Auch wenn ich den Schlüssel besitze oder Besitzer des Fahrzeugs bin? Das wäre mir zu V2 dann neu, das habe ich nicht getestet. Ich probier das gleich mal aus.

**Comment by statevmj** [comment]
Ja, tatsächlich funtkioniert es, wenn der Kofferraum geöffnet ist. Dann wäre ein Hinweis darauf aber vermutlich trotzdem nützlicher als der Fehler "Ungültiges Ziel"
