### ISSUE TITLE
Taschen Inventar nach Maschinen aufruf

### ISSUE THREAD

**Issue by GonzoMenendez** [mexyn/statev_v2_issues#2402]
Sobald man mit einer Tasche ausgerüstet im Inventar an eine Maschine heran läuft die für das entpacken ist,
wird nach dem schließen des Eigeninventar / Maschine / Lager HUD nicht mehr die Tasche beim drücken von "i" angezeigt.

Erst nach ablegen der Tasche ins Char-Inv, Auto, Lager und erneutem ausrüsten wird das HUD wieder angezeigt

**Comment by M4c-M4ni4c** [comment]
Die Tasche kannst du normalerweise wieder öffnen über den button im ui:

![image](https://user-images.githubusercontent.com/52389841/165519429-b18ffa7f-eac9-4d06-98e6-cbe8dd567dad.png)

**Comment by TheOutburst** [comment]
Das was M4c-M4ni4c schreibt, es ist so gewollt.
