### ISSUE TITLE
Banshee zieht weißes Quadrat hinter sich her

### ISSUE THREAD

**Issue by SimonPfeifferStateV** [mexyn/statev_v2_issues#2405]
Character Name
Simon Pfeiffer

Auftrittszeitpunkt (Datum / Uhrzeit)
27.04.2022, 20:15 Uhr

Beobachtetes Verhalten
Sobald ich in meine Banshee einsteige, zeihe ich immer hinter mir ein weißes Quadrat hinter mir her. (Siehe Bild)

Erwartetes Verhalten
Kein weißes Viereck.

Schritte um den Fehler nachvollziehen zu können
In eine Banshee einsteigen.

Monitorauflösung (nur wenn Falsche Darstellung in der UI)

Optional: Video / Bilder des Fehlers
https://prnt.sc/mweU_FdvryAn

**Comment by Saaria83** [comment]
Bei jemanden am Haus stand auch gestern eine Banshee und hatte das gleiche
![Viereck](https://user-images.githubusercontent.com/70151476/165709921-dd35a25c-2544-4cc5-bd6a-ef98df660258.png)
