### ISSUE TITLE
Casino Timer bugged

### ISSUE THREAD

**Issue by Saaria83** [mexyn/statev_v2_issues#2406]
**Character Name**
Hanna Fields - Ricardo Gonzales

**Auftrittszeitpunkt (Datum / Uhrzeit)**
28.04.2022 08:30 Uhr ~

**Beobachtetes Verhalten**
Croupier Timer läuft ins Minus bzw weiter

**Erwartetes Verhalten**
Croupier Timer sollte nicht mehr vorhanden sein, wenn der Timer auf 0 ist

**Optional: Video / Bilder des Fehlers**

https://user-images.githubusercontent.com/70151476/165702814-97dafa23-3d1a-4834-a585-85f8970c6628.mp4

**Comment by Saaria83** [comment]
![Timer](https://user-images.githubusercontent.com/70151476/165703061-d31b47e3-821f-4ce1-840d-a66f52b74d25.jpg)

Der Timer ist auch nach dem Casino Gang noch da und nach einem Neustart nicht mehr

**Comment by TeubyDE** [comment]
Das Problem sollte mittlerweile behoben sein, wenn das nicht so ist gerne noch mal melden.
