### ISSUE TITLE
Durchsichtiger Boden

### ISSUE THREAD

**Issue by Kingkiosk** [mexyn/statev_v2_issues#2408]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Chester Pilgrim

Chester Pilgrim
**Auftrittszeitpunkt (Datum / Uhrzeit)**

29.04.2022 20:50
**Beobachtetes Verhalten**

Bei besuch bei Horizont man kann durch den Boden durch gucken. Im Auto durchgängig, außerhalb in bestimmten Winkeln
**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![grafik](https://user-images.githubusercontent.com/103830515/166008952-e34cdee1-94a7-4a29-85c6-e3d1404a3562.png)

**Comment by M4c-M4ni4c** [comment]
bist vermutlich als beifahrer mit in die Werkstatt rein oder?

**Comment by TeubyDE** [comment]
Nach dem nächsten Update sollte das nicht mehr vorkommen.
