### ISSUE TITLE
Rechtschreibfehler MD Menü

### ISSUE THREAD

**Issue by quotenben** [mexyn/statev_v2_issues#2409]
**Character Name**
Ben Hawking

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Rechtschreibfehler

**Erwartetes Verhalten**
Wie es sich für einen deutschen Server gehört, ohne.

**Schritte um den Fehler nachvollziehen zu können**
MD Menü öffnen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
Toaster

**Optional: Video / Bilder des Fehlers**
![20220429_215416](https://user-images.githubusercontent.com/66183993/166009272-638d0691-8267-4746-b7c4-2245f229f31a.jpg)
![20220429_215337-min](https://user-images.githubusercontent.com/66183993/166009530-10d39215-a5ce-415f-a960-c1f25524f217.jpg)

**Comment by Enemyaa** [comment]
Danke für den Hinweis. Fixed next Update!
