### ISSUE TITLE
Tastenbelegung "#" ohne Funktion

### ISSUE THREAD

**Issue by h3adbang3r** [mexyn/statev_v2_issues#241]
**Thorlic Redoran**

**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020, vermutlich seit Release

**Beobachtetes Verhalten**
Das Overlay, Tacho bei Fahren, bzw. die Vitalitätsanzeige, lässt sich mit "#" nicht ausblenden

**Erwartetes Verhalten**
Zitat wiki: "Blendet alle Anzeigen aus, damit du schöne Fotos machen kannst." ;)

**Schritte um den Fehler nachvollziehen zu können**
Taste # betätigen

**Comment by tastydev** [comment]
wird zu einem späteren zeitpunkt hinzugefügt
