### ISSUE TITLE
Falsche Namen bei neuen Regenschirmen

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#2410]
**Auftrittszeitpunkt (Datum / Uhrzeit)**
29.04.2022 - 22:30

**Beobachtetes Verhalten**
Die neuen Regenschirme haben im StateNet noch Kürzel als Namen. Zusätzlich fehlen dort auch die Bilder.

**Erwartetes Verhalten**
Richtiger Name wird angezeigt. Bilder werden angezeigt

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/i/LFCMD.png

**Comment by DrGrizzlY17** [comment]
StateNet updaten

**Comment by TeubyDE** [comment]
Besteht der Fehler nach dem heutigen Update immer noch? @M4rvinLP

**Comment by M4rvinLP** [comment]
Namen waren schon seit 1 Woche korrekt. Bilder fehlen allerdings noch.

**Comment by DonVitoDiangelo** [comment]
Die werden noch nachgeliefert :)
