### ISSUE TITLE
Fliegende Graffities

### ISSUE THREAD

**Issue by WalDragoner3425** [mexyn/statev_v2_issues#2413]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name:**
William Void

**Auftrittszeitpunkt (Datum / Uhrzeit)**
30.04.2022 um 3:00 Uhr

**Beobachtetes Verhalten**
Fliegende Grafitties in der Luft welche je nach Blickrichtung durchsichtig sind.

**Erwartetes Verhalten**
Keine fliegenden Grafitties in der Luft welche je nach Blickrichtung durchsichtig sind.

**Schritte um den Fehler nachvollziehen zu können**
Einfach hinfahren.

**Optional: Video / Bilder des Fehlers**
Ort: https://pic.statev.de/image/grafik.LFcF0
Video: https://youtu.be/E3WxAwM-oug

**Comment by TheOutburst** [comment]
Wir haben da hinten zwei Trailer entfernt, mit dem Tuner DLC hat R* da die Grafittis drauf gemacht
Gleiches mit dem Grafitti vorne, da hängt das aber am gesamten Gebäude dran und das kriegen wir nicht so simpel entfernt, die Unschönheit muss also wohl erstmal so bleiben.
