### ISSUE TITLE
Produktion Verpacktes Schild: Frisch gewischt

### ISSUE THREAD

**Issue by DerHessenTyp** [mexyn/statev_v2_issues#2414]
Andreas Jung

**Beobachtetes Verhalten**
Die neue Produktion Verpacktes Schild: Frisch gewischt, soll Stand jetzt mit Lackdosen hergestellt werden, würde den Preis aber in die Höhe schiessen.

**Erwartetes Verhalten**
Das Schild soll wie alle anderen Schilder wahrscheinlich auch nur mit Tuben Farbstoff hergestellt werden, daher sehe ich da einen einfachen Produktiosnfehler.

![Schilder](https://user-images.githubusercontent.com/70151958/166098591-912c61e5-2071-4be0-b0f2-65d6600590f6.jpg)

**Comment by DrGrizzlY17** [comment]
Hello,
whoops. Rot und Grün wird dann mit dem nächsten Update zu Farbtuben. Der Schwarze Lack bleibt :)
