### ISSUE TITLE
Unsichtbarer Gegenstand

### ISSUE THREAD

**Issue by MrsSykes** [mexyn/statev_v2_issues#2415]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Madison Cole

30.04.2022, 20 Uhr

Unsichtbarer Gegenstand gegen den man läuft

Keine Blockade des Spieler

Einfach dort entlang laufen, dann läuft man gegen den unsichtbaren Gegenstand

**Monitorauflösung (nur wenn Falsche Darstellung in der U
![Screenshot_3](https://user-images.githubusercontent.com/93479831/166117231-bd65b9c3-7390-4743-9390-506c53badc2e.png)
![Screenshot_60](https://user-images.githubusercontent.com/93479831/166117233-8602056b-e684-478e-b802-4ccfc2a4836a.png)

https://user-images.githubusercontent.com/93479831/166117293-a1b362ac-4e2c-4ba8-bef4-c03fbb186e97.mp4

I)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Hängt da zufällig ne Lichterkette?

**Comment by DrGrizzlY17** [comment]
Ok hab nachgeguckt. Da ist ne Lichterkette. Es kommt von der Lichterkette. Das Prop hat leider eine unsichtbare Kollision wo eigentlich eine Stange ist (auch als Item aufm Server verfügbar). Deswegen ist läufst du dagegen
