### ISSUE TITLE
Schwarzer Faltenrock & weisse Overknees

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#2418]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Mila & Ryan Valdes**

Mila Valdes

**Auftrittszeitpunkt (Datum / Uhrzeit)**

02.05.2022
**Beobachtetes Verhalten**

Schwarzer Faltenrock & weisse Overknees werden beim tragen nicht mehr angezeigt.
Der Rotkarierte mit Overknees funktioniert auch nicht
Scheint als würde der Skin nicht überschrieben dh. wen man eine Hose an hat und dann auf den rock wechselt bleibt die Hose angezeigt die man vorher an hatte. Nur der schwarze mit schwarzen tights geht.

**Erwartetes Verhalten**

Klamotten werden wieder angezeigt.
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![unknown](https://user-images.githubusercontent.com/70231715/166267700-3471570f-5a9c-4c6e-8f33-f6aa5aff5098.png)

**Comment by Enemyaa** [comment]
Hi,

danke für die Info. Fixed next Update!

**Comment by Enemyaa** [comment]
Zusatz: Nächstes Update, nicht das heutige!
