### ISSUE TITLE
Mehrere Fahrzeuge sind langsamer nach Update

### ISSUE THREAD

**Issue by Smaty86** [mexyn/statev_v2_issues#2419]
Tim_Rock 

Der Phantom und auch der Pfister sind nach dem Update deutlich langsamer. Beim Öl fahren kommt man nur sehr schwer den Berg hoch, meistens muss man öfter anfahren. In der Werkstatt sagte man mir das es viele Kunden mit dem gleichen Problem gibt und beim Auslesen keine Fehler gefunden wurden 

Ich konnte es bisher nur bei den beiden Fahrzeugen beobachten. Außerdem sind die Fahrzeuge wieder schnell wenn man über die Beifahrertür einsteigt.

**Comment by sYnaTiion** [comment]
Thrax, T20, Revolter genau das gleiche Problem.

**Comment by SHaagmann** [comment]
Duplikat von #2355 .
Einfach da nochmal reinschreiben
