### ISSUE TITLE
Möbelstücke nicht Sichtbar im Int

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#242]
**Character Name**
Max_Broady

**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020 - 14:06

**Beobachtetes Verhalten**
manche Möbelstücke im Interior nicht sichtbar.
Andere welche vorher unsichtbar waren allerdings schon

**Erwartetes Verhalten**
Das diese Sichtbar sind.

**Schritte um den Fehler nachvollziehen zu können**
Ins Haus gehen mit dem Interior von Michaels Single Player Villa

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![20201120140442_1](https://user-images.githubusercontent.com/70150887/99803402-b1242b80-2b39-11eb-9b46-e30ba1fd1611.jpg)
![20201120140445_1](https://user-images.githubusercontent.com/70150887/99803406-b2edef00-2b39-11eb-9a74-a0215b8e7469.jpg)

**Comment by DonVitoDiangelo** [comment]
fixed next update
