### ISSUE TITLE
Tug einparken

### ISSUE THREAD

**Issue by StateV2Marie** [mexyn/statev_v2_issues#2420]
Wenn man versucht ein Tug einzuparken brauch man bald meiste so um die 20 min bis man die stelle gefunden hat die sich anscheinend immer wieder ändert kann man da i-was machen? das mans schneller einparken kann wäre lieb.

**Comment by Stiefel911** [comment]
Ist es bei der Angelstelle oben Ostseite? 
Da musst nur drauf achten das der Typ an Land sichtbar bleibt. 😉

**Comment by CaleighRhodes** [comment]
> 

Was aber, tbh, fast unmöglich ist. Selbst mit nem kleinen Boot.
