### ISSUE TITLE
O Sheas Barber Shop  Wünscht Bezahlung über Bankeinzug.

### ISSUE THREAD

**Issue by StateV2Marie** [mexyn/statev_v2_issues#2421]
Hallo wäre es vll möglich das ihrs einrichten könntet das die leute nich immer zum atm rennen müssen sondern wie man ic so schön sagt mit EC Karte zahlen kann wäre echt lieb weil viele findens halt doof zum atm rennen zu müssen und ich wolt schon vor ne weile mal fragen aber wust nich obs geht aber bei anderen gehts wohl auch drum frag ich mal lieb könntet ihr das so machen das man kein bargeld bei haben muss? wäre echt lieb danke.

**Comment by DrGrizzlY17** [comment]
Hello, 
nein wir werden für Frisöre keine Zahlung über Bank möglich machen. Wir haben es damals mit gutem Grund umgestellt. Das die Leute auch mit Bargeld unterwegs sind und dadurch vielleicht auch ein wenig vorsichtiger sind.

Bei anderen Frisören ist es ebenfalls nur möglich bar zu bezahlen über das System, aber viele Frisöre arbeiten um das System herum. Vielleicht wäre das auch eine Möglichkeit für dich.
