### ISSUE TITLE
Baravdo STX Stoßdämpfer

### ISSUE THREAD

**Issue by Cro20** [mexyn/statev_v2_issues#2423]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Dominik_Sova**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**während des Fahrens komische geräusche von den Stoßdämpfern. Keine Probleme im Racemodus. Problem tritt nur im Driftmodus auf. Auto ist NICHT Tiefergelegt worden in der Werkstatt. Laut Discord haben andere STX Fahrer keine Probleme**

**Auto fährt ohne ständiges knallen der Stoßdämpfer**

**In den STX Steigen Driftmodus Aktivieren und los fahren**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**[Optional: Video / Bilder des Fehlers](https://www.youtube.com/watch?v=flGsVAVARvg)**

**Comment by DrGrizzlY17** [comment]
Das ist kein Fehler. Durch den Driftmodus liegt das Auto einfach tiefer. Das heißt weniger Federweg, heißt härtere Federung bei Straßenunebenheiten. Das was du hörst ist einfach die Feder die durchknallt bei Unebenheiten. Kein Fehler^^
