### ISSUE TITLE
Dominator ASP, Beschleunigung nach wegnahme vom Gas = 0 

### ISSUE THREAD

**Issue by AndoMalius** [mexyn/statev_v2_issues#2427]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Ando_Malius

**Beobachtetes Verhalten**
Dominator ASP:
Generell ist das Problem das man beim wegnehmen vom Gas ca.10sec keinerlei Beschleunigung mehr hat.
Ganz extrem ist aber, das wenn man eine Straße fährt die nur eine leichte steigung hat die Geschwindigkeit einem Burrito ähnelt und man in einer echt sehr langsamen Geschwindigkeit voran kommt. ( In Race und Driftmode gleich / auch andere Bereifungstypen machen keinen Unterschied ) 
Bitte selbst das Fahrverhalten testen.

**Erwartetes Verhalten**
Wenn man vom Gas geht und wieder rauf sollte eine Beschleunigung vorhanden sein, beim befahren von Straßen mit leichter steigung muss eine deutlich bessere Beschleunigung und Endgeschwindigkeit vorhanden sein. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Am besten mal eine Werkstatt besuchen :)
