### ISSUE TITLE
Dominator ASP, zu wenig Leistung

### ISSUE THREAD

**Issue by AndoMalius** [mexyn/statev_v2_issues#2429]
Dominator ASP:
Generell ist das Problem das man beim wegnehmen vom Gas ca.10sec keinerlei Beschleunigung mehr hat.
Ganz extrem ist aber, das wenn man eine Straße fährt die nur eine leichte steigung hat die Geschwindigkeit einem Burrito ähnelt und man in einer echt sehr langsamen Geschwindigkeit voran kommt. ( In Race und Driftmode gleich / auch andere Bereifungstypen machen keinen Unterschied )
Sämtliche IC inhalte zum lösen des Problems wurden in erwägung gezogen.
Das Proböem besteht nicht bei einem gewissen Dominator ASP, sondern bei jedem Dominator ASP ( ja auch dies wurde IC gestestet um einen Fehler ausfindig machen zu können ) 
Bitte selbst das Fahrverhalten testen.

Erwartetes Verhalten
Wenn man vom Gas geht und wieder rauf sollte eine Beschleunigung vorhanden sein, beim befahren von Straßen mit leichter steigung muss eine deutlich bessere Beschleunigung und Endgeschwindigkeit vorhanden sein.
Dominator ASP generell zu under powered.

Monitorauflösung (nur wenn Falsche Darstellung in der UI)

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2427
