### ISSUE TITLE
Werkstatt Instant Repair

### ISSUE THREAD

**Issue by BlackyGER** [mexyn/statev_v2_issues#243]
Werkstätten haben keine Dauer für eine Repair. 
Hatte 3 Stück gemacht, bei der ersten hatte ich einen dauerbalken und er dauerte auch, 
die 2. und 3. waren instant fertig obwohl das Auto qualmte.

**Comment by r3sist3nt** [comment]
Bedingt durch den Release Branch.

**Comment by JulianMa** [comment]
durch alt:V fixed
