### ISSUE TITLE
Kein passendes Kleidungsstück

### ISSUE THREAD

**Issue by HuiBuh32** [mexyn/statev_v2_issues#2431]
Inge Knesebeck

**Beobachtetes Verhalten**
Zu folgendem Kleidungsstück gibt es keine passende Kombination: [F][U] Weiße Bluse mit gekrempelten Ärmeln

**Erwartetes Verhalten**
Bluse passt zu den existierenden Westen.. sie ist sooo schön :(

**Comment by Enemyaa** [comment]
Hi, 

mit dem nächsten Update dann.

**Comment by Enemyaa** [comment]
Zusatz: Nächstes Update, nicht das heutige!
