### ISSUE TITLE
Arbeiterhelm beim Holzfahren

### ISSUE THREAD

**Issue by Saaria83** [mexyn/statev_v2_issues#2435]
**Character Name**
Hanna Fields

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11.05.2022 gegen 23:00 Uhr

**Beobachtetes Verhalten**
Beim Holzfahren braucht man ja neuerdings einen Arbeiterhelm. Verständlich und super :)
Ich hab mir dann einen Gelben geholt und bekam diese Nachricht (Bild angehängt) 
Ich denke ja mal, dass man jeden dafür nutzen sollte und nicht unbedingt nur den orangenen

**Erwartetes Verhalten**
Dass man jeden Arbeiterhelm zum Holzfahren nutzen kann

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

![GTA5_wG1ax6QwlA](https://user-images.githubusercontent.com/70151476/168027988-f3c8de03-d426-49f8-b7a2-1540e2e2828f.png)

**Optional: Video / Bilder des Fehlers**

**Comment by Enemyaa** [comment]
Doch genau so ist es!
