### ISSUE TITLE
Zugang Balkon

### ISSUE THREAD

**Issue by Eve-Noxito** [mexyn/statev_v2_issues#2436]
Charakter Name:
Eve_Noxito

Wäre es möglich über das Garagentor einen Teleportpunkt zu einem der Balkone zu bekommen? Gibt leider keine andere Möglichkeit auf den/die Balkone zu gelangen.
Haushash: SamsonCountryRew_House_12
![Garage](https://user-images.githubusercontent.com/74910428/168182885-6054d4ac-fb30-4c1f-b9f8-dd075316a1ee.png)

![Balkon](https://user-images.githubusercontent.com/74910428/168183033-35214a49-db31-4f1d-8710-966400e7bc12.png)

**Comment by TeubyDE** [comment]
leider keine Türe vorhanden durch die man hoch kommen könnte.
