### ISSUE TITLE
Antrag auf eine Garage 

### ISSUE THREAD

**Issue by RickoSanchez** [mexyn/statev_v2_issues#2439]
Hausbesitzer
Ricko Sanchez

Haushash
house_MirrorPark_19

Ich würde gerne wie beim Nachbarn (house_MirrorPark_21) eine Garage beantragen .

Nachbar ( house_MirrorPark_21 )
<img src="https://pic.statev.de/i/LLFiu.jpg" alt="LLFiu.jpg" border="0" />

Unser Haus ( house_MirrorPark_19 )

<img src="https://pic.statev.de/i/LLif2.jpg" alt="LLif2.jpg" border="0" />

Und Bitte die Verkaufsschilder weg machen fals es nicht zu viele Umstände macht .

<img src="https://pic.statev.de/i/LLjcP.jpg" alt="LLjcP.jpg" border="0" />
<img src="https://pic.statev.de/i/LL2Oi.jpg" alt="LL2Oi.jpg" border="0" />

Vielen lieben Dank ❤️

**Comment by TheBroady** [comment]
FYI

Die Verkaufsschilder gehen nur Optisch weg.
Es bliebe weiterhin eine Unsichtbare Wand wo die Schilder ständen.

**Comment by Enemyaa** [comment]
Hi, diese Wolfs Schilder sind gar keine einzelnen Objekte.

Der Rest - next Update!
