### ISSUE TITLE
Werkstätten kein progressbalken mehr

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#244]
Nach etwas Tuning habe ich keinen Progressbalken mehr, sprich ich seh nicht das ich was mache. Nach exakt einen Tuning trat das problem auf. 

https://youtu.be/SzmR8tXh19w

**Comment by DrGrizzlY17** [comment]
Bekannt, sollte überall funktionieren außer bei Xenon. Bitte mal testen

**Comment by its4l3x** [comment]
Immer noch beständig der Bug? @BlackyGER

**Comment by BlackyGER** [comment]
scheint fixed, kommt nur wenn man vorher in einer firma eine Produktion anmachte
