### ISSUE TITLE
Garagen Punkt Verschieben

### ISSUE THREAD

**Issue by ChapWinchester** [mexyn/statev_v2_issues#2440]
1. Haus Southside: Carson Ave. 29 - house_EastLS_31 - [https://pic.statev.de/i/LUosY.png](url)

Garage: [https://pic.statev.de/i/LUhQD.jpg](url)  -  Das Aktuelle Punkt an die stelle verlegen wo der Char steht, mehr zur Straße wenn es geht.

2. Damit der Garten begehbar ist wäre auch gut wenn der Zaun in Rot wegkommt. Dann könnte man da zwischen durch laufen um in den Garten zu kommen. [https://pic.statev.de/i/LUvXV.jpg](url)

Grüße und Vielen Dank :)

**Comment by Enemyaa** [comment]
Hi, den Garagenpunkt hab ich mal versetzt, aber das mit dem Zaun ist die Trennwand zu deinem Nachbarn, außerdem kommst du ja rechts in den Garten.

Next Update dann!

**Comment by ChapWinchester** [comment]
Danke Enemyaa, das Nachbar Haus ist auch meiner :) wollte die Zusammen führen. Wenn es nicht geht passt es ja dann.

Vielen Dank
