### ISSUE TITLE
haus Verlassen Punkt verschieben

### ISSUE THREAD

**Issue by DrCassado** [mexyn/statev_v2_issues#2441]
Ricardo Cassado

Immer wenn das haus verlassen wird ( paletobay20 )

beim Verlassen des Hauses wird man mitten in die Einfahrt geportet.
Dies ist Unpraktisch da dort normalerweise Autos geparkt werden was schon zu manch einen Unfall geführt hatte.
Deswegen währe es schon wenn man den Spornpunkt für das verlassen des Hauses eventuell in die Nähe der Haustür Geportet wird

**Comment by Enemyaa** [comment]
Next Update!
