### ISSUE TITLE
Garage am Leuchtturm

### ISSUE THREAD

**Issue by TamiGaming** [mexyn/statev_v2_issues#2442]
**Character Name**
Carlie Tacus

**Beobachtetes Verhalten**
Für das Haus am Leuchtturm Hash JunSandyShoresRew_House_42 gibt es eine Garage für Fahrzeuge unter dem Carport. 
Wäre es möglich an der gleichen Stelle auch eine Garage für den Leuchtturm zu setzen? Da man dort sonst keine Möglichkeit hat ein Fahrzeug zu parken und man jeden Tag bis zur Grapeseed Garage laufen müsste. 
Hash vom Leuchtturm JunSandyShoresRew_House_43

Wenn es nicht möglich ist, wäre eine Alternative vlt. eine Garage zum einparken von Booten auf dem Wasser?

**Bild vom Carport vor dem Leuchtturm / Haus**
![image](https://user-images.githubusercontent.com/40512639/168989210-c92dea70-e961-4900-9dd2-50962655ef76.png)

**Comment by Enemyaa** [comment]
Beides werden wir so nicht umsetzen
