### ISSUE TITLE
[M] Brustverband falscher Name

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#2446]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Sven Rosenbach
**Auftrittszeitpunkt (Datum / Uhrzeit)**

18.05.22
**Beobachtetes Verhalten**

Das Item des Brustverbands für Männer heißt [M] Brustverband
**Erwartetes Verhalten**

Es sollte eher [M] [U] Brustverband heißen, da es den Slot für die Unterkleidung benutzt 
**Schritte um den Fehler nachvollziehen zu können**

Einfach Item Anschauen 
**Optional: Video / Bilder des Fehlers**

https://streamable.com/oug5uo

**Comment by Enemyaa** [comment]
Next Update!
