### ISSUE TITLE
Versetzung Angeln Punkte

### ISSUE THREAD

**Issue by JonnyHart** [mexyn/statev_v2_issues#2447]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Jonny Hart

**Auftrittszeitpunkt (Datum / Uhrzeit)**
20.05.2022 11:21 Uhr

**Beobachtetes Verhalten**
Angeln Unterwasser xD

**Erwartetes Verhalten**
Angeln Überwasser xD

**Schritte um den Fehler nachvollziehen zu können**
Angel + Wurm --> Angeln

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
2560x1440

**Optional: Video / Bilder des Fehlers**
https://clips.twitch.tv/GiantFlaccidPidgeonKippa-19WrZnRszul535eE

**Comment by JonnyHart** [comment]
Angelgrund Osten Richtung Paleto

**Comment by CatherineGallagher** [comment]
Hmm das scheint bei dir nur etwas Visuelles zu sein, da dein Sauerstoff nicht runtergeht, trotz das du Unterwasser bist? Mir ist das auch noch nie passiert, dass die Wellen so nah sind. Benutzt du irgendwelche Grafik Mods?

**Comment by JonnyHart** [comment]
hab nur Reshade drauf

**Comment by Dean-Gallagher** [comment]
das liegt wohl an reshade oder weil du mal ein grafikmod hattest,, das thema hatten wir vorkurzem im Discord auch 
https://discord.com/channels/365251792679862292/411925103048392724/964916643945939066

**Comment by JonnyHart** [comment]
Bis auf Reshade hab ich nichts drauf gehabt.

**Comment by Saaria83** [comment]
Ich habe keine Grafikmods drauf und kann bestätigen, dass das wirklich passiert. Habe grade kein Video zur Hand aber hatte das auch ziemlich oft
