### ISSUE TITLE
Nach Update/Fix immer noch keine Leistung !

### ISSUE THREAD

**Issue by Eskadiel** [mexyn/statev_v2_issues#2448]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Eskadiel Nightmare**

**21.5.22 : 2.10Uhr**

**Paragon R "Fehlerfrei" fährt nach Update 205Km/h bei 350Ps / Einsteigen auf der Beifahrerseite 220-235Km/h**

**Eisteigen auf der Fahrerseite 240-250Km/h ! Der Paragon R ist ein Sportwagen mit 350Ps und kann mit anderen Fahrzeugen nicht mal ansatzweise mithalten. 4-Türer mit der Hälfte der Leistung schaffen 200Km/h, teils mehr, aber ein 2 Sitze Sportscar läuft nicht mal 210Km/h**

**Paragon R "M4/4" Abwechselnd Fahrer/Beifahrerseite Testen**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Bitte einmal Kennzeichen mitteilen

**Comment by Eskadiel** [comment]
Erstmal Danke für diese Ausführliche Antwort.
Ich werde nochmals Fahrtests durchführen, aber wie schon erwähnt sehe ich deinen Durchschnitt von 205-215 Auf dem Highway nicht als "Passig" oder "fine". Der Paragon hat 351Ps und wird von 4 Türern mit der Hälfte der Leistung in einen Topf geschmissen.
Bodenwellen sind auch nicht permanent oder auf allen Routen so massig vorhanden das der Wert von 260+ ein Realer wert ist.
Soll auch nicht bedeuten das der Paragon der neue Metaflitzer sein soll und das er im durchschnitt 260 fahren soll. aber ein Durchschnitt von 230-235 sollte dann doch schon drin sein.
Mein Paragon Kennzeichen "Albtraum"
MFG Eska

**Comment by DonVitoDiangelo** [comment]
Wie gesagt, wir haben ein System, mit den alle Fahrzeuge balanced wurden und werden.
Die 205-210 sind ein worst case. In der Stadt fährst du easy 230-240 und mehr.
Ich habe auch keine Lust das zum 10 mal zu schreiben. Wir lassen ein Fahrzeug nicht 250 auf dem Highway fahren, damit er in der Stadt dann 300 und mehr fährt. Das wird es nicht geben! Der  Paragon fährt so wie er fährt, seiner Klasse entsprechend wie er soll.
