### ISSUE TITLE
Handy geht nicht mehr aus der Hand!

### ISSUE THREAD

**Issue by Otacon225** [mexyn/statev_v2_issues#245]
**Artjom_Kaloshka**
Handy nach Telefonat nicht mehr weggehen.

**Wann?**
14:50 Uhr, 20.11.2020
**Beobachtetes Verhalten**
Handy nach Telefonat nach wir vor in der Hand!

**Erwartetes Verhalten**
Wegstecken des Handys

**Optional: Video / Bilder des Fehlers**
![Grand Theft Auto V Screenshot 2020 11 20 - 14 51 59 07](https://user-images.githubusercontent.com/70226950/99808152-bdf84d80-2b40-11eb-9b19-83eb76f21983.jpg)

**Comment by its4l3x** [comment]
Bitte mir ein Video schicken. Kann das nicht reproduzieren.

**Comment by Clawdie** [comment]
Gleiches Problem gestern Abend erstmals. Wie oben beschrieben.
Bis zum Ausloggen trotz zahlreicher Tätigkeiten Handy weiterhin in der Hand nach Gespräch.

**Comment by Chrinis007** [comment]
Bisher nie aufgetreten und wenn dann über , entfernbar

**Comment by CaleighRhodes** [comment]
Habe den Bug auch schon gehabt, über , nicht weglegbar, erst nach Neustart des Games Handy dann weg.

**Comment by TheBroady** [comment]
Ist es möglich den Delay raus zu nehmen welcher verhindert, dass man das Handy nach dem rausholen direkt wieder weg stecken kann? 🙏🏻

**Comment by its4l3x** [comment]
Nein. Dadurch das wir mit dem Cooldown die Attachments (handy, tablet) abfangen und wir somit Clipping oder sowas wir hiermit abfangen. Einzelne Edge Cases können wir de facto nicht abfangen, da dieses auch an deinem eigenen PC liegen kann, welcher diese Sachen einfach nicht auf die Schnelle verarbeiten kann. Haben das nochmal sukzessiv getestet gehabt und keinen Fehler unserer Seite festellen können.

Wichtig ist hierbei auch das ein PC benötigt wird, welcher auch Power hat. Daher CLOSED
