### ISSUE TITLE
Fahrzeug nach dem Update optisch verändert

### ISSUE THREAD

**Issue by KennanJr** [mexyn/statev_v2_issues#2450]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Kennan Jackson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.05.2022 02:00 Uhr

**Beobachtetes Verhalten**
Fahrzeug sieht optisch nicht so aus, wie vor dem Update.
Fahrzeugtyp: Elegy RH8
Kennzeichen: Spicy

**Erwartetes Verhalten**
Fahrzeug sollte anders aussehen.

**Schritte um den Fehler nachvollziehen zu können**
//

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080 

**Optional: Video / Bilder des Fehlers**

Wie's aussehen sollte:
![Rh1](https://user-images.githubusercontent.com/105954775/169627931-07c57a6f-0afa-40ec-8840-269ceff21d53.png)
![Rh2](https://user-images.githubusercontent.com/105954775/169627933-367d1f49-6c90-43a1-9a19-2496a239a16d.png)
![Rh3](https://user-images.githubusercontent.com/105954775/169627936-b37313f3-8e33-4948-b1df-dd5ac52fa157.png)

Wie's jetzt aussieht:
![Rh4](https://user-images.githubusercontent.com/105954775/169628124-4a22f88d-f1d5-4ea0-8a68-7fa8881240f1.png)
![Unbenannt22](https://user-images.githubusercontent.com/105954775/169628143-d3fde654-097a-47f3-be3c-9e976a62f516.png)

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2449
