### ISSUE TITLE
Fahrzeug Interieur verändert 

### ISSUE THREAD

**Issue by simplycach** [mexyn/statev_v2_issues#2451]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Ralle Kutschera

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.05.2022 / 11:08

**Beobachtetes Verhalten**
Das Fahrzeug Interieur hat sich nach dem Update teilweise verändert bzw. zurückgesetzt.
Fahrzeug Name: Ubermacht Cypher / 225 PS
Kennzeichen:  RK 95 

**Erwartetes Verhalten**
Aussehen wie vor dem Update

**Schritte um den Fehler nachvollziehen zu können**
Vergleichsbilder

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Interieur Farbe vorher (Schwarz mit Carbon Sitze)
https://pic.statev.de/image/202204090010825-1.UIbBJ

Nachher Farbe Rot
https://pic.statev.de/image/20220521110614-1.UIAZs
https://pic.statev.de/image/20220521110533-1.UIJHD

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2449
