### ISSUE TITLE
Sämtliches Tuning+Design wurden entfernt

### ISSUE THREAD

**Issue by Dennymaru** [mexyn/statev_v2_issues#2452]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name** 
Danny Mayer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.05.2022 um 13:05

**Beobachtetes Verhalten**
Sämtliches Tuning und das Design sind entfernt worden

**Erwartetes Verhalten**
Tuning und anderes Design sollte da sein

**Schritte um den Fehler nachvollziehen zu können**
Autos ausparken (mehrere Versuche)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
Fahrzeug: Karin Futo
Besitzer: Albert Pike
Kennzeichen: LS0401AP

Wie es vorher aussah:
![20220225162017_1](https://user-images.githubusercontent.com/105973647/169649193-a4e16ee1-c85e-4157-b1f9-aafcd2aabb0d.jpg)
![header](https://user-images.githubusercontent.com/105973647/169649199-0b1c0de1-032c-44ee-bb02-36300083d3ca.jpg)
![FutoDreckig](https://user-images.githubusercontent.com/105973647/169649227-4314d2dd-edeb-4008-94cc-fb1074f3d89d.png)

Wie es jetzt aussieht:
![Grand Theft Auto V Screenshot 2022 05 21 - 13 10 59 51](https://user-images.githubusercontent.com/105973647/169649249-9251d2a8-0e54-4125-b308-cdad20cfb4a5.png)
![Grand Theft Auto V Screenshot 2022 05 21 - 13 16 44 27](https://user-images.githubusercontent.com/105973647/169649270-e7345bc8-a76f-490d-b9a1-9effb28b9893.png)

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2449
