### ISSUE TITLE
Tunnig nach Update weg 

### ISSUE THREAD

**Issue by Nordlys12** [mexyn/statev_v2_issues#2453]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Frieda_Hansen

Willard Faction Custom /109Ps --- Tunnig weiss nicht mehr genaues datum 

**Auftrittszeitpunkt (Datum / Uhrzeit)**

21.05.2022 beim ausparken ca.13.05uhr aus Garage  Vespucci Beach

**Beobachtetes Verhalten**
 ausgeparkt Folie weg und interroir , mehrmals ein und ausgeparkt

**Erwartetes Verhalten**
 Herstellung vor dem update

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2449
