### ISSUE TITLE
UI Bug 

### ISSUE THREAD

**Issue by SatyriaDine** [mexyn/statev_v2_issues#2455]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Sofia_Black

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.05.2022 19:40

**Beobachtetes Verhalten**
nach dem Aktivieren eines Rennens beim NPC war die Statusleiste (essen, trinken, voice) eingefroren. Man konnte nicht mehr sehen ob man gemutet war, auch wurde das voicesymbol nicht mehr grün. 
Beim ausblenden der UI blendete sich nur die Minimap aus.
Nach dem einsteigen in ein Auto bemerkte ich dass auch die X-Taste zum Auto starten ect nicht mehr das X-Menü triggert. Der Mauszeiger wurde zwar sichtbar, nicht aber das Menü.

Nach einem Gamerestart und erneuten auswählen eines Rennens trat der Fehler nicht auf. 

**Erwartetes Verhalten**
UI sollte nicht einfrieren/crashen

**Schritte um den Fehler nachvollziehen zu können**
Rennen am NPC auswählen. UI anschauen. X-Menü ausprobieren

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2424
