### ISSUE TITLE
Patient steht im RTW nach Einladen

### ISSUE THREAD

**Issue by LukeRiley1507** [mexyn/statev_v2_issues#2456]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Luke Riley

Jerome Jansen
**Auftrittszeitpunkt (Datum / Uhrzeit)**

21.05.2022, 23:10
**Beobachtetes Verhalten**

Patient steht nach Einladen im RTW auf der Trage im RTW
**Erwartetes Verhalten**

Patient liegt im RTW
**Schritte um den Fehler nachvollziehen zu können**

Bewusslose , stabiliesierte Person auf die Trage legen und in den RTW einladen.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![20220521231934_1](https://user-images.githubusercontent.com/75139258/169669743-50750fb8-406b-42fb-bb7f-cb48e4ce2370.jpg)

**Comment by DrGrizzlY17** [comment]
#2438
