### ISSUE TITLE
Türen house_VinewoodHills_166 zum Außenbereich nicht passierbar. 

### ISSUE THREAD

**Issue by Xymena** [mexyn/statev_v2_issues#2457]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Anna_Luna
**Haus/Ort**

house_VinewoodHills_166

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.05.2022

**Beobachtetes Verhalten**
Im Haus lässt sich der Außenbereich nicht mehr betreten MLO besitzt nicht passierbare Türen. 

**Erwartetes Verhalten**
das durchgänge wieder passierbar sind. 

**Schritte um den Fehler nachvollziehen zu können**
Beim versuch durch die Tür zu gehen öffnet sich die zwar allerdings befindet sich noch eine zweite die sich nicht öffnen lässt

**Optional: Video / Bilder des Fehlers**

![alt_V Multiplayer 22 05 2022 02_16_59](https://user-images.githubusercontent.com/76626768/169673131-34b7ce68-ec90-4692-9c47-08552a58cc8f.png)

**Comment by DrGrizzlY17** [comment]
Das geht schon lange nicht mehr und ist auch so gewollt :)
