### ISSUE TITLE
Türen geschlossen

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#2458]
Santito Quintero

Househash: house_michaeldesanta

Siehe: https://github.com/mexyn/statev_v2_issues/issues/2457

lt. @DrGrizzlY17 geht das schon lange nicht mehr und es sei auch so gewollt. 

Allerdings ging es Monate, wenn nicht sogar Jahre und erst seit dem Altv Update vor einigen Tagen geht es nicht mehr. Zudem die Frage wieso es so gewollt ist? Andere MLOs sind ja auch nutzbar und man kann rausgehen zum Pool etc. Zudem haben wir bei unserem Haus nicht mal wirklich ein MLO, sondern es ist das "Original". Türen und Garage sind einfach doppelt vorhanden.

**Comment by DrGrizzlY17** [comment]
Dann hattet ihr Glück das es funktioniert hat. Das die Türen verschlossen und teilweise doppelt sind, ist mindestens seit V2 so. 
Das einzige Hausinterior wo man in den Garten kommt ist das Interior von Franklin wo teilweise riesige offene Wände/Fenster sind die schlecht zu verschließen sind :P 

Grund dafür, ist simple abuse Gefahr aus der Vergangenheit schon öfters passiert :)
