### ISSUE TITLE
Miete erhöht obwohl ich weiterhin eingemietet war

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#2459]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Noah Reese

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.05 - Miete 1$
10.05 - Miete 10$

**Beobachtetes Verhalten**
innerhalb des oben genannten Zeitraum's wurde die Miete erhöht ohne das ich mich aus dem Zimmer ausgemietet habe.

**Erwartetes Verhalten**
Miete kann nicht erhöht werden ohne das der Mieter das Zimmer verlässt.

**Schritte um den Fehler nachvollziehen zu können**
/

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/70150887/169992659-c66a7b9d-2e5c-414f-b2d7-107f2c02ad31.png)

![image](https://user-images.githubusercontent.com/70150887/169992690-5ddede47-0d6f-4461-9eee-27113f07f238.png)

**Comment by DonVitoDiangelo** [comment]
Müssen wir den Hartz5 Satz jetzt erhöhen, damit du über die Runden kommst? :D
Scherz beiseite, werden wir prüfen, danke.

**Comment by TheBroady** [comment]
> Müssen wir den Hartz5 Satz jetzt erhöhen, damit du über die Runden kommst? :D Scherz beiseite, werden wir prüfen, danke.

Danke dir.
Nein müsst ihr nicht, begrüße ich aber müsst ihr nicht 🗡️

Mir geht's eher um die Fehlerursache, da Mieten ja nicht erhöht werden können und niemand auf mich zugekommen ist zwecks Erhöhung. Danke fürs checken ;)

**Comment by Slayraw** [comment]
Hab bereits die Lösung wurde Adminstrativ erhöht da die blocke nun Global Investment gehört (Jedenfalls wurde mir das gesagt)

**Comment by TheBroady** [comment]
Ich glaube nicht das es Administrativ war.
Wäre ja voll der RP Killer & Sie hätten sicherlich die Mieter im Vorfeld informiert.
Sowas ist ja easy IC ausspielbar und muss nicht via Administrativer Lösung geregelt werden.

Bei Inaktiven Spielern okay. Aber ich hatte keinen Anruf, SMS oder Email worin ich über sowas informiert worden bin.

**Comment by TheBroady** [comment]
![image](https://user-images.githubusercontent.com/70150887/171612156-7313a35e-117b-4fa7-a949-b26a563b8bda.png)
nothing more to say.
ik mach hier zu.
