### ISSUE TITLE
Werkstatt - Tuning Felgen Materialanzeige fehlerhaft

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#246]
**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020/ 14:50 Uhr

**Beobachtetes Verhalten**
Felgen Tuning verbraucht keine Rohstoffe

**Erwartetes Verhalten**
Anzeige was man benötigt

**Optional: Video / Bilder des Fehlers**
https://i.imgur.com/7aKmyB4.jpg

**Comment by thumbsucker** [comment]
Vielleicht auch prüfen: 

Was ist wenn der Kunde NUR Farbe will aber keine neuen Felgen. Dann wird nichts verbraucht. Vielleicht hier noch zwei oder drei Dosen Lack zum Verbrauch hinzu fügen?

**Comment by its4l3x** [comment]
@BlackyGER Immer noch beständig der Bug?

**Comment by BlackyGER** [comment]
@its4l3x ja besteht immernoch
