### ISSUE TITLE
Herrenringe lassen lange Bärte verschwinden

### ISSUE THREAD

**Issue by theSiixx** [mexyn/statev_v2_issues#2461]
**Character Name**
Justis_Uhlich

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.05.2022 - ca. 8:30

**Beobachtetes Verhalten**
Beim ausrüsten der neuen Herrenringen werden lange Bärte invisible.

**Erwartetes Verhalten**
Lange Bärte werden nicht invisible.

**Schritte um den Fehler nachvollziehen zu können**
Character mit langem Bart rüstet ein Herrenring aus.

**Comment by SHaagmann** [comment]
Lange Bärte werden als Masken gesetzt genau wie die Ringe

**Comment by CaleighRhodes** [comment]
Guckst du hier den Beitrag von Enemya an:

https://statev.de/forum/thread/12816-vorschlag-m%C3%A4nnerb%C3%A4rte-sowie-harre/?pageNo=2#

**Comment by TheOutburst** [comment]
das was Shagmann sagt. Wir haben in GTA leider nur eine begrenzte Anzahl an Slots auf die wir Kleidung legen können, denke Fraktionisten, die Uniformen ingame erstellen können da auch ein Leidenslied von singen.
Die Bärte liegen auf den Maskenslots, so wie zB manche Copitems und eben auch die Ringe. Wir sind da leider von GTA aus beschränkt, das ist also ein Umstand mit dem wir leben müssen, solange sich kein weniger genutzer Slot findet.
