### ISSUE TITLE
Überteuerte Blitzertickets im Vergleich zum Bußgeldkatalog

### ISSUE THREAD

**Issue by MrMutantus** [mexyn/statev_v2_issues#2462]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Felix Sommer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.05.22 ca 23:15

**Beobachtetes Verhalten**
Ich bin durch die Mautstelle am Los Santos Freeway mit 154.8km/h gefahren und wurde von dem neuen Blitzer geblitzt. Hierfür wurde mir ein Ticket mit 150$ ausgestellt.

**Erwartetes Verhalten**
Das Ticket hätte laut Bußgeldkatalog nur 50$ betragen dürfen.

**Schritte um den Fehler nachvollziehen zu können**
Mit erhöhter Geschwindigkeit durch den Blitzer an der Mautstelle fahren.

**Optional: Video / Bilder des Fehlers**

![Blitzerticket](https://user-images.githubusercontent.com/23027596/170584725-670335a0-80af-4823-ac92-516a4d585e72.PNG)

**Comment by Statev-Bonsai** [comment]
Die Gebühren wurden vor kurzem geändert, wahrscheinlich ist der Bußgeldkatalog nicht überarbeitet wurden...

Die Gebühren passen jedenfalls...

**Comment by Dean-Gallagher** [comment]
Blitzer hat nichts mit Bußgeld zutun

**Comment by TheOutburst** [comment]
quasi das was Dean sagt
die Blitzertickets wurden unabhängig vom IC Bußgeldkatalog erhöht
