### ISSUE TITLE
Fahrzeug bekommt Serien Xenons bis einparken

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#2465]
Fahrzeug steht draußen, bekommt irgendwan random Xenon Serie gesetzt und diese bleiben solange bis eingeparkt

Bisher nicht hinbekommen nachzustellen woran es liegt oder wie es zustande kommt.

**Comment by SHaagmann** [comment]
Bis jetzt auch noch nicht genau gesehen woran es liegt aber gleiche verhalten bei mehreren Fahrzeugen schon beobachten können

**Comment by TeubyDE** [comment]
wurde mit #2466  gefixed
