### ISSUE TITLE
Tuning -> Fehlerhafter teile verbrauch

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#2466]
**Auftrittszeitpunkt (Datum / Uhrzeit)**
in den logs ->
Hash: carWorkshop8
Timestamp: 27.05.2022 16:40 

**Beobachtetes Verhalten**
Gemacht wurde Fahrzeugfolierung 
Verbrauch -> Fahrzeugfolierung + Xenon lichter

**Erwartetes Verhalten**
Nur Folien verbrauch

Direktes reproduzieren nicht möglich, durch tests wissen wir aber schon das Kunde NUR den Xenon verbrauch sieht 
Werkstattmitarbeiter sieht NUR den richtigen verbrauch
beides wird aber aus dem Lagerbestand verbraucht

könnte vll mit einen anderen bug zusammen hängen sprich eine bug kombi sein, konnte ich aber noch nicht testen
anderer bug: 
https://github.com/mexyn/statev_v2_issues/issues/2465
wenn Fahrzeug vll den o.g. Bug hat und man was daran tunen möchte, das so der 2. Bug getriggert wird.

Nachtrag 1:
Wir haben es halbwegs nachstellen können unzwar wirklich der eine Bug greift mit rein.
Sprich setzt es durch den anderen Bug die Xenons auf Serie und man Tunt etwas, so hat man das teil was man Tunen möchte sowie den Xenon verbrauch. 
Der Mechaniker sieht nur den richtigen verbrauch und der Kunde sieht zusätzlich den Xenon verbrauch auf der Rechnung
Tagsüber wo keine Fahrzeuglichter an sind fällt dadurch der Bug nicht auf.

Nachtrag 2:
Es gibt aber auch Fahrzeuge wo einparken nicht hilft, hier ist mal eins davon sowie die ansichten vom Mechaniker und von mir. Einparken hilft da auch nichts egal ob in Werkstatt oder Öffentlich. Dies hatten wir im verlauf gestern häufiger und icht nur bei dem Dominator GTT, ua Sugoi, Remus also wieder aus allen dlcs + base
https://pic.statev.de/i/UF23k.jpg
https://pic.statev.de/i/UFmwn.jpg

Nachtrag 3: 
Alle Fahrzeuge welche KEINE Xenons verbaut haben scheinen das problem zu haben, direkt von Fertigstellung oder Spawnen aus haben die "Xenons Serie" drauf was eig. nicht sein darf. 
Bsp Burrito :D

Nachtrag 4:
Bei Fahrzeugen wo das Tuning Disabled wurde, ist das problem nicht wie Phantom (hash: phantom)
Bei dem Phantom Custom (hash phantom3) wo Tuning eingeschalten ist, da ist das Problem auch.

**Comment by PlayInc89** [comment]
Nachtrag beim neuen LSMD BTW ist kein Tuning Möglich ohne Xenon Scheinwerfer zu verbauen sprich hast du keine Xenon Lichter im Lager kannst du nicht tunen,

**Comment by Dean-Gallagher** [comment]
Nachtrag 3 ist genau das gleiche was du meintest :P

**Comment by TeubyDE** [comment]
Problem gefunden und behoben. Beim nächsten Update fix.
