### ISSUE TITLE
Friseur Langbärte fehlerhaft

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#2467]
**Character Name**
Marvin_Elpe

**Auftrittszeitpunkt (Datum / Uhrzeit)**
28.05.2022 gegen 20 Uhr

**Beobachtetes Verhalten**
Wollte den Oberlippenbart abrasieren lassen, beim Friseur wurde dann Standard Rasur ausgewählt, es wurde aber immer ein anderer Bart (siehe Bild) angezeigt.

**Erwartetes Verhalten**
Bart kann entfernt werden

**Schritte um den Fehler nachvollziehen zu können**
Oberlippenbart haben, Standard Rasur wählen

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/i/UvDH0.jpg

**Comment by M4rvinLP** [comment]
Wird tatsächlich nur falsch angezeigt, Bart wird beim schneiden trotzdem entfernt.

**Comment by Enemyaa** [comment]
Next Update mit richtiger Vorschau!
