### ISSUE TITLE
Tattoo-Studio / Stuhl Dauerhaft Besetzt 

### ISSUE THREAD

**Issue by simplycach** [mexyn/statev_v2_issues#2468]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Ralle Kutschera

**Auftrittszeitpunkt (Datum / Uhrzeit)**

29.05.2022 / 21:10

**Beobachtetes Verhalten**

Der Stuhl an dem die Kunden sitzen und wodurch sich das Menü für die Vorlagen, Piercings, Laser öffnet ist dauerhaft besetzt ohne das jemand dran ist.

Studio: Blazing-Tattoo 
Vinewood

**Erwartetes Verhalten**

Normales auswählen der Vorlagen

**Schritte um den Fehler nachvollziehen zu können**

Mit mehren Personen versucht auf das Menü zuzugreifen.
Alle Personen haben einen Relog durchgeführt, hat auch nicht geholfen.

**Optional: Video / Bilder des Fehlers**

![20220529211120_1](https://user-images.githubusercontent.com/105867680/170888051-26c66f90-1159-4369-a304-6ab2981315b5.jpg)

**Comment by SHaagmann** [comment]
Schon nach dem Restart probiert? Haben wir beim Friseur oder in der Werkstatt manchmal wenn einer der beiden Parteien des Vorgangs crashed.

**Comment by simplycach** [comment]
Bisher noch nicht, werde ich aber gleich mal tun.

**Comment by simplycach** [comment]
Ging nach dem Restart wieder.
