### ISSUE TITLE
Epilepsie Modus zurückgesetzt ?

### ISSUE THREAD

**Issue by cadpri** [mexyn/statev_v2_issues#2469]
**Character Name**
Fabian_Picard

**Auftrittszeitpunkt (Datum / Uhrzeit)**
31.05.2022 08:02

**Beobachtetes Verhalten**
Ich habe den Epilepsie Modus immer an.
wurde dann grad eben von einem mobilen Blitzer geblitzt und habe den Schock meines Lebens bekommen.
Habe danach dann die Einstellungen kontrolliert und der Epilepsie Modus war deaktiviert.

Kann es sein, dass sich so eine Einstellung zurücksetzt ? 

**Erwartetes Verhalten**
Die Einstellungen bleiben so bestehen wie Sie sind.
Als kleiner Zusatz: wäre es vielleicht machbar beim Epilepsie Modus nicht nur den Blitz zu unterdrücken sondern auch das Geräusch ?

**Schritte um den Fehler nachvollziehen zu können**
?

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
Kein Video oder Bild vorhanden

**Comment by TeubyDE** [comment]
Is das einmalig oder passiert das ständig?

**Comment by cadpri** [comment]
Ich werde so oft nicht geblitzt um das zu beantworten.
Ich werde ab jetzt nach jedem Einloggen mal F7 im Auge halten und berichten

**Comment by cadpri** [comment]
ich hab das jetzt jeden Tag kontrolliert und bisher ist es nicht wieder deaktiviert gewesen

**Comment by TeubyDE** [comment]
Danke für die Info. Würde ich so erst mal zu machen.
