### ISSUE TITLE
Blista hohe Beschleunigung/Topspeed

### ISSUE THREAD

**Issue by MrMutantus** [mexyn/statev_v2_issues#247]
**Character Name**

Felix Sommer

**Zeitpunkt (Datum / Uhrzeit)**

20.11.2020 gegen 14:30

**Beobachtetes Verhalten**

Der Blista(Golf 7 replacement) hat eine extreme Beschleunigung und ich habe eine Höchstgeschwindigkeit von 230kmh+ erreicht.
Verhalten sowohl nach Haus betreten sowie relog aufgetreten.

**Erwartetes Verhalten**

Erwartet habe ich eine deutlich langsamere Beschleunigung und um die 170kmh Topspeed erwartet

**Schritte um den Fehler nachvollziehen zu können**

Auto anmachen und losfahren.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/ZkBqHSKU5io

**Comment by DonVitoDiangelo** [comment]
fixed next update
