### ISSUE TITLE
Verschiedene Werkstatt Menüs

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#2471]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

Ryan Valdes & Marcus Folk

**Auftrittszeitpunkt (Datum / Uhrzeit)**

01.06.2022 12:30Uhr
**Beobachtetes Verhalten**

Marcus hat beim Tuning bei der Banshee 2 Tuning Optionen mehr !
**Erwartetes Verhalten**

Keine Option um einen Turbo einzubauen siehe Bilder
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

Tuning Menü Ryan 
![unknown (4)](https://user-images.githubusercontent.com/70231715/171386763-b4a77c75-8eb8-42d5-ab77-4d4bf24767fe.png)

Tuning Menü Marcus
![unknown (5)](https://user-images.githubusercontent.com/70231715/171386815-1564c236-55db-43fa-bbfd-95322f40968e.png)

**Comment by Dean-Gallagher** [comment]
kofferraum auch rigged 
https://prnt.sc/QKDR5kuObxHY

**Comment by DonVitoDiangelo** [comment]
tritt bei der banshee auf, next updatefixed
