### ISSUE TITLE
Kaputte [M] Schwarze Rebel Skinny Jeans

### ISSUE THREAD

**Issue by Beartox** [mexyn/statev_v2_issues#2472]
**Character Name**
Tobias_Schlueter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
04.06.2022 / 20:35

**Beobachtetes Verhalten**
Texturen die wohl an der Kleidung nicht sein sollte

**Erwartetes Verhalten**
das die Texture richtig da stellt wird

**Schritte um den Fehler nachvollziehen zu können**
[M] Schwarze Rebel Skinny Jeans anziehen und man sieht hinten texturen die da wohl nicht sein sollten.

**Optional: Video / Bilder des Fehlers**
![79544cf6d875892b172c4ad699e90086](https://user-images.githubusercontent.com/79170045/172021172-3b40920a-dec0-4cfa-b942-7e029cee127b.png)
![GTA5 2022-06-04 20-19-58_1](https://user-images.githubusercontent.com/79170045/172021263-bc72c6f1-624e-4e33-8145-9ac54bac4634.png)

**Comment by Enemyaa** [comment]
Liegt am mod. Sollte man eher mit Boots tragen.
