### ISSUE TITLE
Buffalo STX Kein NOS verbau möglich

### ISSUE THREAD

**Issue by powerswissi** [mexyn/statev_v2_issues#2474]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Roger Thickle

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Sonntag 5 Juni 2022

**Beobachtetes Verhalten**

Ich wollte eine NOS Flasche verbauen doch Leider ist dies nicht möglich . 

**Fehlermeldung: An diesem Fahrzeug kann kein Nitro verwendet werden**

Laut Changelog vom 26.11.2021 V2.2.1 sollte dies aber möglich sein 

**Erwartetes Verhalten**

Das Nitro in diesem Auto auch funktioniert wie bei ALLEN anderen Muscle Cars. 

**Schritte um den Fehler nachvollziehen zu können**

STX Spawnen 
Nitro Flasche ins Inventar
Versuchen zu verbauen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://cdn.discordapp.com/attachments/931868040784670791/982908397374562304/20220605092638_1.jpg

**Comment by DonVitoDiangelo** [comment]
next update
