### ISSUE TITLE
Garage anbauen

### ISSUE THREAD

**Issue by Looper-L** [mexyn/statev_v2_issues#2475]
Allgemein eine Frage, könnte man bei dem Haus eine Garage anbauen, da mir mitgeteilt wurde das sowas möglich sei. Da ebenfalls auch im Menü vom Haus ein "Garagen" Fenster existiert.

- Am besten selber mal ein Bild machen, bei Gelegenheit: PLZ 826, SandyShores32.

![1](https://user-images.githubusercontent.com/103857358/172068774-cf15aa1f-32d0-48f2-a5ca-07c49a9ad2f6.png)

**Comment by Enemyaa** [comment]
Hi,
das UI ist immer das selbe. Aber für Wohntrailer stehen keine Garagen zur Verfügung.
