### ISSUE TITLE
XENON Lichter zurückgesetzt

### ISSUE THREAD

**Issue by Michi993** [mexyn/statev_v2_issues#2477]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Luke Hammer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
09.06.2022 - 20:00

**Beobachtetes Verhalten**
Fahrzeug mit Orangenen Xenons abgestellt, im Casino für ca. 1h verweilt, beim rauskommen sind die Xenon Lichter Blau (Standard) ( ein und ausparken behebt dieses Problem nicht)

**Erwartetes Verhalten**
Xenons behalten die gleiche Farbe

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug evtl. ein bisschen unbeaufsichtigt stehen lassen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Michi993** [comment]
*add nach 2-3 mal ein- ausparken sind sie wieder in richtiger farbe, ist glaube ja nh alt:v fehler

**Comment by SHaagmann** [comment]
Duplikat von #2465
