### ISSUE TITLE
Hotel umbau

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#2478]
**Firma Hash**
JunDelPerroRew_Flat_4_4_4_4

Hallo, unzwar würden wir gern ein klein umbau bekommen an unseren Hotel. 

1. Wir möchten gern den gelben Poller entfernen lassen damit wir die Tiefgarage nutzen können wie für Veranstaltungen usw. 
https://pic.statev.de/i/UMWmc.jpg
Der Poller blockiert das Tor am hochgehen. 

2. würden wir gern den Teleporter für die Dachterasse von so einen Wartungsschacht eingang in die Hotellobby verlegen lassen. 
Sieht halt einfach besser aus und ist auch besser erreichbar. 

im 1. Bild in Orange etwas mehr nach links der aktuell eingang zum Hotel und der rote Pfeil ist der aktuelle Dachmarker. 
im 2. und 3. Bild ist der Eingang zum Hotel. Man kann die Türfen zum Aufzug öffnen. 

1. https://pic.statev.de/i/UMsr2.jpg
2. https://pic.statev.de/i/UMhgu.jpg
3. https://pic.statev.de/i/UMoDy.jpg

Vielen dank

**Comment by CaleighRhodes** [comment]
Ich hab selber mal in dem Hotel gewohnt, den Poller hat da jemand hingestellt. Die Garage war immer benutzbar. Schwieriger ist, dass in der Garage zwei ziemlich fiese unsichtbare Hitboxen sind - damit hat man nicht so die Freude.

**Comment by Dean-Gallagher** [comment]
wir waren heut beim PD und Reagan meinte der Poller ist "einbetoniert" weil er selbst den schonmal weg machen wollte.

**Comment by cadpri** [comment]
Das mit dem Poller wird den Hintergrund RageMP und AltV haben. In der AltV Map sind viele Gegenstände auf der Karte dazu gekommen die in der RageMP nicht drin waren.

**Comment by TheOutburst** [comment]
Den Poller wegmachen lässt sich einrichten, nur ist die Garage wie auch andere Garagen nicht ganz bugfrei. Unsichtbare Wand, Balken & Leitplanken durch die man laufen kann.
Ich hab den Poller mal weggenommen, kommt es da zu abuse oder Problemen ist die Garage wieder zu.

Den Portmarker verschieben wird tricky. An den Aufzug kommt der nicht wenn man vorne ins Hotel rein kommt, ich würde da eher den Hotelmarker dran machen wollen. Andere Türen wo der Marker dran kann gibt es zwar, aber die sind nicht wirklich besser gelegen als da wo der jetzt ist. Ich könnte höchstens das Häuschen vorne anbieten, oder hast du einen anderen Vorschlag? @Dean-Gallagher 
https://i.imgur.com/3QCEfa3.jpeg

**Comment by Dean-Gallagher** [comment]
@TheOutburst Du Erwin, mach ruhig so, sieht top aus so :)
