### ISSUE TITLE
Werkstatt kein Service und kein Reifenwechsel möglich

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#2479]
Moinsen, 

Mechaniker kann Kunden Rechnung ausstellen, Rechnung kommt aber nicht beim Kunden an. 
Danach ist Werkstatt Rigged bis Client neustart vom Mechaniker. 

Betroffen sind Reifenwechsel (Sommer <-> Winter usw)
Service (egal welches Teil) 
Fahrzeug spielt auch keine Rolle, getestet mit verschiedenen. 

F8 Consolen haben keine Fehler bei beiden:

grüße

**Comment by TeubyDE** [comment]
fix. ab dem nächsten Update wieder möglich.
