### ISSUE TITLE
Funkgerät UI blockiert Tablet UI

### ISSUE THREAD

**Issue by Shirobaka** [mexyn/statev_v2_issues#248]
**Character Name**
Shigekuni_Yamamoto

**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020 - 15:18

**Beobachtetes Verhalten**
Sofern ein Funkgerät "ausgerüstet" ist, befindet sich dieses auch bei geöffnetem Tablet im Vordergrund und verdeckt somit die linke untere Ecke des Tablets, dadurch lässt sich der Immobilien Tab im StateCom nur noch schwierig ausklappen, dahinter befindliche Immobilien lassen sich garnicht mehr ausklappen.

**Erwartetes Verhalten**
Das Funkgerät sollte hinter dem Tablet UI sein, nicht davor, nur so ist eine einwandfreie verwendung des Tablets möglich.

**Schritte um den Fehler nachvollziehen zu können**
Funkgerät ausgerüstet haben -> Tablet öffnen -> StateNet öffnen -> Immobilientab unten Links verdeckt

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
![3TflgdF](https://user-images.githubusercontent.com/8634317/99810218-b5eddd00-2b43-11eb-9685-a16620ccfe17.jpg)

**Comment by KingMarcel** [comment]
Doppelpost
https://github.com/mexyn/statev_v2_issues/issues/226
