### ISSUE TITLE
Sichtbarkeitsbug von Ketten und Ohrringen

### ISSUE THREAD

**Issue by StellaExiguus** [mexyn/statev_v2_issues#2481]
**Charaktername**
Natascha_Sokolov

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.05.2022 / 00:48

**Beobachtetes Verhalten**
Wenn man _[F][Ears] Silber Creolen_ und die _[F] Silberne Majesty Halskette_ kombiniert, ist nur das, was man als letztes angelegt hat, sichtbar.

**Erwartetes Verhalten**
Das sowohl Ohrringe als auch Kette sichtbar sind.

**Schritte um den Fehler nachvollziehen zu können**
Sowohl Kette als auch Ohrringe im Kleidungsmenü anlegen.

**Comment by CaleighRhodes** [comment]
Ist bekannt und kann nicht geändert werden #687

**Comment by Enemyaa** [comment]
Ist kein Bug, sondern der selbe Slot. Das betrifft NUR die Ohrringe.
