### ISSUE TITLE
Straßenlaterne entfernen

### ISSUE THREAD

**Issue by PaxPaxton** [mexyn/statev_v2_issues#2483]
**Klamottenladen Hash**
Ponsenbys1

Guten Tag, wäre es evtl möglich diese Straßenlaterne zu entfernen? (wegen Platzmangel)

![laterne](https://user-images.githubusercontent.com/107564967/173865566-890ad7ca-ee8e-4b7a-aec2-847dbd6c68e5.png)

**Comment by Dean-Gallagher** [comment]
Die hitbox würde bleiben, Sprich nur optisch wäre sie weg aber die Hitbox wo man dagegen laufen/fahren kann würde bleiben, also kein Platzgewinn.

**Comment by PaxPaxton** [comment]
Ok schade, dachte das funktioniert....
