### ISSUE TITLE
Schwebender Abgabepunkt 

### ISSUE THREAD

**Issue by XxDonnieDarkoxX** [mexyn/statev_v2_issues#2484]
**Charakter Name**
Tyrone Murphy

**Auftrittszeitpunkt (Datum / Uhrzeit)**
15.06.2022 - 13:47 Uhr

**Beobachtetes Verhalten**
Ein Abgabepunkt, bei einer 40er Kokslieferung schwebt in der Luft:

![Koks](https://user-images.githubusercontent.com/107570784/173876416-7583684b-be75-44c1-9f2c-c342c5f29103.JPG)

![Koks Bug](https://user-images.githubusercontent.com/107570784/173876480-01e90995-148c-49fb-9994-bd6afaae9078.JPG)

![Koks Bug 3](https://user-images.githubusercontent.com/107570784/173876513-656a9c4e-ef73-477a-940d-0a1088790f0e.JPG)

Lässt sich nur so erledigen:
![Koks Bug 4](https://user-images.githubusercontent.com/107570784/173876534-76523276-e5fa-4829-bc42-cd648fb2994b.JPG)

**Comment by TheOutburst** [comment]
das nicht gut. Fixed next update
