### ISSUE TITLE
Versetzung des Abladepunktes und evtl. Entfernung eines Objektes.

### ISSUE THREAD

**Issue by AlecNova** [mexyn/statev_v2_issues#2485]
Hallo zusammen,

hiermit stelle ich die Anfrage um die Versetzung des Abladepunktes an dem unten angezeigtem Gebäude. Es gab öfters Probleme IC mit Lieferanten, besonders die mit Achse unterwegs waren. Die Frage ist, ob die Versetzung möglich wäre? (siehe angehängte Bilder)

https://i.gyazo.com/8ebdbacaf79c3a1b20b7f95c4b37175c.jpg so ist er momentan.

Und dort wäre genug Platz für einen Abladepunkt. https://i.gyazo.com/6dbfe70c8aa1ffd22096ffbb8e06a7df.jpg

Des Weiteren besteht die Nachfrage, ob es möglich ist einen festen Hotdog Stand zu entfernen? → https://i.gyazo.com/1db058a55e4ca17e295a4e8dd90960c1.jpg

Wäre nett und wünschenswert, aber wenn es nicht geht, muss ich leider mit leben.

Unternehmenssitz | Hawick Ave. 2155 |  

Hash | pfHawick1

![ladepunkt1](https://user-images.githubusercontent.com/96883949/173916292-94e2404d-c3c2-4465-a3b5-afb4a83abbb5.jpg)
![ladepunkt2](https://user-images.githubusercontent.com/96883949/173916295-3252bbc4-5a38-4300-bb77-64b66b8c6819.jpg)
![objekt](https://user-images.githubusercontent.com/96883949/173916304-d873c01d-6089-4626-acde-7e66fd2933a3.jpg)

**Comment by AlecNova** [comment]
https://www.youtube.com/watch?v=9DAe4CV-Avw als Video nochmal hinzugefügt.

**Comment by TheOutburst** [comment]
Hellole
Abladepunkt hab ich ans Ende von den Parkplätzen versetzt, der jetztige ist ja nicht einmal mehr in Schreireichweite.
Den Hotdogstand finde ich pers. zu schade um den zu löschen, der ist glücklicherweise von einem Addonmapping, deswegen konnte ich den 3m nach rechts verschieben.

**Comment by AlecNova** [comment]
Herzlichen Dank für die Bearbeitung. Das mit dem HotDog Stand ist dann ja auch eine gute Lösung. Zumal ich sonst auch einen herstellen könnte.
