### ISSUE TITLE
Eventuelle säuberung hinter meiner Raffenerie

### ISSUE THREAD

**Issue by Nemoshelby** [mexyn/statev_v2_issues#2488]
Hey,
Ich wollte mal nachfrage ob es möglich wäre denn platz denn ihr auf denn Bildern seht zu cleanen so das man da zwischen parken kann bzw wollte ich da eine kleine rp ecke bauen für dann spätere Mitarbeite wo man dann vlt eine kleine sitzt ecke und einen Grill hinstellen könnte. Oder halt wie gesagt zum ziwschen parken für das privat fahrzeug.

Dann die andere frage ob ihr eventuell ein elektro Tor einfügen könntet oder das Tor einfach entfernen damit man ohne probleme auf denn Platz fahren kann ohne das man sein Auto/MTL Beschädigkt.

Mit Freundlichen Grüßen

Nemo Shleby

![20220622134352_1](https://user-images.githubusercontent.com/108000710/175024055-49b84c91-f9a3-4be4-90b7-ab9f2cd03a0f.jpg)
![20220622133641_1](https://user-images.githubusercontent.com/108000710/175024069-d1d35228-598d-4d60-b7d1-99f88d31f704.jpg)
![20220622133655_1](https://user-images.githubusercontent.com/108000710/175024091-1029147e-8a49-4801-95ec-8fc419c20e48.jpg)

**Comment by TheOutburst** [comment]
Das Tor, der kleine Schrottcontainer rechts und die zwei carwrecks sind restlos verschwunden, ich denke das sollte genug Raum für RP bieten

**Comment by Nemoshelby** [comment]
Hey danke das ihr das so schnell bearbeitet habt. war heute kurz ic und wollte mein wagen parken aber leider ist es noch nicht erledigt. es sieht leider immer noch so aus wie auf denn bildern. 


Daher wollte ich mal wissen ob das in einem Patch kommt oder ob der server die änderung nicht angenommen hat.

Mit Freundlichen Grüßen
Nemo Shelby

**Comment by TheOutburst** [comment]
Wir fahren nur alle paar Wochen, nicht täglich oä. Sobald es einen Changelog gibt und/oder du beim connecten was runterlädst kannst du davon ausgehen, dass die Änderung hier auf dem Live Server ist.
