### ISSUE TITLE
Extreme FPS Einbrüche

### ISSUE THREAD

**Issue by BlackyGER** [mexyn/statev_v2_issues#249]
**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020 / 13:10 etwa

**Beobachtetes Verhalten**
extreme fps einbrüche ums mission row auch auf große distanz wenn man da nur hinsieht

**Optional: Video / Bilder des Fehlers**

https://youtu.be/fVhQqKQ740o 
oben rechts in grün sin die FPS

Meine GTA Settings 
https://i.imgur.com/KaT4AtR.jpg
https://i.imgur.com/TRrtPiK.jpg
https://i.imgur.com/t9C0XjV.jpg

Mein Rig: 
CPU: Ryzen 2700x
MB: asus rog strix x470-f 
Ram: 16GB G-Skill DDR4 Ram @3200mhz 
M2 SSD: 500 GB Samsung Evo 960
Graka: RX 5700 XT

**Comment by DonVitoDiangelo** [comment]
Ist vorerst so, teils auch abhängig vom Rechner, + Last an Spieler und Fahrzeuge.
