### ISSUE TITLE
Verschiebung des Be- und Entladepunkt an einer Firma

### ISSUE THREAD

**Issue by CatherineGallagher** [mexyn/statev_v2_issues#2490]
Hey,
Es wäre angenehmer den Punkt etwas mehr richtung Straße auf den Standstreifen zu verlegen (siehe Bild 2)
Damit man besser mit einem Phantom dahin kommt, vielen dank.

Name: Catherine Gallagher
Hash: cypressflats5
Orchardvile Ave. 5 

**Optional: Video / Bilder des Fehlers**
Bild 1: https://pic.statev.de/i/dKvsT.jpg
Bild 2: https://pic.statev.de/i/dKs6R.jpg

**Comment by TheOutburst** [comment]
Punkt verschoben, nicht ganz so weit wie du aufm Bild stehst aber weit genug um mit der Achse entspannt zu parken
