### ISSUE TITLE
Bitte zwei Tickets wieder aufmachen :)

### ISSUE THREAD

**Issue by Erumeldor** [mexyn/statev_v2_issues#2492]
Ich denke alte Tickets die man kommentiert werden nicht nochmal im System als neu auftauchen.

Daher hier zwei alte Tickets die immer noch so sind wie im Ticket beschrieben und wieder geöffnet werden sollten:
https://github.com/mexyn/statev_v2_issues/issues/2374
https://github.com/mexyn/statev_v2_issues/issues/1863

Das Ticket hier kann natürlich sofort weg ;)
Grüße!

**Comment by TheOutburst** [comment]
Habs geöffnet, bitte Rückfrage im Casino Ticket beantworten
