### ISSUE TITLE
Verladepunkt versetzen

### ISSUE THREAD

**Issue by SimonPfeifferStateV** [mexyn/statev_v2_issues#2493]
IC Name: Simon_Pfeiffer

Firmenhash: pfDownVine20 & pfDownVine21

Könnt ihr bitte die Verladepunkte der beiden Firmen zusammensetzen auf folgende Position: https://pic.statev.de/image/option-1.dlf2m

Sollte das nicht gehen, gerne nur den Verladepunkt von pfDownVine20 auf die Straße versetzen (siehe: https://pic.statev.de/image/option-2.dlqMI).

Danke euch schonmal!

**Comment by TheOutburst** [comment]
beide Verladepunkte wurden an der Stelle zusammengefügt
