### ISSUE TITLE
Bei Gebäude 4021, kann durch die Wand gegangen werden.

### ISSUE THREAD

**Issue by Cashiflux** [mexyn/statev_v2_issues#2497]
**Name**
Frank Kruger

**Auftrittszeitpunkt (Datum / Uhrzeit)**
29.06.2022 1545

**Beobachtetes Verhalten**
Mann kann durch die Wände des Gebäudes laufen.

**Erwartetes Verhalten**
Wann verhindert das durchlaufen.

**Schritte um den Fehler nachvollziehen zu können**
Man stelle sich vor das gebäude und geht einfach durch die wand.

**Optional: Video / Bilder des Fehlers**
![Fehler](https://user-images.githubusercontent.com/87946928/176452486-b69b7fc5-17c3-4c1b-b318-49ad29d78b83.jpg)

**Comment by Dean-Gallagher** [comment]
Duplikat https://github.com/mexyn/statev_v2_issues/issues/1298
