### ISSUE TITLE
Fahrzeugschlüssel Gebühr wird weiterhin abgebucht obwohl man den kostenpflichtigen Schlüssel entfernt hat

### ISSUE THREAD

**Issue by TheMoonicorn** [mexyn/statev_v2_issues#2499]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**

Freya Michaels

**Auftrittszeitpunkt (Datum / Uhrzeit)**

ab 30.06. um 20:54

**Beobachtetes Verhalten**

Habe gestern Abend jemand einen kostenpflichtigen Schlüssel weggenommen für den ich 150 Dollar zahlen musste,
dennoch wurden weiterhin diese 3 Dollar abgebucht obwohl der kostenpflichtige Schlüssel entfernt wurde

**Erwartetes Verhalten**

Sobald der kostenpflichtige Schlüssel gelöscht wird, dass nichts mehr abgebucht wird

**Schritte um den Fehler nachvollziehen zu können**

Schlüssel vergeben bis man für einen Schlüssel zahlen muss,
abwarten bis die stündliche Gebühr abgebucht wird,
Andere Leute, wofür man nichts zahlt, löschen
Den Kostenpflichtigen Schlüssel zu einem normalen machen
Und aufs Konto achten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by SHaagmann** [comment]
Du Zahlst nicht für Schlüssel die du vergeben hast sondern die du bekommen hast
