### ISSUE TITLE
UI Waffenladen

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#25]
**Zeitpunkt (Datum / Uhrzeit)**
25.08.2020 20:00

**Beobachtetes Verhalten**
![Screenshot_2](https://user-images.githubusercontent.com/63787507/91210997-57fd5500-e70e-11ea-8619-935da98f0dab.png)

**Erwartetes Verhalten**
Feld zu klein um Wert anzuzeigen.

**Comment by tastydev** [comment]
duplicate of #14
