### ISSUE TITLE
Hotels - Mieter sowie automatischer rauswurf - Mietfrei

### ISSUE THREAD

**Issue by ZacCooperr** [mexyn/statev_v2_issues#250]
**Charaktername**
 Zac_Cooper

**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020 / 12:58Uhr

**Beobachtetes Verhalten**
Hauptkonto war im Minusbereich durch eine Überweisung(2% Steuern). Durch Grundsicherung wurden alle gemietete Wohnungen nicht bezahlt und somit gab es den Rauswurf als Meldung. Am Hotel angekommen war ich trotzdem noch in den Wohnungen als Mieter eingemietet. Laut Statenet waren aber die Wohnungen frei zur Verfügung. Nach Preisänderung an den vermeintlichen freien Wohnungen bin ich wieder Besitzer der Wohnung geworden ohne erneut mich einzumieten. Seitdem muss ich aber auch keine Miete mehr Stündlich zahlen.

**Erwartetes Verhalten**
Rauswurf aus den gemieteten Wohnungen und keine automatische wiedereinstellung durch eine Preisänderung über das Statenet. Des Weiteren das die Miete Stündlich wieder korrekt abgezogen wird.

**Schritte um den Fehler nachvollziehen zu können**
1. gemietete Zimmer/Wohnungen besitzen.
2. Konto leermachen, durch die 2% Regelung ist man automatisch im Minusbereich.
3. Warten auf Grundsicherung und man erhält die Meldung, dass man gemietete Zimmer verliert.
4. Zur Wohnung fahren und sehen, dass diese immernoch begehbar ist.
5. Über das Statenet eine Preisänderung am Zimmer vornehmen.
6. der rausgeworfene Mieter ist automatisch wieder eingemietet
7. Mieter muss seitdem keine Miete mehr stündlich zahlen

**Optional: Video / Bilder des Fehlers**
Falls du ein Video oder Bild vom Fehler gemacht hast, dann kannst du diesen hier einfügen. Dies geht ganz einfach per Drag & Drop:
![Hotelzimmer](https://user-images.githubusercontent.com/74767269/99811044-e6824680-2b44-11eb-95f2-65333bf95b01.JPG)
![Grundsicherung](https://user-images.githubusercontent.com/74767269/99811064-ed10be00-2b44-11eb-970e-0f9980dc0581.JPG)

**Comment by ZacCooperr** [comment]
Nachdem eine Wohnung manuell noch einmal gekündigt worden sowie im Anschluss wieder gemietet worden ist, werden alle Mieten wieder korrekt abgezogen.

**Comment by MarcelMuerto** [comment]
StateNet Problem mit dem Minus gehen behoben!
