### ISSUE TITLE
Golfspielen ab dem zweiten Loch nicht mehr möglich

### ISSUE THREAD

**Issue by badshah23** [mexyn/statev_v2_issues#2500]
**Character Name**
Yuri_Greene

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit ca. 15.06.22

**Beobachtetes Verhalten**
Es stehen schon Flaggen in den ersten Löchern.
Wenn man nachdem man das erste Loch gespielt hat und den Ball wieder aufgenommen hat, versucht das Loch 2 zu spielen und den Ball ablegt und dann zum Schläger greift, verschwindet der Ball und man kann kein Inventar oä mehr öffnen und muss reloggen. Das Problem gab es schhon einmal, dort lag es an den Flaggen die noch gesetzt waren und den Fehler verursacht hatten.

**Erwartetes Verhalten**
Man sollte normal weiterspielen können oder relogg.

**Schritte um den Fehler nachvollziehen zu können**
Auf dem Golfplatz im ersten Loch den Ball einlochen und wieder aufnehmen. dann Ball wieder neu platzieren und versuchen diesen zu spielen.

**Comment by TheOutburst** [comment]
Fixed mit letztem Update
