### ISSUE TITLE
LOCS Brillengläser / Charakterveränderung

### ISSUE THREAD

**Issue by DR-Nox** [mexyn/statev_v2_issues#2503]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Forum!
```

**Character Name**
Callan_Murphy

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.07.2022 / ca. 19.30Uhr

**Beobachtetes Verhalten**
Beim tragen der LOCS "Southside" Brille Clippen die Texturen der Gläser,
des weiteren wurde das Aussehen des Characters verändert. Siehe Video.

**Erwartetes Verhalten**
Brillengläser sollten normal schwarz sein, Gesichtsform und Aussehen sollten sich nicht ändern.

**Schritte um den Fehler nachvollziehen zu können**
Tragen der Locs "Southside" Brille, Kamera bewegen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
--

**Optional: Video / Bilder des Fehlers**
https://clips.twitch.tv/CrazyFineSpaghettiTBTacoLeft-gltCI9xpb7c4JfUI?tt_content=url&tt_medium=clips_api

**Comment by Dean-Gallagher** [comment]
Dein gesicht ist das sogenannte Titoface 
https://github.com/mexyn/statev_v2_issues/issues/2171

**Comment by DR-Nox** [comment]
okay, is mir dann bisher nur nie aufgefallen, dann bleibt nur noch das Problem mit den Brillengläsern, das hat man auch wenn man nicht High ist
