### ISSUE TITLE
Collision von Patienten auf MD Trage

### ISSUE THREAD

**Issue by quotenben** [mexyn/statev_v2_issues#2509]
**Character Name**
Ben_Hawking

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11.07.2022 irgendwann Abends

**Beobachtetes Verhalten**
Patienten auf Tragen haben eine Collision, was dazu führt, dass man nicht nah genug an das Fahrzeug kommt, um über das X-Menü den Patienten einzuladen.

**Erwartetes Verhalten**
Patienten auf der Trage sollten keine Collision wie die Trage selbst haben.

**Schritte um den Fehler nachvollziehen zu können**
Normalerweise war das Ganze vorher nur bei Patienten welche bereits laufen konnten zu beobachten. Im unten aufgeführten Video allerdings war die Person nur stabilisiert. Das Ganze war auch für alle anderen ersichtlich und nicht wie in #2494 .

**Optional: Video / Bilder des Fehlers**
https://youtu.be/1gPeuYVi2k0

**Comment by TeubyDE** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2494
