### ISSUE TITLE
Entfernte Kleidung nicht ausziehbar

### ISSUE THREAD

**Issue by AngelMaravilla** [mexyn/statev_v2_issues#251]
**Character Name**
Angel Maravilla

**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020 / 11:00 Uhr

**Beobachtetes Verhalten**
Beim Login war erkenntlich, dass das Kleidungs-item maletop113210 nicht mehr existiert. Im Kleidungsmenü wurde es jedoch noch als 'angezogen' angezeigt. Es konnte per Rechtklick nicht entfern werden und meldete folgenden Fehler:
_Itemconfig not found for maletop113210_

Ein anderes Oberteil (schwarzer Sweater) wurde testweise in den Slot gezogen, wodurch zwei Oberteil-Icons übereinander im Kleidungsmenü sind. Rechtsklick auf das obere Icon löst weiterhin die beschriebene Fehlermeldung aus, Rechtsklick auf das untere hat keinen Effekt.
(Siehe Bild)

**Erwartetes Verhalten**
Kleidungsstücke die entfernt wurden sollten zumindest ausziehbar/entfernbar sein.

**Schritte um den Fehler nachvollziehen zu können**
Ein vorhandenes Kleidungsstück und die dazugehörige Itemconfig entfernen und dann versuchen es im Kleidungsmenü auszuziehen. Ein weiteres Kleidungsstück auf den bereits belegten Slot ziehen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot_1](https://user-images.githubusercontent.com/74780492/99812698-129ec700-2b47-11eb-984f-b0e0b779610e.png)
![Screenshot_2](https://user-images.githubusercontent.com/74780492/99812716-16324e00-2b47-11eb-8c3a-90f5c3aa9ed4.png)

**Comment by r3sist3nt** [comment]
Nach dem Restart im 18 Uhr behoben.
