### ISSUE TITLE
Brecheisen nach Ausrüsten als Waffe nicht mehr für Hauseinbrüche benutzbar

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#2511]
**Character Name**
Jaden_Pole

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Sobald man ein Brecheisen als Waffe ausrüstet, kann man dieses nach Abrüstung nicht mehr für Hauseinbrüche nutzen

**Erwartetes Verhalten**
Man sollte das Brecheisen dennoch für Hauseinbrüche nutzen können.

**Schritte um den Fehler nachvollziehen zu können**
- Brecheisen als Waffe ausrüsten
- Brecheisen wieder abrüsten und versuchen damit in ein Haus einzubrechen.

**Comment by TeubyDE** [comment]
@Humperrrt  Die Brechstange muss sich technisch im Inventar befinden. Wenn die Brechstange ausgerüstet ist, ist diese nicht mehr im Inventar.

**Comment by Humperrrt** [comment]
Wie gesagt, nach Abrüstung (Also nachdem man es nicht mehr als Waffe hat sondern wieder im Inventar) geht es mit dem brecheisen nicht mehr.
