### ISSUE TITLE
Munitions Bug

### ISSUE THREAD

**Issue by Nightdelta77** [mexyn/statev_v2_issues#2515]
**Character Name**

Ethan Willis

**Auftrittszeitpunkt (Datum / Uhrzeit)**

21.07.22 21:53 Uhr

**Beobachtetes Verhalten**

Man kann weder bei der Barett, noch der EMR die Waffen laden.
Sobald man das passende Magazin auf die Waffe zieht, gibts ein Pop-Up Text (siehe Video).

**Erwartetes Verhalten**

Man sollte beide Waffen ganz normal mit der Munition laden können.

**Schritte um den Fehler nachvollziehen zu können**

Barett oder EMR ausrüsten, Magazin auf die Waffe ziehen.

**Optional: Video / Bilder des Fehlers**

https://youtu.be/SpF6F3zxJU4

**Comment by DonVitoDiangelo** [comment]
Hi,

für Scharfschützengewehre wird es künftig gänzlich nicht mehr möglich sein Munition zu laden.
Bedanken könnt Ihr euch dafür bei Spielern, die damit nicht umgehen können.
Wir müssen daraus Konsequenzen ziehen, so leid es uns tut. Tut dem RP ja aber kein Abbruch. :)

MFG DonVito
