### ISSUE TITLE
Auftragsexporte nicht möglich

### ISSUE THREAD

**Issue by NLTrance** [mexyn/statev_v2_issues#252]
//Erweiterung zu: https://github.com/mexyn/statev_v2_issues/issues/223 (Dort ist nur die Rede von Resourcenexport)

**Character Name**
Eric Ahr

**Zeitpunkt (Datum / Uhrzeit)**
15:00

**Beobachtetes Verhalten**
Aufträge können nicht abgegeben werden. Von der eigenen Firma, als auch von der von Freunden.

**Erwartetes Verhalten**
/

**Schritte um den Fehler nachvollziehen zu können**
/

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
/

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=hJue4xDZiDY

**Comment by DrGrizzlY17** [comment]
Schon vorhanden. Das nächste mal vorher gucken bitte
