### ISSUE TITLE
[MASTER-TICKET] Hud verschiebt sich (Tab drücken)(Funkkanaäle)

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#253]
**Character Name**

Erwin_Dulach

**Zeitpunkt (Datum / Uhrzeit)**

15:45, aber seit mehreren Stunden öfters
**Beobachtetes Verhalten**

Das StateV Overlay verschiebt sich nach oben

**Erwartetes Verhalten**

Nix
**Schritte um den Fehler nachvollziehen zu können**

Wenn man TAB (Waffenrad) + W drückt verschiebt sich das gesamte StateV Overlay. Gta HUD nicht betroffen. Mit nem Funkgerät lässts sich kurz wieder "richtig" schieben". Nur nen Restart fixt es.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

1920 x 1080
rumstehen -> TAB + W gleichzeitig drücken, unglücklich sein

**Optional: Video / Bilder des Fehlers**

https://pic.statev.de/image/AtAr2
https://pic.statev.de/image/AtNDy
https://pic.statev.de/image/At2GA
https://pic.statev.de/image/Atbgu

**Comment by TheOutburst** [comment]
Ich glaube Tab länger drücken reicht aus.
Und das hat irgenwie auch nix mitm Waffenrad zu tun, wenn ich alle Tab Einstellungen in den GTA Settings auf was anderes lege kommts trotzdem auf.
Achja, und bei mir immer reproduzierbar.

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/317

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/344

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/386

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/560

**Comment by DrGrizzlY17** [comment]
Ich weiß nicht ob dir Ursache bekannt ist, aber ich schreib es einfach mal drunter.
Der Fehler passiert wenn man so viele Funkfrequenzen eingespeichert hat, das man im UI nach unten scrollen müsste.
(Bei 1080p tritt das somit ein, wenn man 4 oder mehr Frequenzen hat. Beim öffnen der UI vom Funk sieht man erst 3 und
durch das scrollen werden die nächsten sichtbar)

Tab drücken verrutscht die UI dann noch oben.
Löscht man die 4te wieder raus, tritt es nicht mehr auf

**Comment by its4l3x** [comment]
Fixed next update
