### ISSUE TITLE
Produktion : Handwerker keine Fortschritte

### ISSUE THREAD

**Issue by Lube08** [mexyn/statev_v2_issues#254]
**Luke Long**

**Zeitpunkt (Datum / Uhrzeit)**

20.11.2020 16:34
**Beobachtetes Verhalten**

Balken von Handwerker Produktionsskill macht keine Fortschritte nach Produktionen in der Verpackungsfabrik
**Erwartetes Verhalten**

Balken sollte steigen? 
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Lube08** [comment]
Scheint wirklich nur beim Handwerker Skill in der Verpackung zu sein, dass man keine Fortschritte macht.

**Comment by DonVitoDiangelo** [comment]
fixed next update
