### ISSUE TITLE
Rechnungen nicht anschaubar

### ISSUE THREAD

**Issue by SandyLive89** [mexyn/statev_v2_issues#255]
Sandy Miller

Zeitpunkt (Datum / Uhrzeit)

20.11.2020 13:30 / 14:00
Beobachtetes Verhalten

Wenn man jemanden eine Rechung ausstellt kann man sich diese nicht anschaun so wie früher

Erwartetes Verhalten

 Das sie anschaubar ist

Schritte um den Fehler nachvollziehen zu können
Jemanden eine Rechnung ausstellen beim Handel

**Comment by its4l3x** [comment]
@SandyLive89 Immer noch beständig?

**Comment by SandyLive89** [comment]
@its4l3x  ja man kann sie immer noch nicht anschauen
