### ISSUE TITLE
UI Auflösung

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#256]
**Character Name**
Marvin_Elpe

**Beobachtetes Verhalten**
Finde die UI Auflösung viel zu groß angepasst (siehe Bilder unten). Funkgerät, Tablet, Handy passen von der Größe her. Das Inventar und Animationsmenü sind allerdings viel zu groß. (Größe passt nur die Schrift ist sehr groß gewählt, besonders beim Animationsmenü)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
2k (2560 x 1440)

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/33394632/99821384-429f9780-2b52-11eb-94b6-af2318466e0c.png)
![image](https://user-images.githubusercontent.com/33394632/99821418-4cc19600-2b52-11eb-87f5-32ee6ca1af41.png)

**Comment by M4rvinLP** [comment]
Zum Vergleich: so sah es in der Beta aus wo noch nichts angepasst war. War damals zu klein. Ein schöner Mittelwert würde glaub ich ganz gut passen.
![20200724191513_1](https://user-images.githubusercontent.com/33394632/99826507-be9cde00-2b58-11eb-993d-5134e900ab83.jpg)

**Comment by eiksch** [comment]
Das UI ist optimiert für 1920x1080, es kann sein das manche UI's bei WQHD Auflösung noch nicht so richtig schön skalieren. Wir nehmen diese Fehler aber trotzdem auf und beheben es irgendwann,.
