### ISSUE TITLE
Abschlepper buggt - Autos fallen vom Himmel

### ISSUE THREAD

**Issue by AtreuX** [mexyn/statev_v2_issues#257]
**Character Name**
Tom_Clark

**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020 ca. 16:10

**Beobachtetes Verhalten**
Abschlepper fährt an mir vorbei, buggt rum. Fahrzeuge und Objekte (z.B. Mülleimer) despawnen und fallen danach vom Himmel, auch an anderen Stellen (siehe z.B. Phantom). Tankeachse liegt quer, despawnt nach kurzer Zeit und wird nachher von mir einen Häuserblock entfernt in einer Seitengasse liegend aufgefunden. Relog hat an der Situation nicht geändert, auch Entfernen vom Ort und Wiederkehr nach einer dreiviertel Stunde nicht. Andere Speiler, die teilweise neu eingeloggt sind, sehen ebenfalls die neue Situation wie beschrieben (Achse liegt am neuen Ort rum etc.). Phantom beschädigt (u.a. Scheiben kaputt).

**Erwartetes Verhalten**
Kein Buggen des Abschleppers, kein Fallen von Autos vom Himmel.

**Schritte um den Fehler nachvollziehen zu können**
Siehe erlebtes im Video + neue Lage der Achse im Screenshot

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
-

**Optional: Video / Bilder des Fehlers**
https://youtu.be/DWGsL6wXZkY

Neue Lage der Achse, welche vorher abgekoppelt hinterm Phantom (siehe Video) stand.
![20201120164503_1](https://user-images.githubusercontent.com/74780325/99822813-f2c1d000-2b53-11eb-828e-60e2e944bd67.jpg)

**Comment by r3sist3nt** [comment]
Wir arbeiten bereits dran

**Comment by r3sist3nt** [comment]
Nach dem nächsten Serverneustart behoben.
