### ISSUE TITLE
Ladepunkt verschieben

### ISSUE THREAD

**Issue by Asmier** [mexyn/statev_v2_issues#258]
Asmier Umid

Firma: Bone Eater - Lager
Hash: pfJunVespucciCan24

Aktueller Punkt: http://prntscr.com/vmxw8y
Über dem Gully Deckel, durch die neuen Alt:V Poller kaum rein fahren möglich

Neuer Punkt: http://prntscr.com/vmxxbj
Vorne auf der Straße

**Comment by DrGrizzlY17** [comment]
moved
