### ISSUE TITLE
Helmut's Werkstatt Probleme

### ISSUE THREAD

**Issue by AniballCosta** [mexyn/statev_v2_issues#261]
**Aniball Costa**

**20.11.2020 - 10 Uhr-17:30 Uhr**

**Hebebühne und Lackierkammer schnell und oft defekt / Wenn man bei einer Werkstatt eine Rechnung abbricht, kann der Mitarbeiter nicht mehr an die Hebebühne benutzen, heißt man muss sich ausloggen und neu ein loggen. / Beim Abschleppen spawnen Autos in der Nähe mit Totalschaden an Random Orten**

**Es sollte funktionieren wie gedacht. **

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by r3sist3nt** [comment]
Bekannt und bereits intern behoben
