### ISSUE TITLE
Keine Einstellung in Firmen möglich

### ISSUE THREAD

**Issue by LautaroTesto** [mexyn/statev_v2_issues#262]
**Lautaro_Testo**

 Lautaro_Testo

**Zeitpunkt (Datum / Uhrzeit)** 
17:30

**Beobachtetes Verhalten**  
Keine Einstellung in Firmen möglich, obwohl Rechte vorhanden sind

**Erwartetes Verhalten** 
Das anderer Spieler sollte ein Vertrag per E-Mail erhalten

**Schritte um den Fehler nachvollziehen zu können**
 Ein Spieler in die Firma einstellen > "Neuen Mitarbeiter einstellen" > Charnamen eingeben "Max_Mustermann" > Button "Einstellen" drücken | Vorgang wird nicht durchgeführt, mit Mausklick wird das "Fenster" geschlossen
 

 
![5d144ad5cb1cf376f63d0ed5e23fb510](https://user-images.githubusercontent.com/74772307/99826435-a9c04a80-2b58-11eb-8329-41ff72cd97cc.jpg)

**Comment by MarcelMuerto** [comment]
Problem konnte nicht nachgestellt werden beim StateNet, liegt an etwas anderem.

**Comment by GeorgGold-altf4** [comment]
HINWEIS: Die Einstellung in andere Firmen ist möglich, nur nicht in diese Werkstatt! Könnte also ein Problem von mir oder der Werkstatt sein.

**Comment by GeorgGold-altf4** [comment]
PROBLEM GELÖST: lag an der 15 Personen Grenze
