### ISSUE TITLE
Supreme Hoodie bei den Nike Hoodies

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#263]
**Character Name**
Max_Broady

**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020 - 17:59

**Beobachtetes Verhalten**
Schwarzer Supreme Hoodie in Nike Hoodie Abteilung beim NPC für die Vorschau

**Erwartetes Verhalten**
Das der Hoodie in der Supreme Abteilung ist.

**Schritte um den Fehler nachvollziehen zu können**
NPC menu öffnen.
Nike Hoodie Spalte unter Oberteile öffnen.
Supreme Hoodie auswählen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![Screenshot_4](https://user-images.githubusercontent.com/70150887/99827814-67980880-2b5a-11eb-82e6-831906886b80.png)

**Comment by DonVitoDiangelo** [comment]
next update fixed
