### ISSUE TITLE
Beim Feuerwerk anzünden Anti-Cheat Kick

### ISSUE THREAD

**Issue by MarkHarland** [mexyn/statev_v2_issues#264]
**Mark_Harland**

**20.11.2020 16:04**

**Wollte Feuerwerk zünden als ich dies mit E gemacht hab wurde ich wegen Anti-Cheat von Server gekickt**

**Feuerwerk zünden und angucken (nicht gekickt werden)**

**Feuerwerk mit rechts Klick und Punkt auf gestellt > Mit E gezündet den gekickt**

https://youtu.be/3LjeesKi1nc

**Comment by its4l3x** [comment]
Fixed. Nächstes Update.
