### ISSUE TITLE
Werkstatt/Lackieren

### ISSUE THREAD

**Issue by Oger8602** [mexyn/statev_v2_issues#265]
**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020 ca. 14:30 Uhr

**Beobachtetes Verhalten**
Bei Lackierungen egal welche Farbe werden immer nur 6 Basis sowie 3 Schwarzer Lack benötigt! Dazu wird nicht angezeigt was man für Perleffekt benötigt dort 

**Optional: Video / Bilder des Fehlers**
Würde ich gerne leider Lackierkammer schon kaputt

**Comment by r3sist3nt** [comment]
Behoben
