### ISSUE TITLE
Sync Fehler

### ISSUE THREAD

**Issue by MarkHarland** [mexyn/statev_v2_issues#266]
**Mark_Harland**

**20.11.2020 16:12**

**Fahrzeug vor mir ist hüpft komisch rum und Synct zurück**

**Fahrzeug bleibt flüssig vor mir**

**Bin ganz normal gefahren**

**https://youtu.be/ENqvvNomBFU**

**Comment by DonVitoDiangelo** [comment]
Fahrer dort hat sch*** Netz.
