### ISSUE TITLE
Charakter nach MD Behandlung völlig Blutig

### ISSUE THREAD

**Issue by MarkHarland** [mexyn/statev_v2_issues#267]
**Mark_Harland**

**20.11.2020 17:18**

**Charakter nach Unfall und nachfolgender MD Behandlung komplett Blutig. Für mich sah er komplett normal aus für andere Spieler komplett voller Blut**

**Charakter danach keine so heftigen Verletzungen oder Blutungen**

**Auto Unfall>von MD abgeholt und behandelt>nach entlassung für mich alles normal für andere Personen der Charakter voller Blut**

**https://prnt.sc/vmxz8j**

**Comment by eiksch** [comment]
#137
