### ISSUE TITLE
Unterbodenlicht nach ausparken eingeschaltet

### ISSUE THREAD

**Issue by MrMutantus** [mexyn/statev_v2_issues#268]
**Character Name**

Felix Sommer

**Zeitpunkt (Datum / Uhrzeit)**

20.11.2020

**Beobachtetes Verhalten**

Wenn ich ein Fahrzeug ausparke und den Motor starte, ist das Unterbodenlicht standardmäßig eingeschaltet, auch wenn das Licht beim einparken ausgeschaltet war. Danach muss ich das Unterbodenlicht einmal einschalten, und kann es dann erst ausschalten.

**Erwartetes Verhalten**

Was ich erwarten würde, wäre entweder, dass, wenn ich das Fahrzeug mit ausgeschalteten Unterbodenlicht einparke, und es dann ausparke, das Licht dann auch ausgeschaltet ist, oder dass ich das Unterbodenlicht direkt ausschalten kann und nicht erst einmal einschalten und dann ausschalten muss.

**Schritte um den Fehler nachvollziehen zu können**

Unterbodenlicht ausschalten.
Fahrzeug einparken.
Fahrzeug ausparken. 
Motor starten. (Unterbodenlicht ist an)
Unterbodenlicht einschalten. (Meldung: Unterbodenlicht eingeschaltet. Unterbodenlicht bleibt weiterhin an.)
Unterbodenlciht ausschalten. (Meldung: Unterbodenlicht ausgeschaltet. Unterbodenlicht ist nun aus.)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=Pgf14T2LOL8

**Comment by DonVitoDiangelo** [comment]
Jap ist halt so . :D
