### ISSUE TITLE
Anprobe bei Juwelier "mitnehmbar"

### ISSUE THREAD

**Issue by mxRde** [mexyn/statev_v2_issues#27]
**Zeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Beobachtetes Verhalten**
Man geht in den Juwelier, nimmt sich den Anproben NPC und geht mit E wieder raus.
Gleiche Problem gab es beim Fashion Killa, dies hat t4sty (der schmackhafte) aber schon gefixed gehabt.

**Erwartetes Verhalten**
Bei verlassen des Juweliers die Anprobe Maske verlieren.

**Schritte um den Fehler nachvollziehen zu können**
1. In den Juwelier gehen
2. NPC benutzen
3. N drücken um sich wieder bewegen zu können.
4. Rauslaufen

**Optional: Video / Bilder des Fehlers**

https://puu.sh/GlFhw/33b61896e1.jpg

**Comment by its4l3x** [comment]
Fixed.
