### ISSUE TITLE
Falsche Felgen

### ISSUE THREAD

**Issue by polyholic** [mexyn/statev_v2_issues#270]
**Charaktername:** Amber Antigua

**Zeitpunkt:** 20.11.2020 | 19:55

**Beobachtetes Verhalten**
https://ibb.co/1JxWs4f

**Erwartetes Verhalten**
https://ibb.co/RjnBT3f

**Comment by DonVitoDiangelo** [comment]
Vereinzelt kann es da zu Fehlern kommen.  Einfach neu tunen.
