### ISSUE TITLE
Nach Gamecrash falschen Spawnpunkt

### ISSUE THREAD

**Issue by Chrinis007** [mexyn/statev_v2_issues#271]
**Character Name**
Christian_Maier

**Zeitpunkt (Datum / Uhrzeit)**
Jetzt

**Beobachtetes Verhalten**
Nach Gamecrash 100m weit weg gespawned

**Erwartetes Verhalten**
Am selben punkt login wo der logout war

**Schritte um den Fehler nachvollziehen zu können**
Gamecrash bekommen; einloggen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by HamasakiPinkman** [comment]
ist bei mir auch so zwar nicht wegen ein Gamecrash aber wenn ich mich auslogge und nach ner zeit wieder on komme stehe ich dann mitten in LS und nicht mehr in Sandy  und nun bin ich sogar schon deswegen gestorben ..... BITTE FIXT ES

**Comment by eiksch** [comment]
@HamasakiPinkman @Chrinis007 

Speichern eure Charaktere überhaupt nicht? Oder war das ein Einzelfall?

**Comment by HamasakiPinkman** [comment]
also wenn ich mich bei mir Zuhause auslogge und dann einlogge Falle ich durch den Boden und Spawne in LS

**Comment by Chrinis007** [comment]
Bisher noch nie dort gespawned wo ich Crash/log out hatte

**Comment by Chrinis007** [comment]
Mittlerweile fixed

**Comment by its4l3x** [comment]
Korrekt. Haben das Saving überarbeitet gehabt. Schließe den Eintrag mal
