### ISSUE TITLE
StateCOM Ränge

### ISSUE THREAD

**Issue by Mr-Chris-VRTY** [mexyn/statev_v2_issues#272]
Ränge in der Akte der Person noch nicht übereinstimmend mit tatsächlichem Rang (Dashboard)
![image](https://user-images.githubusercontent.com/70213538/99840175-53f59d80-2b6c-11eb-8151-66df2edb99f7.png)
In diesem Fall Rang Corporal ist in der Personalakte Detective
Detective ist z.B. SAPD Officer

**Comment by milkdrops** [comment]
Wir vermuten, dass das StateCOM eine ältere Version hat als zum Ende von v1, weil:

- Alte Ränge wie SAPD Officer (7) werden angezeigt statt die aktuellen, Detective (7)
- Hinweise/Notizen zu Personen funktionieren nicht
- Dashboard Officer Liste wird sortiert nach Department, aber neue Ränge (wie z.B. Probationary Deputy) sind durcheinander

**Comment by MarcelMuerto** [comment]
- Alte Ränge wie SAPD Officer (7) werden angezeigt statt die aktuellen, Detective (7) ✔
- Hinweise/Notizen zu Personen funktionieren nicht ✔
