### ISSUE TITLE
Werkstatt/Z4 macht den Computer kaputt!!!

### ISSUE THREAD

**Issue by Oger8602** [mexyn/statev_v2_issues#273]
**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020 ca. 20:20

**Beobachtetes Verhalten**
Steht der BMW Z4 auf dem Tuning bzw. Reparatur Punk und man geht an den Computer öffnet sich das Menü nicht!!!
Wurde mehrfach getestet mit dem Fahrzeug!

**Schritte um den Fehler nachvollziehen zu können**
BMW Z4 auf den Punkt stellen!
An den Computer gehen

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/217

**Comment by DonVitoDiangelo** [comment]
duplicate
