### ISSUE TITLE
E-Tankstellen berechnen den Preis falsch

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#274]
**Character Name**
Marvin_Elpe

**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020 / 20:46

**Beobachtetes Verhalten**
Habe bei meiner Tanke einen Preis von $50 für die Akkuzellen eingestellt. Soweit ich weiß ist eine Akkuzelle 1 kW/h. Möchte ich z.B. 10kW/h laden, würde mich das nur $286.73 kosten. Eigentlich sollten es $500 sein.

**Erwartetes Verhalten**
Preis wird richtig berechnet

**Schritte um den Fehler nachvollziehen zu können**
Versuchen ein Elektro Auto zu laden.

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/33394632/99843373-c61cb100-2b71-11eb-9341-404b5c2956ff.png)

**Comment by M4rvinLP** [comment]
Gerade weiter getestet. Alles bis 6 kW/h wird falsch berechnet. Sobald man von 6 auf 7 kW/h geht, geht der Preis richtig hoch. Die Mindestmenge ist auch auf 5 kW/h gesetzt, der Betrag sowie die Dauer sind dabei negativ.

**Comment by M4rvinLP** [comment]
Glaube habe den Fehler dahinter gefunden. Bin aber weiter am testen diesbezüglich.

**Comment by r3sist3nt** [comment]
Ich glaube du verstehst die Anzeige falsch. 10kW/h ist die Zielladung, die du laden willst. Dein Fahrzeug hat aber bereits eine gewisse Ladung. Demnach willst du hier nicht 10kW/h laden, sondern die differenz zwischen 10 und vorhandener Ladung
