### ISSUE TITLE
Gekaufte Waffen aus Ammunation ohne Seriennummer

### ISSUE THREAD

**Issue by masterppc** [mexyn/statev_v2_issues#275]
**Hans_Hentschel**

**Zeitpunkt (Datum / Uhrzeit)**

20.11.2020 20:42
**Beobachtetes Verhalten**
Ich habe 5 Taurus gekauft und bekomme dann 5 Stück gestackt ohne Seriennummer.

**Erwartetes Verhalten**
5 einzelne Taurus mit Seriennummern im Inventar

**Schritte um den Fehler nachvollziehen zu können**
In der Ammunation Taurus kaufen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://i.imgur.com/gJKFFXt.jpg

**Comment by eiksch** [comment]
Sollte beim nächsten Update behoben sein
