### ISSUE TITLE
Nutzung vom Waffenrad verrückt HUD's

### ISSUE THREAD

**Issue by statevfrakes** [mexyn/statev_v2_issues#276]
Ricardo Cooper

Ricardo Cooper

**Zeitpunkt (Datum / Uhrzeit)**

20.11.20 / 21:15 ca

**Beobachtetes Verhalten**

Bei der Nutzung vom Waffenrad verschieben sich die HUD's bzw das HUD was Nahrung und Co anzeigt übernimmt die Animation vom Funkgerät, wenn man "U" drückt. Das Funkgerät ist dann dauerhaft sichtbar.
**Erwartetes Verhalten**

Das Funkgerät sollte beim Drücken von "U" sichtbar/unsichtbar werden. 
Die Interaktion mit dem Waffenrad sollte keinen Einfluss auf die UI's haben
**Schritte um den Fehler nachvollziehen zu können**

"TAB" drücken, dann im Mausrad Scrollen und eine Waffe auswählen, "TAB" loslassen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

-
**Optional: Video / Bilder des Fehlers**

YT Link, da Dateiformat nicht unterstützt: https://www.youtube.com/watch?v=6EHdNjTTkJ0&feature=youtu.be

**Comment by DrGrizzlY17** [comment]
Doppelt
