### ISSUE TITLE
Flatbed kann nicht mehr auf laden Temporär gesperrt

### ISSUE THREAD

**Issue by NitroDog119** [mexyn/statev_v2_issues#277]
**Bernd Shoemaker**

Bernd_Shoemaker
**Zeitpunkt (Datum / Uhrzeit)**

22:06 20.11.2020
**Beobachtetes Verhalten**

Beim Versuch den flatbed mit einem auto zu beladen stand es wäre temporär gesperrt die funktion
**Erwartetes Verhalten**

Mann kann das auto an wählen und aufladen es dauert 1 minuten dann is er normal drauf
**Schritte um den Fehler nachvollziehen zu können**

Neben das auto fahren dann es an wählen zum beladen das flatbed da kommt die meldung
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by r3sist3nt** [comment]
...

**Comment by eiksch** [comment]
So wie in der Meldung angegeben, ist die Funktion temporär deaktiviert.
