### ISSUE TITLE
Bart schneiden funktioniert nicht richtig?

### ISSUE THREAD

**Issue by Naaki6** [mexyn/statev_v2_issues#278]
**Character Name**

Caleb Bradley
**Zeitpunkt (Datum / Uhrzeit)**

22:35
**Beobachtetes Verhalten**

Es wurde versucht den Bart zu schneiden. Es wurde 2x getestet und es wurde 2x After Shave verbraucht aber es hat sich nichts am Bart geändert und die Schnitt wurde nicht übernommen.
**Erwartetes Verhalten**

Entweder es funktioniert nicht und es fehlt dann auch keine Ressource oder es funktioniert und die Ressource wird verbraucht. 
Evtl. Cooldown trennen zwischen Haare schneiden und Bart/Augenbrauen machen. Da es ja z.B. auch keinen Cooldown beim Haarefärben gibt. 
**Schritte um den Fehler nachvollziehen zu können**

Friseur -> Bart auswählen -> Bart schneiden 
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Cooldowns werden bereits getrennt - Es gab ein kleiner Bug, welchen ich nun behoben hatte.
