### ISSUE TITLE
Zu schneller Prozessbalken beim Lackieren

### ISSUE THREAD

**Issue by Asmier** [mexyn/statev_v2_issues#279]
Asmier Umid

**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020 / 23:26

**Beobachtetes Verhalten**
Zu schneller Prozessbalken beim Lackieren

**Erwartetes Verhalten**
Lackierung sollte paar minuten andauern

**Schritte um den Fehler nachvollziehen zu können**
1. Lack einstellen
2. Lackieren
3. Man ist innerhalb von sekunden fertig

**Comment by r3sist3nt** [comment]
Nach nächstem Restart behoben
