### ISSUE TITLE
Ausrüsten aus Rucksack raus nicht möglich

### ISSUE THREAD

**Issue by ProgrammingFox** [mexyn/statev_v2_issues#28]
**Zeitpunkt (Datum / Uhrzeit)**

25.08.2020 20:23 Uhr
**Beobachtetes Verhalten**

Waffen/Munition können nicht vom Rucksack aus ausgerüstet werden. Bei Munition kommt die Fehlermeldung "Du besitzt diese Waffe nicht." und bei Waffen kommt "
**Erwartetes Verhalten**

Man sollte Waffen/Munition auch aus dem Rucksack raus ausrüsten können.
**Schritte um den Fehler nachvollziehen zu können**

Waffe ausrüsten aus der Hosentasche aus und Munition aus dem Rucksack aus nachrüsten.
Waffe ausrüsten vom Rucksack aus.
**Optional: Video / Bilder des Fehlers**

![grafik](https://user-images.githubusercontent.com/48456305/91212787-fbe80000-e710-11ea-92bb-cccf4acbab40.png)
![grafik](https://user-images.githubusercontent.com/48456305/91212873-1c17bf00-e711-11ea-8a5c-7ed89b033414.png)

**Comment by DrGrizzlY17** [comment]
Das Anlegen von Munition&Waffen aus dem Rucksack ist momentan nicht gewollt

**Comment by DrGrizzlY17** [comment]
fixed error message
