### ISSUE TITLE
24/7 Shop - Gitarren können nicht entpackt werden

### ISSUE THREAD

**Issue by ZacCooperr** [mexyn/statev_v2_issues#280]
**Zeitpunkt (Datum / Uhrzeit)**
23:30 / 20.11.2020

**Beobachtetes Verhalten**
Verpackte Gitarren können nicht im 24/7 entpackt werden.

**Erwartetes Verhalten**
Das man die einzelnen Modelle im 24/7 mit der Bezeichnung entpacken kann.

**Optional: Video / Bilder des Fehlers**
![Gitarre](https://user-images.githubusercontent.com/74767269/99856752-f3755900-2b89-11eb-8929-443109eb4be5.JPG)

**Comment by DrGrizzlY17** [comment]
Hast du ne Fehlermeldung oder sonstiges?

**Comment by DrGrizzlY17** [comment]
Fixed
