### ISSUE TITLE
Gießkanne auffüllen dauert länger als gießen

### ISSUE THREAD

**Issue by KruemelGames** [mexyn/statev_v2_issues#281]
Dave Weinstein

**Zeitpunkt (Datum / Uhrzeit)
01.32Uhr

**Beobachtetes VerhaltenWasser:
 in Gießkanne (rostige Kanne) Auffüllen (1-2 Minuten) dauert länger als das Gießen (15 Sekunden)

**Erwartetes Verhalten: 
Das Auffüllen einer Gießkanne ist kürzer als das Gießen

**Schritte um den Fehler nachvollziehen zu können**
1. Gießkanne im Inventar haben
2. Im Wasser stehen und Gießkanne rechtsklicken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
/////

**Optional: Video / Bilder des Fehlers**
Nicht nötig

**Comment by tastydev** [comment]
Kein Handlungsbedarf
