### ISSUE TITLE
Fahrad mit Kofferraum?

### ISSUE THREAD

**Issue by Bronze6** [mexyn/statev_v2_issues#282]
**Character Name**

Nico_Bronze
**Zeitpunkt (Datum / Uhrzeit)**

21.11.2020 / 01:00
**Beobachtetes Verhalten**

Fahrrad Scorcher hat einen Kofferraum von 100 Kg
**Erwartetes Verhalten**

0 Kg? oder Feature? 
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![20201121013132_1](https://user-images.githubusercontent.com/74800637/99862288-6e923b80-2b99-11eb-82df-fbcbbe9b1a45.jpg)

**Comment by DonVitoDiangelo** [comment]
fixed next update
