### ISSUE TITLE
Fahrzeug auf alte Park-Position zurückgesetzt/Handling des Fahrzeugs verändert

### ISSUE THREAD

**Issue by Shirobaka** [mexyn/statev_v2_issues#283]
**Character Name**
Shigekuni Yamamoto

**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020 ca. 23 Uhr - 21.11.2020 ca. 02 Uhr

**Beobachtetes Verhalten**
Mein Fahrzeug Sultan RS (KZ: SY O3 94) stand auf dem Parkplatz am Rockford Plaza, wurde von mir nach Sandy Shores gefahren und dort vor dem Sheriffs Office geparkt und bin dort in den Dienst gegangen. Gegen 2 Uhr habe ich den Dienst wieder verlassen, ich stellte fest, das mein Fahrzeug wieder genauso auf dem Parkplatz am Rockford Plaza stand, wie ich ihn zuvor dort entfernt hatte.
Desweiteren ist mir aufgefallen das sich nach dem zurücksetzen das Handling des Fahrzeuges verändert hat, es ist schwerfälliger, erreicht die eigentliche Maximalgeschwindigkeit nicht mehr und beschleunigt um einiges langsamer.

Wann genau das Fahrzeug zurückgesetzt wurde kann ich nicht sagen.

**Erwartetes Verhalten**
Das Fahrzeug sollte dort bleiben wo es parkt, nicht durch Geisterhand wieder zum alten Parkplatz teleportiert werden.

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug steht auf Parkplatz -> Einsteigen + Motor Starten -> Fahrziel erreichen, Fahrzeug abstellen, Motor ausstellen, Aussteigen.

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/271

**Comment by eiksch** [comment]
Hast du vorher mit dem Fahrzeug irgendwas relevantes gemacht? Geschoben? Abgeschleppt?

Gibt es andere Leute die das Fahrzeug in Sandy gesehen haben?

Haben andere Leute dich beim Fahren gesehen?

**Comment by Shirobaka** [comment]
Ich hab es selbst nicht geschoben, ob es andere gemacht haben, keine Ahnung.
Das Fahrzeug habe ich zuvor gerade auf den Parkplatz Rockford Plaza abgestellt und hatte mich kurz danach ausgeloggt, als ich später wieder kam stand das Fahrzeug etwas schräg in der Parklücke, hatte mir da aber nichts weiter bei gedacht.
Ob mich jemand beim Fahren gesehen hat, oder das Fahrzeug anschließend in Sandy Shores gesehen hat, kann ich nicht sagen.

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/400  


Das mit dem handling sollte soweit behoben sein
