### ISSUE TITLE
Lackierkammer ist nach fertiger Lackierung kaputt

### ISSUE THREAD

**Issue by thumbsucker** [mexyn/statev_v2_issues#284]
**Character Name**
Otto Gust (Lackierer) & Arturo Gonzalez (Kunde)

**Zeitpunkt (Datum / Uhrzeit)**
20.11.2020 23:41

**Beobachtetes Verhalten**
Nachdem der Kunde bezahlt hat, wurde das Auto zunächst optisch lackiert. Als die Lackierung jedoch durch war, war wieder der alte Lack drauf. Danach konnte die Lackierkammer nicht mehr genutzt werden (Meldung: "Bereits in Verwendung!") und das Auto konnte nicht mehr rausgefahren werden. Zuvor haben alle Lackierungen super geklappt. 

**Erwartetes Verhalten**
Fertige Lackierung, eine weiterhin funktionstüchtige Lackierkammer. Das Auto sollte sich vom Punkt fahren lassen. 

**Schritte um den Fehler nachvollziehen zu können**
Der einzige Unterschied zu den Lackierungen zuvor: Auf einen RGB Grünton sollte Perleffekt drauf. Bei den Lackierungen zuvor war es immer auf Speziallack. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
//

**Optional: Video / Bilder des Fehlers**
//

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/290

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/364

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/431
