### ISSUE TITLE
Rauchen verbraucht kein Item.

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#285]
**Zeitpunkt (Datum / Uhrzeit)**
21.11.2020 / 2020

**Beobachtetes Verhalten**
An einen Aschenbecher stellen
y drücken 
Rauchen
man behält das Item

**Erwartetes Verhalten**
An einen Aschenbecher stellen
y drücken 
Rauchen
man behält das Item NICHT

**Comment by DrGrizzlY17** [comment]
Gewollt
