### ISSUE TITLE
Sehe keine Autos, NPCs 

### ISSUE THREAD

**Issue by HamasakiPinkman** [mexyn/statev_v2_issues#286]
**Character Name**

Dennis Pinkman
**Zeitpunkt (Datum / Uhrzeit)**

21.11.2020 4:42 Uhr
**Beobachtetes Verhalten**

wenn ich mich einlogge sehe ich keine Autos, NPCs oder Punkte zum Interagieren wie z.B beim 24/7 bin in einer leeren Welt 
**Erwartetes Verhalten**

Das sehen der oben genannten Objekte  
**Schritte um den Fehler nachvollziehen zu können**

Hierzu kann ich leider keine angaben machen 
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

//
**Optional: Video / Bilder des Fehlers**

//

**Comment by DonVitoDiangelo** [comment]
Sehr sicher falsche Dimension. Einach mal in den Support gehen und bearbeiten lassen.
