### ISSUE TITLE
Playermenü öffnet sich, anstatt Automenü, sobald Spieler im Auto sitzt!

### ISSUE THREAD

**Issue by iNeverSafe** [mexyn/statev_v2_issues#287]
**Character Name**
Lucifer_Black

**Zeitpunkt (Datum / Uhrzeit)**
Jederzeit reproduzierbar! 

**Beobachtetes Verhalten**
Wenn man eine Person als Beifahrer hat und man das Auto Interaktionsmenü öffnen möchte, dann wird der Spieler, welcher als Beifahrer im Auto sitzt als Target genommen und es öffnet sich das Spieler Interaktionsmenü.

**Erwartetes Verhalten**
Wenn eine Person im Auto sitzt, dann wird diese als Target ignoriert, sodass man ohne Probleme das Fahrzeugmenü öffnen kann.

**Schritte um den Fehler nachvollziehen zu können**
Person als Beifahrer reinsetzen und nah am Auto stehen, dann öffnet das Player Target Menü und nicht Auto Menü.

**Comment by DonVitoDiangelo** [comment]
So gewollt. Auch immer darauf achten wohin man genau schaut. ;)
