### ISSUE TITLE
Boot Handbremse

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#29]
**Zeitpunkt (Datum / Uhrzeit)**

20:33 25.08.2020

**Beobachtetes Verhalten**

Boot hat eine funktionierende Handbremse.

**Erwartetes Verhalten**

Es sollte keine haben.

**Schritte um den Fehler nachvollziehen zu können**

X drücken. Handbremse nutzen.

**Optional: Video / Bilder des Fehlers**

![Screenshot_3](https://user-images.githubusercontent.com/63787507/91213895-939a1e00-e712-11ea-89a7-694587fda504.png)

**Comment by its4l3x** [comment]
Fixed, nächstes Update
