### ISSUE TITLE
Police Kopfbedeckungen fehlen

### ISSUE THREAD

**Issue by Mr-Chris-VRTY** [mexyn/statev_v2_issues#291]
**Character Name**
Chris Schubert

**Zeitpunkt (Datum / Uhrzeit)**
21.11.2020 9:00 Uhr

**Beobachtetes Verhalten**
Kopfbedeckungen fehlen im Skinauswahlmenü

**Erwartetes Verhalten**
z.B. campaign hat (BCSO) und LSPD cap fehlen

**Schritte um den Fehler nachvollziehen zu können**
Cop-Skinmenü öffnen

**Comment by its4l3x** [comment]
Nein sie Fehlen nicht - Die Kopfbedeckungen könnt ihr selber auswählen im , Menü. Das wird nicht mehr vorgegeben, da das Variable ist. Bestes bsp. die Medics mit dem Cowboy Hut ;)

Kein Bug, CLOSED

**Comment by Mr-Chris-VRTY** [comment]
Und wo kriegen wir die Kopfbedeckungen her? Kleiderläden führen keine Policemützen?
