### ISSUE TITLE
Tieflader Achse - Falsche Transportgruppe

### ISSUE THREAD

**Issue by ZacCooperr** [mexyn/statev_v2_issues#292]
**Zeitpunkt (Datum / Uhrzeit)**
21:11:2020 9:42 Uhr

**Beobachtetes Verhalten**
Den Kofferraum der Tieflader Achse kann nicht genutzt werden. Man erhält die Meldung: **Falsche Transprtgruppe**.

**Erwartetes Verhalten**
Entweder dass der Kofferraum für die Tieflader Achse genutzt werden kann oder als Alternative das PKWs & LKWs auf dieser Achse transportiert/abgeschleppt werden können.

**Schritte um den Fehler nachvollziehen zu können**
Aufschließen der Achse sowie des Kofferraumes. Im Anschluss auf ein Be/Entlade Punkt fahren. Eine Ware vom Lager in den Kofferraum ziehen. Alternative Kofferraum über Charakter Be/Entladen. Beides führt zur Meldung: Falsche Transportgruppe.

**Optional: Video / Bilder des Fehlers**
![Tieflader](https://user-images.githubusercontent.com/74767269/99872028-0ebe8380-2bdf-11eb-8bf6-c133558a2332.jpg)
Info: Das Gewicht wurde extra auf dem Bild geschwärzt.

**Comment by r3sist3nt** [comment]
Das ist kein Fehler, sondern wurde genau so gedacht.
Der Tieflader ist ausschließlich für Holz gedacht.

**Comment by DonVitoDiangelo** [comment]
Holz ist ab dem nächsten Update möglich

**Comment by ZacCooperr** [comment]
Und ab wann Fahrzeuge?
