### ISSUE TITLE
Im Sitzen telefonieren - nicht mehr möglich aufzustehen

### ISSUE THREAD

**Issue by DonVitoDiangelo** [mexyn/statev_v2_issues#293]
Im Sitzen telefonieren - nicht mehr möglich aufzustehen
Wenn man sich mit Y setzt und dann telefoniert, kann man sich nicht wieder hinstellen und bewegen

https://statev.de/forum/StateBug/index.php?issue/3852-im-sitzen-telefonieren-nicht-mehr-möglich-aufzustehen/

**Comment by its4l3x** [comment]
Fixed. Next Update
