### ISSUE TITLE
Hotel AkiPillboxHillRew_Flat_5

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#294]
**Character Name**
Max_Broady

**Zeitpunkt (Datum / Uhrzeit)**
21.11.2020 - 11:04

**Beobachtetes Verhalten**
Im Tablet sind nur 19 Zimmer - an der Tür allerdings 20
Flat_7_1 fehlt imm Tablet

**Erwartetes Verhalten**
Alle 20 Zimmer im Tablet vorzufinden.
Allerdings hatten wir 40 Zimmer welche seit dem gestrigen Fix auf 20 minimiert wurden. Wäre es möglich wieder auf die 40 Zimmer hoch zu stocken?
Fix von gestern: https://github.com/mexyn/statev_v2_issues/issues/239

**Schritte um den Fehler nachvollziehen zu können**
Im Hotel einstellen & anschließend nur die 19 Zimmer vorfinden.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![20201121110844_1](https://user-images.githubusercontent.com/70150887/99874641-f011ba00-2be9-11eb-8052-9552b4bf7727.jpg)

**Comment by DrGrizzlY17** [comment]
Bitte mal checken

**Comment by TheBroady** [comment]
Es fehlt immernoch das Flat_7_1 im Tablet.
Könntet ihr da nochmal drüber schauen

der Rest ist Super, danke euch!
