### ISSUE TITLE
Doppelte Möbel im Girlie Appartment

### ISSUE THREAD

**Issue by clairekyle** [mexyn/statev_v2_issues#295]
**Claire Kyle**

**Zeitpunkt (21.11.20 / 11.00)**

**Beobachtetes Verhalten**
Im der einfachen Ausstattung des Girlie Appartments fehlten vorher Möbel. Keine Sofas etc. Jetzt sind doppelte Möbel drin. Blaue und schwarze Sofamodelle übereinander, ebenso beim Bett, und im (vom Server) neu eingerichteten Gästezimmer stehen zwei Kommoden aneinander. Es wirkt, als hätten zwei Modder am gleichen App gearbeitet und es überlappt nun 

**Erwartetes Verhalten**
eine ganz normale Einrichtung 

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![grafik](https://user-images.githubusercontent.com/74816388/99874794-c0af7d00-2bea-11eb-9ae3-a35055d3c019.png)

![grafik](https://user-images.githubusercontent.com/74816388/99874817-dc1a8800-2bea-11eb-8e78-ece1d72983a4.png)

**Comment by DonVitoDiangelo** [comment]
next update fixed
