### ISSUE TITLE
Falsche Materialien beim Lackieren?

### ISSUE THREAD

**Issue by callmerusty** [mexyn/statev_v2_issues#296]
**Beobachtetes Verhalten**
Die meisten Lackierungen benötigen Dose Basislack + Dose schwarzer Lack - völlig egal, welche Farbe man lackiert

**Erwartetes Verhalten**
Dose weißer Lack für weiße Lackierungen und Dose roter Lack für rote Lackierungen (nur ein Beispiel)

**Comment by BlackyGER** [comment]
Gabs schonmal 

https://github.com/mexyn/statev_v2_issues/issues/265

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/358
