### ISSUE TITLE
Fehlende Materialliste Felgentuning

### ISSUE THREAD

**Issue by ZirbelR** [mexyn/statev_v2_issues#298]
Richie Zirbel

21.11.2020 12:00

**Beobachtetes Verhalten**
Beim Tunen von Felgen wird nicht angezeigt welche Materialien für den Vorgang benötigt werden

**Erwartetes Verhalten**
Materialliste wird angezeigt wie bei "normalen" Tunings auch (z.B. 4x Felgen, 4x Felgenbereifung)

**Schritte um den Fehler nachvollziehen zu können**
Felgen Tunen

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/70246255/99875659-96ad8900-2bf1-11eb-85bc-1df8ad913b27.png)

**Comment by BlackyGER** [comment]
Gabs schonmal

https://github.com/mexyn/statev_v2_issues/issues/246

**Comment by ZirbelR** [comment]
Ja, besteht nach wie vor.

**Comment by DonVitoDiangelo** [comment]
Reminder

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/246
