### ISSUE TITLE
NotfallMD nach recht kurzer Zeit

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#299]
**Character Name**
Max_Broady

**Zeitpunkt (Datum / Uhrzeit)**
21.11.2020 - 12:04 Uhr

**Beobachtetes Verhalten**
Ich bin durch einen Verkehrsunfall bewusstlos geworden und nach bereits 3-4 Minuten im Notfall MD gelandet.
Der MD'ler war bereits vor ort bei einer Anfanhrtszeit welche vollkommen Ok war. Ein Unfall in Paleto hätte keinen Sinn gehabt einen Arzt zu rufen. Ist das gewollt?
Dadurch habe ich eine Levis Jeans, VLTN Hoodie & Rayban im wert von ca. ~85k verloren
Ersthelfer war vor Ort.
Ich reiche das auf die bitte von Tito ein

**Erwartetes Verhalten**
Das die Zeit länger dauert, da RP so leider auch unterbunden wird.
Hatte mir schon schöne Verletzungen und mein SchmerzRP überlegt :D

**Schritte um den Fehler nachvollziehen zu können**
Schnell Fahren, gegen einen Baum und dann warten ^^

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![d67c29d706a22a78a54f078db7d68ee5](https://user-images.githubusercontent.com/70150887/99875745-2b17eb80-2bf2-11eb-8755-62dc97ac9615.png)
![aef2188d42c3e35e843c2b401a711477](https://user-images.githubusercontent.com/70150887/99875772-6b776980-2bf2-11eb-91ce-5b1b695902cf.png)

**Comment by its4l3x** [comment]
Bereits aufgefallen - Zeit wurde wieder verändert bzw. hochgesetzt.

**Comment by TheBroady** [comment]
Wie gehe ich mit dem Verlust der Kleidung um?
Ist da was zu machen?

**Comment by eiksch** [comment]
Die Items hab ich dir in ein Auto gelegt, was in der Paleto Bay Garage steht. (weiß grad nicht mehr welches)

**Comment by TheBroady** [comment]
> 
> 
> Die Items hab ich dir in ein Auto gelegt, was in der Paleto Bay Garage steht. (weiß grad nicht mehr welches)

Ich danke dir! Ich geh mal schauen
