### ISSUE TITLE
Kein Langwaffen Bild im Inventar

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#30]
**Zeitpunkt (Datum / Uhrzeit)**
25.08.2020 - 20:38 Uhr

**Beobachtetes Verhalten**
Im Inventar wird bei einer ausgerüsteten Langwaffe kein Bild angezeigt.

**Erwartetes Verhalten**
Das dort das Bild der Langwaffe zu sehen ist.

**Schritte um den Fehler nachvollziehen zu können**
Langwaffe besitzen, und ausrüsten. (In meinem Fall die Saiga)

**Optional: Video / Bilder des Fehlers**

![Screenshot_2](https://user-images.githubusercontent.com/70150887/91214279-233fcc80-e713-11ea-9926-b7d1181807b6.jpg)

**Comment by DrGrizzlY17** [comment]
Bei welcher Langwaffe tritt der Fehler?

**Comment by DrGrizzlY17** [comment]
Rückmeldung der Waffe: saiga

**Comment by DonVitoDiangelo** [comment]
next update fixed
