### ISSUE TITLE
wenn Blinker betätigt ist kann der Motor nicht abgeschaltet werden

### ISSUE THREAD

**Issue by DrJaneX** [mexyn/statev_v2_issues#3003]
**Character Name**
Jane Mei

**Auftrittszeitpunkt (Datum / Uhrzeit)**
ca 21:45 Uhr

**Beobachtetes Verhalten**
Beim Motorrad war der rechte Blinker betätigt, wollte den Motor abschalten und konnte dieses nicht tun, bemerkt wurde es am Flghafen

**Erwartetes Verhalten**
das auch beim blinken der Motor aus geht

**Schritte um den Fehler nachvollziehen zu können**
Motor des Motorrads starten, Blinker re einschalten, Motor ausschalten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
-

**Optional: Video / Bilder des Fehlers**
https://youtu.be/hR5GNAnYTdw

**Comment by Domeex3** [comment]
@DrJaneX Tritt der Fehler bei dir immer, auch nach einem Relog auf? Konnte das ganze jetzt nicht reproduzieren.

**Comment by DrJaneX** [comment]
@Domeex3 zu dem Zeitpunkt hab ich nicht neugestartet

**Comment by Domeex3** [comment]
Hab das ganze selbst getestet, hatte das Problem aber nicht. Ich lass hier mal noch einen Tag offen, sollte es nochmal auftreten, gerne nochmal melden.
