### ISSUE TITLE
Beim schreiben der Akte wird bei Z der Sprachradius geändert

### ISSUE THREAD

**Issue by DrJaneX** [mexyn/statev_v2_issues#3004]
**Character Name**
Jane Mei

**Auftrittszeitpunkt (Datum / Uhrzeit)**
00:20

**Beobachtetes Verhalten**
Beim Schreiben einer Akte wird beim drücken der Z Taste wird auch der Sprachradius verändert

**Erwartetes Verhalten**
Beim Schreiben der Akte, wenn man die Taste Z drückt, dass keine Veränderung des Sprachradius stattfindet

**Schritte um den Fehler nachvollziehen zu können**
Akte aufmachen und einfach Z schreiben und auf den Sprachradius achten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/FAf9-bX-mWQ

**Comment by evanhaugestatev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sprachradiusänduerung beim Akte schreiben](https://trello.com/c/kXYlQBgl/311-sprachradius%C3%A4nduerung-beim-akte-schreiben)

**Comment by simplycach** [comment]
Am besten aktuell gemutet die Akten schreiben, damit kannst du es vermeiden.

**Comment by QA-Pregon** [comment]
Keine Ahnung warum das noch offen is, aber seems fixed to me, ansonsten neu aufmachen xD
