### ISSUE TITLE
Tür lässt sich nicht von Raven Slaughterhouse öffnen!

### ISSUE THREAD

**Issue by Xymena** [mexyn/statev_v2_issues#3005]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Alice_Swan  

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05:55

**Beobachtetes Verhalten**
Es gibt ein Problem mit dem Tor. Es öffnete sich für manche Leute, aber nicht für alle. Als das Tor sich öffnete, gab es eine Kollision mit einer Person, die es nicht passieren konnte. Für diese Person blieb das Tor verschlossen, und die Kollision wiederholte sich. Malon_Jaro konnte ohne weiteres rein und raus gehen.

**Erwartetes Verhalten**
Tor öffnet sich für jede Person gleichermaßen

**Schritte um den Fehler nachvollziehen zu können**
Laufe auf das Tor zu  Laufe gegen eine wand..
Jaro läuft auf das tor zu läuft durch das Tor hindurch.

**Sonstiges**

Löschen des Caches und neustart hat nicht geholfen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/76626768/6a81020b-efa8-4499-9aa1-5c413adb08ac)

**Comment by Xymena** [comment]
Update: das Tor lässt sich öffnen wenn man in der Linken ecke läuft.. es öffnet sich allerdings nur sehr sehr langsam. Das oben zu nächste als 2 collesions boxen beschrieben kamm daher zu stande das sich das tor langsam geöffnet hat. ich allerdings es nicht war genommen habe. 

https://medal.tv/games/gta-v/clips/1VKQEyKP3PTRyY/d1337ATMdOsi?invite=cr-MSxTbU0sNjQxMjQ1NTQs

**Comment by Domeex3** [comment]
Hallo, leider liegt das Problem hier bei R* und wir können da leider nichts machen. Gott sei dank ist das Tor aber nicht der einzige Eingang zum Gebäude :)
