### ISSUE TITLE
Namenändern / Einschreibung Racing

### ISSUE THREAD

**Issue by Bronze6** [mexyn/statev_v2_issues#3006]
Passiert nichts wenn ich auf Namen ändern drücke

![image](https://github.com/eiksch/statev_v3_issues/assets/74800637/8cbe0d90-c9fe-4553-af5e-65652fbadd74)

**Comment by Domeex3** [comment]
Hallo, hast du nur den Namen probiert oder ging es allgemein nicht? @Bronze6

**Comment by Bronze6** [comment]
Sorry, ne ging allgemein nicht.
Hab 2 andere Namen probiert

**Comment by SHaagmann** [comment]
Gleiches Problem gerade gehabt

**Comment by simplycach** [comment]
Habt ihr auch nen Namen eingegeben sieht oben nicht so aus :D

**Comment by SHaagmann** [comment]
@simplycach jo habe mehrere Namen versucht. Man konnte den Knopf zwar drücken aber es ist gar nichts passiert

**Comment by SHaagmann** [comment]
![image](https://github.com/eiksch/statev_v3_issues/assets/58612983/ee6b7d49-7f61-4b72-ba5c-4a84566ded13)
Gleicher Bug beim Kartrennen i.V. für Zirbel

**Comment by simplycach** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Racing / Kart Name DB Fehler](https://trello.com/c/Tu1tXXA1/347-racing-kart-name-db-fehler)

**Comment by simplycach** [comment]
fixed
