### ISSUE TITLE
Begrenzer lässt sich teilweise nicht mehr aktivieren.

### ISSUE THREAD

**Issue by bauscha** [mexyn/statev_v2_issues#3007]
Sokolov_Petrovic

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.02.2024/ 11:44

**Beobachtetes Verhalten**
Nach Tanken konnte Begrenzer nicht mehr verwendet werden. Zuvor gab es auch schonmal das Problem, dass man zwar Geschwindigkeit vom Begrenzer umstellen konnte, das Aktivieren ging aber nicht mehr. Leider kann ich beim ersten Mal kein "auslösendes" Event beschreiben, beim zweiten Mal war es das Tanken.

**Erwartetes Verhalten**
Begrenzer sollte einschaltbar sein.

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug: Nightblade
Tanken gehen, Motor anmachen und bei der Fahrt unter dem Threshold (80) Ende drücken. Dann passiert (bei mir) nichts

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920*1080

**Comment by bauscha** [comment]
Kleine Addition: Eventuell lag es daran, dass ich den Begrenzer beim Absteigen noch an hatte. Vielleicht kommt das System da durcheinander?

**Comment by evanhaugestatev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hotkey/Funk bug](https://trello.com/c/ovxDVzlP/272-hotkey-funk-bug)

**Comment by simplycach** [comment]
Liegt ehr an den Werbungen aktuell. Am besten ausschalten.

**Comment by TheOutburst** [comment]
sollte seit ca einer Woche nichtmehr auftreten
