### ISSUE TITLE
Marker im F7 Menü werden nicht gespeichert

### ISSUE THREAD

**Issue by tr1kssi** [mexyn/statev_v2_issues#3008]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Jackson Rodriguez

Wann exakt (Datum / Uhrzeit) ist der Fehler beobachtet worden

Markereinstellungen werden nach Relog/Logout nicht gespeichert

Marker sollten an/aus bleiben

Im F7 Menü testen

**Comment by simplycach** [comment]
Konnte ich selbst nachstellen, hat aber aktuell nicht wirklich hohe Priorität ist nen nice to have.

**Comment by TheOutburst** [comment]
ist mit dem letzten Update fixed 👌
