### ISSUE TITLE
Button für Custom Background falsche Positio

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3009]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

17.02 14:37
**Beobachtetes Verhalten**

Custom Background soll gesetzt werden. Button für die Preview ist an falscher Position
**Erwartetes Verhalten**

Ist im Handy UI
**Schritte um den Fehler nachvollziehen zu können**

Hintergrund ändern
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

2560x1440
**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/58612983/2642d871-8c6c-412a-badf-a578bc92417f)

**Comment by simplycach** [comment]
fixed
