### ISSUE TITLE
Folie der Sanchez ändert sich bei jedem Ein/Ausparken

### ISSUE THREAD

**Issue by ZirbelR** [mexyn/statev_v2_issues#301]
Richie Zirbel

21.11.2020 12:20

Sanchez ändert Folie

Folie Bleibt gleich

Sanchez mehrmals ausparken

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/70246255/99876064-a5496f80-2bf4-11eb-8ba7-6d9d820dac9d.png)
![image](https://user-images.githubusercontent.com/70246255/99876083-bd20f380-2bf4-11eb-9cc9-4867e545dc60.png)

**Comment by DonVitoDiangelo** [comment]
Einmal zum Tuning und eine feste rauf klatschen. Sollte das Problem dann beheben.

**Comment by ZirbelR** [comment]
Tunen ändert bei jedem ändern der Livery auf eine Random Livery.

Einfach mehrmals die verschiedenen Folien durchgehen, z.B. Typ 1 ist jedes mal eine andere.

**Comment by Chrinis007** [comment]
Genau das selbe bei der Folierung von RTW‘s

**Comment by its4l3x** [comment]
Unterschieden muss hier zwischen Emergency Liverys und normalen Liverys bei Normalofahrzeugen. altV hat generell ein Problem mit den Liveries, welches sich seit Monaten schon zieht. Das mit den normalen Liveries sollte klappen, wiederrum die Emergency Liverys würden derzeit nicht klappen

**Comment by Chrinis007** [comment]
Werden die Energency Folien Gefixed?

**Comment by its4l3x** [comment]
Nein. Hatte ich doch oben geschrieben gehabt, dass dies ein altV Bug sei. Man müsste sich das bei der Sanchez nochmal genauer anschauen, ob diese ein Sonderfall ist.

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/746
