### ISSUE TITLE
Item Verschwindet aus Inventar

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3011]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Samuel Navarro
**Auftrittszeitpunkt (Datum / Uhrzeit)**

17.02 ca. 15 Uhr
**Beobachtetes Verhalten**

Es wurde mit rechtsklick auf "Plastik Fass" geklickt im Auto und die Meldung "Du kannst es hier nicht verwenden" kam. Das Item ist daraufhin verschwunden
**Erwartetes Verhalten**

Meldung kommt aber Item bleibt
**Schritte um den Fehler nachvollziehen zu können**

Sitze im Auto und mache Rechtsklick auf "Plastik Fass"
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://streamable.com/80j76p

**Comment by simplycach** [comment]
Bitte nicht in Fahrzeugen placeable Items verwenden.

**Comment by SHaagmann** [comment]
Ja würde ich auch nicht machen sollten da trotzdem nicht verschwinden 👀

**Comment by CrazyKee** [comment]
Sollte zum nächsten Update behoben sein
