### ISSUE TITLE
Text in der öffentlichen Fabrik

### ISSUE THREAD

**Issue by coresync2k** [mexyn/statev_v2_issues#3012]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Jake Parker

17.02.2024 - ca 16:35

**Beobachtetes Verhalten**
Wenn man am Verarbeiten ist ( Orangen zB ) kommt folgende Meldung wenn man nicht mehr Genug Items hat.
https://gyazo.com/f4d7e0479f6886b28a8b2322a9f3b751

**Erwartetes Verhalten**
Ein Hinweis mit -> "Du hast leider nicht genug ITEMNAME im Inventar"

**Schritte um den Fehler nachvollziehen zu können**
Einfach zuwenig Items nach einem Durchlauf im Inventar haben zB 8

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/f4d7e0479f6886b28a8b2322a9f3b751

**Comment by simplycach** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Publicfactory Text](https://trello.com/c/5Ja2tEaL/284-publicfactory-text)

**Comment by simplycach** [comment]
@coresync2k Schau mal ob der Fehler noch auftritt bei dir.

**Comment by coresync2k** [comment]
Fehler ist behoben, danke :)
