### ISSUE TITLE
Probleme mit dem Dispatcher BCSO

### ISSUE THREAD

**Issue by BCSOFoley** [mexyn/statev_v2_issues#3013]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

John Foley

17.02.2024 15:00 bis 19:00

1. Wenn man sich als Dispatcher einstempelt sollte man ein Akkustisches Signal bekommen sobald ein Dispatch rein kommt dies Passiert nicht und  erschwert somit die Arbeit am Controller
2.  Das übersenden von Dispatches an andere Behörden funktioniert nicht
3. Bei manchen Dispatches gab es probleme diese für die Einheiten frei zu geben
4. Die Funkverbindung zwischen den Behörden über Funk funktioniert nicht mit mehreren Personen geprüft keiner kam durch
5. Beim Anrufen von den Notdiensten über das Handy kann man nicht auflegen sollte die Warteschlange zulange sein der Ton der Warteschlange bleibt bestehen selbst wenn man das Handy abrüstet

**Comment by simplycach** [comment]
Punkt 5. bereits fixed.

**Comment by simplycach** [comment]
Sind die Bugs noch vorhanden ?

**Comment by simplycach** [comment]
Sollte soweit fixed sein, wenn nicht bitte hier nochmal in die Karte schreiben.
