### ISSUE TITLE
Lippenbewegung trotz mute

### ISSUE THREAD

**Issue by DrJaneX** [mexyn/statev_v2_issues#3014]
**Character Name**
Jane Mei

**Auftrittszeitpunkt (Datum / Uhrzeit)**
ca. 19:15 Uhr

**Beobachtetes Verhalten**
Mikro ist gemutet, Lippen des Chars bewegen sich trotzdem

**Erwartetes Verhalten**
MIkro ist gemutet, Lippen des Chars bewegen sich nicht

**Schritte um den Fehler nachvollziehen zu können**
muten, dabei reden und auf Lippenbewegung achten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
-

**Comment by simplycach** [comment]
Das siehst nur du, andere Leute können das nicht sehen.

**Comment by simplycach** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Lippensync trotz mute](https://trello.com/c/cUfrU26K/283-lippensync-trotz-mute)

**Comment by simplycach** [comment]
Also wenn du gemutet bist bewegen sich die Lippen, das siehst in dem Fall nur du. Aber bei manchen Leuten bewegen sich die Lippen noch nach wenn man vorher gesprochen hat, ist dir das auch schon aufgefallen ?

**Comment by DrJaneX** [comment]
ja, das ist bei mir auch so

**Comment by simplycach** [comment]
Das Muten sollte jetzt gefixt sein, dass deine Lippen sich bewegen. An dem anderen sind wir dran.
