### ISSUE TITLE
Overlay verschoben

### ISSUE THREAD

**Issue by l1llean** [mexyn/statev_v2_issues#3015]
Charaktername:
Robyn_Banks

Auftrittszeitpunkt:
17.02. - ~19:45

**Beobachtetes Verhalten**
Overlay bzw.  der "Vorschau" Button verschiebt sich, wenn ich versuche mein Hintergrund am Handy zu ändern & Änderung kann nicht durchgeführt werden

**Erwartetes Verhalten**
Button befindet sich auf dem Handy und Hintergrundänderung möglich

**Schritte um den Fehler nachvollziehen zu können**
Auf "eigener Hintergrund" drücken und dann verschiebt sich der Button schon

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
2560x1440

**Optional: Video / Bilder des Fehlers**
![Bug Overlay](https://github.com/eiksch/statev_v3_issues/assets/160354080/2183358d-3cab-498c-b8e7-e3c20854e00b)

**Comment by simplycach** [comment]
Gibt bereits nen offenen Bugtracker, danke dir trotzdem.
