### ISSUE TITLE
BMX Sprung extrem hoch

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#3016]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Kayden Ryles

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Wenn man mit dem BMX springt, dann springt man extrem hoch

**Erwartetes Verhalten**
Keine übermensch Sprünge so wie in v2

**Schritte um den Fehler nachvollziehen zu können**
BMX fahren und springen

**Comment by Erumeldor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BMX springen viel zu hoch](https://trello.com/c/z3JkItLO/306-bmx-springen-viel-zu-hoch)

**Comment by simplycach** [comment]
Next Update fixed voraussichtlich
