### ISSUE TITLE
Konto Probleme/ Kein Harz, Nur abbuchungen

### ISSUE THREAD

**Issue by Elfengames** [mexyn/statev_v2_issues#3017]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Mit welchem Character wurde das Verhalten in-game ausgelöst/beobachtet**
Izaac_Baker

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Im laufe des Tages 17.02.2024 

**Beobachtetes Verhalten**
Es wird nur Geld abgebucht vom Fahrzeug Verleih nicht vom Hotel Zimmer zudem kommt kein Harz

**Erwartetes Verhalten**
Alle abzüge und einkünfte kommen rein

**Schritte um den Fehler nachvollziehen zu können**
Gute frage nächste Frage

**Optional: Video / Bilder des Fehlers**
![Screenshot_48](https://github.com/eiksch/statev_v3_issues/assets/160355710/bccbfe63-34c7-4cea-9d9e-52ec2b296b55)
![Screenshot_49](https://github.com/eiksch/statev_v3_issues/assets/160355710/3c9d2032-bf4d-47b7-8cd0-10141060c489)

**Comment by simplycach** [comment]
Hast du mittlerweile schon Abbuchungen bekommen ?
