### ISSUE TITLE
Verhalten bei der Schwefelmine

### ISSUE THREAD

**Issue by ZacCooperr** [mexyn/statev_v2_issues#3018]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Zac_Connor

**Auftrittszeitpunkt (Datum / Uhrzeit)**

17.02.2024 / 20:30 Uhr

**Beobachtetes Verhalten**

Guten Abend zusammen
ich bin aktuell zusammen mit einem Freund in der Schwefelmine und wir erhalten verhältnungsmäßig viel zu viel unterschiedliche Ressourcen. 
Bei einem zufälligen Gespräch wie weit der andere ist, ist es uns aufgefallen und haben die Inventare verglichen. 
Da wir uns auch außerhalb kennen, hat Er mir für das Ticket sein Inventar geschickt.

**Update:**
Auch nach einem Restart vom Char Zac_Connor, gleiches verhalten.

**Erwartetes Verhalten**

Hauptsächlich sollte man in der Schwefelmine, auch Schwefelseteine erhalten.

**Schritte um den Fehler nachvollziehen zu können**

Char Zac_Connor baut die Punkte in der Schwefelmine ab und bekommt neben Schwefel unerwartet viel Erze heraus.
Bei Benjamin_Stark hauptsächlich Schwefelsteine.

**Optional: Video / Bilder des Fehlers**

Inventar nach paar Punkten von: Benjamin_Stark
https://pic.statev.de/i/HPlHuU.png

Inventar nach paar Punkten von: Zac_Connor
https://pic.statev.de/i/HPlPmy.png

**Comment by simplycach** [comment]
Das ist völlig normal, dass wird Prozentual anders berechnet.
