### ISSUE TITLE
Keine Gebühren beim Geld abheben

### ISSUE THREAD

**Issue by QA-Pregon** [mexyn/statev_v2_issues#3019]
**Character Name**
David Danilov

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.2.2024, 20:24:47

**Beobachtetes Verhalten**
Geld abgehoben, 8$ auf der Hand, 1258 aufm Konto
250 Abgehoben und dann 258 auf der hand und 1008 aufm Konto
Heißt also nirgends gingen Gebühren verloren

**Erwartetes Verhalten**
Vom Konto gehen zusätzlich 5% des Geldes an Gebühren ab oder die Ausgabe Info wird ohne Gebühren angezeigt

**Schritte um den Fehler nachvollziehen zu können**
Geld abheben

**Comment by Domeex3** [comment]
Ist der Fehler bei dir immer Reproduzierbar?

**Comment by QA-Pregon** [comment]
> Ist der Fehler bei dir immer Reproduzierbar?

Ich teste das gleich mal aus

**Comment by ZacCooperr** [comment]
Ja auch bei einem Relog besteht bei mir dieses Verhalten.

**Comment by QA-Pregon** [comment]
passt glaub jz
