### ISSUE TITLE
Restöl ins Inventar nach Produktion

### ISSUE THREAD

**Issue by l1llean** [mexyn/statev_v2_issues#3020]
*Übernommen von Ticket*

Charname - Liam Dixon / Discord - longunso

aufgetreten:
2x am 17.02.2024  (zw. 18 - 21 Uhr)

**Beobachtetes Verhalten**
Öl wurde zu Benzin verarbeitet und die Restmenge wurde, statt ins Lager/Tanker, ins Inventar verschoben

**Erwartetes Verhalten**
Restmenge sollte im Lager/Tanker bleiben 

**Schritte um den Fehler nachvollziehen zu können**
Einfache Verarbeitung von Öl zu Benzin

![image](https://github.com/eiksch/statev_v3_issues/assets/160354080/46a2266d-d198-4f43-9cd5-892947227408)

**Comment by Domeex3** [comment]
Hi, was genau hast du gemacht? Du bist quasi mit 450l Öl an die Refinery, hast die 450kg in das Lager (500kg) gepackt und wann hast du das ins Inventar bekommen?

**Comment by l1llean** [comment]
Grüße dich,
kann nur von den Erzählungen aus dem Ticket reden - der konnte sein GitHub Passwort nicht mehr zurücksetzen
Das war quasi das letzte Öl was übrig bleibt, also von der allerletzen Produktion

**Comment by MarkHarland** [comment]
Nicht reproduzierbar

**Comment by simplycach** [comment]
Wird in Zukunft nicht mehr relevant sein.
