### ISSUE TITLE
Mystique bug

### ISSUE THREAD

**Issue by Toby-cmd** [mexyn/statev_v2_issues#3021]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Sam Braddock

Sam Braddock

17.02 gegen 22 Uhr

Ich habe einen auftrag von Mystice bekommen einen Laden Auszurauben habe ich getan ich habe draht gefunden es kam abere keine meldung das ich zurieck kann und das abgeben kann daraufhin habe ich alle roten kreise abgearbeitet \ immer noch keine meldung \ daraufhin yuruck gefahren und dann kommt nur die Meldung wie im Bild was ich mit sende

DAs ich die Mission abgeben kann

**Optional: Video / Bilder des Fehlers**

![Screenshot 2024-02-17 225717](https://github.com/eiksch/statev_v3_issues/assets/69426336/80589443-e152-4707-9aaf-82d73445a013)

**Comment by Toby-cmd** [comment]
Zusaty info nach Relog besteht das Problem weiterhin

**Comment by MarkHarland** [comment]
Moin hast du wirklich alle Roten Punkte abgearbeitet ? Da wir diesen Bug aktuell nicht rebuild bekommen. Hast du eventuell einen Video? Ist das Problem nochmal aufgetreten ?

**Comment by Toby-cmd** [comment]
https://youtu.be/FYxfHsgJZNQ wird aber noch verarbeitet aktuell // im hinteren raum habe ich angefangen ich hatte alle Punkte abgearbeitet

**Comment by MarkHarland** [comment]
dank dir für das Video wir gehen den mal nach

**Comment by simplycach** [comment]
Sollte fixed sein, wenn nicht bitte nochmal aufmachen.
