### ISSUE TITLE
Pseudonym Menu stuck

### ISSUE THREAD

**Issue by Toby-cmd** [mexyn/statev_v2_issues#3022]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Sam Braddock

Sam Braddock

23:40 Uhr
 

Pseudonym aendern beim Racing geht nicht man klickt auf aender und es passiert nichts und man bleibt im menu stuck

Button Click / Pseudonym aendern

Gehe zum Racing Point / Klicke auf Pseudonym aendern / Sieh den Fehler

**Comment by Domeex3** [comment]
#3006 Bereits bekannt :)
