### ISSUE TITLE
Shopüberfall Barbershop Southside

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#3023]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Kayden Ryles, Kiana Kayen

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01:40 ca 18.02.2024

**Beobachtetes Verhalten**
Sind am Store angekommen und haben angefangen zu überfallen
Dann ist Kiana an den Stuhl und wollte den nehmen und kriegte die Meldung invalid animation.
Danach war der Punkt lockt mit "Hier wird bereits gearbeitet"

**Erwartetes Verhalten**
Alle Punkte sollten easy gehen

**Comment by TheOutburst** [comment]
könnte next update fixed sein
wenn nicht würd mir nen Video helfen

**Comment by simplycach** [comment]
@DrGrizzlY17 War das wieder möglich ?

**Comment by DrGrizzlY17** [comment]
War gestern noch da hab aber mit Erwin privat geschrieben, der hat es gefixt. Sollte dann nachm nächsten update fix sein.
