### ISSUE TITLE
Autodiebstahl - Auto lässt sich nicht abgeben

### ISSUE THREAD

**Issue by SirAres** [mexyn/statev_v2_issues#3024]
Carter Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**
18.02.24 - 01:20 Uhr

**Beobachtetes Verhalten**
Beim ersten Auto Diebstahl ging das Symbol der Fremden Garage nicht weg. Beim 3ten Autodiebstahl sollte ich an die gleiche Stelle zurückkehren und dort lief der Anzeigebalken die ganze Zeit durch. Das Auto konnte nicht abgegeben werden.

**Erwartetes Verhalten**
Nach der Mission verschwindet das Symbol und man kann seine Autos wieder normal abgeben.

**Schritte um den Fehler nachvollziehen zu können**
Auto klauen und abgeben und schauen ob das Symbol besteht. Wenn ja, wieder Autos klauen und solange bis das gleiche Garagen Symbol kommt wie beim ersten mal. Auto versuchen abzugeben.

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/87204556/3c09a280-19ce-4758-b123-d184d2d87ffc)

Video wie der Balken durchläuft hätte ich auch xD

**Comment by MarkHarland** [comment]
Ist dieses Problem nur bei diesen Abgabepunkt aufgetreten ?

**Comment by SirAres** [comment]
Ist bisher nur einmal bei diesem Abgabepunkt aufgetreten. 
Ansonsten bisher alles Top gewesen. Hatte aber bis jetzt auch den Abgabepunkt nicht mehr.
