### ISSUE TITLE
Wegpunkt Shoprob Paleto Blvd 68

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#3026]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Kayden Ryles

**Beobachtetes Verhalten**
Guckt Screenshots :D
Das ist der Shoprob von Knox

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/70150988/99bebb5e-ffa4-435e-b967-f5bccd657aec)
![image](https://github.com/eiksch/statev_v3_issues/assets/70150988/3d315ef1-49dd-4e2d-a7a0-02c29955daad)

**Comment by DrGrizzlY17** [comment]
Das ist der Auftrag zum Barbershop
![image](https://github.com/eiksch/statev_v3_issues/assets/70150988/5434bf44-58ad-49df-8bc0-e099bcea1d0a)
![image](https://github.com/eiksch/statev_v3_issues/assets/70150988/4d444798-f15c-4104-b31d-c48690b82ac9)

**Comment by simplycach** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Wegpunkt falsch Shopraub](https://trello.com/c/sCkFNKH8/282-wegpunkt-falsch-shopraub)

**Comment by simplycach** [comment]
fixed
