### ISSUE TITLE
Crimeshop Klappmesser Text

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#3027]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Beobachtetes Verhalten**
Jo der Text im Shop passt nicht ganz zum Item :D

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/70150988/951c853a-0817-4d3d-bd02-50906ad6e269)

**Comment by TheOutburst** [comment]
next update fixed
