### ISSUE TITLE
Begrenzer lässt sich nicht aktivieren

### ISSUE THREAD

**Issue by TheMonar** [mexyn/statev_v2_issues#3028]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Bitte die Vorlage unten vollständig ausfüllen**
Enzo Diromano
**Mit welchem Character wurde das Verhalten in-game ausgelöst/beobachtet**
Enzo Diromano

**Wann exakt (Datum / Uhrzeit) ist der Fehler beobachtet worden**
dauerhaft
**Beobachtetes Verhalten**
beim Neustart funktioniert der Begrenzer. Sobald man das Fahrzeug verlässt und wieder ins Fahrzeug steigt, dabei ist es egal, welches Auto man nimmt. dann lässt sich der Begrenzer nicht mehr einschalten

**Erwartetes Verhalten**
Über die Taste "ENDE" sollte man den Begrenzer zu jeder Zeit einschalten können, bei zu hoher Geschwindigkeit erhält man ggfs ne Meldung

**Schritte um den Fehler nachvollziehen zu können**
man fährt mit dem Begrenzer. Steigt aus dem Fahrzeug aus, macht irgendwelche Aufgaben oder sonst was und beim Einsteigen lässt sich der Begrenzer nicht aktivieren

**Comment by simplycach** [comment]
Ist bereits offen.

**Comment by evanhaugestatev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TEST KARTE](https://trello.com/c/CCakX1N0/287-test-karte)
