### ISSUE TITLE
Shoprob Bob Muller kann nicht abgegeben werden

### ISSUE THREAD

**Issue by Icceetea** [mexyn/statev_v2_issues#3029]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Quintavious_Carter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
18.02. ungefähr 15 Uhr
17.02. ungefähr 17 Uhr
**Beobachtetes Verhalten**
Wenn man beim Shoprob zum Bob Mullet (South Blvd. Del Perro 1337) muss und alle Marker abgearbeitet hat, erscheint nicht dass man die benötigten Informationen hat. Das ganze ist bei mir schon 2 mal aufgetreten, Immer bei dieser Mission.

**Erwartetes Verhalten**
Nachdem man alle Marker abgearbeitet hat, sollte man die Informationen haben und die Mission abgeben können.

**Schritte um den Fehler nachvollziehen zu können**
-Shoprobmission annehmen und Bob Mullet (South Blvd. Del Perro 1337) bekommen.
-Zum Shoprob fahren und die Marker abarbeiten
-Sehen dass man die mission nicht vervollständigt hat

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Hast du die Mission alleine gemacht ?

**Comment by simplycach** [comment]
fixed
