### ISSUE TITLE
Notruf spinnt

### ISSUE THREAD

**Issue by SirSvenselot** [mexyn/statev_v2_issues#3030]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Jake_Michaelson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
z.b. 18.02. 1:38 Uhr
**Beobachtetes Verhalten**
Wenn man auf "Notruf absetzen" klickt, geht die Warteschleifenmusik an. Das Fenster im Handy ändert sich aber nicht und man kann den Notruf weder abbrechen noch einen Neuen absetzen, da angeblich einer läuft.
So weiß man nicht, ob der Notruf jetzt wirklich durch ging, weil nach mehreren Minuten des Wartens würde man ihn dann gerne abbrechen. Wenn man das Handy ausschaltet, läuft die Musik weiter.

**Erwartetes Verhalten**
Anzeige im Handy wieder so vie früher (Warteschlangenposition anzeigen oder was davor auch immer da stand)

**Schritte um den Fehler nachvollziehen zu können**
Notruf absetzen

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/96785542/59f1ff9b-6a98-4c45-9a5f-7b19b3c5c9f4)

**Comment by evanhaugestatev** [comment]
Wir konnten das Verhalten leider nicht reproduzieren. Ist es nochmal aufgetreten? Gibt es vielleicht ein Video davon?

**Comment by SirSvenselot** [comment]
Das wurde gestern um 17:05 Uhr von Timste2707 auch gemeldet.
Ich schau die Tage nochmal, wenn ich IC bin - habs leider nicht auf Video

**Comment by evanhaugestatev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Leitstelle anrufen Soundbug](https://trello.com/c/lUk4vogc/323-leitstelle-anrufen-soundbug)

**Comment by simplycach** [comment]
fixed
