### ISSUE TITLE
Fahrzeuge nach Serverrestart immer offen

### ISSUE THREAD

**Issue by Raccoonscityttv** [mexyn/statev_v2_issues#3032]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Jackson_Harrison

Jackson_Harrison
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Zum Server Restart
**Beobachtetes Verhalten**

Auto vor Restart abschlossen nach Restart war das Auto aufgeschlossen
**Erwartetes Verhalten**

Nach Restart sollte das Auto Abgeschlossen sein
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by coresync2k** [comment]
Jap, das haben wir auch, vorhin haben wir es 3x überprüft, das Fahrzeug war zu, 1 Server Restart und das Fahrzeug war offen

**Comment by evanhaugestatev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fahrzeuge nach Serverrestart offen](https://trello.com/c/OGU5j5O9/313-fahrzeuge-nach-serverrestart-offen)

**Comment by simplycach** [comment]
fixed
