### ISSUE TITLE
Firmenmarker blockieren Shoprob

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#3033]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Kayden Ryles

**Beobachtetes Verhalten**
Bei Frisören die gekaufter wurden blockieren die Marker die Shoprob Marker

**Erwartetes Verhalten**
Marker sollten nicht blockiert sein^^

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/70150988/a63409e3-a86a-4ad9-b2e4-c87966c291bf)

**Comment by TheOutburst** [comment]
next update fixed
