### ISSUE TITLE
Fahrzeuge nach Restart immer aufgeschlossen

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#3034]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Nach jedem Restart

**Beobachtetes Verhalten**
Nach jedem Restart sind unsere Autos und BMX aufgeschlossen

**Erwartetes Verhalten**
Fahrzeuge sollten den State behalten den sie vor dem Restart

**Comment by coresync2k** [comment]
Jap, das haben wir auch, vorhin haben wir 3x überprüft das Fahrzeug war zu, 1 Server Restart und das Fahrzeug war offen

**Comment by DrGrizzlY17** [comment]
ok duplicate
