### ISSUE TITLE
Patreon verlinkung nicht Möglich

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3035]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Seit V3 Release
**Beobachtetes Verhalten**

Beim Knopf "Patreon Verlinkung" kommt nichts
**Erwartetes Verhalten**

Verlinkung klappt
**Schritte um den Fehler nachvollziehen zu können**

VNet öffnen, auf Verlinkung gehen 
**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/58612983/09a473cd-5704-4770-842d-e3dd4d46e840)

**Comment by simplycach** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Patreon Sync nicht möglich](https://trello.com/c/FQRSqVGp/308-patreon-sync-nicht-m%C3%B6glich)

**Comment by rodistic** [comment]
fixed @simplycach
