### ISSUE TITLE
HartzV wird nicht aufs Konto überwiesen

### ISSUE THREAD

**Issue by Dennymaru32** [mexyn/statev_v2_issues#3036]
**Character Name**
Daniel Knight

**Auftrittszeitpunkt (Datum / Uhrzeit)**
18.02.2024 - 19.02.2024 Zwischen 21 Uhr und 01:00

**Beobachtetes Verhalten**
Hartz wird nicht überwiesen und daher können die Autos / Wohnungen nicht abgebucht werden

**Erwartetes Verhalten**
Hartz wird aufs Konto überwiesen

**Schritte um den Fehler nachvollziehen zu können**
Gute Frage... bei anderen Spielern soll es gehen

**Optional: Video / Bilder des Fehlers**

![Grand Theft Auto V Screenshot 2024 02 19 - 00 49 43 10](https://github.com/eiksch/statev_v3_issues/assets/160437543/36f2dfc0-a037-4aa4-8a6c-3aa46eb466e1)
![Grand Theft Auto V Screenshot 2024 02 19 - 00 48 42 38](https://github.com/eiksch/statev_v3_issues/assets/160437543/96d50504-2f73-4aaf-a9bf-367a9405a8d0)

**Comment by Dennymaru32** [comment]
Übrigens bin ich jetzt umgezogen in ein anderes Appartment / Motel und kriege jetzt sogar die meldung, dass ich die Wohnung verloren habe (bin aber wenn ich die Wohnung betrete noch als Mieter angegeben)
![Grand Theft Auto V Screenshot 2024 02 19 - 01 51 48 74](https://github.com/eiksch/statev_v3_issues/assets/160437543/547d7f48-7d9e-47a6-a810-ecdf7d0d12a4)
![Grand Theft Auto V Screenshot 2024 02 19 - 01 55 02 59](https://github.com/eiksch/statev_v3_issues/assets/160437543/75d86f4f-9e7f-48d8-8c86-4c6391ec3350)

**Comment by simplycach** [comment]
Hast du mittlerweile HartzV bekommen ?

**Comment by Dennymaru32** [comment]
Bin ab 17:30 ca wieder IC und kann dann berichten... war bis ca 01:00 Uhr IC und hatte in der Zeit 3 mal diese oben genannte Meldung.

**Comment by evanhaugestatev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [HartzV](https://trello.com/c/FYyblSf5/317-hartzv)

**Comment by Dennymaru32** [comment]
Also HartzV wird immernoch nicht überwiesen! Habe jetzt schon 6x ca kein Hartz bekommen und habe jetzt von meinem letzten Geld IC was zu Essen gekauft... so langsam wird es lebensbedrohlich xD
![Grand Theft Auto V Screenshot 2024 02 19 - 18 24 06 07](https://github.com/eiksch/statev_v3_issues/assets/160437543/1469bcdb-6037-48a3-bf96-8d921779f9b1)

**Comment by Dennymaru32** [comment]
Sorry will hier nicht spammen... weiß nicht ob die Restarts teils deswegen waren. Aber Problem besteht weiterhin!
![Grand Theft Auto V Screenshot 2024 02 19 - 21 12 28 18](https://github.com/eiksch/statev_v3_issues/assets/160437543/7b8e4ece-d7a9-4c48-b1fa-ed3056cde3eb)

**Comment by evanhaugestatev** [comment]
Wird konnten bereits das Problem reproduzieren und versuchen eine Lösung zu finden. Bitte versuche immer min. 150 Dollar auf dem Konto zu haben. Das könnte vorerst helfen, bis wir eine Lösung gefunden haben.

**Comment by Dennymaru32** [comment]
Alles klar... dann muss ich nur schauen, wie ich an das Geld rankomme! Aber das sollte machbar sein! Danke fürs erste! :)
