### ISSUE TITLE
Bug auf Lifeinvader - Post wird temporär von sich selbst geliked bis LI App neugestartet wird

### ISSUE THREAD

**Issue by NightcoreCEO** [mexyn/statev_v2_issues#3038]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name** 

Kayo_Vik (Lifeinvader Username: DJ_K)

**Auftrittszeitpunkt (Datum / Uhrzeit)**

regelmäßig, letzter Zeitpunkt 19.02.24 14:34 Uhr

**Beobachtetes Verhalten**

Wenn in Lifeinvader ein Post erstellt wird, und dieser kein Bild enthält, dann hat der Post automatisch nach Veröffentlichung einen Like von sich selbst. Dieses Like fällt wieder weg, sobald die LI App einmal geschlossen und neu geöffnet wird. 

**Erwartetes Verhalten**

Neu erstellte Posts sollten direkt bei Erstellung 0 Likes haben.

**Schritte um den Fehler nachvollziehen zu können**

Login auf LI --> neuen Post ohne Bild erstellen --> Posten --> Post hat temporäres Like --> LI App neustarten --> Like ist weg

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot 2024-02-19 143502](https://github.com/eiksch/statev_v3_issues/assets/78972490/4192a13c-dceb-4d22-ab09-e1aa56d2898b)
![Screenshot 2024-02-19 144849](https://github.com/eiksch/statev_v3_issues/assets/78972490/fb5d3e3e-3036-445b-93f0-9624bc1bb5e7)

**Comment by rodistic** [comment]
Ayyy Gude,

sollte beim nächsten Update fixed sein!
