### ISSUE TITLE
Bug auf Lifeinvader - Aktivitäten werden nicht richtig dargestellt / aktualisiert & Eigene Antworten auf Kommentare erscheinen als Aktivität

### ISSUE THREAD

**Issue by NightcoreCEO** [mexyn/statev_v2_issues#3039]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Kayo_Vik (Lifeinvader Username: DJ_K)

**Auftrittszeitpunkt (Datum / Uhrzeit)**

regelmäßig, letzter Zeitpunkt 19.02.24 14:34 Uhr

**Beobachtetes Verhalten**

Die Aktivitäten aktualisieren sich nur teilweise, es fehlen ein Teil der Benachrichtigungen (z.B. Kommentare, Likes oder neue stalker) und es werden "eigen-verfasste Antworten" auf ein Kommentar als Aktivität angezeigt.

**Erwartetes Verhalten**

Die Aktivitäten sollten alle vollständig angezeigt werden, und eine Antwort von einem selbst auf ein Kommentar sollte nicht in den Aktivitäten angezeigt werden. (Neuste meiner Aktivitäten sollte eigentlich "Nike hat dir ein Like gegeben" sein)

**Schritte um den Fehler nachvollziehen zu können**

Login auf LI --> Auf einen beliebigen einen Post mit einem Kommentar gehen --> auf diesen Kommentar mit "@Username [Antwort]" antworten --> Wird anschließend als eigene Aktivität angezeigt 
und für die das Nicht-aktualisieren der Aktivitäten eben warten bis jemand mit dem eigenen Profil interagiert.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot 2024-02-19 144911](https://github.com/eiksch/statev_v3_issues/assets/78972490/207eb19b-0acc-4873-ac3f-3d74b868eb6a)
![Screenshot 2024-02-19 150107](https://github.com/eiksch/statev_v3_issues/assets/78972490/b92fd140-e27e-412f-be03-e31178fb03b0)
![Screenshot 2024-02-19 150030](https://github.com/eiksch/statev_v3_issues/assets/78972490/2ce7ee41-3087-489b-aaf8-63a77c5b4793)

**Comment by NightcoreCEO** [comment]
Hier noch ein Bild von der Notification / Aktivität des eigenen Kommentares:
![Screenshot 2024-02-19 150234](https://github.com/eiksch/statev_v3_issues/assets/78972490/c68ec593-c465-47eb-bbef-f46cb52e3f3a)

**Comment by rodistic** [comment]
Ayyy Gude,

ist nach nächsten Update fixed
