### ISSUE TITLE
Verladepunkt versetzen Bitte 

### ISSUE THREAD

**Issue by Steve-Walker** [mexyn/statev_v2_issues#304]
**Steve_Walker**
Steve_Walker

**Zeitpunkt (Datum / Uhrzeit)**
21.11.2020 10uhr

**Beobachtetes Verhalten**
kann nicht abladen mit gröseren fahrzeugen 

**Erwartetes Verhalten**
bitte den punkt umsetzen 
![Desktop Screenshot 2020 11 21 - 12 13 20 54](https://user-images.githubusercontent.com/74819877/99876803-8dc0b580-2bf9-11eb-817a-5606f025d99b.png)

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Desktop Screenshot 2020 11 21 - 12 13 20 54](https://user-images.githubusercontent.com/74819877/99876810-a03aef00-2bf9-11eb-8e4b-4bc7fdfb2ec7.png)
![Desktop Screenshot 2020 11 21 - 13 02 00 62](https://user-images.githubusercontent.com/74819877/99876897-5c94b500-2bfa-11eb-84ad-6ab2fae6d56d.png)

**Comment by Steve-Walker** [comment]
ich bitte um hilfe danke

**Comment by DrGrizzlY17** [comment]
moved
