### ISSUE TITLE
Weniger Produkt beim HErstellen von Kunststoffgranulat

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#3041]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
 Charly Russo 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.02.2024 20:02

**Beobachtetes Verhalten**
Bei der öffentlichen Weberei wird aus 3 Kautschuk manchmal nur 1 Kunststoffgranulat hergestellt https://i.imgur.com/bjHLWBK.png

**Erwartetes Verhalten**
Es soll 2 - 4 Kunststoffgranulat hergestellt werden https://i.imgur.com/ODGoIql.png

**Schritte um den Fehler nachvollziehen zu können**
Kautschuk sammeln, Kunststoffgranulat in der öffentlichen Weberei herstellen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://i.imgur.com/bjHLWBK.png ,  https://i.imgur.com/ODGoIql.png

**Comment by coresync2k** [comment]
Oh, gut das du das machst, wollte das auch noch melden, ist bei mir auch schon desöfteren passiert.

**Comment by Erumeldor** [comment]
Hi!
Das hängt mit dem gewissen Verlustfaktor zusammen, den es in den Firmen gibt.
Bei einzelnen Produktionen würde das einfach scheitern, bei Kunststoffgranulat bekommst du dann nur eines der Items nicht. :)
