### ISSUE TITLE
Animationshotkeys sporadisch nicht funktionell

### ISSUE THREAD

**Issue by NightcoreCEO** [mexyn/statev_v2_issues#3042]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Kayo Vik

**Auftrittszeitpunkt (Datum / Uhrzeit)**

sporadisch immer mal wieder, letzter Zeitpunkt 19.02.24 19:59 Uhr

**Beobachtetes Verhalten**

Die den Animationen zugewiesenen Hotkeys funktionieren sporadisch nicht. Erkannt werden Sie, da die Zuweisung Animation --> Hotkey erfolgreich ist (siehe Video) die Ausführung durch Drücken der Hotkeys (im Falle des Videos Num 2) jedoch nicht startet

**Erwartetes Verhalten**

Animation wird nach Drücken des Hotkeys erfolgreich ausgeführt / gestartet.

**Schritte um den Fehler nachvollziehen zu können**

Schwierig zu beschreiben, da dieser Fehler nur sporadisch auftritt und meistens durch nen Game-Restart behoben werden kann. 
Das Fehlverhalten (wenn es auftritt) tritt direkt nach dem Login bereits auf und bisher war es bei mir nicht so, dass dies erst im Laufe des "Online-Seins" aufgetreten ist.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://github.com/eiksch/statev_v3_issues/assets/78972490/3976a98e-a282-4342-9155-29c031b40f83

**Comment by evanhaugestatev** [comment]
Vielen Dank für die Meldung. Ist bereits schon bekannt und mit einem anderen Fehler zusammenhängend. Der Übersicht halber wird der Issue geschlossen.

Zu verfolgen: #3000

**Comment by evanhaugestatev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hotkey/Funk bug](https://trello.com/c/ovxDVzlP/272-hotkey-funk-bug)

**Comment by simplycach** [comment]
nächstes Update fixed.
