### ISSUE TITLE
Zigaretten haben kein Prop

### ISSUE THREAD

**Issue by tr1kssi** [mexyn/statev_v2_issues#3043]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Jackson Rodriguez

**Auftrittszeitpunkt (Datum / Uhrzeit)**
permanent

**Beobachtetes Verhalten**
Wenn man sich eine Redwood Zigarette anzündet, ist das prop unsichtbar, die Glut vorne ist zu sehen

**Erwartetes Verhalten**
Zigarette sollte als ganzes zu sehen sein

**Schritte um den Fehler nachvollziehen zu können**

Packung Redwood Zigaretten anzünden

**Optional: Video / Bilder des Fehlers**
https://prnt.sc/nfqY1k_BxjOG

**Comment by SatyriaDine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Zigaretten haben kein Prop](https://trello.com/c/gtVQGsu0/327-zigaretten-haben-kein-prop)

**Comment by simplycach** [comment]
Ich habe das mal eben aufm Dev-Server sowie Live-Server getestet und hatte keine Probleme.
