### ISSUE TITLE
Lager Inventar anderes verhalten als Konto

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3044]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

20.02 8:35
**Beobachtetes Verhalten**

Wenn man die Anzahl der auf einer Seite zu sehenden Items hochstellt wird die liste nicht erweitert sonder eine Scrollbar angezeigt
**Erwartetes Verhalten**

Liste wird verlängert wie beim Konto
**Schritte um den Fehler nachvollziehen zu können**

Firmeninventar übers VNet öffnen. Anzahl der Items pro Seite erhöhen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

2560x1440
**Optional: Video / Bilder des Fehlers**

![2024-02-20_08h32_26-ezgif com-cut](https://github.com/eiksch/statev_v3_issues/assets/58612983/095d911c-13f2-4382-ad42-139f8cd08bf2)

**Comment by simplycach** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Lager Inventar anderes verhalten als Konto](https://trello.com/c/jR4oZeIM/333-lager-inventar-anderes-verhalten-als-konto)

**Comment by simplycach** [comment]
Ist so gewollt.
