### ISSUE TITLE
Ölfeld Pumpen/Map wird doppelt geladen

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#3045]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
James Carter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
jederzeit

**Beobachtetes Verhalten**
Die Pumpen sind doppelt. allerdings nicht alle.

**Erwartetes Verhalten**
immer nur eine Pumpe

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/70150887/b7a53c30-089b-4c0e-be85-799080d22004)

**Comment by simplycach** [comment]
Ich erkenne gerade nicht genau was du meinst ?

**Comment by TheBroady** [comment]
Es gibt einige Pumpen wo das Objekt der Pumpe doppelt vorhanden ist.
Dann Pumpen zwei pumpen ineinander :D

**Comment by simplycach** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Oil Pumpen doppelt](https://trello.com/c/Z6cQyciB/332-oil-pumpen-doppelt)

**Comment by evanhaugestatev** [comment]
Fix kommt beim nächsten Update. Vielen Dank fürs Melden.

**Comment by TheBroady** [comment]
Gerne
