### ISSUE TITLE
Gekauftes Haus wird nicht auf der Map angezeigt

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3046]
Hotellzimmer werden ja angezeigt, erworbene Häuseer nicht. (bei v2 Rotes Haus Icon)---

**Comment by Statev-Bonsai** [comment]
![Screenshot_18](https://github.com/eiksch/statev_v3_issues/assets/70241137/2bbb0117-15c6-4caf-8861-3d2a902c8879)

**Comment by simplycach** [comment]
Wann hast du es gekauft ?  Die Icons erscheinen erst mit dem nächsten Server - Restart.

**Comment by Statev-Bonsai** [comment]
gestern zum abend..

**Comment by simplycach** [comment]
Ja war noch kein Restart.

**Comment by Statev-Bonsai** [comment]
ach ja, lol...
da war ja was, ich beobachte das ;) dankeeeeeeeee

**Comment by simplycach** [comment]
Kein Problem :) ich würde das dann hier schließen wenn nicht mach gerne ein Ticket auf.
