### ISSUE TITLE
Bob mulet interior fehlen Stühle

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#3047]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Beobachtetes Verhalten**
Bob mulet interior fehlen Stühle
Bild sagt alles :D

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/70150988/d518f149-3d62-4d7a-b32d-1df8e7e90dc6)

**Comment by simplycach** [comment]
Sei doch ehrlich ihr habt die Stühle rausgeräumt.

**Comment by evanhaugestatev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Stühle im BobMulet fehlen](https://trello.com/c/v2TgzBX9/335-st%C3%BChle-im-bobmulet-fehlen)
