### ISSUE TITLE
Fehlerhaftes MLO

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#3048]
**Character Name**
Charly Russo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.02.2024 (Einmal Gegen 19 Uhr (500+ Spieler online) und einmal gegen 23:30 Uhr (200 Spieler online) mit zwei verschiedenen Leuten getestet)

**Beobachtetes Verhalten**
Das Italiano Cuisine Restaurant MLO ist ziemlich buggy, sobald man drinnen ist hört man die andere Person nicht mehr und die Charaktere verschwinden teilweise komplett. Hab das zu verschiedenen Uhrzeiten mit verschiedenen Leuten getestet, ist anscheinend unabhängig von der Spielerzahl.

https://www.youtube.com/watch?v=RxqLxUH__jk

**Erwartetes Verhalten**
Keine Probleme mit dem altV Voice und keine Scihtprobleme im MLO 

**Schritte um den Fehler nachvollziehen zu können**
MLO mit einer anderen Person durch die Vordertür betreten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
(Hab ausversehen meine eigene Stimme nicht aufgenommen upsi)
https://www.youtube.com/watch?v=RxqLxUH__jk

**Comment by evanhaugestatev** [comment]
Vielen Dank fürs Melden. Fehler wurde behoben und wird zeitnah auf den Live-Server integriert.
