### ISSUE TITLE
Handy zeigt 1 Ticket an aber nix ticket

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#3049]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Kayden_Ryles

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Nach Update

**Beobachtetes Verhalten**
Gucke Screenshots

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/70150988/04f923e1-8180-4ccc-8e28-b4acae7b553b)
![image](https://github.com/eiksch/statev_v3_issues/assets/70150988/41dfb202-f950-4261-8b1d-493a50b7cdae)

**Comment by coresync2k** [comment]
hatte ich heute auch, hatte von vor paar Tagen noch nen Ticket, hab das dann bezahlt, dann wars weg :)

**Comment by MarkHarland** [comment]
Heyho hast du das Ticket bezahlt und danach war es immer noch da ? Ist die Nachricht nach einen Relog weg gewesen?

**Comment by DrGrizzlY17** [comment]
> Heyho hast du das Ticket bezahlt und danach war es immer noch da ? Ist die Nachricht nach einen Relog weg gewesen?

ich hab das ticket bezahlt bevor das update gab mit den tickets

**Comment by DrGrizzlY17** [comment]
problem besteht immer noch

**Comment by DrGrizzlY17** [comment]
hab mir mittlerweile nen ticket gefangen und es wird mir nicht angezeigt
![image](https://github.com/eiksch/statev_v3_issues/assets/70150988/39b127e6-4e05-4613-86a1-070bfae5a932)
![image](https://github.com/eiksch/statev_v3_issues/assets/70150988/1a50be14-bbb1-4c6a-82b9-d74719499ebe)

**Comment by simplycach** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Blitzer stellen keine Tickets mehr aus](https://trello.com/c/qq425vLj/336-blitzer-stellen-keine-tickets-mehr-aus)

**Comment by simplycach** [comment]
next Update fixed
