### ISSUE TITLE
Kontakte in VNET nicht im Telefonbuch im Handy

### ISSUE THREAD

**Issue by Raccoonscityttv** [mexyn/statev_v2_issues#3052]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Jackson_Harrison

**Auftrittszeitpunkt (Datum / Uhrzeit)**

21.02.2024
**Beobachtetes Verhalten**
Wenn man eine Nummer im Tablet unter VNET einspeichert wird der Kontakt nicht ins Telefon übernommen, andersherum allerdings schon

**Erwartetes Verhalten**

kontakte sollten in beiden Richtungen übernommen werden
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by MarkHarland** [comment]
Dies funktioniert allerdings muss man dafür einmal das Handy neustarten damit die neue Nummer angezeigt wird
