### ISSUE TITLE
Schreibfehler Lifeinvader Verifizierungsmail

### ISSUE THREAD

**Issue by Domo01** [mexyn/statev_v2_issues#3056]
![IMG_2609](https://github.com/eiksch/statev_v3_issues/assets/140542423/92278825-36a1-4115-ad62-d21ee0c1706f)

Diese Mail -dient- als Aktivierungs V-Mail.

anstatt:

Diese Mail -dienst- als Aktivierungs V-Mail.

**Comment by rodistic** [comment]
Ayy Gude, fehler wurde behoben
