### ISSUE TITLE
Unsichtbarer Gegenstand aufn Ölfeld

### ISSUE THREAD

**Issue by StateVSergio** [mexyn/statev_v2_issues#3057]
Liam_Dixon

https://pic.statev.de/i/HPj8Pc.jpg

Da wo mein char steht muss etwas unsichtbares sein. Regelmäßig stehen dort auch defekte lkws. Ich bin persöhnlich auch schonmal reingefahren und Motorkontrollleuchte war rot.

**Comment by StateVSergio** [comment]
Wieso wurden die absperrungen weggemacht ? Existiert immernoch ;(

**Comment by simplycach** [comment]
Das Wissen wir nicht

**Comment by simplycach** [comment]
Hey wenn der Fehler nochmal vorkommt bitte nochmal bescheid geben.
