### ISSUE TITLE
Klamotten clipping

### ISSUE THREAD

**Issue by SauerkirscheJM** [mexyn/statev_v2_issues#3058]
Habe mit meinem Chrakter ein Oberteil gekauft, was in V2 schon buggy war. Dachte zu v3 wäre das gefixt worden. Ärgerlicherweise ist dem nicht so. Egal welche Konfiguration ich nutze, es clippt immer etwas durch. Habe auch schon mit Magic Top rumprobiert. 
Hänge euch mal Bilder an.

**Ist kein dringender Fall,** wollte es nur schonmal anmerken. Ist n schönes Oberteil und bin sicher nicht die Einzige, die es gerne nutzen würde.

Top: Boyfriend Jacket (in diesem beispiel [F] Coca-Cola Boyfriend Jacket )
![Oberteil1](https://github.com/eiksch/statev_v3_issues/assets/123385988/84a81329-6576-4918-87c7-ff5680e39d34)
![Oberteil2](https://github.com/eiksch/statev_v3_issues/assets/123385988/0b78842c-bbb3-4af0-b77f-576d41f03621)

**Comment by Enemyaa** [comment]
Das Modell wird in den nächsten Updates ausgetauscht!
