### ISSUE TITLE
Map Marker sind nicht mehr beschriftet

### ISSUE THREAD

**Issue by Kaycee91** [mexyn/statev_v2_issues#306]
Wie auf dem Bild zu erkennen fehlen bei manchen Farmspots die Map Marker Beschriftungen z.B. Kalmus, Die Wälder, Die Fischgründe usw 

![Map Bug](https://user-images.githubusercontent.com/38119374/99877696-36721380-2c00-11eb-9a1f-1167c4ea98ac.png)

**Comment by DonVitoDiangelo** [comment]
sind vorhanden, nur sind es so viele das rechts dieses Limit von 99 überstiegen wird.
