### ISSUE TITLE
Diesel / Benzin im eigenem Inventar

### ISSUE THREAD

**Issue by QA-Pregon** [mexyn/statev_v2_issues#3060]
David Danilov

21.02.2024 Ca. 23:00

Passiert:
Da ich immer 2 Touren Öl auf einmal verarbeite, hatte ich in der Öffentlichen Fabrik 500L Öl.
Als ich dieses zu Benzin verarbeitet habe, kam es vermutlich bei der ersten Umwandlung dazu, dass die öffentliche Fabrik als voll angesehen wurde und das Benzin in mein Inventar verschoben wurde
(Aussagen beruhen auf Vermutungen)

Sollte passieren:
Bevor das fertige Produkt verschoben wird, sollte zuerst der genutzte Rohstoff aus dem Inventar der Fabrik entfernt werden, um Platz zu schaffen, damit das Benzin auch dort wieder landen kann.

Nachvollziehen:
Mit vollem Lager in der öffentlichen Fertigung Öl in Diesel/Benzin umwandeln.

**Comment by SgtBoaz-Terry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Produktion öff. Raff landet in Spieler-Inventar](https://trello.com/c/Jo80Woi3/345-produktion-%C3%B6ff-raff-landet-in-spieler-inventar)
