### ISSUE TITLE
Netz Zitronenbild im VNET ist nicht vorhanden

### ISSUE THREAD

**Issue by coresync2k** [mexyn/statev_v2_issues#3061]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Egal welchem :)

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Das Bild von "Netz Zitronen" wird nicht angezeigt.

**Erwartetes Verhalten**
Das das Bild angezeigt wird

**Schritte um den Fehler nachvollziehen zu können**
Einfach VNET Ingame oder Extern öffnen und das Bild wird nicht geladen.

Ich weiss das ist kein schlimmer Fehler, wollte es dennoch melden :)

Danke für eure Arbeit

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by SgtBoaz-Terry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fehlendes Bild Zitronennetz VNET](https://trello.com/c/XvvvGNfR/344-fehlendes-bild-zitronennetz-vnet)

**Comment by simplycach** [comment]
fixed
