### ISSUE TITLE
Female Bandana auf Knot wechselt auf Male

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#3062]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Kiana_Kayen

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Wenn eine Frau ein Face Bandana anzieht und dann auf Knot wechselt ist es Male und kann nicht mehr angezogen werden

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/70150988/cbfe242e-14a4-4051-a1f4-82e0991b6474)
![image](https://github.com/eiksch/statev_v3_issues/assets/70150988/10e289b6-071a-4f73-947a-805c5bd046c8)

**Comment by simplycach** [comment]
fixed
