### ISSUE TITLE
Inventar rausgebuggt

### ISSUE THREAD

**Issue by AymsRx** [mexyn/statev_v2_issues#3063]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Jim_Kinley

22.02.2024 18:08

Beim öffnen des Inventares wurde angezeigt "1kg Fassungsvermögen" dann "########" und dann kam der Fehler.

Inventar öffnet sich ganz normal

I gedrückt und dann nochmal zum schließen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

![Screenshot_6](https://github.com/eiksch/statev_v3_issues/assets/123886465/d139991f-4efd-437a-b05a-62b1a055288f)

**Comment by simplycach** [comment]
Wir nehmen den neueren Bug.
