### ISSUE TITLE
Vorhandene Blitzer-Tickets werden im Handy/Tickets App nicht angezeigt

### ISSUE THREAD

**Issue by K0elschi** [mexyn/statev_v2_issues#3064]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Timothy_Goodsen

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.02.2024 / 19:09

**Beobachtetes Verhalten**
Vorhandene Blitzer-Tickets werden im Handy/Tickets App nicht angezeigt, obwohl in der Apps-Übersicht angezeigt wird, dass ein Ticket da ist.

**Erwartetes Verhalten**
Vorhandene Blitzer-Tickets werden im Handy/Tickets App angezeigt.

**Schritte um den Fehler nachvollziehen zu können**
Mit dem Auto blitzen lassen, Handy öffnen, Tickets App Symbol zeigt an, das ein Ticket da ist, Tickets App öffnen, es wird kein Ticket angezeigt.

**Optional: Video / Bilder des Fehlers**
![Screenshot 2024-02-22 190957](https://github.com/eiksch/statev_v3_issues/assets/160853816/0f0183af-02e5-4579-943d-51b0b5ecff7f)
![Screenshot 2024-02-22 191032](https://github.com/eiksch/statev_v3_issues/assets/160853816/506e8156-b380-417b-becc-65ba98e902a1)
![Screenshot 2024-02-22 191216](https://github.com/eiksch/statev_v3_issues/assets/160853816/166485c0-f9e6-4b4a-a155-dacfecb4e8e8)

**Comment by simplycach** [comment]
Wurde bereits in Bugtracker für aufgemacht.
