### ISSUE TITLE
Brechstangen

### ISSUE THREAD

**Issue by Bronze6** [mexyn/statev_v2_issues#3066]
Brechstangen sind nach den Ausrüsten nicht mehr nutzbar für ATM Raub

**Comment by simplycach** [comment]
Ist kein Bug, soll so sein.

**Comment by simplycach** [comment]
Hey, wir nehmen den Bug mal mit auf rechne aber nicht, damit dass es Zeitnah gefixt wird. Solange bitte die Brechstange nicht ausrüsten, damit wird sie unbrauchbar.

**Comment by simplycach** [comment]
Next Update fixed
