### ISSUE TITLE
24/7 Apotheke gibt bei Bandagenkauf keine Items ins Inventar

### ISSUE THREAD

**Issue by ShinzuJackson** [mexyn/statev_v2_issues#3067]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Shinzu Jackson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.02.2024 um 22:10

**Beobachtetes Verhalten**
Ich wollte 5 Bandagen in Harmony in der 24/7 Apotheke kaufen und hatte genügend Bargeld einstecken. Die grüne Meldung in der linken unteren Bildschirmecke hat den Kauf bestätigt. Bei dem Blick in mein Inventar musste ich dann feststellen, dass ich keine Bandagen hatte und mir das Geld abgezogen wurde.

**Erwartetes Verhalten**
Dass die Items beim Kauf auch ins Inventar kommen.

**Schritte um den Fehler nachvollziehen zu können**
In die Harmony 24/7 Apotheke gehen und Bandagen kaufen.

**Optional: Video / Bilder des Fehlers**
Kann ich gerne nachliefern muss nur leider los und habe es nicht mehr geschafft die Aufnahme für euch zu schneiden

**Comment by simplycach** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Apotheke Bandage wird nicht ins Invetar gemoved](https://trello.com/c/vHZRet2C/354-apotheke-bandage-wird-nicht-ins-invetar-gemoved)

**Comment by ShinzuJackson** [comment]
Ok jetzt wird es komplett weird. Habe gerade seit meinem Report gestern das erste mal wieder eingeloggt und habe nun die Bandagen, die ich gestern gekauft und nicht bekommen habe in meinem Rucksack.

**Comment by simplycach** [comment]
:D
