### ISSUE TITLE
Selbstgedrehte Zigarette Funktion ohne Funktion :D

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#3068]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Kayden Ryles

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.30 ca 23.12.24

**Beobachtetes Verhalten**
Wollte ne selbstgedrehte Zigarette anzünden. Nix passiert -> Zigarettenstummel.
Siehe Video

**Erwartetes Verhalten**
Zigarettenprob und Animation vorhanden

**Schritte um den Fehler nachvollziehen zu können**
Zigarette selbst drehen
Anzünden
Enttäuscht sein

**Optional: Video / Bilder des Fehlers**
https://cdn.discordapp.com/attachments/915211337292972052/1210348699805290536/zigarette_bug_clip.mp4?ex=65ea3c11&is=65d7c711&hm=1161db67d80b1601658f2a56566c10abe4cdbedb45b363d3ec413f1fec7ce608&

**Comment by simplycach** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Selbstgedrehte Zigarette Animation und Prop werden nicht getriggert.](https://trello.com/c/sTbbOn67/355-selbstgedrehte-zigarette-animation-und-prop-werden-nicht-getriggert)

**Comment by simplycach** [comment]
fixed.
