### ISSUE TITLE
Tempomat lässt sich nicht aktivieren

### ISSUE THREAD

**Issue by Shirobaka** [mexyn/statev_v2_issues#3069]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Ben Carter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.02.2024 23:35

**Beobachtetes Verhalten**
Der Tempomat lässt sich mit der ENDE Taste nicht einschalten.
Fahrzeug stand still, Motor war eingeschaltet.

**Erwartetes Verhalten**
Der Tempomat soll sich mit der ENDE Taste einschalten lassen

**Schritte um den Fehler nachvollziehen zu können**
ENDE Taste drücken.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Hey ist bereits offen, https://github.com/eiksch/statev_v3_issues/issues/3007
