### ISSUE TITLE
Phantoms und Auflieger warpen aufm Ölfeld

### ISSUE THREAD

**Issue by powerswissi** [mexyn/statev_v2_issues#307]
Heute 21.11.2020 ca 13.50Uhr

Phantom und Auflieger warpen in der Luft durch die Gegend.

Als der Phantom in die Viewrange gekommen is war er plötzlich ca 5 m in der Luft. Der Auflieger dahinter auch 5 m entfernt  und ca 5m in der Luft.. 

Auflieger schwankte nach links und rechts.. 

Komplette Viewrange hat er "geruckelt" "gewarped" .. hat mich letztendlich auch erwischt.. Schaden war real.

Tante Edith: Spieler die oben auf der Plattform stehen beim ölfeld.. werden nach unten teleportiert auf den Sand.. Und am schluss wieder nach oben auf die Plattform teleportiert

**Comment by r3sist3nt** [comment]
Siehe auch #323

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/370
