### ISSUE TITLE
Lifeinvader Bug - Trending Page nicht verfügbar

### ISSUE THREAD

**Issue by NightcoreCEO** [mexyn/statev_v2_issues#3070]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Kayo_Vik (LI Username: DJ_K)

**Auftrittszeitpunkt (Datum / Uhrzeit)**

22.02.24 23:50 Uhr

**Beobachtetes Verhalten**

Trending Page lädt nicht und sorgt dafür, das Lifeinvader App neu gestartet werden muss.

**Erwartetes Verhalten**

Trending Page zeigt trending Posts an

**Schritte um den Fehler nachvollziehen zu können**

LI App öffnen, Anmelden, Über die NavBar auf Trending Page gehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://github.com/eiksch/statev_v3_issues/assets/78972490/f1d38bd4-ae49-4dcf-b6a3-22fc40793600

**Comment by simplycach** [comment]
Wir haben grad ein update gemacht sollte wieder verfügbar sein.
