### ISSUE TITLE
Der Stepbro mag es nicht wenn man nummern aus der Konversation entfernt

### ISSUE THREAD

**Issue by Xymena** [mexyn/statev_v2_issues#3071]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Alice_Swan

**Auftrittszeitpunkt (Datum / Uhrzeit)**
6:00

**Beobachtetes Verhalten**
Beim Versuch eine Falsche Nummer aus einer Gruppen Konversation zu entfernen kommt es zur fehlermeldung :Error:Backend me please Stepbro!
**Erwartetes Verhalten**
Nummer Lässt sich entfernen

**Schritte um den Fehler nachvollziehen zu können**
Es wird eine Gruppe erstellt, versehentlich die falsche Nummerhinzugefügt.. es ist nicht möglich das diese durch den Gruppen eigentümmer entfernt wird. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/76626768/3cb331d4-b423-4ba1-83d9-707a0dcbd863)

**Comment by simplycach** [comment]
Mit dem nächsten Update fixed.
