### ISSUE TITLE
Blitzer Ecplise Tower optisch nicht vorhanden

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#3072]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Kayden Ryles

**Beobachtetes Verhalten**
Man wird am Eclipse Tower geblitzt obwohl dort kein Blitzer mehr optisch steht

**Erwartetes Verhalten**
No Blitzerino / Blitzerino optisch vorhanden

**Schritte um den Fehler nachvollziehen zu können**
Mit Mobsgeschwindigkeit am MD vorbei

**Comment by simplycach** [comment]
Hast mal nen Bild ?

**Comment by DrGrizzlY17** [comment]
Da is halt nix. Was soll ich da screenshotten :D Flieg in der Freecam halt hin

**Comment by simplycach** [comment]
Ich geb das mal weiter.

**Comment by DrGrizzlY17** [comment]
![image](https://github.com/eiksch/statev_v3_issues/assets/70150988/38cd13dd-22a5-49fd-896c-5089eb9f71ff)

**Comment by simplycach** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Blitzer am Eclipse Tower blitzt noch ohne Blitzer](https://trello.com/c/RDpRVQnH/353-blitzer-am-eclipse-tower-blitzt-noch-ohne-blitzer)

**Comment by simplycach** [comment]
next update fixed.
