### ISSUE TITLE
Dashboard Buttons VNet helle Themes

### ISSUE THREAD

**Issue by Ruby-Cross** [mexyn/statev_v2_issues#3073]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Ruby Cross

**Auftrittszeitpunkt (Datum / Uhrzeit)**

keine spezifische Zeit
**Beobachtetes Verhalten**

die Buttons für Nachricht schreiben und GPS Punkt sind nicht erkennbar, wenn mit der Maus darüber gefahren wird, sind sie dezent hervorgehoben, dennoch schwer erkennbar
**Erwartetes Verhalten**

sie sollten sichtbar sein, 
**Schritte um den Fehler nachvollziehen zu können**

das Theme auf helle Themes im VNet stellen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

wurde in verschiedenen Browsern probiert, Fehler bleibt
**Optional: Video / Bilder des Fehlers**

![grafik](https://github.com/eiksch/statev_v3_issues/assets/161027828/65dd8d2c-218f-4251-bae9-32a2c9f507e8)

**Comment by SatyriaDine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard Buttons nicht sichtbar bei hellen Themes VNET](https://trello.com/c/U57ZChXh/351-dashboard-buttons-nicht-sichtbar-bei-hellen-themes-vnet)

**Comment by rodistic** [comment]
Ayyy Gude,
die hellen Themes haben wir wohl vergessen, sind beim nächsten Update nicht mehr da.
