### ISSUE TITLE
VNET falsche Lagergröße Firmen

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#3074]
Im Vnet weden bei jeder Firma 3000KG Lager angezeigt, obwohl es unterschiedliche Lagergrößen bei den Firmen gibt.

**Comment by SatyriaDine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [VNET falsche Lagergröße Firmen](https://trello.com/c/fhy565Nu/362-vnet-falsche-lagergr%C3%B6%C3%9Fe-firmen)

**Comment by simplycach** [comment]
fixed next update
