### ISSUE TITLE
Türen und Tore von privater Metzgerei führen in andere Dimension

### ISSUE THREAD

**Issue by PeterGlore** [mexyn/statev_v2_issues#3075]
**Jaro Malone**

 
Jaro_Malone

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 Kauf von Gebäude. Um das Gebäude gibt es kein 
Abladepunkt

**Beobachtetes Verhalten**
Kauf von Gebäude

**Erwartetes Verhalten**
Abladepunkt sollte vorhanden sein

**Schritte um den Fehler nachvollziehen zu können**
Um das ganze Gebäude herumgelaufen. Aber kein Abladepunkt zu finden

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![Das Schlachthaus](https://github.com/eiksch/statev_v3_issues/assets/74842765/a72eb7c6-ca34-41af-a578-60dbbf7b389b)

**Comment by PeterGlore** [comment]
Neues Problem entdeckt. Wenn man in das Gebäude geht. den hinteren Ausgang nimmt. Wie der Ein/Ausgang bei der öffentliche Metzgerei kommt man in andere Dimension. Also man steht dann unten bei der öffentliche Metzgerei

**Comment by PeterGlore** [comment]
der Ein und Ausgang der MLO
![Tür](https://github.com/eiksch/statev_v3_issues/assets/74842765/5f19271a-c710-40a3-be8b-d93ea4092811)
![Tür1](https://github.com/eiksch/statev_v3_issues/assets/74842765/3a7dff1c-3b36-4905-80dd-f18988a300ac)
![Tür3](https://github.com/eiksch/statev_v3_issues/assets/74842765/8d014f64-c630-4d39-9c7b-7cf406a45808)

**Comment by PeterGlore** [comment]
Korrigiere bezgl. Abladepunkt:
Wurde gefunden, aber schwer zu erkennen.

**Comment by SatyriaDine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Metzgerei Interior macht es möglich in eine andere Dim zu gehen](https://trello.com/c/zv00RpEb/361-metzgerei-interior-macht-es-m%C3%B6glich-in-eine-andere-dim-zu-gehen)

**Comment by simplycach** [comment]
Vermutlich fixed, wenn noch so ist bitte erneut öffnen.
