### ISSUE TITLE
Job Durchsuchungspunkte nicht erreichbar

### ISSUE THREAD

**Issue by adn1337** [mexyn/statev_v2_issues#3076]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Tyler_Johnson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.02.2024 / 22:15 .. bis jetzt

**Beobachtetes Verhalten**
Job bei Mystique angenommen und zum Hafen geschickt worden. Die Punkte, die man zum Durchsuchen betreten soll, kann man nicht erreichen, da ein Zaun drum rum ist über den man nicht klettern kann

**Erwartetes Verhalten**
Man sollte sie erreichen können

**Schritte um den Fehler nachvollziehen zu können**
Versuchen genau diesen Job zu erhalten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Grand Theft Auto V_2024 02 23-22 16](https://github.com/eiksch/statev_v3_issues/assets/24351693/12dc73c5-d4ad-4023-8eab-f45615f33d91)
![Grand Theft Auto V_2024 02 23-22 17](https://github.com/eiksch/statev_v3_issues/assets/24351693/aecdc7be-d513-4a4b-9779-53a98cacc2c7)

**Comment by simplycach** [comment]
Uns fehlen hier leider jegliche Informationen, daher würde ich dich bitten uns die zur Verfügung zu stellen.

**Comment by adn1337** [comment]
Ist editiert.. war alles eingetragen, lag an der Formatierung

**Comment by Flachmeyer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Job Durchsuchungspunkte nicht erreichbar](https://trello.com/c/OeGfRk5n/366-job-durchsuchungspunkte-nicht-erreichbar)

**Comment by TheOutburst** [comment]
Jajut
Next update fixed wa :D
