### ISSUE TITLE
Verkauf Settings Firma

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#3077]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
James Carter / Ben Carter / John Adams

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.02.24 - 23:12

**Beobachtetes Verhalten**
Man kann die Items ein zweites Mal in die Liste der Verkauf/Ankaufbaren Gegenstände hinzufügen.
Dabei ist die Darstellung auch nicht ganz korrekt.

**Erwartetes Verhalten**
Jedes Item nur 1x in der Liste hinzufügbar.

**Schritte um den Fehler nachvollziehen zu können**
Item in die Liste speichern.
Fenster schließen.
Nochmal auf den Speichern button in der Liste klicken.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/70150887/c923e803-c1f7-4258-aa68-0f6fca0c4132)
![Screenshot_7](https://github.com/eiksch/statev_v3_issues/assets/70150887/08a723d0-047b-4ae3-a30e-8e2f6ff250e1)
https://www.youtube.com/watch?v=eVtdY-gvF28

**Comment by TheBroady** [comment]
Betrifft auch den Verkauf.

**Comment by SatyriaDine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Verkauf Settings Firma können verdoppelt werden](https://trello.com/c/73dv95Mv/360-verkauf-settings-firma-k%C3%B6nnen-verdoppelt-werden)

**Comment by Gogglehotmail** [comment]
Zusatz:
Items sind auch nicht löschbar oder editierbar

lg. John Adams

**Comment by simplycach** [comment]
Das betrifft anscheinend aber nur das Verkaufen an der Tür richtig ?

**Comment by simplycach** [comment]
Bitte benutzt aktuell für das An und Verkaufen von Waren die Funktion des Marktplatzes.

**Comment by simplycach** [comment]
next update fixed
