### ISSUE TITLE
Fahrzeug/Kofferaum Fehler wenn Person hinten im Auto sitzt.

### ISSUE THREAD

**Issue by ySimbaa** [mexyn/statev_v2_issues#3078]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Jaquan_Deronvil
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer
**Beobachtetes Verhalten**

Sobald eine Person im Auto hinten sitzt kann mit dem Hotkey weder das Auto abgeschlossen werden noch der Kofferaum auf/zu gemacht werden. Es kommt dann immer die Meldung "Sie besitzen für dieses Fahrzeug keinen Schlüssel"
**Erwartetes Verhalten**

Beides funktioniert ohne Probleme.
**Schritte um den Fehler nachvollziehen zu können**

Person sitzt hinten im Auto und macht versucht mit einem Hotkey das Auto auf/ab zu schließen oder den Kofferaum auf/zu zu machen.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/mNLaxehZzH8

**Comment by simplycach** [comment]
Das ist aus dem Grund nicht möglich, weil wenn du hinten am Kofferraum bist, dass du die Spieler anversierst und das lässt sich aktuell leider nicht anders lösen. Du würdest genauso mit dem X-Menü das triggern. Wir nehmen das mal als QoL auf, rechne aber nicht damit, dass es zeitnah erfolgt.

**Comment by simplycach** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Kofferraum mit Hotkey von außen aufmachen](https://trello.com/c/0rFJLACs/367-kofferraum-mit-hotkey-von-au%C3%9Fen-aufmachen)
