### ISSUE TITLE
Werkstatt/Autohaus NPC hat nen Sprachfehler

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3079]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

24.02.2024 13 uhr
**Beobachtetes Verhalten**

Typ bietet einen Autohäser an (klein sowie groß)
**Erwartetes Verhalten**

Sollte Autohäuser anbieten
**Schritte um den Fehler nachvollziehen zu können**

MIt dem NPC Reden
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/58612983/dd5c94e3-8241-4e0c-bf44-1b0b3fc0c91e)

**Comment by Erumeldor** [comment]
Fixed im nächsten Update, danke :)
