### ISSUE TITLE
Produzierte Kupferbarren nicht in der Maschine aufzufinden

### ISSUE THREAD

**Issue by RioRodriguez** [mexyn/statev_v2_issues#308]
**Rio_Rodriguez**
 Rio Rodriguez

**Zeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
 Es wurden Kupferbarren angeschmissen am 20.11.2020 , diese sind fertig produziert, befinden sich jedoch weder in der Maschine noch im Lager

**Erwartetes Verhalten**
 Die Barren sollten in der Maschine liegen

**Schritte um den Fehler nachvollziehen zu können**
 Es wurde einfach Produziert

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by KingMarcel** [comment]
Einmal an den Produktionscomputer gehen, danach sollten die Barren in der Maschine sein.
