### ISSUE TITLE
Mail löschen (Popup)

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#3080]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
James Carter

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
Wenn ich eine Mail löschen will, steht da folgendes: (siehe Screen)

**Erwartetes Verhalten**
Ich würde erwarten, dass dort dann steht, ich würde den Chat mit Chris Grein verlassen.

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/70150887/2a08d16e-505a-4399-9a27-33db21297703)

**Comment by evanhaugestatev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Falsche Nachricht beim verlassen von Mails](https://trello.com/c/5bwwUE1J/387-falsche-nachricht-beim-verlassen-von-mails)

**Comment by simplycach** [comment]
fixed
