### ISSUE TITLE
Mailweiterleitungen Empfänger löschen

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#3081]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
24.02.24

**Beobachtetes Verhalten**
Bei weiterleitungen von Mails kann man die Empfänger nicht löschen. Nur weitere hinuzfügen.

**Erwartetes Verhalten**
Das man bei einer Weiterleitung die Empfänger beliebig ändern kann um Themen auch im kleinen Kreis teilen zu können.

**Schritte um den Fehler nachvollziehen zu können**
Mail schreiben -> an dritte Person weiterleiten.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/70150887/c78c3456-7fd5-4405-950a-4c9a00e68246)

**Comment by rodistic** [comment]
Ayy Gude,

leider ist dies nicht so einfach möglich.
Wenn du Mail im kleinen Kreis weiterleiten willst musst du wohl erstmal den Mail Content kopieren und eine seperate mail aufmachen.

Technisch ist nämlich eine Mail keine traditionelle E-Mail sondern eher eine Konversation wie im Messenger.

**Comment by evanhaugestatev** [comment]
Die Thematik wurde als Verbesserungsvorschlag aufgenommen. Kurzfristig wird es aber keine Änderung geben. Trotzdem vielen Dank fürs Melden.
