### ISSUE TITLE
Unsichtbares Objekt bei 6002

### ISSUE THREAD

**Issue by CodySunchez** [mexyn/statev_v2_issues#3082]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Cody Sunchez**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
24.02.2024

**Beobachtetes Verhalten**
Unsichtbares Hindernis Gegengefahren

**Erwartetes Verhalten**
Unsichtbares Objekt nicht Vorhanden

**Schritte um den Fehler nachvollziehen zu können**
Mit dem Auto Drüber Fahren und Testen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
 https://www.youtube.com/watch?v=4osaYmDuENw

**Comment by simplycach** [comment]
Fahr mal dahin und mach uns bitte ein Bild wo genau das ist. Kannst die Koordinaten mit STRG + F6 einblenden. -

**Comment by SgtBoaz-Terry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unsichtbarer Gegenstand 6002 Cypress Flats](https://trello.com/c/qYQLNGjp/373-unsichtbarer-gegenstand-6002-cypress-flats)

**Comment by simplycach** [comment]
next Update fixed
