### ISSUE TITLE
Bauarbeiterhelm gegen bandana nach Relog getauscht

### ISSUE THREAD

**Issue by scortie1337** [mexyn/statev_v2_issues#3083]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Dave Scott**
 Dave Scott

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 24.2.2024 ca 21 uhr

**Beobachtetes Verhalten**
 Nach dem ich die Feldmarker beim Sand nciht sehen konnte habe ich gereloggt. Danach war mein Bauarbeiterhelm weg dafür hatte ich ein rotes Bandana im Inventar.
https://gyazo.com/0dbca753d01f3f9bd86aa2defbe0404a

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**
 Wird schwierig da ich ganz normal über F8 QUIT geleavt bin um zu reloggen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)** 
 1920/1080

**Optional: Video / Bilder des Fehlers**
 https://gyazo.com/0dbca753d01f3f9bd86aa2defbe0404a

**Comment by SgtBoaz-Terry** [comment]
Hast du den Bauarbeiterhelm getragen oder hattest du ihn im Inventar?

**Comment by TheOutburst** [comment]
@scortie1337 
Wie siehts aus? :D

**Comment by simplycach** [comment]
Da wir hier keine Rückmeldung mehr erhalten haben, gehe ich von aus, dass das Problem nicht mehr besteht. Wenn doch bitte nochmal melden.
