### ISSUE TITLE
Marker in alter Helmuts Werkstatt Abgehoben

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3084]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

24.02 23:50
**Beobachtetes Verhalten**

Ein Marker oben im Büro ist abgehoben
**Erwartetes Verhalten**

Er sollte mehr auf dem Boden der Tatsachen kommen
**Schritte um den Fehler nachvollziehen zu können**

Werkstatt Raub starten -> Beschaut werden, als wäre man was schlechteres
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/58612983/e34b5a4f-a397-456c-bc67-df09f84c3038)

**Comment by SgtBoaz-Terry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Raub-Marker falsch Werkstatt 6017](https://trello.com/c/qJmNfDRw/374-raub-marker-falsch-werkstatt-6017)

**Comment by TheOutburst** [comment]
lul das ist schon Wochen fixed
