### ISSUE TITLE
Durch die Wand Gebuggt

### ISSUE THREAD

**Issue by ThianaLyon** [mexyn/statev_v2_issues#3085]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Thiana Lyon

Thiana Lyon
**Auftrittszeitpunkt (Datum / Uhrzeit)**

02:18
**Beobachtetes Verhalten**

Ich war im Rebs Liquor Laden (6025 auf der Karte) bin durch gegangen bis zu dem Safe und habe mit Y Anlehnen ausgewählt und war aufeinmal durch die wand Draußen an die Mülltonne Gebuggt
**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Ist kein Bug, sollte halt nicht genutzt werden. Liegt daran weil die Mülltonnen direkt an der Wand sind.
