### ISSUE TITLE
Farbtuben verkauft während Staatskonto vermutlich leer war. Kein Geld bekommen

### ISSUE THREAD

**Issue by K0elschi** [mexyn/statev_v2_issues#3086]
**Character Name**
Timothy_Goodsen

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.02.2024 / ca. 01:45

**Beobachtetes Verhalten**
Verkauf von ca. 40 blauen Farbtuben beim Export, ohne Geld dafür zu bekommen.
Vermutlich war das Staatskonto leer.

**Erwartetes Verhalten**
Ware sollte im Export gar nicht erst angenommen werden, wenn dafür nicht bezahlt werden kann.

**Schritte um den Fehler nachvollziehen zu können**
Verkauf von Material beim Export, während kein Geld mehr auf dem Staatskonto ist.

**Comment by simplycach** [comment]
Dafür bitte ein Ticket im Discord aufmachen.
