### ISSUE TITLE
BMX neuer Burrito

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#3087]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Kayden Ryles

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
BMX hat 100kg Kofferraumvolumen

**Erwartetes Verhalten**
Eigentlich keins, maximal 1kg "Satteltasche"

**Schritte um den Fehler nachvollziehen zu können**
BMX kaufen, Kofferraum aufmachen

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/70150988/d4402edf-7dff-4725-bd9d-16500412f59a)

**Comment by SatyriaDine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fahrräder haben 100KG Kofferraum](https://trello.com/c/5AB5kVv8/372-fahrr%C3%A4der-haben-100kg-kofferraum)

**Comment by nb431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/Wnr7SRN1/377-test)

**Comment by SatyriaDine** [comment]
Next update fixed
