### ISSUE TITLE
Problem mit Firma

### ISSUE THREAD

**Issue by Boing2000** [mexyn/statev_v2_issues#3088]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Bosco Albert
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Dauerhaft
**Beobachtetes Verhalten**

Fahrzeugfertigung: Das bearbeiten und löschen von Preisen zur kalkulation der Produzierbaren teile können nicht mehr gelöscht oder geändert werden. Zu dem werden auch die icons nicht geladen in diesem Menü.
**Erwartetes Verhalten**

Anpassung und löschung sollte funktionieren
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Hast mal nen Screenshot für uns ?

**Comment by Boing2000** [comment]
https://gyazo.com/483e14bbe6d6ddb4b0901acfd2ec4761

**Comment by simplycach** [comment]
Ist next Update fixed
