### ISSUE TITLE
Firmenmitarbeiter werden bei Kündigung nicht aus der Mitarbeiterliste entfernt [StateNet]

### ISSUE THREAD

**Issue by Shirobaka** [mexyn/statev_v2_issues#3089]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Ben Carter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.02.2024 13:08

**Beobachtetes Verhalten**
Wenn ich einen Mitarbeiter aus der Firma entlasse, wird er nicht aus der Liste entfernt, auch nach Neustart des Tablets oder Relogin wird der Name weiterhin angezeigt.
Wenn ich versuche ihn erneut zu entfernen, wird in der Popup Meldung als Name "undefined" angezeigt.

**Erwartetes Verhalten**
Der Mitarbeiter sollte aus der Liste entfernt werden wenn er aus der Firma entlassen wird.

**Schritte um den Fehler nachvollziehen zu können**
Mitarbeiter mittels des X im StateNet aus der Firma entfernen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
2560x1440

**Comment by simplycach** [comment]
Also bei mir ging es ohne Probleme, Mitarbeiter mit dem X entfernen und dann oben auf das Char Bild "Reload" dann ist der Mitarbeiter nicht mehr in der Firma.
