### ISSUE TITLE
Ressourcenexport (NICHT Auftragsexport) funktioniert nicht

### ISSUE THREAD

**Issue by AtreuX** [mexyn/statev_v2_issues#309]
Hier geht es um den Ressourcenexport, nicht um den Auftragsexport!
Deshalb einen eigenen Report geöffnet.

**Character Name**
Tom_Clark

**Zeitpunkt (Datum / Uhrzeit)**
21.11.2020 ca. 13:45

**Beobachtetes Verhalten**
Zum Zeitpunkt des Auftretens gab es einen offenen Export für Diesel (siehe Video). Ich habe Diesel in meiner Achse, kann die Ware dennoch nicht abgeben. Ich erhalte die Fehlermeldung, dass keine Waren gefunden werden. Ich würde die Schlüssel für das Fahrzeug benötigen oder müsse den Kofferraum öffnen.
Ich besitze sowohl die Schlüsssel (jetzt fällt mir aber gerade ein: Hängen am Schlüsselbund. ICHT mit Schlüsseln im Inventar getestet), als auch habe ich den Kofferraum geöffnet. Zur Sicherheit habe ich danach die Achse abgehangen und ohne Phantom getestet (im Video zu sehen).

Das ganze betrifft auch andere Waren, weil nach mir andere Spieler zum Export mit anderen Waren gefahren sind und wir uns kurz ausgetauscht haben.

**Erwartetes Verhalten**
Wenn der Dieselexport wie beschrieben geöffnet ist (ein steigender Preis angeboten wird), sollte ich das Diesel in der Achse exportieren können.

**Schritte um den Fehler nachvollziehen zu können**
1) Mit entsprechendem Fahrzeug und Ware, die derzeit im Ressourcenexport abgenommen ist, zum entsprechenden Marker fahren und Kofferraum öffnen.
2) Exportmitarbeiter (NPC) ansprechen.
3) Auf den Tab Verkauf wechseln und versuchen, die Ware zu exportieren

**Optional: Video / Bilder des Fehlers**
https://youtu.be/ST7WzLlaruU

**Comment by tastydev** [comment]
fixed bei nächstem update

**Comment by tastydev** [comment]
der auftragsexport ebenso war auch buggy
