### ISSUE TITLE
Nach einloggen in Firma vor der Firma

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3090]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

25.02 13:25
**Beobachtetes Verhalten**

Wollte mich kurz im Crime Lager reloggen und bin vor dem Lager gespawnt
**Erwartetes Verhalten**

Man spawnt im Lager

**Comment by simplycach** [comment]
Probiere mal nochmal aus bitte

**Comment by SHaagmann** [comment]
Jo Exakt das gleiche

**Comment by TheOutburst** [comment]
Jau, aus technischen gründen ist das leider so ich mach hier erstmal zu, glaub das wird so bleiben
