### ISSUE TITLE
SMS Gruppen Adminrechte Bug

### ISSUE THREAD

**Issue by Shirobaka** [mexyn/statev_v2_issues#3091]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Ben Carter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.02.2024 13:50

**Beobachtetes Verhalten**
Wenn ich eine SMS Gruppe erstelle und einem Chatteilnehmer die Adminrechte entziehe, verliere auch ich die Adminrechte.

**Erwartetes Verhalten**
Man sollte selbst die Adminrechte behalten wenn man sie anderen entzieht.

**Schritte um den Fehler nachvollziehen zu können**
SMS Chat mit einer Person öffnen, weitere Person hinzufügen, der ersten Person die Admin-Rechte entnehmen, ab den Zeitpunkt verliert man ebenfalls seine Rechte.

**Comment by SatyriaDine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Adminrechte in SMS-Gruppen](https://trello.com/c/Ew1IXfG0/380-adminrechte-in-sms-gruppen)

**Comment by rodistic** [comment]
Ayy Gude, ist mit dem nächsten Update fixed.
