### ISSUE TITLE
Fehlender Marker - Mystique Job

### ISSUE THREAD

**Issue by adn1337** [mexyn/statev_v2_issues#3092]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Tyler_Johnson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.02.2024 / 15:00

**Beobachtetes Verhalten**
Bei Mystique angenommener Job nicht vollständig ausführbar, da scheinbar ein Marker fehlt. 
Es ist kein weiterer Marker an dem angegebenen Punkt zu finden, aber Mystique sagt, dass er Job noch nicht erfüllt sei.

**Erwartetes Verhalten**
Weiterer Marker oder erfüllter Job

**Schritte um den Fehler nachvollziehen zu können**
Job bei Mystique annehmen und alle Marker ablaufen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![Grand Theft Auto V_2024 02 25-15 02](https://github.com/eiksch/statev_v3_issues/assets/24351693/ed2088ea-2a9d-4276-9ec2-aff969f74217)
![Grand Theft Auto V_2024 02 25-15 02_1](https://github.com/eiksch/statev_v3_issues/assets/24351693/4a2d6710-76ab-4afb-9c95-69b6b5b14090)

**Comment by TheOutburst** [comment]
upsi
fixed next update
