### ISSUE TITLE
Markerfarben Silbererz und Eisenerz

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3093]
Die Marker auf dem Feld von den Adern sind nahezu identisch, wäre klasse wenn man es anpassen könnte um es unterscheidbar zu  machen wo man nun was abbaut..

**Comment by Statev-Bonsai** [comment]
![Screenshot_30](https://github.com/eiksch/statev_v3_issues/assets/70241137/3e94e650-a853-4f75-b661-992d5c14f32b)
Links Silber und Rechts Eisenerzader...

**Comment by TheOutburst** [comment]
Jajut
Die sind schon sehr, sehr ähnlich
Ich schieb den Silbernen ma mehr in Cyan oder wat dat is

**Comment by simplycach** [comment]
next Update fixed
