### ISSUE TITLE
Gesprächspartner trotz beendetem Telefonat noch zu hören

### ISSUE THREAD

**Issue by Simonrl9** [mexyn/statev_v2_issues#3094]
**Qwentin_Lance**

*Auftrittszeitpunkt (Datum / Uhrzeit)
Wann exakt 161525022024 ist der Fehler beobachtet worden

**Beobachtetes Verhalten**
Gesprächspartner nach Telefonat immer noch zu hören

**Erwartetes Verhalten**
Wenn man Auflegt sollte man sich nicht mehr hören

**Schritte um den Fehler nachvollziehen zu können**
...

**Optional: Video / Bilder des Fehlers**
Twitch Simonrl9 etwa bei 9h 10min am Angelsteg 
 https://clips.twitch.tv/AbnegateBlindingKittenJKanStyle-7BdDkjPVSCD-ycQs

**Comment by evanhaugestatev** [comment]
Wir konnten das leider noch nicht reproduzieren. Ist es danach nochmal aufgetreten? Gibt es einen Ausschnitt von dem Moment, wo das Telefonat beendet wurde?

**Comment by simplycach** [comment]
Wir schließen das jetzt erstmal, weil wir bisher keine weiteren Meldungen dies bezüglich erhalten haben. Und auch diesen Fehler nicht reproduzieren konnten.
