### ISSUE TITLE
DispatchMarker Sandy Shores Sheriff Office

### ISSUE THREAD

**Issue by Feuronos** [mexyn/statev_v2_issues#3095]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**John Breaker**

John breaker

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
Es werden die maximalen Dispatcher angezeigtso das es nciht möglich sit ein weiteren einzufügen.
Nach anfragen IC und de rbtite die Pager zurück zu geben wurde das Problem nciht behoben.

Das Öffnen der Haupttür im SSSO   ist mitunter direkt überlappend mit dem Dispatch on/Off Marker das führt dazu das einige den Dispatch unfreiwillig nehmen. 

**Erwartetes Verhalten**
Dispatch und Tür marker nciht Zufällig nutzen

**Schritte um den Fehler nachvollziehen zu können**
Tür vom SSSo hauptlobby nutzen (Rechts eite auswerts) sowie dispatch am Empfang

**Comment by TheOutburst** [comment]
Sollte nach dem nächsten Update nichtmehr vorkommen
