### ISSUE TITLE
Textfeld für Nachrichten im Tablet nicht richtig anklickbar

### ISSUE THREAD

**Issue by tr1kssi** [mexyn/statev_v2_issues#3096]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Jackson Rodriguez

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Wenn ich ins Textfeld klicke, komme ich ins Home Menü vom Tablet, da der Home-Butten halb drinnen hängt.

**Erwartetes Verhalten**
Sollte einen Text schreiben können und nicht in die App-Übersicht kommen

**Schritte um den Fehler nachvollziehen zu können**
Im Tablet einen Chat öffnen, ins Feld klicken (Grob in der Nähe vom Home-Button)

**Optional: Video / Bilder des Fehlers**
https://prnt.sc/DjiGtB2SEYiI

**Comment by rodistic** [comment]
Im nächsten Update ist das fixed
