### ISSUE TITLE
Gefreezed beim Verarbeiter in Harmony fruit store für obst und gemüse

### ISSUE THREAD

**Issue by DeXxXTar** [mexyn/statev_v2_issues#3098]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Julius_Behrens**

Beim Verarbeiten wurde nach eine gewissen verarbeitung komplett die spiel figur gefreezed und das menü ploppte nicht mehr auf welches item man verarbeiten möchte funktioniert erst nach relog

**Auftrittszeitpunkt (Datum / Uhrzeit)**

25.02.2024 - 26.02.2024 00:40Uhr

**Beobachtetes Verhalten**

Beim Verarbeiten vom items erscheint das menü zum verarbeiten nicht mehr und der gesammte char freezed und man kann nichts mehr machen bis zum relog

**Erwartetes Verhalten**

Menü sollte immer wie gewohnt neu erscheinen nach verarbeitung des item wie vor erscheinen des eventuellen bugs

**Schritte um den Fehler nachvollziehen zu können**

Rohitem sammeln sprich obst oder gemüse und dann bei der öffentlichen Firma verarbeiten nach einer gewissen zeit freezed es bei mir komplett

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Konnte bisher nicht durch uns reproduziert werden.
