### ISSUE TITLE
Steuerzahlung bei umbuchung auf Zweitkonto

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3099]
Bei umbuchung auf das eigene Zweitkonto werden Steuern fällig, das macht eigentlich keinen Sinn und war bei V2 auch nicht so...

![Screenshot_33](https://github.com/eiksch/statev_v3_issues/assets/70241137/6cafb565-0bee-49b6-9dd4-38ec39b5dd20)

**Comment by Gogglehotmail** [comment]
Das ist ein anzeigefehler es werden nicht wirklich welche abgezogen dennoch wäre ein fix schön das selbe gilt als inhaber einer firma

**Comment by rodistic** [comment]
Ayy Gude, grüße aus der Entwicklung.

Wie der Vorredner bereits erkannt hat ist das nur eine Anzeige der Steuern, nicht das was tatsächlich abgebucht wird. 
Leider können wir das technisch nicht umbauen ohne dabei die Performance zu beeinträchtigen.

Kann mit dieser Antwort hier das Issue geschlossen werden?

**Comment by LeaBrandt** [comment]
Weiß nicht ob der Kommentar hier noch gesehen wird, aber könntet ihr nicht einfach den Text anpassen statt "Steuern" dann "Steuern bei Zahlung auf Fremdkonto"...vielleicht nen bissl lang, aber dann kann keiner sagen, dass es nicht ersichtlich ist 
LG
