### ISSUE TITLE
Motor an/ausschalten

### ISSUE THREAD

**Issue by VictorCorticera** [mexyn/statev_v2_issues#31]
**Zeitpunkt (Datum / Uhrzeit)**

25.08.2020 / 20:30

**Beobachtetes Verhalten**

Das Fahrzeug ist offen, ich steige ein und kann den Motor anschalten, obwohl ich keinen Schlüssel habe. Ausschalten kann ich den Motor ohne Schlüssel allerdings nicht, da erscheint eine Fehlermeldung.

**Erwartetes Verhalten**

Entweder es sollte überhaupt nicht möglich sein, den Motor an/auszuschalten ohne Schlüssel oder es sollte beides möglich sein.

**Schritte um den Fehler nachvollziehen zu können**

1. Ein Fahrzeug eines anderen Spielers öffnen lassen (Motor muss aus sein und man darf keinen Schlüssel dazu haben).
2. In Fahrzeug einsteigen
3. Motor starten (funktioniert)
4. Motor ausschalten (funktioniert nicht - Fehlermeldung)

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Hi, war ein Globales Setting was aktiviert war. Daher schließe ich den Eintrag wieder.
