### ISSUE TITLE
Hafenmitarbeiter klammern/halten einen fest

### ISSUE THREAD

**Issue by AtreuX** [mexyn/statev_v2_issues#310]
**Character Name**
Tom_Clark

**Zeitpunkt (Datum / Uhrzeit)**
21.11.2020 ca. 13:45

**Beobachtetes Verhalten**
Hafenmitarbeiter (sowohl der am Auftragsexport, als auch am Ressourcenaexport) halten einen manchmal fest. Gestern Abend einen anderen Spieler am Auftragsexport. Als Workaround hat nur geholfen, dass ich meinen Burrito nah an ihn heran gefahren habe. Er hat diesen dann weggeschoben und ist so von dem Hafenmitarbeiter weggekommen.

Heut wie im Video zu sehen ist es mir am Ressourcenexport passiert. Ich kam nicht mehr weg. Erst, nach dem ich einmal auf Verkauf gewchselt bin, konnte ich mich wieder richtig bewegen. Beim Auftragsexport geht dieser Workaround unter Umständen nicht, weil man dort keinen zweiten Tab mit Verkauf hat!

**Erwartetes Verhalten**
Hafenmitarbeiter sollten nicht klammern.

**Schritte um den Fehler nachvollziehen zu können**
1) Zum Hafen an den Ressourcenexport oder Auftragsexport fahren und die NPCs ansprechen.
2) Dieser Fehler tritt offnebar nicht immer auf!

**Optional: Video / Bilder des Fehlers**
https://youtu.be/2VbqwPqPJTU

**Comment by DonVitoDiangelo** [comment]
Sollte bereits gefixt sein, bitte noch einmal prüfen.

**Comment by AtreuX** [comment]
Habs geprüft bzw. mehrmals versucht bewusst zu triggern, ist nicht wieder aufgetaucht.
