### ISSUE TITLE
Export - keine neuen Auktionen / verbuggte Auktion / Vertragsstrafen zu niedrig.

### ISSUE THREAD

**Issue by jonesXYZ** [mexyn/statev_v2_issues#3100]
**Character Name**
Maxwell_Scott

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Zurzeit / Dauerhaft

**Beobachtetes Verhalten**
Seit einem oder 2. Tagen kommen keine neuen Exporte in die Auktionen. Zudem hängt eine Auktion in den Auktionen noch in der schwebe obwohl die Zeit schon lange abgelaufen ist. 

Vertragsstrafen sind zudem auch viel zu wenig. Früher lagen die, wenn mich nicht alles täuscht bei 80% vom Startpreis des Exports. Diese Strafen müssen mMn weh tun weil sonst jeder einfach jeden runter bietet und ihn das nicht interessiert.

**Erwartetes Verhalten**
Das Exporte weiterhin rein kommen und nicht leer laufen.

**Schritte um den Fehler nachvollziehen zu können**

1. VNET Einloggen
2. Auf Export gehen
3. Auktionen aufrufen

**Optional: Video / Bilder des Fehlers**
![Bildschirmfoto 2024-02-26 um 10 49 40](https://github.com/eiksch/statev_v3_issues/assets/44285771/533d70e6-3de9-462c-9088-ad27070aa7e6)

**Comment by evanhaugestatev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Exportaufträge verschwinden nicht](https://trello.com/c/fj1iZqcK/386-exportauftr%C3%A4ge-verschwinden-nicht)

**Comment by simplycach** [comment]
fixed
