### ISSUE TITLE
Mystique Auftrag verbuggt

### ISSUE THREAD

**Issue by Wolle218** [mexyn/statev_v2_issues#3101]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Ace Rooks**

**Dauerhaft / seit Tagen**

**Der Autrag besagt, man solle auf das Weedfeld nahe Grapeseed gehen & dort die Pflanzen abernten, nachdem man alle sichtbaren Marker durchlaufen ist, fehlt entweder noch einer um den Auftrag abzuschließen, oder er kann einfach nicht abgeschlossen werden.**

**Nachdem man den letzten Marker erreicht & durchlaufen hat, sollte eine Info erscheinen, alle Infos gesammelt zu haben.**

**Mystique Auftrag annehmen, der zum Weedfeld führt & einfach die Marker durchlaufen**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Nächstes Update fixed.
