### ISSUE TITLE
Keine 5% mehr, bei Abhebung am ATM?

### ISSUE THREAD

**Issue by Schubert82** [mexyn/statev_v2_issues#3102]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Paul Schubert

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.2.2024, 13:02:22

**Beobachtetes Verhalten**
Habe eben vom Konto abgebucht, es kam zwar in der IC Meldung das 5% abgebucht wurden, aber bei den 500$ die ich abgebucht habe, wurden auf dem Konto keine 5% hinzugerechnet!

**Erwartetes Verhalten**
Das auf dem Konto auch die 5% wieder hinzugerechnet werden!

**Schritte um den Fehler nachvollziehen zu können**
Wenn der Charakter Geld am ATM abhebt, wird keine 5% zusätzlich abgebucht!

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/konto.HPnntn

**Comment by simplycach** [comment]
Schau mal nach im Konto die wurden sicher abgezogen.
