### ISSUE TITLE
Firmen Produktionstab (VNET)

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#3103]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
James Carter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
jederzeit

**Beobachtetes Verhalten**
1. Wenn man die Liste erweitert, bspw. auf 25 Wird nur eine Scrollbar hinzugefügt. der Breich bleibt aber gleich groß.
2. Das Dropdown zum auswählen der Menge der Ergebnisse trollt einen und schließt sich immer wieder von selbst. :)

**Erwartetes Verhalten**
1. Liste um X Aufträge erweitert wird und keine Scrollbar.
2. Das Dropdown solange offen bleibt bis man was anklickt.

**Schritte um den Fehler nachvollziehen zu können**
1. Produktionstab der Firma öffnen
2. Anzahl der Ergebnisse anzeigen lassen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/dNpiAL81cbk (HD gleich Verfügbar)

**Comment by simplycach** [comment]
Next Update fixed
