### ISSUE TITLE
QoL Rechtschreibungssachen gem. Ticket 2535

### ISSUE THREAD

**Issue by JohnRappStateV** [mexyn/statev_v2_issues#3104]
![image](https://github.com/eiksch/statev_v3_issues/assets/93606498/3e8e1723-5ca5-4135-9a3d-e2dd72a855b1)
![image](https://github.com/eiksch/statev_v3_issues/assets/93606498/fa527293-4620-405d-94de-9a1ff800d9d3)
![image](https://github.com/eiksch/statev_v3_issues/assets/93606498/30684d6c-0148-4857-b212-a3dfb54d73c1)

Moin, sind nur Kleinigkeiten, aber paar Rechtschreibfehler sind mir aufgefallen. Jaja, kleinlich, jaja, unnötig. I know - ist nur Feedback und QoL. 

"ihr" -> "Ihr"
"ein" -> "einen"
"1" -> "einen"

**Comment by JohnRappStateV** [comment]
![image](https://github.com/eiksch/statev_v3_issues/assets/93606498/2f77ab95-5602-4f68-880e-117994773df4)

**Comment by TheOutburst** [comment]
Ihr kann man groß schreiben, stimmt
Das 1 im Vertrag ist "Vertragssprech", das bleibt so :D
Diensttag ist natürlich dumm :D

**Comment by JohnRappStateV** [comment]
Was ist mit "einEN Kommentar, einEN Like?"

Bzgl "Vertragssprech": -> Google:

Im Kontext von "Vertragssprech" ist die Verwendung von Zahlen wie "1" eher unüblich. Stattdessen wäre es üblicher, "einen" zu verwenden, um zu betonen, dass es sich um eine bestimmte Art von Vertragssprache handelt.

**Comment by simplycach** [comment]
Ist das noch aktuell ?

**Comment by JohnRappStateV** [comment]
Ja

simplycach ***@***.***> schrieb am Mo. 4. März 2024 um 21:43:

**Comment by simplycach** [comment]
Vieles bereits gefixt worden, wenn nochmal was auffällt bitte einen neuen Bug Tracker schreiben
