### ISSUE TITLE
Firmen(Labor) - Preiskalkulationen nicht mehr möglich

### ISSUE THREAD

**Issue by ZacCooperr** [mexyn/statev_v2_issues#3105]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Zac_Connor

**Auftrittszeitpunkt (Datum / Uhrzeit)**

23:00

**Beobachtetes Verhalten**

Wie vorab im Community-Support schon geschildert, fehlt momentan im Labor der Preisrechner, worüber man jedem Item einen Preis zuordnern kann. Vor dem heutigen Update stand er noch auf den Tisch, s. Anhang. 
Nach dem Update haben wir aktuell keine Möglichkeit mehr, änderungen vorzunehmen.
Ob das alle Firmen oder nur das Labor betrifft, können wir aktuell nicht verifizieren.

**Erwartetes Verhalten**
Das man für den Preisrechner jedem Item weiterhin einen Preis zuordnern kann.

**Schritte um den Fehler nachvollziehen zu können**
Einem Item im Labor z.B. einen Preis zuordnern wollen, damit der Preisrechner gefüllt und kalkulieren kann.

**Optional: Video / Bilder des Fehlers**

https://pic.statev.de/i/HPBWsm.png
https://pic.statev.de/i/HPBg4I.png

**Comment by evanhaugestatev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Preiskalkulationen nicht mehr möglich](https://trello.com/c/tVaXMOCG/385-preiskalkulationen-nicht-mehr-m%C3%B6glich)

**Comment by evanhaugestatev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Calc Pro v3](https://trello.com/c/QpZWPOOp/389-calc-pro-v3)

**Comment by simplycach** [comment]
fixed
