### ISSUE TITLE
Blaues Meth mission ausliefern Buggy

### ISSUE THREAD

**Issue by GoatJuan** [mexyn/statev_v2_issues#3107]
Mateo_Morello

27.02.2024   20:14

Blaue Meth Mission löst nicht aus kommt kein Text und keine punkte zum Ausliefern

Big H anlabern und auf die Mission klicken

https://github.com/eiksch/statev_v3_issues/assets/104281291/2a86f7d5-9a55-46ba-8b0f-abf93b2c5e8c

**Comment by evanhaugestatev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Meth ausliefern beim NPC BigH / jimmy nicht möglich](https://trello.com/c/a3LaOwxO/388-meth-ausliefern-beim-npc-bigh-jimmy-nicht-m%C3%B6glich)

**Comment by TheOutburst** [comment]
next update fixed
