### ISSUE TITLE
Falsches Rezept für Ticket Bogen

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#3108]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Kayden Ryles

**Beobachtetes Verhalten**
Auf der Anleitung für den Ticket Bogen wird von Pappkarton geschrieben, aber es wird reguläre Pappe benötigt

**Erwartetes Verhalten**
Das die Anleitung auf Pappe hinweißt und nicht Pappkartons (brauch wer 36 Pappkartons?)

**Schritte um den Fehler nachvollziehen zu können**
Anleitung kaufen und rätseln
Falsche Anleitung bekommen
Auf Falsch Basis 36 Pappkartons kaufen
Enttäuscht werden

**Comment by nb431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Falsches Rezept für Ticket Bogen](https://trello.com/c/t42TArY6/414-falsches-rezept-f%C3%BCr-ticket-bogen)
