### ISSUE TITLE
24/7 Verpackter Lufttänzer sowie Verpackte Spitzhacken nicht auspackbar

### ISSUE THREAD

**Issue by adrosso** [mexyn/statev_v2_issues#3110]
**Isaac_Reed**

13:09 Uhr, 28.02.2024

Ich habe eine Fertigung, was es gerade schwer macht die Produzierten Sachen weg zu bekommen.
Grund: Der 24/7 in Sandy Shores kann dort keine Sachen auspacken, getestet wurde Spitzhacken und Verpackter Lufttänzer

Das man Produzierte Sachen wieder auspacken kann.

**Comment by simplycach** [comment]
Hey das ist kein Bug, es sei so viel gesagt, dass man im 24/7 nicht mehr alles auspacken kann :)
