### ISSUE TITLE
Unsichtbares Objekt auf dem Ölfeld

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#3111]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
James Carter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
29.02.24

**Beobachtetes Verhalten**
Unsichtbares Objekt auf dem Ölfeld

**Erwartetes Verhalten**
Kein Unsichtbares Objekt. :D

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=9QWydrrmA8U

**Comment by SatyriaDine** [comment]
#3057
