### ISSUE TITLE
Casino Croupier hängt und reagiert nicht mehr 

### ISSUE THREAD

**Issue by Ruby-Cross** [mexyn/statev_v2_issues#3112]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Ruby Cross

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14:10 herum am 29.02. 

**Beobachtetes Verhalten**
Croupier hängt in der Stellung, die im Screenshot zu sehen ist, habe extra paar Minuten gewartet, aber keine Reaktion oder weiterführen des Spiels

**Erwartetes Verhalten**
sollte Karten legen und das Spiel zu einem Ende kommen

**Schritte um den Fehler nachvollziehen zu können**
Ich habe meinen Charakter an den Tisch gesetzt und gespielt, meine Reaktion ging, die dritte Karte zog sie nicht mehr bzw. das Spiel stuckt. Hab auch extra unten die Angaben für FPS ect mit eingeblendet. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
4k 

**Optional: Video / Bilder des Fehlers**
![grafik](https://github.com/eiksch/statev_v3_issues/assets/161027828/0582383a-11a5-4029-8aea-dc12c0f38e48)

**Comment by Ruby-Cross** [comment]
achso, aufstehen ect geht nicht, ich kann den Charakter nicht bewegen oder aus der Situation befreien

**Comment by evanhaugestatev** [comment]
Die wievielte Runde war das ca. ?

**Comment by Ruby-Cross** [comment]
Es war die 2. oder 3. Runde, also kurz nach Start eigentlich schon, Neustart hat btw. auch nicht geholfen, Problem blieb bestehen und Money war natürlich weg, ich guck nochmal, welche Croupie das war

**Comment by Ruby-Cross** [comment]
Die Croupie war Maria und anderer Tisch ging, habe ich gerade probiert.

**Comment by simplycach** [comment]
Wenn ihr diesen Bug nochmal habt, bitte mal ein Video machen, würde uns sehr helfen mit F8 Console aufmachen.

**Comment by simplycach** [comment]
Lies sich bisher nicht reproduzieren.
