### ISSUE TITLE
Tetris Highscore Liste wird nicht angezeigt

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#3113]
**Character Name**
Charly Russo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
täglich :(

**Beobachtetes Verhalten**
Der Tetris Highscore wird nicht angezeigt, weder täglich noch wöchentlich noch Gesamt

**Erwartetes Verhalten**
Ich möchte mit meinem Highscore flexen können.

**Schritte um den Fehler nachvollziehen zu können**
1. Öffne Tetris
2. Verlier ein Spiel
3. Profit

**Optional: Video / Bilder des Fehlers**
https://i.imgur.com/B2ca1zB.png

**Comment by SatyriaDine** [comment]
ist bereits bekannt. :) #3001
