### ISSUE TITLE
Werkstatt Tuning Reifenwechsel falsche Anzahl

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#3114]
UHP Reifen bei einem Schafter V12.

Es werden 6 statt 4 Reifen benötigt, Noch nicht bei anderen Fahrzeugen getestet

**Comment by SatyriaDine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reifenwechsel in Werkstatt fehlerhasft](https://trello.com/c/n8FJXTxN/402-reifenwechsel-in-werkstatt-fehlerhasft)

**Comment by epichalt** [comment]
![image](https://github.com/eiksch/statev_v3_issues/assets/16436981/9542bf0c-a395-487b-bf85-47705abac2d3)
![image](https://github.com/eiksch/statev_v3_issues/assets/16436981/b8f9e492-9ffe-4357-8f64-3f6750ed75e0)


Also es werden gar keine Anzahlen im Computer angezeigt. Und teilweise braucht man sogar mehr als 6 Reifen

**Comment by simplycach** [comment]
fixed
