### ISSUE TITLE
Werkstattfehler #2

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#3115]
Es werden keine Folien angezeigt. Bereits mehrere Fahrzeuge getestet
![image](https://github.com/eiksch/statev_v3_issues/assets/16436981/56b3e12f-7622-4029-8798-224ca3b8ee65)

**Comment by SatyriaDine** [comment]
Haben wir auf dem Schirm :)

**Comment by SatyriaDine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fahrzeug Folierungen nicht möglich](https://trello.com/c/MzSlKrup/219-fahrzeug-folierungen-nicht-m%C3%B6glich)

**Comment by simplycach** [comment]
fixed
