### ISSUE TITLE
Autoknacken sagt Inventar ist Voll

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3116]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared (ca. 5KG im inventar) & Izaac Baker (ca. 7KG im Inventar)
**Auftrittszeitpunkt (Datum / Uhrzeit)**

01.03 ca. 18:40
**Beobachtetes Verhalten**

Wir beide haben nacheinander unterschiedliche Autos geknackt mit der Meldung, dass unser Inventar voll ist, ob wohl es das nicht war.
**Erwartetes Verhalten**

Etwas bekommen :(
**Schritte um den Fehler nachvollziehen zu können**

1. Slimjim nehmen
2. Auto Aufknacken
3. Freuen, dass nicht die meldung kommt, dass nichts gefunden wurde
4. Traurig sein, dass die Meldung kommt, das Inventar sei lehr
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://medal.tv/games/gta-v/clips/1YmZXNmcaF-TZy/d1337wTjSL7v?invite=cr-MSxONW4sMTk1NTEzMTMzLA

**Comment by simplycach** [comment]
Hey Sven, das ist kein Fehler bitte habe das Hauptinventar leer, damit du diese Meldung nicht bekommst. Es gibt Teilweise schwere Items.
