### ISSUE TITLE
Augenbraun Lassen sich nicht setzen wenn nicht vorhanden. 

### ISSUE THREAD

**Issue by Xymena** [mexyn/statev_v2_issues#3118]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Alice_Swan bei Mason Liam

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19:30
**Beobachtetes Verhalten**

Es wurde versucht Augenbraun beim Friseur zu setzen, nach dem der Prozess durch gelaufen ist waren sie nach wie vor nicht vorhanden.

**Erwartetes Verhalten**
Augenbraun sind zu sehen

**Schritte um den Fehler nachvollziehen zu können**

Augenbraun ausgewählt -> Bestätigt -> Prozessbalken durchlaufen lassen 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://medal.tv/games/gta-v/clips/1YBNi4Y5pLBF6m/d1337t6RUtTW?invite=cr-MSxRczIsNjQxMjQ1NTQs
https://medal.tv/games/gta-v/clips/1YBRfNx--gpflB/d13371RCYHB4?invite=cr-MSxiakwsNjQxMjQ1NTQs

**Comment by simplycach** [comment]
Bereits fixed
