### ISSUE TITLE
Anfahrtspunkt Bus 745 Haltestelle Maze Bank verlegen

### ISSUE THREAD

**Issue by LeaBrandt** [mexyn/statev_v2_issues#3119]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
 Ronja Brandtberg

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 02.03. 17:22 Uhr bzw. immer 

**Beobachtetes Verhalten**
 Die Buslinie 745 muss sowohl Richtung Airport, als auch auf dem Rückweg östlich von der Maze Bank Arena halten. Das Haltestellenschild steht meines Erachtens nur auf dem Rückweg vom Airport korrekt (siehe auch Foto) - evtl. auf der Gegenfahrbahn noch ein Haltestellenschild stellen. Der Marker zum Halten zählt aber nur, wenn ich den Bus mit mindestens einem Reifen auf den Ausbuchtungen stehen habe. Ich denke der Marker müsste weiter Richtung Maze Bank gesetzt werden. Evtl. auf die Straße damit der Hin- und Rückweg abgedeckt ist. Das auch das Haltestellenschild der 745 an der Straße steht wird es ja hoffentlich nicht gewollt sein, dass man mit dem Bus in die Nischen fährt und dann Rückwärts umständlich raus. Habe ich auch schon getan - ist aber nervig und mit Verkehr von anderen Autos auch teils schwierig. 

**Erwartetes Verhalten**
 Marker auf der Straße...Bus stoppt und kann dann gleich weiter. 

**Schritte um den Fehler nachvollziehen zu können**
 Buslinie 745 als Busfahrer fahren. 

**Optional: Video / Bilder des Fehlers**
 
![Grand Theft Auto V Screenshot 2024 03 02 - 17 22 56 94](https://github.com/eiksch/statev_v3_issues/assets/98689462/bb3ae715-4ec2-4cdf-a58f-c7e3c2238da8)

**Comment by simplycach** [comment]
Ist kein Bug, und wir werden da auch nichts dran ändern, da muss man halt anders ranfahren.
