### ISSUE TITLE
Friseurladen Bug

### ISSUE THREAD

**Issue by jonesXYZ** [mexyn/statev_v2_issues#3120]
**Character Name**
Maxwell Scott

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.03.2024 - 21.30 Uhr

**Beobachtetes Verhalten**
Notification das Rasiermesser fehlt (itemHash ist razors) obwohl mehr als Genug vorhanden

**Erwartetes Verhalten**
Friseur Vorgang sollte starten

**Schritte um den Fehler nachvollziehen zu können**
Spieler setzt sich auf Stuhl 
Friseur ausgewählt 
Notification das Rasiermesser fehlt (itemHash ist razors) obwohl mehr als Genug vorhanden

**Informationen**
{
    "_id": "65c7771c35f1ed5c9e01987e",
    "hash": "barberShop2",
    "label": "💈 County Cut ✂️",
    "street": "Niland Ave.",
    "streetNumber": "96",
    "isOpen": false,
    "adLine": "Termin 1822-50031427",
    "gps": {
        "x": 1933.55,
        "y": 3722.75,
        "z": 32.83
    }
}

**Lagerdaten**
{
    "_id": "65c7771c35f1ed5c9e01987e",
    "items": [
        {
            "_id": "65e38c18cb9323bcf4b47004",
            "hash": "haircolorBlue",
            "amount": 30,
            "totalWeight": 15,
            "singleWeight": 0.5,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b47005",
            "hash": "haircolorGreen",
            "amount": 27,
            "totalWeight": 13.5,
            "singleWeight": 0.5,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b47006",
            "hash": "towel",
            "amount": 137,
            "totalWeight": 41.1,
            "singleWeight": 0.3,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b47007",
            "hash": "haircolorRed",
            "amount": 28,
            "totalWeight": 14,
            "singleWeight": 0.5,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b47008",
            "hash": "hairdryer",
            "amount": 5,
            "totalWeight": 1.5,
            "singleWeight": 0.3,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b47009",
            "hash": "hairclipper",
            "amount": 5,
            "totalWeight": 0.5,
            "singleWeight": 0.1,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b4700a",
            "hash": "comb",
            "amount": 20,
            "totalWeight": 1,
            "singleWeight": 0.05,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b4700b",
            "hash": "curlers",
            "amount": 5,
            "totalWeight": 1,
            "singleWeight": 0.2,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b4700c",
            "hash": "hairdressingcape",
            "amount": 5,
            "totalWeight": 0.25,
            "singleWeight": 0.05,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b4700d",
            "hash": "neckfrond",
            "amount": 5,
            "totalWeight": 0.5,
            "singleWeight": 0.1,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b4700e",
            "hash": "scissor",
            "amount": 82,
            "totalWeight": 16.400000000000002,
            "singleWeight": 0.2,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b4700f",
            "hash": "tweezers",
            "amount": 40,
            "totalWeight": 0.4,
            "singleWeight": 0.01,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b47010",
            "hash": "stylingGel",
            "amount": 9,
            "totalWeight": 0.45,
            "singleWeight": 0.05,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b47011",
            "hash": "hairSpray",
            "amount": 10,
            "totalWeight": 2,
            "singleWeight": 0.2,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b47012",
            "hash": "hairShampoo",
            "amount": 10,
            "totalWeight": 2.5,
            "singleWeight": 0.25,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b47013",
            "hash": "razors",
            "amount": 13,
            "totalWeight": 1.3,
            "singleWeight": 0.1,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b47014",
            "hash": "voke",
            "amount": 5,
            "totalWeight": 2.5,
            "singleWeight": 0.5,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b47015",
            "hash": "mate",
            "amount": 5,
            "totalWeight": 2.5,
            "singleWeight": 0.5,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b47016",
            "hash": "bitterlemon",
            "amount": 5,
            "totalWeight": 2.5,
            "singleWeight": 0.5,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b47017",
            "hash": "spezi",
            "amount": 3,
            "totalWeight": 1.5,
            "singleWeight": 0.5,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b47018",
            "hash": "chickenVings",
            "amount": 6,
            "totalWeight": 4.800000000000001,
            "singleWeight": 0.8,
            "subitems": []
        },
        {
            "_id": "65e38c18cb9323bcf4b47019",
            "hash": "simcard",
            "amount": 1,
            "totalWeight": 0.01,
            "singleWeight": 0.01,
            "data": {
                "label": "1822-50031427"
            },
            "subitems": []
        }
    ],
    "usedSpace": 125.21000000000001,
    "totalSpace": 3000,
    "hasPrices": false
}

**Comment by jonesXYZ** [comment]
Es kann sein das es nach diesem Fehler aufgetreten ist:

https://github.com/eiksch/statev_v3_issues/issues/3118

**Comment by Xymena** [comment]
Es betrifft nicht nur das Schneiden von Frisuren, und Bärten  mittlerweile geht das färben auch nicht mehr. und es wird ein anderes Rezept angezeigt 
![image](https://github.com/eiksch/statev_v3_issues/assets/76626768/74a4c724-989d-462a-a83b-982962ba4f58)

**Comment by nb431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Friseurladen Bug](https://trello.com/c/ATidXSrY/419-friseurladen-bug)

**Comment by Xymena** [comment]
### **Was Funktioniert:**

Färben und ändern der Frisuren
Hinzufügen und Entfernen der Langbärte.

### **Was nicht Funktioniert**
Färben und ändern der Augenbraun
Färben und ändern  von Bart

### **Wo wir nicht wissen ob  es zu Fehler gibt**

Generelles Schminken und entfernen von Makeup aufgrund nicht beschaffbarer Matrialien.

**Comment by simplycach** [comment]
Wie sieht's aktuell aus, ist nochmal was aufgefallen ? 

Noch nicht fixed.

**Comment by simplycach** [comment]
Sollte fixed sein, wenn nicht nochmal melden.

**Comment by TheOutburst** [comment]
Schminke, sonstiges Makeup Zeuch alles next update fixed
