### ISSUE TITLE
Aloe Vera Samen Ultra Rar - 1:1000

### ISSUE THREAD

**Issue by AideenCarter** [mexyn/statev_v2_issues#3121]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Aideen_Carter**

**Aideen_Carter**
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Generell
**Beobachtetes Verhalten**

Alore Vera Samen Ultra Rar
**Erwartetes Verhalten**

idk ?!
**Schritte um den Fehler nachvollziehen zu können**

Samen sammeln und testen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Aloe Vera Samen droppen nicht](https://trello.com/c/SPPjluMu/412-aloe-vera-samen-droppen-nicht)

**Comment by AideenCarter** [comment]
https://gyazo.com/094f8389b275359802983392f6b38787 

Update von Heute :)

**Comment by TheOutburst** [comment]
Wie im Ticket geschrieben, die droppen schon, nur anders
Leichte Anpassung next update
