### ISSUE TITLE
Hauseinbruch Marker von mehreren gleichzeitig bearbeitet werden

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3122]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared & Samuel Navarro
**Auftrittszeitpunkt (Datum / Uhrzeit)**

03.03 ca 14 Uhr
**Beobachtetes Verhalten**

Bei einem Einbruch können mind. 2 Leute gleichzeitig einen Punkt abarbeiten. #TeamworkMakesTheDreamWork 
Wenn es der Letzte ist kommt auch 2. die nachricht, dass alles mitgenommen wurde
**Erwartetes Verhalten**

Es sollte nicht möglich sein zu zweit einen Marker zu machen
**Schritte um den Fehler nachvollziehen zu können**

Hauseinbruch zu zweit starten und gleichen spott "E" drücken
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Wissen wir bereits ist demnächst fixed. Solange bitte nicht so nutzen.
