### ISSUE TITLE
Telefon Anruf bei geteilter Simkarte

### ISSUE THREAD

**Issue by Shirobaka** [mexyn/statev_v2_issues#3123]
Ben Carter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.03.2024 17:23

**Beobachtetes Verhalten**
Wenn mehrere Personen eine SIM-Karte mit der gleichen Nummer besitzen (Sim-Karte geklont) und diese Nummer angerufen wird und einer den Anruf annimmt, klingelt es bei allen anderen mit der Nummer weiter, man kann den Anruf allerdings nicht mehr entgegennehmen bzw. ablehnen, man muss in den Einstellungen des Smartphones den Klingelton einmal kurz Starte und wieder Stoppen damit das Klingeln aufhört.

**Erwartetes Verhalten**
Das Klingeln sollte bei allen aufhören sobald einer dran geht.

**Schritte um den Fehler nachvollziehen zu können**
SIM-Karte kopieren und an eine andere Person geben, eine Person nimmt den Anruf an, bei der anderen Person klingelt es aber weiter.

**Comment by simplycach** [comment]
Also ich hatte den Fehler bisher noch nicht und man kann damit eigentlich auch ganz gut umgehen, wenn mehre Leute eine Sim-Karte haben.
