### ISSUE TITLE
Rotation Bug / Ausparken von Garage und sonstiges

### ISSUE THREAD

**Issue by Oguzhan57x** [mexyn/statev_v2_issues#3124]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Jamiro Ortiz
Haus Hash: house_Davis_4**

**Allgemein. Bemerkt seit einigen Tagen und auch am 03.03.2024**

**Fahrzeuge werden Teleportiert (Größtenteils Motorräder) und hängen sich in Zäunen fest und kriegen eine rote Kontrollleuchte. Ebenfalls wenn die Fahrzeuge in die Hausgarage TPt werden, spawnt mein Auto schief und somit im oder auf dem Zaun wodurch es beschädigt wird und manchmal nicht gefahren werden kann**

**Dass die Fahrzeuge sich nicht bewegen bzw dass die wenn sie ausgeparkt werden in Fahrtrichtung spawnen**

**Auto stehen lassen und einige zeit entfernen bzw nicht fahren**

**https://pic.statev.de/image/HPUL1t 
https://pic.statev.de/image/HPUd6n
https://pic.statev.de/image/HPUwvk**

**Comment by simplycach** [comment]
Hey das ist leider ein AltV Problem, wir müssen da leider auf ein Update von denen Warten. Solange am besten die Bikes einparken.

**Comment by Oguzhan57x** [comment]
@simplycach - Auch das mit dem Garageneinparken?

**Comment by simplycach** [comment]
Sollte fixed sein, wenn nicht Ticket nochmal öffnen.
