### ISSUE TITLE
Aktivieren des Tempomats beim Grotti GT 500 meist nicht möglich

### ISSUE THREAD

**Issue by prtnncrn** [mexyn/statev_v2_issues#3126]
Character Name: Alfredo_Marianni

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.03.2024 zwischen 21:10 Uhr und 21:37 Uhr
Jedoch tritt der Fehler Regelmäßig auf

**Beobachtetes Verhalten**
Bei dem Auto Grotti GT 500 ist es nicht möglich den Tempomat zu aktivieren, dieses Verhalten tritt
vermehrt nach dem betanken des Fahrzeugs auf.
Das aktivieren des Tempomats ist meist, aber nicht immer, nach dem reloggen möglich.

**Erwartetes Verhalten**
Der Tempomat lässt sich mit der "Ende"-Taste, im Grotti GT 500, aktiveren und deaktivieren.

**Schritte um den Fehler nachvollziehen zu können**
- Grotti GT 500 starten 
- Tempomat versuchen zu aktivieren
- Wenn Tempomat aktiviert -> Tempomat deaktivieren
- Grotti GT 500 betanken
- Versuchen Tempomat zu aktivieren

**Comment by SHaagmann** [comment]
#3007  Duplikat

Einfach werbung ausmachen
