### ISSUE TITLE
Anschnall Symbol Flasch nach Geklauten Auto abgeben

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3127]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Vor 2 Tagen oder so
**Beobachtetes Verhalten**

Wenn man angeschnallt ein Auto abgibt, wird der Status zwar resettet, dass UI aber nicht, wodurch eine Unstimmigkeit entsteht
**Erwartetes Verhalten**

Beides sollte sich gleich verhalten
**Schritte um den Fehler nachvollziehen zu können**

1. Auto Klauen
2. Auto abgeben
3. In anderes Auto was bereitsteht zum abhauen einsteigen
4. Verwundert sein ob man jetzt angeschnallt ist oder nicht
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://medal.tv/de/games/gta-v/clips/1YlnpQ0vEnFc52/d1337aTbs6bH?invite=cr-MSw4T0UsMTk1NTEzMTMzLA

**Comment by nb431** [comment]
Grüße ich habe dir das mal angeschaut und versucht zureproduzieren 
ich denke das problem ist aufgetretten weil du zuschnell eingestiegen bist.

**Comment by SHaagmann** [comment]
> Grüße ich habe dir das mal angeschaut und versucht zureproduzieren ich denke das problem ist aufgetretten weil du zuschnell eingestiegen bist.

Das war nicht das einzige Mal. Das ist mir davor schon mehrfach passiert und danach auch. Hab ich nur gefixed nachdem ich aus meinem Wagen nochmal rausgegangen bin dann war alles fine

**Comment by simplycach** [comment]
Mhm @SHaagmann du bist auch immer wie Speed Gonzales in der Karre drin :D

**Comment by SHaagmann** [comment]
@simplycach Gotta Go Fast 😂
Kanns die Tage ja nochmal gemächlicher ausprobieren. Nur normalerweise will man halt nachdem man was illegales gemacht hat schnell weg 😅

**Comment by simplycach** [comment]
Ja guck mal

**Comment by SHaagmann** [comment]
@nb431 Also an der geschwindigkeit kann es nicht liegen: https://www.youtube.com/watch?v=A8BaFuKFphk
