### ISSUE TITLE
Inventar Bug

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#3128]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
James Carter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
04.03.24 - 08:29

**Beobachtetes Verhalten**
Inventar buggt. Es werden keine Items angezeigt und oben beim Gewicht steht nur ####/####kg

**Erwartetes Verhalten**
Alles klappt wie gewohnt

**Schritte um den Fehler nachvollziehen zu können**
War direkt nach dem Login. Nach einem Relog war es wieder okay.
Ist bei mir allerdings schon mehrfach aufgetreten. zuletzt gestern Abend.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/70150887/bacd0eeb-ff51-4182-a32c-30e6bf1374b2)

**Comment by simplycach** [comment]
![image](https://github.com/eiksch/statev_v3_issues/assets/105867680/aa3e414b-99b0-4a5e-930c-c14804099792)

**Comment by TheBroady** [comment]
Hi zusammen,

ich habe gerade gemerkt, dass mit dem Bug auch das Restaurant z.B nicht nutzbar war. Es gab keine Marker in Sandy Shores & der NPC fehlte.

vielleicht is das noch hilfreich ;)

**Comment by TheBroady** [comment]
Heyho,
ich hab nochmal neuen Input.

ich habe mich heute morgen eingeloggt, und hatte plötzlich folgendes im Inventar:
Ich habe leider kein Foto des direkten Inventars, sondern nur das Kleidermenu.
![image](https://github.com/eiksch/statev_v3_issues/assets/70150887/c555c1a2-e173-4c7d-94d8-637d0e58cdab)

Mein eigentliches Inventar sollte so aussehen:
![image](https://github.com/eiksch/statev_v3_issues/assets/70150887/dc0eb77f-eee7-441b-a30d-e05022cd5bb8)


Kurz darauf hatte ich wieder den oben beschriebenen Bug mit den #####/##### & konnte im Restaurant nichts essen.
Durchs Löschen des AltV Cache habe ich mein Inventar wieder bekommen und alles ist wieder gucci.

Es sieht fast so aus, als hätte ich kurz ein fremdes Inventar gehabt.

**Comment by simplycach** [comment]
Sollte jetzt fixed sein, wenn nicht bitte nochmal bei uns melden.
