### ISSUE TITLE
Umlagerung Inventar bei bsp. Lager -> Fahrzeug

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#3130]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
James Carter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Beobachtetes Verhalten**
Habe Benzin aus meiner Raffinerie in meinen MTL geladen.
Nach meinem Stand kann ich wenn ich bsp. 3000 Liter im Lager habe diese einfach in den LKW ziehen. Dort sollte dann nur das eingeladen werden was auch tatsächlich passt (450L)
Allerdings konnte ich nichts einladen, da ich die Meldung bekommen habe das ich nicht genug platz für die 3000 Liter habe.
Schön wäre wenn dadurch das drücken von Q mit der angabe der exakten Menge rausfällt.

**Erwartetes Verhalten**
Nicht wieder Q drücken müssen und eine genaue Menge angeben müssen.
Wenn man eine Menge rüber zieht, soll diese komplett rüber gelagert werden bis der Lagerplatz voll ist.
500 Liter Platz : von 1000 Liter die man rüber zieht werden dann nur 500 ins Fahrzeug gepackt ohne mit Q die genaue Menge angeben zu müssen.

**Schritte um den Fehler nachvollziehen zu können**
Probieren 2000 Liter von Firma in Fahrzeug zu ziehen. Ohne Q drücken um die genaue Menge festzulegen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TheBroady** [comment]
War bereits ein V2 Issue von mir: https://github.com/eiksch/statev_v3_issues/issues/1807

**Comment by QA-Pregon** [comment]
Next Update
