### ISSUE TITLE
Training Strand (Hängen Szenario)

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#3131]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
James Carter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
jederzeit

**Beobachtetes Verhalten**
Die Animation beim Szenario "Hängen" ist optisch nicht so schön. Vielleicht gibts da alternativen oder möglichkeiten das anzupassen.

**Erwartetes Verhalten**
Weniger Wackeln und rumrutschen

**Schritte um den Fehler nachvollziehen zu können**
Szenario Hängen am Vespucci Beach ausführen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/H5AYCh-fKHY

**Comment by TheOutburst** [comment]
Joa, also was schöneres gibts nicht, weil man frei hängt
Habs einfach ma raus genommen :D
