### ISSUE TITLE
Ausdauer wird beim Jetski/Auto fahren trainiert

### ISSUE THREAD

**Issue by MayorHaxe** [mexyn/statev_v2_issues#3133]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Jake Maverick**

**04.03.2024 um ca. 18.15 Uhr bis 18.40 Uhr**

**Es fing auf dem Jetski fahren an das ich bemerkt habe meine Ausdauer wird trainiert und dies zog sich im Auto weiter bis ich das Tageslimit erreicht habe das meine Muskeln Zeit zum aufbauen benötigen**

**Die Ausdauer sollte lediglich beim Joggen, Sprinten, Schwimmen oder Rad fahren antrainiert werden.**

**Möglicherweise sich einen Jetski leihen mit dem 5-10 Minuten rumfahren und dann durchs weiterfahren oder Auto fahren beobachten ob dadurch die Ausdauer trainiert wird**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://github.com/eiksch/statev_v3_issues/assets/162180227/f3093ad3-96b1-4379-84e7-34c17ef5e803

**Comment by Erumeldor** [comment]
Wie schon im Discord bereits geschrieben, bekommen wir das nicht reproduziert. Ich lass das Issue daher mal offen.

**Comment by simplycach** [comment]
Sollte nicht mehr vorkommen, wenn doch bitte Ticket aufmachen.
