### ISSUE TITLE
Kosten konnten nicht berechnet werden Big H. 

### ISSUE THREAD

**Issue by nikosz233** [mexyn/statev_v2_issues#3134]
Wollten grade ein Rezept(Blue Crystal) kaufen bei Big H und es kam die meldung die kosten konnten nicht berrechnet werden

![image](https://github.com/eiksch/statev_v3_issues/assets/162190937/88e90fed-cf70-4107-993a-f3650f850e79)

**Comment by TheOutburst** [comment]
Lul, seh ich ja jetzt erst
wurd vor 3 oder 4 Updates gefixt
