### ISSUE TITLE
Elegy2 nach Tuning mit größerer Kollision

### ISSUE THREAD

**Issue by Larslol140** [mexyn/statev_v2_issues#3135]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Irvin_Pry

**Auftrittszeitpunkt (Datum / Uhrzeit)**

4.3.2024 20:56 Uhr

**Beobachtetes Verhalten**

Wagen ist unfahrbar, kleinere Schlaglöcher oder unebenheiten bringen das Auto zum überschlagen. Bordsteine sind wie wände und können nicht überquert werden.

**Erwartetes Verhalten**

Es wurde kein Tuning vorgenommen, also sollte der Wagen sich wie zuvor normal verhalten.

**Schritte um den Fehler nachvollziehen zu können**

Mit Wagen in die Werkstatt fahren, Tuning UI öffnen und wieder schließen.

Vielleicht auch mit Lackierung, Reparaturen funktionieren aber wohl ohne Probleme.

Wagen: Elegy RH8

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://github.com/eiksch/statev_v3_issues/assets/25729499/441dafdb-1135-4e55-b43e-899b506163ae

**Comment by Erumeldor** [comment]
Wir schauen mal, ob wir da was dran ändern können. 
Habs zumindest nachstellen können.

**Comment by BensiMusic** [comment]
Mein Buccaneer ist nach Dach Tuning (nur Dach Tuning) unfähig, Bürgersteige hochzufahren, kommt aus kleinen Schlaglöchern nur schwer raus und, wie oben im Video, ist er gefühlt bei der kleinsten Bodenwelle sofort am rumfliegen. 
Fixen konnte ich das Problem durch ein und ausparken. Danach war alles super und wie gehabt

**Comment by Larslol140** [comment]
Ich glaube das gewisse sachen den wagen auf die niedrigste stufe beim tieferlegen setzten, was bei manchen fahrzeugen probleme macht.

**Comment by DrGrizzlY17** [comment]
altV hat hier leider einen Fehler bzw laut altV ist es GTA selber mit den Extras. Am besten Fahrzeug direkt einparken, dann sollte es behoben sein

**Comment by TheOutburst** [comment]
Ist bei alt:V von mehreren Servern gemeldet & eskaliert, wir müssen hier leider einfach auf nen Fix von den Jungs warten, ich mach hier mal zu, wir können hier nichts wirklich machen
