### ISSUE TITLE
Blitzertickets bei Carlos-Jobs

### ISSUE THREAD

**Issue by Diak27** [mexyn/statev_v2_issues#3138]
**Tyrese_Stone**

**04.03.2024**

Wenn man ein Job bei Carlos macht und ein Auto klaut, damit dann abhaut und durch nen Blitzer fährt, gibts ja nen Instant-Ticket

Weiss nicht, aber wenn ich nen Auto klaue in der Mission, und bin ja auch maskiert, sollte ich mit der geklauten Karre keinen Ticket bekommen, da man mir das Auto ja nicht zuordnen kann. Vielleicht kann man sich das ja mal angucken ob das technisch überhaupt umsetzbar ist.

**Comment by Flachmeyer** [comment]
Mann soll auch geblitzt werden wenn man ein Auto klaut. Das hat so seine Richtigkeit
