### ISSUE TITLE
Lager Bug in der Weberei

### ISSUE THREAD

**Issue by DerHessenTyp** [mexyn/statev_v2_issues#3139]
Auftrittszeitpunkt: Seit dem 02 oder 03. März zur Uhrzeit kann ich jetzt nichts genau sagen aber es ist aktuell scheinbar noch der Bug vorhanden, da eine Weberei derzeit 1300x Rollen Stoff (3900 kg) am Marktplatz anbietet bei einer Lagerkapazität von 1500kg.

**Beobachtetes Verhalten**
Sobald man ein aktives Marktplatzangebot z.b. Rolle Stoff 500 Stück á 3 KG aus dem Marktplatz entfernt, zusätzlich aber schon Rollen Stoff oder andere Waren im Lager liegen hat, ist es möglich das Lager mit mehr KG auszureitzen. Ich bin mir sicher, dass es zu V2 auf jedenfall der Fall war, dass man Angebote dann nicht mehr löschen konnte, solange man den Platzprobleme im Lager hatte.

**Erwartetes Verhalten**
Das man nur soviel ins Lager räumen kann wie möglich bzw. man keine Angebote löschen kann solange nicht der vorhandene Platz vorhanden ist.

**Schritte um den Fehler nachvollziehen zu können**
Waren im Lager von einer bestimmten KG Anzahl
Angebot aus dem Marktplatz löschen was die Lagerkapazität sprengen würde
Man 1503kg im  Lager (z.b. wenn eine Spitzhacke im Lager liegt) hat statt nur den möglichen 1500kg

**Comment by SatyriaDine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Firmenlager Bug](https://trello.com/c/6cAgq5vp/430-firmenlager-bug)

**Comment by Erumeldor** [comment]
Fixed im nächsten Update.
