### ISSUE TITLE
Useables Essen/Trinken in der Hand anzeigen

### ISSUE THREAD

**Issue by stormbreaker22** [mexyn/statev_v2_issues#314]
**Character Name**

Kilian_Smith

**Zeitpunkt (Datum / Uhrzeit)**

21.11.2020 14:58

**Beobachtetes Verhalten**

Beim essen einiger Früchte wird diese nicht in der Hand angezeigt.

**Erwartetes Verhalten**

Die Früchte sollten in der Hand zusehen sein wenn diese gegessen werden.

**Schritte um den Fehler nachvollziehen zu können**

Beim essen von Pampelmuse , Limette und Zitrone wurde das ganze von mir schon getestet. Orange ist zusehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![früchteessen](https://user-images.githubusercontent.com/61292701/99879126-f7958b00-2c0a-11eb-8ebc-2ca3c1789235.png)

**Comment by stormbreaker22** [comment]
Trift auch bei Kirschen, Himbeeren und Weintrauben zu. Diese sind auch nicht zusehen, falls dies umsetzbar ist bei so kleinen Früchten.

**Comment by DrGrizzlY17** [comment]
Aktuell keine Priorität, deswegen lass ich es erstmal auf und kümmere mich zu einem anderen Zeitpunkt drum

**Comment by DrGrizzlY17** [comment]
@DonVitoDiangelo hätte gesagt hier mal Nytech hinzuziehen für die Props

**Comment by TheNytech** [comment]
Ist notiert. Arbeite nebenbei die Liste mit Gegenständen bereits ab welche noch ein prop brauchen. Wie gesagt low prio, kommt aber.

**Comment by DonVitoDiangelo** [comment]
Kommen nach und nach welche dazu, daher laufender Prozess. Das Ticket wird geschlossen.
