### ISSUE TITLE
Antrag auf Hausgarage (Fudge Lane 8)

### ISSUE THREAD

**Issue by Deloy59** [mexyn/statev_v2_issues#3140]
Grüße, 

Hab mich vorher im Discord übers Ticket System schlau gemacht und wurde hier her verfrachtet.

Es geht um einen Antrag für eine Garage des Objektes "Fudge Lane 8" diese hat auf der Rückseite des Hauses eine kleine Garage angebracht die offensichtlich zu meiner Immobilie gehört 
![Grand Theft Auto V Screenshot 2024 03 05 - 18 17 19 25](https://github.com/eiksch/statev_v3_issues/assets/75677891/00a00690-4e4f-4032-bfbe-da9dcdc80596)
![Grand Theft Auto V Screenshot 2024 03 05 - 18 17 43 100](https://github.com/eiksch/statev_v3_issues/assets/75677891/a8515aec-a3f0-408a-8583-d0ebaa65910b)
![Grand Theft Auto V Screenshot 2024 03 05 - 18 18 45 66](https://github.com/eiksch/statev_v3_issues/assets/75677891/32ff077c-5013-4b53-89d0-0012be9b3cce)

Ob die Ein/Auspark Spots nun vorne über die Einfahrt zu erreichen sind oder realistischerweise auf der Rückseite (vielleicht seitlich zur Straße) ist mir relativ egal und würde ich in eure Hände geben!

**Comment by TheOutburst** [comment]
haste next update
