### ISSUE TITLE
WoCaRu Gas Tankstelle Sandy Shores

### ISSUE THREAD

**Issue by PeterGlore** [mexyn/statev_v2_issues#3141]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Jaro Malone**

Jaro Malone
Franz Koelpe

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot_13](https://github.com/eiksch/statev_v3_issues/assets/74842765/5478fe94-525b-4223-a2b0-24f8516d016f)
![Screenshot_14](https://github.com/eiksch/statev_v3_issues/assets/74842765/21c4cb0e-8ace-4551-93ad-6c87ef73d0af)
![Screenshot_15](https://github.com/eiksch/statev_v3_issues/assets/74842765/588aacf3-2159-455f-8ca6-69429e2170e9)

**Comment by PeterGlore** [comment]
Auftrittszeitpunkt (06.03.24 / gegen 15 Uhr)

Beobachtetes Verhalten
Habe dort mit meinem Youga getankt siehe Bilder das Verhältnis.
Habe darauf eine Person angesprochen, ob die es auch mal testen können, Er hat sein Bison getankt, war die anzeige und berechnung richtig. 
Als er dann sowie ich eine anderen Youga getankt haben, trat der Fehler wieder auf, dass man mehr bezahlt als man getankt hat obwohl der Liter Preis 0.95 $ ist

Erwartetes Verhalten

Das der PReis sowie Liter anzeige richtig dargestellt wird, wie bei dem Bison

Schritte um den Fehler nachvollziehen zu können

wurden 3 Fahrzeuge getestet. 1 Bison 2 Youga mit 2 Personen

**Comment by nb431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WoCaRu Gas Tankstelle Sandy Shores](https://trello.com/c/F4CD3K8M/433-wocaru-gas-tankstelle-sandy-shores)

**Comment by SgtBoaz-Terry** [comment]
Kann nicht reproduziert werden. Beim nächsten Mal wieder melden. Gern auch Video.
