### ISSUE TITLE
Item Darstellung Inventar

### ISSUE THREAD

**Issue by DrColgate** [mexyn/statev_v2_issues#3142]
**Character Name**
Anton Mueller

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.03 15:30 (gestern auch wschon gesehen)

**Beobachtetes Verhalten**
Grafiken werden nicht richtig dargestellt

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
2560x1440

**Optional: Video / Bilder des Fehlers**

![Unbenannt](https://github.com/eiksch/statev_v3_issues/assets/74769835/c87ae6b5-6d3f-4537-9bc4-3ac5a8b8f8f5)

**Comment by nb431** [comment]
Hey ich hätte kurz eine frage welche Grafiken werden nicht richtig dargestellt ?

**Comment by DrColgate** [comment]
Ich meine das Messer

**Comment by nb431** [comment]
Perfekt wissen bescheid Danke für deine einsendung
