### ISSUE TITLE
Wasserkisten Fehler Restaurant / Verpackung?

### ISSUE THREAD

**Issue by LiljaMorningstar** [mexyn/statev_v2_issues#3143]
**Character Name**
Quinn Valen

**Auftrittszeitpunkt (Datum / Uhrzeit)**
0 Uhr

**Beobachtetes Verhalten**
Wenn man eine Kiste Wasser im Restaurant bzw. angeblich auch Clubs entpacken will, bekommt man nurnoch 3 Flaschen als Endprodukt aus der Kiste.
In der Verpackung die die Kisten aber Herstellen, benötigen Sie in der Produktion alles 6x für eigentlich 6 Flaschen Wasser im Restaurant und Co.

**Erwartetes Verhalten**
Dadurch wird der Preis für eine Flasche Wasser im Restaurant zu hoch da das Restaurant mehr bezahlt als es eigentlich erhält. Es wäre also schön wenn man das angleichen könnte. Entweder auf Seiten der Verpackung dass die weniger Material brauchen, Oder auf Seiten der Restaurants bzw. Bars dass die die verpackten 6 Flaschen erhalten.

**Optional: Video / Bilder des Fehlers**

https://pic.statev.de/image/kiste-wasser-fehler.HPet8t

**Comment by SatyriaDine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Wasserkisten Fehler Restaurant / Verpackung](https://trello.com/c/g5SzivmP/447-wasserkisten-fehler-restaurant-verpackung)

**Comment by TheOutburst** [comment]
das ist so korrekt
