### ISSUE TITLE
VCOM falsche Uhrzeit und Datum - Aktenerstellung

### ISSUE THREAD

**Issue by einfachLissy** [mexyn/statev_v2_issues#3144]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

 

 Leyla Parker

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 07.03.2024 - 01.00 Uhr

**Beobachtetes Verhalten**
 Bei den Akten Einträgen des VCOM, wird dauerhaft Montag 19.01 Uhr angezeigt.

**Erwartetes Verhalten**
 Akteneinträge sollten an dem Tag und an um die Uhrzeit angezeigt werden, wann die Einträge erstellt wurden.

**Schritte um den Fehler nachvollziehen zu können**
 In VCOM eine Akte erstellen/ Zeugenaussage erstellen.
![53dfgfdgdfg](https://github.com/eiksch/statev_v3_issues/assets/76963114/24ce61c7-8684-4659-b0df-27cd89522ed1)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by rodistic** [comment]
Fixed im nächsten Update @simplycach
