### ISSUE TITLE
Auto Nach Depo noch immer Putt

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3146]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

07.03 22:50
**Beobachtetes Verhalten**

Auto wurde nach Explosion (Boom) aus dem Depo geholt und die 250$ gezahlt.
nach 2 Metern ist mir aufgefallen, dass ich 4 Platte Reifen habe
**Erwartetes Verhalten**

Reifen Heile
**Schritte um den Fehler nachvollziehen zu können**

Auto Boom machen lassen
Aus Depo holen
Traurig sein, dass es noch immer Putt ist 
Noch Trauriger bei der Werkstatt Rechnung werden

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://medal.tv/de/games/gta-v/clips/1ZAxHxomGAC4OG/d1337vuknI77?invite=cr-MSxDd0ssMTk1NTEzMTMzLA

**Comment by nb431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Auto Nach Depo noch immer Kaputt](https://trello.com/c/gWpgQRfl/443-auto-nach-depo-noch-immer-kaputt)

**Comment by simplycach** [comment]
Ist das noch aktuell ?

**Comment by simplycach** [comment]
Ich mach erstmal zu, wenn es nochmal vorkommt nochmal aufmachen.
