### ISSUE TITLE
Animationsnamen vertauscht - Bewusstlos

### ISSUE THREAD

**Issue by JohnnyNobody98** [mexyn/statev_v2_issues#3147]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Johnathan_Maedows

**Auftrittszeitpunkt (Datum / Uhrzeit)**

08.03. 14.42 und vorher

**Beobachtetes Verhalten**

Namen der Animationen vertauscht, Fehler ist reproduzierbar
Abspielen der Animation "Bewusstlos (Bauch)" Charakter liegt auf dem Rücken
Abspielen der Animation "Bewusstlos (Rücken)" Charakter liegt auf dem Bauch

**Erwartetes Verhalten**

Abspielen der Animation "Bewusstlos (Bauch)" Charakter soll auf dem Bauch liegen 
Abspielen der Animation "Bewusstlos (Rücken)" Charakter soll auf dem Rücken liegen 

**Schritte um den Fehler nachvollziehen zu können**

Animationssuche öffnen - Bewusstlos suchen - Beide Animationen abspielen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

XXX

**Optional: Video / Bilder des Fehlers**

https://i.gyazo.com/cd47de4f3f511faa9ff9c903c8258d87.mp4

**Comment by nb431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Animationsnamen vertauscht - Bewusstlos](https://trello.com/c/gSPcS7UP/444-animationsnamen-vertauscht-bewusstlos)
