### ISSUE TITLE
Schwebende Zigarettenschachtel 

### ISSUE THREAD

**Issue by PeterGlore** [mexyn/statev_v2_issues#3148]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Jaro Malone**

**Auftrittszeitpunkt (08.03.24 / 17:16 Uhr)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot_3](https://github.com/eiksch/statev_v3_issues/assets/74842765/6d29eb2a-c066-46d4-90bd-f5e02de698d4)

**Comment by PeterGlore** [comment]
![Uploading Screenshot_4.png…]()

**Comment by PeterGlore** [comment]
![Uploading Screenshot_5.png…]()

**Comment by nb431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Schwebende Zigarettenschachtel](https://trello.com/c/CTRR5uBS/445-schwebende-zigarettenschachtel)

**Comment by TheOutburst** [comment]
Einfach auch mal keine Clientmod haben
