### ISSUE TITLE
Hotelzimmer auf 1 Dollar / Falsche Anzeige im Vnet

### ISSUE THREAD

**Issue by Raze9900** [mexyn/statev_v2_issues#3149]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Miguel_Torrado

Miguel_Torrado

**Auftrittszeitpunkt (Datum / Uhrzeit)**

08.03.2024 ca. 11 Uhr

**Beobachtetes Verhalten**

Hi, leider hab ich erneut ein Problem mit dem Hotel Hash SandyShores_Flat_4. Mir wurde im Vnet angezeigt das ein Zimmer frei geworden ist. Als ich hochgefahren bin um nach zu schauen ob Müll etc vom Vormieter im Zimmer ist stellte ich das Freie Zimmer auf dem Parkplatz auf 1 Dollar runter um mich selbst kurz ein zu mieten. An der Türe wurde mir das Zimmer dann als belegt angezeigt im Tablet immer noch als Frei. Nach mehrfachem Neuladen sowohl im Tablet als auch über meinem Webbrwoser wurde dann ein Mieter angezeigt. Mein Problem ist jetzt das der Mieter mit dem Namen Michael_Tricle ungewollt ein 1 Dollar Zimmer hat und ich dieses nicht mehr auf den Normalpreis von 20 Dollar hochstellen kann. Leider habe ich keinen Clip davon gemacht da ich zu spät daran gedacht habe. 

**Erwartetes Verhalten**
Zimmer sollte nicht als Leer angezeigt werden im vnet wenn es besetzt ist. / Zimmer sollte am besten wieder auf den Normalpreis von 20 Dollar gesetzt werden.

**Comment by simplycach** [comment]
Ist nicht mehr aktuell.
