### ISSUE TITLE
Kleidung verbuggt/nicht sichtbar

### ISSUE THREAD

**Issue by Oguzhan57x** [mexyn/statev_v2_issues#3150]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Jamiro Ortiz**

**08.03.24 - 21:00-21:30**

**Ein T Shirt kann man sich im Klamottenladen angucken wenn man es jedoch anzieht, verschwindet es in der Kleidung und man sieht nichts davon. Wenn man Oberkörperfrei ist, dann sieht man garnichts vom T Shirt**

**Dass man die Kleidung sieht**

**T Shirt im klamottenladen anschauen, kaufen und versuchen anzuziehen**

**https://pic.statev.de/image/HWPJQg**

**Comment by l4m4rr224** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T-Shirt nicht anziehbar](https://trello.com/c/ensb4jZm/446-t-shirt-nicht-anziehbar)

**Comment by simplycach** [comment]
Wurde erstmal rausgenommen.
