### ISSUE TITLE
VNET Absturz nach Überweisung

### ISSUE THREAD

**Issue by StateV-Jan** [mexyn/statev_v2_issues#3151]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Liam_Taylor**

Liam_Taylor
**Auftrittszeitpunkt (Datum / Uhrzeit)**
 08.03.2024 21:15

**Beobachtetes Verhalten**
 Nach dem Überweisen an ein Unternehmen (Bishop Carfactory) hat das Tablett sich kurz aufgehangen und hat dann für ca 2 sek Fehler 400 angezeigt. Danach lädt das VNet nicht mehr

**Erwartetes Verhalten**
 Nach Überweisung sollte Vnet weiterhin stabil bleiben

**Schritte um den Fehler nachvollziehen zu können**
 Überweisung von ca 10500 Dollar machen 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Scheint jetzt nen kein großes Problem zu sein sondern nur ein seltener Case, hast du dadurch etwas verloren ?

**Comment by StateV-Jan** [comment]
Hab dadurch nichts verloren

**Comment by rodistic** [comment]
Kann es leider nicht reproduzieren. Bitte im Auge behalten, kann sein das es zu dem Zeitpunkt ein Background VNET Hotfix lief

**Comment by simplycach** [comment]
Ich schließe das hier mal, wenn es nochmal aufkommt bitte erneut melden.
