### ISSUE TITLE
Fehlendes Tuning beim Vapid Slamvan

### ISSUE THREAD

**Issue by DonJohn1993** [mexyn/statev_v2_issues#3152]
Reggie_Jennings

08.03.24 23:00

**Beobachtetes Verhalten**
Keine Tuningmöglichkeiten beim Vapid Slamvan vorhanden. Es ist absolut gar nichts zum Tunen vorhanden.

**Erwartetes Verhalten**
https://www.youtube.com/watch?v=-OSgHn0gZPU

![Screenshot 2024-03-08 225152](https://github.com/eiksch/statev_v3_issues/assets/79906053/a4df009c-3e92-4ddb-b6b0-45d09862cecb)

Soll das so? Wäre ziemlich schade, da die Karre eigentlich zwecks RP geleased wurde. Tuningtreffen, Werkstatt-Showcase etc

**Comment by SatyriaDine** [comment]
Das ist der normale Slamvan, der hat nicht viele Tuningmöglichkeiten. Der Slamvan Custom hat dafür mehr Optionen :)
