### ISSUE TITLE
Tore und Türen der Metzgerei "teleportieren" einen in die Stadt 

### ISSUE THREAD

**Issue by Rehki** [mexyn/statev_v2_issues#3153]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Rayana Vemo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
09.03.2024  23:00

**Beobachtetes Verhalten**
Einige Türen und Tore in der Metzgerei lassen sich öffnen bzw gehen auf, wenn man durch diese durchgeht befindet man sich in der Stadt, selbst vom County aus. ( Hier in Grapeseed) 

**Erwartetes Verhalten**
Türen/Tore lassen sich nicht öffnen 
**Schritte um den Fehler nachvollziehen zu können**
Metzgerei betreten und Türen und Tore ausprobieren welche sich öffnen lassen 

**Optional: Video / Bilder des Fehlers**

![Grand_Theft_Auto_V_Screenshot_2024 03 09_-_23 10 13 87](https://github.com/eiksch/statev_v3_issues/assets/87999101/dca1a6ae-70d8-4179-9215-cc45126d2fca)
![Grand_Theft_Auto_V_Screenshot_2024 03 09_-_23 11 23 50](https://github.com/eiksch/statev_v3_issues/assets/87999101/fba5232e-ca80-4448-af14-764d57212e48)

**Comment by SatyriaDine** [comment]
Ist bekannt, bitte nicht nutzen. Ihr landet dann eh im endlosen Void :P #3075
