### ISSUE TITLE
Abladepunkte sind schwer zu erkennen..

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3154]
Im dunklen ist das wirklich ein grauß... ^^

![Screenshot_20](https://github.com/eiksch/statev_v3_issues/assets/70241137/748265c3-ab65-4a60-b574-e14bb4cdf719)

![Screenshot_21](https://github.com/eiksch/statev_v3_issues/assets/70241137/36c8d260-6a31-44da-a3d6-8fcbab4209d4)

![Screenshot_22](https://github.com/eiksch/statev_v3_issues/assets/70241137/f84ec9eb-153d-440e-8d82-437abeddae54)

**Comment by simplycach** [comment]
Also ich weiß immer nicht was du machst aber bei mir sind die Super Sichtbar xD 

Reshade hast du nicht drauf oder ?

**Comment by Statev-Bonsai** [comment]
nein, garnix dergleichen..
ich kenne viele die probleme mit erkennen der abladepunkte haben..

du bruachst ja nur die bilder anschauen, ist echt schwer erkennbar..

**Comment by TheOutburst** [comment]
Moin

das ist mit absicht so, damit das das Stadtbild nicht so versaut
Wir können den Issue ja mal paar Tage auf lassen ob sich paar Stimmen finden die das auch klarer sichtbar haben wollen

**Comment by WalDragoner3425** [comment]
Also ich finde es gut, dass die mittlerweile kaum sichtbar sind. Klar mag man den ein oder anderen dann nicht immer direkt finden aber nach einiger zeit hat man eh raus, wo die die man häufig braucht, sind. Also ich finde es gut so wie es ist, finde die haben früher immer krass genervt.

**Comment by CCastles22** [comment]
stimme ich Bonzai zu, viel zu "unsichtbar" die Entladepunkte
Das Argument das es das Stadtbild versaut kann man glaube ich damit entkräften das man die Marker deaktivieren kann

**Comment by WalDragoner3425** [comment]
> stimme ich Bonzai zu, viel zu "unsichtbar" die Entladepunkte Das Argument das es das Stadtbild versaut kann man glaube ich damit entkräften das man die Marker deaktivieren kann

Bin ich anderer meinung. is mir persönlich viel zu nervig dass immer wieder an und auszuschalten, da schaue ich lieber mal etwas genauer hin, wenn man mal einen von vielen markern nicht gut erkennt.

**Comment by CCastles22** [comment]
hm naja  du musst dich schon entscheiden was dir wichtiger ist entweder Stadtbild oder Komfort, ein anderer Aspekt ist auch noch das viele anderen Leute nicht so genau hinschauen und dir deine Abladepunkte zuparken (alles schon zuhauf passiert bei mir und meinem Nachbarn, musste dann Geld in die Hand nehmen um meine "Zone" sichtbarer zu machen)

**Comment by TheOutburst** [comment]
ich hab ma sneaky die Sichtbarkeit leicht erhöht, ist das so gut für euch?
@Statev-Bonsai @CCastles22

**Comment by Statev-Bonsai** [comment]
jawoll.. kann man so lassen..
