### ISSUE TITLE
Massiver Ausdauerverlust trotz viel Sport

### ISSUE THREAD

**Issue by EaselWeasel** [mexyn/statev_v2_issues#3155]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Sebastian_Blackwood

**Auftrittszeitpunkt (Datum / Uhrzeit)**
10.03.2024 gegen etwa 18:00

**Beobachtetes Verhalten**
Beim Fahrradfahren und Sprinten sinkt die Ausdauer sehr schnell wie ganz am Anfang, vor Training etc.

**Erwartetes Verhalten**
Gestern ging die Ausdauer gar nicht runter und davor auch schon sehr sehr viel langsamer.

**Schritte um den Fehler nachvollziehen zu können**
Einer Aktivität nachgehen die Ausdauer verbraucht und vergleichen wie es gestern war.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Hast mal nen Video bitte

**Comment by simplycach** [comment]
Hey sollte mit dem neuen Update besser geworden sein ansonsten bitte nochmal melden.
