### ISSUE TITLE
Tattoo Shop - Stuhl besetzt..

### ISSUE THREAD

**Issue by CalebPapaCrane** [mexyn/statev_v2_issues#3156]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Caleb_Roberts**

Rayana Vemo
**Auftrittszeitpunkt (Datum / Uhrzeit)**

10:11 Uhr
**Beobachtetes Verhalten**

Kunde hatte das Geld für sein Tattoo auf einem anderen Konto, damit konnte das Tattoo nicht bezahlt und nicht "gestochen" werden. Nun sagt er mir die ganze Zeit, der Stuhl sei besetzt..
**Erwartetes Verhalten**

Abbruch der Aktion um ggf. die Vorlage neu draufmachen zu können
**Schritte um den Fehler nachvollziehen zu können**

1. Summe für Tattoo auf ein separates Konto packen
2. Tattoo machen lassen, kein gedecktes konto triggern
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

FHD
**Optional: Video / Bilder des Fehlers**
 Leider keins

**Comment by Statev-Bonsai** [comment]
ich bekenne mich schuldig.. ^^

**Comment by CalebPapaCrane** [comment]
Hatte dein Namen nicht mehr im Kopf, aber ja! Bonsai war das glaub, alles macht der futsch KEKW

**Comment by simplycach** [comment]
Hey das wird jetzt bis zum nächsten Restart blockiert sein, bitte achte erstmal darauf dass deine Kunden ihr Konto gedeckt haben. 

Ich kann leider noch nicht sagen ob es Technisch machbar ist und wie schnell.

**Comment by nb431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Italiener Testen](https://trello.com/c/BoMkz4sh/451-italiener-testen)

**Comment by simplycach** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tattoo Stuhl besetzt nach Gamecrash](https://trello.com/c/aiOI8rmN/457-tattoo-stuhl-besetzt-nach-gamecrash)

**Comment by simplycach** [comment]
Next update fixed.
