### ISSUE TITLE
Laderampe Firma, Sandy Shores - Harmony

### ISSUE THREAD

**Issue by VeAderian** [mexyn/statev_v2_issues#3157]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Kevin Walker

**Beobachtetes Verhalten**
Laderampe scheinbar von 2 Firmen genutzt

**Erwartetes Verhalten**
Kleiderladen vorne sowie die Firma hinterm Gebäude sollten sepperate Laderampen haben
Firmen hinterm Gebäude Hash:  pf_sandyshores_38 "W+S Lagerhalle"

**Schritte um den Fehler nachvollziehen zu können**
Für die hinten liegende Firma eine eigene Laderampe hinzufügen

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/61833414/ea99aaed-0553-41a0-9e24-85dc278e611a)

**Comment by TheOutburst** [comment]
Jau, das ist bei vielen Firmen so, weil zB wenig Platz ist oder der Platzplatz nutzbar sein soll
Hier letzteres
Das bleibt also so wie es jetzt ist
