### ISSUE TITLE
Klingelton geht weiter wenn jemand anders den Anruf annimmt - Geteilte Simkarte/Firmensimkarte

### ISSUE THREAD

**Issue by AideenCarter** [mexyn/statev_v2_issues#3158]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Aideen_Carter

Aideen_Carter
**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jeder Anruf auf einer Sim die mehrere Leute drin haben

**Beobachtetes Verhalten**
Der Klingelton geht weiter, wenn jemand anderes den Anruf annimmt und man kann ihn nicht mehr abbrechen. 

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by SHaagmann** [comment]
Duplikat #3123
