### ISSUE TITLE
Fehler Restaurant All Osso 

### ISSUE THREAD

**Issue by Matze1993Vapid** [mexyn/statev_v2_issues#3159]
Aktuell gibt es ein Problem das die Gäste nicht gerade am Tisch hocken und der Teller Besteck auf dem Boden liegen 
![IMG-20240311-WA0003](https://github.com/eiksch/statev_v3_issues/assets/162994397/c3adc25c-ec11-4e24-b8cd-a11566af7b71)

**Comment by TheOutburst** [comment]
und man nur auf dem einen Stuhl was essen kann :D

Next update ist dat allet drin
