### ISSUE TITLE
Telefonzellen Bug

### ISSUE THREAD

**Issue by WalDragoner3425** [mexyn/statev_v2_issues#3160]
Die Telefonzelle im Forumdrive (Tel-Nr.: 555-401131) scheint verbuggt zu sein. 

Zuerst ging sie aber als ein Kollege dann damit telefoniert hatte und jemand anderes die Telefonzelle angerufen hatte, ging nichts mehr (kann auch wo anders dran liegen aber erst da haben wir es bemerkt). 
Der kollege, welcher zuvor and der telefonzelle war, konnte dann niemanden mehr anrufen oder angerufen werden genauso wie die person, die die telefonzelle angerufen hat (es kam immer die meldung als ob die person die angerufen wird eine andere sim drinnen hat obwohl es nicht so war). 
Auch bekam der kollege, welcher zuvor an der telefonzelle war, immer eine benachrichtigung, wenn man versucht hat die trelefonzelle anzurufen obwohl er schon längst nicht mehr bei ihr war. 
Nach dem reloggen konnte man mit dem handy wieder untereinander einwandfrei telefonieren, jedoch wird seitdem die telefonzelle als besetzt angezigt bzw siehe bild:
![grafik](https://github.com/eiksch/statev_v3_issues/assets/56478386/cebaabc2-6783-4532-a40f-394f76368534)

**Comment by nb431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Telefonzellen Bug](https://trello.com/c/kxLQRvtP/453-telefonzellen-bug)

**Comment by WalDragoner3425** [comment]
Habe eben nochmal versucht da anzurufen, da ja glaub vorhin ein serverrestart war. beim ersten mal ging es aber beim zweiten mal kam das hier:
![grafik](https://github.com/eiksch/statev_v3_issues/assets/56478386/f66aff5c-7aef-43d2-b69c-45b46a72408a)

**Comment by WalDragoner3425** [comment]
Ich bin jetzt mal eine stunde später an die telefonzelle gegangen und da stand immernoch, dass mein anruf gerade reinkommt. als ich sozusagen rangegangen bin, kam:
![grafik](https://github.com/eiksch/statev_v3_issues/assets/56478386/24fa7840-099b-431f-8bc7-32d214e7431e)


danach bin ich nochmal weg von der telefonzelle und wieder hin und dann kam folgende mledung:

![grafik](https://github.com/eiksch/statev_v3_issues/assets/56478386/ed117921-431e-471c-89f5-54b7aaf07cd5)


Danach war es anderen auch nicht mehr möglich mich anzurufen bzw. wenn die mich angerufen haben, habe ich nur ein tuten gehört (im sinne von ist belegt) aber konnte kein telefonat annehmen.

**Comment by WalDragoner3425** [comment]
wenn man eine telefonzelle anruft und über "n" auflegen möchte, bekommt man auch folgende meldung:

![grafik](https://github.com/eiksch/statev_v3_issues/assets/56478386/da16e191-40ad-4236-a719-e0469e631fc0)


Und wenn man außerhalb des klingel radius ist und dann zur telefonzelle läuft, hört man keinen klingel sound.

warum auch immer bekomme ich jetzt folgende meldung wenn ich nun versuchen will zu telefonieren:
![grafik](https://github.com/eiksch/statev_v3_issues/assets/56478386/286d7cb5-b6af-49bf-8661-63c41b172bb2)

**Comment by simplycach** [comment]
Next Update fixed
