### ISSUE TITLE
Sitzplatz in Italian Cuisine Restaurant

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#3161]
**Character Name**
Charly Russo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.03.24 01:17

**Beobachtetes Verhalten**
Essenstablet unterm Stuhl statt auf dem Tisch

**Erwartetes Verhalten**
Ich würde gerne vom Tisch essen, nicht vom Boden :)

**Schritte um den Fehler nachvollziehen zu können**
Hinsetzen, essen bestellen

**Optional: Video / Bilder des Fehlers**
https://i.imgur.com/mR7as4o.jpg

**Comment by nb431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sitzplatz in Italian Cuisine Restaurant](https://trello.com/c/rWy9fOLs/452-sitzplatz-in-italian-cuisine-restaurant)

**Comment by nb431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Italiener Testen](https://trello.com/c/BoMkz4sh/451-italiener-testen)

**Comment by simplycach** [comment]
Next Update fixed
