### ISSUE TITLE
Flatbed an Werkstatt Marker Freeze

### ISSUE THREAD

**Issue by QA-Pregon** [mexyn/statev_v2_issues#3163]
**Character Name**
David Danilov

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Sowohl vorgestern als auch heute (12.03.2024 Ca. 9:20) 

**Beobachtetes Verhalten**
An beiden Arbeitsplätzen [1] ist das Arbeiten am Flatbed einmal möglich gewesen, beim schließen des Menüs konnte dieser aber nicht weggefahren werden und der Arbeitspunkt ist stuck im Arbeitsmodus (Auch der Reparaturpunkt ist noch von vor 2 Tagen in diesem Modus gefangen)
Dabei ist mir aktuell noch unbekannt ob es am Fahrzeug liegt oder am Arbeitspunkt an sich.

**Erwartetes Verhalten**
Wie in der Werkstatt an sich sollte jeder Punkt den Arbeitsmodus mit dem Schließen Button verlassen

**Schritte um den Fehler nachvollziehen zu können**
Mit einem Flatbed an der LSC Werkstatt [2] im Außenbereich testen, ob der Arbeitsmodus verlassen werden kann und dann das Fahrzeug wegfahrbar ist.
(Gern auch mal andere Fahrzeuge testen zum checken woran das liegt)

**Anhangverzeichnis**
[1] Gemeinten Arbeitspunkte im Außenbereich:
![Screenshot 2024-03-12 092519](https://github.com/eiksch/statev_v3_issues/assets/75855042/fb75415b-df7d-412f-9cce-208b920b6c86)
[2] Location von LSC:
![Screenshot 2024-03-12 093205](https://github.com/eiksch/statev_v3_issues/assets/75855042/46bb1046-94cb-4ff7-9972-d1b936150e48)

**Comment by SatyriaDine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Werkstattpunkte funktionieren nicht richtig](https://trello.com/c/7GMxr2jX/455-werkstattpunkte-funktionieren-nicht-richtig)

**Comment by QA-Pregon** [comment]
Unbestätigte Vermutung:
Es könnte vielleicht an speziellen Fahrzeugen liegen.
Manchmal funktionieren die Punkte, manchmal aber auch nicht.
Mit einem Bison konnten wir zum Beispiel nach Farben gucken und dann wieder wegfahren. Mit dem Flatbed ging es dann aber doch wieder schief.

**Comment by Erumeldor** [comment]
Ist fixed.
