### ISSUE TITLE
Fahrzeugfolierungen werden beim Tunen nicht angezeigt in der Vorschau

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#3164]
**Character Name**
Charly Russo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.03.2024 16:20 Uhr

**Beobachtetes Verhalten**
Fahrzeugfolierungen werden beim Tunen im Menü der Tuningvorschau nicht angezeigt

**Erwartetes Verhalten**
Sollten angezeigt werden wie andere Tuningteile auch

**Schritte um den Fehler nachvollziehen zu können**
Passendes Fahrzeug auf den Tuningpunkt fahren, Spezialaufkleber auswählen

**Optional: Video / Bilder des Fehlers**

Video:
https://www.youtube.com/watch?v=TAjOz_XSbIs

Pastebin Console:
https://pastebin.com/Z725kg9p

**Comment by SatyriaDine** [comment]
Ist bereits bekannt :) #3115
