### ISSUE TITLE
Keine passenden Arme vorhanden für Boyfriend Jacket

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#3165]
**Character Name**
Charly Russo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.03.2024 16:47Uhr

**Beobachtetes Verhalten**
Für die Boyfriend Jackets sind keine passenden Arme vorhanden, weder ohne alles noch mit Magic Corsage

**Erwartetes Verhalten**
Es sollte passende Arme geben.

**Schritte um den Fehler nachvollziehen zu können**
Weiblicher Charakter -> Jacke kaufen -> anziehen und weinen

**Optional: Video / Bilder des Fehlers**
Video:
https://youtu.be/tUmpt5BD3fg

Kleidungsstück:
https://imgur.com/YwI53RI

**Comment by Enemyaa** [comment]
Das Modell wird mit den nächsten Updates ersetzt!
