### ISSUE TITLE
Stuhl besetzt nach Gamecrash!

### ISSUE THREAD

**Issue by Deloy59** [mexyn/statev_v2_issues#3167]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Devin_Jackson

Tyler_Jackson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19:10-19:20, Sandy Shores, Armadillo Ave. 29

**Beobachtetes Verhalten**
Tyler_Jackson legte einer Kundin im Tattooshop gerade Folien auf als sein Game erst einen Freeze bekam und sich letztendlich crashed, nun ist wieder mal der "Stuhl besetzt" und somit wieder gänzlich bis zum nächsten Restart unbrauchbar. 2nd day in a row.

**Erwartetes Verhalten**
Stuhl sollte nicht blockiert sein.

**Schritte um den Fehler nachvollziehen zu können**
Kunden die Folie auflegen und probably Gamequit tuts auch.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080 Window Mode ohne Border

**Optional: Video / Bilder des Fehlers**
hat er nicht dran gedacht aufzunehmen.

**Comment by simplycach** [comment]
Wissen wir bereits und ist bereits und sind dran :)

**Comment by simplycach** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tattoo Stuhl besetzt nach Gamecrash](https://trello.com/c/aiOI8rmN/457-tattoo-stuhl-besetzt-nach-gamecrash)

**Comment by simplycach** [comment]
Das wird etwas Zeit in Anspruch nehmen wir schauen was wir machen können.
