### ISSUE TITLE
Freiflug durch eine Mauer

### ISSUE THREAD

**Issue by SgtTukiTukii** [mexyn/statev_v2_issues#3168]
Teresa Martinez

13.03.2024 gegen 11.15Uhr
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Wollte mich an die Wand lehnen, bin dabei aber durch die Wand gefallen. Das ganz ereignete sich in Paleto am 24/7 / Baumarkt auf der Seite zu den Feldern neben dem ATM. Man fliegt dann etwas und landet dann wieder vor den Läden.

Eine feste Wand zum anlehnen
![image](https://github.com/eiksch/statev_v3_issues/assets/74882929/5d8cf14c-a2a3-43de-8c35-2cdce0a72a83)
![image1](https://github.com/eiksch/statev_v3_issues/assets/74882929/6c39b20a-d884-43cf-bcaf-38aa0394d359)

**Comment by TheOutburst** [comment]
das wurde durch das Update heute gefixt
