### ISSUE TITLE
Kriege keine Rechnung wenn ich beim Frisuer haare schneiden will

### ISSUE THREAD

**Issue by zNion1** [mexyn/statev_v2_issues#3169]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Paxton Oshea**

mit meinem
**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
 wird keiner angezeigt

**Comment by simplycach** [comment]
Hey uns fehlt da etwas Kontext, hast du mehr Informationen für uns ?

**Comment by zNion1** [comment]
> Hey uns fehlt da etwas Kontext, hast du mehr Informationen für uns ?

Ich gehe in den frisuer und möchte meine haare schneiden nach dem aussuchen der frisur und der ausstellung der rechnung wir diese mir nicht angezeigt ich kriege die rechnung nicht angezeigt und deshalb kann man meine frisur dann nicht ändern

**Comment by simplycach** [comment]
Hast du mal ein Video davon ?

**Comment by zNion1** [comment]
müsste ic gehen und eins machen

**Comment by simplycach** [comment]
Würde uns helfen den Fehler besser zu verstehen ja

**Comment by zNion1** [comment]
https://streamable.com/38iwkh

**Comment by simplycach** [comment]
Also wir konnten es gerade alles ohne Probleme machen. Hast du ne XML benutzt bei der Char Erstellung ?

**Comment by zNion1** [comment]
ja

**Comment by zNion1** [comment]
<?xml version="1.0" encoding="utf-16"?>
<OutfitPedData>
  <ModelHash>0x705E61F2</ModelHash>
  <PedProperties>
    <PedProps>
      <_0>-1,-1</_0>
      <_1>-1,-1</_1>
      <_2>-1,-1</_2>
      <_3>-1,-1</_3>
      <_4>-1,-1</_4>
      <_5>-1,-1</_5>
      <_6>-1,-1</_6>
      <_7>-1,-1</_7>
      <_8>-1,-1</_8>
      <_9>-1,-1</_9>
    </PedProps>
    <PedComps>
      <_0>0,0</_0>
      <_1>0,0</_1>
      <_2>0,0</_2>
      <_3>0,0</_3>
      <_4>0,0</_4>
      <_5>0,0</_5>
      <_6>0,0</_6>
      <_7>0,0</_7>
      <_8>0,0</_8>
      <_9>0,0</_9>
      <_10>0,0</_10>
      <_11>0,0</_11>
    </PedComps>
    <HeadFeatures WasInArray="true">
      <ShapeAndSkinTone>
        <ShapeFatherId>2</ShapeFatherId>
        <ShapeMotherId>23</ShapeMotherId>
        <ShapeOverrideId>0</ShapeOverrideId>
        <ToneFatherId>3</ToneFatherId>
        <ToneMotherId>23</ToneMotherId>
        <ToneOverrideId>0</ToneOverrideId>
        <ShapeVal>0.5000</ShapeVal>
        <ToneVal>0.5000</ToneVal>
        <OverrideVal>0</OverrideVal>
        <IsP>0</IsP>
      </ShapeAndSkinTone>
      <HairColour>0</HairColour>
      <HairColourStreaks>0</HairColourStreaks>
      <EyeColour>5</EyeColour>
      <FacialFeatures>
        <_0>0.000000</_0>
        <_1>0.000000</_1>
        <_2>0.000000</_2>
        <_3>0.000000</_3>
        <_4>0.000000</_4>
        <_5>0.000000</_5>
        <_6>0.000000</_6>
        <_7>0.000000</_7>
        <_8>0.000000</_8>
        <_9>0.000000</_9>
        <_10>0.000000</_10>
        <_11>0.000000</_11>
        <_12>0.000000</_12>
        <_13>0.000000</_13>
        <_14>0.000000</_14>
        <_15>0.000000</_15>
        <_16>0.000000</_16>
        <_17>0.000000</_17>
        <_18>0.000000</_18>
        <_19>0.000000</_19>
      </FacialFeatures>
      <Overlays>
        <_1 index="3" colour="0" colourSecondary="0" opacity="1.0000" />
        <_2 index="9" colour="0" colourSecondary="0" opacity="1.0000" />
        <_3 index="255" colour="0" colourSecondary="0" opacity="1.0000" />
        <_4 index="255" colour="0" colourSecondary="0" opacity="1.0000" />
        <_6 index="255" colour="0" colourSecondary="0" opacity="1.0000" />
        <_8 index="255" colour="0" colourSecondary="0" opacity="1.0000" />
        <_9 index="255" colour="0" colourSecondary="0" opacity="1.0000" />
        <_10 index="255" colour="0" colourSecondary="0" opacity="1.0000" />
      </Overlays>
    </HeadFeatures>
  </PedProperties>
  <IsVisible>true</IsVisible>
</OutfitPedData>

**Comment by zNion1** [comment]
das ist der inhalt der xml

**Comment by simplycach** [comment]
Ehm magst du mir die mal auf Discord zusenden bitte

**Comment by zNion1** [comment]
ist grade raus

**Comment by zNion1** [comment]
gilt das neue update auch für mich oder ist das problem bei mir immernoch akut?

**Comment by zNion1** [comment]
jetzt eght das mit der rechnung aber der haarschnitt bleibt danach gleich ändert sich nicht

**Comment by simplycach** [comment]
Hey, ich werde das nochmal weitergeben.

**Comment by simplycach** [comment]
Also bei mir ging das alles ohne Probleme mit deiner XML

**Comment by zNion1** [comment]
seit gestern geht es die ladyq hatte es live miterlebt und mit mir nochmal probiert

**Comment by simplycach** [comment]
Alles können wir das hier schließen ?

**Comment by zNion1** [comment]
jup
