### ISSUE TITLE
Ausdauer anstieg beim fahren

### ISSUE THREAD

**Issue by Elfengames** [mexyn/statev_v2_issues#3170]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Izaac Baker

**Auftrittszeitpunkt (Datum / Uhrzeit)**
am 13.03.2024 zwischen 18:00 und 19:00

**Beobachtetes Verhalten**
ausdaueranstieg beim Fahre/ beifahrer

**Erwartetes Verhalten**
Kein Anstieg

**Schritte um den Fehler nachvollziehen zu können**
gute Frage

**Optional: Video / Bilder des Fehlers**
(https://medal.tv/de/games/gta-v/clips/20L6FuyeSUeVdF/d1337GUkbJyD?invite=cr-MSxFQmIsMjE3Nzc3MjI5LA)

**Comment by DrColgate** [comment]
hatte ich eben auch. Anton Mueller. 14.03 - 18:30. Fahrzeug Bison

**Comment by simplycach** [comment]
Bereits offen https://github.com/eiksch/statev_v3_issues/issues/3133
