### ISSUE TITLE
Fahrzeuge in Werkstatt drehen durch beim berühren

### ISSUE THREAD

**Issue by QA-Pregon** [mexyn/statev_v2_issues#3171]
**Character Name**
David Danilov

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.03 Abends + 13.03 ca. 18:40

**Beobachtetes Verhalten**
Siehe Video, gestern hat sich ein Motorrad ebenfalls am Reparaturpunkt bewegt

**Erwartetes Verhalten**
Auto bleibt starr beim Reparieren

**Schritte um den Fehler nachvollziehen zu können**
Reparieren und gegens Auto laufen, hoffe das reicht aus

**Optional: Video / Bilder des Fehlers**
https://youtu.be/hbn0CPUsaVE

**Comment by QA-Pregon** [comment]
Falls es euch hilft, ist heute um ca. 20:30 wieder passiert

**Comment by simplycach** [comment]
Fixed.
