### ISSUE TITLE
Aufbrechen Abbrechen kann man zu Lange

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3172]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Im laufe des Abend des 13.03
**Beobachtetes Verhalten**

nachdem man fertig ist mit Autos Knacken kommt noch immer die Nachricht, dass man das Aufbrechen abgebrochen hat
**Erwartetes Verhalten**

Es sollte nur kommen, wenn man wirklich dabei ist
**Schritte um den Fehler nachvollziehen zu können**

1. Zu Carlos gehen und ihn nicht mehr Car los machen
2. Einem das zu langweilig werden lassen nach 3 Autos und durch die Stadt fahren
3. Bei ner werkstatt chillen und nen Spontanes Dance battle Starten
4. Beim versuch den Tanz mit "," zu beenden die Nachricht "Aufbrechen abgebrochen" bekommen und verwirrt weiter Tanzen
5. Verblüfft nochmal "," drücken um aufzuhören

Note: Bevor wieder kommt "Du bist zu Schnell" zwischen Letztem Auto und Dance Battle lagen mind. 30 min eher 1h 
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/58612983/b63dc59b-00f7-4918-8adb-f8870cc2c1e2)

**Comment by DrGrizzlY17** [comment]
fixed next update

**Comment by Erumeldor** [comment]
Der Dancebattle war wichtig zum Reproduzieren, sonst geht das nicht 👍 :D

**Comment by SHaagmann** [comment]
> Der Dancebattle war wichtig zum Reproduzieren, sonst geht das nicht 👍 :D

Na klar sonst würde ich das nicht reinschreiben
