### ISSUE TITLE
Friseurprobleme

### ISSUE THREAD

**Issue by Nanabear111** [mexyn/statev_v2_issues#3173]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Nanabear111** [comment]
Es gibt Probleme mit dem Barber, Augenbrauen und Schminke gehen nicht, der Balken läuft aber am Ende ändert sich nichts. Die Sachen werden trotzdem abgezogen

**Comment by simplycach** [comment]
Ist fixed.
