### ISSUE TITLE
Busse betanken

### ISSUE THREAD

**Issue by LeaBrandt** [mexyn/statev_v2_issues#3174]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Ronja Brandtberg 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 13.03.2024 um 21:38 Uhr

**Beobachtetes Verhalten**
 Laut der Info aus dem Discord von "Ray" (siehe Screenshot unten), sollte man die Busse ohne sein eigenes Geld betanken können. Da dies aber nicht geht, melde ich es mal hier. Ich habe mit Bargeld in der Tasche getankt und die Kosten gingen von meinem Bargeld ab. Dann habe ich mein Bargeld abgegeben und konnte mangels Geld nicht mehr tanken. 
P.s.: Nach dem tanken konnte ich auch nicht mehr in den Bus einsteigen, wenn noch jemand anderes darin sitzt. 
Zu beiden Situationen habe ich Videos beigefügt. 

**Erwartetes Verhalten**
 Man kann den Bus tanken ohne das privat zahlen zu müssen. 

**Schritte um den Fehler nachvollziehen zu können**
 Buslinie fahren und tanken gehen. 

**Optional: Video / Bilder des Fehlers**

![Screenshot Discord](https://github.com/eiksch/statev_v3_issues/assets/98689462/713483f8-0bad-4b98-baf4-c8cbe7d912cb)

https://github.com/eiksch/statev_v3_issues/assets/98689462/8c6d0dae-4a06-4797-a7f0-bb09853394cc

https://github.com/eiksch/statev_v3_issues/assets/98689462/fddbf0d9-1f3d-4e2b-a355-c6b5fbc0481f

**Comment by SgtBoaz-Terry** [comment]
Tatsächlich werden die Busse nicht auf Kosten von LST getankt, da sie nach jedem Restart repariert und vollgetankt zum Depot zurück geportet werden.
