### ISSUE TITLE
Rennsitze im Fathom FR36 werden als Verzierung gezählt

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#3175]
**Character Name**
Charly Russo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
13.03.2024 22:00Uhr

**Beobachtetes Verhalten**
Fahrzeugsitze und Überrollkäfig des Fathom FR36 Drift werden als Verzierung gezählt und kosten im Einbau nur 1 Kunststoffgranulat

**Erwartetes Verhalten**
Sitze sollten als Fahrzeugsitze oder Carbonsitze gelten oder zumindest als Extra?

**Schritte um den Fehler nachvollziehen zu können**
Mit dem Fathom FR36 Drift auf den Tuningpunkt fahren, unter Verzierung die Optionen durchschauen

**Optional: Video / Bilder des Fehlers**
https://imgur.com/jH61BZF

**Comment by SatyriaDine** [comment]
Das ist leider aktuell nicht einfach änderbar. Tritt auch bei anderen Fahrzeugen zum Teil auf. :/
