### ISSUE TITLE
Kamacho, Terminus und Merryweather Mesa brauchen LKW Reifen in der Herstellung

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#3176]
**Character Name**
Charly Russo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
13.03.2024 13:00 Uhr

**Beobachtetes Verhalten**
Der Canis Kamacho, der Canis Terminus und der Merryweather Mesa benötigen alle LKW Reifen in der Herstellung

**Erwartetes Verhalten**
Sie sollten PKW Reifen benötigen

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug Fertigung Produktion

**Optional: Video / Bilder des Fehlers**
https://imgur.com/8NhdjrJ
https://imgur.com/O8SxTbf

**Comment by Statev-Bonsai** [comment]
das war schon immer so, sicherlich aufgrund der großen rad/reifenkombination..

**Comment by SatyriaDine** [comment]
Das ist so gewollt :)
