### ISSUE TITLE
Neue Reifen können nicht verbaut werden

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#3177]
**Character Name**
Charly Russo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
13.03.2024 23:00 Uhr

**Beobachtetes Verhalten**
UHP Reifen und andere Reifensorten können nicht verbaut werden, trotz Lagerbestand. Getestet in Bennys Performance, PLZ 4002

**Erwartetes Verhalten**
Reifen sollten verbaut und in der Tuning Übersicht richtig angezeigt werden.

**Schritte um den Fehler nachvollziehen zu können**
Beliebiges Auto tunen, Reifen wechseln

**Optional: Video / Bilder des Fehlers**
https://imgur.com/GXGX0Nq

**Comment by SHaagmann** [comment]
Duplikat: #3114
