### ISSUE TITLE
Versetzung Abladepunkt, Entfernung Schrottbus

### ISSUE THREAD

**Issue by BobbyCarsten** [mexyn/statev_v2_issues#3178]
Bobic_Madujew

es geht um eine Versetzung um ein paar meter vom Abladepunkt und um eine Entfernung von einem Schrottbus da der den Eingang verdeckt und es schwer einsichtlich ist.

![image (1)](https://github.com/eiksch/statev_v3_issues/assets/163411566/541d8966-b83e-4a08-8b3e-f464c37093cc)
Entfernung Schrottbus da er den Firmeneingang Verdeckt und ich die letzten 2 Tage beobachtet habe das viele leute zur nachbarfirma an die Tür gehen

![image](https://github.com/eiksch/statev_v3_issues/assets/163411566/87158193-9fee-410d-9ee8-bd458ab93108)
Versetzung Abladepunkt

![Screenshot 2024-03-14 120248](https://github.com/eiksch/statev_v3_issues/assets/163411566/8502c188-dd71-4107-83db-8632e303f388)
Firmen Hash und Firmen Name

**Comment by nb431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Versetzung Abladepunkt, Entfernung Schrottbus](https://trello.com/c/T923hXtx/462-versetzung-abladepunkt-entfernung-schrottbus)

**Comment by Erumeldor** [comment]
@BobbyCarsten 
Was spricht denn gegen die aktuelle Position des Abladepunkts?

Den Schrottbus werden wir euch hier nicht entfernen, tut mir Leid. Ihr habt vor Firmenkauf gesehen wo der Eingang ist ;)

**Comment by BobbyCarsten** [comment]
Das dort der Punkt ist wo die geklauten Autos spawnen an der Firma ganz knapp neben dem ladepunkt.

Ja schade aber ist halt so. Muss man halt mit Aufstellbaren Objekten dann regeln das man den Eingang dann sieht

**Comment by Erumeldor** [comment]
Also ich habe das gerade selbst mal ausprobiert, es gibt da für mich keinen wirklichen Grund den Marker zu verschieben.
Ihr kommt doch wunderbar hin, mit jeglichem Fahrzeug, oder nicht?
