### ISSUE TITLE
Haare Buggen durch das Sandana

### ISSUE THREAD

**Issue by KevinKelce** [mexyn/statev_v2_issues#3179]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Kevin Kelce**

immer Sobald ich das Sandana als Stirnband nutze

**Auftrittszeitpunkt (Datum / Uhrzeit)**

14.03.24

**Beobachtetes Verhalten**

Sobald ich das Sandana aufsetze buggt es durch die Haare

**Erwartetes Verhalten**

Sandana sollte von den Haaren verdeckt sein

**Schritte um den Fehler nachvollziehen zu können**

Sandana als Stirnband anziehen :D

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![bug kelce](https://github.com/eiksch/statev_v3_issues/assets/163436974/1c8ffe0c-56e0-48ba-85e4-500a9116e07f)

**Comment by simplycach** [comment]
Ich glaube, dass ist teilweise bei einigen Frisuren nicht änderbar, ich mach mich da mal schlau.

**Comment by KevinKelce** [comment]
Also ich hatte extra jede Frisur ausprobiert im Friseur da war es leider bei jeder.
Ich kenns halt con anderen Servern so das wenn man das Stirnband angezogen hat und ne glatze hatte und sich dann seine Frisur neu machen musste damit nix durchbuggt

**Comment by simplycach** [comment]
Vielleicht finden wir da mal was, aktuell liegt der Fokus auf anderen Sachen.
