### ISSUE TITLE
Char stuck in "Handy am Ohr" animation nach Dispatch senden

### ISSUE THREAD

**Issue by FLVFFY1** [mexyn/statev_v2_issues#3180]
Jayden_Banks

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14.03.2024 16:20

**Beobachtetes Verhalten**
Medic-Dispatch gesendet, telefonat beendet, char war in telefonier animation gefangen

**Erwartetes Verhalten**
Char nicht stuck in animation nach telefonat

**Schritte um den Fehler nachvollziehen zu können**
Dispatch anrufen, mit F2 handy weg zum gehen, dispatcher legt auf, schließt direkt den dispatch, char stuck in telefon am ohr animation und man kann auch nicht mehr in der App auf "OK" klicken, da kein offener Dispatch

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Kommt das öfter vor ?

**Comment by FLVFFY1** [comment]
tatsächlich reproduzierbar. vorausgesetzt der dispatcher löscht wohl den dispatch schnell genug

**Comment by Flachmeyer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Char stuck in "Handy am Ohr" Animation nach Dispatch senden](https://trello.com/c/hssIrOZv/472-char-stuck-in-handy-am-ohr-animation-nach-dispatch-senden)

**Comment by simplycach** [comment]
Next Update fixed
