### ISSUE TITLE
Fremde Fahrzeuge in Autohausgarage

### ISSUE THREAD

**Issue by DrColgate** [mexyn/statev_v2_issues#3181]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Anton Mueller

**Auftrittszeitpunkt (Datum / Uhrzeit)**
in den letzten tagen

**Beobachtetes Verhalten**

An Kunden überschriebene Fahrzeuge landen bei uns in der Autohaus Garage.
Trat bisher 3x beim Inductor Fahrrad auf.
Heute rief eine Dame bei uns an, ihr Inductor sei bei uns in der Garage gelandet.
Auf die Garage hat sie kein Zugriff. Kommt somit nicht an ihr Fahrrad.
Laut ihr, stand ihr Inductor aber in Sandy Shores.
Firmenhash: carShop2

Die Dame war Frau Willson
**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DerHessenTyp** [comment]
Früher gabs das Problem, dass Autos wenn Sie noch nicht eingeparkt wurden wieder in der letzten Garage standen also Autohaus. Daher vllt auch bei den genannten 3 Fahrrädern das Problem.

**Comment by Erumeldor** [comment]
https://github.com/eiksch/statev_v3_issues/issues/3526

**Comment by simplycach** [comment]
Dürfte nicht mehr vorkommen.

**Comment by DerHessenTyp** [comment]
Leider kommt dieser Bug immer noch vor.
Und laut dem Autohaus, soll sogar unser Burrito der am meisten dort oben ankommende sein.
Wir haben ihn mehrfach in der gleichen aber auch in anderen Garagen eingeparkt.
Er landet wenn er nicht eingeparkt wurde immer wieder dort wo wir ihn auspacken lassen haben.

Funfact: Unser anderer Gang Burrito den wir in einem anderen Autohaus auspacken lassen haben wurde nach einem Mal einparken in Grapeseed dann vom Indigofeld direkt in eine öffentliche Garage eingeparkt am Elektrowerk und beim erneuten Ausparken dann in Nähe Davis auch dort in die Garage eingeparkt.

Langsam wirds zum Fluch.


![Fahrzeug wieder im Autohaus](https://github.com/user-attachments/assets/154e3088-c95b-419c-94ae-1f6b6b359dc5)

Geht übrigens um das Autohaus in Paleto Bay wo er immer wieder steht.
