### ISSUE TITLE
Entsorgung Müll der Bösen Nachbarn auf unserem Grundstück :) "Entfernung div. Objekte"

### ISSUE THREAD

**Issue by Tobse1904** [mexyn/statev_v2_issues#3182]
Grüße liebes State V Team 😉 

Wir die Jungs und Mädels der Genius Group haben da mal ein paar fragen bzw anschläge auf die lieben Dev´s bzw Gamedesigner vor 😉

Wir besitzen auf einem Geländen Ein Labor und seit gerade eben auch eine Gießerei. Allerdings haben wir so böse Nachbarn die einfach ihren Müll dort abgeladen haben , sowie div. Müllcontainer abgestellt haben und uns somit die Sicht auf die Eingangstür vom Labor versperren durch 3 kisten, als weiteres haben unsere Kunden durch diese Müllsünder keine möglichkein bei uns anständig zu parken, da diese ihren Müll / Container auf die weiteren Parkplätze abgestellt haben.

und zur Krönung kommt noch dazu das wohl ein Formel 1 Team ihre absperrung vergessen hat und diese ebenfalls einfach vor die Tür der Gießerei gestellt hat.

Kommen wir jetzt zu unserem wunsch an euch, wäre es möglich das ihr diese Sachen entfernen könntet / würdet ? Braucht ihr Bilder dazu oder eine vor Ort besichtigung ?

Inhaber des Labor´s : Jake_Parker
Inhaber der Gießerei : Harry_Buktu
Gebäude Hash: pf_cypressflats_2 sowie pf_lamessa_41 ( Gleiches Gelände wird komplett von uns Bespielt.

Sollten Bilder benötigt werden so könnt ihr mich gerne bei Discord anschreiben ( Tobse )

Wir bedanken uns im voraus ❤️

Mit freundlichen Grüßen 
Euer Genius Group Team

**Comment by Tobse1904** [comment]
Anbei mal die Bilder um welche dinge es sich Handelt

![Gelände bearbeitung 1](https://github.com/eiksch/statev_v3_issues/assets/39304481/1583dffa-1357-4a91-833a-c14f60ba3053)
![Gelände bearbeitung 2](https://github.com/eiksch/statev_v3_issues/assets/39304481/68c938c9-07ad-4da2-a580-19779f2e6408)
![Gelände bearbeitung 3](https://github.com/eiksch/statev_v3_issues/assets/39304481/16bb4341-5fac-4df4-9f86-270e33950a58)

**Comment by simplycach** [comment]
Wir schauen mal was sich machen lässt.

**Comment by Tobse1904** [comment]
Habt ihr hier ggf. schon Infos für uns ob es umsetzbar ist ?
wurden jetzt schon öfters angerufen das man die Tür nicht findet weil sie von Kisten verdeckt wird.

**Comment by Erumeldor** [comment]
Hi @Tobse1904 
Tut mir Leid, aber solche Sachen, die nicht funktional stören, entfernen wir grundsätzlich nicht mehr.

**Comment by Tobse1904** [comment]
garnichts davon ? die kisten am Labor wären zumindest schön , weil wie gesagt wir wurden jetzt schon öfters gefragt wo die tür ist weil man sie nicht sieht durch die kisten
