### ISSUE TITLE
Antrag: Verschiebung Werkstattpunkt LSC

### ISSUE THREAD

**Issue by QA-Pregon** [mexyn/statev_v2_issues#3183]
David Danilov

Sehr geehrtes StateV-Team,

wäre es möglich bei bei der LSC Werkstatt [1] einen Werkstattpunkt zu verschieben?
Es ist für uns nicht all zu praktisch wenn ein Arbeitspunkt direkt vor der Ein- und Ausfahrt liegt [2].
Die Neue gewünschte Position habe ich markiert [2].

Vielen Dank für eure Überprüfung

Freundliche Grüße
Pregon

[1] Standort LSC:
![Screenshot 2024-03-16 095158](https://github.com/eiksch/statev_v3_issues/assets/75855042/7d2b2311-a4fb-4f48-998c-1764aa5228b7)
[2] Gemeinter Werkstattpunkt und neuer Ort:
![Werkstatt](https://github.com/eiksch/statev_v3_issues/assets/75855042/93a8d283-b558-4cad-8424-cd7f673e31fd)

**Comment by Erumeldor** [comment]
Hi Pregon,
der Werkstatt Punkt vor der Werkstatt ist eingeführt worden, damit alle Werkstätten LKWs reparieren können. 
Es soll nicht dazu einladen, dauerhaft vor der Werkstatt zu reparieren oder zu tunen.
Tatsächlich haben alle Werkstätten ihren 2. Arbeitspunkt genau in der Einfahrt, da ist also eine gewisse "Chancengleichheit" zwischen den Werkstätten.

Wir werden daher aktuell die Punkte nicht verschieben, sorry.

**Comment by QA-Pregon** [comment]
Ah ok, dann versteh ichs komplett, danke für die Klärung
