### ISSUE TITLE
Bank Daueraufträge

### ISSUE THREAD

**Issue by LeonF0207** [mexyn/statev_v2_issues#3185]
**Character Name**
Jake Thompson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.03.2024 - 18:57 Uhr

**Beobachtetes Verhalten**
Wenn man in einem Dauerauftrag z,B, 3818,75$ angibt, wird nur 3818$ gespeichert und auch überwiesen, ich habe ein Test Dauerauftrag von 10,15$ gemacht und es wurde von meinem Bankkonto nur 10$ + Überweisungsgebühr abgezogen.

**Erwartetes Verhalten**
Das die Cent Beträge mit gespeichert und überwiesen werden.

**Schritte um den Fehler nachvollziehen zu können**
Dauerauftrag erstellen z.B. i.H.v. 10,15$

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
/////

**Optional: Video / Bilder des Fehlers**
/////

**Comment by SgtBoaz-Terry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bank-Daueraufträge fehlerhaft](https://trello.com/c/9xunGoSi/471-bank-dauerauftr%C3%A4ge-fehlerhaft)

**Comment by simplycach** [comment]
Next Update fixed
