### ISSUE TITLE
Be- & Abladepunkt

### ISSUE THREAD

**Issue by LuciaLorenzi** [mexyn/statev_v2_issues#3186]
Charakter Name:
Lucia Lorenzi 

Auftrittsdarum: 16.03.2024

Ich möchte gerne von meinen beiden Firmen Labor und Lager die Be- & Abladepunkte zusammen gefügt haben in die Mitte des Platzes (Firmen in Paleto nebeneinander keine weiter Firma auf dem Grundstück) Ich habe die Bilder hinzugefügt damit dies ersichtlich ist. Die zwei abladepunkte verwirren manch andere wenn Sie etwas ins Lager geben möchten fahren Sie zum Labor Punkt trz. Beschreibung. Eines der Bilder zeigt abladepunkt Labor das andere vom Lager und ein Bild mit dem Kreis in der Mitte was dies vereinfachen könnte wenn der Punkt dort wäre.

![Labor_abladepunkt](https://github.com/eiksch/statev_v3_issues/assets/163678809/3238b8b3-2012-42ef-9eb6-a0e45228cb61)
![Lager_abladepunkt](https://github.com/eiksch/statev_v3_issues/assets/163678809/5ac75714-8fbf-4ddd-9005-afa9f6f0ebee)
![Screenshot_20240316_193023_Chrome](https://github.com/eiksch/statev_v3_issues/assets/163678809/49bde6a1-6a1a-47d1-9133-183c8ff8e873)
![Hope-Lager_infos](https://github.com/eiksch/statev_v3_issues/assets/163678809/2f272bcf-0449-4664-a635-84b6313be52d)

![zentraler_ablagepunkt](https://github.com/eiksch/statev_v3_issues/assets/163678809/4c0f9058-2df3-4927-a591-5fbadfe1ec94)

**Comment by simplycach** [comment]
Wir schauen mal was sich machen lässt

**Comment by TheOutburst** [comment]
Tachchen
Sowas machen wir nichtmehr, wir könnten den Abladepunkt der auf der Straße ist zwar auf den Innenhof verschieben, aber die dinger zusammenlegen ist leider nichtmehr

**Comment by LuciaLorenzi** [comment]
Achso könntet ihr mir den dann auch bitte auf den Innenhof legen ?
