### ISSUE TITLE
Essen Bug 

### ISSUE THREAD

**Issue by einfachLissy** [mexyn/statev_v2_issues#3187]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

 Leyla Parker

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 Ist im Video Einsehbar.

**Beobachtetes Verhalten**
 Essen Inventar ging nicht mehr zu.

**Erwartetes Verhalten**
 Sollte sich schließen

**Schritte um den Fehler nachvollziehen zu können**
 Unbekannt.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
 https://medal.tv/de/games/gta-v/clips/21nYGFoDLgLi3l/d1337i5gmeY3?invite=cr-MSxYS2YsNDU4MjUzMzgs

**Comment by simplycach** [comment]
Ist dir das schon häufiger passiert, für uns wäre nächstes mal noch die F8 Konsole wichtig :) ?
Und wenn du N drückst und dann mit der Maus schließen drückst ging es auch nicht ?

**Comment by SgtBoaz-Terry** [comment]
Aktuell nicht reproduzierbar. Bitte, wie erwähnt, F8 Console beim nächsten Auftreten aufmachen für eventuelle Fehlermeldungen.
