### ISSUE TITLE
Bekomme kein Arbeitslosengeld mehr

### ISSUE THREAD

**Issue by Elozyn** [mexyn/statev_v2_issues#3188]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Macey Bennett**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.03.2024 Zwischen 19:39 - 22:12 Uhr

**Beobachtetes Verhalten**
Ich hab jetzt nach 3 Stunden kein Arbeitslosengeld mehr bekommen. War für eine Stunde im Tattoo Studio und hab kein Arbeitslosengeld mehr bekommen.

**Erwartetes Verhalten**
Das Geld rein kommt und nicht nur abgeht.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![271590_20240316221230_1](https://github.com/eiksch/statev_v3_issues/assets/163599092/a421bf8f-d135-4b5d-aca1-f0be4f67692e)

![271590_20240316220217_1](https://github.com/eiksch/statev_v3_issues/assets/163599092/70e5ac38-d2de-4bf6-84f1-a0b39031d8e7)

**Comment by simplycach** [comment]
Hast du dich zufällig im Studio eingestempelt aus versehen und nicht mehr aus gestempelt ?

Ein anderer Fall fällt mir dazu gerade erstmal nicht ein.

**Comment by simplycach** [comment]
Also hab grad mal nachgeschaut ich sehe da jetzt keinen Fehler und es scheint ja auch wieder zu gehen bei dir. Wenn der Fehler nochmal auftritt gerne nochmal melden, schönen Start in die Woche.
