### ISSUE TITLE
Missions Punkt

### ISSUE THREAD

**Issue by Vinyard873** [mexyn/statev_v2_issues#3189]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**William_Underwood**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.03.2024 04:06

**Beobachtetes Verhalten**
Punkt kann nicht abgearbeitet werden da das Mitarbeiter Sysmbol dort ist

**Erwartetes Verhalten**
Punkt wo anders hinsetzten

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![Bug Paleto Tattoo studio](https://github.com/eiksch/statev_v3_issues/assets/160692156/c49112f0-9b4d-4fea-a44a-cc04a36f8a32)

**Comment by simplycach** [comment]
Kannst du uns vielleicht noch sagen wo genau dieser Punkt ist ? **Ggf. auch mit STRG + F6 offen im Screenshot**.

**Comment by Vinyard873** [comment]
Hallo symply, Hab extra das bild angefügt oder seht ihr das nicht?  Der Punkt ist direkt auf dem Wolfskopf wo mitarbeiter sich einstempeln

**Comment by simplycach** [comment]
Ja aber nicht die genaue Location

**Comment by Vinyard873** [comment]
![Unbenannt](https://github.com/eiksch/statev_v3_issues/assets/160692156/c696ae9e-7ae5-42fe-805a-a1fd4202db36)

**Comment by Erumeldor** [comment]
Fixed im nächsten Update
