### ISSUE TITLE
Barren beim verkauf aus der Gießerei verschwunden

### ISSUE THREAD

**Issue by DomiM88** [mexyn/statev_v2_issues#319]
**Dominik_Manns**

Dominik_Manns (verkäufer) und Jason_Bulls (Käufer)
**Zeitpunkt (Datum / Uhrzeit)**

21.11.2020 ca. 14.55uhr
**Beobachtetes Verhalten**
Ich wollte Jason_Bulls aus der Gießerei 23 Goldbarren, 26 Kupferbarren und 187 Eisenbarren verkaufen, sein Burrito stand auf dem Ladepunkt, es wurde nichts beladen, die Barren sind aber aus dem Lager verschwunden, Jason_Bulls konnte sein Auto auch nicht mehr benutzen!
Wir wollten 
**Erwartetes Verhalten**
Ich wollte Jason_Bulls aus der Gießerei 23 Goldbarren, 26 Kupferbarren und 187 Eisenbarren verkaufen, sein Burrito stand auf dem Ladepunkt, es wurde nichts beladen, die Barren sind aber aus dem Lager verschwunden, Jason_Bulls konnte sein Auto auch nicht mehr benutzen!

**Schritte um den Fehler nachvollziehen zu können**
an die Gießerei und ware in ein Fahrzeug verkaufen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Ist bereits schon lange gefixed. Es hat einfach nur eine simple Meldung gefehlt, dass der Kofferraum offen sein muss - welche nun nachgetragen wurde.
