### ISSUE TITLE
Arbeitstisch(Weed) + Gegenstände nach Restart weg

### ISSUE THREAD

**Issue by LucasKtz** [mexyn/statev_v2_issues#3190]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Nathaniel_Hobbs
**Auftrittszeitpunkt (Datum / Uhrzeit)**

17.03.2024 12:00 Uhr
**Beobachtetes Verhalten**

dass einem die Items zurück ins Inventar gelegt werden 
**Schritte um den Fehler nachvollziehen zu können**

Einfach nochmal verarbeiten wärend der Server restartet
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Statev-Bonsai** [comment]
Das war auch bei V2 schon so, passiert auch beim Serverabsturz... Damals hieß es das man da nix machen kann...

**Comment by Statev-Bonsai** [comment]
https://github.com/eiksch/statev_v3_issues/issues/1375

**Comment by simplycach** [comment]
Das ist leider so Technisch nicht möglich, bitte wenn ihr z.B wisst es kommt ein Restart um 12 Uhr nicht bis kurz vor Restart verarbeiten. Ggf. bitte ein Ticket im Discord aufmachen mit entsprechenden Screenshots.
