### ISSUE TITLE
Gieserei Leute Unsichtbar / nicht hörbar.

### ISSUE THREAD

**Issue by coresync2k** [mexyn/statev_v2_issues#3191]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Jake_Parker

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Eigentlich sobald man die Firma betritt.

**Beobachtetes Verhalten**
Wir haben 2 Firmen. Die quasi Tür an Tür sind.

Ein Labor -> pf_lamessa_41
Eine Schmelze -> pf_cypressflats_2

Die teilen sich 1 BE/Entlade Punkt. das ist soweit alles gut.

Jedoch ist uns nun aufgefallen, das wenn wir die "Schmelze" betreten, uns 1) nicht sehen, und wenn wir uns dort sehen, können wir uns nicht hören. 

Desweiteren ist es so das wenn man Die Schmelze verlässt, man beim Eingang vom Labor landet.

**Erwartetes Verhalten**
Wenn man die Schmelze verlässt man auch vor der Schmelze landet.
Das man die Leute innerhalb der Schmelze sieht und hört.

**Schritte um den Fehler nachvollziehen zu können**
Einfach die Schmelze betreten mit einer anderen Person zusammen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Comment by Snipser92** [comment]
Das mit dem sehen der anderen Personen in der Giesserei haben wir bei uns auch ab und zu.

**Comment by SatyriaDine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unsichtbare Spieler](https://trello.com/c/fOpfT50b/399-unsichtbare-spieler)
