### ISSUE TITLE
Tailgater S nicht Schiebbar

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3193]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew_Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

18.03 12:07
**Beobachtetes Verhalten**

Der Tailgater S ist nicht schiebbar
**Erwartetes Verhalten**

Man kann ihn Schieben
**Schritte um den Fehler nachvollziehen zu können**

Sich vor einem Tailgater S Stellen und wundern, warum man zu dünne Arme hat den zu schieben
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://medal.tv/de/games/gta-v/clips/21Ke8TiQxXFozq/d1337v916fjI?invite=cr-MSxVTHIsMTk1NTEzMTMzLA

**Comment by SatyriaDine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tailgater S lässt sich nicht schieben](https://trello.com/c/bDiNP7JA/465-tailgater-s-l%C3%A4sst-sich-nicht-schieben)

**Comment by Erumeldor** [comment]
Nächstes Update fixed :)
