### ISSUE TITLE
Friseurprobleme 

### ISSUE THREAD

**Issue by Xymena** [mexyn/statev_v2_issues#3194]
Wir konnten mehre Probleme beim Friseur Festellen, aufgrund der Matrialkosten sind sie aber nur bedingt, für uns Reproduzierbar!

Fehler 1: Lippen lassen sich nicht korrekt ändern.

Beim Ändern der Lippen und der Farbe wird eine zufällige Farbe gesetzt.

Es ist aber möglich, die Lippen und Lippenfarbe einzeln zu ändern.

_Entfernung der Farbe wurde nicht versucht._

Fehler 2: Augenbrauen beim Mann lassen sich nicht korrekt ändern.

Eine bestehende Augenbraue lässt sich beim Mann nicht korrekt ändern, es kommt dann eine andere.

Bei der Frau konnten die Augenbrauen erfolgreich geändert werden.

_Färben wurde in beiden Fällen nicht versucht._

Fehler 3: Bärte beim Mann lassen sich nicht ändern, bei einer Änderung kommt ein anderer.

_Färben und Entfernen wurde nicht versucht._

**Comment by simplycach** [comment]
Bereits offen https://github.com/eiksch/statev_v3_issues/issues/3120
