### ISSUE TITLE
Flatbed Farbe resettet nach 12 Uhr restart

### ISSUE THREAD

**Issue by QA-Pregon** [mexyn/statev_v2_issues#3195]
David Danilov

19.03 Restart 12:00

**Beobachtetes Verhalten**
Flatbed SA-WH-6H hat Farbe nach Lackieren gestern zurückgesetzt

**Erwartetes Verhalten**
Farbe bleibt

**Schritte um den Fehler nachvollziehen zu können**
Keine Ahnung ^^

**Comment by nb431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Flatbed Farbe resettet nach 12 Uhr restart](https://trello.com/c/Wr7DofjP/468-flatbed-farbe-resettet-nach-12-uhr-restart)

**Comment by QA-Pregon** [comment]
Der LKW Fix aus V 3.0.22 hat das glaub gefixt, auf jeden Fall war danach die Farbe drauf
