### ISSUE TITLE
TailgatorS Armaturen Cleaning

### ISSUE THREAD

**Issue by Falk-Alers** [mexyn/statev_v2_issues#3196]
Guten Morgen

Beim TailgatorS haben wir versucht beim Innenraum die Handyhalterung zu entfernen (Armaturen Cleaning)

Das bezahlen und der Tuning fortschritt (Ladebalken) war beides möglich, aber das Armaturenbrett war hinterher nicht verändert.

Serie:
![Standart](https://github.com/eiksch/statev_v3_issues/assets/25896156/df828366-4184-4353-add6-7a380f4a3b5c)

Tuning
![Umbau](https://github.com/eiksch/statev_v3_issues/assets/25896156/48521e56-3ee7-443e-9248-9ea53f1b6373)

Bezahlung
![Bezahlung](https://github.com/eiksch/statev_v3_issues/assets/25896156/d8db6018-1cc2-49be-8705-47319016d435)

PS:
Türen und Motorhaube bleiben beim Tuning nicht offen beim TailgatorS, somit nicht möglich den Innenraum zu sehen fürs Tuning

**Comment by SatyriaDine** [comment]
Habt ihr noch irgendwas anderes dabei getuned oder vllt nen missclick gemacht? Bekomme das so nicht reproduziert. :)

**Comment by Falk-Alers** [comment]
Gemacht wurde nichts anderes nebenbei, und auch nicht vorher oder nachher
Mechaniker sagt war kein Missclick

**Comment by Falk-Alers** [comment]
wir haben es heute abend, also genau genommen ejtzt gerade eben 22.3 00:49UHr nochmal bei benny gemacht aber mit einem anderen mechaniker, also denke ich mal der andere hat sich vll doch verklickt
