### ISSUE TITLE
Doppel Bezahlung beim Essen servieren

### ISSUE THREAD

**Issue by Mausi117** [mexyn/statev_v2_issues#3197]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name** Lumina Dakota

Lumina Dakota
**Auftrittszeitpunkt (Datum / Uhrzeit)**

19.03.2024 18:42
**Beobachtetes Verhalten**

Geld wurde abgebucht obwohl die Bestellung nicht aufgenommen wurde
**Erwartetes Verhalten**

Wenn die Nachricht kommt das die Bestellung nicht aufgegeben wurde das die Zahlung auch bitte nicht abgebucht wird.
**Schritte um den Fehler nachvollziehen zu können**

Ich hatte eine Kundin IC diese hat etwas bestellt hat aber noch nicht bezahlt dies ging dann ein paar Sekunden und in dem Moment wo das Script abbricht hat sie bezahlt ich musste sie dann bitten noch einmal das Essen zu bestellen denn bei mir wurde das Essen nicht zubereitet und ich konnte es nicht an den Tisch servieren.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

Bestellung dann genau bezahlen wenn der Timeout das Script resettet.
**Optional: Video / Bilder des Fehlers**

https://medal.tv/de/games/gta-v/clips/21Xo40rkRFEVC7/d1337fld1wUP?invite=cr-MSxNZ3csMzc1OTgzNDgs

**Comment by Xymena** [comment]
Scheint leider so ein genereller bug zu sein, wenn mehr als 2 Leute bestellen kriegt oft eine person kein Essen.. oder  es wird abgebucht und es wird kein essen gebracht.

**Comment by simplycach** [comment]
Konnten wir jetzt bisher so noch nicht verifizieren

**Comment by simplycach** [comment]
Ist das nochmal aufgetreten ?

**Comment by simplycach** [comment]
Da ich keine Infos mehr erhalten habe, gehe ich von aus der Bug ist nicht mehr aufgetreten, wenn nochmal sowas passiert bitte erneut öffnen.
