### ISSUE TITLE
HarzV Geld 7,50 bekommen 

### ISSUE THREAD

**Issue by pumakadse** [mexyn/statev_v2_issues#3198]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Puma_Jackson**

Puma_Jackson
**Auftrittszeitpunkt (Datum / Uhrzeit)**

20.3.2024, 02:11:02
**Beobachtetes Verhalten**

Konto Erhalten 7,50
**Erwartetes Verhalten**

120 Dollar
**Schritte um den Fehler nachvollziehen zu können**

Gute Frage.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot 2024-03-20 160602](https://github.com/eiksch/statev_v3_issues/assets/93686826/556adb34-612a-4b33-8920-2e35a6a22285)

**Comment by simplycach** [comment]
Vermutlich hast du noch Schulden, die erst bezahlt werden müssen.

**Comment by simplycach** [comment]
Scheint lt. deinem Konto wieder zu klappen.
