### ISSUE TITLE
Fit halten

### ISSUE THREAD

**Issue by Kruemel93** [mexyn/statev_v2_issues#3199]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Estrella Alvares**

**20.03.2024 / ca.16:00-16:20 Uhr)**

**Wir sind nach cayo gefahren und ne halbe std ungefähr später nun zurück. seit der rückfahrt bekomme ich die meldung du fühlst dich fitter und eben die meldung deine muskeln brauchen zeit allerdings mache ich nichts un stehe in meiner firma rum .**

**Das beim jetski fahren oder auch während man am Auto fahren ist das nicht funktionieren sollte.**

**Gute Frage. keine Ahnung**

**-**

****

**Comment by Erumeldor** [comment]
Duplicate von #3133 :)
