### ISSUE TITLE
Juwelier - Kauf von Items nicht möglich

### ISSUE THREAD

**Issue by VictorCorticera** [mexyn/statev_v2_issues#32]
**Zeitpunkt (Datum / Uhrzeit)**

25.08.2020 / 20:30

**Beobachtetes Verhalten**

Items im Juwelier können nicht gekauft werden - Fehlermeldung erscheint.

**Erwartetes Verhalten**

Man sollte Items kaufen können ^^

**Schritte um den Fehler nachvollziehen zu können**

1. In Juwelier gehen (wurde in Cartier und Vankhov getestet)
2. Beliebiges Item kaufen (Brillen/Uhren wurde getestet)
3. Funktioniert nicht, obwohl genug Geld vorhanden ist - Fehlermeldung erscheint.

**Optional: Video / Bilder des Fehlers**

![fehlermeldungkauf](https://user-images.githubusercontent.com/28830176/91216760-c3e3bb80-e716-11ea-81e2-f9f7863b962e.png)

**Comment by its4l3x** [comment]
Bereits gefixed mit den Steuern. Auf ein Update warten.
