### ISSUE TITLE
Abschlepper Bug

### ISSUE THREAD

**Issue by ShauniKT** [mexyn/statev_v2_issues#320]
**Character Name**
Shauni Teller

**Zeitpunkt (Datum / Uhrzeit)**
21.11.2020 / 15:30 Uhr

**Beobachtetes Verhalten**
Beim Aufladen eines Autos auf den Flatbed glitshte das Auto durch den Boden, drehte ein Paar Pirouetten, war Kernschrott und flog am Ende in die Luft

**Erwartetes Verhalten**
Das es funktioniert, wie es soll.

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug auf Abschlepper laden. Wenn man mutig ist einsteigen und schon gehts los.
Passiert allerdings nicht immer.
Evtl Zusatz: Fahrzeug, welches am auf den Abschlepper packt vorher schieben.

**Optional: Video / Bilder des Fehlers**
https://puu.sh/GPLnZ/ad875671b7.jpg

**Comment by DonVitoDiangelo** [comment]
_Beim repair müssen die Scheiben und Reifen noch gesetzt/resettet werden._

**Comment by r3sist3nt** [comment]
Fehler gefunden und (leider) erst morgen früh behoben.
Bis dahin müssen wir die abschlepper leider wieder deaktivieren
