### ISSUE TITLE
Haus erscheint nach Überschreibung 2 mal im VNET

### ISSUE THREAD

**Issue by Dennymaru32** [mexyn/statev_v2_issues#3200]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Daniel_Knight

**Auftrittszeitpunkt (Datum / Uhrzeit)**
20.03.2024 00:50:31

**Beobachtetes Verhalten**
Haus erscheint 2 mal in der Hausübersicht im VNET

**Erwartetes Verhalten**
Haus sollte nur 1 mal erscheinen

**Schritte um den Fehler nachvollziehen zu können**
Eventuell ein Hausschlüssel erhalten und danach das haus an der Haustür kaufen

Bei mir war es so, dass ich mir das Haus nicht ganz leisten konnte und daher ein Freund das gekauft hat und mir einen Schlüssel dafür gab, aber selbst der Besitzer war. Ich habe ihn jetzt mit der Zeit rausgekauft und die letzte Rate hat er einfach als Kaufpreis an der Tür eingestellt. Ich habe mir dann quasi das Haus an der Tür gekauft und habe jetzt das Haus 2 mal in der Liste! Beide voll funktionsfähig!

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
-

**Optional: Video / Bilder des Fehlers**

![FehlerHaus](https://github.com/eiksch/statev_v3_issues/assets/160437543/2980233c-05f9-4f14-b8f5-eaec34364f70)

**Comment by simplycach** [comment]
Schmeiß dich doch mal als Mitbewohner raus, wenn du Eigentümer bist dürfte nichts weiter passieren. Wenn doch mach bitte ein Ticket auf und frag nach mir.

**Comment by Dennymaru32** [comment]
Jau hat funktioniert! Hab es nun nur noch 1 mal aufgelistet und kann alles ganz normal noch bedienen! Danke!
