### ISSUE TITLE
Haus Garten 

### ISSUE THREAD

**Issue by MrFricke1** [mexyn/statev_v2_issues#3202]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by MrFricke1** [comment]
Hi ich habe mir ein haus gekauft in Paleto und wollte fragen ob man die gegenstände im garten weg bekommen könnte? Pavilion Grill usw Char name Conor Murphy

**Comment by simplycach** [comment]
Bitte mal Char Namen und Haus Hash hier reinschreiben.

**Comment by MrFricke1** [comment]
Conor Murphy 
house_Paletobay_22

Geht um die sachen hinten im garten am pavilion

**Comment by MrFricke1** [comment]
oder denn grill an die hauswand steht halt alles komisch in der mitte

**Comment by simplycach** [comment]
Unsere Game Designer schauen sich das mal an.

**Comment by MrFricke1** [comment]
danke

**Comment by Erumeldor** [comment]
Hi @MrFricke1 
Tut mir Leid, solche Sachen werden nicht mehr entfernt.
