### ISSUE TITLE
Versetzung Abladepunkt - pf_lamessa_42

### ISSUE THREAD

**Issue by coresync2k** [mexyn/statev_v2_issues#3203]
Hallo liebes Team.

Wir haben uns ein Lager zugelegt, und der Abladepunkt ist etwas sagen wir mal Suboptimal :)

![alterpunkt](https://github.com/eiksch/statev_v3_issues/assets/18634831/3143e469-142f-4855-8718-70aea799dc55)
Das ist der aktuelle Abladepunkt, direkt auf der "Hauptstrasse" und wirkt irgendwie ziemlich verloren dort an der Seite.

![neuerpunkt](https://github.com/eiksch/statev_v3_issues/assets/18634831/9734490d-6956-4000-9904-af1bba56d662)
Hier wo der Youga steht, wäre der neue Abladepunkte perfekt, so blockiert er keine Strasse und wirkt dem Gebäude zugehörig.

Der Gebäude Hash ist -> pf_lamessa_42

Vielen Dank

**Comment by Erumeldor** [comment]
@coresync2k 
Was stört denn an der aktuellen Position?
Da ist ein Garagentor, das gehört zu eurem Gebäude. Ist doch sehr passen da. :)

**Comment by coresync2k** [comment]
@Erumeldor 

Das Problem ist, das die Leute nicht mitbekommen oder denken das dieser Abladepunkt an der Seite so mitten auf der Strasse überhaupt dazu gehört. Mal abgesehen davon das das Tor zwar cool ist, aber viele dieses "Tor" garnicht kennen.

Hauptproblem ist einfach, das man diesen Punkt nicht dem "Eingang" zuordnet und die Leute auch zu Faul sind mal nen Telefon in die Hand zunehmen um anzurufen. Der Punkt in Sichtweite der Türe wäre da um einiges Sinnvoller und "zugehöriger" weil es doch bei 90% der anderen Firmen so ist.
