### ISSUE TITLE
Mrs. Sporty Shorts falsch sortiert

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#3205]
**Character Name**
Charly Russo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.03.24 15:30 Uhr

**Beobachtetes Verhalten**
Die Mrs. Sporty Shorts sind unter Unterhemden sortiert

**Erwartetes Verhalten**
Sollten als Hosen erhältlich sein

**Schritte um den Fehler nachvollziehen zu können**
Kleiderladen in der Westside aufsuchen, Unterhemden Kategorie bei Frauen

**Optional: Video / Bilder des Fehlers**
https://imgur.com/x0r9dAS
https://imgur.com/PYrVUbc

**Comment by Enemyaa** [comment]
Das ist nicht falsch. Manche Designer legen das auf den Undershirt Slot. Das bleibt so!
