### ISSUE TITLE
Klamotten Fehler nach Update

### ISSUE THREAD

**Issue by Elfenblut** [mexyn/statev_v2_issues#3206]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Valea Machiavelli**

**Nach dem leztzten Update**
 Wann exakt (Datum / Uhrzeit) ist der Fehler beobachtet worden 

**Beobachtetes Verhalten**
Item der Brille Black Windsor ist vorhanden und angezogen, jedoch unsichtbar. Hose Black High Rise Jeans V3 ist irgend ein anderes Hosenmodell in Grün

**Erwartetes Verhalten**
 Items sollten das anzeigen was sie wirklich sind

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot 2024-03-21 162837](https://github.com/eiksch/statev_v3_issues/assets/164375348/fdf62f2a-3e81-4715-a519-41613e5ba08e)

**Comment by simplycach** [comment]
Sind bereits dran.
