### ISSUE TITLE
Schuhe werden nach Update falsch angezeigt

### ISSUE THREAD

**Issue by Lvzifer-ctrl** [mexyn/statev_v2_issues#3208]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Lucifer Dawn

**Auftrittszeitpunkt (Datum / Uhrzeit)**

21.03.2024 19:15

**Beobachtetes Verhalten**

Nach Serverupdate eingeloggt, "Just Do It Air Force 1" auf einmal beige Winterstiefel

**Erwartetes Verhalten**

Nikes sollten als Nikes angezeigt werden

**Schritte um den Fehler nachvollziehen zu können**

Just Do It Air Force 1 anziehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/136606428/c62eae23-a02c-4aa8-a734-0fce4f099cda)

**Comment by simplycach** [comment]
Sind bereits dran.
