### ISSUE TITLE
Fehler bei Weißen Air Force 1

### ISSUE THREAD

**Issue by Bonnie-Barrow** [mexyn/statev_v2_issues#3209]
**Character Name**
Liliana Morello

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Nach dem Update am 21.03

**Beobachtetes Verhalten**
Weiße Nike Air Force 1 sind Boots, auch durch ausziehen unverändert.

**Optional: Video / Bilder des Fehlers**
![69a3d691517609f354dcd6baf8a57cae](https://github.com/eiksch/statev_v3_issues/assets/126402348/7c43f633-4960-46cb-b36b-7ab3cb531f47)
![7c9f6aa6bb37fbc60d816aec90aa85ea](https://github.com/eiksch/statev_v3_issues/assets/126402348/900b117c-559f-4b51-889d-7f645af15b53)

**Comment by simplycach** [comment]
Sind bereits dran.
