### ISSUE TITLE
Aus Just Do It Air Force 1 wurden Stiefel

### ISSUE THREAD

**Issue by Pitsch83** [mexyn/statev_v2_issues#3210]
Character Name: Peter_Lundberg

Auftrittszeitpunkt (21.03.2024 / 19:15 Uhr)

**Beobachtetes Verhalten**
Nach dem letzten Update wurden aus meinen Just Do It Air Force 1 Arbeitsstiefel

**Erwartetes Verhalten**
Das es noch immer die normalen Schuhe sind

**Optional: Video / Bilder des Fehlers**
![Air Force 1](https://github.com/eiksch/statev_v3_issues/assets/95588720/8fc44266-b5c6-4be0-8b65-bee4a8769184)
![Stiefel](https://github.com/eiksch/statev_v3_issues/assets/95588720/30270417-707b-4c15-b725-5b2762890296)

**Comment by simplycach** [comment]
Sind bereits dran.
