### ISSUE TITLE
Schminkttisch von Friseur führt regelmässig zu Userface Interface abstürze  | und andere fehler

### ISSUE THREAD

**Issue by Xymena** [mexyn/statev_v2_issues#3212]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Alice_swan

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19:00- 20:00

**Beobachtetes Verhalten**
Bei E Drücken beim Schminktisch kommt es Regelmäßig zu User Interface Abstürze dies betrifft dann nicht nur eine person sondern Sämtliche die ihn betätigen. 

Schminke Reddwood funktioniert nicht es kommt hierbei zu einer meldung "ungültiger vorgang"

**Erwartetes Verhalten**
 Entsprecheende UI öffnet sich Schminken ist möglich 

**Schritte um den Fehler nachvollziehen zu können**
Friseur geht hinten am Stuhl und drückt E.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/76626768/786158c6-a6de-403b-9a88-da6c90e0b653)

![image](https://github.com/eiksch/statev_v3_issues/assets/76626768/9985cba5-b356-4d82-81cf-c09c5b8a5123)

**Comment by Xymena** [comment]
Der Interface Fehler scheint Personen Abhängig zu sein bei **Pearce_Carter** ist dieser Fehler immer wieder aufgetreten. Bei der nächsten person funktionierte es ohne weiteres. Wenn es eine andere person auch versucht tritt der fehler ebenfalls auf

**Comment by simplycach** [comment]
Sollte fixed sein, wenn nicht bitte erneut aufmachen.
