### ISSUE TITLE
Hintertür Sandy Shores Office Schließt bei Restart nicht

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#3213]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
James Carter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.03.  8 Uhr

**Beobachtetes Verhalten**
Die Hintertür Richtung Garage ist morgens immer offen.
Wenn man sie zuschließt, kommt erst die "Aufgeschlossen" Meldung. Dann beim 2. die "Zugeschlossen" Meldung.

**Erwartetes Verhalten**
Wenn sie zugeschlossen ist, auch nicht auf geht.

**Schritte um den Fehler nachvollziehen zu können**
Nach einem Restart zur Tür gehen und schauen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/PLyh7zXevbc

**Comment by TheBroady** [comment]
![20240322080128_1](https://github.com/eiksch/statev_v3_issues/assets/70150887/0eb8f6d9-964e-4ec8-b27d-2badf52c2741)
Gilt auch für diese Seitentür

**Comment by SgtBoaz-Terry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Türen SSSO fehlerhaft geschlossen nach Restart](https://trello.com/c/DdNQydrF/470-t%C3%BCren-ssso-fehlerhaft-geschlossen-nach-restart)

**Comment by TheBroady** [comment]
Scheint auch Türen im MRPD zu betreffen. Also ggf sogar fraktionsübergreifend?

**Comment by simplycach** [comment]
fixed
