### ISSUE TITLE
Interface beim Friseur abgestürzt

### ISSUE THREAD

**Issue by TerrorQueen** [mexyn/statev_v2_issues#3214]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name** Naomi Sunchez
 Naomi Sunchez

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 ‎Freitag, ‎22. ‎März ‎2024, ‏‎00:59:43
                                                                                                                     ‎Freitag, ‎22. ‎März ‎2024, ‏‎11:15;21
**Beobachtetes Verhalten**
 Wenn ich Haare, Makeup etc. machen möchte kommt die Meldung Interface abgestürzt 

**Erwartetes Verhalten**
 Das Interface solle nicht Abstürzen 

**Schritte um den Fehler nachvollziehen zu können**
 Mehrmals versucht , immer wieder Interface abgestürzt

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot (448)](https://github.com/eiksch/statev_v3_issues/assets/164494399/bdbf6a0f-eede-4396-b416-1c193a8b564b)

**Comment by simplycach** [comment]
Ist dasselbe Problem https://github.com/eiksch/statev_v3_issues/issues/3212
