### ISSUE TITLE
Bus verschlossen nach Reparatur

### ISSUE THREAD

**Issue by 48619** [mexyn/statev_v2_issues#3215]
**Auftrittszeitpunkt (Datum / Uhrzeit)**
20.03.2024 21:15 Uhr
11.03.2024 22:45 Uhr

**Beobachtetes Verhalten**
Busse werden bei einer Reparatur in einer Werkstatt leider abgeschlossen und lassen sich mangels Schlüssel nicht wieder öffnen.

**Erwartetes Verhalten**
Busse werden bei der Reparatur nicht abgeschlossen oder können durch das Bus Personal wieder aufgeschlossen werden.

**Schritte um den Fehler nachvollziehen zu können**
- Bus beschaffen
- zur Werkstatt fahren
- Reparieren lassen
- Bus abgeschlossen

PS: wir wollen doch nur RP machen :)

**Comment by SatyriaDine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bus verschlossen nach Reparatur](https://trello.com/c/YNscInOi/469-bus-verschlossen-nach-reparatur)
