### ISSUE TITLE
Bewegungsstiel wird nicht gespeichert

### ISSUE THREAD

**Issue by Elfengames** [mexyn/statev_v2_issues#3216]
**Izaac Baker**

**22.03.2024 ~21:50**

**Beobachtetes Verhalten**
der Bewegungsstiel wird nicht gespeichert und immer mit einem Falschen ersetzt nach der hocke und loggin

**Erwartetes Verhalten**
Der Bewegungsstiel der vorgewählt wurde wird beibehalten

**Schritte um den Fehler nachvollziehen zu können**
Kann ich leider nicht genau sagen

**Optional: Video / Bilder des Fehlers**
https://medal.tv/de/games/gta-v/clips/22vDVPP8L2wZr7/d13375fKURVQ?invite=cr-MSxrakMsMjE3Nzc3MjI5LA

**Comment by simplycach** [comment]
Das der nach dem erneuten einloggen nicht gespeichert wird ist normal.

**Comment by simplycach** [comment]
Aber das mit der Hocke verstehe nicht ganz.

**Comment by Elfengames** [comment]
das ding ist nach dem einloggen hab ich diesen weiblichen stil halt auch

**Comment by SHaagmann** [comment]
Als Außenstehender sieht man das auch nach dem hocken

**Comment by Elfengames** [comment]
Hier auch nochmal direkt nach dem Einloggen falscher Bewegungsstiel obwohl ich zuletzt normal hatte

https://medal.tv/de/games/gta-v/clips/22wnHukBxmMF8j/d1337pO09DYc?invite=cr-MSxmMnosMjE3Nzc3MjI5LA

**Comment by DrGrizzlY17** [comment]
> Hier auch nochmal direkt nach dem Einloggen falscher Bewegungsstiel obwohl ich zuletzt normal hatte
> 
> https://medal.tv/de/games/gta-v/clips/22wnHukBxmMF8j/d1337pO09DYc?invite=cr-MSxmMnosMjE3Nzc3MjI5LA

Kurze Rückfrage: Ist dein "Standard Gehstil" einfach der "Normal"?

**Comment by Elfengames** [comment]
> > Hier auch nochmal direkt nach dem Einloggen falscher Bewegungsstiel obwohl ich zuletzt normal hatte
> > https://medal.tv/de/games/gta-v/clips/22wnHukBxmMF8j/d1337pO09DYc?invite=cr-MSxmMnosMjE3Nzc3MjI5LA
> 
> Kurze Rückfrage: Ist dein "Standard Gehstil" einfach der "Normal"?

Ja

**Comment by DrGrizzlY17** [comment]
> > > Hier auch nochmal direkt nach dem Einloggen falscher Bewegungsstiel obwohl ich zuletzt normal hatte
> > > https://medal.tv/de/games/gta-v/clips/22wnHukBxmMF8j/d1337pO09DYc?invite=cr-MSxmMnosMjE3Nzc3MjI5LA
> > 
> > 
> > Kurze Rückfrage: Ist dein "Standard Gehstil" einfach der "Normal"?
> 
> Ja

Ok is fixed next update
