### ISSUE TITLE
Fehler beim Verkauf im Kleidungsgeschäft

### ISSUE THREAD

**Issue by Velnarya** [mexyn/statev_v2_issues#3217]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Kunden im Kleiderladen.

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Über den Tag verteilt. (22.03.2024)

**Beobachtetes Verhalten**
Wen ein Kunde ein Kleidungsstück im Laden kaufte wurden 3 Schnittmuster aus der Theke entfernt.

**Erwartetes Verhalten**
Pro gekauftes Kleidungsstück sollte nur ein Schnittmuster verbraucht werden und nicht alle.

**Schritte um den Fehler nachvollziehen zu können**
3 Schnittmuster in die Ladentheke lege und anschliessend das Kleidungsstück kaufen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Erumeldor** [comment]
Sollte mit dem Update gestern alles fixed sein.
