### ISSUE TITLE
Lifeinvader Pic Upload durch CORS Policy nicht möglich

### ISSUE THREAD

**Issue by panteLx** [mexyn/statev_v2_issues#3219]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Felix_Sullivan
**Auftrittszeitpunkt (Datum / Uhrzeit)**

23.03.24 01:30
**Beobachtetes Verhalten**

Pic Upload auf Lifeinvader durch CORS Policy nicht möglich.
**Erwartetes Verhalten**

Bild sollte angezeigt werden
**Schritte um den Fehler nachvollziehen zu können**

Hochladen auf pic.statev.de - hochladen auf social.statev.de - F12
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

```
Access to fetch at 'https://pic.statev.de/i/HWDmb0.jpg' from origin 'https://social.statev.de' has been blocked by CORS policy: 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Ich würde einfach mal auf Titos Ankündigung verweisen, dass es heute Nacht noch zu Problemen kommen kann, bitte Morgen früh nochmal probieren.

**Comment by simplycach** [comment]
Geht bei mir ohne Probleme
