### ISSUE TITLE
Lampadati Novak Geschwindigkeit Bergauf/Allgemein

### ISSUE THREAD

**Issue by Domeex3** [mexyn/statev_v2_issues#322]
Domenik_Sommer

Permanent

Extrem langsames Fahrzeug, manche Berge nurnoch mit 60km/h schaffbar, andere längere nicht mehr als 115km/h, Topspeed 170km/h

Mehr leistung, Berge als SUV problemlos bewältigen können.

https://youtu.be/PRI5X1qWaIk

https://youtu.be/R_hBc42pDek

Sounds einfach ignorieren :D

**Comment by DonVitoDiangelo** [comment]
Fahrzeugpool wurde komplett überarbeitet. So gewollt.
