### ISSUE TITLE
Brute Pony Fahrzeug - Folierung

### ISSUE THREAD

**Issue by robka87owl** [mexyn/statev_v2_issues#3220]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Andreas Kowalski

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.03.2024 - zirka 15:30 Uhr

**Beobachtetes Verhalten**
Folierung wechselt jedes mal beim Ein / Ausparken des Fahrzeuges

**Erwartetes Verhalten**
Selbe Folierung wie im Auslieferungszustand

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug einparken, dann ausparken, Fahrzeug hat eine andere Folierung

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920 x 1080

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Hast mal nen Video davon ?

**Comment by robka87owl** [comment]
(https://clips.twitch.tv/LongSlickAardvarkKAPOW-UJv8BcgIJZBY4h3H)

**Comment by SatyriaDine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Brute Pony wechselt Folie beim Einparken](https://trello.com/c/AyxfOzTo/475-brute-pony-wechselt-folie-beim-einparken)

**Comment by Erumeldor** [comment]
Ist im nächsten Update fixed :)
