### ISSUE TITLE
Kartenzahlung Restaurant/Werkstatt

### ISSUE THREAD

**Issue by LeonF0207** [mexyn/statev_v2_issues#3222]
**Character Name**
Jake Thompson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
24.03.2024 - 15:25 Uhr

**Beobachtetes Verhalten**
Wenn man kein Bargeld dabei hat und mit Karte zahlt, bleibt das Bestellfenster weiterhin offen und man muss nachdem Essen entweder das Game restarten, wenn gerade ein Mitarbeiter des Restaurants im Dienst ist oder wenn keiner im Dienst ist erneut das Bestellfenster aufmachen und dann schließen.

Bei einer Werkstatt bleibt einem nichts anderes übrig als kurz mal in die Ecke zu verschwinden und das Game neuzustarten. 

**Erwartetes Verhalten**
Das dass Bestellfenster nachdem das Kartenzahlungsbestätigungsfenster aufgegangen ist nicht mehr offen ist und in der Werkstatt das dass Unterschriftsfenster nach der Unterschrift und sobald man auf "Kaufen" drückt zu geht.

**Schritte um den Fehler nachvollziehen zu können**
Ohne Bargeld ins Restaurant am Tisch setzen und bestellen oder ohne Bargeld in die Werkstatt und ein Fahrzeug reparieren lassen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Hast du mal ein Video davon ?

**Comment by simplycach** [comment]
Da ich bisher von dir keine Antwort erhalten habe gehe ich mal von aus der Bug ist behoben oder nicht mehr existent.
