### ISSUE TITLE
Selbstgedrehte Zigarette ist sehr anhänglich

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3223]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew_Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

24.03 19:32
**Beobachtetes Verhalten**

Nachdem man eine selbstgedrehte Zigarette angefangen hat und diese versucht mit "," abzubrechen hört die Animation zwar auf, aber die angehangende Zigarette verschwindet nicht
**Erwartetes Verhalten**

Gleiches verhalten wie bei allen anderen Zigaretten
**Schritte um den Fehler nachvollziehen zu können**

Zigarette selber drehen und rauchen

Kein bock mehr haben und wundern, dass die Zigarette so anhänglich ist
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/58612983/f93d5c8e-5d0c-445f-9530-55e00a41470f)

**Comment by SatyriaDine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Selbstgedrehte Zigarette geht nicht weg nach Animationsabbruch](https://trello.com/c/27dWa0RK/477-selbstgedrehte-zigarette-geht-nicht-weg-nach-animationsabbruch)
