### ISSUE TITLE
Abladepunkt Versetzung

### ISSUE THREAD

**Issue by Riccardo20240** [mexyn/statev_v2_issues#3224]
## WICHTIGE INFORMATION!!:
Abladepunkt Versetzten

Riccardo Gambino

![Abladepunkt Firma](https://github.com/eiksch/statev_v3_issues/assets/164810114/48b52a84-8059-4aa5-9cac-2d3dd8319dd3)
![Firmen Hash](https://github.com/eiksch/statev_v3_issues/assets/164810114/c93041ac-a466-4727-b9e7-832d769989df)
![Neu Setzten](https://github.com/eiksch/statev_v3_issues/assets/164810114/48234bc6-7e4d-45e2-8ba5-4c1dc8df2b4a)
Vieleicht kann mann ihn Hier auf die Straße setzten

Danke im Vorraus 

Liebe Grüße

**Comment by nb431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Abladepunkt Versetzung](https://trello.com/c/r0slgqFy/480-sitzpl%C3%A4tze-wing-stop-restaurant)

**Comment by Erumeldor** [comment]
@Riccardo20240 
Was stört denn an der aktuellen Position?

**Comment by Riccardo20240** [comment]
Der ablade/belade punkt ist sehr schwer mit grossen Fahrzeugen  , Pounder geht noch grade so von der seitenstraße aus aber mit Zugmaschiene und Achse wird es nichts  werden .


Von der seitenstrasse aus ist die einfahrt zu schmal .
Darum habe ich gefragt ob man den abladepunkt auf die straße setzten kann.

Werde Gleich mal noch ein paar Bilder machen das mann es bessre sieht

Vieleicht kann mann ja auch einfach die einfahrt vergrössern Vieleicht nur den  Müllkontainer hinterm Zaun,  zaunmauerelemente Hydrand und den Poller weg dann würde das gehen .

![Einfahrt](https://github.com/eiksch/statev_v3_issues/assets/164810114/cb504dea-8104-4574-a043-ed262c809cad)
![Einfahrt 2](https://github.com/eiksch/statev_v3_issues/assets/164810114/c1a41feb-b49d-43e3-b5e6-72049036c0f3)

oder hier einfach wenn es einfacher ist

Vieleicht kann mann ja auch einfach die einfahrt vergrössern Vieleicht nur den  Müllkontainer hinterm Zaun,  zaunmauerelemente Hydrand und den Poller weg dann würde das gehen .
![Einfahrt 3](https://github.com/eiksch/statev_v3_issues/assets/164810114/1bbb2285-6a50-4582-94e0-6acc529f0097)


Wie gesagt ich weiss nicht was einfacher ist!



Liebe Grüße und Danke im Vorraus

**Comment by Erumeldor** [comment]
Hab ihn dir auf die Straße gesetzt.
Ist im nächsten Update geändert :)

**Comment by Riccardo20240** [comment]
Danke
