### ISSUE TITLE
Map Symbol für eigene Häuser und Hotels

### ISSUE THREAD

**Issue by WalDragoner3425** [mexyn/statev_v2_issues#3225]
Fehler/Bug:
Gekaufte Häuser und Hotels werden nicht auf der Map angezeigt. (Hotels werden zwar angezeigt wenn man sich eingemietet hat aber nicht wenn man selbst eins besitzt.)

Erwartetes Verhalten:
Gekaufte Häuser und Hotels haben ein Symbol auf der Map und werden angeziegt.

**Comment by DrGrizzlY17** [comment]
Duplicate and fixed next update
