### ISSUE TITLE
Hydrant an der Garage entfernen oder versetzen?

### ISSUE THREAD

**Issue by Surgii** [mexyn/statev_v2_issues#3227]
Quando_Benett

Ist es möglich an meiner Garage den Hydranten zu entfernen oder zu versetzen? Ist ein wenig störend beim ein und ausparken der Fahrzeuge.
![Screenshot_14](https://github.com/eiksch/statev_v3_issues/assets/164812950/029ed2ea-7cac-41c4-90bd-39634a9890ee)

![Screenshot_16](https://github.com/eiksch/statev_v3_issues/assets/164812950/5c37cc75-0224-454d-bec5-b5ba9a35c2a0)

Lg und danke im Vorraus =)

**Comment by Erumeldor** [comment]
Wärs auch fine für dich, die Garagenausfahrt so zu verschieben, das es nicht mehr stört?
Also, so circa einen halben Meter?

**Comment by Surgii** [comment]
Klar das wäre auch ne Lösung die das gleiche bezweckt :)

**Comment by Erumeldor** [comment]
Ich hab ihn mal circa einen halben Meter verschoben. Ist im nächsten Update geändert.
Markier mich gerne nochmal, wenn es noch nicht passt.
