### ISSUE TITLE
Schwarzmarkt - Waffe abkratzen item verschwindet. 

### ISSUE THREAD

**Issue by PapaGambo** [mexyn/statev_v2_issues#3228]
**Beobachtetes Verhalten**
Die Alte Feile verschwindet auch, wenn man eine Waffe abkratzen möchte und nicht genug Geld dabei hat. 

**Erwartetes Verhalten**
Die Alte Feile bleib, auch wenn man nicht genug Geld dabei hat.

**Comment by DrGrizzlY17** [comment]
fixed next update...
