### ISSUE TITLE
Reagenzgläser  - 2 Statt 1/Bodenprobe 

### ISSUE THREAD

**Issue by PapaGambo** [mexyn/statev_v2_issues#3229]
**Beobachtetes Verhalten**

1. Bei einer Bodenprobe verschwinden 2 Reagenzgläser statt 1. 
2. Die Reagenzgläser können auch im Crime Lager verwendet werden [Beton]

**Erwartetes Verhalten**

1. Bei einer Bodenprobe sollte 1 Reagenzgläser  verlieren statt 2
2. Die Reagenzgläser sollten nicht im Crime Lager verwendbar sein.

**Comment by DrGrizzlY17** [comment]
Hi meinst du mit "Die Reagenzgläser sollten nicht im Crime Lager verwendbar sein.", das die genommenen Bodenproben verwendet werden können?

**Comment by PapaGambo** [comment]
@DrGrizzlY17 
Genau, Bodenproben in Crime Lager wo Beton ist, macht nicht wirklich Sinn. Vielleicht eine Meldung wie bei dem Samen, "Dies kannst du nicht machen." / "Der Boden ist Ungeeignet:"

**Comment by DrGrizzlY17** [comment]
Achso ok, dachte man kann die zum craften verwenden. Ja da muss man mal schauen, aber das doppel removen sollte nicht sein

**Comment by PapaGambo** [comment]
Also wenn du die Reagenzgläser im Crime Lager verwendest, bekommst du auch eine Betonprobe mit Kennzeichnung, also benutzbar ist es, nur abgegeben habe ich sie noch nicht.

**Comment by DrGrizzlY17** [comment]
fixed
