### ISSUE TITLE
LKW verliert Trailer sobald er in Streaming Range ist

### ISSUE THREAD

**Issue by Shirobaka** [mexyn/statev_v2_issues#323]
**Character Name**
Shigekuni Yamamoto

**Zeitpunkt (Datum / Uhrzeit)**
21.11.2020 ca. 17 Uhr

**Beobachtetes Verhalten**
Sobald ein LKW mit Trailer in die Streaming Range kommt, löst sich der Trailer und der LKW fährt ohne weiter, passiert scheinbar nur bei dem "vorbeifahrenden", nicht beim Fahrer des LKWs.
Ob es bei jedem LKW vorkommt ist mir derzeit nicht bekannt.
Sobald man die Streaming Range des Trailers verlässt und erneut die stelle abfährt ist der Trailer wieder weg.

**Erwartetes Verhalten**
Der Trailer sollte am LKW gekoppelt bleiben.

**Schritte um den Fehler nachvollziehen zu können**
LKW kommt mit Trailer in Streaming Range, Trailer löst sich und steht mitten auf der Straße

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
![hLilgDk](https://user-images.githubusercontent.com/8634317/99881725-b5c11080-2c1b-11eb-9e39-8ba31f1f88d7.jpg)

**Comment by AtreuX** [comment]
Wahrscheinlich nicht mehr hilfreich, aber hier ein kurzes Video dazu:

https://youtu.be/2muXxg9c7VY
