### ISSUE TITLE
Kleindungs-BUG: Item wechselt die Farbe. 

### ISSUE THREAD

**Issue by PapaGambo** [mexyn/statev_v2_issues#3230]
**Beobachtetes Verhalten**

Das Item in diesem Fall [M][U] Weißes Slim-Fit Hemd, aufgeknöpft, verändert seine Farbe wenn man bei Extras > Shirt > Aufgeknöpft/Geschlossen verändert. Es wurde zu [M][U] Olivgrünes Slim-Fit Hemd, aufgeknöpft,

**Erwartetes Verhalten**

Das item sollte sich nicht verändern, sollte weiterhin ein [M][U] Weißes Slim-Fit Hemd, aufgeknöpft, bleiben.

**Comment by nb431** [comment]
Grüße hättest du ein Bild davon oder ein Video

**Comment by simplycach** [comment]
Wenn der Fehler nochmal auftritt bitte melden.
