### ISSUE TITLE
Bug mit dem Produktionscomputer im Bekleidungsgeschäft

### ISSUE THREAD

**Issue by DerHessenTyp** [mexyn/statev_v2_issues#3231]
Nachdem ich es auch schon zuvor per Ticket gemeldet habe hier auch nochmal als Bug Report:

Es wurde hier mehrere Probleme mit meinem Char ,,Andrea Bailey" im Produktionscomputer im Bekleidungsgeschäft (SubUrban1) festgestellt.

1. Bei manchen Kleidungsstücken werden die richtigen Produktionszeiten von 1Min 30s angezeigt, die Produktion dauert dann auch wirklich solange und dann wiederrum wenn man den Produktionscomputer schliesst, wird das gleiche Produkt erneut mit 0s angezeigt. Was auch dann direkt fertig produziert ist. Ich denke da sollte bei jedem Produkt die Zeit nicht bei 0s liegen.
2. Werden statt 1x Schnittform Collegejacken die mit 3x hinterlegt sind verdoppelt hergestellt.  Wir haben das 2x ausprobiert, weil wir dachten wir hätten uns vielleicht nur verklickt.
3.  Haben wir Schnittform Levi´s Denim Jackets 3-4 Mal gestartet/angeklickt um die Fehlermeldung nochmal zu bekommen die zuvor aufgetaucht ist, (beim ersten Mal ist eine Fehlermeldung erschienen, die ich leider nicht mehr weis) und es wurden innerhalb von 5 Sekunden 7x jeweils 2 / 2 Schnittform Levi´s Denim Jackets hergestellt. Erst nachdem ich die zuvor hergestellten Schnittmuster ins Lager räumen wollte, habe ich festgestellt dass diese Lev´s Schnittformen hergestellt wurden weil die Liste der Maschine länger war um es direkt zu sehen.
4. Wir sollten nach 7 Produktionen wenn Sie richtig durchgeführt worden sein aber nur höchstens 21 Jacken im Lager haben. Hier sind aber 42 in der Maschine gelandet, was mit der Anzeige von 2/2 auch richtig wäre, wenn man die Zahl unten rechts neben dem Produktions starten geändert hätte. Was nicht der Fall bei uns war, da wir jeweils nur 1x Schnittform herstellen wollten.
5. Aufgetreten sind die Fehler am 25.03.2024 zwischen 12:20 und 12:45 Uhr wie auf dem Screenshot zu erkennen ist.

Sollten weitere Fragen offen sein, stehe ich natürlich da gerne zur Verfügung.

**Optional: Video / Bilder des Fehlers**
![Produktionscomputer Kleiderladen](https://github.com/eiksch/statev_v3_issues/assets/70151958/64f346e4-30ab-4a5f-9faf-d83470dcf417)

**Comment by Erumeldor** [comment]
@DerHessenTyp 
Das sollte alles mit dem letzten Update behoben sein.
Falls nicht, gerne nochmal kommentieren dann machen wir das Issue wieder auf.
