### ISSUE TITLE
MLO Fehler MRPD Garageneinfahrt

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#3232]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Beobachtetes Verhalten**
Da buggt was an den Garagen Eingängen. Siehe Video
Very Low prio. Nur n Schönheits Ding

**Optional: Video / Bilder des Fehlers**
https://youtu.be/3PKIkeXk5xk

**Comment by SatyriaDine** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [MLO Fehler MRPD Garageneinfahrt](https://trello.com/c/f3Cj7iCY/478-mlo-fehler-mrpd-garageneinfahrt)

**Comment by simplycach** [comment]
Sollte glaube ich behoben sein.
