### ISSUE TITLE
Sitzplätze Wing Stop Restaurant

### ISSUE THREAD

**Issue by CCastles22** [mexyn/statev_v2_issues#3233]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Kai_Karabach

**Auftrittszeitpunkt (Datum / Uhrzeit)**

immer

**Beobachtetes Verhalten**

Bug im Wing Stop # Mirror Park: wenn sich 4 Personen an einem Tisch setzen wollen, alle mit der Animation "aufrecht" sagt das System "Platz belegt"  wenn sich der 4te und letzte hinsetzen will.
Mit einer anderen Animation wie zb "ruhig" kann sich die 4te Person hinsetzen.

**Erwartetes Verhalten**

alle 4 Gäste können unabhängig ihrer Sitzanimation an einem Tisch platz nehmen

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by nb431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sitzplätze Wing Stop Restaurant](https://trello.com/c/aloFnCNb/479-sitzpl%C3%A4tze-wing-stop-restaurant)

**Comment by QA-Pregon** [comment]
Glaub da wurde nur zu nah am anderen Stuhl gestanden, da geht alles easy
