### ISSUE TITLE
Noodle Exchange, kleine Fehlerchen und Wünsche

### ISSUE THREAD

**Issue by Xymena** [mexyn/statev_v2_issues#3234]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Alice_Swan

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit öffnung des Restaurants

**Serviertablett**
Vor den neuen Stühlen hatten wir andere Serviertabletts, die nicht so nach Pommesbude aussahen. Wäre es möglich, diese wieder zu bekommen?

**Fehlerhafter Spawn von Serviertablett**
Es kommt immer wieder dazu, dass an diesen Tisch das Tablett in der Person spawnt und die Kamera in den Body steckt. Fehler tritt auf, wenn mehrere am Tisch sitzen.
![image](https://github.com/eiksch/statev_v3_issues/assets/76626768/417ef383-4d65-4ad2-a919-a2d9c32c4d4a)

**Personen hängen im Stuhl**
Personen bleiben immer wieder in den linken Stuhl hängen und kommen nur schwer dort weg.
_Vorschlag: Tisch 1 auf die rechte Seite verlegen._
![image](https://github.com/eiksch/statev_v3_issues/assets/76626768/537aafe8-adfe-4886-b718-ae079ae95967)

**Stille Örtchen**

Personen verschwinden ganz oder sind nicht zu hören, wenn sie auf den Plätzen sitzen, können aber die Umgebung hören.
_Vorschlag: Jeweilige Sitzplätze entfernen oder geringfügig verschieben._

![image](https://github.com/eiksch/statev_v3_issues/assets/76626768/cd9deb47-5a65-4ee3-8a0a-d789eb83052e)
https://medal.tv/games/gta-v/clips/23l64S299MLmtc/d1337KmoGphW?invite=cr-MSxLTmUsNjQxMjQ1NTQs

**Instabile Stühle**
Stühle verschwinden gerne mal, wenn mehrere oder eine Person dran sitzen.

![image](https://github.com/eiksch/statev_v3_issues/assets/76626768/bc65db98-1bc0-4f29-8ed6-3f6cee836c2a)

**Dicker Po**
Leider hat der Verkäufer einen zu dicken Po, sodass teilweise schwer nur durchzukommen ist, ohne einen Hechtsprung.
_Vorschlag: Den Guten etwas vorschieben oder andere Pose._

_Stempeluhr kollidiert mit Maschine_
Beim Zugriff auf die Maschine kommt es häufig dazu, dass man sich ungewollt ein- und ausstempelt.
_Vorschlag: Stempeluhr verlegen bzw. so einen Stempelkasten hinzufügen._

![image](https://github.com/eiksch/statev_v3_issues/assets/76626768/fcfc9756-46ad-48d6-99b2-3a00db5bb307)

**Comment by nb431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Noodle Exchange Tische und Sitze Buggen](https://trello.com/c/FNXbsfR2/481-noodle-exchange-tische-und-sitze-buggen)

**Comment by TheOutburst** [comment]
1. diese roten Tischgedecke mit Messer & Gabel? Sollt ihr kriegen
2. Stühle beim Fenster wurden verschoben und sollten nun nicht so Besitzergreifend sein
3. Stille örtchen müsstet ihr nachm Update ma testen, können sich gebesstert haben
4. Instabile Stühle sollten stabiler sein
5. Der Verkäufer zieht nen bisschen den Arsch ein
