### ISSUE TITLE
[M] Weiß- Schwarze Air Force 1 werden beim Anziehen zu Schachbrettschuhen

### ISSUE THREAD

**Issue by Dennymaru32** [mexyn/statev_v2_issues#3235]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Daniel Knight

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.03.2024 21:30

**Beobachtetes Verhalten**
Nike Sneaker werden zu Schachbrettschuhen

**Erwartetes Verhalten**
Nike Sneaker sollten Nike Sneaker bleiben xD

**Schritte um den Fehler nachvollziehen zu können**
Nike Sneaker anziehen (zumindest: [M] Weiß- Schwarze Air Force 1)

**Optional: Video / Bilder des Fehlers**

![SchuheAus](https://github.com/eiksch/statev_v3_issues/assets/160437543/6b3f1e72-69e8-4d79-85cd-36af1d547841)
![SchuheAn](https://github.com/eiksch/statev_v3_issues/assets/160437543/b392c250-4f74-485f-b687-801e557d202e)

**Comment by simplycach** [comment]
Next Update fixed

**Comment by simplycach** [comment]
Ihr könnt mal probieren euren AltV Cache zu löschen, damit lässt sich das Problem lösen.

**Comment by Shazgul** [comment]
> Ihr könnt mal probieren euren AltV Cache zu löschen, damit lässt sich das Problem lösen.

Fehler besteht weiterhin, auch nach löschen des AltV Cache Folders. Das hat leider nicht geholfen.
