### ISSUE TITLE
Entfernen von 3 Objekten

### ISSUE THREAD

**Issue by Tobse1904** [mexyn/statev_v2_issues#3236]
Grüße, 

Wäre es möglich das ihr 3 Kisten rechts vor unserem Labor entfernt ?

![313493823-16bb4341-5fac-4df4-9f86-270e33950a58](https://github.com/eiksch/statev_v3_issues/assets/39304481/439d37fa-5bcb-4e51-8f65-e74e7cba75c1)

P.S wir wurden des Öfteren schon angerufen weil die Tür nicht gefunden wurde.

Das Bild ist von einem anderen Post ,der leider abgelehnt wurde.

**Comment by nb431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Entfernen von 3 Objekten](https://trello.com/c/vweUHF4s/482-entfernen-von-3-objekten)

**Comment by Erumeldor** [comment]
Hi @Tobse1904 
Ich werde euch die Kisten (immer noch) nicht entfernen, hab aber fürs nächste Update den Marker ein klein wenig nach vorne verlegt. Dann ist er nicht mehr ganz so versteckt dahinter.

**Comment by Tobse1904** [comment]
Ist okay, war eine bitte, weil ich dachte das es um die menge geht weil wir beim 1. mal so viel hatten. Aber ich habs mir hinter die ohren geschrieben. Das keine sachen entfernt werden.

Dennoch danke für die Mühe
