### ISSUE TITLE
Lifeinvader Bug: Post mit Bild im Anhang nicht erstellbar

### ISSUE THREAD

**Issue by NightcoreCEO** [mexyn/statev_v2_issues#3237]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Kayo Vik (LI Username: @DJ_K)

**Auftrittszeitpunkt (Datum / Uhrzeit)**

27.03.2024 ca. 17:00 Uhr und danach

**Beobachtetes Verhalten**

Das Erstellen eines Posts mit einem Bild (https://pic.statev.de/i/HgP1yU.png) ist nicht möglich. Sobald ich den Text schreibe, die Bild URL einfüge und auf Posten klicke, werde ich aus LI ausgeloggt. Dies geschieht sowohl IC übers Tablet, als auch OOC übern Browser. Ein normaler Post ohne Bild nur mit Text ist normal machbar und wird korrekt gepostet.

**Erwartetes Verhalten**

Der Post wird normal verfasst und anschließend gepostet

**Schritte um den Fehler nachvollziehen zu können**

-siehe video-

**Optional: Video / Bilder des Fehlers**

https://medal.tv/games/gta-v/clips/23wd0i4VQ_QdAX/d1337YxWHWrw?invite=cr-MSxuRnksMjIxMDMzMDczLA

**Comment by simplycach** [comment]
Scheint nicht wieder aufgetreten zu sein.
