### ISSUE TITLE
Osterei falsches Bild im Inventar

### ISSUE THREAD

**Issue by Snipser92** [mexyn/statev_v2_issues#3238]
Raik_Morton

**Auftrittszeitpunkt (Datum / Uhrzeit)**
28.03.2024 ca. 1:00Uhr

**Beobachtetes Verhalten**
Item im Inventar mit falschem Bild

**Erwartetes Verhalten**
richtiges Bild im Inventar

**Schritte um den Fehler nachvollziehen zu können**
Ei aufsammeln und im Inventar gucken.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/HggBDX
https://pic.statev.de/image/Hgg4G0

**Comment by simplycach** [comment]
Fixe mit diesem Update
