### ISSUE TITLE
Nike Schuhe haben keine Textur mehr

### ISSUE THREAD

**Issue by iamPiiku** [mexyn/statev_v2_issues#3239]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Elijah Latrell

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.03.24 / 22 Uhr

**Beobachtetes Verhalten**
Schuhe haben keine Texturen

**Erwartetes Verhalten**
Schuhe haben Texturen

**Optional: Video / Bilder des Fehlers**

![GTA5_Tm2WVg0O6S](https://github.com/eiksch/statev_v3_issues/assets/165236963/9ffddbbf-c03b-4e4f-98bb-b2b9a0aacb74)
![GTA5_cbnbHCDYlU](https://github.com/eiksch/statev_v3_issues/assets/165236963/7a00e876-4112-4157-93ac-73eb5fd0b929)

**Comment by simplycach** [comment]
Probiere mal deinen AltV Cache zu löschen, dass sollte helfen. Ist aber auch mit dem nächsten Update fixed.
