### ISSUE TITLE
Ball funktioniert nicht

### ISSUE THREAD

**Issue by WalDragoner3425** [mexyn/statev_v2_issues#3240]
Wenn man das Item "Ball" im Inventar rechtsklickt, kommt kurz eine Animation als ob man ihn in ausrüstet allerdings passiert danach nichts und man hat den Ball nicht in der Hand und kann ihn auch nicht werfen.

**Comment by simplycach** [comment]
Ist bereits bekannt, wir sind dran.

**Comment by TheOutburst** [comment]
woraround ist next update drin
