### ISSUE TITLE
Osterei nicht Aufhebbar

### ISSUE THREAD

**Issue by Shazgul** [mexyn/statev_v2_issues#3241]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Cady Young

Cady Young
**Auftrittszeitpunkt (Datum / Uhrzeit)**
28.03.2024
**Beobachtetes Verhalten**
Ostereier sind teilw. nicht aufhebbar

![GTA5 2024-03-28 15-57-20](https://github.com/eiksch/statev_v3_issues/assets/20743799/50aae0cd-8e00-41c7-b519-c38f3ce2990f)

**Comment by simplycach** [comment]
Ist bereits bekannt und wird mit dem nächsten Fix behoben.
