### ISSUE TITLE
Carlos bleibt Car los

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3242]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared & Carter Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

28.03 ca 21:30
**Beobachtetes Verhalten**

Wir beide haben versucht nacheinander Autos zu stehen und konnten beide die Motoren nicht starten nach dem aufbrechen 
**Erwartetes Verhalten**

Man kann nach dem Aufbrechen den Motor starten
**Schritte um den Fehler nachvollziehen zu können**

1. Die Brüderliche Aktivität "Autodiebstahl" bei Carlos starten
2. Zum Spot fahren
3. Auto aus der Garage holen
4. Auto Aufbrechen
5. Sich reinsetzten und denken: "Sollte eig an gehen"
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://medal.tv/de/games/gta-v/clips/23M9mPd7ke_Htd/d1337CoHY40z?invite=cr-MSxXclMsMTk1NTEzMTMzLA

**Comment by DrGrizzlY17** [comment]
Fixed bzw stay tuned nächstes update
