### ISSUE TITLE
Hip Hop Dances funktionieren nicht

### ISSUE THREAD

**Issue by Diak27** [mexyn/statev_v2_issues#3243]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**_Tyrese_Stone_**

**_29.03.24 / 5:30 Uhr_**

Die neuen Tänze "Hip Hop Dance" funktionieren nicht _(Video dazu weiter unten)_

click & Dance **_"Whoop Whoop"_**

Animationsmenü öffnen > Tanzen > Hip Hop Dances

[https://medal.tv/games/gta-v/clips/23SiivkOIsa63T/d133750zPAbw?invite=cr-MSxwVHksODk3OTczMyw](url)

**Comment by simplycach** [comment]
Ist mit dem nächsten Update fixed
