### ISSUE TITLE
Hilfe Knabber und Süßkram Notstand

### ISSUE THREAD

**Issue by LiljaMorningstar** [mexyn/statev_v2_issues#3244]
**Character Name**
Quinn Valen 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22:00 Uhr

**Beobachtetes Verhalten**
Da mir die Leute die Haare vom Kopf fressen was den Gebratenen Reis mit Hühnchen angeht, wollte ich den gestern neu kochen. Aber es war mir nicht möglich trotzdem ich alles dafür da hatte.
Es ist einfach aus dem Rezeptbuch verschwunden. Das ich das kochen konnte kann man sehen in der Produktionsliste da ich am 27.03.2024 von um 21-23:30 Uhr welchen gekocht habe.  

Wenn der "Gebratene Reis mit Hühnchen" nicht zu retten ist, ist das nicht so schlimm. Aber alles andere wäre Toll da ich wie gesagt Bestellungen dafür aufhabe.

Heute morgen ist aufgefallen dass auch noch: Tito´s Paws, Schokoriegel, Zimtschnecken, Don Vito Nachos

**Erwartetes Verhalten**
Ich brauche jetzt nicht unbedingt den "Gebratenen Reis mit Hühnchen" wieder. Aber alles andere wäre schon schön, da ich Bestellungen dafür auf habe und dafür Produkte angekauft habe.

**Schritte um den Fehler nachvollziehen zu können**
Rezeptbuch öffnen
Die Seiten umschlagen
Seiten für oben genannte Produkte fehlen

Wäre toll wenn Ihr euch das mal anschaut, Danke

Gruß 🥞 The Hungry Hud 🥞 Quinn und Connor

**Comment by TheOutburst** [comment]
das hat sich glaub ich mit der Produktionszeitenüberarbeitung erledigt
