### ISSUE TITLE
Osterhase ist weg

### ISSUE THREAD

**Issue by Ruby-Cross** [mexyn/statev_v2_issues#3245]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Ruby Cross**

**29.03.2024 um 10:19, allerdings auch schon einmal am 28. gegen 0 Uhr**

**Der Hase ist nicht sichtbar, auch nicht unsichtbar anwählbar.**

**Das er da ist. **

**Zweimal zum Legion Square gefahren, einmal das Spiel neu gestartet, keine Änderung.**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

****

![etwas stimmt mit Hasi nicht](https://github.com/eiksch/statev_v3_issues/assets/161027828/3ecdf13c-364e-45c5-ab2c-a67177097afc)

**Comment by simplycach** [comment]
Was hast du mit ihm gemacht ? Der Arme

**Comment by simplycach** [comment]
Ich schau gleich mal, eigentlich kann der nicht weg sein :D

**Comment by Ruby-Cross** [comment]
haha, ich wollte an seine Eier.. nein wait, eigentlich bringe ich ihm welche und danke

**Comment by simplycach** [comment]
Ist so gewollt, viel spaß beim suchen.
