### ISSUE TITLE
Hunger/Durst Bug?

### ISSUE THREAD

**Issue by Auralein** [mexyn/statev_v2_issues#3246]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```
Holly Swan

Holly Swan
Surge (weiß der Geier wie der IC heißt xD) aka Payton
Liv Blackwood

28.03.2024 ca. 22 Uhr

**Beobachtetes Verhalten**
Surge und ich haben Köttbullar gegessen und Mate + Eistee Pfirsich getrunken. Leider weiß ich nicht mehr was Liv hatte.
Nach einiger Zeit musste ich wieder essen und habe bis zum Auffallen 4 Portionen unterwegs verdrückt Während Liv und Surge keinen Hunger/Durst hatten. Fiel leider erst später auf, da ich dachte die beiden haben auch unterwegs was gegessen.

**Erwartetes Verhalten**
Man sollte in etwa zur gleichen Zeit nach einem Restaurantbesuch wieder hunger haben.

**Comment by TheOutburst** [comment]
ich bin mir ziemlich sicher, dass hier alles subba ist 👌
