### ISSUE TITLE
Durst vs. Hunger

### ISSUE THREAD

**Issue by ingo-lorenz** [mexyn/statev_v2_issues#3248]
**Character Name**
Peter_Fichtner

**Auftrittszeitpunkt (Datum / Uhrzeit)**
30.03.2024, 14:45

**Beobachtetes Verhalten**
Nach Essen und Trinken im Lucky Plucker war nach einiger Zeit der Durst auf null während der Hunger noch voll war.

**Erwartetes Verhalten**
relativ gleiches Verhalten zwischen Essen und Trinken

**Schritte um den Fehler nachvollziehen zu können**
Essen und Trinken im Lucky Plucker und warten

**Comment by Statev-Bonsai** [comment]
vollkommen normal, manche dinge sättigen mehr und länger als andere...

**Comment by simplycach** [comment]
Danke @Statev-Bonsai
