### ISSUE TITLE
MA Check IN Lucky Plucker

### ISSUE THREAD

**Issue by Schwammbooo** [mexyn/statev_v2_issues#3249]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Mason_Jones

Mason Jones
**Auftrittszeitpunkt (Datum / Uhrzeit)**

12.03.2024 22:03:21
**Beobachtetes Verhalten**

Ma Check In reagiert nicht wenn mitarbeiter sich einstempelt
**Erwartetes Verhalten**

Ma Check in sollte beim Stempel Datum Uhrzeit und ein- oder ausgstempelt zeigen.

Lucky Plucker Mitarbeiter betätigt mit E die Stempeluhr und überprüft dann im Tablet auf Firmen das Fenster MA Check in 

![image](https://github.com/eiksch/statev_v3_issues/assets/165506579/fd50ce80-a7c3-44e8-9946-06de0cbf7af1)

**Comment by QA-Pregon** [comment]
fixed
