### ISSUE TITLE
SlimJim wollen nicht arbeiten

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3250]
Character Name
Samuel Navarro

Auftrittszeitpunkt (Datum / Uhrzeit)
22:54 30.03.24

Beobachtetes Verhalten
Nach dem aufbrechen kommt die Nachricht "Aktion konnte nicht ausgeführt werden!"
Erwartetes Verhalten
Nach erfolgreichem Beenden des Minigames, die Items bekommen. (Natürlich ist ab und zu auch nichts zu holen)

Optional: Video / Bilder des Fehlers

[click](https://medal.tv/de/games/gta-v/clips/24gdeWqV9CghBt/d1337cP27m9W?invite=cr-MSwxeGosMjAwNTY4NDA1LA)

**Comment by simplycach** [comment]
Lösch mal deinen Cache einmal.

**Comment by simplycach** [comment]
Also es geht einwandfrei
