### ISSUE TITLE
vAPI Call per Javascript

### ISSUE THREAD

**Issue by ingo-lorenz** [mexyn/statev_v2_issues#3251]
Ich habe nun Tests mit der API gemacht und bin bei einem Test-Call auf folgendes Problem gestoßen, was ich aktuell nicht lösen kann.

Bevor ein Browser (Javascript) einen Cross-Site-Request macht, erfolgt ein Preflight, um die Settings zu checken.

Der Preflight (OPTIONS) sendet folgende Daten:

:authority: api.statev.de
:method: OPTIONS
:path: /req//factory/list/
:scheme: https
Accept: */*
Access-Control-Request-Headers: authorization
Access-Control-Request-Method: GET

Also wird geprüft, ob der authorization-header gesendet werden darf.

Als Response kommt (Auszug: nur Access-Control-Headers):

...
Access-Control-Allow-Methods: *
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 100
...

Also bekommt der Browser keine korrekte Rückmeldung, dass der Header gesendet werden darf und wirft einen Fehler in die Console:

**Access to XMLHttpRequest at 'https://api.statev.de/req//factory/list/' from origin 'https://xxxx.net' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.**

Wurde diese API schon extern live genutzt und habe ich es vielleicht komplett falsch verstanden? In Postman funktionieren alle meine Test-Calls GET und POST.

Browser: Chrome

Falls der Fehler doch bei mir liegt, würde ich mich über einen Hinweis freuen.

![image](https://github.com/eiksch/statev_v3_issues/assets/9450017/571446cd-19fd-4bb6-88b5-a3be9135bfeb)

Danke und Grüße
Ingo

**Comment by UNST4BL3** [comment]
Ich hatte das selbe bzw. ein ähnliches Problem beim dem es immer an CORS gescheitert ist. Ich habe eine CORS-Proxy zum testen verwendet, damit funktioniert es bei mir.

**Comment by ingo-lorenz** [comment]
Danke für die Antwort. Dann habe ist ja doch richtig interpretiert.

Aber ist es ein gangbarer Weg, dass jeder einen Proxy bauen muss? Außerdem kommuniziert die Webseite dann ja nicht direkt mit der vAPI, was ja auch nicht gewünscht ist.

Eine andere Möglichkeit ist, PHP zuzulassen, um die Calls durchzureichen. So könnte man das ganze CORS-Thema lösen, auch wenn das auch nur ein Workaround ist.

Es wäre schön, wenn es da eine einfache Lösung gibt, liebes State-Team. <3

**Comment by UNST4BL3** [comment]
Die Proxy verwende ich nur solange wie ich die Website lokal teste. Wenn diese dann auf dem Server integriert wir, kann sie wieder raus nehmen da sich die Website dann auf dem selben Server befindet.

Und ob es gewünscht ist kann ich dir nicht beantworten, mir wurde allerdings im Support-Ticket von einem Dev gesagt, dass es aktuell keine andere Möglichkeit gibt.

**Comment by UNST4BL3** [comment]
Und mir ist gerade noch aufgefallen, dass du die falsche method verwendest.
In deinem Beispiel verwendest du anscheinend :method: OPTIONS
Müsstest aber :method: GET verwenden.

**Comment by ingo-lorenz** [comment]
Die Method OPTIONS wird vom Browser für den Preflight verwendet, also automatisch vor meinem Call. Der richtige Call ist GET.

Wie hast du den Proxy gebaut? Suche eine möglichst einfache Art, da es ja hoffentlich absehbar ist, dass sich das nochmal ändert.

Liegt die Seite dann auf dem gleichen Server und die Domain ist auch gleich? Kann ich mir fast nicht vorstellen.

Hast du schon eine Seite ingame, die so funktioniert?

**Comment by UNST4BL3** [comment]
1. Ok, ich mach das nur so ein bisschen Hobby mäßig dann war das mein Fehler.

2. Einfach 'https://corsproxy.io/?' vor den url-String setzen. Also quasi 
`fetch('https://corsproxy.io/?'+url, {
...
})`

3. Es wurde gesagt, das die Website dann in einer Sandbox läuft und der zugriff auf andere Schen unter der statev.de Top-Level-Domain möglich ist. z.B. pic.statev.de

4. Noch nicht, aber hoffentlich bald wenn ich herausfinde warum mir die vAPI sagt, dass 1 keine gültige Nummer ist.

**Comment by ingo-lorenz** [comment]
Danke für die Infos.

Wenn du eine Nummer als String übergibst, also "1", dann bleibt es ein String. Versuche mal die " wegzulassen.

**Comment by UNST4BL3** [comment]
Mein request Body sieht so aus, da ist nix was dem Script sagt, dass das ein String ist:
`const body =  {
        factoryId: id,
        option: 1,
        title: name,
        data: inhalt,
    };`

und wenn ich mir mit console.log(typeof(body.option)) den Variablentyp anzeigen lasse erkenn er ihn ja als Nummer. Das Problem hab ich jetzt seit knapp 2 Tagen und mir gehen langsam die Lösungsansätze aus. XD

**Comment by ingo-lorenz** [comment]
Wir schweifen etwas vom Thema ab. Schreib mich gern dazu mal per Discord an: ingo.lorenz

Edit:
Du musst den Header

content-type: application/json

mitsenden. Dann geht es bei mir. Steht leider nicht in der Doku.

**Comment by rodistic** [comment]
Ist gelöst
