### ISSUE TITLE
Import kosten wurden nicht vom Konto abgebucht

### ISSUE THREAD

**Issue by DrColgate** [mexyn/statev_v2_issues#3252]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Anton Mueller

**Auftrittszeitpunkt (Datum / Uhrzeit)**
30.03.2024 12:20:00

**Beobachtetes Verhalten**
2 Fahrzeuge mit der selben Endzeiit importiert.
Cruiser Gangschaltung wurde vom Konto abgebucht.
Scorcher Gangschaltung wurde NICHT vom Konto abgebucht
Firmenhash: pf_lamessa_20
VBAN: 573 218

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![scorcher1](https://github.com/eiksch/statev_v3_issues/assets/74769835/94835093-d572-4195-b834-5811bd4bf75b)
![scorcher2](https://github.com/eiksch/statev_v3_issues/assets/74769835/856cdbfd-a033-4ef7-a45a-545e192fe5af)

**Comment by simplycach** [comment]
Lies sich leider bisher nicht reproduzieren.
