### ISSUE TITLE
Explodierende Fahrzeuge in der Werkstatt (leider mehrmals Täglich)

### ISSUE THREAD

**Issue by ManuelLadner** [mexyn/statev_v2_issues#3253]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Manuel_Turner**

**Täglich mehrmals!!**

**Fahrzeuge Explodieren beim Reparieren (buggen vorher wild rum - dann Bumm) im Video zu sehen!**

**Kein Explodieren**

**Fahrzeug in die Werkstatt Fahren und Reparieren (passiert nicht immer)**

**nix**

**https://streamable.com/felfey**

**Comment by simplycach** [comment]
Bereits bekannt und auch schon offen.
