### ISSUE TITLE
Werkstatt Tor Uncle Jacek`s!

### ISSUE THREAD

**Issue by ManuelLadner** [mexyn/statev_v2_issues#3254]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Manuel_Turner**

**Täglich / Jederzeit!)**

**Einfahrtstor Werkstatt Uncle Jacek geht zu schnell auf und zu! dadurch werden Fahrzeuge die da stehen "zerquetscht und kaputt"**

**Vielleicht ist es möglich ein Schloss anzubringen damit bei geöffneter Werkstatt das Tor offen bleibt! Wäre auch ein Vorteil für uns das die leite sehen das wir geöffnet haben**

**Hin Fahren oder gehen -  paar schritte entfernen und zuschauen wie das Tor zu rast! oder Fahrzeug hinstellen und weggehen dann wird das Fahrzeug zerdrückt!**

**nix**

**keine Bilder oder Video ist einfach nachzustellen!**

**Comment by Erumeldor** [comment]
Also ein Schloss können wir hier technisch leider nicht machen. 
Das Tor ist auch einfach von GTA so schnell. 

Kann hier also nur empfehlen, keine Autos in dem Bereich stehen zu lassen ;)
