### ISSUE TITLE
Kiste Wasser

### ISSUE THREAD

**Issue by Auralein** [mexyn/statev_v2_issues#3255]
Holly Swan - Nudelhaus

Seit längerem schon.

Kiste Wasser wird in der Verpackung mit 6 Flaschen befüllt und im Restaurant beim auspacken kommen immer nur 3 Flaschen. Das erhöht den Preis von Wasser natürlich (sollte eigentlich günstiger sein als andere Getränke) und ergibt auch keinen Sinn ^^'

**Erwartetes Verhalten**
Aus einer Kiste mit 6 Flaschen auch 6 Flaschen Wasser im Restaurant erhalten.

**Schritte um den Fehler nachvollziehen zu können**
Kiste Wasser im Restaurant entpacken

![grafik](https://github.com/eiksch/statev_v3_issues/assets/76708950/97669a43-a3fa-41cc-9736-8032ac29d913)

![grafik](https://github.com/eiksch/statev_v3_issues/assets/76708950/d3c0f896-0ac3-4a80-bbf4-d103fce66cf8)

**Comment by TheOutburst** [comment]
Moin, das passt, Wasser war immer bisschen OP, jzt isses balanced
Ich verstehe dass es keinen Sinn macht, dass aus 6 Flaschen 3 werden, ggf ändert sich das nochmal, aber an sich ist das erstmal aus balanceing Gründen ok so wie es ist
