### ISSUE TITLE
Afterhour Tisch verschwindet beim benutzen

### ISSUE THREAD

**Issue by Mytex88** [mexyn/statev_v2_issues#3256]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Carlos Sanchez

Carlos Sanchez und andere auch Namen nicht bekannt

**Auftrittszeitpunkt (Datum / Uhrzeit)**
31.03.2024 22:10 und zu anderen Zeiten auch

**Beobachtetes Verhalten**
Afterhour Tisch verschwindet wenn man Ihn aufstellen möchte und kommt nur beim benutzen eines anderen Gegenstandes wieder ins Inventar (siehe Video)

**Erwartetes Verhalten**
Sollte sich wie alle Möbel normal hinstellen lassen

**Schritte um den Fehler nachvollziehen zu können**
Afterhour Tisch versuchen hinzustellen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=cCsq44HqUHk

**Comment by stepz2k9** [comment]
Du bist im County, oder? Den kann man nur in der Stadt aufstellen. Liegt glaube ich an der Streaming Range, da einige Props nur dort gespawned werden können, wo sie im Base-Game stehen.

**Comment by Mytex88** [comment]
Ja bin ich, wird das noch geändert das man den überall aufstellen kann?

**Comment by TheOutburst** [comment]
Das ja dumm
Also... die Einzige Lösung die ich anbieten kann ist den Tisch raus zu nehmen

**Comment by simplycach** [comment]
@TheOutburst Dann geht das leider nicht fürs County in South LS wird der viel verwendet.

**Comment by Mytex88** [comment]
Alles gut rausnehmen würd ich ihn auch nicht, dann muss man dass den Leuten im RP halt so verkauft das der im County nicht geht.

**Comment by simplycach** [comment]
Okey, dann würde ich das hier einmal schließen.
