### ISSUE TITLE
Der Apotheker Job (Crime) bricht zu schnell ab

### ISSUE THREAD

**Issue by MilowJones** [mexyn/statev_v2_issues#3258]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Milow_Jones**

**Auftrittszeitpunkt 01.04.2024/10:23**

**Der Apotheker Job (Crime) bricht zu schnell ab, habe den Auftrag, das ich nach Route 68 soll um 10:05 erhalten und bereits um 10:23 wurde der Job Abgebrochen weil der Ausgelaufen sei.**

**Der Job langsamer abbrechen**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**[Optional: Video / Bilder des Fehlers] (https://prnt.sc/2Wq3E5YEnLMe)**

**Comment by simplycach** [comment]
Scheint ein Einzelfall gewesen zu sein
