### ISSUE TITLE
Laderampen trennenpain

### ISSUE THREAD

**Issue by VeAderian** [mexyn/statev_v2_issues#3259]
Kevin Walker

**Auftrittszeitpunkt (Datum / Uhrzeit)**
permanent

**Beobachtetes Verhalten**
Laderampe "MUSS" geändert werden, Lager hinten und Kleiderladen vorne haben die selbe RAMPE

Es sind immer wieder leute du umherr irren und eine laderampe zum lager suchen, weil sie was kaufen wollen und dann wieder abhauen weil sie keine Laderampe gefunden haben. Ich bin halt auch nicht immer da am Lager um den Leuten zu sagen wo sie hin müssen und die rufen ja auch nicht unbedingt imemr an.

Firmeninformationen:
![freiraum3](https://github.com/eiksch/statev_v3_issues/assets/61833414/85f2a1ec-5aae-4491-a1dd-0f111c23b6d2)

 Laderampe Aktuell:
![Freiraum1](https://github.com/eiksch/statev_v3_issues/assets/61833414/32cd12a0-e171-4469-9cbc-20043861a902)

evtl neuer platz für Laderampe:
![freiraum2](https://github.com/eiksch/statev_v3_issues/assets/61833414/e76acf50-521f-461c-9a6d-a89d3e260c25)

**Comment by TheOutburst** [comment]
1. Was sich ändern muss und was nicht ist glaube ich nicht dein Kompetenzbereich
Aber ich hab ma next update was für euch drin

**Comment by VeAderian** [comment]
ja sorry, war evtl falsch ausgedrückt, es war allerdings wirklich wichtig, weil eventuelle Kunden dann einfach wieder abgehauen sind, da sie nicht dran gedacht haben sich mal auf die laderampe vom kleiderladen zu stellen.
