### ISSUE TITLE
Nase buggt bei Sturmmaske nach dem Hotfix vom 21.11. gegen Mittag plötzlich durch. 

### ISSUE THREAD

**Issue by 3xcu** [mexyn/statev_v2_issues#326]
Vor dem Patch vom 21.11. gab es bei der Sturmmaske V2 keine Probleme. Seit dem Patch, wo der Bug dass Haut durch Masken durchschaut, gefixt wurde, buggt die Nase plötzlich bei der Sturmmaske V2 durch.

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/327

**Comment by Chrinis007** [comment]
Solved?
