### ISSUE TITLE
Abladepunkt versetzen

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#3260]
Hash pf_MurrietaHights_11
Abladepunkt ist zwischen Hydrant und Laterne. 

Bitte so platzieren, dass der besser nutzbar ist. 

![image](https://github.com/eiksch/statev_v3_issues/assets/16436981/b29baabc-6994-4288-910e-2a45bdffa454)

**Comment by TheOutburst** [comment]
wurd vmtl wegen der Haupstraße gemacht, ist next update auf der Nebenstraße 👌
