### ISSUE TITLE
Werkstatt stuck nachdem kein Unterschriften Fenster auftaucht

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#3261]
Beim Selbstausstellen von Rechnungen kommt es hin und wieder zu Problemen, dass kein Unterschriften Fenster auftaucht. 
Problem tritt selten auf, aber mindestens so 3-4x die Woche. 
Die Werkstatt ist dann "stuck" und nur durch reloggen wieder benutzbar.

Wirklich erklären kann ich nicht was den Fehler hervorbringt.

**Comment by simplycach** [comment]
Selber Issue https://github.com/eiksch/statev_v3_issues/issues/3264
