### ISSUE TITLE
Abladepunkt  und  Spwanpunkt versetzten 

### ISSUE THREAD

**Issue by shanel1** [mexyn/statev_v2_issues#3262]
Hallöchen, 

Sophia Delacruz
Es geht um diese Firma:

![2f13ceee5a9dd00b85e8fbae706e86ac](https://github.com/eiksch/statev_v3_issues/assets/75669713/772dbbff-2758-4a08-ba14-0431def2c977)

Könntet ihr die Koordinaten ändern wenn man aus der Firma kommt, man landet jedesmal im Müllsack :D 

![image](https://github.com/eiksch/statev_v3_issues/assets/75669713/40ffff7f-ce95-4ac9-8b63-251a4971e0f8)

Und der Abladepunkt ist nicht sehr vorteilhaft. Mit grösseren Autos steht man halb auf der Straße.

![Unbenannt](https://github.com/eiksch/statev_v3_issues/assets/75669713/82aa05a5-7829-4045-8b91-7c59f10cdf82)

Hier würde es besser passen und stört niemanden :) 

![2](https://github.com/eiksch/statev_v3_issues/assets/75669713/577826eb-da7e-445f-975d-a203a8911029)

Liebe Grüße

Shanel

**Comment by TheOutburst** [comment]
next update drin 👌
