### ISSUE TITLE
Casino Bug

### ISSUE THREAD

**Issue by ThianaLyon** [mexyn/statev_v2_issues#3263]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Thiana Lyon

01.04.2024 um 04:55

Sobald man sich an den Tisch bei der Dame im schwarzen Raum setzte ( Beim reinkommen in die Blackjack abteilung Links) konnte man Jetons setzen aber weiter Aktionen gingen nicht mehr nach dem setzen zb  Halten oder Karte ziehen, Aufstehen. Nach Relog waren auch die Jetons weg. 

**Erwartetes Verhalten**

Am besten an den Tisch setzen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

https://prnt.sc/xEzUpDNFiQpH

**Comment by simplycach** [comment]
Wurde bereits gemeldet.
