### ISSUE TITLE
Werkstatt %-Balken nach Bezahlung nicht angezeigt und Fahrzeug gesperrt (DC-Ticket support-3717)

### ISSUE THREAD

**Issue by QA-Pregon** [mexyn/statev_v2_issues#3264]
David Danilov

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.04.2024 Ca. 13:51

**Beobachtetes Verhalten**
Nach Planung des Fahrzeuges wurde die Rechnung ausgestellt und bezahlt.
Die Bezahlbestätigung habe ich bekommen und wollte kurz danach mit dem Tuning starten, habe dann aber festgestellt, dass der Tuningbalken nicht vorhanden ist (Oben der %-Balken).
Zuvor hat es an exakt dem Auto noch ohne Probleme funktioniert.
Das Fahrzeug ist seit Rechnungsbegleichung auch gesperrt
--> Video im Anhang

**Erwartetes Verhalten**
Tuningbalken startet wie immer

**Schritte um den Fehler nachvollziehen zu können**
Idk, für mich eher random

https://github.com/eiksch/statev_v3_issues/assets/75855042/876bb290-050b-4ab5-9af8-0922056dbf59

![Screenshot 2024-04-02 140301](https://github.com/eiksch/statev_v3_issues/assets/75855042/e7d146eb-478c-44c3-ae06-a8435c31f2a7)

**Comment by QA-Pregon** [comment]
Ergänzung:
Fahrzeug hat sich nach relog nach einer Stunde auch nicht fertiggstellt
Teile aus dem Lager wurden verbraucht und auch nach ein und ausparken war das Fahrzeug nicht fertig.
Verbaute Teile am youga classic:
Auspuff
Windschutzscheibe Blende
Innenausstattung
Tür Verkleidung
Lenkrad
Kofferraum
Dachhutze
Tank-Design
Fenster Verkleidung
Scheibentönung

**Comment by QA-Pregon** [comment]
Nächste Ergänzung:
Bei einem anderen youga classic hab ich einzeln alles davon getunt und noch mehr sogar und das lief

Meine Vermutung also, es war zu viel auf einmal.
Hätte ja eigentlich trotzdem klappen sollen

**Comment by QA-Pregon** [comment]
Another Ergänzung:
Exakt Gleiches Fahrzeug bei dem der Bug aufgetreten ist konnte durch Schritt für Schritt mit dem gleichen Tuning fertiggestellt werden. Problem liegt also 100%ig an 10 Sachen auf einmal.

Für Broady noch die einzelnen Tunings:
Auspuff - Doppelauspuff mit Seitenausl.
Windschutzscheibe Blende - Polsterbett mit Leopardenmuster
Innenausstattung / Armaturenbrett - Cockpit mit Leopardenmuster
Tür Verkleidung - Leopardendekor
Lenkrad - Zwo Retro
Kofferraum - Klass. Profi-Boxensystem
Dachhutze / Außen Design - Doppeldachhupe
Tank-Design - Safari-Dachkorb
Fenster/Tür Verkleidung - Chrom- Sichtlinienspiegel
Scheibentönung - Pure Black

**Comment by epichalt** [comment]
@Pregon 

Nein, wie aus anderen Ticktes ersichtlich war dies auch der Fall bei Einzeltunings.

**Comment by QA-Pregon** [comment]
Nicht reproduzierbar, bzw sporadischer Auftritt
