### ISSUE TITLE
Bug mit Kleidung (Schwarzes Sakko mit schwarzen Akzenten in Kombination)

### ISSUE THREAD

**Issue by MrBastiB** [mexyn/statev_v2_issues#3265]
Das Schwarzes Sakko mit schwarzen Akzenten in Kombination mit Hemden funktioniert nicht.Trotz diverser Kombinationen des Stiles,Bugt das Unterhemd immer wieder durch das Sakko.

**Comment by MrBastiB** [comment]
Als Grafische Hilfestellung :

https://gyazo.com/ea32085931ae5b57892dc41e989b0006

**Comment by SHaagmann** [comment]
Gibt Oberteile die dafür passen bei den Hemden so weit ich weiß
