### ISSUE TITLE
Option "Sitzen (Becher trinken)", "Sitzen (Bier trinken)" und "Sitzen (Donut essen)" funktioniert bei Sofas nicht richtig

### ISSUE THREAD

**Issue by WalDragoner3425** [mexyn/statev_v2_issues#3266]
Wenn ich mich auf ein Sofa mit z.B. der Animation "Sitzen (Donut essen)" setzen will, bekommt man andauernd eine Fehlermeldung und es heißt, einem Fehlen Gegenstände (obwohl man ein richtiges davon dabei hat), bis irgendwann dann mal zufällig das richtige Item ausgewählt wird und man sich dann doch hinsetzen kann.

https://github.com/eiksch/statev_v3_issues/assets/56478386/d736ea44-9ac1-4e71-bd70-a5a850932ade

**Comment by SatyriaDine** [comment]
Am besten vorher immer einmal kurz das Inventar auf und wieder zu machen.  Dann funktioniert es. :)
