### ISSUE TITLE
Hotel kann keine Werbung schalten

### ISSUE THREAD

**Issue by LeVamis** [mexyn/statev_v2_issues#3267]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Jordan_Musiala

permanent, aber erneut getestet um 23:15 am 2. April 2024

Hotel Werbung kann nicht erstellt werden "Deine Fabrik ist nicht valide!", obwohl genug Geld auf dem Konto ist (gestern wurde das Hotel gekauft, aber seitdem gab es auch schon einen Restart)

**Erwartetes Verhalten**
Werbung sollte geschaltet werden, da alle Faktoren wie Geld etc da sind.

**Schritte um den Fehler nachvollziehen zu können**
Werbung schalten als Hotelbesitzer

https://github.com/eiksch/statev_v3_issues/assets/165846622/292a669d-5b04-4e8d-91a0-f27c52eaf676

**Comment by rodistic** [comment]
Um welchen Hotel Hash handelt es sich? 

Factorys > Dein Hotel > Details > Hash

**Comment by LeVamis** [comment]
PillboxHill_Flat_11

**Comment by SatyriaDine** [comment]
Next Update fixed
