### ISSUE TITLE
Leasing Kündigung erkennt Kilometerstand falsch

### ISSUE THREAD

**Issue by QA-Pregon** [mexyn/statev_v2_issues#3269]
**Character Name**
David Danilov

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Wahrscheinlich schon immer 
(03.04.2024)

**Beobachtetes Verhalten**
Bei der Vertragskündigung von Leasingfahrzeugen wird der Kilometerstand nicht korrekt angezeigt.

**Erwartetes Verhalten**
Kilometerstand wird korrekt angezeigt

**Schritte um den Fehler nachvollziehen zu können**
Auto leasen --> fahren --> bei der Leasing Kündigung reingucken
![image](https://github.com/eiksch/statev_v3_issues/assets/75855042/7fe48bb0-c724-4e2c-a627-dde01d4d02f8)
![image](https://github.com/eiksch/statev_v3_issues/assets/75855042/37f5f6bf-842a-4c6b-9f74-f85bdf8b2126)

**Comment by simplycach** [comment]
Also ich konnte mein Fahrzeug neulich ohne Probleme abgeben. Konntest du es abgeben ?

**Comment by QA-Pregon** [comment]
Ich wollte es gar nicht abgeben, wollte nur drauf hinweisen, dass beim Leasing 0,1km steht obwohl ich schon 140km gefahren bin ^^

**Comment by simplycach** [comment]
Schau ich mir nochmal an.

**Comment by simplycach** [comment]
Scheinbar Einzelfall
