### ISSUE TITLE
Katalog NPC fehlt im Kleiderladen

### ISSUE THREAD

**Issue by SheoBam** [mexyn/statev_v2_issues#3270]
Der Kleiderladen mit dem Hash "DiscountStore3" hat keinen Katalog-NPC.

**Comment by simplycach** [comment]
Ist Normal, wenn der Laden noch keinem gehört z.B

**Comment by SheoBam** [comment]
Meinem Charakter Sarah_Sommerfeldt gehört dieser Kleiderladen aber. @simplycach

**Comment by simplycach** [comment]
Ich schau mir das mal an, aber hast du die Firma auch richtig eingerichtet ?

**Comment by simplycach** [comment]
Schick auch gern mal einen Screenshot rein

**Comment by SheoBam** [comment]
![1](https://github.com/eiksch/statev_v3_issues/assets/95241865/22ac5729-b174-4a12-84aa-aee71cb22c48)
![2](https://github.com/eiksch/statev_v3_issues/assets/95241865/4f09f408-ed87-4669-8bd8-4cbf82411c35)
![3](https://github.com/eiksch/statev_v3_issues/assets/95241865/c1b6567c-38a8-47d2-8ed4-255500a71117)

glaube eher nicht das der Fehler bei mir liegt. Wüsste nicht was ich noch einstellen kann damit der NPC an seinem Platz erscheint

**Comment by simplycach** [comment]
Hast du seit dem mal das Spiel neu gestartet ?

**Comment by simplycach** [comment]
Sonst kann es auch sein, dass er erst mit dem nächsten Restart da ist, wenn du den Laden grad gekauft haben solltest.

**Comment by SheoBam** [comment]
Den Laden besitzt mein Charakter schon seit mehreren Wochen. Demnach gab es schon etliche Neustarts meinerseits und auch vom Server :) Da die Kleidungsläden seit V3 Start nicht bespielbar waren, ist mir der fehlende NPC auch erst jetzt aufgefallen.

**Comment by simplycach** [comment]
Ich leite das mal weiter.

**Comment by simplycach** [comment]
@TheOutburst guckst du mal bitte

**Comment by TheOutburst** [comment]
whoops, fixed next update
