### ISSUE TITLE
%-Balken fehlt beim abschleppen nach Revive (durch Teammitglied)

### ISSUE THREAD

**Issue by QA-Pregon** [mexyn/statev_v2_issues#3271]
**Character Name**
David Danilov

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.04.2024, Ca. 14:20

**Beobachtetes Verhalten**
Nach einer Bewusstlosigkeit und dem Revive durch ein Teammitglied kam es dazu, dass beim Abschleppen der %-Balken sowohl beim aufladen, als auch beim abladen gefehlt hat.

**Erwartetes Verhalten**
Der %-Balken sollte immer da sein.

**Schritte um den Fehler nachvollziehen zu können**
Bewusstlos werden und reviven lassen
Dann abschleppen
Wenn das aufhelfen durch Medic nicht den Bug auslöst, dann durch Command reviven.

Keine Ahnung ob da nen Video was bringt weil es eh nur zeigen würde, dass der Prozentbalken fehlt aber das abschleppen trotzdem läuft

**Comment by simplycach** [comment]
Also ist der Fehler nur aufgetreten nachdem du von einem Team-Mitglied revived wurdest, denke mal ein Neustart hätte diesen Fehler sicherlich behoben.
