### ISSUE TITLE
Kondensmilch kann nicht produziert werden

### ISSUE THREAD

**Issue by LeaBrandt** [mexyn/statev_v2_issues#3272]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Ronja Brandtberg

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.04.2024 15:20 Uhr (auch Tag davor mehrmals getestet) 

**Beobachtetes Verhalten**
Sobald ich versuche Kondensmilch in der Verpackung zu produzieren, wird angezeigt "Fehler in der Konfiguration der Produktion!" und es kann nicht produziert werden. 

**Erwartetes Verhalten**
Kondensmilch wird produziert. 

**Schritte um den Fehler nachvollziehen zu können**
In der Verpackung Kondensmilch produzieren. 

**Optional: Video / Bilder des Fehlers**

![Fehler Kondensmilch](https://github.com/eiksch/statev_v3_issues/assets/98689462/fffad55e-5dbc-4c71-9ee7-7374e452e05f)

**Comment by Erumeldor** [comment]
Fixed im nächsten Update :)
