### ISSUE TITLE
Geblitzt obwohl Kennzeichen Abgeklebt

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3273]
Character Name
Samuel Navarro

Auftrittszeitpunkt (Datum / Uhrzeit)

03.04 ca 17 Uhr
Beobachtetes Verhalten
Kennzeichen abgeklebt und dennoch geblitzt worden

Erwartetes Verhalten
Keine Tickets über den Zeitraum wo das Kennzeichen abgeklebt wurde.

Schritte um den Fehler nachvollziehen zu können
Passendes Item verwenden und mit 220 Sachen durch den Blitzer fahren. 
Überrascht sein, dass man geblitzt wurde

Optional: Video / Bilder des Fehlers
![image](https://github.com/eiksch/statev_v3_issues/assets/58612983/959a251d-c8af-44bb-96cd-feced5b90f9e)

**Comment by simplycach** [comment]
Next Update fixed.
