### ISSUE TITLE
Koffer und Aktenkoffer

### ISSUE THREAD

**Issue by Auralein** [mexyn/statev_v2_issues#3274]
**Character Name**
Holly Swan

Keine Ahnung wie lange das schon existiert.

**Beobachtetes Verhalten**
Beide Items werden beim Anlegen NICHT sichtbar. Allerdings hat man den typischen Rucksack Slot dann mit seinen 15kg

**Erwartetes Verhalten**
Anlegen der Koffer verschafft ein visuelles Bild von Koffern/Aktenkoffern

**Schritte um den Fehler nachvollziehen zu können**
Koffer in den Rucksack Slot ziehen

![grafik](https://github.com/eiksch/statev_v3_issues/assets/76708950/664dc6cf-1a38-4f8c-8bd1-3c3bda28d0f0)

**Comment by simplycach** [comment]
Bereits bekannt, sind dran. @TheOutburst ist das was für euch ?

**Comment by TheOutburst** [comment]
woraround ist next update drin
