### ISSUE TITLE
Abladepunkt versetzen

### ISSUE THREAD

**Issue by Snipser92** [mexyn/statev_v2_issues#3275]
Hallo,

wäre es möglich den Abladepunkt um 2 meter zu versetzen? Die Fahrzeuge klemmen fest wenn man aus der Firma rauskommt und sind dann beschädigt, genau so ist das abladen mit größeren Fahrzeugen schwierig da der Punkt sehr dicht an der Wand ist.

https://pic.statev.de/image/HgFFZg
https://pic.statev.de/image/HgF7BV
https://pic.statev.de/image/HgFvvD

**Comment by Erumeldor** [comment]
Fixed im nächsten Update :)
