### ISSUE TITLE
Dauerauftrag wird nicht weiter ausgeführt

### ISSUE THREAD

**Issue by robka87owl** [mexyn/statev_v2_issues#3277]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Andreas Kowalski**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Ab 30.03.2024

**Beobachtetes Verhalten**

Seit dem 30.03.2024 wurde kein Dauerauftrag ausgeführt. Das Guthaben ist gedeckt, der Dauerauftrag besteht.

**Erwartetes Verhalten**

Ausführung des Dauerauftrages

**Schritte um den Fehler nachvollziehen zu können**

Dauerauftrag erstellt, wurde ausgeführt, seit dem 30.03.2024 aber keine weitere Ausführung.

**Optional: Video / Bilder des Fehlers**

![dauerauftrag](https://github.com/eiksch/statev_v3_issues/assets/140908156/e7b3b092-9dc2-45d3-a84d-71387f3f75c0)
![dauerauftrag_01](https://github.com/eiksch/statev_v3_issues/assets/140908156/0a58b9c3-c338-4f0d-ad7e-560ede7b8342)

**Comment by simplycach** [comment]
Hinterleg dich mal bitte nochmal neu.

**Comment by robka87owl** [comment]
Moin, mach ich nochmal. Hatte das Problem ja schon einmal.

**Comment by simplycach** [comment]
Wenn es nochmal aufkommt gerne bescheid geben.
