### ISSUE TITLE
Tanksäulen-Anzeige während der fahrt

### ISSUE THREAD

**Issue by xTheDukeMiX** [mexyn/statev_v2_issues#3278]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Jamal Knox**

**Auftrittszeitpunkt (04.04.2024 / 02:35 Uhr)**

**Ich wollte mit meinem Pickup an der Tankstelle des Flugplatzes tanken, jedoch hatte dieser kein Kraftstoff, deswegen konnte nicht getankt werden. Also fuhr ich mit meinem Pickup weiter, jedoch abseits der festen Straßen, als plötzlich mitten auf einem Stichweg die Anzeige mit der Tanksäule kam. Diese verschwand wenn ich den Stichweg verlassen habe. Der Fehler konnte nach beenden des Spiels nochmal reproduziert werden**

**Es erscheint keine Tanksäule wenn ich nicht an einer Tankstelle stehe.**

**Mit einem Fahrzeug (evtl. den Bison) die unbefestige Straße entlang fahren.**

**Screenshot des Straßenabschnittes**
![Grand Theft Auto V Screenshot 2024 04 04 - 02 36 42 16](https://github.com/eiksch/statev_v3_issues/assets/165970133/e03d596b-57cf-461a-b69a-61d33f596799)

**Comment by xTheDukeMiX** [comment]
Uploading grand-theft-auto-v-20240404-02324602_CL8rc1On.mp4…

**Comment by xTheDukeMiX** [comment]
https://github.com/eiksch/statev_v3_issues/assets/165970133/b2bb9d34-4855-4c6a-92a9-01576094e79f

**Comment by l4m4rr224** [comment]
Next Update fixed
