### ISSUE TITLE
Kategorien bei Youga Classic Tuning komisch sortiert

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#3279]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
James Carter & David Danilov

**Beobachtetes Verhalten**
Ich hab mir von David erklären lassen, was falsch ist und da flott einen Test auf dem Dev Server gemacht.
Im Tuning ist für den Youga Classic was blöd eingeordnet:

Spoiler: OK
V. Stoßstange: OK
H. Stoßstange: OK
Seitenschweller: OK
Auspuff: OK
Rahmen Extras: OK
Frontgrill: OK
Motorhaube: OK
Kotflügel: Ändert die Sonnenblende
Dach: OK
Windschutzscheibe Blende: Verbraucht Scheibentönung und ändert Innenraum
Innenausstattung/Armaturenbrett: OK
Türverkleidung: OK
Sitze: OK
Lenkrad: OK
Kofferraum: OK
Motorraum: Hier verändert sich die Front Schürze etwas. maybe passt das besser bei Kotflügel
Scheinwerfer: Ändert Kuhfänger, passt aber grob.
Sonstige Extras: OK
Dachhutze/Außen Design: OK
Tank Design: Packt Träger aufs Dach.
Fenster/Tür Verkleidung: OK
Spezial Aufkleber: OK
Xenon-Scheinwerfer: OK

**Erwartetes Verhalten**
Die Tunings sprechenderen und besser passenden Kategorien zuordnen lassen.

**Schritte um den Fehler nachvollziehen zu können**
Youga Classic Tunen und sich die Kategorien anschauen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Erumeldor** [comment]
Hey, können wir leider nichts dran ändern.
Das liegt daran, das GTA diese Tunings falsch "zugeordnet" hat, wir übernehmen das bei uns für jedes Fahrzeug von GTA.
