### ISSUE TITLE
Overlay # nicht mehr ausschaltbar

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#328]
**Character Name**
Jannik_Datsch

**Zeitpunkt (Datum / Uhrzeit)**
21.11 18:00

**Beobachtetes Verhalten**
Das Overlay lässt sich nicht mehr mit "#" ausschalten 

**Erwartetes Verhalten**
Man sollte es ausschalten können, auch da es einige FPS frisst

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by JulianMa** [comment]
fixed
