### ISSUE TITLE
Penny geht nicht in Portemonnaie

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3281]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

05.04 10:50
**Beobachtetes Verhalten**

Das item "Penny" kann man nicht ins Portemonnaie packen, obwohl es ja kleingeld ist
**Erwartetes Verhalten**

Sollte reingehen
**Schritte um den Fehler nachvollziehen zu können**

1. Penny für 5$ Kaufen (Glaube wurde abgezogen)
2. Penny versuchen ins Portemonnaie zu packen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://medal.tv/de/games/gta-v/clips/25qmw3ygv3pKQe/d1337Xm9h8gP?invite=cr-MSxKa2YsMTk1NTEzMTMzLA

**Comment by Erumeldor** [comment]
Ist fixed mit dem nächsten Update :)
