### ISSUE TITLE
Pflanzen lassen sich nicht abbauen

### ISSUE THREAD

**Issue by WalDragoner3425** [mexyn/statev_v2_issues#3282]
Kann meine Drogen Pflanzen nicht abbauen (und auch keine neuren anpflanzen), Support meinte ich soll hier nen Beitrag aufmachen.
Charakter: Kane_Brooks

Vorschlag um sowas zukünftig zu vermeiden:
Vertrocknete Pflanzen werden nach 24h automatisch gelöscht/entfernt.

**Comment by simplycach** [comment]
Was hast du genau angebaut ?

**Comment by TheOutburst** [comment]
Die Pflanzen porten sich auf Z 0, daher kann man die nicht abbauen
Ich meine bei dir hatten wir die entfernt
