### ISSUE TITLE
Friseurladen

### ISSUE THREAD

**Issue by EnissaFellar** [mexyn/statev_v2_issues#3283]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Enissa_Fellar**

Enissa_Fellar
**Auftrittszeitpunkt (Datum / Uhrzeit)**

6.4.2024 um 2:40 Uhr
**Beobachtetes Verhalten**

Der Kunde hatte sich auf den Stuhl gesetzt, ich habe ihm dort Haare und Bart gemacht, als ich dann die Rechnung austellen wollte, wurde mir eine Fehlermeldung angezeigt das Rasiermesser fehlen. ( ich habe aber noch 20 stück im Lager) (Die Frisur und der Bart verlangen vom Item bedarf 2 Rasiermesser).
**Erwartetes Verhalten**

Es sollte eigendlich einwandfrei Funktionieren da ich Alle objekte die ich fürs haare schneiden benötige in meinem Lager habe und diese auch ausgepackt sind.
**Schritte um den Fehler nachvollziehen zu können**

Es muss sich jemand auf den stuhl setzen, ein anderer muss dem kunden auf dem stuhl bart und haare  neu auswählen und dann den preis unten eingeben und auf bestädigen sodas der kunde die rechnung erhalten sollte. allerdings bricht es beim bestädigen ab und man wird benachrichtigt das man keine Rasiermesser mehr hat.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Xymena** [comment]
Alice_Swan

**Auftrittszeitpunkt (Datum / Uhrzeit)**

7.4.2024 um 2:23 Uhr
**Beobachtetes Verhalten**

Der Kunde Tia_Stone hatte sich auf den Stuhl gesetzt, ich habe ihr die haare gemacht es kamm die fehler meldung nicht genügend Rassiermesser

(Aufällig war das  Struthioo Aftershave benötigt wurde was bisher meiner meinung nicht der fall ist)

**Erwartetes Verhalten**

Es sollte eigendlich einwandfrei Funktionieren da alle Obejte die benötigt sind im Lager sind. Es sind etwa 36 Acc3zZ Rasiermesser im Lager

Schritte um den Fehler nachvollziehen zu können
Es hat sich jeemand auf den Stuhl gesetzt, und die Frisur wurde gewählt. Nach dem Kassieren kamm die fehlermeldung "Es fehlen folgende Gegenstände: Acc3zZ Rasiermesser


Monitorauflösung (nur wenn Falsche Darstellung in der UI)

Optional: Video / Bilder des Fehlers
![Screenshot 2024-04-07 022616](https://github.com/eiksch/statev_v3_issues/assets/76626768/2ada6074-efd4-457d-a1d8-f232faaf3b59)
![image](https://github.com/eiksch/statev_v3_issues/assets/76626768/e6459990-9b06-400c-905d-faa3dfcabf31)
