### ISSUE TITLE
Tattoos im falschen Pfad

### ISSUE THREAD

**Issue by Oguzhan57x** [mexyn/statev_v2_issues#3284]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Jamiro Ortiz**

**07.04.24 22:55**

**Tattoos aus dem Rückenbereich sind in falschen Kategorien**

**Die sollen in die richtige Kategorie**

**Im Tattooladen nach den Tattoos gucken (Bilder beigefügt)**

**https://pic.statev.de/image/HgYsQw
https://pic.statev.de/image/HgYmgV
https://pic.statev.de/image/HgYi5D
https://pic.statev.de/image/HgYFGz
https://pic.statev.de/image/HgY7XY
https://pic.statev.de/image/HgYrrg
https://pic.statev.de/image/HgY21S**

**Comment by simplycach** [comment]
Next Update fixed

**Comment by Shazgul** [comment]
Problem besteht weiterhin.
