### ISSUE TITLE
Erw. Magazin 9x19mm H&L 92fs lässt sich nicht in die Waffe H&L 92fs laden. 

### ISSUE THREAD

**Issue by AideenCarter** [mexyn/statev_v2_issues#3285]
Erw. Magazin 9x19mm H&L 92fs lässt sich nicht in die Waffe H&L 92fs laden.

**Comment by DrGrizzlY17** [comment]
Ist kein Fehler. Dir fehlt nur was :)

**Comment by AideenCarter** [comment]
Magazin Erweiterung kann ich in der Waffenfertigung nicht herstellen. Ist die Legale Waffe für Attachements also ans Crime gebunden ?

**Comment by DrGrizzlY17** [comment]
Aktuell sind Attachments noch nicht implementiert und auch noch nicht geplant. Time will tell wie wir es machen :)

**Comment by AideenCarter** [comment]
Dann nehmt doch die erweiterten Magazine aus der Herstellung damit nicht noch jemand 10.000$ darin versenkt :)

**Comment by DrGrizzlY17** [comment]
Na dann hat jemand Vorrat wenn sie kommen :D
