### ISSUE TITLE
Neue Häuser für Vespucci

### ISSUE THREAD

**Issue by officialschnoopie** [mexyn/statev_v2_issues#3286]
Hey, ich sollte mich bezüglich der Häuser für Vespucci nochmal hier melden. Wir würden gerne ein paar Häuser bei uns in der Nähe haben, welche auch Garagen besitzen. Allgemein in Vespucci gib es wenig Häuser.

Bitte nicht so teuer, bin immer arme Mann :(

**Character Name**
Jayden_Oneto

**Erwartetes Verhalten**
Mehr Häuser für Vespucci

**Optional: Video / Bilder des Fehlers**
![Screenshot_2024-04-05_185617](https://github.com/eiksch/statev_v3_issues/assets/166428726/cb2766fe-f577-45e7-a13d-bb4756441ee6)
![Screenshot_2024-04-05_185609](https://github.com/eiksch/statev_v3_issues/assets/166428726/00ae0656-b99e-49be-9faf-f92169f2493e)
![Screenshot_2024-04-05_185454](https://github.com/eiksch/statev_v3_issues/assets/166428726/20acb09c-1a6d-41f3-bc7d-95fba2fd643c)

![Screenshot_2024-04-05_185443](https://github.com/eiksch/statev_v3_issues/assets/166428726/dc16af44-e0de-4f73-b909-2cf408a4af01)
![Screenshot 2024-04-08 190547](https://github.com/eiksch/statev_v3_issues/assets/166428726/56d7c0a1-c115-4807-8000-299d5d7a222b)
![Screenshot 2024-04-08 190552](https://github.com/eiksch/statev_v3_issues/assets/166428726/4d2c8161-dc8f-41a8-b636-5c7b9914547d)

**Comment by stepz2k9** [comment]
Wäre in dem Zuge auch cool, wenn am Westhighway bei der Einfahrt zur Stadt wieder paar mehr Häuser kaufbar wären.
Sind aktuell nur noch 5 oder so. :/
Ganz Vespucci war ja früher kaufbar. Das wurde ja iwann mal rausgenommen, weil zu viele Einzelpersonen zu viele Häuser hatten, aber da sich das ja jetzt durch die Beschränkung auf 2 pro Person geändert hat, wäre voll cool, wenn man mehr Häuser (bezogen auf die Menge der vorhandenen Häuser) erstehen könnte. :)

**Comment by TheOutburst** [comment]
Das bei 5028 ist eher nen Apartmentkomplex als nen Haus, das bleibt vorerst ohne Funktion

Aber next update kommt mal ein Schwung neuer Häuser in Del Perro & Vespucci rein, und dann in paar Monaten nochmal nen Schwung 👌
