### ISSUE TITLE
Entfernung von beiden Stuhl&Tisch Sets & einem Grill

### ISSUE THREAD

**Issue by officialschnoopie** [mexyn/statev_v2_issues#3287]
Hellooo, 
ich wollte ma nett nachfragen ob ihr uns diese Tische, Stühle und den einen Grill entfernen könntet, damit wir uns was eigenes dahinbasteln können. 

LG
Euer Schnoopie

**Character Name**
Jayden_Oneto

**Optional: Video / Bilder des Fehlers**
![Bild_2024-04-08_194148944](https://github.com/eiksch/statev_v3_issues/assets/166428726/30f5ad1c-f467-4827-8cc7-ea02ca212411)
![Bild_2024-04-08_194317024](https://github.com/eiksch/statev_v3_issues/assets/166428726/e2854365-1308-4b0e-b108-283e56ebce69)

**Comment by TheOutburst** [comment]
Tachchen, A machen wir das eigentlich nichtmehr, B geht das nicht, weil die Sachen entweder beweglich und/oder mit Y Interagierbar sind
