### ISSUE TITLE
Piercings

### ISSUE THREAD

**Issue by ViviLila** [mexyn/statev_v2_issues#3288]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
Ich habe mir ein Septum stechen lassen und als die Bauchnabelpiercings gekommen sind auch das. Nun ist das Septum verschwunden respektiv weg. Soll das so?

**Erwartetes Verhalten**
Das man beides tragen kann.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Hey, leider ist es nicht mehr möglich, dass man beide Piercings haben kann, man kann nur noch 1 Piercing haben: Sprich Nasen Piercing oder Bauchnabel.
