### ISSUE TITLE
Auto Verbugt nach tuning 

### ISSUE THREAD

**Issue by Drag0nda** [mexyn/statev_v2_issues#3289]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Sam Oconner**

**Auftrittszeitpunkt (08.04.2024/ 18:22)**

**Beobachtetes Verhalten**
 Mein Auto ist in die Luft gebugt
**Erwartetes Verhalten**
 Nicht so wie im Clip

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
 https://medal.tv/games/gta-v/clips/269fZB0hZ_Fw3F/d1337uGeQdND?invite=cr-MSxyazIsMTI0MzY4MDc3LA

**Comment by Erumeldor** [comment]
Duplicate:
https://github.com/eiksch/statev_v3_issues/issues/3135
