### ISSUE TITLE
Klamottenladen

### ISSUE THREAD

**Issue by julieed2** [mexyn/statev_v2_issues#3290]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Giulia Marino**

**Beim letzten Update wurden für die Klamottenläden neue Kleidungsstücke eingefügt, diese kann man zwar produzieren aber nicht verkaufen. (Schnittform Barbee Dress, Buttoned Sweater) -> Cable Knit Sweater wurde auch bei dem Update hinzugefügt kann sein das dort auch das Problem besteht, aber den haben wir noch nicht produziert.

2te Problem: Bei der Produktion von Basic Poloshirts steht bei Orange Stoff 0 und dieses kann man nicht produzieren.**

**Dass der Verkauf funtioniert.
Dass die Basic Poloshirts produziert werden können.**

**Comment by simplycach** [comment]
Ist der Fehler noch da ?
