### ISSUE TITLE
Wasserflasche dupliziert

### ISSUE THREAD

**Issue by UNST4BL3** [mexyn/statev_v2_issues#3294]
**Character Name**
Markus_Ackermann

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11.04.2024 13:50 Uhr

**Beobachtetes Verhalten**
Ich hatte eine Wasserflasche im Inventar meines Fahrzeugs. Diese habe ich getrunken als ich am Firmengebäude über "Lager" auf das Inventar des Fahrzeugs zugegriffen habe. Dabei bekam ich unten Links eine Fehlermeldung und danach hatte ich eine Wasserflasche und eine leere Plastikflasche im Inventar des Fahrzeugs und meine Durst-Anzeige wurde auch aufgefüllt.

**Erwartetes Verhalten**
Wasserflasche wird normal Verbraucht

**Schritte um den Fehler nachvollziehen zu können**
Wurde nicht getestet

**Optional: Video / Bilder des Fehlers**
[![Video](https://img.youtube.com/vi/yCOQfXqPgoE/maxresdefault.jpg)](https://www.youtube.com/watch?v=yCOQfXqPgoE)

**Comment by simplycach** [comment]
Lässt sich leider so nicht bestätigen.

**Comment by simplycach** [comment]
Lässt sich leider so nicht bestätigen.
