### ISSUE TITLE
Tuning PC Unbrauchbar nachdem kein Unterschriften Fenster auftauchte

### ISSUE THREAD

**Issue by LottiFoxy** [mexyn/statev_v2_issues#3295]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Caroline Hovenkoven

11.04.2024 ab 16:18Uhr

Großes Tuning sollte in einzelnen Schritten erledigt werden um Fehler zu vermeiden.
Hab das erste Tuning normal durchlaufen lassen können (Fentser Folierung), wollte danach die Xenons einzeln verbauen und habe mich selber im Tuning PC Erfasst und mit 1$ abrechnen wollen. Konnte auch auf Tuning klicken, bekam aber kein Unterschriften Fenster, es ist auch keine Transaktion von meinem Konto abgegangen, es wurden 2x Xenons aus dem BENNYS Lager verbraucht und der Tuning PC war belegt sowie kein Fortschrittsbalken bei mir. Auch nach ca 20min war der entsprechende Tuning PC noch "in Verwendung!
Der PC wurde erst wieder frei nachdem Ich mich ausgeloggt habe und ein anderer Spieler dann drauf zu greifen konnte!

Das Tuning musste dann vom anderen Spieler erneut gemacht werden, da nichts am Auto verbaut worden war.

Bei Selbstausgestellter Rechnung -> Unterschriften Fenster -> Normales Tuning ohne das der Tuning PC freezt

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by LottiFoxy** [comment]
Korrektur, Es wurden keine Teile verbraucht aus dem Lager. Aber der PC war eben "stuck" nachdem kein Unterschriftenfeld aufgetaucht ist.

**Comment by simplycach** [comment]
Ein relog konnte das auch nicht fixen ?

**Comment by LottiFoxy** [comment]
Doch Relogg hat den PC wieder freigegeben und jem anderes konnte diesen dann wieder nutzen

**Comment by simplycach** [comment]
Dann würde ich das ganze mal schließen, wenn sich dadurch der Fehler beheben lässt und nichts verbraucht wurde.
