### ISSUE TITLE
Versetzung Ladepunkt

### ISSUE THREAD

**Issue by BobbyCarsten** [mexyn/statev_v2_issues#3296]
Ich bitte um die Versetzung des Ladepunktes, da man dort mit einer Tankachse nicht vernünftig drauf kommt ohne irgendwo anzuecken, da sie zu nah an dem Gebäude ist. Deshalb bitte um Versetzung des Ladepunktes und wenn möglich Entfernen des Zaunstücks.

Name Bobic_Madujew

![Unbenannt564545](https://github.com/eiksch/statev_v3_issues/assets/163411566/8e3eef21-6f4a-4db0-a4db-2306842d8cae)

Firmen Hash 
![345345345345](https://github.com/eiksch/statev_v3_issues/assets/163411566/2ba40193-9312-4468-a814-db747daede2f)

**Comment by BobbyCarsten** [comment]
also der ladepunkt ist nicht versetzt wurden ? was wurde da jetzt gefixt? (solved) ? oder kommt das erst mit nem update die tage?

**Comment by l4m4rr224** [comment]
Es kam ja auch noch kein Update...
Sry hätte ich schreiben sollen.
Fixed next update

**Comment by BobbyCarsten** [comment]
danköööö :)
