### ISSUE TITLE
Big Chicken Burger + Chicken Nuggets

### ISSUE THREAD

**Issue by Kryinous** [mexyn/statev_v2_issues#3298]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Miguel Juarez
Firma: Burger Shot

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Die ganze Zeit

**Beobachtetes Verhalten**
Chicken nuggets und Big Chicken Burger
Nicht herstellbar - aber aufgelistet ist es

**Erwartetes Verhalten**
Sollte produzierbar sein

**Schritte um den Fehler nachvollziehen zu können**
nicht herstellbar

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
-

**Optional: Video / Bilder des Fehlers**

**Comment by TheOutburst** [comment]
Aufgelistet im Preiskalkulator?
Das ist so korrekt, in einem Burgerrestaurant kann man keine Chicken Waren herstellen

**Comment by Kryinous** [comment]
Chicken Nuggets okay aber der Big Chicken Burger sollte ja normal gehen oder nicht?
