### ISSUE TITLE
RP Items verschwinden nicht bei Nutzung von Handy

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#33]
**Zeitpunkt (Datum / Uhrzeit)**
25.08.2020 21.10 Uhr

**Beobachtetes Verhalten**
RP Prop Items verschwinden nicht bei Benutzung von Handy

**Erwartetes Verhalten**
Prop sollte verschwinden

**Schritte um den Fehler nachvollziehen zu können**
Gitarre z.B. in die Handy nehmen und dann das Handy ziehen

**Optional: Video / Bilder des Fehlers**
![285769126149ec91aedbfdafd7b85bd9](https://user-images.githubusercontent.com/70150988/91217063-381e5f00-e717-11ea-9e52-d8484d00e7e3.jpg)

**Comment by its4l3x** [comment]
Ist kein Bug an sich. Einfach gewohnt die Anim beenden, dann ist alles wieder normal.
