### ISSUE TITLE
Friseurstuhl sagt, dass das Acc3zZ Rasiermesser im Lager fehlt

### ISSUE THREAD

**Issue by EmmaSvensson** [mexyn/statev_v2_issues#330]
**Character Name**
Emma_Svensson und Emily_Lodge

**Zeitpunkt (Datum / Uhrzeit)**
21.11.20 bereits nachts um ca 3 Uhr und 17 Uhr noch mal

**Beobachtetes Verhalten**
Der Kunde setzt sich auf den Friseurstuhl und bekommt die Rechnung, beim Unterschreiben bekommen die Friseure die Meldung das das Acc3zZ Rasiermesser nicht im Lager vorhanden ist, obwohl dies in ausreichenden Mengen vorhanden ist.

**Erwartetes Verhalten**
Friseurstuhl funktioniert einwandfrei und erkennt das Material

**Schritte um den Fehler nachvollziehen zu können**
Kunde setzt sich auf den Friseurstuhl
Friseur wählt Frisur
Und startet den Vorgang 
Kunde unterschreibt
Auftrag wird abgebrochen mit der Meldung dass das Rasiermesser fehlt

**Comment by its4l3x** [comment]
Ist mit dem Fix zur Transparent vor paar Tagen fixed worden
