### ISSUE TITLE
Auszahlbetrag bei Marktverkauf stimmt nich

### ISSUE THREAD

**Issue by K0elschi** [mexyn/statev_v2_issues#3300]
**Character Name**
Timothy_Goodsen

**Auftrittszeitpunkt (Datum / Uhrzeit)**
13.04.2024 20:21:23

**Beobachtetes Verhalten**
Beim Marktverkauf an der Tür kommt ein anderer Auszahlbetrag zustande als erwartet.
Ausgezahlt/überwiesen wurden für 1300 Sack KG zu 1,40 $ 1815,45 $

**Erwartetes Verhalten**
Ausgezahlt/überwiesen werden sollten für 1300 Sack KG zu 1,40 $ 1820,-- $
Wenn 1,40 $ /St. angezeigt wird, sollte auch damit gerechnet werden und nicht mit 1,3965 $ /St. im Hintergrund, die dann zur Anzeige einfach auf 2 Stellen hinter dem Komma gerundet werden.

**Schritte um den Fehler nachvollziehen zu können**
Warenankauf an der Türe zum Stückpreis von 1,47 $ einstellen.
Ware an der Türe abliefern und nur 1,39 $ /Stück bekommen.

Mögliche Erklärung:
Beim Einstellen des Stückpreises von 1,47 $ werden automatisch 5% Steuer abgerechnet.
Angezeigt werden dann 1,40 $ /St., aber im Hintergrund wird mit 1,3965 $ /St. weitergerechnet.

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/160853816/7f7a469e-009f-4a72-adb4-55ac989908c3)
![image](https://github.com/eiksch/statev_v3_issues/assets/160853816/22babc40-6b77-4c08-9569-433cc040639a)
![image](https://github.com/eiksch/statev_v3_issues/assets/160853816/8441b2cd-4b22-47ce-b773-b2e6cab67871)

**Comment by epichalt** [comment]
Selbes Thema wie hier https://github.com/eiksch/statev_v3_issues/issues/3305

Du schreibst: 
Schritte um den Fehler nachvollziehen zu können
Warenankauf an der Türe zum Stückpreis von 1,47 $ einstellen.
Ware an der Türe abliefern und nur 1,39 $ /Stück bekommen.

Das stimmt so aber nicht. Du bekommst nicht 1.39, sondern 1,3965$ 
1.3965$ sind 1.40$ kaufmännisch gerundet. 

Du schreibst sogar die richtige Rechnung dazu, aber möchtest es trotzdem "falsch" berechnen.
