### ISSUE TITLE
Rasiermesser und Aftershave für Frauenfrisuren benötigt

### ISSUE THREAD

**Issue by stepz2k9** [mexyn/statev_v2_issues#3301]
**Character Name**
Kelani Larsson / Kiana Mckenzie

**Auftrittszeitpunkt (Datum / Uhrzeit)**
13.04. / 22:50 Uhr

**Beobachtetes Verhalten**
Beim Frisieren von Kiana wurden in der Verbrauchsliste 2 Rasiermesser und 1 Aftershave angezeigt & verbraucht.

**Erwartetes Verhalten**
Diese Items sollten nur bei Bärten verbraucht werden.

**Schritte um den Fehler nachvollziehen zu können**
Frauenfrisur auswählen (in unserem Fall Curly Curls Ombre)

**Optional: Video / Bilder des Fehlers**

![haare](https://github.com/eiksch/statev_v3_issues/assets/74977218/d9d60c5c-720b-4575-9743-b977bab2ef21)

**Comment by simplycach** [comment]
Sollte next Update fixed sein.

**Comment by simplycach** [comment]
https://github.com/eiksch/statev_v3_issues/issues/3283
