### ISSUE TITLE
Ammonation Route 15 Großer Raub nicht ausführbar

### ISSUE THREAD

**Issue by Slayraw** [mexyn/statev_v2_issues#3302]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Vitorrio_Marino**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

15.04.2024 7:50 Uhr

**Beobachtetes Verhalten**

Mitarbeiter Einstempel Punkt ist direkt auf den Sammelpunkt um das Regal zu durchsuchen ( Ammonation Großer Raub)
Anstatt Das Regal zu durchsuchen möchte sich der char einstempeln daher ist ein durchsuchen des Regals nicht möglich und damit die mission nicht abschließbar (Route 15 Ammonation)

**Erwartetes Verhalten**

Das man das Regal durchsuchen kann

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

2560 * 1440

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/90334895/0ce7ab1c-004b-4927-8eec-686c2e04fb40)

![image](https://github.com/eiksch/statev_v3_issues/assets/90334895/fba02b51-30f9-4f84-bc52-927c344d5ad7)

**Comment by TheOutburst** [comment]
Der Marker müsste mit ein bisschen rumspielen noch erreichbar sein
Nächstes Updat aber fixed 👌

**Comment by SHaagmann** [comment]
> Der Marker müsste mit ein bisschen rumspielen noch erreichbar sein Nächstes Updat aber fixed 👌

@TheOutburst Gleiche Problem beim Ammunition in Little Soul. Reicht das hier kurz bescheid zu geben oder neuen Bugtrack eintrag machen?

**Comment by Slayraw** [comment]
@TheOutburst Westhighway ist es ebenfalls so

![image](https://github.com/eiksch/statev_v3_issues/assets/90334895/c37cb1cf-f4da-407e-897b-6b7c80fb7c4e)

**Comment by l4m4rr224** [comment]
Ich denke mal das es bei soweit fast ALLEN der fall sein wird
