### ISSUE TITLE
📌 AI Überschwemmung im Lifeinvader

### ISSUE THREAD

**Issue by hfgdgfdgfd** [mexyn/statev_v2_issues#3304]
Liebes Serverteam,

wir, eine Gruppe engagierter Spieler von StateV, möchten euch unser gemeinsames Anliegen bezüglich der Verwendung von KI-generierten Bildern auf Lifeinvader mitteilen. Unsere Sorge betrifft die Integrität und die immersive Erfahrung des Spiels, die durch den übermäßigen Einsatz dieser Technologie beeinträchtigt wird.

Lifeinvader spielt eine zentrale Rolle in unserer Interaktion innerhalb der Welt von GTA. Es dient als Mittel, um unsere Charaktere und deren Geschichten zu vertiefen. Jedoch stört der exzessive Gebrauch von KI-generierten Bildern das Spielgefühl erheblich und entzieht uns der Atmosphäre vom RP, indem es eine offensichtliche Diskrepanz zwischen der Spielwelt und diesen Bildern schafft.

Zudem möchten wir auf die bestehenden Regeln bezüglich OOC Inhalten hinweisen, die darauf abzielen, die Immersion nicht zu stören. Es scheint, dass diese Regeln selektiv angewendet werden, was zu einer Ungleichbehandlung unter den Spielern führt. Wenn es Regelungen gibt, die OOC-Elemente verbieten, die nicht IC vorhanden sind, bitten wir um konsequente Durchsetzung dieser Regeln für alle Spieler ohne Ausnahmen.

Schaut euch die Konten doch einfach mal an und fragt euch: Ist das wirklich gut für den Server?

~~Liebe~~ _genervte_ Grüße 
Joachim

**Schritte um den Fehler nachvollziehen zu können**

- [ ] T&T_Company
- [ ] MrCorporation
- [ ] Beautyx
- [ ] Uncle_Jacek's
- [ ] 🛠️LSC🛠️

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/167117985/e7073e11-84f9-4359-8a1e-6a07f803444c)
![image](https://github.com/eiksch/statev_v3_issues/assets/167117985/574f1282-4651-4ff8-a57e-56051549923b)
![image](https://github.com/eiksch/statev_v3_issues/assets/167117985/a2307454-bf7b-4a97-9259-68cd3ccce1d5)
![image](https://github.com/eiksch/statev_v3_issues/assets/167117985/b65725a7-6b0f-45ee-a20a-fa5ec3b13567)
![image](https://github.com/eiksch/statev_v3_issues/assets/167117985/c7bf9b0f-d671-47bd-a8a1-85d5bf7d9838)
![image](https://github.com/eiksch/statev_v3_issues/assets/167117985/eff2baa4-f7fe-4b3b-b3fc-c47c63b28442)
![image](https://github.com/eiksch/statev_v3_issues/assets/167117985/2b4b5ac6-ff9c-4b49-bd28-98e528337d9c)
![image](https://github.com/eiksch/statev_v3_issues/assets/167117985/5644e8c4-005c-4a13-89e5-46e4ca4cb544)
![image](https://github.com/eiksch/statev_v3_issues/assets/167117985/1120af82-c68d-4c47-9beb-1c66762d4d44)
![image](https://github.com/eiksch/statev_v3_issues/assets/167117985/e7af651f-6822-4dc9-ab4f-bed37678fe27)
![image](https://github.com/eiksch/statev_v3_issues/assets/167117985/b0d17baa-7a76-4cdb-bd50-28252a943a27)
![image](https://github.com/eiksch/statev_v3_issues/assets/167117985/987937a3-5b96-49b9-8512-7b6abdf4e4dc)
![image](https://github.com/eiksch/statev_v3_issues/assets/167117985/283fc89d-a36f-4bee-8c26-eb8217d8c4ae)

**Comment by stepz2k9** [comment]
Das wäre eher was für nen Support-Ticket und nichts für den Bugtracker...
Aber mal davon ab.. die Disney-Figuren finde ich persönlich auch too much, den Rest völlig okay. Es war schon zu V2 erlaubt, grafische Werbung für Firmen zu machen. Da waren KIs nur halt noch nicht so gegeben.

Ob man da nun ein Bild, das jemand eigen erstellt hat, oder ein KI-Bild hinballert, macht mMn keinen großen Unterschied.

Schlimmer finde ich die KI-Enhanced Profilbilder einiger User.

**Comment by rodistic** [comment]
Guten Tag,

wenn du eine Beschwerde aufgeben willst dann bitte über unser Supportsystem nicht über unseren Bugtracker.
Dieser ist nur für, wie es der Name schon sagt, System Fehler oder Requests zu technischen begebenheiten.

case closed

**Comment by hfgdgfdgfd** [comment]
Da haben wir ja genau das Problem noch einmal verdeutlicht, sowas müsste man in einem Ticket ansprechen, was jedoch nicht möglich ist, da im Support immer mit zweierlei Maß gemessen wird und ich mich auf keine neutrale Bewertung verlassen kann.

Und da dort ein anonymes Ansprechen von Problemen nicht möglich ist, auf diesem Wege. 


Und mit “Ob man da nun ein Bild, das jemand eigen erstellt hat, oder ein KI-Bild hinballert, macht mMn keinen großen Unterschied.” seid ihr Teil des Problems.

**Comment by simplycach** [comment]
Wir bitten dich jetzt nochmal, dich per Ticket dazu zu melden. Bei uns wird jedes Ticket ernst genommen und nicht mit zweierlei Maß gemessen.

Aber über diesen Weg wirst du keine weiteren Informationen erhalten. Dies ist ein Bugtracker keine Plattform für Feedback oder Support Angelegenheiten.
