### ISSUE TITLE
Marktverkauf Listenpreis und stückpreis

### ISSUE THREAD

**Issue by VeAderian** [mexyn/statev_v2_issues#3305]
Kevin Walker

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer wenn man in der Firma etwas zum kauf/verkauf in den Markt einstellt

**Beobachtetes Verhalten**
Einstellen eines Kaufauftrages in der fürma über Marktplatz:
Beispiel: 1000 Liter Erdöl zu 0,69$ preis/stück = 0,66$ Listenpreis (0,69$ zahle ich als käufer, 0,66$ erhält der Verkäufer) 
![EK1](https://github.com/eiksch/statev_v3_issues/assets/61833414/15027833-542c-436a-9d54-7fd70b6035e4)

Einstellen eines Verkaufauftrages in der Firma über Marktplatz:
Beispiel: 1000 Liter Erdöl zu 0,66$ preis/stück = 0,66$ Listenpreis (0,66$ erhalte ich als Käufer, 0,69$ zahlt der Verkäufer)
![VK1](https://github.com/eiksch/statev_v3_issues/assets/61833414/0e288c60-1b57-470c-bbf5-98b6a39fabb8)

**Erwartetes Verhalten**
Einstellen eines Verkaufauftrages in der Firma über Marktplatz:
Beispiel: 1000 Liter Erdöl zu 0,66$ preis/stück = 0,69$ Listenpreis (0,66$ erhalte ich als Käufer, 0,69$ zahlt der Verkäufer)

Die Steuern werden nicht angezeigt beim verkauf von Waren über den Marktplatz wenn man den Verkaufsauftrag erstellt.

Es gibt soviele Möchtegern Broker die dann immer diskutieren wollen wegen EK und VK mit den Steuern, wäre also super wenn das überarbeitet wird, dass auch beim einstellen von Verkaufsaufträgen der Listenpreis korrekt angezeigt wird.

**Comment by simplycach** [comment]
Naja wenn ich das richtig sehe, möchtest du für 66 Cent das Öl verkaufen und der Käufer zahlt dann 69 Cent weil er die Steuern trägt und wieso sollte der Verkäufer dort die Steuern tragen ?

**Comment by simplycach** [comment]
Aber denke du willst darauf hinaus, dass beim Einkauf von Waren bei 0,66 Preis/Stück im Listenpreis 0,66 angezeigt wird,  dort sollte dann 0.69 Cent stehen, so meinst du das oder ?

**Comment by VeAderian** [comment]
> Naja wenn ich das richtig sehe, möchtest du für 66 Cent das Öl verkaufen und der Käufer zahlt dann 69 Cent weil er die Steuern trägt und wieso sollte der Verkäufer dort die Steuern tragen ?

Weil der Käufer immer die Steuern bezahlt, wenn du in den Laden gehst und brot kaufst für 3€ zahlst sdu auch die Steuern mit, denn in die 3€ sind bereits die Mehrwertsteuern enthalten.

Wenn du dir das Beispiel anschaust, wie es aussehen sollte dann siehst du was ich meine

**Comment by simplycach** [comment]
Es geht dir doch nur darum, dass die Steuer angezeigt werden beim verkaufen oder nicht ? Also ja klar die Steuern sollen auch berechnet werden. Hab mir dein Beispiel angeschaut.

**Comment by VeAderian** [comment]
ja, das steht aber auch oben in dem Beispiel .... denn zahlen tut der Käufer ja die Steuern, es wird nur nicht korrekt angezeigt, ebenso sollte auch auf den Kontoauszügen dann der Wert stehen der tatsächlich aufs konto eingegangen ist und nicht dort versteckt die Steuern rausgerechnet. aktuell sehe ich aufm Konto leider auch immer der den Brutto Wert, aber nicht was Netto wirklich ankam. das mit 0,66$ ist halt aktuell nur ein Beispiel gewesen, ich verkaufe zur zeit das Öl für 0,76$, so steht es als preis/stück und als Listenpreis drinne im VK, aufm Konto wird es mir auch mit 0,76$ angezeigt, aber wenn du mal rechnest wieviel 450 * 0,76$ ist das nicht identisch mit den 324,90$ die auf mein Konto eingegangen sind. Es geht mir nur darum das beim VK im Markt der Listenpreis korrekt inklusive der Steuern angezeigt wird und auf den Kontoauszügen nur der Netto Wert steht, der tatsächlich aufs Konto eingeht.

**Comment by simplycach** [comment]
Ich leite das mal weiter, dann schauen wir mal was wir machen können.

**Comment by epichalt** [comment]
Das sind einfache Rundungen. Man kann halt nicht jede Zahl "clean" mit 0,95 multiplizieren.
0.76 x 0.95 ergibt 0.722$
0.722 x 450L Öl ergibt genau 324,9$.

Rechnerisch passt dementsprechend alles. Kaufmännisch ist auch alles richtig gerundet. 

Klar man könnte auf dem Kontoauszug den Netto Preis statt dem Brutto Preis angeben. Aber darüber könnte man sich theoretisch genauso "beschweren"
