### ISSUE TITLE
Hotelappartments frei/vermietet

### ISSUE THREAD

**Issue by hxffes** [mexyn/statev_v2_issues#3306]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Charaktername**
Kilian David

**Auftrittszeitpunkt (Datum / Uhrzeit)**
15.04.2024 ca. 15/16 Uhr 

**Beobachtetes Verhalten**
Hotelappartment wurde als frei angezeigt, also unvermietet. Ich hab den Mietpreis auf 20.000$ erhöht um das Zimmer zu blocken und zu schauen ob der Müll draussen ist. Paar Minuten später war derselbe Mieter drin, der vorher drin war. Die 20.000 wurden jedoch nicht gebucht, da der Mieter die ganze Zeit eingemietet war. Das Hotelzimmer war nie frei. Den Fehler konnte ich schon mal beobachten 1-2 Wochen vorher, bei meinem vorherigen Hotel. Wenn ein Hotelzimmer vergeben ist, kann man den Mietpreis nicht ändern. Mir gehört das Hotel auch. Es handelt sich um das PillboxHill_Flat_22. Zimmer PillboxHill_Flat_22_6. Der Mieter war auch in der Zeit nicht online seit 3-4 Tagen. Bei dem ersten Vorfall war der Mieter auch nicht online. Also zusammengefasst: Appartments werden für kurze Zeit als frei angezeigt, obwohl sie vermietet sind. Der Fehler trat in 3 Wochen 2x mal. Bei 2 verschiedenen Hotels.

**Erwartetes Verhalten**
Es werden mehrere Dinge falsch angezeigt, auch die letzte Miete. Das hab ich schon an mir beobachtet.

**Schritte um den Fehler nachvollziehen zu können**
Kann man leider nicht beeinflussen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
Kann ich leider nicht

**Optional: Video / Bilder des Fehlers**
Leider nicht, da ich dachte das Hotelzimmer wäre jetzt frei.

**Comment by CCastles22** [comment]
Ja hatten wir auch schon desöfteren wie von dir beschrieben
Einzig momentane Abhilfe: pysisch vor die Haupttür gehen vom Hotel da wirds richtig angezeigt - bis sich der Sache angenommen wird!

**Comment by simplycach** [comment]
Kann noch vereinzelnd auftreten, dann bitte nochmal nen Ticket eröffnen.
