### ISSUE TITLE
Tasche wird nicht richtig angezeigt

### ISSUE THREAD

**Issue by SauerkirscheJM** [mexyn/statev_v2_issues#3307]
Seit dem 17.04. gegen Mittag rum, wird die Tasche **[Bag] Blaue Jackal Racing Duffle Bag** nicht mehr richtig im inventar angezeigt. Das Image scheind kaputt zu sein?

Anbei Bilder des Fehlers:

![tasche 2](https://github.com/eiksch/statev_v3_issues/assets/123385988/5a542344-81d7-4ca1-b206-ae73fb16b0b6)
![tasche 1](https://github.com/eiksch/statev_v3_issues/assets/123385988/ab6c639a-0a0b-44bd-9db6-c0a389922395)
![tasche 3](https://github.com/eiksch/statev_v3_issues/assets/123385988/6487f03f-b56b-4c86-b6be-bc53329fb9dc)

VG

**Comment by SauerkirscheJM** [comment]
hab schon gehört, dass ihr bescheid wisst. Hat sich dann erledigt

**Comment by TheOutburst** [comment]
sollte next update mit gefixt werden 👌
