### ISSUE TITLE
Gang Burrito folien bug

### ISSUE THREAD

**Issue by gobi552** [mexyn/statev_v2_issues#3308]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Meikel_Kingston
**Auftrittszeitpunkt (Datum / Uhrzeit)**

bei kauf
**Beobachtetes Verhalten**

der Gang Burrito wird mit der Lost MC bemalung ausgelievert das kann bei einer werkstad nicht geändert werden
**Erwartetes Verhalten**

farbe und folie solten änderbar sein
**Schritte um den Fehler nachvollziehen zu können**

-
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

-
**Optional: Video / Bilder des Fehlers**
https://prnt.sc/FrWZx3ebl6aV

**Comment by Statev-Bonsai** [comment]
das müssten zwei verschiedene motoren sein.. einmal gang burrito + gang burrito lost mc...
so war es jedenfalls in v2...

**Comment by gobi552** [comment]
https://prnt.sc/zOU514QKP4gV der wurde gebaut

**Comment by Erumeldor** [comment]
@gobi552 
Wie Bonasi schon richtig sagte, gibt es in GTA zwei Fahrzeuge:
https://gta.fandom.com/wiki/Gang_Burrito_(custom)
https://gta.fandom.com/wiki/Gang_Burrito

Die Fahrzeuge sind auch so in der Produktion benannt. Das von dir gebaute ist also der zweite Link. Da ist die Folie fest drauf, und können wir daher nicht entfernen.

Ist daher kein Bug, weshalb ich hier schließe.

**Comment by Erumeldor** [comment]
Ich hab das Fahrzeug zur Vermeidung von weiterer Verwirrung für das nächste Update mal umbenannt.
