### ISSUE TITLE
Hotelmiete wird Doppelt abgebucht 

### ISSUE THREAD

**Issue by Xymena** [mexyn/statev_v2_issues#3309]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Alice_Swan
**Auftrittszeitpunkt (Datum / Uhrzeit)**
~kann nicht genau gesagt werden

**Beobachtetes Verhalten**
Es wird die Miete Doppelt abgebucht, einmal auf den Konto des Hotels und einmal auf das  Staatliche
**Erwartetes Verhalten**
Miete wird nur einmalig abgebucht..

**Schritte um den Fehler nachvollziehen zu können**

Bei prüfung des Konto auszuges

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/76626768/e2618212-fcd2-41f0-8994-1fe5623fa8a9)

**Comment by Xymena** [comment]
es scheint da ein hotel miete abgebucht zu werden wo ich garnicht mehr miete..

**Comment by simplycach** [comment]
Wird das immer noch doppelt abgebucht ?

**Comment by Xymena** [comment]
war die hotelmiete, ich war angeblich in 2 Hotels eingebucht was aber nicht stimmte. ich habe das eine vor ewigkeiten gekündigt.  der fehler tritt seit dem 12.3.2024, 02:51:02 auf wo ich das Hotelzimmer gewechslt habe und mich aus dem Alten ausgemietet habe.  habe jetzt auch nur gesehen durch die Kündigung aufgrund des Updates. Auf der Karte wurde mir kein zweites Hotel zimmer angezeigt. 

![image](https://github.com/eiksch/statev_v3_issues/assets/76626768/970e8a59-c9e1-4459-8b5d-7b5c810fd632)

**Comment by simplycach** [comment]
Aber wurde dir denn über die Zeit jetzt immer noch das 2 berechnet ?

**Comment by Xymena** [comment]
Genau es wurde die ganze zeit 2 mal berechnet, richtig aufgefallen oder hinterfragt habe ich es jetzt vor kurzen. Wo ich mich mit jemanden drüber unterhalten habe daher auch erst so spät der bug tracker.  wenn ich mich nicht verrechnet habe handelt es sich um 410 Fehlbuchungen.. also knapp 8200$

**Comment by simplycach** [comment]
Ist das noch aktuell ?

**Comment by Xymena** [comment]
nee am 19ten gabs ja den bug wo man aus den Hotels geflogen ist danach ist es halt nicht mehr aufgetreten  nur was mit den doppeltbuchungen ist wäre intressant :3

**Comment by simplycach** [comment]
Sind die Doppelbuchungen noch vorhanden? Also passieren sie noch ?

**Comment by Xymena** [comment]
Nein passieren nicht mehr

**Comment by simplycach** [comment]
Dann schließe ich das hier
