### ISSUE TITLE
MD Fall Bug (Medic)

### ISSUE THREAD

**Issue by Chrinis007** [mexyn/statev_v2_issues#331]
**Character Name**
Christian_Maier

**Zeitpunkt (Datum / Uhrzeit)**
Seit V2

**Beobachtetes Verhalten**
Wenn man sich im LSMD ausloggt oder Gamecrash hat spawned man meistens im Tunnel oder generell in einem Radius von 500m

**Erwartetes Verhalten**
Am selben Punkt wieder ic kommen und auf der selben höhe

**Schritte um den Fehler nachvollziehen zu können**
Gamecrash im oder vorm MD bekommen oder ausloggen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Bitte ab nächsten Restart weiter beobachten und melden wenn es sich gebessert haben sollte.

**Comment by Chrinis007** [comment]
Hat leider keine Besserung gebracht, beim letzten Mal sogar Bewusstlosigkeit

**Comment by r3sist3nt** [comment]
Wir haben einen Potenziellen Fix dafür.

**Comment by Chrinis007** [comment]
Mittlerweile nicht mehr aufgetreten
