### ISSUE TITLE
Fragen und Wünsche zum Haus

### ISSUE THREAD

**Issue by Kaycee91** [mexyn/statev_v2_issues#3310]
Grüße,

bei meinem Anliegen geht es um die Frage ob ihr mir die Eingangstür entweder versetzten könnt oder die COuch die die Tür BLockiert entfernen könnt.

Char: Nick_Harrison
Haus Hash: house_SandyShores_56

Eine kleine Frage noch: Gibt es bei diesem Haus die Möglichkeit einen kleinen Carport / kleine Garage zu bekommen ? 
Wenn nicht all good just asking 

Vielen dank schonmal für eure Zeit

![Grand Theft Auto V Screenshot 2024 04 18 - 23 52 41 77](https://github.com/eiksch/statev_v3_issues/assets/38119374/3091ac9f-9860-4aab-ba65-47be129e7fd6)
![Grand Theft Auto V Screenshot 2024 04 18 - 23 52 21 08](https://github.com/eiksch/statev_v3_issues/assets/38119374/00a31ce8-939e-4b4f-b41c-afe581af7077)

**Comment by Erumeldor** [comment]
Hast du denn einen konkreten Vorschlag, wo der Eingang hinsoll?
Und hast du bei dir am Haus optisch eine Garage/Carport o.ä.?

**Comment by Kaycee91** [comment]
Was die Garage / Carport angeht kann ich ned beurteilen ob euch da was reicht. 

Was die Tür angeht es gibt links von der tür noch eine weitere die nicht genutzt wird

**Comment by TheOutburst** [comment]
Eingang ist einmal nach links gewandert 👌 
Aber nee, der Container hat keinen Carport oder klar abgegrenztes Grundstück, deswegen wird das mit ner Garage leider nichts

**Comment by TheOutburst** [comment]
Eingang verschoben 👌 
Aber nee, für ne Garage hast du keinen Carport oder klar abgegrenztes Grundstrück

**Comment by Kaycee91** [comment]
danke euch

**Comment by simplycach** [comment]
fixed
