### ISSUE TITLE
Verbuggter Drogenlieferungspunkt

### ISSUE THREAD

**Issue by officialschnoopie** [mexyn/statev_v2_issues#3311]
Hey,

dieser Abgabepunkt schein verbuggt zu sein.

![Bild_2024-04-19_125004804](https://github.com/eiksch/statev_v3_issues/assets/166428726/bba056a7-ad3a-4575-b57b-009a4c8a077b)

![Bild_2024-04-19_125017367](https://github.com/eiksch/statev_v3_issues/assets/166428726/840c2a86-691f-4ce3-bf89-123557c729bd)

**Comment by simplycach** [comment]
Next Update fixed.
