### ISSUE TITLE
Mietwohnung verloren

### ISSUE THREAD

**Issue by VeAderian** [mexyn/statev_v2_issues#3312]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Kevin Walker

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.04.2024 / 12:46Uhr

**Beobachtetes Verhalten**
IC Meldung bekommen das ich meine Wohnung am Eclipse Blvd. verloren habe, weil die Miete angeblich nicht gezahlt werden konnte. Allerdings ist auf dem Konto genug Geld vorhanden und laut Kontoauszug wurden die 20$ für die Miete auch abgebucht.

**Optional: Video / Bilder des Fehlers**
![miete](https://github.com/eiksch/statev_v3_issues/assets/61833414/f72d4278-5b67-40d6-8339-99dc69389ba4)

**Comment by simplycach** [comment]
Wird durch das nächste Update behoben.
