### ISSUE TITLE
Sprachreichweite nachdem Patch nicht mehr änderbar.

### ISSUE THREAD

**Issue by coresync2k** [mexyn/statev_v2_issues#3313]
Moin,

nachdem Patch kann ich irgendwie meine Sprachreichweite nicht mehr ändern ( scheine wohl nicht der einzige zu sein )
egal auf welche Taste ich es lege, oder mit der Standarttaste "Z" funktioniert das irgendwie nicht mehr, diverse neustarts wurden durchgeführt..

Erwartetes Verhalten:

Das die Sprachreichweite geändert werden kann bzw. sich ändert.

**Comment by simplycach** [comment]
Next Update fixed
