### ISSUE TITLE
Ball Bug

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#3314]
**Character Name**
Charly Russo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.04.2024 13.00 Uhr

**Beobachtetes Verhalten**
Wenn man nen Ball geworfen hat zieht man automatisch n Messer wenn ausgerüstet

**Erwartetes Verhalten**
Weniger Mikroaggressionen

**Schritte um den Fehler nachvollziehen zu können**
Messer ausrüsten, Ball werfen

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=38V6O819rAs

**Comment by simplycach** [comment]
Bereits offen. https://github.com/eiksch/statev_v3_issues/issues/3240

**Comment by Philosofisch** [comment]
Ja schon, aber der Ball funktioniert ja wieder seit dem Update heute, is halt verbuggt, also n neuer Fehler.

**Comment by TheOutburst** [comment]
Moin
Das ist GTA Behaviour, sobald Waffe A leer ist (Ball geworfen) ziehst du eine andere Waffe die Munition hat (Pistole)

Ich bezweifle ehrlich gesagt, dass wir das wir dafür eine Lösung finden werden

**Comment by simplycach** [comment]
Closed, da wir dafür keine Lösung haben.
