### ISSUE TITLE
Firmen SIM-Karte - Telefon klingelt weiter, obwohl jemand das Gespräch angenommen hat

### ISSUE THREAD

**Issue by ChrisBraun-VIOV** [mexyn/statev_v2_issues#3315]
Character Name
Chris Morrison

Auftrittszeitpunkt (Datum / Uhrzeit)
permanent

Beobachtetes Verhalten
Die  Firmen SIM-Karte wird angerufen und es haben mehrere die SIM aktiv im Handy. Jemand ist dran gegangen, wodurch bei allen anderen der Klingelton in Dauerschleife weiter läuft.

Erwartetes Verhalten
Das wenn jemand anderes den Anruf annimmt der Klingelton aufhört zu Klingeln

Schritte um den Fehler nachvollziehen zu können
Mehrere Leute die gleiche Nummer einsetzen und aktiv haben.
Anrufen lassen und jemand nimmt den Anruf an. Feststellen, dass bei den anderen der Klingelton weiterläuft

Es gab hierzu bereits eine BUG-Meldung, aber nicht zu V3: https://github.com/eiksch/statev_v3_issues/issues/1996

**Comment by QA-Pregon** [comment]
Next update fixed
