### ISSUE TITLE
Wohnung gekündigt obwohl nicht gekündigt, HarzV falsch ausgezahlt

### ISSUE THREAD

**Issue by AdaMckinley** [mexyn/statev_v2_issues#3316]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Ada Mckinley

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.04.2024 13:24

**Beobachtetes Verhalten**
NAch eingang des HartzV wurde mir angezeigt das die Miete nicht bezahlt werden konnte und die Wohnung gekündigt wurde.Wohnung ist aber noch gemietet. Miete wurde auch abgezogen HartzV betrug nur 70 Dollar

**Erwartetes Verhalten**
Richtiger Betrag von HartzV

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![20240419134243_1](https://github.com/eiksch/statev_v3_issues/assets/167531432/b76aee8f-f7ed-445b-ba32-deb5787a9ace)

**Comment by simplycach** [comment]
Wurde bereits gemeldet.
