### ISSUE TITLE
Crime Auftrag verbuggt

### ISSUE THREAD

**Issue by Blackatom98** [mexyn/statev_v2_issues#3317]
**Character Name**
Francesco Allorosso

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.04.2024 13:30 uhr

**Beobachtetes Verhalten**
Ich habe ein crime auftrag angenomme wo ich etwas aus einem laden mit gehn lassen soll und habe jetzt bestimmt schon 15 minuten den auftrag gemacht er lässt sich nicht beenden und gibt zu dem eine fehler meldung

**Erwartetes Verhalten**
eigentlich sollte ich 2 punkte im liquer store in der west side und danach sollte er eigentlich erledigt sein

**Schritte um den Fehler nachvollziehen zu können**
Ich habe bei dem crime npc an der baustelle angegebn das ich etwas aus einem 24/7 besorgen möchte habe dann eine sms bekommen wo ich hin soll und bin hingefahren bin dann in den laden rein an den punkt der aufgabe gegangen und habe E gedrückt mein char hat dann eine animation ausgeführt habe auch 2-3 sachen rausbekommen aber die punkte verschwinden nicht sondern bleiben wesshalb ich den auftrag nicht beenden kann

**Optional: Video / Bilder des Fehlers**
![Screenshot 2024-04-19 134739](https://github.com/eiksch/statev_v3_issues/assets/167531903/1a27fbef-c742-4ab2-ab1a-062746330a7f)

**Comment by simplycach** [comment]
Sollte Next Update fixed sein
