### ISSUE TITLE
Frauen Oberteil hat keine passende Einstellung zum anziehen

### ISSUE THREAD

**Issue by EmilyLodge** [mexyn/statev_v2_issues#3318]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
 Emily Hunter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Schon länger. Ende V2, Start von V3

**Beobachtetes Verhalten**
Egal welche Einstellung ich versuche, es Bugt immer irgendwo Haut durch. Bisher ist die "beste" Einstellung Kurzarm 2, wobei dort die Haut ziemlich offensichtlich am Oberkörper zu sehen ist.

**Erwartetes Verhalten**
Haut Bugt nicht mehr durch und hat eine passende Einstellung bei der Anpassung der Kleidung.

**Schritte um den Fehler nachvollziehen zu können**
Oberteil angezogen, Langarm, Kurzarm etc.. angepasst, nichts passendes gefunden.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Hg9X2c](https://github.com/eiksch/statev_v3_issues/assets/74831514/5ee9d15a-fb4b-4624-9ea9-fd50c71584f2)

![Hg93y7](https://github.com/eiksch/statev_v3_issues/assets/74831514/7dd19ee8-a2d7-41a9-be53-fc05c5754623)

![Hg98MB](https://github.com/eiksch/statev_v3_issues/assets/74831514/6d344ed6-c96d-4d4d-a722-0de34953fa40)

**Comment by Enemyaa** [comment]
Danke für die Info! 
Das Modell dazu wird bald ausgewechselt.

**Comment by simplycach** [comment]
fixed
