### ISSUE TITLE
Spieler nach KO

### ISSUE THREAD

**Issue by Knutx3** [mexyn/statev_v2_issues#3319]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Aiden_Kingston**

Meinem charakter

**19.04.2024 15:30 **

**Ich wurde mit Nackenschlag K.O geschlagen und die anderen spieler hatten die meldung der spieler ist nicht Ohnmächtig jedoch bin ich immer wieder aufgestanden und instand wieder ausgenockt als würde jemand mich 10x instand ausnocken**

**das nach 1 min wieder aufsteht**

**hatte 15% leben noch und habe einfach ein Nackenklatscher bekommen **

** 1920x1080 )**

**Habe leider kein shadowplay offen gehabt jedoch wurde alles in support ticket geschrieben und mir wurde gesagt solle ein bugtracker sicherheitshalber aufmachen **

**Comment by simplycach** [comment]
fixed
