### ISSUE TITLE
Lager/Spind Bug (PD)

### ISSUE THREAD

**Issue by MisterCopeland** [mexyn/statev_v2_issues#332]
Paddy_Copeland

**Zeitpunkt (Datum / Uhrzeit)**
21/11/2020 18:30 Uhr

**Beobachtetes Verhalten**
Beim Verschieben einer befüllten Tasche in den Spind wurde die nach schließen und wieder öffnen des Spindes geleert.
Die Tasche ist also danach Leer.

**Erwartetes Verhalten**
Tasche bleibt wie im Hauslager bzw. Autokofferraum befüllt. 

**Schritte um den Fehler nachvollziehen zu können**
Tasche befüllen -> In den Spind legen -> UI Schließen -> Mit "E" wieder öffnen -> Leere Tasche entnehmen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1080p (1920x1080)

**Optional: Video / Bilder des Fehlers**
Keins, aber einfach mal testen dann sieht man es ja.

**Comment by JulianMa** [comment]
Kann ich bestätigen. Ich schaue mir das an.

**Comment by JulianMa** [comment]
Fixed nach nächstem Update.
