### ISSUE TITLE
Auswahl von Frauen Hosen führen zu Game Crashes

### ISSUE THREAD

**Issue by Xymena** [mexyn/statev_v2_issues#3320]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Alice_Swan
June_Swan
Palina_Pavlova
Kiana_Kayen

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit update  16:00 Uhr

**Beobachtetes Verhalten**
Bei der Auswahl von der Hose  "Cargo Joggr " kommt es zu Spiele absürzten von Personenen die sie ausprobieren und personen die daneben stehen, Fehler kommt Sporadisch aber häufig vor.

**Erwartetes Verhalten**
Kleidung anschauen führt nicht zu fehler.

**Schritte um den Fehler nachvollziehen zu können**
Es wird in Fashion Katalog Hose -> Cargo jogger -> [F]Orange Cargo Jogger ausgwählt
Führt bei dir und umstehende personen zum Crash. Etwa jetzt 6 mal aufgetreten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/76626768/fba6e488-06e1-47f2-bcd6-1e77e42b877f)
![image](https://github.com/eiksch/statev_v3_issues/assets/76626768/04c7947c-c1b2-44d4-b595-913eb0711915)

**Comment by simplycach** [comment]
Kannst du uns mal den Client Log von Altv schicken von dieser Zeit. Und Crash Log

**Comment by Xymena** [comment]
[client_2024-04-19_14-47-38.log](https://github.com/eiksch/statev_v3_issues/files/15042882/client_2024-04-19_14-47-38.log)
[client_2024-04-19_15-40-49.log](https://github.com/eiksch/statev_v3_issues/files/15042885/client_2024-04-19_15-40-49.log)

Du meinst diese?

**Comment by simplycach** [comment]
Wir konnten das bisher auch nicht reproduzieren, eventuell kannst du beim nächsten mal ein Video machen.

**Comment by Xymena** [comment]
Passiert leider auch in Kleidungsladen, wo die Cargo ausgewählt wird un der halbe Laden gefühlt GameCrashes hat..

**Comment by simplycach** [comment]
Spielt ihr mit Mods zufällig ?

**Comment by SauerkirscheJM** [comment]
Habe das selbe Problem im Kleiderladen oben in der Stadt (7020). Einmal als ich durch die Buttoned Jeans durchgeguckt habe und einmal stand ich nur daneben und hatte einen absturz. Keine Fehlermeldung dabei
