### ISSUE TITLE
Gemeinschaftskonto Anzeige Buggt als Nicht-Ersteller

### ISSUE THREAD

**Issue by LottiFoxy** [mexyn/statev_v2_issues#3321]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Caroline Hovenkoven

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit 3.1 Update
**Beobachtetes Verhalten**
Gemeinschaftskonto durch IC Ehemann erstellt -> Rechte erhalten -> Bei Versuch Verlauf aufzuklappen erscheint oben re Fehlermeldung und ewiger Ladekreis ohne das Verlauf auftaucht

**Erwartetes Verhalten**
Einsicht in Verlauf des Gemeinschaftskontos mit entsprechenden Rechten

**Schritte um den Fehler nachvollziehen zu können**
Konto eröffnet -> Rechte bekommen -> Geld überwiesen -> Verlauf aufklappen -> Fehlermeldung -> kein Sichtbarer Verlauf 
(Überweisung nicht getestet)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Rechteverteilung:
![Screenshot_8](https://github.com/eiksch/statev_v3_issues/assets/166732305/e8bceff4-005d-4762-8db4-2b06b6aa1d46)
Fehlermeldung & Ladekreis:
![Screenshot 2024-04-19 150641](https://github.com/eiksch/statev_v3_issues/assets/166732305/9c50368b-a4e6-44c7-a097-efa9aa26117b)
Überweisung von anderem Konto auf Gemeinschaftskonto:
![Screenshot 2024-04-19 150717](https://github.com/eiksch/statev_v3_issues/assets/166732305/5a34fecd-abc0-4c30-9583-4ee8dba87a9d)

**Comment by simplycach** [comment]
fixed
