### ISSUE TITLE
Meldung "Kennzeichen bereits abgeklebt"

### ISSUE THREAD

**Issue by OnkelHomie** [mexyn/statev_v2_issues#3322]
**Character Name**
Alexander_Jones und Yuma_Raiden

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Nachdem das Fahrzeug ausgeparkt wurde

**Beobachtetes Verhalten**
Kennzeichen abgeklebt wurde, wurde das Fahrzeug eingeparkt. Beim Ausparken war das Kennzeichen wieder sichtbar. Wollten es wieder abkleben. Es erscheint die Meldung, dass das Kennzeichen bereits abgeklebt ist.

**Erwartetes Verhalten**
Kennzeichen bleibt weiterhin verdeckt. 

**Schritte um den Fehler nachvollziehen zu können**
Kennzeichen abkleben, Fahrzeug einparken und wieder ausparken. 

**Optional: Video / Bilder des Fehlers**
![image342](https://github.com/eiksch/statev_v3_issues/assets/78343649/eccf3535-f134-4d6a-a038-def499e6249a)

**Comment by simplycach** [comment]
Wie lange war das Auto eingeparkt ?

**Comment by OnkelHomie** [comment]
> Wie lange war das Auto eingeparkt ?

Lass es 2-3 Minuten gewesen sein, weil wir reloggen mussten

**Comment by Erumeldor** [comment]
Ist für mich nicht reproduzierbar. Vermutlich irgendein Randcase.

**Comment by simplycach** [comment]
Same hatte dasselbe wie @Erumeldor

**Comment by OnkelHomie** [comment]
Und was machen wa da nun?

**Comment by eiksch** [comment]
Welches Autokennzeichen? @Bene-RonnyMoritz

**Comment by OnkelHomie** [comment]
> Welches Autokennzeichen? @Bene-RonnyMoritz

SA-4C-SK ist meins. Das von Yuma_Raiden müsste SA-PU-MA sein.

**Comment by simplycach** [comment]
Scheint nen Einzelfall gewesen zu sein, wenn es nochmal vorkommt bitte nochmal melden.
