### ISSUE TITLE
Andere haare als ausgewählt 

### ISSUE THREAD

**Issue by germanmiles** [mexyn/statev_v2_issues#3323]
Hey ihr solltet die Haare mal überprüfen nachdem was man schneidet kommen andere haare raus als ausgewählt

**Comment by simplycach** [comment]
Hast du eventuell mehr Informationen für uns, das ist halt schon bisschen wenig damit wir damit vernünftig arbeiten können. Videos wäre Top.

**Comment by DonJohn1993** [comment]
Yup. Können wir so bestätigen vom County Cut. 

Rachel_Miller
20.4.2024, 00:05:32

Ausgewählte Frisur: High Ponytail

Ergebnis:

![ponytails](https://github.com/eiksch/statev_v3_issues/assets/79906053/52fb70a4-4b92-4da7-aa4a-54af02d9d812)

**Comment by germanmiles** [comment]
okay top wenn ihr schon bescheid wisst hab grade 2 haarschnitte gewaistet deswegen (Hair Kutz)

**Comment by Xymena** [comment]
Hatten, den Fehler auch  konnten ihn aber nicht Reproduzieren nach erneuten schneiden ging der schnitt normal...

**Comment by DonJohn1993** [comment]
Beim High Pony war's 2x diese Frisur

**Comment by Hutstaender** [comment]
Wurde die Frisur 2x beim gleichen char geschnitten? Und wie hieß der Kunde?

**Comment by Hutstaender** [comment]
Und gilt das für alle Kunden und Frisuren?

**Comment by germanmiles** [comment]
hauptsächlich für frauen und bei meheren frisuren

**Comment by germanmiles** [comment]
ja 2 mal beim selben char Name Emilia_Rizzoli

**Comment by DonJohn1993** [comment]
Bei uns war es wie oben beschrieben selbe Spielerinn, selbe Frisur:

Rachel_Miller
20.4.2024, 00:05:32 normaler Versuch

20.4.2024, 00:38:02 müsste der erneute Versuch gewesen sein. Gleiches Ergebnis. Siehe Frisur Bild

Zwischen beiden Schnitten wurde eine andere versucht, die war dann komplett random.

**Comment by germanmiles** [comment]
ja hab 1 mal geschnitten dann kahm eine random frisur dann nochmal  versucht dann error meldung und dann eine andere probiert die ging dann

**Comment by Xymena** [comment]
Bei mir war es Palina_Pavlova hatte versucht Curled Sidesept zu schneiden es kamm dabei der Kurzhaarschnitt raus 
![image](https://github.com/eiksch/statev_v3_issues/assets/76626768/fe2963e7-340a-4c13-82cd-bb9b58b94027)
Wo ich dann habe erneut zu schneiden auch fehlermeldung, beim versuch eine andere zu schneiden ging es zwar aber die "beschreibung" in der rechnung war anders als der name von Schnitt

**Comment by germanmiles** [comment]
ja bei mir war es eine andere frisur hab aber grade keine weibliche person wo ich nochmal nachschauen kann

**Comment by germanmiles** [comment]
nächste frisur macht probleme diesmal bei männern der CLB Buzz Cut

**Comment by simplycach** [comment]
Next Update fixed.
