### ISSUE TITLE
Casino BlackJack Buggy

### ISSUE THREAD

**Issue by ZyroC1337** [mexyn/statev_v2_issues#3324]
Akin Chambers

Auftrittszeitpunkt 20.04 | 04:09

Beobachtetes Verhalten
Casino BlackJack Buggy

Ich musste mehrmals neu verbinden, weil ich am Blackjack-Tisch im Casino spielen wollte und das Spiel sich ständig aufgehängt hat. Sobald ich mich erneut hinsetzte, fing das Problem von vorne an.
![4fafba928cc45360303e129fdbb00fc7](https://github.com/eiksch/statev_v3_issues/assets/167593745/6e781629-a7ef-4633-8113-df20bc1d1f3f)

**Comment by simplycach** [comment]
Bereits offen https://github.com/eiksch/statev_v3_issues/issues/3112
