### ISSUE TITLE
Weinreben 

### ISSUE THREAD

**Issue by DerKumo** [mexyn/statev_v2_issues#3325]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Character Name
Marc Pfennig

Auftrittszeitpunkt (Datum / Uhrzeit)

Am 20.04.2024 mitbekommen

Beobachtetes Verhalten
Wenn ich den Harmony Fruit Market auf mache habe ich dort nicht mehr die Möglichkeiten die Weinreben zu Verarbeiten.

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/96928264/5f706225-8f7c-44d5-a043-570f17469836)
![image](https://github.com/eiksch/statev_v3_issues/assets/96928264/a5814a39-5500-445a-a31b-45246597a0a3)
![image](https://github.com/eiksch/statev_v3_issues/assets/96928264/b0e914cf-6652-43ed-94d7-b13942e897c4)

**Comment by simplycach** [comment]
Ist kein Bug
