### ISSUE TITLE
Marker Überschneidung

### ISSUE THREAD

**Issue by Eve-Noxito** [mexyn/statev_v2_issues#3326]
Crime Mission von San Antonio am Yellow Jack Inn

Charakter Name: Betty Flynn
Hab eben ne Mission von San Antonio angenommen und wurde zum Yellow Jack Inn geschickt.
Seit wir dort unser Hotel haben, überschneiden sich leider der Missionsmarker und die Hotelübersicht und man kann die Mission nicht abschließen
Hab versucht auch aus einiger Entfernung Zugriff zum Missionsmarker zu bekommen, aber keine Chance... 
![image9](https://github.com/eiksch/statev_v3_issues/assets/74910428/ec91d88b-3f21-4ceb-b4ee-4ff5feffc240)

**Comment by l4m4rr224** [comment]
Fixed next Update
