### ISSUE TITLE
Abladepunkt verschieben/zusammenlegen

### ISSUE THREAD

**Issue by StateVSergio** [mexyn/statev_v2_issues#3327]
Liam Dixon

![Screenshot 2024-04-13 151203](https://github.com/eiksch/statev_v3_issues/assets/97253629/40457438-bbfe-4f85-b887-26011f4f89a3)

Bild 1 dort wo der MTL steht ist der Abladepunkt

Hash | pf_MurrietaHights_33
Mirror Park Blvd. 36

![Screenshot 2024-04-13 144938](https://github.com/eiksch/statev_v3_issues/assets/97253629/b140c061-5f23-4615-9f15-6c7fdb706192)

Bild 2

Hash | petrolstation10
West Mirror Drive 34b

Roter Punkt -> aktueller Abladepunkt
Grüner Punkt -> neuer Abladepunkt für beide Firmen

Es wäre toll wenn man die Abladepunkte so legen könnte da die Fahrzeuge auf der Hauptstraße sehr schnell vorbei fahren und wenn ich dort rückwärts hin und her rangiere ist das Unfallrisiko sehr hoch.

Außerdem befindet sich der Tank genau zwischen den beiden Objekten.

Mit freundlichen Grüßen
Sergio

**Comment by Erumeldor** [comment]
Abladepunkte zusammenlegen machen wir nicht.
Außerdem gehört der Abladepunkt der Tankstelle auch auf das Gelände der Tankstelle rüber, und nicht zum Nachbargelände. Der müsste also da drüben bleiben.

Gibt es denn ein Problem mit dem Abladepunkt der Firma aktuell?

**Comment by StateVSergio** [comment]
Alles klar schade und nein gibt es nicht.

**Comment by Erumeldor** [comment]
Alles klar, dann mach ich hier wieder zu.
