### ISSUE TITLE
Hoodie Crop Top kein passender Oberkörper

### ISSUE THREAD

**Issue by LottiFoxy** [mexyn/statev_v2_issues#3329]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Caroline Hovenkoven

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit Update 3.0 (Neue Kleidung)

**Beobachtetes Verhalten**
Female Oberteil Hoodie Crop Top hat keinen passenden Oberkörper - Egal welchen man wählt die Haut bugt durch

**Erwartetes Verhalten**
passende Torsoeinstellung

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![Screenshot 2024-04-20 175902](https://github.com/eiksch/statev_v3_issues/assets/166732305/c899df94-cf87-4f1d-a4b0-832cb5b6ea55)
![GTA5 2024-04-20 17-58-51](https://github.com/eiksch/statev_v3_issues/assets/166732305/a6ae2070-09cc-4510-8a6a-eb09a99ce8cd)
![GTA5 2024-04-20 17-58-45](https://github.com/eiksch/statev_v3_issues/assets/166732305/94643e52-7887-4e24-8da0-ceecb7bd428d)
![GTA5 2024-04-20 17-58-35](https://github.com/eiksch/statev_v3_issues/assets/166732305/bae022f6-9634-403c-91f3-9ba60507e6dd)

**Comment by SauerkirscheJM** [comment]
Das selbe Problem besteht bei dem Oberteil **[F] Navy-Black Sweatjacke**. Die passenste Option hat oben an den Schultern einen Streifen durchsichtig
![GTA5 2024-04-21 01-46-30](https://github.com/eiksch/statev_v3_issues/assets/123385988/90a245f9-05aa-4ecc-b2b5-349bc74d8c0e)
![GTA5 2024-04-21 01-49-14](https://github.com/eiksch/statev_v3_issues/assets/123385988/0f2a0c0c-e93f-4c52-8d24-3b93d06825ae)
Ist auf beiden Seiten, rechts sieht man es besser.

**Comment by Nuuki900** [comment]
Selbes Problem auch beim Cropped Laced Sweater. Die passenste Lösung wäre hier von vorn "Ärmellos 7" - aber auch da bugt hinten sehr viel Haut durch.

![Screenshot_41](https://github.com/eiksch/statev_v3_issues/assets/70228263/cb8f0048-88fd-4e4a-9872-4c10d3c6d271)
![Screenshot_42](https://github.com/eiksch/statev_v3_issues/assets/70228263/b9ff862d-a19c-4346-8516-759de53f823a)

**Comment by ySimbaa** [comment]
1. Top ist raus.
2. Top ist aktuell leider nicht änderbar, wird sich aber nochmal angeschaut.
3. Top ist raus.
