### ISSUE TITLE
Erste Hilfe Kurs - Tattoo -Laser

### ISSUE THREAD

**Issue by EmilyGrant01** [mexyn/statev_v2_issues#333]
In das MD kommen viele aus den Tattoo Läden und fragen nach einem Erste Hilf Kurs damit sie Laser können., Der "Normale" Erste Hilfe Kurs Schein den alle besitzten funktioniert nicht. Gibt es diebzgl. einen Neuen? Muss das MD dieses austellen?

Laser können dadruch nicht eingesetzt werden

**Comment by its4l3x** [comment]
Ne, der normale Erste Hilfe Kurs wird benötigt. Kein Sonderkurs o.Ä.

Gab aber einen Fehler. Habe das fix behoben.

**Comment by EmilyGrant01** [comment]
Danke

Alex D. <notifications@github.com> schrieb am Sa., 21. Nov. 2020, 19:45:
