### ISSUE TITLE
Skill Fortschritt Bug

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3330]
Carlo_ Sossa

Hallo... mein skill fortschritt ist seid dem erlangen eines major points verbugt und es gibt keinen fortschritt mehr (bleibt bei 0.00% stehen)...

![Screenshot_6](https://github.com/eiksch/statev_v3_issues/assets/70241137/87e03594-ce24-45be-a1fd-b1a971ec5271)

**Comment by Statev-Bonsai** [comment]
jetzt geht der fortschritt wieder, aber er war stundenlang auf 0%..

**Comment by DrGrizzlY17** [comment]
@Statev-Bonsai Kann sein das du eigentlich ein Level drunter gewesen wärst durch unsere Änderung, aber ich glaube das die UI dich nicht mehr runter setzt und erst updatet wenn du wieder soweit wärst

**Comment by DrGrizzlY17** [comment]
@simplycach close pls
