### ISSUE TITLE
Weberei Skalierungsproblem Maschinen UI

### ISSUE THREAD

**Issue by PepperBella** [mexyn/statev_v2_issues#3331]
Weberei Skalierungsproblem Maschinen UI 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit V 3.1.0

**Beobachtetes Verhalten**
Weberei Computer in der Spalte "Einkauf" gibt es bei meiner UltraWidescreen Auflösung ein Problem. Preise können deswegen nicht mehr eingetragen werden.  Desweiteren ist in der linken Spalte ein viel zu grosses placeholder pic.

**Erwartetes Verhalten**
Es sollte korrekt dargestellt werden

**Monitorauflösung**
2560 x 1080 Pixel UltraWide21/9

**Bilder des Fehlers**

![20240421124605_1](https://github.com/eiksch/statev_v3_issues/assets/80678852/29df8cc4-7b88-402a-98fe-527d04b8748b)

![20240421123746_1](https://github.com/eiksch/statev_v3_issues/assets/80678852/193c65db-9097-47b4-b74f-037c37f449ad)

**Comment by Erumeldor** [comment]
Kannst du mal versuchen, alle Taschen und Rucksäcke rauszunehmen, und zu schauen ob es dann immer noch Probleme macht?

**Comment by PepperBella** [comment]
Da ist nichts dergleichen in der Maschine oder im Lager und war auch in der letzten Zeit nicht

![20240422131234_1](https://github.com/eiksch/statev_v3_issues/assets/80678852/98581e28-47f9-425a-b5c5-54e06d1a8e88)
![20240422131249_1](https://github.com/eiksch/statev_v3_issues/assets/80678852/106a252c-a9a0-4923-8ff7-2b226e1d19b4)
![20240422131427_1](https://github.com/eiksch/statev_v3_issues/assets/80678852/e7386abe-525b-4aba-aa68-3635f83adc6f)

**Comment by simplycach** [comment]
Konnte bisher nicht reproduziert werden, vmtl. nen Monitor Ding.
