### ISSUE TITLE
Geldkasseten Mission Buggy bei Dmitry

### ISSUE THREAD

**Issue by GoatJuan** [mexyn/statev_v2_issues#3332]
Mateo_Morello

https://medal.tv/games/gta-v/clips/28KtDYeManqJve/d1337nEX9KrE?invite=cr-MSxvb2ksMjcyMTYxNjMs

Mission wird nicht gestartet

**Comment by hollyfizzu** [comment]
Auch Box Liefermissionen starten nicht

**Comment by simplycach** [comment]
Also bei mir funktionieren die Einwandfrei, ist der Fehler nochmal aufgetreten ?

**Comment by hollyfizzu** [comment]
Hab vorhin probiert, passiert gar nichts, geht nicht

**Comment by simplycach** [comment]
Kommt eine Fehlermeldung in der F8 Konsole =?

**Comment by simplycach** [comment]
Ist next Update fixed.

**Comment by simplycach** [comment]
Next Update fixed
