### ISSUE TITLE
Interaktionspunkt bei Mission von Mistique fehlt

### ISSUE THREAD

**Issue by DerKryptex** [mexyn/statev_v2_issues#3333]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Otiz_Walker

Ausgelöst durch das annehmen einer Mission von Mistique, beobachtet durch den Versuch die Mission zu erledigen

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.04.2024, 12:59 Uhr

**Beobachtetes Verhalten**
Der Interaktionspunkt ist nicht auffindbar, kein Stromkasten, Garagentor, Ölhahn etc. war zum interagieren bereit

**Erwartetes Verhalten**
Interaktionspunkt an Gragentor oder Stromkasten 

**Schritte um den Fehler nachvollziehen zu können**
Mission bei Mistique annehmen, zum Ziel fahren und Zeuge werden das man nichts findet 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
16:9 , 1920x1080

**Optional: Video / Bilder des Fehlers**
![Screenshot_4](https://github.com/eiksch/statev_v3_issues/assets/112831071/5281cd63-a2f3-4223-abb7-022097df79db)
![Screenshot_3](https://github.com/eiksch/statev_v3_issues/assets/112831071/090c6877-932c-48cc-8ad0-0db4a17dbd7a)
![Screenshot_1](https://github.com/eiksch/statev_v3_issues/assets/112831071/6078c021-aaed-4d03-bf7b-3bf78aee6b5a)
![Screenshot_5](https://github.com/eiksch/statev_v3_issues/assets/112831071/14559db4-bc59-4615-a7ef-0014833d9109)
![Screenshot_6](https://github.com/eiksch/statev_v3_issues/assets/112831071/b45819b2-4ac5-47b0-86f3-c802798de4bd)

**Comment by Rehki** [comment]
Das ist schon richtig so ;) Hatte die Mission gestern auch
