### ISSUE TITLE
Mystique Auftrag verbuggt

### ISSUE THREAD

**Issue by Elfenblut** [mexyn/statev_v2_issues#3334]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Charaktername**
Valea Machiavelli 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14:50 Uhr am 22.04 

**Beobachtetes Verhalten**
Mystique Auftrag scheint verbuggt zu sein, am Ort wird großflächig drumherum keine Möglichkeit zur Interaktion gefunden. 

**Erwartetes Verhalten**
 Interagieren können wie bei den anderen Aufträgen 

**Schritte um den Fehler nachvollziehen zu können**
Im Anhang befindet sich der Auftrag + Location 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
 Beschreibe Schritt für Schritt wie man den Fehler nachstellen kann 

**Optional: Video / Bilder des Fehlers**
Anhang vorhanden 

https://cdn.discordapp.com/attachments/1231949570829844560/1231950672279371827/image.png?ex=6638d278&is=66265d78&hm=7928f1b1fd92bf8767378cf4ef399f9fa40fc4c4907166c4c18c23e325ead8eb&

https://cdn.discordapp.com/attachments/1231949570829844560/1231949898958504006/image.png?ex=6627ae40&is=66265cc0&hm=979abe3c6e7f65185d5197500d489f2d48a0dab216fe9db779a41095470a3ee3&

**Comment by SatyriaDine** [comment]
Kein Bug. :) Manchmal muss man auch mal "hoch hinaus" :)
