### ISSUE TITLE
Minimap blendet nicht mehr aus im Fahrzeug

### ISSUE THREAD

**Issue by FLVFFY1** [mexyn/statev_v2_issues#3336]
**Jayden_Banks**

**Seit dem Update V 3.1.0**

**Beobachtetes Verhalten**
Das drücken von "#" blendet nicht mehr die Minimap im Auto aus.

**Erwartetes Verhalten**
Minimap sollte auch dort wie gewohnt ausgeblendet werden

**Schritte um den Fehler nachvollziehen zu können**
Ins auto setzen, "#" drücken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
2560*1440

**Optional: Video / Bilder des Fehlers**
https://imgur.com/a/zg6eN97

**Comment by SHaagmann** [comment]
Liegt an der Option "Minimap ausblenden zu Fuß" wenn dies nicht aktiv ist geht es ohne Probleme

**Comment by simplycach** [comment]
Next Update fixed
