### ISSUE TITLE
Automaten-Raub gibt keine ausbeute

### ISSUE THREAD

**Issue by DerKryptex** [mexyn/statev_v2_issues#3337]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Otiz_Walker

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.04.2024, 15:30 Uhr - 16:00 Uhr

**Beobachtetes Verhalten**
Automaten-Raub mit Brecheisen angefangen, nach einiger Zeit bricht die Animation ab und man bekommt kein Geld und keine Geldkasetten, Automat war bei erneuten Versuch des Raubes als ausgeraubt markiert

**Erwartetes Verhalten**
Automaten-Raub anfangen mit Brecheisen und nach einigerzeit öffnet sich das Geldfach zum entnehmen des Geldes und Kasette

**Schritte um den Fehler nachvollziehen zu können**
Brecheisen ins Inventar, Automat ausrauben, auf Beute warten

Folgende Automaten wurden versucht auszurauben:

- Fleeca Bank Lifeinvader, Postcode: 5146
- öffentliche Garage "rotes Parkhaus" Postcode: 3201, an Hauptstraße
- Stadtpark west-seite, Postcode: 3208

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
nicht vorhanden

**Comment by simplycach** [comment]
Also ich habe es gerade mal getestet und bei mir funktioniert das ohne Probleme, hast du mal ein Video wenn ja bitte hier mal reinposten. Ich mach das erstmal zu.

**Comment by DerKryptex** [comment]
Hallo, ich habe nun heute nochmal 2 ausprobiert, habe bei beiden immer noch keine ausbeute bekommen und ich bekomme auch keine Meldung, dass es nicht geklappt hat, ich nichts gefunden habe oder sonst irgendwas vorliegt warum es nicht geht.

hier dazu das Video:

https://youtu.be/3hPnw3bP72E?si=N8L1JnJU1-Y7iMu7

Also bisher 5 Automaten mit dem selben ausgang, keine Meldung, keine Beute, kein Hinweis warum

**Comment by simplycach** [comment]
War die Brechstange im Rucksack oder in einer Tasche ?

**Comment by DerKryptex** [comment]
Sie war ganz normal in meinem Inventar

**Comment by DerKryptex** [comment]
was mir gerade noch eingefallen ist, bevor das Problem bestand und alles noch funktioniert hat, habe ich, während ich einen ATM ausgeraubt habe, mein Messer weggesteckt und die Brechstange ausgerüstet. Seit dem Automaten geht es auch nicht mehr, vielleicht habe ich dadurch etwas an meinem Charakter it-technisch kaputt gemacht.

Bei weiteren Fragen oder ähnlichem steh ich zur Verfügung, habe die Benachrichtigungen an und versuche so schnell wie möglich zu antworten :)

**Comment by simplycach** [comment]
Das erklärt das Problem, du darfst das Brecheisen nicht ausrüsten.

**Comment by DerKryptex** [comment]
Ja, das weiß ich nun auch, deswegen mache ich es auch nicht. Wie gesagt es liegt ganz normal in meinem Inventar, die ganze zeit über. 

Ich meinte damit, daß ich das EINMAL gemacht habe und ich das Problem seit dem habe OBWOHL ES IM INVENTAR LIEGT, also die ganze zeit ich mache nichts und drücke während des rauben nichts weiter, ich habe nur das diesen Bug seit ich es einmal gemacht habe.

Also Brechstange ist im Inventar, ich raube aus, Brechstange bleibt im Inventar, ich mache nichts, Animation hört auf (wie im video), ich bekomme nichts....


Bitte schauen Sie es sich an, da ich aktuell nicht in der Lage bin ATM Beute zu bekommen.

**Comment by DerKryptex** [comment]
Ich werde heute nochmal ein Video drehen von Anfang bis Ende und auch mein Inventar zeigen alles, damit Sie sehen können, dass hier ein Fehler vorliegen muss... vielleicht erkläre ich mich auch schlecht oder keine ahnung. Ich hoffe Sie schauen es sich nochmal an, weil der Fehler besteht, seit ich einmal die Waffe gewechselt habe, nicht weil ich das ständig mache beim ausrauben

**Comment by Stiefel911** [comment]
Du brauchst eine neue Brechstange, diese ist dafür nicht mehr verwendbar, sofern sie einmal angelegt wurde.

So long

**Comment by DerKryptex** [comment]
Okay ich werde es probieren, danke, wusste ich nicht
