### ISSUE TITLE
Carlos Motorrad Missions Punkt nicht sichtbar

### ISSUE THREAD

**Issue by SirAres** [mexyn/statev_v2_issues#3338]
Character Name

Tony Mastavic

Auftrittszeitpunkt (Datum / Uhrzeit)
23.02.2024 16:35

Beobachtetes Verhalten

Carlos Motorrad Mission Garagenpunkt nicht vorhanden 

Erwartetes Verhalten

Der Punkt sollte da sein

Schritte um den Fehler nachvollziehen zu können

Carlos Motorrad Diebstahl Mission wählen und dahin fahren.

**Optional: Video / Bilder des Fehlers**
![BUG_Track_1](https://github.com/eiksch/statev_v3_issues/assets/87204556/765b119a-aa5e-48aa-8394-7e3bba535aae)
![BUG_Track_2](https://github.com/eiksch/statev_v3_issues/assets/87204556/173b63eb-42e2-4c05-9ad1-28fc65d17610)
![Bug_Track_3](https://github.com/eiksch/statev_v3_issues/assets/87204556/ed7ed5dd-f062-45e8-9db9-ef4cae4895e4)

**Comment by SirAres** [comment]
![BUG_Track_1](https://github.com/eiksch/statev_v3_issues/assets/87204556/51cf2fc2-7a67-4cc4-9a81-d6074c4d5583)
![BUG_Track_2](https://github.com/eiksch/statev_v3_issues/assets/87204556/e1634ced-d84f-430a-8d4f-eb208cab9bb3)
![Bug_Track_3 - Kopie](https://github.com/eiksch/statev_v3_issues/assets/87204556/586dffaa-c4b6-4350-b0ff-b457f48fb49a)

Bei den Bilder gibs glaube ich ein paar Problemchen, daher hier Hoffentlich nochmal richtig

**Comment by TheOutburst** [comment]
![grafik](https://github.com/eiksch/statev_v3_issues/assets/70150675/026ac361-57b3-47b3-b190-32d4e9f2ae43)
Also... weiß nicht ob du Marker aus hast oder auf F6 gekommen bist, aber ich kann das leider nicht reproduzieren
