### ISSUE TITLE
Dinka Akuma hintere Felge nicht tauschbar

### ISSUE THREAD

**Issue by FLVFFY1** [mexyn/statev_v2_issues#3339]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Jayden_Banks**

**23.04. 18:40**

**Beobachtetes Verhalten**
Beim tuning aufgeffalen, dass man nur das vorrderrad ändern kann, nicht das hinterrad
**Erwartetes Verhalten**
Beide Felgen tauschbar

**Schritte um den Fehler nachvollziehen zu können**
Akuma zum tuner bringen, felgen tauschen

**Comment by QA-Pregon** [comment]
Ist ein GTA Problem, was aber vielleicht lösbar ist.
Das Problem ist, dass Standard GTA in Vorder- und Hinterreifen Tuning unterscheidet und die Felgen individuell anpassbar sind. (Also eben nicht wie bei Autos)

**Comment by FLVFFY1** [comment]
würd ja mal laienhaft behaupten das man einfach sagt wenn man so wie es aktuell ist den vorderreifen ändert automatisch der hintere mitgesetzt wird. 
Also ein slot weiter vorne = ein slot weiter hinten.

**Comment by QA-Pregon** [comment]
Hab ich so auch den Devs vorgeschlagen, mal sehen wann und wie die sich da entscheiden
Ich kann da nicht mehr machen als es weitergeben ^^
