### ISSUE TITLE
Unsichtbar Bewusstlos

### ISSUE THREAD

**Issue by PrimroseBloom** [mexyn/statev_v2_issues#334]
**Primrose Bloom und Arnaldo Bloom**

**21.11.2020 um 18:32 Uhr**

**Bewusstloser war unsichtbar**

**Ein Bewusstloser liegt auf dem Boden**

**Arnaldo Bloom hatte einen Unfall und war Bewusstlos. Ich und 4 Medics haben ihn nicht gesehen**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Arnaldo Blooms Ansicht
![](https://cdn.discordapp.com/attachments/684073477279580220/779763603586285588/unknown.png)

Primrose Blooms Ansicht
![](https://cdn.discordapp.com/attachments/684073477279580220/779763792024043620/unknown.png)**

**Comment by tastydev** [comment]
liegt am momentan branch ist in zukunftügen alt:V updates gefixt

**Comment by DonVitoDiangelo** [comment]
Hat sich das Problem mittlerweile gelegt?

**Comment by DonVitoDiangelo** [comment]
Falls sich hier etwas neues ergibt bitte neu öffnen. Problem sollte soweit behoben sein.
