### ISSUE TITLE
VCAD nur ein Dispatcher möglich

### ISSUE THREAD

**Issue by FLVFFY1** [mexyn/statev_v2_issues#3340]
**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.04.2024 15:00
**Beobachtetes Verhalten**
Im VCAD lässt sich nur noch ein Dispatcher eintragen

**Erwartetes Verhalten**
Mehrere Eintragungen sollten möglich sein

**Schritte um den Fehler nachvollziehen zu können**
Versuchen als 2. Dispatcher einzutragen

**Optional: Video / Bilder des Fehlers**
https://imgur.com/a/KWOTKKN

**Comment by QA-Pregon** [comment]
fixed
