### ISSUE TITLE
Verlegung des Abladepunkts

### ISSUE THREAD

**Issue by UNST4BL3** [mexyn/statev_v2_issues#3341]
Wie bereits im Titel beschrieben soll der Abladepunkt von hinter dem Gebäude nach vorne verlegt werden.
Gegebenenfalls siehe Bilder

Char: Markus_Ackermann
Firmengebäude: pf_paletobay_8

Aktuelle Position
![Screenshot_4](https://github.com/eiksch/statev_v3_issues/assets/42190810/613df447-69ef-4d5b-8ab2-037d0abe27ed)

Neue Position
![Screenshot_6](https://github.com/eiksch/statev_v3_issues/assets/42190810/01a09bc0-e26e-496a-91c9-254d7be693fd)

**Comment by Erumeldor** [comment]
Ist im nächsten Update nach vorne verlegt - hinten sind schon genügend Abladepunkte.
