### ISSUE TITLE
Stantastic Frisur leicht buggy

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#3342]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Nicht Broady / James Carter (Insider mit Nytech)

**Auftrittszeitpunkt (Datum / Uhrzeit)**
/

**Beobachtetes Verhalten**
Wenn es Nebelig ist, oder bspw die Kam richtung licht dreht kommt es immer wieder vor, dass das Volument der Frisur unsichtbar wird. Siehe Bilder
Mir ist bewusst, dass es low Prio ist, aber sieht dennoch unschön aus und hoffe auf einen Fix <3

**Erwartetes Verhalten**
Wie alle anderen Frisuren nicht unsichtbar werden

**Schritte um den Fehler nachvollziehen zu können**
Frisur haben und mal gegens licht/Neben drehen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/70150887/6ca404ba-b661-4a80-a232-a3016b3b922d)

**Comment by TheBroady** [comment]
![image](https://github.com/eiksch/statev_v3_issues/assets/70150887/7fb28d88-65cd-475d-87b9-6e80aa026a91)
Bspw: in der Werkstatt Synergy Customs
Inzwischen habe ich auch nur noch Reshade drin.

**Comment by ySimbaa** [comment]
Das liegt an der Mod an sich. Da kann man leider nichts machen.
