### ISSUE TITLE
Abladepunkt versetzen

### ISSUE THREAD

**Issue by MarcGibbs** [mexyn/statev_v2_issues#3344]
Hallo, 
ich würde gerne den Abladepunkt von Links an der Seite des Gebäudes nach vorn an die Front des Gebäudes legen lassen. Da es schon recht schwer ist mit dem MTL zwischen Zaun und gebäude zu fahren wegen dem Vordach. Mit einem Phantom und einem Tanker dazu wird es beinahe unmöglich. 
Daher würde ich gern den Abladepunkt an die Front des Gebäudes verlegen. Dort stört man den Verkehr nicht und kann in ruhe abladen und beladen. 
![Screenshot_20](https://github.com/eiksch/statev_v3_issues/assets/168035262/5c956aa6-0e53-42da-8c0d-0b9e9e3cd2a9)

![Screenshot_19](https://github.com/eiksch/statev_v3_issues/assets/168035262/55a3c84e-5cf0-4cc8-9657-f92274b6aa50)

**Comment by Erumeldor** [comment]
Nächstes Update ist er vorne am Tor :)
