### ISSUE TITLE
Geschwindigkeit Hauler (Zugmaschine)

### ISSUE THREAD

**Issue by BobbyCarsten** [mexyn/statev_v2_issues#3347]
**Character Name**
Bobic Madujew

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer 

**Beobachtetes Verhalten**
Die Zugmaschine Hauler hat ohne Achse eine normale und moderate Beschleunigung und Geschwindigkeit, sobald man die Öl Achse ankoppelt schafft man gerade so mit Mühe, bergab und Rückenwind 80-86km/h / bergauf 45-52 km/h Maximum / Sand und Nebenstrecken auch 40-51 km/h 
**Erwartetes Verhalten**
Eine leicht verbesserte Geschwindigkeit mit angekoppelter Achse generell / bergauf / Sand und Nebenstrecken.

**Schritte um den Fehler nachvollziehen zu können**
In Hauler steigen und Öl Achse ankoppeln über das Ölfeld fahren oder am Marktplatz bei Harmony Richtung Stadt fahren.

**Comment by Stiefel911** [comment]
Leider ist es normal. Liegt an dem Öl-Auflieger, dieser scheint extrem schwer zu sein.. war eh und je schon so. Mit anderen wirst du feststellen ist es nicht so.. Und es ist auch egal welche Zugmaschine davor sich befindet. ;)

**Comment by Erumeldor** [comment]
Das was Stiefel schreibt stimmt schon ziemlich.

Tatsächlich ist das so Extrem ein Problem des Haulers - nur der hat so extreme Probleme mit dem Öl-Trailer.
Kann ich aktuell leider auch nur empfehlen für Öl auf einen anderen Truck zu wechseln.. :/

**Comment by BobbyCarsten** [comment]
Na klasse … naja .. wird als besser

**Comment by BobbyCarsten** [comment]
Wenn’s nicht fixabel ist besteht die Möglichkeit aufm Tausch bzw Erstattung ? Weil einfach so auf nen neuen lkw wechseln ist leichter gesagt als getan Geld kann ich leider nicht herzaubern

**Comment by BobbyCarsten** [comment]
Gibt’s dazu noch ne Rückmeldung oder wird da was gemacht oder ist es mit „musste auf nen anderen lkw wechseln“ beendet ? Weil einfach so auf nen neuen lkw wechseln gestaltet sich schwierig da man ja so schon 65k dafür ausgegeben musste. Und wie oben ja geschrieben wurde ist es ja ein Problem des haulers, deswegen könnte man ja schauen ob man es anpassen könnte

**Comment by BobbyCarsten** [comment]
@Stiefel911 habe es mal getestet Phantom 90-100 km/h / hvy semi Truck 85-95km/h beide jeweils bergauf 80km/h also nen spürbaren unterschied hat man definitiv.

**Comment by Erumeldor** [comment]
Wir haben dem Hauler mal etwas mehr Power gegeben. Er ist immer noch langsamer wie andere mit Öltrailer, aber zumindest ein gutes Stück besser.
Ist nächstes Update live.
