### ISSUE TITLE
Items verbrauchen sich nicht beim benutzen

### ISSUE THREAD

**Issue by KarlBergmann1** [mexyn/statev_v2_issues#3348]
**Character Name**
Jaro Brandtberg

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.04.24 13:23

**Beobachtetes Verhalten**
Auto an der Firma auf Verladepunkt geparkt, Erze ausgeladen und einen Akku aus dem Fahrzeug benutzt. Fehler: "Ungültiges Ziel oder Ursprung!" und Akku wurde nicht verbraucht. Der Gegenstand wird aber trotzdem verwendet (Handyakku ist wieder voll).

**Erwartetes Verhalten**
Akku sollte verbraucht werden

**Comment by KarlBergmann1** [comment]
Ist ein Dupingbarer Glitch. Wichtig zu fixen. Beispielsweise habe ich gerade eine Flasche Zitroneneistee getrunken und es werden Plastikflaschen ausgegeben, aber der Eistee nicht verbraucht. 

Uff.

**Comment by Tad3os** [comment]
Konnte den glitch leider nicht reproduzieren. Könntest du uns bitte wenn es möglich ist ein Video dazu machen wie es dazu kam?

**Comment by KarlBergmann1** [comment]
https://www.youtube.com/watch?v=AQIe0W7HpFk

**Comment by Tad3os** [comment]
ok es passiert nur wenn der kofferaum zu ist.

**Comment by QA-Pregon** [comment]
Next update fixxed
