### ISSUE TITLE
Halskette & Armband nicht gleichzeitig anziehbar!

### ISSUE THREAD

**Issue by ManuelLadner** [mexyn/statev_v2_issues#3350]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Manuel_Turner**

**jederzeit beim Anziehen**

**1 Item verschwindet wird unsichtbat wenn man das andere anzieht! beide haben einen extra slot und bleiben aber auch im slot**

**beide items sollten kombinierbar sein, weil die slots ja da sind!?**

**halskette anziehen dann ring oder armband anziehen**

**egal**

**keine bilder da leicht nachstellbar!**

**Comment by stepz2k9** [comment]
Halsketten und Ringe haben meist denselben Slot. Je nach Modder. Wird dir später bei Menyoo auch oft so gehen.

**Comment by BobbyCarsten** [comment]
Zu v2 hat das alles super geklappt konntest Ohrringe Armband Ring und Kette anziehen …. Ring war auf dem Masken Slot zu v2 …

**Comment by stepz2k9** [comment]
Jein. Männer schon. Frauen nicht, es gab viele Ohrringe, mit denen man keine Kette tragen konnte. Man kann jetzt auch als Frau nur noch Bauchnabelpiercing oder Nase. Nicht mehr beides. Das hat alles Gründe. Ist schlecht nachvollziehbar, wenn man nur von außen drauf guckt. Aber dadurch, dass ich menyoo mache, kenne ich den struggle mit den ganzen Slots für Kleidung (dazu gehört Schmuck auch). Ist nicht so einfach wie es scheint.

**Comment by ManuelLadner** [comment]
vielleicht kann man das ja wieder ändern wie auf v2??

**Comment by TheOutburst** [comment]
Ja das ist leider einfach so, GTA hat nur bestimmt viele Decals und da können wir auch nicht wirklich was dran ändern, sorry
