### ISSUE TITLE
Tow-Truck greift Fahrzeuge, meist Busse, nicht

### ISSUE THREAD

**Issue by BensiMusic** [mexyn/statev_v2_issues#3351]
Jayson Baker
26.04.2024, 22:50

Ich bin Abschleppen mit dem Tow-Truck und kann keine Busse greifen. Der Haken fährt wie gewohnt runter, am Fahrzeug hakt dieser aber nicht ein, sondern macht einfach gar nichts. Manchmal klappt es, ganz normal wie es sollte, manchmal macht er einfach garnichts, wie in diesem Fall. 
Aber: NUR BEI BUSSEN! (bislang)
An Autos war es bisher kein Problem, aber die Busse gehen nicht. (evtl. wegen staatseigentum oder sowas)
Vor 1,5 Wochen konnte ich noch Problemlos Busse schleppen, seither aber nicht mehr.
Seit v3.1 gehts nicht mehr.

erwartet: der tow-truck sollte busse wieder normal einhaken :)

1. TowTruck
2. an ein pkw/bus/lkw fahrem
3. haken runterlassen
4. ans fahrzeug fahren
5. glück haben dass es funktioniert.

video: 
https://youtube.com/clip/UgkxfcGBY93RT5Tblr_OmdwkLbVI4fyI1PkM?si=Q5Epb5a-q-g2KP-O

lieben gruß

**Comment by QA-Pregon** [comment]
Kam das ganze schon an anderen Fahrzeugen als Bussen vor oder bisher nur beim Bus?
Wenn auch anderen, dann welche?

**Comment by BensiMusic** [comment]
muss sagen, dass ich den Tow-Truck wenig benutze. Bei den Bussen klappt es, wie gesagt, seit ca. v3.1 nicht mehr. Bei PKWs hat's bisher eig. immer geklappt, bei LKW's hab ich es bis jetzt nie testen können. 
Busse klappen seit dem aber 100% nicht mehr.

**Comment by LottiFoxy** [comment]
Bei LKW (zumind den Tanklastern) is oft eher das Problem, dass man diese zwar gegriffen bekommen, aber nicht von der Stelle kommt. Als wenn die Handbremse angezogen wäre. Es braucht dann immer einige male an und abhaken ehe man vorwärts kommt. Wenn man dann aber den "Schwung" verliert, steckt man quasi wieder fest und muss von vorn anfangen mit rangieren und probieren. Andere LKW bisher keine Erfahrung mit. Bei Bussen hab ich die Erfahrung gemacht das es manchmal auch drauf ankommt wo/wie die stehen. Wenn die auf ner Schräge stehen tritt das Problem mMn eher auf, als wenn die Ebene flach/grade is und der Bus entsprechend grade steht

**Comment by DrGrizzlY17** [comment]
Ich behaupte stark das hier GTA das Problem ist und den Koppelvorgang blockiert. Wir blockieren es nämlich nicht :D
