### ISSUE TITLE
Loose Tee haben keinen passenden Oberkörper

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3352]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared/Sven Rosenbach
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Seit Release dieser Shirts in V2
**Beobachtetes Verhalten**

Wenn man die Loose Tees anzieht kann man nur zwischen Kurzarm 2 und 3 auswählen, wobei 2 zu kurz ist und 3 bei Animationen durchbuggt
**Erwartetes Verhalten**

Nen zwischenschritt währe cool der passt
**Schritte um den Fehler nachvollziehen zu können**

Shirt anziehen und rumprobieren
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

Kurzarm 2
![20240427104423_1](https://github.com/eiksch/statev_v3_issues/assets/58612983/d8f9c796-3e83-4177-a7dc-7a4ccfce84ae)
Kurzarm 3
![20240427104416_1](https://github.com/eiksch/statev_v3_issues/assets/58612983/7a8d713d-2190-4649-8603-7a3fb6c45bc0)

**Comment by ySimbaa** [comment]
Nicht änderbar. Modded Kleidung sind meist nicht für Animation gemacht und dadurch clippen manche Sachen einfach durch.
