### ISSUE TITLE
Accessoires Fehler Armband und Halskette

### ISSUE THREAD

**Issue by MaxiKamui** [mexyn/statev_v2_issues#3353]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Maxi Kamui**

**27.04.2024 15:00 **

**Wenn man die Halskette bei Männern anzieht, sieht man das Armband nicht. Wenn man das Armband anzieht sieht man die Halskette nicht mehr. **

**Man sollte beide Accessoires sehen können gleichzeitig**

**Beide Accessoires mal anziehen und dann gucken ob es nicht angezeigt wird**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![555](https://github.com/eiksch/statev_v3_issues/assets/168280521/ebfd3438-fc1e-4df8-a94a-5a010c87ff4a)

**Comment by SatyriaDine** [comment]
#3350
