### ISSUE TITLE
Koffer wird pro Login nur einmal angezeigt

### ISSUE THREAD

**Issue by quotenben** [mexyn/statev_v2_issues#3354]
**Auftrittszeitpunkt (Datum / Uhrzeit)**
durchgehend

**Beobachtetes Verhalten**
Nimmt man den Koffer das erste Mal mit Rechtsklick in die Hand, wird er ganz normal angezeigt. Lässt man ihn über "Animation abbrechen" wieder verschwinden, wird der Koffer für die gesamte Session nicht mehr angezeigt, wenn man ihn in die Hand nehmen möchte.

**Erwartetes Verhalten**
Das man den Koffer immer in die Hand nehmen kann.

**Schritte um den Fehler nachvollziehen zu können**
Koffer das erste Mal mit Rechtsklick in die Hand nehmen > funktioniert
Nachdem zurücklegen erneut versuchen > funktioniert nicht

**Comment by simplycach** [comment]
Next update fixed
