### ISSUE TITLE
Steuer bei Abhebung Bargeld fehlt

### ISSUE THREAD

**Issue by LeaBrandt** [mexyn/statev_v2_issues#3356]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Ronja Brandtberg 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit 27.04. bis aktuell

**Beobachtetes Verhalten**
Beim Abheben am Geldautomaten wird zwar angezeigt, dass 5% Steuern berechnet werden, aber auf dem Konto wird die Bargeldsumme 1:1 abgehoben. 

**Erwartetes Verhalten**
5% Steuern werden mitberechnet.

**Schritte um den Fehler nachvollziehen zu können**
Geld am Automaten abheben.

**Optional: Video / Bilder des Fehlers**

https://github.com/eiksch/statev_v3_issues/assets/98689462/14149375-a3a9-4e93-886c-0e49a692cbb2

**Comment by epichalt** [comment]
Du hattest 848$. Hast 100$ abgehoben.
hattest danach 743$ auf dem Konto. 

Also gingen 100$ + 5$ Steuern ab.

**Comment by LeaBrandt** [comment]
Ok...dann ist die Darstellung auf dem Konto nur falsch, weil dort nicht -100 $ , sondern -105$ angezeigt werden müssten

**Comment by QA-Pregon** [comment]
Wurde ins Quality of Life aufgenommen und wird behoben (wird dann in einem entsprechendem Change-Log dabei stehen, wenn es fertig ist)
