### ISSUE TITLE
Tattoo Lasern funktioniert nicht

### ISSUE THREAD

**Issue by Vastouuu** [mexyn/statev_v2_issues#3357]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Tyler_Jackson
**Auftrittszeitpunkt (Datum / Uhrzeit)**

28.04.2024 15:50 Uhr
**Beobachtetes Verhalten**

Das Lasern funktioniert nicht ,weil es kommt ein Fehler das der Betrag über 0 sein muss. Obwohl wir 1$ 2$ und 100$ probiert hatten. Der Fehler kam jedesmal.
**Erwartetes Verhalten**

Das Lasern funktioniert dann ganz normal.
**Schritte um den Fehler nachvollziehen zu können**

Lasern probieren.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://pic.statev.de/image/image.HxvO6C

**Comment by simplycach** [comment]
Next Update fixed
