### ISSUE TITLE
Bitte um Versetzung des Ladepunkts

### ISSUE THREAD

**Issue by Auralein** [mexyn/statev_v2_issues#3358]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Holly Swan

**Beobachtetes Verhalten**

Abladepunkt wird meistens übersehen. Die Schilde werden oft angefahren/umgefahren.

**Erwartetes Verhalten**
Problemloses auffinden des Abladepunktes ohne beschädigte Schilde oder Autos.
Gerade Phantoms mit ihren Anhängern haben hier große Probleme.

**Optional: Video / Bilder des Fehlers**
![grafik](https://github.com/eiksch/statev_v3_issues/assets/76708950/74865798-fbc2-4a78-8f99-e63cfa8aced8)

Von da, nach daaa.

![grafik](https://github.com/eiksch/statev_v3_issues/assets/76708950/fbf06b21-b507-4894-b21a-aa25f824c14b)

oder hier

![grafik](https://github.com/eiksch/statev_v3_issues/assets/76708950/9bf898f3-1e3d-4f81-87a0-ef362d28e7f0)

Hier Firma+Hash

![grafik](https://github.com/eiksch/statev_v3_issues/assets/76708950/27343e7f-4586-48a5-b439-eeefa19aac7f)

Vielen Dank <3

**Comment by Erumeldor** [comment]
Ich hab den Abladepunkt ein paar Meter von den Schildern entfernt. Auf die andere Seite, oder ins Feld wird er aber nicht kommen.
Ist dann mit dem nächsten Update live!
