### ISSUE TITLE
Loot Punkt noch da wenn Inventar voll

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3359]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared/Izaac Baker
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Vor 2 Tagen oder so und 29.04 20:47
**Beobachtetes Verhalten**

Beim Looten von Missionen, kommt die Message "Inventar ist Voll", wenn man was findet, was zu schwer ist und der Punkt bleibt stehen. Wenn man diesen dann erneut abbaut findet man nichts.
**Erwartetes Verhalten**

Entweder der Punkt verschwindet wieder in der Art "Pechgehabt" oder man bekommt das, was man Ursprünglich gefunden hätte.
**Schritte um den Fehler nachvollziehen zu können**

Mit fast vollem Inventar missionen machen und Pech im Glück haben
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

Video Folgt

**Comment by SHaagmann** [comment]
https://medal.tv/de/games/gta-v/clips/2afwC6YBpEHd90/d13374VXTGFs?invite=cr-MSw0czIsMjE3Nzc3MjI5LA

**Comment by TheOutburst** [comment]
Das ist so korrekt, da du beim zweiten Ausführen einfach pech hattest und nichts bekommen hast
