### ISSUE TITLE
Ampelschaltung dauert sehr lange

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#336]
**Character Name**
Jannik_Datsch

**Zeitpunkt (Datum / Uhrzeit)**
21.11 19:23

**Beobachtetes Verhalten**
Ampelschaltung dauert sehr lange. Während man in V1 i. d. R. die Chance von 50% hatte,dass die Ampel grün zeigt, ist es jetzt bei ca 20% da nicht nur meistens jede Ampel einzeln schaltet sondern es auch noch Fußgänger und Linksabbiegerphasen gibt. 

Das macht das Fahren in der Stadt zu einer sehr langwierigen Sache wenn man sich (auch aus RP Gründen) an die STVO halten will.

**Erwartetes Verhalten**
Bessere Ampelschaltung die einen nicht ewig an Ampeln warten lässt.     (Mir ist bekannt dass das mit AltV zusammenhängt und nicht direkt ein Bug ist)  

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
GTA/ALTV Verhalten. Nicht unser Problem.
