### ISSUE TITLE
Feature-Request: VAPI - eigener Marktplatz

### ISSUE THREAD

**Issue by ingo-lorenz** [mexyn/statev_v2_issues#3360]
Abfrage der eigenen Ein- und Verkäufe.

Es wäre von großem Nutzen, wenn man die Ein- und Verkäufe der eigenen Firma abfragen könnte, um so den Sinn einer Webseite zu erhöhen. Zum Beispiel Recycling und Lager (und sicher auch andere) könnten so besser ihr Business bespielen, da es momentan keinen Firmenfilter im Marktplatz gibt.

Vielen Dank.

**Comment by simplycach** [comment]
Vorschläge bitte nicht in den Bugtracker, am besten machst du dafür ein Ticket auf.
