### ISSUE TITLE
Drogenmissionen

### ISSUE THREAD

**Issue by RoyMckellar** [mexyn/statev_v2_issues#3361]
Eventuell ist das ein Bug.
Ich soll was liefern und habe aber nichts zu liefern.
https://www.youtube.com/watch?v=nb2zqVfpQJo

**Comment by simplycach** [comment]
Du musst die Tütchen auch schon im Inventar haben und nicht im Rucksack

**Comment by simplycach** [comment]
Also kein Bug

**Comment by RoyMckellar** [comment]
Warum im Rucksack? Ich habe keine Tütchen. Oder muss ich das Gras selber anbauen, trocknen und verpacken und dann kann ich seine Missionen machen? Dann ist es kein Bug

**Comment by simplycach** [comment]
Also du brauchst schon die Tütchen um sie überhaupt abgeben zu können.
