### ISSUE TITLE
moin

### ISSUE THREAD

**Issue by fridreich** [mexyn/statev_v2_issues#3362]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by fridreich** [comment]
moin würde gerne beitreten

**Comment by QA-Pregon** [comment]
Guten Morgen,
hier im Bugtracker sollen nur Bugs gemeldet werden.
Kläre dein Anliegen bitte per Ticket oder im Community Support auf dem Discord Server
https://discord.com/invite/statev
