### ISSUE TITLE
Erstellung Port Punkt zur Terasse

### ISSUE THREAD

**Issue by ManuelLadner** [mexyn/statev_v2_issues#3364]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Jessika_Jackson & Manuel _Turner**

**jederzeit**

**kein Port Punkt zur anderen Seite! (Terrasse)**

**Bitte um Erstellung eines Port Punktes zur Terrasse auf der anderen Seite damit diese genutzt und nicht übers Dach betreten werden muss. Auf den Bildern ersichtlich wäre es cool wenn der Eingang zur Terrasse in der Garage wäre, und der Ausgang dann auf der anderen Seite bei dieser Tür (siehe Foto Nr. 5)**

**ans Haus Fahren und übers Dach klettern zur Terrasse die wir sehr gern nutzen!**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**https://pic.statev.de/image/adresse.HxmeQD
   https://pic.statev.de/image/karte.HxrHXV
   https://pic.statev.de/image/eingang-fur-port.HxrIGg
   https://pic.statev.de/image/garage.HxrK5S
   https://pic.statev.de/image/ausgang-port-auf-terrasse.HxrWgm**

**Comment by ManuelLadner** [comment]
Hallo, was denkt ihr wann man damit rechnen kann?

glg Manu

**Comment by TheOutburst** [comment]
Wir machen keine neuen Portmarker mehr, sorry

**Comment by ManuelLadner** [comment]
aber wie macht man das rp technisch dann auf die terasse? immer übers dach steigen? ich streame deswegen garnicht mehr!
