### ISSUE TITLE
Versetzung Garagenpunkt..

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3365]
Ich würde mich freuen wenn der Garagenpunkt um 1m richtung Straße verschoben wird..
Warum?
Große Fahrzeuge buggen sich beim ausparken in das Tor und werden dadurch zerstört, hier im beispiel 6x6...
![Screenshot_13](https://github.com/eiksch/statev_v3_issues/assets/70241137/2322c589-7e9f-4ff5-be5e-6535595bdc85)

![Screenshot_14](https://github.com/eiksch/statev_v3_issues/assets/70241137/90e0001f-e9f7-437d-bded-622484a8a517)

**Comment by Erumeldor** [comment]
Nächstes Update bisschen verschoben :)
