### ISSUE TITLE
Keine Fehlermeldung bei Accounterstellung wenn Name bereits vergeben ist

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#3366]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Beobachtetes Verhalten**
Wenn man probiert einen Account zu erstellen, der Name aber bereits vergeben ist, gibt es keine Fehlermeldung.
Wurde mir gerade so im Support mitgeteilt.

**Erwartetes Verhalten**
Eine Fehlermeldung, um den Nutzer zu informieren.

**Comment by QA-Pregon** [comment]
Solved
