### ISSUE TITLE
Crime Starter Mission wird nicht fortgesetzt

### ISSUE THREAD

**Issue by ghost** [mexyn/statev_v2_issues#3367]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Joe_Bauer

**Auftrittszeitpunkt (Datum / Uhrzeit)**

26.04.2024,  Uhrzeit unbekannt 

**Beobachtetes Verhalten**

Crime Mission wird nicht fortgesetzt 

**Erwartetes Verhalten**

Crime Mission wird nach Besuch der öffentlichen Garage fortgesetzt

**Schritte um den Fehler nachvollziehen zu können**

Schwer zu reproduzieren, daher hier die Abfolge. Direkt nach Anmeldung und Gespräch mit dem ersten NPC auf dem Schiff hatte ich plötzlich keinen Sound mehr im Spiel. Während ich noch auf dem Schiff stand, habe ich mich dann ausgelogged. Nach dem wieder einloggen war ich direkt bewegungslos unter Wasser, was zum Tod geführt hat. Der Support hat mich dann im Wasser schwimmend wiederbelebt und ich habe begonnen die erste  Mission des NPC abzufahren, d.h. Fahrzeug Miete (BF Club) begonnen. Danach bin ich herumgefahren um ohne Erfolg die Ausweisstelle (City Hall) zu suchen. Danach habe ich die Mine entdeckt und habe begonnen etwas abzubauen. Auf Anraten anderer Minenarbeiter habe ich mir dann anstelle des BF Club einen Bravado Bison gemietet und den Club zurück gegeben. Als ich dann irgendwann eine SIM fürs Handy hatte, habe ich die SMS vom Auftraggeber gelesen und wollte in die Garage fahren. Dort habe ich das Auto erfolgreich eingeparkt und wieder ausparken lassen. Das Problem beginnt ab hier. Die auf der Karte hinterlegte Route führt mich ausschließlich nach 4033 zu der dortigen Garage, welche wohl die zweite Mission darstellt. Egal wie oft ich dort einparke, sie geht nicht weg und keine neue Mission startet.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by QA-Pregon** [comment]
Hat sich schon erledigt und Tutorial kann normal weiter gespielt werden.
