### ISSUE TITLE
Fahrzeug verschwindet bei Reparatur

### ISSUE THREAD

**Issue by ugi58** [mexyn/statev_v2_issues#3369]
https://github.com/eiksch/statev_v3_issues/assets/168770487/563fd270-2808-4f34-ba06-1ab9f1e21e5e

**Comment by ugi58** [comment]
Fahrzeug wurde mitten im Meer geortet vom Kunden.

**Comment by simplycach** [comment]
Scheint nen Einzefall zu sein, wenn der Fehler nochmal aufkommt. Bitte nochmal schreiben.
