### ISSUE TITLE
Skin / Folie von Fahrzeugen Random 

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#337]
**Character Name**
Jannik_Datsch

**Zeitpunkt (Datum / Uhrzeit)**
21.11 19:00

**Beobachtetes Verhalten**
RTW wechselt Skin, nachdem ich in Wohnung gehe und sie wieder verlasse

**Erwartetes Verhalten**
Der Skin bleibt gleich

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/5iH8G7MLRFE

**Comment by its4l3x** [comment]
Leider ein altV Problem. :/

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/735

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/301

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/850

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1080

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1175
