### ISSUE TITLE
Treppenhaus auf machen ;)

### ISSUE THREAD

**Issue by 9meister** [mexyn/statev_v2_issues#3370]
## WICHTIGE INFORMATION!!:

**Chiko_Snooze**

Wäre es möglich einen Port aufs Dach zu bekommen ?
So als wenn das Treppenhaus auf wäre.
![BMC Treppenhaus](https://github.com/eiksch/statev_v3_issues/assets/168065622/c751fa35-049e-4b17-9e71-774105879ef1)

**Comment by simplycach** [comment]
Eventuell kann man einem Port Punkt machen aber aufmachen geht da leider nicht. Das entscheidet aber das GD.

**Comment by TheOutburst** [comment]
Wir machen keine neuen Portmarker mehr, sorry
