### ISSUE TITLE
Tetris: Komplette reihen verschieben sich

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3371]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared 
**Auftrittszeitpunkt (Datum / Uhrzeit)**

03.05 ca 19:30
**Beobachtetes Verhalten**

Nach einer gewissen Zeit verschieben sich einfach alle Seiten und man hat kaum möglichkeit weiter zu spielen (ordentlich zumindest)
**Erwartetes Verhalten**

Die reihen verschieben sich nicht
**Schritte um den Fehler nachvollziehen zu können**

Tetris spielen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

Ich will meine Runde wieder bekommen 😒
https://medal.tv/games/gta-v/clips/2aXar5HZ3qDMZW/d1337TMHXi7v?invite=cr-MSxJTEMsMTk1NTEzMTMzLA

**Comment by simplycach** [comment]
Sven, hör auf Tetris zu spielen no Joke. Du machst alles kaputt :D

**Comment by SHaagmann** [comment]
> Sven, hör auf Tetris zu spielen no Joke. Du machst alles kaputt :D

Nein. Muss wieder Top1 werden und das geht nicht wenn ich nicht spiele. Zudem hatte ich den bug schon zu V2 und zum Teil schon bei so 30-50 da juckt es mich halt nur nicht xD

**Comment by Erumeldor** [comment]
Ähnlich dem hier:
https://github.com/eiksch/statev_v3_issues/issues/2856

**Comment by Erumeldor** [comment]
@SHaagmann 
Da neues Handy = Neues UI mach ich mal zu.
Wenn das nochmal auftritt, bitte nochmal melden / hier wieder öffnen! :)
