### ISSUE TITLE
Bremsanlage und Service Fehler beheben bei einer Akuma

### ISSUE THREAD

**Issue by Mausi117** [mexyn/statev_v2_issues#3372]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Lumina Dakota

**Auftrittszeitpunkt (Datum / Uhrzeit)**

02.05.2024 14:38

**Beobachtetes Verhalten**

Es wurde eine neue Bremsanlage eingekaut da meine Standartbremsen kaputt waren (verschleiß) nach dem Umbau hat der LSC Inhaber noch einmal ausgelesen und es wird immer noch angezeigt das die hintere Bremse defekt ist diese funktioniert auch nur minimal die andere funktioniert einwandfrei. Ich müsste nun rein theorätisch noch einmal einen Service durchführen für 1.6k damit der Fehler behoben ist.

**Erwartetes Verhalten**

Wenn man neue Bremsen einbaut das diese auch funktionieren. Es sind immerhin ja neue Bremsen =)

**Schritte um den Fehler nachvollziehen zu können**

Bremsen benutzen bis beim Auslesen diese als kaputt angezeigt werden dann neue einbauen lassen und dann noch einmal auslesen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=JiJNiYk5SJQ

**Comment by QA-Pregon** [comment]
Soweit ich das gerade überblicke gibt es beim auslesen bei dir einen Fehler. Diese sind in Werkstätten als Service zu beheben, dementsprechend hat der Werkstattmitarbeiter dir das falsche eingebaut (Tuning statt Service).
Ob und wie das ganze durch neue Bremsen beeinflusst werden soll weiß ich nicht, aber ich denke mal da hätte ein Service gemacht werden müssen.

@simplycach bitte da um Bestätigung zu

Kleiner Überblick dazu:
Bei dir stand in der Rechnung der Tuningbegriff "Bremsanlage"
![image](https://github.com/eiksch/statev_v3_issues/assets/75855042/ea4fbe84-0640-460a-ba0f-06146d761dd0)

Eigentlich hätte dastehen müssen vom Service "Bremsen hinten"
![image](https://github.com/eiksch/statev_v3_issues/assets/75855042/1089d008-d0b6-4b7e-a188-ca2d1f8dfb76)

**Comment by simplycach** [comment]
Also wenn ich das so richtig herauslese, hat der Herr dir nur eine andere Bremse eingebaut und keinen Service gemacht wodurch der Fehler nicht behoben wurde. Somit handelt es sich auch nicht um einen Bug. Wir checken aber einmal ob man Code Technisch da etwas anpassen kann, wenn du eine andere Bremse verbaust, das der Fehler auch behoben wird ist aber eher ein QoL Ding.

**Comment by QA-Pregon** [comment]
Nach Absprache mit Tito ist das ganze zum jetzigen Zeitpunkt unglücklich gelaufen.
Da das Service System noch nicht mit dem Tuning System verknüpft ist, hätte dabei tatsächlich der Service eingeleitet werden müssen.
Der Programieraufwand zwischen der Service und der Tuning Seite ist bisher leider kein Teil der Umsetzung gewesen.
Realistisch gesehen ist es zwar richtig, dass der Fehler hätte behoben sein müssen, jedoch ist hier das ganze leider noch nicht umgesetzt.
Danke trotzdem für die Meldung, wir nehmen das ganze trotzdem ins Quality of Live auf.

**Comment by Mausi117** [comment]
Danke Pregon du hast es richtig aufgefasst mir ging es nur darum das wenn man ja neue Bremsen hat man ja kein Service machen müsste da sie ja neu sind =) ich bedanke mich und hoffe das es bei Gelegenheit übernommen wird =) wünsche einen schönen Abend =)
