### ISSUE TITLE
Versetzung des Ladepunkts

### ISSUE THREAD

**Issue by Shark198** [mexyn/statev_v2_issues#3373]
Character Name
Kirito Kobayashi

Hey es wäre super wenn ihr den Ladepunkt ein gutes Stück nach vorne setzen könntet und oder die Pylonen entfernen könntet.
Der Punkt ist jetzt grade in dem Schlagloch drin und dort sind 3-4 Pylonen die das abladen mit Fahrzeugen fast unmöglich machen.
Firmen Hash: pf_lamessa_13
![GTA5 2024-05-04 11-23-48](https://github.com/eiksch/statev_v3_issues/assets/168900193/01fbafe8-fc51-4eb1-9870-43671e6bb22c)
![GTA5 2024-05-04 11-24-07](https://github.com/eiksch/statev_v3_issues/assets/168900193/45e3b2e4-8613-4677-8941-40f6bdba00d1)

**Comment by Erumeldor** [comment]
Ich hab den Spot ein klein wenig aus dem Schlagloch wegbewegt. Ich hatte beim Testen kein Problem mit Fahrzeugen da hin zu kommen - und die Pylonen sind auch nicht fest und können daher bewegt werden.
Nächstes Update live.
