### ISSUE TITLE
Handschuhe & Kurzarm4 Kombination funktioniert nicht.

### ISSUE THREAD

**Issue by IgelJo** [mexyn/statev_v2_issues#3374]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
egal

**Auftrittszeitpunkt (Datum / Uhrzeit)**
04.05.2024 22:45

**Beobachtetes Verhalten**
Wenn man stoffhandschuhe anzieht, kann man nur noch Kurzarm1-3 und nicht mehr Kurzarm4 auswählen. 
Ohne Handschuhe kann man Kurzarm 4 aber auswählen.

**Erwartetes Verhalten**
Stoffhandschuhe + Kurzarm4 sollte zusammen auswählbar sein.

**Schritte um den Fehler nachvollziehen zu können**
erst stoffhandschuhe anziehen und dann versuchen kurzarm 4 auszuwählen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
 - 

**Optional: Video / Bilder des Fehlers**
-

**Comment by SHaagmann** [comment]
Generell bei allen Handschuhen der Fall
