### ISSUE TITLE
Vnet im Browser nutzbar, während man auf Cayo Perico ist

### ISSUE THREAD

**Issue by stepz2k9** [mexyn/statev_v2_issues#3376]
**Character Name**
Kelani Larsson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.05.2024 / 13 Uhr

**Beobachtetes Verhalten**
Wenn man nach Cayo Perico fährt, wird man ja aus dem Funknetz ausgeloggt. Das Telefon zeigt dann beim Wählen "Verbinduuuung.." an, das Tablet kann man nicht öffnen.
Hat man das VNet aber im Browser extern offen, kann man alle Reiter anklicken & auch Nachrichten empfangen und schreiben.

**Erwartetes Verhalten**
Dass man, wie auch unter V2, auch im Browser beim Erreichen der Insel ausgeloggt wird und sich so lange nicht mehr einloggen kann, bis man die Stadt wieder erreicht.

**Schritte um den Fehler nachvollziehen zu können**
Nach Cayo fahren, VNet im Browser öffnen, Nachrichten schreiben.

**Comment by simplycach** [comment]
Wird nicht geändert, wir behalten das im Auge betroffene Spieler, die das ausnutzten müssen mit einer Sanktion rechnen.
