### ISSUE TITLE
Stühle in Mühle Funktionieren Nicht!

### ISSUE THREAD

**Issue by Lether1983** [mexyn/statev_v2_issues#3379]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Hubertus Feger

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Die Gesamte Zeit

**Beobachtetes Verhalten**
In der Mühle kann man keine Stühle im Büro benutzen! Mann muss um die Maschiene zu bedienen neben dem Stuhl stehen das ist etwas Anstrengend für die Beine.

**Erwartetes Verhalten**
Sich Hinsetzen können!

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Hast du mal probiert dich mit Y hinzusetzen?

**Comment by Lether1983** [comment]
Ja die Funktion gibt es Garnicht.
