### ISSUE TITLE
Team Management SAPD: Aktivität wird nicht angezeigt

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#338]
**Character Name**
Jannik_Datsch

**Zeitpunkt (Datum / Uhrzeit)**
21.11 19:40

**Beobachtetes Verhalten**
Im Team Management werden alle auf Rot angezeigt, obwohl Leute im Dienst sind

**Erwartetes Verhalten**
Denke mal, dass die die im Dienst sind, grün sein sollten.

**Schritte um den Fehler nachvollziehen zu können**
Tablet öffnen --> Team --> Management

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://pic.statev.de/image/G6yMq

**Comment by its4l3x** [comment]
Eig. kein Bug, eig. so gewollt. Aber kann das gerne noch anpassen. Habe den ganzen Tag schon mit dem Gedanken gespielt.

**Comment by its4l3x** [comment]
Angepasst ;)
