### ISSUE TITLE
Blackmarket Waffenabgabe Funktioniert nicht

### ISSUE THREAD

**Issue by nb431** [mexyn/statev_v2_issues#3382]
Nathanael_Baker

**Auftrittszeitpunkt 09.05

**Beobachtetes Verhalten

Nach einer Erfolgreichen Auktion kann nicht die waffen nicht abgeben siehe Bilder 

![image1](https://github.com/eiksch/statev_v3_issues/assets/93134468/c4831b2f-9d61-43b1-81a8-5032c1397458)
![image2](https://github.com/eiksch/statev_v3_issues/assets/93134468/a6678c8f-1453-4f33-846e-dbe9fcb194a3)
![image3](https://github.com/eiksch/statev_v3_issues/assets/93134468/e38de397-30e7-4abe-b3da-0ad24ff0e10c)

**Comment by SHaagmann** [comment]
Wurden welche davon zwischendurch ausgerüstet?

**Comment by nb431** [comment]
Ja sie wurden schon mal equipped

**Comment by TheOutburst** [comment]
@DrGrizzlY17 wenn mich nicht alles täuscht ist das schon längst solved, oder?

**Comment by simplycach** [comment]
Da noch keine erneute Meldung kam, gehen wir von aus, dass es fixed ist.
