### ISSUE TITLE
Objekte entfernen, Lager

### ISSUE THREAD

**Issue by adrosso** [mexyn/statev_v2_issues#3383]
Schönen guten Tag, 

Ich habe da mal eine bescheidene Frage.

Wäre es möglich diesen Müll (Gelb umrandet) zu entfernen?

Die zweite Frage, besteht die Möglichkeit (Rot umrandet) das man ein Lager machen kann? (Natürlich mit Kauf)

Adresse: Popular Street 300
Hash: pf_lamessa_9

**Comment by simplycach** [comment]
Bitte einmal Screenshots posten.

**Comment by adrosso** [comment]
![Firma](https://github.com/eiksch/statev_v3_issues/assets/104076600/cbf8314a-6b32-4709-94ae-70e0551cdce4)

**Comment by TheOutburst** [comment]
Wir entfernen den Müll nichtmehr
Und neue Firmen fügen wir erstmal auch nicht hinzu, sorry
