### ISSUE TITLE
Versetzung der Tür und Abladepunkt

### ISSUE THREAD

**Issue by Xymena** [mexyn/statev_v2_issues#3384]
Grüße, ich wollte lieb nachfragen ob man den abladepunkt und die Tür von Noodle Exchange restaurant_LS_noodleExchange versetzen könnte.

![image](https://github.com/eiksch/statev_v3_issues/assets/76626768/6744c3a9-2932-4e60-8d71-45daf3d877c9)

das es nicht wie bisher vor den Laden ist sondern dahinter. 

![image](https://github.com/eiksch/statev_v3_issues/assets/76626768/c0bc8464-e874-4d5c-b7d1-2093d152b552)

Es kamm jetzt das häufigen vor das Personen fast überfahren wurden da durch das jemand grade zum liefern kamm, und leute fast überfahren wurden. desweiteren denke ich ist es förderlich für die RP immision wenn die Lieferung hinter den Laden erfolgt.

**Comment by Erumeldor** [comment]
Ist beides verschoben - im nächsten Update live :)
