### ISSUE TITLE
Hose Dupliziert sich

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3385]
Char
Mike Jenkins

Auftrittszeitpunkt (Datum / Uhrzeit)
10.05.2024 12:30 Uhr

Beobachtetes Verhalten
Wenn ich die Hose Anziehe dann hab ich sie zwar an aber ich hab sie dann noch im Inventar und wenn ich sie dann Ausziehe dann hab ich sie 2 mal im Inventar also Verdoppelt sie sich.

Erwartetes Verhalten
Hose verdoppelt nicht

Schritte um den Fehler nachvollziehen zu können

Hose an und ausziehen

Monitorauflösung (nur wenn Falsche Darstellung in der UI)
2560x1440

Optional: Video / Bilder des Fehlers
[Bild der Hose](https://pic.statev.de/image/screenshot-1.HxCXPy)

**Comment by Erumeldor** [comment]
@SHaagmann 
Ist nicht dein Char - aber weißt du ob das wiederholt auftritt? Also wird die Hose tatsächlich gedupt?

**Comment by Erumeldor** [comment]
Nach Antwort im Discord geschlossen - kein Duping und somit nicht nachvollziehbar.
