### ISSUE TITLE
Frisur oder Kleidungsstück buggt wenn außerhalb von Range

### ISSUE THREAD

**Issue by stepz2k9** [mexyn/statev_v2_issues#3386]
Ich weiß nicht genau, in welcher Kombination dieser Fehler auftritt. Die Frisur an sich trägt auch ein anderer Spieler, der aber diesen Fehler nicht reproduziert. Der Spieler auf dem Video trägt reine Vanilla Kleidung, außer der Tasche. Kann daher nicht nachvollziehen, wie der Bug entsteht, da bei einem anderen Spieler mit selber Frisur nicht solch ein Verhalten der Haare zu beobachten ist.

**Optional: Video / Bilder des Fehlers**
https://youtu.be/ITc1604LQjM

**Comment by QA-Pregon** [comment]
Nutzt du irgendwelche Grafikmods?

**Comment by stepz2k9** [comment]
> Nutzt du irgendwelche Grafikmods?

Nur NVIDIA-Filter.
