### ISSUE TITLE
0$ Ticket nicht bezahlbar

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3387]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

10.05
**Beobachtetes Verhalten**

Hab nen Ticket bekommen was 0$ beträgt und kann es nicht zahlen
**Erwartetes Verhalten**

Sollte es "zahlen" können
**Schritte um den Fehler nachvollziehen zu können**

Ticket mit 0$ ausstellen lassen
**Optional: Video / Bilder des Fehlers**

https://medal.tv/games/gta-v/clips/2ci4eJex03OeIh/d1337fUgmBPA?invite=cr-MSxXcmwsMTk1NTEzMTMzLA

**Comment by TheOutburst** [comment]
its not a bug, its a feature
