### ISSUE TITLE
Ziehen obwohl nicht bewusstlos

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3388]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

10.05
**Beobachtetes Verhalten**

Habe gefettfingert und anstelle von Handeln bei einem Kollegen "Ziehen" ausgewählt.
Nach dem wir fertig gehandelt haben wollte ich ne andere Animation beenden und die Nachricht "Ziehen beendet" kam
**Erwartetes Verhalten**

Die Nachricht sollte nicht kommen
**Schritte um den Fehler nachvollziehen zu können**

Fettfingern und Ziehen anstelle von Handeln auswählen
**Optional: Video / Bilder des Fehlers**

https://medal.tv/games/gta-v/clips/2chfTfcKnxCrIQ/d1337BP0VXLy?invite=cr-MSxaYmQsMTk1NTEzMTMzLA

**Comment by rodistic** [comment]
Next Update fixed
