### ISSUE TITLE
Datum der letzten Miete in der Apartmentübersicht fehlerhaft.

### ISSUE THREAD

**Issue by MarcGibbs** [mexyn/statev_v2_issues#3389]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name** 
Marc Gibbs

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Dauerhaft

**Beobachtetes Verhalten**
In der Apartmentübersicht wird bei einigen Leuten angezeigt das sie vor längeren Miete gezahlt hätten und das obwohl sie aktiv online sind und auch die Miete zahlen.  Einer Freundin von mir wurde aufgrund diesen Fehlers schonmal das Apartment gekündigt. 

**Erwartetes Verhalten**
Korrekte Anzeige in der Apartmentübersicht

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Fall 1 : 
![Screenshot_37](https://github.com/eiksch/statev_v3_issues/assets/168035262/f6ee1466-bb7b-4d6b-85d6-cc2e33d0a5bd)
![Screenshot_41](https://github.com/eiksch/statev_v3_issues/assets/168035262/4bfa78ca-3555-4691-b3a2-c99f95cec759)

Fall 2 : 
![Screenshot_39](https://github.com/eiksch/statev_v3_issues/assets/168035262/71410864-78bf-4bc8-bbe3-87e143c3e89b)
![Screenshot_40](https://github.com/eiksch/statev_v3_issues/assets/168035262/92fb099d-741e-409e-9e51-9a0ffe20b2d0)

**Comment by simplycach** [comment]
Ist dir das nochmal aufgefallen ?

**Comment by MarcGibbs** [comment]
> Ist dir das nochmal aufgefallen ?

Heute und gestern habe ich noch nicht drauf geachtet. 
Allerdings Montag war es definitiv noch fehlerhaft.

**Comment by simplycach** [comment]
Wenn es nochmal aufkommt, bitte nochmal melden.
