### ISSUE TITLE
Produktion Flasche Mate Granatapfel

### ISSUE THREAD

**Issue by Asmier** [mexyn/statev_v2_issues#339]
Asmier Umid

Flasche Mate verbraucht 3x **Plastikflasche** wird nach Verzehr zu Leere Plastikflasche.

Flasche Mate Granatapfel 3x **Glasflaschen** wird nach Verzehr zu Leere Plastikflasche.

Denke da liegt noch ein Fehler drinne das es noch nicht geändert worden ist.

http://prntscr.com/vnhsun

**Comment by DrGrizzlY17** [comment]
Produktion angepasst
