### ISSUE TITLE
Firmen Abladepunkt 

### ISSUE THREAD

**Issue by Basti54** [mexyn/statev_v2_issues#3390]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name** Sebastian Miller 

Gecko on Fire  firmen hash: pf_davis_42
**Auftrittszeitpunkt (Datum / Uhrzeit)**

11.05.24 18:00 Uhr 
**Beobachtetes Verhalten**

Der Blip ist viel zu nah am Gebäude 
**Erwartetes Verhalten**

wenn es geht würde ich halt ganz bequem rann Fahren können 

**Schritte um den Fehler nachvollziehen zu können**

Ich würde den entlade punkt in Bild 1 zu sehen ein wenig nach außen verschieben wollen da man nicht wirklich  mit dem Lkw rann kommt. Denke mal das würde schon reichen wenn man den bis ans ende der Parklücke setzt   
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

 ![alt_V Multiplayer 11 05 2024 17_56_33](https://github.com/eiksch/statev_v3_issues/assets/169544655/eb39f6ea-aa7a-4d19-835c-b9f0e54de339) 

![alt_V Multiplayer 11 05 2024 17_56_49](https://github.com/eiksch/statev_v3_issues/assets/169544655/4f3f66d1-4649-4470-b61f-76e21880e1a1)

**Comment by Erumeldor** [comment]
Ja, ich hab die wirren Marker mal etwas verschoben. 
Die Nachbarfirma ist etwas gewandert, und eurer Punkt ist nun daneben.
Nächstes Update live.
