### ISSUE TITLE
alte Werkstattbug besteht teilweise weiterhin

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#3391]
https://www.youtube.com/watch?v=93RfNtxKJdw

Sonst bisher nicht mehr aufgefallen. Evtl liegts am ausgebrannten Fahrzeug

**Comment by SHaagmann** [comment]
Liegt nicht daran hatten gestern auch eine Karre die so 4m nach links gesprungen ist und den Mechaniker mitgenommen hat

**Comment by DrGrizzlY17** [comment]
Wird sehr stark daran liegen, das ihr da nen komplett zerschrottet fahrzeug repariert habt, das eher in die verwahrstelle gehört als in ne Werkstatt :D Aber wir gucken mal

**Comment by DrGrizzlY17** [comment]
> Liegt nicht daran hatten gestern auch eine Karre die so 4m nach links gesprungen ist und den Mechaniker mitgenommen hat

Hast du davon nen Link

**Comment by SHaagmann** [comment]
> > Liegt nicht daran hatten gestern auch eine Karre die so 4m nach links gesprungen ist und den Mechaniker mitgenommen hat
> 
> Hast du davon nen Link

Ne leider nicht. Clippe sonst eig alles

**Comment by DrGrizzlY17** [comment]
> > > Liegt nicht daran hatten gestern auch eine Karre die so 4m nach links gesprungen ist und den Mechaniker mitgenommen hat
> > 
> > 
> > Hast du davon nen Link
> 
> Ne leider nicht. Clippe sonst eig alles

Oke, hatte das Fahrzeug kaputte reifen oder war explodiert?

**Comment by SHaagmann** [comment]
> > > > Liegt nicht daran hatten gestern auch eine Karre die so 4m nach links gesprungen ist und den Mechaniker mitgenommen hat
> > > 
> > > 
> > > Hast du davon nen Link
> > 
> > 
> > Ne leider nicht. Clippe sonst eig alles
> 
> Oke, hatte das Fahrzeug kaputte reifen oder war explodiert?

Ja Reifen waren zum teil kaputt

**Comment by simplycach** [comment]
Liegt scheinbar an den Kaputten Reifen, da wir noch nen Bugtracker aufhaben, würde ich diesen schließen.
