### ISSUE TITLE
Standard felgen haben keine beschrifteten reifen

### ISSUE THREAD

**Issue by FLVFFY1** [mexyn/statev_v2_issues#3392]
** Jayden Banks **

Auftrittszeitpunkt (Datum / Uhrzeit)

Beobachtetes Verhalten
Standard Felgen, wie "Lowrider" felgen, welche es seit start von GTA gibt haben keine Auswahl für die beschriftung an den Reifen bzw die möglichkeit der weißwandwandbereifung

Erwartetes Verhalten
Auch die "alten" seit GTA Tag 1 vorhanden Felgen sollten die Beschriftung / Weißwand als Option haben

Schritte um den Fehler nachvollziehen zu können:
Felgen ändern, keine besagten reifen finden. /// Ich rede nicht von den bennys felgen!

**Comment by QA-Pregon** [comment]
Soweit ich weiß sind die Felgen auf dem Server alle vom Standard GTA übernommen.
Das können vlt @TheOutburst @simplycach oder @Erumeldor oder someone else beantworten

**Comment by FLVFFY1** [comment]
es geht nicht um die felgen an sich, sondern die zu den kategorien gehören auch beschriftete reifen dazu. sodass du einmal felge + schwarzer reifen und felge + kleiner atomic schriftzug oder felge + weißwand hast

**Comment by FLVFFY1** [comment]
https://gta.fandom.com/wiki/Los_Santos_Customs/Wheels

Dort fast am ende zu sehen, unter der kategorie "Tire Design"

**Comment by Erumeldor** [comment]
Done
