### ISSUE TITLE
Addidas Crossbag unsichtbar bei Weiblichen Charakter

### ISSUE THREAD

**Issue by xMissRi** [mexyn/statev_v2_issues#3393]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
 
Reyna Winchester

**Auftrittszeitpunkt (Datum / Uhrzeit)**

11.05.2024, circa 20 Uhr

**Beobachtetes Verhalten**

Addidas Crossbag ist bei Weiblichen Charakteren Unsichtbar 

**Erwartetes Verhalten**

Das man die Tasche sieht

**Schritte um den Fehler nachvollziehen zu können**

Einfach die Tasche anlegen als Frau.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
 
https://imgur.com/fdTei6k
https://imgur.com/AOg5sjn

**Comment by ySimbaa** [comment]
Die Bags sind für Female nicht nutzbar. Hab sie rausgenommen.
