### ISSUE TITLE
grotti brioso r/a Mehrere Sachen beim tuning nicht erschaubar)

### ISSUE THREAD

**Issue by PulseMcGEE** [mexyn/statev_v2_issues#3394]
**Naoki_Lee**

**Auftrittszeitpunkt (11.05.2024 / 22:00 Uhr)**
11.05.2024 / 22:00 Uhr

**Beobachtetes Verhalten**
Der Grotti Brioso R/A hat beim Tuning ( Spoiler und Spezialaufkleber) mehrere Optionen als am Auto erscheinen 

**Erwartetes Verhalten**
Sollten mehrere Anpassungen möglich sein

**Schritte um den Fehler nachvollziehen zu können**
Bei der Werkstatt nachschauen

**Comment by PulseMcGEE** [comment]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```


**Naoki_Lee**


**Auftrittszeitpunkt (11.05.2024 / 22:00 Uhr)**


**Beobachtetes Verhalten**


**Erwartetes Verhalten**


**Schritte um den Fehler nachvollziehen zu können**


**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**


**Optional: Video / Bilder des Fehlers**

**Comment by Erumeldor** [comment]
Hi @PulseMcGEE 
Kannst du bitte etwas beschreiben was das Problem ist?

Die Vorlage freut sich ausgefüllt zu werden - Beschreibung, ggf. Videos / Bilder ;)

**Comment by PulseMcGEE** [comment]
habe ich, jedoch wird es nicht angezeigt

**Comment by PulseMcGEE** [comment]
![Screenshot_42](https://github.com/eiksch/statev_v3_issues/assets/169558370/0a511a34-cc8f-45ea-9f8b-43dc83e77ccb)

**Comment by SHaagmann** [comment]
@PulseMcGEE Durch die Zeichen wo du es rengeschrieben hast wirds nicht angezeigt... <!--- etc

**Comment by Erumeldor** [comment]
Da können wir aktuell leider nichts ändern. Das sind Tunings aus vmtl Haos Workshop von GTA. Ich nehm das mal auf, aber als Low-Prio.

**Comment by Erumeldor** [comment]
Im letzten Update mit ermöglicht, wird nicht mehr angezeigt :)
