### ISSUE TITLE
Synergy Customs - Repair-Spot

### ISSUE THREAD

**Issue by DonJohn1993** [mexyn/statev_v2_issues#3395]
Moin.

Betrifft Synergy Customs oben in Harmony.

Besteht die Möglichkeit uns den rot markierten Repair-Spot in roter Pfeilrichtung zu versetzen?
Zum einen ist die Bodenwelle extrem hinderlich beim tunen, wenn es um Bodykits und Auspuffe geht (stell ich das Auto quer, kommt niemand mehr in die Halle rein oder raus), was aber gravierender ist, ist das Abschleppen mit dem Towtruck.
Aktuell müssen wir Autos mit dem Towtruck rückwärts "drücken", was mit dem Haken besonders unlustig ist oder frühzeitig runterlassen und zum Punkt schieben. Da wir Tanker eh schon kaum bewegt kriegen beim Abschleppen ist es fast unmöglich den rückwärts Richtung Punkt zu "drücken": Vorher absetzen geht auch nicht, weil die nicht schiebbar sind. Mit dem Towtruck in die Halle, um den Tanker weiter zu ziehen, klappt auch nicht, weil die Halle zu tief ist und der Truck hängen bleibt. 
Wäre der Punkt weiter hinten, könnte man immerhin die mitten auf dem Platz stehende Laterne umfahren, den Tanker ordentlich zum reparieren ablassen und den Towtruck wieder rausbekommen.

![image](https://github.com/eiksch/statev_v3_issues/assets/79906053/9f942785-e4e7-426f-8cc1-381db9d0afaf)

Wäre echt cool, wenn ihr uns das mit einer Änderung vereinfachen könntet. So ist es aktuell echt mühsame die Dinger auf den Hof zu karren.

Liebe Grüße

**Comment by epichalt** [comment]
Ich hatte schon mal angemerkt die außerhalb gelegenen Repair Spots an einigen Werkstätten etwas zu versetzen damit ein Ein- und Ausfahren möglich ist sobald ein Fahrzeug draußen repariert oder getuned wird. Mir wurde damals gesagt, dass es nicht gewünscht ist beide Repair Spots gleichzeitig zu benutzen. 
Daher müssten die Repair Slots aller Werkstätten evtl. versetzt werden.

**Comment by DonJohn1993** [comment]
Wie geschrieben. Uns geht es nicht um die Benutzung beider Spots. Hier geht es einfach darum, dass der Tow-Truck so keine Möglichkeit hat, ein Fahrzeug auf den Spot zu "ziehen".
Wir müssen Autos vorher absetzen und schieben. Sind Autos noch an oder haben die Handbremse gezogen, geht auch das nicht und wir müssen nach dem Abschleppen nochmal den Flatbed benutzen, um das Fahrzeug auf den Punkt zu bewegen.
Bei LKWs bleibt uns gar keine Möglichkeit, außer zu versuchen den rückwärts zu "drücken", was mit einem Haken nicht nur maximal schwierig ist, sondern auch komplett Irrsinnig der Logik nach.

**Comment by epichalt** [comment]
Klar geht es nicht um die Benutzung beider Spots, aber hat den selben Effekt. 

Zudem ändert das ja nichts an der Thematik, dass alle Werkstätten das Problem haben. Also müssten ja trotzdem alle Spots geändert werden.

**Comment by DonJohn1993** [comment]
Eventuell schreiben wir aneinander vorbei. Du redest glaube ich nicht von den Punkten bzgl. dem Towtruck-Problem oder?
Denn das Problem hat zumindest Bennys nachweislich nicht.

![image](https://github.com/eiksch/statev_v3_issues/assets/79906053/9a8504c6-2458-4b05-8860-cba19f9f19cf)

Bei Bennys kann der Twotruck einfach über den Punkt ziehen, abhängen und weiter.
Wir haben, ohne größere Probleme, gar keine Chance direkt über den Punkt zu fahren

**Comment by epichalt** [comment]
Naja, das eine Problem existiert einfach wegen der Maßnahme, dass er äußere Reparaturpunkt bei jeder Werkstatt sehr nah am Gebäude/Eingang ist. Selbst bei deinem Bennys Beispiel müsste man schon sehr nah am Gebäude entlangfahren um an den Punkt zu kommen. 

Aber es gibt halt auch Workarounds. V2 hatte es ja auch geklappt und da musste man im Gebäude in die letzte Ecke fahren.

**Comment by Erumeldor** [comment]
Hey @DonJohn1993 
Wie epichalt schon gesagt hat, haben die meisten Werkstätten das Problem - und das ist begründet um da ein gewisses Handicap zu haben.
Der Punkt muss daher auch bei euch bestehen bleiben.
