### ISSUE TITLE
Auto nach abschleppen wieder am Original Punkt

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3396]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Verlauf des Abends/Nacht vom 11.05 auf den 12.05
**Beobachtetes Verhalten**

Mein Auto wurde vom Vespucci Boulevar abgeschleppt zu West Coast Customs, dort repariert und von dort aus dann zum Pacific Bluff geschleppt.  Als ich mein Auto nach meinem MD Aufenthalt geortet habe (Der rest ist während dessen passiert) Stand das Auto wieder an der Unfallstelle. Freunde von mir haben es zuvor aber auch schon am Hotel gesehen.
**Erwartetes Verhalten**

Auto bleibt da wo es hingeschleppt wird
**Schritte um den Fehler nachvollziehen zu können**

1. Detective Baller in einen reinfliegen lassen
2. Fahrzeug abschleppen
3. F. Reparieren
4. Wegschleppen
5. Wundern, dass es wieder an der unfallstelle ist
**Optional: Video / Bilder des Fehlers**

Nicht direkt vom Bug aber halt vom Unfall und dann wo ich es ganz abgeholt habe. Man sieht halt, dass es die exakt gleiche Position ist:
Unfall:
https://medal.tv/games/gta-v/clips/2cAz0r0TrCG9Du/d13370Nmc5aX?invite=cr-MSxiSkwsMTk1NTEzMTMzLA

Abholen:
![image](https://github.com/eiksch/statev_v3_issues/assets/58612983/59bce089-e341-4ec9-aaab-e676c75095d0)

**Comment by SatyriaDine** [comment]
Schon bekannt :) #3380
