### ISSUE TITLE
Versetzen des Ladepunktes am County Container

### ISSUE THREAD

**Issue by Digawen** [mexyn/statev_v2_issues#3397]
**Character Name**
Ronnie Flex

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Ladepunkt wird oft, trotz Bodenmarkierung, als Parkplatz benutzt.
Des Weiteren ist der Ladepunkt für LKW wie dem Phantom mit Anhänger schwer zu erreichen.
Bzw. steht auch der Mast und die dazugehörigen Steine im Weg, um den Punkt gut zu erreichen.
(Bild 1-3)

**Erwartetes Verhalten**
Daher würde ich darum bitten, den Punkt zu versetzen.
(Bild 4-5)

**Optional: Video / Bilder des Fehlers**
Ausgangssituation:
Bild1: ![Screenshot 2024-05-10 211100](https://github.com/eiksch/statev_v3_issues/assets/4532046/04935774-759d-4544-a514-7cc352e36822) 
Bild2: ![Screenshot 2024-05-10 211014](https://github.com/eiksch/statev_v3_issues/assets/4532046/7a96e0e5-e050-4a4b-8893-13486c9bcff7)
Bild3: ![Screenshot 2024-05-10 210505](https://github.com/eiksch/statev_v3_issues/assets/4532046/e116f6e3-d517-4aa3-8802-bf0d943ef77f)

mögliche Alternative:
Bild4: ![Screenshot 2024-05-10 211042_1](https://github.com/eiksch/statev_v3_issues/assets/4532046/774d49ae-a9d0-482c-bf0a-34df8e485db0)
Bild5: ![Screenshot 2024-05-10 211025_1](https://github.com/eiksch/statev_v3_issues/assets/4532046/e10d38d2-80ef-4ac6-8cc0-f14588d98e55)

**Comment by Erumeldor** [comment]
Ich hab ihn dir auf die Straße, in Richtung Friseur verschoben.
Nächstes Update live :)
