### ISSUE TITLE
Falscher Mapmarker im Tutorial

### ISSUE THREAD

**Issue by EinfachDanielStateV** [mexyn/statev_v2_issues#3398]
**Character Name**
Jabari Simmons

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.05.2024 | ca. 12:10

**Beobachtetes Verhalten**
Wenn man die Legale Einreise wählt und über denn NPC am Flughafen LS zum vermieter geschickt wird schickt er einen zu dem Vermieter an denn Docks wo sind der Crime Spawn befindet und nicht zu dem Vermieter am Flughafen 

**Erwartetes Verhalten**
Das der maker zum Flughafen vermieter führt

**Schritte um den Fehler nachvollziehen zu können**
Legale Einreise wählen mit dem npc sprechen und auf denn maker achten

**Comment by stepz2k9** [comment]
Könnt das dran liegen, dass dein alter Char crime-gelabelt war? Ich wurde normal zu dem Vermieter am Flughafen geschickt.

**Comment by EinfachDanielStateV** [comment]
mein alter char war crime ja

**Comment by simplycach** [comment]
Scheinbar ein Einzelfall
