### ISSUE TITLE
Versetzen des Verlade-Makers für #pf_sandyshores_53

### ISSUE THREAD

**Issue by Guoliveryh** [mexyn/statev_v2_issues#3399]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Carl Kampmann

Das Problem tritt leider permanent auf.

Wenn ich ein beliebiges Fahrzeug auf dem Abladepunkt meines Sägewerks #pf_sandyshores_53 ("Wiggle's - Kisten & Paletten") zum Be- oder Entladen abstelle und die Firma betrete, dann 'driftet' beim Verlassen der Firma das Fahrzeug gefährlich auf mich zu und kann sogar Verletzungen nach sich ziehen. (Vgl. hier: https://www.youtube.com/watch?v=hmbkuESLygA )

Das Fahrzeug sollte beim Verlassen der Firma nicht auf mich zu rutschen.

1. bei #pf_sandyshores_53 im Hof  parken (passiert auch neben dem Verladepunkt)
2. Firma betreten
3. Firma verlassen
(4.) Fahrzeug "glitcht" rum

Hinweis: Um das Problem dann erneut zu reproduzieren, muss das Fahrzeug in der Regel minimal umgeparkt werden. Es glitcht also für eine Parkposition meist nur einmalig herum. Vielleicht hilft das ja bei der Fehlerdiagnose.

irrelevant

Da ich mir vorstellen kann, dass ein Beheben dieses Problems recht aufwendig werden könnte, sei hier gesagt, dass es für mich erstmal hinreichend wäre, wenn der Verladepunkt versetzt werden würde. Idealerweise bekäme der Verlade-Punkt zusätzlichen Abstand zum Firmeneingang und ebenso zusätzlichen Abstand zum Nachbargebäude (hier sind oft Fahrzeuge geparkt, bei denen es unter Verwendung des Log-Trailers zu Karambolagen kommen kann). Einen Vorschlag könnt ihr der beigefügten Skizze entnehmen. Herzlichen Dank für eure Unterstützung!

![Vorschlag Verladepunktkorrektur pf_sandyshores_53](https://github.com/eiksch/statev_v3_issues/assets/126990684/de876a1f-2f46-43c3-b964-cca594e60ce4)

**Comment by Erumeldor** [comment]
Ich hab euren Ausgangspunkt näher ans Gebäude (unter das Dach), und den Marker etwas nach oben verschoben.
Hoffe ihr werdet nach dem nächsten Update nicht mehr erschlagen :)

**Comment by Guoliveryh** [comment]
Tausend Dank, @Erumeldor ! Konntest Du den Abladepunkt so ähnlich wie in der Skizze -also auch mit etwas mehr Abstand zum Nachbarn- platzieren? Neben dem "erschlagen werden" ist nämlich auch das Rangieren manchmal recht qualvoll gewesen, wenn ich mit der Holzachse zwischen den geparkten Autos rumstochern musste.
