### ISSUE TITLE
Funkfrequenzen speichern

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#34]
**Zeitpunkt (Datum / Uhrzeit)**

21:00 25.08.2020

**Beobachtetes Verhalten**

Funkfrequenzen werden nicht gespeichert beim Crash/Relog.

**Erwartetes Verhalten**

Sie sollten gespeichert werden.

**Schritte um den Fehler nachvollziehen zu können**

f8 + quit. AltV starten. Einloggen. "U" drücken.

**Comment by tastydev** [comment]
Dieses feature ist mit dem nächsten server update integriert
