### ISSUE TITLE
Fahrzeuge stehen nach Serverneustart verändert (Position) da

### ISSUE THREAD

**Issue by Asmier** [mexyn/statev_v2_issues#340]
Asmier Umid / Sarah Lagu

**Zeitpunkt (Datum / Uhrzeit)**
Zwischen Server Neustarts

**Beobachtetes Verhalten**
Fahrzeuge sind nach Server neustart schief auf Position

Fehler konnte durch Intieror betreten und Streaming Range verlassen nicht nachgestellt werden

**Erwartetes Verhalten**
Sollten gerade da stehen, wie abgestellt

**Schritte um den Fehler nachvollziehen zu können**
1. Fahrzeug parken
2. Server Neustart
3. Fahrzeug steht schief da

**Optional: Video / Bilder des Fehlers**
https://prnt.sc/vnhvkc
https://prnt.sc/vnhw2w

**Comment by its4l3x** [comment]
Das ist ein derzeitiges altV Issue. War mit dem RC Branch z.B. behoben worden. (Entity Rotation Getter/Setter). Müssen leider warten...

**Comment by JulianMa** [comment]
durch alt:V fixed
