### ISSUE TITLE
Möbelladen LS Sound und Grafikprobleme

### ISSUE THREAD

**Issue by Shark198** [mexyn/statev_v2_issues#3400]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Kirito_Kobayashi

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer

**Beobachtetes Verhalten**

Es ist kaum bis gar nicht möglich in dem MLO Rp zuspielen weil man sich gegenseitig nicht sieht oder hört, man muss jedes mal nach draußen gehen um zureden, das sorgt für komische Situation und man kann den Laden nicht so nutzen wie man ihn eigentlich nutzen sollte. Dazu ist der Laden so dunkel das es auch nichts bringt wenn Abends das Licht an ist.

**Erwartetes Verhalten**

Der Laden sollte etwas heller von innen sein und man sollte sich halt sehen können und sich hören können.
**Schritte um den Fehler nachvollziehen zu können**

Person 1 geht rein, Person 2 geht rein und versucht mit Person 1 zu interagieren.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by jonesXYZ** [comment]
Sieht schwer nach Interiorproxies aus @Erumeldor @nytech

**Comment by TheOutburst** [comment]
Ist bereits seit längerem fixed
