### ISSUE TITLE
Antrag Balkonport / Entfernung Müll

### ISSUE THREAD

**Issue by stepz2k9** [mexyn/statev_v2_issues#3402]
Haaaallöchen.

Ich wollte mal freundlich fragen, ob dem von mir erstandenen Haus mit dem Hash house_PaletoBay_37 ein Portpunkt zum Balkon zugefügt und der Müll entfernt werden kann. Eine Bucht vorher, ebenfalls Chumash, gibt es ein baugleiches Haus, bei dem beide Sachen zu V2 bereits so gemacht wurden. Nachfolgend Bilder von meinem Haus und wie es am anderen Haus gemacht wurde:

![Grand Theft Auto V Screenshot 2024 05 13 - 17 58 39 59](https://github.com/eiksch/statev_v3_issues/assets/74977218/026782c5-a828-4e2e-a996-732fe26d0be3)
Hier wäre die Bitte, Schrottauto und (wenn möglich, am anderen Haus war das wohl nicht möglich, da er beim gegenlaufen immer wieder auftauchte) Wagenheber, sowie den Müll im Hintergrund zu entfernen, damit es dann so (baugleiches Haus vorherige Bucht) aussieht:
![Grand Theft Auto V Screenshot 2024 05 14 - 08 51 14 08](https://github.com/eiksch/statev_v3_issues/assets/74977218/079d729a-9e14-486e-9064-250cbda252ee)
Vorteil wäre: Könnte mein Auto dann mal draußen stehen lassen, aktuell muss ich direkt einparken, da sonst eventuell auf der Straße-

Und hier wäre die Bitte, einen Portpunkt auf den Balkon zu platzieren, da man anders nicht drauf kommt:
![Grand Theft Auto V Screenshot 2024 05 13 - 17 59 39 36](https://github.com/eiksch/statev_v3_issues/assets/74977218/96c5a0ae-35f5-49dd-9e54-680a1f47499c)
Beim anderen Haus kommt der Portpunkt dann hier raus (unterer Balkon, ganz linke Tür):
![Grand Theft Auto V Screenshot 2024 05 14 - 08 51 32 36](https://github.com/eiksch/statev_v3_issues/assets/74977218/92597bd3-d9fb-49b7-8a80-1318cd8c29df)

Würde mich freuen und vielen Dank im Voraus! :)

**Comment by TheOutburst** [comment]
Wir machen keine neuen Portmarker mehr
Und den Müll entfernen wir auch nichtmehr, sorry
