### ISSUE TITLE
Girly Appartement buggy / Möbel werden doppelt angezeigt

### ISSUE THREAD

**Issue by stepz2k9** [mexyn/statev_v2_issues#3404]
**Character Name**
Kelani_Larsson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14.05. / 23:30 Uhr

**Beobachtetes Verhalten**
Haus von Low End Appartement auf Girlys Appartement umgebaut. Dann festgestellt, dass einige Möbel doppelt vorhanden sind. Auch nach Relog keine Änderung.

**Erwartetes Verhalten**
Möbel sollten nur ein Mal vorhanden sein.

**Optional: Video / Bilder des Fehlers**
![Grand Theft Auto V Screenshot 2024 05 14 - 23 32 10 01](https://github.com/eiksch/statev_v3_issues/assets/74977218/4a95a73a-20dd-4c45-9721-d5aa3ffd0f4d)
![Grand Theft Auto V Screenshot 2024 05 14 - 23 30 58 44](https://github.com/eiksch/statev_v3_issues/assets/74977218/0f79a0a5-2a32-4583-9e04-1ba973fa8903)
![Grand Theft Auto V Screenshot 2024 05 14 - 23 31 54 37](https://github.com/eiksch/statev_v3_issues/assets/74977218/d3750609-0ab4-456d-866e-2b3b5972df10)
![Grand Theft Auto V Screenshot 2024 05 14 - 23 32 02 78](https://github.com/eiksch/statev_v3_issues/assets/74977218/739bb3a1-3a35-4c10-b634-c61000fdd591)

**Comment by Erumeldor** [comment]
Ist im nächsten Update fixed :)
