### ISSUE TITLE
Sauerstoffflaschen können nicht über den Markt verkauft werden

### ISSUE THREAD

**Issue by LeaBrandt** [mexyn/statev_v2_issues#3405]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Ronja_Brandtberg 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
15.05.2024 8:54 Uhr (sicherlich auch schon früher) 

**Beobachtetes Verhalten**
Sauerstoffflaschen können nicht in den Verkauf gestellt werden. 

**Erwartetes Verhalten**
Ich kann Sauerstoffflaschen in den Verkauf stellen. 

**Schritte um den Fehler nachvollziehen zu können**
Sauerstoffflaschen ins Firmenlager packen und versuchen in den Firmenverkauf zu stellen. 

**Optional: Video / Bilder des Fehlers**
Sind im Lager vorhanden: 
![Ansicht Lager](https://github.com/eiksch/statev_v3_issues/assets/98689462/d31c8385-97fd-4aca-94dc-a8a95eae4730)
Werden links nicht im Inventar angezeigt: 
![Fehlende Anzeige im Inventar - obwohl in Lager](https://github.com/eiksch/statev_v3_issues/assets/98689462/237db8e0-2ef5-4d13-9d9a-c4efa135c07a)
Auch die Artikelsuche führt zu keinem Produkttreffer: 
![Taucht nicht in Suche der Verkausprodukte auf](https://github.com/eiksch/statev_v3_issues/assets/98689462/6495a8fe-0111-4435-9766-b9c02043fb7f)

**Comment by epichalt** [comment]
denke das ist so gewollt

**Comment by LeaBrandt** [comment]
Ja das habe ich ooc natürlich auch schon überlegt, aber ic macht das ja absolut keinen Sinn. Herstellung und Vertrieb ist doch absolut legal...ic brauchen das die Leute sicherlich um tauchen zu gehen oder fürs MD...ich finde keinen Hintergrund warum der Handel damit nicht möglich sein sollte...

**Comment by DerHessenTyp** [comment]
Da gab es zu V2 mal etwas mit den [Behälter im Kerosin](https://github.com/eiksch/statev_v3_issues/issues/2795). Schon damals waren einige Items nicht im Marktplatz hinterlegt. Ich denke das wird das gleiche auch mit den Sauerstoffflaschen sein.

**Comment by Erumeldor** [comment]
Wie schon geschrieben wurde, ist das bewusst.
Die Sauerstoffflasche ist nur sehr begrenzt für Firmen notwendig und daher dort sicherlich so machbar - für den anderen Anwendungszweck soll aber gerne etwas RP gespielt werden und nicht einfach so gekauft werden.
