### ISSUE TITLE
pf_Strawberry_34 Abladepunkt ändern

### ISSUE THREAD

**Issue by DEHUNTER58711** [mexyn/statev_v2_issues#3406]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Sergei_Popov

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Abladepunkt unpraktisch für große Fahrzeuge

**Erwartetes Verhalten**
Praktischer Abladepunkt

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug entladen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
-

**Optional: Video / Bilder des Fehlers**

![Screenshot 2024-05-17 110058](https://github.com/eiksch/statev_v3_issues/assets/170087823/dbadf977-e623-421c-a2a8-52c6d0525c08)
![Screenshot 2024-05-17 110246](https://github.com/eiksch/statev_v3_issues/assets/170087823/04081e85-d6c6-49af-94a1-6e458ce541f0)

**Comment by QA-Pregon** [comment]
Auch wenn ich zwar weiß wo das ist, gib uns bitte noch für unsere Gamedesigner den Firmenhash

**Comment by DEHUNTER58711** [comment]
hatte ich in den Betreff geschrieben: pf_Strawberry_34

**Comment by QA-Pregon** [comment]
Jo stimmt da sieht man mal das ich vor 10 mins aufgestanden bin😂

**Comment by Erumeldor** [comment]
Nächstes Update verschoben.
