### ISSUE TITLE
Oberteil hat Löcher

### ISSUE THREAD

**Issue by Auralein** [mexyn/statev_v2_issues#3408]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Holly Swan**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jeeederzeit. Meh.

**Beobachtetes Verhalten**
Beim Telefonieren hat das Oberteil plötzlich Löcher.

**Erwartetes Verhalten**
Keine Löcher!

**Schritte um den Fehler nachvollziehen zu können**
Anziehen, anpassen, telefonieren.

**Optional: Video / Bilder des Fehlers**
![grafik](https://github.com/eiksch/statev_v3_issues/assets/76708950/7917fadd-56cb-47a8-aa21-8d80faad3c3a)

![grafik](https://github.com/eiksch/statev_v3_issues/assets/76708950/b9e70ceb-162e-47af-a2d8-c6f3c0725e6f)

**Comment by stepz2k9** [comment]
Das liegt höchstwahrscheinlich am Model... ist vermutlich nicht für RP gemacht :/

**Comment by TheOutburst** [comment]
jau, das einzige was wir hier machen könnten wäre das Oberteil raus zu nehmen, also das wird so bleiben, sorry

Ein hoch auf die Modding Community! Kappa
