### ISSUE TITLE
HaarFrisur Bug

### ISSUE THREAD

**Issue by StateV2Marie** [mexyn/statev_v2_issues#3409]
Ich hab da nen bild das ihr seht das die Männer Frisur verbugt is das is die schulterlange Frisur mit dem Stirnband wen man paar meter weg is schauts aus als würd er drachen steigen lassen. 
![frisurbug](https://github.com/eiksch/statev_v3_issues/assets/74982004/62c93312-7d25-4d2b-8da3-e7f60543af55)

**Comment by simplycach** [comment]
Weißt du welche das ist, so bringt uns das leider überhaupt nichts.

**Comment by StateV2Marie** [comment]
ich weiß den namen leider grad nicht aber die aktiven Frisure müsten ihn doch beim namen kennen. sorry habs nur auf dem feld gesehen das es die Männer Frisur mit dem festen Tuch ist.

**Comment by stepz2k9** [comment]
Ich hab denselben Fehler schon bei #3386 gemeldet.
Scheint alle Frisuren aus einem bestimmten Hairpack zu betreffen, ich hab grad jemanden mit dem Demir-Zopf gesehen, selbes Spiel.

Auf dem Bild übrigens derselbe Spieler, wie bei meinem Video, erkennt man am grünen Bodhi.

**Comment by Erumeldor** [comment]
Ich mach hier mal zu, ist der selbe wie der von CaleighRhodes. :)
