### ISSUE TITLE
Fehlerhafte Zuweisung der Seriennummern bei Waffenkauf in Ammunation

### ISSUE THREAD

**Issue by masterppc** [mexyn/statev_v2_issues#341]
Uwe_Behrens

21.11.2020 14.07 Uhr

**Beobachtetes Verhalten**
Beim Kauf einer Waffe in der Ammunation wird die Waffe auf den Firmeninhaber geschrieben und nicht auf den Käufer

**Erwartetes Verhalten**
Seriennummer der Waffe wird zum Käufer hinzugefügt.

**Schritte um den Fehler nachvollziehen zu können**
In der Ammunation eine Waffe kaufen. (gestern gab es ja den Bug das es gar keine Seriennummern gab und jetzt halt dieser)

**Optional: Video / Bilder des Fehlers**
https://i.imgur.com/OhbFCXMh.jpg

**Comment by its4l3x** [comment]
Ist Tatsache eine kleine Änderung gewesen die wir mit V2 vorgenommen hatte. Wir unterscheiden nun zwischen Käufer und Verkäufer. Bei Käufer wird der Käufer logischerweise eingetragen und bei Verkäufer der Owner der Fabrik (Ammunation, etc...).

Habe nun im statecom das umbennant. Jetzt es kann passieren das Verkäufer/Käufer gleich heißen. Bitte dementsprechend abgleichen und nicht wundern das bei Waffen welche vor V2 gekauft wurden nun bei Verkäufer und Käufer das gleiche steht... Besitzer heißt nun Verkäufer!

**Comment by masterppc** [comment]
d.h. man sieht im Statecom die Waffen dann nicht mehr richtig? Also alles nach V2.

**Comment by eiksch** [comment]
Es steht dort jetzt immer Verkäufer/Käufer.

Früher war Verkäufer und Käufer immer das gleiche, ab dem nächsten Update wird es getrennt wer zu diesem Zeitpunkt Inhaber des Ammunations war, und wer die Waffe gekauft hat.

**Comment by masterppc** [comment]
Ja das hab ich verstanden. Es geht mir jetzt um das Statecom. Wenn ich z.b. eine Akte aufrufe und der hat 10 Waffen registriert. Dieser kauft sich jetzt 5 neue Waffen. Diese findet man dann nur beim "Verkäufer" der ja dann x100 Waffen bei sich stehen hat. Falls dann einer der 5 neuen Waffen verloren geht und er diese bei der Polizei melden will wird es glaub ich unmöglich diese Waffe zu finden. Das meinte ich damit ^^

**Comment by masterppc** [comment]
Ich hab das ganze nochmal Visuell fertig gemacht damit man es besser verstehen kann was ich meine ^^

https://youtu.be/Shx2QKm5T1c

**Comment by masterppc** [comment]
Jetzt ist das eingetreten was ich gestern im Video angesprochen habe.

https://youtu.be/z7VE8zw9Kd0
