### ISSUE TITLE
Gemeinschaftskonto

### ISSUE THREAD

**Issue by robka87owl** [mexyn/statev_v2_issues#3410]
** Name**
Andreas Kowalski

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.05.2024 - 21:39 UHr

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

Gruppenkonto bearbeiten
**Schritte um den Fehler nachvollziehen zu können**

Tablet -> Konto -> Gruppenkonto -> Keine Bearbeitung möglich!
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

1080p

**Optional: Video / Bilder des Fehlers**

https://pic.statev.de/image/gemeinschaftskonto.HyW95g

**Comment by simplycach** [comment]
Dann hast du eventuell keine Berechtigung dafür, was möchtest du denn genau bearbeiten ?

**Comment by robka87owl** [comment]
Ich wollte mein Konto für andere Freigeben.

**Comment by QA-Pregon** [comment]
Wolltest du dein Hauptkonto oder ein anderes freigeben?

**Comment by robka87owl** [comment]
Moin,

nein, ein anderes Konto. "728622"

**Comment by simplycach** [comment]
Also bei mir funktioniert das ohne Probleme

**Comment by robka87owl** [comment]
![image](https://github.com/eiksch/statev_v3_issues/assets/140908156/6c3ffb82-7b12-47c1-997c-173e5137c438)
Hab auch nochmal vom Opera nach Explorer gewechselt, nach wie vor dieses Bild

**Comment by robka87owl** [comment]
Soeben habe ich ein neues Konto erstellt. Dort kann ich dann alles eintragen, bei den alten anderen 3 Konten leider nicht.

**Comment by simplycach** [comment]
Reicht dir das mit dem neuen Konto, weil scheinbar tritt der Fehler nur bei dir auf.

**Comment by robka87owl** [comment]
Moin, ja das reicht, danke.
