### ISSUE TITLE
Antrag für eine Hausgarage

### ISSUE THREAD

**Issue by SauerkirscheJM** [mexyn/statev_v2_issues#3412]
Hallo zusammen!

Ich wollte fragen ob es möglich wäre, für das Haus **house_Paletobay_27** (Adresse Procopio Drive 29) eine Garage hinzuzufügen.
Ich weiß nicht, ob das normal ist, aber das Garagenoverlay wird auch an der Tür und im Tablet angezeigt, es gibt aber keinen Punkt zum Einparken. 
Das Haus hat ein abgegrenztes Grundstück und eine große Einfahrt. Haber auch extra geguckt, ob es andere Häuser mit ähnlichen Begebenheiten gibt, die auch eine Garage haben. (Z.B. Procopio Drive 27)
![GTA5 2024-04-13 12-17-40](https://github.com/eiksch/statev_v3_issues/assets/123385988/31fac18e-cac2-4d41-acd1-3e91f2d30fb0) Mein Haus mit Einfahrt

Des Weiteren wollte ich fragen, ob es möglich ist, einen Punkt für den Balkon zu setzen. Da an der Seite des Hauses eien Tür ist, könnte man die als Eingang dafür benutzen und dann von einem Balkon auf den Anderen gelangen.
![GTA5 2024-04-13 12-15-35](https://github.com/eiksch/statev_v3_issues/assets/123385988/170a8c26-7cf5-4231-8eb1-840d0e71fa7b)

Für Fragen stehe ich gerne zur Verfügung.
Danke im Voraus!

**Comment by TheOutburst** [comment]
Garage kriegste next update
Portmarker machen wir nichtmehr, siehe Changelog vom 10.06

**Comment by SauerkirscheJM** [comment]
DANKE <3
