### ISSUE TITLE
Falsche Sitzposition in Interior Büroraum (normal)

### ISSUE THREAD

**Issue by DamienDuvall** [mexyn/statev_v2_issues#3413]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Damien Duvall

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.05.2024 18:30, wahrscheinlich dauerhaft

**Beobachtetes Verhalten**
Setzt man sich auf den Stuhl am Schreibtisch hinten im Büro, schaut der Charakter nach rechts gedreht statt gerade auf den Monitor. Alle anderen Sitzmöglichkeiten funktionieren wie gewünscht.

**Erwartetes Verhalten**
Charakter schaut auf den Monitor

**Schritte um den Fehler nachvollziehen zu können**
Hinsetzen mit Y (jede Auswahl)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
entfällt

**Optional: Video / Bilder des Fehlers**

![FehlerSitz](https://github.com/eiksch/statev_v3_issues/assets/170451637/8d0c0515-c37d-4658-bf5d-7fb91b87f1c6)

**Comment by TheOutburst** [comment]
mit dem heutigen Update behoben
