### ISSUE TITLE
Klebeband/Blitzer Bug/Fehler

### ISSUE THREAD

**Issue by MrShaddy96** [mexyn/statev_v2_issues#3414]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Logan Pearce

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Kann jederzeit reproduziert werden

**Beobachtetes Verhalten**

Wenn man mit Klebeband sein Kennzeichen abklebt und man das Fahrzeug einparkt und neu ausparkt, ist dass Kennzeichen wieder zu sehen und wird auch bei blitzern erkannt. Leider kann man zu diesem Zeitpunkt kein "neues" Klebeband anbringen.

**Erwartetes Verhalten**

Dass man Klebeband erneut nutzen kann oder dass es nachwie vor Zugeklebt bleibt.

**Schritte um den Fehler nachvollziehen zu können**

Kennzeichen abkleben, Fahrzeug einparken, Fahrzeug ausparken. Danach wird man wieder Geblitzt und man kann kein neues Klebeband anbringen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![3Ek9fub](https://github.com/eiksch/statev_v3_issues/assets/170477991/85c77451-bbbe-404b-b895-9d110709c82c)

**Comment by QA-Pregon** [comment]
Hast du da auch was anderes gemacht?
Kann ich wie beschrieben nicht reproduzieren.

**Comment by QA-Pregon** [comment]
@MrShaddy96 eine Antwort wäre zur Lösung gut ^^

**Comment by simplycach** [comment]
Da keine Antwort kam, schließen wir das mal.
