### ISSUE TITLE
Beantragung ATM an Tankstelle

### ISSUE THREAD

**Issue by SheoBam** [mexyn/statev_v2_issues#3415]
**Ich würde gerne einen ATM für eine Tankstelle beantragen, da dies doch einen erheblichen Wettbewerbsvorteil darstellt und die meisten Tankstellen damit ausgestattet sind. Die nächsten zwei ATMs befinden sich jeweils 1,5km von der Tankstelle entfernt. Da kommt wohl kaum jemand zurück, sondern fährt direkt zur nächsten Tankstelle. Bzw wissen sie auch nicht von deren Existenz der Geldautomaten, weil dies abgelegene Orte sind.**

Hash petrolstation14
Charakter Sarah_Sommerfeldt

![20240522211318_1](https://github.com/eiksch/statev_v3_issues/assets/95241865/be8b94eb-d8f0-473c-9bf8-f266804729b9)

**Comment by simplycach** [comment]
Hey leider, leider ist es nicht so einfach einen ATM einzubauen, daher können wir dort derzeit keine Kapazitäten reinstecken.
