### ISSUE TITLE
Klamotten Bug

### ISSUE THREAD

**Issue by JasminHarper** [mexyn/statev_v2_issues#3416]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Josefine_Miley

**Auftrittszeitpunkt (Datum / Uhrzeit)**
24.05.2024 I 13:30

**Beobachtetes Verhalten**
[F] Schwarze Nike Air Max Thea sind plötzlich Highheels. 
[F] [Glasses] Black Windsor ist am Charakter nicht sichtbar.

**Comment by SatyriaDine** [comment]
ist bekannt, sind dran :)
