### ISSUE TITLE
10F Widebody Schieben nicht abbrechbar

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3417]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

24.05
**Beobachtetes Verhalten**

Beim schieben eines 10F Widebody hat man eine Falsche Position, wodurch man das Schieben auch nicht mehr abbrechen kann
**Erwartetes Verhalten**

An der karre stehen und schieben
**Schritte um den Fehler nachvollziehen zu können**

10F Widebody schieben
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/58612983/f306947c-1a01-473d-ad98-3d0e831bf346)

**Comment by Erumeldor** [comment]
Nächstes Update fixed :)
