### ISSUE TITLE
Schuhe vertauscht im State Prison

### ISSUE THREAD

**Issue by CaddyLo** [mexyn/statev_v2_issues#3418]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name** Louisa Alvarez
 Louisa Alvarez

**Auftrittszeitpunkt (Datum / Uhrzeit)** 25.05.2024 20:29 Uhr
 25.05.2024 20:29 Uhr

**Beobachtetes Verhalten**
 Im State Prison wurde durch das Arbeitssystem ein Klamottentausch vollzogen bei diesem tausch habe ich Weiße Slipper bekommen die beim anziehen aber High Heels waren.  
Foto des Items im Inventar: https://prnt.sc/gxta6uCZw3Pt
Foto des Items wenn die Schuhe angezogen wurden: https://prnt.sc/WhtgHE-v74OQ

**Erwartetes Verhalten**
 Wenn ich Weiße Slipper anziehe sollten es eine Art Turnschuhe sein und keine High Heels

**Schritte um den Fehler nachvollziehen zu können**
 Erarbeite durch die Jobs im State Prison Knastzigaretten und kaufe dir dafür Weiße Slipper beim NPC. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by QA-Pregon** [comment]
War dem Klamottenbug geschuldet und is fixed
