### ISSUE TITLE
Mystique Punkt funktioniert nicht

### ISSUE THREAD

**Issue by Kane403** [mexyn/statev_v2_issues#3419]
Der folgende Mystique Punkt im Laden bei 5001 funktioniert seit Update V3.2 nicht mehr bei mir (lässt sich nicht per "E" starten).
Gamerestart hat bei mir nichts gebracht.

![grafik](https://github.com/eiksch/statev_v3_issues/assets/142750337/83352051-c973-49b2-8a9a-9bce3617cb58)
![grafik](https://github.com/eiksch/statev_v3_issues/assets/142750337/27d89454-1bf8-4fa9-ad85-73c17a859dd3)

**Comment by DerKryptex** [comment]
Selber Laden, auch bei der Mission von Terry funktioniert bei mir der Punkt am Tresor nicht, er reagiert gar nicht, mit oder ohne Maske

**Comment by Statev-Bonsai** [comment]
das liegt am neuen schutzgeld system, die punkte liegen übereinander.. und man kann nur auf den tresor fürs schutzgeld zugreifen... habe auch den bug.. echt nervig weil man die mission nicht abschließen kann und 45min warten muss

**Comment by QA-Pregon** [comment]
fixed
