### ISSUE TITLE
Produzierte Items erst nach erneutem Produktionscomputer Zugriff sichtbar

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#342]
**Beobachtetes Verhalten**
Wenn man eine Produktion startet und vom Produktionscomputer weg geht, währenddessen die Produktion fertiggestellt wird, ist das Item nicht direkt im Maschinenlager. Sondern erst, nachdem man erneut an den Computer geht, ist das Item erst dann im Maschinenlager.

**Erwartetes Verhalten**
Das Item sollte direkt nach Fertigstellung im Maschinenlager erkennbar sein.

**Schritte um den Fehler nachvollziehen zu können**
1. Produktion starten und Produktionsrechner schließen
2. Warten bis fertig ist
3. Erst ans Maschinenlager geht

Original BT Eintrag:
https://statev.de/forum/StateBug/index.php?issue/3910-produktionsausgabe/#comment5666

**Comment by r3sist3nt** [comment]
Das ist so Designed und auch gewollt.
