### ISSUE TITLE
Paketbote verhindert laufen, springen und ins Fahrzeug einsteigen

### ISSUE THREAD

**Issue by Snipser92** [mexyn/statev_v2_issues#3420]
**Character Name**
Raik_Morton

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.15 25.05.2024
**Beobachtetes Verhalten**
Ich wollte als Firmeninhaber mal den Paketbotenjob ausprobieren. Mir wird angezeigt das ich schon in der Firma "MS 745" eingestellt bin. Dann kann ich nicht mehr springen, joggen oder laufen und ins eigene Fahrzeug einsteigen. Nach erneuten ansprechen des NPC ging es wieder

**Erwartetes Verhalten**
NPC ansprechen, Job bekommen und alles normal machen können

**Schritte um den Fehler nachvollziehen zu können**
gleiche machen wie oben beschrieben

**Comment by DrGrizzlY17** [comment]
Hast du vielleicht nebenbei dein Handy aufgehabt?

**Comment by Snipser92** [comment]
Ja hatte ich, habe auch nach dem telefonieren das Problem weiterhin gehabt, bis ich mit dem NPC geredet hatte.

**Comment by DrGrizzlY17** [comment]
Ok sind dran :)

**Comment by DrGrizzlY17** [comment]
Erstmal nicht über N auflegen

**Comment by Kaycee91** [comment]
Hab nen ähnliches Problem kann also weder rennen noch JOggen noch sonst was und hatte das handy nur drausen hab aber regulär aufgelegt also nicht mit "N"

**Comment by QA-Pregon** [comment]
Sollte fixed sein, ansonsten nochmal neu
