### ISSUE TITLE
Charakter Kleidung : Armreif/Halskette bei Männern nciht gleichzeitig anlegbar

### ISSUE THREAD

**Issue by Feuronos** [mexyn/statev_v2_issues#3421]
John Brick

Am 25.05.24 um c.a 12:50

**Beobachtetes Verhalten**
Beim anlegen der Halskette verschwindet der Armreif (Bleibt aber im slot) und anders ehrum auch 

**Erwartetes Verhalten**
Beide Schmuckstücke sollten weiterhin angezeigt bleiben am char und sich nciht  unsichtbar machen

**Schritte um den Fehler nachvollziehen zu können**
Video:
https://medal.tv/de/games/gta-v/clips/2fbRzpmIqUrUwK/d1337nUBYbnD?invite=cr-MSxub24sNTk5OTcwMDEs

Gruß
John

**Comment by stepz2k9** [comment]
Liegen auf dem gleichen Slot. #2550

**Comment by TheOutburst** [comment]
Das was Caleighe sagt
Geht leider nicht anders, sorry
