### ISSUE TITLE
Kein "Rennen", "joggen", "Einsteigen" oder sonstiges nach Telefonat möglich!

### ISSUE THREAD

**Issue by CalebPapaCrane** [mexyn/statev_v2_issues#3422]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Caleb_Roberts**
#
Bei einem Telefonat

**25.05.2024 - 13:31 (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
Nach dem Telefonieren, ist es nicht möglich zu rennen, laufen, ins fahrzeug einzusteigen, animationen zu machen oder sonstiges

**Erwartetes Verhalten**

Weiterhin normales spielen :D

**Schritte um den Fehler nachvollziehen zu können**

Telefonieren - Auflegen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

FHD

**Optional: Video / Bilder des Fehlers**

**Comment by CalebPapaCrane** [comment]
Tirtt übrigens nur auf, wenn man selbst auflegt mit "N".

**Comment by DEHUNTER58711** [comment]
Ich kann das bestätigen, Problem ist vorhanden auch bei mir

**Comment by SatyriaDine** [comment]
#3420
