### ISSUE TITLE
Angelegter Rucksack wird nicht angezeigt

### ISSUE THREAD

**Issue by Cortain** [mexyn/statev_v2_issues#3423]
**Character Name**
Mike Fisher

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.05.24 15:40

**Beobachtetes Verhalten**
Nach dem Anlegen des Rucksacks "Blauer Denim Camping Backpack", ist dieser seit dem Update nicht mehr zu sehen. Funktional ist er aber nach wie vor.

**Erwartetes Verhalten**
Auf dem Rücken sollte der Rucksack zu sehen sein

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/125522102/278bc2ae-3356-4ef3-bb7d-22a0347b79ee)
![image](https://github.com/eiksch/statev_v3_issues/assets/125522102/d6f5b152-1de1-4d09-afad-0d254da1f60c)

**Comment by QA-Pregon** [comment]
Bekannt und sind dran, danke trotzdem ^^
