### ISSUE TITLE
Postboten Job in Paleto

### ISSUE THREAD

**Issue by Finja76** [mexyn/statev_v2_issues#3425]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Fiona Wagner
**Auftrittszeitpunkt (Datum / Uhrzeit)**

25.05.2024 / 17.30 Uhr
**Beobachtetes Verhalten**

Beim 6ten Spot ausliefern kam ein zweiter Postvan um Päckchen zu laden auf dem Spot den ich angefahren hatte, er parkte vor meinem Van und fing an seine 6 Päckchen/Auslieferpunkte zu laden und fing an auszuliefern, ich bekam keinen Payout und konnte meinen Van nicht mehr bewegen. Ich habe dann einen Relog versucht der hat nichts verändert, bin dann zu Fuß zum Post Arbeitgeber gelaufen, gekündigt und den Job neu angenommen in der Hoffnung das er mir den gebuggten Van neu zuweißt. Bin zurück zum Van gefahren aber ich konnte ihn leider immer noch nicht bewegen. Jetzt steht der Van auf einen der Ladepunkte in Paleto, vielleicht könnt ihr ihn dort weg holen... Vielen Dank im Voraus.
**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by QA-Pregon** [comment]
Bitte um mehr Infos, an welchem Spot exakt warst du in Paleto?
Bei welcher PLZ stand dein Truck und an welchem Haus ging was kaputt?

**Comment by QA-Pregon** [comment]
Und wann genau kam der andere Postvan dann an und hat der den Hauptspot erreicht oder ein Haus?
+ haste nen Clip?

**Comment by Finja76** [comment]
Ich stand vor dem Haus Procopio Drive 6, PLZ 937 auf dem Ladepunkt für die 6 Pakete.. ich bin dann die 6 Häuser abgelaufen um die Pakete zuzustellen.... Procopio Drive 6 war mein letztes Paket und bin dann zurück zu meinem Van... Dort stand dann der andere Postvan der auch 6 Pakete laden wollte... Ich meinte noch , kleinen Moment und wollte den Spot frei machen für ihn... Der Radius scheint aber so groß zu sein das er auch so laden konnte indem er vor mir gepart hatte und meinte dann zu mir alles ok, geht schon so ... Ich stieg in meinen Van und bekam kein Payout und konnte ihn nicht mehr bewegen und mein dritter Ladespot war auch nicht mehr zu sehen. Dieses passierte heute am 25.05.2024 um ca. 17.30 Uhr. Ich habe aber gesehen das der Postvan mitlerweile wieder neben dem Arbeitgeber steht... Keine Ahnung ob ihr Ihn vom Team schon zurück gesetzt habt. Einen Clip habe ich leider nicht. Mir geht es auch gar nicht um den Payout , wollte den Bug einfach nur melden :) hatte schon ein paar Runden vorher gefahren und Pakete ausgeliefert was mir sehr viel Spaß gemacht hatte.  Liebe Grüße :)

**Comment by QA-Pregon** [comment]
Bist du bevor du alle 6 Pakete abgegeben hast einmal kurz im Postfahrzeug gewesen oder bist du alle 6 Häuser am Stück abgelaufen ohne im Postauto zu sitzen

**Comment by Finja76** [comment]
Ich bin alle 6 Häuser am Stück abgelaufen wie die vier Lieferungen a 6 Pakete davor auch schon :)

**Comment by QA-Pregon** [comment]
Nachdem du am 6. Haus warst, stand dann unten links, dass du zum Postauto zurück sollst oder stand die Nachricht nicht da?

**Comment by Finja76** [comment]
Ja die stand dort

**Comment by QA-Pregon** [comment]
ok
falls du dich dran erinnerst:
ist die andere Person ausgestiegen nachdem du das 6. Haus fertig hattest oder davor?

**Comment by Finja76** [comment]
er stieg aus als ich am Van wieder ankam nach der letzten Auslieferung, da meinte ich, " oh kleinen Moment ich mache Platz ", da ich dachte er muss auch genau auf diesen Spot laden, er aber meinte " alles gut geht schon " und bei mir ging dann gar nichts mehr und es wurmte mich persönlich das ich den Van da nicht mehr weg bekam und einen Moment echt ratlos war. Er konnte aber laden und auch weiterhin ausliefern.

**Comment by MarcelMuerto** [comment]
N'Abend,
es kam am heutigen Tag ein Update mit viele Fixes.
Bitte könntest du es nochmal testen, ob es bei dir weiterhin auftritt. @Finja76 
Bisher konnten wir das bei uns nicht nachstellen.

Grüße
Marcel

**Comment by MarcelMuerto** [comment]
@Finja76 Beim heutigen Updaten, kam nochmal eine Überarbeitung des Lohnsystems. 
Ich würde damit erstmal das Issue schließen, sollte es nochmal vorkommen, dann bitte schreib uns nochmal ein neues Ticket.
