### ISSUE TITLE
Unterbodenbeleuchtung Taxi Vapid

### ISSUE THREAD

**Issue by Sour247** [mexyn/statev_v2_issues#3426]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
Beim dem Fahrzeug Vapid Taxi 101 PS sollte unterbodenlicht verbaut werden, dieses konnte gestartet werden wurde aber nicht verbaut.

**Erwartetes Verhalten**
Verbauen der Beleuchtung und benutzen jener

**Schritte um den Fehler nachvollziehen zu können**
Beleuchtung in der Werkstatt in ein Taxi einbauen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by QA-Pregon** [comment]
Ich könnte damit falsch liegen, aber ich glaub nen Taxi kann keine Unterboden haben.
Bemerkbar is das dadurch, dass beim Farben durchgucken vorm Einbau auch keine sichtbar gewesen ist denke ich mal oder?

@simplycach korrigier mich wenn ich da falsch liege

**Comment by QA-Pregon** [comment]
Taxis haben keine UBB
