### ISSUE TITLE
Masken tragen mit Modhaaren

### ISSUE THREAD

**Issue by RoseGamingx** [mexyn/statev_v2_issues#3427]
**Character Name**
Mit einem weiblichen Char, Naomi Rose

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.05.2024 / 20:15 Uhr

**Beobachtetes Verhalten**
Die Maske ist unter den Haaren zu sehen

**Erwartetes Verhalten**
Die Maske verdeckt komplett alles, ebenfalls die Haare

**Comment by ySimbaa** [comment]
sollte fixed sein.
