### ISSUE TITLE
Skill 2 "Busfahrer" wird nicht richtig bezahlt

### ISSUE THREAD

**Issue by oxmoxdings** [mexyn/statev_v2_issues#3428]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Boots Miller

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.05.2024 - 22.50 Uhr

**Beobachtetes Verhalten**
Den Skill "Busfahrer" auf Level 3 geskillt und obwohl da 2% mehr Geld pro Haltestelle kommen sollten sind es auf der Linie immernoch nur 4 Dollar.

**Erwartetes Verhalten**
Es sollten 2% mehr sein, also $4,08.

**Schritte um den Fehler nachvollziehen zu können**
Mit Skill 3 "Busfahrer" fahren.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by oxmoxdings** [comment]
Sorry, Skill 2 ist natürlich gemeint.

**Comment by MarcelMuerto** [comment]
@oxmoxdings Wir konnten das benannte Verhalten bei uns reproduzieren und sind aktuell dabei eine Lösung zu erarbeiten. Bitte habe noch etwas Geduld.

**Comment by MarcelMuerto** [comment]
@oxmoxdings Im heutigen Update kam die obengenannte Lösung. Wünsche dir weiterhin viel Spaß beim Spielen auf StateV.
