### ISSUE TITLE
NOS Anzeige Bug

### ISSUE THREAD

**Issue by MrShaddy96** [mexyn/statev_v2_issues#3429]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Logan Pearce

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.05.2024 ca. 22:45

**Beobachtetes Verhalten**
Wenn man NOS aktiviert sieht man den Dampf an der Motorhaube nur als Fahrer

**Erwartetes Verhalten**
Man sieht es auch als Beifahrer oder Passant

**Schritte um den Fehler nachvollziehen zu können**
NOS einbauen einer ins auto einer draußen stehen bleiben und Shift drücken ohne gas zu geben.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Also das konnte ich bisher so nicht reproduzieren, wir haben das immer gesehen.
