### ISSUE TITLE
EAuto laden ohne bezahlung

### ISSUE THREAD

**Issue by badshah23** [mexyn/statev_v2_issues#343]
Yuri_Greene

Beobachtetes Verhalten
Wenn man sein eauto lädt und nicht genug Bargeld einstecken hat, kommt nach der Aufladung der Hinweis das nicht genügend Bargeld vorhanden ist und laden nicht möglich ist, aber Auto ist vollgeladen. 

Erwartetes Verhalten
Ladevorgang sollte den Ladevorgang nicht starten oder nur so viel laden wie auch Bargeld vorhanden ist.

Schritte um den Fehler nachvollziehen zu können

Auto an Ladesäule geparkt und Ladevorgang starten, dabei kein Bargeld oder weniger als die angezeigte Endsumme dabei haben.

**Comment by M4rvinLP** [comment]
Kann ich so bestätigen.
Gibt es zusätzlich noch einen Faktor fürs aufladen? Habe beobachtet das 1 Akkuzelle 1% beim Auto ist. Jetzt hat jemand 22 Akkuzellen verbraucht und ist von 38% auf 69% gestiegen.

**Comment by TheBroady** [comment]
Kann ich ebenso bestätigen. Gestern nochmal an der Tankstelle im Mirrorpark getestet. 20 akkuzellen sind verbraucht worden, kein Geld überwiesen worden.

**Comment by r3sist3nt** [comment]
siehe #397, ist fixed

**Comment by r3sist3nt** [comment]
@M4rvinLP nein, Prozent heißt Prozent. Das ist ein Anteil. Wenn ein Auto einen Speicher für 50 Ladezellen hat, dann wäre eine Ladezelle 2% u.s.w.
