### ISSUE TITLE
Body clipped durch Oberteil

### ISSUE THREAD

**Issue by lavouuzu** [mexyn/statev_v2_issues#3431]
**Jasper Richmond**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer
**Beobachtetes Verhalten**

Bei dem Kleidungsstück Black Slim T-Shirt v2 gibt es keine Body Einstellung bei der nichts von der Haut durchscheint (alle Kurzarm Einstellungen ausprobiert)
**Erwartetes Verhalten**

Kurzarm 5 mit passender Arm Einstellung

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/74792311/27fce7a5-2e4d-4c7b-9e38-549eb6034a75)

**Comment by ySimbaa** [comment]
Da es sich hier um Mod-Kleidung handelt es ist es immer wieder möglich das ein bisschen irgendwo je nach Perspektive und Animation was durch clippt.
