### ISSUE TITLE
Shanel Blush Palette nicht vorhanden falsche bez. in Fertigung?

### ISSUE THREAD

**Issue by Xymena** [mexyn/statev_v2_issues#3432]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit dem letzen update. 
**Beobachtetes Verhalten**
Bei den versuch jemanden ein Blush aufzutragen ist uns aufgefallen das die Shanel Blush Palette benötigt wird. bis Dato konnte diese aber nirgend wo erstellt werden. 

in der Fertigung gibt es die packagedeyeShadowpalettes  die zu ein fehler bei der produktion führt. 

**Erwartetes Verhalten**

Herstellung von der Shanel Blush Palette

**Schritte um den Fehler nachvollziehen zu können**

in der Fertigung Shanel Blush Palette nicht vorhanden. 
der 24/7 kann diese auspacken. 
im Friseur wird diese benötigt. 
Wir haben auch keine andere Firmer gefunden die sie herstellen kann.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/76626768/0440a058-8b18-469f-b70f-584975ac5de1)

**Comment by SatyriaDine** [comment]
Beim Testen konnte ich gerade beide Paletten in der Fertigung herstellen. Teste bitte nochmal :)

**Comment by QA-Pregon** [comment]
Denke mal die Herstellung an sich ist Möglich, da mir beim testen aufgefallen ist, dass der Itemname nicht mehr der Hash ist, aber die Itembilder fehlen noch

**Comment by Xymena** [comment]
Herstellen geht jetzt, nur generell die items bei den neuen fehlt noch ist korrekt

**Comment by QA-Pregon** [comment]
Passt da mitlerweile alles oder ist es immer noch unstimmig

**Comment by SatyriaDine** [comment]
hier sollte mittlerweile alles passen. :)
