### ISSUE TITLE
Nach Auto Tuning flippt das auto fast jedes mal

### ISSUE THREAD

**Issue by Gelawyn** [mexyn/statev_v2_issues#3433]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Chris Johnson

Chris Johnson
**Auftrittszeitpunkt (Datum / Uhrzeit) 28.05.2024 15.45

28.05.2024 15.45Uhr
**Beobachtetes Verhalten**
Ich wollte mit dem Auto nach dem Tuning zur nöchsten garage um einmal aus und einzuparken , Es kam eine kleine erhebung und das auto ist da gegen geknallt und abgehoben etc.

**Erwartetes Verhalten**
 Bodenwellen oder steigung oder auch bordsteine sollten so etwas nicht triggern

**Schritte um den Fehler nachvollziehen zu können**
 Stoßstange Tunen und losfahren.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Erumeldor** [comment]
Hi,
du hast dein Auto nicht dazugeschrieben, es wird aber dasselbe sein wie hier:
https://github.com/eiksch/statev_v3_issues/issues/3135

Ist ein AltV Bug, wir sind da aber noch dran.

**Comment by Gelawyn** [comment]
Oh ja das stimmt. ich schaue mir halt nicht jeden bug an . bzw stimmt auch mit dem auto^^ ist ein RH8

**Comment by Gelawyn** [comment]
und nach dem man eingeparkt hat ist das wieder weg komischerweise!
