### ISSUE TITLE
Grüner Sessel in Produktion Fertigung nicht benannt

### ISSUE THREAD

**Issue by LeaBrandt** [mexyn/statev_v2_issues#3434]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Ronja Brandtberg

**Auftrittszeitpunkt (Datum / Uhrzeit)**
28.05.2024 etwa 17 Uhr

**Beobachtetes Verhalten**
In der Maschine der Fertigung wird der Artikel als packagedArmChairGreen1 angezeigt. 

**Erwartetes Verhalten**
Anzeige des richtigen Artikelnamens...

**Schritte um den Fehler nachvollziehen zu können**
In die Fertigung gehen und versuchen zu produzieren.

**Optional: Video / Bilder des Fehlers**
![Unbenannt](https://github.com/eiksch/statev_v3_issues/assets/98689462/6d95644d-3c70-4000-b366-38397264505f)

**Comment by TheOutburst** [comment]
Hups
Next Update fixed
