### ISSUE TITLE
LKW Setzt sich nicht richtig Zurück

### ISSUE THREAD

**Issue by ManisBauer** [mexyn/statev_v2_issues#3435]
Guten Tag, 

Die LKWs am Truckerjob sollten sich nach gewisser Zeit wieder zurück setzen wenn keine Spieler in der Nähe sind, also Tank sowie Reparatur, um für den nächsten Spieler bereit zu stehen.
Nach einigen Touren ist mir allerdings aufgefallen, wenn sie zurück gesetzt werden, dann leider nur der Tank und die Reparatur teils gar nicht oder fehlerhaft.

Reparaturen über Werkstatt führen zum Verschluss des Lkws und somit Unbrauchbarkeit, da die Lkws zugeteilt werden und keine Schlüssel übergeben.

![LKW Bug](https://github.com/eiksch/statev_v3_issues/assets/171064134/865d3ea3-416b-423e-9a0d-1a11a1141fc5)

**Comment by MarcelMuerto** [comment]
@ManisBauer Das Problem wurde erkannt und eine Lösung ist in dem heutigen Update, somit schließe ich den Bugeintrag und wünsche dir weiterhin viel Spaß auf StateV.
