### ISSUE TITLE
Antrag für eine Hausgarage

### ISSUE THREAD

**Issue by PAEAEAEAEAET** [mexyn/statev_v2_issues#3436]
Hallo zusammen,

bei meinem Haus (house_EastLS_2, Fudge Lane 2) gibt es zwar eine geeignete, zugehörige Parkfläche, jedoch keine Garage. Die nächste öffentliche Garage ist gute 3 Minuten (Joggen) entfernt und es handelt sich leider nicht gerade um eine fußgängerfreundliche Strecke.

Deshalb habe ich folgende Bitte an euch: Wäre es möglich, dem Haus eine Garage zu setzen?

Danke im Voraus für die Bearbeitung der Anfrage,
Henry Wheeler

![20240528043813_1](https://github.com/eiksch/statev_v3_issues/assets/73844109/c353a67f-326c-42e1-87d8-4fa77f286df1)
![20240528043854_1](https://github.com/eiksch/statev_v3_issues/assets/73844109/2bdefb08-e22a-461d-84ac-86bb75027795)
![20240528043825_1](https://github.com/eiksch/statev_v3_issues/assets/73844109/6b2f9a7b-2cce-4b8a-ba05-9f1ad905558d)

**Comment by TheOutburst** [comment]
Garagenmarker nach aktualisierter Garagenregelung next update hinzugefügt
