### ISSUE TITLE
Ladepunkt umsetzen

### ISSUE THREAD

**Issue by MrFricke1** [mexyn/statev_v2_issues#3437]
Hi Könnt ihr meinen entladepunkt umsetzen von hinten nach vorne ? Grüße Fricke

Hash: tequilalabar

![GTA5 2024-05-28 20-01-49](https://github.com/eiksch/statev_v3_issues/assets/164243818/d5418f2d-12fe-4235-8c64-bec174db6d5e)
![GTA5 2024-05-28 20-01-34](https://github.com/eiksch/statev_v3_issues/assets/164243818/2ab710ff-5d92-4daa-b55c-fec80c497c49)

**Comment by Erumeldor** [comment]
@MrFricke1
Gibts dazu einen Grund? Der liegt doch eigentlich ganz gut oder?

**Comment by Erumeldor** [comment]
Wie per PMs geschrieben wird er erstmal dort gelassen.
