### ISSUE TITLE
Schild entfernen

### ISSUE THREAD

**Issue by xXCoCoNuTx3** [mexyn/statev_v2_issues#3439]
**Character Name**
Marcello Valentine

Hallo zusammen,

vor dem Haus steht ein großes Schild, wäre es möglich dieses zu entfernen? Das Haus befindet sich im Nikola Place 20 (Mirror Park Kreisel) 

house_MirrorPark_20 

https://pic.statev.de/i/HyN0kc.jpg

Danke im Voraus für die Bearbeitung der Anfrage,

**Comment by TheOutburst** [comment]
Nee, da im Mirror Park Kreisel sind die großen Schilder alle Teil vom Kreisel selbst, das kann man nicht so easy entfernen, sorry
