### ISSUE TITLE
Dienstwaffe taclight weggebugt

### ISSUE THREAD

**Issue by DerRazer** [mexyn/statev_v2_issues#3440]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Logan Pierce 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
28.05.2024 23:45 Uhr

**Beobachtetes Verhalten**
Konnte gestern meine Dienstwaffen nicht ablegen die meldeung war dafür bist du nicht bereit dann habe ich mich im SSSO Ausgeloggt 
heute Logge ich mich wieder ein meine Dienstwaffen konnte ich wieder ablegen aber mein Taclight ist auf einmal verschunden 

**Erwartetes Verhalten**
Dass das Taclight da ist und nicht verschwindet

**Schritte um den Fehler nachvollziehen zu können**
keine

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
keine

**Optional: Video / Bilder des Fehlers**

![Screenshot_10](https://github.com/eiksch/statev_v3_issues/assets/70866267/f626031d-4ad4-4fd5-bde6-52bafe944e62)

**Comment by AdmiralState** [comment]
+1 ist bei mir gestern Abend genau so passiert und das Taclight ist verschwunden.
Charname: Jacob Bennett

**Comment by DrGrizzlY17** [comment]
Passiert das öfters oder ist das danach erstmal nicht mehr aufgetreten?

**Comment by DerRazer** [comment]
kann ich leider nicht sagen da ich kein Taclight mehr auf der dienstwaffe habe und das LSPD gerade keine hat

**Comment by AdmiralState** [comment]
Hallo zusammen,
habe mal das Video material von mir angeschaut als ich es geclippt habe. Man sieht das das Inventar voll bzw "überladen" war. War mir zu diesem Zeitpunkt allerdings nicht bewusst. Beim entfernen vom Taclight ist es ins Inventar "verschwunden". Danach ging nichts mehr mit Waffen abrüsten.
https://streamable.com/m4mzik

**Comment by MarcelMuerto** [comment]
Wurde bei dem Helloween Update gefixt @DerRazer
