### ISSUE TITLE
Antrag auf Haus Garage

### ISSUE THREAD

**Issue by Maresal5561** [mexyn/statev_v2_issues#3441]
Hallo. Ich wollte bei meinem Haus eine Garage beantragen. Das Haus verfügt über einen geeigneten Stellplatz wo einige Häuser gleichermaßen eine Garage haben weshalb es schön wäre dort ebenfalls eine zu bekommen.
Hier einmal die zugehörigen Bilder vom Haus inklusive Daten vom Haus

Informationen zum Haus:
https://pic.statev.de/image/HyNlYC
Bilder vom Haus inkl vorgestelltem Garagenplatz:
https://pic.statev.de/image/HyNP7y
https://pic.statev.de/image/HyNWBu
https://pic.statev.de/image/HyNgZ2
https://pic.statev.de/image/HyNKHA

Bitte dabei beachten dass der relativ mittig gesetzt wird, nicht dass beim Ausparken von bspw einem längeren Auto (6x6), dieser nicht im Pavillion hängen bleibt.
In der Garage soll kein Fahrzeug wie Pounder o.ä geparkt werden weshalb dies nicht beachtet werden muss was in der Gegend auch nicht viel Sinn machen würde 😄

Wäre vielleicht sogar cool wenn man den Pavillion dort in der Einfahrt entfernen könnte sofern es nicht die ganze gegend nachladen lässt bei Spielern und dies möglich wäre ^^

Danke im Voraus 🙂

**Comment by TheOutburst** [comment]
Garagenmarker nach aktualisierter Garagenregelung next update hinzugefügt
Wir entfernen keine Objekte mehr, der Pavilion bleibt also
