### ISSUE TITLE
Postauto und Trucks bleiben verschlossen

### ISSUE THREAD

**Issue by DJBirdsong** [mexyn/statev_v2_issues#3442]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Alfred Vogelsang**

**28.05. und 29.05. um die Mittagszeit**

**Das Postauto in Sandy Shores ließ sich sowohl gestern als auch heute nach dem Annehmen des Lieferjobs in Sandy Shores nicht öffnen. Zudem konnten heute keine der beiden Trucks am Truckdepot genutzt werden (Selbes Verhalten wie bei dem Postauto in Sandy Shores). Zudem habe ich am Truckdepot jemanden beobachten können der offensichtlich das selbe Problem hatte wie ich.**

**Dass man nach dem Annehmen des jeweiligen Jobs beim NPC auch ein Fahrzeug nutzen kann bzw. zugewiesen wird**

**keine**

**keine**

**keine**

**Comment by MarcelMuerto** [comment]
Guten Abend,
das genannte Verhalten ist uns bereits bekannt und wir konnten auch eine Lösung erarbeiten. 
Diese Lösung kommt beim nächsten Update.

**Comment by MarcelMuerto** [comment]
@DJBirdsong Die Änderungen ist in dem heutigen Update, somit schließe ich den Bugeintrag. Wünsche dir weiterhin viel Spaß beim spielen auf StateV.
