### ISSUE TITLE
Eingang verlegen möglich?

### ISSUE THREAD

**Issue by robka87owl** [mexyn/statev_v2_issues#3444]
Hallo liebes StateV Team,

gerne möchte ich einmal Anfragen, ob es generell Möglich ist, den Eingang zu verlegen
Es geht hierbei um: 
![image](https://github.com/eiksch/statev_v3_issues/assets/140908156/fe54657c-a57f-4093-8c84-a25ec123f0b2)

Das der Eingang dann nach vorne verlegt wird:

![image](https://github.com/eiksch/statev_v3_issues/assets/140908156/1467c143-abb6-43c3-8011-356ea30dc619)
****

Sollte dies nicht Möglich sein, ist es an sich auch kein Problem.

**Comment by Erumeldor** [comment]
Hi @robka87owl 
sorry, das wird nichts hier ;)
