### ISSUE TITLE
Fahrzeug spawnt weg

### ISSUE THREAD

**Issue by loelchn** [mexyn/statev_v2_issues#3445]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Luca Lorenzi

meinen
**Auftrittszeitpunkt (Datum / Uhrzeit)**

seit gestern und heute auch
**Beobachtetes Verhalten**

mein Fahrzeug spawnt zurück, wenn ich vom Blumenfeld nach Paleto fahre, ins Labor gehen, und wieder herauskomme ist es wieder beim Blumenfeld. Gestern 2x, und vorhin wieder. Spawn Punkt am Blumenfeld ist aber immer derselbe Punk
**Erwartetes Verhalten**

Fahrzeug bleibt da wo es geparkt wurde
**Schritte um den Fehler nachvollziehen zu können**

hinfahren, in die Firma gehen, rausgehen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

hinfahren, in die Firma gehen, rausgehen
**Optional: Video / Bilder des Fehlers**

https://prnt.sc/IPMTH2JbS4TJ
da steht das Fahrzeug dann immer zurückgeportet

**Comment by adrosso** [comment]
Gleiche Spiel hatte ich die letzten Tage auch. Und JETZT schon wieder, dass ist leider echt nervig wenn das passiert.

**Comment by TheOutburst** [comment]
Das Problem sollte sich mit dem letzen Update gebessert haben, ist es seit dem 10.06 nochmal aufgetreten?

**Comment by loelchn** [comment]
Nein

TheOutburst ***@***.***> schrieb am Do., 13. Juni 2024, 13:18:
