### ISSUE TITLE
API-Ausgabe für Marktplatz-Ankäufe

### ISSUE THREAD

**Issue by ingo-lorenz** [mexyn/statev_v2_issues#3447]
Ich habe soeben bemerkt, dass die Preise für einen Ankauf am Marktplatz nicht die gleichen sind, wie die Ausgabe der API.

![Screenshot 2024-05-31 000208](https://github.com/eiksch/statev_v3_issues/assets/9450017/9ab4ea5d-92f6-4f39-8449-21c12bb58280)

Im Marktplatz werden 28,50 $ angezeigt und über die API sind es 30,00 $. Das ist nicht richtig so, oder?

Ich bin mir ziemlich sicher, dass das so ist, Habe meinen Ankauf gleich wieder entfernt.

Meiner Meinung nach fehlt da noch zusätzlich der Listenpreis, um auch diesen nutzen zu können.

Vielleicht könnt ihr das ja mal prüfen.

Danke und Grüße
Ingo

**Comment by ingo-lorenz** [comment]
Hat sich erledigt. Danke.

**Comment by SgtBoaz-Terry** [comment]
Hey,

das ist schon korrekt. Wenn du ein Produkt für 30$ einstellst, dann werden da für denjenigen, welcher die Ware bringt, 5% Steuern abgezogen. 5% von 30$ sind 1,5$. Damit erhält der Verkäufer bei deiner Firma die 28.5$. 
Listenpreis = Preis für Warenlieferant.
Reicht die Erklärung?

**Comment by ingo-lorenz** [comment]
Ja, das verstehe ich, aber dann fehlt mir noch der Listenpreis in der API-Ausgabe, um den gleichen Preis wie im Marktplatz angezeigt, zu erhalten.

Wäre schön, wenn es diesen Preis auch noch in der Ausgabe gibt, oder ich muss selbst die 5 % abziehen zur Ausgabe.

**Comment by rodistic** [comment]
hab mal was hinzugefügt (listPrice) guck mal ob das passt.

**Comment by simplycach** [comment]
Sollte behoben sein.
