### ISSUE TITLE
Kein Bild auf dem Ausweis

### ISSUE THREAD

**Issue by Quarkbaelchen** [mexyn/statev_v2_issues#3448]
**Character Name** Mina Cruz

 Mina Cruz

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 tatsächlich schon vor einigen Wochen und bis heute 31.05.2024 um 01:00 Uhr

**Beobachtetes Verhalten**
 Mir ist seit einigen Wochen aufgefallen, dass ich auf meinem IC Ausweis kein Bild habe.

**Erwartetes Verhalten**
 Im Normalfall sollte meines Wissens nach, nach dem Log In ein Bild von dem IC Charakter befinden.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot2 (597)](https://github.com/eiksch/statev_v3_issues/assets/171297959/46125f0a-9405-4452-981f-81949b387bcc)

**Comment by DrGrizzlY17** [comment]
Wenn du jemanden den ausweis zeigst, haben die dort auch kein Bild?

**Comment by Quarkbaelchen** [comment]
Nein die sehen auch kein Bild

**Comment by simplycach** [comment]
@DrGrizzlY17

**Comment by QA-Pregon** [comment]
Ist das immer noch so?

**Comment by Erumeldor** [comment]
Betrifft manche andere Spieler auch

**Comment by rodistic** [comment]
Ayy Gude,

das ist abhängig von einigen Grafikeinstellungen des Users, da können wir leider nix machen
