### ISSUE TITLE
[Bag] Swift Backpack aus dem Kleiderladen nicht anlegbar

### ISSUE THREAD

**Issue by DerHessenTyp** [mexyn/statev_v2_issues#3449]
**Andre Bailey**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Comment by DerHessenTyp** [comment]
Andre Bailey

31.05.2024 um 17:10 Uhr

Beobachtetes Verhalten
Es wurde ein Swift Backpack im Kleiderladen gekauft und man wollte ihn anlegen was aber mit der Fehlermeldung ,,Falsches Item für diesen Slot!" leider nicht funktioniert hat. Alle anderen kaufbaren Taschen oder Rucksäcke sind anlegbar.

Erwartetes Verhalten

Das man wie alle anderen Taschen diesen Rucksack auch anlegen kann.

Schritte um den Fehler nachvollziehen zu können

Tasche über den Slot ziehen und es kam die Fehlermeldung dass es das falsche Item für diesen Slot ist. Und die Tasche blieb natürlich somit auch im Inventar

**Comment by DerHessenTyp** [comment]
Zusätzlich ist die "LS Girlie Backpacks" zwar produzierbar und man kann Sie auch in die Theke legen + Preis einstellen aber man kann Sie dann nicht auswählen zum kaufen im Regal.

**Comment by SatyriaDine** [comment]
Bezüglich der "Swift Rucksäcke" haben wir hier auch noch ein Issue #3452
