### ISSUE TITLE
2x Crash an selber Stelle

### ISSUE THREAD

**Issue by Domeex3** [mexyn/statev_v2_issues#345]
Domenik Sommer

21.11.2020 20:08 und 20:53

Fahre Richtung Würfelpark die San Andreas Ave (Unter MazeBank Tower Brücke) runter, schon 2x an der selben Stelle Crash.

[altv_1301_Steam_0x9010f6_21-11-2020_20-08-27.zip](https://github.com/mexyn/statev_v2_issues/files/5578292/altv_1301_Steam_0x9010f6_21-11-2020_20-08-27.zip)
[altv_1301_Steam_0x6265f7_21-11-2020_20-53-12.zip](https://github.com/mexyn/statev_v2_issues/files/5578293/altv_1301_Steam_0x6265f7_21-11-2020_20-53-12.zip)

**Comment by eiksch** [comment]
@Domeex3 hast du noch eine client-XX-XX-XX-XX.log Datei für diesen Zeitraum?

**Comment by Domeex3** [comment]
[client_21-11-2020_20-22-19.log](https://github.com/mexyn/statev_v2_issues/files/5579619/client_21-11-2020_20-22-19.log)
[client_21-11-2020_19-18-30.log](https://github.com/mexyn/statev_v2_issues/files/5579620/client_21-11-2020_19-18-30.log)

Bitteschön

**Comment by DonVitoDiangelo** [comment]
War vermutlich nen Abschlepper...
