### ISSUE TITLE
Lucas ist geizig (Kein Payout)

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3450]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Jackson Kenzo
**Auftrittszeitpunkt (Datum / Uhrzeit)**

01.06 13:40
**Beobachtetes Verhalten**

Nach einem Schrottplatz ist er zu Lucas gegangen und wollte die Mission abgeben. Es kam die Meldung, dass der Loyalitätsbonus ausgezahlt wurde aber kein geld wurde übertragen. Zudem war die Mission nicht zuende, sodass diese erneut abgegeben werden konnte auch wieder ohne geld aber mit nem abzug im Loyalitätsbonus.

Als es keinen Bonus mehr gab und zwischen durch gegessen wurde in einem Restaurant ging das Payout
**Erwartetes Verhalten**

Man kann es normal abgeben
**Schritte um den Fehler nachvollziehen zu können**

Schrottplatz machen und von Lucas ausgebeutet werden
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://medal.tv/games/gta-v/clips/hYR0T5N2Z1Cv_Oqg4/d13371f3GIlu?invite=cr-MSxUcjQsMjIyNjEyMzU0LA

**Comment by DrGrizzlY17** [comment]
Wir waren pleite, sollte nicht mehr passieren

**Comment by SHaagmann** [comment]
> Wir waren pleite, sollte nicht mehr passieren

An wen kann man die Verlorenen Boni in rechnung stellen 😂

**Comment by DrGrizzlY17** [comment]
rückerstattung@gibts.nicht
