### ISSUE TITLE
Hotel Zimmerpreis ändern CELL_RENT_TOO_LOW

### ISSUE THREAD

**Issue by DEHUNTER58711** [mexyn/statev_v2_issues#3451]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Sergei_Popov

**Auftrittszeitpunkt (Datum / Uhrzeit)**
00:04 Uhr 02.06.2024

**Beobachtetes Verhalten**
Wenn man als Besitzer ein Hotel für z. B. 1$ gemietet hatte und dieses wieder kündigt, kann man den Preis wg. einem Fehler nicht anheben.

**Erwartetes Verhalten**
Preis kann nach Kündigung angehoben werden

**Schritte um den Fehler nachvollziehen zu können**
Hotelzimmer Mieten, Kündigen, Preis versuchen anzupassen.

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/170087823/99718d9d-7133-49b4-89e5-9a418d3781a5)

**Comment by Pregon** [comment]
Auf was wollteste den Preis setzen?

**Comment by rodistic** [comment]
Ayy Gude,

der Fehler ist noch nicht übersetzt, kommt erst die Tage :eikschhund: 
Aber grundlegend gibt es jetzt eine Mindestmiete

**Comment by DEHUNTER58711** [comment]
Hi,

das habe ich mir schon gedacht, aber ich will die Miete hochsetzen und das geht nicht? Ich wollte von 1$ auf 15$ hochsetzen oder ist das zu wenig? Auch bei 150$ funktioniert das ebenfalls nicht.

**Comment by QA-Pregon** [comment]
Sollte eigentlich passen, probiers gern nochmal.
Falls es nicht geht kümmern sich die Devs mal drum

**Comment by simplycach** [comment]
Scheint behoben zu sein.
