### ISSUE TITLE
Retraurant falsche anzeige 

### ISSUE THREAD

**Issue by Sour247** [mexyn/statev_v2_issues#3453]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.06.2024 17:50

**Beobachtetes Verhalten**
https://prnt.sc/jY78oeo0IQmK  Nach einstempeln im Restaurant Wingstop konnte ich in Paleto Diner wartende Gäste auf der Karte vernehmen.

**Erwartetes Verhalten**
Nur Gäste im eigene Restaurant sehen

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Passiert das immer oder war das einmalig?

**Comment by Sour247** [comment]
ich hatte das bis dato das 2te mal aber ka wann das erstemal wahr hielt es für ne einmalige sache,
kam bis jetzt auch nicht mehr vor

**Comment by CCastles22** [comment]
> Passiert das immer oder war das einmalig?

war schon öfters so, teilweise waren die Symbole in Paleto oder auch zb in Sandy
Ist jetzt aber nicht so das weltbewegende Problem

**Comment by simplycach** [comment]
Fehler noch aktuell ?
