### ISSUE TITLE
CID Dienstkleidung mit Krawatten zeigt SK-4 Weste nicht an

### ISSUE THREAD

**Issue by aembee** [mexyn/statev_v2_issues#3454]
**Character Name**

Eterio Santos

**Auftrittszeitpunkt (Datum / Uhrzeit)**

02.06.2024 - 23:40 Uhr

**Beobachtetes Verhalten**

Jegliche Krawatten als Dienstkleidung verhindern das anzeigen von Westen (nur SK-4 getestet, schätze aber die anderen werden auch nicht gehen)

**Erwartetes Verhalten**

Krawatte sollte verschwinden und stattdessen sollte Weste angezeigt werden.

**Schritte um den Fehler nachvollziehen zu können**

Jegliche CID Kleidung mit Krawatte auswählen und dann SK-4 Weste anziehen.

**Comment by quotenben** [comment]
@aembee Liegt daran, dass sich die Westen und CID Krawatten den Westenslot teilen. Der normale Krawattenslot wird nämlich schon von den Holstern/Marken belegt. Deshalb gibt es extra Cop Krawatten. Da diese im Outfitter festgelegt werden müssen, können sie nicht von der angezogenen Weste überschrieben werden. Ist wie wenn man bei den Uniformen auch andere Kleidung anziehen kann, diese aber nicht angezeigt wird.

**Comment by TheOutburst** [comment]
Das was Ben sagt
Ist leider durch die GTA Cloth Sloth Limitierung nicht anders lösbar
