### ISSUE TITLE
Dinka Jester RR Drift nicht baubar

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#3455]
**Character Name**
Charly Russo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01:40 Uhr 03.06.2024

**Beobachtetes Verhalten**
Der Dinka Jester RR Drift wird in der Autofertigung nicht gelistet und ist nicht baubar

**Erwartetes Verhalten**
Sollte baubar sein wenn man den Motor kaufen kann :(

**Schritte um den Fehler nachvollziehen zu können**
Autofertigung gucken, traurig sein

**Optional: Video / Bilder des Fehlers**
https://i.imgur.com/mQjX6En.png

Da ist der Motor

**Comment by SatyriaDine** [comment]
Glaube der Motor ist aus Versehen in den Import gerutscht. Weil eigentlich soll der noch gar nicht dabei sein, da der aktuell durch alt:V im Innenraum noch ziemlich verbuggt ist. Denke @Erumeldor kann da noch mehr zu sagen. :)

**Comment by Philosofisch** [comment]
Oh das ist sad, hätte gerne den Normalen und den Drifter gehabt :I könnte ich denn dafür das Geld zurück bekommen bitte? Waren nach Steuern 7.480$

https://i.imgur.com/X4bPQH6.png

**Comment by Erumeldor** [comment]
Melde dich mal bitte per Discord Ticket, Ping mich dann :)
