### ISSUE TITLE
Fehlplatzierung einer Garage - Hash "house_Davis_16"

### ISSUE THREAD

**Issue by Niiishaa** [mexyn/statev_v2_issues#3457]
Nedaara_Deronvil

Fehlplatzierung einer Garage 
Ich habe vor ein paar Wochen ein Haus, welches sich auf dem Roy Lowenstein Blvd. befindet, gekauft.  Allerdings ist mir heute aufgefallen, dass die Garage, welche sich auf dem Grundstück des Hauses befindet, einem anderen Haus zugeordnet ist. Der Hash von dem Haus lautet "house_Davis_16". Da wäre die Frage ob sich daran etwas machen lässt. 

![Haus 1](https://github.com/eiksch/statev_v3_issues/assets/120753499/d66a875c-0ef3-4c08-abeb-5ca7d56b41ca)
![Haus 3](https://github.com/eiksch/statev_v3_issues/assets/120753499/5f13da9c-362b-4a22-a937-770da98874f2)
![Haus 2](https://github.com/eiksch/statev_v3_issues/assets/120753499/c9c2b32b-e4fc-428f-9a66-7a5a0b04beac)

**Comment by TheOutburst** [comment]
Auf wessen Grundstück sich die Garage jetzt befindet wäre nen Fall fürs Katasteramt, die Garage ist dem linken Haus zugeordnet und dem kann man das jetzt auch nicht Ersatzlos streichen

Ich hab mal einer der zwei Garagen im Garten nen Garagenmarker verpasst, musst nur hoffen dass dein Nachbar dir auch die Zufahrt gewährt.
