### ISSUE TITLE
Überprüfung Crime Skill "Dieb"...

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3458]
Ein paar Spieler und ich haben das Gefühl das wenn man den Skill "Dieb" auflevelt die Ausbeute sinkt.
Klar ist es RNG, aber man kann ja nachfragen ob im Skill sich eine Fehlberechnung eingeschlichen hat (kam ja in der Vergangenheit schon vor).

Wenn es nicht so sein sollte ist es einfach nur Bad Luck zurzeit ;D

**Comment by DrGrizzlY17** [comment]
Da passt alles :)
