### ISSUE TITLE
Einparken in Autohaus Garage beim Restart

### ISSUE THREAD

**Issue by Rehki** [mexyn/statev_v2_issues#3459]
Rayana Vemo

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer zum Restart

Meine Double Ti, die gefühlt schon 100x in der öffentlichen Garage eingeparkt wurde, wird beim Restart, sobald sie draußen steht und nicht genug gefahren worden ist, beim MBM Autohaus in die Garage eingeparkt.

**Erwartetes Verhalten**

Sie wird in der öffentlichen Garage eingeparkt, wie vorgesehen.

![Grand Theft Auto V Screenshot 2024 06 04 - 12 12 29 14](https://github.com/eiksch/statev_v3_issues/assets/87999101/b92df050-5d81-4008-8805-2fff1844760f)

**Comment by SgtBoaz-Terry** [comment]
Hi @Rehki,
hast du das Bike auch bei MBM damals neu gekauft?
Wie oft kommt das vor? Nach jedem Restart oder nur sporadisch?

**Comment by Rehki** [comment]
hey, 
Ja, gekauft habe ich es bei MBM.
Bei jedem Restart, bei dem es automatisch eingeparkt wird aufgrund von zu wenig KM, landet es dort. 
In die Öffentliche ist es bisher noch nie automatisch eingeparkt worden.

**Comment by Rehki** [comment]
![Opera Momentaufnahme_2024-06-08_122527_vnet statev de](https://github.com/eiksch/statev_v3_issues/assets/87999101/e69fb0fd-70fc-4721-b9be-062bb7ba49b6)

Hab das mit Absicht heute mal automatisch einparken lassen zum Restart und ist wieder beim MBM eingeparkt worden...

**Comment by SgtBoaz-Terry** [comment]
Hallo.
Danke dir für die Antwort. Wir schauen uns das dann an, woran das liegt :)
Solange etwas Geduld.

**Comment by SgtBoaz-Terry** [comment]
Hey @Rehki 
Kannst du mir bitte Rückmeldung nach den nächsten Restarts geben, ob es immer noch vorkommt?
Müsste aber jetzt nicht mehr passieren

**Comment by Rehki** [comment]
Hey @SgtBoaz-Terry ,

Die letzten 2 Tage wurde das immer in der Öffentlichen eingeparkt: Ich danke dir/euch 😉
