### ISSUE TITLE
Fahrzeugbug nach Reperatur

### ISSUE THREAD

**Issue by Domeex3** [mexyn/statev_v2_issues#346]
Domenik_Sommer

Nach Gamecrash Lichter und Scheiben i.O. nach 2m Fahren alles kaputt. 
-> Reperatur in der Werkstatt sobald schneller als ca. 15kmh geht wieder alles Kaputt
-> Gefixt nach ein und ausparken!

Nicht Kaputt gehen / Nach reperatur wieder in takt.

https://youtu.be/9pWOIN96Tos

**Comment by r3sist3nt** [comment]
fixed in alt:V RC Branch

**Comment by JulianMa** [comment]
behoben durch alt:V
