### ISSUE TITLE
Trailer 200 portet sich weg

### ISSUE THREAD

**Issue by Cortain** [mexyn/statev_v2_issues#3460]
**Character Name**
Mike Fisher

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.06. / 04.06.24 ca 18:10

**Beobachtetes Verhalten**
Ich habe meinen Trailer 200 am Bison. Fahre zu Firma und gehe in die Firma. Komme ich aus der Firma, hat sich der Trailer dort hin geportet, wo er das letzte mal angekoppelt wurde. Also heute hat er sich 2x zur Mine geportet vom Standort 6001 wo sich die Firmen befinden.

**Erwartetes Verhalten**
Der Trailer sollte am Auto bleiben

**Schritte um den Fehler nachvollziehen zu können**
Tritt bisher nur auf, wenn der Trailer an meinem Bison ist, er vor der Firma steht und ich in der Firma bin.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
Full HD

**Comment by Cortain** [comment]
Es ist jetzt 2 mal vorgekommen, dass wenn ich zum Anhänger fahre, dass er kurz davor an mein fahrendes Fahrzeug geportet wird. Deswegen hab ich mich gerade mega überschlagen, leider hab ich keine Aufnahme davon.

Als Info vielleicht noch wichtig, der Anhänger stand eventuell immer auf dem Verladepunkt wenn er sich weg geportet hat.

**Comment by SatyriaDine** [comment]
Denke das ist das gleiche Problem wie das hier: #3445

**Comment by TheOutburst** [comment]
Das Problem sollte sich mit dem letzen Update gebessert haben, ist es seit dem 10.06 nochmal aufgetreten?
