### ISSUE TITLE
Tablet lässt sich mit Tab halb einblenden

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3461]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

04.06.2024 23:50
**Beobachtetes Verhalten**

Wenn man im Tablet auf dem Browser Tab ist und im Kleiderschrank "Tab" drückt wird das Tablet halb eingeblendet und kann teilweise genutzt werden
**Erwartetes Verhalten**

Es taucht nicht auf
**Schritte um den Fehler nachvollziehen zu können**

1. Browser Tab im Tablet auswählen
2. Tablet schließen
3. Kleiderschrank öffnen
4. Tabulator mehrfach betätigen
5. Wundern, woher da Tablet kommt
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

2560x1440
**Optional: Video / Bilder des Fehlers**

https://medal.tv/games/gta-v/clips/i0gqlOQdMEiF3Tg3d/d1337F1uCUDA?invite=cr-MSxjRmYsMTk1NTEzMTMzLA

**Comment by Hutstaender** [comment]
fixed, Tab Taste ist jetzt generell in unseren UI's unterbunden, wenn jemand ein Tablet hat.

Braucht man die Tab Taste irgendwo?

**Comment by SHaagmann** [comment]
@Hutstaender Nutze die nur wenn ich mich bei Social anmelde um da die Zeile zu wechseln. Oder halt generell an stellen mit mehreren eingaben untereinander

**Comment by simplycach** [comment]
Nächste Update fixed
