### ISSUE TITLE
Meist nach Neustart 

### ISSUE THREAD

**Issue by Asterix526** [mexyn/statev_v2_issues#3462]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Christian Big und Fria Larsen 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.06.2024  ist der Fehler beobachtet worden --> Ja

**Beobachtetes Verhalten**
Mich und meine Mitarbeiterin nicht mehr sichtbar und umgedreht auch nicht sehbar und Hörbar  

**Erwartetes Verhalten**
<Sichtbar und Hörbar sein  

**Schritte um den Fehler nachvollziehen zu können**
Streamer  der ein Viedeo Beweis von einen anderen Fall hat 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Stream bei Minute 3h15 min. https://m.twitch.tv/videos/2163250470

**Comment by Asterix526** [comment]
> ## WICHTIGE INFORMATION!!:
> ```
> Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
> ```
> 
> **Character Name**
> 
> Christian Big und Fria Larsen
> 
> **Auftrittszeitpunkt (Datum / Uhrzeit)**
> 04.06.2024 
> Ja
> **Beobachtetes Verhalten**
> Nicht Sichtbar und Hörbar 
> **Erwartetes Verhalten**
>
> **Schritte um den Fehler nachvollziehen zu können**
> Viedeo
> **Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
> 
> **Optional: Video / Bilder des Fehlers**

**Comment by Erumeldor** [comment]
@Asterix526 
In den angegebenen Vod hab ich keine Ahnung welche Stelle du meinst. 3h15 ist es aber nicht oder?

**Comment by Asterix526** [comment]
Doch ab  3:15 min muss man sich anschauen oder sogar ab 3h 10 min es kommt irgendwann nach 3h 15 min. Von meinem Telefon gesendet-------- Ursprüngliche Nachricht --------Von: Erumeldor ***@***.***>Datum: Fr., 7. Juni 2024, 08:23An: eiksch/statev_v3_issues ***@***.***>Cc: Asterix526 ***@***.***>, Mention ***@***.***>Betreff: Re: [eiksch/statev_v3_issues] Meist nach Neustart  (Issue #3462)
@Asterix526
In den angegebenen Vod hab ich keine Ahnung welche Stelle du meinst. 3h15 ist es aber nicht oder?

**Comment by Asterix526** [comment]
Und nein es passiert nicht nur in Gebäuden sondern auch draußen Von meinem Telefon gesendet-------- Ursprüngliche Nachricht --------Von: Erumeldor ***@***.***>Datum: Fr., 7. Juni 2024, 08:23An: eiksch/statev_v3_issues ***@***.***>Cc: Asterix526 ***@***.***>, Mention ***@***.***>Betreff: Re: [eiksch/statev_v3_issues] Meist nach Neustart  (Issue #3462)
@Asterix526
In den angegebenen Vod hab ich keine Ahnung welche Stelle du meinst. 3h15 ist es aber nicht oder?

**Comment by Stiefel911** [comment]
Das ganze ist irgend ein Frauenchar Ding....für draussen verlasse ich schon 2 mal das Apartment, dann sieht man auch alle stehen..
Drinnen wäre ja somit die selbige Notlösung

**Comment by SgtBoaz-Terry** [comment]
Konnte nicht reproduziert werden.

**Comment by Asterix526** [comment]
Naja ich sehe es immer wieder bei anderen aber oky 😉Von meinem Telefon gesendet-------- Ursprüngliche Nachricht --------Von: SgtBoaz-Terry ***@***.***>Datum: Do., 20. Juni 2024, 20:26An: eiksch/statev_v3_issues ***@***.***>Cc: Asterix526 ***@***.***>, Mention ***@***.***>Betreff: Re: [eiksch/statev_v3_issues] Meist nach Neustart  (Issue #3462)
Konnte nicht reproduziert werden.
