### ISSUE TITLE
Zugmaschine + Achse porten sich weg

### ISSUE THREAD

**Issue by Boing2000** [mexyn/statev_v2_issues#3463]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Bosco Albert

Bosco Albert
**Auftrittszeitpunkt (Datum / Uhrzeit)**

06.06.2024 ca 22.30
**Beobachtetes Verhalten**
Nach dem Betreten einer Firma portet sich die Zugmaschine + Achse weg.
Was mir dabei aufgefallen ist, dass die Achse plus Zugmaschine sich dort hin portet, wo ich sie zuletzt von einander abgekoppelt wurden.
Bei mir an MirrowPark Tanke abgekoppelt zum tanken. Nach dem betreten der Firma in Paleto steht die Achse wenn man wieder rauskommt wieder an der Tanke.

**Erwartetes Verhalten**
Zugmaschine bleibt vor der Firma
**Schritte um den Fehler nachvollziehen zu können**

**Comment by Snipser92** [comment]
Habe das Problem ebenfalls, aber nur wenn die Achse an der Zugmaschine angekoppelt ist und man dann ein Gebäude betritt.
Wenn das Gespann abgekoppelt ist passiert nichts.

**Comment by SgtBoaz-Terry** [comment]
Hi. @Boing2000 und @Snipser92 könnt ihr mir sagen, was für LKW und Trailer ihr hattet?

**Comment by Snipser92** [comment]
Ich besitze einen Barracks + Cargotrailer, ich weiß aber auch das es mit einem Packer + Tankerachse passiert.

**Comment by SgtBoaz-Terry** [comment]
Gut. Danke für die Information. Also liegt es schonmal nicht an einem bestimmten Typ. Wir schauen dann mal. :)

**Comment by DonJohn1993** [comment]
Das passiert, wenn du die range verlässt oder halt in eine Firma gehst und der trailer nicht abgekoppelt ist. Ebenso beim reconnect/disconnect natürlich. 
Danach steht er da, wo er das letzte Mal abgekoppelt wurde und klinkt sich wieder dran, wenn du in range bist.

https://streamable.com/8jnvbu

https://streamable.com/0t50nd

**Comment by Boing2000** [comment]
Bei mir war es Phantom + Cargo Trailer

**Comment by CCastles22** [comment]
Bei mir wars mit Hauler + Box Trailer

**Comment by CCastles22** [comment]
> Das passiert, wenn du die range verlässt oder halt in eine Firma gehst und der trailer nicht abgekoppelt ist. Ebenso beim reconnect/disconnect natürlich. Danach steht er da, wo er das letzte Mal abgekoppelt wurde und klinkt sich wieder dran, wenn du in range bist.
> 
> https://streamable.com/8jnvbu
> 
> https://streamable.com/0t50nd

Hatte ich auch genauso, bin in die Streamingrange gekommen und Trailer dockt wie aus dem nichts an!
Bei mir wars mit Hauler + Box Trailer

**Comment by SgtBoaz-Terry** [comment]
Sollte mittlerweile gefixt sein. Wenn es nochmal auftritt, dann neues Issue.
