### ISSUE TITLE
Collage Jacket, offen verschwindet wenn man versucht sie zu schließen

### ISSUE THREAD

**Issue by thumbsucker** [mexyn/statev_v2_issues#3464]
Billie_Weston

**Auftrittszeitpunkt (Datum / Uhrzeit)**
09.06.2024 ca. 0:20 Uhr

**Beobachtetes Verhalten**
Beim Versuch im Kleidungs-Menu die Jacke von "offen" auf "geschlossen" zu switchen, ist die Jacke verschwunden. Der Char hatte sie nicht mehr an und sie war auch nicht mehr im Inventar zu finden. 

Aufgetreten ist das Problem bei "[F] Navyblue College Jacket, offen" - Ich gehe aber stark davon aus das es auch bei anderen Farben so sein wird. 

Beim Versuch die geschlossene Version zu kaufen und zu gucken, ob auch hier die Jacke verschwindet wenn man sie öffnet, ist der Kauf im Laden fehlgeschlagen. 

**Erwartetes Verhalten**
Die Jacke sollte nicht verschwinden 

**Schritte um den Fehler nachvollziehen zu können**
Besagte Jacke anziehen und versuchen sie übers Menu zu schließen - ggf. nur bei weiblichen Chars?

**Comment by TheOutburst** [comment]
Den Fehler mit dem Wechseln hab ich gefunden und der sollte nächstes Update nichtmehr auftreten (12 Monate alte Fehlconfig, lol)

Welchen Fehler hast du beim kauf bekomen? Der sollte damit nichts zu tun haben

**Comment by thumbsucker** [comment]
Hey,

freut mich zu lesen. 

Den Fehler beim Kauf hatte ich jetzt leider nicht notiert und hatte gehofft es hängt zusammen und ist dann nicht so wichtig. 

War aber nun nochmal im Laden und dieses Mal konnte ich normal kaufen. Sollte ich nochmal die Meldung beim Kauf bekommen, mach ich einen Screenshot. Sorry dafür.

**Comment by TheOutburst** [comment]
ok pörfect
dann mach ich hier zu, wenns du nochma den Fehler kriegst paste den einfach hier rein oder mach nen neuen Tracker auf
