### ISSUE TITLE
Achse anhängen

### ISSUE THREAD

**Issue by HDCuba** [mexyn/statev_v2_issues#3465]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Angelo_Peppers
**Auftrittszeitpunkt (Datum / Uhrzeit)**
<!schon länger, ein oft auftretender Fehler -->

**Beobachtetes Verhalten**

Beim Abstellen einer Achse, egal ob Trailer oder Log Achse, buggen die Abstellfüße sich in den Boden und der Trailer rutscht dann langsam vom LKW, wenn man dann nicht schnell genug ist und reagiert, oder nicht darauf achtet,  kann man folglich die Achse nichtmehr an den LKW ankoppeln 
**Erwartetes Verhalten**

Momentan ein aktuelles und bestehendes Problem an jeder stelle
**Schritte um den Fehler nachvollziehen zu können**

an diversen Orten versuchen die Achse abzuhängen, der Fehler ist nun bei mir sehr häufig aufgetreten in den letzten 2 Tagen wo ich wieder da bin
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![EiTEwjSRUD](https://github.com/eiksch/statev_v3_issues/assets/172267101/b10b806c-2d13-4081-9383-bdea5be5d76e)

**Comment by SgtBoaz-Terry** [comment]
Hey.
Hast du dazu zufällig ein Video oder eine genauere Beschreibung, was du machst? Kannst du gar nicht erst unter den Trailer drunter fahren oder nur mit etwas Kraftaufwand? Wie löst du das Problem, wenn es auftritt?

**Comment by HDCuba** [comment]
Grüüüße, aalso ich möchte den Trailer abhängen, halte H gedrückt, und anschließend fahren ja die beiden Abstellfüße raus und der koppelt sich ab und dabei stellt er sich nicht auf den Boden sondern in oder unter (also die Füße sacken ein wie bei schlammigen Boden), je nach Untergrund und Ebenheit kann es dann sehr schwer bis garnicht mehr funktionieren die Achse anzukoppeln.  Ich versuche erst in irgendeinen Winkel unter die Achse zu kommen, wenn dies überhaupt nicht möglich ist kann ich nur mit Hilfe des Supports die Achse wegporten lassen sonst. Ich kann ja nicht immer mit ach und krach in die Achse donnern, wenn das andere dann sehen oder mitbekommen keine Lust auf irgendwelche Erklärungen IC.

**Comment by SatyriaDine** [comment]
Mit was für einer Zugmaschine versuchst du den Trailer anzukoppeln?

**Comment by HDCuba** [comment]
MTL Packer, das Problem ist nu hauptsächlich bei der Log Achse, auch beim ausparken bei der Garage, buttern sich die stelzen immer in den Boden.

**Comment by simplycach** [comment]
Mal probiert den woanders einzuparken ?

**Comment by QA-Pregon** [comment]
soweit ich das sehe (getestet mit Packer und Achse an der Garage) ist das die Standartabstellhöhe dieser Achse
Mit dem Packer kommt es da auch beim abkoppeln an sich überall zu diesem Problem, aber mit ein klein bisschen Schwung kommt man da ja ohne Probleme drunter oder?

**Comment by simplycach** [comment]
Da bisher keine Antwort kam, schließen wir das erstmal.
