### ISSUE TITLE
Transfer Fahrzeug- und Hausinventar über Garagenpunkt

### ISSUE THREAD

**Issue by DonJohn1993** [mexyn/statev_v2_issues#3466]
Reggie_Jennings

10.06.2024 14:11

Transfer vom Fahrzeuginventar into Hausinventar nicht möglich, wenn der Kofferraum vom Fahrzeug zu ist.
Fehlermeldung: "Ungültiges Ziel oder Ursprung"

**Erwartetes Verhalten**
Wenn gewollt, sollte ein anderer Tooltip kommen a la "Kofferraum nicht geöffnet", ansonsten sollte es Spielern mit Zugriff möglich sein, mit geschlossenem Kofferraum Items umzulagern, wie es auch in Firmen aktuell ist.

**Schritte um den Fehler nachvollziehen zu können**
Auf den Garagenpunkt fahren, Kofferraum geschlossen lassen und "Inventar Transfer" am Haus auswählen. Dann versuchen Items rüberzuschieben

https://streamable.com/v3c8rh

**Comment by DrGrizzlY17** [comment]
Ich denke eher das es ein Bug ist, das man mit geschlossenem Kofferraumen an Firmen umlagern kann, als das hier ein Bug ist.

**Comment by stepz2k9** [comment]
> Ich denke eher das es ein Bug ist, das man mit geschlossenem Kofferraumen an Firmen umlagern kann, als das hier ein Bug ist.

Wurde doch zu Beginn von V3 extra möglich gemacht, weil an den öffentlichen Firmen dauernd die Kofferräume leer geräumt wurden, da man da ja reingehen musste und nicht gesehen hat, ob einer ans Auto geht.

**Comment by Statev-Bonsai** [comment]
ja, aber nur bei öffentlichen firmen ^^

@ here Ein kleiner Hinweis an unsere Kofferraumdiebe: Wer glaubt, einen Kofferraum oder sonstiges ohne RP-Hintergrund leerzuräumen, bekommt bei einer Meldung richtig Ärger! Das heißt, ich möchte keinen mehr sehen, der einen Kofferraum leer räumt, ohne dass darum wirklich RP gespielt wurde oder wird! Für die anderen als Erinnerung: Ihr könnt an den öffentlichen Fabriken mit geschlossenem Kofferraum die Items umlagern.

**Comment by TheOutburst** [comment]
Man muss hier differenzieren

Firmen
Öffentliche Firmen
Häuser

Bei öffentlichen Firmen wurde das umlagern bei geschlossenem Kofferraum ermöglicht, das heißt nicht, dass es bei Häusern nun auch möglich sein soll

Hier ist also alles richitg, kein Bug
