### ISSUE TITLE
Garage hinzufügen 

### ISSUE THREAD

**Issue by blooddog** [mexyn/statev_v2_issues#3467]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Carlo_Breit**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by QA-Pregon** [comment]
Wo möchtest du denn eine Garage hinzugefügt haben?
Eine Hausgarage oder eine öffentliche?
Falls Haus, dann einmal den Haushash bitte und wo am Haus.
Falls eine öffentliche, warum sollte da eine neue da hin und wo.

**Comment by blooddog** [comment]
hey @Pregon Eine Private Garage.
Der hash für das Haus wäre: house_Davis_9

**Comment by QA-Pregon** [comment]
Der Haushash ist im Tablet zu finden, wenn du auf dein Haus gehst und dann auf die Übersicht.
Alternativ vielleicht auch am Hauseingang aber da bin ich gerade net sicher

**Comment by blooddog** [comment]
> Der Haushash ist im Tablet zu finden, wenn du auf dein Haus gehst und dann auf die Übersicht. Alternativ vielleicht auch am Hauseingang aber da bin ich gerade net sicher

Danke, der Hash wäre: house_Davis_9.

LG

**Comment by QA-Pregon** [comment]
Alright, dann heißt es jetzt abwarten was das Gamedesign sagt ^^

**Comment by TheOutburst** [comment]
Hello
Das Haus hat weder eine Garage noch eine dem Haus zuordenbare Einfahrt, hier kann leider keine Garage hin
