### ISSUE TITLE
Abladepunkt ändern

### ISSUE THREAD

**Issue by Gamer99LL** [mexyn/statev_v2_issues#3469]
Character Name
Janis_Ryder

Firmenhash
Auftrittszeitpunkt (Datum / Uhrzeit)
Immerpetrolstation6

Beobachtetes Verhalten
Abladepunkt unpraktisch für große Fahrzeuge
![Tanke](https://github.com/eiksch/statev_v3_issues/assets/133898646/77f6c7c7-b76c-47d6-8c5f-6e09a59bdca8)

Erwartetes Verhalten
Praktischer Abladepunkt auf der Position von dem Char
![Tanke2](https://github.com/eiksch/statev_v3_issues/assets/133898646/85c0317c-cb3d-4368-b74e-cf5476d97f47)

Schritte um den Fehler nachvollziehen zu können
Fahrzeug entladen

**Comment by Gamer99LL** [comment]
Ehm kann es sein das das hier übersehn wurde ?

**Comment by Erumeldor** [comment]
Dein Ladepunkt ist im nächsten Update ein paar Meter verschoben :)
