### ISSUE TITLE
Fahrzeugbug nach Crash

### ISSUE THREAD

**Issue by Domeex3** [mexyn/statev_v2_issues#347]
Domenik_Sommer

Nach Gamecrash spawnt man am Fahrzeug, die Reifen fangen von alleine an durchzudrehen und Platzen irgend wann.
Beim Einsteigen RPM auf Max. und Tank auf 0.0l, Tank fixt sich selbst wieder auf alten wert.

https://youtu.be/sY2EA70XalM

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/201
