### ISSUE TITLE
TacLight von Waffen unsichtbar

### ISSUE THREAD

**Issue by quotenben** [mexyn/statev_v2_issues#3470]
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer, nach Connecten zum Server oder bei Ausrüsten von Waffe

**Beobachtetes Verhalten**

Das TacLight wird zwar im Inventar an der Waffe als attached angezeigt, optisch an der Waffe jedoch nicht und kann nicht verwendet werden. Dies passiert zum Connect, wenn die Waffe ausgerüstet war oder eine Waffe, an welche bereits ein TacLight attached ist, ausgerüstet wird.

**Erwartetes Verhalten**

Das TacLight sollte beim Serverconnect richtig erkannt werden. Wird eine Waffe mit attachtem TacLight ausgerüstet, sollte man dies nicht vorher abnehmen und wieder attachen müssen, damit man es benutzen kann.

**Schritte um den Fehler nachvollziehen zu können**

1. Waffe mit TacLight ausrüsten, disconnecten und wieder connecten
2. Waffe mit TacLight ausrüsten, abrüsten, wieder ausrüsten

**Comment by QA-Pregon** [comment]
Next update
