### ISSUE TITLE
Char ändert sich durch Maskierung

### ISSUE THREAD

**Issue by Hochfels** [mexyn/statev_v2_issues#3471]
**Character Name**: Nevis_Yoki

**Auftrittszeitpunkt (Datum / Uhrzeit)**: Immer, wenn ich eine Maske anziehe

**Beobachtetes Verhalten**: Sobald ich eine Maske aufziehe, ändert sich mein Char. Die Hautfarbe ändert sich, die sichtbaren Gesichtszüge auch ein wenig. Aber vor allem von Weiß auf braun bis hell schwarz ist sehr auffällig.

**Erwartetes Verhalten**: Dass mein Char sich nicht verändert durch eine Maskierung :)

**Schritte um den Fehler nachvollziehen zu können**: Meinen Char kopieren und eine Maske aufziehen. Kann hier auch gerne meine XML zur verfügung stellen.

**Optional: Video / Bilder des Fehlers**
ohne Maske: [https://prnt.sc/3bpAIfTty3_I](url)
mit Maske: [https://prnt.sc/QhC1HsJsJJIy](url)

**Comment by QA-Pregon** [comment]
Lad die Bilder bitte nochmal hoch, Link sie neu, o.ä.
Bei mir komm ich mit den Links auf irgendeinen leeren GitHub Ordner ^^

**Comment by Hochfels** [comment]
![mit maske](https://github.com/eiksch/statev_v3_issues/assets/88154450/1e256815-99b0-41b0-a520-9e45866e7b4b)
![normal](https://github.com/eiksch/statev_v3_issues/assets/88154450/bccb774b-1027-4424-b973-8a272242f07c)

**Comment by Enemyaa** [comment]
@Hochfels Das soll so sein. Dahinter steckt eine Ped Config, die das Gesicht anpasst, so dass die Masken keine Löcher haben.

**Comment by Enemyaa** [comment]
@Hochfels Das soll so sein. Dahinter steckt eine Ped Config, die das Gesicht anpasst, so dass die Masken keine Löcher haben.
