### ISSUE TITLE
Keine Interaktion mit Parkwächter nach Tabletnutzung möglich

### ISSUE THREAD

**Issue by ShinzuJackson** [mexyn/statev_v2_issues#3473]
**Character Name**
Shinzu_Jackson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11.06.2024 um 12:10, nach dem heutigen Update

**Beobachtetes Verhalten**
Nachdem ich mein Tablet benutzt habe, war eine Interaktion mit der Garage über die Taste E nicht mehr möglich. Erst nach Relog konnte dies behoben werden.

**Erwartetes Verhalten**
Auch nach der Nutzung des Tablets weiterhin die Möglichkeit der Interaktion über die Taste E

**Schritte um den Fehler nachvollziehen zu können**
Zu einer Garage gehen
Tablet rausholen etwas darin rumspielen
Tablet wegpacken
Versuchen mit dem Parkwächter über E zu interagieren

**Optional: Video / Bilder des Fehlers**
https://youtu.be/GLghy-GG0MM

**Comment by DrGrizzlY17** [comment]
> **Character Name** Shinzu_Jackson
> 
> **Auftrittszeitpunkt (Datum / Uhrzeit)** 11.06.2024 um 12:10, nach dem heutigen Update
> 
> **Beobachtetes Verhalten** Nachdem ich mein Tablet benutzt habe, war eine Interaktion mit der Garage über die Taste E nicht mehr möglich. Erst nach Relog konnte dies behoben werden.
> 
> **Erwartetes Verhalten** Auch nach der Nutzung des Tablets weiterhin die Möglichkeit der Interaktion über die Taste E
> 
> **Schritte um den Fehler nachvollziehen zu können** Zu einer Garage gehen Tablet rausholen etwas darin rumspielen Tablet wegpacken Versuchen mit dem Parkwächter über E zu interagieren
> 
> **Optional: Video / Bilder des Fehlers** https://youtu.be/GLghy-GG0MM

Hi du hast sicherlich den Transparenz Regler genutzt. Nachdem du den genutzt hast, musst du nochmal im Tablet irgendwo hin klicken, bevor du die ganze zeit relogst :D

**Comment by ShinzuJackson** [comment]
Das könnte eine möglichkeit sein. Werde es testen.
