### ISSUE TITLE
After Hour Tisch lässt sich nicht placen

### ISSUE THREAD

**Issue by TriixV1** [mexyn/statev_v2_issues#3474]
**Jackson Tyler**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 09.06.2024 um 13:40 Uhr 

**Beobachtetes Verhalten**
 Wenn man den After Hour Tisch mit rechtsklick placen möchte verschwindet dieser einfach aus dem Inventar ohne da sman ihn placen kann. Um ihn wieder zu bekommen muss ein anders Objekt was man selber platziert hat abbauen. 

**Erwartetes Verhalten**
Es soll möglich sein den Tisch platzieren zu können. 

**Schritte um den Fehler nachvollziehen zu können**
Item ins Inventar setzen und versuchen zu platzieren.

**Comment by simplycach** [comment]
Wo möchtest du den aufstellen zufällig im County ?

**Comment by TriixV1** [comment]
Fudge Lane 9 

auf dem Dach der Garage East Side

**Comment by TheOutburst** [comment]
Ach keine Ahnung das Ding ist komisch
Ich nehm die Produktion dafür raus, nehm einfach nen anderen Tisch
