### ISSUE TITLE
Stantastic Frisur

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3475]
Wird bei Dämmerung und Dunkelheit durchsichtig...

![stantastic](https://github.com/eiksch/statev_v3_issues/assets/70241137/08d6cab1-1a0d-42d3-8358-82a5b0a13889)

**Comment by stepz2k9** [comment]
Das liegt an der Mod, da kann State nicht viel machen.
Ist leider auch in Menyoo/SP so.

**Comment by Statev-Bonsai** [comment]
dooooooooooooof

**Comment by simplycach** [comment]
Richtig da können wir nicht viel machen.
