### ISSUE TITLE
Relog nach respawn führ zur "Todeslocation"

### ISSUE THREAD

**Issue by Lysiahx3** [mexyn/statev_v2_issues#3476]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Haley Turner

Haley Turner

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Sonntag 09.06.24 um ca. 23-1 Uhr 

**Beobachtetes Verhalten**
Nach einer Schießerei war mein Char bewusstlos in einem Interior und wurde vom Notfallteam abgeholt (North Rockford drive). Da ich als Cop ja den Funk an habe und man nach dem Respawn keine Sachen mehr am Mann hat konnte ich dennoch das Funkgerät hören. Ich entschied mich dazu einen kurzen Relog zu machen, jedoch wurde ich beim wieder einloggen in das Interior des Hauses zurückgeportet in dem ich starb.

**Erwartetes Verhalten**
Ich sollte nach dem Relog natürlich wieder am Mount Zonah stehen, wo ich mich auch ausgeloggt habe.

**Schritte um den Fehler nachvollziehen zu können**
Ich denke wenn man in einem Interior stirb und Respawnt an einem KH, sich dann ausloggt, das so der Fehle reproduziert werden könnte.

**Comment by simplycach** [comment]
Ein Video hast du zufällig nicht oder ?

**Comment by Lysiahx3** [comment]
Nein leider nicht :/ Hatte unglücklicherweise meinen Browser im Hintergrund offen und da ist halt immer nen Tab mit prime video oder so und dann geht nvidia clip nicht >,<

**Comment by simplycach** [comment]
Da wir das bisher nicht reproduzieren konnten, würde ich das erstmal schließen, maybe hast du ja beim nächsten mal ein Video :)
