### ISSUE TITLE
Skillberreich Dieb

### ISSUE THREAD

**Issue by StateV-Jan** [mexyn/statev_v2_issues#3478]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Name des Charakters
Liam Taylor

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Dauerhaft

**Beobachtetes Verhalten**
Mir kommt es sovor als ob Lucas also Schrottplatz den Skill Dieb nicht hochtreibt...(meines letzter Stand war das Lucas zum Dieb zählt) 
Habe die Tage viel Lucas gemacht und bin kaum weiter gekommen bin grade bei 2%. Als ich 5 mal 24/7 gemacht habe, ging der Balken ca 2cm weiter.
**Erwartetes Verhalten**
Skill sollte hochgehen 

**Schritte um den Fehler nachvollziehen zu können**
Mehrer Lucas Missionen machen und Skill Dieb beobachten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by QA-Pregon** [comment]
Fortschritt ist auf jeden Fall da, ich frag mal nach ob der geringe Fortschritt da aber so geplant ist, aber ich denk mal das ist alles passend

**Comment by StateV-Jan** [comment]
Wie gesagt Mystique 5 Läden 2cm und bei Lucas ca 20 Schrottplätze und kein merklichen Fortschritt

**Comment by simplycach** [comment]
Also bei uns geht alles Einwandfrei wenn der Fehler nochmal kommt bitte erneut öfffnen.
