### ISSUE TITLE
Männeroberteile Buggy

### ISSUE THREAD

**Issue by EmilyLodge** [mexyn/statev_v2_issues#3479]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Bitte die Vorlage unten vollständig ausfüllen**
Emily_Hunter

**Mit welchem Character wurde das Verhalten in-game ausgelöst/beobachtet**
Danny_Hunter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.6.24 // ca. 23 Uhr

**Beobachtetes Verhalten**
Beim Kauf des Oberteils wurde versucht diesen auf den Char anzupassen. Leider passt kein langarm, Kurzarm, Ärmellos oder Pberkörperfrei. (Beim Bild wurde Kurzarm 1 verwendet)
Oberteil Name: [M] Grauer Sweater & Snob Shirt 

**Erwartetes Verhalten**
Das Oberteil wird ohne durchgebugten Körper angezeigt. Irgendeine Einstellung auf Kurzarm wäre hier passend.

**Schritte um den Fehler nachvollziehen zu können**
Oberteil anziehen und alle anziehoptionen ausprobieren. Hilft nichts.

**Optional: Video / Bilder des Fehlers**
Bild 1. https://pic.statev.de/image/HyZ5Qs
Bild 2. https://pic.statev.de/i/HyZL3t.png

**Comment by SHaagmann** [comment]
Probier mal Kurzarm 4. Gibt es nur ohne Handschuhe @EmilyLodge

**Comment by EmilyLodge** [comment]
Hat er wohl versucht. Jegliche Einstellungen die es gibt, nichts soll funktionieren

**Comment by EmilyLodge** [comment]
Nachtrag, wurde ernuet getestet. Leider durchgefallen:
Bild 1: https://pic.statev.de/i/HlHRWI.png
Bild 2: https://pic.statev.de/i/HlHhjq.png

**Comment by ySimbaa** [comment]
Sollte nach dem letzten Update nach meinen Infos fixed sein. @EmilyLodge
