### ISSUE TITLE
Unterbodenlicht nach Ausparken immer AN

### ISSUE THREAD

**Issue by Domeex3** [mexyn/statev_v2_issues#348]
Domenik_Sommer

Nach dem Ausparken ist bei meinem Fahrzeug automatisch das Neonlicht an, auch wenn vorher aus.
Beim versuch es auszuschalten kommt die Meldung es wurde "Angeschaltet" 

https://youtu.be/rqMYNXHxgK0

Passiert immer und immer wieder.

**Comment by DonVitoDiangelo** [comment]
wird nicht gespeichert. Einfach ausschalten ;)
