### ISSUE TITLE
Pacific Bluffs DJ Pult + Barhocker

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3482]
Moin
Ich wollte mal anfragen, ob man dem DJ Pult am Pacific Bluffs auch einen Verstärkerpunkt geben kann, damit das DJ system auch dort ohne Probleme genutzt werden kann.

Zudem wollte ich nachfragen ob man den Barhockern die Interaktion mit "y" hinzufügen könnte damit man sich auch auf diese setzten kann

Grüße 
Sven aka. Andrew Jared

**Comment by TheOutburst** [comment]
Moin
Die Barhocker kriegen wir hin
Der DJ Punkt ist leider nen Club Only Feature, dh den kriegen wir da nicht hin, sorry
