### ISSUE TITLE
Tablet geht bei TAb im F7 Menu auf

### ISSUE THREAD

**Issue by MarvinMuecke** [mexyn/statev_v2_issues#3483]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Marvin_Muecke**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
Im F7 Menü Tab gedrückt und dann das Tablet gehabt ohne dieses wieder Schließen zu können

**Erwartetes Verhalten**
Tablet im Bild

**Schritte um den Fehler nachvollziehen zu können**
Im F7 Menü auf TAb gedrückt um diesen als hotkey zu belegen 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://i.gyazo.com/96beb86da81c797cf5f4c6aed06dac07.png

**Comment by SHaagmann** [comment]
Würd gleiches ding wie in #3461

**Comment by simplycach** [comment]
Close wegen Doppel-Post
