### ISSUE TITLE
Schmuckstücke nicht kominierbar

### ISSUE THREAD

**Issue by EmilyLodge** [mexyn/statev_v2_issues#3484]
## WICHTIGE INFORMATION!!:

Emily_Hunter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Schon zu V2 aufgefallen, jedoch hieße es, dass die Sachen den selben Slot belegen und deshalb nicht gleichzeitig getragen werden können, was ja nicht der Fall ist.

**Beobachtetes Verhalten**
Man kann nur 1 Schmuckstück tragen bzw. wird nur 1 angezeigt, obwohl man beide angezogen hat und 2 unterschiedliche Slots belegt. Am Char wird entweder die Kette oder die Ohrringe angezeigt. Ist jedoch nach meinen beobachtungen her bei den Creolen der Fall, dass der Fehler auftritt.

**Erwartetes Verhalten**
Sowohl Kette als auch Ohrringe werden korregt angezeigt (angezogen) und nicht nur 1 Schmuckstück.

**Schritte um den Fehler nachvollziehen zu können**
Sowohl Creolen als auch eine beliebige Kette anziehen

Bild 1: https://pic.statev.de/i/HlHvcc.png
Bild 2: https://pic.statev.de/i/HlHFhB.png

**Comment by QA-Pregon** [comment]
#3350

**Comment by stepz2k9** [comment]
@EmilyLodge doch, die liegen schon von GTA aus auf dem selben Slot. Blöd und nicht nachvollziehbar. Aber ist wirklich so. Kann ich dir bei Interesse gerne mal bei menyoo zeigen.
