### ISSUE TITLE
Männeroberteil INKLUSIVE Fingernägel

### ISSUE THREAD

**Issue by EmilyLodge** [mexyn/statev_v2_issues#3485]
## WICHTIGE INFORMATION!!:

Emily_Hunter

Danny_Hunter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.6.2024 // ca. 00:40

**Beobachtetes Verhalten**
Beim anziehen des Männeroberteils ist aufgefallen, dass die Fingernägel ein Update bekommen :D im gegensatz zu anderen Oberteilen.
Oberteil: [M] Bordeaux Macho Shirt

**Erwartetes Verhalten**
Die Fingernägel verändern nicht ihr aussehen

**Schritte um den Fehler nachvollziehen zu können**
Oberteil anziehen & auf die Hände schauen

**Optional: Video / Bilder des Fehlers**
Bild 1 (Oberteil mit falschen Fingernägeln): https://pic.statev.de/i/HlHbWA.png
Bild 2 (Fingernägel normal): https://pic.statev.de/i/HlHAmy.png
Bild 3 (Oberteil) : https://pic.statev.de/i/HlHGqu.png

**Comment by stepz2k9** [comment]
Das liegt an der Mod an sich. Die kommt eigentlich mit eigenem Torso, weil es keinen Vanilla Torso gibt, der passt. Da der hier fehlt, werden die Fingernägel in der Farbe des Hemdes gezeigt. 

Es müsst der Torso mit eingefügt und bei Anziehen des Hemds automatisch ausgewählt werden. Bei V2 ging das, da hatte jemand den passenden Torso mit eingefügt. 

Gleiches Problem haben wir bei vielen Frauenhosen. Die haben keine Fußknöchel. Eigentlich müssten die als Unterteil eingefügt werden und die Knöchel als Beine (mal am Rand erwähnt. Ich habe ein passendes paar Knöchel, kann sich gerne bei mir gemeldet werden 🫣)

**Comment by ySimbaa** [comment]
Ja wird an den Oberteil an sich liegen. Ich würde es einfach nicht anspielen. 

Zu dem Thema mit den Knöcheln @CaleighRhodes kannst du mir gerne mal eine DM schicken und ich kläre das dann ab in wieweit wir custom lowr einfügen können.
