### ISSUE TITLE
Fehlermeldung bei Tetris

### ISSUE THREAD

**Issue by Quarkbaelchen** [mexyn/statev_v2_issues#3486]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Mina Cruz

**Auftrittszeitpunkt (Datum / Uhrzeit)**

16.06.2024 um 13:34
**Beobachtetes Verhalten**

habe aus dem nichts beim Tetris eine Fehlermeldung bekommen

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/171297959/86677391-5bbb-44b3-a60e-4e54573de58c)

**Comment by Erumeldor** [comment]
Wir machen hier mal zu - neues Handy daher neues Tetris. Wenns nochmal auftritt bitte nochmal melden.
