### ISSUE TITLE
Handy Notruf Bug

### ISSUE THREAD

**Issue by JensGamerBoy** [mexyn/statev_v2_issues#3487]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Jens Steingarten**

**Auftrittszeitpunkt (16.06.2024 / 22:20 uhr ca)**

Wenn man notruf schickt und die den Dispatch dann zumachen hält man das telefon wieder am ohr als wenn man telefonieren würde

sobald der Dispatch geschlossen ist sollte man nicht mehr die Animation ausführen das man am telefonieren ist

1. Notruf rufen egal ob Medic oder PD
2. Warten bis der Einsatz beendet ist und der Dispatch geschlossen wird
3. Sobald die meldung kommt der dispatch wurde geschlossen telefoniert man angeblich wieder obwohl man nicht telefoniert

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

Fehlercode der in f8 console drinne stand:

[WEB, View 00000000E70A8FA0] http://resource/client/ui/index.js:2344:Warning: Internal React error: Expected static flag was missing. Please notify the React team.%s 
    at DispatchApp (http://resource/client/ui/index.js:1167881:5)
    at div
    at div
    at div
    at PhoneComponent (http://resource/client/ui/index.js:1168771:66)
    at ErrorBoundary (http://resource/client/ui/index.js:1426185:7)
    at RecoilRoot_INTERNAL (http://resource/client/ui/index.js:102893:5)
    at RecoilRoot (http://resource/client/ui/index.js:103010:7)
    at div
    at App (http://resource/client/ui/index.js:1426258:20)

**Comment by simplycach** [comment]
Hast du nachdem du den Notruf gewählt hast und das PD oder MD aufgelegt hat auf Ok geklickt, dann sollte er das Telefon weglegen.

**Comment by JensGamerBoy** [comment]
das ding ist ja Ab und zu wird mir nichtmal ein OK angezeigt das ist schon komisch, aber auch wenn ich das OK sehe und drauf drücke kommt meistens der fehler

**Comment by Cortain** [comment]
Kann ich bestätigen. Die Notruf App ist dann defekt, sobald der Dispatch geschlossen wird. Der Char hält dann dauerhaft das Handy am Ohr.

**Comment by simplycach** [comment]
Nächstes Update fixed
