### ISSUE TITLE
Handy klingeln geteilte SIM-Karte Firmentelefon

### ISSUE THREAD

**Issue by RatzFatz1312** [mexyn/statev_v2_issues#3488]
**Character Name**

Alex_Jansen

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 immer wenn Firmentelefon klingelt und Kollege rangeht

**Beobachtetes Verhalten**

Wir besitzen von der Firma die gleiche SIM
Karte, wenn wir angerufen werden und einer geht ran, klingelt es bei dem anderen trotzdem weiter. 

**Erwartetes Verhalten**

Sobald einer den Anruf entgegennimmt, sollte das klingeln aufhören

**Schritte um den Fehler nachvollziehen zu können**

Zwei oder Mehrere Personen besitzen die SIM, werden angerufen und es klingelt trotzdem weiter obwohl jemand den anruf abgenommen hat.

**Comment by simplycach** [comment]
Gibt es bereits einen Bugtracker zu am besten immer eine andere SIM-Karte drin haben und dann switchen
