### ISSUE TITLE
Fußball Dupe

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#3489]
**Character Name**
Charly Russo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.06.2024 23:50 Uhr

**Beobachtetes Verhalten**
Beim Aufheben des Fußballs wurde er geduped

**Erwartetes Verhalten**
Wird ohne Dupe aufgehoben

**Schritte um den Fehler nachvollziehen zu können**
Einer tritt den Fußball während er aufgehoben wird, dann hat man einen Fußball im Inventar und kann den zweiten auch aufheben, weil er noch in der Welt existiert

**Comment by simplycach** [comment]
Ist bereits bekannt, siehe Ankündigung. Wird mit dem nächsten Update behoben.
