### ISSUE TITLE
Dauerauftrag hat nicht überweisen

### ISSUE THREAD

**Issue by Lether1983** [mexyn/statev_v2_issues#3490]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Hubertus Feger

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.06.2024

**Beobachtetes Verhalten**
Dauerauftrag hat an dem Tag nicht überweisen und in der Info zum Dauerauftrag steht Datum von Gestern drin!

**Erwartetes Verhalten**
Dauerauftrag überweist zu seine Bestimmten Zeit ob ich IC bin oder Nicht

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![Screenshot 2024-06-17 064615 Heutige Datum](https://github.com/eiksch/statev_v3_issues/assets/10713022/0cf10033-9999-48b4-9af2-f30945e82424)
![Screenshot 2024-06-17 064541 Dauerauftrag](https://github.com/eiksch/statev_v3_issues/assets/10713022/35bb134d-f9d4-48d2-a3c5-ddee4695abf7)

**Comment by simplycach** [comment]
Ist dir das nochmal passiert ?

**Comment by Lether1983** [comment]
Also ich habe da nun erst mal nix gemacht weil ich nicht sicher war ob ihr das Braucht zum Nachverfolgen! Meint ihr ich soll den  Löschen und dann noch mal neu machen?

**Comment by simplycach** [comment]
Wäre ein Versuch Wert

**Comment by Lether1983** [comment]
Ich habe einen Neuen Erstellt ich schaue mal ob das nun funktioniert

**Comment by simplycach** [comment]
Gehe mal von aus es geht
