### ISSUE TITLE
Türen 1804 Block

### ISSUE THREAD

**Issue by 2FaceOriginal** [mexyn/statev_v2_issues#3491]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Dre_Cones**

2Face
**Auftrittszeitpunkt (Datum / Uhrzeit)**

17.06.- 13:20
**Beobachtetes Verhalten**

Nachdem ich ein Ticket eröffnet habe, in dem ich drum gebeten habe die Gittertüren, sowie den Müll, im 1804 Block in den Projects zu entfernen, wurde ich auf den Bugtracker verwiesen. Heute sehe ich ic, dass die Gittertüren, jedoch nicht die Gitter entfernt worden sind. 
**Erwartetes Verhalten**

Die Gitter mit entfernen
**Schritte um den Fehler nachvollziehen zu können**

Ic auf die Türen schauen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

1. Öffne Altv.
2. Connecte auf den Statev Gameserver.
3. Begebe dich in die Projects.
4. Richte deinen Blick auf den 1804 Block
**Optional: Video / Bilder des Fehlers**

https://prnt.sc/ShhklwHw543w (Türen auf der Süd-Westlichen Seite des Blocks)
https://prnt.sc/Ou4vUX8IUKPt (Türen auf der Süd-Östlichen Seite des Blocks)

**Comment by TheOutburst** [comment]
Jau, das war mein Versuch die weg zu machen, aber die Gitter sind leider Teil des Gebäudes, dh ohne das gesamte Objekt anzufassen wird das nicht, und solche Mappings machen wir an nicht öffentlichen Orten leider nicht, sorry

Ihr seid aber gerne eingeladen als eingetragene Fraktion per Ticket ein Mapping einzureichen / die Vorraussetzungen dafür zu erfragen
