### ISSUE TITLE
Werkstatt Bug ist wieder da .. 

### ISSUE THREAD

**Issue by Gingerxoxo** [mexyn/statev_v2_issues#3492]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Palina_Pavlova

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.06.2004 - 19.30 Uhr US Customs

**Beobachtetes Verhalten**
Ich wollte mein Auto reparieren lassen und dann ist das Auto explodiert

**Erwartetes Verhalten**
Auto soll bitte nicht explodieren

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://medal.tv/games/gta-v/clips/i5xigkaagOc6m66Cg/d1337oDiyPgR?invite=cr-MSxadHgsMTc3NjY5ODc3LA

**Comment by DrGrizzlY17** [comment]
Hattet ihr damage am reifen? Also platten oder so?

**Comment by Gingerxoxo** [comment]
Jaaa da war n Loch im Reifen durch n Schuss vorher den ich reparieren lassen wollte

**Comment by simplycach** [comment]
Ist der Bug nochmal erneut aufgetreten ?

**Comment by simplycach** [comment]
Da ich bisher keine Nachricht erhalten habe gehe ich von aus, dass es nicht nochmal aufgetreten ist.
