### ISSUE TITLE
Entfernen Abgedecktes Auto

### ISSUE THREAD

**Issue by BobbyCarsten** [mexyn/statev_v2_issues#3493]
Wäre es möglich bei dem Haus mit dem Hash: 
house_Davis_31 Adresse: Grove Street 28
das abgedeckte Fahrzeug vor der Tür zu entfernen ? 

Charaktername: Bobic Madujew

![Haus](https://github.com/eiksch/statev_v3_issues/assets/163411566/6907c76f-452f-4bad-9f6b-a1e912138d81)

**Comment by TheOutburst** [comment]
nee, das ist leider nicht möglich, sorry
