### ISSUE TITLE
schwarzen bildschirm nach Wolken sequenz

### ISSUE THREAD

**Issue by Ghettomajor** [mexyn/statev_v2_issues#3494]
IC name ist Kevin Hartmann 
Ich hab nach einem Spielabsturz immer wieder einen blackscreen wenn ich ins spiel komme 

Uhrzeit war ca 20:30-20:45 seiddem komme ich nichtmehr rein ich habe quasi die sequenz wo man aus den wolken nach unten kommt und dann wenn ich eigentlich spawnen sollte habe ich blackscreen und kann garnichts mehr machen nichtmal das spiel lässt sich schließen ich muss jedesmal meinen pc neu starten um wieder gta neu zu starten.

**Comment by simplycach** [comment]
Am besten mal den Altv cache löschen.

**Comment by simplycach** [comment]
Wie kann ich meinen "AltV Cache" löschen ?
In vielen Problem-Fällen kann es bereits helfen den "AltV Cache" zu löschen.

Wie finde ich meinen AltV Ordner: 
Rechtklick auf deine altv - Verknüpfung
Eigenschaften
Dateipfad öffnen
