### ISSUE TITLE
Truckerjob kann nicht gemacht werden

### ISSUE THREAD

**Issue by timblair33** [mexyn/statev_v2_issues#3496]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Charaktername**
 Tim Blair

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 19.06.2024   13:35 Uhr

**Beobachtetes Verhalten**
Die LKW beim Truckerjob stehen so eng neben einander das man nicht auf der Fahrerseite einsteigen kann. Job startet nur auf der Fahrerseite. 

**Erwartetes Verhalten**
Die LKW sollten so spawnen/stehen das man ohne Probleme auf der Fahrerseite einsteigen kann.

**Schritte um den Fehler nachvollziehen zu können**
Versuchen einzusteigen, Fahrerseite ist blockiert, über die Beifahrerseite einsteigen, Job startet nicht da der LKW nur anspringt von der Fahrerseite

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![GTA5 2024-06-19 13-28-46](https://github.com/eiksch/statev_v3_issues/assets/173264092/c4ef0c49-157e-457e-a589-e0088e9ecdc0)

**Comment by simplycach** [comment]
Das ist leider dem AltV rotation Bug geschuldet.
