### ISSUE TITLE
Einparken in Hausgarage nicht möglich. Meldung Garage voll!

### ISSUE THREAD

**Issue by Vastouuu** [mexyn/statev_v2_issues#3497]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Tyler Jackson
**Auftrittszeitpunkt (Datum / Uhrzeit)**

19.06.2024
**Beobachtetes Verhalten**

Garage hat 6 Plätze und vorhin waren 4 Autos drin habe dann eins ausgeparkt und als ich es wieder einparken wollte bekomme ich die Meldung Garage voll. Habe dann ein weiteres Fahrzeug ausgeparkt, wollte es wieder einparken und bekam die gleiche Meldung wieder.
**Erwartetes Verhalten**

Einparken bis zu 6 Fahrzeuge wieder möglich.
**Schritte um den Fehler nachvollziehen zu können**

Versuchen einzuparken bei mir am Haus.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Garage Bug](https://github.com/eiksch/statev_v3_issues/assets/168358444/53bd5ca3-a042-4e0f-b1af-31896ddf97c2)
![Garage bug 2](https://github.com/eiksch/statev_v3_issues/assets/168358444/d3812e05-3e8f-4ca3-a3af-27fd6de14820)

**Comment by stepz2k9** [comment]
Es wurde im Changelog darauf hingewiesen, dass die Garagen-Platz-Anzahl angepasst wurde. Deine 6 wirst du nicht mehr haben.
Bei meinem Haus (Wert 76 k, 2/3) habe ich noch 4 Plätze.

**Comment by simplycach** [comment]
So wie @CaleighRhodes gesagt hat :)
