### ISSUE TITLE
Bitte um Erweiterung der Hausgarage wie Vorher

### ISSUE THREAD

**Issue by ManuelLadner** [mexyn/statev_v2_issues#3498]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Manuel_Turner & Jessika_Jackson**

**jederzeit**

**Garagenplätze von 6 auf 2 reduziert!**

**Bitte wieder auf 6 Plätze erweitern bei einem Haus für 200K**

**einparken am haus**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**https://pic.statev.de/i/Hlxu4q.jpg**

**Comment by simplycach** [comment]
Ist kein Bug ist ein Feature
