### ISSUE TITLE
Trailer Ramp 

### ISSUE THREAD

**Issue by oOBenSch** [mexyn/statev_v2_issues#3499]
**Benno_Stein**

**Dauerhaft**

**Wenn man den Trailer Ramp zuschließt dauert es 70 sek bis die Rampe wieder oben ist 
wenn man die Rampe öffnet haut die Rampe manchmal so auf den Boden das die Kopplung noch weiter unten ist
fahrt man wenn die Rampe noch zugeht bleibt sie auf der Position stehen**

**Comment by Erumeldor** [comment]
Hey @oOBenSch 
Der Trailer hat leider seine Problemchen - wir haben ihn aus RP Gründen trotzdem ins Spiel gebracht.
Leider können wir an dem Verhalten auch nichts groß ändern, das ist GTA Default....

**Comment by oOBenSch** [comment]
okay danke für die Info
