### ISSUE TITLE
Bitte um Versetzung des Garagen Punktes 

### ISSUE THREAD

**Issue by Tobias1496** [mexyn/statev_v2_issues#3501]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Luca_Gerwen**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot 2024-06-20 134733](https://github.com/eiksch/statev_v3_issues/assets/78904117/49343fc1-bb08-48bc-83e2-d68ae4de4cae)
![Screenshot 2024-06-20 134747](https://github.com/eiksch/statev_v3_issues/assets/78904117/9e2a60f9-4728-4faf-beaf-000d93702f54)
![Screenshot 2024-06-20 134928](https://github.com/eiksch/statev_v3_issues/assets/78904117/125b5ff8-4ad4-48a3-ac8d-6345c60f8e53)

**Comment by TheOutburst** [comment]
Der Marker ist dort, weil da hinten ein Carport / Eine Garage ist, so wie bei jedem anderen Carport oder Garage auch, der bleibt also da wo er ist
Und ja ich weiß, das bedeutet das große PKWs da nicht eingepart werden können, so wie bei jedem anderen Marker unter einem Carport auch
