### ISSUE TITLE
Haus Bug Länger nicht mher aktiv gewesen 

### ISSUE THREAD

**Issue by sandy02095530** [mexyn/statev_v2_issues#3502]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Parka_Srevens

Parka_Srevens
**Auftrittszeitpunkt (Datum / Uhrzeit)**

21:38
**Beobachtetes Verhalten**

Ich war nicht mher lange aktiv am spilen und Wohne in 2 Hotels das eine würd mir auf der Karte angezeigt das andre nicht
ich kann aus den Hotel nicht auszihen was mir nicht angezeigt würd

**Erwartetes Verhalten**

Das ich Auszihen kann 

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by sandy02095530** [comment]
![Uploading Hous2222222.png…]()

**Comment by sandy02095530** [comment]
![Hous2222222](https://github.com/eiksch/statev_v3_issues/assets/160181871/ef209f6c-3c89-43b2-9fa3-3bd762d5bc49)

**Comment by simplycach** [comment]
Besteht das Problem noch ?

**Comment by Erumeldor** [comment]
@sandy02095530 
Aus dem Zimmer ausziehen musst du an der Türe machen müssen bei der Immobilie. 
Das andere wird der Anzeigebug sein, der hier auch beschrieben ist:
https://github.com/eiksch/statev_v3_issues/issues/3517
