### ISSUE TITLE
Haus Änderung

### ISSUE THREAD

**Issue by AneRo1337** [mexyn/statev_v2_issues#3503]
Jimmy_Stone
 Mit welchem Character wurde das Verhalten in-game ausgelöst/beobachtet -->
Jimmy_Stone 

Guten Abend 

Ich habe 2 Fragen 

1,Wäre es möglich eine garage mit 2 auto Plätzen bei meinem haus einzufügen ( Wir bespielen es zu 2 ) ?

2,Wäre es möglich 3 Props Vom Grundstück zu entfernen ( Müllsäcke, ein Grosses Pappe Stück und ein Plakat mit werbung was extrem stört ?

Haus Hash = house_Davis_43

LG AneRo und danke für eure zeit 

hier ein bild vom Haus
![haus prps](https://github.com/eiksch/statev_v3_issues/assets/173416929/9731ead3-fb98-46ab-acaf-daae29be593c)

**Comment by TheOutburst** [comment]
Garagenmarker nach aktualisierter Garagenregelung next update hinzugefügt
Wir entfernen keine Objekte mehr von nicht öffentlichen Plätzen solange es nicht zwingend notwendig ist, abgesehen davon dass die Mülltonnen bei Y wieder sichtbar werden würden
