### ISSUE TITLE
Time Stamp fehlt teils bei SMS

### ISSUE THREAD

**Issue by LeaBrandt** [mexyn/statev_v2_issues#3506]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name** 
Ronja Brandtberg 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
glaube seit letztem großem Update / aktuell immer

**Beobachtetes Verhalten**
Wenn man im Tablet eine SMS schreibt bzw. von jemandem bekommt, dann steht darunter ja immer der Zeitpunkt der Nachricht. Wenn einer von beiden aber mehrere Nachrichten schreibt - ohne, dass der Andere antwortet - dann steht nur bei der aktuellsten Nachricht der Time Stamp. 

**Erwartetes Verhalten**
Jede Nachricht hat seinen eigenen Time Stamp, so dass ich z.B. auch später noch nachvollziehen kann wann ich jemanden geschrieben habe (auch wenn derjenige nicht antwortet) 

**Schritte um den Fehler nachvollziehen zu können**
Einer beliebigen Person mehrere Nachrichten hintereinander zu verscheidenen Uhrzeiten/Tagen senden.

**Comment by simplycach** [comment]
Ist alles richtig so wie es sein soll, wird auch nicht so angepasst, dass jede SMS ihren eigenen Timestamp hat.
