### ISSUE TITLE
Antrag auf versetzen des Ladepunktes

### ISSUE THREAD

**Issue by RyanTears** [mexyn/statev_v2_issues#3507]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Ryan Tears**

**Immer**

**Ladepunkt der Firma "BlackTears - Weberei ist nur mit Kleintransportern oder PKWs erreichbar.
Dieser liegt hinter der Firma und ist nur über eine schmale Seitengasse erreichbar und so oder so zu nah am Gebäude.
Des weiteren würde das Anfahren des Ladepunktes der Firma "BlackTears - Foundry", die Straße blockieren/beeinträchtigen.
Beide Firmen Liegen genau nebeneinander und Teilen sich ein Gebäude.**

**Wir würden uns freuen, wenn der Ladepunkt der Weberei ebenfalls vorne an der Straße platziert würde und im Idealfall mit dem der Gießerei kombiniert würde, sollte es Technisch einfacher sein reicht auch einfach das versetzen des Weberei Ladepunktes an die Strasse nach vorne.

Mfg Ryan**

**Versuchen mit größerem Fahrzeug an den Weberei punkt zu fahren**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**
![Einfahrt](https://github.com/eiksch/statev_v3_issues/assets/92888219/7c9858d2-6c39-45e2-9211-0c535967878b)
![Front](https://github.com/eiksch/statev_v3_issues/assets/92888219/c8f436ca-0b89-40db-bed9-b2c9edb39d1a)
![Karte](https://github.com/eiksch/statev_v3_issues/assets/92888219/137dce6c-111b-4a1e-9caf-01e51e1b0218)
![Ladepunkt 1](https://github.com/eiksch/statev_v3_issues/assets/92888219/1d48b896-f343-4165-886b-df3aa4c8b770)
![Ladepunkt 2](https://github.com/eiksch/statev_v3_issues/assets/92888219/30234dac-4a6a-4c3c-a025-e5023cbd4810)
![einfahrt 2](https://github.com/eiksch/statev_v3_issues/assets/92888219/5e98c72d-a028-4cc4-8143-66e00f22a81b)**

**Comment by Erumeldor** [comment]
Ladepunkt ist im nächsten Update nach vorne verlegt.
Zusammenlegen von Firmen tun wir aber nicht.
