### ISSUE TITLE
Ich kann durch verschlossene türen gehen

### ISSUE THREAD

**Issue by Shawn-Duckles** [mexyn/statev_v2_issues#3508]
Moin ich habe vorhin gemerkt das ich durch verschlossen türen gehen kann, ich habe auch einen Clip.

https://github.com/eiksch/statev_v3_issues/assets/173711610/bd65377d-3d59-4bab-82a7-978bfbb4d0a8

**Comment by JensGamerBoy** [comment]
kann ich so bestätigen und ich dachte es liegt an mir deswegen hatte ich das nicht gepostet, und hab es auch nicht ausgenutzt und so weiter

**Comment by simplycach** [comment]
Sollte fixed sein.
