### ISSUE TITLE
Caps passen sich nicht an

### ISSUE THREAD

**Issue by StateV-Jan** [mexyn/statev_v2_issues#3509]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Liam Taylor

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Beobachtetes Verhalten**
Caps passen sich nur mit Maske dem Kopf an.  (Haters Flex)

**Erwartetes Verhalten**
Caps passen sich dem Kopf an auch ohne Maske

**Schritte um den Fehler nachvollziehen zu können**
Mit einem Char der ein etwas größeren Kopf hat Caps anprobieren und schauen ob die Haut durchbuggt. Problem ist mit Maske weg da die Maske irgendwie beides steuert. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/screenshot-2024-06-24-180056.HlRW1z   Bild ohne Maske
https://pic.statev.de/image/screenshot-2024-06-24-180104.HlRgeD    Bild mit Maske

**Comment by Enemyaa** [comment]
@StateV-Jan Da kann man leider nichts machen. Die Maske benutzt eine Config, damit die Nase und so nicht durchbuggt, aber für die Caps gibt es das nicht.

**Comment by Enemyaa** [comment]
@StateV-Jan Da kann man leider nichts machen. Die Maske benutzt eine Config, damit die Nase und so nicht durchbuggt, aber für die Caps gibt es das nicht.
