### ISSUE TITLE
Ammunation Buffs - % Dropchance 92fs

### ISSUE THREAD

**Issue by AideenCarter** [mexyn/statev_v2_issues#3511]
Grüße, 

Würde mich freuen wenn man das System der Ammunation anpasst. 
Aktuell kommen wieder keine Gussformen, letzten 21 Tage - 1x 92fs Gussform. (Vergleich Adder 6x XD)
Klar kann Bad Luck sein, wird aber inzwischen etwas viel Bad Luck. 

Ich würde mich freuen wenn es die Chance gibt vor Ort Waffen zu lackieren und auch RP in der Ammunation zu spielen.
Eine Vielfalt an Waffen würde auch Beratungsgespräche  sinnvoller machen.
Vielleicht kann man ja zusammen etwas brainstormen.

**Comment by simplycach** [comment]
Hey @AideenCarter das ist hier ein Bugtracker, Vorschläge kannst du per Ticket im Discord einreichen.
