### ISSUE TITLE
Skill UI zeigt negativen Bonus (Drogenpflücker, Prison, Drogenverarbeitung)

### ISSUE THREAD

**Issue by gobi552** [mexyn/statev_v2_issues#3513]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Meikel Kingston
**Auftrittszeitpunkt (Datum / Uhrzeit)**

ihmer
**Beobachtetes Verhalten**

falschanzeige im skill https://prnt.sc/EdNbgyQjiaEl
**Erwartetes Verhalten**

richtige anzeige
**Schritte um den Fehler nachvollziehen zu können**

unter K im skillbaum
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://prnt.sc/EdNbgyQjiaEl

**Comment by Statev-Bonsai** [comment]
da hänge ich mich mit dran, allerdings beim skill drogenverarbeitung...
![Screenshot_11](https://github.com/eiksch/statev_v3_issues/assets/70241137/2d2bcc24-13e6-4e87-a1b4-9f14fbf68bfe)

**Comment by rodistic** [comment]
next update fixed
