### ISSUE TITLE
Drogenbuff Fehlerhaft 

### ISSUE THREAD

**Issue by BobbyCarsten** [mexyn/statev_v2_issues#3514]
###  _**Bobic Madujew**_

**Auftrittszeitpunkt (Datum / Uhrzeit)**
###  **_Jederzeit_**

**Beobachtetes Verhalten**
### **_Nutzung von Kokain führt zur Verkürzung der Abbauzeit (Naturausbeuter {Ölpumpen) wie gewollt , führt aber dazu das der Lernwachstum verringert wird. Im Normalzustand Abbauzeit Normal und Lernwachstum auch Normal_**

**Erwartetes Verhalten**
### **_Nutzung von Kokain führt zur verringerten Abbauzeit und der Lernwachstum ist nicht verringert._**

**Schritte um den Fehler nachvollziehen zu können**
 **_### MTL nehmen zur Ölpumpe fahren, Kokain nehmen warten bis die Wirkung einsetzt, anfangen zu pumpen, den Prozess wiederholen ohne Kokain zu nutzen und Prozessbalken Vergleichen._**

Besser nachzuvollziehen ist es, wenn man 1 Lkw befüllt (450L) =2x Kokain und das selbe Ohne Kokain // Prozessbalken Übereinander legen und Vergleichen 

@TheOutburst

**Comment by DonJohn1993** [comment]
![image](https://github.com/eiksch/statev_v3_issues/assets/79906053/c1a22267-9340-4cd7-af28-9a569cbff058)

Hatte das vor 2 Wochen oder so schon mitm Phantom mal analysiert, weil es mir auch komisch vorgekommen ist. Die Balken sind Solo mit Koks, sowieo zu zweit mit und ohne. Ich kann definitiv sagen, es wirkt nicht bei der XP. Der Speedboost klappt

**Comment by BobbyCarsten** [comment]
@simplycach @Pregon hier

**Comment by simplycach** [comment]
Das ist alles so richtig, ist kein Fehler lt. Rücksprache.

**Comment by BobbyCarsten** [comment]
Na dann hab ich jetzt schön 3-4 Wochen umsonst auf ne Antwort gewartet Hammer
