### ISSUE TITLE
Maischefass verbuggt...

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3515]
Jetzt mal Step bei Step...

1. Fass mit Weizen befüllt
2. Wasser zugefügt
3. System hat gefragt ob ich die Maische mit Frucht X verfeinern will.. NEIN geklickt
4. System hat danach gefragt ob ich die Maische mit Frucht Y verfeinern will.. Wieder NEIN geklickt. (hatte 2 verschiedene Sorten Früchte in der Tasche)
5. Char war stuck, konnte mich nicht mehr bewegen (inventar konnte ich noch öffnen), mit dem Fass kann ich garnicht mehr interagieren, also nicht leeren und nicht aufheben (Maischevorgang wurde auch nicht gestartet).

**Comment by Statev-Bonsai** [comment]
![Screenshot_18](https://github.com/eiksch/statev_v3_issues/assets/70241137/b658ce11-8950-46fb-ae2f-9da374eeaf6b)

Erste Fehlermeldung kommt beim aufheben, zweite beim öffnen des Fasses mit E...

**Comment by Statev-Bonsai** [comment]
nach dem restart konnte ich die fertige maische abschöpfen..

**Comment by nb431** [comment]
Ist das öfters aufgetreten oder war das ein einzelfall ?

**Comment by Statev-Bonsai** [comment]
bislang ein einzelfall..

**Comment by nb431** [comment]
Sollte dies nochmal auftretten mach bitte noch mal ein ticket auf
