### ISSUE TITLE
Aktenordner werden Komisch gehalten

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3516]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew_Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer
**Beobachtetes Verhalten**

Wenn man das item "Aktenordner"  verwendet und in die Hand nimmt ist es nen echter Ballanceakt, da dieser sehr weit hinten gegriffen wird
**Erwartetes Verhalten**

Eher die Position eines Kartons o.ä in der Hand
**Schritte um den Fehler nachvollziehen zu können**

Aktenordner in die Hand nehmen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/eiksch/statev_v3_issues/assets/58612983/26e10e0d-0d2b-467c-908a-c8fb7122e6c0)

**Comment by TheOutburst** [comment]
Du findest auch jeden scheiss, kann ich nicht 1x im Leben Faul sein und mir denken: "joa wird schon passen?" :D

Next update fixed
