### ISSUE TITLE
Hotel Anzeigebug auf Map

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3517]
Ich habe vorgestern ein zweites Hotelzimmer gemietet, seitdem wird nur das neue Zimmer auf der Map angezeigt aber nicht das ältere gemietete Zimmer.

**Comment by simplycach** [comment]
Ich glaube es kann immer nur ein Zimmer angezeigt werden.

**Comment by Statev-Bonsai** [comment]
bei v2 war das anders... da wurden alle angezeigt..
häuser werden auch 2 stück auf der map angezeigt..

**Comment by QA-Pregon** [comment]
Mitlerweile schon fixted und schon live
