### ISSUE TITLE
Fortschritt Skill Drogenverarbeitung beim Maischen und der Destillation... 

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3519]
Der skill drogenverarbeitung greift nicht beim ansetzen von maische und auch nicht beim brennvorgang mit der distille.
denke das sollte nicht so sein..

heute irgendwie tag der bugs, sry ;D

**Comment by rodistic** [comment]
Ayy Gude,

tatsächlich ist hier kein Drogen Skill einhängbar.
Das System kann nämlich von jeden genutzt werden und damit auch von jeden beendet werden auch wenn dieser das nicht angefangen hat. Damit wird eine Skill berechnung leider unmöglich
