### ISSUE TITLE
neue Fahrzeuge auspacken nicht möglich.

### ISSUE THREAD

**Issue by Naaki6** [mexyn/statev_v2_issues#352]
Owen West

**Zeitpunkt (Datum / Uhrzeit)**
21.11.2020 21:50

**Beobachtetes Verhalten**

Wenn man versucht im Autohaus oben an dem Punkt das Auto auszupacken passiert absolut gar nichts. Kein Fehler gar nichts.
**Erwartetes Verhalten**

Wenn man ein verpacktes Auto ins Lager tut, sollte man oben im Autohaus am Punkt das Fahrzeug auspacken können sofern man die Rechte hat.
**Schritte um den Fehler nachvollziehen zu können**

Auto vom Flatbat ins Lager -> ins Autohaus rein -> an dem Punkt zum Auspacken -> Nichts passiert.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by tastydev** [comment]
Hast du die Rechte dafür?
Welches Autohaus?
@Naaki6

**Comment by its4l3x** [comment]
Noch eine Zusatzfrage, welches Fahrzeug "erwartest" du auszupacken? bzw. welches dir angezeigt werden sollte?

**Comment by Naaki6** [comment]
Rechte habe ich, extra nochmal nachgefragt.
Autohaus Imperial Cars (also alte Crowns)

An Alex: Ich habe die Manchez Racing gebaut und wollte diese dort auspacken.

**Comment by its4l3x** [comment]
Kansnt du sagen wie viel PS?

**Comment by Naaki6** [comment]
Ja 66 PS. Liegt auch im Lager vom Autohaus falls du nachschauen willst

**Comment by Naaki6** [comment]
Heißt Offiziell laut Lager:
Maibatsu Manchez Cross (Race) / 66 PS

**Comment by its4l3x** [comment]
Fehler gefunden. Fahrzeug-Config fehlt. Habe bereits weitergegeben.

**Comment by its4l3x** [comment]
fixed. Bereits jetzt mit dem Update

**Comment by Naaki6** [comment]
Mega! Danke für die super schnelle Hilfe liebe geht raus
