### ISSUE TITLE
Sb PSP Verbr. Magazinschaft macht den Houdini

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3520]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew_Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

30.06 ca. 17Uhr
**Beobachtetes Verhalten**

Wenn man eine PSP mit erweitertem Mag hat und die Magazinerweiterung ausversehen in das Portemonnaie zieht wird dieses entfernt und man bekommt eine Fehlermeldung, dass du das dort nicht reinpacken kannst.  
Vorher war das Magazin auch nicht richtig drin, wobei ich keine Ahnung habe wieso (2x 6 Schuss anstelle 1x 12 Schuss in der Waffe)

Zudem kann man die Waffe danach nicht entrüsten, weil man zu viele Magazine zusätzlich hat
**Erwartetes Verhalten**

Fehlermeldung kommt und behält die Verbreiterung
**Schritte um den Fehler nachvollziehen zu können**

PSP mit Erweitertem Mag ausgerüstet haben und die Erweiterung ins Portemonnaie  ziehen

Traurig sein, dass es weg ist
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://medal.tv/games/gta-v/clips/iaQRz5nzp1nzGdBYt/d1337GFz3YIn?invite=cr-MSwzbzQsMTk1NTEzMTMzLA

**Comment by SHaagmann** [comment]
Nachtrag: Man kann ne neue Erweiterung ausrüsten und danach funktioniert es wieder normal

Nachtrag 2: Waffe wurde mit equipped extendes Mag abgerüstet und nochmal ausgerüstet im nachhinein daher würde es so gekommen sein.

**Comment by DrGrizzlY17** [comment]
Was hat Eminem damit jetzt zu tun?

**Comment by SHaagmann** [comment]
> Was hat Eminem damit jetzt zu tun?

Er hat mir nen Ohrwurm gegeben

**Comment by QA-Pregon** [comment]
Next update
