### ISSUE TITLE
Restaurant Essen möglich zwischen 18-22 Uhr ohne vorhandene Servicekraft

### ISSUE THREAD

**Issue by LiljaMorningstar** [mexyn/statev_v2_issues#3521]
**Character Name**

Quinn Valen
Arthur Hopkins
Hubertus Feger

**Auftrittszeitpunkt (Datum / Uhrzeit)**

30.06.2024    21.00 - 21.15 Uhr

**Beobachtetes Verhalten**

Die 18 - 22 Uhr Service (pflicht) kann umgangen werden.

**Erwartetes Verhalten**

Das dies nicht möglich ist. 
Denn so kann man als Restaurant sich bereichern wo andere im Restaurant stehen um es vernünftig zu bespielen.
Wenn der Inhaber sich einstempelt kostet Ihn das ganze nichtmal Lohn und er verdient weiterhin obwohl kein Service vor Ort ist.
Das ganze wurde in mehreren Variationen getestet von den oben genannten Personen.
In jeder Konstellation konnte man Essen obwohl keiner vor Ort war.

**Schritte um den Fehler nachvollziehen zu können**

1.) Mitarbeiter stempelt sich ein
2.) Mitarbeiter entfernt sich vom Restaurant soweit dass er ausser Reichweite für Info ist dass jemand etwas essen will.
3,) Gast setzt sich an den Tisch 
4.) Bestellung kann aufgegeben werden und gegessen werden als ob kein Service nötig wäre

**Comment by rodistic** [comment]
next update fixed
