### ISSUE TITLE
Bug beim anprobieren von Kopfbedeckungen

### ISSUE THREAD

**Issue by StateV-Jan** [mexyn/statev_v2_issues#3523]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Liam Taylor

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.07.2024 14:45

**Beobachtetes Verhalten**
Ich konnte nachdem ich die Hüte durchgeschaut habe keine anderen Klamotten mehr anschauen (konnte die zwar auswählen aber hatte durchgehend meine Kleidung an). Ich schätze es lag am Cowboy Hut das er irgendwas ausgelöst hat. Danach wurde meine Maske auch nicht mehr angezeigt. Nach einem Restart vom Game war wieder alles gut. 

**Erwartetes Verhalten**
Das man Caps durchgehen kann ohne diesen Bug

**Schritte um den Fehler nachvollziehen zu können**
Im Klamottenladen Vinest den Hutständer durchklicken und andere Klamotten anprobieren. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by nb431** [comment]
Hast du zufällig ein Clip davon weil ich kann es leider nicht reproduzieren ?

**Comment by StateV-Jan** [comment]
Ne leider nicht...ich probier das nachher nochmal aus und mach dann nen Clip falls es wieder passiert und melde mich dann nochmal

**Comment by StateV-Jan** [comment]
https://youtu.be/JWat3lqdzQU  Bitte

**Comment by StateV-Jan** [comment]
> Hast du zufällig ein Clip davon weil ich kann es leider nicht reproduzieren ?

https://youtu.be/JWat3lqdzQU

**Comment by ySimbaa** [comment]
@nb431 Guck mal bitte ob du es nochmal reproduziert bekommst. Kopfbedeckungen sollten eigentlich alle wieder normal laufen

**Comment by StateV-Jan** [comment]
@ySimbaa war grad nochmal im Kleidungsladen und irgendwie ist es "schlimmer" geworden...viele Klamotten werden nicht angezeigt (auch bei meinem Kollegen) dazu kam dann im nachhinein mehrere Bugs Navi kaputt, Soundproblem etc. Maske konnte ich aber wechseln und wurde auch angezeigt

**Comment by StateV-Jan** [comment]
Ich muss gleich nochmal ausprobieren ob es daran lag das wir zuerst Caps geschaut haben oder ob es die ganze Zeit passiert egal welcher Klamottenständer

**Comment by StateV-Jan** [comment]
Fehler besteht nur wenn man vorher am Cap Regal war

**Comment by ySimbaa** [comment]
> @ySimbaa war grad nochmal im Kleidungsladen und irgendwie ist es "schlimmer" geworden...viele Klamotten werden nicht angezeigt (auch bei meinem Kollegen) dazu kam dann im nachhinein mehrere Bugs Navi kaputt, Soundproblem etc. Maske konnte ich aber wechseln und wurde auch angezeigt


Ja, aufm Live ist auch noch kein Fix deswegen habe ich den guten @nb431 markiert der es mal aufm DEV testen soll :)
