### ISSUE TITLE
Auto nach dem einparken beschädigt. Kein fahren möglich.

### ISSUE THREAD

**Issue by Cramleo234** [mexyn/statev_v2_issues#3524]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Marc Klieter

02.07.2024 11:00

Zum zweiten Mal ist mein Auto nach dem Einparken „zu stark beschädigt“, um noch fahren zu können. Das Auto wurde normal eingeparkt und sieht äußerlich unbeschädigt aus. Diese wiederholten Schäden sind schwer nachvollziehbar und verursachen unnötige Abschlepp- und Reparaturkosten. Nach einem Austausch mit dem Support wurde festegstellt das mein Auto nur noch 814 "Leben" hatte.

**Erwartetes Verhalten**
Wenn ich mein Auto ausparke, sollte es keine Schäden davontragen.

**Schritte um den Fehler nachvollziehen zu können**
Im ersten Fall habe ich mein Auto vor meinem Hotel stehen gelassen, woraufhin es automatisch eingeparkt wurde. Dabei ist der gleiche Fehler aufgetreten.

Beim zweiten Mal habe ich das Auto selbst eingeparkt und wollte es heute wieder ausparken, woraufhin derselbe Fehler erschien.

Wir reden hier wohlgemerkt von einer öffentlichen Garage (Hupen = einparken).

Den Standort habe ich als Screenshot unten angehängt.

Es geht um das Auto mit dem Kennzeichen: SA-J4-DO

![Screenshot 2024-07-02 111549](https://github.com/eiksch/statev_v3_issues/assets/89691483/6667d627-4d6c-4ce8-a8cc-2d4a81afd3d6)
![Screenshot 2024-07-02 112944](https://github.com/eiksch/statev_v3_issues/assets/89691483/c9be7dad-4f77-4f4a-9f67-006f53925583)
![grafik](https://github.com/eiksch/statev_v3_issues/assets/89691483/8002e51b-7e50-4a1b-a2be-926eefce47a1)

**Comment by QA-Pregon** [comment]
Passiert dir das immer an der Garage oder nur ab und zu mal? (Oder auch an anderen Garagen?)

Und wurde vorher gegen das Auto getreten oder geschlagen (egal von wem und egal ob vorm oder nachm einparken)?

**Comment by QA-Pregon** [comment]
@Cramleo234 die Infos wären gut zu haben, da ich das Problem noch immer nicht reproduzieren konnte und es vorher nie aufkam

**Comment by Cramleo234** [comment]
Guten Abend! Sorry für das Nichtmelden.
Der Support hat mir noch mitgeteilt, dass mein Auto wohl von einem anderen Spieler beschädigt worden sein muss.

Ich war mir zwar sicher, dass ich mein Auto eingeparkt habe, dabei hat es sich allerdings wohl um das Auto einer Freundin gehandelt, die genau das gleiche Auto hat. Wir teilen uns den Schlüssel über die KeyApp im Spiel.

Insofern scheint hier alles seine Richtigkeit zu haben.

Tut mir leid für die Umstände.

**Comment by QA-Pregon** [comment]
Kein Problem, meine Vermutung war ja die selbe, danke für die Rückmeldung und schönen Abend noch
