### ISSUE TITLE
Cruiser unsichtbar / nicht vorhanden

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#3525]
**Character Name**
Charly Russo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.07.2024

**Beobachtetes Verhalten**
Wenn man das Cruiser Fharrad auspackt ist es nicht vorhanden / unsichtbar, also hat kein Model

**Erwartetes Verhalten**
Sollte da sein

**Schritte um den Fehler nachvollziehen zu können**
Cruiser bauen, auspacken, traurig sein

**Comment by QA-Pregon** [comment]
Sicher dass du es ausgeparkt hast?
Ich bekomm es direkt

![image](https://github.com/eiksch/statev_v3_issues/assets/75855042/abb7b06a-4cd3-4177-bbac-f466f5810e26)

**Comment by Philosofisch** [comment]
Heute gings wieder komischerweise. Sorry. Kann zu!
