### ISSUE TITLE
Auto wird beim Automatischen einparken ins Autohaus eingeparkt

### ISSUE THREAD

**Issue by JB98989** [mexyn/statev_v2_issues#3526]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

David_Morgan

29.06.2024 / 12:00 (Server Neustart)

**Beobachtetes Verhalten**
Mein Pounder wurde zum Server Neustart automatisch eingeparkt. Anstatt jedoch in die nächste öffentliche Garage, wurde er in ein Autohaus (factory_carShop2) eingeparkt. Auch vorheriges manuelles einparken in eine Öffentliche Garage hat nichts geholfen.

Kennzeichen: SA-DI-22

**Erwartetes Verhalten**
Einparken in die Öffentliche Garage.

**Comment by Erumeldor** [comment]
Haben wir hier schon, ich hab das Issue aus dem Grab gezogen.
https://github.com/eiksch/statev_v3_issues/issues/3181
