### ISSUE TITLE
Police Dinghy zählt als Auto, nicht als Boot

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#3527]
**Character Name**
Charly Russo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.07.2024

**Beobachtetes Verhalten**
Das Police Dinghy zählt im Autohaus als Auto und nicht als Boot, wird beim Autohaus zum Überschreiben also ausgepackt ohne Bootstaufe, ist also n bisschen anstrengend mit dem Flatbed rumzufahren

**Erwartetes Verhalten**
Sollte wie andere Boote zum Überschreiben n Stempel bekommen und beim Hafen ausgepackt werden mit Champagner

**Schritte um den Fehler nachvollziehen zu können**
Police Dinghy bauen und beim Autohaus überschreiben

**Comment by Erumeldor** [comment]
Ist im nächsten Update fixed :)
