### ISSUE TITLE
Grill kann nicht im Möbelladen entpackt werden

### ISSUE THREAD

**Issue by JasminHarper** [mexyn/statev_v2_issues#3528]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Josefine_Miley

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.07.24 ca. 22:20

**Beobachtetes Verhalten**
verpackter Grill kann nicht im Möbelladen entpackt werden.

**Erwartetes Verhalten**
Grill entpacken zu können. 

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/74868934/3cdb38b8-28fb-4ec9-949d-64863662d655)

**Comment by JasminHarper** [comment]
Firmenhash: furniture_LS_1

der Steingrill kann entpackt werden, jedoch der GRILL nicht.

**Comment by simplycach** [comment]
Soweit ich weiß ist der Normale Grill auch nicht für den Möbelladen, aber dazu kann @TheOutburst mehr sagen.

**Comment by QA-Pregon** [comment]
Nach Rücksprache mit Outburst kann ich das so bestätigen, ein Grill gehört nicht ins Möbelhaus ^^
