### ISSUE TITLE
Innenraumfarbe vom Omnis e-GT wird wieder Standard (Dunkelblau)

### ISSUE THREAD

**Issue by CalebPapaCrane** [mexyn/statev_v2_issues#3529]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Caleb_Robertrs**

Ava_Rise
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Heute, den Tag über
**Beobachtetes Verhalten**

Der Innenraum wurde 4 mal geändert, jedoch switcht er wieder zum Standart, in Dunkelblau
**Erwartetes Verhalten**

Das es schwarz bleibt xD (Weiß gibt es btw nicht, wird dunkelgrau)
**Schritte um den Fehler nachvollziehen zu können**

Einfach mit dem Auto rumfahren
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

FHD
**Optional: Video / Bilder des Fehlers**

**Comment by SatyriaDine** [comment]
Versucht mal ein anderes schwarz. Also eins was nicht die nummer 0 ist. :) Dann sollte es funktionieren.

**Comment by CalebPapaCrane** [comment]
Wir haben 4 verschiedene Schwarz Töne draufgepackt x)

**Comment by SatyriaDine** [comment]
Ich habs gerade mehrfach getestet und bei mir setzt sich nichts zurück. :D

Was aber stimmt ist dass es kein richtiges weiß gibt. Generell sind alle Innenraumfarben eher verwaschen.

**Comment by QA-Pregon** [comment]
Welche 4 Schwarztöne wurden getestet?

**Comment by CalebPapaCrane** [comment]
Metalic Black, Matt Black, Anthrazit und Worn Grey

**Comment by QA-Pregon** [comment]
Und bei jeder hat es sich dann resettet?
Direkt oder erst später? (Falls unsicher bitte keine falschaussage xD)

**Comment by CalebPapaCrane** [comment]
Nach ein paar Minuten, etwa 5-10. Auch nach paar mal Ein- und Ausparken, wurde es dann wieder Dunkelblau.

**Comment by QA-Pregon** [comment]
mhh ok danke, ich versuch mal das reproduziert zu bekommen

**Comment by simplycach** [comment]
Konnten wir bisher nicht reproduzieren.
