### ISSUE TITLE
Telefon Buggt

### ISSUE THREAD

**Issue by Domeex3** [mexyn/statev_v2_issues#353]
Domenik_Sommer

Bis ca. 22:50 Problemlos danach Kaputt

Man kann den Anruf entgegen nehmen, danach hängt sich das telefon auf.
Man hat den Anrufer nicht dran, kann den Anruf aber nicht beenden, Telefonneustart und neu Ausrüsten ohne Funktion.
Nach relog -> Anruf selbes problem.

**Comment by mexyn** [comment]
@Domeex3 Kannst du dazu noch ein paar mehr Infos geben? Wer hat wen angerufen (Nummern gerne per Discord oder TS falls Bedenken wegen Meta). Bei wem haengt sich das Phone auf? Beim Anrufer, beim Angerufenen? Bei beiden? Wann genau? In dem Moment, wenn der Anruf entgegengenommen wurde? Kann der Anrufer danach jemand anderen anrufen? Tritt das Problem nur bei einer Nummer auf oder bei allen?

**Comment by Domeex3** [comment]
Angerufen wurde auf der 1822-912 also MD Notruf, beim Anrufer hing es ebenfalls. Aufgehangen hat es sich nach drücken auf den Grünen Höhrer, danach blieb das Annehmen/Ablehnen Fenster aber da. Simkarte entfernen, Telefon aus dem Slot ziehen und An/Ausschalten brachte nichts, einzig der Relog, wurde danach wieder Angerufen, selbes spiel.

Kurz: Anruf -> Angenommen -> Bleibt im Annehmen Bildschirm -> Nix mehr geht.

**Comment by Domeex3** [comment]
Hier einmal aus Sicht des Anrufers: https://youtu.be/j9iC9zwdhyc

Sicht des Angerufenen:  https://youtu.be/AM3ejTJcTU0

Wie zu sehen ist wenn der Angerufene auf Annehmen klickt, nimmt er das Telefon ans Ohr aber es funktioniert nicht.

**Comment by mexyn** [comment]
@Domeex3 Es wurden im letzten Hotfix ein paar Probleme mit der Sim Card gefixt. Bitte mal Feedback geben, ob das Problem noch auftritt

**Comment by mexyn** [comment]
Scheint nicht so, daher schließe ich das Ticket
