### ISSUE TITLE
Motorrad klauen "Carlos"

### ISSUE THREAD

**Issue by robka87owl** [mexyn/statev_v2_issues#3530]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Salomone Ferri

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.07.2024 - 22:51 Uhr

**Beobachtetes Verhalten**
Stehle ein Motorrad ( Crime )

**Erwartetes Verhalten**
Marker am Tor

**Schritte um den Fehler nachvollziehen zu können**
Carlos besuchen, dann Marker auf der Karte, hinfahren, marker auslösen ( dieser fehlt )

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1080p

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/eiksch/statev_v3_issues/assets/140908156/793591c9-8527-49e3-be6a-96da5dde0593)

**Comment by QA-Pregon** [comment]
2 kleine Fragen dazu:
1. 100% die richtige Stelle?
2. Ist das deine erste Carlos Mission an dem Tag?

**Comment by robka87owl** [comment]
- 100% die richtige Stelle?
Ja, da laut Karte soll diese dort sein, leider war kein Marker zu sehen.
- Ist das deine erste Carlos Mission an dem Tag?
Nein, das ist die zweite oder dritte Mission an diesem Tag, jedoch die erste für nen Motorrad.

**Comment by QA-Pregon** [comment]
Hast du die Autos vorher einfach weggebracht oder Ausgeschlachtet?

**Comment by robka87owl** [comment]
Die Fahrzeuge wurde nur weggebracht. Vom Ausschlachten weiß ich IC nichts.

**Comment by QA-Pregon** [comment]
Ok
War die Abholmarkierung auf der Map noch da, als du an der Garage vor Ort warst oder war die dann schon weg?

**Comment by robka87owl** [comment]
Die war weg. Da war ja das Problem. Auf der Karte sichtbar, vor der Nase nicht.

**Comment by robka87owl** [comment]
Hier auch nochmal zu sehen: https://clips.twitch.tv/ClumsySpoopyOysterGrammarKing-UFsWJqJt-p7_G177

**Comment by Pregon** [comment]
Du hast nicht zufällig einen Clip von der Fahrt von Carlos zu der Garage?
Sonst hätte ich vlt eine Vermutung

**Comment by robka87owl** [comment]
https://www.twitch.tv/videos/2190662519

Ab 06:58:23 ist der Anfang

**Comment by QA-Pregon** [comment]
Alles klar danke, ich versuch mal was rauszufinden

**Comment by QA-Pregon** [comment]
Fixed next Update
