### ISSUE TITLE
Änderung Abladepunkte meiner Firmen

### ISSUE THREAD

**Issue by Franklin-1337** [mexyn/statev_v2_issues#3531]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
David Roessler

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
Ich würde gerne die beiden Abladepunkte meiner Firmen umgesetzt haben, da man Sie nur schwer mit eine Achse anfahren kann.

**Erwartetes Verhalten**
Siehe beigefügte Bilder
Lager Hash: pf_cypressflats_13
Labor Hash: pf_cypressflats_8

**Optional: Video / Bilder des Fehlers**
![Lager](https://github.com/eiksch/statev_v3_issues/assets/174944267/14fecc56-47f1-41b1-9275-6171f27326f7)
![Labor](https://github.com/eiksch/statev_v3_issues/assets/174944267/19574495-3255-40f3-9ebf-d21936c408bf)

**Comment by SatyriaDine** [comment]
Ladepunkte sind zum nächsten Update versetzt :)
