### ISSUE TITLE
Speichern von Animationen funktioniert nicht

### ISSUE THREAD

**Issue by SauerkirscheJM** [mexyn/statev_v2_issues#3533]
Hallo zusammen!

seit knapp nem Monat habe ich folgendes Problem:
wenn ich mir bei Animationen neue Ordner erstelle oder eine neue Animation speichere, sind diese nach dem nächsten Relogg verschwunden. Egal wie oft ich das mittlerweile gespeichert habe oder wie lang ich dann online war ohne Disconnect oder sowas, waren sie beim nächsten Einloggen wieder weg. Und da ich im Kopf habe, dass sowas Serverseitig gespeichert wird, wollte ich das melden.

Das Problem ist bei folgenden Personen aufgetreten:
Nova_Rise (mein Char)
Alvar_Pierce
Alfred_Vogelsang

Könnte mir vorstellen, dass dieses Problem vielleicht mehrere Personen haben, aber da sie keine neuen Animationen speichern, fällt es nicht auf.

**Comment by simplycach** [comment]
Also bei mir funktioniert das ohne Probleme, lösch sonst mal einmal deinen AltV Cache.

Passiert das auch wenn du dein Spiel neustartest oder nur wenn der Server neustartet? 

Gucke mir das aber nachher zuhause mal einmal an, kannst du mir sagen um welche Animationen es sich handelt?

**Comment by SauerkirscheJM** [comment]
jedesmal wenn ich auslogge. und das Problem hab ja auch nicht nur ich

Gemerkt hab ich es nur bzgl. der Tänze. Bin seit kurzem in ner Tanzgruppe und muss jedesmal alles neu speichern. Was anderes habe ich nicht probuiert.
Mein Kollege Alvar hat das Problem aber grunsätzlich bei allem. Der hat ne Weile nicht mehr gespielt, und jetzt war alles weg und er kann nichts neu speichern.

**Comment by simplycach** [comment]
Das habe ich gelesen ja, vielleicht könnt ihr uns ja mal die Animationen nennen. Oder ist es ein Grundsätzliches Problem mit allen Animationen ?

**Comment by simplycach** [comment]
Okey grad erst gesehen, ich schau mir das mal heute Abend an, danke fürs melden und einen schönen Abend.

**Comment by SauerkirscheJM** [comment]
Bei Alvar wohl auch allgemeine Animationen wie "Bro Great" und sowas. Bei Alfred und mir gehts um die Tänze. 
Hab da eben nicht weiter rumprobiert, weil alles Alte sonst vorhanden ist.

**Comment by simplycach** [comment]
Kann ich leider weder auf dem Dev-Server oder auf dem Live-Server bestätigen, bei mir funktioniert das ohne Probleme. Bitte einmal den Cache Ordner löschen und ggf. AltV neu installieren. (Wichtig bitte AltV als Admin starten)

Das wird nicht Server-Seitig gespeichert sondern Local.

**Comment by SauerkirscheJM** [comment]
also cache löschen hat an den animationen nix geändert. die waren danach immernoch vorhanden nur nicht vollzählig. und einspeichern und neustarten war dann wieder alles, was ich zugefügt hatte, weg.
Versuche dann mal neuinstallation ~.~
