### ISSUE TITLE
Einparkpunkt am Haus fehlt 

### ISSUE THREAD

**Issue by Dene87** [mexyn/statev_v2_issues#3534]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Jack Hopkins**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

Ich habe ein Haus ( house_Paletobay_6 ) in Paleto gekauft. Beim Kauf stand in der Info, dass das Haus eine Garage mit 2 Plätzen hat. 
Ich habe keinen Einparkpunkt, der fehlt leider.
**Erwartetes Verhalten**

Ich sollte einen Einparkpunkt haben.
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![chrome_eVGpovfvsl](https://github.com/eiksch/statev_v3_issues/assets/104981198/17651a18-0b3b-47ea-b3ee-a825aeb2a402)
![GTA5_9qjtmL9C8i](https://github.com/eiksch/statev_v3_issues/assets/104981198/fb951489-5395-431b-9d13-8b99a0cafd1d)
![GTA5_FpvN7MC4O3](https://github.com/eiksch/statev_v3_issues/assets/104981198/d74f2c78-49ac-45b5-9803-268d9f5f634f)

**Comment by TheOutburst** [comment]
Garagenpunkt zum nächsten Update hinzugefügt
