### ISSUE TITLE
Haus 

### ISSUE THREAD

**Issue by Asterix526** [mexyn/statev_v2_issues#3535]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Haus gekauft und möchte gerne das Verkaufschild entfernt bekommen. 

Adresse Senora Freeway 17

*

**Comment by SgtBoaz-Terry** [comment]
Wir benötigen den Haushash (steht an der Haustür).
Ein Bild, welches Schild entfernt werden soll?

Bitte eine vernünftige Beschreibung das nächste Mal hinzufügen.
Danke :)

**Comment by Asterix526** [comment]
Ich werde das nächste Mal daran denken. house_SandyShores_60Verkaufschild direkt neben Briefkasten Name Christian _BigMit freundlichen Grüßen Von meinem Telefon gesendet-------- Ursprüngliche Nachricht --------Von: SgtBoaz-Terry ***@***.***>Datum: Mi., 10. Juli 2024, 20:07An: eiksch/statev_v3_issues ***@***.***>Cc: Asterix526 ***@***.***>, Author ***@***.***>Betreff: Re: [eiksch/statev_v3_issues] Haus  (Issue #3535)
Wir benötigen den Haushash (steht an der Haustür).
Ein Bild, welches Schild entfernt werden soll?
Bitte eine vernünftige Beschreibung das nächste Mal hinzufügen.
Danke :)

**Comment by Asterix526** [comment]
Guten Morgen währe es eventuell Bitte möglich einen Geldautomat an meine Tankstelle aufzustellen Christian Big, das währe Bigs-Tanke petrolstation14. Leider bemängeln das viele Kunden da weit und breit keiner ist wo es sich lohnt wieder zur Tankstelle zurück zu kommen und somit verliere ich die wenigen Kunden die dort überhaupt Tanken 🙈mit freundlichen Grüßen MLG Von meinem Telefon gesendet-------- Ursprüngliche Nachricht --------Von: SgtBoaz-Terry ***@***.***>Datum: Mi., 10. Juli 2024, 20:07An: eiksch/statev_v3_issues ***@***.***>Cc: Asterix526 ***@***.***>, Author ***@***.***>Betreff: Re: [eiksch/statev_v3_issues] Haus  (Issue #3535)
Wir benötigen den Haushash (steht an der Haustür).
Ein Bild, welches Schild entfernt werden soll?
Bitte eine vernünftige Beschreibung das nächste Mal hinzufügen.
Danke :)

**Comment by simplycach** [comment]
> Guten Morgen währe es eventuell Bitte möglich einen Geldautomat an meine Tankstelle aufzustellen Christian Big, das währe Bigs-Tanke petrolstation14. Leider bemängeln das viele Kunden da weit und breit keiner ist wo es sich lohnt wieder zur Tankstelle zurück zu kommen und somit verliere ich die wenigen Kunden die dort überhaupt Tanken 🙈mit freundlichen Grüßen MLG Von meinem Telefon gesendet-------- Ursprüngliche Nachricht --------Von: SgtBoaz-Terry ***@***.***>Datum: Mi., 10. Juli 2024, 20:07An: eiksch/statev_v3_issues ***@***.***>Cc: Asterix526 ***@***.***>, Author ***@***.***>Betreff: Re: [eiksch/statev_v3_issues] Haus (Issue #3535) Wir benötigen den Haushash (steht an der Haustür). Ein Bild, welches Schild entfernt werden soll? Bitte eine vernünftige Beschreibung das nächste Mal hinzufügen. Danke :) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Das haben wir dir bereits schon mal abgelehnt, daran ändert sich leider nichts.**

**Comment by Asterix526** [comment]
Ich verstehe leider den Grund nicht, deshalb habe ich erneut freundlich gefragt. Ein großer Teil versteht die Problematik nicht. Mit freundlichen Grüßen Von meinem Telefon gesendet-------- Ursprüngliche Nachricht --------Von: simplycach ***@***.***>Datum: Do., 11. Juli 2024, 12:21An: eiksch/statev_v3_issues ***@***.***>Cc: Asterix526 ***@***.***>, Author ***@***.***>Betreff: Re: [eiksch/statev_v3_issues] Haus  (Issue #3535)
Das haben wir dir bereits einmal abgelehnt, daran hat sich auch nichts geändert.

Guten Morgen währe es eventuell Bitte möglich einen Geldautomat an meine Tankstelle aufzustellen Christian Big, das währe Bigs-Tanke petrolstation14. Leider bemängeln das viele Kunden da weit und breit keiner ist wo es sich lohnt wieder zur Tankstelle zurück zu kommen und somit verliere ich die wenigen Kunden die dort überhaupt Tanken 🙈mit freundlichen Grüßen MLG Von meinem Telefon gesendet-------- Ursprüngliche Nachricht --------Von: SgtBoaz-Terry @.>Datum: Mi., 10. Juli 2024, 20:07An: eiksch/statev_v3_issues @.>Cc: Asterix526 @.>, Author @.>Betreff: Re: [eiksch/statev_v3_issues] Haus (Issue #3535) Wir benötigen den Haushash (steht an der Haustür). Ein Bild, welches Schild entfernt werden soll? Bitte eine vernünftige Beschreibung das nächste Mal hinzufügen. Danke :) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.***>

Das haben wir dir bereits schon mal abgelehnt, daran ändert sich leider nichts.

**Comment by SgtBoaz-Terry** [comment]
Führe hier jetzt bitte keine Diskussion. Die Entscheidung steht. Kein ATM.
Außerdem geht dieser Bugtracker um dein Haus und nicht deine Tankstelle.

Danke.

**Comment by simplycach** [comment]
Ich könnte dir jetzt ein paar Begründungen nennen, viele davon werden dich aber nicht Zufriedenstellen. 

1. Aktuell sind die Kapazitäten die wir zur Verfügung haben sehr begrenzt.
2. War dir ja bekannt beim erwerben der Tankstelle, welche Gegebenheiten und Lage dort gegeben ist..
3. Wurden ATMs so gut wie noch nie von uns platziert, sofern sie nicht von einem MLO-Creator bereits vorhanden waren.  
4. Ich sehe in deinem Umkreis bisher keine weitere Tankstelle und mindestens 2 ATMs wo man Geld holen könnte. 

Wie @SgtBoaz-Terry bereits geschrieben hat, geht es hier um dein Haus & bitte sehe davon ab weiter darüber zu diskutieren.

**Comment by Asterix526** [comment]
Mir reicht die Begründung vollkommen,ich fragte hinzu weil ich immer wieder IC gefragt werde warum keiner steht ich könne und solle doch einen beantragen. Als ich sagte das die Bank keinen genehmigt war die Aussage immer wieder ich solle doch einfach nochmal freundlich fragen. Habe ich getan und ist ok. Mir geht's nicht um mich sondern IC Kunden, mir ist es völlig latte ob die nur die meiste Zeit 200 $ pro Tag einspielt oder nicht. Also bitte mich nicht immer wieder direkt böse einstufen. Mit freundlichen Grüßen Von meinem Telefon gesendet-------- Ursprüngliche Nachricht --------Von: simplycach ***@***.***>Datum: Do., 11. Juli 2024, 12:38An: eiksch/statev_v3_issues ***@***.***>Cc: Asterix526 ***@***.***>, Author ***@***.***>Betreff: Re: [eiksch/statev_v3_issues] Haus  (Issue #3535)
Ich könnte dir jetzt ein paar Begründungen nennen, viele davon werden dich aber nicht Zufriedenstellen.
Aktuell sind die Kapazitäten die wir zur Verfügung haben sehr begrenzt.War dir ja bekannt beim erwerben der Tankstelle, welche Gegebenheiten und Lage dort gegeben ist..Wurden ATMs so gut wie noch nie von uns platziert, sofern sie nicht von einem MLO-Creator bereits vorhanden waren.Ich sehe in deinem Umkreis bisher keine weitere Tankstelle und mindestens 2 ATMs wo man Geld holen könnte.
Wie @SgtBoaz-Terry bereits geschrieben hat, geht es hier um dein Haus & bitte sehe davon ab weiter darüber zu diskutieren.

**Comment by TheOutburst** [comment]
Verkaufsschild zum nächsten Update entfernt

**Comment by Asterix526** [comment]
Oky, ich danke euch. Lg Von meinem Telefon gesendet-------- Ursprüngliche Nachricht --------Von: TheOutburst ***@***.***>Datum: Sa., 20. Juli 2024, 21:41An: eiksch/statev_v3_issues ***@***.***>Cc: Asterix526 ***@***.***>, Author ***@***.***>Betreff: Re: [eiksch/statev_v3_issues] Haus  (Issue #3535)
Verkaufsschild zum nächsten Update entfernt
