### ISSUE TITLE
be/entlade Punkt versetzen

### ISSUE THREAD

**Issue by loelchn** [mexyn/statev_v2_issues#3536]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Luca Lorenzi**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Dauerhaft

**Beobachtetes Verhalten**

Be/Entlade Punkt

**Erwartetes Verhalten**

Keine richtige Zufahrt mit Punder +

**Schritte um den Fehler nachvollziehen zu können**

Umsetzung

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

Ne

**Optional: Video / Bilder des Fehlers**

wir würden gerne eine Firma kaufen. Haben getestet ob ein Pounder zum Be-/Entladepunkt durchpasst, dieser ist zu hoch, gescheige von einen Phantom ect. Jetzt einfach blind kaufen, und hoffen, der Be-/Entladepunkt wird schon versetzt wäre mir zu riskant. 
Könnte man da was machen, und vorab das abklären?

Bild mit Erklärung:
https://pic.statev.de/i/HlnKei.png

Firmename:
https://pic.statev.de/i/HlnWs6.png

VG

**Comment by SatyriaDine** [comment]
Ladepunkt zum nächsten Update versetzt :)
