### ISSUE TITLE
Möbelhaus in der Stadt buggt

### ISSUE THREAD

**Issue by StateV-Jan** [mexyn/statev_v2_issues#3537]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Liam Taylor und Arthur Tarasov

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11.07.2024 ca 16:20

**Beobachtetes Verhalten**
Sobald man im Möbelhaus in der Stadt ist, sieht und hört man sich nicht mehr. Dazu fehlen ab und zu Texturen (jenachdem wo man grade ist)

**Erwartetes Verhalten**
Man sollte sich sehen und hören kann und das die Texturen nicht verloren gehen

**Schritte um den Fehler nachvollziehen zu können**
Möbelhaus in der Stadt besuchen und schauen ob der andere Spieler verschwindet

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by stepz2k9** [comment]
Laut #3400 ist es gefixt, aber ich kanns bestätigen, vor 2 Wochen waren wir da auch drin und haben uns nicht gesehen und gehört.

**Comment by TheOutburst** [comment]
Ist das seit dem letzten Update immernoch der Fall?
