### ISSUE TITLE
Fehler beim Essenbestellen

### ISSUE THREAD

**Issue by Lykke55** [mexyn/statev_v2_issues#3538]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Taylor Hughes

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11.07.2024 20:30Uhr

**Beobachtetes Verhalten**
Nach Absenden der Essensbestellung beim County Container schließt sich die "Karte" (Menü) nicht. Auch schon auf schließen geklickt ebenfalls weiterhin offen 

**Erwartetes Verhalten**
Menü schließt sich

**Schritte um den Fehler nachvollziehen zu können**
Keine Ahnung hab mich normal hingesetzt und bestellt.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![Screenshot 2024-07-11 203355](https://github.com/eiksch/statev_v3_issues/assets/175350336/063613c1-a402-4588-849a-c26c59d7fe67)
(Inv is nur offen für Cursor)

**Comment by QA-Pregon** [comment]
Grüße
Tritt das immer auf oder war das ein Einmaliges Thema?

**Comment by Lykke55** [comment]
Also der Fehler weil hetz einmal ... heute am Container hatte ich das Problem, dass ich nicht aufstehen konnte, weil es sagte das irgedn eine Vorgang im X-Menü abgeschlossen sein muss ... ging dann wieder nachdem ich die "Karte" bekommen und schließen durfte

**Comment by QA-Pregon** [comment]
Das mit dem X Menü klingt für mich so, als würdest du Bestellen wollen, hast 'E' gedrückt und konntest dann nicht mehr aufstehen, richtig?

**Comment by Lykke55** [comment]
war auf "Auf Bedienung warten" ja

**Comment by QA-Pregon** [comment]
da kannste nicht aufstehen, da musst du vorher den Bestellvorgang im X-Menü abbrechen

![image](https://github.com/user-attachments/assets/11d28067-93cf-442e-8595-4c35bc8c0c59)

**Comment by Lykke55** [comment]
ahh oki

**Comment by QA-Pregon** [comment]
Kannst einmal genau Schritt für Schritt beschreiben, was den Fehler ausgelöst hat mit der offenen Bestellung wo du auch nicht schließen konntest?

Am besten ab dem Moment an dem du dich hingesetzt hast

**Comment by Lykke55** [comment]
also 
1. Hingesetzt
2. E-Gedrückt
3. Meldung kommt "warten auf Bedienung"
4. Bedienung kommt und gibt mir die Karte
5. ich wähle Essen + trinken aus und wähle bestellen
6. Fenster schließ sich sich nicht
7. ich drücke nochmal "bestellen"
8. schließt immer noch nicht
9. ich drücke schließen 
10. Nachricht unten links kommt
11. wiederhole Punkt 9-10 3x
12. bin dann aufgestanden und habe gerellogt
13. danach war Fenster weg

**Comment by QA-Pregon** [comment]
Wie lang hast du ca. gebraucht bis du bestellt hast nachdem du die Karte bekommen hast?

**Comment by Lykke55** [comment]
boahhh ... ehmmm ... warte ich hab das gestreamt ich mach kurz nen Clip draus

**Comment by QA-Pregon** [comment]
perfekt, noch besser

**Comment by Lykke55** [comment]
https://clips.twitch.tv/BetterRamshackleWhalePJSugar-p9CzYl26jVQyqE2N

**Comment by QA-Pregon** [comment]
Habs mal bei uns aufgenommen, aber passiert echt selten, mal sehen ob wir da was finden

**Comment by Lykke55** [comment]
check danke euch

**Comment by simplycach** [comment]
Konnten wir bisher nicht reproduzieren, wenn es nochmal auffällt bitte erneut posten.
