### ISSUE TITLE
Be/Entladepunkt Versetzen

### ISSUE THREAD

**Issue by AtzeDejavu** [mexyn/statev_v2_issues#3539]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Hades Russo**

Hades Russo
**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
Be/Abladepunkt ist im weg weil wir da  die Fläche aktiv als Parkplatz nutzen weil so wenig vor Ort vorhanden ist. 

**Erwartetes Verhalten**
Es wäre sehr gut (nett) wenn man diesen Punkt versetzen könnte das wir da aktiv ohne Umwege Be. und Entladen könnten.

**Schritte um den Fehler nachvollziehen zu können**
https://ubload.space/uploads/1720785590.png 

https://ubload.space/uploads/1720866345.png

Wie man auf beide Bilder sehen kann stehen da unsere Fahrzeuge. Wir haben da aufn Gelände allg. wenig Park Möglichkeiten deswegen auch meine frage ob man das für uns machen könnte?

https://ubload.space/uploads/1720871188.png

Es wäre sehr nett wenn man den Punkt vielleicht in der Ecke setzen könnte (siehe Bild) . Da kommt man auch eindeutig besser ran mit einer Achse oder andere große Lkw´s .

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Oben schon beschrieben.

**Comment by Erumeldor** [comment]
Hi @AtzeDejavu 
Wir verlegen Ladepunkte nur, wenn sie nicht oder schlecht erreichbar sind.
Der Ladepunkt ist dort wunderschön erreichbar und auch optisch an der Laderampe des Gebäudes.

Deshalb wird der da wohl bleiben. :)
