### ISSUE TITLE
Boot Fehlender Anker/Handbremse

### ISSUE THREAD

**Issue by glb11** [mexyn/statev_v2_issues#354]
**Character Name**

**Zeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by glb11** [comment]
**Character Name**
Jens_Summer

**Zeitpunkt (Datum / Uhrzeit)**
22.11.2020 1:00

**Beobachtetes Verhalten**

Boot treibt weg (Bild 1+2) ohne das mann es verhindern kann. (Fehlende Handbremsen/Anker Funktion) --> und gehrt dadurch defekt (rote Kontrollleuchte) --> wieder Support wegen Rep.

in V1 war dieser Automatisch beim verlasen des Fahrersitzes)

**Erwartetes Verhalten**

Das es eine Funktion gibt wo mann das Boot festmachen kann (Handbremse/Anker) im X-Menü (Bild 3)

**Schritte um den Fehler nachvollziehen zu können**
 
mit einem Boot (z.B. Dinghty  (wahrscheinlich bei allen Wasserfahrzeugen so)) zur Kaffeeinsel/Zuckerinsel fahren das Boot ausschalten und einen Rucksack sammeln und dann dem Boot hinterher schwimmen. bzw einfach das Boot ausgeschaltet auf dem Wasser stellen und warten und beobachten wie es weg treibt.

**Optional: Video / Bilder des Fehlers!**

[20201122005025_1](https://user-images.githubusercontent.com/70204338/99890542-b0d28000-2c60-11eb-846d-84d6d9ef496a.jpg) Bild 1 0:50:25   

![20201122005555_1_LI](https://user-images.githubusercontent.com/70204338/99890575-0b6bdc00-2c61-11eb-80e9-40d0d23d4334.jpg)
 Bild 2 0:55:55  boot weg getrieben

![20201122005804_1](https://user-images.githubusercontent.com/70204338/99890581-1b83bb80-2c61-11eb-804f-37c2ad174c1b.jpg) Bild 3  X-Menü im Boot  Fehlende Handbremse/Anker funktion)

**Comment by DonVitoDiangelo** [comment]
Du musst eine bestimmte Wassertiefe erreichen um das Boot ankern zu können.

**Comment by glb11** [comment]
ok werte ich später nochmal überprüfen ab wann die Funktion kommt und werde mich nochmal melden   weil wenn das Boot wegtreibt und defekt wird verbringt mann mehr zeit im Support als auf dem Feld.

**Comment by glb11** [comment]
mann muss 1/2m weiter auf dem Wasser bleiben was ok ist muss man aber wissen
