### ISSUE TITLE
Casino ist'n Betrüger

### ISSUE THREAD

**Issue by CalebPapaCrane** [mexyn/statev_v2_issues#3540]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Caleb_Roberts

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.07.2024 - 20:12 ~ 20:17

**Beobachtetes Verhalten**
Karten gehen Hoch und runter, also meine "Hand", siehe Video..

**Erwartetes Verhalten**
Richtige Kalkulation :D

**Schritte um den Fehler nachvollziehen zu können**
Siehe Video, ich mach einfach nur meinen Einsatz und ziehe eine Karte

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
FHD

**Optional: Video / Bilder des Fehlers**
https://streamable.com/d4b3wo
https://streamable.com/y4smfc

**Comment by QA-Pregon** [comment]
Alles richtig, Ass ist entweder 1 oder 11
Wenn der Wert über 21 gehen würde, wird die 11 automatisch zur 1

**Comment by CalebPapaCrane** [comment]
Ok? https://streamable.com/fedu4o

**Comment by CalebPapaCrane** [comment]
https://streamable.com/y4smfc - Also das ist auch keine 1 :D

**Comment by QA-Pregon** [comment]
> Ok? https://streamable.com/fedu4o

Unter der 5 liegt ein Ass (5+11=16)

Dann ziehst du eine 9 (5+11+9=25 | 25 > 21)
Ass wird zu 1 (5+1+9=15)

> https://streamable.com/y4smfc - Also das ist auch keine 1 :D

Unter der 4 liegt ein Ass (4+11=15)

Dann ziehst du eine 7 (4+11+7=22 | 22 > 21)
Ass wird zu 1 (4+1+7=12)

**Comment by epichalt** [comment]
![image](https://github.com/user-attachments/assets/cb9232bd-02d2-4d6c-affc-bf8a97f54b9b)
