### ISSUE TITLE
Skillsystem Bug

### ISSUE THREAD

**Issue by JensGamerBoy** [mexyn/statev_v2_issues#3541]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Jens Steingarten

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14.07.2024/ Ganzen tag

**Beobachtetes Verhalten**
Das Skillsystem geht einfach nicht weiter und das seit stunden bei Farmer hängt der die ganze zeit an der stelle und geht nicht weiter
und pro Payday unten die Prozentzahl geht auch nicht hoch immer erst nach paar stunden gefühlt

**Erwartetes Verhalten**
das es hochgeht beim Sammeln

**Schritte um den Fehler nachvollziehen zu können**
Einfach Sammeln und sehen das es nicht hochgeht

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Hier eine fehlermeldung die auch im f8 immer zusehen ist 

Check the render method of `SkillOverview`.  
    at div
    at SkillOverview (http://resource/client/ui/index.js:1200622:26)
    at div
    at div
    at div
    at div
    at SkilltreeComponent (http://resource/client/ui/index.js:1200769:70)
    at ErrorBoundary (http://resource/client/ui/index.js:1426726:7)
    at RecoilRoot_INTERNAL (http://resource/client/ui/index.js:102840:5)
    at RecoilRoot (http://resource/client/ui/index.js:102957:7)
    at div
    at App (http://resource/client/ui/index.js:1426799:20)

**Comment by simplycach** [comment]
Hey am besten machst du mal einen Screenshot vom aktuellen Stand und guckst dann ob es sich weiter bewegt hat. Uns ist bisher kein Fehler bekannt.

**Comment by JensGamerBoy** [comment]
Ja hab ich gemacht sogar und nach 1h oder so hat sich der balken wieder bewegt komischerweiße also ist es so gewollt das es lange dauert bis der balken hochgeht?

**Comment by simplycach** [comment]
Ja ist normal.
