### ISSUE TITLE
Tuning Fehler Betreff Toros 

### ISSUE THREAD

**Issue by Tobias1496** [mexyn/statev_v2_issues#3543]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Luca_Gerwen

**Auftrittszeitpunkt (Datum / Uhrzeit)**
immer 

**Beobachtetes Verhalten**
Wenn ich am Toros nen Spoiler machen will wird die vordere Stoßstange verändert will ich die vordere Stoßstange machen wird der Spoiler verändert
**Erwartetes Verhalten**
Genau andersrum

**Schritte um den Fehler nachvollziehen zu können**
inne werkstatt toros tunen gehen und selber nachschauen 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Erumeldor** [comment]
Hi @Tobias1496 ,
Das kommt dann leider so von GTA. Wenn die das Tuning in die falsche ID packen, zeigen wir das auch falsch an.
Können wir also nichts daran ändern
