### ISSUE TITLE
Versetzung eines Abladepunktes

### ISSUE THREAD

**Issue by HDCuba** [mexyn/statev_v2_issues#3544]
**Angelo_Peppers**

Hallo Zusammen,

ich würde gerne den Verladepunkt von der Metzgerei versetzen lassen, 
da sich die Anfahrt mit einem LKW + Achse erschwert und die Kommunikation
mit Kunden/Lieferanten sich einfacher gestaltet.

Folgendes Bild zeigt den Abladepunkt hinter der Firma wie es ist:

![Abladepunkt (ist)](https://github.com/user-attachments/assets/708bb90d-3896-4290-a78c-e35cfbc69be7)

Und hier wo es gewünscht wäre:
![Abladepunkt soll](https://github.com/user-attachments/assets/8a4928e3-c55e-4fdf-a295-1b79c9a1bdff)

Die Firma ist befindet sich:

Metzgerei Weide und Meer
Hash: pf_lamessa_8
Adresse: Popular Street 744

Gerne höre ich von euch. Danke im Voraus.

**Comment by SatyriaDine** [comment]
Ladepunkt ist zum nächsten Update auf den Parkstreifen rechts vom Firmeneingang verschoben. :)
