### ISSUE TITLE
Lifeinvader Verlikung nicht korrekt

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3545]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer
**Beobachtetes Verhalten**

Wenn man von einem Profil auf ein anderes Posted ist die verlinkung auf das andere über das Bild falsch.
Über den Namen ist der Link korrekt über das Profilbild jedoch nicht. Dort fehlt "id" im Link. (Normal "
**Erwartetes Verhalten**

Beides sollte aufs Profil führen
**Schritte um den Fehler nachvollziehen zu können**

Bild von einem aufs andere Profil posten und rumklicken

![image](https://github.com/user-attachments/assets/fe078207-59ac-46ae-9b04-be1c515843b9)
Man siehts hier auch, dass es fehlt

**Comment by rodistic** [comment]
Ist fixed
