### ISSUE TITLE
Fahrbahnmakierung entfernen an unseren Firmen abladepunkt.

### ISSUE THREAD

**Issue by DexterSnow** [mexyn/statev_v2_issues#3547]
Guten Abend liebes SupportetTeam. 
Wir haben folgendes Problem. Bei unseren Firmen ist der Abladepunkt so gesetzt das wir mit unserer Achse vorne und hinten an einer Roten Makierung stehen.
Es ist jetzt schon öfter vorgekommen das wir von den Cops aufgeschrieben worden sind weil wir dort stehen. 
Die letzte Strafe war ein Ticket über 50 $. 
Wäre es möglich an unserem Abladepunkt die roten Markierungen zu entfernen ? Mann könnte wenigstens die linke Makierung auf dem beigefügten Foto entfernen. 

Lg Dexter Snow & Richard Rheinland

https://pic.statev.de/i/HlSpKs.png

**Comment by simplycach** [comment]
Ist leider nicht möglich, aber euch fällt da sicherlich eine Lösung im RP ein.

**Comment by SHaagmann** [comment]
Naja ist ja auch nicht illegal da zu Parken...

![image](https://github.com/user-attachments/assets/2da39c27-2945-4a96-9101-80aa96948491)
