### ISSUE TITLE
Platzierbare Pflanzen schweben in der Luft

### ISSUE THREAD

**Issue by JB98989** [mexyn/statev_v2_issues#3548]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

David_Morgan

17.07.2024 // ca. 11:40

**Beobachtetes Verhalten**
Die Pflanzen Künstliche Kleine Palme und Künstliche Kleine Doppel-Palme nach dem Platzieren in der Luft. Habe sie beim Platzieren so tief wie möglich gemacht.

**Erwartetes Verhalten**
Pflanzen schweben nicht in der Luft nach dem Platzieren.

**Schritte um den Fehler nachvollziehen zu können**
Pflanzen versuchen zu Platzieren.

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/HlazPJ
https://pic.statev.de/image/Hlayu6

**Comment by TheOutburst** [comment]
Wir orientieren uns mit unserem Platziersystem an den Nullpunkten der GTA Entitys, diese sind in dem Fall nicht optimal, die Objekte sind aber dafür gedacht, dass man sie in andere Kübel steckt
Die Alternative wäre diese Pflanzen gänzlich raus zu nehmen, da sie aber einen Anwendungsbereich haben, wollten wir sie drin behalten
