### ISSUE TITLE
Dupen von aufstellbaren Items, wenn diese im Fahrzeug liegen

### ISSUE THREAD

**Issue by JB98989** [mexyn/statev_v2_issues#3549]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

David_Morgan

17.07.2024 // ca. 11:40

**Beobachtetes Verhalten**
Wenn man ein Aufstellbares Objekt aus einem Auto direkt aufstellt, ohne es ins eigen Inventar zu nehmen, dann wird diese aufgestellt, obwohl eine Fehlermeldung erscheint, jedoch nicht aus dem Auto genommen. Sollte man dies danach wieder aufnehmen, bekommt man das Item doppelt.

**Erwartetes Verhalten**
Item sollte aus Auto Inventar verschwinden.

**Schritte um den Fehler nachvollziehen zu können**
Siehe Video.

**Video / Bilder des Fehlers**
https://youtu.be/-jkhjYfvTmI

**Comment by QA-Pregon** [comment]
#3348
