### ISSUE TITLE
Hotel zuwenig Zimmer für die Größe

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#355]
Ich habe mir vor kurzem ein Hotel gekauft (600.000$), es hat 30 Zimmer.
Nun habe ich es mal mit anderen deutlich kleineren Hotels verglichen und die haben größtenteils mehr Zimmer als mein Riesen Brocken.
Daher bitte ich darum die Anzahl der Zimmer zu erhöhen.
Grüßle Bonsai

![hotel1](https://user-images.githubusercontent.com/70241137/99890718-7538b580-2c62-11eb-8922-bf4691b2a9d1.png)

![hotel2](https://user-images.githubusercontent.com/70241137/99890736-a5805400-2c62-11eb-858b-7ed406f0e373.png)

**Comment by DrGrizzlY17** [comment]
Erweitert
