### ISSUE TITLE
Abladepunkt versetzen

### ISSUE THREAD

**Issue by DannyLaker** [mexyn/statev_v2_issues#3550]
Danny Laker 
Firma: 🔥⚒️Die Schmiede⚒️🔥
Abladepunkt ist zu weit auf dem Gehweg.
Bitte setzt den Punkt weiter auf die Straße, da ich jedes mal den Hydranten und die Kisten umfahren muss.
![grafik](https://github.com/user-attachments/assets/f6bfe8f3-701b-4504-a593-eee83f6d723f)
![grafik](https://github.com/user-attachments/assets/a189de65-475b-42a5-ba5f-6121d491ccd7)

**Comment by Stoffel123** [comment]
Wurde verschoben. Have a nice Day
