### ISSUE TITLE
Erweiterung Garagenplätze

### ISSUE THREAD

**Issue by DannyLaker** [mexyn/statev_v2_issues#3551]
Danny Laker 
Ich bitte um Erweiterung der Garagenplätze, da ich ja eine riesige Garage (Scheune) habe. 
![grafik](https://github.com/user-attachments/assets/1c7fdd8f-4233-4f56-97d2-703a89c43003)
 
![grafik](https://github.com/user-attachments/assets/cee9e92e-4932-402f-833c-6cf3a043511a)

**Comment by TheOutburst** [comment]
Du hast 8 Garagenslots, hier passt alles

Hausgaragengröße an Vorhandensein einer Garage und Größe des Hauses angepasst (2 für Einfahrten oder Carports, 4 für Garagen, +2 für gr. 2, +4 für gr. 3)
