### ISSUE TITLE
Abladepunkt 

### ISSUE THREAD

**Issue by Asterix526** [mexyn/statev_v2_issues#3552]
Christian Big

Da an meiner Firma Bigs-Kraftstoffhandel(pf_davis_41)es zu Schwierigkeiten mit dem Aktuellen abladepunkt kommt bitte ich auf Wunsch von Kunden und meiner seits darum diesen Bitte zu ändern, am besten Mittig des Geländes. 

Mittlerweile sind auf dem Grundstück alle Firmen verkauft was dazu führt das große LKWs es kaum noch Schafen bei mir einzukaufen. 

Bild ist beigefügt. 
![IMG_20240718_104524](https://github.com/user-attachments/assets/3a0615fa-fa14-4e2a-a1b5-c46a0c47e8ed)

**Comment by Stoffel123** [comment]
Beim nächsten Update umgesetzt. Have a nice Day
