### ISSUE TITLE
Haus kann nicht betreten werden

### ISSUE THREAD

**Issue by Auralein** [mexyn/statev_v2_issues#3553]
Holly Swan

**Beobachtetes Verhalten**
Beim betreten des gemeinsamen Hauses kann ich nicht rein, weil das Interior nicht gefunden wurde.

**Erwartetes Verhalten**
Ich kann in das Haus, da das Haus bereits ein Interior hatte

**Schritte um den Fehler nachvollziehen zu können**
Haus als NICHT Besitzer betreten

**Optional: Video / Bilder des Fehlers**
![grafik](https://github.com/user-attachments/assets/1aeb7965-a1e1-4de1-a219-08135dcdfe12)

**Comment by rodistic** [comment]
Wem gehört da Haus?
Kannst du uns bitte den Haus Hash geben

**Comment by Auralein** [comment]
> Wem gehört da Haus? Kannst du uns bitte den Haus Hash geben

![349655905-1c7fdd8f-4233-4f56-97d2-703a89c43003](https://github.com/user-attachments/assets/2b3f3d21-accc-4e30-b21a-caf79ebf42a2)


Wir wohnen da zusammen drin, aber Danny ist die nächsten Tage nicht da. Somit käme ich auch nicht an meine Sachen ran =(

**Comment by rodistic** [comment]
sollte mit neusten Update fixo sein, bitte mal testen

**Comment by Auralein** [comment]
Meeega, funktioniert wieder - Dankeschön!

**Comment by rodistic** [comment]
@simplycach kann zu
