### ISSUE TITLE
Tattoo nach dem Stechen nicht Sichtbar (auch nicht wenn ich über das Laser Menü gehe)

### ISSUE THREAD

**Issue by CalebPapaCrane** [mexyn/statev_v2_issues#3555]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Caleb_Roberts

**Auftrittszeitpunkt (Datum / Uhrzeit)**
13:13

**Beobachtetes Verhalten**
Nach dem Stechen was das Tattoo nicht auf der Kundin, auch nicht im Menü zum lasern

**Erwartetes Verhalten**
Tattoo sollte d asein

**Schritte um den Fehler nachvollziehen zu können**
Tattoowieren und nach abschluss beobachten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
WQHD

**Optional: Video / Bilder des Fehlers**

**Comment by QA-Pregon** [comment]
Stand bei dir da, dass der Tattoovorgang abgeschlossen wurde nach erreichen der 100%?

**Comment by CalebPapaCrane** [comment]
Nein..

**Comment by QA-Pregon** [comment]
Hatte irgendwer zwischendurch einen Gamecrash oder gab es eine andere Meldung?

**Comment by QA-Pregon** [comment]
Seitdem nicht mehr gemeldet worden oder aufgefallen, wir machen erstmal zu
