### ISSUE TITLE
Versetzen Haus Teleport Punkt (Beim Haus verlassen)

### ISSUE THREAD

**Issue by v3rpl4nt** [mexyn/statev_v2_issues#3556]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

John Ellis

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Beobachtetes Verhalten**
Der Port Punkt um das Haus zu verlassen ist weit auf der Einfahrt. (Wie auf dem Bild zu erkennen)
Wenn möglich bitte den Port Punkt direkt zum Eingang umsetzen oder links von der Tür. (Siehe Bild)

**Erwartetes Verhalten**
Port Punkt anpassen :-)

**Schritte um den Fehler nachvollziehen zu können**
Ins Haus und wieder raus gehen 

![Uploading Port Punkt.jpg…]()

**Comment by v3rpl4nt** [comment]
Hash des Hauses: house_Paletobay_15

**Comment by Flachmeyer** [comment]
![20240718150925_1](https://github.com/user-attachments/assets/b98e3d4f-aff9-45fe-b916-9086788518a8)

**Comment by v3rpl4nt** [comment]
![Port Punkt](https://github.com/user-attachments/assets/a69fa066-f264-4aa1-a9df-7ba60f90180a)

Klappt das jetzt mit dem Bild :D

**Comment by Stoffel123** [comment]
Ist geändert zum nächsten Update
