### ISSUE TITLE
Hausumbau in Holz Loft 800kg Angegeben  sind aber nur 700kg 

### ISSUE THREAD

**Issue by Riccardo20240** [mexyn/statev_v2_issues#3558]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Riccardo gambino**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

Holz Loft umbau Hat nur 700 kg lager insgesammt

**Erwartetes Verhalten**

![Hausinventar](https://github.com/user-attachments/assets/ff23e1cc-902a-4df6-b3a7-c6022de394a8)
![Holz Loft](https://github.com/user-attachments/assets/aee485e9-9ec5-4860-b258-e339b0c866e3)
![Kleiderschrank](https://github.com/user-attachments/assets/8ed5226f-416d-438b-bad6-21f4553b0cf0)
![Kühlschrank](https://github.com/user-attachments/assets/6a78e1f3-9424-469e-9bde-5230cb3f6535)

**Optional: Video / Bilder des Fehlers**

**Comment by Riccardo20240** [comment]
![Hausinventar](https://github.com/user-attachments/assets/c4ae7c16-9a62-4f75-8ead-bfbfc0f3ceb9)

**Comment by Riccardo20240** [comment]
Danke schon mal im Vorraus

**Comment by Statev-Bonsai** [comment]
mein Holzloft hat 800kg... 450/250/100kg

**Comment by TheOutburst** [comment]
Hast du einmal deinen Haushash bitte?

**Comment by AlecAlexis** [comment]
Hab das selbe Problem 

HASH: house_Davis_54

**Comment by QA-Pregon** [comment]
Seems fixxed to me
Ist auf 700 gesetzt, steht so auch in der Beschreibung jetzt
