### ISSUE TITLE
Platzierte Möbel im Holzloft nicht aufnehmbar.

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3559]
Ich habe 3 Items plaziert und kann keines mehr aufheben...

**Comment by Flachmeyer** [comment]
Was hast du genau aufgestellt?

**Comment by Statev-Bonsai** [comment]
Ein Bett, Muff Sessel und einen Bonsai Baum

**Comment by Statev-Bonsai** [comment]
nach einem relog ging es jetzt.. komische sache
