### ISSUE TITLE
[F][U] Magic Corsage ruft crash mit zeitüberschreitung hervor

### ISSUE THREAD

**Issue by Hexenjaeger** [mexyn/statev_v2_issues#356]
**Leon_Unger**

**Zeitpunkt (Datum / Uhrzeit)**
 ‎Samstag, ‎21. ‎November ‎2020, ‏‎21:21:25 
**Beobachtetes Verhalten**
 beim kleidungsstück "( [F][U] Magic Corsage )" in den kofferraum ziehen ... crash mit "Zeitüberschreitung" 

**Erwartetes Verhalten**
 das es im kofferraum gelegt werden kann 

**Schritte um den Fehler nachvollziehen zu können**
 im kofferraum ziehen ...  bei 2 personen aufgetreten ca 5 mal 

**Optional: Video / Bilder des Fehlers**
https://youtu.be/cJyNmjQTXKU

**Comment by eiksch** [comment]
Der Fehler wurde seitens AVORO behoben. Wir benötigen kein Update, es sollte bereits wieder funktionieren.
