### ISSUE TITLE
Aufgestellte Items im Haus werden auf der Map angezeigt..

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3561]
Das finde ich etwas verwirrend, vielleicht Bug vielleicht ist es so gewollt ;D
Wenn es so gewollt ist wäre es Klasse wenn man Hausitems ausblenden könnte bzw sie gar nicht erst angezeigt werden.

 
![Screenshot_12](https://github.com/user-attachments/assets/d15d46fb-79e9-48a4-a147-aae752a47493)

**Comment by stepz2k9** [comment]
Du kannst die Items doch grundsätzlich ausblenden, oder geht es dir darum, die in der freien Welt angezeigt zu kriegen und die im Haus nicht?

**Comment by Statev-Bonsai** [comment]
Ich mein es genauso wie ich es geschrieben habe ;p ausblenden kommt nicht in frage für mich...
