### ISSUE TITLE
SAPD Funkgerät funktioniert nicht richtig

### ISSUE THREAD

**Issue by Dene87** [mexyn/statev_v2_issues#3562]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Jack Hopkins**

Jack Hopkins
**Auftrittszeitpunkt (Datum / Uhrzeit)**
Nach dem großem Update Abends im Dienst
Weitere SAPD Spieler haben wohl auch das gleiche Problem

**Beobachtetes Verhalten**
Mit U habe ich das Funkgerät herausgeholt und die Funkfrequenz gewechselt, konnte es danach nicht wieder mit U wegstecken. Ich konnte das Funkgerät erst wieder wegstecken nachdem ich ins Spiel geklickt habe.

**Erwartetes Verhalten**
Mit U Funkgerät herausholen, Funkfrequenz wechseln und mit U direkt wieder wegstecken.

**Schritte um den Fehler nachvollziehen zu können**
Mit U Funkgerät herausholen
Funkfrequenz ändern
Mit U Funkgerät wegstecken (geht nicht)
Einmal ins Spiel klicken
Mit U Funkgerät wegstecken ( jetzt geht es)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by QA-Pregon** [comment]
Also für mich ist es so komplett logisch, aber ich hinterfrag mal ob das geändert werden soll oder ob das so bleiben wird

**Comment by QA-Pregon** [comment]
Jo nach Absprache bleibt das wohl so
