### ISSUE TITLE
Türen im Apartmentinterieur nicht abgeschlossen

### ISSUE THREAD

**Issue by WalDragoner3425** [mexyn/statev_v2_issues#3563]
Hallo,
keine Ahnung ob das so gewollt ist aber wenn man sein Apartment im Hotel renoviert zur Ausstattung "Loft Braun" für nur 800$, sind innendrinnen die Türen nicht abgeschlossen, weswegen man das ganze riesige Büro betreten kann.
Da auf dem Vorschaubild nur ein kleiner Raum beworben wird und man hier ein größeres Interieur bekommt als beim teuersten Ausbau, denke ich mal dass ist nicht gewollt.

Was beworben wird:
![grafik](https://github.com/user-attachments/assets/50b13680-3864-458b-81fe-24d961ffc15a)

Was man bekommt:
![grafik](https://github.com/user-attachments/assets/5da52cc0-a4b8-40b9-93fc-3241a0b83bd6)

**Comment by TheOutburst** [comment]
Joa haben wir ma quick and dirty im GD gefixt, ist bisschen hässlich, aber tut seinen Job
