### ISSUE TITLE
Standard Apartmentinterieur nicht als Renovierungsmöglichkeit vorhanden

### ISSUE THREAD

**Issue by WalDragoner3425** [mexyn/statev_v2_issues#3564]
Hallo, 

aktuell ist es nicht möglich, das standard Interieur der Hotels/Apartments bei der Renovierung wieder auszuwählen nachdem man das Interieur gewechselt hat.
Ich weiß nicht ob das so gewollt ist aber falls ja finde ich es sehr schade, dass man die Ausstattung nicht wieder auf die standard Ausstattung zurücksetzen kann, wenn einem die neuen Interieurs nicht zusagen. Währe schön wenn das möglich wäre.

LG

**Comment by Eve-Noxito** [comment]
Da bin ich ganz bei dir. Hab unser Haus auch umgebaut, und das Interior war jetzt nich so pralle.. Auch die anderen find ich nich ganz so geil weil zBsp. Türen zum Bad und Schlafzimmer zu sind. Wäre echt super wenn man die Möglichkeit hätte die alten Standartinteriors auch auszuwählen

**Comment by Erumeldor** [comment]
Das ist tatsächlich kein Bug, sondern so gewollt.
Wir haben zum Update alles neu gemacht, und dabei auch ein paar Einrichtungen in andere Klassen verschoben.
Es ist einfach Unsinn in einem kleinen abgeranzten Haus eine 3 Stöckige Luxus-Einrichtung zu haben.
Wir haben das so realisiert, das wir die alten Häuser nicht in neue Interieurs zwingen, aber alle neuen und neu umgebauten bekommen nur noch die neue Auswahl.

**Comment by WalDragoner3425** [comment]
@Erumeldor Mir geht es nicht um Häuser. Ich habe ein kleines Hotel und wollte mir die anderen Einrichtungen mal anschauen ob davon vllt etwas besser passt.
Da aber die neuen Einrichtungen entweder kein Bad oder ein nicht so ansehnliches Bett haben oder es mir overall nicht gefällt, würde ich gerne zur alten Einrichtung wie auf dem hier beigefügten Bild zurückkehren, da diese Einreichtung ein schickes Bett hat, ein abgegrenztes Bad und overall ganz schick aussieht. Vielleicht kann man da ja nochmal bei Hotels drüber nachdenken, wüsste nicht was hier dagegensprechen sollte

![grafik](https://github.com/user-attachments/assets/eaf6577b-97de-4eb4-99b0-b643d0b99570)

**Comment by Erumeldor** [comment]
@WalDragoner3425 
Ah, hab ich überlesen. Verstehe.
Würde dich bitten das als Vorschlag im Discord aufzunehmen. Dann schauen wir mal, ob/was wir da machen könnten.

**Comment by WalDragoner3425** [comment]
Danke dir.
Was für ein Ticket soll ich diesbezüglich öffnen?

**Comment by simplycach** [comment]
Ist als Ticket offen, damit kann das hier zu.
