### ISSUE TITLE
Neue Nasen Piercings bei Frauen nicht Sichtbar, bei Männern nicht alle! :) 

### ISSUE THREAD

**Issue by CalebPapaCrane** [mexyn/statev_v2_issues#3567]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Caleb_Roberts

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12:50

**Beobachtetes Verhalten**
Man sieht ein paar der Piercings bei Männern nicht und bei Frauen sieht man die überhaupt nicht, also die neuen! :D
**Erwartetes Verhalten**

Naja, sichtbar eben! :D

**Schritte um den Fehler nachvollziehen zu können**
Einfach die Vorschau gucken! :)
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
WQHD

**Optional: Video / Bilder des Fehlers**

**Comment by simplycach** [comment]
Also geht es um die Vorschau oder wenn das gestochen wurde ?

**Comment by ySimbaa** [comment]
Also es gibt 4 neue Male Nasenpiercings, es kann sein das die bei den Frauen auch angezeigt werden, sind aber Male only. Daher bei Frauen gar nicht sichtbar.

Bei Nasenpiercings kann es aber auch dazu kommen, dass nicht jedes Piercing auf jedem Char passt. Da die Nasen durch Eltern und deren Einstellung so verschieden sind, gibt es das leider das einige Chars diese nicht sehen.

Ich kann z.B mit meinem Char die "alten" Piercings gar nicht nutzen, weil nicht Sichtbar auf der Nase meines Chars :)

**Comment by QA-Pregon** [comment]
Weiß gerade nicht ob aktuell schon drauf oder mitm nächsten Fix, aber auf jeden Fall wird da unterschieden mit Male oder Female
