### ISSUE TITLE
Spiel Stürtzt ab Bei Versuch Das Arpatment zu Betreten 

### ISSUE THREAD

**Issue by DeanHitch** [mexyn/statev_v2_issues#3568]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Dean Hitch**

**Auftrittszeitpunkt (19.07.2024 / 14:50)**

**Beobachtetes Verhalten**
<!Server Gibt diese Fehlermeldung Siehe Bild  >

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
<!--- 
![Screenshot 2024-07-19 144631](https://github.com/user-attachments/assets/beb867d4-9c18-469c-8f33-85e9bccff9c2)

**Comment by DeanHitch** [comment]
![Screenshot 2024-07-19 144631](https://github.com/user-attachments/assets/3f3cdba0-7ada-4576-a726-0a70f0129166)

**Comment by simplycach** [comment]
Bereits bekannt.
