### ISSUE TITLE
einlagerung in lager und firma 

### ISSUE THREAD

**Issue by Hexenjaeger** [mexyn/statev_v2_issues#357]
**Leon_Unger**

**Zeitpunkt (Datum / Uhrzeit)**
21.11.2020 rund 16 uhr

**Beobachtetes Verhalten**
man kann nur noch in die firma einlagern wenn man auch raus nehmen kann

**Erwartetes Verhalten**
wie früher einlagern ohne auslager rechte

**Comment by DrGrizzlY17** [comment]
Früher war much

**Comment by Hexenjaeger** [comment]
wow was das für ne antwort .. 

ein nein so wollen wir das nicht mehr wäre passender oder?? 
wir dachten es ist ein bug deswegen hier geschrieben worde.. früher war much .. fand ich nicht ..
have a nice day

**Comment by r3sist3nt** [comment]
Ich schau mir das mal an

**Comment by Hexenjaeger** [comment]
für leistungslohn firmen so wie es jetzt ist echt schwierig da in den lagern auch wertvolle sachen liegen ..

**Comment by its4l3x** [comment]
@Hexenjaeger Bitte genauere Details. Am Türmarker (über Fahrzeug, etc..)? Am Marker wo das Lager ist?

**Comment by DrGrizzlY17** [comment]
Also um das zu konkretisieren. Es geht hier um die Änderung im Rechtesystem für Firmen. @JulianMa

Früher war es möglich, per Fahrzeug in das Einzulager wenn man in der Firma nur das Recht "Ansehen".
Jetzt ist es so, das man dafür auch das "Bearbeiten" Recht.

**Comment by Hexenjaeger** [comment]
genau wie DrGrizzlY schreibt ..
früher musste man nur eingestellt sein mit ansehen rechte um einlagern zu können 
seit V² ist es so das man auch die Bearbeitungsrechte brauch
sprich man muss jetzt raus nehmen können um einlagern zu können.
was halt nicht immer machbar ist (vertrauen und co)

find ich persönlich ein rückschritt

**Comment by its4l3x** [comment]
Das System was du meinst @Hexenjaeger gibt es nicht mehr. Es ist mittlerweile ein 2in1 System. D.h. Hast du ein Fahrzeug auf dem UnloadingPoint (Ablademarker) und öffnest dein Türmenu kannst du nur noch Auf/Abschließen Betreten, Ankauf/Verkauf und das Lager öffnen. Mit dem Lager ist genau das gemeint. Wenn du auf Lager drückst öffnet sich das Inventar und du kannst Raus nehmen sowie reinnehmen. Daher ist das Bearbeitungsrecht auch notwendig unserer Meinung nach.

**Comment by Hexenjaeger** [comment]
wenn das so gewollt ist wäre ein log nicht schlecht
wer wann was raus genommen hat .
denn bei geteilten recht . sprich einlagerungsrecht    und rasnehmrecht
kann man als besitzer sagen ok den vertrau ich den nicht ..
jetzt ist es so entweder jeder darf alles oder nix..
nehmen wir an man hat im lager goldbarren. 
einer von den 15 leuten die man anstellen kann klaut die ..
schon haste keine gelegenheit mehr zu sagen ok kann nur der , der und der gewesen sein.
sprich wenn ich dann ne anzeige mache wegen diebstahl haste 15 namen und es verläuft sich im sand.
weil einfach zu viel ermitlung die ins nix geht .. 
hoffe ihr versteht das was ich sagen möchte ;-) 
aber wenn es genau so wie es ist gewollt ist dann müssen wir damit leben . sehen es aber als rückschritt an ...
wir haben ic ein weg gefunden passt vielen angestellten nicht aber he ist dann so ..

**Comment by its4l3x** [comment]
Deine Ansicht ist verständlich.

Wir nehmen uns deinen Vorschlag zu Herzen und notieren diesen mal.

Derzeit haben aber andere System prio. Hoffe das ist verständlich :D

**Comment by DonVitoDiangelo** [comment]
Wird nicht kommen.
