### ISSUE TITLE
Prison komische Fehlermeldung

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3571]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew_Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

19.07 18:50 oder so (Siehe video)
**Beobachtetes Verhalten**

Hab ne Fehlermeldung bei den Crime Missionen im Knast bekommen. 
**Erwartetes Verhalten**

Keine Fehlermeldung
**Schritte um den Fehler nachvollziehen zu können**

Crime mission starten und wundern warum das kommt. Dazu nicht immer reproduzierbar gewesen, da es irgendwann nicht mehr aufgeploppt ist
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://medal.tv/games/gta-v/clips/iiHxGonDDMwHQuWsg/d13378YnMyEv?invite=cr-MSxiMm4sMTk1NTEzMTMzLA

**Comment by simplycach** [comment]
Kam der Fehler nochmal bei dir vor ? Bisher lies es sich nicht reproduzieren.

**Comment by SHaagmann** [comment]
Kam bei mir bei 3 runden oder so vor danach nicht nochmal (hab n paar gemacht war 3,5h im prison)

**Comment by simplycach** [comment]
Ja gut, würde jetzt erstmal noch verbleiben, wenn es nochmal vorkommt einfach hier nochmal reinschreiben.
