### ISSUE TITLE
Casino Rad "Erneut drehen" = Restart

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3573]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Emilia_Stone / Andrew_Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

schön öfter letztes mal bei Emilia_Stone am 19.07 23:45
**Beobachtetes Verhalten**

Beim Glücksrad wurde "Erneut Drehen" gewonnen und man kann nicht drehen bis zu einem restart des games
**Erwartetes Verhalten**

Man kann direkt drehen
**Schritte um den Fehler nachvollziehen zu können**

Drehen und erneu drehen gewinnen.
Versuchen erneut zu drehen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TheOutburst** [comment]
durch deaktivierung von Glücksrad quasi solved, oder so ähnlich
