### ISSUE TITLE
Mystique Job 24/7 in Harmony liquor store

### ISSUE THREAD

**Issue by SgtTukiTukii** [mexyn/statev_v2_issues#3574]
Teresa_Martinez
20.07.2024 gegen 11.00 Uhr

Harmony liquor store gegenüber von Postal 706

Der Punkt am Tresor ist sehr schwierig zu triggern. Ich hab ihn zwar triggern können indem ich auf den Tresor geklettert bin und mich mit Ö fallen lassen habe, aber denke mal das ist nicht so der Sinn dahinter ;)

![HarmonyStore](https://github.com/user-attachments/assets/44426020-a0d4-4005-b120-8be7947b3422)

**Comment by Statev-Bonsai** [comment]
https://github.com/eiksch/statev_v3_issues/issues/3570

**Comment by simplycach** [comment]
Wurde bereits gemeldet.
