### ISSUE TITLE
UI Absturz bei Betreten eines Apartments

### ISSUE THREAD

**Issue by The-Qu3st** [mexyn/statev_v2_issues#3576]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Paul_Pinner

**Auftrittszeitpunkt (Datum / Uhrzeit)**

20.07.2024, 13:55 Uhr CEST

**Beobachtetes Verhalten**

Beim Versuch mein gemietetes Apartment über die Tür selbst (grüner Kreis) zu betreten, ist das UI abgestürzt

**Erwartetes Verhalten**

Betreten des Apartments bzw. Abfragefenster

**Schritte um den Fehler nachvollziehen zu können**

Gehe zu Apartment mit eigener Tür, drücke E

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

`
{"message":"Cannot read properties of undefined (reading 'split')","stack":"TypeError: Cannot read properties of undefined (reading 'split')\n    at BuilidingCellMenu (http://resource/client/ui/index.js:1175053:1928)\n    at renderWithHooks (http://resource/client/ui/index.js:13586:28)\n    at updateFunctionComponent (http://resource/client/ui/index.js:15974:30)\n    at beginWork (http://resource/client/ui/index.js:17280:24)\n    at beginWork$1 (http://resource/client/ui/index.js:21071:24)\n    at performUnitOfWork (http://resource/client/ui/index.js:20519:22)\n    at workLoopSync (http://resource/client/ui/index.js:20455:15)\n    at renderRootSync (http://resource/client/ui/index.js:20434:17)\n    at recoverFromConcurrentError (http://resource/client/ui/index.js:20056:30)\n    at performConcurrentWorkOnRoot (http://resource/client/ui/index.js:20004:32)"}
`

**Comment by simplycach** [comment]
Bereits bekannt.  Bitte über den Blauen Marker reingehen.
