### ISSUE TITLE
Abladepunkte Versetzen

### ISSUE THREAD

**Issue by ManuelLadner** [mexyn/statev_v2_issues#3577]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Jessika Jackson & Manuel Turner**

**jederzeit**

**abladepunkte für LKW zu nahe an den Firmen, wenn dann noch Autos auf den Parkplätzen stehen geht garnix mehr wenn man zbsp. mit einer Achse kommt!**

**wir bitten um Versetzung aller punkte in die Mitte des Parkplatzes sodass wir alle nur mehr einen haben! alle Firmenbesitzer sind fein damit! Wir wollten nicht 5 mal das selbe einreichen deswegen mache ich das für uns alle!**

**Zusammenfassen aller Abladepunkte, versetzen in die Mitte /am besten auf diese weiße dicke Linie am platz) und alle sind glücklich!**

**egal**

**https://ibb.co/f1Cyshx
https://ibb.co/ZWSGQPR
https://ibb.co/KzHQ471
https://ibb.co/TrtPqd3
https://ibb.co/6yjyTpm**

**Comment by Erumeldor** [comment]
Hi @ManuelLadner 
Punkte zusammenlegen tun wir nicht mehr. 
Wir könnten die Punkte alle etwas weiter in die Mitte, also weg von den Parkplätzen schieben, hilft euch das?

**Comment by Erumeldor** [comment]
Als Notiz für uns:
Eine andere Firma, selbes Gelände:
https://github.com/eiksch/statev_v3_issues/issues/3552

**Comment by ManuelLadner** [comment]
Toll wäre halt wenn auch wie bei Christian Bigs seiner Firma und Post die Abladepunkte mittig wären! wir kaufen auch grad Zugmaschine und Ölachse. Da wär das Perfekt wenn die da nach innen wandern! Wenn die nicht mehr zusammengelegt werden können dann halt hintereinander? Uns geht's eben um die großen Fahrzeuge die kaum rangieren können wenn da andere parken!
Die Gießerei von Rachel Parker gehört auch noch zu uns! Mit vielen Firmen wäre es top wenn die alle Mittig wären Erleichterung für alle die da ansässig sind!

**Comment by Erumeldor** [comment]
Yes, wir legen die Zeitnah alle in die Fahrmitte :)

**Comment by Stoffel123** [comment]
Alle Punkte wurden mittig verschoben, beim nächsten Update wird es für euch leichter. Have a nice day
