### ISSUE TITLE
T Shirts verschwunden

### ISSUE THREAD

**Issue by IxSHRNxI** [mexyn/statev_v2_issues#3578]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Ava Rise**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by IxSHRNxI** [comment]
Man hat ja die Möglichkeit zwischen das T Shirt in die Hose stecken oder nicht in die Hose stecken. Wenn man die zwei Option durch switcht gehen die T Shirts dabei verloren, also die sind einfach gone. Hab dadurch 2 T Shirts von DJ Birdsong verloren :( 

Passiert ist das ganze am 20.07.2024 zwischen 18 und 19 Uhr

**Comment by Enemyaa** [comment]
@IxSHRNxI Danke für die Info! Mach mal bitte ein Ticket auf, dann erstatte ich dir das.

**Comment by QA-Pregon** [comment]
Looks fixed to mee
