### ISSUE TITLE
UI Crash beim Wohnungsmarker & Kündigung von Apartment nicht möglich

### ISSUE THREAD

**Issue by ELPAJERO88** [mexyn/statev_v2_issues#3579]
**Character Name**
Dan_Kingston

**Auftrittszeitpunkt (Datum / Uhrzeit)**
20.07.2024 gegen 20 Uhr sowie zwischen 10 und 12 Uhr

**Beobachtetes Verhalten**
Wenn man auf den grünen Kreis seiner Wohnung mit E zugreifen will, erscheint Inventar Crash Fehler. Passierte nicht nur bei mir, sondern bei Luna_Holmes ebenfalls. Ihren Screenshot hab ich hochgeladen. Zudem geht bei der Apartment Übersicht die Kündigung nicht (PLZ 7010, nur Betreten und Aufschließen möglich). 

**Erwartetes Verhalten**
Ich wollte kündigen, ging jedoch über die blaue Übersicht nicht (ging nur Aufschließen & Betreten, aber nicht kündigen, ggf. weiterer Bug). Hab dann geschaut, ob es bei der Wohnung direkt geht, dann kam der Crash.

**Schritte um den Fehler nachvollziehen zu können**
Gehste zum grünen Kreis von ner Wohnung bei PLZ 7010 und drückst E

**Optional: Video / Bilder des Fehlers**
![Desktop_Screenshot_2024 07 20_-_20 05 35 21](https://github.com/user-attachments/assets/4cd04867-9d6d-4fa2-bd96-9dba8349248e)

**Comment by simplycach** [comment]
Bitte über den Blauen Marker reingehen, wir wissen schon bescheid.
