### ISSUE TITLE
Frisur nicht Änderbar mit Helm am Kopf

### ISSUE THREAD

**Issue by CoreForceee** [mexyn/statev_v2_issues#3582]
Name: Tim Bradford

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Beobachtetes Verhalten**
Wenn ich mit meiner Bildschrimauflösung einen Helm aufsetze dann kann ich die Haare darunter nicht Ändern wegen dem UI Zoom

**Erwartetes Verhalten**
Haare sollte man änderbar machen (UI Zoom)

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
2560 x 1600

**Optional: Video / Bilder des Fehlers**
<img width="1280" alt="Screenshot_6" src="https://github.com/user-attachments/assets/07b0f6d7-cefb-4e65-af84-159314e952d2">

**Comment by rodistic** [comment]
was passiert wenn du mit # die UI ausblendest?

**Comment by CoreForceee** [comment]
Man kann dann leider auch nichts ändern da das UI zwar ausgeblendet ist aber trotzdem darüber liegt

**Comment by simplycach** [comment]
Hey, da dies leider ein Edgecase ist können wir dort nichts machen.
