### ISSUE TITLE
Carlos gibt kein Auto sondern Fehlermeldung

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3584]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew_Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

21.07.2024 14:55
**Beobachtetes Verhalten**

Beim öffnen des Garagentors kommt eine Fehlermeldung
**Erwartetes Verhalten**

Man bekommt nen Auto
**Schritte um den Fehler nachvollziehen zu können**

Bei Carlos nen SUV bestellen und die Location bekommen im Video. Dann wundern, dass es nicht rauskommt
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://medal.tv/games/gta-v/clips/ijslU4Cly9MTDWhnw/d1337veo4NZK?invite=cr-MSxHanYsMTk1NTEzMTMzLA

**Comment by QA-Pregon** [comment]
Next update fixed
