### ISSUE TITLE
Crime Misson Bug Route 68 Maystic 

### ISSUE THREAD

**Issue by sandy02095530** [mexyn/statev_v2_issues#3585]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Jerome Hiltion 

Looten an den Roten Kreisen 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
15:55 21.07.2024

**Beobachtetes Verhalten**
Ich habe ein Mystic auftrag gemacht und mann kann denn einen Roten kreis nicht looten der am Safe ist 

**Erwartetes Verhalten**
mann sollte auch beim Roten Kreis Looten können wie auch bei alle andern roten kreisen 

**Schritte um den Fehler nachvollziehen zu können**
mann kommt nicht rann 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Comment by sandy02095530** [comment]
![Route 68  Mistyc Misson ](https://github.com/user-attachments/assets/ad37936e-2dcc-409a-b352-a08e27bb1257)

**Comment by SHaagmann** [comment]
Anscheinend doch nicht gefixed: #3570

**Comment by TheOutburst** [comment]
Marker in der Großen Mission wurd verschoben, in der kleinen aber (noch) nicht
Nächstes (bzw wegen altv update übernächstes) Update dann
