### ISSUE TITLE
Apartment Interieur "Loft Braun" unsichtbar

### ISSUE THREAD

**Issue by WalDragoner3425** [mexyn/statev_v2_issues#3586]
Hallo, 
seit heute ist das Apartment Interieur "Loft Braun" unsichtbar, wenn man es betritt. 
Gestern war alles noch normal. Habe auch mehrmals neugestartet aber hat sich nichts geändert.
LG

Wie es aussehen sollte:
![350342650-50b13680-3864-458b-81fe-24d961ffc15a](https://github.com/user-attachments/assets/79f6d5b3-4a29-4db2-9fe8-def9b6a059c1)

Wie es aussieht:
![grafik](https://github.com/user-attachments/assets/430f10c6-e6c3-40b4-b793-c349b649a6fb)

**Comment by Erumeldor** [comment]
Ist beim nächsten Update wieder fixed.
