### ISSUE TITLE
Haus mit Einfahrt hat keine Garage

### ISSUE THREAD

**Issue by Fishbone1992** [mexyn/statev_v2_issues#3588]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Patrick Fischer**

**22.07.2024 11:00 Uhr**

**Haus mit Einfahrt PLZ 4012 /  Hash house_EastLS_40  hat keine Garage.**

**Garage hinzufügen**

****

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot 2024-07-22 112509](https://github.com/user-attachments/assets/54493071-329a-4071-a117-4e3af3867624)

**Comment by TheOutburst** [comment]
Das ist keine Einfahrt, das ist nen Gehweg
Sorry, aber das Haus hat keine der Vorraussetzungen für ne Garage
