### ISSUE TITLE
Buccaneer Custom fehler bei Animation Auto schieben

### ISSUE THREAD

**Issue by PeterGlore** [mexyn/statev_v2_issues#359]
**Character Name**
Peter_Glore

**Zeitpunkt (Datum / Uhrzeit)**
21.11.20 gegen 19 Uhr 
22.11.20 gegen 1:50 Uhr

**Beobachtetes Verhalten**
Ich habe einfach mal ein Random Fahrzeug Buccaneer Custom mit den Animation (Fahrzeug schieben) schieben wollen.
Dann ist folgendes Passiert siehe Video 

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
[https://www.youtube.com/watch?v=FI5VqCJG27Y](url)
[https://www.youtube.com/watch?v=v1isXf2bTqc](url)

**Comment by DrGrizzlY17** [comment]
Changed

**Comment by PeterGlore** [comment]
[https://www.youtube.com/watch?v=hJVGwvjeviQ&feature=youtu.be](url)
Hier nochmals das gleiche einer anderen Person

**Comment by DonVitoDiangelo** [comment]
fixed next update
