### ISSUE TITLE
Explodierte Fahrzeuge haben nach Explosion und auslöse platte Reifen

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#3591]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Zane Kazee

**Auftrittszeitpunkt (Datum / Uhrzeit)**
mir bekannt immer

**Beobachtetes Verhalten**
Wenn ein Fahrzeug explodiert und eingeparkt wird, hat es nachdem man es in Davis abholt, platte reifen

**Erwartetes Verhalten**
Keine Platten reifen (Ein heiles Auto)

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by SHaagmann** [comment]
Gleiche wie bei #3146

**Comment by TheOutburst** [comment]
@simplycach Fehler besteht weiterhin

**Comment by QA-Pregon** [comment]
Ich nehm Duplicate mal raus, weil um neuöffnung gebeten wurde im alten Tracker

**Comment by Erumeldor** [comment]
Sollte fixed sein
