### ISSUE TITLE
Fehlermeldung beim Verschieben von einer Leggins in den Kleiderschrank

### ISSUE THREAD

**Issue by xpepperann** [mexyn/statev_v2_issues#3592]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Kiara Jones

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.07.2024 16:20 Uhr

**Beobachtetes Verhalten**
Jedes Mal wenn ich die [F] Black Cute Leggins in den Kleiderschrank packen möchte, erhalte ich die Fehlermeldung "Das geht hier nicht rein!" 

**Erwartetes Verhalten**
Leggins sollte in den Kleiderschrank gepackt werden können. 

![GTA5 2024-07-23 16-18-00](https://github.com/user-attachments/assets/2365157e-2e28-447e-88d6-e7e1a45dd714)

**Comment by TheOutburst** [comment]
next update fixed
