### ISSUE TITLE
Kann nicht mehr auf die SMS einer bestimmten Nummer zugreifen.

### ISSUE THREAD

**Issue by Shazgul** [mexyn/statev_v2_issues#3593]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Cady Young

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit heute, dem 23.07.2024

**Beobachtetes Verhalten**
![image](https://github.com/user-attachments/assets/e626ac08-2281-45ce-b79e-82b9de430c8b)

**Erwartetes Verhalten**
Zugriff, kein Server Error.

**Schritte um den Fehler nachvollziehen zu können**
Weder per vnet.statev.de / per Tablet IC / per Handy IC öffnet sich die SMS Funktion der Nummer: **1822-18999889**

**Comment by Tobse1904** [comment]
Das gleiche Problem habe ich auch seit gestern, von jetzt auf gleich kein zugriff mehr auf SMS Funktion, anrufen und angerufen werden klappt alles wunderbar nur SMS Funktion nicht.

**Comment by simplycach** [comment]
Immer noch so ?

**Comment by Tobse1904** [comment]
Hey , sorry das ich mich erst jetzt melde, Problem ist behoben. klappt aktuell wieder alles. Danke <3
