### ISSUE TITLE
Entfernen von Objekten

### ISSUE THREAD

**Issue by MaliDikembe** [mexyn/statev_v2_issues#3595]
Mali_Dikembe

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.07.24

In unseren garten vom haus stehen 2 "schrottautos"
Wäre es möglich diese zu entfernen?

![garten1](https://github.com/user-attachments/assets/3901f610-8bd2-481f-aba0-7ecbc483df02)

![haus1 ](https://github.com/user-attachments/assets/49177673-6cd3-46c8-964f-9475ba50d265)

**Comment by SatyriaDine** [comment]
Wir entfernen grundsätzlich keine Objekte mehr.
