### ISSUE TITLE
Sehe das umgebaut Hotellzimmer nicht

### ISSUE THREAD

**Issue by Quarkbaelchen** [mexyn/statev_v2_issues#3596]
**Character Name**

Mina Cruz

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Am 23.07.2024 um 23:06 Uhr

**Beobachtetes Verhalten**

Mein Charakter steht in der Luft nach dem Umbau vom Hotelzimmer

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/user-attachments/assets/1445de0e-d247-4c21-a4b7-bc88870e4769)

**Comment by SHaagmann** [comment]
Duplikat: #3586
