### ISSUE TITLE
Fehler beim herstellen Teppich

### ISSUE THREAD

**Issue by JasminHarper** [mexyn/statev_v2_issues#3597]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Josefine_Miley

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.07.2024 ca- 23:17 Uhr

**Beobachtetes Verhalten**
Verpackter großer Teppich, Verpackter Teppich & Verpackte kleiner Teppich lassen sich nicht in der Weberei herstellen, Fehler im Screen zusehen. 

**Erwartetes Verhalten**
Teppich herstellbar

![teppich](https://github.com/user-attachments/assets/1bc56356-c0f1-4a00-ab98-48ae7f4c413a)

**Optional: Video / Bilder des Fehlers**

**Comment by TheOutburst** [comment]
nächstes Update ists gefixt, danke fürs melden
