### ISSUE TITLE
E-Mail Empfänger Probleme

### ISSUE THREAD

**Issue by Auralein** [mexyn/statev_v2_issues#3598]
Holly Swan

**Beobachtetes Verhalten**
Wenn man manchmal während einer Unterhaltung per E-Mail auf Antworten geht, verschwindet manchmal der Empfänger und es ist nicht möglich diesen nachzutragen

**Erwartetes Verhalten**
Empfänger bleibt bestehen

**Schritte um den Fehler nachvollziehen zu können**
Ja, E-Mail's schreiben :x keine Ahnung woran das lag.

**Optional: Video / Bilder des Fehlers**
![grafik](https://github.com/user-attachments/assets/093164fc-afc2-4cc7-9746-0b9d0d31e510)

**Comment by simplycach** [comment]
Ist das immer noch broke ?

**Comment by QA-Pregon** [comment]
@Auralein ?

**Comment by Auralein** [comment]
Hallo, ich hatte das 2x gehabt aber weiß nicht was das provoziert hat... vllt die Dauer der Antwort? Ich weiß es leider nicht

**Comment by simplycach** [comment]
Mhm, dann würden wir das erstmal closen, wenn du es nochmal hast, vielleicht magst du dann nen Video machen, bei manchen Programmen kann man das ja rückwirkend.
