### ISSUE TITLE
Fehler bei Herstellung von packagedDogBowl

### ISSUE THREAD

**Issue by NitMitDir** [mexyn/statev_v2_issues#3599]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Eric_Ludwig**

**24.07.2024 16:41 UHR**

**Fehler in der Konfiguration der Produktion (in ROT) erscheint unten über der Karte nachdem man die Produktion von packagedDogBowl starten möchte **

**Maschine startet Produktion**

**Gehe zu einer Fertigung lade 5 Kilo Quarzsand 8 Porzelanerde 5 Sack Kunststoffgranulat und 1 Pappe in die Maschine. 
Gehe zum Comuter um die Produktion zu starten nach packagedDogBowl suchen und auswählen und nun Produktion starten drücken.**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot (116)](https://github.com/user-attachments/assets/708e5b76-7f85-4560-b999-f74fb42beb33)

**Comment by AdmiralState** [comment]
Konnte es nicht reproduzieren, bei mir hat es geklappt. Bitte beobachten und ggf. nochmal hier reinschreiben

**Comment by NitMitDir** [comment]
Problem besteht weiterhin

**Comment by TheOutburst** [comment]
ist next update fixed, deswegen konnte Admiral es nicht reproduzieren :D
