### ISSUE TITLE
LSMD Ausweis Rang nicht zentriert

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#36]
**Zeitpunkt (Datum / Uhrzeit)**
25.08.2020 21:20 Uhr

**Beobachtetes Verhalten**
Auf dem Ausweis ist der Rang Text nicht zentriert

**Erwartetes Verhalten**
Sollte zentriert sein

**Schritte um den Fehler nachvollziehen zu können**
Ausweis anzeigen

**Optional: Video / Bilder des Fehlers**
![3d30440ff413509dff3e802feac40ed5](https://user-images.githubusercontent.com/70150988/91218145-f1c9ff80-e718-11ea-97fb-e1026b34278e.png)

**Comment by its4l3x** [comment]
Ist alles in einer Reihe, schließe es, da kein richtiger "bug"
