### ISSUE TITLE
Ladestand im Tablet bei E-Autos falsch

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#360]
**Beobachtetes Verhalten**
Im StateNET wird bei E-Autos noch die Literanzahl angezeigt.

**Erwartetes Verhalten**
Ladestand vom E-Auto wird angezeigt

**Schritte um den Fehler nachvollziehen zu können**
StateNET aufrufen und E-Auto anschauen.

**Optional: Video / Bilder des Fehlers**
![emUEi1V](https://user-images.githubusercontent.com/33394632/99891245-1413e080-2c68-11eb-906f-fcd22afc7ef8.png)

**Comment by its4l3x** [comment]
Fixed. Next Update.
