### ISSUE TITLE
house_EastLS_3

### ISSUE THREAD

**Issue by LoganHatherway** [mexyn/statev_v2_issues#3600]
Logan Hatherway

Hey, 

ich sollte hier was schreiben bezüglich einer gewünschten Garage für mein Haus das wäre die "house_EastLS_3".

**Comment by Stoffel123** [comment]
Guten Abend, ich habe das Gelände geprüft und es entspricht nicht den Anforderungen für eine Garage.

**Comment by LoganHatherway** [comment]
Hey, aber das Haus daneben hat doch auch eine Garage? Verstehe das problem nicht ganz

**Comment by Erumeldor** [comment]
Dein Haus hat kein Carport oder Garage, und auch keine dazugehörige Auffahrt. 
Sorry, aber da ist einfach nirgends etwas, was als Garage in Frage kommt.

**Comment by LoganHatherway** [comment]
Verständlich dann erkläre mir aber bitte wieso dieses Haus https://gyazo.com/5f4d4350a0f65c57017450c139b12065 eine Garage hat.

Und meins https://gyazo.com/c197d41eda0061ff6684892f0c27d0a9 dann keins bekommt. Kann man  nicht einfach bei unseren Garagen hier https://gyazo.com/2b3c470efae3ebaa62364ab678dfc042 nen ausparkpunkt machen?

**Comment by Erumeldor** [comment]
Weil das Haus daneben einen klar definierten Stellplatz hat. Da ist Platz für eine "Garage".

**Comment by Erumeldor** [comment]
Und du hast es vor dem Hauskauf klar erkennen können, das da kein Parkplatz, Auffahrt, Carport oder Garage ist.
