### ISSUE TITLE
Fahrzeug nach 12 Uhr Restart in Autohaus Garage eingeparkt

### ISSUE THREAD

**Issue by Salkin1903** [mexyn/statev_v2_issues#3602]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Raymond Smith**

*24.07.24 12:05 Uhr**

**Beobachtetes Verhalten**
Fahrzeug SA-RS-99 ein Bravado Rumpo Custom wurde automatisch in das Autohaus eingeparkt in dem es überschrieben wurde.
Das Überschreiben ist bereits zwei Monate her und war im Mai gewesen, seitdem wurde das Fahrzeug öfter in eine öffentliche Garage eingeparkt.

**Erwartetes Verhalten**
Fahrzeug wird, wenn zu wenig bewegt in die nächstgelegene öffentliche Garage eingeparkt

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug in Autohaus überschreiben und in eine öffentliche Garage einparken, dann wieder ausparken und überprüfen, wo das Fahrzeug eingeparkt wird bei dem Serverrestart.

**Comment by simplycach** [comment]
Bitte ein Ticket aufmachen, das muss manuell angepasst werden bei Fahrzeugen vor dem letzten großen Update.
