### ISSUE TITLE
Autohaus Fahrzeuge werden teilweise in der öffentlichen Garage eingeparkt

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#3603]
![image](https://github.com/user-attachments/assets/711f06b2-a7cf-4490-b3e4-25574f456710)

Fahrzeuge sind auf dem PDM Autohaus #carShop4 angemeldet und landen in der Garage Unicorn Garage. Nicht alle und nicht immer. Kann das nicht wirklich reproduzieren

**Comment by QA-Pregon** [comment]
Wie oft ist das vorgekommen?
Mit welchen Fahrzeugen ist das vorgekommen?
Wenn du hast, wann genau für welches Fahrzeug exakt?

Oder war es nur mit dem Fahrrad immer?

@epichalt

**Comment by epichalt** [comment]
![image](https://github.com/user-attachments/assets/adb8b4fa-1de4-424c-b3f7-377ffc95b8d3)
die zwei Fahrzeuge aktuell @Pregon

**Comment by QA-Pregon** [comment]
Standen die im Autohaus oder wo anders?

**Comment by epichalt** [comment]
> Standen die im Autohaus oder wo anders?

die standen im Autohaus

**Comment by QA-Pregon** [comment]
wie oft seitdem aufgetreten?

**Comment by Auralein** [comment]
Bei uns ist das auch so.

![grafik](https://github.com/user-attachments/assets/264e704f-537d-4b54-b549-995c1050c8c7)

Allerdings betriftt es in dem Fall ein Auto, dass NICHT neu gebaut wurde und einen Vorbesitzer hatte. Ist zwar trotzdem auf das Autohaus geschrieben, aber denke das es damit zusammenhängt.

**Comment by QA-Pregon** [comment]
Sollte fixxed sein, ansonsten nochmal aufmachen
