### ISSUE TITLE
Shopraub Harmony fehlerhaft

### ISSUE THREAD

**Issue by 2FaceOriginal** [mexyn/statev_v2_issues#3604]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Dre_Cones
**Auftrittszeitpunkt (Datum / Uhrzeit)**

-
**Beobachtetes Verhalten**

Es passiert nichts wenn ich versuche mit dem punkt hinten am Tresor zu interagieren.
**Erwartetes Verhalten**

shop wird ausgeraubt
**Schritte um den Fehler nachvollziehen zu können**

-
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

-
**Optional: Video / Bilder des Fehlers**

![Bild_2024-07-25_151956346](https://github.com/user-attachments/assets/9aee1bec-62b9-48f8-9d29-9ab8bda14385)

![Bild_2024-07-25_151940388](https://github.com/user-attachments/assets/c97e29e8-da55-449c-81e0-0248ff93e3c2)

**Comment by SHaagmann** [comment]
#3585

**Comment by TheOutburst** [comment]
wie im anderen tracker geschrieben, next update fixed
