### ISSUE TITLE
Magazin Erweiterung nach neuem log in.

### ISSUE THREAD

**Issue by Keemobi** [mexyn/statev_v2_issues#3606]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Jarvis_Gorman**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.07.2024 um 10:00

**Beobachtetes Verhalten**
Ich bin eingeloggt und hatte zuvor den Tag eine PSP Pistole mit einer Magazin Erweiterung equiped gehabt.
Als ich heute (am nächsten Tag) einloggte. War das erweiterte Magazin nicht mehr Sichtbar hatte in der Anzeige aber dafür ein
2tes Magazin nachgeladen. (In der Anzeige stand 6/6. Anstatt 12/0)

**Erwartetes Verhalten**
Normal sollte es ja so sein das, dass erweiterte Magazin genau so vorhanden sein sollte auch wenn man reloggen sollte.

**Schritte um den Fehler nachvollziehen zu können**
Schritte
- PSP mit Magazin Erweiterung ausrüsten und ein Magazin reinladen.
- Ausloggen
- wieder einloggen
- Dann sollte der Fehler auftauchen und sichtbar sein

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
Ich spiele ganz normale 1920x1080 auf 16:9 Resolution

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/user-attachments/assets/3cd7c44e-e6e7-4f73-bac8-bccdc91a4b7a)

Magazin Erweiterung auch nicht visualisiert.
![image](https://github.com/user-attachments/assets/3f61fc54-49d7-434d-b2f7-9746752711e4)

nach dem neu ausstatten funktioniert wieder alles normal.
![image](https://github.com/user-attachments/assets/6d7371c1-95b4-47f8-839b-d771979f4867)

**Comment by QA-Pregon** [comment]
Next Update
