### ISSUE TITLE
Garage für Haus house_SandyShores_73

### ISSUE THREAD

**Issue by ghost** [mexyn/statev_v2_issues#3607]
Hi, 

wie der Titel schon sagt, hätte ich gerne rechts neben dem Haus **house_SandyShores_73** einen Garagenstellplatz für 1 Fahrzeug.

![bild](https://github.com/user-attachments/assets/5f6dfda8-264f-4371-a285-a146c7a538fd)

Danke und Grüße

**Comment by Stoffel123** [comment]
Ich habe mir das Gründstück angeschaut und es entspricht nicht den Anforderungen für eine Garage. Ich muss daher die Anfrage leider ablehnen.
