### ISSUE TITLE
Autos nach automatischen einparken in Hausgaragen..

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3608]
Wenn beim Restart automatisch Autos in die Hausgarage einparkt sind sie nach dem ausparken mal auf oder abgeschlossen.
Wäre Klasse wenn sie immer abgeschlossen ausgeparkt werden und nicht mal so oder so...

**Comment by Statev-Bonsai** [comment]
nachtrag: mal ist auch der motor auch an..
wäre echt klasse wenn alle autos beim automatischen einparken den gleichen status haben (verschlossen/motor aus)...

**Comment by QA-Pregon** [comment]
Die werden so in die Garage abgestellt, wie sie auch hinterlassen worden aufm Live.
Das ist auch so geplant --> Feature
