### ISSUE TITLE
Baumarkt Ladentheke

### ISSUE THREAD

**Issue by adrosso** [mexyn/statev_v2_issues#3609]
Guten Tag,

wir würden gerne Anfragen, ob es möglich wäre für YouTool (DIY_BC_1) bzw. für alle Baumärkte eine größere Ladentheke zu bekommen.

Wir haben Aktuell das Problem, dass wir nicht alle Artikel in außreichender Anzahl anbieten können, ohne das uns der Platz ausgeht.
Wir müssen uns entweder auf eine große Auswahl von Artikel beschränken, oder aber mit relativ kleiner Stückzahl (3-5 pro Artikel) den Laden bestücken. Da Werkzeuge natürlich sehr gut gekauft wird, können wir diese Stück zahl nicht Reduzieren, sonst müsste man am Tag min. 4x auffüllen.

Durch das letzte Update und die neu hinzugefügten Artikel, hat sich das vorhandene Problem nur weiter verschärft.

Über eine positive Rückmeldung würde ich mich freuen. 

Lg

Isaac Reed

**Comment by TheOutburst** [comment]
Next update sind alle 247 subtypen von der Lager & Thekengröße gerade gezogen, damit hat der Baumarkt ein wenig mehr Lagerplatz.
