### ISSUE TITLE
Auto Werkstatt - Gehalt wird nicht überwiesen / verbuggt

### ISSUE THREAD

**Issue by GeneraLGomora** [mexyn/statev_v2_issues#361]
**Seal_Brown**

**Zeitpunkt (Datum / Uhrzeit)**

Beobachtet - seit Samtag 21.11.2020 

**Beobachtetes Verhalten**

Ich schreibe in Namen der Mitarbeiter der Werkstatt "NORTH Workshop"
Wir haben ein Problem mit dem **Gehalt System**. Also keiner der Mitarbeiter bekommt nachdem er eingestempelt ist seinen Gehalt. 

Vielen Dank. LG
Seal

**Comment by BlackyGER** [comment]
Dem kann ich mich so anschließen, Horizon Hottest Engines hat das gleiche Problem.

**Comment by Solomonetix** [comment]
Kann ich als Mitarbeiter auch bestätigen. Bekomme kein Gehalt.

**Comment by Solomonetix** [comment]
/push
wäre schön , wenn ein Angestellter endlich mal wieder  Gehalt bekommen würde!

**Comment by MrFluffig** [comment]
Also ich finde neue fetures zu entwickeln immer super! Aber... mehrere hunderte Firmen auf StateV können ihren MItarbeitern kein Stundenlohn bezahlen, das ist ein kritischer bug um den sich schnellstmöglich gekümmert werden sollte, ohne das böse zu meinen.

**Comment by its4l3x** [comment]
Hi @Solomonetix @MrFluffig ,

Der Bug war so wie auf unserer Prio-Liste ganz weit oben. Nun mal müsst ihr bitte bedenken, dass nur eine limitierte Anzahl an DEV's bei uns im Team auch auf dem Gamserver tätig sind.

Sowie bitte bedenkt auch, dass wir das freiwillig tuen und dafür kein Geld o.Ä. erhalten. Wir haben nun mal auch ein RL, Arbeit, sowie Frau/Freundin/Familie, welche nun mal mehr Prio als StateV hat. 

Bitte habt dafür Verständnis.

Außerdem, Bug bereits gefixed siet dem 29.12.20 => https://statev.de/forum/list/index.php?thread/11753-v2-0-26-29-12-2020/
|
-> [Fix] Gehalt bei Fabriken

Vielen Dank.

Alex
