### ISSUE TITLE
Fehler Mettallplatte im Prison

### ISSUE THREAD

**Issue by Stoffel123** [mexyn/statev_v2_issues#3610]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Dean Kipling

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.07.2024 um 00:23 Uhr

**Beobachtetes Verhalten**
Ich wollte eine Metallplatte im Prison zerschneiden und bekam 
![grafik](https://github.com/user-attachments/assets/5afe151e-fad8-4e23-9abb-5fad6db39afc)
Die Metallplatte bleibt erhalten

**Erwartetes Verhalten**
Ich bekomme 2x geschnittene Metallplatte

**Schritte um den Fehler nachvollziehen zu können**
1x Metallplatte setzten an die Metallschneide im Prison gehen und E drücken

**Comment by Stoffel123** [comment]
Nach mehrmaligen Test hat es funktioniert. Aber bei dem Fehler bleibt das Item, eventuell sollte es dabei kaputt gehen?

**Comment by TheOutburst** [comment]
Der Fehler kommt, weil weder im Lager noch in deinem Inventar Platz für das Item ist.

Sollte next update nichtmehr vor kommen, hab das Gewicht von Geschnittene Metallplatte verringert, war Physikalisch eh nicht möglich, das Gewicht durch zerschneiden zu erhöhen.
