### ISSUE TITLE
2 Skills in einer Reihe

### ISSUE THREAD

**Issue by DEHUNTER58711** [mexyn/statev_v2_issues#3611]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Sergei Popov

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.07.2024 14:25 Uhr

**Beobachtetes Verhalten**
2 Skills in einer Reihe

**Erwartetes Verhalten**
Nur 1 Skill pro Reihe

**Schritte um den Fehler nachvollziehen zu können**
Keine Ahnung, ich konnte es aufeinaml lernen. Ich habe zuvor den Busfahrer Skill "entlernt" das war aber ein Tag vorher bereits der Fall.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
-

**Optional: Video / Bilder des Fehlers**
![grafik](https://github.com/user-attachments/assets/00db14bd-e675-494c-b1ef-f75a6c06a7d5)

Es soll bitte das Blumenkind erhalten bleiben, ich hab das nur zum Test gemacht weil ich gesehen habe dass das System er zulässt und wollte es nur wissen, daher auch der Report dazu. Ich werde den Minenarbeteiter nicht Skillen in dem ich in der MIne arbeiten gehe um keine Vorteile auszunutzen.

**Comment by DEHUNTER58711** [comment]
mir wurde gerade gesteckt, das man auch nach dem Update 2 Skills lernen kann. Stimmt das? Ich war zum großen Update nicht da. Falls das stimmt, muss die UI angepasst werden.

**Comment by SatyriaDine** [comment]
Ja das stimmt so, seit dem letzten großen Update sind 2 Skills bei Farming pro Reihe möglich

**Comment by DEHUNTER58711** [comment]
ahh ok danke. Ja dann kann man das wieder zu machen. Upsi
