### ISSUE TITLE
Bewusstlos  Handy und Tablet benutzbar 

### ISSUE THREAD

**Issue by Naloxio** [mexyn/statev_v2_issues#3613]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Andrew_Jackson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
28.07.2024 12:50-13:20

**Beobachtetes Verhalten**
war Bewusstlos und hätte konnte Handy benutzten und hätte Notruf absetzen können 

**Erwartetes Verhalten**
Das Handy Tablet nicht benutzen

**Comment by simplycach** [comment]
Nächst Update fixed
