### ISSUE TITLE
Abladepunkt versetzen

### ISSUE THREAD

**Issue by ManisBauer** [mexyn/statev_v2_issues#3615]
Guten Tag.

Charakter Name Manis Bauer

![image](https://github.com/user-attachments/assets/687753af-a0f3-4938-abe3-318ff1ac6f87)

Der Abladepunkt befindet sich momentan extrem weit weg vom Firmeneingang und ich würde es begrüßen, wenn dieser wie bei den Nachbarfirmen in eine etwas relevantere Entfernung gebracht werden könnte.

![image](https://github.com/user-attachments/assets/e3f5c961-9f68-4dd4-8e19-e2d5ec6df185)

![image](https://github.com/user-attachments/assets/fd4c7a5d-e0df-4080-825a-f59738b8b655)

![image](https://github.com/user-attachments/assets/b44989c7-190f-4fe6-841c-112b94465974)

Begrüßen würde ich es, wenn er hier hin käme

![image](https://github.com/user-attachments/assets/642f768d-8981-4842-8be0-6b145c13ccd2)

Aber auch wie bei den Nachbarläden direkt davor wäre in Ordnung.

![image](https://github.com/user-attachments/assets/b02d6254-69e9-4307-92a3-9cedb7c13db6)

Kunden müssen halt ihr Fahrzeug offen lassen, wärend Sie einmal um den Block rennen um zu An oder zu Verkaufen.

Lg Manis Bauer

**Comment by SatyriaDine** [comment]
Ladepunkt ist zum nächsten Update ein paar Meter versetzt. :)

**Comment by ManisBauer** [comment]
Vilen Dank für die wirklich schnelle Bearbeitung!
