### ISSUE TITLE
Racing Bestenliste Falschherum Sortiert

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3616]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew_Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

28.07
**Beobachtetes Verhalten**

Die bestenliste für die Große Observatorium Strecke zeigt die langsamste Zeit als Platz 1 an
**Erwartetes Verhalten**

Schnellste sollte Platz 1 sein
**Schritte um den Fehler nachvollziehen zu können**

Bestenliste auf all stellen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/user-attachments/assets/a292cb41-5047-44a4-b115-b2bc2b0f058b)

**Comment by QA-Pregon** [comment]
Bereits gefixed, is auf jeder Strecke so, wir warten nur aufn nächsten Hotfix, damit es rein kann
