### ISSUE TITLE
Bus Job Paleto - Defekte Busse

### ISSUE THREAD

**Issue by Cortain** [mexyn/statev_v2_issues#3617]
**Character Name**
Mike Fisher

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.7.
28.7

**Beobachtetes Verhalten**
Bus Job in Paleto mit den Escalera Fahrzeugen, sind in den letzten tagen alle bis auf eines defekt und liegen teilweise kreu und quer. Ich vermute, dass sie nicht korrekt gespawnt werden.

**Erwartetes Verhalten**
Busse stehen ordentlich und heil.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1080P

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/user-attachments/assets/7e717de1-86c3-45a6-96d5-e9d6dea50527)

**Comment by QA-Pregon** [comment]
Ist das seitdem erneut aufgetreten?

**Comment by QA-Pregon** [comment]
Sollte in Update 3.2.5 überarbeitet geworden sein
