### ISSUE TITLE
Bus Job - Reparatur Point funktioniert manchmal nicht

### ISSUE THREAD

**Issue by Cortain** [mexyn/statev_v2_issues#3618]
**Character Name**
Mike Fisher

**Auftrittszeitpunkt (Datum / Uhrzeit)**
vorher nicht notiert
28.07. 21:45

**Beobachtetes Verhalten**
Fahre auf den Rep Point und löse ihn aus, das Fenster was erscheinen soll ist defekt und es passiert nichts.
Bisher aufgetreten in Paleto und bei 5043
Tritt nur sporadisch auf

**Erwartetes Verhalten**
Bus wird getankt und repariert

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/user-attachments/assets/25df72b7-055b-46e6-938e-020b1c970ed1)

**Comment by QA-Pregon** [comment]
Gibt es dabei irgendeine Art von Fehlermeldung oder passiert gar nichts wenn du 'E' drückst?

**Comment by JensGamerBoy** [comment]
Ich kann es bestätigen durch mein Bruder er kann sein Bus auch nie reparieren oder sonstiges es passiert einfach garnichts

**Comment by Cortain** [comment]
Die Meldung die erscheinen sollte erscheint nicht und sieht so aus wie auf dem Screenshot.

**Comment by QA-Pregon** [comment]
Wie oft kam das bei euch seitdem vor? @Cortain @JensGamerBoy

**Comment by QA-Pregon** [comment]
Da keine Antwort mehr kam und es auch kein neuen Eintrag dazu gibt mach ich erstmal zu.
Falls es nochmal aufkommt am besten mit Clip oder F8 neu aufmachen
