### ISSUE TITLE
Klebeband Noch drauf nach Ausparken

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3619]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew_Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

28.07 ca. 22 Uhr
**Beobachtetes Verhalten**

Heute MIttag habe ich Klebeband auf das Kennzeichen meines S2s geklebt (Kennzeichen SA-O2-JA). Nachdem ich das Fahrzeug einmal eingeparkt hatte wegen eines versehentlichen Scheibeneinschlages war das Kennzeichen wieder zu sehen.

Ich wollte es soeben mehrere Stunden später wieder abkleben und hatte ne Fehlermeldung bekommen
**Erwartetes Verhalten**

Keine Fehlermeldung und Kennzeichen ist noch weiterhin abgeklebt (Vllt endlich mal ne Funktion wie man den Kleber selber aktiv entfernen kann <3)
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://medal.tv/games/gta-v/clips/imsVlmA1PdYvBQmD4/d1337f2wObOF?invite=cr-MSxudmwsMTk1NTEzMTMzLA

**Comment by QA-Pregon** [comment]
Wie viel Zeit ist exakt vergangen zwischen den aufklebversuchen?
Falls du es exakt hast wäre es perfekt.
Ungefähre Angaben sind solala;)

**Comment by SHaagmann** [comment]
Irgendwann nach dem restart glaube ich 12-13 Uhr oder so hab ich's aufgeklebt. Also so 10-8h

**Comment by QA-Pregon** [comment]
Wir schaun mal drüber was mit dem Klebeband los ist
Werden aber zum next update bestimmt was gemacht haben

**Comment by QA-Pregon** [comment]
Next update kommt da ein weitreichenden Fix der das System noch einmal grundlegend verändert, also sieh es als fixed ^^
