### ISSUE TITLE
Doppelte Mülleimer am Mirror Park

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#362]
**Character Name**
Marvin_Elpe

**Zeitpunkt (Datum / Uhrzeit)**
22.11.2020 02:26

**Beobachtetes Verhalten**
siehe Bild

**Erwartetes Verhalten**
Ein Mülleimer

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/33394632/99891456-1b3bee00-2c6a-11eb-90d5-1471ef35eb0b.png)

**Comment by DrGrizzlY17** [comment]
Fix
