### ISSUE TITLE
Feuer löschen funktioniert mit dem Fahrzeug des SAFR Firetruck (engine) nicht mehr.

### ISSUE THREAD

**Issue by Hochfels** [mexyn/statev_v2_issues#3620]
**Character Name** Nevis Yoki

**Auftrittszeitpunkt (Datum / Uhrzeit)** bei jedem Feuer

**Beobachtetes Verhalten** Feuer lassen sich nicht mehr mit dem Firetruck gelöscht werden. Es geht aktuell nur mit den Feuerlöschern.

**Erwartetes Verhalten** Feuer können mit dem Firetruck gelöscht werden.

**Schritte um den Fehler nachvollziehen zu können** Feuer legen und versuchen mit dem Firetruck zu löschen.

**Comment by eiksch** [comment]
bitte testen auf neustem build @Pregon
