### ISSUE TITLE
2 Leasingfehler

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#3621]
https://github.com/eiksch/statev_v3_issues/issues/3590 Bezug nehmend darauf,

1. Fahrzeuge die vom Leasing eingezogen werden, sind laut Tablet in der LS Garage. Setzt man den GPS Punkt dort hin, wird man zur Verwahrstelle geführt. Dort ist dann kein Fahrzeug. 

2. Fahrzeuge die vom Leasing eingezogen wurden kann man dadurch an der LS Garage einfach ausparken, ohne weiter sein Leasing zahlen zu müssen. 

![image](https://github.com/user-attachments/assets/4a172c43-c49a-4379-b578-d72f433f85b3)

**Comment by Erumeldor** [comment]
Die Fahrzeuge sind nur ausnahmsweise in der LS Garage, und werden auch nach kurzer Zeit wieder in die Verwahrstelle gepackt.
