### ISSUE TITLE
Gewichts Limit des Ziel Containers... ;D

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3622]
Bei V2 wurden beim verladen der Zielcontainer bis zu seiner max. Größe automatisch befüllt ohne die genaue Menge eingeben zu müssen.
Seid V3 ist es nicht mehr so, denke das ist ein Bug...

Zitat von damals: 
Item-Stacks, die beim Verschieben das Gewicht-Limit des Ziel-Containers überschreiten, werden Automatisch zur Maximal Möglichen Menge aufgeteilt.

https://github.com/eiksch/statev_v3_issues/issues/2018

**Comment by simplycach** [comment]
Könntest du das mal verdeutlichen mit einem Video, dann können wir uns das besser vorstellen.

**Comment by Statev-Bonsai** [comment]
wenn du dein auto mit item x belädst das automatisch aufgefüllt wird wie viel platz noch im inventar z.b. des fahzeugs ist, das gabs halt früher schon..

1. youga vor das lager parken (300kg kofferraum)
2. eisen (1kg pro item) mit der maus in das fahrzeug ziehen
3. ins fahrzeug werden automatisch genau 300stück geladen ohne das man die menge angeben muss, wenn weniger platz im fahrzeug ist natürlich weniger

das fahrzeug wird quasi immer passend mit der menge aufgefüllt ohne das man den freien platz errechnen muss und dementsprechend die items rüberzieht.

der erklärbär ist nicht meine stärke ^^

**Comment by QA-Pregon** [comment]
#3130
