### ISSUE TITLE
Abladepunkt versetzen 

### ISSUE THREAD

**Issue by DannyLaker** [mexyn/statev_v2_issues#3623]
Bitte um versetzung des Abladepunktes ( 🔥⚒️Die Schmiede⚒️🔥 )
```
Hay,
an dem derzeitigen Abladepunkt ist es fast unmöglich ne Achse unbeschädigt hin zu bekommen.
Entweder man fährt den Zaun um oder die Holzpoller vor der Firma.
Es wäre super schön wenn ihr den Abladpunkt vor die Firma setzen könnt (sihe Bild )
Am aller schönsten wäre es natürlich wenn die Eingangstür auch die vordere ist und nicht die hinter der Firma.

Danny Laker 
30.07.24

![grafik](https://github.com/user-attachments/assets/a4d03fb9-c620-444f-b9a1-27712cbea488)


![grafik](https://github.com/user-attachments/assets/df305ea3-a426-4868-aff3-90a93160221f)

**Comment by SatyriaDine** [comment]
Kannst du die Bilder nochmal neu hochladen? Die werden nicht angezeigt. Oder alternativ den Firmenhash posten?  :)

**Comment by SHaagmann** [comment]
![grafik](https://github.com/user-attachments/assets/a4d03fb9-c620-444f-b9a1-27712cbea488)


![grafik](https://github.com/user-attachments/assets/df305ea3-a426-4868-aff3-90a93160221f)

@SatyriaDine Kann man einfach Kopieren die Links ^^

**Comment by SatyriaDine** [comment]
Ladepunkt ist zum nächsten Update verlegt. :)
