### ISSUE TITLE
Versetzen eines Ladepunktes

### ISSUE THREAD

**Issue by Klausi-S** [mexyn/statev_v2_issues#3624]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
 Klaus Schotter 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
31.07.2024 

**Beobachtetes Verhalten**
 Der Ladepunkt ist leider so weit auf dem Gehweg und wird durch feste Objekte auf dem Gehweg eingeschränkt, dass man mit allen größeren Fahrzeugen dort nur schwer ran kommt und eine Achse starke Probleme hat, dort ordentlich ausladen zu können 

**Erwartetes Verhalten**
Den Punkt bitte verschieben für eine bessere Anfahrt. Entweder gerne wie auf dem Vorschlagsbild an die Seite der Firma oder weiter auf die Straße, wo dann aber auch die Straße mitunter blockiert wird. Hauptsache vom Gehweg bitte weg 

**Schritte um den Fehler nachvollziehen zu können**
 Innocence Blvd 2467 - Postcode 4026 - Firma AutoTeileKlausi - Firmen Hashj pf_Strawberry_21 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
 Beschreibe Schritt für Schritt wie man den Fehler nachstellen kann 

**Optional: Video / Bilder des Fehlers**

![Screenshot 2024-07-31 142829](https://github.com/user-attachments/assets/589cf380-4bc0-465c-97e7-893cda324619)

**Comment by SatyriaDine** [comment]
Ladepunkt ist zum nächsten Update verlegt. :)
