### ISSUE TITLE
CentralMiner Autominer Upgrade macht Interaktionen unusable

### ISSUE THREAD

**Issue by ItsPaulAT** [mexyn/statev_v2_issues#3625]
**Character Name**
Patrick Alonso

**Auftrittszeitpunkt (Datum / Uhrzeit)**
31.07.2024 ca. 19 Uhr

**Beobachtetes Verhalten**
Wenn man bei Centralminer ein Upgrade kauft (Autominer) kann man das Tablet nur noch mit ESC schließen, nicht mit F3 und nachdem man es geschlossen hat, funktionieren keine Interactions mer, kein Inventar, Handy, Tablet, E drücken in der Dimitri Mission - garnichts. Man muss restarten.

**Erwartetes Verhalten**
Dass sich das Tablet normal schließen lässt und dann weiterhin alles benutzbar ist.

**Schritte um den Fehler nachvollziehen zu können**
Tablet öffnen, CentralMiner öffnen, (Tablet schließen, wieder öffnen) - nicht sicher ob nötig, Autominer Upgrade kaufen. 
Dann sollte das Tablet mit F3 nicht mehr schließbar sein, nur mit ESC und dann keine Interaktionen mehr möglich.

**Comment by Statev-Bonsai** [comment]
kann ich nicht bestätigen... ^^

**Comment by JensGamerBoy** [comment]
Kann ich auch nicht bestätigen aber einmal kam es bei mir vor ist aber selten der fehler

**Comment by Erumeldor** [comment]
Da es nicht reproduzierbar ist, machen wir hier mal zu. Sonst gerne nochmal melden.

**Comment by QA-Pregon** [comment]
Is doch reproduzierbar
Passiert glaub dadurch, wenn man ein Upgrade kauft und dann nicht nochmal irgendwo ins Tablet reinklickt, dann funktioniert F3 nicht
Wenn man aber dann wieder iwo ins Tablet klickt gehts wieder
