### ISSUE TITLE
Plazierbares Objekt

### ISSUE THREAD

**Issue by Falk-Alers** [mexyn/statev_v2_issues#3626]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Scott Winchester**

Scott Winchester
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Vor ein paar Tagen aufgefallen, heute früh nachgeschaut
**Beobachtetes Verhalten**

Beim Legion Square wir mir ein Plazierbares Objekt angezeigt, dort ist aber nichts bzw ich kann auch nichts aufheben
Mit dem Char habe ich bis jetzt ein Item plaziert und das war in Sandy und habs auch wieder mitgenommen
**Erwartetes Verhalten**

Kein Item?
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot 2024-08-01 065334](https://github.com/user-attachments/assets/6aaac19f-20c8-45d7-8319-6b923832b525)

**Comment by Falk-Alers** [comment]
Stepz2k9 hatte die idee es ist meine deko im appartment ist ich teste das erstmal....

**Comment by simplycach** [comment]
Ja ist deine Deko ist aber mit dem nächsten Update behoben.
