### ISSUE TITLE
Fehler beim schweißen oder hinweis falsch ?

### ISSUE THREAD

**Issue by Tobias1496** [mexyn/statev_v2_issues#3627]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

`Luca_Gerwen

**Auftrittszeitpunkt (Datum / Uhrzeit)**
immer

**Beobachtetes Verhalten**
Beim schweißen soll man laut hinweis dem man auf dem schrottplatz von a findet mit mehreren kfz trolleys schneller schweißen kann dies aber weder mit 4 noch mit 10 trolleys bestätigen siehe bild es dauert immer noch 10 min für ein kfz teil zum schweißen 

**Erwartetes Verhalten**
vllt 2-3 min schneller beim schweißen je nachdem wie viele trolleys stehen

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Erumeldor** [comment]
Also, was du da machst ist kein Bug, sondern FailRP... ;)

**Comment by Tobias1496** [comment]
![Screenshot 2024-08-01 191204](https://github.com/user-attachments/assets/faa13739-46af-4c6a-b17f-025efed0300b)

**Comment by Tobias1496** [comment]
also verstehe ich dass falsch oder wie ?

**Comment by OnkelHomie** [comment]
> also verstehe ich dass falsch oder wie ?

JA! Definitiv JA! XD Hast ja trotzdem nur 2 Hände. Egal wie viel Kisten da stehen.
