### ISSUE TITLE
Crime Missionen fehlerhaft

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#3629]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Zane Kazee

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.08.

**Beobachtetes Verhalten**
Alle Marker abgearbeitet, und auch die bestätigunsmeldung erhalten.
-> Beim NPC lässt sich die Mission aber nur abbrechen.
Tritt nicht bei der Mission auf..

**Erwartetes Verhalten**
Das wenn man die Bestätigung bekommt, dass alle Marker bearbeitet wurden, die Mission auch abgebbar ist.
Ich habe mehrfach geprüft. Es ist kein Marker mehr offen.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/user-attachments/assets/892e0703-522e-4b1e-9192-5d5d7c35977b)
![image](https://github.com/user-attachments/assets/5cfc50c4-d534-4c05-9242-84f4f6e9f87a)

Terry Mission & 24/7 auf dem Highway
![image](https://github.com/user-attachments/assets/3ed750b1-2be7-4787-845f-65ce9466aa2b)
![image](https://github.com/user-attachments/assets/815a8223-cd1c-4601-98af-817777fb67eb)

**Comment by xpepperann** [comment]
Mission bei Lucas ebenfalls fehlerhaft, 

![GTA5 2024-08-02 14-17-12](https://github.com/user-attachments/assets/3b192c87-c182-49ec-a0aa-3483f98a2a7d)

**Comment by TheBroady** [comment]
> Mission bei Lucas ebenfalls fehlerhaft,
> 
> ![GTA5 2024-08-02 14-17-12](https://private-user-images.githubusercontent.com/171585197/354592926-3b192c87-c182-49ec-a0aa-3483f98a2a7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDIzOTgsIm5iZiI6MTcyMjYwMjA5OCwicGF0aCI6Ii8xNzE1ODUxOTcvMzU0NTkyOTI2LTNiMTkyYzg3LWMxODItNDllYy1hMGFhLTM0ODNmOThhMmE3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxMjM0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGI5YWI3MzIyMzYxZjI0M2ViNjdmMWFjNTYwZTk3ZjY3NjJjYTk2ZDA1NTY4MGJlOTJmYjkyYTRkM2FmZDRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ivW4oBubeBen8ls_t7A3NEuGCTdnHwbvLmxI_Th9Bxs)

Liegt daran, dass wir zu schnell waren.

**Comment by 2FaceOriginal** [comment]
Ammunation Route68 und Far-East Highway ist ebenfalls fehlerhaft
Terry 24/7 bei UTool ebenfalls

**Comment by DeRo1337** [comment]
Problem trat nun auch bei 3 Mistique Aufträgen auf:
- Strawberry (innocent blvd)
- Chumash (barbareno Rd)
- Paleto bay

**Comment by Erumeldor** [comment]
Problem ist bekannt.
Auch hier der Tipp:
Bei großen Missionen lieber etwas mehr Zeit lassen mit fertig werden, dann tritt das Problem nicht auf.
Morgen gibts ein Hotfix-Update :)
