### ISSUE TITLE
Porsche GT3 RS 

### ISSUE THREAD

**Issue by AideenCarter** [mexyn/statev_v2_issues#363]
Aideen Carter

Nach V2 Release

Das Handling so wie das anfahren vom GT3 ist Unterirdisch, man hat viel Geld IC Investiert und sich das passenden Auto gesucht und es wurde vom fahrverhalten komplett gereworked zu V2 

Stand vor V2 

veh gt3rs  und fahren

1920x1080

**Comment by DonVitoDiangelo** [comment]
Der gesamte Fahrzeugpool wurde bereits überarbeitet. Hier wird es bis auf wenigen Ausnahmen keine Anpassungen geben.
