### ISSUE TITLE
Nackentattoo verschwunden

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3630]
Ich hatte im Nacken ein großes Tattoo (außenform wie ein Dreieck), dieses ist nun irgendwie verschwunden.
Kann nur mit einem Bild vom verschwundenen Tattoo dienen ^^

**Comment by Statev-Bonsai** [comment]
Sehe grade, über dem linken Auge der Schriftzug ist auch verschwunden, sowie das Doppelkreuz in der mitte

**Comment by ySimbaa** [comment]
Es sind aktuell ca. 15 Tattoos betroffen, die nicht angezeigt werden, da wir diese auf einen anderen Ordner geswitched haben. Hab mal wieder dazu gelernt, das eine Umstellung der XML dazu führt. Was an sich ja kein Problem ist, im RP sich die Nachstechen zu lassen, aber das wird aufgrund eines Fehlers gerade noch verhindert, da das "alte" Tattoo immer noch auf dem Char gespeichert ist. Ich bin da dran das Problem zu fixen. 

Es wird aber darauf hinauslaufen, das man sich die paar Tattoos nachstechen lassen muss

**Comment by QA-Pregon** [comment]
Tattoos müssen wie Simba schon gesagt hat einmal neu gestochen werden.
Entschädigungen gibt es dabei leider nicht, also bitte keine Tickets dazu aufmachen, um den GD, etc Arbeit zu sparen =D
