### ISSUE TITLE
Doppelt Kontobuchung nach Marktplatzkauf

### ISSUE THREAD

**Issue by glb11** [mexyn/statev_v2_issues#3631]
Jens_Holt   (Mit der Firma Trash Transformers Grapeseed)

02.05.2024  17:50/18:05

**Beobachtetes Verhalten**

Nach Marktplatzeinkauf an der Firma  "SYNERGY I Warehouse"  Doppelte Kontobuchung des Einkaufes  "Marktkauf: 12 PKW Reifen zu 160.99$" aber nur einfacher Warentransfer (Waren gesamt 13 im Angebot).  Geld wurde direkt von meiner Firma abgebucht

P.S. danach noch an 2 andren Firmen eingekauft dort wie erwartet (über: 1x Privat Konto, 1x Firmenkonto

**Erwartetes Verhalten**

Nur eine Kontobuchung

**Schritte um den Fehler nachvollziehen zu können**
An die Firma fahren und einkaufen.  Und mit Zufall passiert dieser Bug

**Optional: Video / Bilder des Fehlers**

![20240802180635_1](https://github.com/user-attachments/assets/3751e421-20bc-495e-b0bb-aed519cdca95)
![20240802180647_1](https://github.com/user-attachments/assets/b89d9852-1193-4291-9e31-f0ea9816dece)

Bei Fragen schreiben.

**Comment by QA-Pregon** [comment]
Falls es nochmal passiert bitte mal Bescheid geben.
Konnte da jetzt nichts zu rausfinden oder reproduzieren

**Comment by QA-Pregon** [comment]
Ich mach erstmal zu, gern erneut bescheid geben, falls es nochmal passiert
