### ISSUE TITLE
Kann keine Mitarbeiter einstellen, Email kommt nicht an

### ISSUE THREAD

**Issue by JasminHarper** [mexyn/statev_v2_issues#3633]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Josefine_Miley

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.08.2024 ca. 21:30

**Beobachtetes Verhalten**
Firma: Hash: pf_WestVine_26 
Wollte Jay_Moore einstellen, allerdings bekommt er keine bestätigungs Mail

**Erwartetes Verhalten**
Mitarbeiter einstellen können

**Comment by QA-Pregon** [comment]
Sicher, dass der Name Richtig und mit unterstrich eingegeben wurde?
Bei mir klappt alles

**Comment by TheOutburst** [comment]
Per Ticket gelößt, ist nen 1 in 2000 Fehler, bisher lässt sich das nicht reproduzieren.
Ich mach das hier mal zu, sollte jemand da eine Regelmäßigkeit feststellen gerne wieder öffnen oder neuen Tracker machen
