### ISSUE TITLE
Nach dem umwerfen mit ö kommt man nicht mehr hoch

### ISSUE THREAD

**Issue by Slayraw** [mexyn/statev_v2_issues#3634]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Vittorio_Marino**

Mit mir und Maxym_kalinishenko 
**Auftrittszeitpunkt (Datum / Uhrzeit)**

02.08.2024 21:50
**Beobachtetes Verhalten**

Hab 3 leute mit ö umgeworfen und die kahmen absolut nicht mehr hoch egal wie oft sie ö gedrückt haben
**Erwartetes Verhalten**
Das sie wieder aufstehen

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by QA-Pregon** [comment]
I dont know ob Bug oder Feature, bei mir ging es auch nicht direkt aber nach ein paar Sekunden
Ich hinterfrags mal

**Comment by TheOutburst** [comment]
An sich solltest du nach 10 Sekunden wieder aufstehen können, dh kurz durchatmen, dann einmal Ö drücken

**Comment by QA-Pregon** [comment]
Hat bei mir aufm Live funktioniert, wenn ihr das näächste mal umgeworfen wird try again. macht dann bitte falls es wirklich nicht geht neu auf, dann mach ich den erstmal wieder zu
