### ISSUE TITLE
Kleiderschrank Item Fehler

### ISSUE THREAD

**Issue by Keemobi** [mexyn/statev_v2_issues#3635]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Jarvis_Gorman**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

02.08.2024

**Beobachtetes Verhalten**
Kleidungsstück geht nicht in den Kleiderschrank

**Erwartetes Verhalten**

Sollte als Kleidungsstück erkannt werden und nicht als Gegenstand

**Schritte um den Fehler nachvollziehen zu können**

Kleidungsstück für den Kleiderschrank verstaubar machen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

1920x1080

**Optional: Video / Bilder des Fehlers**
 
![image](https://github.com/user-attachments/assets/f642d7d6-ab58-4eea-bbcc-e3e8dbda30af)

**Comment by stepz2k9** [comment]
Auch das [F] weißes Lace Top ist davon betroffen

**Comment by xpepperann** [comment]
Alle Kleidungsstücke im Inventar sind ebenso betroffen

![GTA5 2024-08-04 02-42-02](https://github.com/user-attachments/assets/8f8263f7-bf5d-442d-a0cb-1a24a4159794)

**Comment by SHaagmann** [comment]
![image](https://github.com/user-attachments/assets/cec08b02-0f26-406b-90fa-bf32a7f19db1)
Das Oberteil auch

**Comment by ySimbaa** [comment]
Nächstes Update Fixed
