### ISSUE TITLE
Sammelreport für zu schnell kaputtgehende autos

### ISSUE THREAD

**Issue by FLVFFY1** [mexyn/statev_v2_issues#3638]
aktuell weitaus schneller kaputt gehende autos als zuvor:
(leichtes touchieren von irgendwas setz die karren in brand / komplett ausser gefecht)
- Remus
- RT3000
- Scout (Police)
- STX (Police)
- Contender (SAFR)
- Sadler (SAFR)

**Comment by ghost** [comment]
Gargoyle

**Comment by v3rpl4nt** [comment]
Police Cruiser
Police Gauntlet

**Comment by Erumeldor** [comment]
Wir sind dran. Team ist fleißig, wir gehen alle Fahrzeuge durch :,)

**Comment by Minischnitzl** [comment]
Verus

**Comment by Erumeldor** [comment]
https://github.com/eiksch/statev_v3_issues/issues/3637

**Comment by Erumeldor** [comment]
Wir machen hier mal zu. Neue Meldungen gerne im Vorschlag Thread auf dem Discord! :)
