### ISSUE TITLE
Neuer Mitarbeiter bei MBM Blockiert Lucas Mission

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3639]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

AJ
**Auftrittszeitpunkt (Datum / Uhrzeit)**

04.08 10:45
**Beobachtetes Verhalten**

Der neue NPC Blockiert einen Punkt im MBM Autohaus
**Erwartetes Verhalten**

Alle punkte kann man easy fertig machen
**Schritte um den Fehler nachvollziehen zu können**

Großes Autohaus annehmen und MBM bekommen. Dort dann alle Punkte durchgehen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

Clipt folgt noch mein Upload hat kein bock gerade

**Comment by SatyriaDine** [comment]
Ist schon gefixt und wird mit dem nächsten Update behoben :)
