### ISSUE TITLE
Garagen Stellplatz 

### ISSUE THREAD

**Issue by Asterix526** [mexyn/statev_v2_issues#3640]
Name Christian Big 

Hallo, ich möchte darum Bitten dem Haus house_SandyShores_61 auf die Hofeinfahrt einen Stellplatz hinzuzufügen, das währe sehr Lieb. 
![IMG_20240804_143845](https://github.com/user-attachments/assets/5165e184-563f-4b15-9c56-4fe2b685561f)

**Comment by Statev-Bonsai** [comment]
Früher war es so das Trailer etc keine Garage bekommen haben, was suchst du dir denn immer für Häuser aus ;D

**Comment by Asterix526** [comment]
🙈Verzeihung, es währe echt lieb wenn es eine platz bekommen könnte. 🙈Von meinem Telefon gesendet-------- Ursprüngliche Nachricht --------Von: Statev-Bonsai ***@***.***>Datum: So., 4. Aug. 2024, 18:42An: eiksch/statev_v3_issues ***@***.***>Cc: Asterix526 ***@***.***>, Author ***@***.***>Betreff: Re: [eiksch/statev_v3_issues] Garagen Stellplatz  (Issue #3640)
Früher war es so das Trailer etc keine Garage bekommen haben, was suchst du dir denn immer für Häuser aus ;D

**Comment by Asterix526** [comment]
Ich habe kurz nach dem Kauf 400 kg Lagerfläche verloren, beim Kauf hatte ich 1000 kg nach dem Update nur noch 700 kg ist für mich auch Ok, darum währe ich für einen Stellplatz sehr dankbar 🙈Von meinem Telefon gesendet-------- Ursprüngliche Nachricht --------Von: Statev-Bonsai ***@***.***>Datum: So., 4. Aug. 2024, 18:42An: eiksch/statev_v3_issues ***@***.***>Cc: Asterix526 ***@***.***>, Author ***@***.***>Betreff: Re: [eiksch/statev_v3_issues] Garagen Stellplatz  (Issue #3640)
Früher war es so das Trailer etc keine Garage bekommen haben, was suchst du dir denn immer für Häuser aus ;D

**Comment by SatyriaDine** [comment]
Ganz genau, das Teil ist ein Trailer, hat weder Garage noch sonst was, daher wird hier kein Garagenplatz kommen. :)

**Comment by Asterix526** [comment]
1.Es würd als Haus definiert. 2.habe ich gleichzeitig 2 Objekte neben einander gekauft hatte 2000kg zusammen kurz danach nur noch 1400 kg zusammen mir wurden 600 kg aufeinmal nach dem Kauf genommen. Es währe nur ein endgegenkommen gewesen. Lg Von meinem Telefon gesendet-------- Ursprüngliche Nachricht --------Von: SatyriaDine ***@***.***>Datum: So., 4. Aug. 2024, 19:10An: eiksch/statev_v3_issues ***@***.***>Cc: Asterix526 ***@***.***>, Author ***@***.***>Betreff: Re: [eiksch/statev_v3_issues] Garagen Stellplatz  (Issue #3640)
Closed #3640 as not planned.
