### ISSUE TITLE
Hals Tattoo verschwunden, "Hat das tattoo bereits" - Meldung erscheint

### ISSUE THREAD

**Issue by CalebPapaCrane** [mexyn/statev_v2_issues#3641]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Caleb Roberts

Kunde, leider ohne Name
**Auftrittszeitpunkt (Datum / Uhrzeit)**
18:30

**Beobachtetes Verhalten**
Kunde hatte das "Skull" Tattoo am Hals, das sei wohl auch verschwunden, nun steht da auch "Tattoo bereits vorhanden".

**Erwartetes Verhalten**
Nachstechen sollte möglich sein

**Schritte um den Fehler nachvollziehen zu können**
Versuchen das Tattoo zu stechen, während es bereits drauf ist.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
QHD

**Optional: Video / Bilder des Fehlers**

**Comment by ySimbaa** [comment]
Nächstes Update Fixed
