### ISSUE TITLE
[M] Black Vulture Boxy Tee kann nicht richtig angezogen werden

### ISSUE THREAD

**Issue by Sc8pe** [mexyn/statev_v2_issues#3642]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Miles Dawsen

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.08.2024

**Beobachtetes Verhalten**
Zu den oben genannten neuen Shirt gibt es nichts passendes. "Loch in Kleidung" 

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**
Hab alle Möglichkeiten probiert um es korrekt anzuziehen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
Besser als das, geht nicht.

![Screenshot 2024-08-05 134205](https://github.com/user-attachments/assets/9e3364c5-cd1b-40a6-8441-8957096c4c3b)

**Comment by QA-Pregon** [comment]
Next Update fixed, ansonsten nochmal schreiben
