### ISSUE TITLE
Antrag auf kleine Garage

### ISSUE THREAD

**Issue by Rehki** [mexyn/statev_v2_issues#3643]
Sari Greren

HausHash :   house_SandyShores_39

Hallo, 

ich wollte einmal nachfragen, ob es die Möglichkeit gibt, bei dem o.g. Haus in der Einfahrt eine kleine Garage mit 2 Stellplätzen zu 
bekommen. Wenn nicht, ist es auch kein Weltuntergang ;)

LG

**Comment by SatyriaDine** [comment]
Hast zum nächsten Update eine kleine Garage unterm Carport :)

**Comment by Rehki** [comment]
Ich danke dir :)
