### ISSUE TITLE
Verlegung Abladepunkt ( Genius Group ) 

### ISSUE THREAD

**Issue by Tobse1904** [mexyn/statev_v2_issues#3644]
**Grüße liebes State V Team,** 

Wäre es möglich den Abladepunkt der Genius Group ( Labor + Gießerei ) zu verlegen beide nutzen den gleichen abladepunkt.

Hash Labor : pf_lamessa_41
Hash Gießerei : pf_cypressflats_2

Grund : Es ist ein wenig eng mit der Achse, als weiteres besteht das Problem wenn man ablädt und in die Gießerei oder das Labor geht man sehr oft im Fahrzeug landet , 2 x deswegen schon bewusstlos gewesen. ( Kleinigkeit noch dazu, wenn man in die Gießerei geht und wieder raus geht landet man am Ausgangspunkt des Labors... Wir sagen immer wir haben den Hinterausgang genommen weil einige sich wundern wenn wir in die Gießerei rein gehen und woanders wieder raus kommen. ggf kann dies gleich mit behoben werden. )

Bilder füge ich hinzu dort wäre der Abladepunkt ein Träumchen.

**Alter Abladepunkt**
![Verlegung Abladenpunkt Genius Group Labor+Gießerei](https://github.com/user-attachments/assets/37b7ee4d-fd4a-493e-8196-d1c4e70056f4)

**Neuer Abladepunkt**
![Verlegung Abladenpunkt Genius Group Labor+Gießerei Neu](https://github.com/user-attachments/assets/ca5f495f-7284-497a-8aee-835dec05df45)

( da wo die achse steht sollte der neue hin )

Herzlichen Dank im voraus <3

**Comment by SatyriaDine** [comment]
Ladepunkte zum nächsten Update verlegt. Und du solltest auch in Zukunft nicht mehr aus der falschen Firmentür rauskommen. :D

**Comment by Tobse1904** [comment]
Mega, Herzlichen Dank für das schnelle umsetzen <3

**Comment by Tobse1904** [comment]
Ach da fällt mir ein kann man den von unserem lager ggf. ein wenig auf die Straße setzen ? mit achse ist auch der ein wenig blöd ^^

Hash Lager : pf_lamessa_42


DANKÖÖÖÖ <3

**Comment by SatyriaDine** [comment]
Ist erledigt. :D

**Comment by Tobse1904** [comment]
<3
