### ISSUE TITLE
[F] Purple Juciy Joggingpants Verschwindet

### ISSUE THREAD

**Issue by Falk-Alers** [mexyn/statev_v2_issues#3645]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Kelly Winchester
**

Wurde uns über das DC gesagt von "Mike Jenkins", IC habe ich das Problem bei Kelly auch gesehen ungefähr ab... 15m vll

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Mi 07.08.24 ca gegen 09:03Uhr

**Beobachtetes Verhalten**

Die Hose wird ca ungefähr ab 15m range unsichtbar/durchsichtig

**Erwartetes Verhalten**

bugt nicht weg

**Schritte um den Fehler nachvollziehen zu können**

hose kaufen von F, und mit anderen char weiter weg gehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot_4](https://github.com/user-attachments/assets/30060859-9b71-4757-8862-d29282184658)
![Screenshot_3](https://github.com/user-attachments/assets/64f94687-4b2e-4a5e-b06e-a9a796382011)

![Screenshot 2024-08-07 092946](https://github.com/user-attachments/assets/61bd21a6-8654-4aee-a343-8ac1e3956bae)

**Comment by ySimbaa** [comment]
Können wir so nichts machen. Der Aufwand ist viel zu hoch um das zu fixen.
