### ISSUE TITLE
Tore an den Firmen demolieren die Fahrzeuge

### ISSUE THREAD

**Issue by Eve-Noxito** [mexyn/statev_v2_issues#3646]
Ingame Name: Eve Lockwoo
Unser Labor liegt zwischen 2 Toren welche beim durchfahren regelmäßig das Fahrzeug kaputt machen.. Das reicht von gelber Kontrolleuchte bis hin zu Motor brennt und ist komplett Schrott.. Das Problem taucht überwiegend bei Autos und kleineren Arbeitsfahrzeugen wie Burritos auf. Aber auch Mtl`s bleiben nicht verschont (siehe Bild). 
Könnten die beiden Tore von euch entfernt werden? Langsam wird das mit den Reperaturen echt teuer... 
Wir haben auch schon versucht rückwärts durchs Tor zu fahren, das Problem, man bleibt an der mittleren Stange der Tore hängen und das Auto verkeilt sich, besonders schlimm ist das bei dem kleineren Tor in Richtugn Capital Blvd.
Danke im Voraus Eve
![image1](https://github.com/user-attachments/assets/f799c9e4-437b-4e04-9c24-0e7966e5808e)
![image2](https://github.com/user-attachments/assets/48543b2a-0b7a-4417-a704-e5b77e334248)
![image3](https://github.com/user-attachments/assets/0f7d40ad-304a-4db8-8e2e-8b1283ad057e)
![image4](https://github.com/user-attachments/assets/eae57679-aeb1-4454-9c2c-a14bb6551c0a)

**Comment by Erumeldor** [comment]
Hi @Eve-Noxito .
Ihr habt euch den Firmenstandort vorher raussuchen können, daher müsst ihr da leider mit leben..
Der MTL sollte im nächsten Update nicht mehr so empfindlich sein.
