### ISSUE TITLE
Diverse Tattoos verschwunden..

### ISSUE THREAD

**Issue by CalebPapaCrane** [mexyn/statev_v2_issues#3647]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Caleb_Roberts

Naomi_Sunchez
**Auftrittszeitpunkt (Datum / Uhrzeit)**
13:50

**Beobachtetes Verhalten**
Es geht prinzipiell darum dass eines Ihrer Gesichtstattoos weg ist "FUCK COPS" unter'm Auge, des weiteren sind aber diverse Gesicht Tattoos verschwunden, wie auch die Namen von einigen einfach weg. wären es nur 2-3 Würde ich die listen aber ich glaube da muss man mal drüber, sind doch einige die Weg sind und oder den Namen verloren haben.

Wird halt auf Dauer schwer den Leuten zu erklären dass die verblassen und nachgestochen werden müssen, davon mal abgesehen dass das nicht jeder erneut zahlen wird, wer soll denn die Kosten tragen?

**Erwartetes Verhalten**
Kein verschwinden :D

**Schritte um den Fehler nachvollziehen zu können**
Einfach die Tattoos im Gesicht durchgehen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
QHD

**Optional: Video / Bilder des Fehlers**

**Comment by stepz2k9** [comment]
![1](https://github.com/user-attachments/assets/7ac90552-22e6-4cb1-b666-9ccba62a11cb)

**Comment by QA-Pregon** [comment]
#3630
