### ISSUE TITLE
Doppelte Frisur

### ISSUE THREAD

**Issue by Xaviju8920** [mexyn/statev_v2_issues#3649]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Sean Miller

08.08.24 13:30

Der Haarschnitt für Frauen"Ultralang - seitlich Links" gibt es 2mal

Evtl. einmal raus nehmen

https://pic.statev.de/image/20240808133424-1.Hzj242

**Comment by SauerkirscheJM** [comment]
Ich hätte noch 2 Frisuren die doppelt sind, die vom Ersteller genannte müsste ich nachgucken, die war mir nicht aufgefallen.

langes Haar blow...
![GTA5 2024-07-19 15-13-48](https://github.com/user-attachments/assets/cdf6d976-ac57-4d42-b9f3-730f0f56d65b)
und 
Mittellang 2 Tone ... (mit braid heißt der weiter, glaube ich)
![GTA5 2024-07-19 15-14-14](https://github.com/user-attachments/assets/5e0dba17-d892-4421-9c7c-ea89e0cc7d85)

Sind die selben Frisuren mit unterschiedlichem Namen.

Dann gibts noch Jazzlyn Twist, die doppelt hintereinander liegen.
![GTA5 2024-08-13 19-46-41](https://github.com/user-attachments/assets/3e6ae2da-1571-464e-93f0-789c0de6a93b)

**Comment by SauerkirscheJM** [comment]
Mir ist noch was aufgefallen:

Die "Raindrop Tails" werden nicht angezeigt. Stattdessen werden wird Dark Diva noch einmal angezeigt. Bin es mehrmals durchgegangne und habe die Liste überprüft.

**Comment by ySimbaa** [comment]
fixed
