### ISSUE TITLE
Frisur geht durch Cap

### ISSUE THREAD

**Issue by Woarx** [mexyn/statev_v2_issues#365]
**Ernst Hendrikson**

**Zeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by tastydev** [comment]
Welche Cap ?

**Comment by Enemyaa** [comment]
@Woarx  Kannst du bitte nochmal den Namen der Cap dazu schreiben?
