### ISSUE TITLE
Dose Lack verschwindet bei kauf mit Tanker

### ISSUE THREAD

**Issue by Kambadin** [mexyn/statev_v2_issues#3651]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Brian Mason**

**08.08.2024 19:19:20**

**Beobachtetes Verhalten**
ich habe heute bei einem Labor versucht eine Dose Lack zu kaufen. Hatte nicht daran gedacht das ich die in den Tanker (Tanktrailer) kaufe die aber da nicht rein geht.
Dann kam die Meldung das es da nicht rein geht. Soweit so gut. Der Inhaber gab mir die Dose dann so und ich wollte das Geld überweisen. Da hab ich gesehen das das Geld abgebucht wurde. Auch die Dose aus dem Marktplatz ist verschwunden. 

**Erwartetes Verhalten**
es sollte nur die Fehlermeldung kommen aber kein Geld oder Ware abegzogen werden.

**Schritte um den Fehler nachvollziehen zu können**
Siehe  Beobachtetes Verhalten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
 https://youtu.be/prVsrWU7rpQ
![image](https://github.com/user-attachments/assets/c34eb4d8-9c2f-447b-a767-9b0448252257)

**Comment by SatyriaDine** [comment]
next update fixed

**Comment by Penthax** [comment]
Falls es relevant ist :

Hatte das gleiche Problem mit dem Pounder.. wollte ungedacht Wasser an der Tür ankaufen...natürlich kam die Meldung das es nicht funktioniert ..aber Geld wurde trotzdem vom Konto abgebucht.
