### ISSUE TITLE
Lackdose nach Kauf an Türe verschwunden

### ISSUE THREAD

**Issue by K0elschi** [mexyn/statev_v2_issues#3652]
**Character Name**
Timothy_Goodsen
Brian_Mason

**Auftrittszeitpunkt (Datum / Uhrzeit)**
08.08.2024 19:19

**Beobachtetes Verhalten**
Brian Mason hat bei mir (Timothy Goodsen) an der Türe (Gee Lab, pf_elysianisland_9) eine Dose blauen Lack gekauft, während sein Öltrailer auf dem Ladepunkt stand. Macht so keine Sinn, ist aber leider passiert.
Das Geld dafür wurde bei Ihm abgezogen und im Marktplatz ist auch eine Dose blauer Lack weniger.
Allerdings ist die Dose blauer Lack jetzt nirgendwo zu finden.

**Erwartetes Verhalten**
Wenn ein Fahrzeug auf dem Ladepunkt steht, dessen Ladefläche für die angekaufte Ware nicht geeignet ist, wird der Ankauf mit einer entsprechenden Fehlermeldung abgebrochen.

**Schritte um den Fehler nachvollziehen zu können**
- Öltrailer auf den Ladepunkt einer Firma stellen
- An der Türe dieser Firma ein Produkt kaufen, was nicht in den Ölttrailer geladen werden kann

**Comment by QA-Pregon** [comment]
#3651
