### ISSUE TITLE
Masken Dupen sich im Auto

### ISSUE THREAD

**Issue by eckbert58** [mexyn/statev_v2_issues#3654]
**Character Name**
Edoardo Colombo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Beobachtetes Verhalten**
masken dupen sich einmalig beim an und ausziehen im auto

**Erwartetes Verhalten**
kein duping

**Schritte um den Fehler nachvollziehen zu können**
einsteigen - maske anziehen maske ausziehen - ins inventar gucken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
<egal>

**Comment by QA-Pregon** [comment]
Hast nen Clip oder den Maskennamen für mich?
Passiert bei mir nämlich nicht

**Comment by eckbert58** [comment]
leider nein, hab es grade auch versucht zu reproduzieren aber klappt nicht. Getestet bei voller fahrt in einem Rubble falls das weiter hilft. maske war ein Schwarzer Neck Gaiter

**Comment by QA-Pregon** [comment]
Gabs immer mal wieder dass sich einzelne Items mal geduped haben.
Ich versuchs die Tage mal iwie hinzubekommen aber denke mal nicht dass ich da iwas finde

**Comment by QA-Pregon** [comment]
Mal bitte ein Auge drauf haben falls es wieder aufkommt, direkt bescheid geben
