### ISSUE TITLE
Möbel aus anderen Stockwerken werden aufgehoben

### ISSUE THREAD

**Issue by DerHessenTyp** [mexyn/statev_v2_issues#3655]
**May Bailey**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.08 - 09.08 

**Beobachtetes Verhalten**
Die Spielerin benutzt ihren Notizblock aus dem Inventar während Sie im Haus steht. Das Haus hat Erdgeschoss, 1 UG und 2 UG. Egal in welchem Stockwerk Sie steht, hat Sie nach jedem Benutzen des Notizblockes (wenn sie ein Blatt abreisst) irgendwelche Random Möbel aus dem Haus im Inventar.

**Erwartetes Verhalten**
Das keine Möbel abgebaut werden, sondern an ihrem Platz stehen bleiben. Und man im Haus problemlos den Notizblock nutzen kann.

**Schritte um den Fehler nachvollziehen zu können**
- Inventar öffnen
- Notizblock benutzen
- Blatt abreissen
- Möbelstück aus verschiedenen Stockwerken landet im Inventar.

**Comment by simplycach** [comment]
Leider nicht änderbar.
