### ISSUE TITLE
Neues Piercing nicht herstellbar + evtl. fehlende Ressource in Produktion

### ISSUE THREAD

**Issue by LeaBrandt** [mexyn/statev_v2_issues#3656]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Ronja Brandtberg

**Auftrittszeitpunkt (Datum / Uhrzeit)**
09.08.2024 - 8:40 Uhr 

**Beobachtetes Verhalten**
Die Produktion in der Fertigung zur "Kette mit türkisem Herz" ist nicht möglich obwohl alle Ressourcen vorhanden sind. Fehlermeldung "Fehler in der Konfiguration der Produktion!" 

Außerdem ist mir aufgefallen, dass es für alle "oliven" Sachen (siehe Bild) immer grüne Farbtuben benötigt werden. Nur bei "[M] 24 SAPD Olive SRT CSS Glasses verpackt" fehlen diese. Ich denke das ist ein Versehen, weil bei den Frauen braucht man die ja auch. 

**Erwartetes Verhalten**
Piercing kann produziert werden. 

**Schritte um den Fehler nachvollziehen zu können**
Versuchen Piercing zu produzieren. 

**Optional: Video / Bilder des Fehlers**

![Fehler Produktion](https://github.com/user-attachments/assets/fe7e471e-b356-41be-9a33-17df060babdc)
![Fehlende Farbtube in Produktion](https://github.com/user-attachments/assets/fa6668af-d43f-4ea2-a878-d7d091dbef94)

**Comment by ySimbaa** [comment]
Piercing guck ich mir heute an. Dauert dann leider noch bis zum nächsten Fix.

**Comment by QA-Pregon** [comment]
Entweder schon drauf oder next update
Aber auf jeden Fall fixed xD
