### ISSUE TITLE
Crimepunkt bei US Customs

### ISSUE THREAD

**Issue by StateV-Jan** [mexyn/statev_v2_issues#3658]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Liam Taylor

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Beobachtetes Verhalten**
Der Punkt ist schwer auszulösen, weil der Lagermarker direkt dort ist (Sie haben kein Zugriff) 

**Erwartetes Verhalten**
Punkt sollte besser auslösbar sein , Punkt versetzen

**Schritte um den Fehler nachvollziehen zu können**
Bei Knox Mission annehmen (US Customs) und versuchen den Punkt auszulösen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot 2024-08-10 081140](https://github.com/user-attachments/assets/1fbd4cc1-829e-4c55-97d4-2546f91b3635)

**Comment by SatyriaDine** [comment]
Next update fixed
