### ISSUE TITLE
Gebäudestrukturen Fehlerhaft durchsichtig

### ISSUE THREAD

**Issue by Bolle-Hirth** [mexyn/statev_v2_issues#3659]
Hallo Zusammen

Ingame Name Bolle Hirth
habe mich Heute 10.08.2024 neu angemeldet auf euren Server wollte gerade den start durchlaufen.
am Flughafen gespawnt und leider nur Fehlerhafte texturen der Gebäude.
keine Wegfindung möglich
Frage meiner seits ist liegt es jetzt an den Texturen vom gebäude oder sind es einstellungen meiner seits die da gerade probleme machen

details siehe Bild
![StateV_airport](https://github.com/user-attachments/assets/a6277879-9a83-439d-acf0-893c1bd3d13c)

**Comment by stepz2k9** [comment]
Mir ist das auch passiert, hab einfach das Tutorial weiter gespielt und wurde dann richtig weggeportet.

**Comment by SatyriaDine** [comment]
Hello hello, das ist leider ein Fehler der ab und zu passiert. Du kannst aber wie Caleigh schon genau richtig erklärt hat, das Tutorial einfach weiter spielen und wirst das rausgeportet. :)

**Comment by Bolle-Hirth** [comment]
Hallo ,
danke für die info
ja hab tutorial beendet und nun passt alles soweit ... denk ich zumindest 

MFG
