### ISSUE TITLE
Tannenholz nicht verladbar (Falsche Transportgruppe)

### ISSUE THREAD

**Issue by DerHessenTyp** [mexyn/statev_v2_issues#366]
**Andreas Jung*

**Zeitpunkt (22.11.2020 um 06:15 Uhr)**

**Beobachtetes Verhalten**
Ich möchte aus dem Lager meines Sägewerkes Tannenholz aus dem Lager in einen Burrito verladen oder auch in meine Tasche Packen (Früher auch schon mit einer Achse und Pounder probiert) und es zeigt mir an Falsche Transportgruppe

**Erwartetes Verhalten**
Es sollte wie auch Holzbretter zumindestens möglich sein diese auch in normale Transporter zu packen.

**Optional: Video / Bilder des Fehlers**
Links Kommt die Fehlermeldung Falsche Transportgruppe

**Comment by DonVitoDiangelo** [comment]
fixed next update
