### ISSUE TITLE
Tattoo verschwindet

### ISSUE THREAD

**Issue by xXCoCoNuTx3** [mexyn/statev_v2_issues#3662]
**Character Name**
Valeria Martinelli

**Auftrittszeitpunkt (Datum / Uhrzeit)**
12.8 zwischen 5 und 6 Uhr (aber denke mal immer )

**Beobachtetes Verhalten**
Bei shorts usw Tattoo am Bein sichtbar, sobald rosa karierter Rock an Tattoo weg

**Erwartetes Verhalten**
Tattoo am bein bleibt sichtbar

**Schritte um den Fehler nachvollziehen zu können**
Wechsel der Kleidung auf oben besagte Kleidung

**Optional: Video / Bilder des Fehlers**
![Screenshot_1](https://github.com/user-attachments/assets/95a195fb-052d-4b93-b6cb-23f2b8384325)
![Screenshot_3](https://github.com/user-attachments/assets/8248ce15-1f32-4b62-87e2-02e38b8d1fba)

**Comment by stepz2k9** [comment]
Das ist leider die Mod an sich. Wenn man den in Menyoo einfügt, dann klaut der einem auch die Bein-Tattoos. Dasselbe haben wir mit noch 2 Hosen IC. Da kann man nicht viel machen, außer nicht tragen.

**Comment by QA-Pregon** [comment]
Soweit ich weiß könn wir da nichts machen
