### ISSUE TITLE
bug/fehler Central Miner 

### ISSUE THREAD

**Issue by Kloputzer02** [mexyn/statev_v2_issues#3663]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
 Jason_Collins

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 12.08.2024 9:20 uhr

**Beobachtetes Verhalten**
bezahle 25 Dolla für den Autominer 

**Erwartetes Verhalten**
der preis müsste teuer sein

**Schritte um den Fehler nachvollziehen zu können**
nach den kauf des 30 autominer sprang die kauf zahl auf 25 dolla bei mir 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://clips.twitch.tv/CoweringPrettiestPangolinDuDudu-1pLnL2J7qdUYxQFF

**Comment by rodistic** [comment]
Ist next update fixed.

Das nächste mal wenn du ein Bug findest, nicht noch so extrem Abusen.

@simplycach bitte zu machen
