### ISSUE TITLE
Knast Klamotten werden zum Overall nach erneutem Knastantritt

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3664]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew_Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

12.08 
**Beobachtetes Verhalten**

Wenn man sich mit Gekauften Klamotten entlassen lässt und wieer eingeknastet wird hat man wieder den Overrall
**Erwartetes Verhalten**

Man behält die klamotten an
**Schritte um den Fehler nachvollziehen zu können**

Hart für 150 Knast Zigaretten Arbeiten

Diese Eintauschen

Entlassen werden mit den klamotten an

Erneut eingeknastet werden

**Comment by QA-Pregon** [comment]
Alles was man bei der Entlassung hat wird ja abgenommen.
Wenn du neu reinkommst bekommst du halt die Klamotten, die dir das PD "übergibt" und das ist nun mal der Overall.
Die Klamotten sind so gesehen einfach ein Zeichen dafür, dass du lang drin bist / Schwerverbrecher bist :)
