### ISSUE TITLE
Perlentaucher habens schwer

### ISSUE THREAD

**Issue by kingrobtv** [mexyn/statev_v2_issues#3666]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Jake Rush**
 Jake Rush

**Auftrittszeitpunkt (Datum / Uhrzeit)**
vom letzten großen Update bis jetzt

**Beobachtetes Verhalten**
 8 Stunden getaucht und 1 Perle gefunden

**Erwartetes Verhalten**
 bei 8 Stunden tauchen mind. ein paar mehr Perlen finden

**Schritte um den Fehler nachvollziehen zu können**
 tauchen gehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by QA-Pregon** [comment]
Wurde nichts verändert, is dann leider sehr unlucky gewesen.

**Comment by DerHessenTyp** [comment]
Wir waren zu zweit 3 Stunden angeln.
Meine Freundin nichts gefunden ich dafür in knapp 3 Stunden 2 Perlen gefunden. Denk das wieder so eine Glückssache. Finde zum Beispiel weniger Sammelkarten und Figuren. Sie dafür sicherlich schon um die 10.
