### ISSUE TITLE
Abladepunkt versetzen

### ISSUE THREAD

**Issue by adrosso** [mexyn/statev_v2_issues#3668]
Einen Wunderschönen guten tag, 

Ich habe da mal ein kleines anliegen was auf Dauer etwas mühselig wird. Es geht darum, denn Abladepunkt zu Versetzen.

Aktuell ist es so:

Fertigung: pf_Alta__4
Labor: pf_Alta__5
Gießerei: pf_Alta__6
Haben den Abladepunkt auf dem Parkplatz. (Rot eingekreist)

Während unser lager: pf_Alta__3 den Abladepunkt auf der Straße hat.(Grün eingekreist)

Zu meinem Anliegen, wäre es im möglichen das die Firmen zusammen gelegt werden und der Abladepunkt auf die Straße kommt?
Das erleichtert zum einen die Logistik und zum zweiten komme ich mit der Achse viel besser dahin und müsste nicht jedes mal rangieren. Durch denn Müll der da liegt, hinterlässt es auch jedes mal einen kleinen Schaden am Fahrzeug. Daher wäre der Abladepunkt auf der Straße für die Firmen am besten.

Liebe grüße, Isaac Reed

![Firman-ladepunkt](https://github.com/user-attachments/assets/1f487cff-28da-4dae-8086-392d7bcad287)

**Comment by SatyriaDine** [comment]
Also als erstes, zusammenlegen werden wir keine Abladepunkte mehr, die nicht schon zusammen sind. :) Ich kann mir das aber gerne mal anschauen und den Abladepunkt der 3 Firmen versetzen. :)

**Comment by adrosso** [comment]
Das wäre mehr als super Lieb, danke schön.
