### ISSUE TITLE
Waffe nicht wegsteckbar

### ISSUE THREAD

**Issue by ELPAJERO88** [mexyn/statev_v2_issues#3669]
**Character Name**
Dan_Kingston

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14.08.2024, 15:00 Uhr

**Beobachtetes Verhalten**
Im Ammunation gekaufte Waffe kann ausgerüstet und geladen, aber nicht weggesteckt werden, bleibt somit permanent in der Hand. Waffenrad ist ab dem Moment ebenfalls nicht mehr verfügbar. Waffe wird erst z.B. bei Einstieg ins Auto weggesteckt. In den Dienst gestempelt (BCSO) können Waffen auch weggesteckt werden, Waffenrad dort ebenfalls vorhanden.

Nachtrag: 
Relogg, PC Neustart etc. haben nicht geholfen. Mods sind nahezu keine installiert (Bodymod & Streetlights). Mit der Dienstwaffe besteht das gleiche Problem, sobald man nicht mehr im Dienst eingestempelt ist.

Nachtrag 2:
Problem bezieht sich ausschließlich auf das Wegstecken mit den Slots (1-9) und das Mausrad. TAB funktioniert. 

**Erwartetes Verhalten**
Bin davon ausgegangen, dass man Waffen auch als Zivilist mit dem Waffenrad (Mausrad) wegstecken kann.

**Schritte um den Fehler nachvollziehen zu können**
1. Waffe ausrüsten
2. Waffe ziehen
3. Waffe nicht mehr wegstecken können (außer Dienst)

**Optional: Video / Bilder des Fehlers**
Kann auf Wunsch angefertigt werden.

**Comment by SHaagmann** [comment]
Sind bodymods nicht verboten 👀

**Comment by ELPAJERO88** [comment]
Grad doppelt und dreifach gecheckt, hast Recht, is aber auch nich drin. Hatte schon richtig Arschwasser :D

**Comment by scootmar** [comment]
Bei Pistolen ist es so gewollt, dass sie nicht mit Mausrad oder Zahlentasten spielbar sind, sondern nur mit Tab.

**Comment by ELPAJERO88** [comment]
Ah okay, das war mir nicht bekannt, kannte es nur aus dem Dienst, wo es geht. Dann kann das ganze zu <3
