### ISSUE TITLE
Jobilot Hauler an Öl Achse anpassen (Geschwindigkeit)

### ISSUE THREAD

**Issue by SwissJokerTV** [mexyn/statev_v2_issues#367]
**Brian_Wagner**

**Zeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Fahrzeugpool wurde komplett überarbeitet. Wird so bleiben.
