### ISSUE TITLE
Bennys Werkstattsystem Defekt.

### ISSUE THREAD

**Issue by AtzeDejavu** [mexyn/statev_v2_issues#3670]
Ein Wunderschönen unser Werkstatsystem ist Defekt.

Hades Russo

Hades Russo und Personen die bei Bennys arbeiten.

Das ist der Punkt das ist mir selber vorletzte Woche aufgefallen und heute kam ein Mitspieler auch auf mich zu und meinte ich solle es mal melden.

Wenn wir ein Kunden eine Rechnung ausstellen und er es ablehnt ist es so das wir das System nicht weiter nutzen können. Der Mitarbeiter der die Rechnung ausgestellt hat muss dann immer neu connecten weil er sonst das System blockiert. Dazu kann der Kunde das Fahrzeug dann auch nicht nutzen solange der Mitarbeiter nicht neu connectet ist ( man kann das Fahrzeug nicht mal aufschließen).

Ja das wenn abgelehnt wird das System normal nutzbar ist. 

Video: https://www.youtube.com/watch?v=2yzHZKFzVDg

**Comment by simplycach** [comment]
Wissen wir, ist next Update fixed

**Comment by AtzeDejavu** [comment]
Du bist ein Schatz
