### ISSUE TITLE
Garage Casino

### ISSUE THREAD

**Issue by awesome1907** [mexyn/statev_v2_issues#3671]
Die Casino Garage ist seit heute verbugt. Sie lässt Trailer auf dem Kopf spawnen. Man hat dadurch keine Chance sie wieder einzuparken

**Comment by AdmiralState** [comment]
Um welche Art von Trailer handelt es sich den? Konnte mit keinem Trailer den gleichen Fehler reproduzieren

**Comment by QA-Pregon** [comment]
plus andere Frage, ist das mehrmals passiert oder hat der Anhänger dann die Garage blockiert?
@awesome1907

**Comment by TheOutburst** [comment]
gerne mit Video den Tracker wiedereröffnen, aber ich mach bis dahin hier erstmal zu, da nicht reproduzierbar
