### ISSUE TITLE
Fehlender Login-Button nach Charauswahl

### ISSUE THREAD

**Issue by Reggie987** [mexyn/statev_v2_issues#3673]
Reggie_Jennings

**Auftrittszeitpunkt (Datum / Uhrzeit)**
15.08. 13:13
15.08. 19:57
16.08. 12:30

**Beobachtetes Verhalten**
Fehlender Login Button

**Erwartetes Verhalten**
Transition von StateV kommt und führt zum Login-Button

**Schritte um den Fehler nachvollziehen zu können**
Spiel starten. Bei Fehlerauftritt ist ein Neustart erforderlich.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
2560x1440

**Optional: Video / Bilder des Fehlers**

![Screenshot 2024-08-16 123014](https://github.com/user-attachments/assets/97b4a068-68d0-4605-aa7f-3b3f9f6544ac)
![Screenshot 2024-08-15 195715](https://github.com/user-attachments/assets/91296743-561f-4ffe-840e-2237a304081c)
![Screenshot 2024-08-15 131327](https://github.com/user-attachments/assets/eb7460d3-e744-43a4-87da-49a130f18c49)

**Comment by QA-Pregon** [comment]
klappt es zwischendurch überhaupt oder ein dauerhafter fehler?
Falls Dauerhaft, schonmal probiert den Cache Ordner zu löschen von AltV?

**Comment by Reggie987** [comment]
Ja, du kannst einfach neustarten und es klappt. Hatte es seit gestern 3x nach dem Update. Vorher noch nie. Passiert auch keine 2x nacheinander.

Benutze aktuell keinerlei Mods

**Comment by QA-Pregon** [comment]
F8 sollte da eigentlich schon gehen, stand da schon irgendwas drin?

**Comment by QA-Pregon** [comment]
Ansonsten schick mal gern deine Log Dateien von den 3x

**Comment by Reggie987** [comment]
Hab ich in dem Moment glaub ich nicht versucht. Ich schau mal, ob ich's mit Metal gespeichert habe

**Comment by QA-Pregon** [comment]
wie gesagt ansonsten Log Datei, da steht alles wie in F8 drin

**Comment by stepz2k9** [comment]
Mir is das bisher immer nur passiert, wenn ich beim Reinladen in den LoginBildschirm rausgetabbt habe.

**Comment by QA-Pregon** [comment]
> Mir is das bisher immer nur passiert, wenn ich beim Reinladen in den LoginBildschirm rausgetabbt habe.

war bei mir tatsächlich auch immer nur dann so, aber hab vergessen das zu hinterfragen xD
Also @Reggie987 falls du beim einloggen gern raustabst, das am besten lassen

Ansonsten wäre mir ein fehlender Login Button neu

**Comment by Reggie987** [comment]
Kann ich so nicht mehr nachvollziehen, aber ja grundsätzlich kann das vorkommen. Ich achte mal drauf. Wenn das bekannt ist, ist der Log dann überflüssig? Ansonsten, brauchste einen der 3 kompletten client-logs zu dem Zeitpunkt denke ich mal?

**Comment by Reggie987** [comment]
[client_2024-08-16_12-27-43.log](https://github.com/user-attachments/files/16636631/client_2024-08-16_12-27-43.log)

**Comment by Reggie987** [comment]
![image](https://github.com/user-attachments/assets/522e73cb-ff22-4454-a130-ec0d8d4b9aa4)

Hab dran gedacht. Aber ich muss da irgendwie ganz unpassend raustabben. Hab ich aber eigentlich schon immer so gemacht und noch nie das Problem gehabt.

**Comment by QA-Pregon** [comment]
Gut ich glaub das hilft uns nicht weiter da, aber danke trotzdem
Wir schauen mal was wir machen können
Aber versuch trotzdem dran zu denken die 5 Sekunden nicht rauszutabben ^^

**Comment by QA-Pregon** [comment]
@Reggie987 wie oft ist es seitdem aufgekommen?

**Comment by Erumeldor** [comment]
@Pregon @Reggie987 
Wenn das beim raustabben immer auftritt, bitte nochmal genauer Beschreiben was wann wo, und Pregon gern dann intern aufnehmen :)

**Comment by QA-Pregon** [comment]
also bei mir passierts beim raustaben nicht mehr, dementsprechend keine Ahnung xD

**Comment by QA-Pregon** [comment]
Wir machen erstmal zu, sollte es nochmal extrem auffallen bitte bescheid sagen aber ich kann da aktuell nichts feststellen
