### ISSUE TITLE
Bitte um Entfernung "alter" Tankstelle am Werkstattgelände!

### ISSUE THREAD

**Issue by ManuelLadner** [mexyn/statev_v2_issues#3675]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Manuel_Turner**

**Jederzeit**

**Dach überlappt sich mit dem alten und sieht unschön aus. Auch am Boden sind teilweise Glasscherben die seither in der Luft schweben (alles auf den Bildern ersichtlich). Auch den Platz würden wir gern anders nutzen. Autos, Schlepper etc. hinstellen. Dieses Dach hat so keinen nutzen.**

**Würden uns freuen wenn ihr uns die Tankstelle entfernen könnt um den Platz für andere Dinge nutzen zu können, und die unschönen Überlappungen loswerden.**

**Hinfahren anschauen!**

**Egal**

**https://pic.statev.de/image/bild1.Hzf2Bc
   https://pic.statev.de/image/bild2.HzfNZB
   https://pic.statev.de/image/bild3.HzfbkR
   https://pic.statev.de/image/bild4.HzfAYT**

**Comment by TheOutburst** [comment]
Den Unterstand gänzlich weg machen wir nicht! Aber die Überreste der kaputten autos sowie die decals des alten Daches sind next update weg!
