### ISSUE TITLE
Feuerwerk

### ISSUE THREAD

**Issue by Asterix526** [mexyn/statev_v2_issues#3676]
Christian Big

Leider gibt es bei dem Feuerwerkssortiment einen Fehler, bei den Feuerwerksbatterien kann nur die Person es sehen die es auch zündet. Hier muss ein Fehler vor liegen. Bei dem Rest kann es jeder sehen. 

Fehler ist immer wieder, bereits auf jeder Veranstaltung an Verschiedenen Tagen das selbe Problem gehabt.

**Comment by QA-Pregon** [comment]
Ist uns bei der Carshow auch aufgefallen, wird soweit ich weiß versucht was dran zu machen

**Comment by Asterix526** [comment]
Oky, Danke euch. Habs bei jeder Veranstaltung gezündet und blieb immer nur für mich sichtbar, der Rest ist Perfekt und funktioniert. Ist speziell diese eine große Batterie 🙈Von meinem Telefon gesendet-------- Ursprüngliche Nachricht --------Von: Pregon ***@***.***>Datum: Sa., 17. Aug. 2024, 22:18An: eiksch/statev_v3_issues ***@***.***>Cc: Asterix526 ***@***.***>, Author ***@***.***>Betreff: Re: [eiksch/statev_v3_issues] Feuerwerk (Issue #3676)
Ist uns bei der Carshow auch aufgefallen, wird soweit ich weiß versucht was dran zu machen

**Comment by MarcelMuerto** [comment]
@Asterix526 
Dies ist beim letzten Updaten behoben worden.
Sollte es dazu weiterhin Probleme geben, dann bitte noch mal ein neuen Bug-Eintrag machen.

Liebe Grüße
Marcel Muerto
