### ISSUE TITLE
Fertigung: Fehler Konfiguration - Herstellung Verpacktes Partylicht

### ISSUE THREAD

**Issue by ZacCooperr** [mexyn/statev_v2_issues#3677]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Zac Connor

**Auftrittszeitpunkt (Datum / Uhrzeit)**

18.08.24  20:30 Uhr

**Beobachtetes Verhalten**

Bei der Herstellung von "Verpacktes Partylicht" erhält man folgende Meldung: Fehler in der Konfiguration der Produktion!

**Erwartetes Verhalten**

Produktion sollte starten, sofern man das Material hat 

**Schritte um den Fehler nachvollziehen zu können**

In einer Fertigung ein Verpacktes Partylicht herstellen

**Optional: Video / Bilder des Fehlers**

https://pic.statev.de/i/Hz1Crs.jpg

**Comment by TheOutburst** [comment]
fixed next update
