### ISSUE TITLE
Carlos Autoknacken funktioniert nicht.

### ISSUE THREAD

**Issue by ItsPaulAT** [mexyn/statev_v2_issues#3678]
**Character Name**
Patrick Alonso

**Auftrittszeitpunkt (Datum / Uhrzeit)**
18.08.2024 - 21 Uhr

**Beobachtetes Verhalten**
Bei Carlos kann man die Lockpick funktion nicht nutzen, das Fenster öffnet sich, jedoch kann man das Lockpick nicht bewegen, nicht mit WASD oder Pfeiltasten (siehe Clip)

**Erwartetes Verhalten**
Man sollte das Auto knacken können, also auch das Lockpick bewegen können.

**Schritte um den Fehler nachvollziehen zu können**
Carlos Auftrag für "Auto" Annehmen --> Auto aus garage holen --> "Aufbrechen" drücken --> Dann kann man das ganze nicht bewegen. Auch reconnect hilft nicht.
Bei anderen Leuten geht es (keine Ahnung warum)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
https://youtu.be/JkI22mw4QrM

**Comment by Pregon** [comment]
War CAPSLOCK aktiviert?
Wenn ja lag es daran ^^

**Comment by QA-Pregon** [comment]
Nach Absprache gings nachm NVE Update wieder
