### ISSUE TITLE
Cash bei Knast Missionen

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3679]
Früher gab es oben beim Gefangenen wo man Missionen annimmt nach abschließen immer etwas Cash, nun gibts das nicht mehr.
Bug oder Feature? ;D

**Comment by simplycach** [comment]
Ist so gewollt :)

**Comment by Statev-Bonsai** [comment]
buuuuuuuuuuuuuuuuuuuuuuuuuuuuh
