### ISSUE TITLE
StateNET im Dienst Bug

### ISSUE THREAD

**Issue by Mr-Chris-VRTY** [mexyn/statev_v2_issues#368]
Seit der neusten Änderung werden ja mit grünem Punkt Personen im Dienst angezeigt. Außerdem sieht man im StateCOM auf dem Dashboard alle Personen im Dienst. Das Problem daran ist jedoch, dass diese Personen solange angezeigt werden, wie sie eingestempelt sind. D.h. im Team und auch im StateCOM sieht man Personen, die gar nicht online sind (vermutlich weil sie eingestempelt sich ausgeloggt haben). Hier wäre eine zusätzliche Abfrage, ob der Spieler online ist sehr sinnvoll, da man ansonsten nicht erkennt, welcher Kollege tatsächlich anwesend ist und welcher nicht.

**Comment by its4l3x** [comment]
Habs geändert und angepasst. Ist im Laufe des Tages auf dem STATENET & STATECOM
