### ISSUE TITLE
Kauf eines Hotels nicht möglich

### ISSUE THREAD

**Issue by ingo-lorenz** [mexyn/statev_v2_issues#3680]
Character: 
Peter_Fichtner

**Auftrittszeitpunkt (Datum / Uhrzeit)**
18.08.2024 ca. 18 Uhr

**Beobachtetes Verhalten**
Beim Kaufvorgang eines Hotels "PillboxHill_Flat_4_3" passiert nix. Keinerlei Rückmeldung zum Kauf, keine Abbuchung usw.
Kontodeckung ist vorhanden.

**Erwartetes Verhalten**
Der Besitz des Objekt soll an den Charakter übergehen und der angezeigte Preis soll vom Konto eingezogen werden.

**Schritte um den Fehler nachvollziehen zu können**
Einfach versuchen das Hotel zu kaufen.

**Comment by QA-Pregon** [comment]
Hattest du vorher schonmal einen anderen Appartmentkomplex oder ein eigenes Haus?

**Comment by ingo-lorenz** [comment]
Hat sich durch einen Fix von euch erledigt und kann geschlossen werden.

Ingo
