### ISSUE TITLE
Auto wird in Haus ohne rechte eingeparkt

### ISSUE THREAD

**Issue by eckbert58** [mexyn/statev_v2_issues#3681]
**Character Name**
Edoardo Colombo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Beobachtetes Verhalten**
Bin aus langeweile bei der Villa meines alten Chars (Hector Cortez) vorbeigefahren und hab ausversehen e gedrückt.
Jetzt steckt meine Karre in der Hausgarage und ich bekomme sie nicht raus,

**Erwartetes Verhalten**
Dass sich das Auto nicht auf fremden Grundstücken einparken lässt wenn man e drückt

**Schritte um den Fehler nachvollziehen zu können**
Ich weiß nicht ob es an meinem alten char lag, aber evtl mit einem neuen char versuchen in die garage eines alten chars einzuparken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
egal

**Comment by Erumeldor** [comment]
Wir können das leider null nachvollziehen oder reproduzieren.
Wenn sowas nochmal auftritt, bitte hier drunter kommentieren. :)
