### ISSUE TITLE
Item "Leuchterblume" nicht placable

### ISSUE THREAD

**Issue by stepz2k9** [mexyn/statev_v2_issues#3682]
**Character Name**
Kelani_Larsson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.08. / 18:10

**Beobachtetes Verhalten**
Item "Leuchterblume" kann nicht geplaced werden. Bei Rechtsklick drauf bekommt man gar nicht erst das Menü zum Platzieren. Man steht einfach da.
Das Item ist dann aus der Tasche weg, wird aber nicht angezeigt. Wenn man dann etwas neues placed, ist das Item wieder in der Tasche.

**Erwartetes Verhalten**
Item ist aufstellbar.

**Schritte um den Fehler nachvollziehen zu können**
Item kaufen, rechtsklick, placen, Inventar angucken, neues Item placen, Inventar wieder angucken.

**Comment by TheOutburst** [comment]
next update "fixed"
