### ISSUE TITLE
Menü "Spielerlautstärke" wird nicht angezeigt

### ISSUE THREAD

**Issue by l1llean** [mexyn/statev_v2_issues#3683]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```
Character Name: Alejandra_Quinones

**Auftrittszeitpunkt (Datum / Uhrzeit)**
unter anderem am 18.08.  ~22:07 Uhr

**Beobachtetes Verhalten**
Sobald ich versuche das Menü für "Spielerlautstärke" zu öffnen, kommt kein neues Overlay und meine Maus wird gezeigt. Im weiteren Verlauf habe ich dann immer wieder das Problem, dass meine Maus angezeigt wird In-Game & ich mich nicht weiter bewegen kann. Derzeit konnte ich es nur lösen, wenn ich mit U mein Fungerät rausgeholt und wieder versteckt habe.

**Erwartetes Verhalten**
Menü für Spielerlautstärke wird angezeigt.

**Schritte um den Fehler nachvollziehen zu können**
F7 -> Spielerlautstärke -> kein angezeigtes Menü

**Optional: Video / Bilder des Fehlers**

https://github.com/user-attachments/assets/65d95150-a661-4c6b-9b3e-60ea6a1203d0

**Comment by QA-Pregon** [comment]
Klappt das ganze nachm Relog wieder oder ist das aktuell ein dauerhaftes Problem bei dir?

**Comment by l1llean** [comment]
also bis jetzt hab ich's mit Relogg noch nicht getestet, aber bewusst ist es jetzt zweimal hintereinander jeweils Abends aufgetreten, weil ich halt nen Spieler lauter machen wollte. Kann das Ganze gerne nochmal testen, aber bin erst in ner Woche wieder zu Hause haha

**Comment by Erumeldor** [comment]
Falls sowas reproduzierbar ist, bitte konkreter melden wie - aktuell ist das sonst für uns leider nicht nachvollziehbar.

Workaround, wenn mal ein Menü nicht läd -> "ESC". (Bitte trotzdem melden wenns häufiger auftritt!)
