### ISSUE TITLE
Tuning / Repair script blocked

### ISSUE THREAD

**Issue by FLVFFY1** [mexyn/statev_v2_issues#3685]
Cesar Kingston

Auftrittszeitpunkt 
seit einiger zeit - immer

Beobachtetes Verhalten
Wenn man das Tuning / Repair script startet, den kunden zur Zahlung bittet, diese abgelehnt wird, ist das auto komplett gesperrt, man kann nicht neu anfangen und muss reloggen

Erwartetes Verhalten
nicht das was passiert :D

Schritte um den Fehler nachvollziehen zu können
Tuning / rep iwas mit dem script starten, rechnung ausstellen, rechnungsempfänger lehnt zahlung ab

**Comment by SatyriaDine** [comment]
ist im nächsten Update fixed :)

**Comment by Pregon** [comment]
#3760

**Comment by QA-Pregon** [comment]
#3670
