### ISSUE TITLE
Waffenlackierung Fehlerhaft

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3686]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

AJ
**Auftrittszeitpunkt (Datum / Uhrzeit)**

19.08 21:30
**Beobachtetes Verhalten**

Beim Waffenlackieren bleibt die Vorschau bestehen, wenn man die Waffe wegsteckt und anschließend das Menü schließt.
**Erwartetes Verhalten**

Die Waffe wird wie vor der Vorschau
**Schritte um den Fehler nachvollziehen zu können**

Zum NPC gehen
Waffe Lackieren
Waffe wegstecken
Menü Schließen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://medal.tv/games/gta-v/clips/ivvzsACIeSlqTuGrP/d1337Qmvxz12?invite=cr-MSxSaHQsMTk1NTEzMTMzLA

**Comment by QA-Pregon** [comment]
Nächstes mal bitte den Clip vorher und danach die Waffe einmal ordentlich in die Kamera halten
Ich erkenn da bei der Videoqualität gefühlt nichts am Ende weil alles auf schwarzen Hintergrund ist xD

'+ aktuell kann ich das nicht reproduzieren deswegen brauch ich einmal den Namen von der Waffe ^^

**Comment by QA-Pregon** [comment]
Ok Frage hat sich erledigt, hab gefunden woran es liegt ^^
Bezieht sich nur auf die Folierung soweit ich das sehe

**Comment by QA-Pregon** [comment]
Next Update
