### ISSUE TITLE
Oberteil geht nicht in den Kleiderschrank

### ISSUE THREAD

**Issue by Falk-Alers** [mexyn/statev_v2_issues#3688]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Schott Winchester**

Kelly Winchester

**Auftrittszeitpunkt (Datum / Uhrzeit)**

20.08.24 ca. 21:27Uhr

**Beobachtetes Verhalten**

Das Oberteil "[F] Purple Rachel Top" kann nicht in den Kleiderschrank verschoben werden

**Erwartetes Verhalten**

Oberteil passt in den Schrank

**Schritte um den Fehler nachvollziehen zu können**

Oberteil kaufen, in schrank packen (wollen)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![BugTop](https://github.com/user-attachments/assets/f58b8879-424c-40e3-a03d-b68515889476)

**Comment by 2FaceOriginal** [comment]
Gleiches Problem bei dem [M] Black Basic Shirt

**Comment by ySimbaa** [comment]
fixed
