### ISSUE TITLE
Ressourcenexport: Man kann nur 999 l eintippen, nicht 1200 l

### ISSUE THREAD

**Issue by AtreuX** [mexyn/statev_v2_issues#369]
**Character Name**
Tom_Clark

**Zeitpunkt (Datum / Uhrzeit)**
22.11.2020 gegen 09:15

**Beobachtetes Verhalten**
Ich wollte bzw. habe Diesel über den Ressourcenexport exportieren wollen. Ich konnte aber nicht den gesamten Tankinhalt der Achse (1200 l) exportieren, sonden nur maximal 999 l . Offenbar akzeptiert das Feld fälschlicherweise nur 3 Ziffern anstatt 4?!

**Erwartetes Verhalten**
Export des gesamten Kofferrauminhaltes (Tankachse: 1200 l) möglich.

**Schritte um den Fehler nachvollziehen zu können**
1) Mit einer Tankachse (gefüllter Kofferrauminhalt > 999 l) zum Ressourcenexport fahren
2) Zu versuchen diesen Kofferrauminhalt > 999 l zu verkaufen

**Optional: Video / Bilder des Fehlers**
https://youtu.be/1_FBgS3pMgM

**Comment by eiksch** [comment]
fixed next update
