### ISSUE TITLE
Knox--> Tattooläden

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3690]
Ich habe die letzten Tage etliche Tattooläden für Knox leergeräumt, ich habe kein einziges Item bei den Punkten gefunden, also ganix ^^
Habe auch eine 10% höhere Chance was zu finden, trozdem nix...

Denke das sollte nicht so sein, eventuell müsste man den Item Pool/Chance höhersetzen...

**Comment by Statev-Bonsai** [comment]
In der Schmelze, Schlachterei und in der Weberei ist die Ausbeute bzw der Pool auch gar nicht vorhanden oder die wahrscheinlichkeit zu gering... 
Frisöre und Baumärkte passen...

**Comment by QA-Pregon** [comment]
Findest du gar nichts oder sehr wenig?

**Comment by Statev-Bonsai** [comment]
sehr sehr sehr sehr wenig (habs die letzten tage bis heute weiterhin gemacht), in frisörläden und baumärkten bekommt man sehr viel mehr items...

**Comment by TheOutburst** [comment]
Next Update haben wir da nen paar Sachen gemacht, wirst mehr finden
