### ISSUE TITLE
Falsche beschriftung von Nighttops und Rachel Top v2 nicht in Kleiderschrank legbar

### ISSUE THREAD

**Issue by xXCoCoNuTx3** [mexyn/statev_v2_issues#3691]
**Character Name**
Valeria Martinelli 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.8 7:15 ca aber denke mal immer

**Beobachtetes Verhalten**
Nighttops auswählen z.b Schwarz heißt im Laden aber Rot

**Erwartetes Verhalten**
Farben sollten auch zum richtigen oberteil passen

**Schritte um den Fehler nachvollziehen zu können**
Kleiderladen besuchen, Nighttops auswählen 

**Optional: Video / Bilder des Fehlers**
![Screenshot_1](https://github.com/user-attachments/assets/e9f9160b-9e77-4472-9321-59f31fdaa53d)
![Screenshot_2](https://github.com/user-attachments/assets/a38184dd-34e5-4a4d-9454-bc03c7c12df5)
![Screenshot_3](https://github.com/user-attachments/assets/2a4db6ca-cfbe-41e2-9d85-e18e87aff72d)
![Screenshot_4](https://github.com/user-attachments/assets/2e270695-ecef-4f8b-a322-7dbd1d9cbb3d)
![Screenshot_5](https://github.com/user-attachments/assets/29ea6d66-55f9-473e-bf86-b7d93fc36167)
![Screenshot_6](https://github.com/user-attachments/assets/5d067c47-f0f4-4101-abd6-aa21bb681215)

Desweiteren kann man die Rachel Top V2 nicht in den Kleiderschrank legen

![Screenshot_7](https://github.com/user-attachments/assets/48e45fbe-f28f-4b78-b637-d3ddf309a4dc)

**Comment by ySimbaa** [comment]
Nächstes Update fixed
