### ISSUE TITLE
Inventar locked in Spiegelreflex

### ISSUE THREAD

**Issue by JohnnyNobody98** [mexyn/statev_v2_issues#3693]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Johnathan_Maedows

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.08. 19:00

**Beobachtetes Verhalten**
Beim Nutzen der Spiegelreflexkamera bleibt das Inventar Overlay aktiv und lässt sich weder mit ESC noch übers X Schließen
X-Menü ebenfalls geblockt.
Animation beenden Tastenbelegung beendet die Kameraanimation, und danach ist es möglich das Invetar zu schließen
Unbekannt ob nur bei Spiegelreflex oder ob auch bei anderen Kameras der Fall

**Erwartetes Verhalten**
Inventar schließt sich selbstständig oder lässt sich manuell schließen in der Kamera-Ansicht

**Schritte um den Fehler nachvollziehen zu können**
Inventar öffnen, Kamera auswählen- rechtsklick, Fotografieren
Animation mit "," beenden, Inventar schließen

**Optional: Video / Bilder des Fehlers**
https://i.gyazo.com/a3d34c67d64dd48476d1c0ed51000b6e.mp4

**Comment by QA-Pregon** [comment]
Teste bitte nochmal, ich bekomm es weder im Gebäude, noch draußen reproduziert

**Comment by JohnnyNobody98** [comment]
Leider keine Änderung. https://i.gyazo.com/9407a87e0c3ffbb7ee56b10f5c1a1b42.mp4
Hab soweit die Grafik Mods runtergehauen, dass ich ne cleane GTA Version habe (wie erwartet nichts gebracht)
Fehler tritt im Gebäude und draussen auf
Kann ich irgendwie helfen?

**Comment by JohnnyNobody98** [comment]
Durchs Update hat sich das Problem gelöst
