### ISSUE TITLE
Schrittzähler zählt auch beim Fahren

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3695]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

AJ
**Auftrittszeitpunkt (Datum / Uhrzeit)**

22.08.2024 17:20
**Beobachtetes Verhalten**

Beim Fahren werden Schritte gezählt
**Erwartetes Verhalten**

Schritte werden nicht gezählt
**Schritte um den Fehler nachvollziehen zu können**

Schrittzähler öffnen
Mitm Auto durch die gegend fahren
Mehr schritte haben
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://medal.tv/games/gta-v/clips/iwFBb85ZyVJOev3lg/d1337hDKv0m5?invite=cr-MSxGWEMsMTk1NTEzMTMzLA

**Comment by QA-Pregon** [comment]
Its not a bug, its a feature xD

Ja also ist uns auch aufgefallen, ich frag mal Rod ob er das noch ändern wollte oder nicht ^^

**Comment by Stiefel911** [comment]
selbige ist auch, aus dem Haus gehen und ins Haus gehen.. Apartment wird gewiss das selbige sein  etc. ;)

**Comment by TheOutburst** [comment]
Porten sollte fixed sein, beim Auto fahren auch, aber ich mach noch kein Solved dran weil QA nochmal drüber geht

**Comment by TheOutburst** [comment]
QA sagt ist solved
