### ISSUE TITLE
Hätte gern ne Garage

### ISSUE THREAD

**Issue by StateV2Marie** [mexyn/statev_v2_issues#3697]
Hallo hätte gern eine Garage hab gesehen das mein nachbar gegen über eine hat nu hätte ich auch gern eine der platz dafür is zu 100 % vorhanden und ich hab den wunsch ob ihr so lieb sein könntet mir auch eine zu machen. das bild pack ich mit im anhang. 
![Screenshot_30](https://github.com/user-attachments/assets/f00d394d-4143-4830-a015-002d1e9e02d7)

Die Adresse vom haus is  Procopio Drive 5     Hash house_Paletobay_5

wenn das ginge wäre echt toll vielen lieben dank im vorraus. 

mfg: Josi Rose

**Comment by SatyriaDine** [comment]
Hey hey, hast zum nächsten Update eine Garage am Haus. :)
