### ISSUE TITLE
IFruit Max Model fehlerhaft

### ISSUE THREAD

**Issue by 2FaceOriginal** [mexyn/statev_v2_issues#3699]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Dre_Cones
**Auftrittszeitpunkt (Datum / Uhrzeit)**

-
**Beobachtetes Verhalten**

In den Händen anderer Spieler wird das IFruit Model angezeigt, welches man selber ausgerüstet hat.
**Erwartetes Verhalten**

Es sollte das Model angezeigt werden, welches der Spieler selbst ausgerüstet hat
**Schritte um den Fehler nachvollziehen zu können**

Mit zwei Personen unterschiedliche IFruit Max's ausrüsten und schauen wem welches angezeigt wird
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

-
**Optional: Video / Bilder des Fehlers**

-

**Comment by TheOutburst** [comment]
next update fixed
