### ISSUE TITLE
Überfall ohne Maske 

### ISSUE THREAD

**Issue by KoenigJustin** [mexyn/statev_v2_issues#3700]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Elijah_Ray

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit dem Update 

**Beobachtetes Verhalten**
Aktuell können Läden mit einem Ring, welcher auf dem Maskenslot liegt, überfallen werden. 

**Erwartetes Verhalten**
Es sollte nur mit einer Maske gehen. 

**Schritte um den Fehler nachvollziehen zu können**
Mistique Mission starten und den Laden mit einem Ring, welcher auf dem Maskenslot liegt, überfallen.

**Comment by QA-Pregon** [comment]
Da ich von Ringen keine Ahnung hab, mit welchen geht das?

**Comment by SHaagmann** [comment]
> Da ich von Ringen keine Ahnung hab, mit welchen geht das?

Gibt welche die auf dem Masken Slot liegen und andere (Vergessen welcher Slot das war). Sind die Ringe mit [Mask] tag

**Comment by Statev-Bonsai** [comment]
Den Bug kann ich bestätigen, ist mir heute auch aufgefallen...

**Comment by Statev-Bonsai** [comment]
![Screenshot_11](https://github.com/user-attachments/assets/a383564f-4209-406e-b362-6fbbea0361be)
