### ISSUE TITLE
Kette / Ohringe

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3701]
Bei anlegen der AK-47 Flex Kette werden die Ohrringe Platin Hoop Set Beidseitig unsichtbar..

**Comment by Statev-Bonsai** [comment]
![Screenshot_5](https://github.com/user-attachments/assets/a5e48c0d-69f4-47fa-8a39-c479b1400191)

**Comment by stepz2k9** [comment]
Da kann State nicht viel machen, das ist ein GTA-eigenes Problem. Liegen auf dem selben Anzeigeslot.

**Comment by Statev-Bonsai** [comment]
sicher? weil bei anderen ohrringen ist das nicht der fall ^^
![Screenshot_6](https://github.com/user-attachments/assets/b5f290b4-8265-47ee-bcb7-6cd5aaecef1b)

**Comment by stepz2k9** [comment]
Ja, sicher. Wir Frauen haben auch einige Ketten, die Ohrringe verschwinden lassen. Ketten liegen auf der Teef-Kategorie. Manche Ohrringe auch. Andere Ohrringe liegen in der Ears-Kategorie. Die lassen keine Ketten verschwinden.

Könnte höchstens sein, dass, wenn es modded Ohrringe sind, die auf ears umgeschrieben werden können. Oder auf Mask. Aber das klappt auch nicht immer.

Modded Zeug ist nur optisch ein Segen. Technisch ist es ein absoluter Fluch. 😅

**Comment by ySimbaa** [comment]
Das was @CaleighRhodes sagt :)

**Comment by Statev-Bonsai** [comment]
versteh nur bahnhof ;D aber wird schon passen. lol

**Comment by stepz2k9** [comment]
> versteh nur bahnhof ;D aber wird schon passen. lol

Deshalb hatte ich in meiner ersten Antwort auf die Erklärung verzichtet, aber du wolltest mir ja nicht glauben :P

**Comment by SHaagmann** [comment]
> versteh nur bahnhof ;D aber wird schon passen. lol

Manchmal liegen die Dinger auf dem gleichen Klamotten Slot (Technischer nicht UI) und überschreiben sich, da nur eine Sache pro Klamottenslot angezeigt werden. So Grob gesagt.

**Comment by QA-Pregon** [comment]
cant do anything here
