### ISSUE TITLE
Abladepunkt Verschiebung

### ISSUE THREAD

**Issue by DeXxXTar** [mexyn/statev_v2_issues#3703]
Grüße und zwar wollte ich nachfrage ob es möglich wäre meine Abladepunkt an meine Firma zu verlegen? ( würde auch eine andere Farbe gehen die besser zu sehen ist als schwarz ich hab echt Probleme dies immer zu erkennen nur wenn möglich? ) ( Dunkles blau oder so ähnlich aber nur wenn möglich )

Vorher:
![Abladeplatz Vorher](https://github.com/user-attachments/assets/44de02d4-19fe-4604-9cc0-3c62729b2dc7)

Nachher:
![Neuer Abladeplatz](https://github.com/user-attachments/assets/5e66862c-b798-44be-b24f-12c980c7b1df)

Firmen Hash:
![Firmen Hash 2024-08-18 205009](https://github.com/user-attachments/assets/3e54d6d9-f934-4697-88b1-5392b6347230)

**Comment by SatyriaDine** [comment]
Hey hey, dein Abladepunkt ist zum nächsten Update ein wenig verschoben nun sollten Auflieger etc nicht mehr an dem Vordach kratzen ^^
