### ISSUE TITLE
Kleidungsstücke sind Verändert

### ISSUE THREAD

**Issue by Tenextrus** [mexyn/statev_v2_issues#3704]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name** John_Doss

**Auftrittszeitpunkt (Datum / Uhrzeit)** 12:40 Uhr 25.08.2024

**Beobachtetes Verhalten**
 Verschiedene Kleidung stücke sind verändert, der Boiler Outfit ist ein Rocker Outfit, und die Maske ist eine komplette Haloween Maske in Orange

**Erwartetes Verhalten**
 bei der "[Maske] Schwarzer Neck Gaiter" soll die maske nur bis zur Nase bedeckt sein 
sowie ein Fehler beim Anziehen des Anzuges "[M] Brauner Boiler Suit (A)" ist das Kleidungsstück ein Rocker Outfit. Das Richtige Outfit hierbei soll ein Brauner normaler Arbeiter Anzug sein.

**Schritte um den Fehler nachvollziehen zu können**

Bei den Kleidungsstücken ziehst du sie einfach an 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
 
![Screenshot (9)](https://github.com/user-attachments/assets/7e359448-9803-40ca-9d5c-781b53790fe8)
![Screenshot (10)](https://github.com/user-attachments/assets/a3e2ab96-df1c-4673-a81c-8ff6a54260a6)

**Comment by ySimbaa** [comment]
[Maske] Schwarzer Neck Gaiter kann ich so nicht bestätigen. Gerade aufm Live getestet, da ist alles normal. 
Boiler gucke ich mir an. Ansonsten kann ich dir empfehlen mal die Cache zu löschen.

**Comment by QA-Pregon** [comment]
Kann ich beides auch nicht bestätigen, einmal bitte machen was Simba sagt, sollte das Problem weiterhin aufkommen bitte nochmal aufmachen oder per Ticket melden
