### ISSUE TITLE
Garage Bourton Pounder steckt fest

### ISSUE THREAD

**Issue by Jano1993** [mexyn/statev_v2_issues#3705]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Devon Scherdinger**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
26.08,24  Uhrzeit 8 Uhr 30

**Beobachtetes Verhalten**
Beim Ausparken meines Pounder Custom Stecke er erneut in der Wand und bekam dadurch einen roten Motor es handelt sich dabei um die Garage Burton beim ehemaligen Gerichtsgebäude. Es jetzt schon das 2te mal passiert

**Erwartetes Verhalten**
Den Ausparkspunkt so verschieben das man gefahrlos ausparken kann 

**Schritte um den Fehler nachvollziehen zu können**
Einen Pounder Custom einparken und dann wieder ausparken

hier ist auch ein bild dazu o er festhängt     nur das er jetzt grade sich befreit ha t

https://pic.statev.de/image/H3IoDT
![20240826083006_1](https://github.com/user-attachments/assets/af034750-5d39-401f-a68d-d30b5cd2a45e)

**Comment by SatyriaDine** [comment]
Hey hey, ist mit dem nächsten Update gefixt. :)
