### ISSUE TITLE
Unsichtbare Wand am Autohaus

### ISSUE THREAD

**Issue by OnkelHomie** [mexyn/statev_v2_issues#3706]
**Alexander_Jones**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Aufgefallen am 27.08.24 um 9:30

**Beobachtetes Verhalten**
Wollte für die Crimeaufträge das Autohaus (Mad Wayne Thunder Dr. 252)betreten. Die Türen/Tore öffnen zwar, aber man läuft gegen eine unsichtbare Wand.

**Erwartetes Verhalten**
Das man das Autohaus betreten kann

**Schritte um den Fehler nachvollziehen zu können**
Zum Autohaus gehen und durch die Türen/Tore laufen

**Optional: Video / Bilder des Fehlers**
![Bild_2024-08-27_095942133](https://github.com/user-attachments/assets/ee087552-d324-4d8c-aca3-97e697734c81)

**Comment by simplycach** [comment]
Spielst du mit Grafikmods ? 

Wenn du NVE hast liegt daran das Problem, da können wir nichts dran machen leider.

**Comment by OnkelHomie** [comment]
Okay das erklärt es dann. Habs gestern runtergeschmissen und seitdem nicht noch einmal getestet
