### ISSUE TITLE
Tankvolumen unterschied zwischen Tipper und Rubble

### ISSUE THREAD

**Issue by Dirk-Frosch** [mexyn/statev_v2_issues#3707]
Dirk_Frosch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
28.08.2024 14:30 Uhr

**Beobachtetes Verhalten**
Mir ist aufgefallen, das der Brute Tipper 2-Axle ein Tankvolumen von 350 Litern hat und der Jobuilt Rubble, der doppelt so groß ist wie der Tipper nur 200 Liter

**Erwartetes Verhalten**
Eventuelle Anpassung des Tankvolumens

**Comment by SatyriaDine** [comment]
Habs mal angepasst. :)

**Comment by Dirk-Frosch** [comment]
Super Danke
