### ISSUE TITLE
Hotel/Apartment Werbung als Mitarbeiter nicht möglich

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#3708]
Hi, wie im Titel, es ist nicht möglich als Mitarbeiter Werbung zu schalten. Alle Rechte sind vorhanden. 
Gibt keine Fehlermeldung, es steht einfach nur dem Besitzer zur Auswahl. 

V2 war das noch möglich mMn.

**Comment by QA-Pregon** [comment]
Korrigiere mich wenn ich falsch liege, aber gibst überhaupt die Berechtigung Werbung bei Apartmentkomplexen?

**Comment by QA-Pregon** [comment]
Wait dafür gibt's keine Berechtigung. Ich frag ma schnell was nach

**Comment by rodistic** [comment]
Ayy Gude,

next update fixed
