### ISSUE TITLE
Ranch Interior Möbel durchlaufbar

### ISSUE THREAD

**Issue by DrJaneX** [mexyn/statev_v2_issues#3709]
Jane Mei

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Charakter kann durch Möbel laufen im Interior der Ranch

**Erwartetes Verhalten**
Das die Möbel ein festes nicht durchlaufbares Objekt sind

**Schritte um den Fehler nachvollziehen zu können**
Ins Objekt laufen im Interior

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
2650x1440 (2k)

**Optional: Video / Bilder des Fehlers**

![20240829182700_1](https://github.com/user-attachments/assets/c117764f-6dca-46e4-934b-8f638d697ce2)
![20240829182711_1](https://github.com/user-attachments/assets/2539d6b1-e73d-44cd-98cb-c1e6af8e65cd)
![20240829182717_1](https://github.com/user-attachments/assets/acdd1c0f-099d-49e7-ba5c-4f503c1c7bb9)
![20240829182722_1](https://github.com/user-attachments/assets/b92f85ff-ae13-4b97-adca-09b23c96ceef)
![20240829182730_1](https://github.com/user-attachments/assets/8d6ff165-ba5b-48eb-95d8-f9a1418509ae)
![20240829182737_1](https://github.com/user-attachments/assets/7ce0701f-aff7-45cb-a963-acee271f53db)

das sind nur einige Beispiele, 90% der Möbel können durchlaufen werden

**Comment by SHaagmann** [comment]
War schon zu V2 so liegt am Interrior glaube ich

**Comment by simplycach** [comment]
Jap wie Sven geschrieben hat es liegt am Interior, vmtl lässt sich da auch nichts machen.
