### ISSUE TITLE
F10 zeigt nicht alle Personen an

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#371]
**Character Name**
Jannik_Datsch

**Zeitpunkt (Datum / Uhrzeit)**
22.11 01:00

**Beobachtetes Verhalten**
Beim Drücken von F10 wurden mir nicht alle im Umkreis befindlichen Personen angezeigt. 

Ich war Beifahrer:  Mein Fahrer wurde nicht angezeigt und eine Person im anderen Fahrzeug auch nicht, die hätte in meinem Umkreis sein müssen. Nur eine Person auf der anderen Seite des anderen Autos wurde angezeigt.  Die war aber am weitesten von allen weg, sodass die anderen hätten auch angezeigt werden müssen.

Zu dem Zeitpunkt standen wir und das andere Fahrzeug nebeneinander.

**Erwartetes Verhalten**

Es sollten alle im Umkreis befindlichen Personen beim Drücken von F10 angezeigt werden.

**Schritte um den Fehler nachvollziehen zu können**
F10 drücken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920-1080

**Optional: Video / Bilder des Fehlers**
leider keines gemacht.

**Comment by its4l3x** [comment]
Kann sein das du in einer dieser 0.000001% Fälle gefallen bist, wenn ein Limit erreicht wurde. Gegen solche Limits können wir wenig machen.

Wiederrum schließe ich das aber mal.
