### ISSUE TITLE
Fehlendes Fahrzeugverschrottungmenü

### ISSUE THREAD

**Issue by glb11** [mexyn/statev_v2_issues#3710]
**Jens_Holt**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Zeit Start von V3 

**Beobachtetes Verhalten**
Sobald man an der Tür den Button Fahrzeugrecycling drückt schließt sich das Tür Menü (was ok ist) aber dann öffnet sich kein Fahrzeugrecycling Menü

**Erwartetes Verhalten**
Das Fahrzeugrecycling Menü öffnet sich und damit wieder möglich

**Schritte um den Fehler nachvollziehen zu können**
an einen Recyclinghof gehen und Menü öffnen

**Optional: Video / Bilder des Fehlers**
](https://youtu.be/l8jYxXBGF7U)

**Comment by simplycach** [comment]
Wie viel KM hat das Fahrzeug was du verschrotten möchtest ?

**Comment by glb11** [comment]
ü 5k  km

bei v2 ging das Menü unabhängig vom km auf   man hat nur nichts groß bekommen

**Comment by BobbyCarsten** [comment]
Würde mich auch interessieren weil hab nen Fahrzeug was nicht über mich läuft was 16k km hat und da wäre das mal ganz gut zu wissen :)

**Comment by glb11** [comment]
> Würde mich auch interessieren weil hab nen Fahrzeug was nicht über mich läuft was 16k km hat und da wäre das mal ganz gut zu wissen :)

bei v2 ging das nur wenn der Inhaber des Fahrzeuges vor Ort ist

**Comment by simplycach** [comment]
Problem besteht anscheinend nur bei dem Bravado Youga Classic 4x4.

**Comment by epichalt** [comment]
Ist das Leasing denn abbezahlt?

**Comment by glb11** [comment]
Ja das Leasing ist komplett fertig

**Comment by Erumeldor** [comment]
Ich denke das sollte fixed sein, wir hatten da ein paar Bugs im Recycling.
