### ISSUE TITLE
Hausgarage nicht nutzbar/belegt

### ISSUE THREAD

**Issue by kingrobtv** [mexyn/statev_v2_issues#3711]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Jake Rush**

Jake Rush

**Auftrittszeitpunkt (Datum / Uhrzeit)**
31.08.24 Uhrzeit 00:30

**Beobachtetes Verhalten**
 Haus gekauft (Hash: house_SandyShores_59 ) und Garage/Stellplatz ist nicht nutzbar. Zeigt immer an Garage ist voll. Wenn man übers Tablet schaut oder am Haus selbst werden keine Fahrzeuge angezeigt 

**Erwartetes Verhalten**
 Garage nutzen zu können 

**Schritte um den Fehler nachvollziehen zu können**
Zur Garage/Stellplatz fahren und versuchen einzuparken  

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by QA-Pregon** [comment]
Mach da bitte ansonsten auch mal ein Ticket im Discord auf-
Wenn da fremde Fahrzeuge drinstehen kann man dir da am besten helfen

(Wird nach Rücksprache auf DC per Ticket angefragt und im Notfall wieder aufgemacht)

**Comment by QA-Pregon** [comment]
Problem:
Garagenplätze auf 0 gesetzt

**Comment by SatyriaDine** [comment]
Next update fixed :)
