### ISSUE TITLE
UI Stuck im Restaurant

### ISSUE THREAD

**Issue by RyanTears** [mexyn/statev_v2_issues#3712]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Ryan Tears**

**31.8.2024 und davor auch schon !**

**Restaurant UI schließt nicht und lässt sich auch durch das betätigen des Schließen Buttens nicht Schließen**

**ach Abgabe der Bestellung, sollte sich die UI schließen.**

**So oft dem Restaurant Kohle in die Kasse spülen bis der Fehler auftritt.**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**
![Hüftgold](https://github.com/user-attachments/assets/88ea48b1-24c3-412f-a135-1ae3efa9f7b0)
**

**Comment by QA-Pregon** [comment]
Haste zufällig auch nen Clip von dem ganzen oder ein Bild aus F8?
Gegebenenfalls vielleicht eine genaue Uhrzeit?

**Comment by RyanTears** [comment]
Nein kein Clip, aber: Kontobuchung: 31.8.2024, 16:45:02
Wie man auf dem Bild sieht, Läuft der % Balken und die UI ist offen.

**Comment by QA-Pregon** [comment]
One in A Ten thousand Moment
Selbst in den Serverlogs konnte Outburst nichts finden, einfach bitte unter beobachtung halten obs wieder passiert und dann vielleicht merken wodurch es maybe ausgelöst sein könnte

**Comment by RyanTears** [comment]
Gerade wieder das Problem !
![Hüfzgold](https://github.com/user-attachments/assets/ccc5798b-39c1-4135-b462-a64fd523e060)

Mein Vorgehen:
An den Tisch setzen
Essen anwählen
Trinken Anwählen
Bestellen


UI Stuck !
Heute morgen keinerlei Probleme gehabt.
Meine Vermutung:
Da es Hauptsächlich Mittags gegen Abends auftritt, wenn bisschen mehr los ist, das mein Pc zu schlecht ist um dem Server in angemessener Reaktionszeit die Informationen zu übermitteln und dadurch der UI Stuck entstehen könnte.
Habe des öfteren auch Probleme mit dem Aufbau der Map wenn ich nachmittags/Abends zu schnell durch die Stadt fahre und er alles am nachladen ist.

**Comment by RyanTears** [comment]
Again !

10.09 13.40uhr
![again](https://github.com/user-attachments/assets/62322c28-9b0b-481d-a9e7-4230763fd3a6)
