### ISSUE TITLE
Neue Smartphones / Akku + 24/7

### ISSUE THREAD

**Issue by Auralein** [mexyn/statev_v2_issues#3713]
Holly Swan

**Beobachtetes Verhalten**
Ich hab ein paar Kunden die neuen Farben von den Smartphones anschauen lassen und seit dem kann ich die nicht mehr im 24/7 verkaufen. Die Handys haben dann natürlcih ein Akku drin gehabt, welches im Verkaufsthresen auch angezeigt wird. Diese Handys werden allerdings den Kunden NICHT angezeigt.

**Erwartetes Verhalten**
Handys lassen sich normal verkaufen.

**Schritte um den Fehler nachvollziehen zu können**
Neues Smartphone ausrüsten und nach "Anprobe" in den Verkaufsthresen eines 24/7 einstellen.

**Optional: Video / Bilder des Fehlers**
Tablet-Anzeige
![grafik](https://github.com/user-attachments/assets/8d2952b9-4854-4cd4-b448-613b3ed8eb9c)
Lager-Anzeige
![grafik](https://github.com/user-attachments/assets/8207d04f-9976-45ac-94f8-5d3870a8ce3a)
Theken-Anzeige
![grafik](https://github.com/user-attachments/assets/048c5c21-75c9-4bb5-96c4-a900656cf81c)

**Comment by epichalt** [comment]
Dadurch, dass die Handys bereits  ausgerüstet waren, kann man diese nicht mehr stacken. Müsstest neue Preise dafür einstellen evtl.

**Comment by simplycach** [comment]
Könntest du höchstens als Gebrauchtwaren zu verkaufen oder als Ausstellungstücke

**Comment by Auralein** [comment]
Find ich ehrlich gesagt schon echt mies, weils keine Gebrauchtwaren sind... Möbelläden dürfen ihre Mödel ja auch präsentieren, warum dürfen wir keine Handys präsentieren? Die mit einmal "angucken" zu "schreddern" ist ja echt kacke :/
