### ISSUE TITLE
Old Graham Flachmann Itemverdopplung beim Befüllen

### ISSUE THREAD

**Issue by DJBirdsong** [mexyn/statev_v2_issues#3714]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Alfred Vogelsang**

**03.09.2024 ca. 20:30**

**Wenn man eine Flasche Old Graham Whisky in den Flachmann füllt erhält man am Ende einen vollen und einen leeren Flachmann**

**Dass man NUR den vollen Flachmann bekommt**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by AdmiralState** [comment]
Konnte nicht nachgestellt werden, bei mir hat es ganz normal funktioniert. Gerne nochmal probieren und ggf, nochmal hier kommentieren

**Comment by QA-Pregon** [comment]
Da nicht reproduzierbar + keine Antwort mach ich erstmal zu
Meine Vermutung ist dass du mehrere leere hattest aber dachtest du hast nur einen

Sollte es nochmal aufkommen und wirklich wieder duplizieren nochmal aufmachen biddö
