### ISSUE TITLE
Antrag auf Entfernung 2er Objekte an der Firma

### ISSUE THREAD

**Issue by Chandena** [mexyn/statev_v2_issues#3716]
Amelia Mccoy

Hallo, ich würde gerne ein Antrag auf Entfernung einer Achse und einem "Rollwagen" stellen. Da wir gerne den Platz für das Parken unserer Firmenautos nutzen würden. Bilder werden beigefügt.
MFG 

![Screenshot_74](https://github.com/user-attachments/assets/7852e44b-7187-46ff-b413-782e4c9d6601)
![Screenshot_73](https://github.com/user-attachments/assets/6e85b791-ad49-4652-bda0-f1b759c5f65e)

**Comment by SatyriaDine** [comment]
Hi @Chandena wir entfernen grundsätzlich aus Performance Gründen keine Objekte mehr. Des weiteren denke ich, dass es auf diesem großen Hof sicherlich einige Parkmöglichkeiten für deine Firmenfahrzeuge gibt. :)
