### ISSUE TITLE
Mapping Ölpumpen fehlt

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#3717]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit etwa dem 01.09 ca (laut Aussagen)

**Beobachtetes Verhalten**
Mapping der Ölpumpen fehlt

**Erwartetes Verhalten**
Mapping sollte da sein

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by QA-Pregon** [comment]
Liegt an der Lagreduzierung
Werden bald wieder da sein, bis dahin pumpt das öl bitte aus dem Boden selbst raus ;)
