### ISSUE TITLE
Crime Mission Marker unschön platziert

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#3718]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
im 24/7 bei einer Crime Mission is der Marker unschön platziert.
Durch den Onduty Punkt im Laden muss man schauen von wo der Marker erreichbar ist.

**Erwartetes Verhalten**
Das der Marker ohne Probleme nutzbar ist.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![image](https://github.com/user-attachments/assets/719ebc37-9939-473e-a9c5-3b7239a8d54b)
![image](https://github.com/user-attachments/assets/d4273d5c-96e0-4277-b481-d3510d1ce1a4)

Siehe Ticket: suppoort-8955-closed
Ticket für den User erstellt.

**Comment by SatyriaDine** [comment]
next update fixed :)
