### ISSUE TITLE
Bug Bei Majorpoints

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3719]
Seid 2 Tagen ist es bei 0% wie festgenagelt, es geht nicht mehr weiter.
Dabei müsste noch ein Major Point erreichbar sein um nochwas lernen zu können (einen habe ich ja noch über)...
![Screenshot_10](https://github.com/user-attachments/assets/365ae90f-4997-436b-b94f-b1c34c34d63b)

**Comment by TheOutburst** [comment]
Stimmt, war anders geplant, next update fixed

**Comment by Statev-Bonsai** [comment]
Danke :)
