### ISSUE TITLE
Autos werden (optisch) in öffentlichen Garagen repariert 

### ISSUE THREAD

**Issue by polyholic** [mexyn/statev_v2_issues#372]
**Charaktername:** Amber Antigua

**Zeitpunkt:** 21.11 Nachmittags und Abends 

**Beobachtetes Verhalten**
Fahrzeuge werden wie in v1 beim einparken von Kratzern, Dreck befreit. Scheiben sowie abgefallene Türen werden wieder eingesetzt. Verhalten wie in v1 nur Kontrollleuchte wird nicht beeinflusst ! Insgesamt 3x ausprobiert um einen einmaligen Fehler auszuschließen.  

**Erwartetes Verhalten**
Kann ich aktuell nicht sagen ob es eben ein Bug ist oder ein so gewünschtes Feature, daher schreib ich mal Schäden nicht reparieren durch einparken in öffentlichen Garagen. 

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug beschädigen Scheiben Einschlagen bzw. Tür abfahren und das Fahrzeug in die öffentliche Garage stellen

**Comment by DonVitoDiangelo** [comment]
Wird vorerst nicht angegangen
