### ISSUE TITLE
Marker in 24/7 Shop Rob "Great Ocean Highway" ist Buggy

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3720]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

AJ
**Auftrittszeitpunkt (Datum / Uhrzeit)**

06.09.2024
**Beobachtetes Verhalten**

Marker am Tresor schwebt in der Luft
**Erwartetes Verhalten**

Er ist am Boden
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/user-attachments/assets/c2caf324-a2ac-4a32-a4c4-a68689f6747a)
![image](https://github.com/user-attachments/assets/ced41913-b702-4fa5-b77f-bc4b9f43741a)

**Comment by SatyriaDine** [comment]
fixed next update
