### ISSUE TITLE
Gewicht von T-Shirt Maske zu Neck Gaiter

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3721]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

AJ
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer
**Beobachtetes Verhalten**

Ein Neck Gaiter wiegt ca das 5,5 fache einer TShirt Maske, die nur 0,15KG wiegt und das Gaiter 0,8KG. 
Mach für mich keinen Sinn, weil das eine nur nen Halstuch ist und das andere nen komplettes T-Shirt
**Erwartetes Verhalten**

Entweder gleiches Gewicht, da diese den gleichen Zweck erfüllen, oder der Neck Gaiter wird leichter.
**Schritte um den Fehler nachvollziehen zu können**

Beide Items Anschauen, ist aber auch nen Bild attached
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/user-attachments/assets/fe78f16b-59bd-434b-af13-ad450793eb61)

**Comment by SatyriaDine** [comment]
sollte gefixt sein :)
