### ISSUE TITLE
Kofferraumvolumen Pizza Boy Roller + Schadensanfälligkeit

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3722]
Das Kofferraumvolumen ist wie bei jedem anderen Roller, jedoch müsste es größer sein da vom Werk aus eine riesen Lagerkiste am Fahrzeug vorhanden ist.
Grade wenn man das Auslierungs RP bespielen möchte wäre es grandios wenn man das Volumen noch ein bissel erhöhen könnte.

Zudem leuchtet bei jeder kleinen berührung die gelbe/rote Motorleuchte, daher wäre es Klasse wenn man da nochmal nachbessert..

![Screenshot_17](https://github.com/user-attachments/assets/6b6ba24d-1300-4d6f-9240-1c71776647bc)

**Comment by AdmiralState** [comment]
Was hast du den alles berührt? Bei mir ist nichts angegangen und alles lief reibungslos

**Comment by Statev-Bonsai** [comment]
das ding ist übelst shit, es fällt um qualmt, du rennst gegen qualmt.. usw usw
wir haben zwei davon, die dinger sind echt ein graus ^^

**Comment by Statev-Bonsai** [comment]
im dc wurde es ja auch schon mal bemängelt...

![Screenshot_19](https://github.com/user-attachments/assets/f2d86119-53fa-4fe6-9698-ae8d9aeae130)

**Comment by Erumeldor** [comment]
Schaden nehmen wir mit im Discord Thread, der Kofferraum wird so bleiben. Ist immer noch ein Roller, und hat 15kg. Da passen genügend Pizzen rein ;)
