### ISSUE TITLE
Sandking nach Server Reboot verschwunden

### ISSUE THREAD

**Issue by VeAderian** [mexyn/statev_v2_issues#3723]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Kevin Walker

**Auftrittszeitpunkt (Datum / Uhrzeit)**

08.09.2024 - nach Server Reboot

Ich war heute vormittag eingeloggt und habe meinen Sandking unten in der Stadt aus der Garage geholt, in der nähe meines Labors und bin damit hoch gefahren zu meinem Lager, ca 20min später gabs dann den Server reboot und als ich wieder einloggte war der Sandking nicht mehr auf dem Parkplatz, laut GPS wird er aber noch genau dort angezeigt, wie auf den Screenshots auch zu sehen ist.

Das Fahrzeug sollte zu sehen sein

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://imgur.com/a/G6NHv3L

https://imgur.com/MXjnoTh

https://imgur.com/LkZm63v

**Comment by stepz2k9** [comment]
Da musste nen Ticket im Discord aufmachen, dann wird der dir aus der falschen Dimension wieder raus geholt.

**Comment by QA-Pregon** [comment]
Joa für mich auch so ein One in A Million Ding
Habs nicht reproduziert bekommen
Beim nächsten mal bitte dann direkt an Ticket Support wenden im DC und gegebenenfalls auf deren Anweisung den Bugtracker aufmachen
