### ISSUE TITLE
Missionspunkt Mystie

### ISSUE THREAD

**Issue by StateV-Jan** [mexyn/statev_v2_issues#3724]
**Character Name**
Liam Taylor

**Auftrittszeitpunkt (Datum / Uhrzeit)**
09.09.24

**Beobachtetes Verhalten**
Mission gestartet bei Mystique und habe den letzten Punkt nicht gefunden entweder ist er sehr gut versteckt oder einfach nicht auffindbar. Ein Punkt müsste zudem versetzt werden (der an der Tankstelle)  Adresse Senora Way 1

**Erwartetes Verhalten**
Punkt solle auffindbar sein. Punkt versetzen

**Schritte um den Fehler nachvollziehen zu können**
Diese Mission starten und schauen ob man den Punkt findet

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by QA-Pregon** [comment]
Für die falsche Formatierung tret ich dir IC in den Arsch xD
Habs mal geändert für dich :)

**Comment by SatyriaDine** [comment]
Whoopsie da sind mir scheinbar ein paar kleine Zahlendreherchen passiert. :D Ist zum nächsten Update gefixt. :D
