### ISSUE TITLE
API setzt sich zurück?

### ISSUE THREAD

**Issue by DrColgate** [mexyn/statev_v2_issues#3725]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Anton Mueller

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

Wir haben immer mal wieder die letzte  Zeit (nicht definierbar) beobachtet, das unser Status der Website nicht richtig ist.
Obwohl wir ihn geändert haben.
![closed](https://github.com/user-attachments/assets/48f4ff06-61b2-4494-ac44-d1469e343797)

ich spreche von unserem open/closed schild.
Ich habe gestern um 17:28:11 MESZ von geschlossen auf geöffnet an die api gesendet.
![log1](https://github.com/user-attachments/assets/37a2bb80-3709-4a82-ac6c-59c929e4b332)

Gestern um 22:28:44 MESZ wurde dann geschlossen gesendet.
![log3](https://github.com/user-attachments/assets/c5fa16e7-735c-46a6-8aba-5d27601bee7f)

Dazwischen wurde von uns nichts an die API gesendet.

Heute um 13:51:09 MESZ lese ich die API aus:
![api](https://github.com/user-attachments/assets/1edf8020-8a3a-4859-a3bc-225ff4116da9)

Laut Api ist die letzte änderung von gestern 20:10:50 MESZ

Wie oben bereits erwähnt, war die letzte änderung von uns um 22:28:44 MESZ. 

ich weiss nicht, wie 20:10:50 MESZ zustande kommt, denn wir haben nur einmal um 17:28:11 MESZ und einmal um
22:28:44 MESZ an die api gesendet. Dazwischen wurde von uns nichts an die API gesendet

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrColgate** [comment]
![Unbenannt](https://github.com/user-attachments/assets/0b35192d-4000-42e5-b84f-50440f227cac)

wurde von uns nicht umgestellt

**Comment by DrColgate** [comment]
![api1](https://github.com/user-attachments/assets/6599d7e7-e75c-436f-a1c9-c8e3f46fe2e3)

**Comment by DrColgate** [comment]
![api2](https://github.com/user-attachments/assets/3288a4e5-24ce-43c9-8dc5-8fbec06bbb3f)

**Comment by rodistic** [comment]
Ayyy Gude,

wie es aussieht nutzt du dafür die Factory Options?
Diese werden nicht durch ein System zurückgesetzt sondern nur bei Request durch einen externen geändert.

Wenn es um einen Open/Close geht kannst du mittlerweile auch anders an die sache gehen. 
Du kannst im VNET den Open/Close Status setzen und dann per GET - /factory/list/ den isOpen Status holen.
