### ISSUE TITLE
Blunt Sorten

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3726]
Egal womit man den Blunt befüllt er heißt immer nur Blunt, schöner wäre es wenn es wie bei den Joints wäre...

![Screenshot_29](https://github.com/user-attachments/assets/41c52186-09f2-4992-9d2e-6b76a326f532)

![Screenshot_26](https://github.com/user-attachments/assets/f7a203b7-bba1-45ae-a22d-331f5e7d3e58)

**Comment by QA-Pregon** [comment]
Simba is dran

**Comment by ySimbaa** [comment]
Simba hat fertig für nächstes Update

**Comment by Statev-Bonsai** [comment]
suuuuuuuuuuuuper :)
