### ISSUE TITLE
Double Cup Rezept

### ISSUE THREAD

**Issue by jonesXYZ** [mexyn/statev_v2_issues#3727]
**Character Name**
irrelevant

**Auftrittszeitpunkt (Datum / Uhrzeit)**
dauerhaft

**Beobachtetes Verhalten**
Leerer double Cup hat config fehler für Produktion im 24/7
https://share.xyzjon.es/CFvR426zDb_1725905500.png

**Erwartetes Verhalten**
Sollte funktionieren

**Schritte um den Fehler nachvollziehen zu können**
Verpackter Double Cup in Produktion Legen
versuchen zu Produzieren

**Optional: Video / Bilder des Fehlers**
![Uploading CFvR426zDb_1725905500.png…]()

**Comment by ySimbaa** [comment]
Next Update fixed
