### ISSUE TITLE
Prison Looter falsche Perks

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3729]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

AJ
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer
**Beobachtetes Verhalten**

Prison Looter Zeigt einen als Bonus -% an und beim besseren finden z.B. -100%
**Erwartetes Verhalten**

Sollten Logische werte sein
**Schritte um den Fehler nachvollziehen zu können**

Prison looter Skillen und anschauen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/user-attachments/assets/62343aaf-7a6b-40a5-9da4-67841c2bf24b)

**Comment by Erumeldor** [comment]
Wurde hier schonmal gemeldet. Ist "nur" die UI, aber sieht natürlich seltsam aus.
https://github.com/eiksch/statev_v3_issues/issues/3513
