### ISSUE TITLE
StateCom bleibt weiß

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#373]
**Character Name**
Jannik_Datsch

**Zeitpunkt (Datum / Uhrzeit)**
22.11  11:40

**Beobachtetes Verhalten**
SAPD StateCom bleibt oftmals beim ersten Einloggen komplett weiß, man muss das Game neustarten, damit man das StateCom bedienen kann.

**Erwartetes Verhalten**
Man sollte sich ohne Neustart einloggen können.

**Schritte um den Fehler nachvollziehen zu können**
siehe oben

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920-1080

**Optional: Video / Bilder des Fehlers**

**Comment by JannikDatsch** [comment]
Zur Info, das ist ein alter Bug, das war schon unter Rage so, aber habs trotzdem mal reingestellt, weil geht ja nicht nur um neue Bugs denk ich.   Haben viele PD Kollegen auch das Problem. Wie es beim MD ausschaut weiß ich nicht.

**Comment by TheBroady** [comment]
Tritt bei mir auch ständig auf, inzwischen nutze ich das stateCom ausschließlich extern.

**Comment by DonVitoDiangelo** [comment]
Wie ist hier so der Stand der Dinge?

**Comment by TheBroady** [comment]
> Wie ist hier so der Stand der Dinge?

Ist bei mir bereits seit längerem nicht mehr aufgetreten.

**Comment by JannikDatsch** [comment]
same

**Comment by its4l3x** [comment]
Jop, kann durch ein Restart zusammenhängen. Nicht mehr weiter relevant, Closed.

**Comment by JannikDatsch** [comment]
Heute erstmals wieder bei einem Kollegen aufgetreten
