### ISSUE TITLE
Lichtleiste am Helion bleibt dunkel

### ISSUE THREAD

**Issue by shoxmox** [mexyn/statev_v2_issues#3730]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
Puka Kuaholo

**Auftrittszeitpunkt (Datum / Uhrzeit)**
10.09.2024 - 21.15 Uhr

**Beobachtetes Verhalten**
Die Lichtleiste mit Gepäckträger auf einem Anis Helion montiert. Danach das Fernlicht eingeschalten, aber die Lichtleiste bleibt dunkel

**Erwartetes Verhalten**
Lichtleiste leuchtet

**Schritte um den Fehler nachvollziehen zu können**
Tuning an Werkstatt, Dach --> Lichtleiste mit Gepäckträger monitieren

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![Screenshot 2024-09-10 212436](https://github.com/user-attachments/assets/88967c90-a29b-45fb-9972-51023488a38c)

**Comment by SgtBoaz-Terry** [comment]
Das funktioniert GTA-seitig schon nicht. Da können wir auch nichts ändern.
