### ISSUE TITLE
Bug erw. Mag PSP

### ISSUE THREAD

**Issue by Resoxxx** [mexyn/statev_v2_issues#3731]
Akin_Chambers
10 September 2024 um 21:15
Als ich das erweiterte Magazin meiner PSP in mein Inventar ziehen wollte, habe ich nicht beachtet, dass mein Inventar voll war. Daraufhin erschien die Meldung, dass mein Inventar voll ist, und das erweiterte Magazin verschwand. Ich hatte die Waffe noch in der Hand, und es wurde angezeigt, dass 12 Schüsse in der Waffe waren. Da das Magazin weg war, habe ich einen Relog gemacht, und nun kann ich die Waffe nicht mehr herausziehen. Das erweiterte Magazin ist ebenfalls nicht mehr vorhanden.

Beim Versuch, das erweiterte Magazin in das Inventar zu ziehen, sollte eine klare Fehlermeldung erscheinen, dass das Inventar voll ist, ohne dass das Magazin verschwindet. Das Magazin sollte entweder im ursprünglichen Slot bleiben damit es nicht verloren geht. Nach einem Relog sollte die Waffe weiterhin normal genutzt werden können, und das Magazin sollte im Inventar wieder aufzufinden sein.

Ich korrigiere, die Waffe kann wieder benutzt werden, aber das erweiterte Magazin ist verschwunden.

Hierbei füge ich noch einen Clip hinzu um den Ablauf zu sehen.

https://github.com/user-attachments/assets/6bb730d4-471b-4a24-911c-9dab2d3d098c

**Comment by MarcelMuerto** [comment]
Ist im aktuellen Update vorhanden.
