### ISSUE TITLE
Loot neuer Davis Baumarkt (große Mission)

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3732]
beim neuen baumarkt in davis gibts irgendwie keinen loot, oben bei den alten beiden baumarkten passt die ausbeute absolut da hat man meistens 3-4 items pro bruch...

bitte da etwas nachbessern...

edit: als am 9.9 der patch mit angepasten loot für frisör und tattooläden kam war die ausbeute super, aber ich weiß nicht was mit dem patch am 10.09 gemacht wurde, seitdem ist die ausbeute extrem unterirdisch.
75% weniger loot als am vortag, irgendwas muss da kränkeln, ich mach ca. 8std täglich diese läden und kann es denke ich daher gut beurteilen.

vielleichtes aber nur bad rng, ich werde es mal in einer tabelle festhalten für den überblick...

**Comment by Statev-Bonsai** [comment]
im hinterraum müsste der marker auch runtergesetzt werden, der schwebt in der luft...
![Screenshot_38](https://github.com/user-attachments/assets/b3c93f3a-d2c2-4893-89bb-eaec7a88396a)

**Comment by QA-Pregon** [comment]
Loot hat sich seit Monaten nicht verändert, den Marker geb ich ans Gamedesign

**Comment by Statev-Bonsai** [comment]
@pregon, das ist absolut falsch was du da sagst...

**Comment by QA-Pregon** [comment]
Aussage kommt von der Stellvertretenden Projektleitung, welche das in dem Moment geprüft hat. Denke also schon dass meine Aussage stimmt

**Comment by Statev-Bonsai** [comment]
nein, vorgestern wurde er z.b. erst angepasst in frisören und tattooläden, es kam auch neuer loot hinzu..
in tattooläden war die dropchance vorher zu gering...

[CHANGED] Kriminelle finden in Friseur & Tattoo Läden mehr nützliche Dinge

**Comment by QA-Pregon** [comment]
Der Lootpool von Baumärkten hat nichts mit dem vom Friseur und Tattoo zu tun.
Wir schauen trotzdem nochmal.
