### ISSUE TITLE
Fehler BIld Meldung Ploppt auf 

### ISSUE THREAD

**Issue by FrankMiller94** [mexyn/statev_v2_issues#3734]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
 Frank Miller

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 11.09.2024 17:40

**Beobachtetes Verhalten**
ich wollte mich mit Y auf die werkbank setzten und aufeinmal Kommt diese Fehler als Bild

**Erwartetes Verhalten**
 
![323232311111111](https://github.com/user-attachments/assets/57becea5-cf62-4c6b-87d7-80e61d34a654)

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by QA-Pregon** [comment]
#3446
