### ISSUE TITLE
Verladepunkt an der Firma

### ISSUE THREAD

**Issue by CrysaGaming** [mexyn/statev_v2_issues#3735]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Rachel_Parker

**Auftrittszeitpunkt (Datum / Uhrzeit)**

11.09.2024 23:39 Uhr

**Beobachtetes Verhalten**

Verladepunkt liegt auf der falschen Seite des Gebäudes, es ist sehr umständlich mit großen Fahrzeugen wie Rubble etc. sich durch die enge Gasse zu bewegen.

**Erwartetes Verhalten**

Den Verladepunkt bitte wie bei den anderen auf die vordere Seite des Gebäudes auf die Dave Ave. 

**Schritte um den Fehler nachvollziehen zu können**

Wenn man vor dem Gebäude mit dem Hash: pf_davis_20, Addresse: Dave Ave. 35 steht hat man mehrere Verladepunkte, aber das dieser Firma ist auf der Rückseite zu finden und man muss mit den großen Fahrzeugen die Gasse reinfahren links neben dem Hair Kutz Frisuer Southside.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

Monitorauflösung ist:  2560x1440

**Optional: Video / Bilder des Fehlers**

Vorderseite des Gebäudes/Firma
![Lager-Voderseite-ohne Verladepunkt-2](https://github.com/user-attachments/assets/ab5aab25-bdad-4482-97c1-d7cff88bbfac)
![Lager-Voderseite-ohne Verladepunkt](https://github.com/user-attachments/assets/1faa8dcf-6a8f-4d1e-a028-47bbaa7bd722)

Rückseite des Gebäudes/Firma
![Lager-Rückseite-mit Verladepunkt-2](https://github.com/user-attachments/assets/200376ee-8c42-4ce6-9eaf-ebf6b0edc29a)
![Lager-Rückseite-mit Verladepunkt](https://github.com/user-attachments/assets/3f909d12-ebbe-42c5-b77c-017b3561af5b)

**Comment by SatyriaDine** [comment]
zum nächsten Update ist der Abladepunkt versetzt. :)

**Comment by CrysaGaming** [comment]
Danke dir (euch).
