### ISSUE TITLE
Animation bugg

### ISSUE THREAD

**Issue by adrosso** [mexyn/statev_v2_issues#3736]
Ich habe einmal ein Video zu gemacht, wenn der Kollege das über < Menü macht, macht Bro Greet#1 auch die Partneranimation. Wenn er das über des X Radialmenü macht, macht er NICHT die Partneranimation. (sieht man auch)

Im Video, aus meiner Sicht sieht man, egal wie ich es mache, es ist und bleibt in allem eine Partneranimation.

https://medal.tv/de/games/gta-v/clips/iFjEmqQhj5E1wtkVA/d1337CDfqmLA?invite=cr-MSx4bXQsMjUxNTM3MzUwLA

Wenn ich das vor dem Wing Stop mache, wenn da jemand ist den ich Drücken will, nimmt der die letzte Person, die ich Bedient habe (gestern abend erst wieder passiert), mein Charakter Portet sich quasi da hin, er drückt den Kunde, ich sehe den WIng Stop von unten und muss mein Game neustartet weil ich im Tisch Bugg.

**Comment by QA-Pregon** [comment]
Zum Thema letzte bediente Person:
Man macht die Animation immer mit der Person mit der man zuletzt das X Menü aufgemacht hat
Das andere kann ich so bestätigen

**Comment by adrosso** [comment]
Durch den Chat im Livestream habe ich erfahren, es könnte daran liegen das bei meiner Liste das Bro Greet #1 fehlt.
![H34c9B](https://github.com/user-attachments/assets/ec4c36ae-195c-4e57-a91a-c1456eca9bfc)
