### ISSUE TITLE
DJ-Verstärker UI verschwindet wenn man ''Z'' drückt

### ISSUE THREAD

**Issue by DJBirdsong** [mexyn/statev_v2_issues#3738]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Alfred Vogelsang**

**12.09.2024 gegen 22 Uhr**

**Sobald man mit dem Verstärker verbunden ist und in Game die ''Z''-Taste drückt verschwindet das UI und man muss reloggen bevor man sich erneut mit dem Verstärker verbinden kann.**

**Dass man entweder ''Z'' drücken kann ohne dass das UI verschwindet ODER das man sich erneut verbinden kann ohne erneutem Relogg**

**1. mit dem Verstärker verbinden || 2. ''Z'' drücken**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by QA-Pregon** [comment]
@DJBirdsong kannste nochmal testen ob das wirklich so passiert ist?
Ich kann das normal machen =D

**Comment by QA-Pregon** [comment]
Da  keine Antwort und nicht reproduzierbar gehts erstmal wieder zu, gern erneut öffnen wenns nochmal auftritt, ggfs. mit Clip
