### ISSUE TITLE
SpiegelreflexKamera keine tiefenschärfe mehr :(

### ISSUE THREAD

**Issue by Zweigesicht** [mexyn/statev_v2_issues#3739]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit dem fix von der kamera mit dem inventar bug hat man bei space kein menü mehr 

**Beobachtetes Verhalten**
Man drückt space und das menü für die tiefenschärfe öffnet sich nicht.

**Erwartetes Verhalten**
Man drückt space und das menü für die tiefenschärfe öffnet sich.

**Schritte um den Fehler nachvollziehen zu können**
Kamera im invetar benutzen und space drücken.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TheOutburst** [comment]
Seit dem 1.11 gefixt
