### ISSUE TITLE
Export Auftrag von gestern noch vorhanden obwohl zeit abgelaufen

### ISSUE THREAD

**Issue by Tobse1904** [mexyn/statev_v2_issues#374]
**Character Name**
Harry Buktu

**Zeitpunkt (Datum / Uhrzeit)**
22.11.2020 ca 11:50 

**Beobachtetes Verhalten**
Ich habe einen Export Auftrag mit Batterien ersteiger, da gestern der Export allerdings defekt war konnte ich den von gestern nicht abgeben und bin davon ausgegangen das dieser gelöscht wird. Jetzt will ich nun den neuen abgeben was auch möglich war, aber sehe den alten noch, dabei sagt das auftragsmenü der Firma das er abgelaufen ist. Eine Strafe gab es dafür nicht aber ich stelle mir jetzt die frage was mit dem von gestern ist. Kann ich diesen Entspannt in den nächsten tagen abgeben ?

P.S : Die Firma von der ich den Auftrag abgeben habe heißt "EMPIRE | Production"

**Erwartetes Verhalten**
Nur der Aktuelle Auftrag vorhanden nicht der von gestern.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920 x 1080

**Optional: Video / Bilder des Fehlers**
Leider kein Screen gemacht,

**Comment by tastydev** [comment]
fixed im nächsten update
