### ISSUE TITLE
Schieben nicht abbrechbar, wenn man Fahrzeug auflädt

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3740]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

AJ
**Auftrittszeitpunkt (Datum / Uhrzeit)**

14.09 23:09
**Beobachtetes Verhalten**

Wenn man ein fahrzeug schiebt und im menü ausversehen aufladen auswählt, kann man es nicht mehr abbrechen und man wird mit aufgeladen
**Erwartetes Verhalten**

Das Schieben hört automatisch auf
**Schritte um den Fehler nachvollziehen zu können**

Fahrzeug schieben und im X Menü aufladen auswählen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://medal.tv/games/gta-v/clips/iGeHXrwBsauDGd_v-/d1337irFQ8Zo?invite=cr-MSxxWHYsMTk1NTEzMTMzLA

**Comment by QA-Pregon** [comment]
Bis zum Fix -> ist per Hotkey abbrechbar (Fahrzeug schieben Hotkey)

**Comment by QA-Pregon** [comment]
Next Update
