### ISSUE TITLE
Bei Hose bugt die haut durch 

### ISSUE THREAD

**Issue by RudiAlme** [mexyn/statev_v2_issues#3741]
Grüßeee Team 
mir ist was an einer Damen Hose auf gefallen da wo die haut sehr hart durch Bugt 

![Screenshot_4](https://github.com/user-attachments/assets/5200e13c-a6f2-46fb-a4db-1e4435405603)
![Screenshot_5](https://github.com/user-attachments/assets/0ca59659-0887-4b25-8334-3776f7650f78)
![Screenshot_6](https://github.com/user-attachments/assets/31775dfc-4214-4374-bbde-92d8403efceb)
![Screenshot_7](https://github.com/user-attachments/assets/66ff5a75-b15d-42f4-aa8d-2c0202599c2d)
die Hose heißt 
![Screenshot_8](https://github.com/user-attachments/assets/e2c5f986-9d10-4e3d-93f9-f47aa9c360ea)
wenn der issues schon vorhanden ist sorry

**Comment by QA-Pregon** [comment]
Simba macht looky looky und guckt was geht

**Comment by ySimbaa** [comment]
fixed
