### ISSUE TITLE
Dinka Double T

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3742]
Seid dem Update vor einiger Zeit ist das Fahrzeug kaputt wenn man gegen läuft und qualmt wenn es umfällt.
Bitte das Bike anpassen, so macht es keinen Sinn das Fahrzeug überhaupt auzuparken..

**Comment by QA-Pregon** [comment]
https://discord.com/channels/365251792679862292/1271377585858941020
