### ISSUE TITLE
Garage 7006 Ausparken von Achsen

### ISSUE THREAD

**Issue by PapaAri999** [mexyn/statev_v2_issues#3743]
Wie hier zu sehen gibts immer Probleme beim Ausparken von Achsen an der Garage.

Garage 7006 Ausparken von Achsen

Problem 

Achse werden von zu weit oben "gespawn"
durch das unebene Gelände kippen Sie.

50/50 Chance sie gerade zu bekommen oder umzuwerfen :dancing_men: 

#Papa_Ari

![14111](https://github.com/user-attachments/assets/ca73d1f4-0db9-4c26-9bfe-58eb0bf060a6)

**Comment by QA-Pregon** [comment]
Glaub da muss illegales Glücksspiel angemeldet werden xD
Ne Spaß bei Seite, so wie ich Sofia kenne guckt die da demnächst mal drüber (oder iwer anderes aber glaub es läuft auf Sofia hinraus ^^)
