### ISSUE TITLE
Mehrfachplatzierung Rennen bei Namensänderung

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#3746]
**Character Name**
Charly Parker

**Auftrittszeitpunkt (Datum / Uhrzeit)**
18.09.2024 04:20 Uhr

**Beobachtetes Verhalten**
Wenn man beim Racing Dude seinen Namen ändert bleibt die alte Platzierung erhalten, so kann man theoretisch wenn man gut ist alle Top Spots füllen. Beobachtet bei JayL der sich in JaaY umbenannt hat.

**Erwartetes Verhalten**
Dass der alte Name in der Liste mitgeändert wird, sodass man nur eine Bestzeit hat.

**Schritte um den Fehler nachvollziehen zu können**
Rennname festlegen, Rennen fahren, Rennname ändern, noch ein Rennen fahren, Bestenliste anschauen

**Optional: Video / Bilder des Fehlers**
https://i.imgur.com/DaSquf4.png

**Comment by QA-Pregon** [comment]
Wird aktuell erstmal nicht geändert, da zu viel aufwand für zu seltene Fälle.

Sollte jemand das ganze Ausnutzen und die ganze Tabelle füllen kann das aber gern gemeldet werden :)
