### ISSUE TITLE
Werkstattpreise nicht Einstellbar wegen Error!

### ISSUE THREAD

**Issue by ManuelLadner** [mexyn/statev_v2_issues#3747]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Manuel_Turner**

**jederzeit beim Versuch die Preise einzustellen**

**Errorcode siehe Bild**

**Beim Neuen System sollte man die Items sehen und deren Preise Einstellen können!"**

**Tuningpreise Reiter öffnen, dann kommt der Fehler**

**egal**

**Optional: Video / Bilder des Fehlers**

![20240918122511_1](https://github.com/user-attachments/assets/09cd29da-5b13-4d82-aea5-1b8d0f21df63)

**Comment by Erumeldor** [comment]
Skibidi rampampam, fixed any moment
