### ISSUE TITLE
Modische Brillen | femaleglasses1510 unsichtbar

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#3748]
**Character Name**
Charly Parker

**Auftrittszeitpunkt (Datum / Uhrzeit)**
18.09.2024 15:45 Uhr

**Beobachtetes Verhalten**
Bei Vangelico unter Modische Brillen | femaleglasses1510 ist das Model nicht sichtbar (und wahrscheinlich auch falsch benannt)

**Optional: Video / Bilder des Fehlers**
https://i.imgur.com/U3RjsKG.png

**Comment by ySimbaa** [comment]
Ist wohl ein kleiner Fehler rein gekommen. Nächstes Update fixed.
