### ISSUE TITLE
Lackierkabine geht Kaputt

### ISSUE THREAD

**Issue by ZirbelR** [mexyn/statev_v2_issues#375]
**Character Name**
Richie_Zirbel

**Zeitpunkt (Datum / Uhrzeit)**
22.11.2020  12:22

**Beobachtetes Verhalten**
Nach dem Starten der Lackierung (Metallic Black/RGB Blue/Pearl) wurde das Geld vom Konto abgebucht, jedoch der Lackiervorgang nicht gestartet. Danach ist die Lackierkabine nicht mehr nutzbar (Bereits in Verwendung!). Selber Fehler ist gestern bei der selben Lackierung aufgetreten.

**Erwartetes Verhalten**
Lackierung startet oder Fehlermeldung (mischen von RGB und Speziallack nicht möglich)

**Schritte um den Fehler nachvollziehen zu können**
Lackierung wie oben beschrieben starten (Speziallack als Primärfarbe + RGB Lack als Sekundärfarbe + Perleffekt)

**Comment by JulianMa** [comment]
@ZirbelR Bitte heute Abend nach dem Update erneut testen. Wenn es noch auftritt, bitte hier rein schreiben.
