### ISSUE TITLE
Central Miner NaN$ Bug

### ISSUE THREAD

**Issue by loelchn** [mexyn/statev_v2_issues#3751]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```
App Central Miner

Luca Lorenzi

Luca Lorenzi
**Auftrittszeitpunkt (Datum / Uhrzeit)**
Dauerhaft

**Beobachtetes Verhalten**
NaN $ 

**Erwartetes Verhalten**
Kann keinen Fortschritt mehr kaufen, oder hänge in der 

**Schritte um den Fehler nachvollziehen zu können**
Tablet in die Hand, und App starten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
-

**Optional: Video / Bilder des Fehlers**
(https://prnt.sc/wCEDq0I7v1s0)

**Comment by AdmiralState** [comment]
Besteht dieser Fehler trotz Relog weiterhin bei dir?

**Comment by loelchn** [comment]
Ja, gerade gemacht. 

https://prnt.sc/3NLUF3eFRbk-

steht so da, immer noch diese NaN$

**Comment by AdmiralState** [comment]
Kannst du dich evtl noch dran erinnern wann genau der Fehler kam? Hast du irgendein Upgrade gekauft oder die Mine gewechselt oder kam er Fehler einfach so?

**Comment by loelchn** [comment]
Ist passiert, wo ich den Ofen upgrade ausgeführt habe. Mine nicht gewechselt. Der bei glaub 1,2mio war oder so.. und da ist jetzt nach restart auch immernoch er fehler NaN$

**Comment by AdmiralState** [comment]
Ich leite es mal weiter, sollte etwas noch unklar sein werden wir hier fragen

**Comment by TheOutburst** [comment]
mit dem vnet von heute gefixed
