### ISSUE TITLE
Spielkarte Armor wird nicht angezeigt

### ISSUE THREAD

**Issue by Snipser92** [mexyn/statev_v2_issues#3752]
**Character Name**
Raik_Morton

**Auftrittszeitpunkt (Datum / Uhrzeit)**
19.09.2024 / 15:10

**Beobachtetes Verhalten**
Ich habe die Spielkarte "Armor" hergestellt und wollte mir diese anschauen. Sie wird leider nicht so wie die anderen Spielkarten angezeigt.

**Erwartetes Verhalten**
Spielkarte Armor mit rechtsklick anschauen und es wird angezeigt.

**Schritte um den Fehler nachvollziehen zu können**
Spielkarte Armor herstellen, mit rechtsklick öffnen.

**Comment by SatyriaDine** [comment]
Da hat sich nen Typo eingeschlichen. Sollte bald fixed sein. :)
