### ISSUE TITLE
SMS/Mailbenachrichtigungston funktioniert nicht

### ISSUE THREAD

**Issue by stepz2k9** [mexyn/statev_v2_issues#3753]
**Character Name**
Kelani Larsson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit einer ganzen Weile

**Beobachtetes Verhalten**
Weder ingame, noch via Browser funktionieren die SMS- und Mail-Benachrichtigungstöne. Es werden einfach keine Töne abgespielt.

Außerdem werden neue SMS am Handy erst angezeigt, wenn man den Bildschirm entsperrt, dann sliden sie von oben rein. Gestern mit einer SMS erlebt, die bereits 20 Minuten vorher versendet worden war.

**Erwartetes Verhalten**
Akustischen Ton / Anzeige einer SMS im Sperrbildschirm und nicht erst, wenn entsperrt wird.

**Comment by Erumeldor** [comment]
Ist das, seit dem letzten Handy Update, noch aktuell? @CaleighRhodes
