### ISSUE TITLE
Werkstatt Bug Fahrzeug ophne beschädigung immer nur für 66 dollar zu reparieren 

### ISSUE THREAD

**Issue by Tobias1496** [mexyn/statev_v2_issues#3754]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Luca Gerwen

**Auftrittszeitpunkt (Datum / Uhrzeit)**
gibt es keine spezifische zeit für 

**Beobachtetes Verhalten**
egal ob ich auserhalb der werkstatt reparieren will oder inner werkstatt ich kriege immer wieder nur die reparatur option statt tuning und lackierung kommt zu stark beschädigt dabei kein schaden vorhanden (Vermutung fahrzeuge die zu nahe stehen ka 

**Erwartetes Verhalten**
Fahrzeug sollte ohne reparatur zu tunten sein vorallem wenn kein schaden vorhanden ist 

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![Screenshot 2024-09-20 161059](https://github.com/user-attachments/assets/621823bb-a707-4c24-a2cf-77ca95ee6ddb)

**Comment by SHaagmann** [comment]
Nachm Reparieren kann man einmal kurz einsteigen und Motor anmachen dann geht das Tuning

**Comment by Erumeldor** [comment]
Gerne mal in Zukunft nochmal beobachten, da kam auch ein kleiner Fix mit rein zu Halloween.
