### ISSUE TITLE
Luxury Cars / Manche Fahrzeuge öffentliche Garage

### ISSUE THREAD

**Issue by JayLaker** [mexyn/statev_v2_issues#3755]
**Character Name**
Jay Laker

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer nach dem automatischen Einparken

**Beobachtetes Verhalten**
Manche Fahrzeuge werden in die öffentliche Garage eingeparkt. Wenn ein Fahrzeug davon einmal betroffen war, wird es immer beim automatischen Einparken in die nächste öffentliche Garage eingeparkt ( Momentan betrifft es den Contender)

Das Fahrzeug wurde immer normal im Autohaus eingeparkt bis zum Brand. Seit es aus dem Depot freigekauft wurde, wird es immer in die öffentliche Garage gesetzt.

**Erwartetes Verhalten**
Fahrzeuge werden wie alle anderen Fahrzeuge auch im Autohaus eingeparkt.

**Comment by QA-Pregon** [comment]
Betrifft es auch andere Fahrzeuge oder nur das, was auch mal im Depot war?

**Comment by SgtTukiTukii** [comment]
Teresa Martinez

Es betrifft bislang nur dieses Fahrzeug. Habe es auch schon extra Seperat nochmal ins Autohaus eingeparkt um zu gucken obs hilft, aber es hilft nicht. Sollte nicht eigentlich sowieso inaktive Fahrzeuge später eingepart werden? Wir müssen nämlich trotzdem jeden Tag die Fahrzeuge erneut nachdem Restart ausparken.

**Comment by QA-Pregon** [comment]
Bald fixed (Hopefully), aber noch nicht endgültig fertiggestellt

**Comment by rodistic** [comment]
ist der Bug wieder aufgetaucht?

**Comment by Erumeldor** [comment]
Sollte kein Problem mehr sein - wurde vor einigen Wochen gefixt.
