### ISSUE TITLE
Werkstatt, zu viel Betrieb

### ISSUE THREAD

**Issue by epichalt** [mexyn/statev_v2_issues#3756]
U.S. Customs
allerdings ist keiner da
![image](https://github.com/user-attachments/assets/a2bc44dd-9ae5-4c78-8ae3-70ce8a676258)

**Comment by QA-Pregon** [comment]
Könnte maybe daran liegen, dass da Fahrzeuge ins System verbugt sind und dann die Plätze blockieren
Hab da iwo letztens was zu gesehen, aber weiß nicht mehr wo xD

**Comment by Erumeldor** [comment]
Kurze Erklärung, falls jemand darüber stolpert:

Bei z.b. einem UI Crash ist das Fahrzeug und der Mechaniker weiterhin in Tuning. Mechaniker kann reloggen. Das Fahrzeug **muss** administrativ eingeparkt werden, da dann also ein Ticket aufmachen. Wird es über andere Wege entblockt, bspw. durch einen Abschlepper oder manuelles einparken, geht das Fahrzeug zwar wieder, die Werkstatt ist aber weiterhin blockiert.

Heißt somit hier ein Folgebug, der hoffentlich faktisch nie Auftritt. (Der UI Bug für die Motorräder ist schon gefixt für das nächste Update.)
