### ISSUE TITLE
Bennys shop raub punkte verbuggt nach neuem change :)

### ISSUE THREAD

**Issue by Zweigesicht** [mexyn/statev_v2_issues#3757]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21.09.2024

**Beobachtetes Verhalten**
Punkte schweben

**Erwartetes Verhalten**
Punkte sind aufm boden ^^

**Schritte um den Fehler nachvollziehen zu können**
Shop bei nox annehmen und die punkte schweben in der luft

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/user-attachments/assets/42345c1e-299a-4082-814e-ac5384368c41)

**Comment by SatyriaDine** [comment]
next update fixed :)
