### ISSUE TITLE
Großer schrottplatz auftrag nicht machbar.

### ISSUE THREAD

**Issue by Zweigesicht** [mexyn/statev_v2_issues#3759]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
Ein punkt ist auf einem crime lager und daher nicht machbar da sich jedes mal das UI öffnet zum lager betretten.

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**
auftrag annehmen hinfahren.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/user-attachments/assets/7011a7ed-763b-45e5-b0c5-7071b9af2e41)

![image](https://github.com/user-attachments/assets/3ab14435-dfb3-4540-91cf-fbdbed13585e)

**Comment by SatyriaDine** [comment]
Bereits bekannt und mit dem nächsten Update gefixt :)
