### ISSUE TITLE
Behandlungszeit um 70% verkürzen

### ISSUE THREAD

**Issue by Chrinis007** [mexyn/statev_v2_issues#376]
**Character Name**
Christian_Maier

**Zeitpunkt (Datum / Uhrzeit)**
Seit V2

**Beobachtetes Verhalten**
Behandlungen im Md dauern ewig

**Erwartetes Verhalten**
Nicht auf nen fortschrittsbalken festmachen sondern einfach RP Behandlung

**Schritte um den Fehler nachvollziehen zu können**
Im Doktorzimmer jemanden behandeln

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Es sind derzeit 100 Sekunden. Ich habe das jetzt erstmal auf 80 gesetzt.  Ist aber rein Feature Wunsch und wird auch demnächst erstmal nicht angegangen. Prio liegt woanders derzeit.

**Comment by Chrinis007** [comment]
Danke dir
