### ISSUE TITLE
Überfälle mit Bandana nicht ausführbar..

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3761]
Ist das ein bug oder feature das man zusätzlich seit neusten auch eine cap etc.  zum bandana tragen muss?

**Comment by QA-Pregon** [comment]
Welches Bandana wurde da benutzt?

**Comment by Statev-Bonsai** [comment]
das schwarze skull

**Comment by QA-Pregon** [comment]
Einmal den genauen Itemnamen bitte, wir haben ja nicht nur eine schwarze Skullmaske

**Comment by Statev-Bonsai** [comment]
doch, gibt tatsächlich nur ein schwarzes skull bandana :D aber hier...>
![Screenshot_2](https://github.com/user-attachments/assets/284dba31-e558-474b-b9cc-fe29212a640a)

**Comment by QA-Pregon** [comment]
Joa hab Bandana überlesen xD hatte alles andere zum Skull und schwarz nur im Kopf, guck ich mir morgen mal an

**Comment by Statev-Bonsai** [comment]
wie gesagt, man muss immer eine kopfbedeckung zum bandana tragen, sonst lässt es das system nicht zu das man läden überfallen kann...

**Comment by QA-Pregon** [comment]
Sollte funktionieren
Was hast du im Kleidungsmenü unter EXTRAS eingestellt gehabt?

**Comment by Statev-Bonsai** [comment]
nur das es als bandana vorm gesicht ist... :)

**Comment by Statev-Bonsai** [comment]
wenns nicht funktioniert werde ich alles mal ablichten...

**Comment by QA-Pregon** [comment]
Clip wäre tatsächlich top xD
Bei mir läuft da alles

**Comment by Statev-Bonsai** [comment]
mach ich dir fertig, kein problem :)

**Comment by Statev-Bonsai** [comment]
@Pregon 
https://www.youtube.com/watch?v=7qMG2g18iBM

**Comment by Pregon** [comment]
Wäre es mit der Uhr zusammen gegangen oder hat die Uhr das auch noch blockiert?

**Comment by Statev-Bonsai** [comment]
@Pregon habe den fehler gefunden... der fehler ist der ring der auf dem maskenslot liegt und wohl das bandana im system überschreibt...

**Comment by QA-Pregon** [comment]
War auch meine Vermutung irgendwann mal dass was anderes das Problem ist, hatte nur vergessen dich nach den Sachen zu fragen die du noch amhattest, aber danke dir

**Comment by simplycach** [comment]
Da können wir dann leider nicht viel machen.
