### ISSUE TITLE
Werkstatt uncle jaceks radius 

### ISSUE THREAD

**Issue by nikosz233** [mexyn/statev_v2_issues#3762]
Mit absprache von eru soll ich hier reinschreiben das der radius für die fahrzeuge für rep tuning und lackieren erweitert werden soll bis hinter die werkstatt wenn das möglich ist. Haben leider bisschen platz probleme :)

**Comment by SatyriaDine** [comment]
Zum nächsten Update habt ihr etwas mehr Platz zum Reparieren und co. :)
