### ISSUE TITLE
Zugänge / Tore Haus house_Vespucci_1

### ISSUE THREAD

**Issue by Ruby-Cross** [mexyn/statev_v2_issues#3765]
Charakter Sara Bran, das Haus wurde gestern abend gekauft 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
generell

**Beobachtetes Verhalten**
 beide Tore als Zugang für das Grundstück sind geschlossen und können nicht geöffnet werden, so dass jedes Mal darüber geklettert werden muss 

**Erwartetes Verhalten**
 Zugang zum Gelände auf den normalen Weg wäre schön(er), vielleicht kann man eines oder beide Tore entfernen, vorzugsweise das größere, damit man das Gelände betreten könnte, ohne wie ein Einbrecher zu wirken. 
 
**Optional: Video / Bilder des Fehlers**
![Tor hinten](https://github.com/user-attachments/assets/7ea81008-b365-4e12-ac3e-f3b6e1184bcf)
![Tor vorn](https://github.com/user-attachments/assets/506bcf1f-6de8-4edd-bef9-938691bc13d5)

**Comment by SatyriaDine** [comment]
Hello Hello, einerseits kann ich direkt sagen dass wir sowas nicht mehr entfernen aus Performancegründen und andererseits habe ich es mir sogar angeschaut und ich könnte es nicht mal so einfach entfernen weil an diesen Toren Details von anderen Häusern in der Häuserreihe hängen. 

Das einzige was ich dir anbieten könnte, wäre deinen Hauseingangsmarker vor das kleine Tor zu verlegen. Ist nicht schön, aber immerhin müsstest du so nicht mehr wie ein Einbrecher über die Mauer und Zaun klettern. :)

**Comment by Ruby-Cross** [comment]
Hey, 

das wäre nice :), aber ich will jetzt nicht beim kleinen Finger die ganze Hand nehmen, vors große vielleicht? da parkt man das Auto ein, ich glaube realistischer braucht man das mehr. Auf jeden Fall danke für die schnelle Antwort und Hilfe.

**Comment by SatyriaDine** [comment]
Hey hey, ich hab dir den Hausmarker nun ans Tor wo auch der Garagenmarker ist hingesetzt. Ist zwar nach wie vor nicht schön gelöst aber besser als in sein eigenes Haus immer "einbrechen" zu müssen :D Ist dann beim nächsten Update geändert. :)
