### ISSUE TITLE
Fehlerhafter Hut sorgt für Identitäts wechsel in Sekunden

### ISSUE THREAD

**Issue by IKuraudoo** [mexyn/statev_v2_issues#3766]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Frank_Guarana

**Auftrittszeitpunkt (Datum / Uhrzeit)**

12:50Uhr 24.09.2024

**Beobachtetes Verhalten**

Der Hut "[M] Secruity Snapback" funktioniert nicht. 
Wenn du die Cap anziehst bekommst du eine neue Frisur und diese Kannst du im Kleidungs Menu sogar noch ändern. 
Neue Identität in Sekunden Quasi

**Erwartetes Verhalten**

Hut Ausrüsten und auch richtig anziehen

**Schritte um den Fehler nachvollziehen zu können**

Man kann den Hut kaufen im Laden und dann brauch man ihn nur anziehen. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

 
![grafik](https://github.com/user-attachments/assets/1d785ca6-5dc3-4343-95fa-d14c0df1e620)
![grafik](https://github.com/user-attachments/assets/18f98253-c726-45e9-aa35-81272ef132fa)
![grafik](https://github.com/user-attachments/assets/4bcaec42-5cd8-4a02-90f2-39f3f85422b1)
![grafik](https://github.com/user-attachments/assets/d1e407a0-f906-42e4-a385-165b72611bee)

**Comment by Jessssssi** [comment]
ich hab sie gestern für meinen weiblichen Char gekauft, bei der Anprobe war sie sichtbar und hat alles gepasst, beim Aufsetzen nach dem Kauf war sie dann unsichtbar, Friseuren kann man aber ändern

**Comment by ySimbaa** [comment]
Cap sollte eig nicht IC sein. Daher auch kein Bug, die funktioniert einfach nicht
