### ISSUE TITLE
Schwarze Shiesty Maske 

### ISSUE THREAD

**Issue by Zweigesicht** [mexyn/statev_v2_issues#3767]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Luciano Valencia

**Auftrittszeitpunkt (Datum / Uhrzeit)**
immer

**Beobachtetes Verhalten**
gesicht bugged durch die maske 

**Erwartetes Verhalten**
Maske bedeckt die stellen komplett

**Schritte um den Fehler nachvollziehen zu können**
Schwarzes Shiesty kaufen und anziehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://github.com/user-attachments/assets/d5109dd8-290d-4958-953c-cddfe8f7abe5)

**Comment by QA-Pregon** [comment]
Ich zitiere: "Es wurde alles rausgeholt durch die pedconfig was nur möglich ist"
Den Rest des Zitats lass ich bewusst mal weg :)
Ist leider nicht möglich da was zu ändern
