### ISSUE TITLE
Anfrage für ein Map Icon fürs Pacific Paradies

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3768]
Moin wir wollten einmal anfragen, ob ihr uns auch das Club Icon geben könntet am Pacific Paradies. Ich bedanke mich schon mal im vorraus ^^
![image](https://github.com/user-attachments/assets/ccf13372-a6ae-4d1d-9a7b-20ac278fd703)

**Comment by SHaagmann** [comment]
Nachdem mich Eru verzweifeln lassen hatte wieder auf und ergänzung:
Sowas hier:
![image](https://github.com/user-attachments/assets/1c5ac56b-0076-4b3e-b1bc-ddc3a1880178)

**Comment by SatyriaDine** [comment]
Helloooo ihr solltet zum nächsten Update auch auf der Map auffindbar sein. :D
