### ISSUE TITLE
HUD Verschiebt sich nach oben

### ISSUE THREAD

**Issue by SEUKings** [mexyn/statev_v2_issues#377]
**Character Name**
Calvin_Kings

**Zeitpunkt (Datum / Uhrzeit)**
22.11.2020 12:30 Uhr

**Beobachtetes Verhalten**
Mein ausrüsten von Waffe und gleichzeitigem öffnen vom Inventar verschiebt sich das HUD nach oben 

**Erwartetes Verhalten**
das es sich nicht nach oben verschiebt ? ^^

**Optional: Video / Bilder des Fehlers**
https://prnt.sc/vnrmc0

**Comment by DrGrizzlY17** [comment]
Schon vorhanden
