### ISSUE TITLE
Teilreparatur Tug nicht möglich

### ISSUE THREAD

**Issue by Kambadin** [mexyn/statev_v2_issues#3771]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Brian Mason**

Brian Mason
**Auftrittszeitpunkt (Datum / Uhrzeit)**

25.09.2024 15:28
**Beobachtetes Verhalten**
Tug geht nicht an da es zu schwer beschädigt ist. Reparaturkasten nutzen um es Teilweise zu reparieren funktioniert nicht da er kein Auto erkennt. Wenn ich am Steuerrad stehe sagt er mir ich soll aussteigen.

**Erwartetes Verhalten**
Tug sollte zumindest wieder fahrtüchtig sein um in die Werkstatt (wenn vorhanden) zu fahren. 

**Schritte um den Fehler nachvollziehen zu können**
Tug kaputt machen und versuchen zu reparieren mit Repkasten.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by QA-Pregon** [comment]
Next Update
