### ISSUE TITLE
Antrag für eine Garage

### ISSUE THREAD

**Issue by RyanTears** [mexyn/statev_v2_issues#3772]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Ryan Tears + Elena Tears**

**Aktuell**

**Antrag für eine Garage am West Mirror Drive 25 , Hash: house_Vinewood_25**

**Es ist zwar ein kleines Gelände, bietet aber durch die Überdachung, trotzdem platz als Carport ,siehe Bild.**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Vide
![Mirror Drive 25](https://github.com/user-attachments/assets/0041a66d-6e88-4ff0-b01e-8689444ff8ac)
o / Bilder des Fehlers**

**Comment by SatyriaDine** [comment]
Hey hey, ich habe dir einen Garagenmarker gesetzt. Der ist dann mit dem nächsten Update auch da. :)

**Comment by RyanTears** [comment]
Guten Morgen,
Gab ja ein kleines Update am 5.10.24.
Garage, ist noch nicht vorhanden.
Wäre Toll wenn es dann beim nächsten "Update" dabei wäre.
Mfg
