### ISSUE TITLE
Flagg gilt nicht als Maskierung bei Frauen

### ISSUE THREAD

**Issue by Shiiinjoo** [mexyn/statev_v2_issues#3773]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Catalina Espinosa**

**26.09.24 / 21 Uhr**

**Das Bandana Wird bei Frauen nicht als Maske gezählt bei Shops usw.**

**Wen man das Bandana über Komma auf Face wechselt wird es nicht als Maske gezählt bei Männer schon**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**![Screenshot 2024-09-26 210520](https://github.com/user-attachments/assets/f6e31354-5418-40c1-99c8-234764e0c077)s**

**Comment by Statev-Bonsai** [comment]
https://github.com/eiksch/statev_v3_issues/issues/3761

wird das gleiche sein...

**Comment by Statev-Bonsai** [comment]
wenn du einen ring auf dem maskenslot hast nehm den mal ab, dann sollte es funktionieren...

**Comment by simplycach** [comment]
Jap genau, da können wir nicht viel machen.
