### ISSUE TITLE
Objektentfernung - Tür Fix am Haus möglich? :)

### ISSUE THREAD

**Issue by CalebPapaCrane** [mexyn/statev_v2_issues#3774]
Grüße, würd gern die 3 Liegen entfernen lassen und die Türen durchgehbar machen oder entfernen lassen, was auch immer besser geht :)

![Screenshot_3](https://github.com/user-attachments/assets/50617bda-bd8b-4643-a7ed-541330dca219)
![Screenshot_1](https://github.com/user-attachments/assets/0691a938-c4ab-43b5-b5bd-8f2b22e6b560)
![Screenshot_2](https://github.com/user-attachments/assets/25cd2b4d-c573-48cb-b5ae-a6010c193ebb)
![Screenshot_4](https://github.com/user-attachments/assets/22c9d297-dea7-4db4-acf1-066cf9a367d1)

**Comment by SatyriaDine** [comment]
Hello da können wir leider nichts machen, da wir allgemein keine Objekte mehr aus Performancegründen entfernen :)
