### ISSUE TITLE
Bestellfenster schließt sich nicht nach Ende der Bestellung

### ISSUE THREAD

**Issue by CaddyLo** [mexyn/statev_v2_issues#3775]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**
 Louisa Alvarez

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 28.09.2024 14:11 Uhr

**Beobachtetes Verhalten** 
 Beim Essen gehen im lucky Plucker hat sich nach der Bestellung das bestellfenster nicht mehr geschlossen. sondern erst nach einem game naustart

**Erwartetes Verhalten**
 Nach dem Bestellen sollte sich das bestellfenster schließen

**Schritte um den Fehler nachvollziehen zu können**
 Essen bestellen und bezahlen 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
  /

**Optional: Video / Bilder des Fehlers**
 https://prnt.sc/sJKNAVhF0QgT

**Comment by simplycach** [comment]
Habe ich leider noch nie gehabt selber, vielleicht haben ja andere User das Problem auch und können ihre Erfahrungen teilen, sonst wird es extrem schwer das nachzustellen.

**Comment by simplycach** [comment]
Da bisher keine weitere Meldung kam, würde ich das hier mal schließen.
