### ISSUE TITLE
Abladepunkt versetzen

### ISSUE THREAD

**Issue by JB98989** [mexyn/statev_v2_issues#3776]
**Character Name**

David Morgan

Guten Tag,
wir haben an unserem Firmenkomplex folgenden Fall, dass die drei Firmen die rot umkreist sind den roten Verladepunkt auf der Straße haben. Die Firmen die Lila umkreist sind den lila Abladepunkt haben. Und die Orangene Firmen den einzelnen Abladepunkt auf dem Hof hat. Nun ist es dadurch sehr umständlich mit großen Fahrzeugen den Punkt anzufahren. Daher würden wir uns freuen, wenn man diesen auch auf die Straße legen könnte.

Firmenhash: pf_Alta__1

Mit freundlichen Grüßen

![Screenshot 2024-10-01 155552](https://github.com/user-attachments/assets/baf60916-4a50-4e5f-9320-050661982139)

**Comment by SatyriaDine** [comment]
Hello der Marker ist nun nicht mehr auf dem Parkplatz und besser mit großen Fahrzeugen erreichbar. Next update dann auch da. :)
