### ISSUE TITLE
Tackeln geht nicht mehr

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3777]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

AJ
**Auftrittszeitpunkt (Datum / Uhrzeit)**

Seit längerem schon nicht mehr
**Beobachtetes Verhalten**

Das Umtackeln mit "Ö" funktioniert nicht mehr
**Erwartetes Verhalten**

Es funktioniert weiterhin oder man bekommt ne Nachricht, dass es entfernt wurde (Discord nicht IC beim Probieren)
**Schritte um den Fehler nachvollziehen zu können**

Rennen und jemanden an öen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by rodistic** [comment]
Ayy Gude,

das feature ist bewusst nicht mehr da.

**Comment by SHaagmann** [comment]
Gude, hatte ich mir gedacht und mir wurd gesagt ich soll n tracker machen
