### ISSUE TITLE
Interior Bug Haus Klasse 3 Edel Villa Rustikal

### ISSUE THREAD

**Issue by AlecAlexis** [mexyn/statev_v2_issues#3778]
Name:
Alexis Garcia

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Beobachtetes Verhalten**
siehe Video

**Erwartetes Verhalten**
Möbel nutzbar, oder zumindestens nicht durchlaufbar

**Schritte um den Fehler nachvollziehen zu können**
In ein Klasse 3 Haus mit dem Interior "Edel Villa Rustikal" gehen und durch die halbe Einrichtugn laufen.

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=DlKSU8u0mn4

Anmerkung: Es ist vielleicht auch nicht mehr so zeitgemäß das ein Interior mit dem Namen "Villa" nur einen großen Raum hat und alle anderen Türen sind zu, während man jetzt schon Appartements hat die gefühlt größer sind. Der Umbau eines solchen Interior liegt zwischen $63000 - $90000. Wobei die "Edel Villa Rustikal" das teuerste ist aber man gefühlt nur einen großen Raum hat.

**Comment by SHaagmann** [comment]
Duplikat #3709 Zumindest vom melden des durchlaufens

**Comment by AlecAlexis** [comment]
Die Frage ist ja auch ob man so ein "kaputtes" interior nicht rauslässt, wenn es so broken ist. Es ärgern sich Leute das sie mit so einer hauseinrichtung nichts anfangen können. Wir haben ja mittlerweile genug andere schöne Einrichtungen.

**Comment by Erumeldor** [comment]
Schauen wir mal, maybe bekommen wir das ja doch gefixt.
Wird aber etwas dauern.
