### ISSUE TITLE
Tablet Animation beim sitzen nach schließung vom tablet

### ISSUE THREAD

**Issue by Fabse96** [mexyn/statev_v2_issues#378]
Fabio_Gonzales
**Zeitpunkt (Datum / Uhrzeit)**
22.11.2020 / 12:42

**Beobachtetes Verhalten**
Beim sitzen das Tablet öffnen und beim beenden wird die tablet animation weiter geführt

**Erwartetes Verhalten**
das die normale sitz animation weitergeführt wird

**Schritte um den Fehler nachvollziehen zu können**
auf stuhl setzten (ruhig sitzen) dann das Tablett öffnen und wieder schließen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![tablet](https://user-images.githubusercontent.com/74773267/99902774-89ab9b00-2cc0-11eb-8809-005b5d9f7217.PNG)

**Comment by its4l3x** [comment]
Fixed. Next Update
