### ISSUE TITLE
Angeschnallt, nachdem man aus dem Auto "geboxt" wurde

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3786]
## **Charname**
Alexander_Jones
## **Discord-Name**
Bene / OnkelHomie
## **Auftrittszeitpunkt**
Vor ca 2 Wochen zum ersten Mal
## **Beobachtetes Verhalten**
Ich saß angeschnallt in meinem Fahrzeug. Ein Officer hat mich aus dem Auto gestoßen um mit den anderen auszuspielen, dass sie mich aus dem Wagen gezogen haben. Als ich im Streifenwagen saß mit Handschellen, konnte ich nicht mehr aussteigen, da ich noch immer angeschnallt war. Abschnallen konnte ich mich nicht, da ich in Handschellen im Wagen saß.

**Comment by QA-Pregon** [comment]
Next Update
