### ISSUE TITLE
Unser liebster 24/7 Verkäufer will uns kein Geld mehr geben

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3787]
## **Charname**
Eve_Baker
## **Discord-Name**
Jessi
## **Auftrittszeitpunkt**
ca 2 Wochen
## **Beobachtetes Verhalten**
Seitdem unsere Fraktion kurzzeitig aufgelöst war und wir diese wieder bekommen haben, konnten wir den Kassierer vom 24/7 in Little Seoul nicht mehr einnehmen. Am anfang wurde uns noch gesagt das wir den code bekommen haben, sobald wir aber nach hinten gehen bekommt man einfach nur die meldung das wir den Code benötigen. Trotz mehrere versuche kriegen wir trotzdem kein schutzgeld mehr von dem netten Bobby. Vielleicht läuft das ganze noch auf unsere 'alte' frak? bitte mal nachschauen :(

**Comment by SHaagmann** [comment]
Haben gleiches Problem in Paleto ohne Frak Auflösung

**Comment by simplycach** [comment]
Mhm, also haben wir einmal eine Frak-Auflösung und 1x ohne. @SHaagmann war der Laden vorher im Besitzt von jemanden anderen also ich vermute mal ja somit wird es dasselbe Problem sein an sich. Wir schauen mal was wir tun können.

**Comment by SHaagmann** [comment]
@simplycach jo war mal unserer und wir wollten ihn wiederholen kann dir noch nen Clip zukommen lassen dafür

**Comment by QA-Pregon** [comment]
Betroffene Fraks bitte ein Ticket aufmachen
