### ISSUE TITLE
Telefonieren im Prison

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3788]
Normalerweise müsste ja das Item nachdem man telefoniert hat verschwinden, macht es aber net... ^^

**Comment by simplycach** [comment]
Welches Item genau meinst du, das Smartphone ?

**Comment by Statev-Bonsai** [comment]
nein, das möchte ich hier nicht reinschreiben weil die gefahr besteht das es andere zu ihren vorteil nutzen. hätte ja ticket aufgemacht, aber da man sich jedes mal unwohl fühlen muss wenn man ein ticket aufmacht habe ich es nicht gemacht...

**Comment by QA-Pregon** [comment]
schreibs mir oder simply am besten auf DC

**Comment by QA-Pregon** [comment]
> aber da man sich jedes mal unwohl fühlen muss wenn man ein ticket aufmacht habe ich es nicht gemacht

Und dazu frag ich mich warum das so ist
Ich hab früher teilweise 3 gleichzeitig gehabt und das war nie ein Problem

**Comment by simplycach** [comment]
Sind interne Infos, werden hier nicht publik gemacht. Weiß aber bescheid was er meint.
