### ISSUE TITLE
Steuer wird am Marktplatz falsch berechnet

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3789]
## **Charname**
Brian Mason
## **Discord-Name**
Kambadin
## **Auftrittszeitpunkt**
05.10.2024 08:50
## **Beobachtetes Verhalten**
Tritt auch bei Werkstätten auf. Die Steuer wird auf den Bruttobetrag berechnet und dann abgezogen wenn man was am Marktplatz verkauft bzw. in der Werkstatt die Rechnung bezahlt. In meinem Beispiel wurden somit 5,26% Steuer tatsächlich berechnet. Klingt eigentlich nicht viel waren aber direkt ca. 2,50$ Wenn man sehr viel über den Markt verkauft oder auch bei Werkstätten die Reparaturen dann läbbert sich das aber schnell zu einem größeren Betrag zusammen. Wäre es in diesem Zusammenhang möglich die Beträge komplett auf 2 Nachkommastellen zu begrenzen. Ist echt Nervig wenn man immer 1 Cent auf dem Konto lassen muss da der nicht umzubuchen geht. In V1 gab es das auch mal da wurde es dann behoben soweit ich das noch weis.

**Comment by QA-Pregon** [comment]
#3305 
Müsste das gleiche sein, falls du was anderes meinst bitte nochmal genau beschreiben

**Comment by Kambadin** [comment]
Nein ist nicht das gleiche. Bei #3305 geht es um das einstellen in den Markt und die Anzeige. Bei mir geht es um direkte falsch Berechnung. Wenn jemand was an der Tür (oder Werkstattcomputer) kauft dann wird da der Bruttopreis angezeigt. Normal sollte jetzt wenn man mal als Beispiel 100$ nimmt auf dem Konto 100$/1,05= 95,24$ erscheinen. Gerechnet wird aber in der Formel akuell 100$-(100$*0,05)=95,00

Wie gesagt bei 100$ ist das nicht viel aber wenn man mehrere Tage Rechnungen über mehrere 1000 Dollar ausstellt (Werkstatt lackieren) damm summiert sich das ganze zu einer größeren Summe.

**Comment by QA-Pregon** [comment]
Ok ja, hat bei mir gerade mathematisch einen Moment gedauert aber jetzt glaub ich zu denken, dass du Recht hast, ich sprech das mal ab wie das sein soll

**Comment by QA-Pregon** [comment]
Ok nach Absprache mit Outburst ist das extra so.
Das Steuersystem ist so, dass es ein Steuerintegiertes Preissystem ist, heißt die Steuern kommen nicht auf den Preis drauf, sondern werden vom Kaufpreis abgezogen.
