### ISSUE TITLE
Keinen Skin nach login

### ISSUE THREAD

**Issue by Chrinis007** [mexyn/statev_v2_issues#379]
**Character Name**
Christian_Maier

**Zeitpunkt (Datum / Uhrzeit)**
Jetzt

**Beobachtetes Verhalten**
Keinen Skin

**Erwartetes Verhalten**
Richtigen skin

**Schritte um den Fehler nachvollziehen zu können**
Keine ahnung

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/jamie.GHD5s

**Comment by its4l3x** [comment]
Hatten wir gestern auch schon. Die Person soll einfach mal sich an- und ausziehen. Ist ein Problem wenn Internet der Person relativ schlecht ist. (Hoher Ping, etc...).  Müssen wir uns aber trotzdem mal genauer anschauen.

**Comment by its4l3x** [comment]
Nochmal aufgetreten?

**Comment by Chrinis007** [comment]
Nein

**Comment by its4l3x** [comment]
Top. Schließe ich dann erstmal wieder.
