### ISSUE TITLE
Loch in der Matrix

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3793]
## **Charname**
Kofi_Mutambo
## **Discord-Name**
jentaroE.
## **Auftrittszeitpunkt**
wann immer man bei meiner Firma zur stelle läuft
## **Beobachtetes Verhalten**
man fällt durch die Erde und spawnt nach dem fallen auf der Straße wieder.
ich habe die stelle erstmal abgesperrt es ist 7020 auf dem kleinen Parkplatz rechts des 24/7(nur optisch) Geschäfts.

**Comment by Erumeldor** [comment]
Ohne Bild, Koordinate oder genaue Beschreibung nicht zu gebrauchen. Kann hier jemand nachliefern?
