### ISSUE TITLE
Wasser in der lost bar am casino?

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3794]
## **Charname**
Luciano Valencia
## **Discord-Name**
Ŧαcε 2 Ŧαcε
## **Auftrittszeitpunkt**
06.10.2024 20:12
## **Beobachtetes Verhalten**
Man schwimmt in der bar
## **Anhänge**
<br>[Link](https://ibb.co/QKsRmCn)<br>

**Comment by K0elschi** [comment]
Ein ähnliches Problem habe ich an meinem Haus.
Je nach Blickwinkel stehe ich auf der Terrasse auch auf einmal unter Wasser.
![Bild_2024-10-07_123338233](https://github.com/user-attachments/assets/c9a8bed7-a365-45e1-8fe4-0ec7244e30f9)
Char Name: Timothy_Goodsen
Haus ist bei PC 7068

**Comment by simplycach** [comment]
Habt ihr Mods drauf ?

**Comment by K0elschi** [comment]
> Habt ihr Mods drauf ?

Ich habe nur Reshade drauf. Fehler ist aber auch da, wenn ich alle Reshade Shader deaktiviert habe.

**Comment by QA-Pregon** [comment]
Habt ihr Pools aufgestellt
Lost Bar auf dem Dach?
K0elschi du auf der Etage über der wo du stehst?

**Comment by QA-Pregon** [comment]
Liegt beides jeweils an einem aufgestellten Pool
