### ISSUE TITLE
Tritbrett Ambulance

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3796]
## **Charname**
Carlos Jasso
## **Discord-Name**
KakaoSchlumpf
## **Auftrittszeitpunkt**
21:40 ca
## **Beobachtetes Verhalten**
Joa es hat sich das tritbret aeiner ambulance gelöst ist über die straße gebugt wo ich grad rüber lief und hat mich so ca 20 meter in die luft geworfen

**Comment by simplycach** [comment]
Wird nen Einzefall gewesen sein, wenn es nochmal auftritt bitte ein Video dazu hochladen.
