### ISSUE TITLE
E-bike Super speed

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3797]
## **Charname**
Tobias_Springer
## **Discord-Name**
Lostaufmbagger
## **Auftrittszeitpunkt**
immer
## **Beobachtetes Verhalten**
Auf den Inductor Ebikes Springen und nach vorne lehnen hat uns dermaßen beschleunigt das mans kaum beschreiben kann. 

ist der Bug bekannt oder Gta v Fehler ?

**Comment by QA-Pregon** [comment]
Yes is GTA Problem
