### ISSUE TITLE
Kann keine Mitbewohner einladen

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3798]
## **Charname**
Kelly Winchester
## **Discord-Name**
Lucy 💜
## **Auftrittszeitpunkt**
08.10.24  20:55
## **Beobachtetes Verhalten**
Habe ein Loft gemietet und wollte da dann meine Mann als Mitbewohner ins Loft einladen. Dies ging jedoch nicht.
## **Anhänge**
<br>![Bild](https://pic.statev.de/i/HXrU5z.png)<br>

**Comment by JensGamerBoy** [comment]
Ja kann ich so bestätigen geht bei mir auch nicht leider

**Comment by simplycach** [comment]
Habt ihr es über den Browser oder IC Tablet versucht ? 

Seit ihr bereits in mehren Apartments eingemietet bzw. die eingeladen werden möchten ?

Mal nach einem Game Neustart probiert ?

**Comment by Falk-Alers** [comment]
Grüße,

alles was du aufgezählt hast Simplycach wurde versucht.
Auch den Serverneustart haben wir abgewartet und erneut danach ausprobiert.
