### ISSUE TITLE
E-GT Ist komplett Verbuggt fährt 500+ Kmh

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3799]
## **Charname**
Luciano Valencia (tritt aber bei allen spielern auf)
## **Discord-Name**
Ŧαcε 2 Ŧαcε
## **Auftrittszeitpunkt**
09.10.2024 3:20
## **Beobachtetes Verhalten**
E-GT fährt über 500 Kmh
## **Anhänge**
<br>[Link](https://www.youtube.com/watch?v=9JLNPmHg7cY)<br>

**Comment by Erumeldor** [comment]
Liegt ein wenig am Elektroauto das du den negativen Effekt nicht spürst - du kannst da IC mal in eine Werkstatt gehen ;)
Im nächsten Update gibts dazu noch einen anderen Nerf.
