### ISSUE TITLE
Fahrzeug nicht ausparken können.

### ISSUE THREAD

**Issue by Ordnael1044** [mexyn/statev_v2_issues#38]
**Zeitpunkt (Datum / Uhrzeit)**
25.08.2020 21:00

**Beobachtetes Verhalten**
Fahrzeug war laut Tablet in der Vinewood West Garage. Fahrzeug war für mich nicht eingelagert. Jemand anderes konnte das Fahrzeug ausparken.

**Erwartetes Verhalten**
Fahrzeug sollte Auflisten und Ausgeparkt werden können.

**Schritte um den Fehler nachvollziehen zu können**
Tablet öffnen -> Schauen wo das Fahrzeug ist -> an der Garage die Liste von eingeparkten Fahrzeugen öffnen.

**Optional: Video / Bilder des Fehlers**
![Download](https://user-images.githubusercontent.com/70153799/91219118-6cdfe580-e71a-11ea-8bad-be7da0a7f065.png)

**Comment by tastydev** [comment]
Bist du der Besitzer des Autos?

**Comment by Kalumel** [comment]
Hatten das Problem auch. Derjenige der ausparken wollte war Besitzer. Ich, der nur den Schlüssel hat, konnte das Auto ausparken. @tastydev

**Comment by Ordnael1044** [comment]
Ja ich bin Besitzer des Fahrzeugs. Ich habe den Schlüssel jemand anderem gegeben und er konnte das ausparken. die Fahrzeuge bei anderen Garagen wurden mir Angezeigt.

**Comment by DrGrizzlY17** [comment]
@Ordnael1044 das heißt zu dem Zeitpunkt als du das Fahrzeug ausparken wolltest, hattest du kein Schlüssel des Fahrzeuges?

**Comment by Ordnael1044** [comment]
Doch ich hatte den Schlüssel. Ich hatte der Anderen Person danach den schlüssel gegeben und er konnte es dann ausparken.
