### ISSUE TITLE
Verladepunkt bitte versetzen.

### ISSUE THREAD

**Issue by Falk-Alers** [mexyn/statev_v2_issues#3800]
## WICHTIGE INFORMATION!!:

**Character Name**
Scott Winchester

**Beobachtetes Verhalten**
Verladepunkt Doof
Der Verladepunkt liegt relativ weit auf der Straße und dann kurz vor einer Kurve.

**Erwartetes Verhalten**
Kann umgesetzt werden

**Schritte um den Fehler nachvollziehen zu können**
Grüße,
unser Verladepunkt ist ist ein wenig doof, die ganze Straße wäre dicht.
Aber unsere Firma hat einen eigenen kleinen Parkplatz und eine perfekte Gasse für einen Verladepunkt.
Es wäre super wenn Ihr uns den Punkt dort in die Gasse setzen würdet (siehe Bilder).

**Optional: Video / Bilder des Fehlers**

![Grand Theft Auto V Screenshot 2024 10 09 - 07 40 42 71](https://github.com/user-attachments/assets/735d505e-421f-45da-b78e-b2ca7a302d80)

![Grand Theft Auto V Screenshot 2024 10 09 - 07 41 19 24](https://github.com/user-attachments/assets/acc5bf6f-3019-472f-9479-79ed125e9fef)

![Screenshot 2024-10-09 130143](https://github.com/user-attachments/assets/1f0bea6b-c2cf-48d4-9a40-d18d6d14569a)
Wenn der Punkt wie im unteren letzten Bild gesetzt wird, kann man mit jedem Fahrzeug dort Problemlos hinein.

**Comment by SatyriaDine** [comment]
Hello, habe deinen Abladepunkt versetzt. Next Update dann. :)

**Comment by Falk-Alers** [comment]
Vielen Dank
