### ISSUE TITLE
Abladepunkt etwas versetzen

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3801]
## **Charname**
Brian Mason
## **Discord-Name**
Kambadin
## **Auftrittszeitpunkt**
10.10.2024 08:00
## **Beobachtetes Verhalten**
Pounder geht nicht regulär rückwärts am Abladepunkt. Man muss vorwärts ranfahren. Das sieht nicht schön aus. Bilder füge ich gleich noch hinzu.

**Comment by Kambadin** [comment]
![image](https://github.com/user-attachments/assets/b6c867d7-0b67-46c3-a0a0-3c7b04a45c3c)
![image](https://github.com/user-attachments/assets/9ad4e14b-ca35-4a4e-8730-91136e83a35a)

**Comment by SatyriaDine** [comment]
Hey hey, habe deinen Marker ein wenig geschubst sodass nun auch Pounder vernünftig abladen können. :) Next update dann.
