### ISSUE TITLE
Firmenauktion Export Sandy Shores nicht vorhanden

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3802]
## **Charname**
David_Morgan
## **Discord-Name**
JB | Alex
## **Auftrittszeitpunkt**
10.10.2024 | 14:10
## **Beobachtetes Verhalten**
Das Map Icon ist zwar da, aber weder der Punkt noch der NPC sind zu sehen.
## **Anhänge**
<br>[Link](https://pic.statev.de/image/HXNuVY)<br> <br>[Link](https://pic.statev.de/image/HXNalw)<br>

**Comment by Snipser92** [comment]
Der Dude wurde vor Wochen mal umgesetzt. Schau dich da mal genauer um. der ist definitiv da. Der Marker auf der Karte stimmt nur nicht zu 100%

**Comment by QA-Pregon** [comment]
Ans Gamedesign, hier bitte nur den Marker umsetzen, ansonsten passt hier alles
