### ISSUE TITLE
Volles Lager --> Marktplatzeinstellung nicht möglich

### ISSUE THREAD

**Issue by glb11** [mexyn/statev_v2_issues#3803]
**Character Name**
Jens_Holt (Trash Transformers)

**Auftrittszeitpunkt (Datum / Uhrzeit)**
10.10. ca 18:00 (+5.10 23:20  damals keine Zeit Fehler genauer einzukrenzen)

**Beobachtetes Verhalten**
Beim Verkaufsangebot Einstellen im Marktplatz kann man nicht den Vollen Lager-Inhalt einstellen. Folgende Meldung kommt dann:  "Du kannst keine Marktplatzorder erstellen wenn die Firma voll ist" 
Marktplatzplatz ist verfügbar

**Erwartetes Verhalten**
Mann kann den Vollen Lagerinhalt einer Firma einstellen (1200KG/L)

**Schritte um den Fehler nachvollziehen zu können**
1200l Liter Erdöl im RC Lager legen und versuchen in den Marktplatz zu stellen da kommt die Fehlermeldung:  "Du kannst keine Marktplatzorder erstellen wenn die Firma voll ist" (Teilmenge einstellen auch nicht möglich).  Wenn man 1 Liter raus tut geht es ohne Probleme.

**Optional: Video / Bilder des Fehlers**
![20241010181952_1](https://github.com/user-attachments/assets/47e555e3-f64e-409b-8fdf-8ebb0141292a)

**Comment by Snipser92** [comment]
Die Meldung bekommst du wenn du die Gesamtzahl an An- und Verkäufen überschreiten würdest. Da ist der Ankauf mit eingebunden.

**Comment by glb11** [comment]
Kann auch sein.  Aber in diesem Fehler ist es so sobald ich nur noch 1199 Liter öl im Lager liegt ( 1kg Platz) ist. Kann ich das Inserat ohne Probleme erstellen im ak sind nur 9 Gesuche

**Comment by DerHessenTyp** [comment]
Wird im Changelog vom 19.04.2024 erwähnt. Das Problem war zu dem Zeitpunkt dass man einfach das Lager vollgemacht hat, seine Sachen rausgenommen hat und man mehr im Lager liegen hat was eig. möglich wäre. Und am Ende zum Beispiel eine Webrei das genutzt hat um 1000x Rollen Stoff anzubieten, wo eig. nur 500x maximal ins Lager gingen.

Auszug aus dem Changelog: [CHANGED] Mit einem vollen Lager kann man keine neue Marktplatz-Order mehr erstellen.

Vielleicht kann man es ja unterscheiden z.w. Ankauf und Verkauf weil gerade bei Firmen wenns Lager voll ist und du kein Lager selbst hast könntest du bei zuviel produziert einen Sonderverkauf machen.

**Comment by glb11** [comment]
Noch als Kleine Ergänzung:

Ende September ging das einstellen von 1200l Erdöl im RC noch ohne Probleme.

Ein einfacher Lösungsvorschlag wäre das Lagevolumen ganz leicht (1-10kg) zu erhöhen so wäre sichergestellt das Mann die inzwischen sehr geläufigen Transporteinheiten(Achse/Trailer) mit einmal verkaufen kann.

**Comment by QA-Pregon** [comment]
Wie DerHessenTyp schreibt "[CHANGED] Mit einem vollen Lager kann man keine neue Marktplatz-Order mehr erstellen"

Heißt das Lager darf nun mal nicht voll sein, da wird auch nicht in naher Zukunft dran geändert.
