### ISSUE TITLE
Andauernde Crashes

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3805]
## **Charname**
Anne Great
## **Discord-Name**
AMPHI
## **Auftrittszeitpunkt**
Seit 4 Wochen mindestens 1x täglich
## **Beobachtetes Verhalten**
siehe Screenshot - an dieser Stelle habe ich mindestens einmal täglich einen Crash, auch bei anderen Spielern ist es mir aufgefallen, dass sie Crashen. Das alles passiert, wenn man mit mehr als 150 km/h richtung Barrio fährt.
## **Anhänge**
<br>[Link](https://pic.statev.de/image/screenshot-106.HXVEuc)<br>

**Comment by QA-Pregon** [comment]
Irgendwas an Grafikmods oder anderem zusätzlich installiert?
