### ISSUE TITLE
evtl fehlende Bushaltestelle Paleto Sandy

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3806]
## **Charname**
Jamverel Greren
## **Discord-Name**
Stiefel911
## **Auftrittszeitpunkt**
immer
## **Beobachtetes Verhalten**
In Paleto im Kleinbus einsteigen und Tour abfahren, dann wird man feststellen zwischen Grapeseet und Sandy Höhe FD befindet sich an der Kreuzung rechts Seitig zwar eine Haltestelle die aber nicht angefahren wird. gegenüber wird angefahren... "alte Werkstatt".

Denke nicht das es so gewollt ist, falls doch dann sry

So long
## **Anhänge**
<br>[Link](https://pic.statev.de/image/HXV1qT)<br>

**Comment by TheOutburst** [comment]
Joa also
Die Bushalte soll da nicht sein
Gleich fixed
