### ISSUE TITLE
Comet Safari Hitbox Fehlerhaft nach Tuning

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3807]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

AJ
**Auftrittszeitpunkt (Datum / Uhrzeit)**

10.10
**Beobachtetes Verhalten**

Hitbox hat kein bock richtig zu hitboxen
**Erwartetes Verhalten**

Hitbox verhält sich richtig
**Schritte um den Fehler nachvollziehen zu können**

Comet Safari Tunen -> gegen nen Bürgersteig fahren (Der sollte da soeben drüber kommen mit der dezenten Bodenfreiheit)
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://medal.tv/games/gta-v/clips/iQUEI7V231XgtnxP0?invite=cr-MSwyTEosMTk1NTEzMTMzLA

**Comment by TheOutburst** [comment]
Der Fehler ist schon länger bekannt und mehrfach von mehreren Servern zu alt:V eskaliert.
Ich mach hier mal zu, sobald alt:V das fixed ists fixed, bis dahin lößt only ein- und ausparken
