### ISSUE TITLE
Falsche Garage Ticket 9767

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3808]
## **Charname**
Bastian Green
## **Discord-Name**
Bastian Green
## **Auftrittszeitpunkt**
11.10.2024
## **Beobachtetes Verhalten**
Ich habe ein Haus und daneben steht eine Garage die eigentlich eindeutig zu meinem Haus gehört wie man auf dem Bild sieht.
Aber leider habe ich keinen zugriff darauf
## **Anhänge**
<br>[Link](https://prnt.sc/DpQwmTOl9NvO)<br> <br>[Link](https://prnt.sc/2f5DfeJHv5Fq)<br>

**Comment by BastianSeppel** [comment]
darf man mal fragen wie hier der Status Is ?

**Comment by BastianSeppel** [comment]
https://prnt.sc/zZtEBorasoRC
PLZ vom haus

**Comment by SatyriaDine** [comment]
Hello hello, die Garage gehört zu dem Haus neben deinem Haus, die Straße ein Stück hoch. :) Daher schwierig da was zu machen.

**Comment by BastianSeppel** [comment]
okay besteht da den die möglichkeit das haus wieder abzugeben
weil es ist ja eigenntlich ersichtlich das die Garage zu dem Gebäude gehört
Weil so bringt mir das Haus nichsts und ich bekomme es IC nicht verkauft

**Comment by BastianSeppel** [comment]
okay hat sich erledigt es wurde gekauft 🗡️
