### ISSUE TITLE
Position Signalfackel an Hose...

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3813]
Soll das so sein? ^^
Sieht irgendwie Määäääääääääääääääääääh aus, aber so richtig ;D

![Screenshot_2](https://github.com/user-attachments/assets/42d387c8-8820-4066-9d43-25d7da89062b)
![Screenshot_3](https://github.com/user-attachments/assets/9ced04de-3768-4c5a-ab22-1d63cfa8a06b)

**Comment by QA-Pregon** [comment]
geht leider nicht anders
