### ISSUE TITLE
Geschwindigkeit und Durchzug Weevil Custom 

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3814]
Normalerweise ist das Fahrzeug für seinen Kickstart und das dauerhafte fahren auf den Hinterreifen bekannt, so war es in V2 ja auch.
In V3 ist die Geschwindigkeit und der Durchzug für solch ein Fahrzeug absolut mau, man kann mit ihm gar nicht mehr auf 2 Rädern starten weil der Dampf einfach fehlt.
Es ist ja ein Hot Rod mit deutlich PS unter der Haube und kein normaler Weevil ^^

https://youtu.be/HOPFu_sFVpg?si=PgU_WhdimKiIEAFl&t=491

**Comment by Erumeldor** [comment]
Hab das Fahrzeug gerade nochmal angeschaut.
Um den vorne hoch zu bekommen braucht er so viel Leistung, das er nicht mehr zum restlichen Balancing passt.
Ist auch deutlich günstiger wie zu V2, daher leider keine Änderung die dich glücklich machen wird :)
