### ISSUE TITLE
Gedeck Spawnt in der Luft

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3815]
## **Charname**
Steve Parker
## **Discord-Name**
Skipper2502
## **Auftrittszeitpunkt**
12.10.2024 22:50
## **Beobachtetes Verhalten**
Habe das Bestellt Essen dem Kollegen Serviert und das Tablett bzw gedeck ist in der Luft neben dem Tisch gespawnt siehe Foto
## **Anhänge**
<br>[Link](https://ibb.co/1zcNvc9)<br>

**Comment by TheOutburst** [comment]
next update fixed
