### ISSUE TITLE
Dunkelblaue Groove Jeans

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3816]
## **Charname**
Katherine_Lane
## **Discord-Name**
Clara
## **Auftrittszeitpunkt**
Seit ich sie anprobiert habe vor wenigen Tagen :-)
## **Beobachtetes Verhalten**
Wir haben die angekauft, ich hab sie dann probiert um sie vorführen zu können. Dabei hab ich dann gemerkt, dass sie irgendwie.. unsichtbar ist? Oder so. kA!
## **Anhänge**
<br>[Link](https://youtu.be/c-GP1xlXZD8)<br>

**Comment by ySimbaa** [comment]
Hose wird gelöscht, da keine Texture dafür vorhanden ist.
