### ISSUE TITLE
Kart fahren nicht länger als 10 Minuten möglich

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3817]
## **Charname**
Andre Bailey
## **Discord-Name**
DerHessenTyp
## **Auftrittszeitpunkt**
10.08.2024 21:55, 23.09.2024 20:10, 13.10.2024 06:53
## **Beobachtetes Verhalten**
Wenn man mal mehr als die vorgegebenen 4 Runden fahren möchte beim Kart fahren, weil man doch ein wenig mehr Spannung reinbringen möchte, muss man trotzdem immer innerhalb von 10 Minuten im Ziel sein, ansonsten wird das Rennen ohne Wertung beenden. Was ich schade finde weil man ja bis zu 20 Runden auswählen kann und gerade da doch die Spannung oben bleibt wenn man mal wirklich mit mehreren fährt.
Die Rennen wurden wie folgt gefahren:
10.08.2024 um 21:55 Uhr mit 2 Teilnehmern
23.09.2024 um 20:10 Uhr mit 4 Teilnehmern
13.10.2024 um 06:53 Uhr mit 1 Teilnehmer (Um mich nochmal zu vergewissern obs wirklich an den 10 Minuten lag)

Ich würde es toll finden wenn man vielleicht die Zeit erhöhen könnte auf 30 Minuten (Sollte eine Zeitangabe wichtig sein) So hätte man genügend Zeit wenn man wirklich länger auf der Bahn unterwegs ist.

Das Problem, wenn das Rennen beendet wird nach den 10 Minuten bleiben die Karts automatisch auf der Strecke stehen und am 10.08.2024 hatten wir das Problem zum Beispiel dass wir gar kein Rennen mehr starten konnten. Heute Morgen zum Beispiel standen weitere 4 Karts mitten auf der Bahn, die wahrscheinlich das gleiche Problem hatten.

**Comment by QA-Pregon** [comment]
Next update fixxed
