### ISSUE TITLE
Schwebende Lampe am Hafen

### ISSUE THREAD

**Issue by Castillo-Cas** [mexyn/statev_v2_issues#3818]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Castillo Torres**

**13.10.24 um 13:30 Uhr**

**Eine Lampe, die dort glaube nicht schweben sollte**

**Keine schwebende Lampe**

**Einfach am Standort schauen**

1. https://cdn.discordapp.com/attachments/1035394352584855562/1294991143062343762/image.png?ex=670d05fc&is=670bb47c&hm=1c4e8aa2d802bfbca76abfc1e7324d7ecd7846de9454ad19b9215bc99ab96f14&
2. https://cdn.discordapp.com/attachments/1035394352584855562/1294990872340860928/image.png?ex=670d05bb&is=670bb43b&hm=19446f8e302550261f825e76398ffa682413ce0a0bc1b4ad43cf3334c20b06d3&
3. https://cdn.discordapp.com/attachments/1035394352584855562/1294990980331606037/image.png?ex=670d05d5&is=670bb455&hm=829a4aaea9d5acade0959cbfdc4d6c3773faddfd0bb177fecddf6726133f0cd3&
4. https://cdn.discordapp.com/attachments/1035394352584855562/1294991064641441895/image.png?ex=670d05e9&is=670bb469&hm=07173d0a1a2e852d6562eac2b067801704e2ec192ad9f14363fa6e94a8110621&**

**Comment by Erumeldor** [comment]
@Castillo-Cas  Discord-Links sind alle nicht mehr gültig, bitte Bilder nochmal direkt hier hochladen.

**Comment by TheOutburst** [comment]
Keine Rückmeldung
