### ISSUE TITLE
Fahrzeugstatus wird nicht übernommen (Handbremse)

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#382]
**Zeitpunkt (Datum / Uhrzeit)**
22.11.2020 / 13.24
**Beobachtetes Verhalten**
Der Status ob die Handbremse angezogen ist oder nicht wird nach einem Restart wieder auf "nicht angezogen" gestellt

**Erwartetes Verhalten**
Status sollte korrekt gespeichert werden

**Schritte um den Fehler nachvollziehen zu können**
Vorm Restart Handbremse anziehen.
Nach dem Restart wieder einloggen und die Handbremse lösen.

**Comment by its4l3x** [comment]
Gewollt. Kein Bug.
