### ISSUE TITLE
Grundloses abbrechen von Aufträgen

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3821]
## **Charname**
Jim_Walker
## **Discord-Name**
Am0KK1990
## **Auftrittszeitpunkt**
14.10.2024     ca07:10   Ablauf siehe Anhang
## **Beobachtetes Verhalten**
Aufträge werden  ggf. abgebrochen , wenn man vorher bei Carlos ein Auto am schweißen war.     Ablauf im Anhang
## **Anhänge**
<br>![Bild](https://pic.statev.de/i/HXO7Cu.png)<br>

**Comment by QA-Pregon** [comment]
Ist mir bekannt, hab ich auch mal dem entsprechenden weitergegeben, aber glaub da wurde noch nichts gemacht.
Ich sag nochmal bescheid
