### ISSUE TITLE
Firmenwerbung blendet nach unten aus

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3823]
## **Charname**
Maxwell Scott
## **Discord-Name**
jonesxyz
## **Auftrittszeitpunkt**
Dauerhaft
## **Beobachtetes Verhalten**
Firmenwerbung sollte nach oben raus animieren und nach unten rein animieren. 

Macht genau das gegenteil.

**Comment by jonesXYZ** [comment]
Anhang - Progressbar fliegt auch von unten rein!

**Comment by QA-Pregon** [comment]
Sind dran
