### ISSUE TITLE
 Gegenstände können nicht platziert oder abbaut werden

### ISSUE THREAD

**Issue by Digawen** [mexyn/statev_v2_issues#3824]
Ronnie Flex

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit dem Update

**Beobachtetes Verhalten**
Man kann keine Gegenstände platzieren oder abbauen.

z.b.: Tabletts im Restaurant oder halt jedes beliebige Objekt

**Erwartetes Verhalten**
Gegenstände können platziert oder abbaut werden.

**Schritte um den Fehler nachvollziehen zu können**
einfaches Platzieren funktioniert nicht

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
------

**Optional: Video / Bilder des Fehlers**
------

**Comment by QA-Pregon** [comment]
Relogge mal bitte

**Comment by Digawen** [comment]
Schon mehrmals probiert

**Comment by QA-Pregon** [comment]
Ok, bisher hat das bei mir geholfen, habs aber weiter gegeben
