### ISSUE TITLE
Tablets lassen sich nicht abräumen im Restaurant

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3825]
## **Charname**
Brian Mason
## **Discord-Name**
Kambadin
## **Auftrittszeitpunkt**
14.10.2024 ca. 18:30
## **Beobachtetes Verhalten**
Nach dem Essen konnte man den Tisch nicht abräumen. Auch nicht die Bedienung. (Wing Stop)

**Comment by QA-Pregon** [comment]
#3824
