### ISSUE TITLE
Schlagring nicht Ausrüstbar

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3828]
## **Charname**
Jamiro Ortiz
## **Discord-Name**
Oguzhan3457
## **Auftrittszeitpunkt**
14.10 Nach Update
## **Beobachtetes Verhalten**
Schlagring ist nicht mehr Ausrüstbar Fehlermeldung:  Falsches Item für diesen Slot!

**Comment by Erumeldor** [comment]
Das ist bewusst, coming soon :)
