### ISSUE TITLE
Rotation von Fahrzeugen nicht gespeichert.

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#383]
**Zeitpunkt (Datum / Uhrzeit)**
22.11.2020 / 13:27
**Beobachtetes Verhalten**
Fahrzeuge haben nicht die Korrekte position nach einem Restart.
**Erwartetes Verhalten**
Fahrzeuge sollten so gespawnt werden wie sie abgestellt worden sind.

**Schritte um den Fehler nachvollziehen zu können**
Auto Parken -> Restart abwarten -> Einloggen -> Komisch geparktes Fahrzeug ansehen

**Optional: Video / Bilder des Fehlers**
https://prnt.sc/vnsafv

**Comment by Kalumel** [comment]
Doppelpost. Nicht gesehen

**Comment by Kalumel** [comment]
Doch kein Doppelpost

**Comment by its4l3x** [comment]
Doch Doppelpost. altV Issue. Ist im RC Branch behoben worden, im release aber nicht.

**Comment by Kalumel** [comment]
Töp!

**Comment by its4l3x** [comment]
Duplicate => Close
