### ISSUE TITLE
Sheriffdepartment trotz geschlossener Tür offen

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3834]
## **Charname**
Jamverel Greren
## **Discord-Name**
Stiefel911
## **Auftrittszeitpunkt**
15.10.2024 00:15
## **Beobachtetes Verhalten**
Tür ist trotz Verschlusssymbol offen
## **Anhänge**
<br>[Link](https://pic.statev.de/image/HXnG0T)<br>

**Comment by QA-Pregon** [comment]
auch hier reicht einer
