### ISSUE TITLE
Unterschriftenfenster nicht mehr Alligned

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3837]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

15.10 9:45
**Beobachtetes Verhalten**

Beim Unterschriftenfenster schreibt man nicht mehr da wo die Maus ist
**Erwartetes Verhalten**

Da wo die Maus ist kommen die Striche
**Schritte um den Fehler nachvollziehen zu können**

Werkstatt gehen und unterschreiben
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

2560x1440
**Optional: Video / Bilder des Fehlers**

https://medal.tv/games/gta-v/clips/iSLD7aE35449pi0zE?invite=cr-MSxiVUYsMTk1NTEzMTMzLA

**Comment by QA-Pregon** [comment]
Bereits bekannt, hatte nur noch keiner Zeit zum fixxen, danke trotzdem fürs melden ^^

**Comment by QA-Pregon** [comment]
Next Update
