### ISSUE TITLE
Konversationen verlassen nicht möglich auf kopierter SIM-Karte

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#384]
**Character Name**

**Zeitpunkt (Datum / Uhrzeit)**
22.11.2020 / 13.40
**Beobachtetes Verhalten**
Wenn man eine Konversation verlassen will passiert nichts weiter als das die MessageBox "Konversation verlassen
" gezeigt wird. 
**Erwartetes Verhalten**
Konversation sollte geschlossen / verlassen werden. 
**Schritte um den Fehler nachvollziehen zu können**
SIM-Karte kopieren -> Nur die Kopie einlegen (am besten einer anderen Person geben) -> Versuchen eine Konversation zu schließen

**Comment by KingMarcel** [comment]
Nur der Simkarten-Besitzer (erstersteller) kann die Konversationen derzeit verlassen

**Comment by MarcelMuerto** [comment]
Moin,
dieses Verhalten ist mir, als Soll-Verhalten bekannt, bis auf das Feedback vom StateNet, das müsste man noch anpassen.

Aktuell würde dies erst einmal Abklären, wie da das Soll-Verhalten ist.

**Comment by Kalumel** [comment]
Könnte man evt ein SIM Kopie machen die "Admin" rechte hat? @MarcelMuerto
