### ISSUE TITLE
Edelsteine allgemein / Export für Edelsteine

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#385]
Irgendwie kann man im Export keine Aufträge mehr für Bergkristalle, Smaragde, Saphire und Musgravite finden.
Wurde das rausgenommen?

Zudem habe ich die Tage wie schon eh und je große Edelsteine angekauft, aber es kamen keine Bergkristalle usw. (die obrigen Sorten) sondern nur Diamanten und Rubine, könnt ihr da auch mal checken?

Kleine Edelsteine kann man laut den anderen Spielern auch nicht mehr finden, bitte hier auch mal Checken.

**Comment by DonVitoDiangelo** [comment]
Alles soweit gewollt. Export Rework kommt später, wenn wir sehen wie sich der Markt so entwickelt hat.  Dann werden diese auch wieder eine Berücksichtigung finden.

**Comment by Statev-Bonsai** [comment]
Vito, ich habe hunderttausende dollar durch diese steine im lager liegen und nun bekomm ich sie nicht exportiert? das geld muss im  umlauf bleiben...
