### ISSUE TITLE
Restaurant Essen ohne Service möglich

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3850]
## **Charname**
Maxwell Scott
## **Discord-Name**
jonesxyz
## **Auftrittszeitpunkt**
15.10.2024 - 21:17
## **Beobachtetes Verhalten**
War essen am County Container, Ronny war im Service aktiv und ich konnte mich hinsetzen wollte die Klingel drücken aber konnte direkt bestellen und hab auch dann direkt Essen könnnen.

**Comment by jonesXYZ** [comment]
2. mal probiert, war wieder normal.

**Comment by QA-Pregon** [comment]
Check, falls es in unmittelbarer Zeit nochmal passiert bitte hier melden, ansonsten würde ich es nächste Woche zu machen

**Comment by jonesXYZ** [comment]
Wir testen es noch nen bisschen @Pregon und ich meld mich zur not hier im Ticket nochmal.

**Comment by rodistic** [comment]
next update fixed
