### ISSUE TITLE
Animationsmenü Fehler

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3851]
## **Charname**
Antonio_Pigeon
## **Discord-Name**
Antonio Pigeon
## **Auftrittszeitpunkt**
15.10.2024 - 21:20
## **Beobachtetes Verhalten**
Wenn man Partneranimationen öffnen will, ist die Liste oben leer und erscheint buggy unten
## **Anhänge**
<br>[Link](https://gyazo.com/6172a23f6ebd5e21a39983ebdeada185)<br>

**Comment by QA-Pregon** [comment]
#3831
