### ISSUE TITLE
[F] White Cropped Top

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3856]
## **Charname**
Violet Lorenzi
## **Discord-Name**
Violet
## **Auftrittszeitpunkt**
Dauerhaft ab 22:00
## **Beobachtetes Verhalten**
Keiner der Körperschnitte passt bei diesem Oberteil, trotz Magic Top

**Comment by ySimbaa** [comment]
Wird demnächst gefixt, dauert aber bis nach Halloween :)
