### ISSUE TITLE
Random Ui Crash

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3862]
## **Charname**
Mason Blackwater
## **Discord-Name**
Samorton
## **Auftrittszeitpunkt**
16.10.2024 / 00:38
## **Beobachtetes Verhalten**
Ich stand in der Wohnung von der Jessica Anderson während einer Maßnahme, es waren mehrere Cops im Apartment. Wollte ans Fenster und Animation (Hände hintern Rücken) anwählen, danach kam die Meldung.

**Comment by jonesXYZ** [comment]
![Grand_Theft_Auto_V_Screenshot_2024 10 16_-_00 38 27 94](https://github.com/user-attachments/assets/18557db3-fa01-4212-8de9-262f8535fc06)
