### ISSUE TITLE
Unsichtbarer Kellereingang am Pillbox MD

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3863]
## **Charname**
Andre Bailey
## **Discord-Name**
DerHessenTyp
## **Auftrittszeitpunkt**
16.10.2024 um 11:20 Uhr
## **Beobachtetes Verhalten**
Die angezeigten Türen am Pillbox MD unterhalb (Gegenüber des Bus Bahnhofes) sind eine unsichtbare Wand, und man fällt direkt unterhalb von dem Busbahnhof.
Entweder man kommt ins MD oder man sollte gegen eine standhafte Wand laufen. 
Ich denke das Problem werden einige schon gehabt haben die gerade dort unterwegs sind, da es bei meiner Freundin kurz nacheinander passiert ist.
## **Anhänge**
<br>![Bild](https://pic.statev.de/i/HXB5Fk.jpg)<br> <br>![Bild](https://pic.statev.de/i/HXBDEw.jpg)<br>

**Comment by TheOutburst** [comment]
Kam durch nen vanilla Mapping was wir für HW genutzt haben, durch Eventende solved
