### ISSUE TITLE
Garagenpunkt versetzen

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3864]
## **Charname**
Patrick Fischer
## **Discord-Name**
Fishbone
## **Auftrittszeitpunkt**
16.10.2024 15:45 Uhr
## **Beobachtetes Verhalten**
Hallo, wäre es bitte möglich den Garagenpunkt bei dem Haus vor das Vordach zu versetzen? 
Hash house_MirrorPark_23
## **Anhänge**
<br>![Bild](https://pic.statev.de/i/HXEPoB.png)<br>

**Comment by SatyriaDine** [comment]
Hello hello, sehe da keinen akuten Handlungsbedarf den Marker zu verlegen. :)
