### ISSUE TITLE
Standort via. Handy funktioniert nicht

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3868]
## **Charname**
Tim Sea
## **Discord-Name**
✎𝕋𝕚𝕞𝕚𝕥𝕣𝕚𝕖
## **Auftrittszeitpunkt**
16.10.2024 ~ 20:30
## **Beobachtetes Verhalten**
Ich habe einen Standort erhalten konnte Ihn jedoch nicht makieren (durch Linksklick auf die Meldung in "Notefy".

**Comment by SHaagmann** [comment]
Gleche Thematik bei Crime Jobs

**Comment by Hutstaender** [comment]
fixed
