### ISSUE TITLE
Telefonbug

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3869]
## **Charname**
Antonio_Pigeon
## **Discord-Name**
Antonio Pigeon
## **Auftrittszeitpunkt**
16.10.2024 - 20:30
## **Beobachtetes Verhalten**
Telefon unter 1% Akku, Anruf gestartet, Akku leer, Telefon kaputt + Relog erforderlich!
## **Anhänge**
<br>[Link](https://www.youtube.com/watch?v=lhZUAyOL1vo)<br>

**Comment by QA-Pregon** [comment]
Wenn ich mich nicht täusche müsste das durch einen anderen fix auch behoben sein ^^
