### ISSUE TITLE
Anhänger schwankt hin und her

### ISSUE THREAD

**Issue by powerswissi** [mexyn/statev_v2_issues#387]
**Character Name**

Roger_Thickle

**Zeitpunkt (Datum / Uhrzeit)**

22.11.2020 14.44
**Beobachtetes Verhalten**

siehe Video

https://youtu.be/VGLsra-g-f0

**Erwartetes Verhalten**

Eigentlich sollte der Anhänger stehen... 

**Schritte um den Fehler nachvollziehen zu können**

Bis jetzt nicht nachvollziehbar.. ist random

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/VGLsra-g-f0

**Comment by DonVitoDiangelo** [comment]
Hat sich das Problem mit dem letzten alt:V Update behoben?

**Comment by powerswissi** [comment]
Das scheint behoben zu sein <3
