### ISSUE TITLE
"Macho Shirts" verbuggt

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3871]
## **Charname**
Mike Lakoschka
## **Discord-Name**
michael
## **Auftrittszeitpunkt**
17.10.2024
## **Beobachtetes Verhalten**
Wenn man das Oberteil (Kurzärmelig und tiefer V-artiger Ausschnitt) anzieht, schimmert immer irgendwo haut durch oder es Fehlt Oberkörper. Von allen möglichen Konfigurationen (Kurz-/ Langarm 1-5) gibt es keine, die mit dem Kleidungsstück funktioniert.

**Comment by ySimbaa** [comment]
Du willst zu den Macho Shirts noch ein Undershirt anziehen verstehe ich das richtig?
