### ISSUE TITLE
Oberteil (Weiblich) Baby Crop Top Buggy

### ISSUE THREAD

**Issue by xMissRi** [mexyn/statev_v2_issues#3873]
Keine der verfügbaren Optionen funktionieren mit dem Oberteil, entweder es glitched in den Charakter oder teile des Charakters sind unsichtbar.
Habe es mit und ohne Magic Corsage versucht und auch alle Optionen.

Bild 1: https://imgur.com/mOvGkim
Bild 2: https://imgur.com/nBrze0i

**Comment by ySimbaa** [comment]
Top wird nach Halloween ausgetauscht gegen eins was besser passt.
