### ISSUE TITLE
Handschuhe nicht mehr ablegbar

### ISSUE THREAD

**Issue by ingo-lorenz** [mexyn/statev_v2_issues#3874]
Peter_Fichtner

Auftrittszeitpunkt: 17.10.2024 22:50

Ich kann die blauen Handschuhe nicht mehr ablegen. Sobald ich ein Oberteil anziehe, werden die Handschuhe angezeigt. Eine Änderung auf "Kurzarm" wird nicht gespeichert. Nach erneuten Öffnen des Menus, steht es wieder auf "Einmalhandschuhe - Blau"

![image](https://github.com/user-attachments/assets/a9570a2b-decf-4411-820c-42e76105b503)
![image](https://github.com/user-attachments/assets/c97e2c31-3d10-4261-82d4-77d6828fe3e0)
![image](https://github.com/user-attachments/assets/fbee2e3e-45aa-4784-8575-38b0e147c3b5)

**Comment by QA-Pregon** [comment]
Hast du auch Rechts im Klamottenmenü dann neu die Kurzarm Variante ausgewählt oder nur wieder Links auf Kurzarm gestellt

**Comment by QA-Pregon** [comment]
Klappt alles normal, denke mal meine Frage war der Fehler
