### ISSUE TITLE
Essen´s Bug (Ristorante All Oso)

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3875]
## **Charname**
Alex_Reynolds
## **Discord-Name**
CHΛⱤLYJUiCΞ
## **Auftrittszeitpunkt**
18.10 - 17:12
## **Beobachtetes Verhalten**
Ich wurde bedient sah aber keinen prop und Balken und kann nicht mehr aufstehen. (Du kannst derzeit nicht aufstehen) passiert am 17.10 und jetzt 18.10 17:12 Uhr das selbe. Gewartet hab ich 11 Minuten aber Essensanzeige/Trinken und unverändert. Aufstehen kann ich nur wenn ich abreche.

**Comment by QA-Pregon** [comment]
Ist das danach nochmal passiert?
Mir ist nämlich auch aufgefallen, dass mal ab und zu die Anzeige fehlt, jedoch ist der Fortschritt dabei immer korrekt abgelaufen

**Comment by QA-Pregon** [comment]
Ersma zu, falls es nochmal auffällt, einfach nochmal 5 mins warten und dann gucken ob noch was passiert
