### ISSUE TITLE
Animationen nicht auswählbar

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3877]
## **Charname**
Aaron_Morgen
## **Discord-Name**
Beartox
## **Auftrittszeitpunkt**
19.12.2024 - 19:41
## **Beobachtetes Verhalten**
Ich habe das problem wenn ich auf eine Kategorie im Animationen auswähle bekomme ich keine angezeigt dann geh ich zurück oder auch wenn ich es neu öffne sieht man es ganz unten ganz klein
## **Anhänge**
<br>![Bild](https://i.gyazo.com/18cd8ad945de0f5b415e6007fc0de5ed.jpg)<br>

**Comment by QA-Pregon** [comment]
#3831
