### ISSUE TITLE
Animationen sind alle leer

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3878]
## **Charname**
Edward Cline
## **Discord-Name**
Tyrese Omelly
## **Auftrittszeitpunkt**
18.10.2024 21:30
## **Beobachtetes Verhalten**
Guten Abend, ich habe gar keine Animationen mehr. Die Listen im Menü sind alle leer. Ich habe auch schon den Cache-Ordner gelöscht. Im Anhang befindet sich einmal das F8-Menü als Screen
## **Anhänge**
<br>![Bild](https://i.gyazo.com/c4f826a93a0f3cfb057cda6d3efe7a15.png)<br> <br>![Bild](https://i.gyazo.com/b483e8ac3a2b2178aa05c48f711ccc92.png)<br>

**Comment by QA-Pregon** [comment]
#3831

**Comment by QA-Pregon** [comment]
Animationen müssen aktuell nach exaktem namen gesucht werden
