### ISSUE TITLE
Bughafter Abladepunkt

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3879]
## **Charname**
Rose Zarske
## **Discord-Name**
♡Lunaria♬
## **Auftrittszeitpunkt**
Jedesmal beim entladen und anschließendem betreten der Firma wenn Fahrzeug noch auf dem Punkt steht
## **Beobachtetes Verhalten**
Guten morgen liebes Team, 

Ich wollte einmal fragen ob man den abladepunkt versetzen kann. 
Jedesmal wenn man ein Fahrzeug auf dem Punkt lässt wenn man die Firma betritt steckt das Fahrzeug im Boden, durch diese metallplatten vor der firma.  Dadurch entstehen unnötige Schäden am Fahrzeug. 

Wir haben überlegt, am liebsten wäre es uns wenn die Platten entfernt werden würden. Wenn dies nicht möglich ist, würden wir den abladepunkt an die Straße versetzen lassen wollen. Denke da wäre es am einfachsten und sinnvollsten. 

Ich danke euch im voraus schonmal
## **Anhänge**
<br>[Link](https://cdn.discordapp.com/attachments/884512681430773772/1297060113483304970/image.png?ex=67148cdd&is=67133b5d&hm=73ba3242eacde6bc3e56809cf7bdee1614aa8aad8212cd528b334a065d7accb2&)<br> , <br>[Link](https://cdn.discordapp.com/attachments/884512681430773772/1297060229271392296/image.png?ex=67148cf8&is=67133b78&hm=0eace4080a34babe5baf6f483bff60a9a3e5ace0cf82be8cc54abcd5ff3b36c5&)<br>

**Comment by QA-Pregon** [comment]
Hast noch den Firmenhash für mich? Steht im V-Net

**Comment by Lunaria1007** [comment]
Klar hier pf_cypressflats_49
