### ISSUE TITLE
Shortkeys funktionieren auch, obwohl StateNet, StateCom etc. offen sind

### ISSUE THREAD

**Issue by StevenMcGarrett** [mexyn/statev_v2_issues#388]
Zac Anderson

**Genaue Uhrzeit kann ich keine nennen**

**Die Shortkeys funktionieren, obwohl man das StateCom oder StateNet offen hat. Hat zur Folge, dass
ich bei einer Verkehrskontrolle bspw. in einer Tour irgendwie Hupe, Sirene an- und ausschalte etc.**

**StateCom oder StateNet aufmachen -> Etwas auf der Tastatur eintippen mit dem Buchstaben 'E', 'R' etc.**

**Comment by Mr-Chris-VRTY** [comment]
https://github.com/mexyn/statev_v2_issues/issues/303 :)

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/463

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/639

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/725

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/816

**Comment by Chrinis007** [comment]
Genau das selbe wenn du im StateNET was eingibst und immer Schneebälle aufnimmst

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1234

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/206

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/303

**Comment by its4l3x** [comment]
fixed next update
