### ISSUE TITLE
Man kann JetSki nicht Tanken

### ISSUE THREAD

**Issue by vdnoez** [mexyn/statev_v2_issues#3880]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Leon Steiger

**Auftrittszeitpunkt (Datum / Uhrzeit)**
18.10.2024 gegen 19-20 Uhr

**Beobachtetes Verhalten**
Ich versuche den Jetski zu tanken, und ich kriege nur 3L rein es betankt mein Jetski nicht.

**Erwartetes Verhalten**
Es sollte soviel getankt werden bis es nicht mehr geht bzw den Tank füllen.

**Schritte um den Fehler nachvollziehen zu können**
Siehe Video

**Optional: Video / Bilder des Fehlers**
(https://youtu.be/Y3JtursBSYs)

**Comment by QA-Pregon** [comment]
Next Update
