### ISSUE TITLE
Fake Nasenring Buggy

### ISSUE THREAD

**Issue by xMissRi** [mexyn/statev_v2_issues#3881]
Bug 1:

Man kann den Fake Nasenring nicht in den Kleiderschrank räumen, man bekommt die Meldung "Das geht hier nicht rein".

Link zum Bild: https://imgur.com/LpFBioP

----------------------------------------------------------------------------------------------------------------------------------------
Bug 2 (?):

Sobald man den Nasenring anzieht verschwinden die Wimpern.

Bild ohne Nasenring:  https://imgur.com/u2UGSqM
Bild mit Nasenring: https://imgur.com/EoCmTeu

**Comment by stepz2k9** [comment]
Hängt vermutlich beides damit zusammen, dass es auf dem Armor-Slot liegt -> Armor ist vermutlich nicht als Kleidungsstück definiert, daher Fehlermeldung beim Schrank.
Die Wimpern halt auch. Deshalb verschwinden die beim Anlegen des Rings.

Ich denke nicht, dass man da viel machen kann.

**Comment by QA-Pregon** [comment]
Bug 1 laut Simba: soll da nicht rein, weil man Piercings ja eher wenig zu Klamotten legt
Bug 2 wie @CaleighRhodes schreibt
