### ISSUE TITLE
Ausladepunkt bei Firma zu nah an Wand

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3883]
## **Charname**
Coco_Carter
## **Discord-Name**
Cas Coco
## **Auftrittszeitpunkt**
Jedes Mal beim Ausladen
## **Beobachtetes Verhalten**
Jedes Mal, wenn jemand eine Zugmaschine mit Trailer an meiner Firma ausladen möchte, bleibt man an der Wand hängen bis man richtig steht. Es wäre super, wenn man den Ausladepunkt verschieben könnte, auf die Straße oder so. Bei der Firma handelt es sich um Thorns Laboratory #pf_cypressflats_54
Bilder von dem Punkt hänge ich an. Ich habe direkt nebenan auch eine Firma (Thorns Weaving #pf_cypressflats_67), vielleicht ist es ja möglich, die Ausladepunkte zusammenzulegen. 
Bei den Bildern hab ich die aktuellen und einen gewünschten Ausladepunkt markiert.
Viele Grüße
## **Anhänge**
<br>[Link](https://pic.statev.de/image/aktuellerstandort-frontansicht.HXCRLB)<br> <br>[Link](https://pic.statev.de/image/aktuellerstandort-seitenansicht.HXCsyR)<br> <br>[Link](https://pic.statev.de/image/aktellestandorte-und-gewunschterstandort.HXCv2T)<br>

**Comment by SatyriaDine** [comment]
Hey hey, also ich kann schon mal ganz klar sagen, dass wir die Abladepunkte nicht zusammen legen werden, da sonst falls du eine der Firmen mal verkaufen solltest, das Abladepunkte trennen losgeht. :D Ich schau es mir aber beim Labor an, damit der Punkt nicht mehr so schwierig zu erreichen ist. :)
