### ISSUE TITLE
Hotel // Apartment nicht kündbar

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3884]
## **Charname**
Jaro Malone
## **Discord-Name**
Jaro
## **Auftrittszeitpunkt**
18.10.2024 // ca. 19 Uhr
## **Beobachtetes Verhalten**
Habe 2 verschiedene Apartments gemietet. Konnte aber keine davon  kündigen
## **Anhänge**
<br>[Link](https://ibb.co/6wc209V)<br> Hotelmenü

**Comment by Pregon** [comment]
Ist das ein Appartmentkomplex, bei dem es auch grüne Marker gibt?
