### ISSUE TITLE
Abladungpunkt-Verlegung

### ISSUE THREAD

**Issue by CalebPapaCrane** [mexyn/statev_v2_issues#3886]
Grüße, ich wollte gerne mal erfragen, ob man ggf. für 2 Firmen den Ablade Punkt aufeinander legen könnte.
![Screenshot_1](https://github.com/user-attachments/assets/62201a01-64f5-4bc8-8e38-d741411eea4f)
Der Punkt ist mit 'nem Phantom absolut schlecht zu be-parken, da wir unseren Friseur direkt daneben haben, der Phantom geht bis auf die Parkfläche des Friseurs mit Anhänger, etwas unpraktisch tatsächlich. Wir haben in dem besagten Gebäude unser Lager, in dem rechts daneben direkt unsere Weberei.
![Screenshot_2](https://github.com/user-attachments/assets/3e96f5ee-a8c4-4503-aee0-bddcd27e81b3)
Wäre natürlich stark, wenn man für beides einen Ablade Punkt hat, wobei der vom Lager (Bild 2) evtl. etwas mehr auf die Straße muss, da die Achse ggf. kippt wenn ich aus der Bude rauskomme, davon abgesehen dass ich etwa 3 Manöver brauche, bis ich überhaupt mal drauf bin (Straßenschilder).

Können auch wenn unmöglich, getrennt von einander bleiben, sollten nur ggf. überdacht werden, beste Grüße ihr Schnuggies :D

**Comment by CalebPapaCrane** [comment]
Firmen Hash Weberei: pf_Alta__7
Firmen Hash Lager: pf_Alta__8

**Comment by SatyriaDine** [comment]
Hello hello, ich hab das ganze gerade mal ausprobiert. Der Phantom kommt lediglich auf die Sperrfläche neben den Parkplätzen vom Friseur. Daher sehe ich da jetzt keinen Grund den Punkt zu verlegen :)
