### ISSUE TITLE
Häuser verlassen...

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3888]
Früher konnte man Häuser selbstständig verlassen (Schlüssel zurückgeben)..
Mittlerweile funktioniert das nicht mehr und führt zu eigenartigen RP...

**Comment by QA-Pregon** [comment]
Bevor mich hier iwer anmeckert, ins Bord mach ichs morgen, kein bock das am handy zu machen :)

**Comment by QA-Pregon** [comment]
Sollte fixxed sein laut Changelog 3.4
