### ISSUE TITLE
Fehler im Produktionscomputer

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3889]
## **Charname**
Bosco Albert
## **Discord-Name**
Boing2000/Björn
## **Auftrittszeitpunkt**
20.10.2024 13:30
## **Beobachtetes Verhalten**
In der Fahrzeugfertigung sollte man am Computer die Teile mit Preisen hinterlegen können. Es werden aber keine Rohstoffe/Fahrzeugteile angezeigt, sondern Lebensmittel
## **Anhänge**
<br>![Bild](https://pic.statev.de/i/HXSfxz.jpg)<br>

**Comment by Flachmeyer** [comment]
Change vom 14.10.24
[CHANGED] Produktionscomputer - Es können alle verfügbaren Items im Einkauf gesetzt werden + Styling-Changes 

Es werden in jeder Firma alle möglichen Items für eine Kalkulation angezeigt. 
Du musst das Item was du braucht ganz Oben in der Suchleiste suchen und dann auswählen
