### ISSUE TITLE
Keine Lackierung am i8 möglich (Werkstatt Lackieren)

### ISSUE THREAD

**Issue by LautaroTesto** [mexyn/statev_v2_issues#389]
**Lautaro Testo**

Lautaro_Testo

**Zeitpunkt (Datum / Uhrzeit)**
15:00Uhr

**Beobachtetes Verhalten**
Reaction Corp Werkstatt Lackierkabine: Lackiersystem führt beim Auto BMW i8 keine Lackierung aus und es kann bis zum nächsten Restart keine Lackierung mehr begonnen werden

**Erwartetes Verhalten**
Farbe auswählen > Rechnung austellen > Rechnung abschließen > Lackiervorgang beginnen > Lackiervorgang beenden

**Schritte um den Fehler nachvollziehen zu können**
 Farbe wird ausgewählt > Rechnung wird gestellt > Rechnung wird angenommen + Überweisung ist erfolgt > Fortschrittsbalken wird NICHT angezeigt > sobald man wieder zum Trigger geht kommt folgende Meldung: Ist bereits in Verwendung!

Zusatz: Dieser Vorgang wurde am 21.11.2020 gegen 21Uhr schonmal versucht und es kam zum Systemabsturz.

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/364
