### ISSUE TITLE
Aufzug für einen Balkon

### ISSUE THREAD

**Issue by LuciaLorenzi** [mexyn/statev_v2_issues#3890]
**Character Name**
Lucia_Lorenzi

**Auftrittszeitpunkt (Datum / Uhrzeit)**
20.10.2024, 14:40 Uhr

**Beobachtetes Verhalten**
Man hat hier bei dem Haus mehrere Terrassen die man nicht betreten kann.

**Erwartetes Verhalten**
Vielleicht kann man durch die Seiten Türe einen Aufzug / Treppen anbringen, dass man von der Seitentüre aus auf die oberste Terrasse kommt.

**Optional: Video / Bilder des Fehlers**

![Seitentüre](https://github.com/user-attachments/assets/cfffdee8-1d60-4aa9-b030-ff56bfcd637c)
![Rückseite](https://github.com/user-attachments/assets/f7b67ac6-94da-4b0d-9910-d13cfd257fa6)

Ich bedanke mich vorab für die Zeit  der Überprüfung und gff. dann der Umsetzung.

Grüße 
Mona aka Lucia_Lorenzi

**Comment by TheOutburst** [comment]
Moin
Solche Portmarker legen wir nichtmehr an, sieher https://discord.com/channels/365251792679862292/1208107686961483876/1249664276030033931
