### ISSUE TITLE
Tank Bug an der Bootstankstelle Westside

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3891]
## **Charname**
Otis Gutierrez
## **Discord-Name**
𒆜ⁱᵃᵐ Brian 𒆜
## **Auftrittszeitpunkt**
20.10.24 ca. 15:40
## **Beobachtetes Verhalten**
Juana Gutierrez hat 3 mal das Boot für einmal 70$ und einmal 30$ und einmal 74$ Getankt und hatte vor dem Tanken und nach dem Tanken die gleiche Mänge von 22,3 L drinn. im Anhang ein Video dazu.
## **Anhänge**
<br>[Link](https://medal.tv/de/games/gta-v/clips/iUVvlHh7iru4JlSna?invite=cr-MSxlUWUsMjIyNDI2NzI3LA)<br>

**Comment by QA-Pregon** [comment]
Next update

**Comment by QA-Pregon** [comment]
#3880
