### ISSUE TITLE
Apartment Umbau mehrfach Abbuchung

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3892]
## **Charname**
Cullam Gallagher
## **Discord-Name**
TheMajic0ne
## **Auftrittszeitpunkt**
20.10.2024 20:00:26 Uhr
## **Beobachtetes Verhalten**
Ich wollte als Besitzer des Apartments einen Umbau vollziehen. Beim auswählen "renovieren" bekam ich den Hinweis, dass sich noch etwas in dem Apartment befindet (Möbel) . Ich hatte aber zwei Mal auf die Taste gedrückt, da ich den Hinweis zuerst überlesen hatte...

Obwohl der Umbau nicht vollzogen wurde, wurden mir insgesamt 6000$ vom Konto abgezogen. 2000$ sollten es eigentlich sein.

Für das zurücküberweisen erstelle ich eine separate Service-Request.
## **Anhänge**
<br>[Link](https://pic.statev.de/image/image.HXaWyP)<br>

**Comment by Erumeldor** [comment]
Sollte bereits fixed sein - Geld hast du auch bereits erhalten.
