### ISSUE TITLE
Garage für ein Haus

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3893]
## **Charname**
Mike Jenkins
## **Discord-Name**
GrinseHund
## **Auftrittszeitpunkt**
-
## **Beobachtetes Verhalten**
-
## **Anhänge**
Hallo zusammen Ich wollte mal nachfragen ob ich auch ne Garage an meinen Haus bekommen kann. Hab von welchen gehört die haben auch eine bekommen. Mein Haus ist in Sandy Shores links vom Tattoo Laden siehe Screenshot. Ich hab auch gesehen das so ein Trailer Wohnwagen sogar eine hat sieht man auf dem Screen <br>[Link](https://pic.statev.de/i/HXaNoI.png)<br> <br>[Link](https://pic.statev.de/i/HXabU7.png)<br> <br>[Link](https://pic.statev.de/i/HXaGyc.png)<br>

**Comment by SatyriaDine** [comment]
Hello hello, leider muss ich hier ablehnen. An deinem Haus fehlt eine eindeutige Auffahrt die eine Garage rechtfertigen würde. :)
