### ISSUE TITLE
Crime mission punkt abarbeiten und dabei weglaufen

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3894]
## **Charname**
Shakeem_Cole
## **Discord-Name**
McPusher
## **Auftrittszeitpunkt**
21.10.2024 17:03
## **Beobachtetes Verhalten**
IIch habe beim punnkt abbauen tab gedrückt dadurch meine waffe gezogen undd konnte dan mit esc auf die map clicken dafür sorgen das die animation vom punkt weg ist und  ich wieder laufen kann aber  dabei der punkt noch abgearbeitet wird

**Comment by QA-Pregon** [comment]
#3838
