### ISSUE TITLE
Bug bei Event

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3895]
## **Charname**
Rakeem Kingston
## **Discord-Name**
Rakeem ⁷⁷⁷
## **Auftrittszeitpunkt**
22.10.2024/ Ca 00:00 uhr
## **Beobachtetes Verhalten**
Ich habe Beim Fib Gebäude alle akten aufgehoben aber bei einem Habe ich zu schnell ESC gedrückt und dann habe ich eine Akte nicht bekommen
## **Anhänge**
Akten die habe: Human labs, Oil rig, Industrial Shore, Power Station, Vinewood

**Comment by QA-Pregon** [comment]
Relog und nochmal machen
