### ISSUE TITLE
Wild platziertes Säuchenzelt

### ISSUE THREAD

**Issue by statevde** [mexyn/statev_v2_issues#3896]
## **Charname**
Manis Bauer
## **Discord-Name**
Mani
## **Auftrittszeitpunkt**
22.10.2024 / 5.54 Uhr
## **Beobachtetes Verhalten**
Beim Durchstreifen der Wälder bin ich auf einen in der Luft hängenden Außenposten gestoßen, welcher wohl nicht dort hin soll. Westlich der Senora Road, Südöstlich vom Redwood Lights Track. direkt an der Geländestrecke.

**Comment by QA-Pregon** [comment]
Keine ahnung ob schon ein fix kam aber das war aufm Schirm, danke trotzdem fürs melden

**Comment by Erumeldor** [comment]
Ist weg
