### ISSUE TITLE
Doc Podder händigt das falsche Tablet aus

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#3897]
**Character Name**
Charly Parker

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.10.2024 11:04

**Beobachtetes Verhalten**
Doc Podder händigt das falsche Tablet aus. Man kriegt aus der verlassenen Hütte Quantum Pad v10.0.4 um ihn zu finden, wenn man synchronisiert erhält man dieses erneut und kann nicht weitermachen.

**Erwartetes Verhalten**
Dass man das nächste Tablet erhält

**Comment by QA-Pregon** [comment]
Alles richtig
