### ISSUE TITLE
Atm und Telefonieren

### ISSUE THREAD

**Issue by MissCrZy** [mexyn/statev_v2_issues#39]
**Zeitpunkt (Datum / Uhrzeit)**
25.08.2020 21:31 Uhr

**Beobachtetes Verhalten**
Während man telefoniert und an den ATM geht, kann man nachdem man Geld abgehoben oder eingezahlt hat sich nicht mehr bewegen. Man kann sich erst wieder bewegen wenn man aufgelegt hat.

**Erwartetes Verhalten**
Man sollte sich danach wieder bewegen können.

**Schritte um den Fehler nachvollziehen zu können**
1. aktives Telefonat haben
2. an den ATM und mit diesem interagieren
3. Geld auszahlen lassen oder einzahlen

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/64669200bbbfa6f2e1c6e3d04aeb6096

**Comment by its4l3x** [comment]
Haben die Animation nach Absprache rausgenommen.

Daher sollte das Problem auch gelöst sein.
