### ISSUE TITLE
Verschwundene Eisenbarren (Ersatz)

### ISSUE THREAD

**Issue by xExplicitx** [mexyn/statev_v2_issues#390]
**Diese Thema wurde geschlossen, ich hätte die 363 Eisenbarren gerne dennoch wieder da dort doch schon ein paar Stunden Arbeit drin stecken auch wenn der Fehler nicht reproduzierbar ist.** 

Charaktername:
Jay Parker

Jay Parker / Kalle Grabowski

Zeitpunkt (Datum / Uhrzeit)
22.11.2020 um 12:45 Uhr

Beobachtetes Verhalten
Fahrzeug (Kalle Grabowski) fuhr auf den Entladepunkt der Firma "House of Flames" (pfAlexMirMurLaEastRew_1).
Beim versuchten Verkauf an der Firma (363 Eisenbarren à 25$) verschwanden die Eisenbarren aus dem Lager und es wurde kein Geld gebucht, weder bei der Firma noch beim Privatkonto von Kalle Grabowski. Nach diesem Fehler konnte Kalle Grabowski den Motor seines Fahrzeugs nicht mehr anlassen.

Erwartetes Verhalten
Beim Verkauf ab Firma hätten die 363 Eisenbarren in das Fahrzeug geladen werden müssen und das Geld vom Privatkonto (Kalle Grabowski) auf das Firmenkonto (House of Flames) gebucht werden müssen. Das Fahrzeug des Käufers hätte weiterhin normal funktionieren müssen.

Schritte um den Fehler nachvollziehen zu können
Fahrzeug fährt auf Entladepunkt->Eingabe Menge des Artikels der verkauft werden soll->363 Eisenbarren nicht mehr im Lager /Fahrzeug des Käufers defekt

**Comment by its4l3x** [comment]
Bitte im Support melden.
