### ISSUE TITLE
Trashmaster hat keinen Platz laut wiki

### ISSUE THREAD

**Issue by Marco128222** [mexyn/statev_v2_issues#391]
Arturo Gonzalez

**Zeitpunkt (Datum / Uhrzeit)**
 22.11.2020 15:30 

**Beobachtetes Verhalten**
 Im StateNet werden 2 Trashmasters deklariert (einer davon der custom). Dort wird beschrieben, dass es keinen Kofferraum gibt. Also keinen Platz um den Müll zu transportieren, welcher für das MullRP wesentlich wichtig ist. Außerdem sollte der Custom laut dem GTA Wesen hinten noch 2 Stehpunkte haben (sprich 4 Sitzer) 

**Erwartetes Verhalten**
 Kofferraum Volumen anpassen und Stehplätze hinten Freigeben wenn nicht schon vorhanden

**Schritte um den Fehler nachvollziehen zu können**
 Für das Recycling-Roleplay ist es für uns Spieler wichtig, den Müll aus den öffentlichen Mülltonnen zu entsorgen. Nichts bietet sich dafür mehr an als ein Müllwagen. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
[wiki](https://user-images.githubusercontent.com/38442368/99906612-60970480-2cd8-11eb-8f20-2f2c42beed98.PNG)

**Comment by DonVitoDiangelo** [comment]
wiki wird angepasst.
