### ISSUE TITLE
Iced Matcha Latte

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3924]
Irgendwie stacken die nicht.. ^^
![Screenshot_15](https://github.com/user-attachments/assets/de7ad9ba-51e2-4042-8b36-4a25472325b6)

**Comment by QA-Pregon** [comment]
Liegt sowohl an verbrauchten Magazinen, als auch an verschiedenen Hashes.
Ist also einfach unlucky ^^
