### ISSUE TITLE
Buggy Mlo oä (keine Kollision in Tür)

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#393]
**Character Name** Erwin Dulach

**Zeitpunkt (Datum / Uhrzeit)** 22.11 15:30

**Beobachtetes Verhalten** Man kann durch die Tür in ein buggy MLO oä gehen. Alle anderen Türen des Gebäudes sind iO

**Erwartetes Verhalten** Eingebautes MLO oder Türe hat Kolliison.

**Schritte um den Fehler nachvollziehen zu können** Bei Firma BeYou Liquids II (Nariana Drive 20) versuchen durch den Haupteingang zu gehen.

**Optional: Video / Bilder des Fehlers**

https://x-up.ws/i/66d0e8ba8c00.jpg

**Comment by DonVitoDiangelo** [comment]
GTA BUG
