### ISSUE TITLE
Hose ist ein falsches Model 

### ISSUE THREAD

**Issue by KoenigJustin** [mexyn/statev_v2_issues#3932]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Elijah_Ray

04.11.2024

Die Hose ist ein anderes Model als vorher. 

Richtige Hose 

https://pic.statev.de/images/28102f31def602854.png

https://pic.statev.de/images/194c6b43fcfd970a.png

**Comment by QA-Pregon** [comment]
Next update
