### ISSUE TITLE
Klamotten können nicht in den Kleiderschrank 

### ISSUE THREAD

**Issue by KoenigJustin** [mexyn/statev_v2_issues#3933]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Elijah_Ray

04.11.2024

Die Klamotten können nicht in den Kleiderschrank gelegt werden. 

https://pic.statev.de/images/8ad491059ea6f10e68.png

**Comment by QA-Pregon** [comment]
Next update
