### ISSUE TITLE
Sidecut Frisur kann keine Mützen tragen

### ISSUE THREAD

**Issue by DeRo1337** [mexyn/statev_v2_issues#394]
**Character Name**
Derk_Ronaldo

**Zeitpunkt (Datum / Uhrzeit)**
22.11.2020 15:54Uhr
**Beobachtetes Verhalten**
Haare drücken durch die Mütze

**Erwartetes Verhalten**
Mütze sollte normal tragbar sein

**Schritte um den Fehler nachvollziehen zu können**
Mütze aufziehen Haare drücken druch

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/8cb3dbde9310a206efb4adf4349844c9
https://gyazo.com/59aa322155bd167f63c32ceca2e758a4

**Comment by Enemyaa** [comment]
@DeRo1337 Während dem Vorgang oder bei jedem Switch von Kleideritems passiert das. Theoretisch müsste DIESE Cap aber wenn du sie anlegst passen. Hast du es nochmal nach dem Friseur versucht? Wenn es immernoch nicht geht, schreib mir bitte kurz den Name der Cap.
