### ISSUE TITLE
Weste macht die Beine weg 

### ISSUE THREAD

**Issue by KoenigJustin** [mexyn/statev_v2_issues#3941]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Elijah_Ray

07.11.2024

Sobald man die Weste anzieht hat man keine Beine mehr. 

Hätte gerne wieder Beine.

https://pic.statev.de/images/ed59aee7d6bad613.png

https://pic.statev.de/images/78ce2e76a9a8b10de.png

**Comment by ySimbaa** [comment]
Welche Hose hast du dabei an?

**Comment by ySimbaa** [comment]
solved
