### ISSUE TITLE
Fahrzeug nach einmaliger Benutzung zu stark beschädigt

### ISSUE THREAD

**Issue by AmeliaWinterssan** [mexyn/statev_v2_issues#3945]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Amelia Winters und Dieter Klausen**

**3.11.2024 gegen Mittag und nach Ausparken am 8.11. gegen 16:30 Uhr **

**Nach mieten des Jetskis und normalem rumfahren auf dem Meer, fing nach stoppen und Anker legen, der Motor des Jetskis zu rauchen an und es kam die Meldung, beim Versuch den Motor zu starten, dass das Fahrzeug zu stark beschädigt ist. Und nach automatischer Einparkung und beim Versuch es wieder zurückzugeben, war das Jetski selbst mit einem Reparaturkit immer noch zu stark beschädigt, um es wieder abgeben zu können. Das Jetski wurde wieder eingeparkt und ich möchte es wieder zurückgeben**

**Jetski Motor sollte nicht schon bereits nach einmaliger Nutzung anfangen zu rauchen und dadurch fahruntüchtig werden**

**![Bug Support Jetski](https://github.com/user-attachments/assets/c7a669cf-7155-4da8-aa92-475649b8fb00)**

Danke für euere Hilfe.

**Comment by rodistic** [comment]
next update ist das fixed
