### ISSUE TITLE
Artefakt bei Hotelreihe am See in Sandy Shores

### ISSUE THREAD

**Issue by Schamocke** [mexyn/statev_v2_issues#395]
**Cam_Snyder**

Cam_Snyder
**Zeitpunkt (Datum / Uhrzeit)**

22.11.2020 / 03:02 Uhr
**Beobachtetes Verhalten**

Bei Anfahrt mit Hellion an Hotelwand kommt wenige Meter neben der Wand zum Zusammenstoß mit einem unsichtbaren Artefakt, welches scheinbar Fahrzeuge unmittelbar außer Betrieb setzt (S. Video-Anhang)
**Erwartetes Verhalten**

Kein Artefakt, da freie Fläche
**Schritte um den Fehler nachvollziehen zu können**

mit Fahrzeug wenige Meter neben der Wand entlang fahren

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

[Grand Theft Auto V 2020.11.22 - 03.02.16.49.DVR_Trim.mp4.zip](https://github.com/mexyn/statev_v2_issues/files/5579708/Grand.Theft.Auto.V.2020.11.22.-.03.02.16.49.DVR_Trim.mp4.zip)

**Comment by its4l3x** [comment]
Bitte bei YouTube oder andere Videoplattform hochladen. Danke.

**Comment by DonVitoDiangelo** [comment]
Müsst ihr euch absperren diesen Bereich. Denke mal das ist die Kollision vom Haus. Da können wir dann eh nichts machen, sry
