### ISSUE TITLE
Vapid Contender Tuning verschwunden

### ISSUE THREAD

**Issue by badshah23** [mexyn/statev_v2_issues#3951]
**Character Name**
Yuri Black

**Auftrittszeitpunkt (Datum / Uhrzeit)**
08.11.24 12:10 Uhr

**Beobachtetes Verhalten**
Tuning - Aufbau Ladefläche verschwunden. 

Das gleiche ist schon mal nach einem Restart zu Halloween passiert. Hatte dann am Montag den Aufbau neu einbauen lassen. Und jetzt war er gestern n ach dem Restart wieder weg.

**Erwartetes Verhalten**
Aufbau noch vorhanden

**Optional: Video / Bilder des Fehlers**
![GTA5 2024-11-09 19-59-17](https://github.com/user-attachments/assets/ce1dd2b5-2444-4a45-8f90-76943587ea32)

![GTA5 2024-10-13 18-09-56-min](https://github.com/user-attachments/assets/ba348fc1-eccc-4b64-8290-342a83bce10a)

**Comment by rodistic** [comment]
hast du zwischendurch noch was anderes in der Werkstatt machen lassen? @badshah23

**Comment by badshah23** [comment]
nein

**Comment by Snipser92** [comment]
Ich melde mich hier auch mal. Beim Jobuilt Rubble habe ich in der Ladefläche auf einmal den Müll wieder drin, obwohl ich den vor Monaten in der Werkstatt entfernt lassen habe.

**Comment by rodistic** [comment]
Gleiches Issue wie https://github.com/statevde/statev_v3_issues/issues/3849 .
Deswegen erstmal geschlossen, wir sind weiter dran
