### ISSUE TITLE
Ladepunkt CraftBar

### ISSUE THREAD

**Issue by SgtTukiTukii** [mexyn/statev_v2_issues#3952]
Teresa_Martinez

10.11.2024 
10.45 Uhr

Ich würde gerne den Ladepunkt der CraftBar vom Gehweg an die Straße verlegen lassen. Warum? Erstmal blockiert man den Gehweg nicht mehr und Zweitens ist es für die Verpackung die uns beliefert immer ein Akt mit der Achse dort vernünftig ranzukommen.
Anbei schicke ich zwei Bilder, einmal den alten Punkt und einmal den neuen Wunschpunkt:

![Uploading CraftBar Ladepunkt Alt.png…

![CraftBar Ladepunkt Neu](https://github.com/user-attachments/assets/d58eaeab-adde-4f3b-8a21-2920f87d006e)
]()

**Comment by SatyriaDine** [comment]
Hab dir den Abladepunkt so verschoben, dass er nun leichter zugänglich ist. :) Next update.
