### ISSUE TITLE
LA Roads geht seit Ende des Halloween Events nicht mehr

### ISSUE THREAD

**Issue by xMissRi** [mexyn/statev_v2_issues#3954]
**Auftrittszeitpunkt:**
Späten Abend/Nacht des 02.11.2024 auf den 03.11.2024 nach ende des Halloweens Events.

**Beobachtetes Verhalten:**
Während des Halloween Events ging LA Roads noch ganz normal, seit der Normale Server wieder Online ist lädt dieses nicht mehr auf State.

**Info:**
Andere Spieler scheinen das selbe Problem zu haben, siehe den Community Support Channel.

**Comment by rodistic** [comment]
Ayy Gude,

wir können keinen Support für externe Mods geben, wir dulden diese (zumindest LA Roads) nur bei uns.
Bitte an den Mod Creator wenden, potentiell hat da ein GTA reingeschlagen.
