### ISSUE TITLE
Verlinkung auf Social funktioniert nicht trotz richtigem Tag

### ISSUE THREAD

**Issue by stepz2k9** [mexyn/statev_v2_issues#3955]
**Character Name**
Kelani_Larsson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11.11. / 20:20 Uhr

**Beobachtetes Verhalten**
Verlinkung der Most Wanted-social Page nicht möglich. Man gibt den Tag in einem Beitrag als @MOST_WANTED ein, wie er angezeigt wird auf dem Profil:

![Screenshot 2024-11-11 074139](https://github.com/user-attachments/assets/5604d8af-e6e5-4325-8512-fbc7c5a2f8df)

Klickt man dann aber auf die Verlinkung, kommt folgende Fehlermeldung: 

![Screenshot 2024-11-11 074737](https://github.com/user-attachments/assets/bca0c0ca-5921-41ed-968a-7d58e2b2112e)

**Erwartetes Verhalten**
Verlinkung funktioniert. Geht ja bei anderen Social-Pages auch und die Unterstriche müssen ja enthalten sein.  Sollte der Tag im Profil von Most Wanted falsch dargestellt sein, müsste das verändert werden.

**Comment by rodistic** [comment]
Ayy Gude,

der Fehler lag spezifisch am Account, ist fixed

P.S.: das gilt nicht rückwirkend für Tags, nur bei neuen
