### ISSUE TITLE
Verladepunkt  verlegen  bitte 

### ISSUE THREAD

**Issue by LuciferMaccabee** [mexyn/statev_v2_issues#396]
Lucifer_Maccabee

22.11.2020 16:39

**Beobachtetes Verhalten**
Verladepunkte sind mitten auf dem Gehweg und kann mit grossenm fahrzeug nicht ab und beladen 

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
[Hallo.pdf](https://github.com/mexyn/statev_v2_issues/files/5579756/Hallo.pdf)

**Comment by DrGrizzlY17** [comment]
Richtige Screenshots und Infos anfügen bitte

**Comment by LuciferMaccabee** [comment]
unter hallo.pdf sind die bilder und infos , oder braucht ihr andere bilder ?

**Comment by LuciferMaccabee** [comment]
> Lucifer_Maccabee
> 
> 22.11.2020 16:39
> 
> **Beobachtetes Verhalten**
> Verladepunkte sind mitten auf dem Gehweg und kann mit grossenm fahrzeug nicht ab und beladen
> 
> **Erwartetes Verhalten**
> 
> **Schritte um den Fehler nachvollziehen zu können**
> 
> **Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
> 
> **Optional: Video / Bilder des Fehlers**
> [Hallo.pdf](https://github.com/mexyn/statev_v2_issues/files/5579756/Hallo.pdf)

![Grand Theft Auto V Screenshot 2020 11 22 - 14 21 41 85](https://user-images.githubusercontent.com/74867601/99938316-d4342280-2d67-11eb-8a30-f9c6d0d47579.png)
![Grand Theft Auto V Screenshot 2020 11 22 - 14 22 45 05](https://user-images.githubusercontent.com/74867601/99938323-d72f1300-2d67-11eb-8d07-2d9c378ec9bd.png)

![Grand Theft Auto V Screenshot 2020 11 23 - 08 34 22 78](https://user-images.githubusercontent.com/74867601/99938344-e2823e80-2d67-11eb-8dbe-6b168c173077.png)
![Grand Theft Auto V Screenshot 2020 11 23 - 08 34 44 51](https://user-images.githubusercontent.com/74867601/99938365-eada7980-2d67-11eb-849b-c3c0842ed04a.png)
![Grand Theft Auto V Screenshot 2020 11 23 - 08 35 20 65](https://user-images.githubusercontent.com/74867601/99938383-f2018780-2d67-11eb-9fa5-b3efa3630b44.png)
![Grand Theft Auto V Screenshot 2020 11 23 - 08 35 46 64](https://user-images.githubusercontent.com/74867601/99938398-f7f76880-2d67-11eb-8b60-1cd375a8df7a.png)
![Grand Theft Auto V Screenshot 2020 11 23 - 08 36 45 24](https://user-images.githubusercontent.com/74867601/99938407-fcbc1c80-2d67-11eb-88df-af6540309e85.png)
![Grand Theft Auto V Screenshot 2020 11 23 - 08 37 05 68](https://user-images.githubusercontent.com/74867601/99938418-0776b180-2d68-11eb-8ebe-77a84171de3e.png)

**Comment by DrGrizzlY17** [comment]
> unter hallo.pdf sind die bilder und infos , oder braucht ihr andere bilder ?

Jaein, ich lade ungern PDFs ausm Internet herunter, die keinen vertrauenshaften Ursprung haben. Arbeitskrankheit,

Danke mit den Bildern, kann ich arbeiten :)

**Comment by DrGrizzlY17** [comment]
Done
