### ISSUE TITLE
Fehler beim auspacken für Weihnachtsbäume

### ISSUE THREAD

**Issue by adrosso** [mexyn/statev_v2_issues#3961]
Seitdem Update kann man die Weihnachtsbäume ja auspacken, leider mit den falschen Sachen.
![fehler](https://github.com/user-attachments/assets/c2168f92-97ce-4df3-9d8a-6b59848ad40b)

**Comment by rodistic** [comment]
Ayy Gude,

ist mit nächsten Update gefixed
