### ISSUE TITLE
E-Auto aufladen Fehlerhaft

### ISSUE THREAD

**Issue by KruemelGames** [mexyn/statev_v2_issues#397]
Dave Weinstein

22.11. 16.49Uhr

Man kann sein E-Auto aufladen ohne dafür bezahlen zu müssen

Man bezahlt vorher und wenn man abbricht bekommt man einen sein Geld zurück was man nicht verbraucht hat mit dem Laden des Autos.

-Mit E-Auto an Ladestation fahren und aufladen.
-Overlay von Ladestation schließen und wieder öffnen
-Ladevorgang abbrechen und nicht genug Geld dabei haben
-Ladevorgang bricht ab
-ins Auto steigen -> Prozentzahl von Akkus gestiegen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=VawVXxDLV6U

**Comment by M4rvinLP** [comment]
https://github.com/mexyn/statev_v2_issues/issues/343

**Comment by Kalumel** [comment]
Ist eine Lösung in Sicht?
@r3sist3nt

**Comment by r3sist3nt** [comment]
Doch, ist fixed nach dem nächsten Update.
