### ISSUE TITLE
Neue Mützen sitzen nicht richtig

### ISSUE THREAD

**Issue by Pandaaabaer** [mexyn/statev_v2_issues#3970]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Hailey Adams

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Heute entdeckt (15.11.2024)

**Beobachtetes Verhalten**
Die Haare clippen nicht.. Dadurch sieht das mit den neuen Mützen bisschen doof aus.

**Erwartetes Verhalten**
Mützen passen

**Schritte um den Fehler nachvollziehen zu können**
Mütze aufsetzen, in dem Fall die (F) Brown Festive Reindeer Hat

**Optional: Video / Bilder des Fehlers**
![20241115231703_1](https://github.com/user-attachments/assets/042e090a-aab0-4ee1-9ec5-1886d5bae432)

**Comment by Statev-Bonsai** [comment]
die weihnachtsmütze für männer ist auch 5 größen zu groß ;D

**Comment by ySimbaa** [comment]
Jaz hatte da extra keine Hair Extra rein gemacht, da viele solche Mützen mit normalen Haaren tragen wollten. 

Und Bonsai, da kann man nichts machen.
