### ISSUE TITLE
Bug Carlos

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3976]
Die letzten Tage kam es vermehrt vor das die Missionen nicht automatisch beendet werden wenn man ein Fahrzeugteil abbrennt obwohl die Meldung kommt.
Ich kann es absolut nicht reproduzieren, es passiert einfach so obwohl ich immer das selbe mache und die Autos gleich "behandel".

**Comment by Statev-Bonsai** [comment]
edit: die Meldung Mission abgebrochen erscheint manchmal gar nicht obwohl man was abbrennt...

**Comment by DrGrizzlY17** [comment]
Klassisches Whoppa
