### ISSUE TITLE
Unstuck durch esc

### ISSUE THREAD

**Issue by SHaagmann** [mexyn/statev_v2_issues#3979]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Character Name**

Andrew_Jared
**Auftrittszeitpunkt (Datum / Uhrzeit)**

17.11
**Beobachtetes Verhalten**

Wenn man in einer Animation ist, die an eine Position gebunden ist und man drückt esc kann man sich frei bewegen und auch z.B. den Tankvorgang nicht abbrechen
**Erwartetes Verhalten**

Man bleibt stuck
**Schritte um den Fehler nachvollziehen zu können**

Irgendeine aktion ausführen mit ner festen Position z.B. Tanken oder nen shop
esc drücken
laufen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by QA-Pregon** [comment]
#3838
Is da mit drin aufgenommen
Zumindest Intern xD
