### ISSUE TITLE
Alarm nicht Sync

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#3988]
Heute ist es aufgetreten das eine Spielerin im Ammunation den Alarm den ich bei meiner Arbeit ausgelöst habe gehört hat aber ich habe nix gehört, irgendwas scheint dort nicht zu passen.

2 Shops vorher habe ich den ausgelösten Alarm von mir aber gehört, also schließe ich mich als Fehlerquelle aus ^^

**Comment by QA-Pregon** [comment]
#3965
