### ISSUE TITLE
Radio nicht sync

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#399]
**Character Name**
Jannik Datsch

**Zeitpunkt (Datum / Uhrzeit)**
22.11 17:25

**Beobachtetes Verhalten**
Das Radio ist nicht sync:  Zum einen kommen bei zwei Personen auf dem gleichen Sender verschiedene Lieder, zum anderen ist auch, wenn man im Auto das Radio anmacht, das Radio nicht gesynct bei Musik und auch Sender wechseln.

**Erwartetes Verhalten**
Radio sollte gesynct sein.

**Schritte um den Fehler nachvollziehen zu können**
siehe oben

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by r3sist3nt** [comment]
Lieder sind nicht sync. Nur ein/ausschalten.
