### ISSUE TITLE
Keine Funktionen mehr nutzbar nach Dispatch Übernahme

### ISSUE THREAD

**Issue by AmeliaWinterssan** [mexyn/statev_v2_issues#3993]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

**Amelia Winters**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.11. ab 19:30 Uhr, schon auch öfters davor an anderen Tagen

**Beobachtetes Verhalten**
nach Übernahme Dispatch keinerlei Funktionen mehr benutzbar, egal ob Handy, Tablet, Dispatchfenster öffnen/ schließen, Fahrzeuge fahren/ öffnen, kein Funkgerät mehr nutzbar, kein Inventar mehr nutzbar etc. 

**Erwartetes Verhalten**
Alles sollte weiterhin nutzbar sein nach Dispatch-Übernahme

**Schritte um den Fehler nachvollziehen zu können**
Übernehme Leitstelle / Dispatch, danach ist kein Öffnen des Dispatchfensters möglich, sowie alle Funktionen außer Gefecht. Nur Neustart des altV Multiplayers hilft kurzzeitig

**Comment by QA-Pregon** [comment]
Irgendwas vorher oder danach gemacht, was da noch mit reinspielen könnte?
Da bei 99% der Spieler das ja ohne Relog geht und ich es nicht reproduziert bekomme, muss da noch ein anderer Faktor mit reinspielen

**Comment by AmeliaWinterssan** [comment]
Zum selben Zeitpunkt war ein weiterer Spieler zeitgleich auch als Leitstelle / Dispatch angemeldet.  Weiß nicht ob das zum Problem führt. Ansonsten ganz normal verhalten davor und danach. Leitstelle übernommen und dann ging danach nichts mehr. Beim Mal davor konnte ich den Dispatch PC IC noch nutzen. Seit gestern komplett nicht mehr.

**Comment by QA-Pregon** [comment]
Kannst du den Dispatch weiterhin nicht nutzen?

**Comment by AmeliaWinterssan** [comment]
Hab ich in den letzten Tag nicht ausprobiert und gestern kam ich nicht rein, wegen diesem Loginproblem. Wenn ich dazu komme diese Woche noch, teste ich es nochmal aus.

**Comment by AmeliaWinterssan** [comment]
Hallooo, hab jetzt den Dispatch ausprobiert und jetzt scheint zu funktionieren. Ich werde es aber weiter beobachten. Danke euch für eure Hilfe
