### ISSUE TITLE
Kleidermenü nach Kleiderkauf im Klamottenladen

### ISSUE THREAD

**Issue by DerHessenTyp** [mexyn/statev_v2_issues#40]
**Zeitpunkt (25.08.2020 / 21:27 Uhr)**

**Beobachtetes Verhalten**
 Nach dem Kauf von einem Oberteil beim Kleiderladen am MRPD wo meine Spielpartnerin was kurzes zuvor an hatte und ich zuvor was langes mussten wir beide den Regler wie aufm Liveserver benutzen, dass wir wieder Arme hatten. Das Ding nicht mit nur anklicken auch nach mehrmaligem Versuch und anderer Kleidung immer noch der Fehler.

**Erwartetes Verhalten**
Ich kann mich erinnern in Phase 1 konnte man seine Kleidung so oft wie möglich ausm Kleiderschrank nehmen an und ausziehen und musste nicht an seiner Kleidung ,,zupfen"

**Schritte um den Fehler nachvollziehen zu können**
Man kauft ein Oberteil, nimmt die Option zum anziehen und muss dann die Regler Kurzarm auswählen um wieder anständig die Arme am Charakter zu haben sonst sind sie weiterhin unsichtbar.

**Comment by tastydev** [comment]
Der Torso musste schon immer manuell ausgewählt werde. Dadurch existiert eine viel höhere Auswahlmöglichkeit von Klamotten/Outfits
