### ISSUE TITLE
[SAMMEL-TICKET] Fahrzeuge teleportieren sich an alte Position

### ISSUE THREAD

**Issue by Warsaft** [mexyn/statev_v2_issues#400]
**Stefan_Ebering und Simon_Burgstaller**

**21.11.20 und 22.11.20 mehrere Zeiten**

**Unser Phantom Jobuilt (Kenzeichen: LS XJ 33 Besitzer: Simon_Burgstaller) wird egal wo wir ihn Parken, ob mit Large Achse angehängt oder abgehängt immer wenn wir uns weiter entfernen auf seinen Alten immer gleichen "Lieblingsparkplatz" zurücktelepotiert.
Wir stellen ihn am Mount Chiliad unten ab, fahren in die Stadt oder rauf zur Klettermine und wenn wir wieder da sind ist der Phantom in LS. Kein Gamecrash oder irgendwas passiert in der Zeit dazwischen.**

**Phantom bleibt da stehen wo er abgestellt wurde**

**Am Mount Chiliad unten abstellen, in die Stadt fahren oder rauf zur Klettermine und nach 5-10 min. wieder nachsehen. 
![Phantom Lieblingsplatz](https://user-images.githubusercontent.com/74870616/99909580-b7f1a080-2ce9-11eb-9931-f68e89010d57.png)
.**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by JulianMa** [comment]
**Bitte in diesem Issue alle Relevanten informationen zu diesem Fehler sammeln**. 
Das alt:V Team kann dies reproduzieren.
Falls jemand genau weiß, welche schritte man machen muss, damit dieser Fehler sicher auftritt, dann schreibt das bitte hier rein. Das würde allen alt:V Servern helfen.

**Comment by sempre88** [comment]
Ich hatte das bisher vermehrt wenn ich ein Fahrzeug ausparke und damit unmittelbar zu einer einer Fertigung fahre, ca 5km, nach dem betreten und verlassen der Firma war das Fahrzeug meist an dem platz wo es zuletzt vor dem einparken stand. Ich werde mal schauen ob ich es zuverlässig reproduzieren kann. Ich hatte das Problem vornehmlich mit einem Rapid GT Classic und einem Osiris, falls das fahrzeug eine Rolle spielen könnte.

**Comment by Statev-Bonsai** [comment]
Man kann keine Schritte sagen wie man es reproduziert, es ist random...
Vorgestern war es am schlimmsten, habe 3 Fahrzeuge benutzt, ALLE wurden teilweise nach verlassen der Streaming Range versetzt, aber das auch nicht jedes mal sofort.
Habe schon versucht es zu unterbinden indem ich am Abstellort mit dem Kofferaum etc interagiert habe, hat aber nix genützt...
Vollkommen willkürlich scheint dieses Problem aufzutreten, und wie gesagt ich habe schon einiges versucht es zu triggern.. aber erfolglos

**Comment by JulianMa** [comment]
@Statev-Bonsai es ist nicht random, weil ein Computerprogramm nun mal deterministisch arbeitet. Der post hier zieht darauf ab, das es reproduzierbar sein muss, und wir eben diesen Prozess finden wollen. Wenn du diese Schritte nicht kennst, dann schreib doch einfach nichts rein. Aber hier rein zu Flamen das es random ist, hilft niemanden weiter.

**Comment by Auralein** [comment]
Bei mir mal wieder ebenso..

Auftrittszeitpunkt (Datum / Uhrzeit)
28.12.2020 ca 21 Uhr

CaraCara wurde hinter den Firmen geparkt (Motor aus, Handbremse gezogen und abgeschlossen) danach für 1h off gegangen und beim LogIn stand der CaraCara beim Restaurant. Verhalten wurde wiederholt, allerdings blieb der CaraCara dieses mal hinter den Firmen. Passierte aber bereits vor einiger Zeit schon mal und da auch mehrmals hintereinander (wurde aber damals im Support bereits nachverfolgt).

Erwartetes Verhalten
CaraCara sollte auf dem Parkplatz bleiben.

Schritte um den Fehler nachvollziehen zu können
Auto beladen am Restaurant -> zu den Firmen gefahren und dort entladen -> Fahrzeug hinter den Firmen wie oben beschrieben geparkt

**Comment by Statev-Bonsai** [comment]
Ich habe ein Video vom kompletten Vorgang, also vom ausparken des Fahrzeuges bis zum Port man sieht auf dem Video jegliche Interaktion..
Ist es hilfreich wenn ich es hochlade, es geht 15minuten, daher die frage...
Es dreht sich um eine Zugmaschine inklusive Hänger, beides wurde nach verlassend es Gebäudes zu einer anderen Stelle geportet.

**Comment by JulianMa** [comment]
Neu geöffnet, da nach wie vor nicht gelöst.
Damit nicht jedes mal neue Issues erstellt werden, bleibt das offen.

**Comment by JulianMa** [comment]
Vielleicht nochmal ein aktuelles Update:
Das alt:V Team weiß von dem Fehler, kann ihn aber nicht beheben, da nicht genau bekannt ist was das ganze auslöst.
Wir haben Serverseitige Logs, die alle Teleportationen aufzeichnen.
Falls es Updates gibt, poste ich die hier.

**Comment by tastydev** [comment]
@Statev-Bonsai Hey Bonsai, hast du das Video noch? Das Problem wird alt:V intern demnächst stärker untersucht, daher könnte dein video eventuell helfen

**Comment by DonVitoDiangelo** [comment]
Bitte einmal Feedback da lassen, ob das Problem noch vorhanden ist.

**Comment by Hutstaender** [comment]
Ich glaub nicht, hab mich auch mal umgehört.

**Comment by JulianMa** [comment]
@DonVitoDiangelo @Hutstaender das Problem ist weiterhin vorhanden.
Ich führe darüber auch Logs. In der Vergangenen Woche sind > 60 Teleports aufgetreten. Die Logik ist dabei relativ offen, sodass bei weitem nicht alle Teleports registriert werden.

**Comment by JulianMa** [comment]
**Aktueller Stand:** Wir haben den wahrscheinlichen Auslöser des Fehlers gefunden und an alt:V gemeldet. Der Fehler ist bestätigt.
**Wir können den Fehler jetzt auch Reproduzieren.**
Wir müssen nur noch auf den Bugfix seitens alt:V warten.

**Comment by Statev-Bonsai** [comment]
Das sind die besten Nachrichten seid Wochen, gute Arbeit Jungs ;)

**Comment by JulianMa** [comment]
alt:V hat gestern einen _**möglichen**_ Fix in den RC Branch gepushed. Wenn der Fix wirksam ist, dann sollte das Problem mit dem alt:V-6.0 Release in 2 Tagen behoben sein.

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2001

**Comment by miischaa** [comment]
#2028

**Comment by miischaa** [comment]
Leider immer noch so...
Gestern zuletzt gegen 23:30 den Wagen in Vinewood bei 7055 auf dem Hof geparkt. 
Nun sehe ich, dass ich ein Ticket von 00:06Uhr habe, weil der angeblich am Würfelpark stand und auch in der Garage eingeparkt ist.

https://i.gyazo.com/26d7778822936907c6d16d58b4498d4f.png

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2086

**Comment by TheOutburst** [comment]
#2116

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/2223
