### ISSUE TITLE
Tuning Factory hat kein Bild im VNet

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#4005]
Ja wie oben beschrieben, die Tuning Factory hat kein Bild im VNet 

Fehler: https://i.imgur.com/jHkyf9L.png

Mögliches Ersatzbild weil ich das rote Auto nicht mehr sehen möchte ;_;: https://i.imgur.com/i3NrxcR.jpeg

LG Charly

**Comment by TheOutburst** [comment]
Hab dat Bild ma eingefügt, kann sein, dass wir das noch ändern, passt nicht ganz ins Styling Konzept der anderen Firmen @Erumeldor @SatyriaDine
