### ISSUE TITLE
Toy Grabber verbuggt?

### ISSUE THREAD

**Issue by Philosofisch** [mexyn/statev_v2_issues#4016]
**Character Name**
Charly Parker

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.12.2024

**Beobachtetes Verhalten**
Ich hab am Weihnachtsmarkt am Toygrabber gespielt und als neugieriger Mensch in die Konsole geguckt. Laut Konsole hätte ich glaub ich schon 2 mal gewinnen sollen, war aber beides mal ein Lose.

**Erwartetes Verhalten**
Das man bei winToyGrabber gewinnt?

**Optional: Video / Bilder des Fehlers**
https://i.imgur.com/fQCmiMj.png
https://i.imgur.com/DYGEwtO.png

**Comment by rodistic** [comment]
Ayy Gude,

der log ist nicht verlässlich was das angeht.
