### ISSUE TITLE
Deko Reh Klein nicht platzierbar

### ISSUE THREAD

**Issue by stepz2k9** [mexyn/statev_v2_issues#4025]
**Character Name**
Kelani_Larsson

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.12.2024 / 22:33

**Beobachtetes Verhalten**
Habe das Deko Reh Klein für ein Ticket gekauft. Wollte es daheim in Chumash platzieren. Rechtsklick drauf passiert nichts. Man kann Punkt spammen, nichts passiert, Reh ist aus dem Inventar weg. Wollte dann in's Haus gehen, wurde mir angezeigt "Du kannst keine Gegenstände im Haus platzieren" und ich kam nicht rein.
Alles was half war, einen anderen platzierbaren Gegenstand aufzustellen. Dann war das Reh wieder in der Tasche.

**Erwartetes Verhalten**
Man kann das Reh platzieren.

**Schritte um den Fehler nachvollziehen zu können**
siehe oben

**Comment by pumakadse** [comment]
Bitte nach restart einmal Checken ob das Problem weiterhin besteht.

**Comment by stepz2k9** [comment]
> Bitte nach restart einmal Checken ob das Problem weiterhin besteht.

Funktioniert leider immer noch nicht.
