### ISSUE TITLE
Ausparkpunkt Garage versetzen..

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#4028]
der ausparkpunkt ist zu nah am tor, bei längeren fahrzeugen buggt sich das fahrzeug im tor fest.
wäre klasse wenn man den punkt auf den bürgersteig VOR der schrägen auffahrt setzen könnte, denn sie knallen beim ausparken immer extrem auf die schräge.
![Screenshot_9](https://github.com/user-attachments/assets/c2d1c62c-b7d2-4ef7-addf-48faa8a18d2b)

![Screenshot_10](https://github.com/user-attachments/assets/2e95d6b2-cedb-4fe2-b139-e2a5bf093900)

![Screenshot_18](https://github.com/user-attachments/assets/e833f8f7-cbe2-4f34-9e47-1d4789d217ed)

**Comment by DrGrizzlY17** [comment]
@Statev-Bonsai dir steht nen kleiner asbo eh mehr. Steig doch lieber darauf um

**Comment by Statev-Bonsai** [comment]
hallo, gibts hier was neues?

**Comment by SatyriaDine** [comment]
Hallöööchen ich habe dir den Garagenpunkt ein kleines Stückchen versetzt. Sollte jetzt eigentlich nicht mehr passieren. :)
