### ISSUE TITLE
Charakter GHOST Innenstadt

### ISSUE THREAD

**Issue by PsYke86** [mexyn/statev_v2_issues#403]
**Charackter Name**

**Zeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Bitte beschreibe dein Problem genau, danke

**Comment by PsYke86** [comment]
Ich bin Richtung PD gefahren am Würfelpark (Über die Brücke) und dort habe ich eine Person stehend durch sie Luft fliegen sehen.. 

Leider kein Bild oder Video vorhanden.

Diese Person verschwand spurlos aus der Luft nach ca 20sec und nach "Nirgendwo hin" ...

**Comment by r3sist3nt** [comment]
bekannt
