### ISSUE TITLE
Annimation bei Lachgas Ballons fehlt..

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#4037]
Irgendwie gibts da keine Annimation mit dem Ballon, ich denke das ist nicht richtig..

**Comment by QA-Pregon** [comment]
Hast da mal nen Clip oder kannste mir mal bitte sagen was du da vorher gemacht hast?
Bzw ist das ein dauerzustand oder war das einmalig?

**Comment by Statev-Bonsai** [comment]
bislang hatte keiner der die ballons konsumiert hat eine annimation, daher denke ich das da was broke ist... 
nur die wirkung setzt halt ein.

**Comment by QA-Pregon** [comment]
Schon immer oder seit neustem?

**Comment by Statev-Bonsai** [comment]
die ballons sind noch net lange dabei, daher gibts da keine vorerfahrungen.

**Comment by QA-Pregon** [comment]
![image](https://github.com/user-attachments/assets/8e160a79-4e1b-45d3-875a-7f3fcffea649)
Geht um die oder?

**Comment by Statev-Bonsai** [comment]
ja, aber befüllt..

**Comment by QA-Pregon** [comment]
jo sind die, is nur kein bild aus Inv ^^

**Comment by Statev-Bonsai** [comment]
du verstehst nicht :D ich komm mal ins dc

**Comment by QA-Pregon** [comment]
sollte halt eigentlich so aussehen
![image](https://github.com/user-attachments/assets/683059a8-cbf4-4249-984a-ecf182e1297e)

**Comment by Statev-Bonsai** [comment]
ne, die annimation kam bei keinem der sie konsumiert hat

**Comment by ySimbaa** [comment]
My fault. Next update fixed
