### ISSUE TITLE
Jetzieger Ladepunkt erschwert das erreichen mit Phantom und Achse Antrag auf verschiebung

### ISSUE THREAD

**Issue by JackHomestone** [mexyn/statev_v2_issues#404]
Jack Homestone

Jetzieger Punkt: https://pic.statev.de/image/GILkR
Vorschlag für neuer Punkt: https://pic.statev.de/image/GI5ZB
Klingelschild: https://pic.statev.de/image/GIuBc

**Comment by DrGrizzlY17** [comment]
moved
