### ISSUE TITLE
Hauler verliert immer Türen 

### ISSUE THREAD

**Issue by powerswissi** [mexyn/statev_v2_issues#406]
**Character Name**

Roger_Thickle

**Zeitpunkt (Datum / Uhrzeit)**

20.11.2020 19.19
**Beobachtetes Verhalten**

Der Hauler schmeisst immer wieder die Türen ab beim ein-austeigen. Obwohl frisch repariert. Beobachte das Verhalten bei vielen Haulern. Bei Phantoms etc. noch nicht gesichtet.

**Erwartetes Verhalten**

Türe sollte dran bleiben

**Schritte um den Fehler nachvollziehen zu können**

Nicht nachvollziehbar

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot_756](https://user-images.githubusercontent.com/70152806/99913473-3ce3b680-2cf8-11eb-9f05-10f09f1577c8.png)

**Comment by DonVitoDiangelo** [comment]
Wie ist hier so der Stand? Probleme noch vorhanden oder hat sich das erledigt?

**Comment by powerswissi** [comment]
Beim Hauler isses ok.. jetzt tritt es aber beim Mixer und beim Packer auf

**Comment by DonVitoDiangelo** [comment]
Hat sich das Problem mit dem letzten alt:V Update behoben?

**Comment by powerswissi** [comment]
Bis jetzt ist nichts aufgetreten.. Danke <3
