### ISSUE TITLE
Zuckungen beim Telefonieren.

### ISSUE THREAD

**Issue by PsYke86** [mexyn/statev_v2_issues#407]
**Character Name**

Jack_Napyr

**Zeitpunkt (Datum / Uhrzeit)**

20:00 / 22.11.20

**Beobachtetes Verhalten**

Zuckungen beim telefonieren 

**Erwartetes Verhalten**

Keine Zuckungen beim telefonieren, wenn man durch eine Tür geht.

**Schritte um den Fehler nachvollziehen zu können**

Telefonieren und durch eine normale Tür gehen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)** 

**Optional: Video / Bilder des Fehlers**
 Leider kann ich mein Video nicht vom Handy aus in die App hier packen... einfach per Discord anschreiben, kann das Video dann dort senden.

**Comment by its4l3x** [comment]
Das ist bereits immer so, da wir die Anim alle 2,8 Sekunden neu forcen zu setzen. Daher invalid und es nicht anders geht.
