### ISSUE TITLE
Heilen durch Bandage und Medic nicht möglich

### ISSUE THREAD

**Issue by CrimeMouse** [mexyn/statev_v2_issues#408]
**Pablo_Dosmas**

**22.11.2020 / ca. 20:00 (Datum / Uhrzeit)**

**Nach Verletzung, lässt sich der Char nicht mehr Heilen, weder durch Bandagen (dort komm ein Error: Item kann zur Zeit nicht genutzt werden) noch von Medizinern**

**Sofortiges Heilen nach der Behandlung vom Mediziner**

**Ich wurde geschlagen, danach war keine Behandlung möglich**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Die Meldung welche du geschrieben hast, gibt es nicht. Bitte die richtige und vollständige Meldung mitteilen.

**Comment by its4l3x** [comment]
#REMEMBER

**Comment by CrimeMouse** [comment]
Ich weiß den genauen Wortlaut der Meldung nicht, da sie nur für ca. 5sek angezeigt wurde. Sollte der Fehler erneut auftreten, werde ich nochmal nen Ticket schreiben :)

**Comment by ShauniKT** [comment]
https://prntscr.com/vs830a

hier die Fehlermeldung, welche beim nutzen von erste-Hilfe-Kästen und Bandagen auftritt.
evtl. ist das die gesuchte Meldung

**Comment by its4l3x** [comment]
Wenn das die Fehlermeldung ist, dann ist die Gewollt. Es herrscht ein Cooldown X auf Bandagen und Erste Hilfe Sets.

**Comment by CrimeMouse** [comment]
Nein, die ist es nicht...
Mein Char hatte noch die Hälfte an Leben und konnte sich weder selbst noch von einem Mediziner heilen lassen...
Leider oder zum Glück ist es bis jetzt nicht wieder aufgetreten, sollte dies der Fall sein mache ich einen Screenshot.
Die Fehlermeldung war leider zu kurz da um mir sie zu merken 🤦🏼‍♂️

**Comment by CrimeMouse** [comment]
@ShauniKT sry, das war doch die Fehlermeldung :/ 

https://pic.statev.de/image/G7ntC

aber der Fehler tritt halt auf obwohl ich genug Leben habe, hab nur ein paar Schneebälle abbekommen.

**Comment by its4l3x** [comment]
Wie gesagt. Da herrscht ein Cooldown drauf. Du musst erst X Minuten warten, bis du wieder ein Medipack / Bandage nutzen kannst. Somit Gewollt und daher kein Bug => Close
