### ISSUE TITLE
Eine bitte zwecks verladepunkte

### ISSUE THREAD

**Issue by StateV2Marie** [mexyn/statev_v2_issues#4083]
Hallo ich hätte eine bitte und zwar gehts um gebäude aka Firma JJ's Mühle  bei der Adresse Hawick Ave. 2146a  der Hash ist   pf_Hawick_8  wir brauchen leider eine umsetzung des verladepunktes da man mit nen lkw echt probleme hat dort ran zu kommen ohne lkw zu schrotten.

![1anichgut](https://github.com/user-attachments/assets/8194feaf-dff3-4382-9d2b-7ca5b6a08490)
![1amarker](https://github.com/user-attachments/assets/25177bdd-a19e-4cb2-8097-013a2da11a0d)

**Comment by SatyriaDine** [comment]
Hallöchen, ich hab das gerade mal mit mehreren verschiedenen LKWs getestet und sehe da wirklich keinen Grund warum der Lademarker an die Straße gesetzt werden soll. Von beiden Seiten aus kann man die Gasse befahren, sei es mit Pounder oder Phantom+Auflieger. :)
