### ISSUE TITLE
Reproduzierbarer Fehler bei Verkauf von Material ab Firma! (Material verschwindet/Fahrzeug bleibt blockiert)

### ISSUE THREAD

**Issue by xExplicitx** [mexyn/statev_v2_issues#409]
**Das unten beschriebene Problem ist gerade eben wieder aufgetaucht ( 20:00 Uhr), beim Verkauf von 10 Eisenbarren ab Firma verschwindet die Menge aus dem Lager, Geld wird weder beim Verkäufer noch beim Käufer gebucht... Material ist verschwunden.
Da der Verkaufsvorgang nicht abgeschlossen werden kann ist der Käufer nicht mehr in der Lage sein Fahrzeug zu bewegen.

**Der Fehler ist also reproduzierbar**

Dies wurde bereits im Support gemeldet, dieser bat mich diese Meldung noch einmal zu schicken mit dem Video im Anhang.**

Charaktername:
Jay Parker

Jay Parker / Kalle Grabowski

Zeitpunkt (Datum / Uhrzeit)
22.11.2020 um 12:45 Uhr

Beobachtetes Verhalten
Fahrzeug (Kalle Grabowski) fuhr auf den Entladepunkt der Firma "House of Flames" (pfAlexMirMurLaEastRew_1).
Beim versuchten Verkauf an der Firma (363 Eisenbarren à 25$) verschwanden die Eisenbarren aus dem Lager und es wurde kein Geld gebucht, weder bei der Firma noch beim Privatkonto von Kalle Grabowski. Nach diesem Fehler konnte Kalle Grabowski den Motor seines Fahrzeugs nicht mehr anlassen.

Erwartetes Verhalten
Beim Verkauf ab Firma hätten die 363 Eisenbarren in das Fahrzeug geladen werden müssen und das Geld vom Privatkonto (Kalle Grabowski) auf das Firmenkonto (House of Flames) gebucht werden müssen. Das Fahrzeug des Käufers hätte weiterhin normal funktionieren müssen.

Schritte um den Fehler nachvollziehen zu können
Fahrzeug fährt auf Entladepunkt->Eingabe Menge des Artikels der verkauft werden soll->363 Eisenbarren nicht mehr im Lager /Fahrzeug des Käufers defekt.

**Video:**

 https://www.youtube.com/watch?v=QQ7dvMoRU7o&feature=youtu.be

**Comment by its4l3x** [comment]
Vorhin debugged. Lag daran, dass der Kofferraum nicht offen war. Beim nächsten Update kommt dann eine Meldung das dieser offen sein muss.

**Comment by xExplicitx** [comment]
Okay, danke.
