### ISSUE TITLE
ständige Gamecrashes in der Stadt

### ISSUE THREAD

**Issue by EnglischAllergie** [mexyn/statev_v2_issues#4099]
## WICHTIGE INFORMATION!!:
```
Hier sollen nur Bugs gemeldet werden, Vorschläge bitte ins StateV-Discord!
```

Mit welchem Character wurde das Verhalten in-game ausgelöst/beobachtet
Richard Rheinland

**Auftrittszeitpunkt (Datum / Uhrzeit)**
ca 1 Woche

**Beobachtetes Verhalten**
Ständige Crashes an verschiedentlichen Punkten in der Stadt, besonders an der Brücke links vom Mission Row PD richtung Mirrow Park und zwischen der Kreuzung Alta Street/San Andreas Ave. und der Kreuzung Peaceful Street/San Andreas Ave. an der Brücke, ebenso regelmäßig in der Kohlemine und am Ölfeld

Ebenso wie auf den anderen 2 Screens erkennen sind auch häufig Gamecrashes

Die Weihnachtsbeleuchtung ist deaktiviert, Grafikmods keine, nur der nvidia Game Filter

**Erwartetes Verhalten**
Kein Game crashs

**Optional: Video / Bilder des Fehlers**
![crash1](https://github.com/user-attachments/assets/0d863ba3-2c22-4870-8f91-d6fd4e038c83)
![crash2](https://github.com/user-attachments/assets/6c28b09f-d563-4bae-85d3-ddd49449ce0d)
![crash3](https://github.com/user-attachments/assets/d4978201-1935-44a6-9b41-6d30e9ba16b0)
![crash4](https://github.com/user-attachments/assets/fe7e3586-2665-487b-b7fc-08b71120f308)

**Comment by Daniel-Meister-508** [comment]
Hey wir sind bereits dabei eine Lösung für die Probleme zu finden

**Comment by pumakadse** [comment]
#4092
