### ISSUE TITLE
Im Imbiss einkaufen nicht möglich

### ISSUE THREAD

**Issue by DerHessenTyp** [mexyn/statev_v2_issues#41]
**Zeitpunkt (25.08.2020 / 21:27 Uhr)**

**Beobachtetes Verhalten**
Ich möchte etwas an einem Imbiss in der Teppichgasse (Dazu das Bild) Aber auch am Pier an den beiden Imbissen von Roland Becker kaufen ob Getränk oder Speisen und es kommt die Fehlermeldung ,,Die Steuern konntne nicht berechnet werden [TAXC801]" und ,,Du hast kein Geld dafür. Wir hatten beide über 500$ auf der Hand und es hat bei beiden nicht geklappt. Geld bleibt in der Geldbörse und Ware beim Imbissverkäufer

**Erwartetes Verhalten**
Ich bekomme nach auswählen des Buttons ,,Kaufen" meine Ware und mir wird Geld abgezogen

**Schritte um den Fehler nachvollziehen zu können**
steht oben im beobachteten Verhalten

**Optional: Video / Bilder des Fehlers**
![Fehler beim Imbiss](https://user-images.githubusercontent.com/70151958/91221552-15dc0f80-e71e-11ea-8fd1-83f26b197c91.jpg)

**Comment by its4l3x** [comment]
Seit dem letzten Restart gefixed. :)
