### ISSUE TITLE
Werkstatt Bennys kein Mitarbeiterlimit

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#410]
**Beobachtetes Verhalten**
Bennys kann mehr als 15 Leute einstellen. Eine LKW Werkstatt ist aber auf 15 Limitiert. Bitte einmal auch die kleinen Werkstätten checken.

**Erwartetes Verhalten**
Nicht mehr als 15 leute einstellbar.

**Comment by MarcelMuerto** [comment]
@Dean-Gallagher 
Sollte im nächsten Update behoben sein.
