### ISSUE TITLE
Verschiedene Items fürs Portemonnaie freigeben

### ISSUE THREAD

**Issue by Kane403** [mexyn/statev_v2_issues#4114]
Hallo, 
es wäre cool wenn man folgende Items ebenfalls ins Portemonnaie packen könnte:

- Schwarze Kreditkarte
- Fahrzeugpapiere
- Autoschlüssel

LG

![grafik](https://github.com/user-attachments/assets/a82af0b2-a574-4887-b8a0-46238e776c09)

**Comment by QA-Pregon** [comment]
Vorschläge bitte nur über den Discord Server
