### ISSUE TITLE
Animationen werden allen Favoriten hinzugefügt

### ISSUE THREAD

**Issue by croveans** [mexyn/statev_v2_issues#412]
Ausgangspunkt: Mehrere Animationsordner zum Aufteilen der Animationen.

Bug: Wenn ich einem Ordner eine Animation hinzufüge, ist diese auch im Anschluss im anderen Ordner vorhanden. Lösche ich aus einem der beiden Ordner die Animation, wird diese auch aus beiden Favoritenordnern gelöscht.

Siehe auch hier im Video: https://streamable.com/ivtaur

**Comment by Chrinis007** [comment]
Fixed???
