### ISSUE TITLE
Ankauf über Auflieger

### ISSUE THREAD

**Issue by powerswissi** [mexyn/statev_v2_issues#413]
**Character Name**

Roger_Thickle

**Zeitpunkt (Datum / Uhrzeit)**

21 Uhr am 22.11.2020

**Beobachtetes Verhalten**

 Über Lager bzw Raffinierie kann nicht angekauft werden..
Verschiedene "Stellungen" wurden ausprobiert um irgendwie anzukaufen.

**Erwartetes Verhalten**

Ankaufen sollte funktionieren..

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Kann schon ;) Denk dran, Kofferraum aufzumachen. Nach dem Update bekommst du auch eine Meldung, dass dieser Offen sein muss.

**Comment by its4l3x** [comment]
fixed. next update
