### ISSUE TITLE
StateNet Bennenungsfehler

### ISSUE THREAD

**Issue by RealSocius** [mexyn/statev_v2_issues#414]
**Character Name**
Sebastian Schindler

**Zeitpunkt (Datum / Uhrzeit)**
22.11.2020 22:02

**Beobachtetes Verhalten**
Statenet:
Anzahl und Preis bei Tankstellen umgedreht: (Bild 1)
Im Dienst und Online umändern! Meta im StateNet (Bild 2)

**Optional: Video / Bilder des Fehlers**
(Bild 1) https://prnt.sc/vnzrni
(Bild 2) https://prnt.sc/vnzs3e

**Comment by MarcelMuerto** [comment]
- Im Dienst und Online umändern! Meta im StateNet (Bild 2) ✔

**Comment by MarcelMuerto** [comment]
- Im Dienst und Online umändern! Meta im StateNet (Bild 2) ❌
(Wurde abgeklärt, dass es so bleibt, wer dies ausnutzt -> Support)
