### ISSUE TITLE
Preise verschwinden aus Ladentheke (Restaurant)

### ISSUE THREAD

**Issue by Asmier** [mexyn/statev_v2_issues#415]
Asmier Umid

**Zeitpunkt (Datum / Uhrzeit)**
22.11.2020 / 14:23 - 16:30 (zwischen drinne)
22.11.2020 / 22:50

**Beobachtetes Verhalten**
Restaurant: snrKebab alias 🦴 Bone Eater 🍽️
Preise verschwinden aus dem Tablet
Daher Ware nicht in Theke 

**Erwartetes Verhalten**
1. Tablet aktualisieren
2. Preise bleiben

**Schritte um den Fehler nachvollziehen zu können**
1. Tablet aktualisiert
2. Preise auf 0

Nachtrag: Preise ab 23:00 Uhr wieder drinnen

**Comment by Asmier** [comment]
Habe es nochmal getestet.
Konnte den Fehler nachproduzieren ist aber nicht so schlimm wie gedacht.
Musste sie aber nicht neueintragen

**Schritte um den Fehler nachvollziehen zu können**
StateNet aktualisieren / neueinloggen
Direkt auf Ladentheke gegangen
Preise sind auf 0
Dann auf Mitarbeiter Check oder anderen Reiter gehen
Wieder auf Ladentheke gehen
Preise stehen richtig drinnen

**Comment by MarcelMuerto** [comment]
@Asmier 
Ich konnte dieses Fehlverhalten leider nicht nachstellen.
Bei mir laden die Preise sofort ohne Probleme, versuch das nochmal nachzustellen und mir bescheid zu geben.

**Comment by Asmier** [comment]
@MarcelMuerto Hab dir hier einmal ein Video gemacht.

https://youtu.be/KpwCxwq-5z0

**Comment by Asmier** [comment]
Aktuell sehe in die Preise direkt wieder wenn ich ins Ladeninventar klicke.
Das Problem wurde also behoben. Auch wenn ich das Video versuche nachzustellen
