### ISSUE TITLE
Name von Feldern fehlt auf Karte rechts

### ISSUE THREAD

**Issue by Blanus-1** [mexyn/statev_v2_issues#416]
**Zeitpunkt (Datum / Uhrzeit)**
Immer
**Beobachtetes Verhalten**
Fast alle Farmfelder sind nicht mehr seitlich auf der Karte beschrieben man sieht nur mehr den farbigen Punkt

**Erwartetes Verhalten**
So wie früher wenn auf einen Punkt klickt dann erscheint Rechts der Name um zu wissen was das dort ist

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Aktuell technisch nicht umsetzbar

**Comment by Blanus-1** [comment]
Dann wäre ein Wiki Eintrag welche Farbe was ist unbedingt notwendig oder eine Eingabe der Felder wie bei Firmen!
