### ISSUE TITLE
öffentliche Garagen

### ISSUE THREAD

**Issue by Annabelle-Smith** [mexyn/statev_v2_issues#417]
**Annabelle_Smith**

**22.11.2020/ 13:00 - 16:00 Uhr**

**Beobachtetes Verhalten**

Los. Santos Öffentliche Garage, Auto kann nicht mehr in die öffentliche Garage eingeparkt werden wen man einen Schlüssel zu diesem Fahrzeug hat 

**Erwartetes Verhalten**

Durch die Fahrzeug Thematik, wäre es gut wen man die Fahrzeuge von denen man einen Schlüssel hat auch wieder in die öffentliche zurück parken kann wen man diese benötigt hat. Sonst stehen bald wieder viele Fahrzeuge bei den öffentlichen Garagen. 

**Schritte um den Fehler nachvollziehen zu können**

 Hingefahren, Schlüssel vorhanden, geht nicht in die Garage

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Annabelle-Smith** [comment]
Sorry fürs falsch ausfüllen vorhin

**Comment by r3sist3nt** [comment]
war der schlüssel in deinem Inventar oder in der Schlüsseltasche?

**Comment by Annabelle-Smith** [comment]
der war am schlüsselbund
also schlüsseltasche

**Comment by Annabelle-Smith** [comment]
war ein pounder vielleicht hilft das weiter

**Comment by tastydev** [comment]
Welche garage war das?

**Comment by tastydev** [comment]
@Annabelle-Smith

**Comment by Annabelle-Smith** [comment]
Los Santos kart 3201
 aso die unter der hk

**Comment by tastydev** [comment]
Kann es sein, dass es eine Teamgarage war? :D

**Comment by Annabelle-Smith** [comment]
nein war die öffentliche unter der Hk wo auf der Hauptstrasse ist wo dan auch central ist.  aber versuche es gleich nochmal.

**Comment by Annabelle-Smith** [comment]
Also ich habe es nochmals versucht mit Schlüssel in der Tasche sowie Schlüssel am Schlüsselbund. Mit Motor Aus und An. Es geht nicht es Parkt ihn nicht ein den Pounder. hab jetzt mal bezeichnung geschaut steht Garage 1 /20 ist es

**Comment by Annabelle-Smith** [comment]
hab es ebend versucht und muss den pounder bei der garage auf dem platz stehen lassen weil ich ihn da nicht mehr eingparkt bekomm.

**Comment by Annabelle-Smith** [comment]
![pounder piet](https://user-images.githubusercontent.com/74880091/100119741-7db60980-2e77-11eb-9903-38060a208fc0.png)
![pounder piet1](https://user-images.githubusercontent.com/74880091/100119844-9b836e80-2e77-11eb-860e-456632470ec7.png)
![piet3](https://user-images.githubusercontent.com/74880091/100119880-a63e0380-2e77-11eb-9a34-134716e4ba33.png)

**Comment by its4l3x** [comment]
Ist der Bug noch beständig @Annabelle-Smith ? Wenn Ja, bitte mir Daten zu deinem Pounder schicken (Kennzeichen). Dann gucke ich mal

**Comment by Annabelle-Smith** [comment]
Sorry hat sich erledigt. geht wieder dachte ihr hattet das schon gemacht (gefixt) deshalb habe ich mich nicht mehr geachtet. danke aber für eure mühen. es funktioniert :-)
