### ISSUE TITLE
Pegassi Ruffian

### ISSUE THREAD

**Issue by Stiefel911** [mexyn/statev_v2_issues#418]
Nun da ich gerade nicht weiß ob es bearbeitet wird oder nicht, erstelle ich dieses hier......

Für die Problematik nun dieser LinK https://statev.de/forum/StateBug/index.php?issue/3919-pegassi-ruffian-teil2/

So long

**Comment by r3sist3nt** [comment]
Bitte schauen ob nach dem nächsten Update gefixed

**Comment by Stiefel911** [comment]
Nabend/Morgen/Tag :-D

Leider ist es negativ, ein meiner Ruffi befindet sich noch immer kein Scheinwerfer :~

vor ca. 10 min extra ausgeparkt und dementsprechend, da es dunkel ist, wieder eingeparkt.

So long

**Comment by Stiefel911** [comment]
why?

**Comment by DonVitoDiangelo** [comment]
Ist auf jeden Fall solved. Wenn, dann vllt. durch altes Tuning, Am besten mal resetten und neu schauen. Ansonsten via DB neu setzen lassen.

**Comment by Stiefel911** [comment]
Die Ruffi ist ungetuned, so Original wie sie aus dem Werk kam... Da werde ich morgen in den TS Supp gehen für einen reset
