### ISSUE TITLE
Antrag auf Verlegung des Ladepunktes/ Palme ist gewachsen 

### ISSUE THREAD

**Issue by Warsaft** [mexyn/statev_v2_issues#419]
Stefan_Ebering

Aktueller Ladepunkt
![aktueller Ladepunkt](https://user-images.githubusercontent.com/74870616/99918992-e20f8680-2d1a-11eb-933e-2bdc3a659e32.png)

Neuer Ladepunkt etwas mehr auf die Straße wegen der Palme
![Neuer Ladepunkt](https://user-images.githubusercontent.com/74870616/99919010-feabbe80-2d1a-11eb-9930-1a78b62f1efd.png)

Klingelschild
![Klingelschild](https://user-images.githubusercontent.com/74870616/99919032-213dd780-2d1b-11eb-8ecd-060051408f78.png)

**Comment by DrGrizzlY17** [comment]
moved
