### ISSUE TITLE
Fahrzeuginventar nach Explosion noch nutzbar

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#42]
**Zeitpunkt (Datum / Uhrzeit)**
25.08.2020 - 22:08

**Beobachtetes Verhalten**
Mögl. Fehler:
Fahrzeug Inventar ist noch Nutzbar nach Fahrzeugexplosion.
Reproduzierbar bei Helikoptern und "normalen" Fahrzeugen.
Ebenfalls kann man mit dem Fahrzeug noch Interagieren. Sowohl mit X Menu als auch mit Schlüssel. (Türen auf, etc.)

**Erwartetes Verhalten**
Das Kofferraum Inventar wäre nicht erreichbar und Türen nicht Interagierbar

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug ausparken, Kofferraum befüllen. Fahrzeug zum Explodieren bringen, In den Kofferraum schauen.

**Optional: Video / Bilder des Fehlers**
![20200825221212_1](https://user-images.githubusercontent.com/70150887/91222839-0d84d400-e720-11ea-8a3a-1786971abf87.jpg)
![20200825221214_1](https://user-images.githubusercontent.com/70150887/91222845-0eb60100-e720-11ea-8735-23ef779dd1d1.jpg)

**Comment by eiksch** [comment]
fixed beim nächsten Update
