### ISSUE TITLE
Phantom+Achse fährt max. 50 km/h oder langsamer

### ISSUE THREAD

**Issue by Gamba1701** [mexyn/statev_v2_issues#420]
**Max_Maiham , Tom_Clark**

**22.11.2020 zwischen 19 - 22 Uhr**

**Phantom fährt mit Achse sehr Langsam, bei kleinsten Anstieg bleibt man sogar stehen. Man muss erst wieder aussteigen und wieder einsteigen, dann kann man wieder normal weiter fahren.**

**Fahrzeuge sollte mit normaler Geschwindigkeit bewegt werden können**

**Kann kein Schritt nennen der dazu führt. Ist mir (Max_Maiham) passiert und  Tom_Clark ist es ebenfalls passiert. Kann passieren wenn man die Achse gerade angekuppelt hat aber auch wenn die schon längst dran ist(z.B. von einer Ölpumpe zur nächsten fahren)**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Fahrzeugpool wurde überarbeitet. Hier wurden auch div. Fahrzeuge generfed/normalisiert.
Keine Änderung vorgesehen, wir behalten das aber im Auge.
