### ISSUE TITLE
Hauler fährt abnormal Langsam mit Achse

### ISSUE THREAD

**Issue by Kaycee91** [mexyn/statev_v2_issues#421]
**Nick Adam**

**Zeitpunkt (22.11.2020 / ca 20Uhr)**

**Beobachtetes Verhalten**

Der Hauler fährt mit Achse sehr sehr langsam und Bergauf muss man ihn fast Tragen maximal 35 kmh Bergauf oder Stillstand und nur mit Anlauf möglich
**Erwartetes Verhalten**

Der Hauler sollte wie früher ohne große Probleme normale Anstiege bewältigen können 
**Schritte um den Fehler nachvollziehen zu können**

In Hauler einsteigen Achse anhängen z.b übers große Öl Feld Fahren 
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Kaycee91** [comment]
Korrektur das Problem besteht nur mit der Tank Achse mit der Trailer Achse verhält er sich relativ normal

**Comment by DonVitoDiangelo** [comment]
Fahrzeugpool wurde überarbeitet. Hier wurden auch div. Fahrzeuge generfed/normalisiert.
Keine Änderung vorgesehen, wir behalten das aber im Auge.
