### ISSUE TITLE
Versetzung des Ladepunktes

### ISSUE THREAD

**Issue by SandyFolk** [mexyn/statev_v2_issues#422]
Sandy_Folk
**Character Name**
Sandy_Folk

**Zeitpunkt (Datum / Uhrzeit)**
23.11.2020 / 01:16 

**Beobachtetes Verhalten**
Kann an diesem Punkt nicht mit größeren Fahrzeugen Be- und Entladen

**Erwartetes Verhalten**
 Punkt bitte nach vorne an die Strasse setzen

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Ladepunkt Alt](https://user-images.githubusercontent.com/74882929/99921335-045cd080-2d2a-11eb-9c84-9392695e4b8b.png)

![Ladepunkt Neu](https://user-images.githubusercontent.com/74882929/99921341-0aeb4800-2d2a-11eb-9cf9-4c0a935c6baf.png)

Firmenhash | davis35
-- | --
![InkedKarte_LI](https://user-images.githubusercontent.com/74882929/99921413-88af5380-2d2a-11eb-9a0b-e7aa0da9d8ac.jpg)

**Comment by DrGrizzlY17** [comment]
done
