### ISSUE TITLE
UI verschiebt sich mit Tab-Taste

### ISSUE THREAD

**Issue by MrMutantus** [mexyn/statev_v2_issues#423]
**Character Name**

Felix Sommer

**Zeitpunkt (Datum / Uhrzeit)**

23.11.2020 01:30

**Beobachtetes Verhalten**

Nach drücken der Tab-Taste verschiebt sich das UI nach oben hin um die Länge des Funkgerätes.
Auch zu beobachten ist, dass nach mehrfachem drücken der TAB-Taste ein Fokus im Vunk liegt (zu sehen im zweiten Bild).

**Erwartetes Verhalten**

Das UI bleibt wo es ist.

**Schritte um den Fehler nachvollziehen zu können**

Stehen. Tab drücken.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

1920x1080 window mode

**Optional: Video / Bilder des Fehlers**

![20201122210819_1](https://user-images.githubusercontent.com/23027596/99925253-af2aba00-2d3d-11eb-8127-08e607a8551a.jpg)
![20201122210838_1](https://user-images.githubusercontent.com/23027596/99925259-b5b93180-2d3d-11eb-9b6b-c23091137855.jpg)

**Comment by r3sist3nt** [comment]
siehe #253
