### ISSUE TITLE
LKWs können nicht eingeparkt werden (Garage kleiner Weihnachtsmarkt)

### ISSUE THREAD

**Issue by polyholic** [mexyn/statev_v2_issues#424]
**Character Name**
Amber Antigua

**Zeitpunkt (Datum / Uhrzeit)**
23.11. 05:31

**Beobachtetes Verhalten**
Pounder und Hauler konnten nicht eingeparkt werden 

**Erwartetes Verhalten**
Pounder und Hauler einparken können 

**Schritte um den Fehler nachvollziehen zu können**
Pounder und Hauler einparken versuchen

**Comment by DonVitoDiangelo** [comment]
Funktioniert, Bitte erneut versuchen.
