### ISSUE TITLE
Bitte um Ladepunktversetzung

### ISSUE THREAD

**Issue by Clawdie** [mexyn/statev_v2_issues#425]
Glinda Leverstone/Ehrmantraut

Chiliad Nähstube
Vespucci Blvd. 55

pfAkiMissionRowRew_11

Ladepunkt zuvor bereits schwer erreichbar, v.a. durch Pounder usw., ohne Laterne umzustoßen.
Jetzt zusätzlich Straßenschild gegeben.

Bitte um Versetzung des Ladepunkts ein Stück mehr zur Straße hin.

**Erwartetes Verhalten**
Problemloses Be-/Entladen

![ladepunkt](https://user-images.githubusercontent.com/74894642/99934878-96cb9700-2d5f-11eb-98f1-61fa0886945f.jpg)

**Comment by DrGrizzlY17** [comment]
https://i.gyazo.com/7c3b87d0157e37dde1b66130c249f40c.jpg
https://gyazo.com/91d92ad189a8cffdf4d4826cc79856f3

Keine Probleme dran zu kommen ohne irgendwas um zu rammen. Weder Pounder noch Achse
