### ISSUE TITLE
Kleidungsbug: Fehldarstellung/Artefakte/Tattoos sichtbar

### ISSUE THREAD

**Issue by Clawdie** [mexyn/statev_v2_issues#426]
**Character Name**
Glinda Leverstone

**Zeitpunkt (Datum / Uhrzeit)**
In den letzten Tagen, wiederholt, reproduzierbar

**Beobachtetes Verhalten**
Kleidung verbuggt, Anzeige zeigt schwarze oder weiße Flecke/Artefakte in Brusthöhe bzw. Tattoos sind zu sehen.
Unabhängig von Einstellung (langärmlig 1-3 z. B.), diverse Kleidungskategorien, auch bei männl. Charakteren schon gesehen, bislang:
- Minikleider
- Biker Shirts
- Hinterland Snap Front Jacket
- Uniformhemden
- Hemdblusen

**Erwartetes Verhalten**
Keine Fehldarstellung/Artefakte, keine Tattoos sichtbar

**Schritte um den Fehler nachvollziehen zu können**
Sachen anziehen.

![bikershirt](https://user-images.githubusercontent.com/74894642/99935229-8667ec00-2d60-11eb-80d1-2bd105f0c300.jpg)

**Comment by Chrinis007** [comment]
Gehört hier nicht so gut hin, aber unter Alt:V sehe ich nur selten die Tattoos von Leuten die natürlich auch ein erkennungsmerkmal sind. Der Grund ist mir unklar aber wenn ich die sehe dann nur ne Minute dann sind sie wieder für 10mins weg

**Comment by DonVitoDiangelo** [comment]
alt:V issue im release branch

**Comment by its4l3x** [comment]
Ist bekannt bei alt:V mal schauen, wann die das fixen.
