### ISSUE TITLE
Beim versetzen des Ladepunktes vergessen den alten zu entfernen

### ISSUE THREAD

**Issue by Warsaft** [mexyn/statev_v2_issues#428]
Stefan_Ebering

Der rechte auf dem Bild an der Palme müsste noch entfernt werden. Vielen Dank
![doppelt](https://user-images.githubusercontent.com/74870616/99950321-a6a5a400-2d7c-11eb-9109-2a6209eb6d8b.png)

Klingelschild
![Klingelschild](https://user-images.githubusercontent.com/74870616/99950340-ae654880-2d7c-11eb-9487-639360f4a049.png)

**Comment by DrGrizzlY17** [comment]
Das ist nicht der Ladepunkt deiner Firma. Da haben wohl zwei Punkte gelegen, was mir nicht aufgefallen ist. Habs angepasst. Danke für den Report
