### ISSUE TITLE
Tauchen - Keine Auswirkung auf Skill Jäger

### ISSUE THREAD

**Issue by RomanSpielberg** [mexyn/statev_v2_issues#429]
Roman_Spielberg

23.11.2020 ca. 10 bis 11Uhr

Trotz mehrere Tauchgänge, hat sich der Skill Jäger nicht verändert.

**Erwartetes Verhalten**
Verbessung im Skill

**Schritte um den Fehler nachvollziehen zu können**
Tauchen gehen

**Comment by DonVitoDiangelo** [comment]
Das ist so korrekt :)  Finds IC raus.
