### ISSUE TITLE
Lackierstation defekt

### ISSUE THREAD

**Issue by Eve-Noxito** [mexyn/statev_v2_issues#431]
**Character Name**
Eve_Noxito

**Zeitpunkt (Datum / Uhrzeit)**
23.11.2020 ca 12:15

**Beobachtetes Verhalten**
Wir wollten so eben in der Werkstatt Sludgie Customs eine Lackierung durchführen, haben die Farbe ausgewählt, Kunde hat die Rechnung unterschrieben, Geld wurde vom Konto abgezogen und Material wurde aus dem Lager benutzt. Jedoch kam kein Fortschrittsbalken. Nach einer Stunde noch keine Veränderung, weder beim Fortschrittsbalken noch bei der Lackierung. Fahrzeuge konnte nicht aufgeschlossen oder bewegt werden. Haben das Auto dann mittels Abschlepper von der Lackierstation entfernt.
Bei erneutem Versuch zu Lackieren mit einem anderen Fahrzeugmodel, selbes Problem. 

Der Inhaber des Fahrzeugs wie auch der Werkstatt angestellt haben beide das Spiel beendet udn erneut eingeloggt. Auch das blieb erfolglos.

**Comment by CatherineGallagher** [comment]
Das passiert nur bei RGB Lackierung

**Comment by r3sist3nt** [comment]
ist bekannt

**Comment by BlackyGER** [comment]
Sobald du einen Lack hast der 3,05 Dose Roten Lack braucht triggert es den Bug. Sprich einen Lack verbrauch von x,05. Das lager hat nämlich keine komma lagerstände mehr. Sprich es liegen immer 10 Dosen Lack rum und nicht mehr 6 komma 95 dosen lack

**Comment by r3sist3nt** [comment]
danke, ist mit dem nächsten restart behoben
