### ISSUE TITLE
Defibrillator Erfolg erhöhen

### ISSUE THREAD

**Issue by Chrinis007** [mexyn/statev_v2_issues#434]
**Character Name**
Christian_Maier

**Zeitpunkt (Datum / Uhrzeit)**
Seit V2

**Beobachtetes Verhalten**
Manchmal braucht man um eine Person aufzuheben 10-15 versuche.
Wäre super wenn die alte Erfolgsrate wieder käme

**Erwartetes Verhalten**
Höherer Erfolg wie bei V1

**Schritte um den Fehler nachvollziehen zu können**
Bewusstlose Person defibrillieren

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by tastydev** [comment]
Chance erhöht mit nächstem Update
