### ISSUE TITLE
2 Abladepunkte blockiert & bitte versetzen

### ISSUE THREAD

**Issue by DRECKSGitHub** [mexyn/statev_v2_issues#435]
Guten Tag, ich würde gerne den Abladepunkt von meiner Tankstelle versetzen lassen, da dieser jetzt mit großen Phantoms+Achse nicht belieferbar ist, während Autos an den Elektrozapfsäulen betankt werden

Es handelt sich um die Tankstelle RedBull Racing Team, Little Seoul/Ginger St.3 Firmenhash petrolstation35

Darüber hinaus könnten wir hier mit einer Fehlermeldung 2 Fliegen mit einer Klappe schlagen,

da bei unserer Firma: DarkNet Industries Store2 - Calais Eve 110 Firmenhash: pfGroupAllRew_34 nun eine neue Palme im Weg des Abladepunktes dieser Firma steht und dieser ebenfalls schlecht anzufahren ist

Da wir von beiden Firmen gerne den Abladepunkt zusammengelegt auf der markierten Stelle auf dem Foto hätten, denke ich ist es auch für euch so am einfachsten.

Die Stelle ist auf dem Foto markiert, RP technisch macht es auch Sinn da die Firme direkt an die Tankstelle angrenzt.

Die neue Position blockiert auch keine anderen wichtigen Punkte, tanken kann man auf dieser Seite der Tankstellenzapfsäulen auch nicht

Vielen lieben Dank dafür

![ABLADEPUNKT TANKE](https://user-images.githubusercontent.com/74914206/99968520-846e4f00-2d99-11eb-8353-7afed3e87cb3.png)

**Comment by DrGrizzlY17** [comment]
@DRECKSGitHub woher der Hass gegen GitHub?

Beide Ladepunkte versetzt
