### ISSUE TITLE
Animationsgegenstände können auch aus Kofferraum ausgeführt werden

### ISSUE THREAD

**Issue by croveans** [mexyn/statev_v2_issues#437]
**Character Name**
Marty Taylor

**Zeitpunkt (Datum / Uhrzeit)**
23.11.2020

**Beobachtetes Verhalten**
Gegenstände, die eine Animation ausführen (z.B. Notizblock, Fernglas etc.) können auch ausgeführt werden, wenn diese im Kofferraum liegen.

**Erwartetes Verhalten**
Man sollte Gegenstände nur verwenden können, wenn diese am Körper getragen werden.

**Schritte um den Fehler nachvollziehen zu können**
Gegenstand in Auto legen --> Rechtsklick --> Fernglas in der Hand. Kann so auch von mehreren über ein Objekt ausgeführt werden.

**Optional: Video / Bilder des Fehlers**
https://streamable.com/4ad7gz

**Comment by Chrinis007** [comment]
Das ist tatsächlich sehr praktisch beim MD da dort die Trage nur aus dem Kofferraum angewählt werden muss und man so diese nie ins Inventar geben kann und dort auch nicht vergessen werden kann.

**Comment by DonVitoDiangelo** [comment]
Bekommen wir hin mit Ausnahmen ;) Der  @its4l3x  macht das schon 👍

**Comment by its4l3x** [comment]
Sehe bei dieser Sache auch kein Handlungsbedarf. Mmn. finde ich das eher besser als schlechter. Würde das Ticket wieder schließen, da kein Bug.
