### ISSUE TITLE
Neue Tauruskisten werden nicht im Laden angezeigt

### ISSUE THREAD

**Issue by MvvvM** [mexyn/statev_v2_issues#438]
**Duke_Rain**
 Mellow_Esposito

**Zeitpunkt (Datum / Uhrzeit)**
 23.11.2020 - 15:50 ung.

**Beobachtetes Verhalten**
 Die neuen Tauruskisten werden nicht alleine in der Ladentheke angezeigt. Erst wenn die alten Tauruskisten ebenfalls in der Theke sind, werden diese angezeigt.

**Erwartetes Verhalten**
 Die neuen Tauruskisten sollten auch alleine in der Ladentheke angezeigt werden

**Schritte um den Fehler nachvollziehen zu können**
Verpackte Tauruskisten aus der Theke nehmen, die neu produzierten (mit Seriennummer) in die Ladentheke packen. => Taurus steht nicht zum verkauf. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
 https://youtu.be/mTCU9jn8Jzk Video der Situation

**Comment by eiksch** [comment]
@MvvvM Sammel am besten alle deine Waffenkisten mit Seriennummern in einem Auto, wir müssen dann die Seriennummern von den Kisten entfernen, dass du sie wieder verkaufen kannst.

Der Fehler ist beim Update behoben - in Zukunft haben Waffenkisten keine Seriennummern mehr, man tut aber weiterhin Waffenkisten in die Ladentheke, aus denen werden dann Taurus mit Seriennummern.
