### ISSUE TITLE
Antrag auf Garage

### ISSUE THREAD

**Issue by Hawtin1** [mexyn/statev_v2_issues#439]
Jerry_Brown
**Zeitpunkt (Datum / Uhrzeit)**

23.11.2020
**Beobachtetes Verhalten**

house_DavisMidLS_6 wären Baulich platz für 3 Garagen, leider hat das Haus keine einzige, dafür aber das Nachbarhaus eine auf dem Grundstück. 
**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://gyazo.com/97382ee8557a036973913ba19f9eaa7c
https://gyazo.com/e4d5592b9515ecc9eece8405ea573f67
https://gyazo.com/c7190258834941ac66b3bfeec0ec2b89

**Comment by DrGrizzlY17** [comment]
Done

**Comment by Hawtin1** [comment]
Hallo! Hat leider nicht funktioniert kein Marker auf Map für die Garage.

**Comment by DrGrizzlY17** [comment]
Punkt nun hinterm Haus verfügbar
