### ISSUE TITLE
Jedes Tuning benötigt Xenon Scheinwerfer

### ISSUE THREAD

**Issue by ZirbelR** [mexyn/statev_v2_issues#441]
**Character Name**
Richie Zirbel

**Zeitpunkt (Datum / Uhrzeit)**
23.11.2020 17:10

**Beobachtetes Verhalten**
Tuning ohne Xenon Scheinwerfer benötigt Xenon Scheinwerfer, obwohl diese nicht in der Materialliste angezeigt werden.

**Erwartetes Verhalten**
Wenn keine Xenon Scheinwerfer verbaut werden, werden auch keine benötigt

**Schritte um den Fehler nachvollziehen zu können**
In meinem Fall Tuning mit Motorrad (siehe Screenshots) ausführen. Ist laut meinen Aufzeichnungen wohl bei jedem Tuning, da einige Xenon Scheinwerfer mehr im Lager Fehlen als verbaut wurden. Hängt eventuell damit zusammen, dass laut Tuning Tablet alle Fahrzeuge bereits Xenonscheinwerfer mit Farbe Serie verbaut haben obwohl diese seit v2 Release nicht getunt wurden. (ebenfalls siehe Screenshots, laut Kunden wurden keine Xenons verbaut)

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/70246255/99985766-a8885b00-2dae-11eb-92d8-ff1857fe5317.png)
![image](https://user-images.githubusercontent.com/70246255/99985783-afaf6900-2dae-11eb-90ba-4c6c4c8b46c4.png)
![image](https://user-images.githubusercontent.com/70246255/99985854-c48bfc80-2dae-11eb-8a77-bd7fea938d36.png)

**Comment by ZirbelR** [comment]
Weitere Info: Die Xenon Leuchten werden wohl nicht bei jedem Arbeitsgang verbraucht, jedoch müssen sie im Lager vorhanden sein. Gerade getestet beim Dach Tuning vom Lampadati Novak, danach fehlen keine Leuchten im Lager (extra vorher und nachher bestände geprüft)

**Comment by BlackyGER** [comment]
Gibts dazu schon ne Info?

**Comment by JulianMa** [comment]
ist behoben
