### ISSUE TITLE
PD Fahrzeug in öffentlicher Garage

### ISSUE THREAD

**Issue by Shirobaka** [mexyn/statev_v2_issues#443]
**Character Name**
Shigekuni Yamamoto

**Problem**
Ich hatte mit dem Dienstwagen SY 585 (Police Interceptor) am 20.11. einen Unfall, weswegen er mit dem Flatbed zur Werkstatt geschleppt werden sollte, an der Werkstatt hat sich dann der Schlepper mit dem Streifenwagen aufs Dach "gelegt", wodurch das Abladen des Fahrzeuges nicht mehr möglich war.
Mein Kollege war anschließend im Support und hat den Schlepper und den Streifenwagen in die Garage packen lassen.
Das Fahrzeug konnte ich anschließend allerdings in keiner PD Garage vorfinden, also begab ich mich erneut in den Support um das Fahrzeug entsprechend umsetzen zu lassen, dies wurde auch gemacht, laut Aussage sollte das Fahrzeug nun in der Sandy Shores PD Garage sein, dort konnte ich ihn allerdings nicht auffinden.
Nach einem erneuten besuch im Support erfuhr ich, das der Wagen in der öffentlichen Garage Harmony steht, der GM das Fahrzeug aber wohl nicht umsetzen kann.
PD Fahrzeuge können meines Wissens nach nicht aus einer öffentlichen Garage herausgeholt werden, entsprechend muss das Fahrzeug wohl über die Datenbank direkt in die PD Garage gesetzt werden.

**Comment by r3sist3nt** [comment]
schaue mir das mal an

**Comment by r3sist3nt** [comment]
Fahrzeug steht nun im Mission Row
