### ISSUE TITLE
Tankstelle Flughafen LS Zapfsäule fehlt

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#444]
**Character Name**
Jannik_Datsch

**Zeitpunkt (Datum / Uhrzeit)**
23.11 28:06

**Beobachtetes Verhalten**
Bei der Tankstelle am Flughafen LS im Hanger fehlt die Zapfsäule, sie ist aber unsichtbar da, wo ich auch dagegen gefahren bin.

**Erwartetes Verhalten**

Zapfsäule sollte sichtbar sein
**Schritte um den Fehler nachvollziehen zu können**
siehe oben

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/GW6Gi

**Comment by DrGrizzlY17** [comment]
moved
