### ISSUE TITLE
Fahrzeuge werden in öff. Garagen komplett repariert

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#445]
**Character Name**
Jannik_Datsch

**Zeitpunkt (Datum / Uhrzeit)**
23.11 18:27

**Beobachtetes Verhalten**
Fahrzeuge werden in Garage nicht nur optisch sondern auch insgesamt repariert (Motorleuchte)

**Erwartetes Verhalten**
Fahrzeuge bleiben in dem physischen Zustand, in dem sie eingeparkt wurden

**Schritte um den Fehler nachvollziehen zu können**

siehe oben
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by r3sist3nt** [comment]
bekannt, alt:V issue

**Comment by JulianMa** [comment]
fixed durch alt:V
