### ISSUE TITLE
Fahrzeug schließt nach Tankvorgang ab

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#446]
**Character Name**
Jannik Datsch

**Zeitpunkt (Datum / Uhrzeit)**
23.11 18:29

**Beobachtetes Verhalten**
Nach jedem Tankvorgang schließt das Fahrzeug ab, und man muss es erst aufsperren, um wieder einsteigen zu können. 

**Erwartetes Verhalten**
Fahrzeug sollte sich nicht absperren

**Schritte um den Fehler nachvollziehen zu können**
Tanken --> Fahrzeug abgesperrt

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Safety Feature, so gewollt.
