### ISSUE TITLE
Antrag Änderung Ausparkpunkt Vinewood-Garage

### ISSUE THREAD

**Issue by Kindderddr** [mexyn/statev_v2_issues#447]
**Heinrich Zeiss**

**bei jeden Ausparken von Achsen an der Vinewood-Garage**

**Achsen werden in Richtung Gebäude ausgeparkt**

**1. Fahrzeuge gedreht ausparken lassen oder 2. alten Vinewood-Garagen-Ausparkpunkt nutzen (auf der Straße)**

**Achse ausparken lassen**

***

****

**Comment by DonVitoDiangelo** [comment]
@DrGrizzlY17  Bitte checken und wenn möglich etwas verschieben, rotaion bug is alt:V issue in "release" branch.
