### ISSUE TITLE
Sitzanimation "mit Trinken" im Chumach PD im Meetingroom --> Kameraperspektive verbuggt 

### ISSUE THREAD

**Issue by Woarx** [mexyn/statev_v2_issues#449]
**Character Name**
Ernst Hendrikson

**Zeitpunkt (Datum / Uhrzeit)**
23.11.20 - 19:06

**Beobachtetes Verhalten**
Sitzanimation "mit Trinken" im Chumach PD im Meetingroom --> Kameraperspektive verbuggt: Man ist mit seiner Kameraperspektive im Char verbuggt. Dies lässt sich beheben in dem man in die Ego Perspektive wechselt. Normales sitzen ohne Becher funktioniert einwandfrei.

**Erwartetes Verhalten**
Normale Kameraperspektive bei allen Sitzanimationen

**Schritte um den Fehler nachvollziehen zu können**
Auf einen Stuhl im Meetingroom des Chumach PD setzen mit der Animation: Sitzen (Trinken)

**Comment by JannikDatsch** [comment]
Selbiges im Mission Row Aufenthaltsraum

**Comment by DrGrizzlY17** [comment]
Kommt durch den Prop und den Raum. Da man es eigenhändig beheben kann, nicht weiter schlimm
