### ISSUE TITLE
LSPD Rechtesystem Recht Ticket bearbeiten

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#451]
**Beobachtetes Verhalten**

Nicht zwingend ein Fehler, aber im LSPD Rechtesystem fehlt, falls es gewünscht ist, die Option einzustellen, wer Tickets bearbeiten & löschen darf.

**Erwartetes Verhalten**

Rang 13 kann einstellen, wer Rechte hat Tickets zu ändern

**Schritte um den Fehler nachvollziehen zu können**

Team Management öffnen

 @its4l3x weiß bescheid

**Comment by its4l3x** [comment]
Habe ich umgesetzt. Nächstes StateCOM Update.
