### ISSUE TITLE
Dauerhaft Abfallende Türen (normales öffnen) durch teilweise unsaubere Animation (Mustang GT, Hauler, Mixer)

### ISSUE THREAD

**Issue by polyholic** [mexyn/statev_v2_issues#452]
**Character Name**
Amber Antigua

**Zeitpunkt (Datum / Uhrzeit)**
23.11 (seit Nachmittag)

**Beobachtetes Verhalten**
Mixer, Hauler und Mustang GT Türen fallen dauerhaft bzw. nach fast jedem aussteigen  ab, teilweise ist es so schlimm das kaum ist das Fahrzeug repariert und man will aussteigen fällt die Tür ab. Am extremsten ist es beim Mustang GT hier steht man in der halb geöffneten Tür und sobald sich der Charakter teilweise in der Animation noch bewegt ist die Tür schon Geschichte. Gegen 20:20 war es sogar so schlimm das die Tür bei jedem aussteigen ab war. Zum Vergleich beim Buccaneer trat dieses Problem bisher überhaupt nicht auf. 

**Erwartetes Verhalten**
Türen die nicht beim normalen öffnen abfallen, speziell bei besagten Fahrzeugen (vor allem Mustang GT) 

**Schritte um den Fehler nachvollziehen zu können**
Türen der beschriebenen Fahrzeuge öffnen, beim Mustang GT im speziellen auf die Animation achten diese wirkt als wurde Sie nicht sauber ablaufen und dabei die Tür in Mitleidenschaft ziehen. Bzw. die Charakterposition nicht stimmen.

**Comment by DrColgate** [comment]
beim mixer habe ich das auch. aber erst seit nachmittags/abends. heute morgen hatten wir garkeine probleme damit!

**Comment by r3sist3nt** [comment]
Ja, das ist bekannt und es gibt da bereits ein Ticket zu: #406
Ich schließe das deshalb hier.
