### ISSUE TITLE
Werkstatt - Unrealistischer Verbrauch von Lacken 

### ISSUE THREAD

**Issue by LautaroTesto** [mexyn/statev_v2_issues#453]
**Lautaro_Testo**

Lautaro Testo

**Zeitpunkt (Datum / Uhrzeit)**
19:46 - 23.11.2020

**Beobachtetes Verhalten** 
Es wurde Rot-Weiße Lackierung gewünscht und auch ausgeführt. Im Normalfall sollte ja z.B 4x Basislack, 7x Rotlack und 3x Weißlack verbraucht werden, aber 4x Basis Lack und 2x Schwarzlack - was nach meiner Auffindung nicht wirklich der Realität entspricht.

**Erwartetes Verhalten**
Realistischer Verbrauch von Ressourcen 

**Schritte um den Fehler nachvollziehen zu können**
Überprüfen wie das Ergebnis von Farben bei Lackdosen für eine Lackierung berechnet wird.

**Comment by DonVitoDiangelo** [comment]
Bitte erneut prüfen und Rückmeldung geben.

**Comment by LautaroTesto** [comment]
Realistischer ist es vom Verbrauch der Farben, wenn ich Rot lackiere wird auch Rot verbraucht. Jetzt is es aber so, wenn Perllack lackiert wird, kommen da krasse Summen raus + Diamantenstaub.


![](https://i.gyazo.com/d93886c9fde57d1e952ed8573ad4c9c2.png)

![](https://i.gyazo.com/e31dd0d15dcb3bac69bb1b6ae06c9414.png)

**Comment by DonVitoDiangelo** [comment]
Korrekt, da Perl Effekt Extra kostet.
