### ISSUE TITLE
Auto abgeschleppt ohne auszubrennen

### ISSUE THREAD

**Issue by Riyakan** [mexyn/statev_v2_issues#455]
**Riyan Scot**

Riyan Scot
**Zeitpunkt (Datum / Uhrzeit)**
23.11.2020 / ca. 21:40

**Beobachtetes Verhalten**
bin gegen eine leitplanke gefahren und der kofferraum hat angefangen zu brennen das feuer ist ca na 2minuten aus gegangen wollte dann nen abschlepper rufen aber in dem moment wurde der wagen in den Fahrzeug Depot geportet ( auto war so heile nicht expoliert oder kommplett ausgebrannt)

**Erwartetes Verhalten**
Auto hätte da sein sollen damit ich ihn in der werkstatt reperieren kann

**Schritte um den Fehler nachvollziehen zu können**
Bin auf der strecke ins rutschen gekommen seitlich in die leitplanke an irgendetwas hängen geblieben (an der leitplanke) dann brannte der kofferraum
Bild von der unfall stelle ort unten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![Unfall](https://user-images.githubusercontent.com/74933442/100014509-beaa1180-2dd6-11eb-9bd9-bbb884eb4e23.png)

**Comment by DonVitoDiangelo** [comment]
Bitte beobachten. Das Fahrzeug war schon zerstört. Hier gab es einen kleinen Konflikt, daher das direkte einparken. Sollte nicht wieder auftreten.
