### ISSUE TITLE
Antrag versetzung Lade + Eingangspunkt

### ISSUE THREAD

**Issue by Matthew-Dillon** [mexyn/statev_v2_issues#456]
Matthew Dillon

Schon immer

Wenn man jetzt mit einer Achse zum Verladepunkt fahren will bekommt das Fahrzeug Schaden da alles zu eng in dieser Gasse ist und Gegenstände das gefahrlose Rangieren stört.

Es wäre schön wenn man Verlade- und Eingangspunkt auf die andere Seite des Gebäudes verlegen könnte. Dort ist genung Platz siehe Bilder.

Einfach vorbei kommen und anschauen

![Unbenannt1](https://user-images.githubusercontent.com/74933708/100016249-64f71680-2dd9-11eb-9fcf-c067a648d7a6.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/74933708/100016253-66284380-2dd9-11eb-946f-29563fc3740f.PNG)

**Comment by DrGrizzlY17** [comment]
Entladepunkt in die Gasse gesetzt. Eingang bleibt
