### ISSUE TITLE
Hinweise hinzufügen im StateCom defekt

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#458]
**Character Name**
Paul Humpert

**Zeitpunkt (Datum / Uhrzeit)**
23.11.2020 / 20:34 Uhr

**Beobachtetes Verhalten**
Man kann im StateCom keine Hinweise hinzufügen, da bei "Farbe auswählen" nichts mehr ausgewählt werden kann. Die anderen Reiter funktionieren jedoch.

**Erwartetes Verhalten**
Man sollte bei "Farbe auswählen" im StateCom eine Farbe auswählen können.

**Schritte um den Fehler nachvollziehen zu können**
- Im StateCom anmelden
- Die Akte einer beliebigen Person öffnen
- Versuchen, einen Hinweis hinzuzufügen

**Comment by MarcelMuerto** [comment]
@Humperrrt Sollte eigentlich wieder funktionieren, habe das nämlich schon behoben bei dem letzten Update.

**Comment by Humperrrt** [comment]
Funktioniert auch wieder. Habe den Beitrag vor dem Fix erstellt :D
