### ISSUE TITLE
Durchsuchen nach Ergeben

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#46]
**Zeitpunkt (Datum / Uhrzeit)**
25.08.2020 - 22:53

**Beobachtetes Verhalten**
Durchsuchen nach Ergeben ist nach erstmaligem Ergeben immer möglich. Auch über Distanz.

**Erwartetes Verhalten**
Das man sofern die Hände nicht oben sind, man nicht durchsuchen kann.

**Schritte um den Fehler nachvollziehen zu können**
Person muss sich ergeben. Dann Hände wieder runter nehmen.
Anschließend kann man die Person nach lust und laune Durchsuchen.
Dabei spielt es keine Rolle ob die Person während des Durchsuchens weg läuft.

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=_f51cAKyCFM

**Comment by its4l3x** [comment]
Ist kein Bug. Das solltet ihr bitte im RP Handeln 😂
