### ISSUE TITLE
Alte Schlüssel bei der Fahrzeugüberschreibung verlieren nicht die Gültigkeit.

### ISSUE THREAD

**Issue by ChrisY2k** [mexyn/statev_v2_issues#460]
**Character Name**
John Vernon

**Zeitpunkt (Datum / Uhrzeit)**
23.11.2020 - 01:10 Uhr

**Beobachtetes Verhalten**
Hatte den RS7 ins Autohaus gebracht um dieses Fahrzeug auf das MD zu überschreiben. Habe jeweils 2x ans Autohaus verkauft und dann 1x an die Privatperson und 1x an die Fraktion geschrieben. Hatte dann 12 Schlüssel in der Tasche und alle "12" Schlüssel konnten für das Fahrzeug verwendet werden. Es klappte auf und zu sperren sowie Motor anlassen und ausmachen etc...

**Erwartetes Verhalten**
Es sollte so sein wenn das Fahrzeug überschrieben worden ist das die alten Schlüssel ungültig sind und nur die 3 neuen Schlüssel funktionieren sollten aber nicht auch die alten.

**Schritte um den Fehler nachvollziehen zu können**
Autohaus fahren mehrmals aufs Autohaus und Person überschreiben und alle Schlüssel durch testen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Die sind nur gültig, wenn man noch im Inventar die neuen Schlüssel hat. Ansonsten funktionieren sie nicht mehr

**Comment by its4l3x** [comment]
Ein Wontfix. Ist bzw. war auf RageMP auch schon so. Wir werden das mal näher in betracht ziehen, die alten Schlüssel (wenn vorhanden) aus dem Inventar einfach zu löschen.

**Comment by DonVitoDiangelo** [comment]
nein, dafür ist der Schlüsseltausch beim Mechaniker gedacht. Gibt dem Arbeit. ;)
