### ISSUE TITLE
Neue Mieter kriegen keine Miete abgezogen

### ISSUE THREAD

**Issue by RickoSanchez** [mexyn/statev_v2_issues#461]
**Character Name**
Ricko_Sanchez,Shelly_Rose

**Zeitpunkt (Datum / Uhrzeit)**
ca. 16uhr war der Einzug 

**Beobachtetes Verhalten**
Neue Mieter haben sich um 16 uhr im Hotel ( Firmenhash | LittleSeoul_Flat_9 ) eingemietet . Waren auch im Zimmer drin aber es wurde  bis jetzt noch keine Miete gezahlt . Von den alten Mietern wird das Geld korrekt abgezogen nur bei den neuen nicht .

**Erwartetes Verhalten**
Die neuen Mieter ziehen ein und jede anwesende Stunde sollte eigentlich die Miete gezahlt werden .

**Comment by DonVitoDiangelo** [comment]
@RickoSanchez  besteht das Problem nach wie vor?

**Comment by RickoSanchez** [comment]
Das Problem besteht immer noch @DonVitoDiangelo

**Comment by DonVitoDiangelo** [comment]
Wenn das Problem noch bestehen sollte, bitte Gebäude im Support checken lassen.
