### ISSUE TITLE
Fehler bei eingabe im Statecom bei Einsatzfahrzeugen (PD)

### ISSUE THREAD

**Issue by Feuronos** [mexyn/statev_v2_issues#463]
**John Brick**

John Brick

**Zeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

Als PDler im Statecom Beim eingeben der Notizen Werden ebenfalls z.b. bei der Taste E die Blaulichter oder Sirene eingeschaltet. 

**Erwartetes Verhalten**

Es sollte keine Sichtliche reakion geben sondern alles bleiben wie es vor dem eingabefeld ist auf der Tastatur. Sprich Kein an und auschalten von Sirenen  bei eingabe von personen im Statecom

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Chrinis007** [comment]
Duplikat von #388
