### ISSUE TITLE
Frisörladen meldet Roten fehler 

### ISSUE THREAD

**Issue by HansKelly** [mexyn/statev_v2_issues#464]
**Hans_Kelly**

**Zeitpunkt (Datum / Uhrzeit)**
23:35 Uhr am 23.11.2020

**Beobachtetes Verhalten**
Friseurladen mit dem Thema Schminken usw. Sachen sind im Lager vorhanden kommt, aber ein Fehler in der linken Ecke unten das nicht Bonita Creme vorhanden ist obwohl es im Lager liegt vom laden bitte einmal nachschauen danke 

**Erwartetes Verhalten**
Das er Die meldung bringt es sein nicht genügen vorhanden im Lager oder das nix von dem im Lager ist das wir wissen ob wir was neu kaufen müssen.

**Schritte um den Fehler nachvollziehen zu können**
Nach dem man eine kunden/in das Make-Up machen will kommt dir Rote meldung es sei nix im Lager aber es ist vorhanden

**Comment by r3sist3nt** [comment]
Da gibt es bereits ein Ticket zu: #330 
Ich mache das hier deshalb zu.
