### ISSUE TITLE
Antrag auf Garagenplatz/Entladepunkt Haus

### ISSUE THREAD

**Issue by femilu** [mexyn/statev_v2_issues#466]
Riley_Everett Nate_Beckham

**Zeitpunkt (Datum / Uhrzeit)**
24.11.2020

**Beobachtetes Verhalten**
Leider kann ich nichts aus den Fahrzeugen entladen da leider kein Garagenpunkt vorhanden ist bäulichen wären dort 2 Garagen,Leider hat dieses Haus keine einzige  

house_MirrorPark_17

**Optional: Video / Bilder des Fehlers**
https://prnt.sc/vos29s
https://prnt.sc/vos2h1

**Comment by Statev-Bonsai** [comment]
Häuser ohne Garage haben diesen Be/Entladepunkt nicht. Und Garagenplätzen hat das Haus nur wenn eine Garage auf dem Gelände vorhanden ist. Du hast kein Garagengebäude und daher keinen Entladepunkt... Vollkommen normal :)
