### ISSUE TITLE
Fahrräder Cooldown erhöhen

### ISSUE THREAD

**Issue by Chrinis007** [mexyn/statev_v2_issues#467]
**Character Name**
Christian_Maier

**Zeitpunkt (Datum / Uhrzeit)**
Seit einpark update

**Beobachtetes Verhalten**
Fahrräder werden gleich schnell wie Autos eingeparkt

**Erwartetes Verhalten**
Cooldown erhöhen auf 1x pro Restart, sollte es davor nicht (aktiv zb. um in die Firma zu fahren und es dort abzustellen) genutzt worden sein sollte kann das Fahrzeug eingeparkt werden

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Wird so bleiben, ist technisch gesehen wie ein Auto zu behandeln.
