### ISSUE TITLE
Patienten liegen nicht auf dem Bett sondern unter dem Bett wenn diese per RTW eingeliefert werden

### ISSUE THREAD

**Issue by Chrinis007** [mexyn/statev_v2_issues#468]
**Character Name**
Christian_Maier

**Zeitpunkt (Datum / Uhrzeit)**
Seit V2

**Beobachtetes Verhalten**
Patient unten ausn RTW ausgeladen (außerhalb Renderreichweite schätze ich)
Über teleporter nach oben gegangen; Patient liegt unter dem Bett bei ihm aber synced auf dem Bett

**Erwartetes Verhalten**
Am Bett liegend für jeden

**Schritte um den Fehler nachvollziehen zu können**
Selbiges wie beim beobachteten Verhalten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Ist das Problem noch existent?

**Comment by Chrinis007** [comment]
Nicht mehr vorgekommen
