### ISSUE TITLE
Funkgerät Bug

### ISSUE THREAD

**Issue by Chrinis007** [mexyn/statev_v2_issues#469]
**Character Name**
Christian_Maier

**Zeitpunkt (Datum / Uhrzeit)**
Seit V2

**Beobachtetes Verhalten**
Wenn während dem funken ein Anruf ankommt und du dann aufhörst zu funken und rangehst und danach auflegst und weiter funken willst gibt es keine Animation mehr und es kommt kein Ton an

**Erwartetes Verhalten**
Nach dem Auflegen des Telefonats weiter funken können und nicht funk channel ausschalten und wieder aktivieren

**Schritte um den Fehler nachvollziehen zu können**
Funken; Anruf bekommen; Annehmen; Auflegen; Weiterfunken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Chrinis007** [comment]
?

**Comment by its4l3x** [comment]
sollte behoben sein.
