### ISSUE TITLE
Flatbed zu klein für LKW Schleppen.

### ISSUE THREAD

**Issue by Shirobaka** [mexyn/statev_v2_issues#470]
**Character Name**
Shigekuni Yamamoto

**Zeitpunkt (Datum / Uhrzeit)**
24.11.2020 09:20

**Beobachtetes Verhalten**
Der Flatbed ist zu klein um LKWs abschleppen zu können, lässt sich zwar aufladen, sieht aber äußerst unschön aus.

**Erwartetes Verhalten**
Ich denke es sollte ein weiteres Schleppfahrzeug für LKWs eingeführt werden, der Flatbed ist eigentlich nur für PKWs geeignet...

**Optional: Video / Bilder des Fehlers**
![jXbcJNy](https://user-images.githubusercontent.com/8634317/100067813-006aa480-2e37-11eb-918b-27e5a89234df.jpg)

**Comment by DonVitoDiangelo** [comment]
aktuell nicht möglich, da die normalen Schlepper noch zu crashes führen können.

**Comment by Shirobaka** [comment]
> 
> 
> aktuell nicht möglich, da die normalen Schlepper noch zu crashes führen können.

Gibts aktuell ne alternative Möglichkeit um einen LKW zur Werkstatt zu schaffen? Oder muss das Fahrzeug so wie oben auf dem Screenshot dann transportiert werden?

**Comment by DonVitoDiangelo** [comment]
nein, der oiltanker wird blacklisted für den flatbed. Repairkit und ab zur Werkstatt. geht aktuell nicht anders
