### ISSUE TITLE
Motor ist wieder repariert nach einem Serverneustart

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#471]
**Character Name**
Paul Humpert

**Zeitpunkt (Datum / Uhrzeit)**
23.11.2020 / 14:02

**Beobachtetes Verhalten**
Nach dem Serverneustart werden Autos, die zuvor beschädigt waren oder bei welchem die Motorkontrollleuchte gelb war, wieder automatisch repariert.

**Erwartetes Verhalten**
Fahrzeuge sollten weiterhin beschädigt bleiben bzw. die Motorkontrollleuchte sollte weiterhin gelb leuchten.

**Schritte um den Fehler nachvollziehen zu können**
- Ein Fahrzeug so beschädigen, dass der Motor gelb leuchtet
- Nach Serverneustart erneut ins Fahrzeug setzen und Motorleuchte überprüfen

**Comment by JulianMa** [comment]
fixed durch alt:V
