### ISSUE TITLE
Fahrzeuge teleportieren sich zurück

### ISSUE THREAD

**Issue by DettmarDettmers** [mexyn/statev_v2_issues#472]
Manchmal teleportieren sich meine Fahrzeuge "unkontrolliert" zurück. Ich habe zwei Fahrzeuge auf Fläche A stehen. Fahre mit Fahrzeug X dann auf Fläche B. Werde von einem Freund dann von B wieder nach A gefahren um Fahrzeug Y zu holen und wenn ich dann wieder auf Fläche B angekommen bin, steht das Fahrzeug X wieder auf A. Klingt komplizierter als es ist, aber ist schon 2-3 mal passiert und ich hab keinen Hinweis darauf, warum es passiert, weil ich beide Fahrzeuge ja aktiv benutzt habe und die nicht eingeparkt waren.

**Comment by r3sist3nt** [comment]
Ja, ist bekannt und gibt auch schon ein ticket dazu : #400

**Comment by r3sist3nt** [comment]
Bitte alle Hinweise darauf hier rein schreiben #400
