### ISSUE TITLE
Kein Einreisedatum auf Personalausweis

### ISSUE THREAD

**Issue by Opsizexe** [mexyn/statev_v2_issues#473]
**Ed_Prudhomme**

**Beobachtetes Verhalten**
Kein Einreisedatum auf Personalausweis einfach nur leeres Feld

**Erwartetes Verhalten**
Korrektes Einreisedatum 

**Schritte um den Fehler nachvollziehen zu können**
Ich habe damals vor 2 Jahren auf den Server angefangen zu spielen und habe zu dieser Zeit glaube ich keinen Personalausweis beantragt. Jetzt seid 2 Tagen spiele ich wieder und habe einen Personalausweis beantragt und denke daher kommt der Fehler.

**Comment by its4l3x** [comment]
fixed. Next Update
