### ISSUE TITLE
Char friert immer kurz ein / Abbau Felder Kartoffeln/Gurken/Salat/Kürbis

### ISSUE THREAD

**Issue by RomanSpielberg** [mexyn/statev_v2_issues#474]
Roman_Spielberg

24.11.2020 10:07Uhr

Nachdem das Fenster für die Entnahme erscheint, man die Sachen in seine Tasche tut und das Fenster schließt, bleibt der Char noch ca. 1-2Sekunden "eingefroren". Vermutlich läuft die Animation noch, obwohl der Zeitbalken lange weg ist.

Das man, wie bei allen anderen Feldern, unmittelbar nachdem man das Fenster geschlossen hat, weiterlaufen kann.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Lube08** [comment]
kann ich vollkommen bestätigen. Die Fähigkeit schneller abzubauen macht auf den genannten Feldern schon keinen Sinn mehr, weil die Animation länger dauert als der Abbauprozess. evtl gibt es da ne schnellere Animation?

**Comment by RomanSpielberg** [comment]
Noch als Ergänzung, wenn man mit seinem Skill dann nur noch 95% der Zeit benötigt, hilft dies nicht, da die Animation genauso lange wie bei 100% läuft + die 1-2Sek.

**Comment by r3sist3nt** [comment]
Wird wenn möglich zum nächsten Update behoben

**Comment by Lube08** [comment]
Problem besteht immer noch, obwohl es bei den fixes steht ^^

**Comment by RomanSpielberg** [comment]
Das gleiche Problem ist beim Ocker Feld, hier bitte auch noch beheben.

**Comment by LukiiTime1806** [comment]
Kann ich auch noch bestätigen

**Comment by RomanSpielberg** [comment]
Problem besteht weiterhin (30.11.2020 13:!1Uhr): Kürbisfeld

**Comment by DonVitoDiangelo** [comment]
Bei Beendung des Vorgangs wird die End-Animation des Scenarios abgespielt. Ihr spart trotzdem Zeit, da es ja früher abgebrochen wird. Hier muss zwischen "Scenarios" und "normalen Animationen" unterschieden werden.
