### ISSUE TITLE
Fehlerhafte Produktion Pflaster

### ISSUE THREAD

**Issue by sempre88** [mexyn/statev_v2_issues#475]
**Character Name**
Benny_Holmes
**Zeitpunkt (Datum / Uhrzeit)**
23.11.2020 19 Uhr
**Beobachtetes Verhalten**
Zur Herstellung von Pflaster in der Fertigung werden entpackte Kompressen benötigt.

**Erwartetes Verhalten**
Pflaster sollten verpackte Kompressen benötigen oder Kompressen sollten ausgepackt werden können

**Schritte um den Fehler nachvollziehen zu können**
siehe Produktion Pflaster in der Fertigung

**Comment by DrGrizzlY17** [comment]
So gewollt
