### ISSUE TITLE
Tieflader: Baumstämme abholzen im Wald noch nicht möglich

### ISSUE THREAD

**Issue by ZacCooperr** [mexyn/statev_v2_issues#476]
**Zeitpunkt (Datum / Uhrzeit)**
24.11.2020 11:30 Uhr

**Beobachtetes Verhalten**
Nachdem soweit alles vom #427 funktioniert, habe ich es heute noch einmal mit den Baumstämmen versucht. Das Laden von Baumstämmen aus einem Lager ist prinzipiell möglich, jedoch an der Arbeitsstätte Wald können die Baumstämme nicht abgeholzt und in den Tieflader gelagert werden: Meldung: Die Ressource kann nur in den folgenden Fahrzeugen gelagert werden: guardian, picador, ratloader2...

**Erwartetes Verhalten**
Da aus einem Lager prinzipiell Baumstämme in den Tieflader gelagert werden können s.Bild. würde ich nun erwarten, dass auch das abholzen am Wald hiermit funktioniert. Wahrscheinlich fehlt hier noch das Fahrzeug: Tieflader 

**Schritte um den Fehler nachvollziehen zu können**
1. Geprüft ob Baumstämme überhaupt in eine Tieflader Achse gelagert werden können: Ja
2. Zum Wald gefahren und versucht die Ressource: Baumstämme abzuholzen: Nicht möglich (s. Bild)

**Optional: Video / Bilder des Fehlers**
![Meldung_Fahrzeuge](https://user-images.githubusercontent.com/74767269/100083647-028a2e80-2e4a-11eb-8edd-4ea24ccda738.JPG)
![Meldung_Fahrzeuge1](https://user-images.githubusercontent.com/74767269/100083676-09b13c80-2e4a-11eb-8a97-829f6632934e.JPG)

**Comment by DonVitoDiangelo** [comment]
next update
