### ISSUE TITLE
Kleidungsstück "[M] Schwarzes Sakko schmal offen" zeigt "Risse" an den Ärmeln 

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#477]
**Character Name**
Paul Humpert

**Zeitpunkt (Datum / Uhrzeit)**
24.11.2020 / 11:49

**Beobachtetes Verhalten**
Das oben genannte Kleidungsstück ist an den Ärmeln verbuggt, sodass man Haut erkennen kann.

**Erwartetes Verhalten**
Das Sakko sollte vollkommen geschlossen sein.

**Schritte um den Fehler nachvollziehen zu können**
- Sakko kaufen
- Sakko mit Hemd untendrunter anziehen
- Kleidung überprüfen
![Bug](https://user-images.githubusercontent.com/74912696/100084745-6f51f880-2e4b-11eb-9f4d-b7a19fc8a645.PNG)

**Comment by r3sist3nt** [comment]
Du musst den passenden Torso im Kleidungsmenü auswählen.
