### ISSUE TITLE
AltV eine Ressource kann nicht heruntergeladen werden.

### ISSUE THREAD

**Issue by Yuna-Roads** [mexyn/statev_v2_issues#478]
**Yuna Roads**

Yuna Roads - Aber ich komme dann nicht einmal in den Log-In.
**Zeitpunkt (Datum / Uhrzeit)**

Seit gestern IMMER wenn es ein Update gab & ich es herunterladen möchte.
**Beobachtetes Verhalten**

Es kommt ein Update, ich Starte AltV & möchte es downloaden & dann kommt die Fehlermeldung das eine Ressource nicht heruntergeladen werden kann. Zusätzlich habe ich eine Textdatei im Altv ordner gefunden, wo ein Fehlertext drin steht, immer wenn ich nicht selber downloaden kann. Ich füge die mal mit ein: [1124/011011.506:ERROR:widevine_loader.cc(383)] Widevine CDM registration failed; Missing file E:\AltV State\cef\widevine\widevinecdm.dll <- Konnte nur beobachten das die auftaucht, in der datei Logs & dann textdatei cef, wenn ich versuche nach einem Update zu downloaden.
**Erwartetes Verhalten**

Das es problemlos downloadet & ich spielen kann.
**Schritte um den Fehler nachvollziehen zu können**

Ich habe keine Ahnung..

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://pic.statev.de/image/altv-fehler.GgYlD

Im Support konnte man mir da aktuell nur helfen, indem mir jemand seine aktuellen cache dateien zur verfügung gestellt hat. 
Danke für eure Hilfe & ich hoffe wir finden eine Lösung.

**Comment by DonVitoDiangelo** [comment]
Am besten mal den Inhalt des "cache" Ordners im altV Installationsordner löschen und alles neu laden.

**Comment by Yuna-Roads** [comment]
@DonVitoDiangelo 

Haben wir schon probiert, selbst das klappt nicht, da kommt die selbe Fehlermeldung.

**Comment by DonVitoDiangelo** [comment]
Bitte im Support melden und dir dort weiterhelfen lassen.
