### ISSUE TITLE
Portale am Roadhouse Diner

### ISSUE THREAD

**Issue by Knippsa** [mexyn/statev_v2_issues#481]
**Kalle_Knutsen**

**Zeitpunkt (Datum / Uhrzeit)**
24.11.2020 um 12:55 Uhr

**Beobachtetes Verhalten**
Es ist möglich in die Zimmer des Gebäudes rechts neben dem Roadhouse Diner zu gehen. Man fällt daraufhin in die Tiefe und spawnt zufällig in der nähe des Diners, je nachdem welche Tür man durchschreitet.

**Erwartetes Verhalten**
Türen sollten nicht begehbar sein

**Schritte um den Fehler nachvollziehen zu können**
Einfach mal durchgehen :)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
gta issue
