### ISSUE TITLE
Fahrzeuge Jonny Decker

### ISSUE THREAD

**Issue by JonnyDeckert** [mexyn/statev_v2_issues#482]
**Character Name**
    Jonny Decker

**Zeitpunkt (Datum / Uhrzeit)**
20.11.20 Beginn bei V2

**Beobachtetes Verhalten**
Meine fahrzeuge stehen in der Brouge Ave.17

**Erwartetes Verhalten**
Sie solten in der Brouge Ave. 19 stehen

**Schritte um den Fehler nachvollziehen zu können**
Umstellung auf V2

Es handelt sich um folgende fahrzeuge : Declasse Burrito/159 PS (NICE01), Albany Buccaneer/150PS (CLASSICX),
 Declasse Rhapsody/75PS (500PS), Ubermacht Rebla GTS/234PS (NICE28), Annis Hellion/135PS (NICE 4) 
*Kennzeichen in klammern (.......)

![Jonny Decker](https://user-images.githubusercontent.com/74964478/100089070-6401cb80-2e51-11eb-9687-d46988e8762b.jpg)

![Jonny Decker 1](https://user-images.githubusercontent.com/74964478/100091218-9eb93300-2e54-11eb-89ca-0dccb1dc97bf.jpg)

![Jonny Decker2](https://user-images.githubusercontent.com/74964478/100091239-a4af1400-2e54-11eb-974a-c8564d6d33af.jpg)

**Comment by r3sist3nt** [comment]
Äh, ich weiß gerade nicht genau was hier kaputt sein soll.
Warum meinst du denn, dass deine Fahrzeuge überhaupt in Brouge Ave. 19 stehen sollten?

**Comment by JonnyDeckert** [comment]
weil da mein haus ist mit Garage 
![Unbenannt](https://user-images.githubusercontent.com/74964478/100092468-63b7ff00-2e56-11eb-8e79-5fe948023dfc.jpg)

**Comment by JonnyDeckert** [comment]
auf den ersten Bild sieht man das die Enduro die ich vorhin eingepackt habe richtig steht ,und auf die Brouge Ave.17 habe ich kein zugriff da es nen ganz anderes Haus ist

**Comment by JonnyDeckert** [comment]
![h](https://user-images.githubusercontent.com/74964478/100329911-92f17c00-2fce-11eb-8d13-8e96aeb34106.png)
