### ISSUE TITLE
Sprach Visualisierung

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#483]
**Character Name**
Max_Broady

**Zeitpunkt (Datum / Uhrzeit)**
24.11.2020 - 13:00

**Beobachtetes Verhalten**
Die Sprachvisualisierung für Normales Reden und Schreien ist nicht ganz korrekt.
Wenn Spieler sich in dem "Dome" befinden, können sie einen dennoch nicht hören.
Erst wenn man näher dran geht.

**Erwartetes Verhalten**
Das Alle innerhalb des angezeigten Dome einen hören können.

**Schritte um den Fehler nachvollziehen zu können**
Gewisse entfernung zum Spieler aufbauen und dome checken.
Dann sprechen und schauen ob die Person einen hört.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Auf beiden Bildern kann mich mein gegenüber nicht hören.
![20201124125937_1](https://user-images.githubusercontent.com/70150887/100091657-328aff00-2e55-11eb-8126-cd931ee15e29.jpg)

![20201124125843_1](https://user-images.githubusercontent.com/70150887/100091653-31f26880-2e55-11eb-9e4c-0acb6610b1b2.jpg)

**Comment by TheBroady** [comment]
Grün (Flüstern) klappt soweit.

**Comment by tastydev** [comment]
Das soll nur ein ungefährer Indikator sein. Kein 100%er.
