### ISSUE TITLE
Bug beim Sitzen mit der Animation "Sitzen (Donut essen)" und "Sitzen (Trinken)" im Freizeitraum des MRPD

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#484]
**Character Name**
Paul Humpert

**Zeitpunkt (Datum / Uhrzeit)**
24.11.2020 / 12:57

**Beobachtetes Verhalten**
Wenn man sich im Freizeitraum des MRPDs hinsetzt mit der Animation "Sitzen Donut essen" oder "Sitzen Trinken", sieht man alles nur aus der Perspektive seines Gesäß. Die anderen Animationen funktionieren ganz normal.
![Bug](https://user-images.githubusercontent.com/74912696/100092128-df657c00-2e55-11eb-9d50-38a0c18ebd39.PNG)

**Erwartetes Verhalten**
Man sollte alles aus der normalen Perspektive sehen können.

**Schritte um den Fehler nachvollziehen zu können**
- Im MRPD den Freizeitraum betreten (von der Umkleide aus nach oben in dem Raum mit dem Billard Tisch)
- Einen der vielen Sitzplätze auswählen und sich darauf niederlassen

**Comment by DonVitoDiangelo** [comment]
later update
