### ISSUE TITLE
Verpackte Kompressen nicht entpackbar

### ISSUE THREAD

**Issue by SandyLive89** [mexyn/statev_v2_issues#485]
Charaktername: Sandy_Miller

**Beobachtetes Verhalten**
Mann kann die Verpackten Kompresse nicht mehr im 24/7 entpacken. War auch schon in der LSMD Aphoteke schaun ob man es dort kann aber da geht es auch nicht. Solange ich diese nicht entpacken kann , kann ich auch keine Pflaster herstellen für das LSMD

**Erwartetes Verhalten**
Das man sie wieder im 24/7 entpacken kann

**Comment by DonVitoDiangelo** [comment]
next updat eadded
