### ISSUE TITLE
Dinka Double T (Race) 122 PS kann nicht ausgepackt werden.

### ISSUE THREAD

**Issue by Naaki6** [mexyn/statev_v2_issues#486]
**Character Name**

Owen West
**Zeitpunkt (Datum / Uhrzeit)**

24.11.2020 14:30
**Beobachtetes Verhalten**

Wenn man an den auspack punkt im Autohaus geht passiert nichts. Gleiche Problem wie mit der Manchez vor ein paar Tagen.
**Erwartetes Verhalten**

Auto sollte ausgepackt werden können.
**Schritte um den Fehler nachvollziehen zu können**

Double T im Lager im Autohaus und dann versuchen auszupacken.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
next update implemented
