### ISSUE TITLE
Laptop und Mischpult fallen durch den Tisch nachdem Hausbesuch.

### ISSUE THREAD

**Issue by RoyMckellar** [mexyn/statev_v2_issues#487]
**Roy_Mckellar**

22.11.2020 / 12:00 Uhr

**Beobachtetes Verhalten**
Ich stelle einen Tisch auf und einen Laptop und Mischpult oben drauf.
Ich betrete meine Wohnung und gehe wider raus.
Danach ist der Laptop und das Mischpult unterm Tisch am Boden.

**Erwartetes Verhalten**
Laptop und Mischpult sollten weiter auf dem Tisch stehen.

**Schritte um den Fehler nachvollziehen zu können**
Ich stelle einen Tisch auf und einen Laptop und Mischpult oben drauf.
Ich betrete meine Wohnung und gehe wider raus.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Leider nicht anders möglich aktuell.
