### ISSUE TITLE
[M] Schwarze Turnschuhe

### ISSUE THREAD

**Issue by LukasObrien** [mexyn/statev_v2_issues#488]
**Lukas Obrien**

**Zeitpunkt (Datum / Uhrzeit)**

24.11.2020/16:00

**Beobachtetes Verhalten**

Fersen schauen bei den Schuhen hinaus

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![20201124162216_1](https://user-images.githubusercontent.com/74976097/100114198-75f36680-2e71-11eb-8bd3-350fe31adce7.jpg)

**Comment by LukasObrien** [comment]
Die fersen schauen bei den Turnschuhen hinaus.

**Comment by Enemyaa** [comment]
Danke für die Schuhe.

**Comment by Enemyaa** [comment]
Danke für die Info!
