### ISSUE TITLE
Verbrauch von Make-Up-Material

### ISSUE THREAD

**Issue by CaleighRhodes** [mexyn/statev_v2_issues#489]
**Caleigh_Rhodes**

**Zeitpunkt (Datum / Uhrzeit)**
24.11.2020 - 16:00 Uhr

**Beobachtetes Verhalten**
Beim Schminken im Friseurstudio verbrauchen sich Kajalstift und Lipbalm jeweils mit einer Nutzung

**Erwartetes Verhalten**
Mehrere Nutzungen möglich, Bonita Basiscreme bspw. kann auch mindestens 4 Mal genutzt werden - ansonsten wird Schminken einfach weit zu teuer und weder für den Kunden bezahlbar, noch für den Friseur rentabel.

**Schritte um den Fehler nachvollziehen zu können**
Make-Up im Friseurstudio auswählen, bei dem Kajalstift und LipBalm benutzt werden müssen

**Comment by Enemyaa** [comment]
Alle Materialien haben bereits die selbe Chance verbraucht zu werden.
