### ISSUE TITLE
Klettermine benutzbar ohne Lizenz dafür

### ISSUE THREAD

**Issue by mxRde** [mexyn/statev_v2_issues#49]
**Zeitpunkt (Datum / Uhrzeit)**

Jederzeit.

**Beobachtetes Verhalten**

Klettermine lässt sich ohne Kletterlizenz nutzen. Zudem fehlt der NPC für die Lizenzen.

**Erwartetes Verhalten**

Nur Benutzung der Klettermine mit Kletterlizenz

**Schritte um den Fehler nachvollziehen zu können**

Tür zu Klettermine benutzen ohne Kletterlizenz.

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Solved.
