### ISSUE TITLE
Fehler mit der Trage

### ISSUE THREAD

**Issue by Chrinis007** [mexyn/statev_v2_issues#490]
**Character Name**
Personal des LSMD

**Zeitpunkt (Datum / Uhrzeit)**
Seit V2

**Beobachtetes Verhalten**
Sollte man einen Patienten auf die Trage legen in einem Innenraum kann dieser nicht über den Teleporter nach draußen

**Erwartetes Verhalten**
Sollte den Marker nutzen können

**Schritte um den Fehler nachvollziehen zu können**
Bewusstlose Person stabilisieren und auf Trage legen und nach draußen gehen aus ner Werkstatt

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Korrekt. Innerhalb eines Interiors (Port Marker) mit Defi arbeiten.
