### ISSUE TITLE
Person die bei Bewusstsein ist in den RTW einladen und auf Trage legen funktioniert nicht

### ISSUE THREAD

**Issue by Chrinis007** [mexyn/statev_v2_issues#491]
**Character Name**
Christian_Maier

**Zeitpunkt (Datum / Uhrzeit)**
Seit V2

**Beobachtetes Verhalten**
Man kann keine Personen die bei Bewusstsein sind also laufen können auf die Trage heben; außerdem kann man keine Personen die nahe am RTW stehen per X Menü einladen was wieder gut wäre wie bei V1

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Das System mit der Trage ist ausschließlich für Bewusstlose Personen gedacht. Daher gewollt und kein Bug

**Comment by Chrinis007** [comment]
Und dass man Leute wieder übers X Menü hinten in den RTW packen kann?

**Comment by Chrinis007** [comment]
@its4l3x

**Comment by DrGrizzlY17** [comment]
Leute die laufen können, brauchst du nicht übers System einladen. Die können selber sich rein setzen.

**Comment by its4l3x** [comment]
Nein auch nicht. @DrGrizzlY17 hat Recht und die sollen sich am besten selber reinsetzen.
