### ISSUE TITLE
Auftrags-Export mit Trailer Large nicht möglich.

### ISSUE THREAD

**Issue by SternChef** [mexyn/statev_v2_issues#494]
**Character Name**
Stella_Sanchez

**Zeitpunkt (Datum / Uhrzeit)**
24.11.20 - 18:20 Uhr

**Beobachtetes Verhalten**
Die Abgabe einer Auftrags-Auktion mittels einer Trailer Large (Achse) war nicht möglich.
Es erschienen 2 Fehlermeldungen. 

**Erwartetes Verhalten**
Anfahren an den Marker, Kofferraum der Trailer Large öffnen, beim NPC auf den Auftrag klicken,
auf Meldung warten das der Auftrag erfolgreich abgegeben wurde.

**Schritte um den Fehler nachvollziehen zu können**
Mit Trailer Large an den Auftrags-Export fahren.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot_278](https://user-images.githubusercontent.com/74982338/100131371-3bdf9000-2e84-11eb-89cf-74c3c57bee05.png)

**Comment by tastydev** [comment]
Achse aufgeschlossen ? (Kupplung)

**Comment by SternChef** [comment]
Ja, Auflieger war aufgeschlossen, Schlüssel einmal in der Schlüsseltaschen und versucht. Dann Schlüssel im Inventar und auch probiert. Ging beide male nicht

**Comment by SternChef** [comment]
Nach langem vor und zurück fahren habe ich jetzt den genauen Punkt zum entladen gefunden.
Genau mittig zwischen den Stützen.  Kann man den Radius vergrößern; damit es leichter wird?

![Screenshot_279](https://user-images.githubusercontent.com/74982338/100230073-806f3800-2f25-11eb-8080-a777b9d36f66.png)

**Comment by tastydev** [comment]
Sollte mit nächstem Update einfacher sein die Distanz wurde verdoppelt
