### ISSUE TITLE
Wechsel von Fahrzeugverleih in öffentlicher Parkplatz

### ISSUE THREAD

**Issue by croveans** [mexyn/statev_v2_issues#495]
**Character Name**
Marty Taylor

**Zeitpunkt (Datum / Uhrzeit)**
24.11.2020 / 18:51

**Beobachtetes Verhalten**
Durch den Wegfall von den mehrfach Parkplätzen im Haus (Vorher hatte jeder Untermieter eigene Garagenplätze, sodass in Häusern zum Teil bis zu 50 Autos standen) ist die Parksituation am Westhighway deutlich schlechter geworden. Als Verbesserung würde ich vorschlagen, dass die Fahrzeugvermietung am Westhighway in einen öffentlichen Parkplatz gewandelt wird. Dann würden auch eingeparkte Fahrzeuge nicht auf der 

**Erwartetes Verhalten**
Durch Reduktion von Parkplätzen im Haus muss mehr öffentlicher Parkraum geschaffen werden. Notfalls vielleicht daraus eine Garage & öffentlichen Fahrzeugverleih zusammen machen? Quasi beide Funktionen über einen NPC möglich machen.

Geht um Fahrzeugverleih 9

![Fahrzeugverleih_Westhighway](https://user-images.githubusercontent.com/40040984/100133426-08eacb80-2e87-11eb-955d-62184344b657.png)

**Comment by DonVitoDiangelo** [comment]
Fahrzeugvermietung bleibt, aber es wird eine neue Garage kommen.

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/509
