### ISSUE TITLE
Hotel, keine Werbung schalten!

### ISSUE THREAD

**Issue by Chandena** [mexyn/statev_v2_issues#497]
Chandena_Mascarponi

22.11.20/?

**Beobachtetes Verhalten**
Ich bin Geschäftsführerin eines Hotels, kann aber keine Werbung schalten. Support hat mich hier hin geschickt.

**Erwartetes Verhalten**
Werbung schalten.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by tastydev** [comment]
Verwendungszeck -> Eigenwerbung

**Comment by DonVitoDiangelo** [comment]
Kannst du schlicht keine erstellen oder ist die Meldung erfolgreich und du siehst nur keine?

**Comment by Chandena** [comment]
Also ich kann bei Verwendungszweck das Hotel nicht angeben. Da es dort nicht steht.

**Comment by Chandena** [comment]
Bei Eigenwerbung kann ich ja kein GPS angeben.

Am Di., 24. Nov. 2020 um 19:46 Uhr schrieb DonVitoDiangelo <
notifications@github.com>:

**Comment by its4l3x** [comment]
Immer noch beständig?

**Comment by Chandena** [comment]
jap

**Comment by its4l3x** [comment]
Okay ich brauche dann bitte eine Detail Beschreibung von deinem Problem.

**Comment by Chandena** [comment]
Also ich bin Geschäftsführer (mit allen rechten) eines Hotels und möchte gerne übers Tablett Werbung schalten..das Problem an der Sache ist, wenn ich unter "Verwendungszweck" das Hotel auswählen will, dann wird es dort nicht angezeigt. Und da ich mit GPS Anzeige dies machen will, bräuchte ich das natürlich.  "Verwendungszweck -----> Eigenwerbung" würde da nichts bringen.

**Comment by KingMarcel** [comment]
Getestet, geht mitlerweile.
