### ISSUE TITLE
Ausbleibende Gehaltszahlung

### ISSUE THREAD

**Issue by Solomonetix** [mexyn/statev_v2_issues#498]
Curtis_Boone

Ab Release V2

**Beobachtetes Verhalten**
ausbleibende Gehaltszahlung. Anstellung in einem 24/7

**Erwartetes Verhalten**
Gehalt $xxx sollte jede Stunde überwießen werden.
PD & MD Gehaltszahlungen scheinen ja zu funktionieren. Nur der kleine Angestellte nicht?

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Daniel-Meister-508** [comment]
Ist bei Helmuts Werkstatt auch so das kein Gehalt an Mitarbeiter rausgehen wenn man eingestempelt.

**Comment by PlayInc89** [comment]
Im Klamottenladen geht die Gehaltsauszahlung auch nicht

**Comment by Eve-Noxito** [comment]
Grüße von Sludgie Customs, auch bei und gehen keine Gehälter raus, habe auch schon versucht die gehälter auf 0 zu setzen und dann wieder normal einzustellen, hat leider nicht geholfen

**Comment by eiksch** [comment]
#640

**Comment by its4l3x** [comment]
Fixed seit dem letzten Update.
