### ISSUE TITLE
Stühle in der Handelskammer nicht fest montiert

### ISSUE THREAD

**Issue by KingMarcel** [mexyn/statev_v2_issues#499]
**Character Name**
Tim_Schmit

**Zeitpunkt (Datum / Uhrzeit)**
Permanent

**Beobachtetes Verhalten**
Alle Bürostühle in der Handelskammer sind nicht fest montiert.

**Erwartetes Verhalten**
Die Bürostühle sollten fest montiert sein, bzw. nicht bei jeder kleinen Berührung umkippen.

**Schritte um den Fehler nachvollziehen zu können**
Gegen einen Stuhl laufen :D

**Optional: Video / Bilder des Fehlers**
z.b.
https://prnt.sc/vpbda8
http://prntscr.com/vpbysl

**Comment by its4l3x** [comment]
Kein Bug. Stühle kommen von GTA. Ist in jedem Inv so.
