### ISSUE TITLE
Inventar überfüllt wenn man alles einsammelt

### ISSUE THREAD

**Issue by powerswissi** [mexyn/statev_v2_issues#50]
**Zeitpunkt (Datum / Uhrzeit)**

25,8,2020 23,18 Uhr

**Beobachtetes Verhalten**

Wenn man alles abbaut was mach aufgestellt hat kann man mit über 50kg rumrennen. Wahrscheinlich sogar mehr 

**Erwartetes Verhalten**

Maximal bis 15kg so wie das Inventar bezeichnet ist 

**Schritte um den Fehler nachvollziehen zu können**

Einige Sachen aufstellen. Und Mit dem PUNKT einsammeln 

**Optional: Video / Bilder des Fehlers**

![Screenshot_500](https://user-images.githubusercontent.com/70152806/91228997-73c22480-e729-11ea-8576-69e934eb8704.png)

**Comment by tastydev** [comment]
@powerswissi Kein bug es ist an manchen Stellen im servercode gewollt das items bei zu wenig platz akzeptiert werden, um Fehler zu verhindern. Da es sich hier um Items handelt die vom Server in das Spielerinventar gegeben werden ist das okay und wird es noch an anderen Stellen geben die gewollt sind.
