### ISSUE TITLE
Weedtisch Überprüfung

### ISSUE THREAD

**Issue by eldoodaks** [mexyn/statev_v2_issues#500]
Darryl Bradley

**Zeitpunkt (Datum / Uhrzeit)**
den ganzen 24.11.2020

**Beobachtetes Verhalten**
Nix beobachtet da nix geht. Bitte überprüfen ob alle Komponenten herstellbar sind! Bitte :(

**Erwartetes Verhalten**
Joints drehen können.

**Comment by tastydev** [comment]
funktioniert :D

**Comment by eldoodaks** [comment]
Ich kriege langsam nen krampf

**Comment by tastydev** [comment]
so soll das sein
