### ISSUE TITLE
Kündigung des Hotelzimmers ohne bestehende Voraussetzungen

### ISSUE THREAD

**Issue by AmschelGoldblum** [mexyn/statev_v2_issues#501]
**Amschel_Goldblum**

**Zeitpunkt (24.11.2020 / 16:47)**

**Das Hotelzimmer (PillboxHill_Flat_14 - Klatschiresort) wurde gekündigt, obgleich das Hauptkonto mit ca. 92.000 $ gedeckt und der letzte Onlinezeitpunkt vor 2-3 Tagen war.**

**Eine Kündigung des Hotelzimmers sollte nicht möglich sein.**

**Mir wurde lediglich IC eine Mail zugeschickt.**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Kerrders** [comment]
Grüße, Mitbesitzer vom Hotel hier, deine letzte Miete hast du am 24.10 um 00:15 gezahlt und konntest somit gekickt werden. Es kann sein, dass du lange nicht online warst und dann einmalig kurz online warst (Weniger als 1 Stunde online) und somit keine Miete gezahlt hast. Hab das System mit dem Kicken schon getestet und scheint einwandfrei zu funktionieren.

**Comment by AmschelGoldblum** [comment]
Servus ... ja das mit der einen Stunde kann sein. Wußte nichts von der Stunde! Früher war das wohl anders. Ich gehe mal davon aus das somit die Containerwaren alle verloren sind?
