### ISSUE TITLE
Neue Bandanas müssen noch angepasst werden

### ISSUE THREAD

**Issue by CubeXLIVE** [mexyn/statev_v2_issues#502]
Patrick Nowak

**Zeitpunkt (Datum / Uhrzeit)**
aktuell

**Beobachtetes Verhalten**
Wie bei den alten Bandanas guckt bei mir sowohl die Nase als auch die Wangen raus.

**Erwartetes Verhalten**
So wie bei den alten, gefixten Bandanas, dass die Nase dann nicht mehr rausguckt

**Schritte um den Fehler nachvollziehen zu können**
Neues Bandana aufsetzen. Wahrscheinlich geht es nur bei bestimmten Gesichtsformen

**Optional: Video / Bilder des Fehlers**
https://prnt.sc/vpdffh

**Comment by DonVitoDiangelo** [comment]
Exakter hash/name dieses Bandanas?

**Comment by CubeXLIVE** [comment]
Der Name des Bandanas lautet "Rotes Paisley Bandana". Bei dem ist es an meinem Char aufgefallen aber ich bin mir fast sicher, dass es bei allen neuen Paisley Bandanas so ist
