### ISSUE TITLE
Verbuggter Bodhi

### ISSUE THREAD

**Issue by Daniel-Meister-508** [mexyn/statev_v2_issues#503]
**Daniel Meister**

**Zeitpunkt (24.11.2020 / 21:00)**

**Beobachtetes Verhalten**
Bodhi Taucht plötzlich auf und verschwindet immer wieder und beim Abschleppversuch ist er immer wieder weg gewesen und wenn man den Abschlepper fährt schwebt man in der Luft 

**Erwartetes Verhalten**

Das der Bodhi nicht vom Abschlepper runter Glitcht

**Optional: Video / Bilder des Fehlers**

https://youtu.be/7FuYEWfGusk

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/504

**Comment by JulianMa** [comment]
sollte fixed sein
