### ISSUE TITLE
MTL Flatbed nimmt im leeren Zustand automatisch Bodhi auf und Fliegt durch die Gegend

### ISSUE THREAD

**Issue by LautaroTesto** [mexyn/statev_v2_issues#504]
**Lautaro_Testo**

Lautaro Testo

**Zeitpunkt (Datum / Uhrzeit)**
21:15Uhr - 24.11.2020

**Beobachtetes Verhalten**
MTL Flatbed (Lackiert) nimmt im leeren Zustand Bodhi auf. Flatbed buggt durch

**Erwartetes Verhalten**
MTL Flatbed soll Fahrzeugeabschleppen ohne in die Luft zu buggen

**Schritte um den Fehler nachvollziehen zu können**
MTL Flatbed steht > es wird random ein Bodhi gespawnt auf dem Abschlepper > Man steigt ein und fliegt in die Luft und buggt rum

**Comment by JulianMa** [comment]
Fixed nach nächstem Update
