### ISSUE TITLE
Tasche lässt sich nicht 100% füllen

### ISSUE THREAD

**Issue by Felitschee** [mexyn/statev_v2_issues#505]
**Felix Ecal**

Felix Ecal

**Zeitpunkt (24.11.2020 / 22:13)**

**Beobachtetes Verhalten**

14,5kg Lithium in der Tasche, 15kg genau gehen nicht 

**Erwartetes Verhalten**

Tasche sollte sich komplett füllen lassen

**Schritte um den Fehler nachvollziehen zu können**

Tasche füllen und ausprobieren

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Bitte das Formular ausfüllen

**Comment by Felitschee** [comment]
*Edited*

**Comment by DonVitoDiangelo** [comment]
Aus technischen Gründen (gibt auch teils Kommastellen ala 1,000000003 ) passt das dann manchmal nicht genau.
Das ist aber so gewollt und schützt vor Abuse. Daher, damit muss man dann ab und an leben, sry.
