### ISSUE TITLE
Fahrzeuge abschleppen.

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#51]
**Zeitpunkt (Datum / Uhrzeit)**

23:45 25.08.2020
**Beobachtetes Verhalten**

Wenn man Beifahrer (ohne Schlüssel zum Tieflader) ist, kann man Autos die aufgeladen sind absatteln. Selbst während der Fahrt.
Wenn man nun als Fahrer aussteigt und versucht ein neues Auto aufzuladen klappt dies nicht. Erst muss der Beifahrer aussteigen.
**Erwartetes Verhalten**

Sollte nicht gehen. 
**Schritte um den Fehler nachvollziehen zu können**

1. Fahrer Fahrzeug aufsattlen
2. Beifahrer "X" Menu - Absatteln
3. Fahrer versucht neues Auto aufzusatteln.

**Comment by Kalumel** [comment]
**Zeitpunkt (Datum / Uhrzeit)**

siehe Oben:

**Beobachtetes Verhalten**

Man müsste Collisions überprüfen bevor man ein Auto abladen kann. Zur Zeit werden Fahrzeuge in Häuser etc. abgeladen
**Erwartetes Verhalten**
Sollten nicht abgeladen werden können.


Sollten nicht abgeladen werden können. ggf. Fehlermeldung. 

**Schritte um den Fehler nachvollziehen zu können**

1. Abladen
2. Warten und sehen wie es in nem Haus verschwindet.

**Comment by Kalumel** [comment]
Generell sollte die Abladefunktion nicht innerhalb des LKWs funktionieren.

**Comment by its4l3x** [comment]
Wie schon im Ts besprochen, nur das mit dem Beifahrer gefixed. Rest gewollt, oder nicht umsetzbar. Fixed mit dem nächsten Update.
