### ISSUE TITLE
Werkstatt Terminal crasht durch abbruch der Rechnung 

### ISSUE THREAD

**Issue by DrColgate** [mexyn/statev_v2_issues#512]
**Character Name**

Anton Mueller / Simon Milsa
**Zeitpunkt (Datum / Uhrzeit)**

ca 23:30 24.11.2020
**Beobachtetes Verhalten**

Die ausgestellte Rechnung habe ich als Kunde geschlossen, um eine neue ausgestellt zu bekommen.
Ein erneutes Tuning konnten wir nicht durchführen, da der Tuningplatz bereits belegt war. 
Werkstatt Horizon, Fahrzeug war GT63.

Haben noch versucht ein anderes Fahrzeug zu Tunen, ging aber auch nicht mehr.

**Erwartetes Verhalten**

Tuningplatz hätte nach abbruch der Rechnung wieder frei sein müssen
**Schritte um den Fehler nachvollziehen zu können**

In der Werkstatt Rechnung ausstellen lassen, aber nicht bezahlen, sondern das Feld schließen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by JulianMa** [comment]
Fixed nach nächstem Update.
