### ISSUE TITLE
Favortien Ordner löschen sich 

### ISSUE THREAD

**Issue by wichtTSV** [mexyn/statev_v2_issues#513]
**Character Name**
Tom Spider

**Zeitpunkt (Datum / Uhrzeit)**
25.11.2020 ca 19 - 23:25
**Beobachtetes Verhalten**
Ich habe mir ab ca. 19:30 neue Favoriten Ordner angelegt für die Animationen angelgt für die True Steps Tanzgruppe, habe mich ausgeloggt um ca 22:30 und dann ca 23:20 wieder eingeloggt und wollte meine Arme verschränken und sehe das alle Ordner leer sind.

**Erwartetes Verhalten**
Die Ordner sollten nach dem erstellen und nach dem Speichern alle noch vorhanden sein, so wie es bei anderen auch ist, die mit dabei waren.

**Schritte um den Fehler nachvollziehen zu können**
Paar eigene Ordner erstellen mit Animationen drinnen, und reloggen, vllt tritt der Fehler dann ja auch auf.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Nur ein Bild wie alle weg sind.
![jhb](https://user-images.githubusercontent.com/74994115/100162401-d3100c00-2eb3-11eb-900b-5c7e12e93604.PNG)

**Comment by DonVitoDiangelo** [comment]
Diese werden lokal bei dir abgelegt. hast du vllt. den "cache" Ordner im alt:V Ordner geleert?

**Comment by r3sist3nt** [comment]
Falls du deinen Cache nicht geleert haben solltest, brauche ich zur Fehleranalyse einmal deine .local_storage Datei: Diese findest du im cache Ordner von alt:V. Dort gibt es mindestens einen Unterordner, in dem die Dateien von StateV liegen. In diesem liegt auch die .local_storage Datei. Falls du mehrere Ordner haben solltest, dann ist der StateV Ordner der, in dem auch die Datei statev-rp.resource liegt.

**Comment by wichtTSV** [comment]
Habe zwei davon. Einmal vermutlich von eurem Launcher und vom Alt V launcher daher lade ich einfach beide hoch. Hatte Sie nicht gelöscht.
[local storage.zip](https://github.com/mexyn/statev_v2_issues/files/5597250/local.storage.zip)
[local storage.zip](https://github.com/mexyn/statev_v2_issues/files/5597253/local.storage.zip)

Sollten 2 verschiedene sein.

**Comment by wichtTSV** [comment]
Porblem ist nun auch bei 2 weiteren mit denen ich zusammen die Ordner erstellt hatte (da sie auch in der Tanz gruppe sind)

**Comment by DonVitoDiangelo** [comment]
Sollte das Problem wiederkehren, bitte erneut öffnen.
