### ISSUE TITLE
Glasgran. Produktion instant fertig

### ISSUE THREAD

**Issue by DrColgate** [mexyn/statev_v2_issues#514]
**Character Name**

Anton Mueller
**Zeitpunkt (Datum / Uhrzeit)**

24.11.2020 
**Beobachtetes Verhalten**

Ich stelle in der Gießerei (pfGroupAllRew_103) Glasgranulat her. Nach Produktionsstart öffne ich erneut den Computer. Dann liegt im Maschinenlager bereits das fertige Glasgranulat. 
**Erwartetes Verhalten**

Das ich erst das Glasgranulat im Maschinenlager haben dürfte, wenn die Produktion fertig ist.
**Schritte um den Fehler nachvollziehen zu können**

Glasgranulat herstellen, Produktionscomputer schließen und wieder öffnen. Dann zum Maschinenlager schauen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
1x geht relativ schnell. Daher hast du es dann auch schon fertig

**Comment by DrColgate** [comment]
nein das ist falsch! video lade ich gerade hoch

**Comment by DrColgate** [comment]
https://www.youtube.com/watch?v=w6djMIyv5cY&feature=youtu.be
