### ISSUE TITLE
Muschelohhringe + Herz-Layering Halskette werden nicht zeitgleich angezeigt

### ISSUE THREAD

**Issue by Nuuki900** [mexyn/statev_v2_issues#515]
Anuk Dehler

24.11.2020, 22:15 Uhr

Beim Anlegen der Kette [F][Neck] Silber-Goldene Herz-Layering Halskette und zeitgleich angelegten Muschelohrringen werden die Ohrringe nicht mehr angezeigt. Sobald man die Kette wieder "auszieht" werden die Ohrringe wieder angezeigt. Andersherum ist es genauso.

Ohrringe UND Kette werden zeitgleich angezeigt

Kette angelegt

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

https://youtu.be/IwndlovPY3M

**Comment by DonVitoDiangelo** [comment]
Kann nicht kombiniert werden. Falls ich falsch liege, korrigiere mich bitte @Enemyaa
