### ISSUE TITLE
Lippenstifttransparenz ändert sich nach Abschluss vom Make-Up für Augen

### ISSUE THREAD

**Issue by EmmaSvensson** [mexyn/statev_v2_issues#516]
**Character Name**
Emma_Svensson

**Zeitpunkt (Datum / Uhrzeit)**
25.11.2020 ca 2:00Uhr

**Beobachtetes Verhalten**
Es wurde im Frisörsalon über den Schminkstuhl ein Make-up (Augen) angelegt, die Kundin war zufrieden und der Vorgang startete. Als der (fürs schminken auch viel zu lange) prozess fertig war, hatte die Dame auf einmal knall rote Lippen, da sich die Transparenz ihres vorab schon aufgetragenen Lippenstiftes geändert hat. Das ist blöd für den Friseur und die Kundin.

**Erwartetes Verhalten**
Lippenstifttransparenz ändert sich nicht beim schminken von Augen

**Schritte um den Fehler nachvollziehen zu können**
s.o.

**Comment by its4l3x** [comment]
Fixed. Next Update.
