### ISSUE TITLE
Tuning Unterbodenbeleuchtung: Zu wenig Items verbraucht, fehlende Vorschau

### ISSUE THREAD

**Issue by ZirbelR** [mexyn/statev_v2_issues#519]
**Character Name**
Richie_Zirbel

**Zeitpunkt (Datum / Uhrzeit)**
25.11.2020

**Beobachtetes Verhalten**
Wenn man Unterbodenbeleuchtung in der Werkstatt tunt, werden (wie in V1 auch) 4 LED Unterbodenbeleuchtungen als benötigte Items angezeigt. Nach Abschluss des Tunings ist das Item nur 1x weniger im Lager, jedoch verfügt das Fahrzeugt über Unterbodenbeleuchtung an 4 Seiten. Außerdem gibt es keine Vorschau für die Unterbodenbeleuchtung, sprich man sieht die Farbe nicht obwohl der Motor läuft und die Beleuchtung aktiviert ist. Dies wurde an einem Fahrzeug beobachtet an dem vorher keine Unterbodenbeleuchtung verbaut war.

**Erwartetes Verhalten**
Wird ein Tuning durchgeführt so sollte auch die richtige Anzahl an Items verbraucht werden. Außerdem sollte eine Vorschau angezeigt werden.

**Schritte um den Fehler nachvollziehen zu können**
Unterbodenbeleuchtung tunen

**Comment by JulianMa** [comment]
fixed nach nächstem Update. Motor muss für die Vorschau allerdings eingeschaltet sein.
