### ISSUE TITLE
[Kleinigkeit] Gewichtsanzeige der Schwarzen Witze 

### ISSUE THREAD

**Issue by Tobse1904** [mexyn/statev_v2_issues#520]
**Character Name**
Harry Buktu

**Zeitpunkt (Datum / Uhrzeit)**
25.11.2020 / 5:22

**Beobachtetes Verhalten**
Gewicht von einer Schwarzen Witze wird nicht angezeigt im Inventar, das Gewicht einer Fledermaus hingegen schon.
kleinigkeiten aber dennoch mal gemeldet :)

**Erwartetes Verhalten**
Richtige Gewichtsanzeige 

**Schritte um den Fehler nachvollziehen zu können**
Schwarze Witze eingesammelt und in die Tasche sowie Rucksack gesteckt, wird bei beidem kein Gewicht angezeigt.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920 * 1080

**Optional: Video / Bilder des Fehlers**
![271590_20201125052018_1](https://user-images.githubusercontent.com/39304481/100183148-868df600-2ede-11eb-96c4-94abd28351f0.png)

**Comment by DonVitoDiangelo** [comment]
Gewicht wird korrekt angezeigt

**Comment by Tobse1904** [comment]
Dann hab ich echt zu wenig schlaf in letzter zeit.
Die fledermaus hat 0,05 und die witwe 0,01 - 0,05 wird angezeigt aber 0,01 nicht ?! Da bin ich verwirrt jetzt ^^
