### ISSUE TITLE
Blumenkästen

### ISSUE THREAD

**Issue by StateV2Marie** [mexyn/statev_v2_issues#521]
[https://pic.statev.de/image/GySIX](url) Hallo es geht um das bild was ich mit geschickt habe meine bitte is. ich wünschte mir das die netten mapper so lieb sind und mir rings rum ums gelände diese schönen blumen kübel hin stellen damit man nur durchs metal tor rein und raus kann wäre das vll möglich? weil ich kann nix anderes mehr dekoriren wenn ich die kübel hin gestellt hab a sieht es schöner aus und b wird man dann nich übern haufen gefahren aktuell is es sehr nackt und ich hab nur ein kübel hinten damit man keine 10/80 über mein hof fährt. würd aber gern rings rum machen damit ich auch noch unsere alte sitz ecke wieder aufbauen kann was ohne eure hilfe leider nich geht drum bitte ich euch mir da zu helfen... auf dem bild sehr ihr c.a wie ichs meine und mal ehrlich es schaut schöner aus wie die ollen reifenstapel....

**Comment by DonVitoDiangelo** [comment]
Abgelehnt.
