### ISSUE TITLE
Balken von Waffen Ablegen resetted sich mit ablegen einer zweiten Waffe

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#522]
**Character Name** Erwin_Dulach

**Zeitpunkt (Datum / Uhrzeit)** 24.11.2020 ~21:40

**Beobachtetes Verhalten** Zwar wird beim Ablegen der Waffen jetzt ein Fortschrittsbalken angezeit (Bugtracker dazu war #457 ) aber den kann man mit ablegen einer anderen Waffe überschreiben. So kann man mehrere Waffen schneller ablegen als warsch. gewollt.

**Erwartetes Verhalten** Inventar wird wie beim Waffen anlegen gefreezed, sodass man den Balken durchlaufen lassen muss, bevor man eine zweite Waffe ablegen kann.

**Schritte um den Fehler nachvollziehen zu können** Mehrere Waffenslots füllen -> Waffen schnell hintereinander von den Slots ins Inventar ziehen

**Optional: Video / Bilder des Fehlers** Könnte ich nachreichen falls benötigt.

**Comment by Chrinis007** [comment]
Immer noch
