### ISSUE TITLE
Flatbed (PD) nicht nutzbar für die Officer wegen fehlendem Schlüssel

### ISSUE THREAD

**Issue by DerHessenTyp** [mexyn/statev_v2_issues#524]
Andreas Jung

**Beobachtetes Verhalten**
Der Flatbed aus dem PD funktioniert leider nicht ohne den Schlüssel. Da wir im PD aber alle eine sogenannte Schlüsselkarte für alle Fahrzeuge haben ist somit für uns nicht möglich den Flatbed zu nutzen da wir eine Fehlermeldung bekommen: ,, Du besitzt keinen Schlüssel für den Abschlepper!" 

**Erwartetes Verhalten**
Das wir so wie bei allen anderen PD Fahrzeugen auch den Flatbed ohne Schlüssel nutzen können. Gerade wenn keine Werkstatt im Dienst ist und Fahrzeuge wild auf den Straßen rumstehen, ist das von Vorteil.

![PD Abschlepper nicht funktionsfähig](https://user-images.githubusercontent.com/70151958/100226465-156f3280-2f20-11eb-8a50-b857887d8045.jpg)

**Comment by ZirbelR** [comment]
Ähnliches Problem tritt bei meinem Flatbed auf, dieser ist auf die Werkstatt geschrieben und funktioniert ebenfalls ohne Schlüssel. In der Regel funktioniert das Abschleppen jedoch beim 2. oder 3. Versuch, sprich einfach nochmal probieren, dann gehts.

**Comment by DerHessenTyp** [comment]
Ja kann ich mittlerweile auch bestätigen. Hat sic erledig
