### ISSUE TITLE
Mützen mit aktueller Frisur nicht tragbar.

### ISSUE THREAD

**Issue by Naaki6** [mexyn/statev_v2_issues#525]
**Character Name**

Owen West
**Zeitpunkt (Datum / Uhrzeit)**

25.11.2020
**Beobachtetes Verhalten**

Mit den probierten Mützen: Bucket Hat, Danbanna, Snapback guckt die Frisur durch das Item durch.
**Erwartetes Verhalten**

Frisur guckt nicht durch. Evtl. kann man es setzten das wenn man eine Mütze trägt, das der Char eine Glatze für den Zeitraum hat?
**Schritte um den Fehler nachvollziehen zu können**

Frisur wie im Beispielbild nehmen und einen der verschiedenen Kopfbedeckungen anlegen.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![dfg](https://user-images.githubusercontent.com/74776926/100227807-05f0e900-2f22-11eb-82e1-ff0eaa4167e8.png)

**Comment by DonVitoDiangelo** [comment]
next update solved
