### ISSUE TITLE
Kofferraum bei Flatbed und Tieflader

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#526]
Es ist kaum möglich in den Kofferaum des Flatbeds und Tiefladers zu schauen.
Der Punkt ist nicht wie gehabt mittig gelegen das man mit dem Kofferraum agieren kann.
Mann muss den Punkt regelrecht suchen da er ziemlich klein zu sein scheint.

Daher bitte den Punkt mittig auf das Fahrzeug legen und den Radius zum bearbeiten vergrößern

**Comment by DonVitoDiangelo** [comment]
fixed next update

**Comment by Statev-Bonsai** [comment]
BTW, der ist doch **auch** gedacht für LKW´s zu abschleppen, aber irgendwie kann man sie nicht aufladen

**Comment by ZirbelR** [comment]
@Statev-Bonsai Dazu gab es gestern in den Patchnotes was:
[FIX] Öltanker kann nicht mehr auf den Flatbed geladen werden
Daher denke ich, dass das so beabsichtigt ist.

**Comment by Statev-Bonsai** [comment]
Das geht nicht um Flatbeds, sondern um Tieflader Achsen!!!

**Comment by DonVitoDiangelo** [comment]
Der Tieflader kann nicht als Abschlepper genutzt werden
