### ISSUE TITLE
Auto steht im Zaun

### ISSUE THREAD

**Issue by PsYke86** [mexyn/statev_v2_issues#527]
**Character Name**
Jack_Napyr

**Zeitpunkt (Datum / Uhrzeit)**
25.11.20 14:00

**Beobachtetes Verhalten**
Ein Burrito steht im Zaun

**Erwartetes Verhalten**
Burrito steht davor oder steht auf umgekippten Zaun.

**Schritte um den Fehler nachvollziehen zu können**
I dont know 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![Uploading 100231433...]

**Comment by DonVitoDiangelo** [comment]
alt:V rotation bug in "release" branch
