### ISSUE TITLE
Abends kleine Lags und ruckler

### ISSUE THREAD

**Issue by PsYke86** [mexyn/statev_v2_issues#528]
**jack_Napyr**

**immer abends ab 19:00**

**autos Laggen und das Spiel stockt immer mal wieder kurz zeitig bei Stabilen 60FPS**

**Keine Lags**

**abends ab 19:00/20:00 Uhr einloggen wenn der Server gut gefüllt ist und am Würfelpark rum fahren**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
wenn Probleme anhalten, einfach mal nen Video machen.  Kann so in dem Sinne nicht bestätigt werden.

**Comment by PsYke86** [comment]
https://youtu.be/D4gTwTK_pBI
https://youtu.be/FLNJtMynUEQ
