### ISSUE TITLE
Tablet in der Hand

### ISSUE THREAD

**Issue by PsYke86** [mexyn/statev_v2_issues#529]
**jack_Napyr**

**Immer**

**Tablet oder Handy in der Hand beim abbauen**

**wenn man eine Spitzhacke in der Hand hält und Erze abbaut ist's normalerweise nicht möglich noch mit dem Handy oder dem Tablett etwas zu machen? Außer man hat 3-4Arme ^^**

Erze abbauen und einfach mal dazu das Tablet oder Handy in die Hand nehmen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Kein Bug. Wir wollen und werden nicht alles abfangen. Dieser "Eintrag" zählt zur Kategorie. Ich öffne ja auch nicht einfach mein Tablet wenn ich in der Mine bin und eine Spitzhacke in Hand habe? ;)
