### ISSUE TITLE
Minus Prozentangabe bei Produktionen immer noch da

### ISSUE THREAD

**Issue by glb11** [mexyn/statev_v2_issues#53]
**Zeitpunkt (Datum / Uhrzeit)**
26.08.2020  0:30

**Beobachtetes Verhalten**
Produktion beginnt bei Minus % (z.B: 5%) 

**Erwartetes Verhalten**
Sollte Bei 0% Beginnen

**Schritte um den Fehler nachvollziehen zu können**
Maschine anmachen (getestet in der Mühle aber wahrscheinlich bei allen) und am Computer stehen bleiben und beobachten 

**Optional: Video / Bilder des Fehlers**
![20200826001711_1_LI (2)](https://user-images.githubusercontent.com/70204338/91237906-1aafbc00-e73c-11ea-8101-c2fd542ac5a2.jpg)

**Comment by r3sist3nt** [comment]
nach restart fixed.
