### ISSUE TITLE
Fahrzeug Schließt ab nach Tanken

### ISSUE THREAD

**Issue by PsYke86** [mexyn/statev_v2_issues#531]
**Character Name**
Jack_Napyr

**Zeitpunkt (Datum / Uhrzeit)**
Immer 

**Beobachtetes Verhalten**
Jedes Fahrzeug das ich nutze, ist immer nach dem Betanken des Fahrzeugs abgeschlossen, ohne das man es selber abgeschlossen hat.

**Erwartetes Verhalten**
Wenn ich das Fahrzeug vor dem betanken nicht selber abschließe, sollte es nach dem betanken auch auf sein.

**Schritte um den Fehler nachvollziehen zu können**
Einfach tanken fahren & den Waagen nicht abschließen

**Comment by DonVitoDiangelo** [comment]
Das ist gewollt. Repost
