### ISSUE TITLE
BMW i8 immer wieder kaputt

### ISSUE THREAD

**Issue by SandyLive89** [mexyn/statev_v2_issues#532]
Sandy Miller

**Beobachtetes Verhalten**
Ich habe heute früh meinen i8 reparieren lassen und bin nach einer zeit zur Fertigung gefahren um dort was zu checken, als ich wieder raus gekommen bin stand mein i8 unten am MD auf dem parkplatz und wieder so kaputt wie vor der reparatur. Das ganze ist 2-3 mal passiert das er auf einmal weg war und immer wieder am MD stand und immer wieder do kaputt wie vor der ersten reparatur.

**Erwartetes Verhalten**
Eigentlich sollte doch das fahrzeug da stehen bleiben wo ich es abgestellt habe und vor allem nach einer reparatur auch ganz bleiben wenn er nur irgendwo geparkt ist

**Comment by DonVitoDiangelo** [comment]
können wir aktuell nicht beeinflussen
