### ISSUE TITLE
Schwebende Person

### ISSUE THREAD

**Issue by No1likeyou** [mexyn/statev_v2_issues#533]
**Character Name**
Beobachtet: Ben_Stark
Auslöser: Lela_Brick

**Zeitpunkt (Datum / Uhrzeit)**
25.11.2020 um 17:12 Uhr

**Beobachtetes Verhalten**
Lela_Brick schwebte über dem Boden

**Erwartetes Verhalten**
Füße von Lela_Brick berühren den Boden

Möglicherweise werden die Schuhe als Highheels eingestuft.

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/40e0db734ac09ca2e5346cdddf888504

**Comment by Enemyaa** [comment]
Kann ich so nicht bestätigen. https://prnt.sc/vq7kth Gleicher Ort + selber Schuhe = keine Probleme!
