### ISSUE TITLE
Feuerwerksbatterie die Zweite

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#536]
Ich glaube das ist durch gerutscht bei euch, da auch keinerlei Labels an dem Thema sind... :)  

https://github.com/mexyn/statev_v2_issues/issues/510

**Comment by its4l3x** [comment]
Schau mal bitte, obs geht. Es ist beim Update durch gegangen - Changelog stehts halt nicht drinnen ;)

**Comment by Statev-Bonsai** [comment]
Dankeeeeeeeeeeeeeeeeee.. Funktioniert, Super Arbeit wie immer :)

**Comment by its4l3x** [comment]
Top. Perfekt. 👍
