### ISSUE TITLE
PD Fahrzeuge stehen in der falschen Garage (Öffentliche Garage Vespucci)

### ISSUE THREAD

**Issue by DerHessenTyp** [mexyn/statev_v2_issues#537]
**Beobachtetes Verhalten**
Seit dem Update fehlen uns 2 Fahrzeuge in der PD Garage.  Caracara mit KZ India und Juliett.
Laut Support (Gamemaster Lundro_Lagu) stehen beide Caracara mit den KZ India und Juliett in der öffentlichen Garage in Vespucci. Leider ist es uns als PD nicht möglich beide Fahrzeuge dort rauszuholen. Schlüssel sind dafür nicht mehr vorhanden.

**Erwartetes Verhalten**
Beide Fahrzeuge gehören dem PD an somit sollten Sie in der MRPD Garage in LS stehen. Laut Lundro_Lagu soll ich den Fehler doch bitte hier reinschreiben da er keine andere Möglichkeit hat diese auszuparken bzw. umzuparken.

**Comment by its4l3x** [comment]
Leider finde ich keine Fahrzeuge mit den genannten Kennzeichen.

Plus dazu, dürften diese Fahrzeuge dann dem Team nicht angehören, da wir Team Fahrzeuge besonders behandeln.

Bitte check das nochmal genau mit den kennzeichen und teile mir die mit

**Comment by DerHessenTyp** [comment]
![India und Juliett](https://user-images.githubusercontent.com/70151958/100389483-c0b9dd80-302d-11eb-8b9e-847de10f0a18.jpg)


Extra nochmal geschaut. Beide Fahrzeuge gehören dem PD an und wie schon erwöhnt laut GM Lundro_Lagu sollen sie in der Vespucci Beach Garage stehen.

**Comment by its4l3x** [comment]
Vor 10 Min. bei mir gegentestet - Kann das leider nicht reproduzieren. Vllt wurde der per Teammitglied dort reingesetzt.
Kein Bug. Habe dir aber trotzdem die beiden Fahrzeuge in die LSPD Garage in LS verschoben.
