### ISSUE TITLE
Ziehen während Bewusstlosigkeit

### ISSUE THREAD

**Issue by statev-aki** [mexyn/statev_v2_issues#538]
**Aki Singh**

Aki Singh
**heute 25.11.2020**

**Beobachtetes Verhalten**

Fehler ist hier gut zu sehen:
https://www.youtube.com/watch?v=bP3Bj6WRPsQ&feature=youtu.be

**Erwartetes Verhalten**
 selbst erklärend

**Optional: Video / Bilder des Fehlers**
 **https://www.youtube.com/watch?v=bP3Bj6WRPsQ&feature=youtu.be**

Wurde bereits von Tom bearbeitet. Hier lediglich zur Information.

PS: Nach jedem Restart ist die Handbremse der Autos nicht mehr aktiv und man kann sie wieder schieben...

peace
Aki

**Comment by its4l3x** [comment]
Zählt mmn zur Kategorie "Spiele Richtiges RP" Ich ziehe auch 'nen Spieler und führe nebenbei eine Herzrhythmus Massage durch? Sorry, aber Leute - Denkts doch einfach nach was ihr macht mit den Features die wir euch geben. Wenn wir euch alle einschränken, dann meckert ihr auch nur rum.

Daher mein Appel an euch (an dich) BITTE BITTE BITTE. Denkts nach was ihr macht und machts keine Herzrhythmus Massage und ziehts die Person dabei? Wo ist da das RP?

**Comment by statev-aki** [comment]
ich bin der der liegt wie du im Video siehst alex von daher kann ich nicht beeinflussen was da iwer mit mir macht aber danke für dem kleinen appel ;)

ps. denk an die autos ;)

**Comment by its4l3x** [comment]
Das ist mir auch bewusst. Ich meine damit generell alle.
