### ISSUE TITLE
Bezeichnugn Produktion/Rezept

### ISSUE THREAD

**Issue by Annabelle-Smith** [mexyn/statev_v2_issues#539]
****

Annabelle Smith

**Zeitpunkt (Datum / Uhrzeit)**

25.11.2020 / 15 uhr

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

Fehler  Im Produktions Computer

**Schritte um den Fehler nachvollziehen zu können**

Richtige Bezeichnung? Beim Rezept dan keine Roten Pigmente für Orange?

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![rezept 1](https://user-images.githubusercontent.com/74880091/100260992-6eec5700-2f4a-11eb-8f10-e849b54f3a96.jpg)

**Comment by DonVitoDiangelo** [comment]
ist ok so wie es ist
