### ISSUE TITLE
Nur Barzahlung im Ammunation möglich

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#54]
**Zeitpunkt (Datum / Uhrzeit)**
26.08.20 00:30

**Beobachtetes Verhalten**
Beim Kauf im Ammunation wird nur Bargeld akzeptiert.-

**Erwartetes Verhalten**
Das Geld wird wie auf dem Liveserver auch von Konto abgebucht da es im Ammunation um große Summen geht.

**Schritte um den Fehler nachvollziehen zu können**
Einfach einkaufen...
![ammo3](https://user-images.githubusercontent.com/70241137/91235525-fea91c00-e735-11ea-8ed6-1b63b1874322.jpg)

**Optional: Video / Bilder des Fehlers**

**Comment by eiksch** [comment]
fixed beim nächsten Update
