### ISSUE TITLE
Weedtisch kann nicht abgebaut werden und ist unter manchen Umständen unsichtbar

### ISSUE THREAD

**Issue by DeRo1337** [mexyn/statev_v2_issues#540]
**Character Name**
Derk_Ronaldo

**Zeitpunkt (Datum / Uhrzeit)**
25.11.2020

**Beobachtetes Verhalten**
Weedtisch wurde aufgestellt und kann nicht mehr eingepackt werden, bzw. in manchen fällen nicht mehr benutzbar. Tisch war bei manchen Personen sichtbar bei manchen nicht.

**Erwartetes Verhalten**
Tisch sollte dargestellt werden. und eingepackt werden können.

**Schritte um den Fehler nachvollziehen zu können**
Tisch aufstellen und abbauen. Funktioniert nicht kommt Fehlermeldung.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/b325a725de40d6c693500ad782f45e6d

**Comment by eiksch** [comment]
Sollte behoben sein - wenn so etwas erneut auftritt, bitte mit genauer Fehlerbeschreibung erneut melden.
