### ISSUE TITLE
Herstellung wieder hinzugefügter Munition (AK47, Mini-Uzi usw) gleich Herstellung Hülsen

### ISSUE THREAD

**Issue by Diak27** [mexyn/statev_v2_issues#542]
**Jacob_Mason**
Jacob Mason
**Zeitpunkt (Datum / Uhrzeit)**
25.11.2020 18:43 Uhr
**Beobachtetes Verhalten**
Waffenfabrik, Herstellung von Munition nach Update von heute um 17:15 Uhr:
In der Waffenfabrik selber ist der Herstellungsprozess von verpackten Magazinen von den wieder hinzugefügten Munitionsarten (AK-47, MP5, QBZ, Mini Uzi usw.) der gleiche wie der von den Hülsen der jeweiligen Munition. (in diesem Fall ausprobiert Herstellung verpacktes Magazin AK-47) sprich die Munition selber kostet nur Messingbarren und  das andere halt. Somit kann gerade Munition ohne Hülsen, Schießpulver, Munitionskugeln usw. hergestellt werden.
**Erwartetes Verhalten**
Normalerweise 1. Herstellung Hülsen AK-47 >> 2. Herstellung verpacktes Magazin Ak-47 mit vorher hergestellten Hülsen
**Schritte um den Fehler nachvollziehen zu können**
1. Waffenfabrik Herstellungscomputer > runter scrollen zu wieder hinzugefügten Munitionsarten > auswählen und herstellen.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot_1](https://user-images.githubusercontent.com/75038769/100264980-d8bb2f80-2f4f-11eb-9676-26b4983809c1.jpg)

**Comment by Statev-Bonsai** [comment]
das ist sehr kritisch... ^^

**Comment by Diak27** [comment]
ja, kann gerade mega abused werden, @Statev-Bonsai  kannst du vielleicht mal nen screen rein hauen von deiner waffenfabrik von den rezepten, bei mir läuft ja die prouduktion noch

**Comment by Statev-Bonsai** [comment]
die läuft zur zeit, damit kann wenn man es anlegt die ganze munitionswirtschaft über monate lahmlegen!

**Comment by DrGrizzlY17** [comment]
Bin schon dran Mädels

**Comment by Diak27** [comment]
bist nen geiler @DrGrizzlY17

**Comment by Statev-Bonsai** [comment]
https://prnt.sc/vq3bsi alles wieder wie früher.. danke!
