### ISSUE TITLE
Ausparkpostion Garage Vinwood West + Achsenproblematik

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#543]
Bitte den Ausparkpunkt der Garage Vinewood West an die Straße legen oder die Fahrzeuge beim ausparken um 180grad drehen, denn sie stehen genau falschrum was ein ankoppeln von Achsen unmöglich macht, man muss sie erst sehr aufwendig mit der Zugmaschine drehen
![Screenshot_10](https://user-images.githubusercontent.com/70241137/100266487-318bc780-2f52-11eb-8948-344bca40eba4.png)

Zudem wäre es sinnvoll wenn Achsen aufgeschlossen sind wenn sie ausgeparkt werden, momentan sind sie verschlossen, und da manche Leute zuerst die Achse ausparken ist es unmöglich wenn ein fremder die Achsen wegfahren will um den Ausparkpunkt frei zu machen.

**Comment by DrGrizzlY17** [comment]
#447
