### ISSUE TITLE
Motorbezeichnung

### ISSUE THREAD

**Issue by Fergoz** [mexyn/statev_v2_issues#544]
Fabian Vecter

25.11.2020/ca 19:00

Im Import wird der Motor für den Rebel so "Karin Rusty Rebel & Rebel Motor / 132 PS " aufgeführt. Es lässt sich aber nur der Rusty Rebel bauen.

Wenn in der Beschreibung des Motors beide Varianten aufgeführt sind sollten auch beide herstellbar sein.

In einer Autofertigung nachschauen bzw in den hinterlegten Datein

![Rebel](https://user-images.githubusercontent.com/75041115/100270862-f8a32100-2f58-11eb-9e62-d27a611d3836.jpg)

**Comment by DonVitoDiangelo** [comment]
solved next update

**Comment by Fergoz** [comment]
das ging ja fix danke :) aber in wie fern wird es geregelt nur der Text geändert oder kann ich den normalen dann bauen lassen würde das gerne vorher wissen nicht das ich den bauen lasse und habe dann möglichkeit den anderen bauen zu lassen
