### ISSUE TITLE
Verlust Kleidungsstück bei vollem Inventar

### ISSUE THREAD

**Issue by Atomic3** [mexyn/statev_v2_issues#545]
**Patrick_Baader**

**ca 25.11.2020 00:15**

**Ich wollte die Hose anziehen, es kam die Meldung Inventar voll und rechts im Menü waren beide hosen. Habe die eine zurück holen wollen ins Inventar und dann war sie weg. Hatte dann aber eine komplett andere Hose an die ich weder gezogen habe oder an geklickt hatte.**

**Ich kann die Hose nicht anziehen Meldung kommt Inventar voll und fertig.**

**Inventar voll machen und dann umziehen.**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**(https://youtu.be/UJVWFhBR26s)**

**Comment by JulianMa** [comment]
nach update fixed.
