### ISSUE TITLE
LSMD Apotheke falsches Werbeschild

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#546]
**Character Name**
Dan_Lee

**Zeitpunkt (Datum / Uhrzeit)**
25.11.2020

**Beobachtetes Verhalten**
Das Werbeschild der LSMD Apotheke (pharmacy) zeigt als Vorschau eine Autohaus Werbung an

**Erwartetes Verhalten**
Ändern das es das Vorschaubild vom Lager anzeigt

![image](https://user-images.githubusercontent.com/70150988/100273550-3ace6180-2f5d-11eb-8f63-6ba6288356de.png)

**Comment by its4l3x** [comment]
fixed
