### ISSUE TITLE
Ladepunkt Objekt pfKryptStrawbRew_1 umsetzen

### ISSUE THREAD

**Issue by DiyosVZ** [mexyn/statev_v2_issues#548]
**Character Name**

**Zeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
Könnte man eventuell den Ladepunkt beim Objekt "pfKryptStrawbRew_1" umsetzen. 
Man kommt mit einem Pounder oder einer Achse nur zur Ladestelle wenn man sämtliche Objekte "umfährt"

**Erwartetes Verhalten**
Eventuell den Ladepunkt auf setzen wie im Bild 3
Vielen Dank!

**Optional: Video / Bilder des Fehlers**
![Inked20201123161911_1_LI](https://user-images.githubusercontent.com/75044008/100279127-3bb7c100-2f66-11eb-89c8-7a9a9a4f1b5d.jpg)
![Inked20201123161808_1_LI](https://user-images.githubusercontent.com/75044008/100279244-70c41380-2f66-11eb-9aba-2cbff1fbc2c2.jpg)
![Inked20201123174911_1_LI](https://user-images.githubusercontent.com/75044008/100279285-876a6a80-2f66-11eb-80ec-4f876f7f0005.jpg)
![20201125214147_1](https://user-images.githubusercontent.com/75044008/100279558-14152880-2f67-11eb-8d91-eb6e6c0ad7ab.jpg)

**Comment by Enemyaa** [comment]
Dann nehmen wir mal Nummer 3.
