### ISSUE TITLE
Tasche nicht sichtbar

### ISSUE THREAD

**Issue by Noah9461** [mexyn/statev_v2_issues#549]
**Character Name**
Noah Draper

**Zeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Wenn man eines der Los Hermano Hemden trägt ist die Tasche verbuggt, heißt sie wird nicht angezeigt. Ist aber im Inventar normal abrufbar

**Erwartetes Verhalten**
Tasche sollte am Rücken angezeigt werden

**Schritte um den Fehler nachvollziehen zu können**
Los Hermanos Hemd schwarze Umhängetasche anziehen, diese wird dann nicht am Rücken angezeigt

![image](https://user-images.githubusercontent.com/71601830/100279503-f5169680-2f66-11eb-9aab-04ee8c7a5798.png)

![image](https://user-images.githubusercontent.com/71601830/100279515-fd6ed180-2f66-11eb-99b2-c420a3a03bf3.png)

**Comment by Enemyaa** [comment]
Hast du das mit den Teams und der Tasche schon behoben? @its4l3x

**Comment by Kalumel** [comment]
Habe ich bei der "Rockerkutte",  vom Lost glaube ich, auch schon gesehen.

**Comment by Enemyaa** [comment]
Das Problem haben im Moment alle mod. Oberteile!
