### ISSUE TITLE
Personen im Kabrio bewusstlos

### ISSUE THREAD

**Issue by Headmonsta** [mexyn/statev_v2_issues#55]
**Zeitpunkt (Datum / Uhrzeit)**
25.08.2020 23:20

**Beobachtetes Verhalten**
Wenn man jemanden aus dem Auto tritt das diese Person bewusstlos ist. Fliegt diese 15-20 Meter hinter das Fahrzeug. Dies passiert nach ein paar sec nach der Bewusstlosigkeit.

**Erwartetes Verhalten**
Normalerweise muss die Person bewusstlos werden im Fahrzeug und dann dort sitzenbleiben oder gleich neben dem Fahrzeug liegen

**Schritte um den Fehler nachvollziehen zu können**
(Bis jetzt nur im Kabrio getestet) Erst aufs Fahrzeug steigen. Und dann an den Kopf treten. 

**Optional: Video / Bilder des Fehlers**
https://youtu.be/Egy-DTbsny0 Youtube Upload weil zu groß

Bei nachfragen Uri_Holiday oder HeadMonsta#8147 bei Discord

**Comment by Headmonsta** [comment]
29.08.2020
Also wir haben weiter geguckt.

Dieser Fehler tritt auch auf wenn:

Angeschnallt im Kabrio
Anstatt Bewusstlosgetreten erschossen im Fahrzeug
Nicht angeschnallt und angeschnallt in einem Fahrzeug mit Dach (getestet im Unmarked Mustang GT (MD))

**Comment by DrGrizzlY17** [comment]
Keine relevanz mehr
