### ISSUE TITLE
Behandlung mehrmals durchführbar

### ISSUE THREAD

**Issue by LivePlayerHD** [mexyn/statev_v2_issues#550]
Character Name
Kira_Noka

Fehler gefunden: 23.11.2020 um ca 20:30 Uhr

Beobachtetes Verhalten
Ich habe bemerkt das man während einer Behandlung im MD mit Fußläufigen Patienten mehrmals die Behandlung durchführen kann. Ich weiß momentan nicht wie es mit den Patienten ist die mit den RTW eingeliefert werden.

Erwartetes Verhalten
Damals was es so das man während der Behandlung keine neue Behandlung mit den gleichen Patienten durchführen kann.

Schritte um den Fehler nachvollziehen zu können
Um das nachstellen zu können muss man lediglich eine Person Behandeln und die Behandlung nochmal ausführen und dann Behandelnd man die Person 2x gleichzeitig

**Comment by Chrinis007** [comment]
Ist nur bei fußläufigen Patienten so

**Comment by LivePlayerHD** [comment]
Zusatz:

Ich habe auch gefunden das man auch eine Behandlung macht an Irgendwas/Irgendjemanden wenn man in der Nähe steht.

[Video.zip](https://github.com/mexyn/statev_v2_issues/files/5610887/Video.zip)

**Comment by Chrinis007** [comment]
Das finde ich tatsächlich gut weil so kann man sich auf den Stuhl im doktorzimmer sitzen oder Ähnliches

**Comment by Chrinis007** [comment]
Würde ich tatsächlich so lassen dass man den aus der Nähe nimmt so wird n gewisser Zwang weggenommen

**Comment by LivePlayerHD** [comment]
Okay. Ja an das habe ich jetzt nicht gedacht

**Comment by its4l3x** [comment]
Sorry for late Answer. Gewollt. Du bist nicht mehr gezwungen auf irgendwelchen Betten zu sitzen. Lediglich in der nähe eines definierten Bettes welches wir vorgeben. Ihr sollt das ausspielen.
