### ISSUE TITLE
Mustang GT steht nicht auf den Flatbed

### ISSUE THREAD

**Issue by LivePlayerHD** [mexyn/statev_v2_issues#551]
Character Name
Kira Noka

Fehler Gefunden
25.11.2020 um ca 23 Uhr

Beobachtetes Verhalten
Der Mustang schwebt etwas über den Fletbed wenn der abgeschleppt wird

Schritte um den Fehler nachvollziehen zu können
Man muss lediglich mit einen Fletbed einen Mustang GT abschleppen.

Bild
![20201125225108_1](https://user-images.githubusercontent.com/74984092/100287828-b4724980-2f75-11eb-85a6-9c9797e826c9.jpg)

**Comment by DonVitoDiangelo** [comment]
config adden, keine Prio

**Comment by DonVitoDiangelo** [comment]
Wird hier kein weiteres Feature geben da es soweit passt.

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1366
