### ISSUE TITLE
Boot x-Menü

### ISSUE THREAD

**Issue by glb11** [mexyn/statev_v2_issues#553]
**Character Name**
Jens_Summer

**Zeitpunkt (Datum / Uhrzeit)**
22.11.   23.Uhr

**Beobachtetes Verhalten**
Läd teilweise falsches x-Menü (ohne Anker)

**Erwartetes Verhalten**
Anker setzten/lösen immer zu sehen

**Schritte um den Fehler nachvollziehen zu können**
in das Dinghy setzten und x Menü öffnen dann teilweise (random) kein Anker-Symbol zu sehen wird nur durch absitzen und wieder hinsetzen erst wieder sichtbar

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/h-jiCXFRBXY

**Comment by its4l3x** [comment]
Habe das XMenu Handling des Bootes vor paar Tagen angefasst. Sollte nicht mehr vorkommen. Du musst lediglich im Wasser sein. D.h. nicht gerade von einer Welle mitgenommen sein.
