### ISSUE TITLE
beim Hochsee Angel buggt/klitscht man durchs boot 

### ISSUE THREAD

**Issue by glb11** [mexyn/statev_v2_issues#554]
**Character Name**
Jens_Summer

**Zeitpunkt (Datum / Uhrzeit)**
25.11 23.15 Uhr

**Beobachtetes Verhalten**
Beim öffnen des Farmfeldes buggt man teilweise durchs Boot durch --> bei kurzer Unaufmerksamkeit Not-MD

**Erwartetes Verhalten**
Das Mann am ende des Vorganges normal auf dem Boot steht

**Schritte um den Fehler nachvollziehen zu können**
Angeln und Angel bei ungünstiger Konstellation der Wellen durch rutschen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/d-ARoFKmUbw

**Comment by DonVitoDiangelo** [comment]
freeze ausnahme

**Comment by DonVitoDiangelo** [comment]
fixed next update
