### ISSUE TITLE
Kleiderladen Alta street 277 Oberteilständer verschieben

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#555]
**Character Name**

**Zeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

Der Kleiderständer war vorher immer an dieser Stelle (Siehe Bild) die Leute sind es sich so gewöhnt. Zusätzlich ist es als verkaufspersonal angenehmer wen nicht alle Leute auf einem Fleck stehen damit man sich unterhalten kann während der Beratung.

**Erwartetes Verhalten**

Wäre nett wen dieses umgesetzt werden kann. 

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![unknown (8)](https://user-images.githubusercontent.com/70231715/100295735-9a8f3180-2f8a-11eb-80c6-f15e6b1d9a18.png)

**Comment by Enemyaa** [comment]
Nee, wurde bewusst an die anderen Läden angepasst.
