### ISSUE TITLE
Bild des Verpackten Chemikalienanzugs ist fehlerhaft

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#556]
**Character Name**

**Zeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

Wie in der Beschreibung steht kann das icon nicht geladen werden

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![unknown](https://user-images.githubusercontent.com/70231715/100295856-0a052100-2f8b-11eb-826c-d0de49e515a4.png)

**Comment by DonVitoDiangelo** [comment]
next update
