### ISSUE TITLE
Antrag für einen ATM Kleiderladen Alta Street 277

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#557]
**Character Name**

**Zeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

Wäre schön wenn dies an dieser stelle gehen würde.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![ATMpng](https://user-images.githubusercontent.com/70231715/100316965-c971cb80-2fbb-11eb-8602-4febaed2807f.png)

**Comment by DonVitoDiangelo** [comment]
Abgelehnt.
