### ISSUE TITLE
Falsche Bezeichnung *Helix Workbreaker

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#558]
**Character Name**

**Zeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

Helix Worker sind die Hosen 

**Erwartetes Verhalten**

Helix Workbreaker sind die Oberteile 

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![unknown (2)](https://user-images.githubusercontent.com/70231715/100296503-b7c4ff80-2f8c-11eb-87ee-f3f750c4d21b.png)

**Comment by Enemyaa** [comment]
Fixed!
