### ISSUE TITLE
Werkstatt, Xenon lichter verbrauch bei nicht Xenon Tuning

### ISSUE THREAD

**Issue by BlackyGER** [mexyn/statev_v2_issues#559]
**Beobachtetes Verhalten**
Beim Tunen werden Xenon lichter verbraucht obwoh man diese nicht mal tuned. Bei mir als Werkstattarbeiter steht dies auch nicht. Bei dem Kunden auf der Rechnung sind diese aber dennoch gelistet. Wegwerfen kann dieser aber die Rechnung auch nicht da so der andere Bug getriggert wird.

**Erwartetes Verhalten**
Tuned man keine Xenon Lichter, so sollte man auch keine Verbrauchen. 

**Optional: Video / Bilder des Fehlers**

meine Sicht: https://pic.statev.de/i/GzSTy.png
Sicht des Kunden: https://pic.statev.de/image/20201126020831-1.GzM4A

**Comment by r3sist3nt** [comment]
da gibt es beteits ein ticket zu..
