### ISSUE TITLE
Entpackte Waffen/Munition kann im Ammunation verkauft werden

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#56]
**Zeitpunkt (Datum / Uhrzeit)**
26.08.20 00.30

**Beobachtetes Verhalten**
Gekaufte Waffen/Munition kann beim Ammunation wieder über die Theke verkauft werden, dies sollte nicht möglich sein da man NUR verpackte Waffen/Muntion verkaufen kann.
Zudem verlieren so bereits registrierte Waffen mit Seriennummern ihre Seriennummer!

**Erwartetes Verhalten**
Meldung das man nur verpackte Gegenstände in die Theke legen kann

**Schritte um den Fehler nachvollziehen zu können**
Waffe kaufen, wieder in die Theke legen und den Preis einstellen und danach die Waffe normal kaufen.

**Optional: Video / Bilder des Fehlers**

**Comment by eiksch** [comment]
fixed beim nächsten Update, im Ammunation können dann nur verpackte Sachen verkauft werden. Falls noch unverpackte Waffen drinliegen, werden diese nicht mehr im Shop angezeigt.
