### ISSUE TITLE
Keine Interaktion im Haus möglich

### ISSUE THREAD

**Issue by Cil91** [mexyn/statev_v2_issues#561]
**Character Name**
Jerry Brown

**Zeitpunkt (Datum / Uhrzeit)**
26.11      8:45

**Beobachtetes Verhalten**
Keine Interaktion im Haus möglich, weder öffnen des Hausinventars noch Verlassen des Hauses

**Erwartetes Verhalten**
Interaktion möglich, Haus kann Verlassen werden und das Lager des Hauses ist zu öffnen

**Schritte um den Fehler nachvollziehen zu können**
Beim Verlassen des Hauses hat sich mein Spiel aufgehängt, dieses anschließend geschlossen. Spiel neu gestartet und versucht das Haus zu verlassen, aber keine Interaktionen waren möglich.

**Comment by Chrinis007** [comment]
Falsche Dimension

**Comment by DonVitoDiangelo** [comment]
Bitte den Support aufsuchen
