### ISSUE TITLE
Platzierbarer Schneemann ist zu hoch platziert

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#562]
**Beobachtetes Verhalten**
Schneemann wird zu hoch platziert.

**Erwartetes Verhalten**
Schneemann steht auf Boden.

**Optional: Video / Bilder des Fehlers**
![](https://pic.statev.de/i/Gze8k.jpg)

**Comment by DonVitoDiangelo** [comment]
Schneemann bei Regen und Plus Graden? 

Wird aber nicht gefixt. Wird von der GTA Standard coll so geplaced und wir werden hierfür kein System einbauen.
