### ISSUE TITLE
Samen verschwinden wenn sie nicht platziert werden/das Spiel abstürzt oder man den Server verlässt

### ISSUE THREAD

**Issue by Humperrrt** [mexyn/statev_v2_issues#563]
**Character Name**
Paul_Humpert

**Zeitpunkt (Datum / Uhrzeit)**
26.11.2020 / 11:28

**Beobachtetes Verhalten**
Wenn man einen Samen platzieren will und während man noch einen Ort sucht um den Samen zu platzieren, verliert man den Samen, wenn man währenddessen das Spiel verlässt bzw. das Spiel abstürzt.

**Erwartetes Verhalten**
Man sollte den Samen ins Inventar zurückerhalten, wenn man während dem Platzieren das Spiel verlässt oder das Spiel abstürzt.

**Schritte um den Fehler nachvollziehen zu können**
- Rechtsklick auf einen Samen machen
- Vor dem Platzieren des Samens das Spiel verlassen
- Nach dem neuen joinen überprüfen, ob man den Samen noch im Inventar besitzt

**Comment by DonVitoDiangelo** [comment]
Erst suchen, dann setzen.
