### ISSUE TITLE
Masken/Bandanas

### ISSUE THREAD

**Issue by Nightdelta77** [mexyn/statev_v2_issues#564]
**Character Name**
Ethan Willis

**Zeitpunkt (Datum / Uhrzeit)**
25.11.2020 / 22 Uhr

**Beobachtetes Verhalten**
Teile des Gesichts (Wange) clippen durch Sturmhaube durch (auch bei Police Uniform) Setzt man dann noch eine Sonnenbrille oder Schutzbrille (z.B. bei Uniformen) an, buggt noch mehr des Gesichts durch die Maske

**Erwartetes Verhalten**
Normalerweise gab es durch resett_face (?) keine Probleme und das Gesicht war vollkommen bedeckt

**Schritte um den Fehler nachvollziehen zu können**
Uniform mit Maske auswählen oder Sturmhaube anziehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
/

**Optional: Video / Bilder des Fehlers**
/
![Maske](https://user-images.githubusercontent.com/75073413/100353884-84678c80-2fef-11eb-9ebf-2b4c6bb589da.png)

**Comment by Nightdelta77** [comment]
Bild hochgeladen und Augenextras-Thematik hinzugefügt

**Comment by Enemyaa** [comment]
Kann ich so bestätigen! @r3sist3nt "defaultFace" ist inaktiv

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/650

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1304

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1371

**Comment by Chrinis007** [comment]
@Hutstaender Fehler immer noch vorhanden
