### ISSUE TITLE
Flüssigkeiten ins autohaus lagern

### ISSUE THREAD

**Issue by Hexenjaeger** [mexyn/statev_v2_issues#565]
>
Leon_Unger

die letzten tage

**Beobachtetes Verhalten**
man kann keine flüssigkeiten mehr ins autohaus lagern (Falsche tranzportgruppe bei versuch mit auflieger)

**Erwartetes Verhalten**
einlagern können

**Schritte um den Fehler nachvollziehen zu können**
mit zugmaschiene ran fahren kofferraum öffnen und einlagern

**Optional: Video / Bilder des Fehlers**
video kann ich bei bedarf nachreichen

**Comment by Statev-Bonsai** [comment]
Was haben Flüssigkeiten im Autohaus zu suchen? o.0 Das wurde Extra so gemacht :)

**Comment by DonVitoDiangelo** [comment]
So ist es, hier wurde ein Menge angepasst.

**Comment by Hexenjaeger** [comment]
ok dachten bug weil meldung ...   danke für die rückmeldung @DonVitoDiangelo
