### ISSUE TITLE
Farmpunkte werden auf der Map nicht richtig angezeigt

### ISSUE THREAD

**Issue by VerenaBelters** [mexyn/statev_v2_issues#567]
**Verena Belters**
Verena Belters

**Zeitpunkt (Datum / Uhrzeit)**
26.11.20 Das Problem besteht dauerhaft

**Beobachtetes Verhalten**
Die Punkte auf der Map sind fehlerhaft. Manche werden dauerhaft angezeigt (auch wenn das Feld zu ist und manche nur, wenn sie offen sind)

**Erwartetes Verhalten**
Punkt nur sichtbar, wenn das Feld offen ist

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Tobse1904** [comment]
Das liegt soweit ich weiß daran, das einige punkte auch andere dinge sind, und Altv nur 90 Marker zulässt. Falls ich hier falsch liege einfach ignorieren :)

**Comment by DonVitoDiangelo** [comment]
@VerenaBelters  Bitte mal genauer beschreiben. Das mit der Markierung über die Punkte an der rechten Seite ist aktuell leider so, da wir hier begrenzt sind auf 99 Stück. Dadurch wird dann einiges nicht angezeigt.

Auf der karte selbst die Punkte der Farmfelder sind nur zu sehen, wenn ein Farmfeld auch "geöffnet " ist.

**Comment by VerenaBelters** [comment]
@DonVitoDiangelo zum Beispiel ist das Kautschuk Feld am Strand gerade geöffnet aber wird in der Legende nicht angezeigt. Find ich für neue Spieler ein bisschen problematisch.

**Comment by VerenaBelters** [comment]
@DonVitoDiangelo vor wenigen Tagen war es der Fall, dass der Punkt auf der Map war aber das Feld hatte zu. Ich werde es nochmal weiter im Auge behalten.

**Comment by DonVitoDiangelo** [comment]
Also das es nicht in der Legende erscheint, ja das kann halt passieren, da können wir aktuell nichts dran ändern.
Das Feld allerdings sollte, wenn es zu ist, nicht auf der karte erscheinen. Bei weiteren Fragen mich einfach markieren.

**Comment by Tobse1904** [comment]
@DonVitoDiangelo wäre es nicht machbar, das wenn man mit dem Curser der Maus über den Punkt fährt das dort nen Name erscheint. Funktionieren tut dies das weiß ich aus eigener Erfahrung ist halt nur die frage ob es von euch gewünscht ist somit wäre das Problem mit den 99 Legenden behoben und man könnte die ggf sogar ausblenden
