### ISSUE TITLE
Fehlermeldung bei fehlendem Item im 24/7

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#568]
**Zeitpunkt (Datum / Uhrzeit)**
26.11.2020 / 14.30
**Beobachtetes Verhalten**
siehe Bild. 
**Erwartetes Verhalten**
Fehlermeldung ersetzten mit Text
**Schritte um den Fehler nachvollziehen zu können**
Produktion starten (PC dabei nicht schließen) -> warten bis Produktion fertig ist ->  kein neues Item auswählen -> Produktion starten
**Optional: Video / Bilder des Fehlers**
https://puu.sh/GRtOb/dafaecf668.png

**Comment by DrGrizzlY17** [comment]
Die Translation ist vorhanden, wird Clientseitig trotzdem nicht angezeigt

**Comment by its4l3x** [comment]
fixed next update
