### ISSUE TITLE
Auto spawnt random, obwohl woanders abgestellt

### ISSUE THREAD

**Issue by statevmj** [mexyn/statev_v2_issues#569]
**Character Name**
Mathew_Jones

**Zeitpunkt (Datum / Uhrzeit)**
26.11.2020 / 14:46 Uhr

**Beobachtetes Verhalten**
Der Sultan RS spawnt aufeinmal an der Stelle, wo er vorher geparkt war - obwohl er ca. 5 min vorher am Pucci Vesgucci abgestellt wurde. Der Wagen spawnt nach dem Ausführen einer Animation, kann aber auch Zufall sein. Kurze Zeit danach stand auch aufeinmal eine Zugmaschine da, wo sie beim Ankauf geparkt hatte. Dazwischen sind auch etwa 5 Minuten +- vergangen.

**Erwartetes Verhalten**
Autos sollten da stehen bleiben, wo sie abgestellt werden und nicht an den Ort zurückgeportet werden, wo sie vorher mal standen.

**Schritte um den Fehler nachvollziehen zu können**
Keine Ahnung, ob das so einfach zu reproduzieren ist. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=CpfXOx__FWk&feature=youtu.be

**Comment by tastydev** [comment]
#400
