### ISSUE TITLE
Import bieten nicht möglich

### ISSUE THREAD

**Issue by mxRde** [mexyn/statev_v2_issues#57]
**Zeitpunkt (Datum / Uhrzeit)**
01:20 | 26.08.2020

**Beobachtetes Verhalten**

Kann auf Motoren mit jeder Firma bieten aber nicht auf Brands.
Folgende Meldung erscheint: Bieten nicht möglich
(Konto ist gedeckt, habe alle rechte in Firmen)

**Erwartetes Verhalten**

Ich sollte mit egal welche Firma drauf bieten können, Vertragsstrafen gehören zum RP dazu.

**Schritte um den Fehler nachvollziehen zu können**

1. Tablet auf
2. Import
3. Bieten
4. Geht nicht

**Optional: Video / Bilder des Fehlers**

**Comment by MarcelMuerto** [comment]
@mxRde Also ich habe das jetzt bei mir lokal ausprobiert und dort kann ich zum Beispiel mit einer Carfactory auf ein Brand bieten.
Womit hast du das getestet gehabt?

**Comment by DonVitoDiangelo** [comment]
Bitte Firmenname nachtragen und auf welche Brands du geboten hast @mxRde

**Comment by mxRde** [comment]
Alle möglichen Klamottenbrands.
Teils bin ich Inhaber, Teils nicht,

Dabei waren:
Labor,
Schneiderei,
Weberei,
Klamottenladen,
u.a.

**Comment by MarcelMuerto** [comment]
Also aktuell bin ich grade noch dran diese Bug zu reproduzieren, sieht aber bisher schlecht aus.

Konnte mit meiner Weberei bieten, habe aber dafür das Error Handling angepasst, jetzt sollte man zumindest mehr Informationen bekommen was der Fehler ist in der Message die man bekommt.

@mxRde

**Comment by mxRde** [comment]
Hey, war mb. Niemals gesehen das es einen Maximalgebotsschritt gibt.

kann denke geclosed werden.
