### ISSUE TITLE
Verbesserungsvorschläge Tablett

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#570]
1. Nach schließen des Tablets soll die letzte geöffnete Page angezeigt werden, momentan wir immer die Startseite angezeigt (wo man Statenet,Browser,Social auswählen kann) , das ist etwas nervig auf die Dauer wenn man das Tablett öfters wegen Import / Export nutzt.
Die Home Taste sollte dann zur Auswahl der verschiedenen Seiten Statenet,Browser,Social führen.

2. Passwort merken, so wie es früher war...

**Comment by RomanSpielberg** [comment]
Anmeldung merken würde ich auch begrüßen!

**Comment by Statev-Bonsai** [comment]
Roman, siehe meinen Punkt 2...

**Comment by its4l3x** [comment]
Autologin ist wieder beständig.

**Comment by its4l3x** [comment]
Sollte eig. mitlerweile alles so sein, oder irre ich mich?
