### ISSUE TITLE
Suchfunktion Lager

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#574]
**Zeitpunkt (Datum / Uhrzeit)**
26.11.2020 / 17.45
**Beobachtetes Verhalten**
Wenn man nach etwas sucht das sich im Lager befindet bekommt man kein Ergebnis. Erst wenn man ein 2. oder 3. mal das Lagerfenster öffnet.
**Erwartetes Verhalten**
Der gesuchte Gegenstand sollte sofort erscheinen.
**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug auf Abladepunkt stellen -> Kofferraum aufmachen -> An die Firma gehen (In diesem Fall ein Lager) -> Im ganz rechten Suchfeld etwas suchen 
**Optional: Video / Bilder des Fehlers**
https://puu.sh/GRwfP/32e73bdfe0.png

**Comment by DonVitoDiangelo** [comment]
Suche löschen und dann neu eingeben. Manchmal ist schon etwas in der Such eingetragen.
