### ISSUE TITLE
Private Garage

### ISSUE THREAD

**Issue by EmilyLodge** [mexyn/statev_v2_issues#575]
**Emily_Lodge**

Emily_Lodge
**Zeitpunkt (Datum / Uhrzeit)**

mehrfach, bei jedem Restart
**Beobachtetes Verhalten**

Meine Autos werden nicht automatisch in die Garage eigene Garage eingeparkt. Sei es sie stehen auf dem Grundstück oder direkt auf dem Garagenpunkt.
**Erwartetes Verhalten**

Die Autos sollen eigentlich, wenn sie auf dem Grundstück stehen in meiner Garage eingeparkt werden. 
**Schritte um den Fehler nachvollziehen zu können**

Das Auto steht auf dem Grundstück / Auffahrt, beim Restart steht es auf einmal in der öffentliche Garage Mirror Park
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Ist die Garage eventuell voll?

**Comment by EmilyLodge** [comment]
Nein, die Garage hatte nur 2 Fahrzeuge eingeparkt. Die Garage ist jedoch für 6 Fahrzeuge ausgelegt.

Von meinem iPhone gesendet

Am 28.11.2020 um 01:21 schrieb DrGrizzlY17 <notifications@github.com>:

﻿

Ist die Garage eventuell voll?

**Comment by its4l3x** [comment]
Hi, es kann sein das das ein Fahrzeug war, wo du nicht der Owner bist/warst whatever.

Mitlerweile werden auch wenn du die benötigen Rechte hast bzw. besitzer des Hauses auch Fahrzeuge von denen du nur einen Schlüssel hast, eingeparkt. Das Problem sollte damit eig. gelöst sein. Wenn es immer noch beständig ist, in einer anderen weise, dann mach ein neues Ticket auf mit Details (Fahrzeug (kennzeichen etc..), Haus (Adresse, Hash, etc..))
