### ISSUE TITLE
Werkstatt: "Bereits in Verwendung" - Schlosswechsel

### ISSUE THREAD

**Issue by Gordon13m** [mexyn/statev_v2_issues#576]
Sollte man bei einem Fahrzeug ein Schlosswechsel machen, und der Spieler, der die Rechnung bekommt ist nicht der Besitzer des Fahrzeuges, so kommt die Meldung "Das kann nur der Besitzer des Fahrzeuges" - sobald man die Meldung bekommen hat, ist die Werkstatt defekt und in dieser Server Periode nicht mehr nutzbar. "Bereits in Verwendung"

Dieses Problem tritt auch auf, wenn man einem Spieler eine Rechnung ausstellst und dieser nicht genug Geld hat.
Danach bekommt man ebenfalls die Meldung "Bereits in Verwendung"

Des weiteren kommt dieser Fehler zu Stande, wenn der Kunde das UI mit "Abbrechen" wegdrückt.

**Comment by Gordon13m** [comment]
- Der Fehler tritt auch bei Reparaturen auf. Zumindest wenn der Kunde das UI mit Abbrechen schließt.

**Comment by JulianMa** [comment]
Nach nächstem Update gefixed
