### ISSUE TITLE
Error beim Versuch Sneakers auszupacken 

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#578]
**Character Name**

**Zeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

Beim Versuch [M] Schwarz-Weiße Sneakers auszupacken erscheint ein Error auf der Seite. (Siehe Screenshot)

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![sneakers](https://user-images.githubusercontent.com/70231715/100383946-34a0b980-301f-11eb-840d-314ccddb5f7c.png)

**Comment by Enemyaa** [comment]
Danke für die Info. Das sind Dateileichen. Sind doppelt und kommen nun raus.
