### ISSUE TITLE
Cliping Fehler Polizei Uniformen

### ISSUE THREAD

**Issue by Irishman1991** [mexyn/statev_v2_issues#579]
**Patrick_Okeen**

**26.11.2020 19:47 Uhr**

**Cliping Fehler bei Polizei Uniformen**

**Update EUP pack auf aktuelle Version**

**Die Fehler treten bei den meisten BCSO Uniformen auf und bei einigen LSPD Uniformen**

**3440x1440**

**Alls Fraktionsmitglied in den Dienst einstempeln und Waffen anlegen. Manchmal funktioniert das Clipping meistens aber nicht.**

![Cliping_fehler_1](https://user-images.githubusercontent.com/75093060/100384548-b6451700-3020-11eb-8846-72e9bbe7fd3a.png)
![Cliping_fehler_2](https://user-images.githubusercontent.com/75093060/100384562-bd6c2500-3020-11eb-9e72-6478b31c4a77.png)

**Comment by DonVitoDiangelo** [comment]
Wo genau ist hier jetzt für dich ein Fehler? Bitte beschreibe mal den Fehler genauer.
EUP ist hier nicht relevant da wir alles selbst einstellen.

**Comment by Irishman1991** [comment]
Die Taser werden seitlich an der Hüfte angezeigt nicht so wie früher das Diese den platz des am Gürtel hängenden Tasers einnehmen. Werden also zwei Taser Angezeigt. Beim Zweiten Bild glitcht die ausgerüstete Pistole durch die Pistole im Holster.

**Comment by Enemyaa** [comment]
Das Ding ist, dass dieser Gürtel einmalig ist. Es gibt ihn gar nicht ungeholstert und den gab es auch auf Rage nicht ungeholstert. Ihr equiped also einen geholsterten Gürtel mit noch einer Waffe und dann sieht das wohl so aus. Da kann man alternativ wohl nur den Gürtel wechseln oder es hat jemand das Gegenstück dazu, dann kann er es mir gerne zukommen lassen.

**Comment by Irishman1991** [comment]
Also es muss ihn ungeholstert geben... 
![Cliping_fehler_3](https://user-images.githubusercontent.com/75093060/100457522-77679d80-30c2-11eb-802c-1b29cc8a0bfd.png)
![Cliping_fehler_4](https://user-images.githubusercontent.com/75093060/100457542-7e8eab80-30c2-11eb-8ce1-2c7c5cead130.png)

Ansonsten würde vielleicht ein update helfen (würde uns sehr freuen ;) ) https://www.lcpdfr.com/downloads/gta5mods/character/8151-emergency-uniforms-pack-law-order/

**Comment by Enemyaa** [comment]
@Irishman1991 Du trägst da aber 2 verschiedene Ausrüstungsstücke. Denn du hast ja auf dem Bild den Gürtel an den es nur mit Taser gibt und das Holster ohne Waffe, was es wiederum auch mit Waffe gibt.
Zum Thema EUP kann ich dir nur sagen - wir nutzen kein EUP mehr! Neue PD Kleidung steht aber auf jeden Fall auf der Liste, allerdings stehen momentan Server Performance und einige Bugs im Vordergrund.
