### ISSUE TITLE
Bereits tätowierte Stelle nicht doppelt tätowierbar?

### ISSUE THREAD

**Issue by Koree7** [mexyn/statev_v2_issues#580]
Wollte jemandem eine Tattoo-Kombi stechen, was nicht (mehr?) möglich ist.
"Diese Stelle ist bereits tätowiert." Kam als Meldung.
Fehler oder gewollt?

**Comment by its4l3x** [comment]
Korrekt. Wir unterscheiden hier in Zonen. Wenn diese Zone bereits einmal vorhanden ist, geht das nicht. Daher kein Bug.

**Comment by its4l3x** [comment]
Planänderung. Nachdem ich gerade angeschrieben worden bin und wir durch einen kurzen Meinungsaustausch uns ausgetauscht haben sind wir zum Entschluss gekommen, diesen Check wieder rauszunehmen.
