### ISSUE TITLE
Tankwert wird falsch angezeigt

### ISSUE THREAD

**Issue by Noah9461** [mexyn/statev_v2_issues#581]
**Character Name**
Noah Draper

**Zeitpunkt (Datum / Uhrzeit)**
26.11  21:06

**Beobachtetes Verhalten**
Auto wird für 10L getankt, nachdem die Animation fertig ist, stehen 100Liter als Summe drin

**Erwartetes Verhalten**
Richtige Anzeige der Tankfüllung

**Schritte um den Fehler nachvollziehen zu können**
Auto tanken, danach auf die Literanzahl achten

![image](https://user-images.githubusercontent.com/71601830/100388656-7fc0c980-302b-11eb-889a-71b5fb3f4f18.png)

**Comment by its4l3x** [comment]
Immer noch beständig?

**Comment by DonVitoDiangelo** [comment]
Falls der Fehler erneut auftritt. neu öffnen.
