### ISSUE TITLE
Handy Animation Bug

### ISSUE THREAD

**Issue by Noah9461** [mexyn/statev_v2_issues#582]
**Character Name**
Noah Draper

**Zeitpunkt (Datum / Uhrzeit)**
Jederzeit

**1.1.Beobachtetes Verhalten**
Mit dem Handy kann man die Waffenanrüstanimation unterbrechen, somit sieht man nicht ob jemand eine Waffe anlegt

**1.2.Erwartetes Verhalten**
Animation soll ausgeführt werden

**1.3.Schritte um den Fehler nachvollziehen zu können**
Inventar öffnen, danach das Handy öffnen und die Waffe in den Slot ziehen. Animation wird nicht ausgeführt da Handyanimation dazwischen ist. 

**2.1.Beobachtetes Verhalten**
Handy wurde vor Faustkampf geöffnet, danach ging der Kampf 2 Sekunden und der Gegner lag. 

**2.2.Erwartetes Verhalten**
Normaler Damage nach Handynutzung?

**2.3.Schritte um den Fehler nachvollziehen zu können**
Handy öffnen, schließen und dann schlagen

**Comment by Hawtin1** [comment]
https://www.youtube.com/watch?v=xbK2WPfunXQ&feature=youtu.be

**Comment by its4l3x** [comment]
Sollte seit dem vorletzten Update behoben sein :)
