### ISSUE TITLE
Avarus und Hexer lassen sich nicht tanken

### ISSUE THREAD

**Issue by HolyEddi** [mexyn/statev_v2_issues#583]
**Character Name**

Eddi Lakus

**Zeitpunkt (Datum / Uhrzeit)**

24.11.2020

**Beobachtetes Verhalten**

Beim Fahren verringert sich nicht die Menge des Benzins im Tank, stattdessen wird das Tankvolumen kleiner. Somit wird der Tank trotz Verbrauch immer als voll angezeigt und die Fahrzeuge lassen sich nicht tanken

**Erwartetes Verhalten**

Tank voll, wird beim Fahren entleert, lässt sich nachtanken

**Schritte um den Fehler nachvollziehen zu können**

Beim Fahren die Tankanzeige beobachten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![avarus_LI](https://user-images.githubusercontent.com/74856205/100390634-6589ea00-3031-11eb-9562-d97b1f36833f.jpg)

**Comment by DonVitoDiangelo** [comment]
@ GD bitte gegen checken

**Comment by DrGrizzlY17** [comment]
Konnte ich nicht reproduzieren. Das maximum bei Avarus und Hexer sind 30L im Tank, solltest du >29L im Tank kannst du nicht tanken. Sollte das nochmal auftreten, mal ab und aufsteigen. Ansonsten nochmal melden
