### ISSUE TITLE
Kleiner Rechtschreibfehler beim Bewegungsstil Menü

### ISSUE THREAD

**Issue by m4xellde** [mexyn/statev_v2_issues#584]
**Character Name**
Thomas Stone

**Zeitpunkt (Datum / Uhrzeit)**
26.11 22:20

**Beobachtetes Verhalten**
Schreibfehler bei dem Bewegungsstil Rasierklinge unter den Achseln

**Erwartetes Verhalten**
Das k von Raskierklinge weg xD

**Schritte um den Fehler nachvollziehen zu können**
Einfach Stilmenü öffnen und nach dem Stil "Rasierklingen unter den Achseln" suchen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![GTA5_0ExLBYC2Xc](https://user-images.githubusercontent.com/75097512/100392507-11820400-3037-11eb-93bf-a80d11cc347d.png)

**Comment by Enemyaa** [comment]
Danke für die Info ;)
