### ISSUE TITLE
Antrag auf ein Müllcontainer & Bankautomat an der Yellow Jack Inn Bar

### ISSUE THREAD

**Issue by Pablito90** [mexyn/statev_v2_issues#586]
Pablito_Suarez

**Zeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

Wir wünschen uns an unserer Bar in Sandy Shores ein Müllcontainer und am liebsten auch ein Bankautomat. Wir führen regelmäßig Events, jede Woche min. 1 an der Bar. Es wäre Praktisch für die Gäste die Möglichkeit zu geben Ihren Müll los zu werden. 
Der Bankautomat wäre Praktisch da man in der Bar, Bar zahlen muss und beim Events auch oft gern Bar bezahlt wird aber da vergisst man gern mal Geld abzuheben. Ebenso für unseren Glückspiel Abende wäre es Nice das ganze mit Bargeld zu machen. 
**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Müllcontainer solved,
ATM @DonVitoDiangelo
