### ISSUE TITLE
Sind Lackrechner und Tuning nun richtig eingestellt?

### ISSUE THREAD

**Issue by thumbsucker** [mexyn/statev_v2_issues#587]
**Character Name**
Riley Everett

**Zeitpunkt (Datum / Uhrzeit)**
//

**Beobachtetes Verhalten**
Wenn nur Metallic Lack lackiert wird, bleibt der Verbrauch immer bei 4x Basis und 2x Schwarz. Bei Matt mit Perleffekt wird auch nur mehr Lack und nicht wie zuvor mehr Staub verbraucht (Staub bleibt immer bei 2x Perlen 2x Dia). Ist das so gewollt und darf so weiter lackiert werden oder wird da nochmal etwas angepasst?

Wenn bei Felgen NUR Farbe drauf soll und keine neuen Felgen, wird nicht angezeigt was verbraucht wird und es wird auch nichts im Lager abgezogen. Ist dies so gewollt? 

**Erwartetes Verhalten**
Ggf. sollte bei reinem Metallic Lack auch weitere Farben verwendet werden? Dies würde dann aber wohl auch wieder die ganze Berechnung für Perleffekt ändern.

Wenn Felgen eingefärbt werden sollten vielleicht 2 oder 3 Lackdosen ebenfalls verbraucht werden

**Optional: Video / Bilder des Fehlers**
![Desktop Screenshot 2020 11 26 - 23 38 13 43](https://user-images.githubusercontent.com/74800184/100401889-18227280-305b-11eb-9b19-57416dbbe495.png)

![Desktop Screenshot 2020 11 26 - 23 39 12 49](https://user-images.githubusercontent.com/74800184/100401920-296b7f00-305b-11eb-9e75-87be2e8ad136.png)

![Desktop Screenshot 2020 11 26 - 23 58 19 25](https://user-images.githubusercontent.com/74800184/100402029-8830f880-305b-11eb-8d8a-0a255abfe31e.png)

**Comment by DonVitoDiangelo** [comment]
0-11 etc. adden. Bei fragen an mich wenden.
