### ISSUE TITLE
Error in der Log

### ISSUE THREAD

**Issue by mK33y** [mexyn/statev_v2_issues#588]
Micheal_Miller

Siehe Log

Siehe Log

Habe mich in der Fahrzeugherstellung ausgeloggt. Hab mich wie man in der Log entnehmen kann wieder eingeloggt und bekam diese Error Meldung ohne mich irgendwie bewegt zu haben. Nach einem relog kam die Meldung immer noch.
Fahrzeugfertigung in der ich drin war/bin.

FirmenHash: pfEveMorningwoodRew_11

[error.log](https://github.com/mexyn/statev_v2_issues/files/5606861/error.log)

**Comment by r3sist3nt** [comment]
Der log ist egal.
Hattest du sonst noch irgendwelche Fehler?

**Comment by mK33y** [comment]
Okay interessant, wenn ERROR Logs egal sind..
Nein ich hatte keine Weiteren Fehler.
