### ISSUE TITLE
Antrag Garage

### ISSUE THREAD

**Issue by Micha190** [mexyn/statev_v2_issues#589]
**Michy_Sauerland**

**Zeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
Hiermit beantrage ich eine Garage zu meinem Haus. Ist nicht das schönste Anwesen, aber vielleicht ist es möglich.
Platz ist genug vorhanden.
![Paleto Haus 8](https://user-images.githubusercontent.com/75121724/100442105-cc49ea80-30a7-11eb-8bc4-835a3e1174ca.jpg)

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Abgelehnt
