### ISSUE TITLE
Schuhe käfern durch lange Hosen

### ISSUE THREAD

**Issue by Gee1337** [mexyn/statev_v2_issues#59]
**Zeitpunkt (Datum / Uhrzeit)**
26.08.2020 / 01:35

**Beobachtetes Verhalten**
Valenciaga Sneaker inkl. alle Boots bis auf Westernstiefel X käfern durch lange Hosen.

**Erwartetes Verhalten**
Schuhe sollten unter der Hose sein

**Optional: Video / Bilder des Fehlers**
![schuhe1](https://user-images.githubusercontent.com/70242468/91238252-ea1c5200-e73c-11ea-979d-ab26613c160c.PNG)
![schuhe2](https://user-images.githubusercontent.com/70242468/91238294-04eec680-e73d-11ea-99fa-e21546ff55d2.PNG)

**Comment by tastydev** [comment]
GTA behaviour
