### ISSUE TITLE
Antrag auf ein Müllcontainer für die Green Gas Tankstelle

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#590]
Würde mir für die Kunden gerne einen Müllcontainer an meiner Tankstelle wünschen. Die Tankstelle wird sehr stark bespielt und hat ein großes Konzept (siehe www.thegreen-group.de).
Rechts vom Tankstellengebäude sind normale Mülleimer, dort würde ein Container gut hin passen. Ich bedanke mich.

Calais Ave./Innocence Blvd. 58
Hash: petrolstation8

![image](https://user-images.githubusercontent.com/33394632/100444126-3c0da480-30ab-11eb-8d14-4142642f12a0.png)

**Comment by DrGrizzlY17** [comment]
Da man dort nichts erwerben kann, das "Müll" produziert, sehe ich keinen Grund unnötig auf der Map Gegenstände zu platzieren. Für Restaurants, Shops, etc. die Sachen verkaufen macht das durchaus mehr Sinn
