### ISSUE TITLE
Fahrzeug nach Betreten einer Firma verschwunden

### ISSUE THREAD

**Issue by mK33y** [mexyn/statev_v2_issues#591]
**Character Name**
Micheal Miller

**Zeitpunkt (Datum / Uhrzeit)**
ca. 12:30 Uhr

**Beobachtetes Verhalten**

Ich hab meine Fahrzeug vor der Firma (Firmen Hash: MurrietaHights2) abgestellt gehabt, höhe des Ladepunktes ziemlich an der Wand dran, so das man vorne vorbei laufen konnte noch. Ich war 20min in der Firma kam raus und mein Fahrzeug stand an einer Stelle wo ich es zuvor noch nie abgestellt hatte.

**Erwartetes Verhalten**

Das mein Fahrzeug da stehen bleibt wo ich es abgestellt habe und zwar vor der besagten Firma.

**Schritte um den Fehler nachvollziehen zu können**

[client_27-11-2020_09-58-06.log](https://github.com/mexyn/statev_v2_issues/files/5607727/client_27-11-2020_09-58-06.log)
Das ist das einzige was ich sagen kann, wie dieser Fehler zustande kam, keinerlei Ahnung.
Des Weiteren fällt mir gerade in den Logs auf da steht dieser Eintrag: [12:52:53][Error] Attachments Error: Unknown Attachment Used: WDSP_GADGET_PARACHUTE, ich besitze aber kein Fallschirm. Nichts desto trotz, ihr wisst am besten was hier falsch ist. Danke für eure Arbeit. 

**Optional: Video / Bilder des Fehlers**

Fahrzeug Stand an dieser Position https://prnt.sc/vr6im7

**Comment by r3sist3nt** [comment]
Bereits bekannt. Siehe #400 .
