### ISSUE TITLE
[Interior] Office - fehlende Stühle

### ISSUE THREAD

**Issue by h3adbang3r** [mexyn/statev_v2_issues#592]
**Zeitpunkt (Datum / Uhrzeit)**
seit Release

**Beobachtetes Verhalten**
fehlende Stühle im Office
2x am Schreibtisch
1x am Empfang
1x in der Gardeobe

**Erwartetes Verhalten**
die fehlenden Stühle sollten vorhanden sein

**Schritte um den Fehler nachvollziehen zu können**
beliebiges Büro betreten

**Optional: Video / Bilder des Fehlers**
![2020_1127-131043](https://user-images.githubusercontent.com/15799077/100448683-fa80f780-30b2-11eb-83a2-fd7012bdb0c8.png)
![2020_1127-131055](https://user-images.githubusercontent.com/15799077/100448704-01a80580-30b3-11eb-9586-720871c05e30.png)
![2020_1127-131118](https://user-images.githubusercontent.com/15799077/100448711-04a2f600-30b3-11eb-9811-58218a5cfa3f.png)

**Comment by DonVitoDiangelo** [comment]
Nn dem Interior bitte selbst hinstellen.

**Comment by h3adbang3r** [comment]
Leider lässt sich im Interior nichts
![2020_1201-113949 (2)](https://user-images.githubusercontent.com/15799077/100730275-26a9ba80-33ca-11eb-91bd-9d0463d2ab67.png)
 aufstellen
