### ISSUE TITLE
Weibliche Snapbacks haben nach anziehen zwei seitliche Zöpfe.

### ISSUE THREAD

**Issue by FIOX25** [mexyn/statev_v2_issues#593]
**Marie_Kronewald**
 Mit meinem eigenen

**Zeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
 Sobald ich die neuen Snapbacks anziehe habe ich zwei Zöpfe obwohl meine Frisur eine andere ist

**Erwartetes Verhalten**
Keine Zöpfe mehr

**Schritte um den Fehler nachvollziehen zu können**
 Snapback kaufen,Snapback aufziehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Gewollt
