### ISSUE TITLE
Tättowierer kann sich nicht mehr im Auswahl Menü über Taste N bewegen

### ISSUE THREAD

**Issue by SandyFolk** [mexyn/statev_v2_issues#594]
Sandy_Folk
**Character Name**
Sandy_Folk

**Zeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
Als Tättowierer konnte man sich bisher per N-Taste frei bewegen um sich vernünftig zum Kunden zu stellen und eventuell auch die Vorlage gut sehen kann damit man dem Kunden auch etwas besser was zur Vorlage sagen zu können.

**Erwartetes Verhalten**
Wie beim Friseur sollte man sich im Auswahlmenü wieder per N-Taste bewegen können sollen

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Chrinis007** [comment]
Generell sollte die N Taste wieder aktiviert werden, nicht nur wenn du n Ausweis in der Hand hast

**Comment by r3sist3nt** [comment]
die taste N ist für bestimmte menüs freigeschaltet

**Comment by r3sist3nt** [comment]
Ich habe die Taste hier aber wieder aktiviert.
