### ISSUE TITLE
Einkauf Waren Firma

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#596]
Wenn man z.b 12 Waren mit Preis ins System für den Ankauf eingegeben hat und man später den Preis für eine Ware ändern möchte wird die ganze Warenliste gelöscht und man muss alles neu eingeben.

Das ist ja nicht Sinn der Sache :)

**Comment by Craig-Statev** [comment]
Kann das bestätgen, der Effekt bei mir war so das ich 10 Items eingetragen habe und wenn ich das 2. von den Lösche/Ändern will werden alle gelöscht die danach kommen. somit war nur noch 1 Item vorhanden.

**Comment by Statev-Bonsai** [comment]
Ich hole es nochmal hoch, das ist wirklich sehr sehr nervend :(

**Comment by its4l3x** [comment]
Habe das mal gemacht...

Ist im nächsten Update mit enthalten ;)

**Comment by Statev-Bonsai** [comment]
Dankeeeeeeeeeeeeeeee...yahuuuuuuuuuu
