### ISSUE TITLE
Haare clippen teilweise noch durch die Mützen

### ISSUE THREAD

**Issue by Naaki6** [mexyn/statev_v2_issues#597]
**Character Name**

Owen West
**Zeitpunkt (Datum / Uhrzeit)**

immer.
**Beobachtetes Verhalten**

Mittlerweile funktioniert es, wenn man mit den neuen Frisuren Bucket Hat, Danbanna etc. aufsetzt das die Frisur nicht durch clippt. Wenn man aber ein anderes Teil (T-Shirt, Bandana etc.) umzieht dann clippen die Haare wieder durch und man muss die Mützen einmal neu aufsetzten.
**Erwartetes Verhalten**

Haare sollten auch dann nicht durch clippen.
**Schritte um den Fehler nachvollziehen zu können**

Mütze aufziehen, T-Shirt, Bandana oder der gleichen ausziehen und ein anderes Teil anziehen und die Haare clippen wieder durch die Frisur.
![Simba 3](https://user-images.githubusercontent.com/74776926/100461874-aa615f80-30c9-11eb-8bfd-6756ccb1fc95.png)
![Simba 1](https://user-images.githubusercontent.com/74776926/100461878-acc3b980-30c9-11eb-93d4-c19647a92d61.png)
![Simba 2](https://user-images.githubusercontent.com/74776926/100461888-b0efd700-30c9-11eb-843f-1854aa35d6c2.png)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Das Cap/Die Mütze muss man aktuell immer als letztes aufsetzen. bekannt, danke.

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/709

**Comment by rEd0r** [comment]
Wie schauts aus mit dem bug ?

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1227

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1228

**Comment by TheBroady** [comment]
Nach einem Kleiderwechsel Clippen Haare die eigentlich Funktionieren wieder durch Mützen etc.
https://www.youtube.com/watch?v=fUJy1Q1mrQA

**Comment by Mr-Chris-VRTY** [comment]
Bug nach wie vor aktuell. Bei allen neuen Police Caps der Fall. Fix mit Beanie funktioniert nicht
![image](https://user-images.githubusercontent.com/70213538/118254903-dde34b00-b4ab-11eb-97e0-cdd70bc7b567.png)
![image](https://user-images.githubusercontent.com/70213538/118254921-e2a7ff00-b4ab-11eb-838d-b5e91761dfe9.png)

**Comment by TheOutburst** [comment]
Durch Haarauswahl schon länger fixed
