### ISSUE TITLE
E-Ladestation Buggt

### ISSUE THREAD

**Issue by Domeex3** [mexyn/statev_v2_issues#598]
Domenik_Sommer

26.11.2020, 19:30 Paleto Tankstelle bei der Werkstatt

**Beobachtetes Verhalten**
Die Ladesäule war soweit fertig mit laden (99%) zeigte aber an das sie noch 1kw/h laden könnte, habe den Vorgang also gestartet, die zeit lief wie gewohnt auf 00:00 und stoppte dort, beendete aber nicht. Auch auf den versuch hin den Ladevorgang manuell zu stoppen blieb die Zeit auf 00:00 jedoch wurden bei jedem Click auf Abbrechen -> JA! der Preis pro kw/h abgebucht und es erschien die Meldung diese Tankstelle hat keine Energie mehr. Das Fahrzeug musste über den Support eingeparkt werden da zugriff aufs Fahrzeug ebenfalls durchs laden blockiert war.

Zeit fertig -> Vorgang beendet -> Wegfahren

https://youtu.be/s_GgLGFdlNE

**Comment by r3sist3nt** [comment]
Fixed nach nächstem Update.
