### ISSUE TITLE
Cop Mustang - Reifen Platzen direkt nach Reperatur wieder auf

### ISSUE THREAD

**Issue by AideenCarter** [mexyn/statev_v2_issues#60]
**Zeitpunkt (Datum / Uhrzeit)**
Day 2 Beta Phase 2 - 02:22

**Beobachtetes Verhalten**

Cop Mustang Platzen instant die Reifen wieder nachdem er repariert wurde in einer Werkstatt.
**Erwartetes Verhalten**

Sollte vollständig repariert sein.
**Schritte um den Fehler nachvollziehen zu können**

Reifen Kaputt machen und in eine Werkstatt fahren
**Optional: Video / Bilder des Fehlers**

**Comment by mexyn** [comment]
wir warten hier auf einen Fix von altV
