### ISSUE TITLE
E-Säulen "Ladepunkt nicht gefunden"

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#601]
**Character Name**
Marvin_Elpe

**Zeitpunkt (Datum / Uhrzeit)**
27.11.2020 18:40

**Beobachtetes Verhalten**
Beim aufladen von E-Fahrzeugen kommt jetzt folgende Fehlermeldung: "Ladepunkt nicht gefunden! Bitte starte den Vorgang erneut!". Habe das Auto auch mehrfach umgestellt, kommt immer wieder auch bei anderen E-Säulen.

**Erwartetes Verhalten**
Aufladen funktioniert.

**Schritte um den Fehler nachvollziehen zu können**
E-Auto an E-Säule aufladen.

**Optional: Video / Bilder des Fehlers**
![](https://pic.statev.de/i/GkCSP.jpg)

**Comment by KruemelGames** [comment]
Kann den Bug bestätigen, gleiches Problem mit meinem Coil Raiden.

**Comment by Kalumel** [comment]
Kann es auch bestätigen. Versucht an einer Tankstelle wo definitiv Akkuzellen zu Verfügung standen.

**Comment by MrGotAB** [comment]
21:40 Uhr an mehreren Tankstellen mit Pfister Neon versucht
Fehlermeldung: Auto nicht gefunden

**Comment by r3sist3nt** [comment]
Parkt mal das Auto ein und wieder aus. Schaut mal ob das dann klappt.

**Comment by Domeex3** [comment]
Auto aus und einparken brachte nichts außer das der Fehler jetzt nu ein anderer ist. :"Auto nicht gefunden!"

**Comment by r3sist3nt** [comment]
Anscheinend wurde die UI beim letzten Update von Gameserver nicht richtig aktualisiert. Daher der Fehler. Sollte daher nach dem nächsten Update behoben sein.

**Comment by r3sist3nt** [comment]
(Ich lasse das doch noch offen, damit andere das sehen)
