### ISSUE TITLE
Ins Bett geglitcht

### ISSUE THREAD

**Issue by Headmonsta** [mexyn/statev_v2_issues#602]
**Character Name**

Uri_Holiday

**Zeitpunkt (Datum / Uhrzeit)**

27.11.202. 19:30

**Beobachtetes Verhalten**

Beim Hinlegen über das Y Menu auf der rechten Seite glitcht man sich in das Bett hinein. Hausinterior ist "Luxury Apartment Modern Rustical".

**Erwartetes Verhalten**

Man sollte auf dem Bett liegen

**Schritte um den Fehler nachvollziehen zu können**

an die rechte Seite treten. Y drücken. Eine der Animationen auswählen. Reinglitchen. 

**Optional: Video / Bilder des Fehlers**

link zum Video: https://youtu.be/pJqsQ49_HIM

**Comment by DonVitoDiangelo** [comment]
Kann mal passieren, konnte ich jetzt nicht reproduzieren.
