### ISSUE TITLE
Gamechrases MD

### ISSUE THREAD

**Issue by LukeRiley1507** [mexyn/statev_v2_issues#603]
Luke_Riley

Luke Riley
**Zeitpunkt (Datum / Uhrzeit)**

26.11.2020 23.30
**Beobachtetes Verhalten**
Mehrere Gamechrashes im MD beim stehen im MD und das mehrfach hintereinander ohne irgendeine Fehlermeldung zu bekommen

**Erwartetes Verhalten**
Keine Gamechrashes

**Schritte um den Fehler nachvollziehen zu können**
Kann ich nicht genau sagen das ich nur im MD stand und mein Spiel ständig abstürzte

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
keine Reproduktion möglich. Eventuell kannst du den letzten log von nach einem Crash hochladen.

**Comment by LukeRiley1507** [comment]
Wo genau finde ich den denn?


DonVitoDiangelo <notifications@github.com> schrieb am Fr., 27. Nov. 2020,
20:14:

**Comment by LukeRiley1507** [comment]
[altv_1301_Steam_0x621931930_27-11-2020_20-53-14.zip](https://github.com/mexyn/statev_v2_issues/files/5609607/altv_1301_Steam_0x621931930_27-11-2020_20-53-14.zip)

**Comment by DonVitoDiangelo** [comment]
Danke. Leider gibt es im normalen log keine hinweis auf irgendetwas. Ist dein GTA auch sicher eine "saubere" Installation und dein Rechner halbwegs potent? Diese harten Crashes sind mMn. auf ein lokales Problem zurück zu führen. Wie ergeht es Spielern in deiner Umgebung.

**Comment by DrGrizzlY17** [comment]
@DonVitoDiangelo hab ihm mal empfohlen reshade etc. runter zu schmeißen. Er hat direkt alles neu gemacht, seitdem ist deutlich besser.
