### ISSUE TITLE
Antrag auf Umbauarbeiten/ Lagermöglichkeit eines Krad

### ISSUE THREAD

**Issue by Stiefel911** [mexyn/statev_v2_issues#604]
Grand Senora Road 2440
Wohntrailer (Doppeltrailer der hintere)
Haushash | JunSandyShoresRew_House_21

Ich dachte mir wer es nicht versucht kann auch gleich sich "einbuddeln" :-D

gedacht ist für **ein** Zweirrad eine Unterstellmöglichkeit. Kein Auto sondern wirklich nur ein Moped.

Anbei habe ich natürlich auch ein Bild erstellt zur Veranschaulichung, da ist auch direkt zu sehen, PKW etc, würde eh keinen sinn bringen. Optisch könnten auch mehrer Bikes rein passen, aber das muß ja nicht.
![StateV Garagenwunsch](https://user-images.githubusercontent.com/74860269/100477967-15229300-30ea-11eb-816b-b24cc53fd1a5.png)

Flagge (rot) zum einparken, deswegen auch eine Holzrampe. Irgendwie muß ich das Moped ja auch reinschieben können!
Und der Kreis in Pfeilrichtung zum ausparken.

_Dreistigkeit siegt_?

so Long

P.s.: _gibt es ein facepalm, dann ist es eben so_

**Comment by DonVitoDiangelo** [comment]
Abgelehnt
