### ISSUE TITLE
Fahrzeug- Folienänderung

### ISSUE THREAD

**Issue by Krapfal** [mexyn/statev_v2_issues#605]
**Lundro_Lagu**

Lundro_Lagu
**Zeitpunkt (Datum / Uhrzeit)**

27.11.2020 / 20:30
**Beobachtetes Verhalten**

Fahrzeug - Windsor Drop - Kennzeichen - SAHK03LL ändert nach ein und ausparken die Folie 
**Erwartetes Verhalten**

Keine Folie =D
**Schritte um den Fehler nachvollziehen zu können**

Fahrzeug einparken -> Ausparken -> Neue Folie - Einparken - Ausparken - wieder eine andere
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

Fahrzeug einparken -> Ausparken ->  - Einparken - Ausparken
**Optional: Video / Bilder des Fehlers**

![Drop1](https://user-images.githubusercontent.com/70897064/100479918-fa531d00-30ef-11eb-9129-ad23619c73f8.png)
![Drop2](https://user-images.githubusercontent.com/70897064/100479920-fde6a400-30ef-11eb-9097-0d5c9181428a.png)

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/301
