### ISSUE TITLE
E-Auto Ladesäule Fehler

### ISSUE THREAD

**Issue by Domeex3** [mexyn/statev_v2_issues#606]
Domenik_Sommer + Bobby William

27.11.2020 ca. 20:30Uhr

Es war weder mir noch der zweiten Person möglich ihr E-Auto (Coil Voltic & Pfister Neon) zu laden da immer der Fehler "Ladepunkt nicht Gefunden! Bitte starte den Vorgang erneut!" kam, egal wie das Auto stand. Fehler trat sowohl beim Laden von 1 KW/h als auch beim Volltanken auf.

https://prnt.sc/vrg1sp

**Comment by Kalumel** [comment]
#601

**Comment by MrGotAB** [comment]
21:40 Uhr an mehreren Tankstellen mit Pfister Neon versucht
Fehlermeldung: Auto nicht gefunden
