### ISSUE TITLE
Haus Kauf nicht möglich

### ISSUE THREAD

**Issue by Daniel160982** [mexyn/statev_v2_issues#607]
**Daniel_Rossi**
 
Daniel_Rossi

**Zeitpunkt (Datum / Uhrzeit)**

27.11.2020 um 21:00 Uhr

**Beobachtetes Verhalten**

Kaufbares Haus in Sandy zeigt die Meldung "Das Objekt kann nicht Verkauft werden wenn es bereits Vermietet ist" Es ich aber kein Besitzer drauf und man kann auf Kaufen Klicken, dann kommt die Meldung.

**Erwartetes Verhalten**

Ich sollte das Haus Kaufen können

**Schritte um den Fehler nachvollziehen zu können**

An die die Tür gehen und versuchen das Haus zu Kaufen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
 
![ha](https://user-images.githubusercontent.com/75142290/100482146-ba436880-30f6-11eb-92dd-4a81fb8b7d81.JPG)

**Comment by Statev-Bonsai** [comment]
Das Haus gehört einem Spieler, es hat einen Kaufpreis eingetragen aber es ist noch vermietet.
War schon öfters Thema im Bugtracker..

**Comment by Daniel160982** [comment]
Ok Danke, dass heißt man kann nichts machen oder?

**Comment by Statev-Bonsai** [comment]
richtig :)

**Comment by Daniel160982** [comment]
Ok Schade, aber Danke
