### ISSUE TITLE
Entladepunkt bitte versetzten 

### ISSUE THREAD

**Issue by JosefRitter** [mexyn/statev_v2_issues#608]
**Character Name**
<!-- Josef_Ritter

<!--- Ich möchte nur darum bitten wie untem im Bild zu sehen den Entladepunkt zu verändern.

**Optional: Video / Bilder des Fehlers**
<!--- https://media.discordapp.net/attachments/780248836823449622/780249094261309480/Ablagepunkt_jpeg.jpg?width=308&height=467

**Comment by DrGrizzlY17** [comment]
?
