### ISSUE TITLE
Dupe Bug beim Öl Tanken

### ISSUE THREAD

**Issue by powerswissi** [mexyn/statev_v2_issues#609]
**Character Name**

Roger_Thickle

**Zeitpunkt (Datum / Uhrzeit)**

27 November 2020 22.20 Uhr

**Beobachtetes Verhalten**

Hatte das Tablet in der Hand. Hatte abgepumpt.. Am grossen Ölfeld. Hab eine Nachricht geschrieben. Oben lief der Balken durch 100% -> Tablet weggelegt .. I gedrückt.. Und dann stand dort 1200 Liter Öl mit 2x Fahrzeuginventar

**Erwartetes Verhalten**

sollte wohl so nicht sein 

**Schritte um den Fehler nachvollziehen zu können**

Auf Plattform stellen
E drücken 
Tablet in der Hand
Balken durchlaufen lassen
kurz warten
I drücken 
rüberziehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by r3sist3nt** [comment]
Konntest du wirklich dupen, oder wurde das nur angezeigt?

**Comment by powerswissi** [comment]
Ich hab mal probiert 10 liter rüberzuziehen.. das ging.. hab die 10 liter dann wieder rausgepumpt beim nächste ladestelle

**Comment by DonVitoDiangelo** [comment]
Der Weg ist ja so an sich normal. Du kannst nach dem Vorgang dann noch einmal "I" drücken, um das Fenster zu öffnen.
Beim Versuch dies zu reproduzieren konnte ich einen solchen Wert nicht feststellen, nur die normalen Werte. 

@powerswissi  Hattest du das schon öfter?

**Comment by powerswissi** [comment]
Jap hatte das schon mal öfters.. dachte zuerst irgendwie an nen bug. War nur immer kleinere Sachen z.b 12 liter.. 20 liter.. 15 Liter. hab das nicht näher beobachtet. hab einfach i gedrückt und hab im RP getan als hätte ich nur 10 Liter..

Es steht dann so 
Inventar Fahrzeug Fahrzeug

so stehen die Boxen aus


Die tritt auch nur manchmal auf. Komplett Random. Gestern isses mir halt nur aufgefallen das da plötzlich 1200 Liter standen

Es stand dann so

Inventar         Fahrzeug                     Fahrzeug 1200/1200
                    754 Liter Öl                   1200 Liter Öl

Dies passiert echt random aber auch nur wenn man das Tablet auf hat. Die 100% durchlaufen lässt .. Sonst passiert das nicht..
Ich teste das heute nochmal ob ichs triggern kann und lass Shadowplay laufen

**Comment by DonVitoDiangelo** [comment]
Ja wie gesagt. Das nach dem farmen wenn Tablet offen war, nochmal öffnen, ist so gewollt. Wenn dann normale Werte zu sehen sind ist das ok. Aber vllt. habe ich das gerade falsch vor Augen. Am besten mal nen Video dsazu.

**Comment by powerswissi** [comment]
ja das konnte ich triggern.. sind normale werte.. aber der volle konnte ich noch nicht erneut triggern
