### ISSUE TITLE
Verladen von Gebäude in Fahrzeuge nicht möglich

### ISSUE THREAD

**Issue by DerHessenTyp** [mexyn/statev_v2_issues#61]
**Zeitpunkt (26.08.2020 / 02:25 Uhr)**

**Beobachtetes Verhalten**
Egal von welchem Lagerort in welches Fahrzeug (Versucht aus Giesserei, Lagerhaus, Mühle,Labor,Friseur in Pounder,Benson oder Phantom) ist nicht möglich, dort kommt die Fehlermeldung ,,error.inventory.entity.invalid" Vom Rucksack ins Lager legen funktioniert und von Rucksack ins Fahrzeug in Kofferraum legen funktioniert auch.

**Erwartetes Verhalten**
Man stellt sein Auto auf den Abladepunkt geht an die Tür des Gebäudes und Belädt und entlädt sein Fahrzeug. 

**Schritte um den Fehler nachvollziehen zu können**
Ich fahre auf den Abladepunkt und versuche Produkte vom Lager ins Fahrzeug zu laden und es kommt die Fehlermeldung

**Optional: Video / Bilder des Fehlers**
![Keine verladung möglich](https://user-images.githubusercontent.com/70151958/91241357-f3112180-e744-11ea-9acd-f811a905b805.jpg)

**Comment by its4l3x** [comment]
Kofferraum nicht offen :)

**Comment by DerHessenTyp** [comment]
Gerade mit offenem Kofferraum getestet. Da funktioniert es. Aber bei geschlossenem Kofferraum (Eigenes Fahrzeug) kommt die Fehlermeldung.

**Comment by its4l3x** [comment]
Korrekt. Auch wenns dein eigenes Fahrzeug ist, muss der Kofferraum bei sowas aufgemacht werden :D

**Comment by DerHessenTyp** [comment]
Finde ich Super.
