### ISSUE TITLE
Ändern der Notify Position(F7) funktioniert nicht.

### ISSUE THREAD

**Issue by djshatterz** [mexyn/statev_v2_issues#610]
**Character Name**

Damian_Braun

**Zeitpunkt (Datum / Uhrzeit)**

27.11.2020

**Beobachtetes Verhalten**

Wenn ich mit der F7 taste zu den Settings gehe und die Notify Position änder, hat das ganze keinen Einfluss egal auf was ich es Stelle. Auch nicht nach einem Gamerestart.

**Erwartetes Verhalten**

Die Position sollte sich beim umstellen ändern.

https://we.tl/t-KM7zcBr358

**Comment by its4l3x** [comment]
Korrekt. Ist ein Feature welches von einer Seite fertig war, aber von der anderen nicht. Lasst euch/dich noch überraschen wenn das Feature fertig entwickelt wurde...
