### ISSUE TITLE
Telefon zeigt keine Telefonierdauer über 1h Stunde an

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#611]
**Character Name**
Jannik_Datsch

**Zeitpunkt (Datum / Uhrzeit)**
28.11.2020 00:01

**Beobachtetes Verhalten**
Nach der Telefonierdauer von 1h Stunde setzt das Handy den Timer wieder zurück, statt das die 1h dabei steht

**Erwartetes Verhalten**
Die Dauer sollte korrekt dort stehen

**Schritte um den Fehler nachvollziehen zu können**
Telefonieren über 1h 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Ihr habt for real ne Stunde telefoniert?

**Comment by Chrinis007** [comment]
Setzt sich leider zurück, hab letztens auch 2.5h telefoniert

**Comment by its4l3x** [comment]
Habe es gefixed. Ist im nächsten Update enthalten.
