### ISSUE TITLE
Kokstisch verbuggt

### ISSUE THREAD

**Issue by Noah9461** [mexyn/statev_v2_issues#613]
**Character Name**
Noah Draper

**Zeitpunkt (Datum / Uhrzeit)**
28.11 00:40

**Beobachtetes Verhalten**
Verabeitungstisch für Koks und Opium konnte nach Verwendung von zwei Spielern nicht mehr abgebaut werden, 

**Erwartetes Verhalten**
Lässt sich wieder abbauen

**Schritte um den Fehler nachvollziehen zu können**
Tisch aufstellen, den Anzug weitergeben an zweiten Spieler, danach in die Produktion schauen und man kann den Tisch nicht mehr abbauen,

**Comment by Noah9461** [comment]
https://gyazo.com/75ce64bcd8d2764b0c0bfb25bdde0d2e

**Comment by DrGrizzlY17** [comment]
#540
