### ISSUE TITLE
Kein Abbau Balken beim Wasser drehen.

### ISSUE THREAD

**Issue by StateV2Marie** [mexyn/statev_v2_issues#616]
Hallo Als ich beim Wasser Fahren die nacht war is mir aufgefallen das es kein abbau balken gab weils bissel schwer is mit dem erklären hab ich euch nen kleines video von gemacht [https://www.youtube.com/watch?v=75qiLtMZqbQ](url)  is übrigens in Paleto so wie es bei dem anderen is weiß ich nich da ich da kaum fahre weils zu eng is und ich nen maulwurf bin.

mfg: Marie Pech

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/253
