### ISSUE TITLE
Problem export abgabe (trailer large achse)

### ISSUE THREAD

**Issue by taofeng92** [mexyn/statev_v2_issues#619]
**Character Name**
tao_feng
**Zeitpunkt (Datum / Uhrzeit)**
28.11.2020 06:00 Uhr

**Beobachtetes Verhalten**
 beim abladen beim export konnte ich es nicht abgeben, kofferraum war auf und habe mehrere versuche probiert.

**Erwartetes Verhalten**
zum ablade punkt fahren kofferraum auf und an den herren abgeben.

**Optional: Video / Bilder des Fehlers**
https://youtu.be/8jpidywsAdg

**Comment by DrColgate** [comment]
1x kupplung von der achse abschließen, dann wieder aufschließen. wenn kofferraum dann offen ist, geht es !
