### ISSUE TITLE
Sirene und Hupe beim Tippen ins Handy

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#62]
**Zeitpunkt (Datum / Uhrzeit)**
 
26.08.2020 02:28

**Beobachtetes Verhalten**

Sitzt man im Auto und tippt im Handy/Tablet/StateCom,  wird durch Tippen der entsprechenden Tasten die entsprechende Funktion im Auto wie Sirene, Licht usw. mit betätigt.

**Erwartetes Verhalten**

Schreiben im Handy/Tablet/StateCom hat keine Auswirkungen auf das Fahrzeug

**Schritte um den Fehler nachvollziehen zu können**

Man sitzt im Auto -> Öffnet Handy/Tablet/StateCom -> Drückt drückt Tasten, die auch im Auto eine Funktion haben -> Diese Funktion wird ausgeführt 

**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=OjG2claodBU&

**Comment by eiksch** [comment]
fixed beim nächsten Update - auch bei anderen Tasten die hier nicht beschrieben sind.

**Comment by JannikDatsch** [comment]
@its4l3x @eiksch Das Problem wurde beim Handy behoben, ist aber beim Tablet und beim StateCom weiterhin vorhanden.
