### ISSUE TITLE
Problem mit den Sim-Karten

### ISSUE THREAD

**Issue by DirtyRebel** [mexyn/statev_v2_issues#620]
Char:
Jeff Grimm

Seit wann:
Seit launch V2

Beschreibung:
Es können zwar mehrere Sim Karten in das Handy gelegt werden, jedoch ist man nur über die aktive Nummer erreichbar.
Dies ist im Vergleich zu V1 ein riesiges Downgrade und verringert für mich und viele andere Spieler die user experience sehr stark. Wenn man mehrere Unternehmen verwaltet oder im Dienstleistungssektor auf Abruf arbeitet, ist die Arbeit kaum noch möglich. Alle möglichen Kundenaufträge werden verpasst, man ist nur am zurückrufen und alle 5 Minuten am Sim wechseln. Das Spiel fühlt sich wie ein Stress-Simulator an und macht so keinen Spaß.

**Erwartetes Verhalten**
Bitte das alte V1 Sim-System mit mehreren erreichbaren Sim-karten und mit einer aktiven Kontakt- bzw. Anrufliste zurückbringen. 
Alternativ: Ein RL-Dualsim-System einführen oder die Möglichkeit mehrere Handys aktiv nutzen zu können.

**Schritte um den Fehler nachvollziehen zu können**
Zwei oder mehr Sim-Karten einlegen und sich auf einer "nicht aktiven" anrufen lassen.

**Comment by Statev-Bonsai** [comment]
+1

**Comment by Annabelle-Smith** [comment]
+ 1 
auch für ein Autohaus und so ist es übelst. ich kann nicht jedem kunden meine private nr. geben den dann hab ich ic nie mal Freizeit. aber so wie Bonsai bin auch ich nicht mehr erreichbar für private kontakte weil es einfach nicht geht. seid den schönen Änderungen und vielem eindecken haben aber auch diese Sachen wirklich wie oben geschrieben mehr Stress zu verantworten und das spiel macht nicht mehr wirklich Fun.  Wen man Geschäfte hat oder diese leitet , kann man nur nachteile ziehen daraus und das haben die Geschäfte schon durch diese zusätzlichen gebühren. Sorry aber sonst sehr nice.

**Comment by JannikDatsch** [comment]
Selbiges gilt für Taxiunternehmen, wo man logischerweise auch dauerhaft die Taxinummer einlegen muss, und somit unerreichbar für alles private ist. Wäre es nicht möglich, dass man das ganze vlt. zumindest auf 2 wieder hochstuft, so Dual-Sim mäßig? Denn so wie es aktuell ist, lässt sich das ganze kaum mehr miteinander vereinbaren.

**Comment by DonVitoDiangelo** [comment]
Aktuell ist es so, seit Ihr nun privat oder geschäftlich unterwegs. Weiterhin hat das auch Performance Gründe.
Hier muss die Bequemlichkeit hinten anstellen. Ob hier eine andere Lösung gefunden wird, kann ich euch nicht sagen. Wir werden das Thema intern bestimmt noch einmal besprechen, aber aktuell ist das nun so. Ihr habt ja auch noch Funk Geräte, was gerade bei Taxis mehr sinn macht, untereinander. Privat habt Ihr dann eine Geschäfts-Sim die Ihr nutzt wenn Ihr im Dienst seid und "arbeitet".

**Comment by Hexenjaeger** [comment]
man erreicht kaum noch firmen die sonst immer da waren weil alles über funk geht .. die spinnen auch rum ...   recht lästig vorallem wenn man als geschäftsführer 4 firmen leitet ... angestellte haben die auch über der nummer erreichbar sein müssen ...   cop und md leitstelle können gar nicht mehr privat erreicht werden womit die leitstellen oft nicht erreichbar sind ...   
wie bonsai sagt mega downgrade...

**Comment by DirtyRebel** [comment]
> Aktuell ist es so, seit Ihr nun privat oder geschäftlich unterwegs. Weiterhin hat das auch Performance Gründe.
> Hier muss die Bequemlichkeit hinten anstellen. Ob hier eine andere Lösung gefunden wird, kann ich euch nicht sagen. Wir werden das Thema intern bestimmt noch einmal besprechen, aber aktuell ist das nun so. Ihr habt ja auch noch Funk Geräte, was gerade bei Taxis mehr sinn macht, untereinander. Privat habt Ihr dann eine Geschäfts-Sim die Ihr nutzt wenn Ihr im Dienst seid und "arbeitet".

Zunächst möchte ich dir und dem Dev-Team für eure harte Arbeit danken! Ihr habt in den letzten Monaten großartiges geleistet und dass auch noch ehrenamtlich! Ich verstehe, dass V2 immens viel Arbeit bringt und manche Fixes bzw. Lösungen auch ein paar Wochen/Monate dauern werden. Ihr seid keine Spieleschmiede mit fettem Budget wie Rockstar.

Ich glaube aber auch, dass immens unterschätzt wird wie wichtig das Telefon für ein funktionierendes Wirtschafts-RP ist. Wirtschafts-RP ist mehr als nur in der Miene unter unansprechbaren Personen Eisen zu kloppen. Das Wirtschaft-RP lebt vom Handels- und Interaktions-RP. In der Miene gibt es kein RP - RP findet auf dem Markt statt. 
Als selbstständiger Dienstleister muss man durchgehend erreichbar sein. 
Wenn man sich entscheiden muss, ob man privat oder bei 1 Unternehmen erreichbar ist, lohnt sich der Dienstleistungssektor zudem finanziell gar nicht mehr im Vergleich zu Jobs, bei denen man sich einfach einstempeln kann.

Ich habe viel Energie investiert, um mich als Dienstleister zu spezialisieren, weil ich RP machen und nicht solo grinden möchte.
Private Angebote wie WTB/WTS funktionieren btw. so auch nicht, wenn man dann "im Dienst ist", denn derzeit kann man kaum jemanden erreichen, der z.B. sein Privatfahrzeug zum Verkauf anbietet.

Die mehrfach vorgeschlagene "Dual-Sim Lösung" wäre ein fairer Kompromiss und auch realitätsnah was das RP betrifft.

Der Wechsel auf V2 hat sehr viele Vorteile gebracht. Doch was das Handy betrifft, wünschen sich die meisten das alte System zurück. Don't fix it, if it's not broken."

Liebes Team, haltet durch und nicht alles muss sofort gelöst werden, auch nicht meine Anliegen. Denkt an eure Gesundheit und eure work-life balance <3

**Comment by JannikDatsch** [comment]
Abend liebe Devs, @DonVitoDiangelo @DirtyRebel 

das Thema ist jetzt schon älter, die Trackermeldung 3 Wochen alt. Ich habe gehofft, zu dem Thema etwas in den letzen  Teamsitzungsprotokoll zu lesen, da es für viele, gerade im Dienstleistungs-, aber auch generell im Wirtschaftssektor die einschneidenste und auch mit Abstand negativste Erneuerung durch V2 gewesen sein dürfte. 

Dieses Problem hält logischerweise auch weiterhin an. 
Meine Frage ist, wie aktuell der Stand zu dem Thema ist bzw. ob man sich überhaupt damit beschäftigt. Die Argumente gegen dieses neue System stehen ja bereits alle oben und werde ich jetzt nicht nm. wiederholen. 

Über eine Rückmeldung zum aktuellen Stand würde ich mich, und viele andere sicher auch sehr freuen.

**Comment by DonVitoDiangelo** [comment]
♥
