### ISSUE TITLE
Handyanimation behindert zu lange die Bewegung/Fahrzeugsteuerung + Handy-Popup downgrade

### ISSUE THREAD

**Issue by DirtyRebel** [mexyn/statev_v2_issues#621]
**Character Name**
Jeff Grimm

**Zeitpunkt (Datum / Uhrzeit)**
Seit release V2

**Beobachtetes Verhalten**
(1) Während der Fahrt im Auto behindern die Handyanimationen die Fahrzeugsteuerung so lange, dass man bei jedem Anruf rechts ran fahren muss um zu sehen wer anruft oder um an das Telefon zu gehen.  Bricht die Immersion da man IRL auch ein Handy via Freisprechanlage oder Autohalterung bedienen kann und gleichzeitig das Steuer halten kann. 

(2) Dass die Nummer des Anrufenden unten links bei einem eintreffenden Anruf nicht mehr angezeigt wird, ist auch ein kleines quality of life downgrade.
 
**Erwartetes Verhalten**

Im Auto:
Die Kontrolle über die Steuerung/Fahrzeugsteuerung sollte durch die Handyanimation nicht blockiert werden.

Lösungsvorschläge:
>Entweder: Die Handyrausholanimation beim Fahrer nicht auslösen (Autohalterung RP)
>Alternativ:  Die Handyrausholanimation sollte durch das weglegen des Handys gecancelt werden
>Alt 2: Beschleunigung der Handy-Animationen

Anruf-Popup: Sollte die Nummer bzw. falls abgespeichert den Namen anzeigen (wie in V1)

**Schritte um den Fehler nachvollziehen zu können**
Auto fahren und das Telefon rausholen, kurz drauf schauen/Anruf annehmen und versuchen Handy wegzulegen.

**Comment by its4l3x** [comment]
Während der Fahrt einfach kein Handy nutzen ;) Gibt auch die Möglichkeit des Stehenbleibens.

Die Sache mit der Nummer kann man arrangieren. Wird aber durchbesprochen.
