### ISSUE TITLE
Mietfahrzeug kann nicht abgegeben werden

### ISSUE THREAD

**Issue by NLTrance** [mexyn/statev_v2_issues#622]
Eric Ahr
28.11.2020 - 11:00 Uhr

**Beobachtetes Verhalten**
Mietfahrzeug kann nicht abgegeben werden.
Es erscheint die Meldung "Um dein Fahrzeug abzugeben, musst du erst deinen Kofferraum leeren."
Der Kofferraum wird IC als leer angezeigt, nach Rücksprache mit dem Support befindet sich dort aber noch ein "altes Kriegsbeil" was wohl mit der V2 removed wurde.

**Optional: Video / Bilder des Fehlers**
https://youtu.be/HE-UbjUSEo8

**Comment by DonVitoDiangelo** [comment]
fixed enxt update
