### ISSUE TITLE
(N) deaktiviert den Mauscursor nicht, während man sich beim Tätowieren im Vorlagen-Screen befindet

### ISSUE THREAD

**Issue by DirtyRebel** [mexyn/statev_v2_issues#625]
**Character Name**
Jeff_Grimm

**Zeitpunkt (Datum / Uhrzeit)**
Seit V2

**Beobachtetes Verhalten**
Als Tätowierer kann man sich nicht bewegen sobald man sich im Vorlagen-Screen befindet. Bei V1 konnte man (N) drücken, was den Mauscursor deaktivierte und man konnte sich anschließend bewegen. 

Note: Als Mechaniker kann man wie in V1 über (N) den Cursor deaktivieren und sich um das Auto bewegen, während man den Tuning-Screen offen hat.

Add: Gleiches gilt für das Benutzen des Telefons: Man kann nicht einfach (N) drücken und mit dem Handy in der Hand herumlaufen. Dies stellt aber nur ein kleines "quality of life" Problem dar.

**Erwartetes Verhalten**
(N) sollte den Mauscursor deaktivieren, während man sich beim Tätowieren im Vorlagen-Screen befindet.

**Schritte um den Fehler nachvollziehen zu können**
Als Tätowierer den Vorlagen-Screen bei einem Kunden aktivieren und versuchen sich zu bewegen, nachdem 8n

**Comment by its4l3x** [comment]
fixed next update
