### ISSUE TITLE
Inventar Transfer am Haus und Rucksäcke

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#626]
**Character Name** Erwin Dulach

**Zeitpunkt (Datum / Uhrzeit)** 28.11 ~15:50

**Beobachtetes Verhalten** Wenn man mit einem ausgerüsteten Rucksack (getestet: Umhängetasche) das Inventartransfermenü (getestet: Haus) aufruft und wieder schließt, bleibt das Rucksackmenü weiterhin verborgen. Erst nach ab- und anlegen des Rucksacks (wenn er gefüllt ist dann in ein Inventar was die Füllmenge frei hat) sieht man wieder das Rucksackmenü.
Außerdem geht das Ausrüsten des Rucksacks in diesem Menü nicht und es kommt zu einer Fehlermeldung.

**Erwartetes Verhalten** Man sollte nach schließen des Menüs wieder den Rucksack sehen können.

**Schritte um den Fehler nachvollziehen zu können** Mit ausgerüstetem Rucksack an das Transfermenü vom Haus gehen, Dinge hin und her schieben und Menü wieder schließen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

1920x1080

**Comment by DonVitoDiangelo** [comment]
Da kannst du links an der Seite wechseln zwischen div. Inventaren, dort auch der Rucksack aktivieren und deaktivieren..
