### ISSUE TITLE
Tezeract Aufladung nicht möglich

### ISSUE THREAD

**Issue by HaroldCooper** [mexyn/statev_v2_issues#628]
**Harold Cooper**

**Zeitpunkt (Datum / Uhrzeit)**

28.11.2020 17:35
**Beobachtetes Verhalten**

Wollte den Tezeract aufladen, aber es steht da "Fahrzeug nicht gefunden!" 

**Erwartetes Verhalten**

Das es lädt.

**Schritte um den Fehler nachvollziehen zu können**

**Optional: Video / Bilder des Fehlers**

![AUTO NICHT GEFUNDEN](https://user-images.githubusercontent.com/75176331/100520945-fb905280-31a0-11eb-914a-33f0d6162f3c.PNG)

**Comment by its4l3x** [comment]
Nächstes Update. Bereits fixed
