### ISSUE TITLE
HUD ausblenden

### ISSUE THREAD

**Issue by Mr-Chris-VRTY** [mexyn/statev_v2_issues#629]
Seit dem V2 Update kann man leider über # das HUD nicht mehr ausblenden. Es wäre schön, wenn man diese Funktion wieder einbauen könnte (Wahlweise anderer Hotkey)
Außerdem würde es das Spielerlebnis verbessern, wenn man die Funktion etwas erweitern könnte, sodass man auch Himmelsrichtung und Straße auf der man fährt (rot/weiße Anzeige), Funkgerät und insofern das geht die Minimap mit diesem Hotkey auf einen Schlag deaktivieren und aktivieren kann.

**Comment by JulianMa** [comment]
Nach nächstem Update wieder da. Minimap wird dann ebenfalls ausgeblendet. Funkgerät kannst du da einfach ausziehen.
