### ISSUE TITLE
Dimensions Bug 

### ISSUE THREAD

**Issue by sunforise** [mexyn/statev_v2_issues#632]
**Character Name**
 Anton Ressler

**Zeitpunkt (Datum / Uhrzeit)**
 28.11.2020 / ~20:13

**Beobachtetes Verhalten**
 Wenn man in der HK auf Toilette geht, das Spiel schließt und dann wieder startet landet man in der falschen Dimension ... 

**Erwartetes Verhalten**
 man sollte nach dem Einloggen in der Dimension 12240 landen um den Marker zum Verlassen der Toilette sehen und nutzen zu können aber man landet meines Wissens nach in Dimension 0 aber kommt somit dann nicht mehr aus der Toilette raus

**Schritte um den Fehler nachvollziehen zu können**
 gehe in die HK, gehe in die Toilette im Inneren Bereich, schließe das Spiel, logge dich wieder ein und Voila

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Bitte mal nen Standard TP Marker erstellen hinten in der Ecke, dann kommen die Spieler wenigstens noch raus, wenn Sie sich da ausloggen. @DrGrizzlY17

**Comment by DrGrizzlY17** [comment]
Tür dynamisch machen @DonVitoDiangelo :P

**Comment by DonVitoDiangelo** [comment]
Wird bei den "normalen" Klo Ports vorerst so bleiben, also da am besten nicht ausloggen. sry.
