### ISSUE TITLE
Buritto Inventar

### ISSUE THREAD

**Issue by Stiefel911** [mexyn/statev_v2_issues#633]
Moin,
ist es gewollt das man vom Buritto nur noch von außen an das Inventar kommt?
Bin immer gerne hinten eingestiegen um die sachen raus zu holen etc... 
Vlt ist es wieder möglich dieses wieder so zu bekommen?

So long

**Comment by DrGrizzlY17** [comment]
Ist gewollt das man nicht mehr innerhalb des Fahrzeuges mit dem Kofferraum interagieren kann
