### ISSUE TITLE
StateCOM + Kofferraum funktioniert in Winterfahrzeugen des PDs nicht

### ISSUE THREAD

**Issue by Mr-Chris-VRTY** [mexyn/statev_v2_issues#635]
Leider funktioniert das StateCOM unter F4 im den beiden Winterfahrzeugen des PDs (North Yankton) nicht.
Police Rancher (Winter)
Police Roadcruiser (Winter)
Außerdem besitzt der Cruiser (Und der Rancher wahrscheinlich auch hab ich aber nicht getestet) keinen Kofferraum. D.h. dieser lässt sich zwar öffnen, aber mit I öffnet sich kein Inventar des Fahrzeuges
Wäre cool wenn das gefixt werden könnt :D

**Comment by DonVitoDiangelo** [comment]
StateCom fixed next update , inv sollte gehen. Wenn nicht vermutlich alte Eventfahrzeuge. Hier im Support melden und prüfen lassen.
