### ISSUE TITLE
neue SNOW PD-Fahrzeuge haben keinen StateCom Zugang

### ISSUE THREAD

**Issue by KilianLobges** [mexyn/statev_v2_issues#636]
**Kilian Lobges**
 Kilian Lobges

**Zeitpunkt (Datum / Uhrzeit)**
 28.11. 21:30

**Beobachtetes Verhalten**
 kein StateCOM zugang mit dem SNOW Fahrzeugen vom Police Department

**Erwartetes Verhalten**
 mit F4 Statecom öffnen

**Schritte um den Fehler nachvollziehen zu können**
 in das Auto setzen und F4 drücken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
 1080*1920

**Optional: Video / Bilder des Fehlers**

**Comment by Mr-Chris-VRTY** [comment]
https://github.com/mexyn/statev_v2_issues/issues/635 Ehem :D
