### ISSUE TITLE
E-Säulen laden abbrechen

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#637]
**Beobachtetes Verhalten**
Mal wieder das Thema E-Säulen. Man kann bei Fahrzeugen welche gerade stehen als fremde Person den Ladevorgang abbrechen. Dadurch wird nur bis zu dieser Zeit geladen. Das bezahlte Geld bleibt bei der Tankstelle, der eigentliche Besitzer hat aber ein nicht vollgeladenes Auto, wofür er eigentlich bezahlt hat.

**Erwartetes Verhalten**
Tankvorgang kann nur von einer Person mit Schlüssel beendet werden.

**Comment by DonVitoDiangelo** [comment]
Da hat wohl jemand den Stecker gezogen. 
Wird besprochen....

**Comment by M4rvinLP** [comment]
Verstehe den Punkt, hab ich mir auch gedacht. Bloß ist der Strom aktuell sehr sehr teuer, und wenn dann so ein Witzbold eine $1500 Ladung beendet, ist das schon ziemlich belastend.

**Comment by JulianMa** [comment]
Ist mir bekannt und steht auf meiner liste

**Comment by JulianMa** [comment]
Nach nächstem Update behoben.
