### ISSUE TITLE
Ungültiges Ziel oder Ursprung beim Öl

### ISSUE THREAD

**Issue by xqeno** [mexyn/statev_v2_issues#638]
Kann das öl weder in noch aus dem ÖlT-Tanker nehmen. Kommt immer nur die Fehlermeldung "Ungültiges Ziel oder Ursprung!" Relog hat nichts gebracht. Kofferraum geöffnet / geschlossen

**Comment by DonVitoDiangelo** [comment]
Wohin willst du dein Öl entladen?

**Comment by its4l3x** [comment]
@tastydev Hatten gestern einen Bug gefunden gehabt. Ist bereits gefixed mit dem nächsten Update des Gameservers.
