### ISSUE TITLE
"J" triggert Schneeball aufheben im StateCom

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#639]
**Character Name**
Jannik_Datsch

**Zeitpunkt (Datum / Uhrzeit)**
29.11 00:21

**Beobachtetes Verhalten**
Beim drücken von "J" bsp. beim eingeben der StateNet Login Daten wird ein Schneeball aufgehoben.

**Erwartetes Verhalten**
Es wird kein Schneeball aufgehoben

**Schritte um den Fehler nachvollziehen zu können**
StateNet öffnen --> Textfeld auswählen --> "J" drücken

**Optional: Video / Bilder des Fehlers**

https://youtu.be/lCZc8HryREM

**Comment by MrGotAB** [comment]
Ja kann ich so bestätigen, hebt auch in Gebäuden Schneebälle auf wenn man im Tablet schreibt.
