### ISSUE TITLE
Verschobenes UI im Werkstattmenü - Unterbodenbeleuchtung

### ISSUE THREAD

**Issue by ZirbelR** [mexyn/statev_v2_issues#64]
**Zeitpunkt (Datum / Uhrzeit)**
26.08.2020 3:40

**Beobachtetes Verhalten**
Rahmen zum Auswählen der Unterbodenbeleuchtung ist verschoben und geht durch das Auto.

**Erwartetes Verhalten**
Rahmen sollte sich um das Auto legen

**Schritte um den Fehler nachvollziehen zu können**
Unterbodenbeleuchtung Tunen

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/70246255/91245610-2dcb8780-e74e-11ea-8f36-b02e6dedca7a.png)

**Comment by Acc3zZ** [comment]
fixed!
Danke für die Meldung.
