### ISSUE TITLE
Stundenlohn wird nicht ausgezahlt

### ISSUE THREAD

**Issue by xtorox** [mexyn/statev_v2_issues#640]
**Robin_Toro**

Mitarbeitern
**Zeitpunkt (Datum / Uhrzeit)**

28.11.2020 ganzen Tag
**Beobachtetes Verhalten**

Die Mitarbeiter waren in der Fabricacion Suarez eingestempelt, es wurde aber kein Stundenlohn überwiesen.
**Erwartetes Verhalten**

Sobald der Mitarbeiter über eine Stunde angestempelt ist, sollte der eingestellte Stundenlohn ausgezahlt werden.
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by eiksch** [comment]
Wird behoben und ist bekannt - leider wird es aktuell noch ein wenig dauern.

**Comment by Scox-Schompi** [comment]
betrifft auch andere Firmen wie z.B. werkstätten. und auf die Dauer echt schwierig bis nervig

**Comment by its4l3x** [comment]
Fixed, seit dem letzten Update.
