### ISSUE TITLE
Fieldmaster Graintrailer

### ISSUE THREAD

**Issue by HowardSnooze** [mexyn/statev_v2_issues#641]
**Howard_Snooze**

**Zeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

(Firmen: Stars KFZ Werk 1/2 ,  Stars KFZ Werk 2/2 )

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/Gv7T6

**Comment by ZacCooperr** [comment]
Hey Howard,

ich klinke mich mal kurz ein.
Seitlich gibt es noch einen Scroll-Balken mit weiteren Materialien, die noch für den zusammenbau benötigt werden.
Z.b. Gummi weitere Barren etc.

**Comment by DonVitoDiangelo** [comment]
So ist es.

 Ansonsten bitte beim nächsten Tracker ganze Sätze schrieben. @HowardSnooze
