### ISSUE TITLE
Produktion : Autoverrückter keine Fortschritte bei Tuningteilen

### ISSUE THREAD

**Issue by ZacCooperr** [mexyn/statev_v2_issues#642]
**Zeitpunkt (Datum / Uhrzeit)**
29.112020 09:55

**Beobachtetes Verhalten**
Balken von Produktionsskil Autoverrückter macht keine bzw. einen zu geringen Fortschritt, sofern Tuningteile angehauen werden.
Das bitte einmal überprüfen und anpassen.

**Erwartetes Verhalten**
Auch bei Tuningteilen sollte der Balken einen entsprechenden Fortschritt anzeigen.

**Schritte um den Fehler nachvollziehen zu können**
Produktionen Felgen/Felgenbereifung/Spoiler/Xenon etc. (betrifft wahrscheinlich alle Tuningteile).
Bei Fahrzeugen oder Autoteilen konnte der Fehler nicht festgestellt werden.

**Optional: Video / Bilder des Fehlers**
![Skill_Autoverrückter](https://user-images.githubusercontent.com/74767269/100537522-93d21a00-3229-11eb-89f9-486fc584f576.png)

**Comment by Statev-Bonsai** [comment]
Das geht nach zeit, und 80min Produktionszeit sind halt nix, grade wenn du schon einen level aufstieg hattest.. Das geht bei Tuningteilen ganz normal hoch...
