### ISSUE TITLE
Geschwindigkeit/Beschleunigung -> Porsche Panamera 

### ISSUE THREAD

**Issue by motioncsgo** [mexyn/statev_v2_issues#645]
**Character Name**
Marc_Randall

**Zeitpunkt (Datum / Uhrzeit)**
Gesamter Zeitraum seit dem V2 Update

**Beobachtetes Verhalten**
Der Porsche Panamera erscheint langsamer als vorher. Die Höchstgeschwindigkeit ist an sich gleich geblieben, allerdings erscheint die Beschleunigung langsamer.

**Erwartetes Verhalten**
Vor allem im Vergleich zum neuen Mercedes AMG, sollte die Beschleunigung womöglich etwas nach oben korrigiert oder zumindest auf die Beschleunigung des Mercedes angepasst werden.

**Comment by DonVitoDiangelo** [comment]
Fahrzeugpool wurde komplett überarbeitet und bleibt so.
