### ISSUE TITLE
Firma steht zum Verkauf

### ISSUE THREAD

**Issue by VictorCorticera** [mexyn/statev_v2_issues#646]
Gustavo Luciano

29.11.2020 zwischen 11:30 und 12:00 Uhr

Ein Labor mit dem Firmenhash cypressflats12 ist zwar vorhanden und Eigentümer und Mitarbeiter sind gleich, aber an dem eigentlichen Standort der Firma kann man nun eine Firma für ca. 130k kaufen. Diese Firma hat aber eine andere Adresse. Siehe Screenshot.

Keine Firma steht zum Verkauf

An den eigentlichen Standort der Firma gehen mit dem Firmenhash cypressflats12 gehen und an den Marker gehen. 

![8edabe1f8f132dd620400e591375b595-jpg](https://user-images.githubusercontent.com/28830176/100540658-db16d580-323e-11eb-954b-4d33c539a3c2.jpg)

**Comment by its4l3x** [comment]
Sollte mit dem 18 Uhr restart gefixed sein.
