### ISSUE TITLE
Dominator (Race) das kleine liebe kuscheltier

### ISSUE THREAD

**Issue by Hexenjaeger** [mexyn/statev_v2_issues#647]
**Character Name**
Leon Unger

**Zeitpunkt (Datum / Uhrzeit)**
immer seit V²

**Beobachtetes Verhalten**
leider musste ich fest stellen das der Dominator (Race) in keinster weise mehr wie vorher ist (kaufgrund)
er stellt sich in kurven nicht mehr quer  er hat kein anzug mehr im unteren drezahlbereich womit das heck nicht mehr quer geht.
der anzug ist so schwach das die front auch nicht mehr hoch geht (kein muss) ..

**Erwartetes Verhalten**
versteht es nicht falsch ich will kein 300 kmh auto ... aber das race sollte schon für anzug stehen .. driften nur noch schwer möglich und nur mit handbremmse vorher konnte man ihn ohne bremsen um die kreuzung driften lassen 
bitte um anpassung  ... 

**Schritte um den Fehler nachvollziehen zu können**
rein setzen fahren entäuscht sein

**Comment by DonVitoDiangelo** [comment]
Fahrzeugpool wurde komplett überarbeitet und bleibt so.
