### ISSUE TITLE
Liter Wasser ins Maschinenlager (Restaurant) nicht möglich (Falsche Transportgruppe!)

### ISSUE THREAD

**Issue by DerHessenTyp** [mexyn/statev_v2_issues#65]
**Zeitpunkt (26.08.2020 / 07:46 Uhr)**

**Beobachtetes Verhalten**
Ich wollte Liter Wasser Einzeln aber auch die gesamten Liter die im Restaurant vorhanden sind ins Maschinenlager ziehen. Funktioniert leider nicht da mir gesagt wird Falsche Transportgruppe. Daher keine Möglichkeit Getränke die Liter Wasser als Zutat brauchen herzustellen.

**Erwartetes Verhalten**
Man sollte die Liter Wasser im ganzen oder auch im Einzelnen vom Lager in die Maschine ziehen können um dann am Herd Getränke zuzubereiten. 

**Schritte um den Fehler nachvollziehen zu können**
Man wählt Liter Wasser aus und zieht es vom Lager in das Maschineninventar wodurch der Fehler (Unten links im Bild) angegeben wird.

**Optional: Video / Bilder des Fehlers**
![Falsche Transportgruppe Wasser ins Maschinenlager](https://user-images.githubusercontent.com/70151958/91264303-df7bb000-e770-11ea-889c-28a783acfffd.jpg)

**Comment by DonVitoDiangelo** [comment]
fixed next update

**Comment by DerHessenTyp** [comment]
Gerade getestet beim Sägewerk kann man Tannenholz nicht in ein Fahrzeug verladen.
