### ISSUE TITLE
Haare ändern sich beim aufsetzen von Mützen

### ISSUE THREAD

**Issue by EmmaSvensson** [mexyn/statev_v2_issues#651]
**Character Name**
Viele weibliche Charaktere

**Zeitpunkt (Datum / Uhrzeit)**
Immer wenn man eine Kopfbedeckung aufsetzt

**Beobachtetes Verhalten**
Die Haare gucken bei der Kopfbedeckung durch oder man hat ganz andere Haare darunter

**Erwartetes Verhalten**
Man behält seine Frisur oder aber man hat zumindest keine Kurzhaarfrisur

**Schritte um den Fehler nachvollziehen zu können**
-mütze auf
-andere Haare

**Optional: Video / Bilder des Fehlers**
![eigentliche frisur](https://user-images.githubusercontent.com/74768516/100545547-a3b72180-325c-11eb-959f-4b052cd783fd.png)
![Haare durch mütze](https://user-images.githubusercontent.com/74768516/100545548-a4e84e80-325c-11eb-9464-37174f8e61e6.png)
![Mütze nach dem haarschnitt](https://user-images.githubusercontent.com/74768516/100545549-a580e500-325c-11eb-84ba-ec32750edb7d.png)

**Comment by DonVitoDiangelo** [comment]
normal und so gewollt, da die Haare sonst durch glitchen. Mütze immer zu letzt aufsetzen.
