### ISSUE TITLE
Balancing und Funktionalität

### ISSUE THREAD

**Issue by 3xcu** [mexyn/statev_v2_issues#652]
Fahrzeug Balancing: 
 - Cops Autos: Buffalos sind unfahrbar (Handling), Beschleinigung wie ein Oldtimer, Endgeschwindigkeit langsamer als der CVPI // Mustangs sind nicht konurrenzfähig anderen zivilien Sportwagen gegenüber, Beschleunigung viel zu langsam // Der Mclaren ist nicht konkurrenzfähig als Supersportler mit einem Cyclone der in 3 Sekunden auf 250 geht oder anderen E-Autos und Porsche. Der Interceptor ist als 4 Sitzer mit dem CVPI die einzige Alternative. 
Copautos sind nicht konkurrenzfähig.
 - Zivile Autos: GT63 und vergleichbare Autos sind gnadenlos overpowered im Vergleich zu Supersportlern und den Copwagen. 
 
Funktionalität: 
Es braucht dringends: 
 - eine größere Voice range. Die maximale Range ist viel zu klein, oft eskalieren Situationen weil man einfach zu weit weg ist. Man kann im PD nicht mal durch den kompletten Flur schreien oben von einer Wand zur Anderen an vielen Stellen. 
- shortcuts für den gehstil schleichen, shortcuts für Anschnallen, Motor anschalten etc.

**Comment by Domeex3** [comment]
Es sind aktuell leider einige Autos die nicht mehr so wirklich sinn ergeben bezogen auf Leistung, Fahrzeugtyp, Preis etc. aber was willste machen...

**Comment by DonVitoDiangelo** [comment]
- Fahrzeuge werden über Zeit beobachtet, Dort wird es vorerst keine großen Änderungen geben.
- Voice Range ist i.O.
- Shortcuts werden wir nicht einführen
