### ISSUE TITLE
Kartenanzeige unvollständig

### ISSUE THREAD

**Issue by Clawdie** [mexyn/statev_v2_issues#653]
**Character Name**
Glinda Ehrmantraut

**Zeitpunkt (Datum / Uhrzeit)**
Dauerhaft seit Tagen wiederholt geprüft

**Beobachtetes Verhalten**
Chiliad Fashion Bekleidungsladen wird nicht mehr in der Legende angezeigt

**Erwartetes Verhalten**
Chiliad Fashion wird wie die anderen Bekleidungsläden angezeigt

**Schritte um den Fehler nachvollziehen zu können**
auf die Karte gucken

**Comment by DonVitoDiangelo** [comment]
Können wir aktuell nicht beeinflussen. Es gibt zu viel Einträge bei einer Begrenzung von 100 Slots.
