### ISSUE TITLE
Items verschwinden aus dem Inventar beim rechtsclick

### ISSUE THREAD

**Issue by 3xcu** [mexyn/statev_v2_issues#656]
rechtsklickt man ein Item im Inventar, kommt unten links eine Fehlermeldung (irgendwas mit invalid) und das Item verschwindet (Bei mir eine Taurus)

**Comment by jonasesser** [comment]
Ich habe ein Ähnliches Problem. Tshirt und Kappe verloren: https://youtu.be/IrPBZ22m1nE

**Comment by Annabelle-Smith** [comment]
jup kann ich bestätigen meine halskette ist verschwunden als ich das halstuch angezogen habe mit rechtsklick und ich diese dan mit rechtsklick wieder anziehen wollte

**Comment by JulianMa** [comment]
fixed

**Comment by jonasesser** [comment]
Habe Gestern zwei Zettel aus meinem Schrank genommen. Mit rechtsklick gelesen. Danach waren Sie weg. Bin mir gerade unsicher ob das so beabsichtigt sein könnte. Video könnte ich hochladen bei Bedarf.
