### ISSUE TITLE
Ausstieg mit Schleudersitz

### ISSUE THREAD

**Issue by Noah9461** [mexyn/statev_v2_issues#657]
**Character Name**
Noah Draper

**Zeitpunkt (Datum / Uhrzeit)**
29.11 18:30 ca

**Beobachtetes Verhalten**
Wenn man Ö im Auto drückt und danach aussteigt passiert folgendes: https://www.youtube.com/watch?v=V_MvDbFEipA&ab_channel=Noahs

**Erwartetes Verhalten**
Normales aussteigen

**Schritte um den Fehler nachvollziehen zu können**
Ö im Auto drücken und dann aussteigen

**Comment by its4l3x** [comment]
fixed next update
