### ISSUE TITLE
Müllcontainer Fort Zancudo schwebt

### ISSUE THREAD

**Issue by AngelMaravilla** [mexyn/statev_v2_issues#658]
**Character Name**
Angel Maravilla

**Zeitpunkt (Datum / Uhrzeit)**
29.11.2020 / 18:45 Uhr

**Beobachtetes Verhalten**
Müllcontainer schwebt.

**Erwartetes Verhalten**
Müllcontainer hält sich an die Gesetze der Physik.

**Schritte um den Fehler nachvollziehen zu können**
Müllcontainer anschauen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot_1](https://user-images.githubusercontent.com/74780492/100550057-82176380-3277-11eb-881f-98d997eefd79.png)

**Comment by DrGrizzlY17** [comment]
Uffi, ich gucks mir an :D

**Comment by DrGrizzlY17** [comment]
Hab fix mit Einstein gesprochen. Ist fixed

**Comment by RomusLapisimus** [comment]
Vielen Dank!
