### ISSUE TITLE
Müllcontainer Fort Zancudo schwebt

### ISSUE THREAD

**Issue by RomusLapisimus** [mexyn/statev_v2_issues#659]
Guten Abend,

vielen Dank für das Platzieren des Müllcontainers!

Könnt Ihr den Müllcontainer nach unter versetzen? Er schwebt.

![Müllcontainer schwebt](https://user-images.githubusercontent.com/75159759/100550155-416c1a00-3278-11eb-9219-296a58fc0f6f.GIF)

Vielen Dank für Eure super Arbeit!

Grüße
Romus

**Comment by jonesXYZ** [comment]
#658 duplicate

**Comment by RomusLapisimus** [comment]
Bug bereits gepostet.
