### ISSUE TITLE
Verpackter Regenschirm nicht herstellbar 

### ISSUE THREAD

**Issue by DerHessenTyp** [mexyn/statev_v2_issues#66]
**Zeitpunkt (26.08,2020 / 09:54 Uhr)**

**Beobachtetes Verhalten**
Nachdem ich viele neue Produkte hergestellt habe für den 24/7 in der Fertigung wollte ich auch 10 verpackte Regenschirme herstellen (Auch 1x versucht und nicht möglich), daraufhin kam die Fehlermeldung: ,,error.factory.production.target.config" (Bild im Anhang)

**Erwartetes Verhalten**
Die Produktion sollte nach dem Drücken des Buttons ,,Produktion starten" wie bei allen anderen Produkten starten.

**Schritte um den Fehler nachvollziehen zu können**
1. Man legt die Sachen die man für Regenschirme ins Maschineninventar
2. Wählt Verpackter Regenschirm aus
3. Stellt die Mengenangabe ein
4. Drück Produktion starten
Daraufhin kommt die Fehlermeldung 
Danach ein anderes Produkt versucht, das ging liegt also wirklich nur an dem Regenschirm

**Optional: Video / Bilder des Fehlers**
![Error Regenschirmen](https://user-images.githubusercontent.com/70151958/91277291-eb706d80-e782-11ea-80a9-c7d27ad1e5fb.jpg)

**Comment by DerHessenTyp** [comment]
Im Labor für Sauerstoffflaschen die gleiche Fehlermeldung bekommen.

**Comment by eiksch** [comment]
`error.factory.production.target.config` bedeutet, dass die Itemconfig nicht gefunden werden kann.

1. Entweder ist der hash falsch definiert in der Produktion
2. Oder das Item selbst wurde nicht als Item definiert.. sondern nur als Produktion/Translation
