### ISSUE TITLE
Gleiche Farbe Kleidung

### ISSUE THREAD

**Issue by glb11** [mexyn/statev_v2_issues#660]
**Character Name**
Jens_Summer

**Zeitpunkt (Datum / Uhrzeit)**
29.11.2020 19:30

**Beobachtetes Verhalten**
Unterschiedliche Farbtöne bei gleicher Marke und Serie der Kleidung --> das Orange am Oberteil viel Kräftiger und klarer, als bei der Hose wo es eher dreckig wirkt 

**Erwartetes Verhalten**
gleiche Farbtöne der Kleidung innerhalb der Helix Serie

(Betrifft auch die Hose   [M] Orange Helix Worker   )

**Schritte um den Fehler nachvollziehen zu können**
Kleidung kaufen und anziehen und vergleichen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![heliux](https://user-images.githubusercontent.com/70204338/100551261-ac6d1f00-327f-11eb-9914-e7f8a57b34c4.jpg)
![20201129194103_1](https://user-images.githubusercontent.com/70204338/100551262-aecf7900-327f-11eb-82ff-2b6908da5c7c.jpg)

**Comment by Enemyaa** [comment]
Es gibt zu jedem Workbreaker eine namentlich passende Hose. Deine Kombination ist scheinbar nicht die richtige, ABER es gibt die richtige. :) https://prnt.sc/vt0qrv

**Comment by glb11** [comment]
welche Hose soll das dann sein?   weil die haben ja den gleichen Namensbestandteile.  P.S. (auch auf dem Bild ist der Unterschied sichtbar das oberer Teil ist rötlicher(dadurch kräftiger) wie die Hose die Gelber ist.    (Komme zur not deswegen gerne mal in den ts)

**Comment by Enemyaa** [comment]
ZU dem "[M] Orange-Grauer Helix Workbreaker" passt die "[M] Orange-Graue Helix Worker X" und sollte es da wirklich unschöne Farbabweichungen geben, dann kannst du dies ja nochmal im "GTA" Bugtracker posten.
