### ISSUE TITLE
Flatbed Aufsatteln abbrechen und Range

### ISSUE THREAD

**Issue by ZirbelR** [mexyn/statev_v2_issues#661]
**Character Name**
Richie Zirbel

**Zeitpunkt (Datum / Uhrzeit)**
immer

**Beobachtetes Verhalten**
Aktuell ist es nicht möglich das Aufsatteln abzubrechen (obwohl dies ja möglich sein sollte, ich kann ja einfach aufhören den Haken anzuhängen usw), außerdem ist manchmal die Range in welcher der Flatbed stehen muss um aufzusatteln viel zu hoch, was gelegentlich zu schwer im RP zu erklärenden Situationen führt. (Autos stehen auf einmal auf einem Meterweit entferntem Flatbed).

**Erwartetes Verhalten**
Aufsatteln kann abgebrochen werden, realistische Range.

**Schritte um den Fehler nachvollziehen zu können**
Auto auf Flatbed laden.

**Optional: Video / Bilder des Fehlers**

![image](https://user-images.githubusercontent.com/70246255/100551409-8f851b80-3280-11eb-84d6-80c60514b1ab.png)

**Comment by DonVitoDiangelo** [comment]
Das mit dem nicht mehr abbrechen ist so gewollt. Ist das Thema mit der Range noch aktuell und tritt das nur bei bestimmten Fahrzeugen auf? @ZirbelR

**Comment by ZirbelR** [comment]
sorry, hab voll übersehen dass hier nochmal geantwortet wurde. Ja, Thema range ist nach wie vor Aktuell, tritt bei jedem getesteten fahrzeug auf (Kamacho, Drift tampa, GT63, RS7....)

![image](https://user-images.githubusercontent.com/70246255/102027027-c8091700-3da1-11eb-89f7-aedb66dea4ef.png)

**Comment by DonVitoDiangelo** [comment]
Die normalen Abschlepper sind ja wieder länger zurück, daher sollte sich das Problem hier durch Auswahl selbst "lösen" lassen.  Woran genau das liegt ist aktuell nicht ersichtlich und da werden jetzt auch keine Kapazitäten hinein fließen, sry.
