### ISSUE TITLE
nach einlogen immer an anderen punkt

### ISSUE THREAD

**Issue by Hexenjaeger** [mexyn/statev_v2_issues#662]
Kira Petrovic

**Zeitpunkt (Datum / Uhrzeit)**
immer einlogen   20:23 uhr 29.11.2020 letzte mal

**Beobachtetes Verhalten**
beim einloegen und auf der map spawnen kurz am otr wo man sich aus logt dann mitmal woanders ... meist 20 meter weiter wech mitten auf der straße

**Erwartetes Verhalten**
nicht wech teleportieren

**Schritte um den Fehler nachvollziehen zu können**
einlogen und verschwinden ...

**Comment by Hexenjaeger** [comment]
und nach auslogen im haus immer weiter wech vinewood auslogen  erscheinen oben am baumwollfeld oder mitten in der stadt ...

**Comment by DonVitoDiangelo** [comment]
Bitte weiter beobachten und ggf. erneut melden. Danke

**Comment by Hexenjaeger** [comment]
eben wieder vor gekommen 01.12.2020 umd 13:54 Uhr  erschienen auf den bett zack wech ... musste wieder support um zur nsa zu kommen ..
da ab und an wenn zur NSA porten das sie meistens auf der strasse in weinwood steht

**Comment by Hexenjaeger** [comment]
18:53 wieder am anderen ort ca 20 m weiter wech auf der straße ... 
und da war der chat vorher nicht sprich auch nicht zurück gesetzt so leicht

**Comment by Hexenjaeger** [comment]
heute 20 uhr wieder ... wieder support besuch da zur nse setzen lassen müssen

**Comment by Hexenjaeger** [comment]
so wieder ... eingelogt ... vorm bahama mama erschienen dieses mal auf nen dach und leben verloren ... 
so langsam macht es kein fun mehr jedes mal woanders auf zu wachen ...  
vllt ja was mit den haus ...   (house_VinewoodHills_132)
wäre schön wenn ihr da mal schauen könntet .. 
endet jeden tag mit support besuch weil andere dimension
![lauft](https://user-images.githubusercontent.com/74836248/100989321-08ba9200-3551-11eb-95fd-743c30f96235.PNG)

**Comment by Hexenjaeger** [comment]
und täglich grüßt das murmeltier ;-)   heute mal was neues...  
![asdd](https://user-images.githubusercontent.com/74836248/101163411-db92e000-3633-11eb-828c-a395d0f8daff.PNG)

**Comment by its4l3x** [comment]
Ist was komplett anderes - Hat nichts mit deinem Fehler zu tun.

Sollte mittlerweile aber nicht mehr Vorkommen. Immer noch?

**Comment by its4l3x** [comment]
Okay, da keine Antwort gehe ich mal von aus - das der Fehler nicht mehr beständig ist.
