### ISSUE TITLE
Anrufpopup zeigt eigenen Namen im Telefon an

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#663]
**Character Name** Erwin Dulach

**Zeitpunkt (Datum / Uhrzeit)** 29.11 ~22:00

**Beobachtetes Verhalten** Meldung links unten zeigt eigenen Kontaktnamen an

**Erwartetes Verhalten** Meldung links unten sollte fremden Kontaktnamen anzeigen.

**Schritte um den Fehler nachvollziehen zu können** Angerufen werden

**Optional: Video / Bilder des Fehlers**

https://x-up.ws/i/f5f6f7e67405.png

**Comment by its4l3x** [comment]
fixed. next update
