### ISSUE TITLE
Doppelbelegung Taste "Komma" in KFZ

### ISSUE THREAD

**Issue by DrColgate** [mexyn/statev_v2_issues#664]
**Character Name**
Anton Mueller
**Zeitpunkt (Datum / Uhrzeit)**
Seit mehreren Tagen
**Beobachtetes Verhalten**
In Fahrzeugen löst die Taste "Komma" das Radio und das Kleidungsfenster gleichzeitig aus
**Erwartetes Verhalten**
Nur eins von beiden sollte auslösen
**Schritte um den Fehler nachvollziehen zu können**
In KFZ steigen und "Komma" drücken
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Hier musst du dann die Komma Taste in deinen GTA Einstellungen entsprechend deaktivieren.
