### ISSUE TITLE
Nachtrag: Glasgran. Produktion instant fertig #514

### ISSUE THREAD

**Issue by DrColgate** [mexyn/statev_v2_issues#665]
Issue wurde geschlossen und auf wontfix gesetzt. Bug besteht nachwievor.
Beweißvideo wurde im Originalpost als Kommentar von mir hinzugefügt
https://github.com/mexyn/statev_v2_issues/issues/514

**Comment by DonVitoDiangelo** [comment]
Danke. Das kannst du aber nicht direkt reproduzieren oder? Das ist dann random?

**Comment by JulianMa** [comment]
Du bist dir auch ganz sicher, dass das nicht die Vorherige Produktion gewesen ist?
Eine Produktion wird erst dann abgeschlossen, wenn du einmal das Produktions UI geöffnet hast.
Das heißt, das die Items erst dann im Lager auftauchen, wenn du einmal am Computer warst! 
In deinem Video öffnest du die Produktions UI, (was eine Potentiell vorherige Produktion abschließt) und startest eine neue mit 25 Einheiten Glas, hast dann aber 104 Säcke raus (104/8 = 13), was ja vorne und hinten nicht passen kann.
Ich schließe das hier.
