### ISSUE TITLE
Funkgerät/Voice Aussetzter.

### ISSUE THREAD

**Issue by Naaki6** [mexyn/statev_v2_issues#666]
**Character Name**

Owen West bzw. allen Ballas.
**Zeitpunkt (Datum / Uhrzeit)**

Zur jeder Zeit.
**Beobachtetes Verhalten**

Wenn man neben einer Person anfängt zu funken und dabei etwas weg geht hört man weder den Funk der Person noch das normale Sprechen der Person. Man hört diese erst wieder wenn die Person a) weit genug weg ist oder b) oder wieder nah genug bei einem dran steht.
**Erwartetes Verhalten**

Egal ob man neben einer Person steht die Funkt oder ob diese etwas weiter weg geht sollte man die Person hören.
**Schritte um den Fehler nachvollziehen zu können**

Person A und B stehen nebeneinander. Person B fängt an zu reden und funkt dann und entfernt sich von Person A.
https://lowkey.gg/v/ea667b28-5be9-4627-b296-5dbe1eec42cb
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Kalumel** [comment]
bei den Skullz auch aufgetreten, seit dem letzten Voice Update

**Comment by MisterCopeland** [comment]
Kann es auch bestätigen.

**Comment by tastydev** [comment]
fixed
