### ISSUE TITLE
Schlüssel nach Notfall MDd aus Tasche weg?

### ISSUE THREAD

**Issue by eldoodaks** [mexyn/statev_v2_issues#668]
Darryl Bradley

**Zeitpunkt (Datum / Uhrzeit)**
30.11.2020 ca 00:15Uhr

**Beobachtetes Verhalten**
Schlüssel weg nach Notfall MD, war vorher nicht so

**Erwartetes Verhalten**
Schlüssel und Dokumente bleiben weiterhin in der Tasche

**Schritte um den Fehler nachvollziehen zu können**
Ja umkippen und notfall kommen

**Comment by Statev-Bonsai** [comment]
Alle Schlüssel die NICHT am Schlüsselbund sind nimmt seit V2 das Notfallteam ab :)

**Comment by DrGrizzlY17** [comment]
Waren die Schlüssel im normalen Inventar? Dann sind se weg, das war mMn auch schon bei v1 so. Schlüssel werden nun gesaved wenn du sie im Schlüsselbund hattest

**Comment by eldoodaks** [comment]
Ist natürlich ärgerlich das ich das nirgends gelesen habe.. da ich oder die kollegen auch schon ewig nimmer im notfall waren wusste das niemand.. son scheiß eh..
