### ISSUE TITLE
Schranke öffnet sich nicht. Parkplatz/Garage LSPD

### ISSUE THREAD

**Issue by Gee1337** [mexyn/statev_v2_issues#67]
**Zeitpunkt (Datum / Uhrzeit)**
26.08.2020 / 10:35

**Beobachtetes Verhalten**
Schranke öffnet sich nicht mehr. Weder vom Parkplatz, noch von der Straße aus. Auch nicht beim leicht antitschen.

**Erwartetes Verhalten**
Schranke öffnet sich beim Anfahren

**Optional: Video / Bilder des Fehlers**

![schranke1](https://user-images.githubusercontent.com/70242468/91281765-c5e66280-e788-11ea-8fcf-3408735623f5.PNG)

**Comment by tastydev** [comment]
Das ist eine GTA eigene Schranke und daran können wir nichts ändern, sowas braucht ihr nicht zu reporten.

**Comment by its4l3x** [comment]
By @Gee1337 in GTA Online https://i.gyazo.com/e6ceff07a466de18782a954bd4a8c9b1.jpg

**Comment by tastydev** [comment]
GTA Online !== GTA Singelplayer
