### ISSUE TITLE
Sirenen triggern im StateNet

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#670]
**Character Name**
Max_Broady

**Zeitpunkt (Datum / Uhrzeit)**
29.11.2020

**Beobachtetes Verhalten**
Wenn man in einem Streifenwagen sitzt und sich im StateNet einloggt.
So wird beim drücken der Taste E. R, etc die Sirene des Fahrzeugs getriggert.

**Erwartetes Verhalten**
Das innerhalb des StateNet keine Funktionen von außerhalb getriggert werden

**Schritte um den Fehler nachvollziehen zu können**
Ins Streifenfahrzeug setzen und StateNet öffnen.
Anschließend R drücken. Sollte dann die Sirene angehen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Mr-Chris-VRTY** [comment]
https://github.com/mexyn/statev_v2_issues/issues/303
;)
