### ISSUE TITLE
Animation beim Farming zu lange

### ISSUE THREAD

**Issue by Lube08** [mexyn/statev_v2_issues#671]
**Character Name**

Luke Long
**Zeitpunkt (Datum / Uhrzeit)**

Seit Release
**Beobachtetes Verhalten**

Die Animation bei verschiedenen Feldern bei denen man sich "bücken" muss dauert länger als die Zeit beim farmen. Bsp: Gurken, Salat, Kartoffeln
**Erwartetes Verhalten**

Animation die dann beendet ist, wenn der Abbauprozess auch beendet ist. Evtl andere Animation für die genannten Felder. Skillsystem macht keinen Sinn, weil die Animation immer gleich lange dauert.
**Schritte um den Fehler nachvollziehen zu können**

Bei den entsprechenden Feldern mit höherem Skill farmen
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
@its4l3x  check mal bitte, ob die scenarios korrekt gecanceled werden. ist glaube immer nur bei scenarios  der Fall.

**Comment by its4l3x** [comment]
Wir haben leider keinen Einfluss auf Animationen das die exakt zur Sekunde X beendet werden können. Es gibt immer eine kleine "Fade Out" Zeit, welche fest je nach Szenario definiert wurde.
