### ISSUE TITLE
StateNet Preise

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#673]
**Character Name**
Marvin_Elpe

**Zeitpunkt (Datum / Uhrzeit)**
30.11.2020

**Beobachtetes Verhalten**
Im StateNet werden teilweise die Preise nicht mehr geladen und stehen für $0 da. Wenn man mehrfach herum klickt auf anderen Seiten und dann wieder zu den Preisen geht ist es manchmal wieder normal da, dann wieder 0.

**Erwartetes Verhalten**
Preise werden richtig angezeigt

**Optional: Video / Bilder des Fehlers**
![](https://i.imgur.com/4mzlwvd.png)

**Comment by Solomonetix** [comment]
Kann ich so bestätigen. Das selbe bei der "Firmenhash | petrolstation29"
Es kann NICHT mehr getankt werden!

**Comment by M4rvinLP** [comment]
Also ich konnte tanken

**Comment by Asmier** [comment]
Restaurant ist aktuell auch betroffen "Bone Eater / snrKebab"

Preise stehen zwar in Ladentheke drinnen aber nicht im Tablet

**Comment by Chandena** [comment]
Also bei uns ist es genauso, mittlerweile so das wenn man ein neuen Preis angibt, alles aus der Theke verschwindet.

**Comment by M4rvinLP** [comment]
Zusatz: manchmal wird aktuell statt wie auf dem Bild oben die Ankaufspreise für die Artikel angezeigt.

**Comment by TheBroady** [comment]
Feedback stand jetzt:
Preise sind immer mal wieder auf 0 und man muss mehrfach die seite neuladen damit die korrekten Verkaufspreise angezeigt werden.
