### ISSUE TITLE
Holz kann nicht in Pounder / Caracara geladen werden 

### ISSUE THREAD

**Issue by powerswissi** [mexyn/statev_v2_issues#674]
**Character Name**

Roger_Thickle

**Zeitpunkt (Datum / Uhrzeit)**

30.11.2020

**Beobachtetes Verhalten**

es kann kein Holz in den Pounder gemacht werden. Vom Wald aus. Obwohl dies Laut Changelog möglich sei.
![Screenshot_767](https://user-images.githubusercontent.com/70152806/100623077-f1499200-3321-11eb-8452-dee9ea749697.png)

![Screenshot_765](https://user-images.githubusercontent.com/70152806/100623139-07575280-3322-11eb-8bcb-d8f34c47abdf.png)

**Erwartetes Verhalten**

Holz in Pounder laden

**Schritte um den Fehler nachvollziehen zu können**

In den Wald fahren , Axt nicht vergessen. Versuchen in Pounder zu laden 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Screenshot_767](https://user-images.githubusercontent.com/70152806/100623266-366dc400-3322-11eb-8084-973f8dc7bcbf.png)

![Screenshot_766](https://user-images.githubusercontent.com/70152806/100623300-3ff72c00-3322-11eb-9f66-a8f0eb3f5c52.png)

![Screenshot_765](https://user-images.githubusercontent.com/70152806/100623315-44234980-3322-11eb-8849-8ecca814b486.png)

**Comment by DrGrizzlY17** [comment]
Servus, das Beladen im Changelog bezieht sich daraus, das man Holz aufladen kann, nicht das man damit abbauen kann.
Heißt: Farmen = Nope, Ausm Lager aufladen = Yes!
