### ISSUE TITLE
Animation Autoreparatur

### ISSUE THREAD

**Issue by ShauniKT** [mexyn/statev_v2_issues#675]
**Shauni Teller**

**Zeitpunkt: bei jeder Reparatur**

**Wenn man ein Auto in der Werkstatt repariert, wird der sichtbare Schaden direkt nach Unterschrift des Kunden und nicht erst nach Abschluss des Reparaturvorganges, wie es vorher war, optisch entfernt. Ich finde es rein aus RP Gründen besser, wenn das Auto wirklich erst wieder ein intaktes Model hat, wenn die Reparatur abgeschlossen ist, gerade, da man ja nun die Defekte auch sehen kann. Durch dieses Verhalten schließt sich zb auch die Motorhaube des Autos sofort, bevor man RP technisch überhaupt ans Fahrzeug kommt um daran zu arbeiten. Sieht halt komisch aus, über einer geschlossenen Motorhaube zu hängen, weil man da arbeitet.**

**Erwartetes Verhalten
Model des Autos ist erst nach Abschluss des Reparaturbalkens wieder intakt.**

**Schritte um den Fehler nachvollziehen zu können
- demoliertes Auto auf Reppoint
- Rechnung ausstellen
- unterschreiben und bestätigen
- Schadensmodell des Autos sofort behoben trotz laufendem Ladebalken**

Vor Reparatur
https://prntscr.com/vsy7gr

Nach Unterschrift (Ladebalken aktiv)
https://prntscr.com/vsy7o8

MfG

**Comment by JulianMa** [comment]
Nach nächstem Update fixed.
