### ISSUE TITLE
Keine Xenon Farben für Camaro SS 

### ISSUE THREAD

**Issue by ShauniKT** [mexyn/statev_v2_issues#677]
**Shauni Teller**

**Zeitpunkt 30.11.2020 / 16:55**

**Beobachtetes Verhalten
Die Farbe der Scheinwerfer ändern sich beim Camaro Tuning nicht. Man könnte allerdings Trotzdem welche Kaufen und dafür bezahlen. In Kombination mit dem Bug, dass bei solchen Autos bei egal welchem Tuning immer Xenons verbaut werden sehr nervig.**

**Erwartetes Verhalten Tuningoption deaktiviert oder wechselnde Farben der Lichter**

**Schritte um den Fehler nachvollziehen zu können
- Camaro SS auf Tuningpoint stellen
- Scheinwerfer Auswählen
- Xenon Farbe auswählen
- sehen wie nix passiert**

**Optional: Video / Bilder des Fehlers**

https://prntscr.com/vsyzdw

**Comment by DrGrizzlY17** [comment]
Keine feste Aussage, aber es kann sein dass das modded Fahrzeug das Tuningteil einfach nicht besitzt

**Comment by DonVitoDiangelo** [comment]
jupp, steht dann nicht zur Verfügung.
