### ISSUE TITLE
Auch das Funk HUD ausblenden

### ISSUE THREAD

**Issue by Mr-Chris-VRTY** [mexyn/statev_v2_issues#678]
Erstmal vielen lieben Dank für das Einbinden der Funktion zum Ausblenden des HUDs, ich denke, diese Funktion wird viele Spieler einschließlich mir sehr viel coole Situationen bereiten 👍 :)

Es wäre cool, wenn beim Ausblenden des HUDs über # auch das Funk HUD ausgeblendet wird. Das bleibt aktuell noch (siehe Screen).
![image](https://user-images.githubusercontent.com/70213538/100635731-26111580-3331-11eb-82df-bb43279f950d.png)

**Comment by its4l3x** [comment]
Umgesetzt. Next Update
