### ISSUE TITLE
Uboot betanken + Sprittyp..

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#679]
Hallo, das Uboot ist nicht betankbar, zudem müsste ein Uboot Diesel anstatt Benzin Tanken denn es hat einen Kreislaufantrieb.
 (Wiki: Der Kreislaufantrieb ist ein Verfahren zum außenluftunabhängigen Antrieb von Unterseebooten. Er besteht im Wesentlichen aus einem Dieselmotor, der unter Wasser mit komprimiertem oder Flüssigsauerstoff betrieben wird. )

![Screenshot_2](https://user-images.githubusercontent.com/70241137/100639617-b3eeff80-3335-11eb-9763-45fc66e4d354.png)

**Comment by DonVitoDiangelo** [comment]
Bitte ein Marker tiefer im Wasser ein paar Meter entfernt setzen. @DrGrizzlY17

**Comment by DrGrizzlY17** [comment]
WIR HABEN UBOOTS AUFM SERVER?

**Comment by Statev-Bonsai** [comment]
Jawollo...

**Comment by DrGrizzlY17** [comment]
Welche Tankstelle war das?

**Comment by Statev-Bonsai** [comment]
Es dreht sich um alle Bootstanken Dan, man kann ja nicht mit einem 20kmh Fahrzeug um die halbe Insel fahren ;)

**Comment by DrGrizzlY17** [comment]
Ey, du hast dich dafür entschieden nen U-Boot zu kaufen. Ich wusste bis gestern nichtmal, das wir sowas aufm Server haben

**Comment by DonVitoDiangelo** [comment]
@DrGrizzlY17  kannst ja einfach mal teste ob das "etwas tiefer setzen" schon was bringt. Werde den Verbrauch noch anpassen das man nicht so oft damit tanken muss. Müssen nicht zwingend alle Tanken überarbeitet werden

**Comment by DrGrizzlY17** [comment]
Hab einige Punkte näher an die Wasseroberfläche gesetzt. Meld dich nochmal falls es noch nicht wie gewollt klappt
