### ISSUE TITLE
Tablet Vollbildmodus nach Strg+Linksklick

### ISSUE THREAD

**Issue by Gee1337** [mexyn/statev_v2_issues#68]
**Zeitpunkt (Datum / Uhrzeit)**
26.08.2020

**Beobachtetes Verhalten**
Strg+Linksklick auf sämtliche Links im Tablet führen dazu, dass sich das Tablet in den Vollbildmodus begibt. Sei es unangemeldet bei Klick auf Facebook und co oder angemeldet im Statenet auf Fahrzeuge, Firmen, Finanzen etc. 

**Schritte um den Fehler nachvollziehen zu können**
Strg+Linksklick auf irgendeinen Link

**Optional: Video / Bilder des Fehlers**
![9172ef3f8489b59a4ccb93a19434222e](https://user-images.githubusercontent.com/70242468/91285712-db11c000-e78d-11ea-97c4-3fe4557ca3ef.gif)

**Comment by r3sist3nt** [comment]
Das ist ein alt:V Issue, wir haben keinen Einfluss auf das Verhalten der Browsers an dieser Stelle. Ich mache dafür einen Issue bei alt:V auf.

**Comment by TheOutburst** [comment]
#2116
