### ISSUE TITLE
Auftragsexport: Gewicht zu hoch, kann nicht erfüllt werden.

### ISSUE THREAD

**Issue by Craig-Statev** [mexyn/statev_v2_issues#680]
Beim Export ist die Menge nicht angepasst für Goldbarern. Das Gewicht ist von 0.1Kg auf 1Kg gesetzt worden in V2. Es gibt kein Fahrzeug um den Auftrag erfüllen zu können.

![Export](https://user-images.githubusercontent.com/75133881/100640574-dd5c5b00-3336-11eb-801e-582ab3b56ab3.PNG)

**Comment by DonVitoDiangelo** [comment]
next update
