### ISSUE TITLE
Skillsystem-Fehler Pflanzenkunde 

### ISSUE THREAD

**Issue by Zooreo** [mexyn/statev_v2_issues#682]
**Ilyas_Zink**

**27.11.2020**

**Trotz gelerntem Skill, finde ich nach vielen Stunden farmen (Kalmus,Indigo,Tabak) keine Samen außer Aloe Vera Samen. Alle anderen Samen werden als Unbekannte Samen im Inventar angezeigt.**

**Schlafmohn Samen etc. Sollten beim farmen auftauchen und zu erkennen sein, wenn man es als Item im Inventar hat.**

**Comment by tastydev** [comment]
kein bug :-)

**Comment by Zooreo** [comment]
Also soll dies beudeten: Das dieser Fehler kein Fehler ist sondern ein "Feature" ist, welches mir nicht ermöglicht Samen zu finden oder zu erkennen(trotz Skill). Jeder andere kann dies aber von unseren Jungs. Es hängt also auch nicht von irgend einer Liste für Fraktionen ab, in der ich nicht drin stehen soll. Sprich der Fehler liegt bei mir und ich muss es IC herausfinden?
