### ISSUE TITLE
Sheriff SUV des Sheriffs Department

### ISSUE THREAD

**Issue by MPV-Domenko** [mexyn/statev_v2_issues#683]
**Character Name**
Erik_Domenko

**Zeitpunkt (Datum / Uhrzeit)**
Seitdem V2 verfügbar wurde 

**Beobachtetes Verhalten**
Der Sheriff Granger, oder SUV wie man nennen möchte, kommt keinem Fahrzeug mehr hinterher. Es ist selbst schwer, Fahrzeuge aus dem Fahrzeugverleih dran zu bleiben oder gar in die nähe zu kommen. Die Beschleunigung ist extrem nach unten geschraubt worden. Die Endgeschwindigkeit wurde ebenfalls nach unten geschraubt. Mehr stört aber die Beschleunigung.

**Erwartetes Verhalten**
Die Beschleunigung höher schrauben sowie Endgeschwindigkeit nach meinen Vorschlag um 15 - 20kmh höher setzen.

**Comment by DonVitoDiangelo** [comment]
Ok, so wie er ist.

**Comment by MPV-Domenko** [comment]
Wurde da schon was verändert?
LG
