### ISSUE TITLE
[Verbesserungsvorschlag] Animationen Umsortieren können

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#684]
**Character Name** Erwin Dulach

**Zeitpunkt (Datum / Uhrzeit)**  30.11 20:30

**Beobachtetes Verhalten** Derzeit kann man Animationen innerhalb eines Animationsordners nur durch löschen aller darüber liegenden Animationen und erneutes hinzufügen dieser sortieren.

**Erwartetes Verhalten** Ein Sortiersystem wie es bereits bei den Animationsordnern existiert wäre hier schön. Es ist doch recht Müsam, jetzt nach dem Update seine Seiten an Animationen wieder aufzubauen.

**Comment by Hutstaender** [comment]
#1729

**Comment by JulianMa** [comment]
Ich hab das schon länger auf dem schirm, bin da allerdings lange Zeit nicht zu gekommen.
Mit dem Umbau auf Server-Side saving hab ich mich da jetzt aber auch mal dran gesetzt.
