### ISSUE TITLE
Position von gesetzten Objekten fehlerhaft...

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#685]
Der Teddy wurde nach dem Schild gestellt und sollte oben drauf sitzen (Wie bei Bild 1)...
Aber es wechselt immer hin und her wenn man in ein Gebäude geht, ob es behebbar ist keine Ahnung ... :)

![Screenshot_4](https://user-images.githubusercontent.com/70241137/100675307-00066800-3367-11eb-8353-4b3167258ab3.png)

![Screenshot_3](https://user-images.githubusercontent.com/70241137/100675313-04328580-3367-11eb-8e8e-2b61095adea9.png)

**Comment by DrGrizzlY17** [comment]
![image](https://user-images.githubusercontent.com/70150988/100739085-de44c980-33d6-11eb-99ab-37535eeca245.png)

**Comment by tastydev** [comment]
Die Reihenfolge wann welches Objekt zuerst eingestreamt wird ist nicht definiert @eiksch.

**Comment by TheBroady** [comment]
Ist bei allem. Bsp: Laptop auf Theke. Anschließend kann es sein das der Laptop unter der Theke steht.
