### ISSUE TITLE
Probleme mit Bootstankstelle. petrolstation2

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#686]
**Zeitpunkt (Datum / Uhrzeit)**
1.12.2020 / 00.20
**Beobachtetes Verhalten**

Wir haben 2 Probleme mit der Tankstelle.
Hash: petrolstation2
1. Problem: Es ist kein Bilp auf der Map gesetzt.
2. Problem: Der Wasserstand ist zu niedrig um zu tanken. D.h. der Marker wo das Boot hin muss um betankt zu werden ist zu hoch gesetzt. 

**Erwartetes Verhalten**
1. Problem: Blip auf der Map hinzufügen.
2. Problem: Marker etwas nach unten setzten.

**Optional: Video / Bilder des Fehlers**
https://puu.sh/GSSum/b946d818ec.png

**Comment by jonesXYZ** [comment]
Glaube das mit dem Wasserstand ist tatsächlich nen GTA Problem, denke würde helfen wenn man den Radius "einfach" erhöht.

**Comment by DrGrizzlY17** [comment]
Der Blip müsste vorhanden sein, kann sein das wir Verluste bei euch haben, da das alt:V maximum erreicht ist was Blips angeht

**Comment by Kalumel** [comment]
> Glaube das mit dem Wasserstand ist tatsächlich nen GTA Problem, denke würde helfen wenn man den Radius "einfach" erhöht.

naja, man könnte ja denk punkt einfach etwas tiefer setzten oder einen 2. der Tiefer ist hinzufügen damit das TUG noch tanken kann. 

Haben eben getestet zu tanken... kein erfolg @DrGrizzlY17

**Comment by Kalumel** [comment]
Edit: Ist nach dem Restart gefixt. Danke
