### ISSUE TITLE
Anlegen von Herz-Layering-Kette lässt Ohrringe verschwinden

### ISSUE THREAD

**Issue by CaleighRhodes** [mexyn/statev_v2_issues#687]
**Character Name**
Caleigh_Rhodes

**Zeitpunkt (Datum / Uhrzeit)**
01.12.2020 / 09:00

**Beobachtetes Verhalten**
Wenn man die Herz-Layering-Kette anlegt, die neu zugekommen ist, verschwinden Ohrringe (in meinem Fall Silber Creolen). Legt man dann die Ohrringe wieder an, verschwindet die Kette - und so weiter und so fort.

**Erwartetes Verhalten**
Schmuck jeglicher Art wird komplett dargestellt.

**Schritte um den Fehler nachvollziehen zu können**
Herz-Layering-Kette anlegen, wenn bereits Ohrringe angelegt waren. Dann wechseln. Eines von beidem verschwindet immer (das vorletzte angelegte)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
-

**Optional: Video / Bilder des Fehlers**
-

**Comment by Enemyaa** [comment]
@CaleighRhodes Die Creolen und die Muschelohrringe kann man nicht mit Ketten, Schals und Krawatten kombinieren, da alle 4 unter der selben Komponenten ID liegen.
