### ISSUE TITLE
"Dach" von Police Sheriff Granger wechselt

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#688]
**Character Name** Erwin Dulach

**Zeitpunkt (Datum / Uhrzeit)** -

**Beobachtetes Verhalten** 
Man kann zwar das "Dach", also die Nummer, die oben auf dem Granger drauf ist, durch Felgentunings beeinflussen (05,16, 32, 84, ...) aber das ist nicht immer bei allen Spielern gleich.
Besonders viel hab ichs nicht getestet, aber augenscheinlich ändert es sich, wenn man neu in die Dimension kommt (relogin, firma, haus).

**Erwartetes Verhalten** 
Die Nummer sollte bei allen Spielern gleich sein.
Im Idealfall kann man das Dach als einzelnd ändern und nicht durch Felgentunings beeinflussen.

**Schritte um den Fehler nachvollziehen zu können**
Menschen die auf Granger starren.

**Optional: Video / Bilder des Fehlers**

Könne ich nachliefern falls benötigt

**Comment by DonVitoDiangelo** [comment]
Nummer immer random
