### ISSUE TITLE
Andere UI Elemente während Produktionsrechner

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#69]
**Zeitpunkt (Datum / Uhrzeit)**
26.08.2020 11.54Uhr

**Beobachtetes Verhalten**
Man kann diverse UI (Handy,Inventar,Funk, Tablet) Elemente öffnen, welches sich über den Produktionsrechner legt, während man noch aktiv am Rechner ist.
Wenn man z.B. den Funk aufmacht und wieder schließt, kann man sich anschließend bewegen obwohl man noch am rechner ist.

**Erwartetes Verhalten**
UI Elemente sollten keinen Focus bekommen

**Schritte um den Fehler nachvollziehen zu können**
1. An den Computer gehen mit E
2. Diverse Buttons für die UI Elemete drücken (Handy, Tablet, Inventar, Funk)

**Optional: Video / Bilder des Fehlers**

[video.zip](https://github.com/mexyn/statev_v2_issues/files/5129087/video.zip)

**Comment by r3sist3nt** [comment]
Nach restart fixed.
