### ISSUE TITLE
Lifeinvader für IOS

### ISSUE THREAD

**Issue by biiina** [mexyn/statev_v2_issues#690]
Lifeinvader für IOS funktioniert nicht, egal mit welchem Browser. Wäre super wenn man das Problem beheben könnte 😉

https://www.imagebanana.com/s/1956/DQSIVzmk.html

**Comment by TheOutburst** [comment]
Funfact: auch die Desktopseite anzufordern bringt nichts.
Auf Android muss man die nichtmal anfordern, kriegt sie aber trotzdem (zumindest sehe ich keine Unterschiede)

**Comment by JulianMa** [comment]
was soll ich sagen..
Ich kann das nicht testen, da ich keinen Safari Browser habe. Apple weigert sich leider Safari für Windows weiterhin zu unterstützen.

**Comment by biiina** [comment]
Kennst du niemanden der ein iPhone hat? 👀

**Comment by h3adbang3r** [comment]
Das Problem besteht unter iOS (14) aber mit jedem Browser.
Ich habe es unter iOS 14.2 mit Safari, Chrome sowie Firefox getestet.
![20201201_105152000_iOS](https://user-images.githubusercontent.com/15799077/100731474-b6039d80-33cb-11eb-84eb-d87d563e5d3d.png)
Der Screen stammt von Firefox. Interessant ist, das die Seite zwar gestaucht aber klar geladen wird. Diesen markierende rot kommt erst wenn man den Bildschirm berührt.
![20201201_104922000_iOS](https://user-images.githubusercontent.com/15799077/100731188-57d6ba80-33cb-11eb-8d3b-255a22269bd8.png)

**Comment by DonVitoDiangelo** [comment]
Keine Prio und wird vorerst auch nicht angegangen.

**Comment by TheBroady** [comment]
![unknown](https://user-images.githubusercontent.com/70150887/102363890-2c9cbf80-3fb6-11eb-8cd5-f26940cd1089.png)
Ich bin an einem Windows PC mit 1920x1080

**Comment by JulianMa** [comment]
Behoben.
