### ISSUE TITLE
Haus Garagen/Abladepunkt versetzen

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#691]
Moin, der alte Abladepunkt sitzt etwas bescheiden, grade im Bezug auf größere Autos und dem Garagendach.
Daher bitte den Punkt vorne an die Straße setzen das man auch einen Pounder+Achse be/entladen kann, quasi genau dort hin wo Bonsai steht.
Dankeeeeeeeeeeeee

![Screenshot_5](https://user-images.githubusercontent.com/70241137/100751309-72b72800-33e7-11eb-8c45-4f5a7ae9e207.png)

![Screenshot_6](https://user-images.githubusercontent.com/70241137/100751434-9da17c00-33e7-11eb-9dd0-7ed86d8af640.png)

**Comment by DrGrizzlY17** [comment]
Versetzt, aber unters Carport. Das Haus soll nicht als Lagerersatz dienen das irgendwie mit Poundern oder sonstiges beladen und entladen werden soll

**Comment by Statev-Bonsai** [comment]
Aber was ist wenn sie automatisch in die Garage eingeparkt werden? Also die Mule-Pounder etc...da bekomme ich sie ja nimmer mehr raus!
