### ISSUE TITLE
Bargeld anzeige im Tauschmenu

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#692]
**Character Name**
Max_Broady

**Zeitpunkt (Datum / Uhrzeit)**
01.12.2020 - 15:14 Uhr

**Beobachtetes Verhalten**
Ich habe 1.97$ Bar dabei.
Mein Kollege hat 411.16$ dabei.
Im Tauschmenu wird uns beiden oben links 20$ angezeigt.

**Erwartetes Verhalten**
Das jeder im Tauschmenu sein eigenes Bargeld sieht.

**Schritte um den Fehler nachvollziehen zu können**
Handelsmenu öffnen und vergleichen was oben drin steht.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Mein Inventar
![Screenshot_3](https://user-images.githubusercontent.com/70150887/100751796-130d4c80-33e8-11eb-8493-182c6a3f4789.jpg)

Inventar Kollege
![Screenshot_1](https://user-images.githubusercontent.com/70150887/100751828-1ef90e80-33e8-11eb-9f57-cda49a981bd6.jpg)

Handelsmenu
![Screenshot_2](https://user-images.githubusercontent.com/70150887/100751849-26201c80-33e8-11eb-87af-295401853ebc.jpg)

**Comment by Acc3zZ** [comment]
Wurde erstmal ausgeblendet. Wird demnächst gefixxt

**Comment by DonVitoDiangelo** [comment]
Wird nicht angezeigt werden.
