### ISSUE TITLE
Antrag: Entfernen von Gegenständen und Verlegen des Be/Entladepunkts

### ISSUE THREAD

**Issue by KruemelGames** [mexyn/statev_v2_issues#693]
Firmenhash: pfGroupAllRew_86

Wir würden gerne die neuen Gegenstände vor Central Logistics entfernt haben (Stühle, Tische, Sonnenschirme)
Diese haben für uns keinen Mehrwehrt da man sich auf viele der Stühle nicht setzen kann, weil zu nahe am Tisch sind oder verschoben wurden. Desweiteren spawnt man beim Verlassen des Lagers in die Tische hinein. 
Das entfernen der Sonnenschirme würde außerden Fail-RP verhindern in dem man statt die Treppe nutzt, über die Sonnenschirme nach oben steigt.
Wir würden das Entfernen sehr begrüßen, um den Bereich selbst dekorieren zu können.

https://pic.statev.de/image/20201129191211-1.GmpA6

Verlegen des Ladepunkts wäre für uns sehr von Vorteil, da wir oft beim Ankaufen mit dem Verkäufer lauthals schreien müssen da man sonst einander nicht hört. Durch das Verlegen wäre das nicht mehr nötig. Die neue Position wird durch den blauen Coil Raiden dargestellt. 

https://pic.statev.de/image/20201201152010-1.Gm0uJ

**Comment by DrGrizzlY17** [comment]
Eingangspunkt versetzt. Rest bleibt so

**Comment by DrGrizzlY17** [comment]
> Das entfernen der Sonnenschirme würde außerden Fail-RP verhindern in dem man statt die Treppe nutzt, über die Sonnenschirme nach oben steigt.

Sowas kommt von Spielern und nicht weil Objekte vorhanden sind. Wenn sowas passiert, melden!
