### ISSUE TITLE
Tankstelle kann keine Preise einstellen

### ISSUE THREAD

**Issue by SandyLive89** [mexyn/statev_v2_issues#694]
Sandy Miller

**Zeitpunkt (Datum / Uhrzeit)**
seit gestern

**Beobachtetes Verhalten**
Seit gestern mittag können wir keinen Preis mehr in unserer Tanke einstellen. Das heißt wir können auch nichts verkaufen weil die Tanstelle auf 0$ steht

**Erwartetes Verhalten**
Das die Preise eingestellt bleiben und man Tanken kann.

Firmenhash: petrolstation29

**Comment by Solomonetix** [comment]
Problem besteht seit Aufspielen "V2.0.15 - 30.11.2020"

**Comment by Statev-Bonsai** [comment]
Tanken kann man trotzdem.. Vorhin erst bei dir getankt..

**Comment by Solomonetix** [comment]
> 
> 
> Tanken kann man trotzdem.. Vorhin erst bei dir getankt..

Ich sehe auch Einnahmen im Konto.
Aber: Wie dies dann zu erklären?

![Desktop Screenshot 2020 12 01 - 16 38 10 85 (2)](https://user-images.githubusercontent.com/21086123/100762701-97fe6300-33f4-11eb-8bb0-9c198a68985e.png)

**Comment by TheBroady** [comment]
Bei mir ist die Anzeige im tablet auch schon aufgetreten, allerdings durch mehrfaches reload der Seite waren die Preise dann drin.
Tanken ist möglich

**Comment by SandyLive89** [comment]
tanken ist nur möglich wenn ich im browser das State net öffne und dort die preise eingebe das dann speicher und die seite nicht mehr schließe , sobald ich die seite schließe kann man nicht mehr tanken weil die preise auf 0 stehen

**Comment by TheBroady** [comment]
> tanken ist nur möglich wenn ich im browser das State net öffne und dort die preise eingebe das dann speicher und die seite nicht mehr schließe , sobald ich die seite schließe kann man nicht mehr tanken weil die preise auf 0 stehen

Ich Probier das gleich mal an meiner tanke aus.

**Comment by TheBroady** [comment]
> 
> 
> > tanken ist nur möglich wenn ich im browser das State net öffne und dort die preise eingebe das dann speicher und die seite nicht mehr schließe , sobald ich die seite schließe kann man nicht mehr tanken weil die preise auf 0 stehen
> 
> Ich Probier das gleich mal an meiner tanke aus.

Konnte ich  nicht nachstellen.
Das einzige was bei mir identisch ist, ist das das StateNet mir teils 0 Doller als Preis anzeigt.
Durch mehrfaches Reloaden steht dann irgendwann der Preis drin.
Aber Tanken scheint wohl immer zu gehen.

**Comment by SandyLive89** [comment]
ja bei uns aber nicht siehst du ja am oberen bild was gepostet worden ist das es nicht geht sondern das dort 0 steht und auch nicht getankt werden kann

**Comment by JulianMa** [comment]
bestätigt.
Ich behebe das so schnell wie möglich

**Comment by JulianMa** [comment]
@SandyLive89 Wenn bei euch nicht getankt werden kann, warum gehen dann alle paar Minuten Überweisungen auf das Konto mit dem Verwendungszweck Tanken rein?

**Comment by JulianMa** [comment]
Besteht das Problem überhaupt noch?

**Comment by SandyLive89** [comment]
Ich hab überwiegend das state net offen, ich weiß nicht ob es weiter funktioniert wenn ich es zu habe, ich kann es gerne ausprobieren und geb dir dann hier nochmal bescheid.

**Comment by SandyLive89** [comment]
Ok geht jetzt auch wenn ich das state net zu habe. Auch wenn die Preise auf 0 stehen kann man tanken. Wäre trotzdem schön wenn es irgendwann wieder klappen würde

**Comment by TheBroady** [comment]
Halten wir fest: aktueller Fehler ist das, dass StateNet zwischenzeitlich als Preis 0 eingetragen hat und dies erst durch neu laden der Seite wieder behoben wird.
