### ISSUE TITLE
Garage zum Haus 

### ISSUE THREAD

**Issue by KoenigJustin** [mexyn/statev_v2_issues#695]
Jan_Meise

01.12.2020

**Beobachtetes Verhalten**
Ich habe neben meinem Haus eine Garage stehen die aktuell unbenutzt ist und sonst zu keinem Haus gehört. Wäre es möglich das ich diese Garage für mein Haus bekomme damit ich meine Fahrzeuge dort einparken kann.

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/3bd40bf549f12c9bed1663212cc240f0
https://gyazo.com/584dd8b61a9401b14a05e6ab1e460e39

**Comment by DonVitoDiangelo** [comment]
@DrGrizzlY17  Bitte prüfen, Glaube rechts neben der Garage ist nen Haus, wo Sie eigentlich zu gehört.

**Comment by DrGrizzlY17** [comment]
@DonVitoDiangelo Nope, das Haus hat ne eigentliche Garage. Die Garage gehört eigentlich zum Haus, das hinter der Garage liegt, welches nunmal keinen Sinn macht, deswegen soll er die Garage haben
