### ISSUE TITLE
Preisanzeige Restaurant

### ISSUE THREAD

**Issue by NLTrance** [mexyn/statev_v2_issues#696]
Eric Ahr
Restaurant: 🌎 NaNo.Evo.Food 🌎 Firmenhash: LongPig

Seit Update V2.0.15 - 30.11.2020

Die Preise werden im Restaurant angezeigt und Kunden können einkaufen, jedoch steht im Tablet (Intern als auch Extern) bei allen Produkten "0". Nach Rücksprache mit Gordon werden die Werte korrekt in die DB übermittelt.

https://pic.statev.de/i/Gm5WS.jpg
https://pic.statev.de/i/GmDmm.jpg

*Evtl. ähnliches Problem wie hier: https://github.com/mexyn/statev_v2_issues/issues/694
Jedoch können Kunden weiterhin einkaufen.

**Comment by MarcelMuerto** [comment]
Duplicate of #415

**Comment by MarcelMuerto** [comment]
#415
