### ISSUE TITLE
Mülleimer dubliziert sich

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#697]
**Character Name** Erwin Dulach

**Zeitpunkt (Datum / Uhrzeit)** 1.12 19:00

**Beobachtetes Verhalten** Mülleimer Chumash dubliziert sich beim interagieren

**Erwartetes Verhalten** Mülleimer besinnt sich auf seinen Job und behält sich in sich.
Man kann nach wie vor nur mit dem ersten Mülleimer interagieren.

**Schritte um den Fehler nachvollziehen zu können** E drücken 

**Optional: Video / Bilder des Fehlers**

https://x-up.ws/i/3f5f4344fa70.png

**Comment by DonVitoDiangelo** [comment]
@GD  Bitte nochmal prüfen.

**Comment by gd** [comment]
Ziemlich sicher ein anderer gd gemeint...

> @gd Bitte nochmal prüfen.
