### ISSUE TITLE
Lederjacken Namen vertauscht.

### ISSUE THREAD

**Issue by eldoodaks** [mexyn/statev_v2_issues#698]
**Character Name**
Darryl Bradley

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.12.2020 19:00Uhr

**Beobachtetes Verhalten**
[M] Cremeweiße DS Lederjacke
[M] Graue DS Lederjacke

Namen sind vertauscht bei den Lederjacken

**Erwartetes Verhalten**
Richtige bezeichnung

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/6449772fa27cba050b3d0a14faf3cfb0
https://gyazo.com/c0cdf34b64d6c2ae1c87ce63e32812a4

**Comment by Enemyaa** [comment]
Danke.. fixed!
