### ISSUE TITLE
Recht für Einlagern

### ISSUE THREAD

**Issue by VictorCorticera** [mexyn/statev_v2_issues#700]
Gustavo Luciano

01.12.2020 / 20:40

Mitarbeiter, die in einer Firma angestellt sind und das Recht "Lager ansehen" haben, können nicht einlagern. Es wird das Recht "Lager bearbeiten" benötigt.

Früher hat das Recht "Lager ansehen" ausgereicht, um einzulagern. Vielleicht ist es auch gewollt, allerdings können so quasi keine Mitarbeiter mehr angestellt sein, da ansonsten die Abuse-Gefahr zu hoch ist irgendetwas auszulagern. Es muss also alles über Ankauf erfolgen.

Rechte in einer beliebigen Firma "Lager ansehen" und "Lager bearbeiten" prüfen. Bei ersterem kann weder eingelagert noch ausgelagert werden, bei zweiterem kann beides gemacht werden.

**Comment by DonVitoDiangelo** [comment]
Jap ist so gewollt. Wen du IC vertraust, musst du dann selbst wissen. Und falls dich mal jemand bestiehlt, gibt es die Cops oder was auch immer dir an Lösungen einfällt.

**Comment by VictorCorticera** [comment]
Dafür muss ich aber erstmal wissen, dass jemand was gestohlen hat^^

**Comment by Tobse1904** [comment]
Was bei 15 Leuten schwierig werden kann finde ich , das es sinn macht das wen man einlagern kann auch auslagern kann darüber brauchen wir nicht diskutieren, aber ich finde dann sollten firmen irgendwie eine Möglichkeit haben zusehen wer was rein und raus legt
