### ISSUE TITLE
Funkgerät-Slot-Bild verzerrt

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#701]
**Character Name** Erwin Dulach

**Auftrittszeitpunkt (Datum / Uhrzeit)** 1.12 21:12

**Beobachtetes Verhalten** Absolutes Autistenproblem, aber das Bild, wenn kein Funkgerät eingelegt ist, ist verzerrt.

**Erwartetes Verhalten** Bild solle nicht verzerrt sein

**Schritte um den Fehler nachvollziehen zu können** Funkgerät von Slot ziehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)** 1920x1080

**Optional: Video / Bilder des Fehlers**

https://x-up.ws/i/b7e71a68a885.png
Zum Vergleich: wenn Funkgerät eingelegt ist:
https://x-up.ws/i/a1e198b00452.png

**Comment by Kalumel** [comment]
das gleiche mit dem Handy. Dort nur andersrum http://kalumel.jonesinc.de/GTA5_mnZ5wmdwnk.png
