### ISSUE TITLE
Preisanpassung von Dinka Marquis Motor!?

### ISSUE THREAD

**Issue by Irishman1991** [mexyn/statev_v2_issues#702]
Der Breis für den Motor des Dinka Merquis ist in Realisation zu den Fertigungskosten (ca. 25.000$) extrem hoch! Tatsächlich ist es einer der Teuersten Motoren die es im Import gibt! Ist das gewollt oder ein Fehler? 

![Motor_Preis](https://user-images.githubusercontent.com/75093060/100797403-5684ac80-3422-11eb-889e-528a786cfb03.png)

**Comment by DonVitoDiangelo** [comment]
gewollt
