### ISSUE TITLE
Werbung trotz leerem Hotelkonto möglich

### ISSUE THREAD

**Issue by Luca5k** [mexyn/statev_v2_issues#703]
**Character Name** Luca Fiedler

**Auftrittszeitpunkt (Datum / Uhrzeit)** 01.12 - 22:00 Uhr

**Beobachtetes Verhalten** Werbung für Hotel möglich, auch wenn Hotelkonto nicht genug gedeckt ist. Das Guthaben des Kontos ist dann negativ. 

**Erwartetes Verhalten** Keine Werbung möglich, da das Hotelkonto nicht gedeckt ist.

**Schritte um den Fehler nachvollziehen zu können** 1. Leeres Hotelkonto haben, 2. Werbung mit Verwendungszweck "Werbung für (Hotelname)", 3. Werbung schalten

**Optional: Video / Bilder des Fehlers**

Folgende Meldung erscheint, wenn die Werbung geschalten wird:
![Download](https://user-images.githubusercontent.com/75338130/100797307-3523c080-3422-11eb-958e-021a93caba97.png)

**Comment by its4l3x** [comment]
fixed next update
