### ISSUE TITLE
Voice Bug im MD (Pillbox Hill OP)

### ISSUE THREAD

**Issue by rubbaduck-twitch** [mexyn/statev_v2_issues#704]
Beim OP Tisch im Pillboxhill ist ein Object welches vom Voice Plugin als Barriere erkannt wird bei leisester/geringster range.
Anbei Clips die das veranschaulichen. Für nähere Details gerne an mich wenden oder Dan_Lee aus dem GD. Er weiss worum es geht.

https://clips.twitch.tv/PreciousAbrasiveTomatoPraiseIt
https://clips.twitch.tv/ArbitraryInquisitiveDumplingsTBTacoRight

**Comment by DonVitoDiangelo** [comment]
Bitte in die "First Person" gehen bei diesem Problem. Können wir so nicht weiter beeinflussen ohne das Feature zu deaktivieren.
