### ISSUE TITLE
Marker öffentliche Garage "Würfelpark"

### ISSUE THREAD

**Issue by No1likeyou** [mexyn/statev_v2_issues#705]
**Character Name**
Ben_Stark

**Auftrittszeitpunkt (Datum / Uhrzeit)**
01.12.2020 22:12 Uhr

**Beobachtetes Verhalten**
Mein Auto war in der öffentlichen Garage "Würfelpark" eingeparkt. Als ich per StateNET einen Marker auf die Garage gesetzt habe, wies dieser den alten Standort 

**Erwartetes Verhalten**
Anzeigen der korrekten Position

**Schritte um den Fehler nachvollziehen zu können**
1. Auto bei der Würfelpark-garage einparken.
2. StateNET öffnen und Marker beim entsprechenden Fahrzeug anfordern.

**Optional: Video / Bilder des Fehlers**
![Bug Würfelpark garage](https://user-images.githubusercontent.com/55114714/100798282-bb8cd200-3423-11eb-8c61-d379df758b18.png)

**Comment by its4l3x** [comment]
Hi, korrekt. In der Datenbank war noch die alte Position gespeichert. Fahrzeug ein ausparken hilft da. Können da nichts machen wenn sich die Positions updaten.

CLOSED
