### ISSUE TITLE
Garage am Kraftwerk fehlt

### ISSUE THREAD

**Issue by Jolu2831** [mexyn/statev_v2_issues#706]
**Vinc_Vega**

Vinc_Vega
**Auftrittszeitpunkt (Datum / Uhrzeit)**

start von V2
**Beobachtetes Verhalten**

Die öffentliche Garage am Kraftwerk fehlt
**Erwartetes Verhalten**

Ich werde irgendwann auf dem Weg zur nächsten öffentlichen Garage, diese befindet sich in Sandy ca. 1,5 km weit weg, überfahren. Vinc wohnt im Trailerpark hinter Dino Tankstelle. Ich gehe mal davon aus das dort noch mehr Personen wohnen. Nun gibt es keinen Fußweg / Gehweg von der Dino Tankstelle bis nach Sandy. Besonders gefährlich sind die beiden Brücken, einmal über die Schienen und einmal über den Freeway. Diese haben ebenfalls keinen Fußweg dafür viele wild gewordene Tanklaster und möchte gern Rennfahrer. Also Lebensgefährlich. Ich würde mich (bestimmt nicht alleine) daher freuen wenn die Garage am Kraftwerk wieder geöffnet werden würde.

**Schritte um den Fehler nachvollziehen zu können**

Von der Dino Tankstelle zu Fuß zur Garage nach Sandy, am besten wenn Betrieb herscht. Z.B. kleines Ölfeld hat offen.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Diese Garage war damals eingefügt worden als Festival Garage. Dadurch das wir uns damals intern geeinigt hatten diese nach dem Event wieder zu entfernen war es zu spät, da dort einige Fahrzeuge in dieser Garage waren. Durch V2 hatten wir diese Gelegenheit genutzt und diese Garage entfernt. Alle Fahrzeuge welche damals da waren, wurden in die NSA Garage Automatisch verschoben. Daher gewollt und kein Bug.
