### ISSUE TITLE
Garage für Haus

### ISSUE THREAD

**Issue by SevenJordan** [mexyn/statev_v2_issues#707]
Seven_Jordan

**Auftrittszeitpunkt (Datum / Uhrzeit)**
jetzt

**Beobachtetes Verhalten**
keine Garage, keine öffentliche in der Nähe

**Erwartetes Verhalten**
Eine Garage fürs Haus da 2 Leute deine aktiv wohnen

**Schritte um den Fehler nachvollziehen zu können**
Bitte eine Garage hinzu fügen bei SandyShores59

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Keine optische Garage am Haus verfügbar
