### ISSUE TITLE
Sanchez Tuning Verbuggt

### ISSUE THREAD

**Issue by ShauniKT** [mexyn/statev_v2_issues#708]
**Shauni Teller / Fahrzeug von Denis Lee**

**02.12.2020 / 18:17 Uhr**

**Beobachtetes Verhalten**

Maibatsu Sanchez Racing 88 PS
Das Motorrad wechselt dauerhaft die Folie. Wenn man es tunen möchte, gibt es keine Folien Option, einzig Scheibentönung. Mit dieser Option kann man auch die Folie ändern. Allerdings bleibt diese nicht und wechselt trotz allem das Motiv. Auch wenn man im Tuning Auswahlfenster Bremsen und felgen ändert, ändert sich die Folierung.

**Erwartetes Verhalten**

Folie bleibt bzw wechselt nicht dauerhaft. 

**Schritte um den Fehler nachvollziehen zu können**

- Sanchez auf Tuningpoint stellen
- Regler bei Scheibenfolie verändern
- Folie wechselt sich Random. Keine gezielte Auswahl der Folierung möglich.
- Bremsen und Reifen wechseln
- Folie ändert sich auch Random
- Bei Scheibenfolie zwischen Serie und Typ 1 hin und her wechseln
- Jedesmal ist die Serienfolie eine andere

**Optional: Video / Bilder des Fehlers**

Bei Scheibenfolie zwischen Serie und Typ 1 hin und her gewechselt 

https://prntscr.com/vuhfuz
https://prntscr.com/vuhg3o
https://prntscr.com/vuhgf6

**Comment by DrGrizzlY17** [comment]
#301
