### ISSUE TITLE
Selfie-Animation und automatischer Zoom für Selfie-Effekt

### ISSUE THREAD

**Issue by Gee1337** [mexyn/statev_v2_issues#71]
**Character Name**
Gee_Rodriguez

**Zeitpunkt (Datum / Uhrzeit)**
26.08.2020

**Beobachtetes Verhalten**
Bei einer Selfie-Animation zoomt die Kamera nicht automatisch ein.

**Erwartetes Verhalten**
Zoom-in für Selfie-Effekt

**Schritte um den Fehler nachvollziehen zu können**
Beliebige Selfie-Animation benutzen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**

![peache](https://user-images.githubusercontent.com/70242468/91301993-128c6680-e7a6-11ea-9c95-660b21a26baa.PNG)

**Comment by its4l3x** [comment]
Ist kein Bug. Ist mit Absicht draußen, und wird auch in naher Zukunft nicht mehr reinkommen.
