### ISSUE TITLE
Antrag: Be/Entladepunkt versetzen

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#710]
**Beobachtetes Verhalten**
Bitte den Ladepunkt für die Firma HK-K313 | 🍃Green Logistics📦 (Firmenhash: pfGroupAllRew_59) umsetzen. Das Gebäude wird hauptsächlich als Treibstofflager benutzt, und mit Achsen ist der Punkt sehr schwer zu erreichen, besonders wenn dort noch Autos geparkt werden (siehe Bilder).

**Optional: Video / Bilder des Fehlers**
Aktueller Punkt:
![](https://pic.statev.de/i/G2ciU.jpg)
![](https://pic.statev.de/i/G2U0c.jpg)

Vorschlag für neuen Punkt: 
![](https://pic.statev.de/i/G2Za0.jpg)

Vielen Dank

**Comment by Tobse1904** [comment]
Also ich finde der Punkt ist gut erreichbar habe da auch eine Firma und nutze diesen Punkt wer da parkt muss halt damit leben mal ne Beule im Fahrzeug zu haben.

**Comment by M4rvinLP** [comment]
> Also ich finde der Punkt ist gut erreichbar habe da auch eine Firma und nutze diesen Punkt wer da parkt muss halt damit leben mal ne Beule im Fahrzeug zu haben.
Trotzdem sehr schwierig da bei den eigenen Fahrzeugen keine Beulen rein zu machen

**Comment by M4rvinLP** [comment]
Trotzdem sehr schwierig da bei den eigenen Fahrzeugen keine Beulen rein zu machen

**Comment by Tobse1904** [comment]
Wie gesagt ich habe keine Probleme, und fahr mir auch keine Beule, bedenke der Punkt wird da von allen Firmen genutzt und da wo du ihn haben möchtest, müssten andere dann weiter laufen was beim Ankauf wieder total doof ist.

**Comment by M4rvinLP** [comment]
Ne es sollte ja nur meiner versetzt werden. Da sind bloß alle Punkte an der exakt gleichen Stelle, was du an der Transparenz vom Marker siehst. Die ist viel niedriger als bei anderen.

**Comment by Tobse1904** [comment]
Na wenn das so ist wie du sagst wäre mir das egal, aber wenn es alle firmen betrifft wäre ich dagegen weil dann haben andere wieder nen Nachteil

**Comment by DonVitoDiangelo** [comment]
nein, wenn dann nur der eine Marker seiner Firma :)

**Comment by Tobse1904** [comment]
Ah okay, wieder was dazu gelernt. Danke @DonVitoDiangelo , dann schau ich mal ob ich für das lager auch nen Antrag stelle, weil wir hatten schon das Problem das jemand anderes einfach ausgelagert hatte von ner anderen Firma. Wir es aber nicht nachweisen konnten.

**Comment by DrGrizzlY17** [comment]
Hatte keine Probleme da anzufahren... außerdem wenn man sich die Begebenheiten anschaut, sollte einem klar sein das man dort nicht unbedingt mit großen Geräten hantieren sollte

**Comment by M4rvinLP** [comment]
ok..
