### ISSUE TITLE
Kopfbedeckungen im Fahrzeug

### ISSUE THREAD

**Issue by Craig-Statev** [mexyn/statev_v2_issues#712]
Aktuell ist es so das beim einsteigen in ein Fahrzeug man die Kopfbedeckung "Hut, Mütze etc." Automatisch abgesetzt bekommt.
So ist man gezwungen diese jedesmal wieder aufzusetzen. Und das ist auf dauer sehr anstrengend, gibt es da eine möglichkeit dies zu ändern? "Ja", als Sandfahrer und Deputy muss ich oft Ein- und Aussteigen. Denke es käme jedem auf dem Server mit Kopfbedeckung zu Gute.

**Comment by DonVitoDiangelo** [comment]
Nein, Kopfbedeckungen werden standardmäßig immer im Fahrzeug abgesetzt, da Sie sonst durch Dächer glitchen können etc.
Das wird auch so bleiben.
