### ISSUE TITLE
Versetzung Be / Entlade Punkt

### ISSUE THREAD

**Issue by Tobse1904** [mexyn/statev_v2_issues#714]
**Firmenhash :** pfGroupAllRew_84

Hiermit beantrage ich die Versetzung des Be / Entlade Punktes.

**Begründung :** 1. Man muss nicht immer Brüllen wie nen Irrer :D
                       2. So kann vermieden werden das jemand von einer anderen Firma einem den Wagen / Achse / was auch immer 
                       leer macht leider ist dies vor längerem schon passiert, gibt allerdings keine beweise hierfür.

**Aktueller Be / Entlade Punkt :** 

![271590_20201203145126_1](https://user-images.githubusercontent.com/39304481/101027190-13d4e880-3578-11eb-96cb-026efdc6e2f3.png)

**Gewünschter Be / Entlade Punkt :** ( da wo der Kamacho steht )

![271590_20201203145204_1](https://user-images.githubusercontent.com/39304481/101027245-1f281400-3578-11eb-8fd1-d299993368f9.png)

**#Danke #Devsloben #ihrmachtnegeilearbeit**

**Comment by DrGrizzlY17** [comment]
Wenn wir jeden Punkt separieren besteht der Parkplatz nur noch aus Markern. Einfach aufpassen ob jemand da ist oder nicht.

**Comment by Tobse1904** [comment]
Bei der Menge an Firmen nicht immer möglich, und nachweisen kann man es leider auch nicht das es einer raus genommen hat. Aber Trotzdem Danke muss ich das halt RP mäßig anders lösen falls sowas nochmal passiert.
