### ISSUE TITLE
Magazin wird nicht leer (letzte Kugel)

### ISSUE THREAD

**Issue by RomanSpielberg** [mexyn/statev_v2_issues#715]
Roman_Spielberg

03.12.2020 16:09Uhr

HK P7 mit einem Magazin ausrüsten, wo nur noch eine Kugel drin ist. Die letzte Kugel abfeuern und danach die Waffe wieder ab legen. Im Inventar erscheint die HK P7 und wieder ein Magazin mit 1 Kugel.

Das Magazin muss leer sein oder verschwinden.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by RomanSpielberg** [comment]
Habe es jetzt mal noch mehrfach gemacht, vermutlich nach dem 6. mal war dann das Magazin doch weg.

**Comment by DonVitoDiangelo** [comment]
Keine hohe Relevanz. Wird bei Zeiten mal jemand drüber schauen.

**Comment by its4l3x** [comment]
Besteht das Problem immer noch? Bitte nochmal nachtesten.

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1134

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1642https://github.com/mexyn/statev_v2_issues/issues/1642
