### ISSUE TITLE
Motorrad Felgen ändern sich nur beim Vorderrad

### ISSUE THREAD

**Issue by thumbsucker** [mexyn/statev_v2_issues#716]
**Character Name**
Riley Everett

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.12.2020 - Eigentlich schon immer 

**Beobachtetes Verhalten**
Wir haben unter den Felgen Typen welche die "Bike Wheels" heißen und auch Optisch wohl für Motorräder gedacht sind. Allerdings ändert sich bei der Auswahl immer nur das Vorderrad. Dies war auch schon vor v2 so. 

**Erwartetes Verhalten**
Wenn dieser Felgen Typ für Motorräder gedacht ist, sollten sich auch beide Räder ändern und nicht nur das Vorderrad. 

**Schritte um den Fehler nachvollziehen zu können**
Siehe Video

**Optional: Video / Bilder des Fehlers**

https://streamable.com/r81xub

https://streamable.com/8upwbl

**Comment by JulianMa** [comment]
Mit nächstem Update behoben.
