### ISSUE TITLE
Großen Waffenschein austellen

### ISSUE THREAD

**Issue by TaylorTheguy** [mexyn/statev_v2_issues#717]
**Character Name**
Taylor_Durden

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.12.2020 19:30

**Beobachtetes Verhalten**
Bürger setzt sich auf den Stuhl, ich interagieren mit ihm und bekomme die Oberfläche zum ausstellen eines kleinen Waffenscheins trotz des Gutachtens welches ihm erlaubt einen großen zu bekommen. 

**Erwartetes Verhalten**
Bürger setzt sich auf den Stuhl, ich interagieren mit ihm und bekomme die Oberfläche zum ausstellen eines kleinen oder großen Waffenscheins. 

**Schritte um den Fehler nachvollziehen zu können**
Jemanden auf den Stuhl setzen mit einem Gutachten des LSMDs welches ihm erlaubt den kleinen und / oder großen Waffenschein zu bekommen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by tastydev** [comment]
Schonmal in eine andere Richtung gedacht? :-)

**Comment by TaylorTheguy** [comment]
ja freilich habe ich , wir sind im RP nochmal zum LSMD gefahren  mit dem Kunden. Im LSMD hat man uns versichert das sie alles richtig gemacht haben, was das Gutachten angeht. Und einen kleinen Schein haben wir ihm auch ausgestellt um zu sehen ob dann der große Schein auf plopt. Weshalb ich nun von einem "Fehler" ausgegangen bin.
