### ISSUE TITLE
Kleidung verschwindet beim anziehen, wenn man noch ein Outfit trägt

### ISSUE THREAD

**Issue by zarazandra** [mexyn/statev_v2_issues#72]
**Character Name**
Shiva_Connelly

**Zeitpunkt (Datum / Uhrzeit)**
26.08.20; 14:45

**Beobachtetes Verhalten**
Zieht man ein Kleidungsstück, in dem Fall grau/schwarze Camo-Leggins an, während man noch ein Outfit trägt (Knastoverall), verschwindet das Icon, es kommt aber die Fehlermeldung, dass man erst das Outfit ausziehen muss. 

**Erwartetes Verhalten**
Die Hose landet wieder im Inventar ODER das Outfit wird automatisch ausgezogen

**Schritte um den Fehler nachvollziehen zu können**
Hose auf den Slot ziehen/doppelklicken, während noch ein Outfit angelegt ist

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
"verschwindet das Icon" welches Icon? Das des anzuziehenden Kleidungsstück?

**Comment by zarazandra** [comment]
Das Icon im Sinne von: der Gegenstand ist nicht mehr da und wird auf der Kleidungsseite nicht mehr angezeigt (als hätte man nichts an). Das Item befindet sich nicht mehr im Inventar danach und kann nicht mehr zurückgeholt werden. 
Zieht man das Outfit aus, kann man sich ganz normal ankleiden.

**Comment by eiksch** [comment]
Ich hab einen Taucheranzug, ziehe ihn an... dann will ich Schuhe anziehen -> passiert nix. Schuhe bleiben im Inventar. Kannst du das immer wieder reproduzieren?

**Comment by zarazandra** [comment]
Müsste es ausprobieren, bin aktuell auf dem Liveserver. Gebe Meldung, sobald ich das reproduziert habe.

**Comment by DrGrizzlY17** [comment]
Also du hast da wirklich nen Zaubertrick hingekriegt. Ich hab jetzt mehrmals es versucht zu replizieren aber ich kriege es nicht hin. Ich kann kein Kleidungsstück anziehen, solange ich ein Outfit trage

**Comment by r3sist3nt** [comment]
Ich kann mir die stelle mal im Code anschauen, vielleicht gibt es da nen edge-case. Ich will das da nicht ausschließen.

**Comment by zarazandra** [comment]
> Also du hast da wirklich nen Zaubertrick hingekriegt. Ich hab jetzt mehrmals es versucht zu replizieren aber ich kriege es nicht hin. Ich kann kein Kleidungsstück anziehen, solange ich ein Outfit trage

Ja... Wenn ich eins kann, dann das... Ich probiere es gleich nochmal,sobald ich an den Rechner gehe.

**Comment by zarazandra** [comment]
Info: Bei mir funktioniert es auch nicht mehr. Ich weiß, dass ich, nachdem der Bug aufgetreten ist, definitiv keine Leggins mehr hatte, da ich sie erst direkt davor gekauft habe und sich kein solches Objekt mehr in meinem Inventar befunden hat. Jetzt, nachdem ich quasi neugestartet habe, hatte ich aber eine zweite Leggins, die allerdings im Auto lag. 
Bin gerade selbst etwas verwirrt. 

Ich denke mal, dass das geclosed werden kann, da ich es selbst auch nicht mehr reproduzieren kann mit den gleichen Gegenständen.

**Comment by eiksch** [comment]
Wir haben natürlich auch noch recherchiert dazu. Wenn du die Fehlermeldung bekommst hast, zieht dir das System vorher nichts ab. Also die Fehlermeldung ist in dem Fall das Zeichen, das alles nach Plan funktioniert.

Ich schließe das einfach mal.
