### ISSUE TITLE
Unsichtbare Hitbox in Auffahrt

### ISSUE THREAD

**Issue by AngelMaravilla** [mexyn/statev_v2_issues#720]
**Character Name**
Angel Maravilla

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Am 03.12.2020 zum ersten Mal aufgefallen. Nicht genau bekannt, ob das Problem vorher bestand.

**Beobachtetes Verhalten**
In der Auffahrt des Gebäudes house_Vinewood_0 fiel heute (03.12.2020) eine merkwürdige, kleine Hitbox direkt in der Einfahrt auf. Dabei handelt es sich um ein unsichtbares Objekt, etwa quaderförmig und circa 20cm hoch (Siehe Bild). Beim Fahren in die Auffahrt ist das Fahrzeug mit der Hitbox kollidiert und nahm Schaden, an der unsichtbaren Hitbox waren danach ebenfalls Kratzer zu sehen. Es ist möglich, dass dieser Fehler mit dem letzten Update aufgetreten ist, da zuvor noch nie ein Fahrzeug mit dieser Hitbox kollidiert ist, obwohl die Auffahrt täglich mehrfach befahren wird.

**Erwartetes Verhalten**
Es befindet sich keine unsichtbare Hitbox auf der Einfahrt.

**Schritte um den Fehler nachvollziehen zu können**
Mit einem flachen Fahrzeug möglichst mittig die Einfahrt hochfahren. Am Scheitelpunkt der Auffahrt kollidiert das Fahrzeug mit dem Objekt. Oder mit einem Char darüber laufen, sodass er seinen Fuß darauf abstellt (siehe Bild).

![hitboxbug](https://user-images.githubusercontent.com/74780492/101088084-6bdd1080-35b3-11eb-9d8d-1a3c3eb567b1.png)

**Comment by DonVitoDiangelo** [comment]
Einfach mal gucken was da so aufgestellt wurde in der näheren Umgebung. Vllt. gibt es hier wie bei den Tankstellen so eine Ecke die 10 Meter weit reicht.

**Comment by AngelMaravilla** [comment]
Stellt sich raus, dass jeweils die vier Eckpunkte der Lichterkette auf Bodenhöhe die Hitbox verursachen.
Kann geschlossen werden.
