### ISSUE TITLE
Firefox: StateNET broken

### ISSUE THREAD

**Issue by ProgrammingFox** [mexyn/statev_v2_issues#722]
**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Gestern abend ab 18:00 Uhr + heute

**Beobachtetes Verhalten**

StateNET im Firefox ist nicht mehr funktionabel. Viele Tabs lassen sich nicht mehr öffnen oder stacken sich untereinander an.

**Erwartetes Verhalten**

Dass das StateNET normal funktioniert.

**Schritte um den Fehler nachvollziehen zu können**

Firefox -> StateNET einloggen -> benutzen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![grafik](https://user-images.githubusercontent.com/48456305/101151973-b34eb580-3622-11eb-9f54-5b24df3ac850.png)

**Comment by JulianMa** [comment]
12 Uhr restart dann fixex
