### ISSUE TITLE
Scrollen im Inventar / Tablet / Smartphone nicht möglich

### ISSUE THREAD

**Issue by Schamocke** [mexyn/statev_v2_issues#723]
**Cam_Snyder**

s.o.
**Auftrittszeitpunkt (Datum / Uhrzeit)**

seit 03.12.2020 permanent
**Beobachtetes Verhalten**

Scrollen mit Mausrad in sämtlichen In-Game Listen nicht möglich (Tablet / Smartphone / Schrankinventar)
**Erwartetes Verhalten**

Scrollen sollte möglich sein
**Schritte um den Fehler nachvollziehen zu können**

sobald Auflistungen zu lang sind, dass man Scrollen muss, funktioniert das in o.g. Interfaces nicht. Bei den allgemeinen Ingame Einstellungen wie Grafik, Audio usw. funktioniert das Scrollen jedoch einwandfrei.
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

Dashboard, Kontaktliste oder Hotelinventar öffnen und versuchen über das Mausrad zu scrollen.
**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Ist problemlos möglich. Hast du das Problem öfter oder immer? Kannst du es reprodzuzieren?

**Comment by Schamocke** [comment]
Ich habe das Problem seit Donnerstag abend durchgängig. Kann meine Interfaces nur noch über die Scrollbar an der Seite durchgehen. Ich würde gerne einen Videobeweis erstellen, was sich als schwierig erweist, da Tastenbefehle nicht aufgenommen werden. Evtl. kann man einen Termin für TS oder DC vereinbaren, ob es sich nicht irgendwie besser erklären oder sogar schon troubleshooten lässt?

**Comment by DonVitoDiangelo** [comment]
gehe am besten mal dazu in den Support. Dort wird man dir dann helfen.
