### ISSUE TITLE
Funk blockiert

### ISSUE THREAD

**Issue by GonzoMenendez** [mexyn/statev_v2_issues#726]
Gonzo_Menendez

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Zufälliges Verhalten während der PlayTime

**Beobachtetes Verhalten**
Zwischenzeitlich kommt es vor das trotz des Betätigen des Funks, der Funk nicht ausgelöst wird.
Gut zu erkennen ist das die Animation dazu ebenfalls nicht startet.
Bisher lässt es sich aber schwer nachvollziehen wann genau es eintrifft.
Lösen lässt sich das nur beim Aus- und Wiedereintreten in den Funk-Kanal

**Erwartetes Verhalten**
Funktatser zu jeder Zeit Möglich - andere beschreibung fällt mir ned ein ^-^

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/771

**Comment by its4l3x** [comment]
Immer noch beständig?

**Comment by JannikDatsch** [comment]
Ja, kommt weiterhin vor.
