### ISSUE TITLE
Outfit-Editor

### ISSUE THREAD

**Issue by GonzoMenendez** [mexyn/statev_v2_issues#728]
Gonzo_Menendez

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit Patch Änderung

**Beobachtetes Verhalten**
Wenn man den Outfitter benutzt und eine weile (ca5-10) sekunden nichts auswählt,
zieht der Charakter automatisch seine aktuelle Kleidung an statt "NAckt" zu bleiben.
Man muss also stetig den Outfitter neu öffnen oder ein bereits bestehendes preSet editieren.
Dabei werden aber Kleidungsstücke welche das PreSet nicht hat, aber der Char anhat (zb Krawatte) in das PreSet als Anzeige übernommen

**Erwartetes Verhalten**
Char bleibt Nackt, oder zeigt nur ausgewählte Kleidungsstücke aus dem Outfitter an

**Schritte um den Fehler nachvollziehen zu können**
Outfitter öffnen und warten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
fixed next update
