### ISSUE TITLE
Sortierung der Kleidung

### ISSUE THREAD

**Issue by GonzoMenendez** [mexyn/statev_v2_issues#729]
Gonzo_Menendez

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit Änderung

**Beobachtetes Verhalten**
Eine Änderung zur Sortierung der Kleidung beißt sich mit dem Gehaltsklassen-System"
Durch die Änderung des Sortier-Systems sind (sofern man Uniformen ncicht nach Rang Sortiert)
komplett durcheinander.
Da es mit V2 ja nun das Gehalts-Klassen System gibt müssen dementsprechend Uniformen versch. Ränge alle auf einen Rang (bei PD 0) Damit bei einer Änderung zum Gunsten oder zum negativen des Betroffenen dennoch alle Kleidungen des jw. Ranges benutzt werden können.
Eine Sortierung nach Namen wäre hier empfehlenswerter anstelle der Sortierung nach Rang / Herstellung / Name
um die Breitgefächerte möglichkeiten des Gehalts-Klassensystems nutzen zu können

Beim PD sortieren wir dies mit Zahlen
Beispielsyntax:  [M][100] LSPD: Officer II - Schutzweste
                         [M][210] BCSO; Deputy III - Warnweste

 
**Erwartetes Verhalten**
Eine Umänderung des Sortiersystems damit man auch bei einer größeren Auswahl an Uniformen eine Übersichtliche Sortierung
nutzen kann

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Klärt das IC. Die Sortierung könnt Ihr entsprechend selbst durch Benennung vornehmen.
Alles andere wie gesagt IC, wenn jemand z.B was falsches trägt etc.,
