### ISSUE TITLE
Fahrzeuge schieben

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#73]
**Character Name**
Paul Schmutz

**Zeitpunkt (Datum / Uhrzeit)**
26.08.2020 / 14:49

**Beobachtetes Verhalten**
Wenn man ein Fahrzeug schiebt und das Handy zieht beendet das die Animation aber man schiebt weiter. 

**Erwartetes Verhalten**
Wenn man das Handy zieht sollte aufgehört werden zu schieben.

**Schritte um den Fehler nachvollziehen zu können**
1. Fahrzeug schieben
2. Handy ziehen

**Comment by Kalumel** [comment]
@its4l3x das gleiche passiert mit dem Tablet.

**Comment by its4l3x** [comment]
Okay, auch fixed

**Comment by Kalumel** [comment]
und beim Fingerzeigen auch noch :D @its4l3x
