### ISSUE TITLE
Abschlepper des SAPD (Tow Truck)

### ISSUE THREAD

**Issue by GonzoMenendez** [mexyn/statev_v2_issues#730]
Gonzo Menendez

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.12.20 - ggn Mitternacht

**Beobachtetes Verhalten**
Die Getauschten Tow-Trucks des SAPD für Notfälle haben die Möglichkeit Fahrzeuge 
"Aufzusatteln" - aber sobald die Fahrzeuge drauf sind können diese nicht mehr aus der Kabine heraus abgelassen werden.
Seltsamerweise betrifft dies aber NUR die aktuellen Trucks des SAPD. Eventuell Falsches Fahrzeug o.Ä?

**Erwartetes Verhalten**
Nutzung der Abladefunktion für die SAPD Tow Trucks

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Wie genau stellt sich das dar? Kein XMENU Eintrag, Fehlermeldung ?

**Comment by GonzoMenendez** [comment]
Genau man sieht das ICON spezifisch bei diesen Trucks nicht im X-Menü

**Comment by DonVitoDiangelo** [comment]
Kann ich im test nicht bestätigen. Funktioniert ganz normal alles. Was war hinten drauf?

**Comment by GonzoMenendez** [comment]
Ein Mietfahrzeug, hier war es ein Emporer in unserem Fall

**Comment by DonVitoDiangelo** [comment]
Kann auch nicht bestätigt werden. Falls es reproduziert werden kann, erneut melden.

**Comment by TheBroady** [comment]
@GonzoMenendez 
Man muss zum Ablassen des Fahrzeugs im Towtruck sitzen, und darf während des Prozesses nicht aussteigen.
