### ISSUE TITLE
Abschleppbare Fahrzeuge

### ISSUE THREAD

**Issue by GonzoMenendez** [mexyn/statev_v2_issues#731]
Gonzo_Menendez

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
Das Mietfahrzeug Bodhi sowie der Guardian lassen sich nciht von einem Abschlepper aufladen.
Beide Fahrzeuge können auch nicht geschoben werden

**Erwartetes Verhalten**
Aufgrund der Schwere könnte ich verstehen das diese nicht geschoben werden können.
Aber man sollte diese auf den Schlepper laden können da man sie nicht beseitigen kann

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Der Guardian ist blacklisted, weil zu groß und der Bodhi kann normal aufgeladen werden.
