### ISSUE TITLE
Game und UI-Crash

### ISSUE THREAD

**Issue by MrGotAB** [mexyn/statev_v2_issues#734]
**Character Name**

Jason_Forelli

**Auftrittszeitpunkt (Datum / Uhrzeit)**

04.12.2020 19:00 - 19:30

**Beobachtetes Verhalten**

Gamecrash, UI-Crash

**Erwartetes Verhalten**

Keine Crashs

**Schritte um den Fehler nachvollziehen zu können**

sporadisch aufgetreten, keine Rekonstruktion möglich

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

[interface.txt](https://github.com/mexyn/statev_v2_issues/files/5644674/interface.txt)
https://github.com/mexyn/statev_v2_issues/files/5644676/altv_1301_Social.Club_0x53ec46_04-12-2020_19-19-04.zip
https://github.com/mexyn/statev_v2_issues/files/5644681/altv_1301_Social.Club_0x6073b4_04-12-2020_19-01-06.zip
https://github.com/mexyn/statev_v2_issues/files/5644683/altv_1301_Social.Club_0x626a77_04-12-2020_18-54-42.zip

**Comment by DonVitoDiangelo** [comment]
Wo warst du? Was hast du gemacht?

**Comment by MrGotAB** [comment]
War vor und im Gericht, habe aber keine besonderen Aktionen durchgeführt, bin lediglich in diesem Bereich gelaufen.
