### ISSUE TITLE
Inventar überladen durch Waffen entholstern und anschließend hat Essen keine Wirkung mehr

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#736]
**Character Name** Erwin Dulach

**Auftrittszeitpunkt (Datum / Uhrzeit)** 4.12.20 ~21:10

**Beobachtetes Verhalten** Man kann das Inventar durch Waffen entholstern überladen. Anschließend hat das benutzern von Lebensmitteln keinen Effekt mehr.

**Erwartetes Verhalten** Inventar kann nicht überladen werden und Lebensmittel haben keinen Effekt mehr.

**Schritte um den Fehler nachvollziehen zu können** Waffen ausrüsten, Inventar beladen, Waffen entrüsten, Lebensmittel verwenden.

**Optional: Video / Bilder des Fehlers**

https://youtu.be/wOXzeFGX-6g (Video Zeigt auch Bug #522 )

**Comment by its4l3x** [comment]
solved siehe mention oben
