### ISSUE TITLE
Schneiderei - Nicht produzierbar

### ISSUE THREAD

**Issue by jonesXYZ** [mexyn/statev_v2_issues#737]
**Character Name**
Maximilian_Jones

**Auftrittszeitpunkt (Datum / Uhrzeit)**

04.12.20 - 22:47

**Beobachtetes Verhalten**
Seihe Screenshot, lässt sich nicht Produzieren.
Firma - Schneiderei
Hash - pfEveMorningwoodRew_3

**Erwartetes Verhalten**
Lässt sich produzieren.

**Schritte um den Fehler nachvollziehen zu können**
Produktion öffnen -> Item produzieren -> Error.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
n/a

**Optional: Video / Bilder des Fehlers**
![GTA5_a0ITvyb1XM](https://user-images.githubusercontent.com/44285771/101218310-212ac980-3683-11eb-95c6-0c3ce5596850.jpg)

**Comment by DrGrizzlY17** [comment]
Bitte noch das Icon hinzufügen. Die Produktion is fixed

**Comment by DonVitoDiangelo** [comment]
Icon zieht er sich selbst. Hier am besten @Enemyaa  das Kleidungs-Thema überlassen. Sie kann dann checken, ob oder was da genau nicht stimmt.
