### ISSUE TITLE
Inhaber kann Fahrzeuge von Autohaus nicht benutzen

### ISSUE THREAD

**Issue by VictorCorticera** [mexyn/statev_v2_issues#738]
Gustavo Luciano

05.12.2020 / 01:00

Inhaber, Simon Maddicks, des Autohauses (Яeaction 👁‍🗨 Corp - Carshop) konnte ein Ratbike, das auf das Autohaus geschrieben ist, nicht aufschließen. Es wird ein Fehler angezeigt, dass der Schlüssel nicht vorhanden sei. Der Mitarbeiter Gustavo Luciano mit allen Rechten, konnte das Fahrzeug aufschließen und damit fahren.

Der Inhaber sollte alle Rechte und damit auch die Schlüssel für Fahrzeuge des Autohauses haben.

Inhaber eines Autohauses werden, kein Mitarbeiter mehr sein, Fahrzeug auf das Autohaus schreiben, Fahrzeug versuchen aufzuschließen. Getestet wurde es nur mit einem Ratbike, gehe aber davon aus, dass ein generelles Problem ist. Kann das morgen aber auch nochmal ggf. testen.

![2deab861953af84fc35a19de4eec197e](https://user-images.githubusercontent.com/28830176/101227666-f481ac80-3698-11eb-849b-9a20988faf5b.png)

**Comment by its4l3x** [comment]
Kann das leider nicht bestätigen - Bitte bedenke das dies auch durch ein längerer Save Process resultieren kann.

In Zukunft einfach kurz paar Sekunden mehr warten, dann sollte dies auch nicht passieren.
