### ISSUE TITLE
LED Unterboden anstatt Xenon Lichter

### ISSUE THREAD

**Issue by CatherineGallagher** [mexyn/statev_v2_issues#74]
**Character Name**
Catherine Gallagher

**Zeitpunkt (Datum / Uhrzeit)**
25.08.20 / 19 Uhr

**Beobachtetes Verhalten**
Es werden für das verbauen der Xenon Lichter 4x LED Unterbodenbeleuchtungen verbraucht
**Erwartetes Verhalten**
Es wäre sinniger für Xenon Lichter , dass auch Xenon Lichter verbraucht werden, in dem Fall 2x Xenon Lichter.

**Schritte um den Fehler nachvollziehen zu können**
Bein Tunen Xenon Lichter einbauen und es steht unten was verbraucht wird.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
next update changed
