### ISSUE TITLE
Man kann an meinem Firmengebäude die Leiter nicht runterklettern. 

### ISSUE THREAD

**Issue by MrFluffig** [mexyn/statev_v2_issues#740]
Michael Dooley
 Michael Dooley

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 04.12.2020 23:30

**Beobachtetes Verhalten**
 Man kann an meinem Firmengebäude (HK-P978 | 🐮Metzgerei⚜️König⚜️ - Popular Street 50) die große Leiter aufs dach hinaufklettern und auf die leiter darüber auch, leider kann man nicht mehr runterklettern weil die leieter nicht erkennt das jemand an der leiter steht und runterklettern möchte. ist das fixbar ?

**Erwartetes Verhalten**
 an geht auf die leite zu und wenn man an der leiter ist wird der charackter automatisch an diew leiter gesetzt und kann runterklettern

**Schritte um den Fehler nachvollziehen zu können**
 einfach ausprobioeren. hochklettern und dann versuchen wieder runterzuklettern

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
 irrelevant

**Optional: Video / Bilder des Fehlers**

[https://www.bilder-upload.eu/bild-edd9fd-1607132228.png.html](url)

**Comment by DonVitoDiangelo** [comment]
können wir nichts dran ändern
