### ISSUE TITLE
Störenden Sattelanhänger entfernen (Mapping)

### ISSUE THREAD

**Issue by MrFluffig** [mexyn/statev_v2_issues#741]
Michael Dooley

**Beobachtetes Verhalten**
Das gelände meiner firma könnte groß und geräumig sein, wenn dieser Sattelauflieger dort nicht stehen würde. Dummerweise steht er direkt vor dem Eingang und man kommt auch dran vorbei um in das gebäude einzutreten aber man muss die lkws immer so weit vorne hinstellen und dann immer soweit laufen. Der Auflieger nimmt wirklich viel platz weg und stört auch massiv das erscheinungsbild ich würde mich freuen, wenn ihr so nett wärt und den sattelauflieger entfernt. habe das auch schon in codewalker ausprobiert und den auflieger mit der collision unter die map gezogen. hat wunderbar funktioniert.

Ist jetzt kein kritisdher fehler aber  ich würde mich wirklich riesig freuen, wenn ihr das hässliche riesige teil entfernen könntet :)

**Optional: Video / Bilder des Fehlers**

[https://www.bilder-upload.eu/bild-1d75d7-1607132524.png.html](url)
[https://www.bilder-upload.eu/bild-cd952c-1607132555.png.html](url)

**Comment by DonVitoDiangelo** [comment]
Können wir nichts machen, da die collision von dem Anhänger bleiben würde, daher abgelehnt.
