### ISSUE TITLE
Stundenlohnauszahlung in Firma wird nicht durchgeführt

### ISSUE THREAD

**Issue by MrFluffig** [mexyn/statev_v2_issues#742]
Michael Dooley

Ich habe eine Metzgerei gepachtet. Ich zahle meinen Mitarbeitern Stundenlohn zwischen 100 und 200 Dollar pro stunde. Das ist auch unter Gehälter so eingestellt. Die mitarbeiter loggen sich auch immer ein und aus. Das Problem ist, dass die mitarbeiter sich einloggen und das system einfach keinen stundenlohna uszahlt. Auf dem Firmenkonto sind über 20.000 Dollar drauf. Es wurde bis jetzt kein gehalt abgebucht, obwohl bereits um die 10 Stunden arbeit im eingestempelten zustand stattgefunden hat. habe es bei mehreren Personen in der firma ausprobiert und auch an mir selber, aber es wird kein gehalt üpberwiesen.

**Comment by BlackyGER** [comment]
https://github.com/mexyn/statev_v2_issues/issues/361

**Comment by Solomonetix** [comment]
ich frag mich was für eine "a confirmation for this issue is needed" NOCH nötig ist? Das Problem wurde doch mehrfach schon gemeldet!
ICH bekomme seit V2 kein Gehalt mehr! Seit weit über 40 Onlinestunden.
Und dann wird gemeckert das keine Steuern rein kommen. Ja wie auch.

**Comment by MrFluffig** [comment]
Fehler ist imemrnoch vorhanden

**Comment by its4l3x** [comment]
Hi zusammen,

Dieser Fehler ist bereits gefixed.

Ich verlinke mal das Ticket #361 hiermit, da ich dort eine kleine Antwort gegeben habe zu diesem Thema.
