### ISSUE TITLE
Stundenlohnauszahlung wird nicht durchgeführt (seit v2 Release)

### ISSUE THREAD

**Issue by ShauniKT** [mexyn/statev_v2_issues#747]
**Shauni Teller**

**Seit V2 Release)**

**Beobachtetes Verhalten**

Sei dem Release von V2 wird in keiner mir bekannten Firma Stundenlohn ausgezahlt. In meinem Falle betrifft es Bennys. Die Leute stempeln sich auch dauerhaft ein um zu gucken, ob es wieder geht, aber, leider beseht dieses Problem weiterhin, was nun einmal für Leute, welche keine Provisionen, sondern Festgehälter zahlen wichtig ist.

Versuche das Problem zu fixen ohne Erfolg:
- Mitarbeiter entlassen und wieder Einstellen
- Stundenlohn hin und her ändern
- generell Mitarbeiter auf unter 15 reduzieren (Dachten lag an unseren 18 Mitarbeitern)

**Erwartetes Verhalten**

Stündlich ausgezahlter Lohn für die eingecheckten Mitarbeiter in einer Firma, wie es auch im PD/MD/etc funktioniert

**Schritte um den Fehler nachvollziehen zu können**

- Mitarbeiter einstellen
- Stundenlohn einstellen
- eine Stunde eingecheckt sein und warten
- nix passiert

**Comment by DrGrizzlY17** [comment]
#742
