### ISSUE TITLE
Tore mit "E"

### ISSUE THREAD

**Issue by CaptainGhostLive** [mexyn/statev_v2_issues#749]
**Emilio_Luciano**

**Das Haus von Michael welches IC bereits verkauft ist an an den außen Toren eine Funktion womit man mit "E" das Tor auf und zu machen kann (jeder kann dies machen), da an der Werkstatt das Tor dauerhaft auf und zu geht sobald sich da wer nährt würde ich das auch gerne an Unserer Werkstatt beantragen wollen, da wir so das Tor Dauerhaft auflassen könnten. Zusätzlich würde ich das selbe am Haus von "Christian Bings" beantragen, da genau das selbe Problem herrscht.**

MFG 
Emilio

**Comment by DonVitoDiangelo** [comment]
abgelehnt
