### ISSUE TITLE
Bei verunfalltem Auto (rote Leuchte, nicht ausgebrannt) kommt man nicht mehr an den Kofferraum

### ISSUE THREAD

**Issue by zarazandra** [mexyn/statev_v2_issues#75]
**Character Name**
Shiva_Connelly

**Zeitpunkt (Datum / Uhrzeit)**
26.08.20, 15:05

**Beobachtetes Verhalten**
Fahrzeug ist verunfallt, Motorhaube hat kurz gebrannt und das Feuer ist ausgegangen. 
Danach war kein Zugriff mehr auf den Kofferraum möglich, ohne dass das Fahrzeug ausgebrannt ist. 

**Erwartetes Verhalten**
Man kann nach Öffnen des Kofferraumes auf dessen Inhalt zugreifen

**Schritte um den Fehler nachvollziehen zu können**
Fahrzeug kaputt fahren, ohne dass es ausbrennt, Fahrzeug und anschließend Kofferraum öffnen, hintendran stellen und i drücken. Es öffnet sich nur das reguläre Inventar.
![unknown](https://user-images.githubusercontent.com/70195103/91307393-2c31ac00-e7ae-11ea-9e98-bc291bfda775.png)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by eiksch** [comment]
Ist vorerst so gewollt.
