### ISSUE TITLE
Rechnungsbug bei Tattoostudio Stichfest

### ISSUE THREAD

**Issue by adn1337** [mexyn/statev_v2_issues#750]
**Character Name**
Michael_Kusnetzov

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.12.2020 um 18:55, 19:19, 19:31 & 19:49

**Beobachtetes Verhalten**
Mitarbeiter hat in First Person eine Rechnung ausgestellt. Geld wurde dem Konto zugeschrieben und der Mitarbeiter hat es zusätzlich bar erhalten. Dem Kunde wurde der Betrag aber nur einmal abgezogen

**Erwartetes Verhalten**
Geld wird nur dem Firmenkonto zugeschrieben und dem Kunde einmal abgezogen

Bei weiteren Fragen bitte an Akin Tas (Discord: Resox#8153) oder Adrian Luciano (adn ;.#3222) wenden.

**Comment by its4l3x** [comment]
Kann ich nicht bestätigen. Gegengetestet gerade eben. Würde mich wundern, wenn das neu wäre. Da wir das Tattoo System seit Beta nicht mehr angerührt hatten. Hatte sukzessiv damals das Tattoo System getestet gehabt.
