### ISSUE TITLE
Y durch Wand

### ISSUE THREAD

**Issue by Noah9461** [mexyn/statev_v2_issues#751]
**Character Name**
Noah Draper

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21:40

**Beobachtetes Verhalten**
Man kann sich durch Wände mit Y auf Stuhl setzen.

**Erwartetes Verhalten**
Kein Menü durch die Wand

**Schritte um den Fehler nachvollziehen zu können**
An Wand stellen wo dahinter ein Stuhl steht, danach einfach hinsetzen

**Comment by DonVitoDiangelo** [comment]
Bitte mitteilen, wo genau

**Comment by Noah9461** [comment]
Casa de los hermanos, Yallow Jack Inn. Vorne bei der Kühltruhe

**Comment by DonVitoDiangelo** [comment]
ab nächsten update kein Problem mehr.
