### ISSUE TITLE
Abführen von Steuern via. Überweisung automatisieren als neues Feature

### ISSUE THREAD

**Issue by croveans** [mexyn/statev_v2_issues#753]
**Character Name**
Marty_Taylor

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.12.2020 / 02:55

**Beobachtetes Verhalten**
-
Handelt sich hierbei um eine Verbesserung, um das Abführen von Steuern für Unternehmen an die HK zu vereinfachen. Wenn heute z.B. Finanzierungen, händische Lohnauszahlungen, händischer Ankauf von Grundstoffen etc. durchgeführt werden, fällt aktuell automatisch nur die Transaktionsgebühr von 2% an. Wenn ich z.B. Waren über die Laderampe ankaufe, wird automatisch die Steuer abgeführt und es fallen weiterhin keine Transaktionsgebühren an. Nun gibt es ja immer die Situation, dass Mitarbeiter Waren einlagern und hinterher der Lohn (bzw. der Ankauf der Grundstoff) manuell ausgezahlt wird via Überweisung und im Anschluss dann händisch die Steuer an die Handelskammer. In diesem Fall wird durch die händische Transaktion 2 x die Transaktionsgebühr abgeführt, obwohl eine Überweisung quasi 100% Steuergeld ist.

Ich würde es begrüßen, wenn man in der Überweisung, die Art und Weise der Transaktion z.B. durch ein Dropdown Menü auswählen kann und in diesem Fall für manche Überweisungen (z.B. Lohn) entsprechend die Transaktionsgebühr wegfällt und stattdessen nur der Steuersatz für eine Lohnzahlung fällig wird + automatisch abgeführt wird. Wichtig ist hierbei, dass im Vergleich zur Transaktionsgebühr nicht zusätzlich die Steuer anfällt, sondern das Unternehmen einfach (z.B. Ankauf 100 Eisenerz für 2.1$ --> Überweisung 210$ --> Automatische Abführung der Steuern mit passenden Steuersatz von den 210$ an die HK) den Bruttolohn auswählt und der Mitarbeiter Netto überwiesen kriegt.

Das könnte bei diversen Transaktionen das Leben vereinfachen und die Steuer könnte bei der Überweisung sauber abgeführt werden und die Transaktionsgebühren fallen dann wirklich nur noch bei Überweisungen an, bei denen Geld hin und her geschoben wird. Anbei noch ein Auszug der aktuellen Steuersatzkategorien:

![grafik](https://user-images.githubusercontent.com/40040984/101269326-2b75c200-376e-11eb-8aac-8477a0e8103b.png)

**Erwartetes Verhalten**
-
Einfaches Abführen von Steuern durch Auswahl des Steuersatzes bei Überweisung. Entfall der Doppelbesteuerung, wenn Transaktionen durchgeführt, bei denen eigentlich 100% Steuern bezahlt werden. 

Reguläre Überweisung von 100$: 100$ + 2$ Transaktionsgebühren
Steuerbelastete Überweisung von 100$ z.B. bei Warenankauf: 100$ - 8$ = 92$ an Empfänger, 8$ Steuer automatisch abgeführt. Entfall der Transaktionsgebühren, da steuerbelastete Überweisung.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
siehe Steuersätze oben.

**Comment by KingMarcel** [comment]
Durch die Einheitssteuer nicht mehr nötig.
