### ISSUE TITLE
Unübersichtlichkeit in der Theke

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#754]
Siehe Bild.. ;)

![Screenshot_3](https://user-images.githubusercontent.com/70241137/101285131-dd9ba100-37e3-11eb-8810-16c567b5ea83.png)

**Comment by JulianMa** [comment]
Ist bekannt.
In solchen Fällen wird demnächst immer nur eine Reihe zu sehen sein

**Comment by JulianMa** [comment]
behoben nach update
