### ISSUE TITLE
[Wunsch] persl. Fraktionsfahrzeug in eigene und/oder öfftl. Garage parken

### ISSUE THREAD

**Issue by h3adbang3r** [mexyn/statev_v2_issues#755]
**Charname**
Thorlic Redoran

**Beobachtetes Verhalten**
Dienstwagen des LSMD werden nach Zeit x automatisiert in die "lsmd1garage" eingeparkt 

**Erwartetes Verhalten**
Fraktionsfahrzeuge zu denen man einen (bzw. sogar alle drei) Schlüssel besitzt sollten sich in die eigene Garage, min. aber in eine öffentl. Garage einparken lassen

**Schritte um den Fehler nachvollziehen zu können**
- mit persl. Dienstwagen nach Hause (Chumash) gefahren, 
- gezwungenermaßen vor dem Haus geparkt, 
- nach dem 8 Uhr Restart steht der Wagen in der lsmd1garage

**Optional: Video / Bilder des Fehlers**
![2020_1206-174101](https://user-images.githubusercontent.com/15799077/101286348-45ed8100-37ea-11eb-8ad2-27944262986f.png)

**Comment by DonVitoDiangelo** [comment]
Wird auch so bleiben. Abgelehnt
