### ISSUE TITLE
Import Bug

### ISSUE THREAD

**Issue by StateMellow** [mexyn/statev_v2_issues#756]
**Mellow_Esposito**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Ein leerer Tracker kann auch beglücken
