### ISSUE TITLE
Grafikfehler bei neuer Frisur

### ISSUE THREAD

**Issue by EduardSpargel** [mexyn/statev_v2_issues#757]
Ruediger_Reidenbach

Fehler kann jederzeit beobachtet werden.
**Beobachtetes Verhalten**

Bei einer der neuen Frisuren ist diese nur Vollständig zu sehen wenn der Spieler "Mindestens" MSAA x2 aktiviert hat. 
**Erwartetes Verhalten**

Die Frisur müsste auch mit abgeänderten Grafik Settings vollständig sichtbar sein.
**Schritte um den Fehler nachvollziehen zu können**

Man kann den Fehler nachstellen indem man in den Einstellungen die Kantenglättung MSAA komplett ausschalten. Dann ist die Frisur verbuggt. 
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

Bild der Frisur ohne MSAA
![Screenshot_200](https://user-images.githubusercontent.com/75588094/101293939-587cb000-3814-11eb-8913-d6bb364ae5ba.png)

Bild der Frisur mit MSAA
![Screenshot_199](https://user-images.githubusercontent.com/75588094/101293959-6e8a7080-3814-11eb-987d-3ea91badfb7a.png)

**Comment by DonVitoDiangelo** [comment]
Wird dazu keine Änderung geben. Div. Frisuren sind extern erstellt und haben je nach Detailstufe eben ein "vermindertes" aussehen.
