### ISSUE TITLE
Pegassi Ruffian

### ISSUE THREAD

**Issue by Stiefel911** [mexyn/statev_v2_issues#758]
hi,
Nachdem die Ruffi am 05.12. nun in der DB zurück gesetzt wurde, ist es mir nicht möglich diese zu verändern.
Selbst beim Ausparken aus der öffentlichen Garage sitze ich nicht auf der Maschine sonder stehe weiterhin neben dem Pagen vom Parkservice....und laufe somit zum Moped.. egtl nicht wirklich tragisch
Wenn versucht wird über die Werkstatt an die Ruffian eine Veränderung oder scheinbar auch Reperatur durch zuführen, geht in dieser Werkstatt nichts mehr, und nur durch Abschleppen und powernaping ist die Werkstatt für andere wieder nutzbar.
Sobald aber meine Maschine wieder am Punkt steht und der Terminal bedient wird ist es rum....

So long

**Comment by DonVitoDiangelo** [comment]
Werde ich nochmal testen. Mit nem frischen Bike war soweit alles i.O. / Sollte das aber solche Problem bereisten wird es raus genommen.

**Comment by DonVitoDiangelo** [comment]
bitte mal Kennzeichen mitteilen

**Comment by Stiefel911** [comment]
Kennzeichen ist O5YA16VE

"Sollte das aber solche Problem bereisten wird es raus" <- diese Aussage verstehe ich leider nicht :~

**Comment by DonVitoDiangelo** [comment]
Ok, bitte  parke es nochmal aus und schau, wie es jetzt aussieht.

**Comment by Stiefel911** [comment]
Hi,
das Ausparken und direkt drauf sitzen funktioniert.
In der Werkstatt gab es ein kleines Problem, das ich nach dem ersten Tuning
nicht auf das Bike steigen konnte, dies ging erst über die Fernbedienung
aufschließen und ein anderer musste sich drauf setzten. Erst dann konnte
ich zwar drauf aber kein Motor starten. Dies wurde durch Schlüssel
Weitergabe gelöst.
Nur leider scheint es nur den Streetfighter Scheinwerfer zu geben 😟, oder
es wurde falsch geschaut. Möglich?
Ich finde optisch es schöner mit einem Scheinwerfer und Windschutz.

😉


DonVitoDiangelo <notifications@github.com> schrieb am Mi., 9. Dez. 2020,
07:19:

**Comment by DonVitoDiangelo** [comment]
Es kann sein, das div. Slots nicht gewhitelistet sind, dann steht nichts anderes zur Verfügung. Aber wie ich sehe schient es jetzt zu funktionieren, ja?

**Comment by Stiefel911** [comment]
Ja würde ich so sehen.
Mit der Kleinigkeit kann ich gut umgehen, eben mal Schlüssel übergeben, das
kann  man auch gut im RP verpacken 😁.

Vielen dank 👋

DonVitoDiangelo <notifications@github.com> schrieb am Do., 10. Dez. 2020,
09:08:
