### ISSUE TITLE
Schwarzer Sub Zip Hoodie nicht Herstellbar

### ISSUE THREAD

**Issue by PlayInc89** [mexyn/statev_v2_issues#759]
**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Immer
**Beobachtetes Verhalten**

Nicht im Produktionscomputer vorhanden 
**Erwartetes Verhalten**

Der Männliche Schwarzer Sub Zip Hoodie ist nicht herstellbar den man im Fashion Killa einsehen kann. Vielleicht vergessen worden einzupflegen ? Siehe Bilder
**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![fashionzip](https://user-images.githubusercontent.com/70231715/101296946-a0a4ce00-3826-11eb-8a12-dc6e0e655d2c.png)
![produktion nicht vorhanden](https://user-images.githubusercontent.com/70231715/101296950-a39fbe80-3826-11eb-9ff0-6f1544d66959.png)

**Comment by DrGrizzlY17** [comment]
Er ist schon vorhanden, nur vielleicht falsch benannt oder verdreht? Who knows ist aber zum nächsten Update fixed

**Comment by PlayInc89** [comment]
Merci
