### ISSUE TITLE
Keine Outfits im Klamottenladen Kaufbar

### ISSUE THREAD

**Issue by CatherineGallagher** [mexyn/statev_v2_issues#76]
**Character Name**
Catherine Gallagher
**Zeitpunkt (Datum / Uhrzeit)**
25.08.20 / 19 Uhr

**Beobachtetes Verhalten**
In V1 kann man Outfits bei den Hosen als Seperate Kategorie aufrufen und kaufen, was jetzt nicht mehr der Fall war.
Outfits hab ich nirgendswo zum Kauf oder Anprobe finden können, sind aber im Ladeninventar und auch bepreist.

**Erwartetes Verhalten**
Outfits irgendwo mit einbinden

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Enemyaa** [comment]
https://prnt.sc/ucle3x Die Outfits sollten wie auf dem Liveserver unter den Hosen sein, allerdings sollte das erste was man anprobiert am Marker eine Hose sein und kein Outfit, da das Outfit alles überblendet.

**Comment by r3sist3nt** [comment]
@Enemyaa auf V2 gibt kann man auch "nichts" auswählen, von daher überblendet das Outfit auch nicht die Hosen.

**Comment by r3sist3nt** [comment]
Solved nach Restart
