### ISSUE TITLE
Indianer Beil kann nicht gesehen werden

### ISSUE THREAD

**Issue by DaveFriedmann** [mexyn/statev_v2_issues#761]
Der Axt fehlt ein Icon. Genauso kann man sie nicht sehen wenn sie nicht in der Hand ist.

**Dave_Friedmann**

![20201207043333_1](https://user-images.githubusercontent.com/75597845/101306833-3b60d500-3846-11eb-8c63-db9afd17b013.jpg)
![20201207043328_1](https://user-images.githubusercontent.com/75597845/101306841-3ef45c00-3846-11eb-9aa9-feb3a676dd5e.jpg)
![20201207043347_1](https://user-images.githubusercontent.com/75597845/101306847-4287e300-3846-11eb-874b-3c93d89230c4.jpg)

**Comment by DonVitoDiangelo** [comment]
icon next update fixed, das Sie versteckt sein kann, ist so gewollt
