### ISSUE TITLE
AK Munition

### ISSUE THREAD

**Issue by statevmj** [mexyn/statev_v2_issues#762]
**Character Name**
Mathew_Jones

**Auftrittszeitpunkt (Datum / Uhrzeit)**
07.12.2020 / 9:00 Uhr

**Beobachtetes Verhalten**
Ich wollte das Magazin mit nur 1x Kugel entleeren, damit ich keine Krise kriege, wenn ich es im Hauslager liegen habe. Nachdem ich die Kugel verschossen habe und die Waffe zurück ins Inventar gelegt habe, war die Kugel aber noch da. Das Ganze kann man jedes mal so reproduzieren.

**Erwartetes Verhalten**
Wenn das Magazin leer geschossen ist, sollte es auch wirklich leer sein. 

**Schritte um den Fehler nachvollziehen zu können**
AK-47 in die Hand nehmen und mit nur einem Magazin mit 1x Kugel nachladen und schießen, danach die vermeintlich leere Waffe wieder in das Inventar ziehen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=8IlL8ZG7vKk

**Comment by statevmj** [comment]
Es bleibt wohl immer 1x Kugel übrig auch wenn die Waffe leer geschossen ist. Das Gleiche ist auch bei einem Taurus Magazin mit 3x Kugeln passiert, als ich sie nach dem leer Schießen wieder ins Inventar gelegt habe.

**Comment by RomanSpielberg** [comment]
Siehe [715](https://github.com/mexyn/statev_v2_issues/issues/715)
