### ISSUE TITLE
Fehler im Restaurant La Gino´s mit den Preisen im Tablet.

### ISSUE THREAD

**Issue by PhillippSonnenberg** [mexyn/statev_v2_issues#763]
**Phillipp Sonnenberg**
Phillipp_Sonneberg Fehler im Tablet bei denn Preisen vom Restaurant. Stimmen in der Ladentheke aber nicht im Tablet nach Aktualisierung 

**Auftrittszeitpunkt (01.12 / 18:30)**
Am 1.12 gegen 18:30

**Beobachtetes Verhalten**
Mann kann die preise im Tablet eingeben sie sind nach dem speichern auch in der Ladentheke drin aber leider nicht nach Aktualisierung des Tablets, da werden sie mit 0$ angezeigt in der Theke aber mit dem Richtigen Preis

**Erwartetes Verhalten**
 die Preise sollten im Tablet sowohl in der Theke richtig sein 

**Schritte um den Fehler nachvollziehen zu können**
 Video Material ansehen  

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
 nicht vorhanden

**Optional: Video / Bilder des Fehlers**
 Video auf YT vorhanden https://youtu.be/BI07wGsj78M

**Comment by Asmier** [comment]
Fehler wie bei [https://github.com/mexyn/statev_v2_issues/issues/673](url) +   [https://github.com/mexyn/statev_v2_issues/issues/696](url) + [https://github.com/mexyn/statev_v2_issues/issues/415](url)
