### ISSUE TITLE
StateNET lässt sich im Vollbild öffnen

### ISSUE THREAD

**Issue by RealSocius** [mexyn/statev_v2_issues#764]
Sebastian Schindler
07.12.2020
BUG:
Ingame StateNet im Vollbild lässt sich nicht schließen
Reproduzierbarkeit:
Doppelklick mit dem Mittleren Mausbutton auf einen NavLink Links
Edit: Nach einigen Tests habe ich herausgefunden, dass alle <a></a> Elemente betroffen sind.
Das bedeutet der Browser so wie das Wiki sind auch davon betroffen.
Video:
https://medal.tv/clips/38231990/d1337Et3zn89
P.S.: Man wird dabei aus dem Ingame-Voice geworfen

**Comment by JulianMa** [comment]
da gibt es hier schon einige Issues zu.

**Comment by JulianMa** [comment]
#68
