### ISSUE TITLE
Lade-/Kofferraumvolumen Rumpo und Sandking sind verändert

### ISSUE THREAD

**Issue by Kindderddr** [mexyn/statev_v2_issues#766]
Heinrich Zeiss

Immer

Kofferraumvolumen vom Rumpo beträgt nur noch 250kg,
Kofferraumvolumen vom Sandking beträgt 240kg (beide Versionen) - vorher 210 und 240 - logisch da 4/2 -Sitzer

Rumpo - 300kg
Sandking 210kg bzw 250kg

Auto öffnen, Kofferraum öffnen, in den Kofferraum rein schauen

**Comment by DonVitoDiangelo** [comment]
div. Eigenschaften wurden zu V2 angepasst. Wird auch so bleiben.

**Comment by Kindderddr** [comment]
Dann ist ja die logische Gewichtsverteilung nicht mehr vorhanden und niemand kauft mehr ein Rumpo weil der Kaufgrund 300Kg Ladevolumen nicht mehr vorhanden ist. Genauso bei dem Sandking. Ein 4 Türer hat ja auch logischerweise weniger Ladevolumen als ein 2 Türer. 
Dürfte man da vllt den Hintergrund wissen? Da es jakein logischer Fix ist...

Lg
