### ISSUE TITLE
Antrag für "öffentliche Garage auf Hotelgrundstück"

### ISSUE THREAD

**Issue by SEUKings** [mexyn/statev_v2_issues#767]
Calvin Kings

**Beobachtetes Verhalten**
Das Hotel "RockfordHills_Flat_4" wird als "Bed & Car Hotel" betrieben. Das heißt, dass die Mieter zu Ihrem Zimmer auch die Möglichkeit haben, ein Auto zu bekommen.
Das führt dazu, dass viele Autos immer im freien rum stehen, da die Vinewood Garage doch ein großes Stück weit weg ist.
Zudem muss aufgrund der Entfernung zur Vinewood Garage immer bei Server Restart ein guter Fußmarsch hingelegt werden um sein Auto wieder zu holen.

**Erwartetes Verhalten**
Das Hotel bietet an zwei Stellen eine perfekte Garageneinfahrt. Die Bessere habe ich mal bildlich gestaltet. Da es keine Möglichkeit gibt, den Hotels eine private Garage zum einparken zur Verfügung zu stellen, wäre an dieser Stelle auch eine öffentliche Garage, eine für mich vertretbare Lösung.

**Schritte um den Fehler nachvollziehen zu können**
Hier sind modifizierte Bilder, wie so eine öffentliche Garage eingefügt werden kann. Der grüne Marker soll darstellen, an welchem Punkt das ausgeparkte Fahrzeug spawnt.

**Bild 1** https://pic.statev.de/image/1.GBifz

**Bild 2** https://pic.statev.de/image/2.GBj9D

**Comment by DrGrizzlY17** [comment]
@DonVitoDiangelo bitte guck dir die Bilder an und entscheide dann... bitte :D

**Comment by SEUKings** [comment]
Ihr könnt sagen was ihr wollt, Kreativität ist hier on point, genauso wie meine mehr als perfekten Photoshop Skills 😂😂

**Comment by DonVitoDiangelo** [comment]
Abgelehnt, die nächste Garage ist um die Ecke, Straße runter 500 Meter entfernt.
