### ISSUE TITLE
Gemüse (Salat, Gurken) Animation dauert zu lange

### ISSUE THREAD

**Issue by Asmier** [mexyn/statev_v2_issues#768]
Asmier Umid

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Dauerhaft beim Salat / Gurken sammeln
Unbekannt wegen Tomaten / Kartoffeln

**Beobachtetes Verhalten**
Animation wird noch abgespielt obwohl Fortschrittsbalken verschwunden ist.
Dadurch bringt der Skillvorteil auch nichts.

**Erwartetes Verhalten**
1. Animation + Fortschrittsbalken fangen zusammen an
2. Enden auch zusammen

**Schritte um den Fehler nachvollziehen zu können**
1. Animation + Fortschrittsbalken fangen zusammen an
2. Inventar öffnet sich 
3. Char bleibt weiter in Animation

**Optional: Video / Bilder des Fehlers**
https://prnt.sc/vxquqb   Char am Boden, in Animation.
https://prnt.sc/vxqwqg  Inventar offen, Char immer noch in Animation.

**Comment by PlayInc89** [comment]
Selbe auch bei Ocker !

**Comment by DonVitoDiangelo** [comment]
Das ist korrekt so wie es ist. Die reine Farmzeit (Progressbar) wird hier berechnet.
Die Auslaufanimation, also dieses aufstehen ist immer fest. Das gehört zu diesem Scenario mit dazu.
Aber Ihr spart zu 100% Euro Zeit aufs Farming. Da gibt es keinen Fehler.

**Comment by BlackyGER** [comment]
Ich glaube du hast sie falsch verstanden, Du bleibst in der Farm Animation drin obwohl der Balken durch ist. Sprich man sammelt weiter ohne balken. Der Zeitliche vorteil bringt also nur visuell was aber am balken, technisch bringt es nichts.

**Comment by Asmier** [comment]
[https://www.youtube.com/watch?v=z6Q2xVuBIjM](url)
Aktuell Stufe 1, bei höheren Zeiten geht das Inventar schon auf wenn der Char die Schaufel erst in die Hand nimmt. Innerhalb der Animation.
@DonVitoDiangelo Sicher das es so gewollt ist?
Wenn ja einfach ignorieren.

**Comment by Knippsa** [comment]
Hier muss wirklich was pasieren. Jedem Verpacker und Arbeiter in diesem Bereich wird ein großes Handicap verpasst. Es ist richtig, dass die Progressbar vom SKill profitiert. Es bringt aber gar nichts, wenn du dann nochmal 2,3 Sekunden auf der Stelle trittst und nicht wegkommst. D.h. während auf allen anderen Feldern die Arbeiter real auch z.B. 30% schneller von Fleck zu Fleck kommen, stehen die Schaufler die vollen 100% rum. 

Da hat doch niemand Lust drauf und du kannst auch keinem neu eingereisten das als gute Arbeit verkaufen. Der/die wirk auf kurz oder lang auch sagen, er geht lieber was arbeiten, wo die Skill-Beschleunigung ordentlich funktioniert,.

**Comment by RomanSpielberg** [comment]
Kann man dies eventuell nochmal überdenken, wäre echt super, es ist einfach nervig, wenn man ca 1-2 SEK eingefroren wartet. Die Gesamtzeit muss dabei gar nicht verkürzt werden, aber ein flüssiger Übergang sollte machbar sein. Bitte ggf. auch mal selbst testen.
