### ISSUE TITLE
Antrag: Veränderungen am Gebäude 

### ISSUE THREAD

**Issue by Roxylein** [mexyn/statev_v2_issues#769]
Firmenhash | AkiPillboxHillRew_Hotel_1
-- | --

Wir wollen das Gebäude mehr ins RP einbinden und wären für folgende Änderungen dankbar:

**Erstellen einer öffentlichen Garage**
Wir planen dort Veranstaltungen und es werden sich dort täglich mehrere Leute aufhalten. Deshalb wäre eine öffentliche Garage gut, um dort nicht so Autos dort stehen zu haben und damit auch zu viel Auslastung zu haben. Die anderen Garagen befinden sich zudem alle relativ weit weg.

https://pic.statev.de/i/GEmmu.jpg

**Verlegung des Aufzugs**
Da wir auch die Dachterrasse viel nutzen, wäre es uns ein Anliegen, dass der Aufzug, um eine Tür nach links verschoben wird.
Wir müssten den Eingang ansonsten mit zusätzlichen Gegenständen ein bisschen abgrenzen, was man sich dadurch sparen könnte.

https://pic.statev.de/i/GEr12.jpg

**Fixierung der Sonnenliegen**
Sobald man an denen vorbei geht, verschieben sie sich und liegen gefühlt auch bei jedem anders. Allgemein schwierig das auszuspielen. Wenn die so fest wären wie die Tische und Stühle wäre es praktisch.

https://pic.statev.de/i/GEAT6.jpg

https://pic.statev.de/i/GEYXJ.jpg

**Müllcontainer**
Der Umwelt zuliebe ;)

https://pic.statev.de/i/GE05t.jpg

LG

**Comment by DonVitoDiangelo** [comment]
@DrGrizzlY17 

Erstellen einer öffentlichen Garage:
Bitte checken ob nötig oder 50 meter auch gelaufen werden können

Verlegung des Aufzugs:
Von mir aus

Fixierung der Sonnenliegen:
Nein, diese werden wenn, dann entfernt, dann können dort aber auch keine mehr aufgestellt werden.

Müllcontainer
Nein, auch da werdet Ihr wie andere auch eben schauen wo Ihr euer Müll los werdet. Von mir aus beauftragt im RP jemanden(Müllmann). Klärt das im RP.

**Comment by Roxylein** [comment]
Danke schon mal für die Bearbeitung.

Garage: das ist schon ein ganzes Stück und auch für Bennys und co wäre es sicherlich angenehm dort Autos parken zu können und tatsächlich nur ein paar Meter über die Straße laufen zu müssen.  Zudem gehen wir davon aus, es würden sich dort oft zu viele Fahrzeuge sammeln und rumstehen.  Das nur nochmal als kurzer Zusatz

Aufzug: Danke

Sonnenliegen: Die vorderen drei Liegen sind echt kritisch, weil man da ständig gegen rennt und die kaum umgehen kann. Wenn ihr die wegmachen könntet, dann wäre das schon eine riesen Erleichterung.

https://pic.statev.de/i/GEAT6.jpg

Müllcontainer: Kriegen wir hin

**Comment by DrGrizzlY17** [comment]
Kurze Randnotiz meiner Seits

Teleport wird verschoben eins weiter links wie gewünscht...

aber für welchen Charakter auf dem Server sind die Liegen kaum umgehbar? Selbst Fat Joe aufm Server würde daran vorbei kommen. Man muss halt nicht immer mit Hass sprinten

![image](https://user-images.githubusercontent.com/70150988/101658956-d542a080-3a45-11eb-8824-51f93eb5bd4e.png)

**Comment by Roxylein** [comment]
Ha, ja wenn man es so sieht :P aber wir wollen da nicht sprinten sondern Veranstaltungen machen. Aber können wir gucken. Vielleicht werden die ja wirklich von Allen umgangen.  Wir waren da letztens mit relativ wenigen Leuten und die Dinger sind einfach jedem vor die Füße gefallen. 
Das ist aber wirklich das kleinere Problem am Ende. Müssen wir dann irgendwie umgehen. Das mit der Garage wäre halt eine riesen Erleichterung und danke schon mal für die Versetzung des Aufzugs :p
