### ISSUE TITLE
Visuelle Garage an Haus hinzufügen

### ISSUE THREAD

**Issue by SevenJordan** [mexyn/statev_v2_issues#770]
Seven_Jordan 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jetzt

**Beobachtetes Verhalten**
Eine visuelle Garage bitte ans bereits vorhandene Haus hinzu fügen, so das an dieses Haus 6 oder 7 Garage Plätze vergeben werden können, da die nächste öffentliche Garage ein Stück weg ist und das Haus ein paar aktive Bewohner hat.

**Erwartetes Verhalten**
Bitte visuelle Garage mit garagen Plätzen bei SandyShores59 einfügen

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Statev-Bonsai** [comment]
Da gabs doch schonmal den gleichen Fred... https://github.com/mexyn/statev_v2_issues/issues/707

**Comment by SevenJordan** [comment]
Das ist so richtig, naja fast. Habe nach Garagen Plätzen gefragt, da aber keine "Garage" da war, konnte nichts hinzu gefügt werden. Deswegen frage ich nun auch nach einer visuellen Garage, die würde sogar ans Haus perfekt passen so eine kleine, auch eine große passt ans Haus ran. Ich möchte halt echt eine Garage für uns haben und nicht immer so weit laufen müssen. Genau so wenig möchte ich viele Autos vor dem Haus stehen haben.

**Comment by Statev-Bonsai** [comment]
Warum hast du anfangs nicht ein Haus mit Garage gekauft? ;p

**Comment by DonVitoDiangelo** [comment]
Abgelehnt.
