### ISSUE TITLE
Voice crash + Game freeze

### ISSUE THREAD

**Issue by MissCaliente** [mexyn/statev_v2_issues#771]
**Character Name**
Luna_Caliente
 

**Auftrittszeitpunkt (Datum / Uhrzeit)**
07.12.2020 20-22 Uhr
 

**Beobachtetes Verhalten**
Voice Crash + Game freeze nachdem Funk nicht mehr funktioniert/reagiert
 

**Erwartetes Verhalten**
Sollte nicht von den aufgezählten sachen crashen/freezen
 

**Schritte um den Fehler nachvollziehen zu können**
Funk Animation ist nicht mehr gegeben + man selbst wird nicht gehört. <-- Fehler bekannt ABER, sobald man das Funkgerät aus dem Slot ins Inventar ziehen will, crasht das Voice und das Game freezed komplett. Heißt, es hilft nur noch Alt F4.
 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
@MissCaliente Kannst du das reproduzieren?

**Comment by MissCaliente** [comment]
Sobald man ein Funkkanal kurz ausschaltet und wieder aktivieren will, geht in dem Funk UI nichts mehr und wenn man dann das Funkgerät aus dem Inventar Slot nimmt, crashed alles.
