### ISSUE TITLE
Weitere Animationen (Rauchen)

### ISSUE THREAD

**Issue by MissCaliente** [mexyn/statev_v2_issues#772]
**Character Name**
Luna_Caliente

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Beobachtetes Verhalten**
Beim rauchen am Aschenbecher/tonne gibt es leider nur eine seeeehr feminine Animation

**Erwartetes Verhalten**
Weitere Auswahl an Rauchanimationen

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Rauchen ist nur ein scenario das auch genutzt wird. Mehr gibt es nicht, sry.
