### ISSUE TITLE
Firmen Punkte verlegen (Eingang+Lager)

### ISSUE THREAD

**Issue by Patrick-Snooze** [mexyn/statev_v2_issues#773]
**Character Name**
Patrick_Snooze

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Schön länger

**Beobachtetes Verhalten**
Jetzt mit einem Pounder/Phantom zum Verladepunkt zu kommen ist einfach nur shit.
Deswegen wäre es super wenn man den Eingangs Marker und Lagerpunkt auf die Linke Seite des Gebäude verlegen könnte.

Firmenname: Snooze Lab. - Popular Street 743 
Firmenhash | lamessa7

**Erwartetes Verhalten**
Siehe Screenshot

**Schritte um den Fehler nachvollziehen zu können**
---

**Optional: Video / Bilder des Fehlers**
![snooze_lab](https://user-images.githubusercontent.com/74994851/101431375-0d8f9500-3907-11eb-883d-9ddacf939eb2.PNG)

Danke im vorraus und gr33tz
P. Snooze

**Comment by DrGrizzlY17** [comment]
@Patrick-Snooze den Eingangspunkt werde ich da nicht nicht hinter machen. Da is ne Leiter :D den Entladepunkt kann ich dir trotzdem dahin legen, müsst ihr halt nur nen stück laufen, wenn das Ok für euch ist

**Comment by Patrick-Snooze** [comment]
@DrGrizzlY17 nee das lass mal, ein wenig muss man sein Fahrzeug schon im Auge haben, da man ja jetzt immer den Kofferraum offen haben muss beim entleeren.

Dann vielleicht hier hier das Tor als Eingang? wäre das vielleicht möglich?
![labor_tuer](https://user-images.githubusercontent.com/74994851/102013128-71beb880-3d4e-11eb-87b2-3de02146c10b.PNG)

**Comment by DrGrizzlY17** [comment]
Nein

**Comment by Patrick-Snooze** [comment]
Dann shice drauf!

**Comment by DrGrizzlY17** [comment]
Alles klar
