### ISSUE TITLE
Bankkonto Löschen

### ISSUE THREAD

**Issue by Tobse1904** [mexyn/statev_v2_issues#774]
Harry Buktu

**Auftrittszeitpunkt (Datum / Uhrzeit)**
08.12.2020 / 06:12

**Beobachtetes Verhalten**
Bankkonto erstellt -> einer Firma zugewiesen -> Nicht mehr Löschbar

**Erwartetes Verhalten**
Konto erstellen -> Konto Löschen können

**Schritte um den Fehler nachvollziehen zu können**
Konto Erstellen -> Konto versuchen zu Löschen

Ist es so gewollt das man das Konto nicht mehr löschen kann ? ( Es handelt sich hier um ein 2. Konto , kein Hauptkonto )

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920 * 1080

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
korrekt.

**Comment by Tobse1904** [comment]
Und wie kann man das jetzt löschen lassen ? Handelskammer ? Support ? weil gibt ja keine bespielbare Bank :P
