### ISSUE TITLE
Carbon RS - Motorschaden ohne Grund (mehrmals)

### ISSUE THREAD

**Issue by Deloy59** [mexyn/statev_v2_issues#775]
**John_Pearce**

**Zuletzt gestern den 07.12.2020 ca. 21Uhr (Datum / Uhrzeit)**

**Carbon RS Motor nimmt mehrfach Schaden ohne ersichtlichen & logischen Grund:
Beispiel 1: Motorrad frisch repariert, kein einzigen Kratzer oder sonstiges am Motorrad verursacht, man geht in ein Restaurant, kommt wieder raus, Motorkontrollleuchte "Gelb" und der Motor qualmt - ist mittlerweile 2x an einem Tag vorgefallen.

Beispiel 2: Motorrad wurde frisch repariert nach Problemen aus "Beispiel 1" - ohne jeglichen Unfall bin ich nach der Werkstatt zur öffentlichen Garage gefahren und entschied das Motorrad erstmal einzuparken - nach gut 1 1/2 Tagen, wollte ich das frisch reparierte Motorrad ausparken -> Motor qualmt, Kontrolleuchte "Gelb" - Bin Besitzer aller 3 Schlüssel - dementsprechend liegt ein Fremdverschulden nicht vor.**

**Meine Gedanken dazu - möglicherweise nimmt der Motor Schaden beim z.B ein und ausparken -> fällt aus kleiner Distanz zum Boden. Generell ist mir aufgefallen das dass Motorrad sehr schnell kaputt geht, kriegt der Motor evtl Schaden wenn man das Rad hochzieht und es danach wieder auf den Boden fällt? Liegt es evtl am Schnee, das es als Supersportler Motorrad nicht dafür ausgelegt ist? Lichter & Spiegel platzen wenn man das Motorrad auch nur leich berührt -> evtl ein Schaden der dauerhaft gesynced wird und das den Motor schadet? Bin absolut überfragt und hoffe Ihr könnt helfen! **

**Siehe "Meine Gedanken" ^**

**Motorrad reparieren -> 15 Min Unfallfrei hin und her fahren -> Restaurant betreten & verlassen.**

**Bis jetzt noch nicht vorhanden, werde ab nun an sammeln.**

**Comment by DonVitoDiangelo** [comment]
Punkt 1: Es ist Winter, mach dir mal darüber Gedanken.
Punkt 2: Punkt 1
Punkt 3: Sind Motorräder aktuell sehr anfällig. Schon kleine Rempler etc. verursachen aktuell Schaden. Hier werden wir uns wenn, erst später etwas zu einfallen lassen.
