### ISSUE TITLE
Werkstatt Finanzen trennen

### ISSUE THREAD

**Issue by BlackyGER** [mexyn/statev_v2_issues#776]
Heyo, 

mir ist grad aufgefallen das Lackieren nicht mehr als dass in den Finzanzen einer Werkstatt deklariert ist. 
Durch diese änderung ist es nicht mehr möglich nachzuvollziehen ob nun lackiert oder getunt wurde. 
Bitte um wieder änderung. 

Siehe Screenshots, bitte auf Datum achten :)

1. screen ist von vor V2 
2. ist nach V2 .. am 06.12.20 um 23:33 war eine lackierung 

https://i.imgur.com/BkJ9AuC.jpg
https://i.imgur.com/SCpBFrw.jpg

**Comment by its4l3x** [comment]
Hi,

habe jetzt mal alle Sorten unterteilt ;)

D.h. bei den Transaktionen steht beim Schlosswechsel "Schlosswechsel" etc...

**Comment by BlackyGER** [comment]
Ehrenmann
