### ISSUE TITLE
Durch 2x Crashes zum Casinodach

### ISSUE THREAD

**Issue by m4xellde** [mexyn/statev_v2_issues#777]
**Character Name**
Thomas_Stone

**Auftrittszeitpunkt (Datum / Uhrzeit)**
08.12.2020 gegen 18:40 Uhr

**Beobachtetes Verhalten**
Ich hatte einen plötzlichen Crash. Bei einem Spielneustart hatte ich einen erneuten direkten Crash. Danach hatte ich wieder connectet und war plötzlich auf dem Casinodach

**Erwartetes Verhalten**
Wieder dort zu spawnen wo man den Crash hatte.

**Schritte um den Fehler nachvollziehen zu können**
Schwer zu sagen. Ich hatte 2 Crashes und die kann man schlecht von selbst verursachen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![mx2aoy4r](https://user-images.githubusercontent.com/75097512/101522156-2475cc00-3987-11eb-9834-a481b6dd995f.jpg)

**Comment by h3adbang3r** [comment]
Wenn Du beim Login einen Crash hast stehst Du in einer anderen Dimension. Die Konsequenz daraus ist, das Du bei einem erneutem Login in der letzten bekannten Dimension "spawnst".
Dir bleibt nur der Support und ein Port in die Dimension 0.
