### ISSUE TITLE
Schranken Mautstelle

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#778]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
08.12.2020 - 19:00

**Beobachtetes Verhalten**
Wenn wir die Schranke am Central Highway schließen. und ein Fahrzeug sich der Schranke nähert. Geht diese Schranke auf.
Zudem werden die Schranken dadurch ständig kaputt gefahren wodurch wir mit Leitkegeln die Schranke ersetzen müssen.
Wäre es möglich die Schranken wieder wie früher aufzubauen?
Ich denke es bezieht sich auf jede Schranke an allen Mautstellen.

**Erwartetes Verhalten**
Schranken öffnen sich nicht von selbst, wenn ein Fahrzeug sich nähert.

**Schritte um den Fehler nachvollziehen zu können**
Schranke als SAPD  Officer Schließen.
Mit einem Fahrzeug der Schranke näher kommen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Hi,

Das mit dem nähern ist Resultat unseres Object-Streamers, welche die Schranken an die Spieler in dem Moment synced.

Bzgl. der Sache mit dem das die Schranken zerfahren werden. Könnte man anschauen, ja.

**Comment by its4l3x** [comment]
https://pic.its4l3x.de/share/LLII4L3hjS.gif

Wenn herauskommt, es wird abused => Folgen werden passieren, nichts gutes passieren wird mein junger Padwan

https://pic.its4l3x.de/share/Star-Wars-Yoda.jpg
