### ISSUE TITLE
Ticketautomaten an den Mautkontrollen

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#779]
**Character Name**
Max_Broady

**Beobachtetes Verhalten**
Wäre es möglich an jede Mautstelle einen Ticketautomaten zu bekommen?
Am liebsten den Automaten welcher auch am MRPD steht.
Alternativ auch Tickets im Schrankenhäuschen bezahlbar machen.
Es ist immer ein recht großer Auffwand Personen vom Highway zum Ticketautomaten zu bringen und  anschließend wieder zum Highway. Da Ihre Fahrzeuge dann dort rumstehen und unsere Einheiten welche an der Mautstelle benötigt werden Taxi spielen müssen.

**Comment by TheBroady** [comment]
Mir kommt gerade in den Sinn, das man Tickets nur bar bezahlen kann und demnach auch win Bankautomat benötigt wird.
Finde das beides etwas zu viel an jeder Mautkontrolle. Außer Tickets wären via Überweisung / Bankeinzug bezahlbar.

**Comment by DonVitoDiangelo** [comment]
Die Ticket Dinger sind eben dazu da, auch bezahlen zu können "wann man will".  Wenn jemand zu viel Dreck am stecken hat, müsste Ihr das eben ausspielen.
