### ISSUE TITLE
Kartenmarkierungen fehlen: Juweliere Cartier + Diamond Unicorn + Juwelier Würfelpark

### ISSUE THREAD

**Issue by zarazandra** [mexyn/statev_v2_issues#78]
**Character Name**
Shiva_Connelly
**Zeitpunkt (Datum / Uhrzeit)**
26.8.20, 16:00

**Beobachtetes Verhalten**
Auf der Suche nach Juwelieren ist aufgefallen, dass mindestens zwei Juweliere nicht auf der Karte verzeichnet sind. Ich habe nicht alle geprüft, aber definitiv fehlen die Kartenmarkierungen für das Cartier neben H&M sowie der Diamond Unicorn Jeweller (genauer Name gerade nicht bekannt) Beide Läden sind voll funktionsfähig, können betreten und genutzt werden.

Die KArtenmarkierung des Juweliers am Würfelpark ist ebenfalls nicht zu sehen, dort war ich aber nicht nachsehen, ob der Laden betret- und nutzbar ist. 

**Erwartetes Verhalten**
Mapmarker sollte auf der Karte sichtbar sein

**Schritte um den Fehler nachvollziehen zu können**
Karte öffnen (P)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![unknown](https://user-images.githubusercontent.com/70195103/91317855-d4e60880-e7ba-11ea-8146-0115fb57a749.png)
![unknown](https://user-images.githubusercontent.com/70195103/91317867-dadbe980-e7ba-11ea-805e-e46e2962890a.png)
![unknown](https://user-images.githubusercontent.com/70195103/91317883-e0393400-e7ba-11ea-984a-4e9e5eef1793.png)
![unknown](https://user-images.githubusercontent.com/70195103/91317968-fcd56c00-e7ba-11ea-80c7-9d8943b3666a.png)

**Comment by eiksch** [comment]
Fixed beim nächsten Update.
