### ISSUE TITLE
Dublizieren von Magazinen

### ISSUE THREAD

**Issue by SiberiusV** [mexyn/statev_v2_issues#780]
Siberius_Vaako

Mit dem Charakter Siberius_Vaako.

Circa 19:20Uhr, 08.12.2020

Ich habe mehrere Schneebälle aufgehoben, 5 um exakt zu sein, habe dann mit der linken Maustaste auf einen Spieler gezielt, mich gerollt (zur Seite, nach vorne und auch nach hinten) und den Schneeball geworfen. Nach circa 3 geworfenen Schneebällen kam ich in eine Stuckanimation in welcher ich mit einer nicht sichtbaren Pistole anfange zu zielen ohne es kontrollieren zu können wann ich aufhören möchte zu zielen. In dieser Animation scheint man sich in den Augen anderer Spieler um einige Meter von A nach B zu teleportieren ohne, dass der eigene Charakter, welcher sich in der dieser Stuckanimation befindet, sich bewegt. Aus dieser Animation kann man sich für gewöhnlich nicht befreien außer durch das Ziehen einer Waffe oder einem Relog. Ich entschied mich eine Waffe zu ziehen, es war die Taurus mit 6 Magazinen welche ich ausgerüstet hatte. Der Animation wurde unterbrochen und meine Magazine im selben Moment auf 12 ausgerüstete Magazine dubliziert. Ich loggte aus um den Fehler gegen 19:45 Uhr zu melden. Zum Test der Reproduzierbarkeit loggte ich mich erneut ein und probierte erneut in die Stuckanimation zu glitchen. Allerdings erfolglos. Um dem Support zu zeigen wie viele Magazine ich in der Tasche habe, legte in die ausgerüstete Taurus mit 144 Schuss (Ursprünglich 72 Schuss) zurück in das Inventar. Mir fiel auf, dass die Magazine wieder bei 6 Stk anstatt bei 12 Stk waren. Ich rüstete die Waffe erneut aus und sah, dass es wieder korrekte 72 Schuss anstatt die falschen 144 waren. 
Mit anderen Waffen wurde dies noch nicht getestet, zumindest nicht von meiner Seite aus. 

Man zielt normalerweise mit dem Schneeball, wirft diesen und wird automatisch für kurze Zeit aus der Zielen-Animation geworfen um erneut zielen zu können da man einen neuen Schneeball in der Hand hat. 

- Mehrere Schneebälle durch häufiges "J" drücken in die Hand nehmen (Anzahl wie viele es sein MÜSSEN ist unbekannt)
- Auf eine oder mehrere Personen zielen, dabei rollen und den Schneeball werfen (Anzahl der Gruppengröße unbekannt welche es sein MUSS)
- Häufig und schnell wiederholen

(So zumindest wie ich in diese Animation geraten bin. Angaben können variieren.)

![alt_V Multiplayer 08 12 2020 20_25_54](https://user-images.githubusercontent.com/75697656/101536138-e33ae780-3999-11eb-81b9-e1cb2325436e.png)

Jo_Harris hat als GM den Fall aufgenommen. 

EDIT: Die Magazine können sich auch random einfach dublizieren. Beim entholstern und wegstecken der Waffe ins Inventar sind die Magazine wieder reduziert auf 6 Stk.

**Comment by DonVitoDiangelo** [comment]
Wird bei Abuse hart bestraft. Logs werden am Ende des Schneeball Events ausgewertet und entsprechend sanktioniert.
Ein Fix, wird Aufgrund der aktuell anfallende Arbeit für wichtigere Features und Fixes nicht erwartet.
