### ISSUE TITLE
Platzieren "künstliche Doppel-Palme"

### ISSUE THREAD

**Issue by stormbreaker22** [mexyn/statev_v2_issues#781]
**Character Name**
Kilian_Smith

**Auftrittszeitpunkt (Datum / Uhrzeit)**
09.12.2020 00:24

**Beobachtetes Verhalten**
Pflanze hängt ein guten Meter über dem Boden nach dem platzieren

**Erwartetes Verhalten**
Pflanze steht auf dem Boden

**Schritte um den Fehler nachvollziehen zu können**
Platzieren von Künstliche Doppel-Palme

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![GTA5 2020-12-09 00-21-03](https://user-images.githubusercontent.com/61292701/101553497-04f59800-39b5-11eb-97ae-0af11691713a.png)

**Comment by DonVitoDiangelo** [comment]
Das ist halt leider so, werden wir nicht weiter beeinflussen. Das Objekt hat da unten schon eine Hitbox, die dann mit dem Boden kollidiert und daher steht Sie so weit "oben"
