### ISSUE TITLE
Garagenpunkt nicht vorhanden -Anfrage

### ISSUE THREAD

**Issue by PhantomSeventyEight** [mexyn/statev_v2_issues#783]
Hallo Anbei einige Bilder für die Anfrage für einen  Garagenpunkt bei meinem Haus in der West Mirror Drive 33  (house_MirrorPark_32)

Das Haus Hat ein Großes Vordach 

Einfahrt
https://pic.statev.de/image/garage1.GqX1k
https://pic.statev.de/image/garage11.GqhQD

Adresse  und Garagen Infos Vorhanden
https://pic.statev.de/image/garage2.Gq8ew

Nachbar Haus mit Garage als Beispiel
https://pic.statev.de/image/garagenachbar.GqosY

Danke schon Jetzt für die Bemühungen.

Mfg Mcgraham

**Comment by DonVitoDiangelo** [comment]
@DrGrizzlY17  kannst du machen :)
