### ISSUE TITLE
Geldautomat Auszahlung

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#784]
**Character Name**
Max_Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
09.12.2020 - 10 Uhr

**Beobachtetes Verhalten**
Beim Auszahlen von Geld, muss man mehrfach den "Bestätigen" Button drücken, bevor ausgezahlt wird.

**Erwartetes Verhalten**
Einmal drücken dann sollte die Auszahlung folgen.

**Schritte um den Fehler nachvollziehen zu können**
man gehe zum Bankautomaten und zahlt geld aus.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by jonesXYZ** [comment]
Kann ich so bestätigen.

**Comment by its4l3x** [comment]
Hallo Jungs, dass ist kein Bug. Da ist seit neusten ein kleiner Cooldown von 4,5 Sekunden drauf.

Daher invalid und closed

**Comment by jonesXYZ** [comment]
😥
