### ISSUE TITLE
Garagen Bug am Haus

### ISSUE THREAD

**Issue by StateV2Marie** [mexyn/statev_v2_issues#785]
Als mein Burito nach einen neu start eingeparkt wurde landete er in   Procopio Drive 4  die Garage is aber leider nich groß genug und der burito fing gleich feuer und brannte musste ihn dann einparken und durch den supports hand wieder in die öffentliche porten lassen da man ihn bei der Haus Garage nich raus bekommt hoffe ihr könnt da auch ohne bild was machen weil musste schnell handeln sonst wäre ich leider verbrannt.

mfg Marie Pech

**Comment by StateV2Marie** [comment]
Mein Mixer hängt da auch noch grad fest könntet ihr den in die öffentliche von Paleto bringen bitte?

**Comment by DrGrizzlY17** [comment]
> Mein Mixer hängt da auch noch grad fest könntet ihr den in die öffentliche von Paleto bringen bitte?

Support gehen, ich guck mir das Haus an und versetze notfalls den Punkt. Ansonsten demnächst drauf achten die Fahrzeug direkt einzuparken wenn sie nicht mehr gebraucht werden.
