### ISSUE TITLE
Police Mustang wird in verschiedenen Folierungen ausgeparkt

### ISSUE THREAD

**Issue by SEUKings** [mexyn/statev_v2_issues#786]
Calvin KIngs

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer

**Beobachtetes Verhalten**
Beim ausparken des Police Mustang SEU 905 wird beim ausparken immer eine andere Folierung ausgeparkt.
zum Beispiel. Police Schriftzug, Unmarked, MD Folierung, Military Folierung, 

**Erwartetes Verhalten**
Eigentlich sollte nur eine Folierung erscheinen (Sheriff)

**Schritte um den Fehler nachvollziehen zu können**
Mehrmals den gleichen Mustang ausgeparkt

**Optional: Video / Bilder des Fehlers**
https://www.youtube.com/watch?v=QIM3V5h1-yk

**Comment by jonesXYZ** [comment]
#735
