### ISSUE TITLE
Giro Konto nicht löschbar

### ISSUE THREAD

**Issue by SandyFolk** [mexyn/statev_v2_issues#787]
Sandy_Folk
**Character Name**
Steve_Walker

**Auftrittszeitpunkt (Datum / Uhrzeit)**
09.10.2020 17:17

**Beobachtetes Verhalten**
Steve_Walker wollte sein eines Konto löschen und stellte fest das diese Funktion nicht mehr vorhanden ist. Als wir zur Bank fuhren um zu gucken, ob man dies nun eventuell von da ausmachen muss, ist nur dabei raus gekommen das ich nun ein weiteres Konto besitze, was ich ebenfalls nicht wieder löschen kann

**Erwartetes Verhalten**Funktion zum löschen des Kontos

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by MarcelMuerto** [comment]
@SandyFolk ist noch beabsichtigt.
@eiksch
