### ISSUE TITLE
Sitz Bänke

### ISSUE THREAD

**Issue by StateV2Marie** [mexyn/statev_v2_issues#788]
Hätte eine Frage die sitz bänke sind cool kann man machen das man sich drauf sitzen kann????  [https://pic.statev.de/image/img-20201209-150736.G1GFk](url)   wäre in Paleto an der Firma Weberei Summer - Great Ocean Highway 42

**Comment by DonVitoDiangelo** [comment]
Leider kann man mit diesen Bänken, wenn Sie freistehend sind, nicht interagieren. Das geht nur mit den selbst platzierten.
Vllt. stellst du deine eigenen dann direkt da mit rein. Das Sie sozusagen überlappen.
