### ISSUE TITLE
Pöller enfernen is das möglich???

### ISSUE THREAD

**Issue by StateV2Marie** [mexyn/statev_v2_issues#789]
Also es ginge um die 3 bilder [https://pic.statev.de/image/img-20201209-150558.G1VMt](url) [https://pic.statev.de/image/img-20201209-150609.G1AIn](url)  [https://pic.statev.de/image/img-20201209-150805.G1YEw](url)  rund um  Gießerei Pech - Paleto Blvd. 36  und Weberei Summer - Great Ocean Highway 42  stehen die krummen Pöller an der Gießerei komm ich kaum mit lkw zwischen wegen der strohm kiste die da vorher auch nich standen. drum wäre es cool wenn ihr so lieb sein würdet sie zu entfernen lieben dank im vorraus 

mfg : Marie Pech

**Comment by DonVitoDiangelo** [comment]
abgelehnt
