### ISSUE TITLE
Repkits nach fehlgeschlagener Reparatur

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#79]
**Character Name**
Paul Schmutz

**Zeitpunkt (Datum / Uhrzeit)**
26.08.2020 / 16:45

**Beobachtetes Verhalten**
Wenn man ein Repkit, welches sich im Rucksack befindet, benutzt an einen nicht genug zerstörten Fahrzeug, schiebt es das Repkit ins Inventar. Das hat kein Limit. D.h. man hat mehr als 15 kg im Inv. 

**Erwartetes Verhalten**
man sollte max 5. Repkits in Inv bekommen (wenn es leer ist)

**Schritte um den Fehler nachvollziehen zu können**
**Optional: Video / Bilder des Fehlers**
https://gyazo.com/9e7353a198bd18b09e8d36f7307c7a5f

**Comment by eiksch** [comment]
Fixed beim nächsten Update
