### ISSUE TITLE
Haus Kauf, geht aber wegen Miete nicht 

### ISSUE THREAD

**Issue by Schnarch** [mexyn/statev_v2_issues#790]
Thomas_Schnarch

**09.12.20 19:00**

**Beobachtetes Verhalten**
Wollte ein Haus am Schalter kaufen, der Preis ist auch ausgeschrieben. Kann es aber seit Wochen nicht kaufen, weil ein Mieter drin ist. Dabei kann es ja vermietet bleiben. Möchte nur den Trailer haben.

**Erwartetes Verhalten**
Wenn ich etwas am Schild kaufen kann und das Geld habe, sollte es auch kaufbar sein.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![20201209_022211](https://user-images.githubusercontent.com/75751082/101670251-3886ff80-3a53-11eb-878d-1b9568051142.jpg)
![20201209_022211](https://user-images.githubusercontent.com/75751082/101670278-3de44a00-3a53-11eb-8d92-a322ccbdb59a.jpg)

**Comment by its4l3x** [comment]
War das Haus von der HK zurückgesetzt worden?

**Comment by Schnarch** [comment]
Nicht so richtig. Jetzt kann man es gar nicht mehr erwerben. Das Haus stammt doch aber zum VK...

**Comment by Schnarch** [comment]
?? Grüße

**Comment by its4l3x** [comment]
Sorry. Gerade ist bei uns allen Land unter. Wie meinst du nicht so richtig?

**Comment by Schnarch** [comment]
Jetzt kann man das Haus für diesen Betrag gar nicht mehr kaufen. 
Vorher war es nur ein Fehler das es nicht ging und zum VK stand, jetzt habe ich gar nicht mehr die Möglichkeit...

**Comment by its4l3x** [comment]
Dann wurde es vllt. durch die HK resetet. Wie die Meldung sagte, war da ein Mieter drinnen. Wir als Server können und wollen Aktiv da nicht eingreifen. Das sollte alles im RP geregelt werden.


Wie erwähnt, die Meldung kommt mit Absicht, da sich da noch ein Mieter drinnen befindet.

**Comment by its4l3x** [comment]
Ansonsten bitte IG mit der HK klären (wenn möglich). Schließe das Issue wieder.
