### ISSUE TITLE
Fehlende Bilder für Items im StateNet

### ISSUE THREAD

**Issue by RomanSpielberg** [mexyn/statev_v2_issues#793]
Roman_Spielberg

10.12.2020 11:43Uhr

Für die folgenden neuen Items fehlt noch das Bild im StateNet:
Nordwälder Schinken Verpackt
Gordon Bleu

Ein Bild anzeigen in der Lagerliste.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Done. Bilder aktualisiert.
