### ISSUE TITLE
Private sowie Öffentliche Garage (Omerta Villa)

### ISSUE THREAD

**Issue by EddiRos** [mexyn/statev_v2_issues#795]
**Character Name**
Eddi Rossmeisl

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Beobachtetes Verhalten**
Die Fahrzeuge werden sehr weit weg Geparkt (Richman). Da keine andere Garage in der Nähe.

**Erwartetes Verhalten**
Private Garage für die Villa (max. Anzahl). Parkplätze auf dem Grundstück vorhanden.

Einen Öffentlichen Parkplatz außerhalb in der Nähe. 

**Optional: Video / Bilder des Fehlers**

**BESITZER**
![271590_20201130194526_1](https://user-images.githubusercontent.com/75706231/101814472-8157ba80-3b1e-11eb-8425-9f316c7f45e2.png)

**Vorschlag - Privater Parkplatz/Garage**
![Inked271590_20201130194424_1_LI](https://user-images.githubusercontent.com/75706231/101814448-77ce5280-3b1e-11eb-89a4-3f7d97222953.jpg)

**Vorschlag - Öffentlicher Parkplatz**
![271590_20201130194352_1](https://user-images.githubusercontent.com/75706231/101814641-b6fca380-3b1e-11eb-94fa-7b2ba36d1b6d.png)

**Karte/Map**
![271590_20201210202217_1](https://user-images.githubusercontent.com/75706231/101819596-c29f9880-3b25-11eb-9b7e-027333897bb4.png)

**Comment by DrGrizzlY17** [comment]
Hausgarage:
Keine optische Garage vorhanden

Öffentliche Garage:
Kein passendes Gelände in der nähe

**Comment by EddiRos** [comment]
Hallo DrGrizzlY17,

wie schaut es mit diesem Platz aus? Schaut aus wie ein Carport. 

![1](https://user-images.githubusercontent.com/75706231/102261654-44226c80-3f12-11eb-899b-32315007ad77.png)

![2](https://user-images.githubusercontent.com/75706231/102261673-497fb700-3f12-11eb-9b89-4439e5de0204.png)
