### ISSUE TITLE
[StateV] neue Firma, kann niemanden als Mitarbeiter einladen

### ISSUE THREAD

**Issue by SeanwiedereinBug** [mexyn/statev_v2_issues#796]
**Character Name**
Sean_Bishop / Jacob_Walker (mit AK auf der Stirn) / John_Claire

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer nach einer Einladung in die Firma 
Firmenhash: Movie Do Nuts  (ja das ist er wirklich. Der HK-Mensch wollte es erst auch nicht glauben) 

**Beobachtetes Verhalten**
keine neuen Mitarbeiter :/

**Erwartetes Verhalten**
neue Mitarbeiter

**Schritte um den Fehler nachvollziehen zu können**
Spieler in Firma einladen -> unvollständiger Link

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
-
**Optional: Video / Bilder des Fehlers**
https://prnt.sc/vyx0ix

**Comment by eiksch** [comment]
Notiz: @MarcelMuerto der Hash muss URL-encoded werden, da er Leerzeichen enthält.

**Comment by MarcelMuerto** [comment]
@SeanwiedereinBug 
Das Fehlverhalten sollte beim nächsten Update nicht mehr auftreten.
