### ISSUE TITLE
Hotel Werbung schalten geht nicht + Burrito bauen falsches Rezept?

### ISSUE THREAD

**Issue by CCastles22** [mexyn/statev_v2_issues#797]
Hi , kann mit meinem Hotel keine Werbung schalten Hash: "JunDelPerroRew_Flat_4_4_4_4" obwohl Geld am Konto ist Name: "⚜️Royal Estate⚜️" VBAN: 245781  
Fehlermeldung: Kein Bank-Konto der Fabrik gefunden , du kannst diese Werbung nicht veröffentlichen , die Fabrik verfügt über kein Bank-konto

Das Burrito Rezept ist anscheinend auch buggy hab alle Zutaten incl Motor in der Maschine bzw alles grün aber bei dem 159PS Burrito zeigt er mir trotzdem 0 an (hab auch mit nem 2t stärksten Motor ausprobiert da gehts auch nicht! + noch ausprobiert alle Zutaten genau und nichts anderes in der Maschine  Firmenhash: "pfJunRockfordHillsRew_92"

VG

**Comment by DrGrizzlY17** [comment]
1. Konten
@CCastles22 reine Sicherheitsfrage? Sind mehrere Konten verfügbar bei dem Haus?
Habe aber notfalls die andere mögliche Ursache

2. Burrito
Ist den von den Materialien auch alles in der richtigen Masse vorhanden? Nur weil es grün angezeigt wird, heißt es nicht das die komplette benötigte Menge vorhanden ist

**Comment by CCastles22** [comment]
nein nur 1 Konto beim Hotel!

![20201210235945_1](https://user-images.githubusercontent.com/75815218/101844865-ad3e6480-3b4d-11eb-9a4a-95ca83fe1b43.jpg)

**Comment by epichalt** [comment]
Wenn ich mich hier mal einmischen darf, auf dem Screen sieht man einfach nur einen Teil der benötigten Materialien. Ist keinesfalls ein Bug.

**Comment by CCastles22** [comment]
? das ist ja das Rezept wie soll ich das verstehen gehören noch mehr Sachen ins Rezept?

**Comment by epichalt** [comment]
Wenn du mal ein bisschen genauer schaust, man kann scrollen. Und ich hoffe du kochst den Burrito nicht ^^

**Comment by tastydev** [comment]
Bitte nochmal probieren und Rückmeldung geben

**Comment by DrGrizzlY17** [comment]
@CCastles22 als du Werbung schalten wolltest, warst du dort online oder hast es nur über den Webbrowser probiert. Für Werbung schalten muss dein Charakter immer auf dem Server online sein

**Comment by DrGrizzlY17** [comment]
@CCastles22 was @epichalt meint ist, das nicht alle benötigten ressourcen in einem angezeigt werden. Du kannst innerhalb der Produktion noch runterscrollen 

![Inked101844865-ad3e6480-3b4d-11eb-9a4a-95ca83fe1b43_LI](https://user-images.githubusercontent.com/70150988/101876512-c61a3a80-3b8c-11eb-8fc1-2a8da4234c5e.jpg)

**Comment by CCastles22** [comment]
Ja war beim Werbung schalten Online die 3 Fehlermeldungen von meinem Eingangspost hats mir ja im Spiel angezeigt

**Comment by CCastles22** [comment]
und mit dem scrollen danke für die Aufklärung!

**Comment by DrGrizzlY17** [comment]
Ok dann probiere es heute noch einmal und gib Feedback.

Thema Burrito
NoBug :D

**Comment by CCastles22** [comment]
naja Burrito war natürlich mein Fail ja ^^
Wegen Hotel nochmal probieren?

**Comment by CCastles22** [comment]
Werbung funktioniert wieder danke!
