### ISSUE TITLE
Viele Klamotten nicht Produzierbar oder Doppelt

### ISSUE THREAD

**Issue by jonesXYZ** [mexyn/statev_v2_issues#798]
**Character Name**
Maximilian Jones

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Beobachtetes Verhalten**
Klamotten lassen sich nicht Produzieren - Referenz zu  #737 
Oder existieren Doppelt

**Erwartetes Verhalten**
Produktion sollte Funktionieren und nicht doppelt sein.

**Schritte um den Fehler nachvollziehen zu können**
Sind oben zu entnehmen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/i/GSikc.jpg

**Comment by Enemyaa** [comment]
@jonesXYZ Du schreibst, dass "viele" Klamotten nicht produzierbar sind oder ein doppelten Namen haben. Gibts denn da jetzt noch mehr? Weil auf dem Screenshot scheint es sich ja nur um eine Krawatte zu handeln mit gleichen Namen - herstellbar sind alle.
