### ISSUE TITLE
Büro: Stühle nicht funktionsfähig

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#800]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
11.12.2020 14:10

**Beobachtetes Verhalten**
Man kann sich auf die im Bild gezeigte Stühle nicht mehr setzen.

**Erwartetes Verhalten**
Man sollte sich auf die Stühle setzen können

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/Gazcy

**Comment by DrGrizzlY17** [comment]
@JannikDatsch mal drauf geachtet wie nah die stühle am tisch stehen? der char würde halt permanent im tisch stucken :D

**Comment by JannikDatsch** [comment]
Ich weiß, die standen davor aber dementsprechend ein Stücken weiter weg, sodass man sich mit Ö auf all diese Stühle setzen konnte.
