### ISSUE TITLE
Visitenkarten Lifeinvader

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#802]
Sind die nun mit V2 wieder verfügbar?
Habe vor ca einem Dreivierteljahr welche bei Lifeinvader bestellt und damals/heute hört man nur von ihnen das sie nicht gedruckt werden können.

**Comment by its4l3x** [comment]
@Statev-Bonsai Bitte sprich das mit Lifeinvader durch, die sollen sich dann bitte bei @DonVitoDiangelo melden.

Schließe das Ticket dann wieder
