### ISSUE TITLE
Antrag auf Mülltonne am GioV Restaurant

### ISSUE THREAD

**Issue by DylanDuncan** [mexyn/statev_v2_issues#807]
Bei uns wird extrem oft nach der nächsten Mülltonne gefragt. Einen passenden Platz dafür haben wir wie im Bild zu sehen als Vorschlag.

**Optional: Video / Bilder des Fehlers**

![2020-12-12](https://user-images.githubusercontent.com/75174723/101991310-1e942980-3cac-11eb-9d43-e8fa81657069.png)
![2020-12-12 (2)](https://user-images.githubusercontent.com/75174723/101991316-2784fb00-3cac-11eb-847d-fc9abe1a6dce.png)

**Comment by DonVitoDiangelo** [comment]
abgelehnt
