### ISSUE TITLE
Herstellungscomputer

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#808]
**Auftrittszeitpunkt (Datum / Uhrzeit)**
Nach dem Update vom 12.12.2020 20.00 Uhr
**Beobachtetes Verhalten**
https://youtu.be/NelxStDbPmc
**Erwartetes Verhalten**
Der Herstellungscomputer sollte wie vorher in die Produktionsansicht wechseln.
**Schritte um den Fehler nachvollziehen zu können**
Einfach eine Produktion starten.
**Optional: Video / Bilder des Fehlers**
https://youtu.be/NelxStDbPmc

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/817

**Comment by CrimeMouse** [comment]
error.factory.production.running

https://streamable.com/7f2vvq

**Comment by JulianMa** [comment]
Fixed mit nächstem Update.
