### ISSUE TITLE
Ausgewählte Simkarte wird im Telefon nicht gespeichert

### ISSUE THREAD

**Issue by zarazandra** [mexyn/statev_v2_issues#81]
Shiva_Connelly

**Zeitpunkt (Datum / Uhrzeit)**
26.08.20, 16:55 

**Beobachtetes Verhalten**
Leider bestehender Bug aus V1 - es wird nicht gespeichert, welche Simkarte man im Handy angehakt hat. Eigene Reihenfolge leider auch nicht auswählbar. 

Dies führt besonders dann zu Problemen, wenn man, wie ich, die Simkarte eines anderen Spielers hat, die aber älter ist als die Eigene. Telefoniert man oder schreibt man SMS ohne daran zu denken, dass die erste NICHT die eigene Nummer ist, schreibt und telefoniert man über eine fremde Telefonnummer. 

**Erwartetes Verhalten**
Hauptsimkarte festlegen, die auch ausgewählt bleibt, bis man die Auswahl selbst ändert ODER selbst festlegen der Reihenfolge, sodass man eine bestimmte Karte dauerhaft als "erste" Nummer anlegen kann. 
Bonus: Benennen der Nummern wie "Firmennummer XY", "Private Nummer" etc, um eine bessere Übersicht über die vorhandenen Nummern zu haben. 
Im Tablet kann man die Nummern leider auch nicht sortieren, sodass man sich aussuchen kann, welche Simkarte standardmäßig zuerst angezeigt bekommen möchte. Wenn hier einfach die (selbstgewählte) Sortierung aus dem Telefon übernommen werden könnte, wäre das schonmal ein toller Anfang. 

**Schritte um den Fehler nachvollziehen zu können**
Nach Relog oder bisher nicht näher definierten Triggerpunkten (vll Bewusstlosigkeit oder einfach Zeitmarke, noch nicht genau rausgefunden) wird die ausgewählte Nummer mit der Nummer im Handy ausgetauscht, die ganz oben in der Liste steht (also die älteste Simkarte). 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![unknown](https://user-images.githubusercontent.com/70195103/91320365-b6cdd780-e7bd-11ea-9d20-69ff1be3284a.png)

**Comment by r3sist3nt** [comment]
Ich weiß nicht warum, aber das wurde anscheinend noch nie in der Datenbank gespeichert. Ich korrigiere das mal.

**Comment by zarazandra** [comment]
DANKE!! <3

**Comment by r3sist3nt** [comment]
Ich hab beides angepasst:
![image](https://user-images.githubusercontent.com/10810443/94727818-8ef30600-035f-11eb-9e4b-ad05b4fa954b.png)

**Comment by zarazandra** [comment]
Das is ja wie Weihnachten! <3 Ganz viel Liebe geht raus!
