### ISSUE TITLE
Antrag für Öffentliche/Fraktions Garage

### ISSUE THREAD

**Issue by MamfredBrown** [mexyn/statev_v2_issues#810]
**Character Name**
Mamfred Brown

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jetzt

**Erwartetes Verhalten**
In der Niners Hood gibt es kein Gebäude an dem eine Garage angrenzt leider, aber am ende der Straße steht ein kompletter Garagenkomplex mit 5 Garagengebäuden und 7 Garagentoren, um den Mangel an Garagen, in der Straße auszugleichen wäre es gut dort die Garagen benutzen zu können. 
Wenn keine Fraktionsgarage möglich ist, eine Öffentliche würde auch vollkommen ausreichen.

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/GUtf0
https://pic.statev.de/image/GU9cX

**Comment by DonVitoDiangelo** [comment]
@DrGrizzlY17  Kannst mal checken wie das am besten passen würde mit den Häusern. Ne Öffi kommt da aber nicht hin. Höchsten in der näheren Umgebung bei einem passenden platz, wenn weit und breit nichts ist.

**Comment by DrGrizzlY17** [comment]
@DonVitoDiangelo 8 Häuse auf 7 Garagen

![image](https://user-images.githubusercontent.com/70150988/102363739-f9f2c700-3fb5-11eb-87f7-304f53187f44.png)

Etwas weiter nördlich befindet sich bereits eine Öffi

**Comment by DrGrizzlY17** [comment]
![image](https://user-images.githubusercontent.com/70150988/102363829-1858c280-3fb6-11eb-96f7-c6989cae8008.png)

**Comment by DrGrizzlY17** [comment]
Bleibt erstmal so wie es ist, dadurch das die Häuser nicht auf die Garagen passen von der Anzahl her, würde jemand den kürzeren ziehen. Die Garage ist ja in unmittelbarer nähe
