### ISSUE TITLE
Fehlermeldung bei Maschinenstart

### ISSUE THREAD

**Issue by AtreuX** [mexyn/statev_v2_issues#811]
**Character Name**
Tom_Clark

**Auftrittszeitpunkt (Datum / Uhrzeit)**
13.12.2020 gegen  00:25

**Beobachtetes Verhalten**
Bin mir nicht sicher, ob diese Fehlermeldung auch vorher schonmal erschienen ist. Jetzt aber mir das erste mal aufgefallen:
Bei Produktionsstart erscheint unten links über der Minimap die Fehlermeldung "error.factory.production.running". Produktion läuft offenbar allerdings bis jetzt normal.

Raffinerie - Herstellung von Diesel

**Erwartetes Verhalten**
Produktionsstart ohne eine Fehlermeldung

**Schritte um den Fehler nachvollziehen zu können**
1) Öl in die Maschine laden
2) Herstellung (hier Diesel) auswählen
3) Herstellungsprozess starten

**Optional: Video / Bilder des Fehlers**
https://youtu.be/IhjmFBA9QTQ

**Comment by Stiefel911** [comment]
Kann ich bestätigen , kam im Restaurant gestern auch, zum ersten Mal...

**Comment by Solomonetix** [comment]
gleiches in der Fertigung

**Comment by Nialicious** [comment]
In Waffenfertigung und Goldschmiede ebenfalls.
