### ISSUE TITLE
StateCom Dashboard Bug

### ISSUE THREAD

**Issue by Chrinis007** [mexyn/statev_v2_issues#812]
**Character Name**
Christian_Maier

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit V2

**Beobachtetes Verhalten**
Dashboard zeigt keine im Dienst befindlichen Personen mehr an

**Erwartetes Verhalten**
Rang+Name+ Online so wie in V1
**Schritte um den Fehler nachvollziehen zu können**
StateCOM MD öffnen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Ich gehe mal von LSMD aus... Korrekt?

**Comment by Chrinis007** [comment]
Ja LSMD

**Comment by its4l3x** [comment]
Fixed. Next Update
