### ISSUE TITLE
Akten Fehlermeldung StateCOM

### ISSUE THREAD

**Issue by Chrinis007** [mexyn/statev_v2_issues#813]
**Character Name**
Christian_Maier

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit V2

**Beobachtetes Verhalten**
Wenn eine Akte angelegt wird/eine bearbeitet wird erscheint rechts oben eine Fehlermeldung obwohl die Akte erfolgreich angelegt ist

**Erwartetes Verhalten**
Fenster schließen; Erfolgreich Akte angelegt wie in V1

**Schritte um den Fehler nachvollziehen zu können**
Akte im StateCom schreiben

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![grafik](https://user-images.githubusercontent.com/70342279/101999786-c9263f80-3ce0-11eb-969e-229aba0f4a07.png)

**Comment by its4l3x** [comment]
fixed seit vor vor letzten Update
