### ISSUE TITLE
Entfernung eines Verkaufsschildes

### ISSUE THREAD

**Issue by motioncsgo** [mexyn/statev_v2_issues#815]
**Character Name**
Marc Randall (Hash des Hauses: house_Richman_9)

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit Release von V2

**Beobachtetes Verhalten**
An unserem Wohnhaus steht ein "For Sale" Schild auf dem Rasen. Ein Schild wurde bereits entfernt, allerdings wurde das andere bei der Entfernung nicht gelöscht. 

**Erwartetes Verhalten**
Kein Schild auf dem Rasen

**Optional: Video / Bilder des Fehlers**

![unknown](https://user-images.githubusercontent.com/74965816/102017746-0e8e4f80-3d69-11eb-84a4-99558f62b550.png)

**Comment by DonVitoDiangelo** [comment]
abgelehnt, da die collision bestehen bleiben würde.
