### ISSUE TITLE
Sirenen Bug PD Fahrzeug

### ISSUE THREAD

**Issue by theStrongPD** [mexyn/statev_v2_issues#816]
**Lia Amirez**
 
Lia Amirez

**Auftrittszeitpunkt (Datum / Uhrzeit)**

13.12.2020 um 17:00 Uhr das letzte Mal 
**Beobachtetes Verhalten**

Sirenen des PD Fahrzeugs lösen aus, sobald man am Steuer sitzt, einen Namen im Handy sucht, eine Person oder Kennzeichen im State.com oder etwas auf dem Tablet schreibt bei den Buchstaben "E, R, Q" ggf. "1,2,3"

**Erwartetes Verhalten**

Die Sirenen des Streifenwagens sollten nicht auslösen bei Interaktionen mit anderen Geräten innerhalb des Fahrzeugs

**Schritte um den Fehler nachvollziehen zu können**

auf dem Fahrersitz sitzend, beispielsweise am Handy und einen Namen suchen, der "E,R,Q" im Namen hat
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Chrinis007** [comment]
Selbiges bei einem RTW oder wenn man was ic im statecom eingibt dass man dauernd Schneebälle aufnimmt
