### ISSUE TITLE
Error Meldung beim Maschine an machen.

### ISSUE THREAD

**Issue by StateV2Marie** [mexyn/statev_v2_issues#817]
Ich versuche es so gut wie möglich  zu erklären hab leider kein video also egal welche maschine ich an mache ob in Gießerei oder Weberei oder Labor oder Vertigung ich geb die menge ein klicke einmal auf denn knopf nix geht dann klicke ich erneut auf denn knopf dann gehts aber es kommt immer diese fehler meldung [https://pic.statev.de/image/img-20201213-164933.Gw5y7](url)

**Comment by Chandena** [comment]
kann ich so wiedergeben, is bei mir auch..

**Comment by PlayInc89** [comment]
Glaube das ist an allen Produktionsstätten so genau das selbe wie beim auspacken von Endprodukten.

**Comment by CaleighRhodes** [comment]
Man muss nicht zwei Mal drücken, die Produktion läuft schon nach dem ersten Drücken. Allerdings wechselt der Produktionspc nicht mehr in die Produktionsansicht. Die kriegt man, wenn man den PC einmal verlässt und dann neu reinschaut.
