### ISSUE TITLE
Rechtes Frontlicht Turismo R geht andauernd kaputt

### ISSUE THREAD

**Issue by CubeXLIVE** [mexyn/statev_v2_issues#818]
**Character Name**
Patrick_Nowak

**Auftrittszeitpunkt (Datum / Uhrzeit)**
21:15 - 13.12.2020
Schon seit mehreren Wochen aufgefallen

**Beobachtetes Verhalten**
Bei dem Turismo R geht bei ausgeparktem Zustand nach einiger Zeit das rechte Vorderlicht kaputt.
Sowohl manchmal beim Fahren als auch in abgestelltem Zustand. Offensichtlich nicht durch Unfall beschädigt.

**Erwartetes Verhalten**
Licht sollte nicht einfach so zerspringen, sondern nur kaputt gehen, wenn man wirklich einen Unfall hat oder eben dagegen Tritt oder sonstiges

**Schritte um den Fehler nachvollziehen zu können**
Turismo R ausparken -> rumfahren oder ausgeparkt für 30-90 Minuten stehen lassen -> Licht sollte kaputt sein

**Optional: Video / Bilder des Fehlers**
https://prntscr.com/w1wsni

**Comment by DonVitoDiangelo** [comment]
Mh, denke mal hängt mit dem bodyhealth Problem seitens alt:V zusammen. Bitte mal nach dem nächsten großen Update von altV weiter beobachten. Können aber sonst nichts dran ändern.
