### ISSUE TITLE
Sachen aus dem Rucksack verschwunden!

### ISSUE THREAD

**Issue by TorbenGross** [mexyn/statev_v2_issues#819]
**Torben_Gross**
**Freyhild_Gross**

Torben und Freyhild Gross

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
Wir haben je einen Rucksack aus dem Lager unserer Firma (Labor) genommen in den en unsere Anziehsachen und Waffen (2x Taurus eine Zugelassen auf Torben Gross und eine auf Freyhild Gross + 20 Magazine) waren, diese Rücksäcke waren beide leer und die Sachen verschwunden.

**Erwartetes Verhalten**
Das unsere Sachen noch in dem Rucksack sind 

**Schritte um den Fehler nachvollziehen zu können**
kann ich nicht genau sagen

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1005
