### ISSUE TITLE
"Das Fahrzeug ist nicht genug beschädigt", Motorleuchte Rot

### ISSUE THREAD

**Issue by zarazandra** [mexyn/statev_v2_issues#82]
**Character Name**
Shiva_Connelly

**Zeitpunkt (Datum / Uhrzeit)**
26.08.20, Uhrzeit nicht mehr bekannt (ca. 15 Uhr?)

**Beobachtetes Verhalten**
das verunfallte Fahrzeug mit roter Warnleuchte und brennendem Kühlergrill sollte, nachdem das Feuer nur noch rauchte (nicht ausgebrannt) mit einem Repkit repariert werden. Es kam die Meldung "Das Fahrzeug ist nicht beschädigt genug". Die Reparatur ging erst, nachdem man nochmal gegen das Fahrzeug getreten hat. 

**Erwartetes Verhalten**
Das Fahrzeug lässt sich ohne erneutes beschädigen reparieren.

**Schritte um den Fehler nachvollziehen zu können**
- Auto kaputtfahren, bis die Motorwarnleuchte rot ist
- Repkit benutzen
- Gegentreten
- Repkit tatsächlich nutzen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by mexyn** [comment]
@DonVitoDiangelo ich nehme an du konntest den fehler nachstellen, wenn du den bug confirmed hast? Ich bekomme es nämlich nicht hin?!
