### ISSUE TITLE
Verlagerung des Entladepunktes

### ISSUE THREAD

**Issue by MiguelTacus** [mexyn/statev_v2_issues#820]
Firmenhash : pfGroupAllRew_84

Hiermit beantrage ich die Versetzung des Be / Entlade Punktes.

Begründung : 1. Die maximale Sprachreichweite reicht für eine Kommunikation am Entladepunkt nicht aus
2. Der Entladepunkt wird sich mit einer anderen Firma geteilt, dies ist bei dem verfügbaren Platz nicht nötig/ Kann durch eine Kombination des Entladepunktes mit dem dessen von LionCut eleganter gelöst werden.

Aktueller Be / Entlade Punkt :
(Firma ist direkt neben dem LionCut, Entladepunkt entsprechend rechts an der Straßenecke)
![image](https://user-images.githubusercontent.com/75954035/102025542-f9c9b000-3d98-11eb-9967-2241347437ae.png)

Gewünschter Be / Entlade Punkt : 
(Entweder Teilung mit Entladepunkt des LionCut oder an Position des GT63)
![image](https://user-images.githubusercontent.com/75954035/102025556-17971500-3d99-11eb-81cd-547d15c3c185.png)

**Comment by DrGrizzlY17** [comment]
Der Punkt von der "pfGroupAllRew_8" ist quasi direkt vorm Laden...
Und der vorgeschlagene Punkt weiter weg als jetzt. Bist du dir sicher das es der richtige Hash war?
Ich weiß ja das dir Sky nicht gehört :D

**Comment by MiguelTacus** [comment]
Bin halt einfach behindert.
 Das Labor Twinkle Toes(das is tatsächlich meins lol) hat den Hash pfJunAltaRew_9. 
Bin leicht lost.
