### ISSUE TITLE
Wand Bug Gebäude Rancho Garage

### ISSUE THREAD

**Issue by Tiltplank** [mexyn/statev_v2_issues#821]
Nikolas Wick

14.12.2020 ca. 2:00 Uhr

Am Gebäude neben der Rancho Garage kann man durch die Wand laufen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

https://youtu.be/KYFCthFfS6Y

**Comment by DonVitoDiangelo** [comment]
Bekannt, danke. Wird vorerst nicht gefixt.
