### ISSUE TITLE
Club: Bahama Mamas kein Fortschritt im Skillbaum Ernährer nach Auspacken/Produzieren von Getränken

### ISSUE THREAD

**Issue by CrimeMouse** [mexyn/statev_v2_issues#826]
**Pablo Dosmas**

Pablo Dosmas

**Auftrittszeitpunkt**
14.12.2020 / 20:10

**Beobachtetes Verhalten**
Skillfortschritt Ernährer für Erfolgschance Bars funktioniert nicht

**Erwartetes Verhalten**
Skill sollte langsam steigen

**Schritte um den Fehler nachvollziehen zu können**
Einfach Sachen produzieren

**Optional: Video / Bilder des Fehlers**
![20201214201508_1](https://user-images.githubusercontent.com/74876113/102124968-394fd500-3e49-11eb-955c-21fa5aab47a1.jpg)

**Comment by DonVitoDiangelo** [comment]
next update fixed
