### ISSUE TITLE
Ansprache in Mitarbeitervertrags Email falsch

### ISSUE THREAD

**Issue by sGtDeath** [mexyn/statev_v2_issues#829]
**Character Name**
Frank_Gruber

**Auftrittszeitpunkt (Datum / Uhrzeit)**
14.12.2020

**Beobachtetes Verhalten**
Bei Mitarbeiterverträgen per Mail wird der Name des Versenders und nicht des Empfängers in der Ansprache angezeigt.

**Erwartetes Verhalten**
Der Name des Empfängers wird angezeigt.

**Schritte um den Fehler nachvollziehen zu können**
In eine Firma einstellen lassen

**Optional: Video / Bilder des Fehlers**
![Bug Email](https://user-images.githubusercontent.com/70219617/102135740-b171c700-3e58-11eb-89c8-9c2172a4fbae.png)

**Comment by its4l3x** [comment]
Bereits fixed. Ist schon davor augefallen. Einfach auf das nächste StateNET Update warten.
