### ISSUE TITLE
Inventory Bug

### ISSUE THREAD

**Issue by Acc3zZ** [mexyn/statev_v2_issues#83]
**Max_Strammer**

**26.08.2020 - 17:03 Uhr**

**Ich schaute in den Kofferraum des Fahrzeugs yosemite2. Inventory hing sich auf. Ich muss das Game komplett schließen.
https://prnt.sc/u6apsj**

**UI sollte sich nicht aufhängen. **

**Auto aufschließen, Kofferraum öffnen.**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by eiksch** [comment]
Ich habe ein paar Fixes aufgespielt, bitte erneut melden wenn dieser Fehler nochmal auftritt - und wo.

**Comment by r3sist3nt** [comment]
Bekannt und fixed.
