### ISSUE TITLE
Neue Kleidung [U] Tshirts mit Ärmeln

### ISSUE THREAD

**Issue by Koree7** [mexyn/statev_v2_issues#831]
Moin,
da es, glaube ich, unter Rage nicht möglich war [U] Tshirts mit Ärmeln hinzuzufügen wäre jetzt die Frage, ob es unter AltV möglich ist?

Siehe Link: [https://prnt.sc/w2rzlx]

Wäre bestimmt für den ein oder anderen Westenträger interessant, wenn der Schnee endlich mal schmilzt. :P

**Comment by Enemyaa** [comment]
Ist notiert. Wird kommen!
