### ISSUE TITLE
Änderungsvorschlag für Gamedesign: Item Forelle und davon abhängige Items

### ISSUE THREAD

**Issue by RomanSpielberg** [mexyn/statev_v2_issues#832]
Roman_Spielberg

15.12.2020

Kein Fehler, sondern ein Änderungsvorschlag an Gamedesign

Bereits seit Monate sind Forellen als Item eigentlich wirtschaftlich Tod. Durch die letzten Anpassungen, insbesondere Sättigungsgrad und Drinkverbrauch, werden die Forellenfilets kaum noch von der Bevölkerung angenommen.

Die Folgen daraus sind aktuell, es stapeln sich überall beim Metzer und Restaurant die Forellen und verpackten Forellenfilets. Praktisch unverkäuflich. Nicht mehr angeln ist auch keine Lösung, da ja die Lachse benötigt werden.
Ich kann jetzt natürlich hier nicht für den ganzen Server sprechen, aber IC konnte ich mir einigen Restaurant und Metzgereien sprechen und das Problem war dort genauso vorhanden.

Vielleicht kann man da ja was dran ändern, und entweder was am Sättigungsgrad und Drinkverbrauch anpassen oder die Forellenfilets im Export aufnehmen oder neue Gerichte entwickeln, die den Bedarf wieder erhöhen.
 

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Ich denke Serverseitig daran was zu verändern ist nicht die Lösung. Du landest damit in einem Teufelskreis, da dann zum Beispiel nur noch forellenfilet gekauft wird und nichts anderes mehr. Wir sind auf einem Wirtschaftsserver, da gilt auch das Konzept von Angebot und Nachfrage. Also in erster Linie ein Problem das die User verursacht wird und nicht von uns
