### ISSUE TITLE
Tablet aktualisiert Uhrzeit nicht.

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#833]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
15.12 15:05

**Beobachtetes Verhalten**
Öffnet man das Tablet, wird die Uhrzeit, zu der das Tablet geöffnet wurde, dauerhaft angezeigt. Beim Handy hingegen läuft die Uhrzeit weiter.   Beim Tablet aktualisiert sich die Uhrzeit hingegen nur, wenn man komplett aus dem Programm (StateNet, LI ...) rausgeht und in den Startbildschirm geht.

**Erwartetes Verhalten**
Auch im Tablet sollte immer die aktuelle Uhrzeit angezeigt werden.

**Schritte um den Fehler nachvollziehen zu können**
Tablet öffnen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Chrinis007** [comment]
Genauso wie ich in n anderes tab wie Messenger kurz rein muss damit sich die Dashboard anzeigen aktualisieren, wäre super wenn sich das tablet generell jedes Mal beim öffnen neu laden würde bzw. halt kurz aktualisiert

**Comment by its4l3x** [comment]
Fixed. Next Update
