### ISSUE TITLE
NotMD-Fraktions-Restart Bug

### ISSUE THREAD

**Issue by RealSocius** [mexyn/statev_v2_issues#834]
**Character Name**
Sebastian Schindler - Lifeinvader

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17:45-19 Uhr

**Beobachtetes Verhalten**
War im Not MD und die Stechuhr ist weitergelaufen, obwohl der Server neugestartet ist.

**Erwartetes Verhalten**
Nach Serverrestart keine Verbindung mehr zum Server möglich --> Offline stellen

**Schritte um den Fehler nachvollziehen zu können**
Einstempeln, Sterben, Restart und Spiel offen lassen, Geld verdienen

**Comment by RealSocius** [comment]
Ja also es wurde im Tablet angezeigt und die Uhr ist weitergelaufen, bei einem anderen wurde es ebenfalls angezeigt aber die Stechuhr ist nicht weitergelaufen.

**Comment by its4l3x** [comment]
fixed next update
