### ISSUE TITLE
Private Garage / Omerta Villa

### ISSUE THREAD

**Issue by EddiRos** [mexyn/statev_v2_issues#835]
Character Name
Eddi Rossmeisl

Auftrittszeitpunkt (Datum / Uhrzeit)
Jederzeit

Beobachtetes Verhalten
Die Fahrzeuge werden sehr weit weg Geparkt (Richman). Da keine andere Garage in der Nähe zur Verfügung steht.

Dadurch Parken und Schlafen wir immer in der Nähe einer Öffentlichen Garage.

Erwartetes Verhalten
Private Garage für die Villa (max. Anzahl). Optisches Carport vorhanden.
Schlafen/Übernachten gemeinsam in der Villa. (RP-Fördernd)

Optional: Video / Bilder des Fehlers

![271590_20201209200550_1](https://user-images.githubusercontent.com/75706231/102261873-95caf700-3f12-11eb-8d84-4e7e678bfce2.png)

![271590_20201209200552_1](https://user-images.githubusercontent.com/75706231/102261895-9d8a9b80-3f12-11eb-9dfe-1f4a8e5fa169.png)

![271590_20201210202217_1](https://user-images.githubusercontent.com/75706231/102262700-b5aeea80-3f13-11eb-81ee-0a9902281c18.png)

![1](https://user-images.githubusercontent.com/75706231/102261816-8350bd80-3f12-11eb-8a19-9be478a9a293.png)

![2](https://user-images.githubusercontent.com/75706231/102261835-88157180-3f12-11eb-8b15-5f631211d707.png)

**Comment by DrGrizzlY17** [comment]
Das ist kein Carport 😅
