### ISSUE TITLE
Stühle im MRPD nicht funktionsfähig

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#837]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
15.12 22:30

**Beobachtetes Verhalten**
Die Stühle im MRPD sind teilweise nicht besetzbar. Die hinter dem Tresen nicht, die Bänke auch nicht. Oben im 1. OB im Großraumbüro dasselbe.

**Erwartetes Verhalten**
Man sollte sich auf die Stühle setzen können.

**Schritte um den Fehler nachvollziehen zu können**
siehe oben

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/xidiYYpJJ2g
https://youtu.be/jesK9xawwMo

**Comment by DonVitoDiangelo** [comment]
wird vorerst nicht angegangen.
