### ISSUE TITLE
Haus mit 3 Garagen auf dem Grundstück hat keine Garage die zum Haus Gehört Antrag auf Garage 

### ISSUE THREAD

**Issue by MaxiKowa** [mexyn/statev_v2_issues#839]
**Character Name**
Maxi Kowa

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Erwartetes Verhalten**
Ich habe auf meinem Grundstück 3 Garagen und keine davon gehört zu meinem Haus. Die Garage die direkt neben meinem Haus ist sehr eindeutig auf meinem Grundstück steht Gehört zu dem Haus auf dem Nachbargrundstück. Deshalb hätte ich gern das die Garage die direkt neben meinem Haus die auf meinem Grundstück steht auch zu meine Haus Gehört

Haushash house_DavisMidLS_16
Adresse Brouge Ave. 13

**Optional: Video / Bilder des Fehlers**

https://youtu.be/mORVM-OgX_c

**Comment by DrGrizzlY17** [comment]
Das ist natürlich ein wenig Problematisch. Das Haus wo die Garage gelandet ist, ist auch schon gekauft... Somit kann ich die Garage nicht einfach umsetzen auf dein Haus...

Die Garagen die noch im Garten sind, haben keine eigene Zufahrt...
Ich bespreche mich da mal mit @DonVitoDiangelo

**Comment by DrGrizzlY17** [comment]
Hab mit Vito Rücksprache gehalten... Leider bist du der leidtragende, aber wir werden das nicht ändern. Immerhin ist in nichtmal 20m Luftlinie ne öffentliche Garage
