### ISSUE TITLE
Login Fehler

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#84]
**Character Name**
Marvin_Elpe

**Zeitpunkt (Datum / Uhrzeit)**
jederzeit

**Beobachtetes Verhalten**
Wenn man im Login Screen sein PW falsch eingibt und dann STRG+A drückt um die Zeile zu markieren um es schneller raus löschen zu können, markiert man alles und kann diese Markierung nicht wieder weg machen um das PW neu einzugeben. Neustart ist nötig

**Erwartetes Verhalten**
Nur das Markieren des PW

**Schritte um den Fehler nachvollziehen zu können**
Im Login Screen STRG+A drücken

**Optional: Video / Bilder des Fehlers**
![zOk9Ahg 1](https://user-images.githubusercontent.com/33394632/91325173-2abeae80-e7c3-11ea-8651-17afdfcaaedf.jpg)

**Comment by r3sist3nt** [comment]
da fehlt ```user-select: none``` im scss

**Comment by eiksch** [comment]
Mit TAB kann man da auch rumspielen um den Fokus vom Feld wiederzubekommen, ohne das Spiel neustarten zu müssen.

**Comment by M4rvinLP** [comment]
alles klar danke

**Comment by eiksch** [comment]
Fixed im nächsten Update.
