### ISSUE TITLE
Keine Fahrzeuge im Statenet mehr sichtbar

### ISSUE THREAD

**Issue by State-DiegoCruz** [mexyn/statev_v2_issues#840]
**Character Name**
Diego_Cruz

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seid dem 13.12.2020

**Beobachtetes Verhalten**
Keine Fahrzeuge im Tablett mehr sichtbar weder mit dem PC noch am Laptop oder sonstigen anderen Geräten. Sobalt ich im Statenet Links auf Fahrzeuge drücke bleibt die Seite rechts leer

**Erwartetes Verhalten**
Das man die Fahrzeuge natürlich wieder wie zu erwarten sieht und orten kann

**Schritte um den Fehler nachvollziehen zu können**
Ganz normal im Statenet auf Fahrzeuge Drücken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
3440 x 1440 aber ich glaube nciht das dass das Problem sein wird da auf anderen geräten mit anderer Auflösung ja das selbe Problem besteht

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/G99xI

**Comment by CaleighRhodes** [comment]
Bei mir funktioniert alles einwandfrei. Sowohl IC als auch OOC.

**Comment by State-DiegoCruz** [comment]
Das weiß ich es geht ja nur bei mir eben nicht mehr

**Comment by its4l3x** [comment]
Bitte noch mal auf die Fahrzeug-Übersicht gehen und F12 Öffnen, sowie die Console öffnne. Dann nochmal ein Screen machne bitte.

**Comment by State-DiegoCruz** [comment]
https://pic.statev.de/image/YHIvw

**Comment by State-DiegoCruz** [comment]
https://pic.statev.de/image/YHPZz

**Comment by JulianMa** [comment]
Versuch mal folgendes:
F12 -> Application -> LocalStorage -> https://net.statev.de
Und dann alle Einträge in der Liste löschen. (Mit entf Taste)
Dann neu Laden/Einloggen

**Comment by State-DiegoCruz** [comment]
https://pic.statev.de/image/YHjyX

**Comment by State-DiegoCruz** [comment]
geht immer noch nciht fehler siehe oben

**Comment by its4l3x** [comment]
Fixed.
