### ISSUE TITLE
Gewisse Hosen des SAPD nicht mehr vorhanden.

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#841]
**Character Name**
Suna_Nolan

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.12.2020, 15:30 Uhr

**Beobachtetes Verhalten**
Gewisse Hosen für die Frauen sind am Spint des SAPD nicht mehr nutzbar und werden durch die "Private" hose ersetzt.
Bei Uniformen wo dies vorher noch anders war.
Dies ist seit dem letzten GTA Update so

**Erwartetes Verhalten**
Das die Uniformen wieder wie gehabt aussehen.

**Schritte um den Fehler nachvollziehen zu können**
Frau sein.
SAPD Sheriff Uniformen anziehen sollen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![f340d6278d2d129314bc50f3f7790ca5](https://user-images.githubusercontent.com/70150887/102362345-91efb100-3fb4-11eb-9ae6-4ad9841364a8.png) 
😜😏

**Comment by Enemyaa** [comment]
Welche trägt man denn darunter? Die normale Hose oder die Leggings?

Bei beiden gibt es keine Probleme: https://prnt.sc/w49gki  https://prnt.sc/w49gwb

**Comment by Enemyaa** [comment]
@TheBroady

**Comment by Enemyaa** [comment]
Ok, ich weiß welche. Die Drawable steht gar nicht mehr zur Verfügung - komischerweise. Entweder verschoben oder ganz gelöscht. Das muss ich mal herausfinden.

**Comment by Enemyaa** [comment]
Tatsächlich wurden die Hosen von Rockstar himself verschoben. Sollten aber nach dem nächsten Update wieder tragbar sein.
