### ISSUE TITLE
Zweiter, rotes, fragmentiertes Hemd wird über Ausgerüstet [U] angezeigt

### ISSUE THREAD

**Issue by theSiixx** [mexyn/statev_v2_issues#842]
**Character Name**
Justis Uhlich

**Auftrittszeitpunkt (Datum / Uhrzeit)**
ca 7:23PM

**Beobachtetes Verhalten**
Es wird bei anderen Spielern ein zweites, rotes, fragmentiertes Hemd in meinem aktuell ausgerüsteten Hemd angezeigt.

**Schritte um den Fehler nachvollziehen zu können**
Es ist mir nicht bekannt wie der Fehler reproduziert werden könnte, Jedoch habe ich heut erst ein [Issue im AltV Discord gesehen](https://discordapp.com/channels/371265202378899476/557307592129511444/788720321108770816)

**Bilder des Fehlers**
![not-good](https://user-images.githubusercontent.com/25814900/102391403-f53e0b00-3fd5-11eb-8c00-e584e1def4f3.jpg)
![good](https://user-images.githubusercontent.com/25814900/102391417-f96a2880-3fd5-11eb-89b9-86eaa0cada48.png)

**Comment by theSiixx** [comment]
// Edit: Hab den Fehler gerade auch bei anderen Entdeckt:
![Screenshot_203](https://user-images.githubusercontent.com/25814900/102391788-785f6100-3fd6-11eb-9c73-97e1df0ae241.png)

**Comment by JulianMa** [comment]
alt:V Issue

**Comment by JulianMa** [comment]
fixed durch alt:V
