### ISSUE TITLE
Lager unterschiedlich groß

### ISSUE THREAD

**Issue by Clawdie** [mexyn/statev_v2_issues#843]
Glinda Ehrmantraut

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16./17.12.2020

**Beobachtetes Verhalten**
Lager Suburban (Harmony, ehem. Chiliad Fashion) hat 1600kg, Binco in Harmony (DiscountStore3) hat nur 980kg

**Erwartetes Verhalten**
Gleicher Lagerumfang der Bekleidungsgeschäfte

**Schritte um den Fehler nachvollziehen zu können**
Lagergrößen vergleichen

**Comment by Enemyaa** [comment]
Die Lagergröße variiert zwischen der Art des Laden's. Schon immer!

**Comment by DrGrizzlY17** [comment]
> Die Lagergröße variiert zwischen der Art des Laden's. Schon immer!

So siehts aus, auch für Kleidungsläden gilt das Prinzip von Größe und Klasse etc.
