### ISSUE TITLE
Ladenpreise werden teils nicht gespeichert

### ISSUE THREAD

**Issue by Clawdie** [mexyn/statev_v2_issues#844]
**Character Name**
Glinda Ehrmantraut

**Auftrittszeitpunkt (Datum / Uhrzeit)**
aktuell und schon Januar/Februar 2020

**Beobachtetes Verhalten**
Wenn Ladenpreise im Bekleidungsgeschäft eingegeben werden, werden diese nur manchmal gespeichert.

**Erwartetes Verhalten**
Ladenpreise werden durch Speicherung gesichert.

**Schritte um den Fehler nachvollziehen zu können**
Versucht:
- verschiedene Personen
- IC mit offener Theke, IC ohne Theke, IC mit Tablet, extern via State.net
- kleinere Mengen und größere Anzahl Preise auf einmal festgelegt
- Nutzung der Tab-Taste und ohne

Teils wird ein Packen Preise gespeichert und kann entsprechend wieder abgerufen werden. Teil ist es jedoch so, dass bei Eingabe weiterer Preise nach Speicherung alle Preise, die vorigen Preise oder random Preise mittendrin nicht mehr angezeigt werden.
Ein Aufrufen anderer State.net-Bereiche (z.B. Finanzen, Gehälter, Messenger etc.) scheint die Nicht-Anzeige/Löschung zu begünstigen.

Im TS-Support mit gordon nachvollzogen/getestet.

Betraf sowohl den Suburban in Harmony Anfang des Jahres als auch jetzt den DiscountStore3 in Harmony.

Im Suburban trat das Problem primär bei Erstbepreisung auf, später kaum noch (gilt auch für den Discount aktuell).

**Comment by JulianMa** [comment]
Bereits bekannt

**Comment by its4l3x** [comment]
Sollte fixed sein.
