### ISSUE TITLE
Mietzins Einnahmen Email

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#845]
**Character Name**
Max_Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.12.2020, 12:14

**Beobachtetes Verhalten**
Ich schaue in mein Tablet in die Emails uns sehe dort die "Mietzins Einnahmen".
Dort wird mir eine mail geschickt wenn jemand Miete in meinem Hotel bezahlt hat.
Allerdings sind dort seit dem 10.12.2020 19:23 keine neuen Mails eingegangen.
Demnach wenn ich das System richtig deute sollten auch seit dem keine Mieten mehr bezahlt worden sein.
Mein Konto im Hotel spricht dort allerdings andere Bände.
Dort ist die letzte Miete am 17.12.2020 01:39 eingegangen.

**Erwartetes Verhalten**
Jedes mal wenn eine Miete Bezahlt wird, wird eine Mail in die "Mietzins Einnahmen" geschickt.

**Schritte um den Fehler nachvollziehen zu können**
Hotel besitzen und Mieten bekommen.
Scheinbar wird nicht jede Mietüberweisung per Mail verschickt.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Mails Kopie, der letzten Mail:
![Screenshot_1](https://user-images.githubusercontent.com/70150887/102481057-7c849080-4061-11eb-9225-d9707ba8ac3a.jpg)

Kontoauszug letzte Miete:
![Screenshot_2](https://user-images.githubusercontent.com/70150887/102481080-86a68f00-4061-11eb-805c-716b81a4539c.jpg)

**Comment by its4l3x** [comment]
Brauche den Hash deines Buildings bitte.

**Comment by TheBroady** [comment]
> Brauche den Hash deines Buildings bitte.

AkiPillboxHillRew_Flat_5

**Comment by its4l3x** [comment]
Sorry for late Answer. Ist das Problem nochmal aufgetreten?

**Comment by its4l3x** [comment]
Glaube nicht. Trotzallerdessen werden wir in Zukunft ein Refactor des ganzen Haus/Building Systems in Betracht ziehen, da dort Potenzial besteht, weitere Sachen zu erweitern.

**Comment by TheBroady** [comment]
Jo ist immernoch nicht richtig.

![Screenshot_2](https://user-images.githubusercontent.com/70150887/107130651-0ae1f980-68d0-11eb-85a4-17e89e963a02.jpg)

![Screenshot_1](https://user-images.githubusercontent.com/70150887/107130652-0b7a9000-68d0-11eb-8ac6-9d859be29f41.jpg)

**Comment by its4l3x** [comment]
Okay got it. Gerade nachgeschaut: Betrag $10 ist Brutto ohne Abzüge. Betrag $8,50 ist Netto. Dort wird einfach der falsche Wert angezeigt. Könnte das Problem jetzt lösen in dem man das ändert den Text in "[...] über $10 mit Abzug von Gebühren & Steuern" oder so. :D

**Comment by TheBroady** [comment]
> Okay got it. Gerade nachgeschaut: Betrag $10 ist Brutto ohne Abzüge. Betrag $8,50 ist Netto. Dort wird einfach der falsche Wert angezeigt. Könnte das Problem jetzt lösen in dem man das ändert den Text in "[...] über $10 mit Abzug von Gebühren & Steuern" oder so. :D

Gesundheit 😂

**Comment by its4l3x** [comment]
Haha xD

=> $10 = Brutto
=> 8,50 = Netto mit Abzügen
=> Lösung 1: Nachricht umbennen im StateNET. 

Passts so? :D

**Comment by TheBroady** [comment]
> Haha xD
> 
> 
> 
> => $10 = Brutto
> 
> => 8,50 = Netto mit Abzügen
> 
> => Lösung 1: Nachricht umbennen im StateNET. 
> 
> 
> 
> Passts so? :D 

Ja das passt so, danke dir 😂😂

**Comment by its4l3x** [comment]
Passt. Message angepasst. 

In Zukunft steht hinter den $10 noch (Brutto) damit das gekennzeichnet ist :D

**Comment by TheBroady** [comment]
@its4l3x bedenke bei den Fotos die ich vor kurzem beigefügt habe, dass die schreibweise nicht das Hauptproblem war. Sondern das die letzte Mail nicht die letzte gezahlte Miete widerspiegelt.

Nach meiner Auffassung sollte jedes Mal wenn eine Miete gezahlt wird, eine email versendet werden.
Wie aber in den Fotos zu sehen ist, ist die letzte Mail von einer anderen Person als die, die als letztes Miete gezahlt hat.
