### ISSUE TITLE
Suchfunktion in Lagern/Spint etc unsauber

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#846]
**Character Name**
Max Broady (im Video Gonzo_Menendez)

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.12.2020

**Beobachtetes Verhalten**
Beim nutzen der Suchleiste im Spint/Hauslager etc wird oftmals nicht richtig gefiltert. Erst beim Scrollen oder langsameren eintippen der Buchstaben.
Erst bei erneutem Öffnen wird der gesuchte Gegenstand (Hier eine G36) richtig gefiltert.

**Erwartetes Verhalten**
Saubere filterung der Gegenstände im Lager beim eintippen der Buchstaben in das Suchfeld.

**Schritte um den Fehler nachvollziehen zu können**
Recht volles Lager öffnen und anschließend wie im Clip nach einem Gegenstand suchen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Ich habe leider kein eigenes Video, aber gestern im Stream bei Gonzo diesen Fehler nochmal gesehen.
Daher einfach fix einen Clip von dem Moment gemacht.
https://clips.twitch.tv/CarelessRelievedSandstormYouWHY

**Comment by DrGrizzlY17** [comment]
Ist mir auch bereits aufgefallen. Der Fehler liegt wohl daran, das die UI Position bei der Suche nicht resettet wird.
Das heißt scrolle ich im Lager runter und suche dann ein Item wird es nicht richtig angezeigt, da die Seite noch den Status hat
das sie runtergescrollt wurde.

Um es quasi anhand eines Textdokuments zu beschreiben.
Ich scrolle im Dokument runter, so das Zeile 30 die oberste Zeile ist die ich noch sehe.
Suche ich dann nach einem Item im Dokument wird das in Zeile 1 angezeigt.
Meine Ansicht vom Dokument bleibt aber stuck bei Zeile 30 und springt nicht hoch auf Anfang.

Ich hoffe das konnte man verstehen^^

**Comment by Acc3zZ** [comment]
Wurde gefixt und wird beim nächsten Update dabei sein
