### ISSUE TITLE
SAPD/BCSO Livery

### ISSUE THREAD

**Issue by MisterCopeland** [mexyn/statev_v2_issues#847]
Howdy an die Entwickler und alle anderen Neugierigen Nasen,

am 17.02.2019 wurde die Fraktion LSPD umstrukturiert und es wurde das SAPD geboren. Das SAPD wurde zwischen dem LSPD und dem SACS getrennt. Im späteren Verlauf kam dann noch die SAHP dazu. 
Anfang des Jahres wurde durch die SAPD Leitung ein Fraktionskonzept eingereicht (Welches durch die Fraktionsverwaltung befürwortet wurde) was viele Änderungen im SAPD herbeigeführt hat. 
Das SACS und die SAHP wurden zusammengeführt und es entstand am 16.08.2020 das Blaine County Sheriff Office.

Seitdem wird dieses „Department“ oder gar eine Fraktion innerhalb der anderen Fraktion bespielt.
Das BCSO ist ein wichtiger und großer Bestandteil des SAPD geworden. Mit 37 von 119 Spielern macht dies einen guten drittel der Fraktion aus.

Das GTA Lore selbst besitzt kein BCSO. Sondern nur das LSSD (Los Santos County Sheriff Department). Und dies zeigt sich bei den Fahrzeugen der Fraktion.

Weder ein einheitliches Livery Set noch genügend Livery für alle Fahrzeuge stehen zur Verfügung.

Seit dem V2 Update stehen dem SAPD die Scouts zur Verfügung. Leider nur mit LSPD Livery.
Ich und hier spreche ich für den größten Teil der Sheriffs wünschen uns für das BCSO ein einheitliches Livery Set für alle Fahrzeuge.

Mit dieser Modifikation wäre dies „Lore Friendly“ möglich 
(Vorteil dieser Modifikation ist es ja: Es sind keine Modded Fahrzeuge, also keine Performance Einbußen). https://de.gta5-mods.com/vehicles/blaine-county-sheriff-pack-bozza-et-al

Ich bedanke mich fürs Lesen und hoffe auf Positive Entscheidungen.

Howdy von einem Sheriff 😊

**Comment by DrGrizzlY17** [comment]
Die Entscheidungsgewalt liegt hier bei @DonVitoDiangelo 
Ich stell trotzdem mal die Frage in den Raum... Wieso brauchen wir sowas?
Es gibt nicht ein Fahrzeug auf dem explizit Los Santos Police Department steht, wenn doch Change my mind...
Wenn wir damit nämlich Anfangen unterschiede zu machen, kommt demnächst das LSPD und will LSPD Aufschriften.

Zudem wenn euch stört das es in GTA nur das LSSD gibt und nicht das BCSO (was ne eigen Erschaffung ist), dann nennt euch doch einfach in LSSD dann habt ihr euren Wunsch. 

Psst... Wenn wir euch LSSD nennt, wären eure Departments jedenfalls einheitlich benannt und so....
LSPD -> Los Santos Police Department
LSSD -> Los Santos Sheriff Department

**Comment by MisterCopeland** [comment]
Weil die Stadt Los Santos über die Grenzen hinweg in Los Santos County und Blaine County unterscheidet. 
Und die bisherigen LSPD Fahrzeuge sind auch LSPD Fahrzeuge. Das Logo sagt schon aus das es das LSPD / City ist.

Auch ein Einheitliches LSSD Livery Set gibt es ja nicht. Der Fuhrpark alleine von GTA aus bietet kaum eine Auswahl.

Ich frage mich was dagegen spricht? Es gibt keine Nachteile davon und eine Spielerschaft wäre glücklich.

**Comment by Mr-Chris-VRTY** [comment]
"Es gibt nicht ein Fahrzeug auf dem explizit Los Santos Police Department steht, wenn doch Change my mind..."
vllt nur ein paar Ausschnitte um es zu verdeutlichen:
[https://static.wikia.nocookie.net/gtawiki/images/b/b1/PoliceCruiser2-GTAV-front.png/revision/latest?cb=20180331183631](url)
[https://i.redd.it/7ys70mr97kj01.jpg](url)
[https://www.gtabase.com/images/gta-5/vehicles/emergency/main/police-cruiser.jpg](url)

**Comment by DonVitoDiangelo** [comment]
Vorerst abgelehnt.  Wir werden wir das Modding derzeit nicht erweitern. Vllt. später einmal aber aktuell ist der Stand so, wie Ihr auch damit zurecht kommen müsst.

**Comment by DrGrizzlY17** [comment]
@Mr-Chris-VRTY Naja nen kleiner Sticker auf dem steht In Emergency dial LSPD rechtfertigt jetzt keine komplette Livery. Das ist für mich auch keine Fahrzeug Aufschrift sondern einfach nur nen kleiner Sticker

**Comment by MisterCopeland** [comment]
Um diese Entscheidung nachvollziehen zu können würde ich gerne wissen, was dagegen spricht. Sind es Performance Gründe, oder gibt es aktuell große Critical Bugs die mehr Zuwendung benötigen, oder wird es nur abgelehnt, weil man keine Lust hat sich damit zu beschäftigen?
