### ISSUE TITLE
SMS Konversationen löschen auf Behörden Nummern (919, 911, etc.)

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#848]
**Character Name**
Max_Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
17.12.2020 14:43

**Beobachtetes Verhalten**
Es ist nicht mehr möglich eine Konversation auf der 919 oder 911 (alle außer man selbst ist Admin) zu löschen.
Früher ging es indem man die Konversation über das Smartphone gelöscht hat.
Dadurch, dass die App allerdings nicht mehr auf dem Smartphone ist, kann man die Konversationen nicht mehr löschen.
Gerade bei den Nummern 919, 911 und weiteren häufen sich mit der Zeit recht viele SMS an und wir würden gerne dort für Überblick sorgen.

**Gewünschtes Verhalten**
Das man auch wenn man nicht Admin der Sim ist, eine Konversation löschen kann

**Schritte um den Fehler nachvollziehen zu können**
919 einlegen und probieren eine Konversation zu löschen (als nicht Admin)
Keine Ahnung wer der Admin der 919 Sim ist.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
-

**Optional: Video / Bilder des Fehlers**
-

**Comment by Chrinis007** [comment]
912 das selbe

**Comment by DrGrizzlY17** [comment]
Das trifft generell auf jede Nummer zu wo man nicht der Besitzer ist

**Comment by its4l3x** [comment]
Korrekt. Nur der Besitzer kann derzeit SMS Konv. löschen.

Wir werden dies mal im kommenden Meeting besprechen und Feedback geben.

**Comment by its4l3x** [comment]
Siehe Meeting Protokoll von vor paar Wochen (Abgelehnt)


Closed, aber stay tuned. :)
