### ISSUE TITLE
Chara Erstellung Buggy

### ISSUE THREAD

**Issue by cocokamisama82** [mexyn/statev_v2_issues#849]
**Pan_Li**

**Dienstag vor einer Woche / Ka welche Uhrzeit)**

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by TheBroady** [comment]
Kannst du bitte den Bugeintrag so ausfüllen, das die Entwickler damit auch arbeiten können.
Hier fehlen einige informationen.

**Comment by cocokamisama82** [comment]
Buggy ist die gesamte Chara Erstellung, da sich kein Chara bauen lässt da er ständig aus dem Bild rennt oder wie im Report in meiner Akte festgehalten wurde von einem Supporter. den Rücken zu dreht. Er lässt sich halt nicht erstellen 

Davor? Ganz normales EInloggen und eben den Char versucht zu erstellen 

Der Bug hat sich durch zwei Verschiedene Arten bemerkbar gemacht : 
1) Hatte ich ab und an das Waffenrad direkt nach Login in der Erstellung 
2) Chara ist nicht im Bild und "rennt" nach einigen Versuchen mal durchs Bild aber bleibt nicht stehen so das eine erstellung unmöglich wird.

Man saß auch mit dem Support daran und haben einiges ausprobiert und das über gefühlt Stunden.

**Comment by DonVitoDiangelo** [comment]
hast du noch immer keinen Char? Oder konnte das Problem mittlerweile gelöst werden?

**Comment by cocokamisama82** [comment]
Nein , habe leider noch immer keinen chara erstellen können. 
Eine Idee wäre ja gewesen mal von einem Bekannten von euch der nen acc hat den darüber zu bauen ........

**Comment by cocokamisama82** [comment]
Hier auch ein Video von dem Problem
hoffe , das hilft euch 

https://www.youtube.com/watch?v=N10ONvHS9Uo&feature=youtu.be

**Comment by DonVitoDiangelo** [comment]
Also es wirkt so als sei dein Rechner auf jeden Fall an seiner Belastungsgrenze. Hast du denn schon einmal GTA so an sich gespielt?
Sonst könntest du auch einfach mal versuchen, alles andere an Programmen was nicht benötigt wird zu schließen.
Also z.B. Discord, Browser, Aufnahmeprogramm usw.

**Comment by JulianMa** [comment]
Sind deine Inputs in den Einstellungen auf RAW gestellt?
![image](https://user-images.githubusercontent.com/10810443/102781682-5e3bcf00-4398-11eb-868d-e4154d2b4415.png)

**Comment by cocokamisama82** [comment]
alle Einstellungen sind auf Raw Input Umgestellt bei mir.

GTA an sich habe ich schon ohne Probleme spielen können. 
Das Game ansich Funktioniert nur mein Charakter rennt ha ständig weg, darum geht es ja eigentlich ^^ 

Ich hatte letztens mit Harry Spotter schon ein wenig ausprobiert zb den Charakter unverändert erstellt, bin auch gespawnt und er hatte mich zur NSA Base teleportiert und da hat alles ohne probleme funktioniert ( konnte  rumrennnen ect ) .


Vielleicht ist es Hilfreich den Charakter zu löschen und einen Neuen zu erstellen ? 
Oder gibt es die möglichkeit das ihr mir den Chara erstellt ? oder gibt es die möglichkeit das sich jemand anderes , ein guter Freund , sich mit dem Acc einloggt ? und Probiert ob der Charakter bei ihm ebenfalls wegrennt ( zwecks fehleranalyse ) .

**Comment by JulianMa** [comment]
Wenn es wirklich nicht anders geht, kann man bestimmt auch darüber reden wenn du das ganze auf nem PC von deinem Kollegen machst. 
Es ist aber immernoch merkwürdig das es nur bei dir auftritt.

**Comment by cocokamisama82** [comment]
ob Merkwürdig oder nicht. Das Problem scheint ja da zu sein. Ob es nun bei Nur mir ist oder nicht.

und finde es auch sehr merkwürdig das es nicht geht. 

Und das probieren wäre ja wie erwähnt auch nur zur Fehleranalyse über seinen Rechner dann dllung zu machen. 

Weis halt sonst auch nicht mehr weiter.

**Comment by cocokamisama82** [comment]
Ich würde dann an dieser stelle gerne den "Multiaccount" beantragen , da mein Kollege Benschi Brown , meinen Chara dann mit mir zusammen erstellen würde. 
Wäre es also möglich dafür eine Freigabe zu bekommen und freigeschaltet zu werden dafür ? 

Liebe Grüße

**Comment by JulianMa** [comment]
Ihr müsst dafür (am besten beide) in den TS-Support kommen.
Wenn du heute Zeit hast, kannst du mich einfach im Discord anschreiben, dann mache ich das eben. (r3sist3nt#3119)

**Comment by JulianMa** [comment]
Ich schaue mir den Fehler trotzdem mal genauer an, es gibt jetzt noch jemanden bei dem das Auftritt, womit ich ausschließe das es an deinem PC liegt.

**Comment by JulianMa** [comment]
@cocokamisama82 du hast aber keinen Controller angeschlossen, oder?

**Comment by cocokamisama82** [comment]
Hey Julian. Nein habe keinen Kontroller angeschlossen

Noch einen ? wow :D irgendwie erleichtert das es nicht nur an meinem rechner liegt / lappi 

und ich sag Benschi Bescheid, der kommt allerdings heute später nach Hause

**Comment by JulianMa** [comment]
ich schließe hier, da alle anderen Personen einen Controller angeschlossen haben und niemand sonst den Bug reprodozieren konnte.
