### ISSUE TITLE
Oclet Jugular Leistung

### ISSUE THREAD

**Issue by Jonstrange-beta** [mexyn/statev_v2_issues#85]
Jon Strange

**Zeitpunkt (Datum / Uhrzeit)**
26.08.2020

**Beobachtetes Verhalten**
Ich bin in den Jugular eingestiegen und wollte sehen welche Leistung er bringt.
Doch leider war die Beschleunigung sehr niedrig, dennoch kam ich auf 240 km/h nach der Zeit.
Für ein Auto was 160.000$ kostet und ein allrad Sportwagen ist, war die Beschleunigung sehr entteuschend

**Erwartetes Verhalten**
Ich hab erwartet das die endgeschwindigkeit gedrosselt wird. Aber die Beschleunigung normal bleibt.

Ich hab zum test meinen caracara ausgeparkt und von der Beschleunigung kaum ein unterschied gemerkt.

Könnt Ihr bitte die BEschleunigung wieder hochsetzen, aber dafür den Endgeschwindigkeit drosseln?

**Optional: Video / Bilder des Fehlers**
https://streamable.com/xykmnx

**Comment by Statev-Bonsai** [comment]
Was hat der Preis mit der Geschwindigkeit zu tun? 👯‍♀️

**Comment by eiksch** [comment]
Das Auto ist komplett in Ordnung.

**Comment by Jonstrange-beta** [comment]
Es geht mir auch nicht um den Preis oder endgeschwindigkeit.

Es geht mir um die Beschleunigung. Mein Char hat  Auto die eigentlich eine gute Beschleunigung haben und sollten

Mustang GT, Hellfire und der Jugular.

Aber mit V2 ist die Beschleunigung bei alle dreien stark reduziert. Ich finde sogar zu stark

**Comment by zarazandra** [comment]
Die Beschleunigung ist wirklich stark abgeschwächt - das war die eigentliche Stärke des Jugular.
