### ISSUE TITLE
Penumbra hat keine sichtbaren Folierungen mehr 

### ISSUE THREAD

**Issue by HamasakiPinkman** [mexyn/statev_v2_issues#850]
Hallo ich habe gestern mein Penumbra (Auto) ausgeparkt und musste feststellen das die Folierung nicht mehr vorhanden war, als ich dann am nächsten Tag (heute) zu meiner Werkstatt des Vertrauens gefahren bin mussten wir mit Erstaunen feststellen das keine Folierung in der Vorschau angezeigt wird.

MFG
Dennis_Pinkman

**Comment by JulianMa** [comment]
alt:V bug

**Comment by KarlKreislauf** [comment]
Die Folierung finden du Unter den Bremsen weiß der Teufel wie die da hingekommen sind aber Wenn du den Bremsen typ änderst, änderst du auch die Folierung. und siehst sie natürlich auch wieder . 
Lg

**Comment by HamasakiPinkman** [comment]
@KarlKreislauf danke für die Info, habe es eben IC getestet nur hängen die Folierungen nun mit der Bremse zusammen was recht blöd ist da dann eine Folierung so rund 6k kostet und es gibt nur weniger Bremsen und mehr Folierungen für das Auto und da ist die die ich drauf hatte nicht dabei, muss also noch mal irgendwie nachbearbeitet werden

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/893
