### ISSUE TITLE
Garagenstellplatz Anfrage Westmirror Drive 35

### ISSUE THREAD

**Issue by Drambu** [mexyn/statev_v2_issues#851]
Ich erbitte einen Garagenstellplatz für West Mirror Drive 35  (Haushash    | GroupAllRew_House_4 )

Das Haus hat eine sehr lange Einfahrt, auf der mehrere Fahrzeuge Platz hätten (sh. Foto)

Adresse und Garageninfos vorhanden.

Vielleicht kann man ja was machen, das wäre schön.

MfG
Claire_Kyle

![Hausbezeichnung Garage](https://user-images.githubusercontent.com/76182029/102536664-37388100-40aa-11eb-97f6-5f3c9473a996.jpg)

![Garage](https://user-images.githubusercontent.com/76182029/102536673-3acc0800-40aa-11eb-8a90-5e89da9399de.jpg)

![Garagenauffahrt](https://user-images.githubusercontent.com/76182029/102536679-3d2e6200-40aa-11eb-834c-45047f9ed479.jpg)

**Comment by DonVitoDiangelo** [comment]
abgelehnt
