### ISSUE TITLE
Naturausbeuter keine Anzeige

### ISSUE THREAD

**Issue by powerswissi** [mexyn/statev_v2_issues#852]
**Character Name**

Roger Thickle

**Auftrittszeitpunkt (Datum / Uhrzeit)**

17.12.2020 23 Uhr

**Beobachtetes Verhalten**

Bei 60% erscheint nun dieses Fenster. Keine Anziege oder ähnliches
![unknown](https://user-images.githubusercontent.com/70152806/102549657-c5b5fe00-40bc-11eb-826f-1e4eb283b1d0.png)

**Erwartetes Verhalten**

Keine Ahnung ob das gewollt ist oder nicht.. Aber sollte da nich 60% stufe stehen und 10% doppelter Ertrag

**Schritte um den Fehler nachvollziehen zu können**

Leveln auf Stufe 60%
Angucken :-)

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

Siehe oben

**Comment by DrColgate** [comment]
weitere erfahrung gibt es nicht mehr. ist das beabsichtigt?

**Comment by Statev-Bonsai** [comment]
Da steht nix mehr, also nicht mal die aktuelle Stufe.. Also ist es ein Bug!

**Comment by its4l3x** [comment]
Immer noch beständig?

**Comment by powerswissi** [comment]
Negativ.. Wurde ja mit einem Patch vor ca 5 Wochen behoben

**Comment by its4l3x** [comment]
Easy. Schließe den Eintrag wieder.
