### ISSUE TITLE
Gießkannen verschwinden

### ISSUE THREAD

**Issue by No1likeyou** [mexyn/statev_v2_issues#853]
**Character Name**

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Beobachtetes Verhalten**
Ich hatte drei unbefüllte Gießkannen im Inventar. Nachdem ich eine mit Wasser gefüllt habe, sind zwei Gießkannen aus meinem Inventar verschwunden.

**Erwartetes Verhalten**
Im Inventar hätte ich eine gefüllte Gießkanne und zwei leere erwartet.

**Schritte um den Fehler nachvollziehen zu können**
1. Drei Gießkannen kaufen
2. Zur Wasserstelle gehen und die erste Gießkanne mit Wasser befüllen
3. Inventar öffnen und nachschauen, ob Gießkannen weg sind

**Comment by DonVitoDiangelo** [comment]
Immer nur eine nutzen ;)
