### ISSUE TITLE
StateCom nach einparken nicht mehr schließbar

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#855]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
16.12.2020 21:30

**Beobachtetes Verhalten**
Ich hatte das StateCom offen. Währendessen wurde das Fahrzeug in die PD Garage eingeparkt. Daraufhin war das StateCom nicht mehr schließbar, und es bedurfte eines Game Restarts um weiter machen zu können, da das StateCom nicht wegging und die Sicht so blockierte.

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**
StateCom im PD Fahrzeug offen --> Fahrzeug einparken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/B5njvFlWXBM

**Comment by its4l3x** [comment]
Fixed next Update
