### ISSUE TITLE
Einzelne Produktion immer Erfolg

### ISSUE THREAD

**Issue by ShauniKT** [mexyn/statev_v2_issues#856]
**Character Name**

Shauni Teller

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Mit neuem Skillsystem

**Beobachtetes Verhalten**

Wenn man eine Produktion startet und nur eine Produktion auswählt, kommt nach meiner Beobachtung auch immer eine Erfolgreiche Produktion raus und geht nie kaputt. Beobachtete Firma: Mühle
Vielleicht ist es auch nur ein Zufall, allerdings wollte ich Fragen, ob des gewollt ist, da man ja zb. beim Diamanten schleifen auch definitiv immer aus einem Rohdiamant einen Geschliffenen bekommt, solange man sie einzeln schleift. 
Oder in meinem Fall: wenn ich 20 Perlen zu staub mache, geht immer etwas kaputt. Bei einzelnen Produktionen, welche andere Angestellte in der Mühle durchgeführt haben allerdings ging nie etwas kaputt.
Vielleicht ist dies auch nur mein Empfinden. Evtl. mal kontrollieren.

**Erwartetes Verhalten**

Auch bei einzelnen Produktionen sollte etwas kaputt gehen

**Schritte um den Fehler nachvollziehen zu können**

mit gleichen Skillvorraussetzungen eine große Produktion anwerfen und dann mehrere einzelne. bei den einzelnen sollte es keinen Verlust geben.

**Comment by Statev-Bonsai** [comment]
Das ist definitiv zufall...
Wäre schön wenn alle Edelsteine heile bleiben wenn man sie einzeln schleift..

**Comment by Statev-Bonsai** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/70241137/102699106-94673a80-4242-11eb-9c3e-31c5c99cd685.jpg)

**Comment by Statev-Bonsai** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/70241137/102699366-6be04000-4244-11eb-97b3-e4237d78ea83.jpg)

**Comment by ShauniKT** [comment]
OK gut zu wissen. dann ist es in dem falle nur Zufall oder Glück.
