### ISSUE TITLE
Tippfehler Geldautomat Konto nicht gedeckt

### ISSUE THREAD

**Issue by ZirbelR** [mexyn/statev_v2_issues#859]
**Character Name**
Richie_Zirbel

**Auftrittszeitpunkt (Datum / Uhrzeit)**
20.12.2020 14:05
**Beobachtetes Verhalten**
Tippfehler bei der Fehlermeldung wenn das Konto nicht ausreichend für eine Abhebung gedeckt ist.

**Erwartetes Verhalten**
Korrekte Rechtschreibung

**Schritte um den Fehler nachvollziehen zu können**
Versuchen Geld von einem nicht gedeckten Konto abzuheben

**Optional: Video / Bilder des Fehlers**

![image](https://user-images.githubusercontent.com/70246255/102714101-c8873d80-42cc-11eb-88a9-34a8596b97ec.png)

**Comment by Kalumel** [comment]
👶🏼

**Comment by its4l3x** [comment]
Haha :D

Fixed. next update ;)
