### ISSUE TITLE
Telefonanimation 

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#86]
**Zeitpunkt (Datum / Uhrzeit)**
Jederzeit

**Beobachtetes Verhalten**
Telefonanimation wird nicht korrekt beendet

**Erwartetes Verhalten**
Animation sollte beendet werden.

**Schritte um den Fehler nachvollziehen zu können**
Wen anrufen der nicht erreichbar ist, dann Handy wegpacken.

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/e0417cd9a4f4b30d27784ecedf055bed

**Comment by its4l3x** [comment]
Dahinter steckt ein Timeout welcher Notwendig war, um die Anim richtig zu triggern. Musst einfach nur 2 Sekunden länger warten :D

**Comment by Kalumel** [comment]
Oke
