### ISSUE TITLE
Mülleimer

### ISSUE THREAD

**Issue by Python-72** [mexyn/statev_v2_issues#860]
**Sam Wattson**

**19.12.2020 20.15**

**Fehlende Mülltonne im Whitelist Wartebereich**

**Könnte man dort eine kleine Mülltonne hinzufügen**

**Bei längeren Aufenthalt wird das Inventar recht voll und man kann nichts entfernen**

****

****

**Comment by DonVitoDiangelo** [comment]
Wir werden dort keine Tonne hinein stellen. Die Spieler können die Whitelister diesbezüglich im RP ansprechen.

**Comment by Python-72** [comment]
ok
