### ISSUE TITLE
Probleme beim ordentlichen Entmuten IC 

### ISSUE THREAD

**Issue by glb11** [mexyn/statev_v2_issues#862]
**Character Name**
Jens_Summer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
20.12.2020 Ab nach den Restart (aber auch schon mal davor (Siehe Anmerkungen))

**Beobachtetes Verhalten, Ablauf der Ungereimtheiten**

Das das Voice System teilweise rum spinnt und mann nicht mehr ordentlich reden kann: 

_Solche Voicefehler hatte ich schon öfters, kann aber dort nicht mehr sagen wie es dazu kamm_ 

- tritt meist erst nach langer Laufzeit (ca 3/4/5h+) auf 
- und da erst nach einem gewollten oder ungewollter Resart/Gamecrash auf

**So war der Ablauf heute:**

- 10/15 min davor ein Resart gemacht  weil ich Microruckler hatte
- Das Mikrofon war gemutet --> Über Stunden weil alleine gewesen

- mann wird nicht mehr vollständig in Voice gezogen (Nach dem Crash/Resart)
       - ich bin aus den Willkommenschannel gezogen wurden
       - konnte aber nicht IC sprechen, (war immer noch gemutet (Laut anzeige)) 
       - F5 hat nichts gebracht, 
       - das Microfon manuell im TS unmuten war auch nicht möglich  
 
- TS neugestartet  --> F5 da kam der Fehler: nicht auf dem richtigen Teamspeak (obwohl im Willkommenschannel) 2x-3x probiert 
        --> kein Erfolg

- TS und Game neugesartet ---> dann ohne Probleme ins Voice connected 

**Erwartetes Verhalten**
Das das Voice ordentlich funktioniert und dass man beim joinen korrekt entmutet wird 

**Anmerkungen**
Sie oben  (Der Fehler tritt mal auf mal nicht)  
Ich kenne Solche Fehler erst, Zeit dem das Voiceupdate kam wo der Mikrophonestratus immer wie im TS gesetzt wird.  Und nicht mehr so wie früher wo mann das mic 1x muten und entmuten musste das es ordentlich Funktioniert (Wenn es gemutet war) 

**Optional: Video / Bilder des Fehlers**
kein Bild/Video vorhanden weil nicht daran gedacht und es war zu kurz um irgendwass zu sehen

**Comment by glb11** [comment]
Ich hatte das Problem die Tage noch einmal.  Das war direkt nach dem Restart um 18.00 normal geladen keine Symbole auf der Karte gesehen aber Autos rum stehen auf der Map normal --> also keine 2. Dimension --> Game geschlossen und dann gleich wieder gestartet --> karte dann wieder alles top --> aber ich wurde nicht richtig entmuttet (F5 ging nicht/kein Erfolg) --> ging auch erst nach einem Resart des TS wieder zu sprechen IC

**Comment by its4l3x** [comment]
Ist bekannt. Es wird an einer Lösung gearbeitet.
