### ISSUE TITLE
Brands aus Import bei Herstellung gehen des weiteren kaputt

### ISSUE THREAD

**Issue by LiljaMorningstar** [mexyn/statev_v2_issues#864]
Lilja Morningstar

Lilja Morningstar

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Wahrscheinlich desweiteren immer möglich 

**Beobachtetes Verhalten**

Beim herstellen einer Ray Ban Cumshot für Frauen ist erneut ein Brand kaputt gegangen
**Erwartetes Verhalten**

Sollte dieser fehler nicht behoben werden da Brands Preis intensiv sind

**Schritte um den Fehler nachvollziehen zu können**

Einfache Produktion in der Goldschmiede von 2 Ray Ban Brillen wovon dann allerdings eine kaputt ging

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![image](https://user-images.githubusercontent.com/76446293/102803247-43795280-43b8-11eb-87be-db813b779253.png)

**Comment by DonVitoDiangelo** [comment]
Korrekt, Produktion leveln. :)
