### ISSUE TITLE
Sitzmöglichkeiten benutzbar machen Bennys

### ISSUE THREAD

**Issue by ShauniKT** [mexyn/statev_v2_issues#866]
**Character Name**

Shauni Teller

**Auftrittszeitpunkt (Datum / Uhrzeit)**

**Erwartetes Verhalten**

Im Oberen Bereich von Bennys sind ein Sofa, ein Sessel, ein Stuhl und ein Sitzkissen, welche wir gerne mit Interaktionen besetzt haben möchten. Zusätzlich befindet sich dort auch ein Sportgerät, welches evtl. auch nutzbar gemacht werden könnte, sowie anderer Krimskrams wie das Schlagzeug (nur wenn es möglich ist).

**Optional: Video / Bilder**

[https://puu.sh/GZXhq/d89e6ae598.jpg](url)

**Comment by DrGrizzlY17** [comment]
Der Schwarze Stuhl muss weiterhin per Animation bespielt werden

**Comment by ShauniKT** [comment]
kann er nicht durch einen anderen Stuhl notfalls ersetzt werden?
