### ISSUE TITLE
Doppelte PLZ auf Karten

### ISSUE THREAD

**Issue by Knippsa** [mexyn/statev_v2_issues#867]
Kalle Knutsen

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.12.2020 18:30

**Beobachtetes Verhalten**
Es gibt einige doppelte PLZ auf der Karte / Einmal bei dem Morningwood 24/7 und dann noch Beim Movie-Park südöstlich vom Lifeinvader
5152, 5153 sind doppelt ggf. noch weitere

**Erwartetes Verhalten**
Glaube die beim 24/7 müssten 5172 und 5173 sein

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
Karte auf, Augen ebenso :)

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Wird so bleibe, ist eine externe Source.
