### ISSUE TITLE
Fehler beim Tuning Spezialaufkleber (Fahrzeugfolierung) Karin Futo

### ISSUE THREAD

**Issue by ZirbelR** [mexyn/statev_v2_issues#869]
**Character Name**
Richie Zirbel

**Auftrittszeitpunkt (Datum / Uhrzeit)**
22.12.2020 21:00

**Beobachtetes Verhalten**
Ändert man im Tuningmenü die Folierung vom Karin Futo, so ist bei keiner Auswahlmöglichkeit eine Veränderung am Fahrzeug festzustellen, sprich man sieht keine Vorschau. Ob sich die Folie ändert wenn man den Tuningvorgang startet und abschließt wurde nicht getestet.

**Erwartetes Verhalten**
Folie ändert sich.

**Schritte um den Fehler nachvollziehen zu können**
Futo in die Werkstatt fahren und Tuningmenü öffnen. Punkt "Spezialaufkleber/1" verändern.

**Optional: Video / Bilder des Fehlers**
![image](https://user-images.githubusercontent.com/70246255/102931238-4c445400-449e-11eb-93c4-4d8275335395.png)

**Comment by ZirbelR** [comment]
evtl Duplicate #850 , mal überprüfen ob das der selbe fehler (alt:v issue) ist.

**Comment by JulianMa** [comment]
Duplicate von #850
