### ISSUE TITLE
Beim Taueranzug bugt die Kleidung durch

### ISSUE THREAD

**Issue by Frommser9** [mexyn/statev_v2_issues#87]
**Norman_Frommer**

Norman_Frommser

**Zeitpunkt (Datum / Uhrzeit)**
26. Aug. um 17:59 Uhr

**Beobachtetes Verhalten**
Beim anziehe des Taucheranzuges bugt ein weißes Hemd durch

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**
Taucheranzug anziehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://prnt.sc/u6d48z

**Comment by DonVitoDiangelo** [comment]
Japp, ist leider normal, wenn er die Flasche absetzt. Sollst du auch nur im Wasser tragen.
