### ISSUE TITLE
Autorampe nicht mehr nutzbar 

### ISSUE THREAD

**Issue by Schnarch** [mexyn/statev_v2_issues#870]
Thomas_Schnarch

Thomas_Schnarch und weitere

**Beobachtetes Verhalten**
Fahrzeuge verschwinden in der Rampe oder auf der Rampe oder gehen kaputt nach dem man nicht hinschaut. 

**Erwartetes Verhalten**
Das Fahrzeug sollte wie auf Statev darauf stehen können

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/bd32d2ad0f0ff9d72cb0054db7aace52
https://gyazo.com/f20ccdd5f98f463061688863eac3a81b

**Comment by JulianMa** [comment]
Steht die rampe immer da, oder wurde die von euch platziert?

**Comment by Schnarch** [comment]
Die wurde von uns platziert

**Comment by epichalt** [comment]
Das hat vlt nix mit der Rampe direkt zu tun, sondern liegt daran, dass Autos sich irgendwie etwas quer stellen, wenn man nicht hinschaut - obwohl man gerade geparkt hat. Aber irgendwie auch nicht immer. Habe da noch kein Muster feststellen können. 
Das würde jedenfalls Screenshot 1 erklären

**Comment by Schnarch** [comment]
Gute Frage. Vorher auf State funktionierte es immer. Da konnte man sich auch schlafen legen und der LKW war darauf. Jetzt hat man teilweise ein komplett zerstörtes auto :D

**Comment by JulianMa** [comment]
Wir werden das nicht beheben.
Die selbst platzierten Objekte werden erst nach den Autos rein gestreamed, was unweigerlich zu solchen Fehlern führt. Da können wir leider nichts machen.

**Comment by Schnarch** [comment]
top! danke..

**Comment by Schnarch** [comment]
Schönes fest :)

**Comment by its4l3x** [comment]
Danke! :) Gleichfalls.

Schließe das Ticket somit wieder.
