### ISSUE TITLE
Antrag Garage / Entfernung eines Objektes beim Haus.

### ISSUE THREAD

**Issue by MisterGarry** [mexyn/statev_v2_issues#871]
**Brain Garry und weitere**

Entfernung der Lost Flagge die an Haus hängt. Die Flagge hat keine Kollision und könnte somit einfach entfernt werden
Sowie Antrag auf Garage, ob Möglichkeit besteht die Garage gegenüber dafür nutzbar zu machen.
Das Haus besitzt auch ein Optisches Carport. 

Adresse des Hauses:
SandyShores1 // Seaview Road 1

Bilder des Hauses sowie Lostflagge

![20201107134517_1](https://user-images.githubusercontent.com/76521332/102996243-08476280-4523-11eb-987f-1ce772d1917a.jpg)
![20201115181507_1](https://user-images.githubusercontent.com/76521332/102996249-0aa9bc80-4523-11eb-9079-dcd6e61ceb22.jpg)

PS die Bilder sind vor V2 entstanden noch mit NVE

**Comment by DonVitoDiangelo** [comment]
Flagge weg, Garage nein
