### ISSUE TITLE
Reminder Hotel AkiPillboxHillRew_Flat_5

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#872]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit 21.11.2020 - 11:04

**Beobachtetes Verhalten**
**_Flat_7_1 fehlt imm Tablet.
Grizzly hatte sich das aufgeschrieben, wollte es nochmal hier als Reminder rein setzen.

**Erwartetes Verhalten**
Alle 40 Zimmer im welche an der Tür sind, auch im Tablet vorzufinden

**Schritte um den Fehler nachvollziehen zu können**
Ins Hotel Einladen.
Zimmer Tür mit Tablet vergleichen.
_7_1 fehlt

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Damaliger Report:
https://github.com/mexyn/statev_v2_issues/issues/294

**Comment by DrGrizzlY17** [comment]
Im Code ist die Wohnung vorhanden. Ich guck da nochmal genauer drüber nach den Festtagen...

**Comment by DrGrizzlY17** [comment]
@its4l3x bitte mal DB checken... AkiPillboxHillRew_Flat_7_1 ist im Code vorhanden, wir dem Hotel AkiPillboxHillRew_Flat_5 aber nicht zugeschrieben... alle anderen schon also AkiPillboxHillRew_Flat_7_2, AkiPillboxHillRew_Flat_7_3, ....

**Comment by its4l3x** [comment]
Korrekt, dass wir derzeit der AkiPillboxHillRew_Flat_6 zugeschrieben. Ich ändere das mal ab, ist mit dem nächsten Restart dann auch  richtig.

**Comment by its4l3x** [comment]
Ist abgeändert. :)

**Comment by DrGrizzlY17** [comment]
@its4l3x KUSS
