### ISSUE TITLE
[Statenet] Import/Export aktualisiert sich nach Gebot öfters nicht selbständig

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#873]
Das ist mir nun schon öfters aufgefallen, man bietet auf was und es wird erst nach dem aktualisieren des Tablets angezeigt.
Dieses mal habe ich ein Beweisfoto gemacht ;D
Zudem läuft auch manchmal die Auktionszeit auf 0.00min runter ohne das die Auktion verschwindet, das Statenet hat öfters diese hänger.

Hier auf dem Bild sieht man es, ich habe erfolgreich auf die 8 Bergkristalle geboten aber das Gebot als HÖCHSTBIETENDER wurde nicht angezeigt, erst nach aktualisieren des Tablets.
Grade wenn man in den letzten Sekunden bietet ist dieses Problem sehr gravierend, weil man sieht dann auch nicht wenn man überboten wird!

![tablett](https://user-images.githubusercontent.com/70241137/102999565-83ac1280-4529-11eb-9823-bbccea2be408.jpg)

**Comment by ShauniKT** [comment]
Kann ich so bestätigen. Gern wirft er auch mal aus, dass ein Fehler aufgetreten sei beim bieten. Durch das Aktualisieren ändert sich dann auch gern mal die Firma, womit man Geboten hat, was mir IC ne HK Strafe eingebracht hat. Daher definitiv mal nachprüfen und korrigieren, bevor es noch weiteren Leuten passiert.

**Comment by Statev-Bonsai** [comment]
Ich hole es mal aus der Versenkung hoch, das Problem ist wirklich sehr sehr nervig.. ;D

**Comment by MarcelMuerto** [comment]
@Statev-Bonsai 
Aktuell konnte ich dieses Verhalten nicht reproduzieren.

Werde es aber weiterhin versuchen.
