### ISSUE TITLE
Stockade abschleppen fehlerhaft

### ISSUE THREAD

**Issue by ShauniKT** [mexyn/statev_v2_issues#874]
**Character Name**
Shauni Teller

**Auftrittszeitpunkt (Datum / Uhrzeit)**

23.12.2020 / 15.50 Uhr

**Beobachtetes Verhalten**

Siehe Bild

**Erwartetes Verhalten**

Entweder liegt der Stockade richtig auf dem Abschlepper oder wird wie auch Rettungswagen etc fürs Abschleppen gesperrt ( Hat immerhin selbe länge wie der RTW, welcher allerdings nicht abgeschleppt werden kann, weil geblockt)

**Schritte um den Fehler nachvollziehen zu können**

Stockade auf Abschlepper aufladen

**Optional: Video / Bilder des Fehlers**

https://puu.sh/H0hrx/3384568f8c.png
https://puu.sh/H0hrn/1d8b212da4.png

**Comment by DonVitoDiangelo** [comment]
Der ist eh auf der Blacklist für den TowTruck. repairkit und Abmarsch. Fixed next update
