### ISSUE TITLE
Werkstatt Crash beim Rechnung ausstellen

### ISSUE THREAD

**Issue by ZirbelR** [mexyn/statev_v2_issues#876]
**Character Name**
Richie_Zirbel

**Auftrittszeitpunkt (Datum / Uhrzeit)**
23.12.2020 20:05

**Beobachtetes Verhalten**
Wenn ich versuche mir selbst eine Rechnung in der Werkstatt auszustellen Crasht der Arbeitspunkt. Hierbei wird zwar der Mauszeiger eingeblendet aber keine Rechnung angezeigt.

**Erwartetes Verhalten**
Rechnung wird angezeigt.

**Schritte um den Fehler nachvollziehen zu können**
Unbekannt, tritt nicht jedes mal auf. Tritt sowohl bei Tunings als auch Reparaturen auf. (Gestern 22.12.2020 gegen 22:30 an einem Futo beim Tuning(Heckspoiler&Scheibentöung), heute an einem Buffalo, Reparatur). Grundsätzlich: Rechnung an einen selbst ausstellen (Mechaniker ist gleichzeitig Kunde).

**Comment by JulianMa** [comment]
ich glaube das hatte ich auch schonmal.
Ich schau mir das an

**Comment by KarlKreislauf** [comment]
ich glaub es liegt am Cursor wenn man den Preis eingibt , wenn der Cursor noch Blinkt Crasht es meist , es hilft einfach ir wo ins Feld zu klicken( so das da nix mehr Blinkt ) und dann erst die Rechnung aus zu stellen. das Problem hatten wir damals schon mal. 
LG

**Comment by DonVitoDiangelo** [comment]
Ist der Fehler noch existent oder hat sich das gelegt?

**Comment by ZirbelR** [comment]
Ist immer wieder vorgekommen solang ich die Werkstatt hatte, bin dort aber seit mittlerweile 2 Monaten oder so raus.. Bennys (Shauni) und Horizons (Dean Gallagher) hatten da ähnliche Probleme gemeldet wenn ich das noch richtig im Kopf habe.

**Comment by DonVitoDiangelo** [comment]
Alles klar. Ja das alte Ticket wurde geschlossen. Dieses werde ich auch schließen. Wenn der Fehler erneut auftreten sollte,, einfach neu erstellen.
