### ISSUE TITLE
Random Spawnende Autos und Emperor rutscht von Flatbed

### ISSUE THREAD

**Issue by ShauniKT** [mexyn/statev_v2_issues#877]
**Character Name**

Shauni Teller

**Auftrittszeitpunkt (Datum / Uhrzeit)**

24.12.2020 / 18.00 Uhr

**Beobachtetes Verhalten**

Kurz vor 18.00 Uhr parkte eine Person mit Pony vor unserem Lager, um etwas zu verkaufen. Er fuhr danach ganz normal weg. Kurze Zeit später stand an der Stelle ein Boodhi2, weil diese Person auch etwas verkaufen wollte. Auf einmal spawnte der Pony von davor direkt in den Boodhy hinein. Beides Kernschrott. Als wir den Pony weggeschleppt haben, fiel auf einmal ein Emperor auf besagten Boodhi, welcher Brannte. Dieser war allerdings vorher nicht bei uns gewesen.
Allerdings war dieser wohl auf einem Flatbed einer anderen Werkstatt (Horizon), welche sie zu ihrer bringen wollte. Beim Versuch, den Emperor aufzuladen und erneut zur anderen Werkstatt zu bringen, ist der Emperor von der Ladefläche des Flatbeds gefallen und stand auf der Straße. Dann musste er erneut aufgeladen werden, bis er dann endlich die Werkstatt erreichte.

**Erwartetes Verhalten**

Das einem keine Autos auf den Kopf fallen bzw der Emperor2 (Das Leihauto) auf dem Flatbed bleibt und nicht "runterrutscht"

**Schritte um den Fehler nachvollziehen zu können**

- Emperor2 (Leihwagen) auf Flatbed aufladen und rumfahren
- Zwecks Random spawnender Autos: bisher kein Muster erkannt

**Comment by JulianMa** [comment]
alt:V bug
ein potentieller fix dafür ist mit dem heutigen alt:V update live
