### ISSUE TITLE
Neue Taschen werden am Charakter nicht angezeigt.

### ISSUE THREAD

**Issue by Naaki6** [mexyn/statev_v2_issues#878]
**Character Name**

Owen West

**Auftrittszeitpunkt (Datum / Uhrzeit)**

25.12.2020 00:30
**Beobachtetes Verhalten**

Wenn man eine der neuen Taschen ausrüstet wird diese am Charakter nicht angezeigt solange man ein Kleidungsstück an hat.
**Erwartetes Verhalten**

Tasche sollte auch angezeigt werden wenn man einen Pullover an hat.
**Schritte um den Fehler nachvollziehen zu können**

Tasche ausrüsten. Kleidungsstück ausziehen. Tasche wird sichtbar. 
https://streamable.com/t07xty
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Enemyaa** [comment]
Die Taschen sind momentan leider nur bei standard GTA "Oberteilen" sichtbar.

**Comment by Naaki6** [comment]
Okay gut zu wissen. Danke!

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/549

**Comment by TheBroady** [comment]
Betrifft das auch die pd Uniformen?
Denn oder sind die Taschen ebenfalls nicht sichtbar solange ich im Dienst mit der Uniform rum renne
