### ISSUE TITLE
Hutladen Einkaufen

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#88]
**Zeitpunkt (Datum / Uhrzeit)**
Jeder Zeit

**Beobachtetes Verhalten**
man kann keine Caps kaufen

Fehlermeldung
Die Steuern konnten nicht berechnet werden. [TAXCB01]
Du hast nicht genug Geld.

**Erwartetes Verhalten**
man sollte sie kaufen können

**Schritte um den Fehler nachvollziehen zu können**
Kaufen

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/82a457ad0b36cd7f8c1837ec8e5f2b00

**Comment by its4l3x** [comment]
Da fehlt noch die taxConfig @eiksch

**Comment by DonVitoDiangelo** [comment]
fixed next restart
