### ISSUE TITLE
Mitarbeiter nach Serverrestart ausloggen aus der Teams übersicht

### ISSUE THREAD

**Issue by Chrinis007** [mexyn/statev_v2_issues#880]
**Character Name**
Christian Maier

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit Restart

**Beobachtetes Verhalten**
Person ist offline aber immer noch im LSMD StateCom sowie Teams Übersicht online

**Erwartetes Verhalten**
Person sollte offline sein

**Schritte um den Fehler nachvollziehen zu können**
Im Dienst sein vor dem letzten Restart der gemacht wurde aufgrund irgendwelcher kritischer Probleme; danach mit einem anderen Char ic gehen und Personen sind immer noch online angezeigt

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![grafik](https://user-images.githubusercontent.com/70342279/103112521-4c874f80-4656-11eb-85a1-368f886acb99.png)

**Comment by TheBroady** [comment]
Beim PD genau so :)

**Comment by its4l3x** [comment]
Fixed. Next StateNET Update

**Comment by Chrinis007** [comment]
Fehler besteht beim LSPD immer noch
