### ISSUE TITLE
Ausrüstungsgegenstände auf der Straße

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#881]
Meines Erachtens hatten wir dieses Problem gar nicht mehr, heute ist es mir das erste mal wieder aufgefallen, und das an mehreren Stellen!

![Screenshot_9](https://user-images.githubusercontent.com/70241137/103131788-6e0e2880-46a2-11eb-8980-e21f5992142c.jpg)

**Comment by ShauniKT** [comment]
Bestätigt. Bin gerade auch zu einer Gruppe Polizisten gefahren und die ganzen Waffen von ihnen schwebten auf der Straße.

**Comment by tastydev** [comment]
Da ist etwas durch alt:V update kaputt gegangen und wir suche noch nach der Ursache. Allerdings ist es nicht sooo schlimm, da die Gegenstände keine Kollision aktiviert haben. Sprich man kann durchlaufen/durchfahren.
