### ISSUE TITLE
Verbuggter Emperor blockiert Flatbed

### ISSUE THREAD

**Issue by ShauniKT** [mexyn/statev_v2_issues#882]
**Character Name**
Shauni Teller / Danny Ocean (Autobesitzer Emperor KZ: Satan666)

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Schon Gestern, allerdings heute erneut Aufgetreten ( 24.12. / 25.12.2020)

**Beobachtetes Verhalten**

Am gestrigen Abend fiel uns bei Bennys ein Emperor quasi "auf den Kopf", welcher auf einem Abschlepper von einer anderen Werkstatt (horizon) war und von dehnen einfach verschwand. Als wir es dann von uns wieder zur anderen Werkstatt bringen wollten, fiel es auch bei uns einfach vom Flatbed und stand random auf der Straße. Nun hatte ich gestern ein Tiket geschrieben, hies allerdings, dass es gefixt wurde mit alt:v. 
Neuer Tag neues Glück selber Emperor. Auto stand defekt an der Garage und Kd rief mich an, damit ich es abholen soll zum reparieren. Da ich vorher an der Garage schonmal war, sah ich es dort auch. Als ich dann erneut hinfuhr, um es abzuholen, spawnte es weg und landere etwas weiter weg auf der straße. Dort habe ich es auf den Flatbed aufgeladen und bekomme es nun nicht mehr runter, da die Ablade funktion nicht eingeblendet wird.

**Erwartetes Verhalten**

Dass es da bleibt, wo es soll und wieder abzuladen geht.

**Schritte um den Fehler nachvollziehen zu können**

Wahrscheinlich liegt es geziehlt an dem Emperor oder allgemein an der Leihkarre. Daher keine möglichkeit es genau nachzuvollziehen.

**Optional: Video / Bilder des Fehlers**

https://puu.sh/H0Oj2/317e8b92b1.jpg

**Comment by JulianMa** [comment]
Ich denke das hängt hiermit zusammen #890 
Ich vermute, dass es am alt:V update liegt, muss das aber erst untersuchen
