### ISSUE TITLE
Spawnpunkt auf dem Casino

### ISSUE THREAD

**Issue by meindelinho** [mexyn/statev_v2_issues#883]
**Character Name**
Josef Wolpe

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.12.20 13:32

**Beobachtetes Verhalten**
Spawne nach den Login auf dem Casino

**Erwartetes Verhalten**
Spawn beim letzten Logout

**Comment by meindelinho** [comment]
Da es ein bisschen unklar ist.
Gestern Abend im Apartment ausgeloggt -> heute früh auf dem Casion gespawnt.
Heute vormittag am Strand ausgeloggt -> wieder auf dem Casion gespawnt um 13:33

**Comment by meindelinho** [comment]
![image](https://user-images.githubusercontent.com/76588340/103135175-c3eccb80-46b6-11eb-984d-c35afcdd9f56.png)

**Comment by Chrinis007** [comment]
Ist mir auch schon oft passiert, vor 3 Tagen bei Gordon customs Gamecrash gehabt; Casino - gestern bei jeden der 2 restarts - Casino

**Comment by meindelinho** [comment]
Also mittlerweile habe ich 100% spawn auf dem Casinodach. falls es euch weiterhilft

**Comment by Xymena** [comment]
Anna_Luna hab das problem seit gestern tritt nach jedem Discconeced und Crash auf.  Es kommt der normale Ladebildschirm es wird auch der alte standort angezeigt und bin dann aber auf den Dach.  Als ob ich nach dem Login nicht zu mein alten standort teleportiert werde oder anders rum.

**Comment by Chrinis007** [comment]
Existiert immer noch

**Comment by Chrinis007** [comment]
Immer noch existent

**Comment by tastydev** [comment]
mit dem nächsten erst update gefixt deswegen label solved und das issue nicht closed
