### ISSUE TITLE
Sanchez Falsche Treibstoffklasse

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#884]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
25.12.2020

**Beobachtetes Verhalten**
Sanchez tankt Benzin, sollte aber eigentlich Diesel Tanken wenn ich mich nicht irre

**Erwartetes Verhalten**
Tankt Diesel

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Statev-Bonsai** [comment]
Das ist Falsch, tankt schon immer Benzin.. 
Hat ja keinen Dieselmotor, zudem sind Dieselmotoren bei Zweirädern eher selten angesiedelt...

**Comment by TheBroady** [comment]
Nvm hatte einen Denkfehler xD
