### ISSUE TITLE
Spawnpunkt immer Casino Dach

### ISSUE THREAD

**Issue by PsYke86** [mexyn/statev_v2_issues#887]
Jack_Napyr

Immer beim Einloggen

Nachdem ich auf LOGIN gedrückt habe, werde ich laut der MAP (Camera) zu meinem alten Standort gebracht.. an dem ich mich ausgeloggt habe.. aber dann Spawne ich doch wieder auf dem Casino Dach... 

 das ich dort spawne wo ich mich ausgeloggt hatte 

ausloggen einloggen

**Comment by Chrinis007** [comment]
#883

**Comment by its4l3x** [comment]
Duplicate.
