### ISSUE TITLE
Bänke in LS Kirche nicht interagierbar

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#888]
**Character Name** Erwin Dulach

**Auftrittszeitpunkt (Datum / Uhrzeit)** immer

**Beobachtetes Verhalten** Y funktioniert an keiner Bank im MLO der LS Kirche

**Erwartetes Verhalten** Y bietet wie bei allen anderen Sitzgelegenheiten ein Interaktionsmenü

**Schritte um den Fehler nachvollziehen zu können** 
In LS Kirche gehen -> 
An Bank stellen -> 
Y drücken -> 
? -> 
Profit

**Comment by DrGrizzlY17** [comment]
@TheOutburst Screenshot oder Video von der Kirch bitte. Die in LS das MLO sollte zu 100% funktionieren

**Comment by TheOutburst** [comment]
habs nochmal getestet, geht mittlerweile
