### ISSUE TITLE
Anrufe / SMS gehen nicht durch

### ISSUE THREAD

**Issue by Raindiax** [mexyn/statev_v2_issues#889]
**Character Name**
Marvin_Colt

**Auftrittszeitpunkt (Datum / Uhrzeit)**
seit 22.12.2020 (Uhrzeit nicht bekannt) bis heute

**Beobachtetes Verhalten**
Nach langer Pause und Umstellung von RageMP auf AltV funktioniert Telefon und Tablet nicht richtig. Bestimmte Nummern (u.A. auch Nummer der Polizei) sind nicht erreichbar obwohl diese besetzt sind. Der Kontakt ist definitiv da und auch nicht in einem Gespräch und Handy ist angeschaltet. Trotzdem kommt der "Besetzt" Rufton. Dieses Problem betrifft immer nur bestimmte Nummern. Manche Nummern sind ohne Probleme erreichbar.

Beispiel (Ich war gegenüber einer Person A, die ich nicht anrufen konnte (Person A hatte das Handy an und war nicht am telefonieren). Neben uns stand Person B, die darauf hin versucht hat Person A anzurufen. Dies klappte dann ohne Probleme. Es war also klar, dass nur ich Person A nicht anrufen konnte. (Nummer etc. war definitiv korrekt, dies wurde mehrfach überprüft (evtl. leerzeichen, Zahlendreher, etc). Person B die anwesend war berichtete jedoch von einem ähnlichem Problem, das Person B mit einem seiner Kontakte hatte.

Selbiges Problem tritt bei SMS auf. Ich schreibe die SMS über das Tablet und gebe definitiv die Korrekte Nummer ein an die ich eine SMS schreiben möchte. Mir wird diese auch angezeigt. Aber bei dem Empfänger kommt nichts an. Dies betrifft aber nochmal andere Nummern. Also als Beispiel: Ich kann Person A anrufen, sie erhält aber keine SMS von mir. Anders herum: Ich kann Person B nicht anrufen, aber sie erhält SMS von mir.

Folgendes habe ich getan um das Problem eventuell zu beheben, hat jedoch NICHT geholfen:
Telefon/Tablet ins Inventar/Fahrzeug packen und wieder zurück in den Ausrüstungsslot, Handy/Tablet neustarten, mehrere Sim Karten ausprobiert, SMS über die Homepage über das StateNET versenden. GTA und AltV bzw StateV neuinstallieren,

**Erwartetes Verhalten**
Normales funktionieren des Telefons bzw Anruffunktion und SMS Funktion.

**Schritte um den Fehler nachvollziehen zu können**
Nicht nachvollziehbar, dadurch dass es mir erst nach mehreren Tagen aufgefallen ist, da man nicht unbedingt mit einem Fehler rechnet wenn mal jemanden nicht erreicht. 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
2560x1440

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Gib mir bitte mal die Nummern, wo du denkst, dass dort ein Fehler sein könnte.

**Comment by Raindiax** [comment]
Hi, kam leider jetzt erst dazu. Ich konnte das Problem beheben. Ich habe mir schlicht und einfach ein neues Handy und ein neues Tablet gekauft. Das hat das Problem komplett beheben können. Anscheinend hat sich da irgendwas leicht verbugged.

**Comment by its4l3x** [comment]
Ok, nice. Haben außerdem das Phone sowieso reworked. Sollte generell jetzt nicht mehr vorkommen
