### ISSUE TITLE
Kletterlizenz Dude

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#89]
**Zeitpunkt (Datum / Uhrzeit)**
Jederzeit
**Beobachtetes Verhalten**
Der NPC zum Kletterlizenz austellen fehlt 

**Erwartetes Verhalten**
Er sollte da sein.

**Comment by its4l3x** [comment]
Das ist über das Public Factory Module gehandelt worden. Müssten uns das mal anschauen, wie wir das jetzt nun lösen

**Comment by its4l3x** [comment]
Müssten eine Lösung finden, von der Öffentlichen Fabrik vllt. in eine Firma exportieren und dort herstellbar machen.

**Comment by DonVitoDiangelo** [comment]
in Stadthalle als Kaufoption hinzufügen
