### ISSUE TITLE
Car Teleport Jumpscare

### ISSUE THREAD

**Issue by silas555** [mexyn/statev_v2_issues#890]
Ich hab mein Spiel grad frisch gestartet um Farmen zu gehen und plötzlich wird mein Auto als ich am PD vorbei fuhr plötzlich auf einen Abschlepper teleportiert.

https://youtu.be/g4roHsH6iaA
Stelle 2:28

**Comment by JulianMa** [comment]
wtf

**Comment by JulianMa** [comment]
Es gibt hinweise darauf, dass das durch eine Fehlerhafte Funktion von alt:V ausgelöst sein kann, das muss ich aber erstmal untersuchen.
