### ISSUE TITLE
Ammunations + Waffenfertigungen

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#891]
Ich würde mir ein bissel Liebe für die Ammunations + Waffenfertigungen wünschen, da ja nun die Langwaffen nun auch nimmer hergestellt und dadurch nicht mehr vertrieben werden können ist das Sortiment etwas mau..

Als ersten Schritt würde ich es gut finden wenn die Feuerwerksbatterien in der Waffenfertigung hergestellt und im Ammunation verkauft werden können.
Zur Zeit macht das die Fertigung und 24/7, aber der 24/7 bekommt ja in einer Tour neue Produkte!
Zudem ist da Schießpulver etc enthalten, und das hat laut Sicherheitsbestimmungen nichts in einen Kiosk dauerhaft zu suchen!

Zudem würde ich mir Schusssichere Westen für den Ammunation wünschen, egal ob sie wirklich schützen oder nur ein Optisches Item sind.
Herstellungsort sollte die Waffenfertigung sein...

Jedes Endverbrauchergeschäft hat neue Produkte on Mass bekommen, außer die Ammunations, die haben eher was gestrichen bekommen (Langwaffen), daher besteht dort Handlungsbedarf .

**Comment by DonVitoDiangelo** [comment]
Wird in der Zukunft angegangen
