### ISSUE TITLE
Tisch im Haus sowie auf der Terasse nicht nutzbar 

### ISSUE THREAD

**Issue by Annabelle-Smith** [mexyn/statev_v2_issues#892]
**Character Name**

Annabelle_Smith

**Auftrittszeitpunkt (Datum / Uhrzeit)**

seit V2 Start

**Beobachtetes Verhalten**

Tisch im Innern sowie auf der Terrasse nicht nutzbar mit Y, Ist umbau:  Luxury House Modern Design Art Grösse 3

**Erwartetes Verhalten**

mit Y sich hinsetzen

**Schritte um den Fehler nachvollziehen zu können**

Haussystem - Interior Größe 3 kaufen  Luxury House Modern Design Art und ausprobieren

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![Tisch 1](https://user-images.githubusercontent.com/74880091/103155893-df81d000-47a3-11eb-9538-b0314cdd3e9c.png)
![Tisch 2](https://user-images.githubusercontent.com/74880091/103155898-e4468400-47a3-11eb-9bdf-f6cc842ef292.png)
![Tisch Bild](https://user-images.githubusercontent.com/74880091/103155901-e7417480-47a3-11eb-9662-b328893dd56c.png)

**Comment by DonVitoDiangelo** [comment]
@DrGrizzlY17  int chairs on dev
