### ISSUE TITLE
Rechnung selbst ausstellen nicht möglich - Werkstatt

### ISSUE THREAD

**Issue by ShauniKT** [mexyn/statev_v2_issues#896]
**Character Name**

Shauni Teller

**Auftrittszeitpunkt (Datum / Uhrzeit)**

seit ca. 24.12.2020

**Beobachtetes Verhalten**

Bennys:
In der Werkstatt ist es mir nicht mehr möglich, mir selbst eine Rechnung auszustellen, wenn ich an meinem eigenen Auto oder auch ein Kundenauftrag machen möchte. Dies betrifft sowohl Lackierung, als auch Tuning/Reparatur/Felgen/,etc.
Dies ist problematisch, da es mir so nicht möglich ist Kundenaufträge abzuarbeiten, welche Ihr Auto bei uns lassen, um es fertig tunen zu lassen und es dann später abholen.
Komischerweise betrifft dieses Problem allerdings prioritär bisher nur mich in unserer Werkstatt.
Wenn ich mir selbst eine Rechnung austelle ist zwar die Maus gelockt, dass ich Unterschreiben und bestätigen könnte, als würde das Fenster aufgehen, allerdings erscheint es garnicht, weshalb nur ein Restart meines Spiels hilft, damit die Werkstatt wieder nutzbar ist, da ich in der Zeit auch diese blockiere.

**Erwartetes Verhalten**

Dass Die Rechnung angezeigt wird, ich sie Unterschreibe und die Arbeit starten kann.

**Schritte um den Fehler nachvollziehen zu können**

- Auto auf Rep/Lackierpoint stellen
- Tuning/Lackfenster öffnen, sodass der eigene Name auch im Fenster steht
- Preis einstellen und bestätigen
- Fenster zum Unterschreiben erscheint nicht

**Comment by ShauniKT** [comment]
Update: Beim Lack ist das Auto erst wieder entsperrt, wenn es einmal eingeparkt wurde (Autohaus oder sonstiger NPC, wo man nicht ins Auto muss zum einparken)

**Comment by Statev-Bonsai** [comment]
Also ich Tune/Repariere/Lackiere bei Gordon Customs immer auf eigene Rechnung und bislang hatte ich noch keine Probleme damit.. Grade vor 2 Stunden erst mehrfach gemacht...

**Comment by ShauniKT** [comment]
Wie ich schon schrieb betrifft es in der Werkstatt bisher nur mich.

**Comment by BlackyGER** [comment]
@ShauniKT Bei welchen Fahrzeug tritt dieses Problem zu erst auf?

**Comment by ShauniKT** [comment]
Ich weiß nicht, ob davor auch schon war, aber es fing an bei Xenon Lichtern an einem Police Interceptor und Felgen. Dachte allerdings, es läge am Auto, weshalb ich diesbezüglich auch einen Bugtracker verfasst hatte. Allerdings hatte ich da nicht erwähnt, dass ich Mechaniker und Kunde gleichzeitig war.
Seitdem ist mir aber bewusst aufgefallen, dass ich dies bei garkeinem Fahrzeug mehr kann.
Ob es aber nun gezielt am Interceptor lag, kann ich allerdings nicht bestätigen.
Kein anderer in unserer Werkstatt hat das Problem.

[https://github.com/mexyn/statev_v2_issues/issues/875](url)

**Comment by Dean-Gallagher** [comment]
https://github.com/mexyn/statev_v2_issues/issues/876

Zusammenhang?

**Comment by ShauniKT** [comment]
Puush.

Bei mir tritt das Problem nicht mehr auf, allerdings hat es nun seit gestern Klaus Kevin erwischt.

**Comment by its4l3x** [comment]
Ok, im Sinne von Crash vom UI wo steht das was abgestürzt ist oder es einfach gar nicht geht? Kommt ein Meldung? Iwas? :D
