### ISSUE TITLE
Bug vor der Garage

### ISSUE THREAD

**Issue by Sharox90** [mexyn/statev_v2_issues#897]
![1](https://user-images.githubusercontent.com/76650160/103170568-6e92f480-4845-11eb-8a9e-a3f6651b2e06.png)
![2](https://user-images.githubusercontent.com/76650160/103170570-6fc42180-4845-11eb-8f1f-0638ed43b0a9.png)
![3](https://user-images.githubusercontent.com/76650160/103170571-705cb800-4845-11eb-98ac-7b9c618e7fd9.png)

Name: Sascha_Bell

Ich habe vor der Garage einen Bug. Man kann dagegen fahren und er macht das auto kaputt.

**Comment by AngelMaravilla** [comment]
Das ist von der Lichterkette die darüber hängt. An den äußeren vier Ecken des Lichterkette-Objekts sind diese kleinen Dinge in etwa auf Bodenhöhe.

**Comment by DonVitoDiangelo** [comment]
so ist es
