### ISSUE TITLE
Kein Mülleimer Symbol an Hotel 

### ISSUE THREAD

**Issue by Smaty86** [mexyn/statev_v2_issues#898]
**Tim_Rock**

**Auftrittszeitpunkt Dauerhaft seitdem Wohnung gemietet wurde Anschrift: Vespucci Beach 49**

**Beobachtetes Verhalten Mülleimer zum kündigen fehlt -Vespucci Beach 49
![Wohnung_NEU](https://user-images.githubusercontent.com/76659094/103175911-0a385b00-486e-11eb-869e-976f4c6fd756.PNG**

**Schritte um den Fehler nachvollziehen zu können Bitte diese Wohnng kündigen - ich hatte schon mehrere Wohnngen alle konnten gekündigt werden, es liegt an diesem Haus... -  Vespucci Beach 49**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DrGrizzlY17** [comment]
Wann wurde die Wohnung gemietet?

**Comment by Smaty86** [comment]
Wenn ich mich richtig erinnere dann am 11.12.20

**Comment by Smaty86** [comment]
kann ich das genaue datum irgendwo nachschauen?

**Comment by DrGrizzlY17** [comment]
solved next update
