### ISSUE TITLE
Club7 fehlende Logos

### ISSUE THREAD

**Issue by M4rvinLP** [mexyn/statev_v2_issues#90]
**Character Name**
Marvin_Elpe

**Zeitpunkt (Datum / Uhrzeit)**
jederzeit

**Beobachtetes Verhalten**
Beim Club7 fehlen die Custom Logos an der Außenseite.

**Erwartetes Verhalten**
Logos vom Live Server sind zu sehen

**Schritte um den Fehler nachvollziehen zu können**
Club7 besuchen

**Optional: Video / Bilder des Fehlers**
![m5v9ow1](https://user-images.githubusercontent.com/33394632/91340464-5f893080-e7d8-11ea-96ec-720091a7e731.jpg)

**Comment by DonVitoDiangelo** [comment]
bleibt vorerst raus
