### ISSUE TITLE
Charger Medic kein Auspuff

### ISSUE THREAD

**Issue by VictorCorticera** [mexyn/statev_v2_issues#900]
Gustavo Luciano

27.12.2020

Dodge Charger von den Medics benötigt keinen Auspuff in der Produktion

Dodge Charger Medic benötigt Auspuff für die Herstellung

Maschine in Fahrzeugfertigung prüfen --> Auspuff nicht aufgeführt

<img width="750" alt="dodge charger" src="https://user-images.githubusercontent.com/28830176/103179268-7923ad00-488a-11eb-8bed-3bdb7fb532e8.PNG">

**Comment by DonVitoDiangelo** [comment]
fixed next update
