### ISSUE TITLE
Probleme beim ausparken von Fahrzeugen

### ISSUE THREAD

**Issue by Thievo** [mexyn/statev_v2_issues#901]
**Character Name**

Thievo Mcdonald
**Auftrittszeitpunkt (Datum / Uhrzeit)**

28.12.2020 12:42Uhr
**Beobachtetes Verhalten**

Beim Ausparken eines Pounders Plötzlich Rot ohne grund gestern abend eingeparkt mit weißer Ölstands anzeige
**Erwartetes Verhalten**

Selbsterklärend
**Schritte um den Fehler nachvollziehen zu können**

Ein und auspark günter anquatschen und fahrzeug ausparken
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Reproduzierbar? Welche Garage? Kommt das öfter vor oder immer?

**Comment by flogut4e** [comment]
Hallo, kann ich so bestätigen, ist mir in den letzten Wochen jetzt auch öfters passiert. Egal ob Mustang, Sandking, Packer, Phantom ... passiert aber nicht immer, komplett random will man das Fahrzeug ausparken und die Motorleuchte ist rot.

**Comment by DonVitoDiangelo** [comment]
Wies ist hier so der Stand der Dinge? Gibt es diese Probleme noch?

**Comment by Pregon** [comment]
Ja dieses Problem ist noch immer vorhanden. Bei mir ist es heute 2x mit einem Canis Bodhi an der Rockfordhills Garage passiert.

**Comment by DonVitoDiangelo** [comment]
Bitte einmal Rückmeldung geben ob sich das Problem geändert hat, nachdem man den Garagen Spawn etwas angepasst hat.

**Comment by Pregon** [comment]
Ich werde es im Verlauf der nächsten Tage beobachten und Rückmelden
