### ISSUE TITLE
Naturausbeuter Menge

### ISSUE THREAD

**Issue by Shinigaminiam** [mexyn/statev_v2_issues#902]
Falk Alers

**Auftrittszeitpunkt (Datum / Uhrzeit)**

 Pro Pumpe beim Öl

**Beobachtetes Verhalten**
 
Beim Naturausbeuter bin ich bei 66% ( http://prntscr.com/wbjnpt )
Dennoch bekomme ich von 10 Pumpen 9x 21-27 L und 1x mit 50/50 idR bis 36 L

**Erwartetes Verhalten**

Bei hohen Lernfortschritt mind 30l  pro Pumpe

**Schritte um den Fehler nachvollziehen zu können**

Pumpen an den Öl-Feldern mit hohen Lv 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Es steht doch auch da:  "Chance auf doppelten Ertrag" - das doppelte +- /// Und wenn du von gerade 6 % 1x in 10x den doppelten bekommst sei doch froh. Hier ist alles i.O.

**Comment by Shinigaminiam** [comment]
vom doppelten bin ich nicht ausgegangen da das doppelte völlig ok ist und bei mir nach ca 25 pumpen 1x auftrit, es geht mir drum das ich primär nur 21-27 l bekomme

aber ok
