### ISSUE TITLE
Tasche nicht sichtbar 

### ISSUE THREAD

**Issue by SunaNolan** [mexyn/statev_v2_issues#903]
Suna_Nolan

Seit 27.12.2020

**Beobachtetes Verhalten**
Beim anziehen von RNASUN Hoodie F verschwindet die Tasche beim Charakter. Sie ist noch nutzbar aber nicht mehr optisch sichtbar.

**Erwartetes Verhalten**
Tasche ist sichtbar

**Schritte um den Fehler nachvollziehen zu können**
Frau sein. Tasche anziehen. RNASUN Hoodie anziehen.

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/c00cee3ed997393037a3649cd05ad98e
https://gyazo.com/85c06c2d809a584bb9161c8fa1a3d06e

**Comment by jonesXYZ** [comment]
MOD Klamotten, steht im Changelog ist bekannt daher Invalid.

**Comment by ShauniKT** [comment]
Enemyaa commented 4 days ago
Die Taschen sind momentan leider nur bei standard GTA "Oberteilen" sichtbar.

**Comment by DrGrizzlY17** [comment]
> MOD Klamotten, steht im Changelog ist bekannt daher Invalid.



> Enemyaa commented 4 days ago
> Die Taschen sind momentan leider nur bei standard GTA "Oberteilen" sichtbar.

![image](https://user-images.githubusercontent.com/70150988/103231871-34a31a80-4939-11eb-9299-7639249790f3.png)
