### ISSUE TITLE
Schwarze Umhängetasche nicht sichtbar bei MD Uniform

### ISSUE THREAD

**Issue by nathanielstb** [mexyn/statev_v2_issues#904]
**Character Name**
Matze_Steiner

**Auftrittszeitpunkt (Datum / Uhrzeit)**
27.12.2020

**Beobachtetes Verhalten**
Schwarze Umhängetasche bei SP Paramedicuniform nicht sichtbar

**Erwartetes Verhalten**
Sollte sichtbar sein

**Schritte um den Fehler nachvollziehen zu können**
Medic werden, Uniform anziehen und Tasche ausrüsten

**Comment by ShauniKT** [comment]
Enemyaa (Gamedesign für Klamotten) commented 4 days ago:
Die Taschen sind momentan leider nur bei standard GTA "Oberteilen" sichtbar.

denke das ist bei MD Sachen das selbe Problem.

**Comment by DrGrizzlY17** [comment]
Von welcher Umhängetasche ist hier die Rede?
Von den neuen oder alt bestehenden?

**Comment by Enemyaa** [comment]
[](https://github.com/mexyn/statev_v2_issues/issues/878)

**Comment by Enemyaa** [comment]
[https://github.com/mexyn/statev_v2_issues/issues/878](url)

**Comment by Enemyaa** [comment]
[878](https://github.com/mexyn/statev_v2_issues/issues/
)
