### ISSUE TITLE
Ladepunkt versetzen

### ISSUE THREAD

**Issue by DylanDuncan** [mexyn/statev_v2_issues#906]
Hallo zusammen,
bitte den Ladepunkt der Firma versetzen:

💚 GioV Ankauf Lager 💚

South Rockford Drive 8
# pfGroupAllRew_100
![Ladepunkt Ankauf Lager](https://user-images.githubusercontent.com/75174723/103236453-3bd02580-4945-11eb-8ac7-17c7facf81c5.png)

Vielen Dank und noch einen schönen Abend :)

**Comment by DrGrizzlY17** [comment]
Was stimmt mit dem jetzigen Verladepunkt nicht?

**Comment by DylanDuncan** [comment]
Mit Phantom+Achse muss man, wenn man vorwärts in die Gasse fährt, hinten rechts schräg rein und dadurch das dort ein Vordach ist und die Mülltonne steht, wird das extrem knapp und man versperrt zudem noch den Punkt vom Nachbarn.
Wenn man rückwärts reinfährt, stehen Lieferanten teilweise mit ihrer Achse quer auf einer sehr stark befahrenen Straß bevor sie dann rückwärts in die Gasse fahren.
Würde man noch den Ladepunkt des Nachbarn etwas näher zu seinem Gebäude legen aber auf der selben Höhe lassen, könnten sogar beide parallel mit Phantom+Achse auf ihre Ladepunkte.
