### ISSUE TITLE
Kofferraum nicht mehr 100% Beladbar

### ISSUE THREAD

**Issue by Reverzion** [mexyn/statev_v2_issues#907]
Rever_Wirtz

Rever_Wirtz
**Auftrittszeitpunkt (Datum / Uhrzeit)**
1 Woche ca

**Beobachtetes Verhalten**
Erst ist es mir in der Mine mit nem Rucksack aufgefallen, das ich nur noch 39 von 40 kg Erz rein bekommen habe. Dann habe ich den Rucksack leer gemacht und in ein Fahrzeug gelegt. Wieder aufgezogen und konnte ohne Relog oder ähnliches wieder 40kg Erz in den selben Rucksack packen. Das ganze hat sich auf 2 von meinen Fahrzeugen verlagert. Mein Burrito und mein Hellion kann ich nur noch bis 209,8kg von 210kg bzw 349,8kg von 350kg beladen. Habe es mit Salzkristallen getestet, deswegen die Gewichtsangaben. Ich sehen aber im Kofferraum sonst kein Item oder irgend etwas, selbst die Gewichtsangabe im Inventar bei leerem Kofferraum ist 0 von x kg. 
TS Support hat auch nur die Salzkristalle gesehen in meinen Fahrzeugen und das die nicht "Voll" waren. 

**Erwartetes Verhalten**
Wenn ich ein Fahrzeug mit x kg Kofferraumvolumen habe, kann ich auch bis x kg wie vor dem "Fehler" beladen.

**Schritte um den Fehler nachvollziehen zu können**
Wie oben beschrieben handeln, keine Ahnung wodurch ich das verursacht habe.

**Comment by DonVitoDiangelo** [comment]
Das kommt durch eine Berechnung zustande, welche nach Addition der Gewichte z.B. die Nachkommastelle 30.0065494 hat und damit über dem Limit der 30 liegt. Da nimmst du dann eines weniger mit. Wir wollen ja nicht, dass die Tasche platzt. ;)
keine Prio.


https://github.com/mexyn/statev_v2_issues/issues/1148

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1295

**Comment by its4l3x** [comment]
Wie @DonVitoDiangelo schon sagte. Liegt dann weil dann ewig Lange Nachkommastellen entstehen, wie z.B. 30.0345671 ist in dem Fall größer als 30. 

Daher invalid und kein Bug. Closed
