### ISSUE TITLE
Türen im Justizgebäude/Paleto Police HQ

### ISSUE THREAD

**Issue by motioncsgo** [mexyn/statev_v2_issues#908]
**Character Name**
Marc Randall

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit Veröffentlichung der V2

**Beobachtetes Verhalten**
Im Justizgebäude und im Paleto Police HQ hat jede Tür ein eigenes Schloss, somit kann man bei einer Doppeltür sowohl die Linke als auch die Rechte Tür separat aufschließen. 

**Erwartetes Verhalten**
Die gesamte Doppeltür (Links und Rechts) sollte nur ein gemeinsames Schloss haben wie im Mission Row Police Department.

**Schritte um den Fehler nachvollziehen zu können**
Türen zwischen Mission Row PD und Justizgebäude/Paleto HQ vergleichen
![Screenshot_1](https://user-images.githubusercontent.com/74965816/103241563-e6e7db80-4953-11eb-9e9e-b7d2f2dcdf47.png

**Optional: Video / Bilder des Fehlers**
![Screenshot_1](https://user-images.githubusercontent.com/74965816/103241572-eb13f900-4953-11eb-8333-ecc9b1913c11.png)

**Comment by DonVitoDiangelo** [comment]
Nein, bleibt so
