### ISSUE TITLE
Minenarbeiter Fertigkeit Bug oder generft?

### ISSUE THREAD

**Issue by SynaX1** [mexyn/statev_v2_issues#909]
Hatte vor dem 24.12.2020 eine Fertigkeitstufe von 80% schneller abbauen ( circa 66% zum nächsten Gesamtpunkt ),
jetzt habe ich 85% Abbaugeschwindkeit ( 2ten Gesamtpunkt, 12% vom nächsten Gesamtpunkt ).
Da muss ja irgendwas nicht stimmen.

**Comment by DonVitoDiangelo** [comment]
Nein, hier gab es keine Änderung. nach der 80% kommt erst einmal 75% usw. 
Bitte beobachte noch einmal weiter, ob der Fehler wieder Auftritt.

**Comment by SynaX1** [comment]
Naja, mein Kumpel hat auch 85% Abbaugeschwindigkeit und hat 85% zum zweiten Gesamtpunkt
und ich hatte 100% vorher schon 80% gehabt.
