### ISSUE TITLE
Club 7 - DJ Pult funktioniert nicht

### ISSUE THREAD

**Issue by Valaray** [mexyn/statev_v2_issues#91]
**Character Name**
Valaray_Youth

**Zeitpunkt (Datum / Uhrzeit)**
jederzeit

**Beobachtetes Verhalten**
DJ-Pult - Menü öffnet sich nicht

**Erwartetes Verhalten**
DJ-Pult - Menü öffnet sich 

**Schritte um den Fehler nachvollziehen zu können**
an den DJ-Pult herantreten und E drücken

**Comment by its4l3x** [comment]
fixed, next update
