### ISSUE TITLE
Taco-Van

### ISSUE THREAD

**Issue by Auralein** [mexyn/statev_v2_issues#910]
Clara Young

im Wiki steht, der Taco-Van wäre ein 2-Sitzer. Im Spiel kann allerdings keine 2. Person einsteigen -> Hintertüren öffnen zeigen 2 weitere Sitzplätze hinten, die nicht besetzbar sind. Taco-Van ist also (leider) nur ein 1-Sitzer?

**Comment by DonVitoDiangelo** [comment]
https://gta.fandom.com/wiki/Taco_Van ist ein 1-Sitzer
