### ISSUE TITLE
Haus/Objekt SandyShores30 kann nicht gekauft werden

### ISSUE THREAD

**Issue by JonesMorgan2020** [mexyn/statev_v2_issues#913]
**Jones Morgan**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
immer

**Beobachtetes Verhalten**
Objekt **SandyShores30** kann nicht gekauft werden weil vermietet - Haus ist aber scheinbar noch nie verkauft worden wie ich das sehe

**Erwartetes Verhalten**
Beim Klick auf Kaufen sollte das Haus in meinen Besitz übergehen

**Schritte um den Fehler nachvollziehen zu können**
An die Tür treten und auf kaufen klicken

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/image.YmT0P
https://pic.statev.de/image/image.YmZUC

**Comment by DrGrizzlY17** [comment]
Das Haus war bereits gekauft wurden. Der Eigentümer wurde aber ausgetragen.
Support -> Verwaltung oder höher müsste sich als Besitzer eintragen und die Miete disablen
