### ISSUE TITLE
4. Voicerange Stufe wird benötigt.

### ISSUE THREAD

**Issue by 3xcu** [mexyn/statev_v2_issues#914]
Es braucht eine 4. Voicerange Stufe über ca. 32m. Zu oft ist man in hitzigen Standoffs und RP Situationen zu weit voneinander weg, aktiv näher zu gehen auf die Leute kann man aber so gut wie nie da diese entweder sofort wegrennen oder das Feuer eröffnen weil man sich nähert. RP wird massiv dadurch behindert. Das gleiche gilt für Verfolgungsjagden zu Fuß und im Auto. Aus dem Auto hat man nie die Möglichkeit den Leuten auch mal was zu zurufen und sie zum anhalten zu bewegen ohne pitten zu müssen, da das ja auch nicht sonderlich gerne gesehen ist und zu Fuß rennt man sich hinterher ohne miteinander zu reden, da man zu weit weg ist, keine Möglichkeit Schusswaffen oder Taser anzudrohen oder das RP detailreicher durch Kommunikation zu machen.

**Comment by DonVitoDiangelo** [comment]
Abgelehnt. Diese Grenze werdet ihr immer haben und eure Argumente sind zum Teil nachvollziehbar, können aber auch für eine 5,6,7 Stufe gelten. Irgendwo muss es eben eine Grenze geben. Diese Grenzen sind seit jeher gleich und diese ist auch groß genug.  Und das mit dem vom Auto zu Auto brüllen bei 200 über die Autobahn, werde ich mal nicht weiter kommentieren. Und wenn du nach genug zum pitten dran bist kannst du da auch locker etwas sagen, sodass ein anderer das hört.

**Comment by 3xcu** [comment]
Ich muss in der Tat sagen dass mich das sehr schockiert und enttäuscht. Ich sehe keinerlei Argumente die dagegen sprechen dies zu tun. Eine 4. Voicerangestufe ist auf fast allen Servern standard, und ja, man muss ja nicht sinnlos Dinge nach machen, voll und ganz richtig, aber wenn etwas woanders besser ist, dann könnte man darüber nachdenken den eigenen Server in diesem Gesichtspunkt auch zu verbessern. 
Thema Realismus "bei 200 km/h hinterher schreien": Richtig, ist unrealistisch, aber wo fängt denn im RP Realismus an und wo hört es auf? Bei schreien aus dem Auto achten wir auf Realismus, die Cops aber müssen fern ab jeder Realität spielen - dem RP zu Liebe voll verständlich, bei dem Punkt aber nicht? Auto werden repariert in 5 Minuten für 100 Dollar, vollkommen unrealistisch, aber in dem Fall dann wieder ok? Autos komplett umlackieren und tunen in 30 Minuten? Alle 10 Minuten essen und trinken müssen und in der Hosentasche immer 10 Wasserflaschen dabei haben? Tank alle 20 Minuten komplett leer? Man kann durch geschlossene Türen reden, durch geschlossene Autoscheiben? Alles vollkommen unrealistisch, aber notwendig um RP dynamisch, interessant und aktiv zu halten. Schreit man aber bei 200 km/h aus einem Auto ist es mehr als abwegig und unrealistisch? Das Gleiche gilt für die Voicerange. keine 20m kann man also rufen? Im PD Besprechungsraum hört man den Redner am Pult nicht bis ans Ende des Raumes? Auf dem PD Parkplatz kann man nicht mal über die gesamte Breite des Parkplatzes annähernd rufen? Das ist alles komplett unrealistisch, aber dann auch wieder ok? 

Ich spiele tagtäglich auf dem Server, seit Monaten stets in Situationen die RP Stränge von Bedeutung zwischen PD und Crime maßgeblich entscheiden, wo es Sekunden sind, die zwischen RDM und hochwertigem RP sind, zwischen PowerRP und es allen Recht machen, sodass alle Spaß haben, täglich zwischen Bann und positiver RP Gestalter. Natürlich gelingt dabei nie alles perfekt, aber es sollte vor Allem Leuten wie mir deutliche Unterstützung entgegen gebracht werden teamseitig, dass in solche engen Situationen immer öfter Entscheidungen und Handlungen in einem soliden Ausgang im RP enden. Diese eben beschriebene Rolle im RP von mir betrifft nicht nur mich oder die Leute direkt um mich herum. Das sind alle Crime Spieler, Gang OG's, Mafia Don's und PD Spieler. All diese Leute die tagtäglich schwere Entscheidungen im RP treffen müssen, wo man im Zweifel mit einem Bein immer im Support sein kann. 
Diese Leute spielen jeden Tag und sollten, meiner Meinung nach, bei so einer Entscheidung die maßgeblich auf das RP Einfluss nimmt, wie das Thema der Voicerange, Einfluss nehmen können, denn sie sind es die die Entscheidungen die getroffen werden bespielen müssen und damit klar kommen müssen.
Ich bin mir sehr sehr sicher, und das ist keines Falls böse gemeint, würdet ihr mal einen Monat in den täglichen Situationen sein wie jeder Crime/Cop Spieler es immer wieder ist, würde eure Entscheidung anders ausfallen. 

Falls irgendwer bis hier hin überhaupt gelesen hat, möchte ich nur sagen, dass das keineswegs als Angriff gemeint ist und ich weiß, dass meine Meinung sowieso keinen Wert und keine Gewichtung hat. Fühlt euch bitte nicht angegriffen, ich denke dass Kritik, sowohl positiv als auch negativ das aller Wichtigste ist, um sich stetig weiter zu entwickeln. Ich gehe aber eh davon aus dass das durchweg positiv aufgefasst wird und zeigt, dass es auf dem Server immer noch sehr viele Leute gibt die sich Gedanken machen um dieses Projekt, was für viele mehr als nur ein einfaches Hobby ist, voran zu bringen. Vielleicht bewegt euch das ja solche Entscheidungen von den Leuten die täglich spielen mit entscheiden zu lassen, denn nur die, die täglich damit konfrontiert werden, können das schließ endlich beurteilen.

Liebe Grüße
