### ISSUE TITLE
Police6 Liverys

### ISSUE THREAD

**Issue by GonzoMenendez** [mexyn/statev_v2_issues#915]
Die Livery des Police6 (Mustang) ändert bei jedem Spawn, und wird auch für jeden Spieler anders angezeigt.
Dabei wählt es immer Random zwischen allen verfügbaren Liverys die verfügbar sind.
In Werkstätten kann bei der Lackierei die Livery geändert und auch durchgeschaltet werden, aber auch da sieht 
jeder eine andere Livery zur selben Zeit.

**Comment by Chrinis007** [comment]
Repost; Alt:V Fehler
