### ISSUE TITLE
Police7 Fahrverhalten (Scout)

### ISSUE THREAD

**Issue by GonzoMenendez** [mexyn/statev_v2_issues#916]
Fahrzeug: Police7 (Vapid Police Scout)

Das Fahrverhalten des Police7 müsste noch dezent angepasst werden. 
Der Wagen Untersteuert sehr stark auf der Hinteren Achse, daraus resultiert das er unnatürlich
und extrem beim nutzen der Bremse (S) und der Handbremse (Space) anfängt zu Schieben
und der Wagen gänzlich außer Kontrolle gerät.
Versucht man die Untersteuerung abzufangen, drehen die Reifen nur noch durch und der Wagen schlittert 
extrem weiter.

Dadurch kommt kein natürliches Fahrgefühl aus.
Eventuell wäre es Ratsam das Fahrverhaltenl eines Streiters / Cavalcade oder ähnlichen City SUV als Vorbild zu nehmen.

**Comment by DonVitoDiangelo** [comment]
Ist ok wie er ist. Hat auch ein GTA Sport SUV Handling verpasst bekommen. Somit abgelehnt.

**Comment by MisterCopeland** [comment]
Hast du selbst mal getestet wie dieser fährt @DonVitoDiangelo ?
