### ISSUE TITLE
Unterboden Bug

### ISSUE THREAD

**Issue by Afrostatev** [mexyn/statev_v2_issues#917]
**Character Name**
 Felix_Bang

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 Ich denke seit V2

**Beobachtetes Verhalten**
 Nach Unfällen ist das KFZ des anderen Spielers kaputt und 3sek später wieder heile da er den Bug ausgenutzt hat.

**Erwartetes Verhalten**
 Nicht benutzen

**Schritte um den Fehler nachvollziehen zu können**
 Auto wird beschädigt man macht die Unterbodenbeleuchtung einmal aus und dann wieder an und das Auto ist wieder heil.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
 https://www.youtube.com/watch?v=BcUhhsAsyS8&feature=youtu.be

**Comment by jonesXYZ** [comment]
Ist die Motorkontrollleuchte dann auch weiß oder nur das aussehen?

**Comment by TheBroady** [comment]
Im Video ist zusehen, dass die Motorkontrollleuchte von Gelb auf weiß wechselt, nachdem das Unterbodenlicht umgeschaltet wurde
