### ISSUE TITLE
Pegassi Speeder kein Bild im StateNet

### ISSUE THREAD

**Issue by MisterCopeland** [mexyn/statev_v2_issues#919]
Wie im Titel beschrieben fehlt im StateNet ein Bild vom Speeder.

https://i.gyazo.com/f18e09bdc6bd4633f34c109d41ccdeef.png

**Comment by DrGrizzlY17** [comment]
![image](https://user-images.githubusercontent.com/70150988/103358023-e74bb800-4ab4-11eb-92bd-d1f0c8876464.png)

**Comment by DrGrizzlY17** [comment]
veh hash: "speeder"
unser hash: "speeder_engine_speeder_102ps"
