### ISSUE TITLE
Export Uhrzeitenanpassung

### ISSUE THREAD

**Issue by ChrisY2k** [mexyn/statev_v2_issues#921]
**Character Name**
John Vernon

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Jedesmal im Statenet unter dem Reiter Export - Beendete Auktionen

**Beobachtetes Verhalten**
Die Uhrzeiten werden in AM/PM Form angezeigt.

**Erwartetes Verhalten**
Die Uhrzeiten sollten im 24h System angezeigt werden sowie im Bereich Import.

**Schritte um den Fehler nachvollziehen zu können**
StateNet öffnen - Export - Beendete Auktionen - Uhrzeiten ansehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://i.gyazo.com/687e440a8ade9f37934970058be665f3.png

**Comment by its4l3x** [comment]
Immer noch beständig?
