### ISSUE TITLE
Neue Track Tights (Schwarze Farben)

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#923]
**Character Name**
Max Broady & Emilia Porter

**Auftrittszeitpunkt (Datum / Uhrzeit)**
29.12.2020, 22 Uhr

**Beobachtetes Verhalten**
Die neuen Hosen sind für die Frauen nicht Schwarz.
Die Hosen haben alle einen Grünstich.
Anbei ein Vergleichsbild zwischen der Herren und Damenhose

Es betrifft die:

[F] Schwarze Track Tights
[F] Track Tights, Stripes

**Erwartetes Verhalten**
Beide gleich Schwarz

**Schritte um den Fehler nachvollziehen zu können**
Beide Hosen im Klamottenladen anprobieren.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

[F] Schwarze Track Tights
[M] Schwarze Track Tights
![unknown](https://user-images.githubusercontent.com/70150887/103315473-f5062c80-4a25-11eb-8c80-8a7304722a3f.png)

[M] Schwarze Heat Track Tights
[F] Schwarze Heat Track Tights
![Screenshot_3](https://user-images.githubusercontent.com/70150887/103315625-6a71fd00-4a26-11eb-995e-82f35edcb4e1.jpg)

[F] Schwarze Track Tights, Stripes
[M] Schwarze Track Tights, Stripes
![Screenshot_4](https://user-images.githubusercontent.com/70150887/103315715-aefd9880-4a26-11eb-8b07-e4aa9c0deb4f.jpg)

**Comment by TheBroady** [comment]
Edit:
Ich habe noch weitere Kleidungstücke hinzugefügt wo die Farben nicht übereinstimmen

**Comment by Enemyaa** [comment]
@TheBroady Also ich hab die mal anprobiert und tatsächlich n ganz leichten Grünstich, aber nicht annährend so stark wie du. Hast du da Einstellungen die das noch intensiver begünstigen? Ansonsten bin ich leider nicht der Designer der Hosen, sondern GTA selbst.

**Comment by Enemyaa** [comment]
aber ich benenne die mal um. Danke für die Info!

**Comment by TheBroady** [comment]
Hier nochmal komplett ohne Filter von Reshade
![Screenshot_4](https://user-images.githubusercontent.com/70150887/103379254-59d48c00-4ae5-11eb-879d-99c1bbfcf56b.jpg)
