### ISSUE TITLE
Gemietete Wohnung kann nicht gekündigt werden / bei bestimmter Wohnung immer FallBug

### ISSUE THREAD

**Issue by NossMoriati** [mexyn/statev_v2_issues#924]
Noss_Moriati

Mit welchem Character wurde das Verhalten in-game ausgelöst/beobachtet

Noss_Moriati

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Wann exakt (Datum / Uhrzeit) ist der Fehler beobachtet worden
Allgegenwertig 

**Beobachtetes Verhalten**
ich kann meine Wohnung beim Blauen Kreis nicht Kündigen. Auch nach mehrmaligem ausloggen, oder abwarten des Servers Neustarts behebt sich dieses Problem nicht.
Adresse : Procopio Drive 1 (Siehe BIld)

Beim Rausgehen einer dieser Wohnungen fällt man immer durch den Boden.   -->

**Erwartetes Verhalten**
Das neben der Tür das Mülltonnen Icon ist damit man die Wohnung Kündigen kann.

**Schritte um den Fehler nachvollziehen zu können**
 Erläuterung auf dem Foto sichtbar. (Mülltonnen Icon) in beide Wohnungen reingehen und wieder austreten eine Wohnung lässt dich zu 100% durch die map fallen (Spawnpoint unter dem boden gesetzt)

**Optional: Video / Bilder des Fehlers**
Falls du ein Video oder Bild vom Fehler gemacht hast, dann kannst du diesen hier einfügen. Dies geht ganz einfach per Drag & Drop
![GTA fehler](https://user-images.githubusercontent.com/76772384/103342571-1e58a400-4a8a-11eb-9bc1-bf59fd96f327.jpg)

PS: Ich bitte um Kündigung dieser beiden Wohnungen.

**Comment by NossMoriati** [comment]
Beobachtetes Verhalten
Kündigung ist nicht möglich,

Beim austreten der einer dieser beiden Wohnungen fällt mann immer durch den boden spwanpoint zu niedrig. 
Erwartetes Verhalten
Mülltonnen Symbol sollte vorhanden sein. 
Das man nicht durch den boden fällt. 

Schritte um den Fehler nachvollziehen zu können
wohnung betreten und verlassen.

**Comment by Statev-Bonsai** [comment]
Tja, die wirst du auch net beim blauen Marker kündigen können... Du musst die an deiner Tür mit grünen Marker kündigen, das Hotel hat ja auch Einzelzimmer!
Das ist m.e. ersichtlich das man da selber drauf kommen müsste!

**Comment by NossMoriati** [comment]
Die Türen sind doppelbelegt sprich es gibt keinen grünen Punkt den ich anlaufen kann .

**Comment by Statev-Bonsai** [comment]
Ich habe es mal angeschaut, dein Name taucht nirgends auf...
Normalerweise müsste der in der unteren Reihe rechts stehen.
Einzelzimmer muss man immer an der grünen Tür kündigen, aber dein Name taucht an keiner Tür auf, nur an der Übersicht..eindeutig Tricky ;D

**Comment by NossMoriati** [comment]
jap irgendwas ist da faul oO.....

**Comment by DrGrizzlY17** [comment]
Fixed next Patch

**Comment by NossMoriati** [comment]
Danke das dass so schnell ging :) 
Kann die Kündigung Serverseitig erledigt werden? zahle grade 100 Doller pro Spielstunde und habe effektiv nichts weil ich die Wohnung nicht betreten kann.
