### ISSUE TITLE
skill problem

### ISSUE THREAD

**Issue by StateV2Marie** [mexyn/statev_v2_issues#926]
Hab da nen Problem jeder sagt mir was von i-was von Prozenten aber bei mir tut sich am balken gar nix dabei hät da schon einiges stehen müssen aber es bleibt dauerhaft auf 0% [https://pic.statev.de/image/Y2o5i](url)  << hier der beweiss.
hoffe man kann mir da sagen was da los is wäre nett danke. mfg: Marie Pech

**Comment by epichalt** [comment]
vielleicht hast du schon die "maximale" Punktzahl erreicht?

**Comment by Statev-Bonsai** [comment]
Ich kann dir sagen das es kein Fehler ist ;)

**Comment by DrGrizzlY17** [comment]
Hallöle Marie,

die Leiste die du da gescreenshotet hast ist der allgemeine Fortschritt für die Major Points. Wenn sich da nichts mehr bewegt, biste wohl am Maximum :)

Es gibt bei den Skills noch Details (unterm Skill steht "Klicke für Details") da sieht das ganze etwas so aus:

![image](https://user-images.githubusercontent.com/70150988/103357632-f4b47280-4ab3-11eb-829f-cb653c541df7.png)


Hier liegt also kein Fehler vor

**Comment by StateV2Marie** [comment]
ne eben nich bin nich auf max sehe sie wenn ichs auf und zu mache das der strich nen viertel voll wäre
