### ISSUE TITLE
xeon licht wird ohne tuning gespeichert

### ISSUE THREAD

**Issue by halloheyleon** [mexyn/statev_v2_issues#927]
Grezzer_Morgan

29.12.2020 ca. 2uhr
29.12.2020 ca.2uhr

**Beobachtetes Verhalten**

**Erwartetes Verhalten**

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by ChrisY2k** [comment]
Was passiert wenn das Fahrzeug ein und ausparkst?

**Comment by DrGrizzlY17** [comment]
Das ist denn überhaupt das Problem :D

**Comment by JulianMa** [comment]
ich schließe das, bis du hier was vernünftiges rein geschrieben hast.

**Comment by ShauniKT** [comment]
_Ich beschreibe den Fehler mal genauer, da ich denke zu wissen was gemeint ist:_

**Wann der Fehler passiert:**
Seit V2 Release

**Beobachtetes Verhalten**
Wenn man Xenonlichter beim tuning auswählt und das fenster schließt ohne zu tunen, bleiben die xenons gefärbt, allerdings nur, bis zum restart oder man das auto ein- und ausparkt.

**Erwartetes Verhalten**
Erwartet wird, dass sich auch die Xenon resetten auf das, was davor war wie beim restlichen Tuning

**Schritte um den Fehler nachvollziehen zu können**
- Fahrzeug auf Tuningpoint stellen
- Xenonlichter auswählen und Farbe verändern
- Tuningfenster mit dem schließen Button schließen
- Xenon bleibt angezeigt trotz fehlendem Tuning
- Resett durch ein - und ausparken sowie Server restart, ansonsten muss es erneut per tuning Fenster auf Serie gestellt werden und wieder einfach nur geschlossen, damit es weg ist.

**Hab gerne beim Übersetzen geholfen :D**
