### ISSUE TITLE
Falsche Tankstellen Anzeige

### ISSUE THREAD

**Issue by Falk-Alers** [mexyn/statev_v2_issues#928]
Falk Alers

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Beim Tanken, Tankstelle Sandy (812)

**Beobachtetes Verhalten**

Das Auto hat einen 70L Tank, die anzeige der Tankstelle war / ist falsch (siehe bild http://prntscr.com/wd5xpp )
getank wurden gerade mal 20L in das fahrzeug

**Erwartetes Verhalten**

richtige anzeige

**Schritte um den Fehler nachvollziehen zu können**

tanken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by KingMarcel** [comment]
https://github.com/mexyn/statev_v2_issues/issues/1001
