### ISSUE TITLE
Durch Farmanimation kein Skillvorteil

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#929]
**Character Name**
Dean Gallagher

**Beobachtetes Verhalten**
Duckanimation beim Farmen geht über die Abbauzeit hinaus, Animation bleibt solang bis man umgeladen hat, nach beendigung der Animation muss man nochmal eine sekunde oder zwei warten bis man laufen kann. Durch alles zusammen hat man keinen Zeitvorteil mehr den man duch den Skill bekommt. Ich hab den Skill auf 72%

**Erwartetes Verhalten**
Wenn der Fortschrittsbalken voll ist, das man da wieder steht und weiter gehen kann und nicht das die Animation da erst anfängt zu ende zu gehen.

**Schritte um den Fehler nachvollziehen zu können**
Auf Feld gehen, in meinen Fall Ocker und anfangen zu arbeiten.

**Optional: Video / Bilder des Fehlers**
https://youtu.be/a7W5ncSZ1K4

**Comment by DonVitoDiangelo** [comment]
https://github.com/mexyn/statev_v2_issues/issues/768

Das ist korrekt so wie es ist. Die reine Farmzeit (Progressbar) wird hier berechnet.
Die Auslaufanimation, also dieses aufstehen ist immer fest, immer gleich. Das gehört zu diesem Scenario mit dazu und ist halt das ausfaden. Das ist identisch, immer.
Aber Ihr spart zu 100% Euro Zeit aufs Farming, also in der Progressbar selbst.

1. Progressbar startet, hockt sich hin. (Zeitersparnis ist eingerechnet)
2. Progressbar endet, Scenario Ende wird eingeleitet (immer feste Zeit)

Ich habe das selbst via Stopp Uhr getestet und das passt soweit.
