### ISSUE TITLE
Club 7 Geldautomat fehlt

### ISSUE THREAD

**Issue by Valaray** [mexyn/statev_v2_issues#93]
**Character Name**
Valaray_Youth

**Zeitpunkt (Datum / Uhrzeit)**
jederzeit

**Beobachtetes Verhalten**
kein Geldautomat im ganzen Club

**Erwartetes Verhalten**
mindestens ein Geldautomat im Club 

**Schritte um den Fehler nachvollziehen zu können**
in den Club herein gehen, überall umsehen.

**Comment by DrGrizzlY17** [comment]
@DonVitoDiangelo maybe weils über json in dim -1 definiert wurde, gleiche gilt wahrscheinlich für #92 #91

**Comment by its4l3x** [comment]
Der DJ-Punkt ist unabhängig von dem ATM oder iwelchen anderen Props/Objekten @DrGrizzlY17
