### ISSUE TITLE
Personen sitzen "in der Luft" anstatt auf dem Stuhl

### ISSUE THREAD

**Issue by No1likeyou** [mexyn/statev_v2_issues#930]
**Character Name**
ben_Stark

**Auftrittszeitpunkt (Datum / Uhrzeit)**
30.12.2020, 20.10 Uhr

**Beobachtetes Verhalten**
Die Personen möchten sich mit Y hinsetzen und sitzen leider in der Luft.

**Erwartetes Verhalten**
Personen nutzen die Stühle zum sitzen

**Schritte um den Fehler nachvollziehen zu können**
Zum Stuhl gehen und Y drücken.

**Optional: Video / Bilder des Fehlers**

![Bug_Luftsitzen](https://user-images.githubusercontent.com/55114714/103375805-5a682500-4adb-11eb-8e59-86fec2a69cfb.png)

**Comment by its4l3x** [comment]
An diesem Module wurde seit 6 Monaten nichts mehr gemacht. Sieht sehr danach aus, nach einem altV Problem nach dem Update. Werden wir uns in näherer Zeit nochmal genauer anschauen.

**Comment by Chrinis007** [comment]
Das selbe im MD beim MRT sowie Röntgen

**Comment by DonVitoDiangelo** [comment]
Hat sich das Problem mit dem neuesten alt:V Update gelegt?

**Comment by Dean-Gallagher** [comment]
nein ist immer noch
