### ISSUE TITLE
Bewusstlos bei Öffnen des Klamottenladen Menu mit Ö

### ISSUE THREAD

**Issue by TheBroady** [mexyn/statev_v2_issues#932]
**Character Name**
Max Broady

**Auftrittszeitpunkt (Datum / Uhrzeit)**
30.12.2020, 22:30

**Beobachtetes Verhalten**
Wenn man Ö drückt und gleichzeitig das Menu des Klamottenladen öffnet, wird man bewusstlos.

**Erwartetes Verhalten**
Öhm möglichst nur eines von beiden tritt in kraft ohne Bewusstlosigkeit.

**Schritte um den Fehler nachvollziehen zu können**
Ö drücken und gleichzeitig im Klamottenladen das Menu öffnen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=CQIwXfN9vIo

**Comment by its4l3x** [comment]
😂 War ziemlich lustig anzusehen hahaha.

Da aber sowas so gut wie nie vorkommt, und wenn nur in ganz seltenen Fällen, werden wir das nicht fixen.

Da E und Ö weit auseinander liegen, ist das auch kein Problem. 
Somit ist das ganz easy vermeidbar. Ich tue im RP ja auch nicht eben beim Kleideranziehen mich eben wie eine Robbe auf den Boden werfen :D 


schließe das mal wieder :D

**Comment by TheBroady** [comment]
Es reicht allerdings auch aus wenn man im Marker liegt und um "Zeit zu sparen" einfach dann E drückt, anstatt zu warten bis der Char wieder aufgestanden ist. Hat also nicht mit der Zeitlichen Abfolge des Keypress'es zu tun.

**Comment by its4l3x** [comment]
Halte davon relativ wenig, mmn ist dann schon FailRP. Das Zeit sparren Argument ist da wenig aussagekräftig.

Appelliere da Tatsache an euch, einfach Ö zu drücken, das RP zu spielen, das du aufstehst und so weiter anstatt danach zu handeln:

"Ich drücke E hehhehe das geht schneller und ich bin schneller oben muhahaha" Weißte wie ich meine? :D

**Comment by TheBroady** [comment]
Ja klar, verstehe ich das :D

Wollte nur nicht as es falsch aufgefasst wird. Daher hab ich das nochmal kommentiert. ;)
