### ISSUE TITLE
HUD verrutscht

### ISSUE THREAD

**Issue by PsYke86** [mexyn/statev_v2_issues#934]
Jack_Napyr

**Auftrittszeitpunkt (Datum / Uhrzeit)**
31.12.20 /00:07

**Beobachtetes Verhalten**
Anzeige verrutscht

**Erwartetes Verhalten**
nicht verrutschen wenn ich TAB drücke

**Schritte um den Fehler nachvollziehen zu können**
TAB drücken / Gedrückt Halten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**

**Comment by tastydev** [comment]
#253
