### ISSUE TITLE
Fehler Mülltonnen Mirror Park

### ISSUE THREAD

**Issue by glb11** [mexyn/statev_v2_issues#935]
**Character Name**
Jens_Summer

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Schon länger kein genaues Datum bekannt (ist mir schon mehrfach aufgefallen)

**Beobachtetes Verhalten**
Die 2 oberen Mülleimer im Mirror Park haben das Selbe Inventar (Immer den selben Inhaber) 

**Erwartetes Verhalten**
2 Mülleimer = 2 Inventare

**Schritte um den Fehler nachvollziehen zu können**
Hingehen und was reinlegen und zum anderen Mülleimer gehen und es dort wieder finden

**Optional: Video / Bilder des Fehlers**
https://youtu.be/MOBpW8eVs9o

**Comment by its4l3x** [comment]
Bitte checken, du hattest einen doppelten Hash bei den Trashbins vor einem Monat hinzugefügt.

**Comment by tastydev** [comment]
fixed
