### ISSUE TITLE
Neue Summe am Konto anzeigen

### ISSUE THREAD

**Issue by Chrinis007** [mexyn/statev_v2_issues#936]
**Character Name**
Christian_Maier

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit V2

**Beobachtetes Verhalten**
Bei Einzahlung nicht einsehbar wie viel Geld anschließend auf dem Konto ist

**Erwartetes Verhalten**
Neue Summe auf dem Konto direkt anzeigen nach auswahl der Summe der Einzahlung

**Schritte um den Fehler nachvollziehen zu können**
Geld am ATM einzahlen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![grafik](https://user-images.githubusercontent.com/70342279/103396400-5ff15980-4b33-11eb-9891-0ca5981dcf4b.png)

**Comment by Statev-Bonsai** [comment]
War das nicht schon immer genauso? o.0

**Comment by its4l3x** [comment]
Bonsai hat Recht. 

Außerdem wird das nicht umgesetzt, da wir erst den Server das prüfen lassen müssen, was du eingegeben hast.

dahiner invaid und closed
