### ISSUE TITLE
LSPD Team Managment durcheinander

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#938]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
31.12 12:00

**Beobachtetes Verhalten**
ist seit ein paar Tagen durcheinander

**Erwartetes Verhalten**
Wieder nach Rängen geordnet

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/Yblsm

**Comment by its4l3x** [comment]
Korrekt, mit Absicht und gewollt. Da ihr die Lohnklasse nicht mehr sehen sollt ;) Ihr somit halt auch kein Verdacht schöpfen könnt, wer der höchste ist.

Daher invalid und closed

**Comment by JannikDatsch** [comment]
@its4l3x Könnte man das ganze nicht trotzdem irgendwie sortieren, bsp. einfach nur nach Rang und nicht nach Lohnklasse, oder nach Anfangsbuchstaben der Nachnamen oder so, weil so ist das halt einfach nur durcheinander.

**Comment by CaleighRhodes** [comment]
Da wir eh die Lohngruppen neuerdings eh nicht mehr sehen (dort steht UNSICHTBAR) wäre es trotzdem wünschenswert, die Mitarbeiter wieder nach Dienstgrad zu sortieren, da stimme ich dem Kollegen Datsch völlig zu.
Also bitte denkt mal nochmal drüber nach :/

**Comment by its4l3x** [comment]
@JannikDatsch Das System wurde so umgebaut, dass Lohnklasse == Rang ist. 

@CaleighRhodes In Absprache mit den Fraktionsleadern der Fraktionen, wo das vorgefallen ist, dass einige eurer Leute das IG anspielen und darauf auch derartig rumhaken => "Wieso hat der eine bessere LK als ich?!?!?!" und das zerstört RP. Würd' es nach mir gehen, solltet ihr die weiterhin sehen, aber wenn das nicht anders geht, dann müssen wir halt Beschränkungen einbauen.

Außerdem warum das jetzt durcheinander ist, dass ihr ja sonst immer noch wisst, wer theo. welche LK hat. Was ja jetzt nicht mehr Sinn und Zweck ist. Ihr dürft euch da gerne bei paar von euren LSPD/LSMD Kollegen bedanken.
