### ISSUE TITLE
Werbungen direkt sichtbar machen

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#939]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
31.12 12:00

**Beobachtetes Verhalten**
Wenn Werbungen (F7) ausgeschaltet sind, und man diese einschaltet, sind die Werbungen der aktuellen Range nicht zu sehen, und man muss erst raus und wieder rein laufen/fahren, um diese zu sehen.

**Erwartetes Verhalten**

Man sollte die Werbungen direkt beim einschalten sehen

**Schritte um den Fehler nachvollziehen zu können**

Werbungen ausgeschaltet haben --> in die Range einer Werbung fahren --> Werbungen (F7) einschalten

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/tpRNKUpduhQ

**Comment by its4l3x** [comment]
Korrekt, auch gewollt. Wenn du die Werbung wieder sehen möchtest dann fahr schnell 200m weg. Durch das Ausschalten der Werbung spart der Server sich ein wenig Performance für den Client, um die direkt danach wieder Anzuzeigen, muss der Server die zwischenspeichern, was sich nicht lohnen würde.

Daher gewollt und closed.
