### ISSUE TITLE
Produktionscomputer

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#94]
**Zeitpunkt (Datum / Uhrzeit)**
Immer.
**Beobachtetes Verhalten**

Ladeanzeige ist Buggy. Sie erreicht 100% obwohl die Produktion noch nicht fertig ist.  Keine 10 sec. sind abgelaufen.
https://gyazo.com/e9af05677b93a700357dfc5e39da349c
https://gyazo.com/10c6952a611526bb768ad786e7934942

**Comment by its4l3x** [comment]
Paul, sorry, aber wo ist da der Fehler? :D

**Comment by Kalumel** [comment]
Naja die Ladeanzeige ist halt Buggy. Sie erreicht 100% obwohl die Produktion noch nicht fertig ist. @its4l3x

**Comment by its4l3x** [comment]
Interessant. Liegt warscheinlich am Zeit Unterschied zwischen dir und dem Server.

**Comment by Kalumel** [comment]
Ja wohne in Uganda. @its4l3x

**Comment by r3sist3nt** [comment]
@its4l3x nein, ich habe das gestern Umgebaut. Mein commit kam um 14:30 Uhr. Laut Discord wurde der Server erst um 22:11 Uhr, neu gestartet, der Issue kam aber um 20:41 Uhr rein.
@Kalumel bitte teste das Nocheinmal nach. Falls du immernoch das gleiche Verhalten hast, dann schreibe das bitte hier rein.

**Comment by r3sist3nt** [comment]
Siehe auch #53

**Comment by r3sist3nt** [comment]
In Rücksprache mit @Kalumel bereits mit #53 behoben. Ich schließe hier.
