### ISSUE TITLE
Fundquote verschiedener Edelsteinsorten...

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#940]
Vorneweg, es geht NICHT um die Fundmengen von Edelsteinen, es geht um deren Verteilung!

Also, ich bin der Meinung das die Verteilquote der Edelsteine nicht passt, Rohdias bringen die Leute zu 80-85%.
Die anderen Edelsteinsorten außer Rubine werden kaum bis gar nicht gefunden, z.b. Musgravit..

Ich würde es gut finden wenn man die Fundquote von Diamanten/Rohdiamanten runterdreht und dafür die von Rubin/Rohrubin, Bergkristall/Roher Bergkristall, Smaragd/Roher Smaragd, Saphir/Roher Saphir und Musgravit/Roher Musgravit hochdreht.
Meiner Meinung nach werden von der Verteilung her zuviele Rohdias gefunden, der Rest kommt sehr sehr sehr schleppend rein!

Zz. gibt es durch die Flut an Rohdias schon regelrecht ein Überangebot auf der Insel, hingegen bei Smaragden,Berkristalleten etc. einen Mangel!
Bei V1 war die Verteilquote Ideal!

**Comment by Chrinis007** [comment]
Liegt auch daran dass sich die Leute nicht mehr so in die Klettermine trauen weil das MD nur noch selten Einsätze im Winter oben anfährt

**Comment by Statev-Bonsai** [comment]
Das hat mit der Klettermine rein gar nix zu tun!

**Comment by DrGrizzlY17** [comment]
> Bei V1 war die Verteilquote Ideal!

![image](https://user-images.githubusercontent.com/70150988/103424003-4808ec80-4baa-11eb-91ab-0f9cd29c6fec.png)

**Comment by Statev-Bonsai** [comment]
Meine Statistiken von Ankauf sagen aus das die Verteilung extrem verschiedenwie zu V1 ist.. ^^

**Comment by Chrinis007** [comment]
Vllt verkauft einfach nicht jeder an dich :D
