### ISSUE TITLE
Tachoanzeige auf Beifahrersitz nach Rüberrutschen

### ISSUE THREAD

**Issue by AngelMaravilla** [mexyn/statev_v2_issues#941]
**Character Name**
Angel_Maravilla

**Auftrittszeitpunkt (Datum / Uhrzeit)**
31.12.2020 / 20:22 Uhr

**Beobachtetes Verhalten**
Wenn man von der Fahrerseite eines Fahrzeugs mit **G** einsteigt und somit über den Fahrersitz auf den Beifahrersitz rüber rutscht, dann bleibt das Tacho-Overlay sichtbar. Es ist allerdings statisch und verändert sich während der Fahrt nicht.

**Erwartetes Verhalten**
Sobald man nicht mehr auf dem Fahrersitz sitzt, sollte das Overlay verschwinden. Auch wenn man zuvor über den Fahrersitz auf den Beifahrer gerutscht ist.

**Schritte um den Fehler nachvollziehen zu können**
Auf der Fahrerseite des Fahrzeugs mit **G** einsteigen, sodass man sich zunächst auf den Fahrersitz setzt und dann automatisch auf den Beifahrersitz rutscht.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Hi, kannst mir das Fahrzeug sagen, bei dem das aufgetreten ist?

**Comment by its4l3x** [comment]
fixed next update
