### ISSUE TITLE
Tuning BMW Z4

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#943]
Kein Plan ob es gewünscht ist aber beim Z4 (neues Modell seid V2) sind keinerlei Tuning Optionen vorhanden, nicht mal die farbigen Scheinwerfer / Unterbodenbeleuchtung/ Bremsen oder die Scheibentönung
Wäre Klasse wenn man dies ändern könnte ;)

**Comment by DrGrizzlY17** [comment]
Der Z4 ist ein Mod Fahrzeug, wir sind somit daran gebunden was der Mod Hersteller mitliefert.
Wir haben alles verfügbare soweit mit drinne, also mehr ist also mit dem aktuellem Mod nicht verfügbar
