### ISSUE TITLE
Anrufsliste 17.04

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#945]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.01 08:45

**Beobachtetes Verhalten**
Seit Update heute morgen erscheint in der Anrufsliste erst kurz eine vom 17.04

**Erwartetes Verhalten**
sollte nicht da sein

**Schritte um den Fehler nachvollziehen zu können**
Telefon --> Kontakte --> Anrufsliste

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://youtu.be/HNV8d0OX-S8

**Comment by Hutstaender** [comment]
fixed next update.
