### ISSUE TITLE
Lücke am Rücken bei lange Seidenhandschuhe 

### ISSUE THREAD

**Issue by ReikaNight** [mexyn/statev_v2_issues#948]
**Character Name**
Lucia_Ashton

**Auftrittszeitpunkt (Datum / Uhrzeit)**
02.01.2021 18:41

**Beobachtetes Verhalten**
Bei anziehen eines Corsagenkleid ([F] Sole Nero Corsagenkleid) und dem auswählen der "Lange Seidenhandschuhe" (egal welche Farbe) fehlt am Rücken ein teil Haut 

**Erwartetes Verhalten**
Wenn man das Kleid und die Handschuhe anzieht, das keine Lücke entsteht 

**Schritte um den Fehler nachvollziehen zu können**
[F] Sole Nero Corsagenkleid  + [F][U] Magic Corsage anziehen
Lange Seidenhandschuhe auswählen /Anziehen 

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![20210102183615_1](https://user-images.githubusercontent.com/76880216/103463390-4830f580-4d2c-11eb-8c15-a9115f68ccdd.jpg)

**Comment by Enemyaa** [comment]
Es gibt davon nicht soviele Variationen. Passend dazu wäre das Trägerkleid.
