### ISSUE TITLE
Fahrzeuge langsamer als vor dem Schnee

### ISSUE THREAD

**Issue by Daniel160982** [mexyn/statev_v2_issues#949]
**Daniel Rossi**

Daniel Rossi
**Auftrittszeitpunkt (Datum / Uhrzeit)**

02.01.2021 / 21:00
**Beobachtetes Verhalten**

Fahrzeuge langsamer als vor dem Schnee und während Schnee lag.
**Erwartetes Verhalten**

Fahrzeuge sollten ca. 10 bis 20 km/h schneller gewesen sein als jetzt.
**Schritte um den Fehler nachvollziehen zu können**

Test mit Sultan RS, Elegy Retro Custom und Kamacho gemacht
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by tastydev** [comment]
Es ist alles richtig.

**Comment by Daniel160982** [comment]
Ok vielen Dank
