### ISSUE TITLE
Gefesselter Spierler

### ISSUE THREAD

**Issue by Kalumel** [mexyn/statev_v2_issues#95]
**Beobachtetes Verhalten**
Gefesselte Spieler können keine Kleidung an oder ausziehen. (Wäre hilfreich wenn man ein Bandana o. Ä ausziehen soll)

**Erwartetes Verhalten**
Der Gangster sollte die Möglichkeit haben der Geisel nen Bandana auszuziehen.

**Comment by r3sist3nt** [comment]
Wie willst du denn den das Bandena ausziehen, wenn deine Hände gerade gefesselt sind? Das macht überhaupt keinen Sinn.
Ich weiß nicht was die anderen dazu sagen, aber wenn du einen Spieler gefesselt hast, dann musst du ihm halt die Fesseln abnehmen wenn er Kleidung ausziehen soll. Das muss im RP ausgespielt werden.

**Comment by DonVitoDiangelo** [comment]
So ist es :)
