### ISSUE TITLE
Produktionen in der Goldschmiede vertauscht (Skull Ohrringe)

### ISSUE THREAD

**Issue by miischaa** [mexyn/statev_v2_issues#950]
**Character Name**
 Heinrich Iwanow

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 03.01.2021 00:35Uhr

**Beobachtetes Verhalten**
 Die Ohrringe unterscheiden sich lediglich auf welcher Seite man sie trägt, sprich: Links, Rechts, Beidseitig, wodurch die benötigten Ressourcen ja eigentlich gleich sein sollten. Die sind jedoch vertauscht. 

 Black Skull (L) braucht Kupferbarren
 Black Skull (R) braucht Eisenbarren
 Black Skull beidseitig braucht Eisenbarren
    Bei den anderen Schwarzen Ohrringen werden Kupfer statt Eisenbarren benötigt
    
Gold Skull (L) braucht Eisenbarren
Gold Skull (R) braucht Kupferbarren
Gold Skull beidseitig braucht Kupferbarren
    Bei den anderen Goldenen Ohrringen werden Eisenbarren statt Kupferbarren benötigt

**Erwartetes Verhalten**

Oben beschrieben.

**Schritte um den Fehler nachvollziehen zu können**

In der Goldschmiede die entsprechenden Stücke suchen. Wohlgemerkt sind das die [M][Ears] in jedem Fall.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

1920x1080

**Optional: Video / Bilder des Fehlers**

https://gyazo.com/699069ccc9d1b083c4a417624bd772d8
https://gyazo.com/12252dd396b8622252559034f5fc622a

**Comment by Enemyaa** [comment]
Sollte jetzt passen!
