### ISSUE TITLE
Goldschmiede falscher Anzeigename bei Kleinen Diamanten

### ISSUE THREAD

**Issue by miischaa** [mexyn/statev_v2_issues#951]
**Character Name** 
 
Heinrich Iwanow

**Auftrittszeitpunkt (Datum / Uhrzeit)**

03.01.2021 00:35 Uhr

**Beobachtetes Verhalten**

Statt "Kleiner Diamant" wird "littleDiamond" ausgegeben.

**Erwartetes Verhalten**

Sollte "Kleiner Diamant" heißen wie beim Rest auch.

**Schritte um den Fehler nachvollziehen zu können**

Einfach in der Goldschmiede besagte Stücke auf den Screenshots suchen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

1920x1080

**Optional: Video / Bilder des Fehlers**

https://gyazo.com/fe77de1defddfc04258c647ff1ebdd64
https://gyazo.com/608c0c5a798018ebe3cc9808ad734f23

**Comment by DonVitoDiangelo** [comment]
fixed next update
