### ISSUE TITLE
Ticketnummer mehrmals vergeben

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#952]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.01 11:00

**Beobachtetes Verhalten**
Es kommt immer wieder vor, dass Tickets nicht nachgeschaut werden können, da die vergebene Ticketnummer zuvor bereits schon einmal vergeben wurde, und somit das neuere Ticket nicht mehr angeschaut werden kann

**Erwartetes Verhalten**
Jede Nummer für ein Ticket sollte nur einmal vergeben werden.

**Schritte um den Fehler nachvollziehen zu können**
siehe Video

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

https://www.youtube.com/watch?v=aHEbQUYHHOw

**Comment by its4l3x** [comment]
Ist gefixed und ab dem nächsten Update, können Ticketnummern nicht mehr doppelt vergeben werden.
