### ISSUE TITLE
Mesa Bild im StateV Net

### ISSUE THREAD

**Issue by RomusLapisimus** [mexyn/statev_v2_issues#953]
Character Name
Romus Lapisimus

Auftrittszeitpunkt (Datum / Uhrzeit)
-

Beobachtetes Verhalten
Kein Bild im StateV Net.

Erwartetes Verhalten
-

Schritte um den Fehler nachvollziehen zu können
-

Monitorauflösung (nur wenn Falsche Darstellung in der UI)

Optional: Video / Bilder des Fehlers

![Mesa Foto für State-Net](https://user-images.githubusercontent.com/75159759/103477482-a65ae880-4dbf-11eb-9daf-e67c37e931da.GIF)

**Comment by its4l3x** [comment]
Habe ich hinzugefügt. Nächstes Update ist das Bild dann drinnen.
