### ISSUE TITLE
Garagen marker fehlt. Wohnhaus / Zaun entfernen?

### ISSUE THREAD

**Issue by rubbaduck-twitch** [mexyn/statev_v2_issues#954]
Hi,
das gekaufte Haus verfügt über eine Garage in der Einfahrt, Jedoch fehlt der Marker/Funktion.

Der Zaun um das Haus ist etwas "Einengend". Es gibt keine Texturfehler oder dergleichen wenn man ihn entfernt, da er im Onlinemodus nicht vorhanden ist (siehe Bilder). Wenn ihr mir den entfernt würde ich das feiern.

Danke
LG

Char/Besitzer:
Raymond_Brooks

Objektname:
Westmirror Drive 15

![Garage](https://user-images.githubusercontent.com/75338532/103478620-3d2ba300-4dc8-11eb-93c2-4b34ea57cc80.jpg)
![Zaun](https://user-images.githubusercontent.com/75338532/103478621-3e5cd000-4dc8-11eb-872e-ddcd6bc843f4.jpg)
![ZaunRev1](https://user-images.githubusercontent.com/75338532/103478622-3e5cd000-4dc8-11eb-8dab-4dd8a9875a9a.png)
![ZaunRev2](https://user-images.githubusercontent.com/75338532/103478625-40269380-4dc8-11eb-9275-4412bc5acd6a.png)
![ZaunRev3](https://user-images.githubusercontent.com/75338532/103478628-41f05700-4dc8-11eb-9663-0c945d405c15.png)
![ZaunRev4](https://user-images.githubusercontent.com/75338532/103478630-43ba1a80-4dc8-11eb-87ea-314f79563bc0.png)

**Comment by DrGrizzlY17** [comment]
Garage next Update

Zaun bleibt... dieser ist nicht von uns sondern Standard von GTA
