### ISSUE TITLE
Ausparken von Towtrucks nicht möglich

### ISSUE THREAD

**Issue by ZacCooperr** [mexyn/statev_v2_issues#956]
**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.01.2020 15:45

**Beobachtetes Verhalten**
Vorhandene Flatbeds wurden vom Support wieder in die ursprünglichen Towtrucks zurückgetauscht.
Ausparken der Towtrucks von der Garage nicht möglich, da folgende Meldung erscheint:
Du hast versucht ein Fahrzeug auszuparken, welches entfernt wurde. Melde dich bitte im Support.

**Erwartetes Verhalten**
Die Towtrucks wieder aus der Garage ausparken zukönnen.

**Schritte um den Fehler nachvollziehen zu können**
Vorhandene Towtrucks in einer Garage haben und diese ausparken wollen.

**Optional: Video / Bilder des Fehlers**
![Towtrucks_ausparken](https://user-images.githubusercontent.com/74767269/103481442-5db12880-4ddb-11eb-9533-ed2a9df7d4b3.png)

**Comment by its4l3x** [comment]
Ist bereits gefixed mit dem nächsnte Update
