### ISSUE TITLE
Mehrere Rostige Kannen im Inv während auffüllen

### ISSUE THREAD

**Issue by ProgrammingFox** [mexyn/statev_v2_issues#957]
**Character Name**
Daniel Fox

**Auftrittszeitpunkt (Datum / Uhrzeit)**
03.01.2020 - 20:53 Uhr

**Beobachtetes Verhalten**
Wenn man eine Kanne füllt während man mehrere Kannen im Inventar hat, verschwinden die anderen und man hat nur eine volle Kanne.

**Erwartetes Verhalten**
Man hat bei 3 rostigen Kannen danach 1 volle Kanne und 2 leere Kannen.

**Schritte um den Fehler nachvollziehen zu können**
Mehrere Rostige Kannen im Inventar haben und diese am Wasser benutzen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by tastydev** [comment]
fixed näschtes update
