### ISSUE TITLE
Western Motorcycle Company Sovereign ständig defekt!!!

### ISSUE THREAD

**Issue by ConnorBaextor** [mexyn/statev_v2_issues#958]
Connor_Baextor

**Auftrittszeitpunkt (Datum / Uhrzeit)**
mehrere Tage,letztes mal Samstag, ‎2. ‎Januar ‎2021, ‏‎16:43:57

**Beobachtetes Verhalten**
Beim Absteigen von einem anderen Motorrad gegen die Sovereign gekommen.Gleich defekt(gelbe Leuchte an).Nach einparken in die öffentliche Garage Paleto Bay komplett defekt(rote Leuchte).Gleiches nach abstellen des Motorrades(jemand läuft vorbei,gelbe Leuchte an und qualmender Motor).Das kommt nach jeder Ausfahrt...

**Erwartetes Verhalten**
Bitte mal überprüfen ob das Damage Verhalten des Motorrades korrekt ist.War vor dem großen Update nicht so.

**Schritte um den Fehler nachvollziehen zu können**
Gegen das Motorrad lehnen oder gehen.Und danach einparken.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by DonVitoDiangelo** [comment]
Bitte nach dem nächsten Update erneut prüfen.
