### ISSUE TITLE
Nase bugt durch Maskierungen durch

### ISSUE THREAD

**Issue by D3nni58719** [mexyn/statev_v2_issues#959]
**Andrej William**

**Auftrittszeitpunkt (Datum / Uhrzeit)**
 Seid umstieg auf altV sollte aber warten da es dazu schon ein Patch gab.

**Beobachtetes Verhalten**
 Beim anziehen der Maskierung schaut die Nase raus.

**Erwartetes Verhalten**
 Nase unter der Maskierung :D

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://pic.statev.de/image/bandana.Y44Am
https://pic.statev.de/image/ski-maske.Y4B5I

**Comment by DrGrizzlY17** [comment]
#564
