### ISSUE TITLE
Aktenkoffer nicht sichtbar

### ISSUE THREAD

**Issue by Kerrders** [mexyn/statev_v2_issues#96]
**Character Name**
Kevin_Crimson

**Zeitpunkt (Datum / Uhrzeit)**
26.08.2020 21:27 Uhr

**Beobachtetes Verhalten**
Aktenkoffer ist nicht sichtbar nachdem er angezogen wurde

**Erwartetes Verhalten**
Aktenkoffer in der Hand für die crimsische Doppeltasche

**Comment by tastydev** [comment]
@DonVitoDiangelo Muss als Waffe entfernt werden und als Objekt definiert werden

**Comment by Kerrders** [comment]
> 
> 
> @DonVitoDiangelo Muss als Waffe entfernt werden und als Objekt (Usableitem) definiert werden

Dat Ding war die Tage noch ein Objekt meine ich, aber ist jetzt wieder eine Waffe

**Comment by its4l3x** [comment]
War immer schon eine Waffe @Kerrders
