### ISSUE TITLE
Übersetzung Motor

### ISSUE THREAD

**Issue by mK33y** [mexyn/statev_v2_issues#960]
Dieses Umbenennen:

`   "engine_cavalcade2_122ps":"Albany Cavalcade Motor / 122 PS",
   "engine_cavalcade2_127ps":"Albany Cavalcade Motor / 127 PS",
   "engine_cavalcade2_133ps":"Albany Cavalcade Motor / 133 PS",
   "engine_cavalcade2_137ps":"Albany Cavalcade Motor / 137 PS",`

in 

`   "engine_cavalcade2_122ps":"Albany Cavalcade 2nd Gen Motor / 122 PS",
   "engine_cavalcade2_127ps":"Albany Cavalcade 2nd Gen Motor / 127 PS",
   "engine_cavalcade2_133ps":"Albany Cavalcade 2nd Gen Motor / 133 PS",
   "engine_cavalcade2_137ps":"Albany Cavalcade 2nd Gen Motor / 137 PS",`

Wird im Import angezeigt alle 8 Motoren als nur Albany Cavalcade Motor, ist kein Unterschied zu erkennen also welchen Motor man ersteigert.

**Comment by DonVitoDiangelo** [comment]
Umbrüche checken @MarcelMuerto
