### ISSUE TITLE
Tuning / Lackierung Vorschau

### ISSUE THREAD

**Issue by ShauniKT** [mexyn/statev_v2_issues#961]
**Character Name**

Shauni Teller

**Auftrittszeitpunkt (Datum / Uhrzeit)**

04.01.2021 - Ist allerdings wohl schon länger so laut Mitarbeiteraussagen

**Beobachtetes Verhalten**

Damals konnte man, wenn man am Auto die Tuningvorschau geöffnet hatte am selben Auto gleichzeitig auch die Lackvorschau öffnen. Dies war RP technisch gut, da man zB. Lack und Folien miteinander besser im voraus kombinieren und ansehen konnte.
Nun allerdings kann man am selben Auto nur noch eins öffnen. 
Was mich daran stört:
Der Kunde kann nun nicht mehr seine Lackierung mit der Folie abstimmen. Entweder, man sucht eine Folie aus und Lackiert danach oder eben andersrum. Problem ist nur, wenn das eine nicht mit dem anderen harmoniert, muss der Kunde theoretisch mehrfach bezahlen, um am ende zufrieden zu sein (macht keine Sau verständlicherweise). Es schränkt uns das RP einfach ein.
Wir zb. passen die Farben des Autos des Öfteren mit RGB Code an die Folie an, finden es andererseits aber auch fail erst die Folie zu kleben und danach den Lack aufzutragen (evtl. nehme ich das da zu erst, aber naja). 

**Erwartetes Verhalten**

Dass wenigstens die Vorschau von beidem einsehbar und benutzbar ist. Es geht nicht darum, Lackieren und tunen gleichzeitig zu können. Es kann ja gerne, wenn man versucht zu lackieren wenn man gerade aktiv tuned, eine Fehlermeldung kommen, dass es schon benutzt wird. Aber die Vorschau sollte wenigstens einsehbar sein.

**Schritte um den Fehler nachvollziehen zu können**

- als Fahrer im Auto sitzen und auf tun/rep Point fahren
- Mechaniker nimmt tuning/rep tablet in die hand
- Fahrer fährt zum Lackierpoint
- anderer Mechaniker nimmt Lackiertablet in die Hand
- ->  nicht möglich, weil Fehlermeldung, dass es bereits in Benutzung sei

**Comment by DonVitoDiangelo** [comment]
Wird leider nicht kommen.  Erst lackieren, dann folieren. sry
