### ISSUE TITLE
Cop Unmarked Mustang hat Lightbars auf dem Dach

### ISSUE THREAD

**Issue by 3xcu** [mexyn/statev_v2_issues#962]
Der Unmarked Mustang kann seine Funktion als UNMARKED Wagen nicht mehr erfüllen, kann nicht mehr im Verkehr als Ziviler Mustang untertauchen und ist somit in seiner Funktion nicht zu gebrauchen. Dies liegt daran, dass auf dem Dach große, leuchtende Lightbars sind.

**Comment by DonVitoDiangelo** [comment]
Aktuell ist das Tuning hier dem Anschein nach fehlerhaft. Das müssen wir uns genauer angucken.

**Comment by DonVitoDiangelo** [comment]
Wird nicht weiter verfolgt. Der Stand bleibt jetzt wie er ist.
