### ISSUE TITLE
Statenet fehlende Fahrzeugbilder...

### ISSUE THREAD

**Issue by Statev-Bonsai** [mexyn/statev_v2_issues#963]
Siehe Bilder ;)
![outlaw](https://user-images.githubusercontent.com/70241137/103638741-9ec94a00-4f4d-11eb-9773-1de425f72336.jpg)

![tieflader kraken](https://user-images.githubusercontent.com/70241137/103638763-a4269480-4f4d-11eb-8a8a-5ce3e989a3ce.jpg)

![manchez](https://user-images.githubusercontent.com/70241137/103638771-a688ee80-4f4d-11eb-90f4-fb733bb930c0.jpg)

**Comment by ProgrammingFox** [comment]
Da mir gerade langweilig ist, hab ich mal Bilder dafür rausgesucht:
Outlaw:
![grafik](https://user-images.githubusercontent.com/48456305/103640360-22843600-4f50-11eb-8bfc-fa96c628fa7b.png)

Tieflader:
![grafik](https://user-images.githubusercontent.com/48456305/103640372-29ab4400-4f50-11eb-9e4d-998406bd03c7.png)

Kraken:
![grafik](https://user-images.githubusercontent.com/48456305/103640379-3039bb80-4f50-11eb-94c5-f7ba88c77c5b.png)

Manchez:
![grafik](https://user-images.githubusercontent.com/48456305/103640394-37f96000-4f50-11eb-8eeb-fb63eaa03de1.png)




@Devs : Darf man eigentlich auch neue Bilder für breits vorhandene Fahrzeuge vorschlagen? Da die aktuellen teilweise nicht sehr hochauflösend sind.
