### ISSUE TITLE
"Tanne in Stein" schwebt

### ISSUE THREAD

**Issue by ProgrammingFox** [mexyn/statev_v2_issues#965]
**Character Name**
Daniel Fox

**Auftrittszeitpunkt (Datum / Uhrzeit)**
05.01.2020 - 13:22

**Beobachtetes Verhalten**
"Tanne in Stein" schwebt in der Luft

**Erwartetes Verhalten**
Dass diese nicht sichtbar schwebt.

**Schritte um den Fehler nachvollziehen zu können**
"Tanne in Stein" platzieren.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![grafik](https://user-images.githubusercontent.com/48456305/103645907-0933b780-4f59-11eb-8dcc-fd1ab4a39a5f.png)

**Comment by DonVitoDiangelo** [comment]
Standard Hitbox von GTA, werden wir nicht weiter beeinflussen
