### ISSUE TITLE
Darstellungsweise Überweisungsgebühren

### ISSUE THREAD

**Issue by TheOutburst** [mexyn/statev_v2_issues#966]
**Character Name** Erwin Dulach

**Auftrittszeitpunkt (Datum / Uhrzeit)** 3.1 15:32

**Beobachtetes Verhalten** Überweisungssumme und Gebühren werden Buchhalterisch falsch dargestellt

**Erwartetes Verhalten** Es müsste eine Aufdröselung der Gesamtsumme (Überweisungsbetrag + Gebühren) passieren, leider wird nur in Gesamtsumme und darin enthaltene Gebühren unterschieden, was die auseinanerrechung unnötig verkompliziert.
Ich würde mir eine genauere Aufdröselung in Gesamtsumme, Überweisungsbetrag, Gebühren wünschen

**Schritte um den Fehler nachvollziehen zu können**

Überweisung tätigen -> Im StateNET Überweisungsdetails anschauen

**Optional: Video / Bilder des Fehlers**

https://prnt.sc/wgu0co
Bei dem Beispiel war der Überweisungsbetrag 2.003$ was man aber nicht auf einem Blick erkennt.

**Comment by M4rvinLP** [comment]
War soweit ich weiß bis vor ein paar Tagen auch noch so.

**Comment by MarcelMuerto** [comment]
Das beschriebene Verhalten wurde angepasst und ist im nächsten Update verfügbar. ✅
