### ISSUE TITLE
Bekomme als Inhaber Gehaltscheck´s

### ISSUE THREAD

**Issue by DrColgate** [mexyn/statev_v2_issues#968]
**Character Name**
Anton Mueller

**Auftrittszeitpunkt (Datum / Uhrzeit)**

erster check am 29.12.2020 21:47
**Beobachtetes Verhalten**

bekomme jede stunde gehaltschecks von meinem lager. wenn ich versuche mich auszustempeln, wird mir gesagt das ich inhaber bin und nicht on duty gehen kann. hat eventuell etwas mit der umschreibung zu tun? laut sahk wurde die umschreibung auf mich am 30.12 durchgeführt. firmenhash: terminal6

bei meinen anderen firmen habe ich das nicht.
**Erwartetes Verhalten**

das ich außer dienst gehen kann
**Schritte um den Fehler nachvollziehen zu können**

sehr gute frage. vor dem 29.12 war das nicht. 
**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Ich brauche bitte den Hash deines Lagers.

**Comment by DrColgate** [comment]
habe ich mit hineingeschrieben. terminal6
hatte gestern gesehen das ich noch als mitarbeiter eingetragen war. habe mich selbst aus der mitarbeiter liste gelöscht. seit dem kommt nichts mehr. ich trage mich jetzt wieder als mitarbeiter ein, um zu schauen ob ich dann wieder gehaltschecks bekomme.

**Comment by DrColgate** [comment]
Update: es kommen keine gehaltschecks mehr

**Comment by its4l3x** [comment]
Danke.

Jop, du warst nämlich noch als Mitarbeiter eingeschrieben, deshalb hattest du auch Gehalt bekommen.

Wir lassen das Feature so oder so noch an, da vllt auch Firmenchefs ihr Geld stündlich bezahlt haben möchten.

Closed
