### ISSUE TITLE
Animationsbug im MD

### ISSUE THREAD

**Issue by Ordnael1044** [mexyn/statev_v2_issues#97]
**Character Name**
Leandro Strelizia

**Zeitpunkt (Datum / Uhrzeit)**
26.08.2020  22:55 Uhr

**Beobachtetes Verhalten**
beim Liegen Tablet Rausholen

**Erwartetes Verhalten**
Man sollte Theorhetisch nicht das Tablet rausholen können wenn man in Behandlung ist.

**Schritte um den Fehler nachvollziehen zu können**
1. Werd bewusstlos 2. vom MDler aufs KH-Bett gelegt um behandelt zu werden 3. Tablet rausholen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

![MD Tablet](https://user-images.githubusercontent.com/70153799/91356406-e8f82d00-e7ef-11ea-9bc7-d61643dff4ac.png)

**Comment by its4l3x** [comment]
Fixed, next update
