### ISSUE TITLE
Mehrgeschossigen Gebäuden / glitch through floors

### ISSUE THREAD

**Issue by PrimroseBloom** [mexyn/statev_v2_issues#970]
**Character Name**
Primrose_Bloom

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Ende November bis jetzt

**Beobachtetes Verhalten**
Leute die oben im Lifeinvadergebäude stehen oder sitzen "rutschen" für andere ins Erdgeschoss. Wenn man dann nach oben geht sieht man die Person auch nicht im 1. Geschoss. Erst wenn die Person eine Animation ausführt. 

**Erwartetes Verhalten**
Die Leuten sollten da stehen wo sie sich hingestellt haben.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
Das hier z.B. die Person stand im 1. Geschoss
https://cdn.discordapp.com/attachments/684073477279580220/796065484658442280/unknown.png

**Comment by DonVitoDiangelo** [comment]
Tritt das Problem noch auf?

**Comment by JannikDatsch** [comment]
@DonVitoDiangelo Ja, auch das tritt weiterhin auf, zumindest im MRPD
