### ISSUE TITLE
Fehlende Fahrzeugbilder Statenet

### ISSUE THREAD

**Issue by ShauniKT** [mexyn/statev_v2_issues#971]
**Character Name**

Shauni Teller

**Auftrittszeitpunkt (Datum / Uhrzeit)**

Schon immer

**Optional: Video / Bilder des Fehlers**

https://prnt.sc/wgwqgc

**Bilderideen:**

Ocelot Locust

https://static.wikia.nocookie.net/gtawiki/images/8/8c/Locust-GTAO-front.png/revision/latest/scale-to-width-down/1000?cb=20190723230519

Karin Sultan Classic

https://static.wikia.nocookie.net/gtawiki/images/9/9a/SultanClassic-GTAO-FrontQuarter.png/revision/latest/scale-to-width-down/1000?cb=20191214174312

Bravado Banshee (Racing)

https://wiki.rage.mp/images/thumb/9/9b/Banshee2.png/800px-Banshee2.png

**Comment by callmerusty** [comment]
https://wiki.statev.de/index.php?title=ETR1_(Racing) fehlt auch

**Comment by DrGrizzlY17** [comment]
hash: locust
![image](https://user-images.githubusercontent.com/70150988/103915174-290add00-510b-11eb-9d12-5c7c0f824274.png)

hash: sultan2
![image](https://user-images.githubusercontent.com/70150988/103916646-f95cd480-510c-11eb-91bd-c716a141db53.png)

hash: banshee2
![image](https://user-images.githubusercontent.com/70150988/103916833-3032ea80-510d-11eb-90d2-1571a21bb591.png)

hash: sheava
![image](https://user-images.githubusercontent.com/70150988/103917103-7f791b00-510d-11eb-97db-439129230cb0.png)
