### ISSUE TITLE
Pounder Kofferraum

### ISSUE THREAD

**Issue by Auralein** [mexyn/statev_v2_issues#972]
Clara Young

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Immer ~

**Beobachtetes Verhalten**
Kofferraum kann immer vom Führerhaus aus in Rucksack oder Hosentaschen be/entladen werden

**Erwartetes Verhalten**
Das es nicht geht sondern man am Kofferraum stehen muss um diesen zu Be- oder Entladen

**Schritte um den Fehler nachvollziehen zu können**
In Pounder einsteigen und dann Kofferraum öffnen -> beladen/entladen in Rucksack

**Comment by its4l3x** [comment]
So gewollt, da diese Fahrzeuge (Meistens LKWS, Boote, etc..) einen großen Radius benötigen haben wir uns entschieden diese auch via Sitz im Fahrzeug bedienbar machen zu lassen.

daher close
