### ISSUE TITLE
Fehlendes Bild Nordwälder Schinken!

### ISSUE THREAD

**Issue by MrFluffig** [mexyn/statev_v2_issues#976]
Beim Nordwälder Schinken fehlt überall das Bild!

Macht man aus Schweinebauch und Kunststoffgranulat in der Metzgerei.

**Comment by DonVitoDiangelo** [comment]
next update fixed

**Comment by MrFluffig** [comment]
Wurde beim letzten update vor 3 stunden NICHT gefixed.

**Comment by MrFluffig** [comment]
@DonVitoDiangelo @its4l3x 
Im Lager wird das Bild vom Schinken nicht angezeigt
