### ISSUE TITLE
Verladepunkt versetzen an Metzgerei

### ISSUE THREAD

**Issue by MrFluffig** [mexyn/statev_v2_issues#977]
**Michael Dooley**

Ich bitte um versetzung des Verladepunktes an meiner FIrma
Metzgerei König
Popular Street 50
PLZ: 6016 rechts neben dem Mission Row PD

Anbei ein Bild mit dem jetzigen und dem gewünschten verladepunkt:
![Punktversetzung Metzgerei Verladung](https://user-images.githubusercontent.com/75510436/103770865-00a9b280-5027-11eb-892a-c33cf5e4fcb6.png)

**Comment by DrGrizzlY17** [comment]
Frage... Wieso?

**Comment by MrFluffig** [comment]
Damit der punkt weiter hinten sitzt. ist besser zum rangieren und man muss nicht so weit laufen. von der hk wurde ja gesagt das das kein problem wäre =).
ansonsten wollte ich noch fragen ob es für euch möglich wäre das man neben dem auflieger der auf dem gelände steht, den hubwagen und die paletten mit papp und holzboxen entfernen kann? diese gegenstände sind beweglich und collision ist nicht das problem, die geht dann mit weg.
daamit man da ordentlich parken kann weil die eine box steht halt mitten im weg und ich muss die jedes mal wegdsrücken damit ich mit dem pounder da parken kann

**Comment by DrGrizzlY17** [comment]
Beides abgelehnt. 
Verladepunkt ändert nichts am rangieren und wegen 1m den Punkt zu versetzen ändert nichts an der Kommunikation.
Die Objekte stören keinesfalls. Fürs Parken hast du da so unendlich viel Platz
