### ISSUE TITLE
TS: Beim joinen auf Server manchmal nicht in Voice geschoben 

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#978]
**Character Name**
Jannik_Datsh

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Öfters seit V2 

**Beobachtetes Verhalten**
Beim joinen auf den Server wird man manchmal nicht in V2 Voice geschoben, sondern muss das manuell per F5 machen

**Erwartetes Verhalten**
Man sollte beim joinen automatisch verschoben werden, wie in V1 eig. zuverlässig.

**Comment by Kaycee91** [comment]
Passiert mir auch öfter vor allem wenn ich einen Game Crash hatte
