### ISSUE TITLE
Versetzen des Verladepunktes an meinem Lager

### ISSUE THREAD

**Issue by MrFluffig** [mexyn/statev_v2_issues#979]
Michael Dooley

Ich bitte um versetzung des Verladepunktes an meiner FIrma
HK-K114 | Umschlaglager König
Buccaneer Way 8
Terminal 8
PLZ: 3705 Unten rechts am Containerhafen

Gewünschte Position: so, dass man mit einem Pounder, oder einem Sattelauflieger bis an die Rampe Heranfahren kann zum be und entladen.

Anbei ein Bild mit dem jetzigen und dem gewünschten verladepunkt:
![Verladepunkt lager](https://user-images.githubusercontent.com/75510436/103772708-3ef4a100-502a-11eb-9e35-1e9e323e1270.png)

**Comment by DrGrizzlY17** [comment]
Abgelehnt...

Die Gefahr dass das Fahrzeug stehen bleibt und man ins Interior geht und dann wieder raus, besteht die zu hohe Chance dass das Fahrzeug flipped

**Comment by MrFluffig** [comment]
ja danbn kann man den punkt ein stück weiter nach vorne setzen so dass dann zwischen lkw und rampe ein wenig luft ist und nicht wie jetzt 30 meter. die lkws sollen auch nicht da stehen bleiben sondern nur be und entladen werden und dann direkt wierder fahren, das betreten des interiörs ist nicht vorgesehen
