### ISSUE TITLE
Fehlendes Item Maracuja

### ISSUE THREAD

**Issue by Asmier** [mexyn/statev_v2_issues#980]
Asmier_Umid

**Beobachtetes Verhalten**
Aktuell bekommt man auf keinem Feld das Produkt "Maracuja"
Dieses braucht man aber für die Dose Sprunk Exotic.

**Erwartetes Verhalten**
Auf einem Feld die Maracuja finden

**Schritte um den Fehler nachvollziehen zu können**
Felder abfarmen

**Comment by DonVitoDiangelo** [comment]
Korrekt, kommt zu einem späteren Zeitpunkt.  :)
