### ISSUE TITLE
"Sim-Karte null" bei verpassten Anrufen

### ISSUE THREAD

**Issue by ProgrammingFox** [mexyn/statev_v2_issues#981]
**Character Name**
Daniel Fox

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.01.2021 - 15:18 Uhr

**Beobachtetes Verhalten**
Wenn ich nicht auf der 1822-900 bin und es ruft dort jemand an, kriege ich die Meldung "Die Simkarte null wurde angerufen von 1822-XXXXXXXX"

**Erwartetes Verhalten**
Es sollte dastehen "Die Simkarte 1822-900 wurde angerufen von 1822-XXXXXXXX"

**Schritte um den Fehler nachvollziehen zu können**
1822-900 einlegen, auf anderer Simkarte sein und jemand anrufen lassen.

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
![grafik](https://user-images.githubusercontent.com/48456305/103778510-a0207280-5032-11eb-8d57-d253b4d9495e.png)

**Comment by its4l3x** [comment]
Ist bereits gestern schon aufgefallen und bei dem Update auch schon gefixed bei neuen SIM-Karten die erstellt werden.

Einfach die SIM-Karte umbenennen und speichern, dann ist das Problem auch schon gelöst.

Hatte gestern das bei neuen SIM-Karten auch so eingestellt, das diese Automatisch erstmal als Description, die Telefonnummer erhalten bis ihr z.B. dieser SIM eine manuelle Beschreibung zuweißt.
