### ISSUE TITLE
Lifeinvader Badge und Items werden nicht oder falsch angezeigt !

### ISSUE THREAD

**Issue by Arnaldo-Milano** [mexyn/statev_v2_issues#982]
Arnaldo_Bloom

**Beobachtetes Verhalten**
Items werden nicht/oder anders angezeigt.

**Erwartetes Verhalten**
Items werden richtig angezeigt.

**Schritte um den Fehler nachvollziehen zu können**
Ist bis jetzt nur bei mir aufgefallen !

**Optional: Video / Bilder des Fehlers**
----------------------------------------------
Lifeinvader Badge (nicht vorhanden)

https://cdn.discordapp.com/attachments/684073477279580220/796386116093345802/unknown.png
https://cdn.discordapp.com/attachments/684073477279580220/796386144442777631/unknown.png

https://cdn.discordapp.com/attachments/684073477279580220/796386196905394226/unknown.png
https://cdn.discordapp.com/attachments/684073477279580220/796386340559650846/unknown.png

----------------------------------------------

Grüner Rucksack (wird nicht angezeigt)

https://cdn.discordapp.com/attachments/684073477279580220/796386718542331914/unknown.png
https://cdn.discordapp.com/attachments/684073477279580220/796386791946453012/unknown.png

----------------------------------------------

Blauer Rucksack (wird als Handtasche angezeigt)

https://cdn.discordapp.com/attachments/684073477279580220/796386862586658816/unknown.png
https://cdn.discordapp.com/attachments/684073477279580220/796386946871853066/unknown.png

----------------------------------------------

Roter Rucksack (wird nicht angezeigt)

https://cdn.discordapp.com/attachments/684073477279580220/796387051612143636/unknown.png
https://cdn.discordapp.com/attachments/684073477279580220/796387104275300362/unknown.png

----------------------------------------------

Gelber Bauarbeiterhelm (wird anders angezeigt)

https://cdn.discordapp.com/attachments/684073477279580220/796388912745676800/unknown.png
https://cdn.discordapp.com/attachments/684073477279580220/796388958614585374/unknown.png

----------------------------------------------

Roter Bauarbeiterhelm  (wird anders angezeigt)

https://cdn.discordapp.com/attachments/684073477279580220/796389144476647464/unknown.png
https://cdn.discordapp.com/attachments/684073477279580220/796389150718427146/unknown.png

**Comment by Enemyaa** [comment]
HI @Arnaldo-Milano 

kann ich leider nicht so bestätigen:

https://prnt.sc/wijv13
weder als Frau

https://prnt.sc/wijymh
noch als Mann


Bist du bei allen Fällen "on duty" unterwegs?

**Comment by Arnaldo-Milano** [comment]
Nicht im Dienst !
https://cdn.discordapp.com/attachments/684073477279580220/797174172865921064/unknown.png

https://cdn.discordapp.com/attachments/684073477279580220/797174228578861066/unknown.png

**Comment by DonVitoDiangelo** [comment]
Problem noch vorhanden? bei allen Skins? Auch wenn du deine eigene Kleidung mal ausziehst?

**Comment by PrimroseBloom** [comment]
Ja es ist immer noch so. Kein Badge zusehen, er hat immer Sticker auf den Klamotten, ihm werden bei anderen Personen Tattoos angezeigt die die Person nicht hat.

**Comment by Arnaldo-Milano** [comment]
Das Problem gibt es immer noch.  Sollte ich vieleicht mal statev neu installieren ?

**Comment by Arnaldo-Milano** [comment]
@DonVitoDiangelo 
Hab den Statev installer neu ausgeführt. Problem besteht noch !

**Comment by Arnaldo-Milano** [comment]
@DonVitoDiangelo nach GTA neuinstallation geht alles wieder !
