### ISSUE TITLE
Y-Menü Animation wird nach Schließen von Tablet abgebrochen

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#983]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.01.20 16:40

**Beobachtetes Verhalten**
Sitzanimation (über y-menü) wird nach schließen von Tablet abgebrochen, nach schließen von Handy jedoch nicht
(jede y-Menü animation)

**Erwartetes Verhalten**
Die Animation sollte auch nach Schließen vom Tablet weiterhin ausgeführt werden.

**Schritte um den Fehler nachvollziehen zu können**
Über y-Menü sitzen --> tablet öffnen --> tablet schließen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**
https://youtu.be/kW5tLeyIg_U

**Comment by its4l3x** [comment]
In Addition zu deinem vorherigen Post, genau deshalb wurde die Funk Animation unterbrochen. Wir überlegen ob wir das Tablet auch wieder hinzufügen.

Lässt sich leider nicht lösen, weil beides sich überschneidet GTA Seitig her
