### ISSUE TITLE
Funkanimation wird bei aktiver y-Menü Animation nicht ausgeführt

### ISSUE THREAD

**Issue by JannikDatsch** [mexyn/statev_v2_issues#984]
**Character Name**
Jannik_Datsch

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.01.2020 16:45

**Beobachtetes Verhalten**
Bei aktiver y-menü Animation wird keine Funkanimation ausgeführt. Gefunkt werden kann jedoch.

**Erwartetes Verhalten**
Es sollte, auch aufgrund des Abuse-potentiales, eine Animation ausgeführt werden.

**Schritte um den Fehler nachvollziehen zu können**
Animation über y-Menü --> Funken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by its4l3x** [comment]
Ist richtig und notwendig, da sonst das Sitzen unterbrochen wird. :/

**Comment by JannikDatsch** [comment]
@its4l3x ok, aber aufgrund des Abuse Potentials kritisch, da du so alles was du sprichst dann dann funken kannst, und so "stillen Alarm" auslösen kannst.

**Comment by its4l3x** [comment]
Verständlich. Wir schauen mal. 

Aber was da gilt => einfach Reporten
