### ISSUE TITLE
Fahrrad nicht über X-Menü Schiebbar

### ISSUE THREAD

**Issue by CatherineGallagher** [mexyn/statev_v2_issues#985]
**Character Name**
Catherine Gallagher

**Auftrittszeitpunkt (Datum / Uhrzeit)**
06.01.2021 // 18:45 Uhr

**Beobachtetes Verhalten**
Fahrrad nicht schiebbar, Meldung erhalten "Motor muss ausgeschalten sein" 
(Fahrrad hat kein Motor daher kann man nichts ausschalten)

**Erwartetes Verhalten**
Fahrrad sollte schiebbar sein

**Schritte um den Fehler nachvollziehen zu können**
X Menü öffnen und versuchen das Fahrrad zu schieben

**Comment by its4l3x** [comment]
Fixed, next Update
