### ISSUE TITLE
Umhängetasche nicht sichtbar bei Helldogs Kutte

### ISSUE THREAD

**Issue by Koree7** [mexyn/statev_v2_issues#989]
**Character Name**
Brooks Miller

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit AltV

**Beobachtetes Verhalten**
Umhängetasche anziehen, nicht sichtbar am Rücken

**Erwartetes Verhalten**
Umhängetasche anziehen, sichtbar am Rücken

**Schritte um den Fehler nachvollziehen zu können**
Tasche in Taschenslot ziehen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**
1920x1080

**Optional: Video / Bilder des Fehlers**
https://prnt.sc/wif846

**Comment by Enemyaa** [comment]
[878](https://github.com/mexyn/statev_v2_issues/issues)
