### ISSUE TITLE
Beim Outfit anziehen werden Cap und Brille nicht ausgezogen

### ISSUE THREAD

**Issue by DrGrizzlY17** [mexyn/statev_v2_issues#99]
Dan_Lee

**Zeitpunkt (Datum / Uhrzeit)**
27.08.2020 00:52

**Beobachtetes Verhalten**
Wenn ich das Outfit Kletterausrüstung anziehe, werden die Slots Brille und Cap nicht geleert

**Erwartetes Verhalten**
Slots sollten geleert werden, da sie visible überlegt werden

**Schritte um den Fehler nachvollziehen zu können**
Brille und Cap anziehen
Outfit Kletterausrüstung anziehen

**Optional: Video / Bilder des Fehlers**
https://gyazo.com/8f5949021d1ed5906ca68514369b5e8c

**Comment by r3sist3nt** [comment]
Ich weiß nicht ob wir das beheben sollten.
Das Problem ist, dass die Kollision die du da beschreibst durch die Props in den Configs verursacht werden. Wenn du aktuell ein Outfit anziehst, dann werden alle Kleidungsstücke ausgezogen, die sich in clothes -config mit dem outfit überschneiden. Die hier betroffenen Stellen sind aber **props**. Problem hierbei ist, dass ich 10 Props mit dem Selben Component-Type an meinem Character haben kann, ohne das diese sich visuell überschneiden. Dafür sind Props ja auch da - damit man additiv Props an einen Character anheften kann.
Ich kann jetzt natürlich einbauen, dass auch alle Kleidungsstücke die sich mit de Outfit in der Props-Config überschneiden ausgezogen werden, damit werden wir aber auch eine Menge false-positives haben (z.B. oufit hat ne Snap-Back, du hast Ohrringe ausgerüstet -> Beim ausrüstet des Outfits würden die Ohrringe verschwinden.)

**Comment by r3sist3nt** [comment]
Wir setzten das nicht um, da es sich hierbei um props handelt.
