### ISSUE TITLE
Kofferraum Bravado Buffalo S verkleinert seit V2

### ISSUE THREAD

**Issue by CaleighRhodes** [mexyn/statev_v2_issues#990]
**Character Name**
Caleigh_Rhodes

**Auftrittszeitpunkt (Datum / Uhrzeit)**
immer

**Beobachtetes Verhalten**
Seit dem Update auf V2 ist der Kofferraum vom Buffalo S nur noch 40 Kilo groß, statt - wie früher und wie im Wiki auch angegeben - 70 Kilo. In Anbetracht dessen, dass vergleichbare Fahrzeuge (Bauart Sedan/Limousine) größere Kofferraumvolumen haben und die 40 Kilo für einen Sedan wirklich wenig sind, wäre eine Anpassung nur logisch. Im Vergleich dazu ist das Kofferraumvolumen bei Cabrios wie dem Z4 mit 40 Kilo zu groß, da hier ja noch das Dach verstaut werden muss.

Vergleichbare Fahrzeuge und deren Kofferraumvolumina:
Camaro SS -> 65 Kilo (in meinem Bestand)
Coil Raiden -> 60 Kilo (in meinem Bestand)
Mustang -> 70 Kilo (laut Wiki)
RS7 -> 60 Kilo (laut Wiki)
M5 -> 70 Kilo (laut Wiki und Aussage eines Freundes)

**Erwartetes Verhalten**
Kofferraum mindestens 60 Kilo Ladevolumen

**Schritte um den Fehler nachvollziehen zu können**
Wiki -> https://wiki.statev.de/index.php?title=Buffalo_S
Buffalo S -> ![buffaloS](https://user-images.githubusercontent.com/74977218/103934651-9fb4d400-5125-11eb-870a-de4c61219ef8.PNG)

**Comment by DonVitoDiangelo** [comment]
Der Wagen hatte schon immer 40k. Wird etwas angepasst.

**Comment by CaleighRhodes** [comment]
Sorry Vito, aber nein, er hatte immer 70 Kilo. Als ich ihn nach V2 Release ausgeparkt hab, waren 65 Kilo von meinem Zeug drin.
Sonst hätte ich es doch gar nicht gemeldet :)

**Comment by DonVitoDiangelo** [comment]
mh, also der alte code sagt auch 40, bin etwas verwundert. Aber egal, wird ja angehoben :)
