### ISSUE TITLE
Brillenpreis lässt sich nicht auf 0$ stellen - Juwelier

### ISSUE THREAD

**Issue by miischaa** [mexyn/statev_v2_issues#992]
**Character Name**
 
Heinrich Iwanow

**Auftrittszeitpunkt (Datum / Uhrzeit)**

23:36 Uhr 07.01.2021, eigentlich über längere Zeit, ist jedoch unabhängig von Uhrzeit oder Datum

**Beobachtetes Verhalten**

Ich möchte den Preis der Brille auf 0$ stellen. Jedoch immer wenn ich den Preis von 0$ speichere, eine andere Seite im StateNET aufrufe und wieder auf das Ladeninventar gehe, ist die Uhr wieder auf 250$. Dabei ist es egal ob ich es über den Browser oder IC mache. Bei den anderen 200+ Items im Ladeninventar passiert das ganze nicht.

**Erwartetes Verhalten**

Eigentlich sollte der Preis bei 0$ gespeichert werden, sodass die Brille erstmal nicht in der Theke beim Kauf angezeigt wird, bis ein anderes Preis eingestellt ist. So taucht sie aber auch in der Theke für 250$ auf.

**Schritte um den Fehler nachvollziehen zu können**

Wie oben beschrieben

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

1920x1080

**Optional: Video / Bilder des Fehlers**

https://gyazo.com/eae8c9d66d6d05f2abc61c5ef618a98c

**Comment by its4l3x** [comment]
Hi Mischa,

Seit V2 ist das so, dass auch Items angezeigt werden, welche bei 0$ liegen.

Wir hatten dies geändert, da das eine nicht gewollte Änderung zu Zeiten von RageMP war. Fällt auf eine falsche Abfrage zurück.

Werde das Ticket wieder schließen.

Alex

**Comment by its4l3x** [comment]
Hi Mischa,

Sorry für die zuvor falsch geschriebene Nachricht. Habe nicht gründlich geschaut ;)

Habe das im STATENET angepasst und man kann nach dem nächsten Update auch die Preise dort auf $0 setzen.

Alex
