### ISSUE TITLE
Juwelier - Schmuck geht beim Entpacken kaputt?

### ISSUE THREAD

**Issue by miischaa** [mexyn/statev_v2_issues#993]
**Character Name**

Heinrich Iwanow

**Auftrittszeitpunkt (Datum / Uhrzeit)**

07.01.2021, 02:42 Uhr
08.01.2021, 01:03 Uhr
08.01.2021, 01:10 Uhr

**Beobachtetes Verhalten**

Schmuckstücke gehen beim entpacken kaputt

**Erwartetes Verhalten**

Naja ich kann verstehen, dass bei der Produktion der Materialien und der Schmuckstücke selbst, etwas kaputt gehen kann, aber beim entpacken, ein bereits fertiges Schmuckstück kaputt gehen zu lassen? 
Vielleicht ist das ein Bug, vielleicht aber auch gewollt, falls gewollt finde ich das fraglich, vielleicht lässt man sich das nochmal durch den Kopf gehen?

**Schritte um den Fehler nachvollziehen zu können**

Ein produziertes Schmuckstück im Juwelier entpacken

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

1920x1080

**Optional: Video / Bilder des Fehlers**

https://gyazo.com/68ef860a96e2f7fa42a88c02607762c2
https://gyazo.com/3be82d09d380c62ee84754dd758d9ea0

**Comment by CaleighRhodes** [comment]
Das passiert auch im 24/7 beim Entpacken, bspw. bei Karabinerhaken. Das ist "normal".

**Comment by miischaa** [comment]
Gibt es da eine Grenze? Bei den Items in den Screenshots ist das ganze noch gut verkraftbar, gibt aber auch deutlich teurere Sachen.

**Comment by Statev-Bonsai** [comment]
Das war schon immer so das was kaputt geht, egal ob 24/7 oder Juwelier..
Bei mir ging auch so eine teure SN Anhänger Kette für über 20k beim entpacken kaputt, Ray Ban Brillen etc können auch kaputt gehen..

Denke das wird auch ans Skill System gekoppelt sein, wenn du ausgelernt bist geht sicherlich nix mehr kaputt...

**Comment by miischaa** [comment]
Das entpacken ist aber wenn ich das richtig sehe nicht an ein Skillsystem gekoppelt, sondern nur die Produktion

**Comment by Statev-Bonsai** [comment]
Dann wäre es durchaus Sinnvoll das entpacken beim Juwelier mit in den Wissenschaftler Skill einzufügen (der ist ja auch für die Goldschmiede).

**Comment by DonVitoDiangelo** [comment]
Das ist alles berücksichtigt. Auch das entpacken wird gelevelt. 


> Denke das wird auch ans Skill System gekoppelt sein, wenn du ausgelernt bist geht sicherlich nix mehr kaputt...
> Sollte jedenfalls so sein, das wäre Fair :)

;)
