### ISSUE TITLE
Schmuck - Falscher Anzeigename

### ISSUE THREAD

**Issue by miischaa** [mexyn/statev_v2_issues#994]
**Character Name**

Heinrich Iwanow

**Auftrittszeitpunkt (Datum / Uhrzeit)**

08.01.2021 12:15 Uhr

**Beobachtetes Verhalten**

Eine eckige Klammer zu viel am Anfang -> [[M]...

**Erwartetes Verhalten**

[M]...

**Schritte um den Fehler nachvollziehen zu können**

[M][Bracelet] Gelbe Neon Armbänder (L) produzieren und das Item anschauen

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

1920x1080

**Optional: Video / Bilder des Fehlers**

https://gyazo.com/e054a24569647d61f5c337ef7ff04481

**Comment by Enemyaa** [comment]
Hi @miischaa habs ausgebessert. Danke für die Info!
