### ISSUE TITLE
Towtruck Large sehr wenig Motor Leistung

### ISSUE THREAD

**Issue by Dean-Gallagher** [mexyn/statev_v2_issues#995]
**Character Name**
Dean Gallagher

**Beobachtetes Verhalten**
Tow Truck Large hat extrem wenig Motorleistung. Beim Abschleppen von LKWs schwächelt der größte Tow Truck Motor (125PS) extrem. Einen MTL Öltanker kann man von Glück reden wenn man über 15 kmh kommt. Auch Pounder und Phantoms sind nicht das gelbe vom Ei. 

Man kommt mit einen Pounder hinten dran nichtmal den MT Vinewood Drive von der Zentralmine aus hoch. So extrem wenig Leistung hat der Motor

**Erwartetes Verhalten**
Wenigstens das man 80 kmh kommt und bei dem öltanker auf mehr als 15kmh

**Schritte um den Fehler nachvollziehen zu können**
Tow Truck Large (125PS) nehmen, versuchen LKW abzuschleppen. 

Nachtrag: wir haben ebend festgestellt das der Small Towtruck die selben Leistungswerte wie der große hat. Darin scheint auch der fehler zu liegen.

**Comment by thumbsucker** [comment]
Die Leistung von kleinen Towtruck scheint auch niedriger zu sein (ist beim big aber definitiv schlimmer). Des weiteren hat er wohl noch das Tankvolumen des Flatbeds.

**Comment by Dean-Gallagher** [comment]
Nee das Tankvolumen haben sie nicht von Flatbeds, wenn du die Falts vorher vollgemacht hattest ist der Tank nur überfüllt, sobald du den Tank etwas unter maximal gefahren hast ist es fixed.
