### ISSUE TITLE
Export mit Large Achse abgeben funktioniert nicht

### ISSUE THREAD

**Issue by DylanDuncan** [mexyn/statev_v2_issues#996]
**Character Name**
Dylan Duncan

**Auftrittszeitpunkt (Datum / Uhrzeit)**
Seit dem Update als die Range angepasst wurde um Fahrzeuge auf dem Export Entladepunkt zu erfassen

**Beobachtetes Verhalten**
Egal wo die Achse abgestellt wird und wo die Zugmaschine abgestellt wird, man bekommt eine Fehlermeldung (siehe Screenshots) und man kann die Aufträge sowohl beim Ressourcenexport als auch beim Auftragsexport nicht abgeben

![2021-01-08 (1)](https://user-images.githubusercontent.com/75174723/104018588-519de000-51ba-11eb-983d-127aaf47c4b6.png)

![2021-01-08 (2)_LI](https://user-images.githubusercontent.com/75174723/104018595-59f61b00-51ba-11eb-8eea-0b324bf53bf9.jpg)

![2021-01-08 (3)](https://user-images.githubusercontent.com/75174723/104018827-c3762980-51ba-11eb-8824-d3c765f91651.png)

**Erwartetes Verhalten**
Wie vor dem Update - auf den Exportpunkt, Kofferraum öffnen, Export abgeben

**Schritte um den Fehler nachvollziehen zu können**
Versuchen mit Large Achse Export abzugeben

**Comment by tastydev** [comment]
Die Achse muss aufgeschlossen sein

**Comment by DylanDuncan** [comment]
Und ja, die Achse war offen und bis oben hin voll mit Packung Kakaopulver hab vergessen ein Screenshot zu machen

**Comment by tastydev** [comment]
Ich habe gerade nachgetestet und es funktioniert alles.

**Comment by tastydev** [comment]
Hat doch bei ihm funktioniert, daher close
