### ISSUE TITLE
Schlüssel nach Notfall MD nicht mehr im Inventar

### ISSUE THREAD

**Issue by Tiltplank** [mexyn/statev_v2_issues#997]
Nikolas Wick

06.01.2020 Abends 

Hatte für 2 verschiede Reblas Schlüssel im normalen Inventar diese sind beim spawnen am Notfall MD weg gewesen.

Die Schlüssel sind noch im Inventar.

**Schritte um den Fehler nachvollziehen zu können**

**Monitorauflösung (nur wenn Falsche Darstellung in der UI)**

**Optional: Video / Bilder des Fehlers**

**Comment by Statev-Bonsai** [comment]
Nikolas, das ist vollkommen normal seid V2.. Jeder Schlüssel der nicht am Schlüsselbund ist wird vom MD abgenommen, das ist auch so gewünscht. Daher kein Bug ;)

**Comment by its4l3x** [comment]
Korrekt. Bonsai hat es schon gesagt.

Daher Closed
